var s = [
  {
    "manager_Name": "783( 1 )",
    "Teams": "(Wes) Brownie Points( Kumar Isaac )",
    "SXL": "USA",
    "Latp": "7",
    "Player_1": "Raya SUN",
    "Player_11": "\u0160e\u0161ko 0",
    "Player_10": "Haaland LIV",
    "Player_12": "Pope BRE",
    "Player_13": "Yoro 0",
    "Player_14": "Thiago NEW",
    "Player_7": "Rice SUN",
    "Player_2": "Van de",
    "Player_5": "Gu\u00E9hi BHA",
    "Player_6": "Mbeumo 6",
    "Player_3": "Gabriel SUN",
    "Player_4": "Cash BOU",
    "Player_8": "Caicedo WOL",
    "Player_9": "Semenyo AVL",
    "Player_15": "Palmer WOL"
  },
  {
    "manager_Name": "780( 2 )",
    "Teams": "ZayceCFC( Zay McGuire )",
    "SXL": "USA",
    "Latp": "0",
    "Player_1": "Pope BRE",
    "Player_11": "Haaland LIV",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Petrovi\u0107 AVL",
    "Player_13": "Virgil MCI",
    "Player_14": "Ndiaye FUL",
    "Player_7": "Caicedo WOL",
    "Player_2": "Cucurella WOL",
    "Player_5": "Gabriel SUN",
    "Player_6": "Rice SUN",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "J.Timber SUN",
    "Player_8": "Semenyo AVL",
    "Player_9": "Woltemade BRE",
    "Player_15": "Kudus 0"
  },
  {
    "manager_Name": "770( 3 )",
    "Teams": "Calafiorication( Aryan Kumar )",
    "SXL": "BHR",
    "Latp": "0",
    "Player_1": "Raya SUN",
    "Player_11": "Mateta BHA",
    "Player_10": "Haaland LIV",
    "Player_12": "Sels LEE",
    "Player_13": "Virgil MCI",
    "Player_14": "Onana BOU",
    "Player_7": "Enzo WOL",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "Tarkowski FUL",
    "Player_6": "Semenyo AVL",
    "Player_3": "Mu\u00F1oz BHA",
    "Player_4": "Gabriel SUN",
    "Player_8": "Rice SUN",
    "Player_9": "Caicedo WOL",
    "Player_15": "Ekitik\u00E9 MCI"
  },
  {
    "manager_Name": "768( 4 )",
    "Teams": "Shiver Me Timber( Mike Tomlin )",
    "SXL": "ENG",
    "Latp": "2",
    "Player_1": "Raya SUN",
    "Player_11": "Haaland LIV",
    "Player_10": "Mateta BHA",
    "Player_12": "Sels LEE",
    "Player_13": "Senesi AVL",
    "Player_14": "Damsgaard NEW",
    "Player_7": "Rice SUN",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "Gabriel SUN",
    "Player_6": "B.Fernandes 2",
    "Player_3": "Murillo LEE",
    "Player_4": "Mu\u00F1oz BHA",
    "Player_8": "Bruno G.",
    "Player_9": "Semenyo AVL",
    "Player_15": "Welbeck CRY"
  },
  {
    "manager_Name": "766( 5 )",
    "Teams": "Ballo fc( Ade Bayo )",
    "SXL": "NGA",
    "Latp": "1",
    "Player_1": "Martinez BOU",
    "Player_11": "Haaland LIV",
    "Player_10": "Welbeck CRY",
    "Player_12": "Petrovi\u0107 AVL",
    "Player_13": "Senesi AVL",
    "Player_14": "Tonali BRE",
    "Player_7": "Rice SUN",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "Van de",
    "Player_6": "Szoboszlai MCI",
    "Player_3": "Saliba SUN",
    "Player_4": "Gabriel SUN",
    "Player_8": "Caicedo WOL",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Kudus 0"
  },
  {
    "manager_Name": "765( 6 )",
    "Teams": "saka nuts( lucas clarke )",
    "SXL": "NZL",
    "Latp": "7",
    "Player_1": "Raya SUN",
    "Player_11": "Mateta BHA",
    "Player_10": "Haaland LIV",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Est\u00E8ve WHU",
    "Player_14": "Reinildo ARS",
    "Player_7": "Minteh CRY",
    "Player_2": "Lacroix BHA",
    "Player_5": "Semenyo AVL",
    "Player_6": "B.Fernandes 1",
    "Player_3": "Senesi AVL",
    "Player_4": "Gabriel SUN",
    "Player_8": "Mbeumo 6",
    "Player_9": "Saka SUN",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "764( 7 )",
    "Teams": "Manchester City( Javier Rufo )",
    "SXL": "ESP",
    "Latp": "1",
    "Player_1": "Donnarumma LIV",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland LIV",
    "Player_12": "Vicario 1",
    "Player_13": "Gu\u00E9hi BHA",
    "Player_14": "Palmer WOL",
    "Player_7": "Caicedo WOL",
    "Player_2": "Saliba SUN",
    "Player_5": "J.Timber SUN",
    "Player_6": "Yeremy BHA",
    "Player_3": "Gabriel SUN",
    "Player_4": "Pedro Porro",
    "Player_8": "Cherki LIV",
    "Player_9": "Semenyo AVL",
    "Player_15": "Nmecha NFO"
  },
  {
    "manager_Name": "763( 8 )",
    "Teams": "teddy\u0027s xv( C McQuade )",
    "SXL": "ENG",
    "Latp": "1",
    "Player_1": "Raya SUN",
    "Player_11": "Mateta BHA",
    "Player_10": "Haaland LIV",
    "Player_12": "Verbruggen CRY",
    "Player_13": "Lacroix BHA",
    "Player_14": "Bowen BUR",
    "Player_7": "Semenyo AVL",
    "Player_2": "Mu\u00F1oz BHA",
    "Player_5": "Gabriel SUN",
    "Player_6": "Bruno G.",
    "Player_3": "Burn BRE",
    "Player_4": "Van de",
    "Player_8": "Kudus 0",
    "Player_9": "Eze SUN",
    "Player_15": "Enzo WOL"
  },
  {
    "manager_Name": "763( 9 )",
    "Teams": "lambo( Thomas Lamb )",
    "SXL": "ENG",
    "Latp": "2",
    "Player_1": "Raya SUN",
    "Player_11": "Woltemade BRE",
    "Player_10": "Haaland LIV",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Thiago NEW",
    "Player_14": "Konsa BOU",
    "Player_7": "Rice SUN",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "M.Salah MCI",
    "Player_6": "Casemiro 1",
    "Player_3": "Van de",
    "Player_4": "Gabriel SUN",
    "Player_8": "Caicedo WOL",
    "Player_9": "Ndiaye FUL",
    "Player_15": "Trippier BRE"
  },
  {
    "manager_Name": "762( 10 )",
    "Teams": "Ode08fc( Enoch Lariba )",
    "SXL": "GHA",
    "Latp": "1",
    "Player_1": "Raya SUN",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland LIV",
    "Player_12": "Sels LEE",
    "Player_13": "Walker WHU",
    "Player_14": "Gibbs-White LEE",
    "Player_7": "Rice SUN",
    "Player_2": "Van de",
    "Player_5": "Frimpong MCI",
    "Player_6": "Semenyo AVL",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "Gabriel SUN",
    "Player_8": "Kudus 0",
    "Player_9": "Caicedo WOL",
    "Player_15": "Bowen BUR"
  },
  {
    "manager_Name": "762( 10 )",
    "Teams": "Saka spuds!( Jack Hall )",
    "SXL": "ENG",
    "Latp": "1",
    "Player_1": "Pope BRE",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland LIV",
    "Player_12": "Raya SUN",
    "Player_13": "Cash BOU",
    "Player_14": "Gravenberch MCI",
    "Player_7": "Bruno G.",
    "Player_2": "Livramento BRE",
    "Player_5": "Cucurella WOL",
    "Player_6": "B.Fernandes 1",
    "Player_3": "Gabriel SUN",
    "Player_4": "Gu\u00E9hi BHA",
    "Player_8": "Rice SUN",
    "Player_9": "Caicedo WOL",
    "Player_15": "Watkins BOU"
  },
  {
    "manager_Name": "762( 12 )",
    "Teams": "Angeball( Oscar Pernehed )",
    "SXL": "SWE",
    "Latp": "7",
    "Player_1": "Pickford FUL",
    "Player_11": "Haaland LIV",
    "Player_10": "Thiago NEW",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Semenyo AVL",
    "Player_14": "Senesi AVL",
    "Player_7": "L.Paquet\u00E1 BUR",
    "Player_2": "J.Timber SUN",
    "Player_5": "Tarkowski FUL",
    "Player_6": "B.Fernandes 1",
    "Player_3": "Gabriel SUN",
    "Player_4": "Mu\u00F1oz BHA",
    "Player_8": "Mbeumo 6",
    "Player_9": "Enzo WOL",
    "Player_15": "Barnes WHU"
  },
  {
    "manager_Name": "762( 13 )",
    "Teams": "The Honest Trundlers( Ian Foster )",
    "SXL": "GBR",
    "Latp": "1",
    "Player_1": "Raya SUN",
    "Player_11": "Ekitik\u00E9 MCI",
    "Player_10": "Haaland LIV",
    "Player_12": "Pope BRE",
    "Player_13": "Van Hecke",
    "Player_14": "Thiago NEW",
    "Player_7": "B.Fernandes 1",
    "Player_2": "Gabriel SUN",
    "Player_5": "Rice SUN",
    "Player_6": "Semenyo AVL",
    "Player_3": "Mu\u00F1oz BHA",
    "Player_4": "Thiaw BRE",
    "Player_8": "Tonali BRE",
    "Player_9": "Szoboszlai MCI",
    "Player_15": "Pedro Porro"
  },
  {
    "manager_Name": "760( 14 )",
    "Teams": "g7412877( George McNicholas )",
    "SXL": "ENG",
    "Latp": "6",
    "Player_1": "Raya SUN",
    "Player_11": "Woltemade BRE",
    "Player_10": "Haaland LIV",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Gu\u00E9hi BHA",
    "Player_14": "Bates FUL",
    "Player_7": "Semenyo AVL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Mbeumo 6",
    "Player_6": "Gibbs-White LEE",
    "Player_3": "J.Timber SUN",
    "Player_4": "Cucurella WOL",
    "Player_8": "Caicedo WOL",
    "Player_9": "Mateta BHA",
    "Player_15": "R.Williams MCI"
  },
  {
    "manager_Name": "760( 14 )",
    "Teams": "\uFFFD( Vincent Ngula )",
    "SXL": "KEN",
    "Latp": "7",
    "Player_1": "Donnarumma LIV",
    "Player_11": "Haaland LIV",
    "Player_10": "Mbeumo 6",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Welbeck CRY",
    "Player_14": "Gy\u00F6keres SUN",
    "Player_7": "Cherki LIV",
    "Player_2": "J.Timber SUN",
    "Player_5": "Gu\u00E9hi BHA",
    "Player_6": "Caicedo WOL",
    "Player_3": "Gabriel SUN",
    "Player_4": "Van Hecke",
    "Player_8": "Bruno G.",
    "Player_9": "Cunha 1",
    "Player_15": "Burn BRE"
  },
  {
    "manager_Name": "760( 16 )",
    "Teams": "cabdixaafidmaxamed( Cabdi Jeeriya )",
    "SXL": "SOM",
    "Latp": "6",
    "Player_1": "Raya SUN",
    "Player_11": "Haaland LIV",
    "Player_10": "Thiago NEW",
    "Player_12": "Vicario 1",
    "Player_13": "Senesi AVL",
    "Player_14": "Foden LIV",
    "Player_7": "Caicedo WOL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Mbeumo 6",
    "Player_6": "Rice SUN",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "Virgil MCI",
    "Player_8": "Semenyo AVL",
    "Player_9": "Woltemade BRE",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "759( 17 )",
    "Teams": "TheYellowFlash( Brent Paulse )",
    "SXL": "ZAF",
    "Latp": "6",
    "Player_1": "S\u00E1nchez WOL",
    "Player_11": "Welbeck CRY",
    "Player_10": "Haaland LIV",
    "Player_12": "Pope BRE",
    "Player_13": "Burn BRE",
    "Player_14": "Sarr BHA",
    "Player_7": "Mbeumo 6",
    "Player_2": "Gabriel SUN",
    "Player_5": "Ndiaye FUL",
    "Player_6": "Semenyo AVL",
    "Player_3": "Mitchell BHA",
    "Player_4": "Cash BOU",
    "Player_8": "Eze SUN",
    "Player_9": "Mateta BHA",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "758( 18 )",
    "Teams": "MI fc( Kagujje Thanos )",
    "SXL": "UGA",
    "Latp": "0",
    "Player_1": "Raya SUN",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Mateta BHA",
    "Player_12": "Jos\u00E9 S\u00E1",
    "Player_13": "Van de",
    "Player_14": "Xhaka ARS",
    "Player_7": "Eze SUN",
    "Player_2": "Mitchell BHA",
    "Player_5": "Sarr BHA",
    "Player_6": "Semenyo AVL",
    "Player_3": "Romero 0",
    "Player_4": "Gabriel SUN",
    "Player_8": "Kudus 0",
    "Player_9": "Haaland LIV",
    "Player_15": "Chalobah WOL"
  },
  {
    "manager_Name": "758( 19 )",
    "Teams": "Jurgenmeister( Simon Herbert )",
    "SXL": "ENG",
    "Latp": "6",
    "Player_1": "Raya SUN",
    "Player_11": "Mateta BHA",
    "Player_10": "Haaland LIV",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Senesi AVL",
    "Player_14": "Kudus 0",
    "Player_7": "Semenyo AVL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Ndiaye FUL",
    "Player_6": "Caicedo WOL",
    "Player_3": "Mu\u00F1oz BHA",
    "Player_4": "Cucurella WOL",
    "Player_8": "Mbeumo 6",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Hoever CHE"
  },
  {
    "manager_Name": "757( 20 )",
    "Teams": "Saliba the solution( Jacob Davis )",
    "SXL": "ENG",
    "Latp": "1",
    "Player_1": "Raya SUN",
    "Player_11": "Mateta BHA",
    "Player_10": "Haaland LIV",
    "Player_12": "Donnarumma LIV",
    "Player_13": "Cucurella WOL",
    "Player_14": "Edozie CHE",
    "Player_7": "Rice SUN",
    "Player_2": "Gabriel SUN",
    "Player_5": "Gu\u00E9hi BHA",
    "Player_6": "Foden LIV",
    "Player_3": "Burn BRE",
    "Player_4": "Virgil MCI",
    "Player_8": "Semenyo AVL",
    "Player_9": "Richarlison 1",
    "Player_15": "J.Murphy BRE"
  },
  {
    "manager_Name": "757( 21 )",
    "Teams": "Up on the Roefs( Matthew Coggin )",
    "SXL": "ENG",
    "Latp": "1",
    "Player_1": "Roefs ARS",
    "Player_11": "Haaland LIV",
    "Player_10": "Mateta BHA",
    "Player_12": "Vicario 1",
    "Player_13": "Tarkowski FUL",
    "Player_14": "Semenyo AVL",
    "Player_7": "Eze SUN",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "Van de",
    "Player_6": "Xhaka ARS",
    "Player_3": "Gabriel SUN",
    "Player_4": "Cucurella WOL",
    "Player_8": "Rice SUN",
    "Player_9": "Caicedo WOL",
    "Player_15": "Woltemade BRE"
  },
  {
    "manager_Name": "757( 22 )",
    "Teams": "gnik fc( Gnik Paul )",
    "SXL": "KEN",
    "Latp": "8",
    "Player_1": "Raya SUN",
    "Player_11": "\u0160e\u0161ko 1",
    "Player_10": "Haaland LIV",
    "Player_12": "Pickford FUL",
    "Player_13": "Bassey EVE",
    "Player_14": "Baleba CRY",
    "Player_7": "Semenyo AVL",
    "Player_2": "J.Timber SUN",
    "Player_5": "Cucurella WOL",
    "Player_6": "Mbeumo 6",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "Gabriel SUN",
    "Player_8": "Caicedo WOL",
    "Player_9": "B.Fernandes 1",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "757( 23 )",
    "Teams": "Croydon Eagles( Luke Townsend )",
    "SXL": "ENG",
    "Latp": "8",
    "Player_1": "Pope BRE",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Mateta BHA",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Van de",
    "Player_14": "Mukiele ARS",
    "Player_7": "Enzo WOL",
    "Player_2": "Mu\u00F1oz BHA",
    "Player_5": "Mbeumo 8",
    "Player_6": "Semenyo AVL",
    "Player_3": "Senesi AVL",
    "Player_4": "Gabriel SUN",
    "Player_8": "Ndiaye FUL",
    "Player_9": "Haaland LIV",
    "Player_15": "Reijnders LIV"
  },
  {
    "manager_Name": "757( 24 )",
    "Teams": "FatKRATOS( Ryan Madigan )",
    "SXL": "ENG",
    "Latp": "10",
    "Player_1": "Raya SUN",
    "Player_11": "Mateta BHA",
    "Player_10": "Haaland LIV",
    "Player_12": "Hermansen BUR",
    "Player_13": "Gu\u00E9hi BHA",
    "Player_14": "Gakpo MCI",
    "Player_7": "Summerville BUR",
    "Player_2": "Van de",
    "Player_5": "Sarr BHA",
    "Player_6": "Semenyo AVL",
    "Player_3": "Calafiori SUN",
    "Player_4": "Gabriel SUN",
    "Player_8": "Mbeumo 8",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Digne BOU"
  },
  {
    "manager_Name": "756( 25 )",
    "Teams": "Pain in Dias( Dougie Shukie )",
    "SXL": "ENG",
    "Latp": "10",
    "Player_1": "Donnarumma LIV",
    "Player_11": "Mateta BHA",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Raya SUN",
    "Player_13": "Wieffer CRY",
    "Player_14": "Van de",
    "Player_7": "Caicedo WOL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Mbeumo 8",
    "Player_6": "Semenyo AVL",
    "Player_3": "Saliba SUN",
    "Player_4": "Gu\u00E9hi BHA",
    "Player_8": "Ndiaye FUL",
    "Player_9": "Haaland LIV",
    "Player_15": "Est\u00E8ve WHU"
  },
  {
    "manager_Name": "756( 26 )",
    "Teams": "losksjsns( Alex Simons )",
    "SXL": "ENG",
    "Latp": "0",
    "Player_1": "Pickford FUL",
    "Player_11": "Haaland LIV",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Ramsdale BRE",
    "Player_13": "Grealish FUL",
    "Player_14": "Van de",
    "Player_7": "Semenyo AVL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Enzo WOL",
    "Player_6": "Eze SUN",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "Senesi AVL",
    "Player_8": "Rice SUN",
    "Player_9": "Woltemade BRE",
    "Player_15": "Mu\u00F1oz BHA"
  },
  {
    "manager_Name": "755( 27 )",
    "Teams": "Jonas Fc( Jonas Bernotas )",
    "SXL": "IRL",
    "Latp": "8",
    "Player_1": "Raya SUN",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland LIV",
    "Player_12": "S\u00E1nchez WOL",
    "Player_13": "Pedro Porro",
    "Player_14": "Xhaka ARS",
    "Player_7": "Rice SUN",
    "Player_2": "Gabriel SUN",
    "Player_5": "Gu\u00E9hi BHA",
    "Player_6": "Mbeumo 8",
    "Player_3": "Virgil MCI",
    "Player_4": "Gvardiol LIV",
    "Player_8": "Caicedo WOL",
    "Player_9": "Welbeck CRY",
    "Player_15": "Semenyo AVL"
  },
  {
    "manager_Name": "755( 28 )",
    "Teams": "ThomasTheFrankEngine( Chris Masters )",
    "SXL": "ENG",
    "Latp": "8",
    "Player_1": "Raya SUN",
    "Player_11": "Mateta BHA",
    "Player_10": "Bowen BUR",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Ndiaye FUL",
    "Player_14": "Van de",
    "Player_7": "Mbeumo 8",
    "Player_2": "Mu\u00F1oz BHA",
    "Player_5": "Rice SUN",
    "Player_6": "Semenyo AVL",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "Calafiori SUN",
    "Player_8": "Enzo WOL",
    "Player_9": "Haaland LIV",
    "Player_15": "Spence 2"
  },
  {
    "manager_Name": "754( 29 )",
    "Teams": "Team 26( Andrew Jennings )",
    "SXL": "ENG",
    "Latp": "10",
    "Player_1": "Pope BRE",
    "Player_11": "Haaland LIV",
    "Player_10": "Merino SUN",
    "Player_12": "Verbruggen CRY",
    "Player_13": "Lacroix BHA",
    "Player_14": "Thiago NEW",
    "Player_7": "Semenyo AVL",
    "Player_2": "Mu\u00F1oz BHA",
    "Player_5": "Gabriel SUN",
    "Player_6": "Rice SUN",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "Van de",
    "Player_8": "Caicedo WOL",
    "Player_9": "Mbeumo 8",
    "Player_15": "Woltemade BRE"
  },
  {
    "manager_Name": "752( 30 )",
    "Teams": "Buffelsfontein FC( JEFF ABSALOM )",
    "SXL": "ZAF",
    "Latp": "11",
    "Player_1": "Raya SUN",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland LIV",
    "Player_12": "Henderson BHA",
    "Player_13": "Ballard ARS",
    "Player_14": "Eze SUN",
    "Player_7": "B.Fernandes 3",
    "Player_2": "Pedro Porro",
    "Player_5": "Chalobah WOL",
    "Player_6": "Caicedo WOL",
    "Player_3": "Virgil MCI",
    "Player_4": "Gabriel SUN",
    "Player_8": "Semenyo AVL",
    "Player_9": "Amad 6",
    "Player_15": "Fraser CHE"
  },
  {
    "manager_Name": "752( 31 )",
    "Teams": "Stevens Team( Steven Murphy )",
    "SXL": "IRL",
    "Latp": "10",
    "Player_1": "Raya SUN",
    "Player_11": "Haaland LIV",
    "Player_10": "Mateta BHA",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Virgil MCI",
    "Player_14": "O\u2019Reilly LIV",
    "Player_7": "Kudus 0",
    "Player_2": "Pedro Porro",
    "Player_5": "Eze SUN",
    "Player_6": "Semenyo AVL",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "Gabriel SUN",
    "Player_8": "Mbeumo 8",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "King EVE"
  },
  {
    "manager_Name": "752( 32 )",
    "Teams": "Absolutely Fabregas( Kia Anglin )",
    "SXL": "IRL",
    "Latp": "3",
    "Player_1": "Raya SUN",
    "Player_11": "Woltemade BRE",
    "Player_10": "Haaland LIV",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Van de",
    "Player_14": "Senesi AVL",
    "Player_7": "Gakpo MCI",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "Caicedo WOL",
    "Player_6": "B.Fernandes 3",
    "Player_3": "Gabriel SUN",
    "Player_4": "Ballard ARS",
    "Player_8": "Semenyo AVL",
    "Player_9": "Mateta BHA",
    "Player_15": "Reijnders LIV"
  },
  {
    "manager_Name": "752( 33 )",
    "Teams": "Vamos!!( Gaurav Sareen )",
    "SXL": "IND",
    "Latp": "10",
    "Player_1": "Henderson BHA",
    "Player_11": "Woltemade BRE",
    "Player_10": "Mateta BHA",
    "Player_12": "Vicario 2",
    "Player_13": "Konsa BOU",
    "Player_14": "Reijnders LIV",
    "Player_7": "Semenyo AVL",
    "Player_2": "Van de",
    "Player_5": "Mbeumo 8",
    "Player_6": "Rice SUN",
    "Player_3": "Gabriel SUN",
    "Player_4": "Gu\u00E9hi BHA",
    "Player_8": "Enzo WOL",
    "Player_9": "Haaland LIV",
    "Player_15": "R\u00FAben LIV"
  },
  {
    "manager_Name": "751( 34 )",
    "Teams": "Bigos most hated( Josh Cut )",
    "SXL": "ENG",
    "Latp": "2",
    "Player_1": "Raya SUN",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland LIV",
    "Player_12": "Heaton 0",
    "Player_13": "Van Hecke",
    "Player_14": "A\u00EFt-Nouri LIV",
    "Player_7": "Silcott-Duberry AVL",
    "Player_2": "R\u00FAben LIV",
    "Player_5": "J.Palhinha 2",
    "Player_6": "M.Salah MCI",
    "Player_3": "Gabriel SUN",
    "Player_4": "J.Timber SUN",
    "Player_8": "Caicedo WOL",
    "Player_9": "Semenyo AVL",
    "Player_15": "Obi 0"
  },
  {
    "manager_Name": "751( 35 )",
    "Teams": "Hals XI( Eoghan Hallissey )",
    "SXL": "IRL",
    "Latp": "0",
    "Player_1": "Raya SUN",
    "Player_11": "Welbeck CRY",
    "Player_10": "Mateta BHA",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Mbeumo 8",
    "Player_14": "Wan-Bissaka BUR",
    "Player_7": "Semenyo AVL",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "Sarr BHA",
    "Player_6": "Caicedo WOL",
    "Player_3": "Senesi AVL",
    "Player_4": "Gabriel SUN",
    "Player_8": "Rice SUN",
    "Player_9": "Haaland LIV",
    "Player_15": "R\u00FAben LIV"
  },
  {
    "manager_Name": "751( 35 )",
    "Teams": "Al_Mo7nk( Montadher Mohammed )",
    "SXL": "IRQ",
    "Latp": "0",
    "Player_1": "Pope BRE",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Mateta BHA",
    "Player_12": "Petrovi\u0107 AVL",
    "Player_13": "Gakpo MCI",
    "Player_14": "Semenyo AVL",
    "Player_7": "Sarr BHA",
    "Player_2": "J.Timber SUN",
    "Player_5": "Senesi AVL",
    "Player_6": "Gu\u00E9hi BHA",
    "Player_3": "Gabriel SUN",
    "Player_4": "Calafiori SUN",
    "Player_8": "Caicedo WOL",
    "Player_9": "Haaland LIV",
    "Player_15": "Kudus 0"
  },
  {
    "manager_Name": "751( 37 )",
    "Teams": "N5( Graham Allen )",
    "SXL": "ENG",
    "Latp": "8",
    "Player_1": "Sels LEE",
    "Player_11": "Mateta BHA",
    "Player_10": "Haaland LIV",
    "Player_12": "Darlow NFO",
    "Player_13": "Van de",
    "Player_14": "Welbeck CRY",
    "Player_7": "Minteh CRY",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "Saka SUN",
    "Player_6": "Rice SUN",
    "Player_3": "Gabriel SUN",
    "Player_4": "Cucurella WOL",
    "Player_8": "Mbeumo 8",
    "Player_9": "Semenyo AVL",
    "Player_15": "Reinildo ARS"
  },
  {
    "manager_Name": "751( 38 )",
    "Teams": "simers snipers( omally robin )",
    "SXL": "DMA",
    "Latp": "3",
    "Player_1": "Raya SUN",
    "Player_11": "Haaland LIV",
    "Player_10": "Enzo WOL",
    "Player_12": "Roefs ARS",
    "Player_13": "Van de",
    "Player_14": "Welbeck CRY",
    "Player_7": "Semenyo AVL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Gu\u00E9hi BHA",
    "Player_6": "Szoboszlai MCI",
    "Player_3": "J.Timber SUN",
    "Player_4": "Mitchell BHA",
    "Player_8": "Gakpo MCI",
    "Player_9": "B.Fernandes 3",
    "Player_15": "Calvert-Lewin NFO"
  },
  {
    "manager_Name": "751( 39 )",
    "Teams": "Fifmer( Micha\u0142 Jastrz\u0119bski )",
    "SXL": "POL",
    "Latp": "13",
    "Player_1": "Raya SUN",
    "Player_11": "Haaland LIV",
    "Player_10": "Mateta BHA",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Zubimendi SUN",
    "Player_14": "Virgil MCI",
    "Player_7": "Caicedo WOL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Mu\u00F1oz BHA",
    "Player_6": "B.Fernandes 3",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "Van de",
    "Player_8": "Mbeumo 8",
    "Player_9": "Semenyo AVL",
    "Player_15": "Welbeck CRY"
  },
  {
    "manager_Name": "750( 40 )",
    "Teams": "Change Name( Joshua Butcher )",
    "SXL": "AUS",
    "Latp": "2",
    "Player_1": "Raya SUN",
    "Player_11": "Haaland LIV",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Darlow NFO",
    "Player_13": "Wan-Bissaka BUR",
    "Player_14": "A.Ramsey WHU",
    "Player_7": "Semenyo AVL",
    "Player_2": "Virgil MCI",
    "Player_5": "Van de",
    "Player_6": "M.Salah MCI",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "Gabriel SUN",
    "Player_8": "Iwobi EVE",
    "Player_9": "Rice SUN",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "750( 41 )",
    "Teams": "Change Name( Elijah Cookson )",
    "SXL": "CAN",
    "Latp": "0",
    "Player_1": "Henderson BHA",
    "Player_11": "Mateta BHA",
    "Player_10": "Haaland LIV",
    "Player_12": "Vicario 2",
    "Player_13": "Gvardiol LIV",
    "Player_14": "Cherki LIV",
    "Player_7": "Bruno G.",
    "Player_2": "Cucurella WOL",
    "Player_5": "J.Timber SUN",
    "Player_6": "Caicedo WOL",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "Gabriel SUN",
    "Player_8": "Rice SUN",
    "Player_9": "Semenyo AVL",
    "Player_15": "Woltemade BRE"
  },
  {
    "manager_Name": "750( 42 )",
    "Teams": "Rice Rice Baby( Lewis Young )",
    "SXL": "ENG",
    "Latp": "2",
    "Player_1": "Raya SUN",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland LIV",
    "Player_12": "Kinsky 0",
    "Player_13": "Reijnders LIV",
    "Player_14": "Est\u00E8ve WHU",
    "Player_7": "M.Salah MCI",
    "Player_2": "Gabriel SUN",
    "Player_5": "Gu\u00E9hi BHA",
    "Player_6": "Semenyo AVL",
    "Player_3": "Senesi AVL",
    "Player_4": "Van de",
    "Player_8": "Caicedo WOL",
    "Player_9": "Rice SUN",
    "Player_15": "Kroupi.Jr AVL"
  },
  {
    "manager_Name": "750( 42 )",
    "Teams": "Lallanas in Pyjamas( Catrina Macarthur )",
    "SXL": "ENG",
    "Latp": "7",
    "Player_1": "S\u00E1nchez WOL",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland LIV",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Gakpo MCI",
    "Player_14": "Rodon NFO",
    "Player_7": "Semenyo AVL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Rogers BOU",
    "Player_6": "Ndiaye FUL",
    "Player_3": "Pedro Porro",
    "Player_4": "Van de",
    "Player_8": "B.Fernandes 3",
    "Player_9": "Mateta BHA",
    "Player_15": "Est\u00E8ve WHU"
  },
  {
    "manager_Name": "750( 44 )",
    "Teams": "HavertzYourWay( Joel Rogers )",
    "SXL": "WAL",
    "Latp": "0",
    "Player_1": "Petrovi\u0107 AVL",
    "Player_11": "Mateta BHA",
    "Player_10": "Haaland LIV",
    "Player_12": "Kelleher NEW",
    "Player_13": "Caicedo WOL",
    "Player_14": "Buend\u00EDa BOU",
    "Player_7": "Grealish FUL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Mu\u00F1oz BHA",
    "Player_6": "Semenyo AVL",
    "Player_3": "J.Timber SUN",
    "Player_4": "Gu\u00E9hi BHA",
    "Player_8": "Rice SUN",
    "Player_9": "Woltemade BRE",
    "Player_15": "Branthwaite FUL"
  },
  {
    "manager_Name": "750( 44 )",
    "Teams": "Eyob( Eyob Admasu )",
    "SXL": "ETH",
    "Latp": "8",
    "Player_1": "Raya SUN",
    "Player_11": "Mateta BHA",
    "Player_10": "Haaland LIV",
    "Player_12": "Martinez BOU",
    "Player_13": "Burn BRE",
    "Player_14": "Dunk CRY",
    "Player_7": "Caicedo WOL",
    "Player_2": "J.Timber SUN",
    "Player_5": "Minteh CRY",
    "Player_6": "Neto WOL",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "Gabriel SUN",
    "Player_8": "Mbeumo 8",
    "Player_9": "Ekitik\u00E9 MCI",
    "Player_15": "Kudus 0"
  },
  {
    "manager_Name": "749( 46 )",
    "Teams": "bowen 747( harry dale )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "Raya SUN",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Mateta BHA",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Mbeumo 8",
    "Player_14": "Van Hecke",
    "Player_7": "B.Fernandes 3",
    "Player_2": "Van de",
    "Player_5": "Gu\u00E9hi BHA",
    "Player_6": "Caicedo WOL",
    "Player_3": "Gabriel SUN",
    "Player_4": "J.Timber SUN",
    "Player_8": "Semenyo AVL",
    "Player_9": "Haaland LIV",
    "Player_15": "Baleba CRY"
  },
  {
    "manager_Name": "749( 47 )",
    "Teams": "Expect Toulouse FC( Bailey Armstrong )",
    "SXL": "ENG",
    "Latp": "2",
    "Player_1": "S\u00E1nchez WOL",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland LIV",
    "Player_12": "Donnarumma LIV",
    "Player_13": "Senesi AVL",
    "Player_14": "Reijnders LIV",
    "Player_7": "Enzo WOL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Van de",
    "Player_6": "Rice SUN",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "Mu\u00F1oz BHA",
    "Player_8": "Semenyo AVL",
    "Player_9": "Woltemade BRE",
    "Player_15": "Xhaka ARS"
  },
  {
    "manager_Name": "749( 47 )",
    "Teams": "tongue wagglers( Jack Pascall )",
    "SXL": "ENG",
    "Latp": "10",
    "Player_1": "Raya SUN",
    "Player_11": "Woltemade BRE",
    "Player_10": "Mateta BHA",
    "Player_12": "Pope BRE",
    "Player_13": "Eze SUN",
    "Player_14": "Ndiaye FUL",
    "Player_7": "Semenyo AVL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Burn BRE",
    "Player_6": "Mbeumo 8",
    "Player_3": "Van de",
    "Player_4": "Gu\u00E9hi BHA",
    "Player_8": "Doku LIV",
    "Player_9": "Haaland LIV",
    "Player_15": "Richards BHA"
  },
  {
    "manager_Name": "749( 47 )",
    "Teams": "Left 4 Djed( Oliver Lovegrove )",
    "SXL": "ENG",
    "Latp": "0",
    "Player_1": "Raya SUN",
    "Player_11": "Haaland LIV",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Leno EVE",
    "Player_13": "Mu\u00F1oz BHA",
    "Player_14": "Gakpo MCI",
    "Player_7": "Kudus 0",
    "Player_2": "Cucurella WOL",
    "Player_5": "Gu\u00E9hi BHA",
    "Player_6": "Semenyo AVL",
    "Player_3": "Gabriel SUN",
    "Player_4": "Gvardiol LIV",
    "Player_8": "Rice SUN",
    "Player_9": "Ndiaye FUL",
    "Player_15": "Flemming WHU"
  },
  {
    "manager_Name": "749( 50 )",
    "Teams": "Cancelo culture( Samuel Greathead )",
    "SXL": "NZL",
    "Latp": "0",
    "Player_1": "Roefs ARS",
    "Player_11": "Mateta BHA",
    "Player_10": "Haaland LIV",
    "Player_12": "Raya SUN",
    "Player_13": "Sch\u00E4r BRE",
    "Player_14": "Reijnders LIV",
    "Player_7": "Caicedo WOL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Burn BRE",
    "Player_6": "Kudus 0",
    "Player_3": "Kerkez MCI",
    "Player_4": "Gu\u00E9hi BHA",
    "Player_8": "Eze SUN",
    "Player_9": "Semenyo AVL",
    "Player_15": "Jo\u00E3o Pedro"
  }
];