var s = [
  {
    "manager_Name": "698( 7,511 )",
    "Teams": "cavac215( Ankit Chhetri )",
    "SXL": "IND",
    "Latp": "7",
    "Player_1": "Pope BRE",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland LIV",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Minteh CRY",
    "Player_14": "Calvert-Lewin NFO",
    "Player_7": "Rice SUN",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "Chalobah WOL",
    "Player_6": "Saka SUN",
    "Player_3": "Gabriel SUN",
    "Player_4": "Van de",
    "Player_8": "Semenyo AVL",
    "Player_9": "Mbeumo 6",
    "Player_15": "Est\u00E8ve WHU"
  },
  {
    "manager_Name": "663( 85,777 )",
    "Teams": "False 9( Rohan Rai )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "Pope BRE",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Woltemade BRE",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Gudmundsson NFO",
    "Player_14": "Mukiele ARS",
    "Player_7": "Saka SUN",
    "Player_2": "Senesi AVL",
    "Player_5": "Anthony WHU",
    "Player_6": "Sarr BHA",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "Gabriel SUN",
    "Player_8": "Semenyo AVL",
    "Player_9": "Haaland LIV",
    "Player_15": "Kudus 0"
  },
  {
    "manager_Name": "653( 154,328 )",
    "Teams": "PWS( Z S )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "D\u00FAbravka WHU",
    "Player_11": "Haaland LIV",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Donnarumma LIV",
    "Player_13": "Gakpo MCI",
    "Player_14": "Van de",
    "Player_7": "Caicedo WOL",
    "Player_2": "Senesi AVL",
    "Player_5": "Rice SUN",
    "Player_6": "Semenyo AVL",
    "Player_3": "Gabriel SUN",
    "Player_4": "J.Timber SUN",
    "Player_8": "Grealish FUL",
    "Player_9": "Mateta BHA",
    "Player_15": "Dorgu 1"
  },
  {
    "manager_Name": "633( 414,419 )",
    "Teams": "error404( Duri Tadu )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "Raya SUN",
    "Player_11": "Haaland LIV",
    "Player_10": "Woltemade BRE",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Rodon NFO",
    "Player_14": "Virgil MCI",
    "Player_7": "Semenyo AVL",
    "Player_2": "Richards BHA",
    "Player_5": "Enzo WOL",
    "Player_6": "Saka SUN",
    "Player_3": "Gabriel SUN",
    "Player_4": "Andersen EVE",
    "Player_8": "Ndiaye FUL",
    "Player_9": "Mateta BHA",
    "Player_15": "Stach NFO"
  },
  {
    "manager_Name": "620( 732,107 )",
    "Teams": "RIP-DIOGO.20( pranam rai )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "D\u00FAbravka WHU",
    "Player_11": "Haaland LIV",
    "Player_10": "Woltemade BRE",
    "Player_12": "Vicario 1",
    "Player_13": "\u0160e\u0161ko 0",
    "Player_14": "Gakpo MCI",
    "Player_7": "Semenyo AVL",
    "Player_2": "Mu\u00F1oz BHA",
    "Player_5": "Cucurella WOL",
    "Player_6": "Est\u00E8ve WHU",
    "Player_3": "Gabriel SUN",
    "Player_4": "J.Timber SUN",
    "Player_8": "Mbeumo 6",
    "Player_9": "Malen BOU",
    "Player_15": "Kudus 0"
  },
  {
    "manager_Name": "619( 744,573 )",
    "Teams": "Kung fu Pandoos( Indrajeet Singh )",
    "SXL": "IND",
    "Latp": "8",
    "Player_1": "S\u00E1nchez WOL",
    "Player_11": "Woltemade BRE",
    "Player_10": "Haaland LIV",
    "Player_12": "Kelleher NEW",
    "Player_13": "Gvardiol LIV",
    "Player_14": "Virgil MCI",
    "Player_7": "Semenyo AVL",
    "Player_2": "Pedro Porro",
    "Player_5": "Grealish FUL",
    "Player_6": "Foden LIV",
    "Player_3": "Walker WHU",
    "Player_4": "De Ligt",
    "Player_8": "Mbeumo 6",
    "Player_9": "Bowen BUR",
    "Player_15": "A.Ramsey WHU"
  },
  {
    "manager_Name": "618( 772,880 )",
    "Teams": "abcde FC( Prayash Thapa )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "D\u00FAbravka WHU",
    "Player_11": "Mateta BHA",
    "Player_10": "Haaland LIV",
    "Player_12": "Roefs ARS",
    "Player_13": "James WOL",
    "Player_14": "Senesi AVL",
    "Player_7": "Sarr BHA",
    "Player_2": "J.Timber SUN",
    "Player_5": "Enzo WOL",
    "Player_6": "Minteh CRY",
    "Player_3": "Mu\u00F1oz BHA",
    "Player_4": "Gabriel SUN",
    "Player_8": "Mbeumo 6",
    "Player_9": "Semenyo AVL",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "615( 869,986 )",
    "Teams": "11 n over( Ashish Rai )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "Raya SUN",
    "Player_11": "Welbeck CRY",
    "Player_10": "Haaland LIV",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Gakpo MCI",
    "Player_14": "Rodon NFO",
    "Player_7": "O.Dango NEW",
    "Player_2": "Diouf BUR",
    "Player_5": "Cash BOU",
    "Player_6": "Minteh CRY",
    "Player_3": "Mu\u00F1oz BHA",
    "Player_4": "J.Timber SUN",
    "Player_8": "Saka SUN",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Kudus 0"
  },
  {
    "manager_Name": "614( 893,912 )",
    "Teams": "Top Gooner( VibhutiHang Subba )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "Raya SUN",
    "Player_11": "Bowen BUR",
    "Player_10": "Haaland LIV",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Pedro Porro",
    "Player_14": "Reijnders LIV",
    "Player_7": "Semenyo AVL",
    "Player_2": "Rodon NFO",
    "Player_5": "Mbeumo 6",
    "Player_6": "Eze SUN",
    "Player_3": "Senesi AVL",
    "Player_4": "Lacroix BHA",
    "Player_8": "Saka SUN",
    "Player_9": "Welbeck CRY",
    "Player_15": "Mukiele ARS"
  },
  {
    "manager_Name": "601( 1,371,516 )",
    "Teams": "Blue Brigade( Bhuman Basnet )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "D\u00FAbravka WHU",
    "Player_11": "Haaland LIV",
    "Player_10": "Mateta BHA",
    "Player_12": "Vicario 1",
    "Player_13": "Senesi AVL",
    "Player_14": "Tuanzebe WHU",
    "Player_7": "Sarr BHA",
    "Player_2": "Calafiori SUN",
    "Player_5": "Semenyo AVL",
    "Player_6": "Enzo WOL",
    "Player_3": "Gabriel SUN",
    "Player_4": "Gu\u00E9hi BHA",
    "Player_8": "Mbeumo 6",
    "Player_9": "Kudus 0",
    "Player_15": "Barnes WHU"
  },
  {
    "manager_Name": "601( 1,371,516 )",
    "Teams": "Alpha11( AVIJIT DAS )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "D\u00FAbravka WHU",
    "Player_11": "Mateta BHA",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Vicario 1",
    "Player_13": "Senesi AVL",
    "Player_14": "King EVE",
    "Player_7": "Saka SUN",
    "Player_2": "Lacroix BHA",
    "Player_5": "Enzo WOL",
    "Player_6": "Semenyo AVL",
    "Player_3": "Gabriel SUN",
    "Player_4": "Chalobah WOL",
    "Player_8": "Mbeumo 6",
    "Player_9": "Haaland LIV",
    "Player_15": "Gudmundsson NFO"
  },
  {
    "manager_Name": "601( 1,371,516 )",
    "Teams": "\u0160e\u0161ko and Destroy( Pema Lepcha )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "Sels LEE",
    "Player_11": "Haaland LIV",
    "Player_10": "Bowen BUR",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Wieffer CRY",
    "Player_14": "Walker WHU",
    "Player_7": "Semenyo AVL",
    "Player_2": "James WOL",
    "Player_5": "Rice SUN",
    "Player_6": "Saka SUN",
    "Player_3": "Mu\u00F1oz BHA",
    "Player_4": "Gabriel SUN",
    "Player_8": "L.Paquet\u00E1 BUR",
    "Player_9": "Mateta BHA",
    "Player_15": "Gudmundsson NFO"
  },
  {
    "manager_Name": "594( 1,651,065 )",
    "Teams": "MANCHESTER IS BLUE( PRAYAS BAJGAI )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "Pope BRE",
    "Player_11": "Haaland LIV",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Dewsbury-Hall FUL",
    "Player_14": "Rodon NFO",
    "Player_7": "Semenyo AVL",
    "Player_2": "Andersen EVE",
    "Player_5": "Saka SUN",
    "Player_6": "Enzo WOL",
    "Player_3": "Gabriel SUN",
    "Player_4": "J.Timber SUN",
    "Player_8": "Sarr BHA",
    "Player_9": "Mateta BHA",
    "Player_15": "Senesi AVL"
  },
  {
    "manager_Name": "594( 1,660,749 )",
    "Teams": "F.C. ASSASSINS( Kushal Sahota )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "D\u00FAbravka WHU",
    "Player_11": "Haaland LIV",
    "Player_10": "Welbeck CRY",
    "Player_12": "Roefs ARS",
    "Player_13": "Van de",
    "Player_14": "Est\u00E8ve WHU",
    "Player_7": "Caicedo WOL",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "Sarr BHA",
    "Player_6": "M.Salah MCI",
    "Player_3": "J.Timber SUN",
    "Player_4": "Senesi AVL",
    "Player_8": "Semenyo AVL",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "King EVE"
  },
  {
    "manager_Name": "594( 1,660,749 )",
    "Teams": "ASHLAD FC( Ashim Lama )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "D\u00FAbravka WHU",
    "Player_11": "Haaland LIV",
    "Player_10": "Mateta BHA",
    "Player_12": "Roefs ARS",
    "Player_13": "Van de",
    "Player_14": "Gvardiol LIV",
    "Player_7": "Ndiaye FUL",
    "Player_2": "Senesi AVL",
    "Player_5": "Rice SUN",
    "Player_6": "Caicedo WOL",
    "Player_3": "Gabriel SUN",
    "Player_4": "J.Timber SUN",
    "Player_8": "Semenyo AVL",
    "Player_9": "Sarr BHA",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "590( 1,836,210 )",
    "Teams": "PINE( SATYAM RAI )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "Raya SUN",
    "Player_11": "Haaland LIV",
    "Player_10": "Mateta BHA",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Van de",
    "Player_14": "Marc Guiu",
    "Player_7": "Semenyo AVL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Mbeumo 6",
    "Player_6": "Ndiaye FUL",
    "Player_3": "Senesi AVL",
    "Player_4": "Burn BRE",
    "Player_8": "Saka SUN",
    "Player_9": "Enzo WOL",
    "Player_15": "Mukiele ARS"
  },
  {
    "manager_Name": "587( 2,007,297 )",
    "Teams": "Comet FC( Pranesh Sharma )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "S\u00E1nchez WOL",
    "Player_11": "Haaland LIV",
    "Player_10": "Woltemade BRE",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Senesi AVL",
    "Player_14": "Kudus 0",
    "Player_7": "Ndiaye FUL",
    "Player_2": "Calafiori SUN",
    "Player_5": "Saka SUN",
    "Player_6": "Semenyo AVL",
    "Player_3": "Cash BOU",
    "Player_4": "Andersen EVE",
    "Player_8": "Mbeumo 6",
    "Player_9": "Welbeck CRY",
    "Player_15": "Est\u00E8ve WHU"
  },
  {
    "manager_Name": "580( 2,343,003 )",
    "Teams": "Lu Lu( Nishant Lohagun )",
    "SXL": "IND",
    "Latp": "1",
    "Player_1": "Raya SUN",
    "Player_11": "Woltemade BRE",
    "Player_10": "Haaland LIV",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Marc Guiu",
    "Player_14": "Richards BHA",
    "Player_7": "Semenyo AVL",
    "Player_2": "Andersen EVE",
    "Player_5": "Senesi AVL",
    "Player_6": "B.Fernandes 1",
    "Player_3": "Gabriel SUN",
    "Player_4": "Mu\u00F1oz BHA",
    "Player_8": "Enzo WOL",
    "Player_9": "Saka SUN",
    "Player_15": "Reijnders LIV"
  },
  {
    "manager_Name": "571( 2,791,810 )",
    "Teams": "Fu\u00DFball-Mannschaft( Gaurav Shrestha )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "Raya SUN",
    "Player_11": "Mateta BHA",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Senesi AVL",
    "Player_14": "Stach NFO",
    "Player_7": "Ndiaye FUL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Saka SUN",
    "Player_6": "Semenyo AVL",
    "Player_3": "Andersen EVE",
    "Player_4": "Richards BHA",
    "Player_8": "Minteh CRY",
    "Player_9": "Haaland LIV",
    "Player_15": "Rodon NFO"
  },
  {
    "manager_Name": "566( 3,089,601 )",
    "Teams": "Native United( Monlom Rongong )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "Raya SUN",
    "Player_11": "Haaland LIV",
    "Player_10": "Mateta BHA",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Senesi AVL",
    "Player_14": "Rodon NFO",
    "Player_7": "Ndiaye FUL",
    "Player_2": "Gabriel SUN",
    "Player_5": "Caicedo WOL",
    "Player_6": "Mbeumo 6",
    "Player_3": "J.Timber SUN",
    "Player_4": "Gu\u00E9hi BHA",
    "Player_8": "Semenyo AVL",
    "Player_9": "Woltemade BRE",
    "Player_15": "King EVE"
  },
  {
    "manager_Name": "566( 3,103,146 )",
    "Teams": "G\u00CBNJ\u00CF\u00CF UNITED( Pema Bhutia )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "Raya SUN",
    "Player_11": "Haaland LIV",
    "Player_10": "Mateta BHA",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Anthony WHU",
    "Player_14": "Van de",
    "Player_7": "Semenyo AVL",
    "Player_2": "Senesi AVL",
    "Player_5": "Minteh CRY",
    "Player_6": "Rice SUN",
    "Player_3": "Gabriel SUN",
    "Player_4": "Richards BHA",
    "Player_8": "Mbeumo 6",
    "Player_9": "Woltemade BRE",
    "Player_15": "Alderete ARS"
  },
  {
    "manager_Name": "563( 3,256,176 )",
    "Teams": "Liverpool FC( Sunil Rai )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "S\u00E1nchez WOL",
    "Player_11": "Haaland LIV",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Pope BRE",
    "Player_13": "Virgil MCI",
    "Player_14": "Van de",
    "Player_7": "Anthony WHU",
    "Player_2": "Mu\u00F1oz BHA",
    "Player_5": "Enzo WOL",
    "Player_6": "Semenyo AVL",
    "Player_3": "Gabriel SUN",
    "Player_4": "Gvardiol LIV",
    "Player_8": "Grealish FUL",
    "Player_9": "Woltemade BRE",
    "Player_15": "Tavernier AVL"
  },
  {
    "manager_Name": "562( 3,302,018 )",
    "Teams": "Bruno-nly Fans( Bejoy M Shrestha\u00B2\u2076\u2074 )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "Raya SUN",
    "Player_11": "Woltemade BRE",
    "Player_10": "Haaland LIV",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "King EVE",
    "Player_14": "Van de",
    "Player_7": "Ndiaye FUL",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "Saka SUN",
    "Player_6": "Semenyo AVL",
    "Player_3": "Gabriel SUN",
    "Player_4": "Senesi AVL",
    "Player_8": "Mbeumo 6",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Gudmundsson NFO"
  },
  {
    "manager_Name": "554( 3,743,374 )",
    "Teams": "GustavousGooner( Ashish Subba )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "S\u00E1nchez WOL",
    "Player_11": "Mateta BHA",
    "Player_10": "Haaland LIV",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Cullen WHU",
    "Player_14": "Gudmundsson NFO",
    "Player_7": "Enzo WOL",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "Szoboszlai MCI",
    "Player_6": "Semenyo AVL",
    "Player_3": "Senesi AVL",
    "Player_4": "Gabriel SUN",
    "Player_8": "Saka SUN",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Livramento BRE"
  },
  {
    "manager_Name": "554( 3,753,468 )",
    "Teams": "Cheesygarlic( Rishi Thulung )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "S\u00E1nchez WOL",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland LIV",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Senesi AVL",
    "Player_14": "Reijnders LIV",
    "Player_7": "Saka SUN",
    "Player_2": "J.Timber SUN",
    "Player_5": "Mbeumo 6",
    "Player_6": "Semenyo AVL",
    "Player_3": "Tarkowski FUL",
    "Player_4": "Botman BRE",
    "Player_8": "Enzo WOL",
    "Player_9": "Kroupi.Jr AVL",
    "Player_15": "Mukiele ARS"
  },
  {
    "manager_Name": "549( 4,060,730 )",
    "Teams": "The Regista.( Passang T Sherpa )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "Roefs ARS",
    "Player_11": "Haaland LIV",
    "Player_10": "Thiago NEW",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Woltemade BRE",
    "Player_14": "Reijnders LIV",
    "Player_7": "Semenyo AVL",
    "Player_2": "Cucurella WOL",
    "Player_5": "Gu\u00E9hi BHA",
    "Player_6": "Mbeumo 6",
    "Player_3": "Calafiori SUN",
    "Player_4": "Gabriel SUN",
    "Player_8": "Grealish FUL",
    "Player_9": "Rice SUN",
    "Player_15": "Est\u00E8ve WHU"
  },
  {
    "manager_Name": "539( 4,607,714 )",
    "Teams": "Hooligans25( Pradhyumna Subba )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "Raya SUN",
    "Player_11": "Haaland LIV",
    "Player_10": "Woltemade BRE",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Van de",
    "Player_14": "Reijnders LIV",
    "Player_7": "Sarr BHA",
    "Player_2": "Gabriel SUN",
    "Player_5": "Neto WOL",
    "Player_6": "Mbeumo 6",
    "Player_3": "Richards BHA",
    "Player_4": "J.Timber SUN",
    "Player_8": "Caicedo WOL",
    "Player_9": "Ekitik\u00E9 MCI",
    "Player_15": "Reinildo ARS"
  },
  {
    "manager_Name": "537( 4,742,661 )",
    "Teams": "Busby Baby( Regean Lama )",
    "SXL": "IND",
    "Latp": "8",
    "Player_1": "S\u00E1nchez WOL",
    "Player_11": "Woltemade BRE",
    "Player_10": "Isidor ARS",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Reijnders LIV",
    "Player_14": "Dorgu 1",
    "Player_7": "Mbeumo 6",
    "Player_2": "Van de",
    "Player_5": "Grealish FUL",
    "Player_6": "Semenyo AVL",
    "Player_3": "J.Timber SUN",
    "Player_4": "Mu\u00F1oz BHA",
    "Player_8": "B.Fernandes 1",
    "Player_9": "Haaland LIV",
    "Player_15": "Alex Moreno"
  },
  {
    "manager_Name": "536( 4,786,860 )",
    "Teams": "Imperial Blues( Saurabh Tamang )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "S\u00E1nchez WOL",
    "Player_11": "Mateta BHA",
    "Player_10": "Haaland LIV",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Senesi AVL",
    "Player_14": "Foster WHU",
    "Player_7": "Mbeumo 6",
    "Player_2": "Gabriel SUN",
    "Player_5": "Caicedo WOL",
    "Player_6": "Semenyo AVL",
    "Player_3": "Richards BHA",
    "Player_4": "Botman BRE",
    "Player_8": "Ndiaye FUL",
    "Player_9": "Saka SUN",
    "Player_15": "Est\u00E8ve WHU"
  },
  {
    "manager_Name": "533( 4,956,205 )",
    "Teams": "GODFATHER FC( Riwaj Rai )",
    "SXL": "IND",
    "Latp": "1",
    "Player_1": "D\u00FAbravka WHU",
    "Player_11": "Haaland LIV",
    "Player_10": "Isidor ARS",
    "Player_12": "Sels LEE",
    "Player_13": "Cash BOU",
    "Player_14": "Semenyo AVL",
    "Player_7": "Caicedo WOL",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "Kudus 0",
    "Player_6": "O.Dango NEW",
    "Player_3": "Cucurella WOL",
    "Player_4": "Pedro Porro",
    "Player_8": "Grealish FUL",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Est\u00E8ve WHU"
  },
  {
    "manager_Name": "528( 5,224,511 )",
    "Teams": "I_am_done_XI( Dipen Thapa )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "Raya SUN",
    "Player_11": "Mateta BHA",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Kudus 0",
    "Player_14": "Gy\u00F6keres SUN",
    "Player_7": "Caicedo WOL",
    "Player_2": "Senesi AVL",
    "Player_5": "Konsa BOU",
    "Player_6": "Semenyo AVL",
    "Player_3": "Gu\u00E9hi BHA",
    "Player_4": "Gabriel SUN",
    "Player_8": "M.Salah MCI",
    "Player_9": "Grealish FUL",
    "Player_15": "Est\u00E8ve WHU"
  },
  {
    "manager_Name": "515( 5,947,654 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "Raya SUN",
    "Player_11": "Haaland LIV",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Mukiele ARS",
    "Player_14": "Gudmundsson NFO",
    "Player_7": "Reijnders LIV",
    "Player_2": "Gabriel SUN",
    "Player_5": "L.Paquet\u00E1 BUR",
    "Player_6": "Xhaka ARS",
    "Player_3": "Cucurella WOL",
    "Player_4": "Senesi AVL",
    "Player_8": "Rice SUN",
    "Player_9": "Thiago NEW",
    "Player_15": "L.Miley BRE"
  },
  {
    "manager_Name": "513( 6,067,953 )",
    "Teams": "GUNNERS( Omkar Subba )",
    "SXL": "IND",
    "Latp": "1",
    "Player_1": "Vicario 1",
    "Player_11": "Thiago NEW",
    "Player_10": "Haaland LIV",
    "Player_12": "Verbruggen CRY",
    "Player_13": "Gravenberch MCI",
    "Player_14": "Van de",
    "Player_7": "Semenyo AVL",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "Senesi AVL",
    "Player_6": "Caicedo WOL",
    "Player_3": "Virgil MCI",
    "Player_4": "Gabriel SUN",
    "Player_8": "Rice SUN",
    "Player_9": "Woltemade BRE",
    "Player_15": "Anthony WHU"
  },
  {
    "manager_Name": "508( 6,329,597 )",
    "Teams": "Hangkim_0011( ABHINANDAN RAI )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "S\u00E1nchez WOL",
    "Player_11": "Haaland LIV",
    "Player_10": "Mateta BHA",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Est\u00E8ve WHU",
    "Player_14": "Welbeck CRY",
    "Player_7": "Mbeumo 6",
    "Player_2": "Gu\u00E9hi BHA",
    "Player_5": "Rogers BOU",
    "Player_6": "Rice SUN",
    "Player_3": "Burn BRE",
    "Player_4": "Gabriel SUN",
    "Player_8": "Semenyo AVL",
    "Player_9": "Caicedo WOL",
    "Player_15": "Konsa BOU"
  },
  {
    "manager_Name": "499( 6,803,028 )",
    "Teams": "Jorebungalow YFC( Vivek Lama )",
    "SXL": "IND",
    "Latp": "1",
    "Player_1": "Mamardashvili MCI",
    "Player_11": "Mateta BHA",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "L.Miley BRE",
    "Player_14": "Trippier BRE",
    "Player_7": "Semenyo AVL",
    "Player_2": "Calafiori SUN",
    "Player_5": "Caicedo WOL",
    "Player_6": "Saka SUN",
    "Player_3": "Van de",
    "Player_4": "James WOL",
    "Player_8": "Gakpo MCI",
    "Player_9": "Haaland LIV",
    "Player_15": "Est\u00E8ve WHU"
  },
  {
    "manager_Name": "492( 7,152,809 )",
    "Teams": "Let MEE COOK( \u00CFaraplang Pompyrthat )",
    "SXL": "IND",
    "Latp": "6",
    "Player_1": "Pope BRE",
    "Player_11": "Haaland LIV",
    "Player_10": "Woltemade BRE",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Xhaka ARS",
    "Player_14": "Rodon NFO",
    "Player_7": "Caicedo WOL",
    "Player_2": "J.Timber SUN",
    "Player_5": "Mbeumo 6",
    "Player_6": "Semenyo AVL",
    "Player_3": "Senesi AVL",
    "Player_4": "Burn BRE",
    "Player_8": "Enzo WOL",
    "Player_9": "Mateta BHA",
    "Player_15": "Est\u00E8ve WHU"
  },
  {
    "manager_Name": "468( 8,257,428 )",
    "Teams": "Boehly Blues( Aditya Bhandari )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "Petrovi\u0107 AVL",
    "Player_11": "Haaland LIV",
    "Player_10": "Woltemade BRE",
    "Player_12": "D\u00FAbravka WHU",
    "Player_13": "Anthony WHU",
    "Player_14": "Senesi AVL",
    "Player_7": "Saka SUN",
    "Player_2": "J.Timber SUN",
    "Player_5": "Gabriel SUN",
    "Player_6": "Enzo WOL",
    "Player_3": "James WOL",
    "Player_4": "Gu\u00E9hi BHA",
    "Player_8": "Semenyo AVL",
    "Player_9": "Mateta BHA",
    "Player_15": "Stach NFO"
  },
  {
    "manager_Name": "433( 9,517,137 )",
    "Teams": "Invincibles( Bishal Rai )",
    "SXL": "IND",
    "Latp": "7",
    "Player_1": "Raya SUN",
    "Player_11": "Mateta BHA",
    "Player_10": "Caicedo WOL",
    "Player_12": "Kinsky 0",
    "Player_13": "Ekitik\u00E9 MCI",
    "Player_14": "Milenkovi\u0107 LEE",
    "Player_7": "Semenyo AVL",
    "Player_2": "Mu\u00F1oz BHA",
    "Player_5": "Gabriel SUN",
    "Player_6": "Enzo WOL",
    "Player_3": "J.Timber SUN",
    "Player_4": "Pedro Porro",
    "Player_8": "Mbeumo 6",
    "Player_9": "Neto WOL",
    "Player_15": "Wood LEE"
  }
];