var s = [
  {
    "manager_Name": "1,593( 45,142 ) TotalXfr : 24",
    "Teams": "Humbesi( ~ Kopi ~ )",
    "SXL": "countryCode",
    "Latp": "97",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Isak 2",
    "Player_10": "Gakpo 5, EVE (A)",
    "Player_12": "Fabianski CHE (A)",
    "Player_13": "Amad 2",
    "Player_14": "Huijsen 0",
    "Player_7": "M.Salah 48, EVE (A)",
    "Player_2": "Alexander-Arnold 6, EVE (A)",
    "Player_5": "B.Fernandes 1",
    "Player_6": "Palmer WHU (H)",
    "Player_3": "Mykolenko 6, LIV (H)",
    "Player_4": "Gabriel 2",
    "Player_8": "Rogers 1",
    "Player_9": "Wood 17",
    "Player_15": "Castagne 2"
  },
  {
    "manager_Name": "1,564( 125,048 ) TotalXfr : 27",
    "Teams": "Jelly Flood( Lorin Minxhozi )",
    "SXL": "countryCode",
    "Latp": "86",
    "Player_1": "Verbruggen -1",
    "Player_11": "Isak 2",
    "Player_10": "Gakpo 5, EVE (A)",
    "Player_12": "Moyes 12, LIV (H)",
    "Player_13": "Fabianski CHE (A)",
    "Player_14": "Rogers 1",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Robinson 4",
    "Player_5": "Mbeumo 2",
    "Player_6": "Gordon 1",
    "Player_3": "Mykolenko 6, LIV (H)",
    "Player_4": "Alexander-Arnold 6, EVE (A)",
    "Player_8": "Palmer WHU (H)",
    "Player_9": "Wood 17",
    "Player_15": "Kerkez 1"
  },
  {
    "manager_Name": "1,462( 1,222,038 ) TotalXfr : 22",
    "Teams": "#SorareMarin( Marin Jano )",
    "SXL": "countryCode",
    "Latp": "80",
    "Player_1": "Sels 8",
    "Player_11": "Gakpo 5, EVE (A)",
    "Player_10": "Isak 2",
    "Player_12": "Flekken 0",
    "Player_13": "Gabriel 2",
    "Player_14": "Kerkez 1",
    "Player_7": "Palmer WHU (H)",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Gordon 1",
    "Player_6": "M.Salah 48, EVE (A)",
    "Player_3": "Hall 1",
    "Player_4": "Alexander-Arnold 6, EVE (A)",
    "Player_8": "Rogers 1",
    "Player_9": "Amad 2",
    "Player_15": "Chiwome 0"
  },
  {
    "manager_Name": "1,409( 2,347,097 ) TotalXfr : 25",
    "Teams": "Supercampeones( Ronny Nelkenbaum )",
    "SXL": "countryCode",
    "Latp": "78",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Wood 17",
    "Player_10": "Isak 2",
    "Player_12": "Fabianski CHE (A)",
    "Player_13": "Colwill WHU (H)",
    "Player_14": "Ra\u00FAl 8",
    "Player_7": "Rogers 1",
    "Player_2": "Hall 1",
    "Player_5": "B.Fernandes 1",
    "Player_6": "Luis D\u00EDaz 3, EVE (A)",
    "Player_3": "Alexander-Arnold 6, EVE (A)",
    "Player_4": "Mykolenko 6, LIV (H)",
    "Player_8": "M.Salah 32, EVE (A)",
    "Player_9": "Palmer WHU (H)",
    "Player_15": "Mu\u00F1oz 9"
  },
  {
    "manager_Name": "1,487( 813,880 ) TotalXfr : 26",
    "Teams": "Wiggler FC( Andrew Carr )",
    "SXL": "countryCode",
    "Latp": "100",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Wood 17",
    "Player_10": "Isak 2",
    "Player_12": "Valdimarsson 1",
    "Player_13": "I.Sarr 3",
    "Player_14": "Murillo 5",
    "Player_7": "Palmer WHU (H)",
    "Player_2": "Hall 1",
    "Player_5": "Gordon 1",
    "Player_6": "M.Salah 48, EVE (A)",
    "Player_3": "Alexander-Arnold 6, EVE (A)",
    "Player_4": "Mu\u00F1oz 9",
    "Player_8": "Damsgaard 2",
    "Player_9": "Gakpo 5, EVE (A)",
    "Player_15": "Greaves 1"
  },
  {
    "manager_Name": "1,470( 1,088,567 ) TotalXfr : 29",
    "Teams": "Iwobi Wan-Kenobi( Sunit Patel )",
    "SXL": "countryCode",
    "Latp": "96",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Isak 2",
    "Player_10": "Wood 17",
    "Player_12": "Moyes 12, LIV (H)",
    "Player_13": "Fabianski CHE (A)",
    "Player_14": "Trossard 2",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Robinson 4",
    "Player_5": "Amad 2",
    "Player_6": "Palmer WHU (H)",
    "Player_3": "Mykolenko 6, LIV (H)",
    "Player_4": "Alexander-Arnold 6, EVE (A)",
    "Player_8": "Rogers 1",
    "Player_9": "Gakpo 5, EVE (A)",
    "Player_15": "J.Timber 1"
  },
  {
    "manager_Name": "1,418( 2,138,939 ) TotalXfr : 24",
    "Teams": "Data Crisis( Camilla Nurkhanov )",
    "SXL": "countryCode",
    "Latp": "101",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Ra\u00FAl 8",
    "Player_10": "Wood 17",
    "Player_12": "Slot 10, EVE (A)",
    "Player_13": "Turner 0",
    "Player_14": "Young 1, LIV (H)",
    "Player_7": "Amad 2",
    "Player_2": "Aina 6",
    "Player_5": "Kluivert 2",
    "Player_6": "Iwobi 2",
    "Player_3": "Alexander-Arnold 6, EVE (A)",
    "Player_4": "Hall 1",
    "Player_8": "M.Salah 32, EVE (A)",
    "Player_9": "Haaland 6",
    "Player_15": "Castagne 2"
  },
  {
    "manager_Name": "1,420( 2,087,198 ) TotalXfr : 21",
    "Teams": "Enter Team Name( teo teo )",
    "SXL": "countryCode",
    "Latp": "106",
    "Player_1": "Sels 8",
    "Player_11": "Wood 17",
    "Player_10": "Isak 2",
    "Player_12": "Henderson 6",
    "Player_13": "Robinson 4",
    "Player_14": "Ra\u00FAl 8",
    "Player_7": "Palmer WHU (H)",
    "Player_2": "Hall 1",
    "Player_5": "Elanga 13",
    "Player_6": "Luis D\u00EDaz 3, EVE (A)",
    "Player_3": "Alexander-Arnold 6, EVE (A)",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "M.Salah 48, EVE (A)",
    "Player_9": "Kluivert 2",
    "Player_15": "Kerkez 1"
  },
  {
    "manager_Name": "1,360( 3,499,055 ) TotalXfr : 26",
    "Teams": "Herr Direktor( Roger Shehu )",
    "SXL": "countryCode",
    "Latp": "67",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Isak 2",
    "Player_10": "Wissa 2",
    "Player_12": "Fabianski CHE (A)",
    "Player_13": "Ra\u00FAl 8",
    "Player_14": "Eze 1",
    "Player_7": "Palmer WHU (H)",
    "Player_2": "Virgil 5, EVE (A)",
    "Player_5": "Davis 1",
    "Player_6": "M.Salah 32, EVE (A)",
    "Player_3": "Mykolenko 6, LIV (H)",
    "Player_4": "Alexander-Arnold 6, EVE (A)",
    "Player_8": "Mbeumo 2",
    "Player_9": "Amad 2",
    "Player_15": "Hall 1"
  },
  {
    "manager_Name": "1,416( 2,188,891 ) TotalXfr : 27",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "countryCode",
    "Latp": "82",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Isak 2",
    "Player_10": "Wood 17",
    "Player_12": "Henderson 6",
    "Player_13": "J.Timber 1",
    "Player_14": "Dalot 1",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Konat\u00E9 6, EVE (A)",
    "Player_5": "Palmer WHU (H)",
    "Player_6": "Kluivert 2",
    "Player_3": "Burn 0",
    "Player_4": "Milenkovi\u0107 6",
    "Player_8": "B.Fernandes 1",
    "Player_9": "Ndiaye 7, LIV (H)",
    "Player_15": "Iroegbunam 1, LIV (H)"
  },
  {
    "manager_Name": "1,223( 6,292,932 ) TotalXfr : 9",
    "Teams": "Ibis Warriors( Harmeet Chana )",
    "SXL": "countryCode",
    "Latp": "53",
    "Player_1": "Raya 3",
    "Player_11": "Ra\u00FAl 8",
    "Player_10": "Haaland 12",
    "Player_12": "Turner 0",
    "Player_13": "Adama 2",
    "Player_14": "Harwood-Bellis 1",
    "Player_7": "Onana 1",
    "Player_2": "Saliba 2",
    "Player_5": "Palmer WHU (H)",
    "Player_6": "Smith Rowe 2",
    "Player_3": "Digne 1",
    "Player_4": "Robertson 7, EVE (A)",
    "Player_8": "M.Salah 16, EVE (A)",
    "Player_9": "Welbeck 1",
    "Player_15": "Barco 0"
  },
  {
    "manager_Name": "1,415( 2,201,061 ) TotalXfr : 21",
    "Teams": "Blue Boys \uFFFD( Ilir B )",
    "SXL": "countryCode",
    "Latp": "50",
    "Player_1": "S\u00E1nchez WHU (H)",
    "Player_11": "Isak 4",
    "Player_10": "Wood 17",
    "Player_12": "Fabianski CHE (A)",
    "Player_13": "Iwobi 2",
    "Player_14": "Harwood-Bellis 1",
    "Player_7": "Amad 2",
    "Player_2": "Aina 6",
    "Player_5": "Mbeumo 2",
    "Player_6": "Palmer WHU (H)",
    "Player_3": "Huijsen 0",
    "Player_4": "Martinez 2",
    "Player_8": "M.Salah 16, EVE (A)",
    "Player_9": "Watkins 1",
    "Player_15": "Keane 0, LIV (H)"
  },
  {
    "manager_Name": "1,352( 3,681,038 ) TotalXfr : 23",
    "Teams": "5-D( Erald Haxhiu )",
    "SXL": "countryCode",
    "Latp": "79",
    "Player_1": "Raya 3",
    "Player_11": "Havertz 9",
    "Player_10": "Isak 2",
    "Player_12": "Cahill 0",
    "Player_13": "Wissa 2",
    "Player_14": "Lewis 0",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Pedro Porro 6",
    "Player_5": "Mbeumo 2",
    "Player_6": "Elanga 13",
    "Player_3": "Alexander-Arnold 6, EVE (A)",
    "Player_4": "Hall 1",
    "Player_8": "Luis D\u00EDaz 3, EVE (A)",
    "Player_9": "Iwobi 2",
    "Player_15": "Mykolenko 6, LIV (H)"
  },
  {
    "manager_Name": "1,194( 6,797,590 ) TotalXfr : 8",
    "Teams": "RoboKoop( Enio Minxhozi )",
    "SXL": "countryCode",
    "Latp": "37",
    "Player_1": "Raya 3",
    "Player_11": "Haaland 12",
    "Player_10": "Isak 2",
    "Player_12": "Fabianski CHE (A)",
    "Player_13": "Harwood-Bellis 1",
    "Player_14": "Chiwome 0",
    "Player_7": "Buonanotte 0",
    "Player_2": "Alexander-Arnold 6, EVE (A)",
    "Player_5": "Rogers 1",
    "Player_6": "Eze 1",
    "Player_3": "Mazraoui 2",
    "Player_4": "Gvardiol 0",
    "Player_8": "Mbeumo 2",
    "Player_9": "Son 8",
    "Player_15": "A.Phillips 0"
  },
  {
    "manager_Name": "1,244( 5,916,879 ) TotalXfr : 20",
    "Teams": "Sniper( Florian Toslluku )",
    "SXL": "countryCode",
    "Latp": "63",
    "Player_1": "Henderson 6",
    "Player_11": "N.Jackson WHU (H)",
    "Player_10": "Isak 2",
    "Player_12": "Ederson M. 0",
    "Player_13": "Alex Moreno 0",
    "Player_14": "Strand Larsen 0",
    "Player_7": "Thomas 7",
    "Player_2": "Alexander-Arnold 6, EVE (A)",
    "Player_5": "Maddison 0",
    "Player_6": "Gordon 1",
    "Player_3": "Virgil 5, EVE (A)",
    "Player_4": "Mazraoui 2",
    "Player_8": "Amad 2",
    "Player_9": "M.Salah 32, EVE (A)",
    "Player_15": "Andersen 1"
  },
  {
    "manager_Name": "1,266( 5,501,496 ) TotalXfr : 19",
    "Teams": "Inceneratori( Geri Muho )",
    "SXL": "countryCode",
    "Latp": "73",
    "Player_1": "Raya 3",
    "Player_11": "Gakpo 5, EVE (A)",
    "Player_10": "Ndiaye 7, LIV (H)",
    "Player_12": "Moyes 12, LIV (H)",
    "Player_13": "Fabianski CHE (A)",
    "Player_14": "Harwood-Bellis 1",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Mykolenko 6, LIV (H)",
    "Player_5": "B.Fernandes 1",
    "Player_6": "Madueke WHU (H)",
    "Player_3": "Gvardiol 0",
    "Player_4": "Alexander-Arnold 6, EVE (A)",
    "Player_8": "Palmer WHU (H)",
    "Player_9": "Vardy 1",
    "Player_15": "Greaves 1"
  },
  {
    "manager_Name": "1,355( 3,609,434 ) TotalXfr : 22",
    "Teams": "Kokeqethurit( Daver Berberi )",
    "SXL": "countryCode",
    "Latp": "94",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Gakpo 5, EVE (A)",
    "Player_10": "Wood 17",
    "Player_12": "Moyes 12, LIV (H)",
    "Player_13": "Fabianski CHE (A)",
    "Player_14": "Cucurella WHU (H)",
    "Player_7": "Amad 2",
    "Player_2": "Gabriel 2",
    "Player_5": "Mykolenko 6, LIV (H)",
    "Player_6": "M.Salah 32, EVE (A)",
    "Player_3": "Alexander-Arnold 6, EVE (A)",
    "Player_4": "Hall 1",
    "Player_8": "Palmer WHU (H)",
    "Player_9": "Isak 2",
    "Player_15": "Rogers 1"
  },
  {
    "manager_Name": "1,354( 3,630,921 ) TotalXfr : 21",
    "Teams": "Tokenized Maxi \u26A1\uFE0F( Eni Shtini )",
    "SXL": "countryCode",
    "Latp": "92",
    "Player_1": "Sels 8",
    "Player_11": "Wood 17",
    "Player_10": "Gakpo 5, EVE (A)",
    "Player_12": "Moyes 12, LIV (H)",
    "Player_13": "Fabianski CHE (A)",
    "Player_14": "Rogers 1",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Konat\u00E9 6, EVE (A)",
    "Player_5": "Gordon 1",
    "Player_6": "Amad 2",
    "Player_3": "Mykolenko 6, LIV (H)",
    "Player_4": "Hall 1",
    "Player_8": "Palmer WHU (H)",
    "Player_9": "Isak 2",
    "Player_15": "N.Williams 12"
  },
  {
    "manager_Name": "1,116( 8,046,476 ) TotalXfr : 24",
    "Teams": "Yaya( Bardhyl Minxhozi )",
    "SXL": "countryCode",
    "Latp": "77",
    "Player_1": "Henderson 6",
    "Player_11": "Jo\u00E3o Pedro 1",
    "Player_10": "Kulusevski 3",
    "Player_12": "Ederson M. 0",
    "Player_13": "Akanji 0",
    "Player_14": "Broja 0, LIV (H)",
    "Player_7": "Palmer WHU (H)",
    "Player_2": "Alexander-Arnold 6, EVE (A)",
    "Player_5": "Digne 1",
    "Player_6": "Mbeumo 2",
    "Player_3": "Pedro Porro 6",
    "Player_4": "Robertson 7, EVE (A)",
    "Player_8": "Elanga 13",
    "Player_9": "M.Salah 32, EVE (A)",
    "Player_15": "Scarlett 1"
  },
  {
    "manager_Name": "1,112( 8,104,426 ) TotalXfr : 23",
    "Teams": "Leftisti( Magi Muco )",
    "SXL": "countryCode",
    "Latp": "57",
    "Player_1": "S\u00E1nchez WHU (H)",
    "Player_11": "Strand Larsen 0",
    "Player_10": "Haaland 6",
    "Player_12": "Areola CHE (A)",
    "Player_13": "Nwaneri 6",
    "Player_14": "Bednarek 1",
    "Player_7": "Schade 2",
    "Player_2": "Hall 1",
    "Player_5": "Amad 2",
    "Player_6": "Palmer WHU (H)",
    "Player_3": "Pedro Porro 6",
    "Player_4": "Quansah 0, EVE (A)",
    "Player_8": "M.Salah 32, EVE (A)",
    "Player_9": "Delap 8",
    "Player_15": "Faes 0"
  }
];