var s = [
  {
    "manager_Name": "1,575( 86,088 ) TotalXfr : 23",
    "Teams": "Blue Brigade( Bhuman Basnet )",
    "SXL": "countryCode",
    "Latp": "94",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Wood 17",
    "Player_10": "Isak 2",
    "Player_12": "Moyes 12, LIV (H)",
    "Player_13": "Fabianski CHE (A)",
    "Player_14": "Amad 2",
    "Player_7": "Palmer WHU (H)",
    "Player_2": "Aina 6",
    "Player_5": "M.Salah 32, EVE (A)",
    "Player_6": "Rogers 1",
    "Player_3": "Alexander-Arnold 6, EVE (A)",
    "Player_4": "Gabriel 2",
    "Player_8": "Mbeumo 2",
    "Player_9": "Gakpo 5, EVE (A)",
    "Player_15": "Faes 0"
  },
  {
    "manager_Name": "1,564( 123,538 ) TotalXfr : 23",
    "Teams": "BLIND at the BACK( Prayash Thapa )",
    "SXL": "countryCode",
    "Latp": "78",
    "Player_1": "Henderson 6",
    "Player_11": "Isak 2",
    "Player_10": "Gakpo 5, EVE (A)",
    "Player_12": "Valdimarsson 1",
    "Player_13": "Mu\u00F1oz 9",
    "Player_14": "Jo\u00E3o Pedro 1",
    "Player_7": "M.Salah 48, EVE (A)",
    "Player_2": "Alexander-Arnold 6, EVE (A)",
    "Player_5": "Rogers 1",
    "Player_6": "Mbeumo 2",
    "Player_3": "Hall 1",
    "Player_4": "Milenkovi\u0107 6",
    "Player_8": "Gordon 1",
    "Player_9": "Palmer WHU (H)",
    "Player_15": "Robinson 4"
  },
  {
    "manager_Name": "1,523( 384,362 ) TotalXfr : 25",
    "Teams": "FALSE 9( Rohan Rai )",
    "SXL": "countryCode",
    "Latp": "84",
    "Player_1": "Henderson 6",
    "Player_11": "Gakpo 5, EVE (A)",
    "Player_10": "Wood 17",
    "Player_12": "Slot 10, EVE (A)",
    "Player_13": "Fabianski CHE (A)",
    "Player_14": "Eze 1",
    "Player_7": "Rogers 1",
    "Player_2": "Mykolenko 6, LIV (H)",
    "Player_5": "Palmer WHU (H)",
    "Player_6": "Mbeumo 2",
    "Player_3": "Digne 1",
    "Player_4": "Gabriel 2",
    "Player_8": "M.Salah 32, EVE (A)",
    "Player_9": "Isak 2",
    "Player_15": "Robinson 4"
  },
  {
    "manager_Name": "1,513( 479,008 ) TotalXfr : 22",
    "Teams": "The SAFfron Sword( Milan Singh )",
    "SXL": "countryCode",
    "Latp": "89",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Isak 2",
    "Player_10": "Wood 17",
    "Player_12": "Slot 10, EVE (A)",
    "Player_13": "Fabianski CHE (A)",
    "Player_14": "Mu\u00F1oz 9",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Alexander-Arnold 6, EVE (A)",
    "Player_5": "Mbeumo 2",
    "Player_6": "Palmer WHU (H)",
    "Player_3": "Gabriel 2",
    "Player_4": "Mykolenko 6, LIV (H)",
    "Player_8": "Rogers 1",
    "Player_9": "Amad 2",
    "Player_15": "Jo\u00E3o Pedro 1"
  },
  {
    "manager_Name": "1,513( 481,866 ) TotalXfr : 24",
    "Teams": "Last Season\u0027s Loser( \u00CFaraplang Pompyrthat )",
    "SXL": "countryCode",
    "Latp": "79",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Isak 2",
    "Player_10": "Ndiaye 7, LIV (H)",
    "Player_12": "Moyes 12, LIV (H)",
    "Player_13": "Verbruggen -1",
    "Player_14": "I.Sarr 3",
    "Player_7": "Palmer WHU (H)",
    "Player_2": "Alexander-Arnold 6, EVE (A)",
    "Player_5": "Rogers 1",
    "Player_6": "Mbeumo 2",
    "Player_3": "Gabriel 2",
    "Player_4": "Hall 1",
    "Player_8": "M.Salah 32, EVE (A)",
    "Player_9": "Gakpo 5, EVE (A)",
    "Player_15": "Castagne 2"
  },
  {
    "manager_Name": "1,513( 482,894 ) TotalXfr : 25",
    "Teams": "Fu\u00DFball-Mannschaft( Gaurav Shrestha )",
    "SXL": "countryCode",
    "Latp": "79",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Jo\u00E3o Pedro 1",
    "Player_10": "Ndiaye 7, LIV (H)",
    "Player_12": "Slot 10, EVE (A)",
    "Player_13": "Fabianski CHE (A)",
    "Player_14": "I.Sarr 3",
    "Player_7": "Amad 2",
    "Player_2": "Gabriel 2",
    "Player_5": "M.Salah 32, EVE (A)",
    "Player_6": "Palmer WHU (H)",
    "Player_3": "Mykolenko 6, LIV (H)",
    "Player_4": "Alexander-Arnold 6, EVE (A)",
    "Player_8": "Mbeumo 2",
    "Player_9": "Isak 2",
    "Player_15": "Greaves 1"
  },
  {
    "manager_Name": "1,503( 597,038 ) TotalXfr : 25",
    "Teams": "Blue Moon X1\uFFFD( PRAYAS BAJGAI )",
    "SXL": "countryCode",
    "Latp": "76",
    "Player_1": "Raya 3",
    "Player_11": "Isak 2",
    "Player_10": "Mateta 10",
    "Player_12": "Fabianski CHE (A)",
    "Player_13": "Kluivert 2",
    "Player_14": "Gabriel 2",
    "Player_7": "Rogers 1",
    "Player_2": "Mykolenko 6, LIV (H)",
    "Player_5": "Palmer WHU (H)",
    "Player_6": "M.Salah 32, EVE (A)",
    "Player_3": "Alexander-Arnold 6, EVE (A)",
    "Player_4": "Mu\u00F1oz 9",
    "Player_8": "Mbeumo 2",
    "Player_9": "Gakpo 5, EVE (A)",
    "Player_15": "Van den Berg 1"
  },
  {
    "manager_Name": "1,498( 659,285 ) TotalXfr : 24",
    "Teams": "Error404( Duri Tadu )",
    "SXL": "countryCode",
    "Latp": "81",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Jo\u00E3o Pedro 1",
    "Player_10": "Isak 2",
    "Player_12": "Slot 10, EVE (A)",
    "Player_13": "Fabianski CHE (A)",
    "Player_14": "Enzo WHU (H)",
    "Player_7": "Palmer WHU (H)",
    "Player_2": "Gabriel 2",
    "Player_5": "Amad 2",
    "Player_6": "M.Salah 32, EVE (A)",
    "Player_3": "Mu\u00F1oz 9",
    "Player_4": "Virgil 5, EVE (A)",
    "Player_8": "Mbeumo 2",
    "Player_9": "Ndiaye 7, LIV (H)",
    "Player_15": "Robinson 4"
  },
  {
    "manager_Name": "1,494( 715,631 ) TotalXfr : 27",
    "Teams": "Avijit@afc( AVIJIT DAS )",
    "SXL": "countryCode",
    "Latp": "94",
    "Player_1": "Sels 8",
    "Player_11": "Mateta 10",
    "Player_10": "Wood 17",
    "Player_12": "Slot 10, EVE (A)",
    "Player_13": "Fabianski CHE (A)",
    "Player_14": "Kluivert 2",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Hall 1",
    "Player_5": "Palmer WHU (H)",
    "Player_6": "Mbeumo 2",
    "Player_3": "Mykolenko 6, LIV (H)",
    "Player_4": "Virgil 5, EVE (A)",
    "Player_8": "Rogers 1",
    "Player_9": "Isak 2",
    "Player_15": "Robinson 4"
  },
  {
    "manager_Name": "1,485( 839,617 ) TotalXfr : 23",
    "Teams": "FC ASSASSINS( Kushal Sahota )",
    "SXL": "countryCode",
    "Latp": "95",
    "Player_1": "S\u00E1nchez WHU (H)",
    "Player_11": "Haaland 6",
    "Player_10": "Wood 17",
    "Player_12": "Slot 10, EVE (A)",
    "Player_13": "Fabianski CHE (A)",
    "Player_14": "Dibling 0",
    "Player_7": "Mbeumo 2",
    "Player_2": "N.Williams 12",
    "Player_5": "Gana 3, LIV (H)",
    "Player_6": "Palmer WHU (H)",
    "Player_3": "Virgil 5, EVE (A)",
    "Player_4": "Hall 1",
    "Player_8": "M.Salah 32, EVE (A)",
    "Player_9": "Ndiaye 7, LIV (H)",
    "Player_15": "O\u0027Shea 1"
  },
  {
    "manager_Name": "1,479( 932,306 ) TotalXfr : 23",
    "Teams": "Bottled FC( Rishi Thulung )",
    "SXL": "countryCode",
    "Latp": "100",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Haaland 6",
    "Player_10": "Ndiaye 7, LIV (H)",
    "Player_12": "Henderson 6",
    "Player_13": "Van den Berg 1",
    "Player_14": "Robinson 4",
    "Player_7": "Palmer WHU (H)",
    "Player_2": "Konat\u00E9 6, EVE (A)",
    "Player_5": "Amad 2",
    "Player_6": "Mbeumo 2",
    "Player_3": "Mazraoui 2",
    "Player_4": "Hall 1",
    "Player_8": "M.Salah 48, EVE (A)",
    "Player_9": "Wood 17",
    "Player_15": "Winks 2"
  },
  {
    "manager_Name": "1,461( 1,252,235 ) TotalXfr : 36",
    "Teams": "GUNNERS( Omkar Subba )",
    "SXL": "countryCode",
    "Latp": "94",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Isak 2",
    "Player_10": "Wood 17",
    "Player_12": "Henderson 6",
    "Player_13": "Robinson 4",
    "Player_14": "Ra\u00FAl 8",
    "Player_7": "M.Salah 48, EVE (A)",
    "Player_2": "Alexander-Arnold 6, EVE (A)",
    "Player_5": "Gordon 1",
    "Player_6": "Luis D\u00EDaz 3, EVE (A)",
    "Player_3": "Milenkovi\u0107 6",
    "Player_4": "Hall 1",
    "Player_8": "Palmer WHU (H)",
    "Player_9": "Rogers 1",
    "Player_15": "Huijsen 0"
  },
  {
    "manager_Name": "1,458( 1,295,663 ) TotalXfr : 22",
    "Teams": "PINE( SATYAM RAI )",
    "SXL": "countryCode",
    "Latp": "85",
    "Player_1": "Sels 8",
    "Player_11": "Mateta 10",
    "Player_10": "Isak 2",
    "Player_12": "Slot 10, EVE (A)",
    "Player_13": "Lis 0",
    "Player_14": "O.Dango 2",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Alexander-Arnold 6, EVE (A)",
    "Player_5": "Palmer WHU (H)",
    "Player_6": "Rogers 1",
    "Player_3": "Hall 1",
    "Player_4": "Mykolenko 6, LIV (H)",
    "Player_8": "Mbeumo 2",
    "Player_9": "Ndiaye 7, LIV (H)",
    "Player_15": "Gabriel 2"
  },
  {
    "manager_Name": "1,449( 1,465,439 ) TotalXfr : 16",
    "Teams": "Jatin( Jatin Ghimiray )",
    "SXL": "countryCode",
    "Latp": "86",
    "Player_1": "Raya 3",
    "Player_11": "Isak 2",
    "Player_10": "Wood 17",
    "Player_12": "Valdimarsson 1",
    "Player_13": "Konsa 1",
    "Player_14": "Van den Berg 1",
    "Player_7": "Luis D\u00EDaz 3, EVE (A)",
    "Player_2": "Gvardiol 0",
    "Player_5": "Palmer WHU (H)",
    "Player_6": "M.Salah 48, EVE (A)",
    "Player_3": "Alexander-Arnold 6, EVE (A)",
    "Player_4": "Robinson 4",
    "Player_8": "Amad 2",
    "Player_9": "Mitoma 1",
    "Player_15": "Jebbison 1"
  },
  {
    "manager_Name": "1,449( 1,474,238 ) TotalXfr : 24",
    "Teams": "The Regista.( Passang T Sherpa )",
    "SXL": "countryCode",
    "Latp": "72",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Isak 2",
    "Player_10": "Wood 17",
    "Player_12": "Sels 8",
    "Player_13": "Cucurella WHU (H)",
    "Player_14": "Smith Rowe 2",
    "Player_7": "Gordon 1",
    "Player_2": "Kerkez 1",
    "Player_5": "M.Salah 32, EVE (A)",
    "Player_6": "Palmer WHU (H)",
    "Player_3": "Aina 6",
    "Player_4": "Hall 1",
    "Player_8": "Amad 2",
    "Player_9": "Watkins 1",
    "Player_15": "Bednarek 1"
  },
  {
    "manager_Name": "1,444( 1,575,519 ) TotalXfr : 24",
    "Teams": "Mawat( Arwat Lyngdoh )",
    "SXL": "countryCode",
    "Latp": "74",
    "Player_1": "Sels 8",
    "Player_11": "Isak 2",
    "Player_10": "Ndiaye 7, LIV (H)",
    "Player_12": "Onana 1",
    "Player_13": "Wissa 2",
    "Player_14": "Wan-Bissaka CHE (A)",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Mu\u00F1oz 9",
    "Player_5": "Rogers 1",
    "Player_6": "Gordon 1",
    "Player_3": "Mykolenko 6, LIV (H)",
    "Player_4": "Konat\u00E9 6, EVE (A)",
    "Player_8": "Palmer WHU (H)",
    "Player_9": "Foden 2",
    "Player_15": "Mazraoui 2"
  },
  {
    "manager_Name": "1,435( 1,761,497 ) TotalXfr : 23",
    "Teams": "100 Yard Line Lords( Abhinay Pradhan )",
    "SXL": "countryCode",
    "Latp": "77",
    "Player_1": "Raya 3",
    "Player_11": "Gakpo 5, EVE (A)",
    "Player_10": "Wood 17",
    "Player_12": "Turner 0",
    "Player_13": "Huijsen 0",
    "Player_14": "Gabriel 2",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Hall 1",
    "Player_5": "Gordon 1",
    "Player_6": "Mbeumo 2",
    "Player_3": "Alexander-Arnold 6, EVE (A)",
    "Player_4": "Aina 6",
    "Player_8": "Kluivert 2",
    "Player_9": "Isak 2",
    "Player_15": "Winks 2"
  },
  {
    "manager_Name": "1,431( 1,849,566 ) TotalXfr : 24",
    "Teams": "\u2694\uFE0FFURY\u2694\uFE0F( Ashim Lama )",
    "SXL": "countryCode",
    "Latp": "92",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Gakpo 5, EVE (A)",
    "Player_10": "Isak 2",
    "Player_12": "Moyes 12, LIV (H)",
    "Player_13": "Flekken 0",
    "Player_14": "Kulusevski 3",
    "Player_7": "Rogers 1",
    "Player_2": "Virgil 5, EVE (A)",
    "Player_5": "Amad 2",
    "Player_6": "M.Salah 32, EVE (A)",
    "Player_3": "Hall 1",
    "Player_4": "Mykolenko 6, LIV (H)",
    "Player_8": "Palmer WHU (H)",
    "Player_9": "Wood 17",
    "Player_15": "Milenkovi\u0107 6"
  },
  {
    "manager_Name": "1,428( 1,921,422 ) TotalXfr : 29",
    "Teams": "YFC Jb( Vivek Lama )",
    "SXL": "countryCode",
    "Latp": "79",
    "Player_1": "A.Becker 9, EVE (A)",
    "Player_11": "Wood 17",
    "Player_10": "Isak 2",
    "Player_12": "Arrizabalaga 2",
    "Player_13": "Ra\u00FAl 8",
    "Player_14": "Saliba 2",
    "Player_7": "Palmer WHU (H)",
    "Player_2": "Alexander-Arnold 6, EVE (A)",
    "Player_5": "Gordon 1",
    "Player_6": "Amad 2",
    "Player_3": "Dalot 1",
    "Player_4": "Doherty 6",
    "Player_8": "M.Salah 32, EVE (A)",
    "Player_9": "Gana 3, LIV (H)",
    "Player_15": "Coady 0"
  },
  {
    "manager_Name": "1,422( 2,046,848 ) TotalXfr : 23",
    "Teams": "nativ fc( Monlom Rongong )",
    "SXL": "countryCode",
    "Latp": "74",
    "Player_1": "Henderson 6",
    "Player_11": "Isak 2",
    "Player_10": "Wood 17",
    "Player_12": "Valdimarsson 1",
    "Player_13": "Cunha 7",
    "Player_14": "Harwood-Bellis 1",
    "Player_7": "Gordon 1",
    "Player_2": "Milenkovi\u0107 6",
    "Player_5": "Palmer WHU (H)",
    "Player_6": "M.Salah 32, EVE (A)",
    "Player_3": "Hall 1",
    "Player_4": "Virgil 5, EVE (A)",
    "Player_8": "Mbeumo 2",
    "Player_9": "Amad 2",
    "Player_15": "Nedeljkovic 1"
  },
  {
    "manager_Name": "1,419( 2,123,083 ) TotalXfr : 30",
    "Teams": "heregoesnothing11!!( Ashish Rai )",
    "SXL": "countryCode",
    "Latp": "94",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Haaland 6",
    "Player_10": "Gakpo 5, EVE (A)",
    "Player_12": "Slot 10, EVE (A)",
    "Player_13": "Fabianski CHE (A)",
    "Player_14": "Kerkez 1",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Mykolenko 6, LIV (H)",
    "Player_5": "I.Sarr 3",
    "Player_6": "J.Murphy 8",
    "Player_3": "A\u00EFt-Nouri 7",
    "Player_4": "Aina 6",
    "Player_8": "Amad 2",
    "Player_9": "Palmer WHU (H)",
    "Player_15": "Coady 0"
  },
  {
    "manager_Name": "1,416( 2,188,891 ) TotalXfr : 27",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "countryCode",
    "Latp": "82",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Isak 2",
    "Player_10": "Wood 17",
    "Player_12": "Henderson 6",
    "Player_13": "J.Timber 1",
    "Player_14": "Dalot 1",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Konat\u00E9 6, EVE (A)",
    "Player_5": "Palmer WHU (H)",
    "Player_6": "Kluivert 2",
    "Player_3": "Burn 0",
    "Player_4": "Milenkovi\u0107 6",
    "Player_8": "B.Fernandes 1",
    "Player_9": "Ndiaye 7, LIV (H)",
    "Player_15": "Iroegbunam 1, LIV (H)"
  },
  {
    "manager_Name": "1,411( 2,296,991 ) TotalXfr : 23",
    "Teams": "FOMO7 FC( Chaje Lokam )",
    "SXL": "countryCode",
    "Latp": "79",
    "Player_1": "Pickford 9, LIV (H)",
    "Player_11": "Wood 17",
    "Player_10": "Ra\u00FAl 8",
    "Player_12": "Fabianski CHE (A)",
    "Player_13": "Bree 2",
    "Player_14": "Burgess 0",
    "Player_7": "Palmer WHU (H)",
    "Player_2": "Pedro Porro 6",
    "Player_5": "Luis D\u00EDaz 3, EVE (A)",
    "Player_6": "B.Fernandes 1",
    "Player_3": "Hall 1",
    "Player_4": "Gvardiol 0",
    "Player_8": "M.Salah 32, EVE (A)",
    "Player_9": "Isak 2",
    "Player_15": "Yarmoliuk 0"
  },
  {
    "manager_Name": "1,409( 2,345,445 ) TotalXfr : 24",
    "Teams": "GustavousGooner( Ashish Subba )",
    "SXL": "countryCode",
    "Latp": "82",
    "Player_1": "Sels 8",
    "Player_11": "Isak 2",
    "Player_10": "Wood 17",
    "Player_12": "Fabianski CHE (A)",
    "Player_13": "Kerkez 1",
    "Player_14": "Rogers 1",
    "Player_7": "Amad 2",
    "Player_2": "Gabriel 2",
    "Player_5": "M.Salah 32, EVE (A)",
    "Player_6": "Palmer WHU (H)",
    "Player_3": "Aina 6",
    "Player_4": "Pedro Porro 6",
    "Player_8": "Mbeumo 2",
    "Player_9": "Gakpo 5, EVE (A)",
    "Player_15": "Keane 0, LIV (H)"
  },
  {
    "manager_Name": "1,405( 2,430,319 ) TotalXfr : 20",
    "Teams": "Mersali( Bishal Rai )",
    "SXL": "countryCode",
    "Latp": "60",
    "Player_1": "Raya 3",
    "Player_11": "Isak 2",
    "Player_10": "Wissa 2",
    "Player_12": "Fabianski CHE (A)",
    "Player_13": "Milenkovi\u0107 6",
    "Player_14": "Castagne 2",
    "Player_7": "Mbeumo 2",
    "Player_2": "Hall 1",
    "Player_5": "Luis D\u00EDaz 3, EVE (A)",
    "Player_6": "M.Salah 32, EVE (A)",
    "Player_3": "Gabriel 2",
    "Player_4": "Aina 6",
    "Player_8": "Palmer WHU (H)",
    "Player_9": "Cunha 7",
    "Player_15": "Choudhury 0"
  },
  {
    "manager_Name": "1,398( 2,599,669 ) TotalXfr : 23",
    "Teams": "Imperial Blues FC( Saurabh Tamang )",
    "SXL": "countryCode",
    "Latp": "67",
    "Player_1": "Sels 8",
    "Player_11": "Isak 2",
    "Player_10": "Gakpo 5, EVE (A)",
    "Player_12": "Valdimarsson 1",
    "Player_13": "Wood 17",
    "Player_14": "Robinson 4",
    "Player_7": "J.Murphy 8",
    "Player_2": "Gabriel 2",
    "Player_5": "Rogers 1",
    "Player_6": "M.Salah 32, EVE (A)",
    "Player_3": "Hall 1",
    "Player_4": "Alexander-Arnold 6, EVE (A)",
    "Player_8": "Kluivert 2",
    "Player_9": "Palmer WHU (H)",
    "Player_15": "Faes 0"
  },
  {
    "manager_Name": "1,393( 2,711,578 ) TotalXfr : 20",
    "Teams": "Busby Baby( Regean Lama )",
    "SXL": "countryCode",
    "Latp": "81",
    "Player_1": "Henderson 6",
    "Player_11": "Ndiaye 7, LIV (H)",
    "Player_10": "N.Jackson WHU (H)",
    "Player_12": "Turner 0",
    "Player_13": "Semenyo 2",
    "Player_14": "A\u00EFt-Nouri 7",
    "Player_7": "Amad 2",
    "Player_2": "Colwill WHU (H)",
    "Player_5": "Palmer WHU (H)",
    "Player_6": "Rogers 1",
    "Player_3": "Mykolenko 6, LIV (H)",
    "Player_4": "Alexander-Arnold 6, EVE (A)",
    "Player_8": "M.Salah 48, EVE (A)",
    "Player_9": "Gakpo 5, EVE (A)",
    "Player_15": "Livramento 2"
  },
  {
    "manager_Name": "1,393( 2,720,675 ) TotalXfr : 25",
    "Teams": "\uFFFD Fields FC( Ravish Verma )",
    "SXL": "countryCode",
    "Latp": "91",
    "Player_1": "A.Becker 9, EVE (A)",
    "Player_11": "Wissa 2",
    "Player_10": "Isak 2",
    "Player_12": "Fabianski CHE (A)",
    "Player_13": "Colwill WHU (H)",
    "Player_14": "Enzo WHU (H)",
    "Player_7": "M.Salah 48, EVE (A)",
    "Player_2": "Alexander-Arnold 6, EVE (A)",
    "Player_5": "I.Sarr 3",
    "Player_6": "Palmer WHU (H)",
    "Player_3": "Digne 1",
    "Player_4": "Hall 1",
    "Player_8": "Mbeumo 2",
    "Player_9": "Wood 17",
    "Player_15": "O\u0027Shea 1"
  },
  {
    "manager_Name": "1,389( 2,808,956 ) TotalXfr : 22",
    "Teams": "ZilchExpectationsXI( Dipen Thapa )",
    "SXL": "countryCode",
    "Latp": "65",
    "Player_1": "Raya 3",
    "Player_11": "Wood 17",
    "Player_10": "Isak 2",
    "Player_12": "Flekken 0",
    "Player_13": "Sou\u010Dek CHE (A)",
    "Player_14": "Harwood-Bellis 1",
    "Player_7": "Mbeumo 2",
    "Player_2": "Hall 1",
    "Player_5": "M.Salah 32, EVE (A)",
    "Player_6": "Palmer WHU (H)",
    "Player_3": "Gvardiol 0",
    "Player_4": "Aina 6",
    "Player_8": "Rogers 1",
    "Player_9": "Watkins 1",
    "Player_15": "Young 1, LIV (H)"
  },
  {
    "manager_Name": "1,371( 3,229,484 ) TotalXfr : 17",
    "Teams": "PR11( pranam rai )",
    "SXL": "countryCode",
    "Latp": "64",
    "Player_1": "Raya 3",
    "Player_11": "Wood 17",
    "Player_10": "Jo\u00E3o Pedro 1",
    "Player_12": "Areola CHE (A)",
    "Player_13": "Smith Rowe 2",
    "Player_14": "Lewis 0",
    "Player_7": "Palmer WHU (H)",
    "Player_2": "Colwill WHU (H)",
    "Player_5": "Mbeumo 2",
    "Player_6": "Rogers 1",
    "Player_3": "Mazraoui 2",
    "Player_4": "Alexander-Arnold 6, EVE (A)",
    "Player_8": "M.Salah 32, EVE (A)",
    "Player_9": "N.Jackson WHU (H)",
    "Player_15": "Wan-Bissaka CHE (A)"
  },
  {
    "manager_Name": "1,371( 3,232,819 ) TotalXfr : 21",
    "Teams": "Darjeeling City( Ruben Pradhan )",
    "SXL": "countryCode",
    "Latp": "98",
    "Player_1": "Sels 8",
    "Player_11": "Isak 2",
    "Player_10": "Watkins 1",
    "Player_12": "S\u00E1nchez WHU (H)",
    "Player_13": "Elanga 13",
    "Player_14": "Chalobah WHU (H)",
    "Player_7": "J.Murphy 8",
    "Player_2": "Burn 0",
    "Player_5": "Palmer WHU (H)",
    "Player_6": "Gravenberch 2, EVE (A)",
    "Player_3": "Alexander-Arnold 6, EVE (A)",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "M.Salah 48, EVE (A)",
    "Player_9": "Wood 17",
    "Player_15": "Kerkez 1"
  },
  {
    "manager_Name": "1,366( 3,360,313 ) TotalXfr : 28",
    "Teams": "KungFuPandoos( Indrajeet Singh )",
    "SXL": "countryCode",
    "Latp": "40",
    "Player_1": "Henderson 6",
    "Player_11": "Haaland 12",
    "Player_10": "Foden 2",
    "Player_12": "S\u00E1nchez WHU (H)",
    "Player_13": "Ra\u00FAl 8",
    "Player_14": "Colwill WHU (H)",
    "Player_7": "Son 8",
    "Player_2": "Dalot 1",
    "Player_5": "Konat\u00E9 6, EVE (A)",
    "Player_6": "B.Fernandes 1",
    "Player_3": "Cash 0",
    "Player_4": "Burn 0",
    "Player_8": "Kluivert 2",
    "Player_9": "Mbeumo 2",
    "Player_15": "Vardy 1"
  },
  {
    "manager_Name": "1,353( 3,668,031 ) TotalXfr : 38",
    "Teams": "Busby Babes( Pema Lepcha )",
    "SXL": "countryCode",
    "Latp": "83",
    "Player_1": "S\u00E1nchez WHU (H)",
    "Player_11": "Isak 2",
    "Player_10": "Wood 17",
    "Player_12": "Muric 1",
    "Player_13": "Wan-Bissaka CHE (A)",
    "Player_14": "Semenyo 2",
    "Player_7": "Palmer WHU (H)",
    "Player_2": "Gvardiol 0",
    "Player_5": "Mazraoui 2",
    "Player_6": "Kluivert 2",
    "Player_3": "Hall 1",
    "Player_4": "Alexander-Arnold 6, EVE (A)",
    "Player_8": "M.Salah 48, EVE (A)",
    "Player_9": "Gakpo 5, EVE (A)",
    "Player_15": "Eze 1"
  },
  {
    "manager_Name": "1,352( 3,689,722 ) TotalXfr : 33",
    "Teams": "Comet FC( Pranesh Sharma )",
    "SXL": "countryCode",
    "Latp": "77",
    "Player_1": "S\u00E1nchez WHU (H)",
    "Player_11": "Gakpo 5, EVE (A)",
    "Player_10": "Isak 2",
    "Player_12": "Slot 10, EVE (A)",
    "Player_13": "Fabianski CHE (A)",
    "Player_14": "Kluivert 2",
    "Player_7": "Gordon 1",
    "Player_2": "Robinson 4",
    "Player_5": "Palmer WHU (H)",
    "Player_6": "Elanga 13",
    "Player_3": "Hall 1",
    "Player_4": "J.Timber 1",
    "Player_8": "M.Salah 32, EVE (A)",
    "Player_9": "Delap 8",
    "Player_15": "Emerson CHE (A)"
  },
  {
    "manager_Name": "1,300( 4,816,981 ) TotalXfr : 9",
    "Teams": "Renga FC( William Serto )",
    "SXL": "countryCode",
    "Latp": "62",
    "Player_1": "Fabianski CHE (A)",
    "Player_11": "Haaland 6",
    "Player_10": "Jo\u00E3o Pedro 1",
    "Player_12": "Flekken 0",
    "Player_13": "Faes 0",
    "Player_14": "B.Soumar\u00E9 2",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Gvardiol 0",
    "Player_5": "Robinson 4",
    "Player_6": "Rogers 1",
    "Player_3": "Alexander-Arnold 6, EVE (A)",
    "Player_4": "A\u00EFt-Nouri 7",
    "Player_8": "Martinelli 5",
    "Player_9": "Neto WHU (H)",
    "Player_15": "N.Jackson WHU (H)"
  },
  {
    "manager_Name": "1,289( 5,052,063 ) TotalXfr : 24",
    "Teams": "Hooligans \u00B0\u00B024( Pradhyumna Subba )",
    "SXL": "countryCode",
    "Latp": "66",
    "Player_1": "S\u00E1nchez WHU (H)",
    "Player_11": "Watkins 1",
    "Player_10": "Haaland 6",
    "Player_12": "Fabianski CHE (A)",
    "Player_13": "Van den Berg 1",
    "Player_14": "Aina 6",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Konsa 1",
    "Player_5": "A.Doucoure 8, LIV (H)",
    "Player_6": "Rogers 1",
    "Player_3": "Alexander-Arnold 6, EVE (A)",
    "Player_4": "Hall 1",
    "Player_8": "Luis D\u00EDaz 3, EVE (A)",
    "Player_9": "Ndiaye 7, LIV (H)",
    "Player_15": "Dibling 0"
  },
  {
    "manager_Name": "1,252( 5,770,828 ) TotalXfr : 23",
    "Teams": "Dany11( Avinash DAniel Khawas )",
    "SXL": "countryCode",
    "Latp": "59",
    "Player_1": "Sels 8",
    "Player_11": "Isak 2",
    "Player_10": "Watkins 1",
    "Player_12": "Turner 0",
    "Player_13": "Stewart 0",
    "Player_14": "Mazraoui 2",
    "Player_7": "Palmer WHU (H)",
    "Player_2": "Aina 6",
    "Player_5": "Kerkez 1",
    "Player_6": "M.Salah 32, EVE (A)",
    "Player_3": "Faes 0",
    "Player_4": "Virgil 5, EVE (A)",
    "Player_8": "Mbeumo 2",
    "Player_9": "Amad 2",
    "Player_15": "Choudhury 0"
  },
  {
    "manager_Name": "1,168( 7,240,242 ) TotalXfr : 29",
    "Teams": "HEROES11( Obed Hang Subba )",
    "SXL": "countryCode",
    "Latp": "84",
    "Player_1": "Onana 1",
    "Player_11": "Gakpo 5, EVE (A)",
    "Player_10": "Isak 2",
    "Player_12": "Bentley 0",
    "Player_13": "Emerson CHE (A)",
    "Player_14": "Hall 1",
    "Player_7": "M.Salah 32, EVE (A)",
    "Player_2": "Mykolenko 6, LIV (H)",
    "Player_5": "Amad 2",
    "Player_6": "Palmer WHU (H)",
    "Player_3": "Tarkowski 11, LIV (H)",
    "Player_4": "Virgil 5, EVE (A)",
    "Player_8": "Gana 3, LIV (H)",
    "Player_9": "Wood 17",
    "Player_15": "Nwaneri 6"
  }
];