var pcc = [
   {
      "PLAYERS":"Ramsdale",
      "PLAYERS_COUNT":"13",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Alexander-Arnold",
      "PLAYERS_COUNT":"18",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Livramento",
      "PLAYERS_COUNT":"19",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"James",
      "PLAYERS_COUNT":"14",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"White",
      "PLAYERS_COUNT":"7",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Benrahma",
      "PLAYERS_COUNT":"9",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Smith",
      "PLAYERS_COUNT":"13",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Salah",
      "PLAYERS_COUNT":"31",
      "CAPTAIN_COUNT":"20",
      "CAPTAINED_MGR":"Sahil Lampard , Saurabh Tamang , Pranesh Sharma , Sanjeev Kumar , Kushal Sahota , Ashim Lama , Vivek Pradhan , Sibin _ , Omkar Subba , Rishi Thulung , Dipen Thapa , Nishant Singh , Ashish Subba , Raj Kanango , Gaurav Shrestha , Bishal Rai , RAJIYUNG Sun , AVIJIT DAS , Abhijeet Singh , SATYAM RAI"
   },
   {
      "PLAYERS":"Greenwood",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Vardy",
      "PLAYERS_COUNT":"15",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Saint-Maximin",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Sánchez",
      "PLAYERS_COUNT":"9",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Maupay",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Townsend",
      "PLAYERS_COUNT":"3",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Marçal",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Guaita",
      "PLAYERS_COUNT":"4",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Cancelo",
      "PLAYERS_COUNT":"19",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Duffy",
      "PLAYERS_COUNT":"11",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Gallagher",
      "PLAYERS_COUNT":"16",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Cornet",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Ronaldo",
      "PLAYERS_COUNT":"9",
      "CAPTAIN_COUNT":"4",
      "CAPTAINED_MGR":"Kumar Anku , Regean Lama , Ashish Rai , PRAYAS BAJGAI"
   },
   {
      "PLAYERS":"Gray",
      "PLAYERS_COUNT":"4",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Omobamidele",
      "PLAYERS_COUNT":"3",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Archer",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Schmeichel",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Dier",
      "PLAYERS_COUNT":"3",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Jota",
      "PLAYERS_COUNT":"5",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Pukki",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Foster",
      "PLAYERS_COUNT":"18",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Bissouma",
      "PLAYERS_COUNT":"6",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Amartey",
      "PLAYERS_COUNT":"4",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"de",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Shaw",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Son",
      "PLAYERS_COUNT":"11",
      "CAPTAIN_COUNT":"1",
      "CAPTAINED_MGR":"pranam rai"
   },
   {
      "PLAYERS":"Mbeumo",
      "PLAYERS_COUNT":"9",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Raphinha",
      "PLAYERS_COUNT":"11",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Kane",
      "PLAYERS_COUNT":"10",
      "CAPTAIN_COUNT":"6",
      "CAPTAINED_MGR":"Indrajeet Singh , Rohan Rai , Ravish Verma , Prayash Thapa , Tenzing Ninjey , Harsh Raval"
   },
   {
      "PLAYERS":"Alonso",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Hwang",
      "PLAYERS_COUNT":"10",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"McCarthy",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Reguilón",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Walker",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Antonio",
      "PLAYERS_COUNT":"20",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Bergwijn",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Tomiyasu",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Moder",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Mendy",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Tsimikas",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Rüdiger",
      "PLAYERS_COUNT":"5",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Havertz",
      "PLAYERS_COUNT":"4",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Pinnock",
      "PLAYERS_COUNT":"3",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Veltman",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Scarlett",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Dias",
      "PLAYERS_COUNT":"7",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Manquillo",
      "PLAYERS_COUNT":"3",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Bernardo",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Højbjerg",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Raya",
      "PLAYERS_COUNT":"3",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Dennis",
      "PLAYERS_COUNT":"3",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Ødegaard",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Lloris",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Jansson",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Chilwell",
      "PLAYERS_COUNT":"13",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Ward",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Gilmour",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Ederson",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Foden",
      "PLAYERS_COUNT":"9",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Alisson",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Toney",
      "PLAYERS_COUNT":"6",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Tierney",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Coady",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Söyüncü",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Saka",
      "PLAYERS_COUNT":"3",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Jiménez",
      "PLAYERS_COUNT":"5",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Digne",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Douglas",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Christensen",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Aubameyang",
      "PLAYERS_COUNT":"3",
      "CAPTAIN_COUNT":"1",
      "CAPTAINED_MGR":"prabin kumar"
   },
   {
      "PLAYERS":"Steele",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Williams",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Allan",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Ings",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"McArthur",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Ayling",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Obafemi",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Laporte",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Zaha",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Brownhill",
      "PLAYERS_COUNT":"7",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Martínez",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Cresswell",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Jesus",
      "PLAYERS_COUNT":"2",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Richardson",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Matip",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Steer",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Krul",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Rodrigo",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Sarr",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Emerson",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Normann",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   },
   {
      "PLAYERS":"Davis",
      "PLAYERS_COUNT":"1",
      "CAPTAIN_COUNT":"0",
      "CAPTAINED_MGR":""
   }
]