var s = [
  {
    "manager_Name": "995( 18,738 ) TotalXfr : 13",
    "Teams": "Lorrainesson( Lorraine Busuttil )",
    "SXL": "Malta",
    "Latp": "67",
    "Player_1": "Sels\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Strand Larsen\r 2",
    "Player_12": "Lumley\r 3",
    "Player_13": "Gabriel\r 0",
    "Player_14": "Okoli\r 0",
    "Player_7": "Saka\r 2",
    "Player_2": "Hall\r 1",
    "Player_5": "Bowen\r 12",
    "Player_6": "Palmer\r 36",
    "Player_3": "A\u00EFt-Nouri\r 4",
    "Player_4": "J.Timber\r 2",
    "Player_8": "Semenyo\r 2",
    "Player_9": "N.Jackson\r 2",
    "Player_15": "M.Salah\r -"
  },
  {
    "manager_Name": "954( 149,454 ) TotalXfr : 14",
    "Teams": "Udogie\u0027s Doggies( Claude Taliana )",
    "SXL": "Malta",
    "Latp": "60",
    "Player_1": "Flekken\r 3",
    "Player_11": "Haaland\r 14",
    "Player_10": "Strand Larsen\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "M.Salah\r -",
    "Player_14": "Young\r -",
    "Player_7": "Palmer\r 18",
    "Player_2": "J.Timber\r 2",
    "Player_5": "Amad\r 5",
    "Player_6": "Rogers\r 2",
    "Player_3": "Pedro Porro\r 3",
    "Player_4": "Dalot\r 1",
    "Player_8": "Georginio\r 2",
    "Player_9": "Wood\r 8",
    "Player_15": "Aina\r 1"
  },
  {
    "manager_Name": "954( 150,842 ) TotalXfr : 14",
    "Teams": "The Bees( Tove Ronneb\u00E4ck )",
    "SXL": "Malta",
    "Latp": "70",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 8",
    "Player_10": "Wissa\r 7",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "M.Salah\r -",
    "Player_14": "Gomez\r -",
    "Player_7": "Palmer\r 36",
    "Player_2": "Harwood-Bellis\r 2",
    "Player_5": "Saka\r 2",
    "Player_6": "Enzo\r 9",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "Gabriel\r 0",
    "Player_8": "Rogers\r 2",
    "Player_9": "Cunha\r 1",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "931( 361,282 ) TotalXfr : 14",
    "Teams": "NoHopeFC( John Maguire )",
    "SXL": "Malta",
    "Latp": "81",
    "Player_1": "Flekken\r 3",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Cunha\r 1",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "M.Salah\r -",
    "Player_14": "Robinson\r 1",
    "Player_7": "Palmer\r 36",
    "Player_2": "Harwood-Bellis\r 2",
    "Player_5": "Saliba\r 9",
    "Player_6": "Mbeumo\r 13",
    "Player_3": "Davis\r 1",
    "Player_4": "Digne\r 1",
    "Player_8": "B.Fernandes\r 9",
    "Player_9": "Maddison\r 4",
    "Player_15": "Welbeck\r 1"
  },
  {
    "manager_Name": "930( 369,636 ) TotalXfr : 14",
    "Teams": "Fantasikonungen( Albin Jonsson )",
    "SXL": "Malta",
    "Latp": "59",
    "Player_1": "Fabianski\r 2",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Delap\r 1",
    "Player_12": "Jos\u00E9 S\u00E1\r 0",
    "Player_13": "M.Salah\r -",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Semenyo\r 2",
    "Player_2": "A\u00EFt-Nouri\r 4",
    "Player_5": "Saka\r 2",
    "Player_6": "Palmer\r 18",
    "Player_3": "Hall\r 1",
    "Player_4": "Digne\r 1",
    "Player_8": "Bowen\r 24",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Konat\u00E9\r -"
  },
  {
    "manager_Name": "927( 412,764 ) TotalXfr : 16",
    "Teams": "klopp notch( Tobias Nocke )",
    "SXL": "Sweden",
    "Latp": "74",
    "Player_1": "Verbruggen\r 1",
    "Player_11": "Solanke\r 6",
    "Player_10": "Watkins\r 1",
    "Player_12": "Kelleher\r -",
    "Player_13": "M.Salah\r -",
    "Player_14": "Gomez\r -",
    "Player_7": "\u00D8degaard\r 2",
    "Player_2": "Digne\r 1",
    "Player_5": "Palmer\r 36",
    "Player_6": "Mitoma\r 2",
    "Player_3": "Van den Berg\r 0",
    "Player_4": "Estupi\u00F1an\r 5",
    "Player_8": "Bowen\r 12",
    "Player_9": "Ra\u00FAl\r 8",
    "Player_15": "Harwood-Bellis\r 2"
  },
  {
    "manager_Name": "923( 464,812 ) TotalXfr : 12",
    "Teams": "Los Blancos( Eamonn Mifsud )",
    "SXL": "Malta",
    "Latp": "66",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 1",
    "Player_10": "Isak\r 8",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Gabriel\r 0",
    "Player_14": "Van den Berg\r 0",
    "Player_7": "Rogers\r 2",
    "Player_2": "Konsa\r 8",
    "Player_5": "Saka\r 4",
    "Player_6": "Palmer\r 18",
    "Player_3": "A\u00EFt-Nouri\r 4",
    "Player_4": "Lewis\r 4",
    "Player_8": "Mbeumo\r 13",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "M.Salah\r -"
  },
  {
    "manager_Name": "922( 486,597 ) TotalXfr : 15",
    "Teams": "FC Pek( Erik Lindberg )",
    "SXL": "Sweden",
    "Latp": "37",
    "Player_1": "Henderson\r 1",
    "Player_11": "Wissa\r 7",
    "Player_10": "N.Jackson\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Gabriel\r 0",
    "Player_14": "M.Salah\r -",
    "Player_7": "Mitoma\r 2",
    "Player_2": "Gvardiol\r 1",
    "Player_5": "Faes\r 1",
    "Player_6": "\u00D8degaard\r 2",
    "Player_3": "Digne\r 1",
    "Player_4": "A\u00EFt-Nouri\r 4",
    "Player_8": "Rogers\r 2",
    "Player_9": "Haaland\r 14",
    "Player_15": "Winks\r 0"
  },
  {
    "manager_Name": "921( 492,892 ) TotalXfr : 10",
    "Teams": "Kinder Mbeumo( Gerson Seguna )",
    "SXL": "Malta",
    "Latp": "67",
    "Player_1": "Raya\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r 1",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Alexander-Arnold\r -",
    "Player_14": "M.Salah\r -",
    "Player_7": "Saka\r 2",
    "Player_2": "O\u0027Shea\r 1",
    "Player_5": "Palmer\r 36",
    "Player_6": "Mitoma\r 2",
    "Player_3": "A\u00EFt-Nouri\r 4",
    "Player_4": "Milenkovi\u0107\r 7",
    "Player_8": "Rogers\r 2",
    "Player_9": "Wood\r 8",
    "Player_15": "Hall\r 1"
  },
  {
    "manager_Name": "913( 626,047 ) TotalXfr : 13",
    "Teams": "Lallish United( Melwin Holst )",
    "SXL": "Sweden",
    "Latp": "62",
    "Player_1": "Raya\r 2",
    "Player_11": "Welbeck\r 1",
    "Player_10": "Cunha\r 1",
    "Player_12": "Fabianski\r 2",
    "Player_13": "M.Salah\r -",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Palmer\r 36",
    "Player_2": "Van Hecke\r 1",
    "Player_5": "Amad\r 5",
    "Player_6": "Rogers\r 2",
    "Player_3": "Dalot\r 1",
    "Player_4": "A\u00EFt-Nouri\r 4",
    "Player_8": "Son\r 7",
    "Player_9": "N.Jackson\r 2",
    "Player_15": "Davis\r 1"
  },
  {
    "manager_Name": "910( 684,689 ) TotalXfr : 13",
    "Teams": "Ajax CT( Dimitrios Siderakis )",
    "SXL": "Malta",
    "Latp": "53",
    "Player_1": "Sels\r 2",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Watkins\r 1",
    "Player_12": "S\u00E1nchez\r 0",
    "Player_13": "M.Salah\r -",
    "Player_14": "Luis D\u00EDaz\r -",
    "Player_7": "Palmer\r 18",
    "Player_2": "Saliba\r 9",
    "Player_5": "Mazraoui\r 1",
    "Player_6": "Carvalho\r 2",
    "Player_3": "Pedro Porro\r 3",
    "Player_4": "Gu\u00E9hi\r 1",
    "Player_8": "Mbeumo\r 13",
    "Player_9": "Welbeck\r 1",
    "Player_15": "Murillo\r 1"
  },
  {
    "manager_Name": "903( 824,168 ) TotalXfr : 15",
    "Teams": "MainooInTheBank( Thanasis Fouras )",
    "SXL": "Greece",
    "Latp": "55",
    "Player_1": "Henderson\r 1",
    "Player_11": "Haaland\r 14",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Matthews\r 0",
    "Player_13": "M.Salah\r -",
    "Player_14": "Winks\r 0",
    "Player_7": "Johnson\r 4",
    "Player_2": "Digne\r 1",
    "Player_5": "Faes\r 1",
    "Player_6": "Gordon\r 1",
    "Player_3": "A\u00EFt-Nouri\r 4",
    "Player_4": "Robinson\r 1",
    "Player_8": "Palmer\r 18",
    "Player_9": "Wood\r 8",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "893( 1,051,285 ) TotalXfr : 5",
    "Teams": "Nachos( Melvin Xuereb )",
    "SXL": "Malta",
    "Latp": "63",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Ra\u00FAl\r 8",
    "Player_10": "Haaland\r 14",
    "Player_12": "Areola\r 0",
    "Player_13": "M.Salah\r -",
    "Player_14": "Andersen\r 0",
    "Player_7": "Semenyo\r 2",
    "Player_2": "Saliba\r 9",
    "Player_5": "Faes\r 1",
    "Player_6": "Palmer\r 18",
    "Player_3": "Estupi\u00F1an\r 5",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Damsgaard\r 1",
    "Player_9": "Eze\r 2",
    "Player_15": "Calvert-Lewin\r -"
  },
  {
    "manager_Name": "892( 1,087,193 ) TotalXfr : 15",
    "Teams": "Tourinho FC( Alexis Touris )",
    "SXL": "Greece",
    "Latp": "51",
    "Player_1": "Martinez\r 6",
    "Player_11": "Wood\r 8",
    "Player_10": "Isak\r 8",
    "Player_12": "Henderson\r 1",
    "Player_13": "M.Salah\r -",
    "Player_14": "Adama\r 1",
    "Player_7": "Saka\r 4",
    "Player_2": "Pedro Porro\r 3",
    "Player_5": "Aina\r 1",
    "Player_6": "Johnson\r 4",
    "Player_3": "Dalot\r 1",
    "Player_4": "Gvardiol\r 1",
    "Player_8": "Mbeumo\r 13",
    "Player_9": "Evanilson\r 2",
    "Player_15": "Andersen\r 0"
  },
  {
    "manager_Name": "883( 1,328,109 ) TotalXfr : 14",
    "Teams": "Joga Bonito( Christophe Peixoto )",
    "SXL": "Hungary",
    "Latp": "60",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Isak\r 8",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Flekken\r 3",
    "Player_13": "M.Salah\r -",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Palmer\r 36",
    "Player_2": "Hall\r 1",
    "Player_5": "Faes\r 1",
    "Player_6": "Mitoma\r 2",
    "Player_3": "Colwill\r 1",
    "Player_4": "Pedro Porro\r 3",
    "Player_8": "Saka\r 2",
    "Player_9": "Evanilson\r 2",
    "Player_15": "Smith Rowe\r 1"
  },
  {
    "manager_Name": "880( 1,403,335 ) TotalXfr : 10",
    "Teams": "BienRayados( Luis Ricardo J\u00E1uregui V )",
    "SXL": "England",
    "Latp": "52",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Havertz\r 5",
    "Player_10": "Ra\u00FAl\r 8",
    "Player_12": "S\u00E1nchez\r 0",
    "Player_13": "J.Araujo\r 0",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Saka\r 2",
    "Player_2": "Murillo\r 1",
    "Player_5": "Palmer\r 18",
    "Player_6": "Madueke\r 2",
    "Player_3": "Pau\r 6",
    "Player_4": "Virgil\r -",
    "Player_8": "M.Salah\r -",
    "Player_9": "Duran\r 8",
    "Player_15": "McNeil\r -"
  },
  {
    "manager_Name": "877( 1,505,690 ) TotalXfr : 16",
    "Teams": "Salahvation Army( Tom Atkinson )",
    "SXL": "Malta",
    "Latp": "33",
    "Player_1": "Pope\r 1",
    "Player_11": "Jo\u00E3o Pedro\r 4",
    "Player_10": "Isak\r 8",
    "Player_12": "Slicker\r 0",
    "Player_13": "Gabriel\r 0",
    "Player_14": "Winks\r 0",
    "Player_7": "M.Salah\r -",
    "Player_2": "Lewis\r 4",
    "Player_5": "Saka\r 2",
    "Player_6": "Rogers\r 2",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "Collins\r 7",
    "Player_8": "Mitoma\r 2",
    "Player_9": "N.Jackson\r 2",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "875( 1,557,265 ) TotalXfr : 15",
    "Teams": "Ctrl Alt De Ligt( Marlon Vella )",
    "SXL": "Malta",
    "Latp": "73",
    "Player_1": "S\u00E1nchez\r 0",
    "Player_11": "Welbeck\r 1",
    "Player_10": "N.Jackson\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Faes\r 1",
    "Player_14": "M.Salah\r -",
    "Player_7": "Rogers\r 2",
    "Player_2": "A\u00EFt-Nouri\r 4",
    "Player_5": "Saka\r 2",
    "Player_6": "Mbeumo\r 13",
    "Player_3": "Lewis\r 4",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Palmer\r 36",
    "Player_9": "Ra\u00FAl\r 8",
    "Player_15": "Milenkovi\u0107\r 7"
  },
  {
    "manager_Name": "872( 1,644,662 ) TotalXfr : 11",
    "Teams": "Blue Core( Avinash Chatlani )",
    "SXL": "Malta",
    "Latp": "62",
    "Player_1": "Sels\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "N.Jackson\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Winks\r 0",
    "Player_14": "M.Salah\r -",
    "Player_7": "Mbeumo\r 13",
    "Player_2": "Lewis\r 4",
    "Player_5": "Harwood-Bellis\r 2",
    "Player_6": "Palmer\r 18",
    "Player_3": "Pedro Porro\r 3",
    "Player_4": "Aina\r 1",
    "Player_8": "Adama\r 1",
    "Player_9": "Haaland\r 14",
    "Player_15": "Vestergaard\r 1"
  },
  {
    "manager_Name": "871( 1,676,034 ) TotalXfr : 11",
    "Teams": "JDT Out( Filip Larsson )",
    "SXL": "Malta",
    "Latp": "41",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Welbeck\r 1",
    "Player_10": "Strand Larsen\r 2",
    "Player_12": "Flekken\r 3",
    "Player_13": "M.Salah\r -",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Rogers\r 2",
    "Player_2": "Lewis\r 4",
    "Player_5": "Semenyo\r 2",
    "Player_6": "\u00D8degaard\r 2",
    "Player_3": "Aina\r 1",
    "Player_4": "J.Timber\r 2",
    "Player_8": "B.Fernandes\r 9",
    "Player_9": "Haaland\r 14",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "867( 1,824,123 ) TotalXfr : 17",
    "Teams": "Im Sorry Nic Jackson( Jon Briscoe White )",
    "SXL": "Malta",
    "Latp": "45",
    "Player_1": "Sels\r 2",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Watkins\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Luis D\u00EDaz\r -",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Palmer\r 18",
    "Player_2": "A\u00EFt-Nouri\r 4",
    "Player_5": "Vestergaard\r 1",
    "Player_6": "Semenyo\r 2",
    "Player_3": "Pedro Porro\r 3",
    "Player_4": "Dalot\r 1",
    "Player_8": "Rogers\r 2",
    "Player_9": "Wood\r 8",
    "Player_15": "M.Salah\r -"
  },
  {
    "manager_Name": "865( 1,875,440 ) TotalXfr : 13",
    "Teams": "Gambit( Nicola Frasca )",
    "SXL": "Malta",
    "Latp": "45",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Haaland\r 14",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Pickford\r -",
    "Player_13": "Alexander-Arnold\r -",
    "Player_14": "Choudhury\r 0",
    "Player_7": "Smith Rowe\r 1",
    "Player_2": "Gvardiol\r 1",
    "Player_5": "Pedro Porro\r 3",
    "Player_6": "Yarmoliuk\r 2",
    "Player_3": "Greaves\r 0",
    "Player_4": "Martinez\r 1",
    "Player_8": "Palmer\r 18",
    "Player_9": "Ings\r 1",
    "Player_15": "M.Salah\r -"
  },
  {
    "manager_Name": "865( 1,887,763 ) TotalXfr : 17",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "India",
    "Latp": "60",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Cunha\r 1",
    "Player_10": "Armstrong\r 2",
    "Player_12": "Henderson\r 1",
    "Player_13": "M.Salah\r -",
    "Player_14": "W.Fofana\r 0",
    "Player_7": "Saka\r 2",
    "Player_2": "Dalot\r 1",
    "Player_5": "Faes\r 1",
    "Player_6": "B.Fernandes\r 18",
    "Player_3": "Saliba\r 9",
    "Player_4": "J.Timber\r 2",
    "Player_8": "Johnson\r 4",
    "Player_9": "Palmer\r 18",
    "Player_15": "Wheatley\r 0"
  },
  {
    "manager_Name": "863( 1,934,116 ) TotalXfr : 7",
    "Teams": "Matteo fc( Matteo Vella )",
    "SXL": "Malta",
    "Latp": "71",
    "Player_1": "Pope\r 1",
    "Player_11": "Watkins\r 1",
    "Player_10": "Isak\r 8",
    "Player_12": "Fabianski\r 2",
    "Player_13": "M.Salah\r -",
    "Player_14": "Johnson\r 4",
    "Player_7": "Mbeumo\r 26",
    "Player_2": "Gvardiol\r 1",
    "Player_5": "Hall\r 1",
    "Player_6": "Palmer\r 18",
    "Player_3": "Konsa\r 8",
    "Player_4": "Pedro Porro\r 3",
    "Player_8": "Rogers\r 2",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "863( 1,960,235 ) TotalXfr : 20",
    "Teams": "Biancoverde Utd 4.0( Michael Keramas )",
    "SXL": "Greece",
    "Latp": "50",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 1",
    "Player_10": "Delap\r 1",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "M.Salah\r -",
    "Player_14": "Aina\r 1",
    "Player_7": "Kulusevski\r 7",
    "Player_2": "Gvardiol\r 1",
    "Player_5": "B.Fernandes\r 9",
    "Player_6": "Palmer\r 18",
    "Player_3": "A\u00EFt-Nouri\r 4",
    "Player_4": "Robinson\r 1",
    "Player_8": "Saka\r 4",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Johnson\r 1"
  },
  {
    "manager_Name": "861( 1,998,285 ) TotalXfr : 0",
    "Teams": "KAMACIO FC( Francisco Camacho )",
    "SXL": "Malta",
    "Latp": "74",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Watkins\r 1",
    "Player_10": "Havertz\r 5",
    "Player_12": "Areola\r 0",
    "Player_13": "Foden\r 0",
    "Player_14": "Mykolenko\r -",
    "Player_7": "Gordon\r 1",
    "Player_2": "Hill\r 1",
    "Player_5": "Palmer\r 36",
    "Player_6": "Saka\r 2",
    "Player_3": "Saliba\r 9",
    "Player_4": "Pedro Porro\r 3",
    "Player_8": "Bowen\r 12",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "851( 2,377,381 ) TotalXfr : 19",
    "Teams": "Guglielmo( Jonas Megert )",
    "SXL": "Sweden",
    "Latp": "65",
    "Player_1": "Martinez\r 6",
    "Player_11": "Haaland\r 7",
    "Player_10": "Wood\r 8",
    "Player_12": "Turner\r 0",
    "Player_13": "Winks\r 0",
    "Player_14": "Quansah\r -",
    "Player_7": "Saka\r 4",
    "Player_2": "Pedro Porro\r 3",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "Johnson\r 4",
    "Player_3": "Konsa\r 8",
    "Player_4": "Lewis\r 4",
    "Player_8": "Palmer\r 18",
    "Player_9": "N.Jackson\r 2",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "845( 2,598,132 ) TotalXfr : 18",
    "Teams": "LxFxC( Ervin Rigo )",
    "SXL": "Malta",
    "Latp": "61",
    "Player_1": "Pope\r 1",
    "Player_11": "Isak\r 8",
    "Player_10": "Welbeck\r 1",
    "Player_12": "Jos\u00E9 S\u00E1\r 0",
    "Player_13": "M.Salah\r -",
    "Player_14": "Virgil\r -",
    "Player_7": "Palmer\r 18",
    "Player_2": "J.Timber\r 2",
    "Player_5": "Semenyo\r 4",
    "Player_6": "Johnson\r 4",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "Kerkez\r 2",
    "Player_8": "Mbeumo\r 13",
    "Player_9": "Wissa\r 7",
    "Player_15": "Pedro Porro\r 3"
  },
  {
    "manager_Name": "841( 2,742,921 ) TotalXfr : 16",
    "Teams": "ThereWeLand( Haykel Mansour )",
    "SXL": "Malta",
    "Latp": "60",
    "Player_1": "S\u00E1nchez\r 0",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Cunha\r 1",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Smith Rowe\r 1",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Kulusevski\r 7",
    "Player_2": "Collins\r 7",
    "Player_5": "Rashford\r 1",
    "Player_6": "Palmer\r 18",
    "Player_3": "A\u00EFt-Nouri\r 4",
    "Player_4": "Lewis\r 4",
    "Player_8": "\u00D8degaard\r 2",
    "Player_9": "Haaland\r 14",
    "Player_15": "Nedeljkovic\r 0"
  },
  {
    "manager_Name": "837( 2,901,009 ) TotalXfr : 17",
    "Teams": "Starship( Olumide Okedusi )",
    "SXL": "Estonia",
    "Latp": "43",
    "Player_1": "Raya\r 2",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Robinson\r 1",
    "Player_14": "M.Salah\r -",
    "Player_7": "Saka\r 4",
    "Player_2": "Burn\r 0",
    "Player_5": "Amad\r 5",
    "Player_6": "Palmer\r 18",
    "Player_3": "Pedro Porro\r 3",
    "Player_4": "A\u00EFt-Nouri\r 4",
    "Player_8": "Rogers\r 2",
    "Player_9": "Cunha\r 1",
    "Player_15": "Virgil\r -"
  },
  {
    "manager_Name": "836( 2,933,872 ) TotalXfr : 17",
    "Teams": "Gidia KK( Aggelos Flamiatos )",
    "SXL": "Greece",
    "Latp": "39",
    "Player_1": "Verbruggen\r 1",
    "Player_11": "Welbeck\r 1",
    "Player_10": "Delap\r 1",
    "Player_12": "Flekken\r 3",
    "Player_13": "McNeil\r -",
    "Player_14": "Virgil\r -",
    "Player_7": "Rogers\r 2",
    "Player_2": "Burn\r 0",
    "Player_5": "Murillo\r 1",
    "Player_6": "Mbeumo\r 13",
    "Player_3": "Robinson\r 1",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Maddison\r 4",
    "Player_9": "Haaland\r 14",
    "Player_15": "M.Salah\r -"
  },
  {
    "manager_Name": "834( 2,998,674 ) TotalXfr : 14",
    "Teams": "Red Tigers FC( George Vepkhvadze )",
    "SXL": "Georgia",
    "Latp": "53",
    "Player_1": "Pope\r 1",
    "Player_11": "Watkins\r 1",
    "Player_10": "Havertz\r 5",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Semenyo\r 2",
    "Player_14": "Greaves\r 0",
    "Player_7": "Palmer\r 18",
    "Player_2": "Van den Berg\r 0",
    "Player_5": "Saka\r 4",
    "Player_6": "Bowen\r 12",
    "Player_3": "Gusto\r 1",
    "Player_4": "Kerkez\r 2",
    "Player_8": "Gordon\r 1",
    "Player_9": "Isak\r 8",
    "Player_15": "Gabriel\r 0"
  },
  {
    "manager_Name": "833( 3,035,668 ) TotalXfr : 11",
    "Teams": "HUNdorito( Adam Rajki )",
    "SXL": "Hungary",
    "Latp": "39",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 7",
    "Player_10": "Cunha\r 1",
    "Player_12": "Turner\r 0",
    "Player_13": "Szoboszlai\r -",
    "Player_14": "Nelson\r 0",
    "Player_7": "Mitoma\r 4",
    "Player_2": "Pedro Porro\r 3",
    "Player_5": "Kerkez\r 2",
    "Player_6": "M.Salah\r -",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "Saliba\r 9",
    "Player_8": "Kluivert\r 2",
    "Player_9": "Wood\r 8",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "833( 3,046,211 ) TotalXfr : 14",
    "Teams": "Wan Utd( Mindaugas Grigaitis )",
    "SXL": "Lithuania",
    "Latp": "49",
    "Player_1": "Raya\r 2",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Havertz\r 10",
    "Player_12": "Vicario\r 0",
    "Player_13": "M.Salah\r -",
    "Player_14": "Pedro Porro\r 3",
    "Player_7": "Garnacho\r 4",
    "Player_2": "Kerkez\r 2",
    "Player_5": "Johnson\r 4",
    "Player_6": "Bowen\r 12",
    "Player_3": "Saliba\r 9",
    "Player_4": "Gvardiol\r 1",
    "Player_8": "Mitoma\r 2",
    "Player_9": "Cunha\r 1",
    "Player_15": "Aina\r 1"
  },
  {
    "manager_Name": "829( 3,195,829 ) TotalXfr : 13",
    "Teams": "Massilia( Daniel Borg )",
    "SXL": "Malta",
    "Latp": "54",
    "Player_1": "Martinez\r 6",
    "Player_11": "N.Jackson\r 4",
    "Player_10": "Cunha\r 1",
    "Player_12": "Flekken\r 3",
    "Player_13": "M.Salah\r -",
    "Player_14": "Virgil\r -",
    "Player_7": "Mbeumo\r 13",
    "Player_2": "Aina\r 1",
    "Player_5": "Johnson\r 4",
    "Player_6": "B.Fernandes\r 9",
    "Player_3": "A\u00EFt-Nouri\r 4",
    "Player_4": "Konsa\r 8",
    "Player_8": "Rogers\r 2",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Keane\r -"
  },
  {
    "manager_Name": "828( 3,235,831 ) TotalXfr : 15",
    "Teams": "FC Qvantas( Johan Hammarstrom )",
    "SXL": "Sweden",
    "Latp": "64",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 14",
    "Player_10": "Cunha\r 1",
    "Player_12": "Sels\r 2",
    "Player_13": "Wood\r 8",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Madueke\r 1",
    "Player_2": "Burn\r 0",
    "Player_5": "Johnson\r 4",
    "Player_6": "Mbeumo\r 13",
    "Player_3": "Saliba\r 9",
    "Player_4": "Faes\r 1",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "Palmer\r 18",
    "Player_15": "Keane\r -"
  },
  {
    "manager_Name": "828( 3,239,323 ) TotalXfr : 13",
    "Teams": "Crvena Zvezda( Dejan Mrdanov )",
    "SXL": "Malta",
    "Latp": "40",
    "Player_1": "Raya\r 2",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Wood\r 8",
    "Player_12": "Areola\r 0",
    "Player_13": "Luis D\u00EDaz\r -",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Hudson-Odoi\r 5",
    "Player_2": "Colwill\r 1",
    "Player_5": "Mbeumo\r 13",
    "Player_6": "Kluivert\r 4",
    "Player_3": "Digne\r 1",
    "Player_4": "Pedro Porro\r 3",
    "Player_8": "M.Salah\r -",
    "Player_9": "Cunha\r 1",
    "Player_15": "Tarkowski\r -"
  },
  {
    "manager_Name": "819( 3,606,252 ) TotalXfr : 15",
    "Teams": "\u0106umura\u0161i( Aleksandar Deletic )",
    "SXL": "Serbia",
    "Latp": "35",
    "Player_1": "Raya\r 2",
    "Player_11": "Zirkzee\r 1",
    "Player_10": "Ra\u00FAl\r 8",
    "Player_12": "S\u00E1nchez\r 0",
    "Player_13": "Virgil\r -",
    "Player_14": "M.Salah\r -",
    "Player_7": "Mbeumo\r 13",
    "Player_2": "Hall\r 1",
    "Player_5": "Saka\r 4",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Gu\u00E9hi\r 1",
    "Player_4": "Digne\r 1",
    "Player_8": "Mitoma\r 2",
    "Player_9": "Cunha\r 1",
    "Player_15": "Gabriel\r 0"
  },
  {
    "manager_Name": "818( 3,642,088 ) TotalXfr : 13",
    "Teams": "Rekegutt United( Eirik Presttun )",
    "SXL": "Malta",
    "Latp": "49",
    "Player_1": "S\u00E1nchez\r 0",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Haaland\r 14",
    "Player_12": "Henderson\r 1",
    "Player_13": "M.Salah\r -",
    "Player_14": "Dibling\r 2",
    "Player_7": "Madueke\r 1",
    "Player_2": "Faes\r 1",
    "Player_5": "A\u00EFt-Nouri\r 4",
    "Player_6": "Mbeumo\r 13",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "Dalot\r 1",
    "Player_8": "Garnacho\r 4",
    "Player_9": "Ra\u00FAl\r 8",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "817( 3,679,009 ) TotalXfr : 13",
    "Teams": "Hakuna Mateta( Jason Evans )",
    "SXL": "Malta",
    "Latp": "19",
    "Player_1": "Raya\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "N.Jackson\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Armstrong\r -",
    "Player_14": "Alexander-Arnold\r -",
    "Player_7": "Semenyo\r 2",
    "Player_2": "Burgess\r 4",
    "Player_5": "M.Salah\r -",
    "Player_6": "Mitoma\r 2",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "Gabriel\r 0",
    "Player_8": "Saka\r 2",
    "Player_9": "Watkins\r 2",
    "Player_15": "Thomas\r 0"
  },
  {
    "manager_Name": "813( 3,845,273 ) TotalXfr : 14",
    "Teams": "20x MU( John Tiltmann )",
    "SXL": "Malta",
    "Latp": "29",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Cunha\r 1",
    "Player_10": "Isak\r 8",
    "Player_12": "Martinez\r 6",
    "Player_13": "Alexander-Arnold\r -",
    "Player_14": "McNeil\r -",
    "Player_7": "Madueke\r 1",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Saka\r 4",
    "Player_6": "Enzo\r 9",
    "Player_3": "Robinson\r 1",
    "Player_4": "Digne\r 1",
    "Player_8": "M.Salah\r -",
    "Player_9": "Welbeck\r 1",
    "Player_15": "Keane\r -"
  },
  {
    "manager_Name": "808( 4,039,106 ) TotalXfr : 7",
    "Teams": "St Peters FC( Clayton Borda )",
    "SXL": "Malta",
    "Latp": "58",
    "Player_1": "Pope\r 1",
    "Player_11": "Mateta\r 2",
    "Player_10": "Haaland\r 14",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Andersen\r 0",
    "Player_14": "Chiwome\r 0",
    "Player_7": "Palmer\r 18",
    "Player_2": "Burn\r 0",
    "Player_5": "B.Fernandes\r 9",
    "Player_6": "Bruno G.\r 2",
    "Player_3": "Konsa\r 8",
    "Player_4": "De Ligt\r 1",
    "Player_8": "Saka\r 2",
    "Player_9": "Smith Rowe\r 1",
    "Player_15": "Kristiansen\r 1"
  },
  {
    "manager_Name": "806( 4,128,836 ) TotalXfr : 14",
    "Teams": "FC Lokomotiv Sliema( Philip H\u00E5kansson )",
    "SXL": "Malta",
    "Latp": "37",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 14",
    "Player_10": "Solanke\r 6",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "M.Salah\r -",
    "Player_14": "Virgil\r -",
    "Player_7": "Neto\r 1",
    "Player_2": "Harwood-Bellis\r 2",
    "Player_5": "Johnson\r 4",
    "Player_6": "Semenyo\r 2",
    "Player_3": "Mazraoui\r 1",
    "Player_4": "Romero\r 1",
    "Player_8": "Rogers\r 2",
    "Player_9": "Strand Larsen\r 2",
    "Player_15": "Gabriel\r 0"
  },
  {
    "manager_Name": "805( 4,177,627 ) TotalXfr : 14",
    "Teams": "Cursed Technique( Ini Etienam )",
    "SXL": "Estonia",
    "Latp": "43",
    "Player_1": "Flekken\r 3",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Wood\r 16",
    "Player_12": "Pickford\r -",
    "Player_13": "McNeil\r -",
    "Player_14": "Virgil\r -",
    "Player_7": "Luis D\u00EDaz\r -",
    "Player_2": "Digne\r 1",
    "Player_5": "Martinez\r 1",
    "Player_6": "Mbeumo\r 13",
    "Player_3": "Pedro Porro\r 3",
    "Player_4": "Aina\r 1",
    "Player_8": "Saka\r 2",
    "Player_9": "Cunha\r 1",
    "Player_15": "M.Salah\r -"
  },
  {
    "manager_Name": "802( 4,293,923 ) TotalXfr : 12",
    "Teams": "Rolling Fernander( Adam Ruggier )",
    "SXL": "Malta",
    "Latp": "43",
    "Player_1": "Raya\r 2",
    "Player_11": "Wheatley\r 0",
    "Player_10": "Haaland\r 14",
    "Player_12": "Turner\r 0",
    "Player_13": "Konat\u00E9\r -",
    "Player_14": "Barco\r 0",
    "Player_7": "Smith Rowe\r 1",
    "Player_2": "Harwood-Bellis\r 2",
    "Player_5": "Palmer\r 18",
    "Player_6": "Semenyo\r 2",
    "Player_3": "De Ligt\r 1",
    "Player_4": "Gabriel\r 0",
    "Player_8": "Yarmoliuk\r 2",
    "Player_9": "Welbeck\r 1",
    "Player_15": "M.Salah\r -"
  },
  {
    "manager_Name": "800( 4,360,511 ) TotalXfr : 0",
    "Teams": "Thebackstreetmoyes( Dave Clarke )",
    "SXL": "Ireland",
    "Latp": "45",
    "Player_1": "Raya\r 2",
    "Player_11": "Watkins\r 1",
    "Player_10": "Isak\r 16",
    "Player_12": "Bettinelli\r 0",
    "Player_13": "Alexander-Arnold\r -",
    "Player_14": "Cash\r 0",
    "Player_7": "B.Fernandes\r 9",
    "Player_2": "Burn\r 0",
    "Player_5": "Eze\r 2",
    "Player_6": "Saka\r 2",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "Saliba\r 9",
    "Player_8": "Mainoo\r 2",
    "Player_9": "Cunha\r 1",
    "Player_15": "Diogo J.\r -"
  },
  {
    "manager_Name": "797( 4,493,840 ) TotalXfr : 8",
    "Teams": "FC Why-Do-I-Bother( Frode Danielsen )",
    "SXL": "Malta",
    "Latp": "55",
    "Player_1": "Raya\r 2",
    "Player_11": "Strand Larsen\r 2",
    "Player_10": "Haaland\r 7",
    "Player_12": "Turner\r 0",
    "Player_13": "Tuanzebe\r 0",
    "Player_14": "Marsh\r 0",
    "Player_7": "\u00D8degaard\r 2",
    "Player_2": "Gvardiol\r 1",
    "Player_5": "Yarmoliuk\r 2",
    "Player_6": "M.Salah\r -",
    "Player_3": "Mazraoui\r 1",
    "Player_4": "Vestergaard\r 1",
    "Player_8": "Palmer\r 36",
    "Player_9": "Joelinton\r 1",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "784( 5,019,797 ) TotalXfr : 6",
    "Teams": "Korta All Stars( Magnus Hammerstad )",
    "SXL": "Malta",
    "Latp": "60",
    "Player_1": "Raya\r 2",
    "Player_11": "Watkins\r 1",
    "Player_10": "Vardy\r 12",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Enzo\r 9",
    "Player_14": "Alexander-Arnold\r -",
    "Player_7": "Kulusevski\r 7",
    "Player_2": "Dalot\r 1",
    "Player_5": "Palmer\r 18",
    "Player_6": "Semenyo\r 2",
    "Player_3": "Robinson\r 1",
    "Player_4": "Burn\r 0",
    "Player_8": "Rogers\r 2",
    "Player_9": "Haaland\r 14",
    "Player_15": "Gabriel\r 0"
  },
  {
    "manager_Name": "780( 5,175,747 ) TotalXfr : 2",
    "Teams": "Sparta( Andrew Spiteri )",
    "SXL": "Malta",
    "Latp": "27",
    "Player_1": "Raya\r 2",
    "Player_11": "Havertz\r 5",
    "Player_10": "Isak\r 16",
    "Player_12": "Steele\r 0",
    "Player_13": "M.Salah\r -",
    "Player_14": "Zinchenko\r 0",
    "Player_7": "Foden\r 0",
    "Player_2": "Alexander-Arnold\r -",
    "Player_5": "Tielemans\r 1",
    "Player_6": "Nkunku\r 1",
    "Player_3": "Andersen\r 0",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Diogo J.\r -",
    "Player_9": "Welbeck\r 1",
    "Player_15": "Cash\r 0"
  },
  {
    "manager_Name": "780( 5,185,435 ) TotalXfr : 10",
    "Teams": "kabana( Sebastian Agius )",
    "SXL": "Malta",
    "Latp": "53",
    "Player_1": "Raya\r 2",
    "Player_11": "Welbeck\r 1",
    "Player_10": "Watkins\r 1",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Alexander-Arnold\r -",
    "Player_14": "Luis D\u00EDaz\r -",
    "Player_7": "Smith Rowe\r 1",
    "Player_2": "Robinson\r 1",
    "Player_5": "Pedro Porro\r 3",
    "Player_6": "Palmer\r 18",
    "Player_3": "Saliba\r 9",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Rogers\r 2",
    "Player_9": "Haaland\r 14",
    "Player_15": "Ugochukwu\r 0"
  }
];