var s = [
  {
    "manager_Name": "924( 325,410 ) TotalXfr : 13",
    "Teams": "WMB( Raj Kanango )",
    "SXL": "India",
    "Latp": "60",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Cunha\r 1",
    "Player_10": "Wood\r 8",
    "Player_12": "Kelleher\r -",
    "Player_13": "Alexander-Arnold\r -",
    "Player_14": "M.Salah\r -",
    "Player_7": "Saka\r 4",
    "Player_2": "Pedro Porro\r 3",
    "Player_5": "Palmer\r 18",
    "Player_6": "Rogers\r 2",
    "Player_3": "A\u00EFt-Nouri\r 4",
    "Player_4": "Justin\r 1",
    "Player_8": "B.Fernandes\r 9",
    "Player_9": "Ra\u00FAl\r 8",
    "Player_15": "Keane\r -"
  },
  {
    "manager_Name": "872( 1,385,955 ) TotalXfr : 16",
    "Teams": "Weightloss Coach( Abhijeet Singh )",
    "SXL": "India",
    "Latp": "51",
    "Player_1": "Flekken\r 3",
    "Player_11": "Cunha\r 1",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Greaves\r 0",
    "Player_14": "McNeil\r -",
    "Player_7": "Palmer\r 18",
    "Player_2": "Lewis\r 4",
    "Player_5": "Faes\r 1",
    "Player_6": "Saka\r 4",
    "Player_3": "Gabriel\r 0",
    "Player_4": "Konsa\r 8",
    "Player_8": "Semenyo\r 2",
    "Player_9": "Wood\r 8",
    "Player_15": "M.Salah\r -"
  },
  {
    "manager_Name": "865( 1,586,036 ) TotalXfr : 13",
    "Teams": "yoo( Nishant Singh )",
    "SXL": "India",
    "Latp": "35",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r 1",
    "Player_12": "S\u00E1nchez\r 0",
    "Player_13": "Mbeumo\r 13",
    "Player_14": "Konsa\r 8",
    "Player_7": "M.Salah\r -",
    "Player_2": "Gabriel\r 0",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "Saka\r 2",
    "Player_3": "Alexander-Arnold\r -",
    "Player_4": "Justin\r 1",
    "Player_8": "Palmer\r 18",
    "Player_9": "Ra\u00FAl\r 8",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "861( 1,725,814 ) TotalXfr : 16",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "India",
    "Latp": "59",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Cunha\r 1",
    "Player_10": "B.Fernandes\r 18",
    "Player_12": "Henderson\r 1",
    "Player_13": "Armstrong\r 2",
    "Player_14": "W.Fofana\r 0",
    "Player_7": "Saka\r 2",
    "Player_2": "J.Timber\r 2",
    "Player_5": "Dalot\r 1",
    "Player_6": "Johnson\r 4",
    "Player_3": "Faes\r 1",
    "Player_4": "Saliba\r 10",
    "Player_8": "M.Salah\r -",
    "Player_9": "Palmer\r 18",
    "Player_15": "Wheatley\r 0"
  },
  {
    "manager_Name": "846( 2,227,835 ) TotalXfr : 12",
    "Teams": "Bihar 11( Sanjeev Kumar )",
    "SXL": "India",
    "Latp": "43",
    "Player_1": "Onana\r 1",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "N.Jackson\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Smith Rowe\r 1",
    "Player_14": "Robinson\r 1",
    "Player_7": "Johnson\r 4",
    "Player_2": "Gabriel\r 0",
    "Player_5": "Palmer\r 18",
    "Player_6": "M.Salah\r -",
    "Player_3": "J.Timber\r 2",
    "Player_4": "A\u00EFt-Nouri\r 4",
    "Player_8": "Semenyo\r 2",
    "Player_9": "Isak\r 8",
    "Player_15": "O\u0027Shea\r 1"
  },
  {
    "manager_Name": "757( 5,814,273 ) TotalXfr : 12",
    "Teams": "Danapur United( Nitesh Kumar Singh )",
    "SXL": "India",
    "Latp": "57",
    "Player_1": "Flekken\r 3",
    "Player_11": "Watkins\r 1",
    "Player_10": "Haaland\r 7",
    "Player_12": "King\r 0",
    "Player_13": "Amo-Ameyaw\r 0",
    "Player_14": "McNeil\r -",
    "Player_7": "Garnacho\r 4",
    "Player_2": "Dalot\r 1",
    "Player_5": "Aina\r 1",
    "Player_6": "Palmer\r 36",
    "Player_3": "Alexander-Arnold\r -",
    "Player_4": "R\u00FAben\r 1",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "Mateta\r 2",
    "Player_15": "Keane\r -"
  },
  {
    "manager_Name": "628( 9,043,712 ) TotalXfr : 0",
    "Teams": "Prabin Singh( Prabin Singh )",
    "SXL": "India",
    "Latp": "23",
    "Player_1": "Ederson M.\r 0",
    "Player_11": "Isak\r 8",
    "Player_10": "Darwin\r -",
    "Player_12": "A.Becker\r -",
    "Player_13": "Gvardiol\r 1",
    "Player_14": "Eze\r 2",
    "Player_7": "Sterling\r 0",
    "Player_2": "Walker\r 1",
    "Player_5": "Virgil\r -",
    "Player_6": "Martinelli\r 0",
    "Player_3": "Gabriel\r 0",
    "Player_4": "Calafiori\r 0",
    "Player_8": "Mbeumo\r 13",
    "Player_9": "Rashford\r 1",
    "Player_15": "Mateta\r 2"
  }
];