var s = [
  {
    "manager_Name": "1848227",
    "Teams": "PUFC",
    "SXL": "IN",
    "Latp": "108",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "McNeil\r 15",
    "Player_12": "Slicker\r 0",
    "Player_13": "Wood\r 2",
    "Player_14": "Pedro Porro\r 5",
    "Player_7": "Sancho\r 9",
    "Player_2": "Romero\r 6",
    "Player_5": "Robinson\r 7",
    "Player_6": "Rogers\r 7",
    "Player_3": "Saliba\r 0",
    "Player_4": "Martinez\r 0",
    "Player_8": "Palmer\r 50",
    "Player_9": "M.Salah\r 10",
    "Player_15": "Cannon\r 0"
  },
  {
    "manager_Name": "4307659",
    "Teams": "Injury fc",
    "SXL": "IN",
    "Latp": "87",
    "Player_1": "Flekken\r 2",
    "Player_11": "N.Jackson\r 5",
    "Player_10": "Ra\u00FAl\r 9",
    "Player_12": "Martinez\r 2",
    "Player_13": "Robinson\r 7",
    "Player_14": "Murillo\r 1",
    "Player_7": "Palmer\r 50",
    "Player_2": "Colwill\r 1",
    "Player_5": "Saka\r 3",
    "Player_6": "Luis D\u00EDaz\r 2",
    "Player_3": "Virgil\r 2",
    "Player_4": "Digne\r 0",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Smith Rowe\r 3",
    "Player_15": "Wood\r 2"
  },
  {
    "manager_Name": "1063426",
    "Teams": "\u20ACze Mone\u00A5",
    "SXL": "IN",
    "Latp": "67",
    "Player_1": "Pope\r 3",
    "Player_11": "N.Jackson\r 10",
    "Player_10": "Haaland\r 2",
    "Player_12": "Gauci\r 0",
    "Player_13": "Winks\r 2",
    "Player_14": "Livramento\r 1",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Konsa\r 1",
    "Player_5": "Smith Rowe\r 3",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Robinson\r 7",
    "Player_4": "Lewis\r 2",
    "Player_8": "Palmer\r 25",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Bednarek\r 1"
  },
  {
    "manager_Name": "319175",
    "Teams": "Old Havertz Kai Hard",
    "SXL": "IN",
    "Latp": "79",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Havertz\r 6",
    "Player_12": "Steele\r 0",
    "Player_13": "Welbeck\r 2",
    "Player_14": "Lewis\r 2",
    "Player_7": "Saka\r 3",
    "Player_2": "Konsa\r 1",
    "Player_5": "Smith Rowe\r 3",
    "Player_6": "Luis D\u00EDaz\r 2",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Aina\r 2",
    "Player_8": "Palmer\r 50",
    "Player_9": "Rogers\r 7",
    "Player_15": "Robinson\r 7"
  },
  {
    "manager_Name": "178964",
    "Teams": "Jeffrey Palmer",
    "SXL": "IN",
    "Latp": "89",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Watkins\r 22",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Faes\r 0",
    "Player_14": "Johnson\r 0",
    "Player_7": "Palmer\r 25",
    "Player_2": "Konat\u00E9\r 7",
    "Player_5": "Rogers\r 7",
    "Player_6": "Smith Rowe\r 3",
    "Player_3": "Saliba\r 0",
    "Player_4": "Lewis\r 2",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Evanilson\r 9",
    "Player_15": "Choudhury\r 0"
  },
  {
    "manager_Name": "7346332",
    "Teams": "FC Vaazha",
    "SXL": "IN",
    "Latp": "73",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Calvert-Lewin\r 1",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Ra\u00FAl\r 9",
    "Player_14": "Harwood-Bellis\r 7",
    "Player_7": "Palmer\r 25",
    "Player_2": "Konsa\r 1",
    "Player_5": "Saka\r 3",
    "Player_6": "M.Salah\r 20",
    "Player_3": "Robinson\r 7",
    "Player_4": "Lewis\r 2",
    "Player_8": "Smith Rowe\r 3",
    "Player_9": "Rogers\r 7",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "8236028",
    "Teams": "PeakyFknBlinders 2.0",
    "SXL": "IN",
    "Latp": "92",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 2",
    "Player_12": "Flekken\r 2",
    "Player_13": "Harwood-Bellis\r 7",
    "Player_14": "Faes\r 0",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Robinson\r 7",
    "Player_5": "Rogers\r 7",
    "Player_6": "Smith Rowe\r 3",
    "Player_3": "Konsa\r 1",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Palmer\r 50",
    "Player_9": "Semenyo\r 7",
    "Player_15": "Vardy\r 1"
  },
  {
    "manager_Name": "1215103",
    "Teams": "\uFFFDCHELSEA\uFFFD",
    "SXL": "IN",
    "Latp": "73",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r 11",
    "Player_12": "Flekken\r 2",
    "Player_13": "Keane\r 0",
    "Player_14": "Pedro Porro\r 5",
    "Player_7": "Bowen\r 2",
    "Player_2": "Harwood-Bellis\r 7",
    "Player_5": "Luis D\u00EDaz\r 2",
    "Player_6": "Mbeumo\r 9",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Konat\u00E9\r 7",
    "Player_8": "Adama\r 3",
    "Player_9": "Palmer\r 25",
    "Player_15": "Fraser\r 0"
  },
  {
    "manager_Name": "630969",
    "Teams": "INTERMIAMI\uFFFD",
    "SXL": "IN",
    "Latp": "84",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Ra\u00FAl\r 9",
    "Player_12": "Turner\r 0",
    "Player_13": "Son\r 0",
    "Player_14": "Harwood-Bellis\r 7",
    "Player_7": "Martinelli\r 13",
    "Player_2": "Gvardiol\r 9",
    "Player_5": "Van de Ven\r 11",
    "Player_6": "Palmer\r 25",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Konsa\r 1",
    "Player_8": "Luis D\u00EDaz\r 2",
    "Player_9": "Rogers\r 7",
    "Player_15": "Jo\u00E3o Pedro\r 0"
  },
  {
    "manager_Name": "541384",
    "Teams": "BABBAAL SQUAD",
    "SXL": "IN",
    "Latp": "86",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Watkins\r 11",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Dibling\r 1",
    "Player_14": "Bednarek\r 1",
    "Player_7": "Rogers\r 7",
    "Player_2": "Mazraoui\r 0",
    "Player_5": "McNeil\r 15",
    "Player_6": "Palmer\r 25",
    "Player_3": "Robertson\r 2",
    "Player_4": "Digne\r 0",
    "Player_8": "M.Salah\r 20",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Tuanzebe\r 0"
  },
  {
    "manager_Name": "5998349",
    "Teams": "Red Devils",
    "SXL": "IN",
    "Latp": "69",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "H\u00F8jlund\r 1",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Harwood-Bellis\r 7",
    "Player_14": "Rogers\r 7",
    "Player_7": "Smith Rowe\r 3",
    "Player_2": "Gvardiol\r 9",
    "Player_5": "Saliba\r 0",
    "Player_6": "Palmer\r 25",
    "Player_3": "Pedro Porro\r 5",
    "Player_4": "Dalot\r 0",
    "Player_8": "Saka\r 3",
    "Player_9": "Rashford\r 2",
    "Player_15": "Stewart\r 1"
  },
  {
    "manager_Name": "3308571",
    "Teams": "Yanited",
    "SXL": "IN",
    "Latp": "52",
    "Player_1": "Ederson M.\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r 11",
    "Player_12": "Matthews\r 0",
    "Player_13": "Taylor\r 1",
    "Player_14": "Barco\r 0",
    "Player_7": "Smith Rowe\r 3",
    "Player_2": "Robinson\r 7",
    "Player_5": "Mbeumo\r 9",
    "Player_6": "Luis D\u00EDaz\r 2",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Pedro Porro\r 5",
    "Player_8": "Saka\r 3",
    "Player_9": "Madueke\r 5",
    "Player_15": "Fraser\r 0"
  },
  {
    "manager_Name": "4159294",
    "Teams": "Bholghaats 11",
    "SXL": "IN",
    "Latp": "66",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Calvert-Lewin\r 2",
    "Player_10": "Haaland\r 2",
    "Player_12": "McCarthy\r 0",
    "Player_13": "Bednarek\r 1",
    "Player_14": "Nedeljkovic\r 0",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Smith Rowe\r 3",
    "Player_6": "Mbeumo\r 9",
    "Player_3": "Robinson\r 7",
    "Player_4": "Robertson\r 2",
    "Player_8": "Palmer\r 25",
    "Player_9": "Watkins\r 11",
    "Player_15": "Winks\r 2"
  },
  {
    "manager_Name": "5416022",
    "Teams": "Emunah Fc",
    "SXL": "IN",
    "Latp": "106",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "N.Jackson\r 5",
    "Player_10": "Haaland\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Tuanzebe\r 0",
    "Player_14": "Faes\r 0",
    "Player_7": "Palmer\r 50",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Mbeumo\r 9",
    "Player_6": "Saka\r 3",
    "Player_3": "Robinson\r 7",
    "Player_4": "Pedro Porro\r 5",
    "Player_8": "McNeil\r 15",
    "Player_9": "Rogers\r 7",
    "Player_15": "Jo\u00E3o Pedro\r 0"
  },
  {
    "manager_Name": "3471165",
    "Teams": "POPPINS",
    "SXL": "IN",
    "Latp": "69",
    "Player_1": "Areola\r 2",
    "Player_11": "Watkins\r 11",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Onana\r 3",
    "Player_13": "Harwood-Bellis\r 7",
    "Player_14": "Sarabia\r 0",
    "Player_7": "Rogers\r 7",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Gvardiol\r 9",
    "Player_6": "Smith Rowe\r 3",
    "Player_3": "Konat\u00E9\r 7",
    "Player_4": "Pedro Porro\r 5",
    "Player_8": "M.Salah\r 20",
    "Player_9": "Haaland\r 2",
    "Player_15": "Winks\r 2"
  },
  {
    "manager_Name": "1181379",
    "Teams": "huntx47",
    "SXL": "IN",
    "Latp": "79",
    "Player_1": "Areola\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Faes\r 0",
    "Player_14": "Lankshear\r 0",
    "Player_7": "Smith Rowe\r 3",
    "Player_2": "Saliba\r 0",
    "Player_5": "Saka\r 3",
    "Player_6": "Mbeumo\r 9",
    "Player_3": "Pedro Porro\r 5",
    "Player_4": "R\u00FAben\r 1",
    "Player_8": "Palmer\r 50",
    "Player_9": "Luis D\u00EDaz\r 2",
    "Player_15": "Harwood-Bellis\r 7"
  },
  {
    "manager_Name": "6583811",
    "Teams": "Kkl11",
    "SXL": "IN",
    "Latp": "62",
    "Player_1": "Raya\r 1",
    "Player_11": "N.Jackson\r 5",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Welbeck\r 2",
    "Player_14": "Bednarek\r 1",
    "Player_7": "Saka\r 3",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Rogers\r 7",
    "Player_6": "Smith Rowe\r 3",
    "Player_3": "Digne\r 0",
    "Player_4": "Van de Ven\r 11",
    "Player_8": "Palmer\r 25",
    "Player_9": "Luis D\u00EDaz\r 2",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "518116",
    "Teams": "los blancos",
    "SXL": "IN",
    "Latp": "61",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "N.Jackson\r 5",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Van den Berg\r 2",
    "Player_14": "Kilman\r 1",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Rogers\r 7",
    "Player_6": "Saka\r 6",
    "Player_3": "Digne\r 0",
    "Player_4": "Lewis\r 2",
    "Player_8": "Palmer\r 25",
    "Player_9": "Evanilson\r 9",
    "Player_15": "Winks\r 2"
  },
  {
    "manager_Name": "1469521",
    "Teams": "dRiceFC",
    "SXL": "IN",
    "Latp": "83",
    "Player_1": "Flekken\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Watkins\r 22",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Harwood-Bellis\r 7",
    "Player_14": "Ui-jo\r 0",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Lewis\r 2",
    "Player_5": "Rogers\r 7",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Konsa\r 1",
    "Player_4": "Robinson\r 7",
    "Player_8": "Smith Rowe\r 3",
    "Player_9": "Palmer\r 25",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "6484383",
    "Teams": "Raja Ji Ki Fauj",
    "SXL": "IN",
    "Latp": "91",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "N.Jackson\r 5",
    "Player_12": "Turner\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 0",
    "Player_14": "Faes\r 0",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Bednarek\r 1",
    "Player_5": "De Ligt\r 1",
    "Player_6": "Palmer\r 50",
    "Player_3": "Gu\u00E9hi\r 9",
    "Player_4": "Romero\r 6",
    "Player_8": "Smith Rowe\r 3",
    "Player_9": "M.Salah\r 10",
    "Player_15": "Winks\r 2"
  },
  {
    "manager_Name": "1375166",
    "Teams": "Chinhar City FC",
    "SXL": "IN",
    "Latp": "83",
    "Player_1": "Raya\r 1",
    "Player_11": "Watkins\r 22",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Mazraoui\r 0",
    "Player_14": "Harwood-Bellis\r 7",
    "Player_7": "Palmer\r 25",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Semenyo\r 7",
    "Player_6": "Luis D\u00EDaz\r 2",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Digne\r 0",
    "Player_8": "Rogers\r 7",
    "Player_9": "McNeil\r 15",
    "Player_15": "Jo\u00E3o Pedro\r 0"
  },
  {
    "manager_Name": "10150",
    "Teams": "L Company",
    "SXL": "IN",
    "Latp": "56",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Havertz\r 6",
    "Player_12": "Sels\r 2",
    "Player_13": "Davis\r 2",
    "Player_14": "Burn\r 2",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Dalot\r 0",
    "Player_5": "Mbeumo\r 9",
    "Player_6": "Smith Rowe\r 3",
    "Player_3": "Robertson\r 2",
    "Player_4": "Gabriel\r 1",
    "Player_8": "Garnacho\r 2",
    "Player_9": "Palmer\r 25",
    "Player_15": "Stewart\r 1"
  },
  {
    "manager_Name": "8018469",
    "Teams": "Dexadroitus",
    "SXL": "IN",
    "Latp": "96",
    "Player_1": "Raya\r 1",
    "Player_11": "Calvert-Lewin\r 1",
    "Player_10": "Haaland\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Coufal\r 0",
    "Player_14": "Winks\r 2",
    "Player_7": "Smith Rowe\r 3",
    "Player_2": "Konat\u00E9\r 7",
    "Player_5": "Palmer\r 50",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Van de Ven\r 11",
    "Player_8": "Doku\r 1",
    "Player_9": "Vardy\r 1",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "7323408",
    "Teams": "IVAN DUPLICATE",
    "SXL": "QA",
    "Latp": "65",
    "Player_1": "Onana\r 3",
    "Player_11": "Haaland\r 2",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Areola\r 2",
    "Player_13": "Ra\u00FAl\r 9",
    "Player_14": "Coufal\r 0",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Robinson\r 7",
    "Player_5": "Palmer\r 25",
    "Player_6": "M.Salah\r 20",
    "Player_3": "Dalot\r 0",
    "Player_4": "Dunk\r -1",
    "Player_8": "Smith Rowe\r 3",
    "Player_9": "Onana\r 2",
    "Player_15": "Burn\r 2"
  },
  {
    "manager_Name": "1195597",
    "Teams": "Tasho11",
    "SXL": "IN",
    "Latp": "66",
    "Player_1": "Raya\r 1",
    "Player_11": "Watkins\r 11",
    "Player_10": "Haaland\r 4",
    "Player_12": "Kelleher\r 0",
    "Player_13": "Faes\r 0",
    "Player_14": "Stewart\r 1",
    "Player_7": "Smith Rowe\r 3",
    "Player_2": "Virgil\r 2",
    "Player_5": "Mbeumo\r 9",
    "Player_6": "Palmer\r 25",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Konsa\r 1",
    "Player_8": "Luis D\u00EDaz\r 2",
    "Player_9": "Rogers\r 7",
    "Player_15": "Harwood-Bellis\r 7"
  },
  {
    "manager_Name": "3057830",
    "Teams": "Netflix \u0026 Chilwell",
    "SXL": "IN",
    "Latp": "85",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Havertz\r 6",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Welbeck\r 2",
    "Player_14": "Keane\r 0",
    "Player_7": "Mbeumo\r 9",
    "Player_2": "Faes\r 0",
    "Player_5": "Palmer\r 25",
    "Player_6": "M.Salah\r 20",
    "Player_3": "Mazraoui\r 0",
    "Player_4": "Konat\u00E9\r 7",
    "Player_8": "Rogers\r 7",
    "Player_9": "Semenyo\r 7",
    "Player_15": "Stephens\r 0"
  },
  {
    "manager_Name": "822612",
    "Teams": "M_KiThan",
    "SXL": "IN",
    "Latp": "70",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Calvert-Lewin\r 1",
    "Player_10": "Haaland\r 4",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Faes\r 0",
    "Player_14": "Harwood-Bellis\r 7",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Konsa\r 1",
    "Player_5": "Palmer\r 25",
    "Player_6": "Saka\r 3",
    "Player_3": "Konat\u00E9\r 7",
    "Player_4": "Robinson\r 7",
    "Player_8": "Smith Rowe\r 3",
    "Player_9": "Rogers\r 7",
    "Player_15": "Jebbison\r 0"
  },
  {
    "manager_Name": "7459938",
    "Teams": "BrokenFC",
    "SXL": "IN",
    "Latp": "61",
    "Player_1": "Henderson\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "Rogers\r 7",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 0",
    "Player_14": "Pedro Porro\r 5",
    "Player_7": "Palmer\r 25",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Konsa\r 1",
    "Player_6": "Smith Rowe\r 3",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Robinson\r 7",
    "Player_8": "Saka\r 3",
    "Player_9": "Diogo J.\r 8",
    "Player_15": "Archer\r 1"
  },
  {
    "manager_Name": "3456377",
    "Teams": "kdfc",
    "SXL": "IN",
    "Latp": "77",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r 11",
    "Player_12": "Ederson M.\r 2",
    "Player_13": "Kilman\r 1",
    "Player_14": "Welbeck\r 2",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Robertson\r 2",
    "Player_5": "McNeil\r 15",
    "Player_6": "Sou\u010Dek\r 10",
    "Player_3": "Colwill\r 1",
    "Player_4": "Lewis\r 2",
    "Player_8": "Palmer\r 25",
    "Player_9": "Smith Rowe\r 3",
    "Player_15": "Pedro Porro\r 5"
  },
  {
    "manager_Name": "7429221",
    "Teams": "TEAM 11",
    "SXL": "IN",
    "Latp": "74",
    "Player_1": "Raya\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "Wood\r 2",
    "Player_12": "Flekken\r 2",
    "Player_13": "Harwood-Bellis\r 7",
    "Player_14": "Vardy\r 1",
    "Player_7": "Palmer\r 25",
    "Player_2": "Pedro Porro\r 5",
    "Player_5": "Gvardiol\r 9",
    "Player_6": "Smith Rowe\r 3",
    "Player_3": "Konsa\r 1",
    "Player_4": "Konat\u00E9\r 7",
    "Player_8": "Rogers\r 7",
    "Player_9": "M.Salah\r 10",
    "Player_15": "Winks\r 2"
  },
  {
    "manager_Name": "1035990",
    "Teams": "Nishals",
    "SXL": "IN",
    "Latp": "56",
    "Player_1": "Martinez\r 2",
    "Player_11": "Wood\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Greaves\r 0",
    "Player_14": "Faes\r 0",
    "Player_7": "Mbeumo\r 9",
    "Player_2": "Collins\r 2",
    "Player_5": "Saka\r 3",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Rogers\r 7",
    "Player_9": "Semenyo\r 7",
    "Player_15": "Stewart\r 1"
  },
  {
    "manager_Name": "1761601",
    "Teams": "Citizens FC",
    "SXL": "IN",
    "Latp": "99",
    "Player_1": "Pope\r 3",
    "Player_11": "Haaland\r 2",
    "Player_10": "Muniz\r 1",
    "Player_12": "Turner\r 0",
    "Player_13": "Pedro Porro\r 5",
    "Player_14": "Jebbison\r 0",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Gvardiol\r 9",
    "Player_5": "Mbeumo\r 9",
    "Player_6": "Diogo J.\r 8",
    "Player_3": "Konat\u00E9\r 7",
    "Player_4": "Gabriel\r 1",
    "Player_8": "Palmer\r 50",
    "Player_9": "Rogers\r 7",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "2147305",
    "Teams": "IG-Abhi",
    "SXL": "IN",
    "Latp": "96",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Watkins\r 11",
    "Player_10": "Haaland\r 2",
    "Player_12": "Bentley\r 0",
    "Player_13": "Robinson\r 7",
    "Player_14": "Minteh\r 1",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Pedro Porro\r 5",
    "Player_5": "Rogers\r 7",
    "Player_6": "Smith Rowe\r 3",
    "Player_3": "Konat\u00E9\r 7",
    "Player_4": "Konsa\r 1",
    "Player_8": "Palmer\r 50",
    "Player_9": "Havertz\r 6",
    "Player_15": "Vestergaard\r 0"
  },
  {
    "manager_Name": "185741",
    "Teams": "Kroos Control",
    "SXL": "IN",
    "Latp": "69",
    "Player_1": "Raya\r 1",
    "Player_11": "Calvert-Lewin\r 1",
    "Player_10": "Haaland\r 4",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Aina\r 2",
    "Player_14": "Jo\u00E3o Pedro\r 0",
    "Player_7": "Rogers\r 7",
    "Player_2": "Konsa\r 1",
    "Player_5": "M.Salah\r 10",
    "Player_6": "Palmer\r 25",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Robinson\r 7",
    "Player_8": "Smith Rowe\r 3",
    "Player_9": "Mbeumo\r 9",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "383465",
    "Teams": "FC NuTMeG",
    "SXL": "IN",
    "Latp": "88",
    "Player_1": "Kelleher\r 0",
    "Player_11": "Haaland\r 2",
    "Player_10": "N.Jackson\r 5",
    "Player_12": "Turner\r 0",
    "Player_13": "Faes\r 0",
    "Player_14": "Harwood-Bellis\r 7",
    "Player_7": "Palmer\r 25",
    "Player_2": "Konsa\r 1",
    "Player_5": "M.Salah\r 20",
    "Player_6": "Smith Rowe\r 3",
    "Player_3": "Konat\u00E9\r 7",
    "Player_4": "Robinson\r 7",
    "Player_8": "Rogers\r 7",
    "Player_9": "Watkins\r 11",
    "Player_15": "Winks\r 2"
  },
  {
    "manager_Name": "790389",
    "Teams": "Lassoon XI",
    "SXL": "IN",
    "Latp": "64",
    "Player_1": "Henderson\r 1",
    "Player_11": "Haaland\r 2",
    "Player_10": "Watkins\r 11",
    "Player_12": "Slicker\r 0",
    "Player_13": "Johnson\r 0",
    "Player_14": "Sangar\u00E9\r 0",
    "Player_7": "M.Salah\r 20",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Mbeumo\r 9",
    "Player_6": "Smith Rowe\r 3",
    "Player_3": "Robinson\r 7",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Rogers\r 7",
    "Player_9": "Wood\r 2",
    "Player_15": "Mykolenko\r 2"
  },
  {
    "manager_Name": "5495557",
    "Teams": "H\u0026H",
    "SXL": "IN",
    "Latp": "79",
    "Player_1": "Raya\r 1",
    "Player_11": "Ra\u00FAl\r 9",
    "Player_10": "Watkins\r 11",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "Pedro Lima\r 0",
    "Player_14": "Lewis\r 2",
    "Player_7": "Martinelli\r 13",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Rogers\r 7",
    "Player_6": "M.Salah\r 20",
    "Player_3": "Digne\r 0",
    "Player_4": "Mazraoui\r 0",
    "Player_8": "McNeil\r 15",
    "Player_9": "Haaland\r 2",
    "Player_15": "Winks\r 2"
  },
  {
    "manager_Name": "6384653",
    "Teams": "INvincibles 2.0",
    "SXL": "IN",
    "Latp": "76",
    "Player_1": "Raya\r 1",
    "Player_11": "Watkins\r 11",
    "Player_10": "Haaland\r 2",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "Welbeck\r 2",
    "Player_14": "Lewis\r 2",
    "Player_7": "Palmer\r 25",
    "Player_2": "Konat\u00E9\r 7",
    "Player_5": "Luis D\u00EDaz\r 4",
    "Player_6": "Diogo J.\r 8",
    "Player_3": "Robinson\r 7",
    "Player_4": "Gabriel\r 1",
    "Player_8": "Rogers\r 7",
    "Player_9": "Adama\r 3",
    "Player_15": "Mazraoui\r 0"
  },
  {
    "manager_Name": "5687923",
    "Teams": "eleven of ten",
    "SXL": "IN",
    "Latp": "91",
    "Player_1": "Flekken\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Rogers\r 7",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 0",
    "Player_14": "Faes\r 0",
    "Player_7": "Palmer\r 50",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Harwood-Bellis\r 7",
    "Player_6": "Saka\r 3",
    "Player_3": "Konsa\r 1",
    "Player_4": "Robinson\r 7",
    "Player_8": "Smith Rowe\r 3",
    "Player_9": "Diogo J.\r 8",
    "Player_15": "Wissa\r 0"
  },
  {
    "manager_Name": "6210372",
    "Teams": "ASIF NTR",
    "SXL": "IN",
    "Latp": "86",
    "Player_1": "Raya\r 1",
    "Player_11": "N.Jackson\r 5",
    "Player_10": "Ra\u00FAl\r 9",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "Adama\r 3",
    "Player_14": "Mazraoui\r 0",
    "Player_7": "Palmer\r 25",
    "Player_2": "Pedro Porro\r 5",
    "Player_5": "Saka\r 3",
    "Player_6": "M.Salah\r 20",
    "Player_3": "Robertson\r 2",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Luis D\u00EDaz\r 2",
    "Player_9": "Antonio\r 5",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "6683107",
    "Teams": "Chunky Monkey",
    "SXL": "IN",
    "Latp": "68",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Havertz\r 6",
    "Player_10": "Haaland\r 4",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Welbeck\r 2",
    "Player_14": "White\r 0",
    "Player_7": "Smith Rowe\r 3",
    "Player_2": "Robertson\r 2",
    "Player_5": "Luis D\u00EDaz\r 2",
    "Player_6": "Palmer\r 25",
    "Player_3": "Konsa\r 1",
    "Player_4": "Robinson\r 7",
    "Player_8": "Mbeumo\r 9",
    "Player_9": "Rogers\r 7",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "4584036",
    "Teams": "emptyhad XI",
    "SXL": "IN",
    "Latp": "80",
    "Player_1": "Leno\r 5",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Gusto\r 1",
    "Player_14": "Winks\r 2",
    "Player_7": "Palmer\r 50",
    "Player_2": "Saliba\r 0",
    "Player_5": "Luis D\u00EDaz\r 2",
    "Player_6": "Smith Rowe\r 3",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Virgil\r 2",
    "Player_8": "Rogers\r 7",
    "Player_9": "Havertz\r 6",
    "Player_15": "Van Hecke\r 0"
  },
  {
    "manager_Name": "799689",
    "Teams": "moh17",
    "SXL": "IN",
    "Latp": "52",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Watkins\r 11",
    "Player_10": "Haaland\r 4",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Welbeck\r 2",
    "Player_14": "Lewis\r 2",
    "Player_7": "Saka\r 3",
    "Player_2": "Harwood-Bellis\r 7",
    "Player_5": "Van den Berg\r 2",
    "Player_6": "Smith Rowe\r 3",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Aina\r 2",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Rogers\r 7",
    "Player_15": "Winks\r 2"
  },
  {
    "manager_Name": "4529359",
    "Teams": "\uFFFD",
    "SXL": "IN",
    "Latp": "84",
    "Player_1": "Raya\r 1",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Aina\r 2",
    "Player_14": "Johnson\r 0",
    "Player_7": "Palmer\r 50",
    "Player_2": "Saliba\r 0",
    "Player_5": "Smith Rowe\r 3",
    "Player_6": "Rogers\r 7",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Robinson\r 7",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Duran\r 1",
    "Player_15": "Winks\r 2"
  },
  {
    "manager_Name": "927307",
    "Teams": "Sarvesh Lanjewar",
    "SXL": "IN",
    "Latp": "70",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r 11",
    "Player_12": "Steele\r 0",
    "Player_13": "Nedeljkovic\r 0",
    "Player_14": "Jo\u00E3o Pedro\r 0",
    "Player_7": "Palmer\r 25",
    "Player_2": "Robertson\r 2",
    "Player_5": "Dibling\r 1",
    "Player_6": "Rogers\r 7",
    "Player_3": "Lewis\r 2",
    "Player_4": "J.Timber\r 4",
    "Player_8": "Mbeumo\r 9",
    "Player_9": "Saka\r 3",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "1122533",
    "Teams": "VIVIPOOL",
    "SXL": "IN",
    "Latp": "64",
    "Player_1": "Henderson\r 1",
    "Player_11": "Wood\r 2",
    "Player_10": "Welbeck\r 2",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "Harwood-Bellis\r 7",
    "Player_14": "Winks\r 2",
    "Player_7": "Palmer\r 25",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Smith Rowe\r 3",
    "Player_6": "Rogers\r 7",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Mazraoui\r 0",
    "Player_8": "M.Salah\r 20",
    "Player_9": "Haaland\r 2",
    "Player_15": "Burn\r 2"
  },
  {
    "manager_Name": "6685685",
    "Teams": "adithyan",
    "SXL": "IN",
    "Latp": "99",
    "Player_1": "Raya\r 1",
    "Player_11": "Watkins\r 11",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Pedro Lima\r 0",
    "Player_14": "Chiquinho\r 0",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Gvardiol\r 9",
    "Player_5": "Lewis\r 2",
    "Player_6": "Mbeumo\r 9",
    "Player_3": "Saliba\r 0",
    "Player_4": "Romero\r 6",
    "Player_8": "Palmer\r 50",
    "Player_9": "Rogers\r 7",
    "Player_15": "Jo\u00E3o Pedro\r 0"
  },
  {
    "manager_Name": "4833105",
    "Teams": "Darwin\u0027s Evolution",
    "SXL": "IN",
    "Latp": "111",
    "Player_1": "Raya\r 1",
    "Player_11": "Haaland\r 2",
    "Player_10": "Watkins\r 11",
    "Player_12": "Flekken\r 2",
    "Player_13": "Amad\r 1",
    "Player_14": "Keane\r 0",
    "Player_7": "Diogo J.\r 8",
    "Player_2": "Van de Ven\r 11",
    "Player_5": "Palmer\r 50",
    "Player_6": "Semenyo\r 7",
    "Player_3": "Konat\u00E9\r 7",
    "Player_4": "Gabriel\r 1",
    "Player_8": "Rogers\r 7",
    "Player_9": "Havertz\r 6",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "3248545",
    "Teams": "SS25",
    "SXL": "IN",
    "Latp": "71",
    "Player_1": "Raya\r 1",
    "Player_11": "Watkins\r 11",
    "Player_10": "Haaland\r 4",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "Pedro Porro\r 5",
    "Player_14": "Winks\r 2",
    "Player_7": "Rogers\r 7",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Robinson\r 7",
    "Player_6": "Palmer\r 25",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Smith Rowe\r 3",
    "Player_9": "Welbeck\r 2",
    "Player_15": "McNeil\r 15"
  },
  {
    "manager_Name": "2936918",
    "Teams": "HarryMaguireXI",
    "SXL": "IN",
    "Latp": "86",
    "Player_1": "Arrizabalaga\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "N.Jackson\r 5",
    "Player_12": "D\u00FAbravka\r 0",
    "Player_13": "Harwood-Bellis\r 7",
    "Player_14": "Okoli\r 1",
    "Player_7": "Palmer\r 50",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Luis D\u00EDaz\r 2",
    "Player_6": "Semenyo\r 7",
    "Player_3": "Saliba\r 0",
    "Player_4": "J.Timber\r 4",
    "Player_8": "Hudson-Odoi\r 1",
    "Player_9": "Trossard\r 12",
    "Player_15": "Delap\r 12"
  }
];