var s = [
  {
    "manager_Name": "278( 822,974 )",
    "Teams": "MoreLife( Eric Odeifor )",
    "SXL": "GHA",
    "Latp": "18",
    "Player_1": "A.Becker 2",
    "Player_11": "Isak 1",
    "Player_10": "Haaland ARS (A)",
    "Player_12": "Raya MCI (H)",
    "Player_13": "Calafiori MCI (H)",
    "Player_14": "Adu-Adjei NEW (H)",
    "Player_7": "Enzo 1",
    "Player_2": "Gu\u00E9hi 7",
    "Player_5": "Eze MCI (H)",
    "Player_6": "Gakpo 2",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Senesi NEW (H)",
    "Player_8": "Semenyo NEW (H)",
    "Player_9": "Caicedo 4",
    "Player_15": "A.Murphy BOU (A)"
  },
  {
    "manager_Name": "254( 3,013,765 )",
    "Teams": "Refti Nyame( Jonat Jonabil )",
    "SXL": "GHA",
    "Latp": "37",
    "Player_1": "Sels 3",
    "Player_11": "Jo\u00E3o Pedro 2",
    "Player_10": "Richarlison 9",
    "Player_12": "Areola 1",
    "Player_13": "Beto 1",
    "Player_14": "Baleba 1",
    "Player_7": "Wirtz 0",
    "Player_2": "Cucurella 0",
    "Player_5": "Senesi NEW (H)",
    "Player_6": "M.Salah 10",
    "Player_3": "Virgil 4",
    "Player_4": "Van de Ven 1",
    "Player_8": "Kudus 7",
    "Player_9": "Palmer 1",
    "Player_15": "Est\u00E8ve 4"
  },
  {
    "manager_Name": "247( 3,922,835 )",
    "Teams": "Difari( Seidu Yahaya )",
    "SXL": "GHA",
    "Latp": "23",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Haaland ARS (A)",
    "Player_10": "Mateta 6",
    "Player_12": "Pope BOU (A)",
    "Player_13": "A\u00EFt-Nouri ARS (A)",
    "Player_14": "Gruda 2",
    "Player_7": "Mitoma 2",
    "Player_2": "Gabriel MCI (H)",
    "Player_5": "Gu\u00E9hi 7",
    "Player_6": "Mbeumo 3",
    "Player_3": "De Ligt 2",
    "Player_4": "Frimpong 0",
    "Player_8": "Yeremy 1",
    "Player_9": "Jo\u00E3o Pedro 2",
    "Player_15": "Gittens 0"
  },
  {
    "manager_Name": "219( 7,125,744 )",
    "Teams": "Dav utd( David Nsesonkpa )",
    "SXL": "GHA",
    "Latp": "26",
    "Player_1": "D\u00FAbravka 4",
    "Player_11": "Watkins SUN (A)",
    "Player_10": "Richarlison 9",
    "Player_12": "Henderson 1",
    "Player_13": "Calafiori MCI (H)",
    "Player_14": "Gakpo 2",
    "Player_7": "Foden ARS (A)",
    "Player_2": "Virgil 4",
    "Player_5": "Cucurella 0",
    "Player_6": "Mbeumo 3",
    "Player_3": "Zinchenko 2",
    "Player_4": "Tarkowski 3",
    "Player_8": "Neto 1",
    "Player_9": "Marc Guiu 0",
    "Player_15": "Wirtz 0"
  },
  {
    "manager_Name": "211( 7,823,242 )",
    "Teams": "McCoyJOTA20( Richie Perkins )",
    "SXL": "GHA",
    "Latp": "12",
    "Player_1": "Kelleher 1",
    "Player_11": "Gy\u00F6keres MCI (H)",
    "Player_10": "Haaland ARS (A)",
    "Player_12": "Darlow 3",
    "Player_13": "Mitoma 2",
    "Player_14": "Reinildo AVL (H)",
    "Player_7": "Palmer 1",
    "Player_2": "J.Timber MCI (H)",
    "Player_5": "Semenyo NEW (H)",
    "Player_6": "Doku ARS (A)",
    "Player_3": "Burn BOU (A)",
    "Player_4": "Pedro Porro 1",
    "Player_8": "Kudus 7",
    "Player_9": "Jo\u00E3o Pedro 2",
    "Player_15": "Pond 0"
  }
];