var s = [
  {
    "manager_Name": "273( 130,524 )",
    "Teams": "Charlie\u0027s Angels( Charlie Smith )",
    "SXL": "ENG",
    "Latp": "11",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Watkins SUN (A)",
    "Player_10": "Haaland ARS (A)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Saliba MCI (H)",
    "Player_14": "King BRE (H)",
    "Player_7": "M.Salah 10",
    "Player_2": "Digne SUN (A)",
    "Player_5": "Van de Ven 1",
    "Player_6": "P.M.Sarr 0",
    "Player_3": "Cash SUN (A)",
    "Player_4": "Gabriel MCI (H)",
    "Player_8": "Semenyo NEW (H)",
    "Player_9": "Reijnders ARS (A)",
    "Player_15": "Abdullahi AVL (H)"
  },
  {
    "manager_Name": "267( 221,971 )",
    "Teams": "Rice Rice Baby( kaisler Schembri )",
    "SXL": "MLT",
    "Latp": "2",
    "Player_1": "Verbruggen 1",
    "Player_11": "Jo\u00E3o Pedro MUN (A)",
    "Player_10": "Haaland ARS (A)",
    "Player_12": "Darlow 3",
    "Player_13": "Ndiaye 6",
    "Player_14": "Est\u00E8ve 2",
    "Player_7": "Rogers SUN (A)",
    "Player_2": "Cucurella MUN (A)",
    "Player_5": "Mbeumo CHE (H)",
    "Player_6": "Wirtz 0",
    "Player_3": "Gabriel MCI (H)",
    "Player_4": "Van de Ven 1",
    "Player_8": "Reijnders ARS (A)",
    "Player_9": "Woltemade BOU (A)",
    "Player_15": "Wan-Bissaka 0"
  },
  {
    "manager_Name": "262( 349,028 )",
    "Teams": "kurt slika( Kurt Gatt )",
    "SXL": "MLT",
    "Latp": "1",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Gy\u00F6keres MCI (H)",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "Jos\u00E9 S\u00E1 1",
    "Player_13": "Cucurella MUN (A)",
    "Player_14": "J.Palhinha 4",
    "Player_7": "Wirtz 0",
    "Player_2": "Frimpong 0",
    "Player_5": "Senesi NEW (H)",
    "Player_6": "Mbeumo CHE (H)",
    "Player_3": "Livramento BOU (A)",
    "Player_4": "Van de Ven 1",
    "Player_8": "Zubimendi MCI (H)",
    "Player_9": "Haaland ARS (A)",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "261( 370,341 )",
    "Teams": "Slika FC( Kyle Gatt )",
    "SXL": "MLT",
    "Latp": "19",
    "Player_1": "Darlow 3",
    "Player_11": "Isak 1",
    "Player_10": "Haaland ARS (A)",
    "Player_12": "S\u00E1nchez MUN (A)",
    "Player_13": "Gabriel MCI (H)",
    "Player_14": "Mitoma 2",
    "Player_7": "Ndiaye 6",
    "Player_2": "Pedro Porro 1",
    "Player_5": "N.Williams 8",
    "Player_6": "Enzo MUN (A)",
    "Player_3": "Sch\u00E4r BOU (A)",
    "Player_4": "Frimpong 0",
    "Player_8": "Reijnders ARS (A)",
    "Player_9": "Gy\u00F6keres MCI (H)",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "257( 502,919 )",
    "Teams": "gunner_xi( Justin kind )",
    "SXL": "MLT",
    "Latp": "10",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Wood 2",
    "Player_10": "Haaland ARS (A)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Reijnders ARS (A)",
    "Player_14": "Kudus 7",
    "Player_7": "Gakpo 2",
    "Player_2": "Livramento BOU (A)",
    "Player_5": "Milenkovi\u0107 2",
    "Player_6": "Reinildo AVL (H)",
    "Player_3": "Gabriel MCI (H)",
    "Player_4": "Romero 2",
    "Player_8": "Ndoye 2",
    "Player_9": "Jo\u00E3o Pedro MUN (A)",
    "Player_15": "Sarr 0"
  },
  {
    "manager_Name": "254( 663,724 )",
    "Teams": "Noni your business( Owen Farrugia )",
    "SXL": "MLT",
    "Latp": "13",
    "Player_1": "D\u00FAbravka 4",
    "Player_11": "Watkins SUN (A)",
    "Player_10": "Gy\u00F6keres MCI (H)",
    "Player_12": "S\u00E1nchez MUN (A)",
    "Player_13": "Ndiaye 6",
    "Player_14": "Reijnders ARS (A)",
    "Player_7": "Rogers SUN (A)",
    "Player_2": "Livramento BOU (A)",
    "Player_5": "Van de Ven 1",
    "Player_6": "Semenyo NEW (H)",
    "Player_3": "Andersen BRE (H)",
    "Player_4": "Pedro Porro 1",
    "Player_8": "Kudus 7",
    "Player_9": "Haaland ARS (A)",
    "Player_15": "Cucurella MUN (A)"
  },
  {
    "manager_Name": "253( 696,784 )",
    "Teams": "Arteta Ball FC( Dylan Camilleri )",
    "SXL": "MLT",
    "Latp": "28",
    "Player_1": "Sels 3",
    "Player_11": "Thiago FUL (A)",
    "Player_10": "Gy\u00F6keres MCI (H)",
    "Player_12": "S\u00E1nchez MUN (A)",
    "Player_13": "Tarkowski 3",
    "Player_14": "Est\u00E8ve 2",
    "Player_7": "M.Salah 10",
    "Player_2": "Gabriel MCI (H)",
    "Player_5": "Semenyo NEW (H)",
    "Player_6": "Ndiaye 6",
    "Player_3": "Konsa SUN (A)",
    "Player_4": "Mu\u00F1oz 2",
    "Player_8": "Kudus 7",
    "Player_9": "Jo\u00E3o Pedro MUN (A)",
    "Player_15": "Sarr 0"
  },
  {
    "manager_Name": "253( 696,784 )",
    "Teams": "TetasSexyReds( Gary Pace )",
    "SXL": "MLT",
    "Latp": "19",
    "Player_1": "Sels 3",
    "Player_11": "Haaland ARS (A)",
    "Player_10": "Gy\u00F6keres MCI (H)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Pedro Porro 1",
    "Player_14": "Beto 1",
    "Player_7": "Mbeumo CHE (H)",
    "Player_2": "Gabriel MCI (H)",
    "Player_5": "Diouf 3",
    "Player_6": "Rice MCI (H)",
    "Player_3": "Andersen BRE (H)",
    "Player_4": "Virgil 4",
    "Player_8": "Kudus 7",
    "Player_9": "Gakpo 2",
    "Player_15": "Reijnders ARS (A)"
  },
  {
    "manager_Name": "252( 747,682 )",
    "Teams": "Bend it like Boogie( Ryan Bonello Gatt )",
    "SXL": "MLT",
    "Latp": "19",
    "Player_1": "Sels 3",
    "Player_11": "Gy\u00F6keres MCI (H)",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "Kelleher FUL (A)",
    "Player_13": "Grealish 1",
    "Player_14": "R\u00FAben ARS (A)",
    "Player_7": "Eze MCI (H)",
    "Player_2": "Gabriel MCI (H)",
    "Player_5": "Xavi 1",
    "Player_6": "Semenyo NEW (H)",
    "Player_3": "Virgil 4",
    "Player_4": "Gu\u00E9hi 7",
    "Player_8": "Gakpo 2",
    "Player_9": "Isak 2",
    "Player_15": "Aina 0"
  },
  {
    "manager_Name": "251( 786,788 )",
    "Teams": "diavoli 11( Paul Micallef )",
    "SXL": "MLT",
    "Latp": "8",
    "Player_1": "Donnarumma ARS (A)",
    "Player_11": "Haaland ARS (A)",
    "Player_10": "Gy\u00F6keres MCI (H)",
    "Player_12": "Setford MCI (H)",
    "Player_13": "Senesi NEW (H)",
    "Player_14": "Reijnders ARS (A)",
    "Player_7": "Semenyo NEW (H)",
    "Player_2": "Gu\u00E9hi 7",
    "Player_5": "B.Fernandes CHE (H)",
    "Player_6": "Enzo MUN (A)",
    "Player_3": "Mings SUN (A)",
    "Player_4": "Chalobah MUN (A)",
    "Player_8": "Xavi 1",
    "Player_9": "Jo\u00E3o Pedro MUN (A)",
    "Player_15": "Byram 0"
  },
  {
    "manager_Name": "246( 1,080,380 )",
    "Teams": "Clarky FC( Carl Clark )",
    "SXL": "ENG",
    "Latp": "12",
    "Player_1": "Leno BRE (H)",
    "Player_11": "Haaland ARS (A)",
    "Player_10": "Gy\u00F6keres MCI (H)",
    "Player_12": "Slonina MUN (A)",
    "Player_13": "Mayenda AVL (H)",
    "Player_14": "Cullen 4",
    "Player_7": "Semenyo NEW (H)",
    "Player_2": "Mitchell 7",
    "Player_5": "Murillo 0",
    "Player_6": "Spence 1",
    "Player_3": "Konat\u00E9 4",
    "Player_4": "Sch\u00E4r BOU (A)",
    "Player_8": "Enzo MUN (A)",
    "Player_9": "Eze MCI (H)",
    "Player_15": "Saka MCI (H)"
  },
  {
    "manager_Name": "242( 1,388,973 )",
    "Teams": "Sammygooner****( Sammy Vella )",
    "SXL": "MLT",
    "Latp": "13",
    "Player_1": "S\u00E1nchez MUN (A)",
    "Player_11": "Gy\u00F6keres MCI (H)",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Reijnders ARS (A)",
    "Player_14": "Konsa SUN (A)",
    "Player_7": "Semenyo NEW (H)",
    "Player_2": "Virgil 4",
    "Player_5": "Eze MCI (H)",
    "Player_6": "Kudus 7",
    "Player_3": "Van de Ven 1",
    "Player_4": "Gabriel MCI (H)",
    "Player_8": "Cunha CHE (H)",
    "Player_9": "Isak 1",
    "Player_15": "A\u00EFt-Nouri ARS (A)"
  },
  {
    "manager_Name": "242( 1,419,466 )",
    "Teams": "Lions( Daniel Ferriggi )",
    "SXL": "MLT",
    "Latp": "27",
    "Player_1": "Kelleher FUL (A)",
    "Player_11": "Gy\u00F6keres MCI (H)",
    "Player_10": "Wood 2",
    "Player_12": "Pickford 1",
    "Player_13": "Murillo 0",
    "Player_14": "Reijnders ARS (A)",
    "Player_7": "Caicedo MUN (A)",
    "Player_2": "Virgil 4",
    "Player_5": "M.Salah 10",
    "Player_6": "Kudus 7",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Milenkovi\u0107 2",
    "Player_8": "P.M.Sarr 0",
    "Player_9": "Jo\u00E3o Pedro MUN (A)",
    "Player_15": "Tarkowski 3"
  },
  {
    "manager_Name": "241( 1,531,821 )",
    "Teams": "Sultan Army( Julian Sultana )",
    "SXL": "MLT",
    "Latp": "22",
    "Player_1": "Sels 3",
    "Player_11": "Jo\u00E3o Pedro MUN (A)",
    "Player_10": "Ekitik\u00E9 6",
    "Player_12": "Pickford 1",
    "Player_13": "Saliba MCI (H)",
    "Player_14": "Gibbs-White 2",
    "Player_7": "Xavi 1",
    "Player_2": "Cucurella MUN (A)",
    "Player_5": "Gabriel MCI (H)",
    "Player_6": "Semenyo NEW (H)",
    "Player_3": "Virgil 4",
    "Player_4": "Calafiori MCI (H)",
    "Player_8": "Grealish 1",
    "Player_9": "Kudus 7",
    "Player_15": "Richarlison 6"
  },
  {
    "manager_Name": "239( 1,659,142 )",
    "Teams": "Hamrun Gunners( Mark Monseigneur )",
    "SXL": "MLT",
    "Latp": "9",
    "Player_1": "Henderson 1",
    "Player_11": "Jo\u00E3o Pedro MUN (A)",
    "Player_10": "Haaland ARS (A)",
    "Player_12": "Pickford 1",
    "Player_13": "Bruno G. BOU (A)",
    "Player_14": "Walker 2",
    "Player_7": "Grealish 1",
    "Player_2": "Clyne 0",
    "Player_5": "Rice MCI (H)",
    "Player_6": "Gakpo 2",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Virgil 4",
    "Player_8": "Neto MUN (A)",
    "Player_9": "Gy\u00F6keres MCI (H)",
    "Player_15": "Toti 1"
  },
  {
    "manager_Name": "238( 1,776,990 )",
    "Teams": "matthew 14( matthew borg )",
    "SXL": "MLT",
    "Latp": "19",
    "Player_1": "Pope BOU (A)",
    "Player_11": "Haaland ARS (A)",
    "Player_10": "Ekitik\u00E9 6",
    "Player_12": "Foderingham 0",
    "Player_13": "Pedro Lima 0",
    "Player_14": "Hughes 2",
    "Player_7": "Neto MUN (A)",
    "Player_2": "Burn BOU (A)",
    "Player_5": "Wirtz 0",
    "Player_6": "B.Fernandes CHE (H)",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Konsa SUN (A)",
    "Player_8": "Elanga BOU (A)",
    "Player_9": "Mateta 12",
    "Player_15": "Tarkowski 3"
  },
  {
    "manager_Name": "238( 1,806,872 )",
    "Teams": "Eze Come Eze Go( Theo Magro )",
    "SXL": "MLT",
    "Latp": "17",
    "Player_1": "Henderson 1",
    "Player_11": "Mateta 6",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "Petrovi\u0107 NEW (H)",
    "Player_13": "Trippier BOU (A)",
    "Player_14": "Reijnders ARS (A)",
    "Player_7": "Scott NEW (H)",
    "Player_2": "Van de Ven 1",
    "Player_5": "Gakpo 2",
    "Player_6": "M.Salah 5",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Gabriel MCI (H)",
    "Player_8": "Xhaka AVL (H)",
    "Player_9": "Gy\u00F6keres MCI (H)",
    "Player_15": "Kerkez 4"
  },
  {
    "manager_Name": "237( 1,904,852 )",
    "Teams": "Taggers FC( Karl Caruana )",
    "SXL": "MLT",
    "Latp": "21",
    "Player_1": "Kelleher FUL (A)",
    "Player_11": "Jo\u00E3o Pedro MUN (A)",
    "Player_10": "Haaland ARS (A)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Est\u00E8ve 4",
    "Player_14": "Marc Guiu MUN (A)",
    "Player_7": "Ndiaye 6",
    "Player_2": "Gabriel MCI (H)",
    "Player_5": "M.Salah 5",
    "Player_6": "Kudus 7",
    "Player_3": "Van de Ven 1",
    "Player_4": "Konsa SUN (A)",
    "Player_8": "Semenyo NEW (H)",
    "Player_9": "Ndoye 2",
    "Player_15": "Wan-Bissaka 0"
  },
  {
    "manager_Name": "237( 1,915,915 )",
    "Teams": "Senglea Gunners( Daryl Ebejer )",
    "SXL": "MLT",
    "Latp": "22",
    "Player_1": "Pope BOU (A)",
    "Player_11": "Jo\u00E3o Pedro MUN (A)",
    "Player_10": "Gy\u00F6keres MCI (H)",
    "Player_12": "Moore AVL (H)",
    "Player_13": "Xhaka AVL (H)",
    "Player_14": "King BRE (H)",
    "Player_7": "Semenyo NEW (H)",
    "Player_2": "Virgil 4",
    "Player_5": "R\u00FAben ARS (A)",
    "Player_6": "M.Salah 10",
    "Player_3": "Gabriel MCI (H)",
    "Player_4": "Lacroix 2",
    "Player_8": "Eze MCI (H)",
    "Player_9": "Ekitik\u00E9 6",
    "Player_15": "Tuanzebe 0"
  },
  {
    "manager_Name": "235( 2,039,766 )",
    "Teams": "RZM765( Cedrik Dalli )",
    "SXL": "MLT",
    "Latp": "11",
    "Player_1": "Verbruggen 1",
    "Player_11": "Wood 2",
    "Player_10": "Haaland ARS (A)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Est\u00E8ve 4",
    "Player_14": "Rodon 2",
    "Player_7": "Palmer MUN (A)",
    "Player_2": "Van de Ven 1",
    "Player_5": "Anderson 4",
    "Player_6": "Rogers SUN (A)",
    "Player_3": "Cucurella MUN (A)",
    "Player_4": "Mu\u00F1oz 2",
    "Player_8": "Johnson 1",
    "Player_9": "Watkins SUN (A)",
    "Player_15": "Reijnders ARS (A)"
  },
  {
    "manager_Name": "233( 2,264,036 )",
    "Teams": "Kind FC( Richard Kind )",
    "SXL": "MLT",
    "Latp": "15",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Haaland ARS (A)",
    "Player_10": "Gy\u00F6keres MCI (H)",
    "Player_12": "Henderson 1",
    "Player_13": "Cucurella MUN (A)",
    "Player_14": "Reijnders ARS (A)",
    "Player_7": "Mbeumo CHE (H)",
    "Player_2": "Lacroix 2",
    "Player_5": "L.Paquet\u00E1 1",
    "Player_6": "Kudus 7",
    "Player_3": "Gabriel MCI (H)",
    "Player_4": "Dunk 3",
    "Player_8": "Ndoye 2",
    "Player_9": "Jo\u00E3o Pedro MUN (A)",
    "Player_15": "Rodon 2"
  },
  {
    "manager_Name": "232( 2,351,338 )",
    "Teams": "Ellul FC( Andrew Ellul )",
    "SXL": "MLT",
    "Latp": "18",
    "Player_1": "Pope BOU (A)",
    "Player_11": "Gy\u00F6keres MCI (H)",
    "Player_10": "Haaland ARS (A)",
    "Player_12": "Henderson 1",
    "Player_13": "Milenkovi\u0107 2",
    "Player_14": "Mitoma 2",
    "Player_7": "Gakpo 2",
    "Player_2": "Gu\u00E9hi 7",
    "Player_5": "Van de Ven 1",
    "Player_6": "Rice MCI (H)",
    "Player_3": "Gabriel MCI (H)",
    "Player_4": "Romero 2",
    "Player_8": "Semenyo NEW (H)",
    "Player_9": "Ekitik\u00E9 6",
    "Player_15": "Douglas Luiz 5"
  },
  {
    "manager_Name": "231( 2,478,147 )",
    "Teams": "Boca Seniors FC( Jake Bonnici )",
    "SXL": "MLT",
    "Latp": "23",
    "Player_1": "Vicario 1",
    "Player_11": "Beto 1",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "Ramsdale BOU (A)",
    "Player_13": "Cherki ARS (A)",
    "Player_14": "Lewis-Skelly MCI (H)",
    "Player_7": "Saka MCI (H)",
    "Player_2": "Kerkez 4",
    "Player_5": "M.Salah 5",
    "Player_6": "Rogers SUN (A)",
    "Player_3": "Bassey BRE (H)",
    "Player_4": "Spence 1",
    "Player_8": "Wharton 5",
    "Player_9": "Ekitik\u00E9 6",
    "Player_15": "Aina 0"
  },
  {
    "manager_Name": "231( 2,518,121 )",
    "Teams": "Gozo Gunners( Jonathan Portelli )",
    "SXL": "MLT",
    "Latp": "17",
    "Player_1": "S\u00E1nchez MUN (A)",
    "Player_11": "Wood 2",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Est\u00E8ve 4",
    "Player_14": "Reijnders ARS (A)",
    "Player_7": "M.Salah 10",
    "Player_2": "Tarkowski 3",
    "Player_5": "Milenkovi\u0107 2",
    "Player_6": "Rogers SUN (A)",
    "Player_3": "Gabriel MCI (H)",
    "Player_4": "Burn BOU (A)",
    "Player_8": "Rice MCI (H)",
    "Player_9": "Semenyo NEW (H)",
    "Player_15": "Marc Guiu MUN (A)"
  },
  {
    "manager_Name": "230( 2,594,499 )",
    "Teams": "Bench Warmers( kevin dalli )",
    "SXL": "MLT",
    "Latp": "22",
    "Player_1": "Petrovi\u0107 NEW (H)",
    "Player_11": "Haaland ARS (A)",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "Kelleher FUL (A)",
    "Player_13": "Kudus 7",
    "Player_14": "Reijnders ARS (A)",
    "Player_7": "Wirtz 0",
    "Player_2": "Gu\u00E9hi 7",
    "Player_5": "Pedro Porro 1",
    "Player_6": "Semenyo NEW (H)",
    "Player_3": "Burn BOU (A)",
    "Player_4": "Calafiori MCI (H)",
    "Player_8": "Gakpo 2",
    "Player_9": "Ekitik\u00E9 12",
    "Player_15": "Est\u00E8ve 4"
  },
  {
    "manager_Name": "229( 2,727,076 )",
    "Teams": "MaltArsenal FC( Claude Spiteri )",
    "SXL": "MLT",
    "Latp": "22",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Jo\u00E3o Pedro MUN (A)",
    "Player_10": "Mateta 6",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Haaland ARS (A)",
    "Player_14": "Enzo MUN (A)",
    "Player_7": "B.Fernandes CHE (H)",
    "Player_2": "Gabriel MCI (H)",
    "Player_5": "Gudmundsson 2",
    "Player_6": "Calafiori MCI (H)",
    "Player_3": "Van de Ven 1",
    "Player_4": "Est\u00E8ve 4",
    "Player_8": "Kudus 7",
    "Player_9": "Gakpo 2",
    "Player_15": "Grealish 1"
  },
  {
    "manager_Name": "229( 2,756,625 )",
    "Teams": "Zubi dubi doo( Julia Schembri )",
    "SXL": "MLT",
    "Latp": "13",
    "Player_1": "Kelleher FUL (A)",
    "Player_11": "Beto 1",
    "Player_10": "Gy\u00F6keres MCI (H)",
    "Player_12": "Verbruggen 1",
    "Player_13": "Wan-Bissaka 0",
    "Player_14": "Dewsbury-Hall 1",
    "Player_7": "Semenyo NEW (H)",
    "Player_2": "Konsa SUN (A)",
    "Player_5": "Eze MCI (H)",
    "Player_6": "M.Salah 5",
    "Player_3": "Saliba MCI (H)",
    "Player_4": "Gu\u00E9hi 7",
    "Player_8": "Elanga BOU (A)",
    "Player_9": "Jo\u00E3o Pedro MUN (A)",
    "Player_15": "Van de Ven 1"
  },
  {
    "manager_Name": "225( 3,255,461 )",
    "Teams": "GunnerPorts( Matthew Portelli )",
    "SXL": "MLT",
    "Latp": "26",
    "Player_1": "D\u00FAbravka 4",
    "Player_11": "Watkins SUN (A)",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "S\u00E1nchez MUN (A)",
    "Player_13": "Dewsbury-Hall 1",
    "Player_14": "De Cuyper 0",
    "Player_7": "Gakpo 2",
    "Player_2": "Konsa SUN (A)",
    "Player_5": "Semenyo NEW (H)",
    "Player_6": "M.Salah 5",
    "Player_3": "N.Williams 8",
    "Player_4": "Van de Ven 1",
    "Player_8": "Madueke MCI (H)",
    "Player_9": "Ekitik\u00E9 6",
    "Player_15": "Diouf 3"
  },
  {
    "manager_Name": "224( 3,384,082 )",
    "Teams": "Mandra United( Steven Silvio )",
    "SXL": "MLT",
    "Latp": "17",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Jo\u00E3o Pedro MUN (A)",
    "Player_10": "Gy\u00F6keres MCI (H)",
    "Player_12": "Lecomte BRE (H)",
    "Player_13": "Konsa SUN (A)",
    "Player_14": "Wan-Bissaka 0",
    "Player_7": "Enzo MUN (A)",
    "Player_2": "Gu\u00E9hi 7",
    "Player_5": "Semenyo NEW (H)",
    "Player_6": "Palmer MUN (A)",
    "Player_3": "Virgil 4",
    "Player_4": "Calafiori MCI (H)",
    "Player_8": "Foden ARS (A)",
    "Player_9": "Ekitik\u00E9 6",
    "Player_15": "Grealish 1"
  },
  {
    "manager_Name": "224( 3,384,082 )",
    "Teams": "The Invincibles 49( Clive Caruana )",
    "SXL": "MLT",
    "Latp": "30",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Mateta 6",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Grealish 1",
    "Player_14": "Reijnders ARS (A)",
    "Player_7": "Semenyo NEW (H)",
    "Player_2": "Virgil 4",
    "Player_5": "Van de Ven 1",
    "Player_6": "M.Salah 10",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "J.Timber MCI (H)",
    "Player_8": "Kudus 7",
    "Player_9": "Gy\u00F6keres MCI (H)",
    "Player_15": "Est\u00E8ve 4"
  },
  {
    "manager_Name": "223( 3,471,414 )",
    "Teams": "Old Havertz Kai Hard( Andy Bonaci )",
    "SXL": "MLT",
    "Latp": "15",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Haaland ARS (A)",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Isak 1",
    "Player_14": "Tosin MUN (A)",
    "Player_7": "Semenyo NEW (H)",
    "Player_2": "Virgil 4",
    "Player_5": "Senesi NEW (H)",
    "Player_6": "Caicedo MUN (A)",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Lacroix 2",
    "Player_8": "Eze MCI (H)",
    "Player_9": "Xavi 1",
    "Player_15": "Dewsbury-Hall 1"
  },
  {
    "manager_Name": "223( 3,483,560 )",
    "Teams": "Harambe FC( Glenn Gauci Borda )",
    "SXL": "MLT",
    "Latp": "16",
    "Player_1": "S\u00E1nchez MUN (A)",
    "Player_11": "Bowen 6",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Wan-Bissaka 0",
    "Player_14": "Est\u00E8ve 4",
    "Player_7": "Reijnders ARS (A)",
    "Player_2": "Van de Ven 1",
    "Player_5": "Semenyo NEW (H)",
    "Player_6": "M.Salah 5",
    "Player_3": "Konsa SUN (A)",
    "Player_4": "Reinildo AVL (H)",
    "Player_8": "Mbeumo CHE (H)",
    "Player_9": "Wood 4",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "222( 3,615,810 )",
    "Teams": "Dial Square( Liam Carabott )",
    "SXL": "MLT",
    "Latp": "18",
    "Player_1": "Sels 3",
    "Player_11": "Watkins SUN (A)",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Iwobi BRE (H)",
    "Player_14": "Virgil 4",
    "Player_7": "Enzo MUN (A)",
    "Player_2": "Livramento BOU (A)",
    "Player_5": "M.Salah 10",
    "Player_6": "Semenyo NEW (H)",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Van de Ven 1",
    "Player_8": "Zubimendi MCI (H)",
    "Player_9": "Wood 2",
    "Player_15": "Wan-Bissaka 0"
  },
  {
    "manager_Name": "221( 3,736,621 )",
    "Teams": "InvinciblesCOYG( Clayton Camilleri )",
    "SXL": "MLT",
    "Latp": "12",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Wilson 1",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "Kelleher FUL (A)",
    "Player_13": "Saka MCI (H)",
    "Player_14": "A\u00EFt-Nouri ARS (A)",
    "Player_7": "Xhaka AVL (H)",
    "Player_2": "Cucurella MUN (A)",
    "Player_5": "M.Salah 5",
    "Player_6": "Grealish 1",
    "Player_3": "Reinildo AVL (H)",
    "Player_4": "Est\u00E8ve 4",
    "Player_8": "Dewsbury-Hall 1",
    "Player_9": "Gy\u00F6keres MCI (H)",
    "Player_15": "Kerkez 4"
  },
  {
    "manager_Name": "220( 3,952,792 )",
    "Teams": "SC CARBINE( yan cutajar )",
    "SXL": "MLT",
    "Latp": "22",
    "Player_1": "Raya MCI (H)",
    "Player_11": "\u0160e\u0161ko CHE (H)",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Konsa SUN (A)",
    "Player_14": "Wan-Bissaka 0",
    "Player_7": "Semenyo NEW (H)",
    "Player_2": "Romero 2",
    "Player_5": "Wirtz 0",
    "Player_6": "Kudus 7",
    "Player_3": "Van de Ven 1",
    "Player_4": "Gu\u00E9hi 7",
    "Player_8": "M.Salah 5",
    "Player_9": "Gy\u00F6keres MCI (H)",
    "Player_15": "Baleba 1"
  },
  {
    "manager_Name": "218( 4,183,737 )",
    "Teams": "Gunz( Kurt Zammit )",
    "SXL": "MLT",
    "Latp": "19",
    "Player_1": "D\u00FAbravka 4",
    "Player_11": "Gy\u00F6keres MCI (H)",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "Sels 3",
    "Player_13": "Wan-Bissaka 0",
    "Player_14": "Ekitik\u00E9 6",
    "Player_7": "M.Salah 10",
    "Player_2": "Senesi NEW (H)",
    "Player_5": "Xhaka AVL (H)",
    "Player_6": "Rice MCI (H)",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Est\u00E8ve 4",
    "Player_8": "Mbeumo CHE (H)",
    "Player_9": "Semenyo NEW (H)",
    "Player_15": "Aina 0"
  },
  {
    "manager_Name": "217( 4,319,827 )",
    "Teams": "Lassie fc( Kirsten Tanti )",
    "SXL": "MLT",
    "Latp": "16",
    "Player_1": "A.Becker 2",
    "Player_11": "Gy\u00F6keres MCI (H)",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "Benitez 0",
    "Player_13": "A\u00EFt-Nouri ARS (A)",
    "Player_14": "Rogers SUN (A)",
    "Player_7": "Semenyo NEW (H)",
    "Player_2": "Pedro Porro 1",
    "Player_5": "Saliba MCI (H)",
    "Player_6": "M.Salah 5",
    "Player_3": "Gabriel MCI (H)",
    "Player_4": "Konsa SUN (A)",
    "Player_8": "Baleba 1",
    "Player_9": "Kudus 7",
    "Player_15": "Y.Chermiti 0"
  },
  {
    "manager_Name": "216( 4,425,334 )",
    "Teams": "Zubi-Dooby Doo( Malcolm Vella Vidal )",
    "SXL": "MLT",
    "Latp": "27",
    "Player_1": "S\u00E1nchez MUN (A)",
    "Player_11": "Gy\u00F6keres MCI (H)",
    "Player_10": "Watkins SUN (A)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Reijnders ARS (A)",
    "Player_14": "Est\u00E8ve 4",
    "Player_7": "Kudus 7",
    "Player_2": "Milenkovi\u0107 2",
    "Player_5": "Diouf 3",
    "Player_6": "Palmer MUN (A)",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Richards 4",
    "Player_8": "M.Salah 10",
    "Player_9": "Rogers SUN (A)",
    "Player_15": "Marc Guiu MUN (A)"
  },
  {
    "manager_Name": "215( 4,590,963 )",
    "Teams": "Zubi Zubi Zooo( Andrew Brincat Ruffini )",
    "SXL": "MLT",
    "Latp": "7",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Jo\u00E3o Pedro MUN (A)",
    "Player_10": "Gy\u00F6keres MCI (H)",
    "Player_12": "Darlow 3",
    "Player_13": "A\u00EFt-Nouri ARS (A)",
    "Player_14": "Marc Guiu MUN (A)",
    "Player_7": "Semenyo NEW (H)",
    "Player_2": "Lewis ARS (A)",
    "Player_5": "Eze MCI (H)",
    "Player_6": "Elanga BOU (A)",
    "Player_3": "Frimpong 0",
    "Player_4": "Pedro Porro 1",
    "Player_8": "Palmer MUN (A)",
    "Player_9": "Ndiaye 6",
    "Player_15": "Alex Moreno SUN (A)"
  },
  {
    "manager_Name": "213( 4,835,813 )",
    "Teams": "Henry\u2019s Heroes( Jean Azzopardi )",
    "SXL": "MLT",
    "Latp": "18",
    "Player_1": "D\u00FAbravka 4",
    "Player_11": "Isak 1",
    "Player_10": "Gy\u00F6keres MCI (H)",
    "Player_12": "Vicario 1",
    "Player_13": "Rice MCI (H)",
    "Player_14": "A\u00EFt-Nouri ARS (A)",
    "Player_7": "Semenyo NEW (H)",
    "Player_2": "Virgil 4",
    "Player_5": "Eze MCI (H)",
    "Player_6": "Elanga BOU (A)",
    "Player_3": "Senesi NEW (H)",
    "Player_4": "Gu\u00E9hi 7",
    "Player_8": "Gakpo 2",
    "Player_9": "Jo\u00E3o Pedro MUN (A)",
    "Player_15": "Cucurella MUN (A)"
  },
  {
    "manager_Name": "211( 5,133,440 )",
    "Teams": "Very Rice( Jake Caruana )",
    "SXL": "MLT",
    "Latp": "46",
    "Player_1": "D\u00FAbravka 4",
    "Player_11": "Mateta 6",
    "Player_10": "Kudus 7",
    "Player_12": "Sels 3",
    "Player_13": "Watkins SUN (A)",
    "Player_14": "Wood 2",
    "Player_7": "Minteh 7",
    "Player_2": "Gabriel MCI (H)",
    "Player_5": "Reinildo AVL (H)",
    "Player_6": "Est\u00E8ve 4",
    "Player_3": "Van de Ven 1",
    "Player_4": "Mu\u00F1oz 2",
    "Player_8": "Semenyo NEW (H)",
    "Player_9": "M.Salah 10",
    "Player_15": "Caicedo MUN (A)"
  },
  {
    "manager_Name": "209( 5,371,047 )",
    "Teams": "Gy\u00F6keres14( Zack Vella )",
    "SXL": "MLT",
    "Latp": "4",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Jo\u00E3o Pedro MUN (A)",
    "Player_10": "Haaland ARS (A)",
    "Player_12": "Heaton CHE (H)",
    "Player_13": "Est\u00E8ve 4",
    "Player_14": "Gudmundsson 4",
    "Player_7": "Wirtz 0",
    "Player_2": "Reinildo AVL (H)",
    "Player_5": "Eze MCI (H)",
    "Player_6": "Palmer MUN (A)",
    "Player_3": "Cash SUN (A)",
    "Player_4": "Virgil 4",
    "Player_8": "Reijnders ARS (A)",
    "Player_9": "Gy\u00F6keres MCI (H)",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "207( 5,630,308 )",
    "Teams": "Kanokk 118( Rodney Azzopardi )",
    "SXL": "MLT",
    "Latp": "13",
    "Player_1": "Henderson 1",
    "Player_11": "Ekitik\u00E9 12",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "Sels 3",
    "Player_13": "Milenkovi\u0107 2",
    "Player_14": "A\u00EFt-Nouri ARS (A)",
    "Player_7": "Reijnders ARS (A)",
    "Player_2": "Cucurella MUN (A)",
    "Player_5": "Rice MCI (H)",
    "Player_6": "Semenyo NEW (H)",
    "Player_3": "Gabriel MCI (H)",
    "Player_4": "Frimpong 0",
    "Player_8": "Enzo MUN (A)",
    "Player_9": "Evanilson NEW (H)",
    "Player_15": "Saka MCI (H)"
  },
  {
    "manager_Name": "206( 5,814,687 )",
    "Teams": "Rice Rice Baby( Ian Falzon )",
    "SXL": "MLT",
    "Latp": "20",
    "Player_1": "S\u00E1nchez MUN (A)",
    "Player_11": "Jo\u00E3o Pedro MUN (A)",
    "Player_10": "Woltemade BOU (A)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Murillo 0",
    "Player_14": "Est\u00E8ve 4",
    "Player_7": "Mbeumo CHE (H)",
    "Player_2": "Van de Ven 1",
    "Player_5": "M.Salah 10",
    "Player_6": "Grealish 1",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Truffert NEW (H)",
    "Player_8": "Wirtz 0",
    "Player_9": "Kudus 7",
    "Player_15": "Marc Guiu MUN (A)"
  },
  {
    "manager_Name": "205( 5,908,155 )",
    "Teams": "Mihawha( Matthew Paris )",
    "SXL": "MLT",
    "Latp": "24",
    "Player_1": "S\u00E1nchez MUN (A)",
    "Player_11": "Watkins SUN (A)",
    "Player_10": "Mateta 6",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Richarlison 6",
    "Player_14": "De Cuyper 0",
    "Player_7": "Reijnders ARS (A)",
    "Player_2": "Van de Ven 1",
    "Player_5": "Senesi NEW (H)",
    "Player_6": "Semenyo NEW (H)",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Milenkovi\u0107 2",
    "Player_8": "M.Salah 10",
    "Player_9": "Anderson 4",
    "Player_15": "Ndiaye 6"
  },
  {
    "manager_Name": "199( 6,600,389 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "23",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Jo\u00E3o Pedro MUN (A)",
    "Player_10": "Gy\u00F6keres MCI (H)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "L.Paquet\u00E1 1",
    "Player_14": "Senesi NEW (H)",
    "Player_7": "Grealish 1",
    "Player_2": "Gabriel MCI (H)",
    "Player_5": "Reijnders ARS (A)",
    "Player_6": "M.Salah 10",
    "Player_3": "Virgil 4",
    "Player_4": "Andersen BRE (H)",
    "Player_8": "Gakpo 2",
    "Player_9": "Mateta 6",
    "Player_15": "Gudmundsson 4"
  },
  {
    "manager_Name": "193( 7,256,330 )",
    "Teams": "Select Team Name( Kurt Bonnici )",
    "SXL": "MLT",
    "Latp": "16",
    "Player_1": "D\u00FAbravka 4",
    "Player_11": "Gy\u00F6keres MCI (H)",
    "Player_10": "Ekitik\u00E9 6",
    "Player_12": "S\u00E1nchez MUN (A)",
    "Player_13": "Reijnders ARS (A)",
    "Player_14": "Heaven CHE (H)",
    "Player_7": "B.Fernandes CHE (H)",
    "Player_2": "Reinildo AVL (H)",
    "Player_5": "Gakpo 2",
    "Player_6": "Palmer MUN (A)",
    "Player_3": "Tosin MUN (A)",
    "Player_4": "Gabriel MCI (H)",
    "Player_8": "Semenyo NEW (H)",
    "Player_9": "Wood 4",
    "Player_15": "Wan-Bissaka 0"
  },
  {
    "manager_Name": "191( 7,450,121 )",
    "Teams": "Jack Nigret( Jack Gatt )",
    "SXL": "MLT",
    "Latp": "1",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Gy\u00F6keres MCI (H)",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "Verbruggen 1",
    "Player_13": "Rogers SUN (A)",
    "Player_14": "Adams NEW (H)",
    "Player_7": "Doku ARS (A)",
    "Player_2": "Van de Ven 1",
    "Player_5": "R\u00FAben ARS (A)",
    "Player_6": "Reijnders ARS (A)",
    "Player_3": "Gabriel MCI (H)",
    "Player_4": "Frimpong 0",
    "Player_8": "Palmer MUN (A)",
    "Player_9": "\u0160e\u0161ko CHE (H)",
    "Player_15": "Mu\u00F1oz 2"
  },
  {
    "manager_Name": "188( 7,703,283 )",
    "Teams": "NLD( Jordi Farrugia )",
    "SXL": "MLT",
    "Latp": "2",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Jo\u00E3o Pedro MUN (A)",
    "Player_10": "\u0160e\u0161ko CHE (H)",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Romero 2",
    "Player_14": "Saka MCI (H)",
    "Player_7": "Eze MCI (H)",
    "Player_2": "Cucurella MUN (A)",
    "Player_5": "James MUN (A)",
    "Player_6": "Elanga BOU (A)",
    "Player_3": "Gabriel MCI (H)",
    "Player_4": "Burn BOU (A)",
    "Player_8": "Gibbs-White 2",
    "Player_9": "Rogers SUN (A)",
    "Player_15": "Evanilson NEW (H)"
  },
  {
    "manager_Name": "183( 8,125,844 )",
    "Teams": "Gorsil Gunners( Gordon Silvio )",
    "SXL": "MLT",
    "Latp": "10",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Gy\u00F6keres MCI (H)",
    "Player_10": "Beto 1",
    "Player_12": "Sels 3",
    "Player_13": "Saka MCI (H)",
    "Player_14": "\u0160e\u0161ko CHE (H)",
    "Player_7": "Eze MCI (H)",
    "Player_2": "Wan-Bissaka 0",
    "Player_5": "Van de Ven 2",
    "Player_6": "Konsa SUN (A)",
    "Player_3": "James MUN (A)",
    "Player_4": "Gu\u00E9hi 7",
    "Player_8": "Palmer MUN (A)",
    "Player_9": "Kluivert NEW (H)",
    "Player_15": "Marmoush ARS (A)"
  }
];