var s = [
  {
    "manager_Name": "235( 2,039,766 )",
    "Teams": "yoo( Nishant Singh )",
    "SXL": "IND",
    "Latp": "14",
    "Player_1": "Vicario 1",
    "Player_11": "Wood 2",
    "Player_10": "Jo\u00E3o Pedro MUN (A)",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "J.Timber MCI (H)",
    "Player_14": "Richarlison 6",
    "Player_7": "Reijnders ARS (A)",
    "Player_2": "Senesi NEW (H)",
    "Player_5": "Livramento BOU (A)",
    "Player_6": "Semenyo NEW (H)",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Cucurella MUN (A)",
    "Player_8": "M.Salah 10",
    "Player_9": "Caicedo MUN (A)",
    "Player_15": "B.Fernandes CHE (H)"
  },
  {
    "manager_Name": "213( 4,865,105 )",
    "Teams": "WMB( Raj Kanango )",
    "SXL": "IND",
    "Latp": "33",
    "Player_1": "Sels 3",
    "Player_11": "Watkins SUN (A)",
    "Player_10": "Wood 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Mbeumo CHE (H)",
    "Player_14": "Reijnders ARS (A)",
    "Player_7": "M.Salah 10",
    "Player_2": "Gu\u00E9hi 5",
    "Player_5": "N.Williams 8",
    "Player_6": "Rogers SUN (A)",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Konsa SUN (A)",
    "Player_8": "Kudus 4",
    "Player_9": "Jo\u00E3o Pedro MUN (A)",
    "Player_15": "Reinildo AVL (H)"
  },
  {
    "manager_Name": "199( 6,600,389 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "23",
    "Player_1": "Raya MCI (H)",
    "Player_11": "Jo\u00E3o Pedro MUN (A)",
    "Player_10": "Gy\u00F6keres MCI (H)",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "L.Paquet\u00E1 1",
    "Player_14": "Senesi NEW (H)",
    "Player_7": "Grealish 1",
    "Player_2": "Gabriel MCI (H)",
    "Player_5": "Reijnders ARS (A)",
    "Player_6": "M.Salah 10",
    "Player_3": "Virgil 4",
    "Player_4": "Andersen BRE (H)",
    "Player_8": "Gakpo 2",
    "Player_9": "Mateta 6",
    "Player_15": "Gudmundsson 2"
  },
  {
    "manager_Name": "189( 7,635,110 )",
    "Teams": "DUFC( Nitesh Kumar Singh )",
    "SXL": "IND",
    "Latp": "23",
    "Player_1": "Pickford 1",
    "Player_11": "Watkins SUN (A)",
    "Player_10": "Welbeck 1",
    "Player_12": "Foderingham 0",
    "Player_13": "Mu\u00F1oz 2",
    "Player_14": "J.Murphy BOU (A)",
    "Player_7": "Mbeumo CHE (H)",
    "Player_2": "Mings SUN (A)",
    "Player_5": "Collins FUL (A)",
    "Player_6": "M.Salah 10",
    "Player_3": "Milenkovi\u0107 2",
    "Player_4": "Mitchell 7",
    "Player_8": "Elanga BOU (A)",
    "Player_9": "Wood 2",
    "Player_15": "Tavernier NEW (H)"
  }
];