var s = [
  {
    "manager_Name": "548( 39,475 )",
    "Teams": "YoureAToneyNoMore( Brendan Kehoe )",
    "SXL": "ENG",
    "Latp": "4",
    "Player_1": "Petrovi\u0107 NFO",
    "Player_11": "Haaland AVL",
    "Player_10": "Grealish TOT",
    "Player_12": "Vicario EVE",
    "Player_13": "Thiago LIV",
    "Player_14": "Dewsbury-Hall TOT",
    "Player_7": "Kudus EVE",
    "Player_2": "Gvardiol AVL",
    "Player_5": "J.Timber CRY",
    "Player_6": "Senesi NFO",
    "Player_3": "Gabriel CRY",
    "Player_4": "Thiaw 2",
    "Player_8": "Semenyo NFO",
    "Player_9": "Enzo 2",
    "Player_15": "Mateta ARS"
  },
  {
    "manager_Name": "530( 134,109 )",
    "Teams": "Kings of Leon Osman( Declan Reilly )",
    "SXL": "ENG",
    "Latp": "20",
    "Player_1": "Raya CRY",
    "Player_11": "Haaland AVL",
    "Player_10": "Bowen 5",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Reijnders AVL",
    "Player_14": "Van de",
    "Player_7": "Saka CRY",
    "Player_2": "Gabriel CRY",
    "Player_5": "Rodon 13",
    "Player_6": "Ndiaye TOT",
    "Player_3": "Senesi NFO",
    "Player_4": "Tarkowski TOT",
    "Player_8": "Semenyo NFO",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Anderson BOU"
  },
  {
    "manager_Name": "518( 274,004 )",
    "Teams": "Goalless( Panagiotis Sfikas )",
    "SXL": "GRC",
    "Latp": "6",
    "Player_1": "Petrovi\u0107 NFO",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Dewsbury-Hall TOT",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Semenyo NFO",
    "Player_2": "Gabriel CRY",
    "Player_5": "Reijnders AVL",
    "Player_6": "Saka CRY",
    "Player_3": "J.Timber CRY",
    "Player_4": "Cucurella 1",
    "Player_8": "B.Fernandes 1",
    "Player_9": "Marc Guiu",
    "Player_15": "Diouf 1"
  },
  {
    "manager_Name": "518( 276,938 )",
    "Teams": "KERAMACTICOS \u26A1( Michael Keramas )",
    "SXL": "GRC",
    "Latp": "6",
    "Player_1": "Raya CRY",
    "Player_11": "Haaland AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Mu\u00F1oz ARS",
    "Player_14": "King 1",
    "Player_7": "Grealish TOT",
    "Player_2": "Virgil BRE",
    "Player_5": "Enzo 2",
    "Player_6": "Kudus EVE",
    "Player_3": "Senesi NFO",
    "Player_4": "J.Timber CRY",
    "Player_8": "Semenyo NFO",
    "Player_9": "Woltemade 2",
    "Player_15": "Tosin 1"
  },
  {
    "manager_Name": "517( 286,765 )",
    "Teams": "Malta Knights( Martin Knight )",
    "SXL": "MLT",
    "Latp": "17",
    "Player_1": "Pope 3",
    "Player_11": "Haaland AVL",
    "Player_10": "Bowen 10",
    "Player_12": "Raya CRY",
    "Player_13": "Konsa MCI",
    "Player_14": "Sarr ARS",
    "Player_7": "Mac Allister",
    "Player_2": "Diouf 1",
    "Player_5": "Burn 2",
    "Player_6": "Semenyo NFO",
    "Player_3": "Gabriel CRY",
    "Player_4": "Gu\u00E9hi ARS",
    "Player_8": "Rice CRY",
    "Player_9": "L.Paquet\u00E1 1",
    "Player_15": "Ekitik\u00E9 BRE"
  },
  {
    "manager_Name": "513( 355,584 )",
    "Teams": "FC Cantona( Nelson Schutt )",
    "SXL": "SWE",
    "Latp": "7",
    "Player_1": "D\u00FAbravka WOL",
    "Player_11": "Wilson 2",
    "Player_10": "Mateta ARS",
    "Player_12": "S\u00E1nchez 1",
    "Player_13": "Patterson MCI",
    "Player_14": "King 1",
    "Player_7": "Saka CRY",
    "Player_2": "Trippier 2",
    "Player_5": "B.Fernandes 1",
    "Player_6": "Semenyo NFO",
    "Player_3": "Gu\u00E9hi ARS",
    "Player_4": "James 1",
    "Player_8": "Mbeumo 1",
    "Player_9": "Haaland AVL",
    "Player_15": "Pond BUR"
  },
  {
    "manager_Name": "513( 360,806 )",
    "Teams": "Wirtz Nightmare( Adam Owens )",
    "SXL": "WAL",
    "Latp": "7",
    "Player_1": "Raya CRY",
    "Player_11": "Bowen 5",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Reijnders AVL",
    "Player_14": "N.Williams BOU",
    "Player_7": "Ndiaye TOT",
    "Player_2": "Van de",
    "Player_5": "Saka CRY",
    "Player_6": "Semenyo NFO",
    "Player_3": "Est\u00E8ve WOL",
    "Player_4": "Pedro Porro",
    "Player_8": "Gakpo BRE",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Andersen 0"
  },
  {
    "manager_Name": "506( 509,592 )",
    "Teams": "Joga Bonito FC( Christophe Peixoto )",
    "SXL": "HUN",
    "Latp": "7",
    "Player_1": "Raya CRY",
    "Player_11": "Woltemade 2",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Anthony WOL",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Reijnders AVL",
    "Player_2": "Chalobah 1",
    "Player_5": "Enzo 2",
    "Player_6": "Semenyo NFO",
    "Player_3": "Gabriel CRY",
    "Player_4": "Senesi NFO",
    "Player_8": "Saka CRY",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Richards ARS"
  },
  {
    "manager_Name": "499( 692,668 )",
    "Teams": "Lallish United( Melwin Holst )",
    "SXL": "SWE",
    "Latp": "6",
    "Player_1": "Raya CRY",
    "Player_11": "Haaland AVL",
    "Player_10": "Woltemade 2",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Thiago LIV",
    "Player_14": "Sarr ARS",
    "Player_7": "Semenyo NFO",
    "Player_2": "J.Timber CRY",
    "Player_5": "Burn 2",
    "Player_6": "Stach 0",
    "Player_3": "Senesi NFO",
    "Player_4": "Gvardiol AVL",
    "Player_8": "Saka CRY",
    "Player_9": "Enzo 2",
    "Player_15": "Gu\u00E9hi ARS"
  },
  {
    "manager_Name": "498( 728,156 )",
    "Teams": "DinamoB( Pietro Menna )",
    "SXL": "MLT",
    "Latp": "5",
    "Player_1": "Vicario EVE",
    "Player_11": "Haaland AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Darlow 0",
    "Player_13": "Senesi NFO",
    "Player_14": "Reijnders AVL",
    "Player_7": "Anthony WOL",
    "Player_2": "Calafiori CRY",
    "Player_5": "Caicedo 2",
    "Player_6": "Semenyo NFO",
    "Player_3": "J.Timber CRY",
    "Player_4": "Cucurella 1",
    "Player_8": "Foden AVL",
    "Player_9": "Gy\u00F6keres CRY",
    "Player_15": "Gu\u00E9hi ARS"
  },
  {
    "manager_Name": "498( 728,156 )",
    "Teams": "Maggnificent15( Derren Maggs )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "Raya CRY",
    "Player_11": "Haaland AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Richards ARS",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Semenyo NFO",
    "Player_2": "Van de",
    "Player_5": "B.Fernandes 1",
    "Player_6": "Reijnders AVL",
    "Player_3": "Senesi NFO",
    "Player_4": "Gabriel CRY",
    "Player_8": "Sarr ARS",
    "Player_9": "Gy\u00F6keres CRY",
    "Player_15": "King 1"
  },
  {
    "manager_Name": "497( 758,986 )",
    "Teams": "Rekegutt United( Eirik Presttun )",
    "SXL": "MLT",
    "Latp": "11",
    "Player_1": "S\u00E1nchez 1",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "King 1",
    "Player_14": "Sarr ARS",
    "Player_7": "Gakpo BRE",
    "Player_2": "James 1",
    "Player_5": "Est\u00E8ve WOL",
    "Player_6": "Cullen WOL",
    "Player_3": "Senesi NFO",
    "Player_4": "Burn 2",
    "Player_8": "Semenyo NFO",
    "Player_9": "Bowen 5",
    "Player_15": "Gu\u00E9hi ARS"
  },
  {
    "manager_Name": "494( 851,400 )",
    "Teams": "kinder mbeumo( Gianluca Tanti )",
    "SXL": "MLT",
    "Latp": "6",
    "Player_1": "Raya CRY",
    "Player_11": "Haaland AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Anderson BOU",
    "Player_14": "Konsa MCI",
    "Player_7": "Enzo 2",
    "Player_2": "Senesi NFO",
    "Player_5": "Semenyo NFO",
    "Player_6": "Ndiaye TOT",
    "Player_3": "Gabriel CRY",
    "Player_4": "Lacroix ARS",
    "Player_8": "Saka CRY",
    "Player_9": "Woltemade 2",
    "Player_15": "Reinildo 2"
  },
  {
    "manager_Name": "494( 857,170 )",
    "Teams": "Bugibba FC 4.0( Adam Azzopardi )",
    "SXL": "MLT",
    "Latp": "5",
    "Player_1": "Raya CRY",
    "Player_11": "\u0160e\u0161ko 1",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Gonzalez BUR",
    "Player_14": "Wan-Bissaka 1",
    "Player_7": "Kudus EVE",
    "Player_2": "Gabriel CRY",
    "Player_5": "Est\u00E8ve WOL",
    "Player_6": "Semenyo NFO",
    "Player_3": "Van de",
    "Player_4": "Gu\u00E9hi ARS",
    "Player_8": "M.Salah BRE",
    "Player_9": "Calvert-Lewin 4",
    "Player_15": "A.Ramsey WOL"
  },
  {
    "manager_Name": "493( 882,213 )",
    "Teams": "The Bees( Tove Ronneb\u00E4ck )",
    "SXL": "MLT",
    "Latp": "5",
    "Player_1": "S\u00E1nchez 1",
    "Player_11": "Haaland AVL",
    "Player_10": "Gy\u00F6keres CRY",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Est\u00E8ve WOL",
    "Player_14": "Diouf 1",
    "Player_7": "Saka CRY",
    "Player_2": "Van de",
    "Player_5": "Mbeumo 1",
    "Player_6": "Reijnders AVL",
    "Player_3": "Lacroix ARS",
    "Player_4": "Virgil BRE",
    "Player_8": "Foden AVL",
    "Player_9": "Semenyo NFO",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "493( 899,290 )",
    "Teams": "Alpha Academy( Jamie Davies )",
    "SXL": "ENG",
    "Latp": "3",
    "Player_1": "S\u00E1nchez 1",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Gy\u00F6keres CRY",
    "Player_12": "Verbruggen 1",
    "Player_13": "Matheus N.",
    "Player_14": "McGinn MCI",
    "Player_7": "Reijnders AVL",
    "Player_2": "Truffert NFO",
    "Player_5": "Kudus EVE",
    "Player_6": "Semenyo NFO",
    "Player_3": "J.Timber CRY",
    "Player_4": "Van de",
    "Player_8": "Gakpo BRE",
    "Player_9": "Haaland AVL",
    "Player_15": "Frimpong BRE"
  },
  {
    "manager_Name": "490( 1,008,365 )",
    "Teams": "Saksa FC( Neil Mifsud )",
    "SXL": "MLT",
    "Latp": "13",
    "Player_1": "Pope 3",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Bowen 5",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Rodon 13",
    "Player_14": "Dewsbury-Hall TOT",
    "Player_7": "Saka CRY",
    "Player_2": "Gabriel CRY",
    "Player_5": "Semenyo NFO",
    "Player_6": "Enzo 2",
    "Player_3": "J.Timber CRY",
    "Player_4": "Cucurella 1",
    "Player_8": "Reijnders AVL",
    "Player_9": "Haaland AVL",
    "Player_15": "Richards ARS"
  },
  {
    "manager_Name": "487( 1,100,644 )",
    "Teams": "Rodalleguianos( Sergio Andres P\u00E9rez Fern\u00E1ndez )",
    "SXL": "MLT",
    "Latp": "5",
    "Player_1": "S\u00E1nchez 1",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland AVL",
    "Player_12": "Sels BOU",
    "Player_13": "A.Murphy 0",
    "Player_14": "Enzo 2",
    "Player_7": "Gakpo BRE",
    "Player_2": "Mu\u00F1oz ARS",
    "Player_5": "Walker-Peters 1",
    "Player_6": "B.Fernandes 1",
    "Player_3": "Milenkovi\u0107 BOU",
    "Player_4": "J.Timber CRY",
    "Player_8": "J.Arias BUR",
    "Player_9": "Zubimendi CRY",
    "Player_15": "Morgan LIV"
  },
  {
    "manager_Name": "487( 1,102,259 )",
    "Teams": "House TarGoalyen( Matteo Farrugia )",
    "SXL": "MLT",
    "Latp": "2",
    "Player_1": "Raya CRY",
    "Player_11": "Watkins MCI",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Est\u00E8ve WOL",
    "Player_14": "Konsa MCI",
    "Player_7": "Mbeumo 1",
    "Player_2": "Saliba CRY",
    "Player_5": "Semenyo NFO",
    "Player_6": "B.Fernandes 1",
    "Player_3": "Virgil BRE",
    "Player_4": "Van de",
    "Player_8": "Anderson BOU",
    "Player_9": "Rogers MCI",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "487( 1,124,150 )",
    "Teams": "XG Stats XI( Will Gunn )",
    "SXL": "ENG",
    "Latp": "10",
    "Player_1": "Pope 3",
    "Player_11": "Haaland AVL",
    "Player_10": "Woltemade 2",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Sarr ARS",
    "Player_14": "Rodon 13",
    "Player_7": "Semenyo NFO",
    "Player_2": "J.Timber CRY",
    "Player_5": "Enzo 2",
    "Player_6": "Saka CRY",
    "Player_3": "Senesi NFO",
    "Player_4": "Gabriel CRY",
    "Player_8": "B.Fernandes 1",
    "Player_9": "Marc Guiu",
    "Player_15": "Alderete 0"
  },
  {
    "manager_Name": "486( 1,170,635 )",
    "Teams": "Toasted Ekitike( Ollie Hatfield )",
    "SXL": "WAL",
    "Latp": "5",
    "Player_1": "D\u00FAbravka WOL",
    "Player_11": "Haaland AVL",
    "Player_10": "Woltemade 2",
    "Player_12": "Kelleher LIV",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Van de",
    "Player_7": "Semenyo NFO",
    "Player_2": "James 1",
    "Player_5": "Caicedo 2",
    "Player_6": "Saka CRY",
    "Player_3": "Calafiori CRY",
    "Player_4": "Est\u00E8ve WOL",
    "Player_8": "Kudus EVE",
    "Player_9": "Ndiaye TOT",
    "Player_15": "Diouf 1"
  },
  {
    "manager_Name": "485( 1,181,591 )",
    "Teams": "REMIBOY( Remeez Persent )",
    "SXL": "ZAF",
    "Latp": "5",
    "Player_1": "Donnarumma AVL",
    "Player_11": "Gy\u00F6keres CRY",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Darlow 0",
    "Player_13": "Frimpong BRE",
    "Player_14": "Bogarde MCI",
    "Player_7": "Caicedo 2",
    "Player_2": "J.Timber CRY",
    "Player_5": "Gakpo BRE",
    "Player_6": "Semenyo NFO",
    "Player_3": "Gvardiol AVL",
    "Player_4": "Cucurella 1",
    "Player_8": "Zubimendi CRY",
    "Player_9": "Haaland AVL",
    "Player_15": "Cullen WOL"
  },
  {
    "manager_Name": "485( 1,182,524 )",
    "Teams": "Ctrl Alt De Ligt( Marlon Vella )",
    "SXL": "MLT",
    "Latp": "15",
    "Player_1": "Petrovi\u0107 NFO",
    "Player_11": "Haaland AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Minteh 1",
    "Player_14": "Richards ARS",
    "Player_7": "Reijnders AVL",
    "Player_2": "Rodon 13",
    "Player_5": "Saka CRY",
    "Player_6": "Sarr ARS",
    "Player_3": "Senesi NFO",
    "Player_4": "Gabriel CRY",
    "Player_8": "Semenyo NFO",
    "Player_9": "Gy\u00F6keres CRY",
    "Player_15": "Alderete 0"
  },
  {
    "manager_Name": "485( 1,185,455 )",
    "Teams": "Gambit( Nicola Frasca )",
    "SXL": "MLT",
    "Latp": "6",
    "Player_1": "S\u00E1nchez 1",
    "Player_11": "Gy\u00F6keres CRY",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Verbruggen 1",
    "Player_13": "Est\u00E8ve WOL",
    "Player_14": "Wan-Bissaka 1",
    "Player_7": "M.Salah BRE",
    "Player_2": "Gabriel CRY",
    "Player_5": "Reijnders AVL",
    "Player_6": "Grealish TOT",
    "Player_3": "Gudmundsson 1",
    "Player_4": "Van de",
    "Player_8": "Caicedo 2",
    "Player_9": "Haaland AVL",
    "Player_15": "L.Miley 2"
  },
  {
    "manager_Name": "482( 1,312,013 )",
    "Teams": "COYS( Zachary Black )",
    "SXL": "CAN",
    "Latp": "4",
    "Player_1": "S\u00E1nchez 1",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Konsa MCI",
    "Player_14": "Nyoni BRE",
    "Player_7": "Kudus EVE",
    "Player_2": "Cucurella 1",
    "Player_5": "Est\u00E8ve WOL",
    "Player_6": "M.Salah BRE",
    "Player_3": "Van de",
    "Player_4": "Gu\u00E9hi ARS",
    "Player_8": "Saka CRY",
    "Player_9": "Anthony WOL",
    "Player_15": "Sherif TOT"
  },
  {
    "manager_Name": "481( 1,388,153 )",
    "Teams": "Ctrl Alt Attack( Laimonas Zukas )",
    "SXL": "LTU",
    "Latp": "3",
    "Player_1": "D\u00FAbravka WOL",
    "Player_11": "Haaland AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Roefs 4",
    "Player_13": "Anderson BOU",
    "Player_14": "Est\u00E8ve WOL",
    "Player_7": "Grealish TOT",
    "Player_2": "Gabriel CRY",
    "Player_5": "B.Fernandes 1",
    "Player_6": "Semenyo NFO",
    "Player_3": "J.Timber CRY",
    "Player_4": "Truffert NFO",
    "Player_8": "Sarr ARS",
    "Player_9": "Mateta ARS",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "480( 1,411,743 )",
    "Teams": "Bebenciukai( Marius z )",
    "SXL": "LTU",
    "Latp": "6",
    "Player_1": "Pope 3",
    "Player_11": "Gy\u00F6keres CRY",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Reijnders AVL",
    "Player_14": "Van de",
    "Player_7": "Kudus EVE",
    "Player_2": "Gudmundsson 1",
    "Player_5": "Semenyo NFO",
    "Player_6": "Eze CRY",
    "Player_3": "J.Timber CRY",
    "Player_4": "Senesi NFO",
    "Player_8": "Xavi EVE",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Mu\u00F1oz ARS"
  },
  {
    "manager_Name": "478( 1,487,116 )",
    "Teams": "DBA Utd( Jim Lennox )",
    "SXL": "ENG",
    "Latp": "4",
    "Player_1": "Raya CRY",
    "Player_11": "Haaland AVL",
    "Player_10": "Richarlison EVE",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Reijnders AVL",
    "Player_14": "Andersen 0",
    "Player_7": "B.Fernandes 1",
    "Player_2": "Gabriel CRY",
    "Player_5": "Foden AVL",
    "Player_6": "Mbeumo 1",
    "Player_3": "Senesi NFO",
    "Player_4": "Tarkowski TOT",
    "Player_8": "Semenyo NFO",
    "Player_9": "Marc Guiu",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "477( 1,535,876 )",
    "Teams": "Hltex Lykoi( Ioannis Poulios )",
    "SXL": "GRC",
    "Latp": "7",
    "Player_1": "S\u00E1nchez 1",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Romero EVE",
    "Player_14": "Anderson BOU",
    "Player_7": "Kudus EVE",
    "Player_2": "Van de",
    "Player_5": "Saka CRY",
    "Player_6": "Reijnders AVL",
    "Player_3": "J.Timber CRY",
    "Player_4": "Senesi NFO",
    "Player_8": "Semenyo NFO",
    "Player_9": "Gy\u00F6keres CRY",
    "Player_15": "Konsa MCI"
  },
  {
    "manager_Name": "477( 1,542,056 )",
    "Teams": "IK S\u00E4tra( Filip Larsson )",
    "SXL": "MLT",
    "Latp": "3",
    "Player_1": "S\u00E1nchez 1",
    "Player_11": "Gy\u00F6keres CRY",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Van de",
    "Player_14": "Est\u00E8ve WOL",
    "Player_7": "Gakpo BRE",
    "Player_2": "Pedro Porro",
    "Player_5": "Semenyo NFO",
    "Player_6": "Reijnders AVL",
    "Player_3": "Virgil BRE",
    "Player_4": "Mu\u00F1oz ARS",
    "Player_8": "Kudus EVE",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Anderson BOU"
  },
  {
    "manager_Name": "476( 1,583,411 )",
    "Teams": "Los Blancos( Eamonn Mifsud )",
    "SXL": "MLT",
    "Latp": "5",
    "Player_1": "Donnarumma AVL",
    "Player_11": "Gy\u00F6keres CRY",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Reijnders AVL",
    "Player_14": "Rodon 13",
    "Player_7": "Semenyo NFO",
    "Player_2": "Gabriel CRY",
    "Player_5": "Caicedo 2",
    "Player_6": "Ndiaye TOT",
    "Player_3": "Senesi NFO",
    "Player_4": "J.Timber CRY",
    "Player_8": "B.Fernandes 1",
    "Player_9": "Haaland AVL",
    "Player_15": "Andersen 0"
  },
  {
    "manager_Name": "475( 1,629,328 )",
    "Teams": "For Better or Wirtz( Theo Dixon )",
    "SXL": "ENG",
    "Latp": "15",
    "Player_1": "Raya CRY",
    "Player_11": "Woltemade 2",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Sarr ARS",
    "Player_14": "Richarlison EVE",
    "Player_7": "Reijnders AVL",
    "Player_2": "Tarkowski TOT",
    "Player_5": "Gabriel CRY",
    "Player_6": "Grealish TOT",
    "Player_3": "Rodon 13",
    "Player_4": "Senesi NFO",
    "Player_8": "Foden AVL",
    "Player_9": "Saka CRY",
    "Player_15": "Mukiele 2"
  },
  {
    "manager_Name": "472( 1,776,036 )",
    "Teams": "AlpayFC( Alpay Al\u0131n )",
    "SXL": "TUR",
    "Latp": "7",
    "Player_1": "Trafford AVL",
    "Player_11": "Thiago LIV",
    "Player_10": "Haaland AVL",
    "Player_12": "Sels BOU",
    "Player_13": "Calafiori CRY",
    "Player_14": "J.Palhinha EVE",
    "Player_7": "Sarr ARS",
    "Player_2": "Saliba CRY",
    "Player_5": "Cucurella 1",
    "Player_6": "Cherki AVL",
    "Player_3": "James 1",
    "Player_4": "Virgil BRE",
    "Player_8": "B.Fernandes 1",
    "Player_9": "Joelinton 4",
    "Player_15": "Solanke EVE"
  },
  {
    "manager_Name": "472( 1,813,045 )",
    "Teams": "Glazebrook FC( Sam Frankland )",
    "SXL": "ENG",
    "Latp": "4",
    "Player_1": "Sels BOU",
    "Player_11": "Haaland AVL",
    "Player_10": "Woltemade 2",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Foster WOL",
    "Player_14": "Gu\u00E9hi ARS",
    "Player_7": "Semenyo NFO",
    "Player_2": "Mu\u00F1oz ARS",
    "Player_5": "Saka CRY",
    "Player_6": "Mbeumo 1",
    "Player_3": "Pedro Porro",
    "Player_4": "Van de",
    "Player_8": "Minteh 1",
    "Player_9": "Kudus EVE",
    "Player_15": "Cash MCI"
  },
  {
    "manager_Name": "471( 1,856,085 )",
    "Teams": "Gedward City FC( Graham Edwards )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "S\u00E1nchez 1",
    "Player_11": "Ekitik\u00E9 BRE",
    "Player_10": "Haaland AVL",
    "Player_12": "Sels BOU",
    "Player_13": "Dewsbury-Hall TOT",
    "Player_14": "Mu\u00F1oz ARS",
    "Player_7": "Doku AVL",
    "Player_2": "Van de",
    "Player_5": "Grealish TOT",
    "Player_6": "Semenyo NFO",
    "Player_3": "Burn 2",
    "Player_4": "Gabriel CRY",
    "Player_8": "Kudus EVE",
    "Player_9": "Woltemade 2",
    "Player_15": "Justin 0"
  },
  {
    "manager_Name": "468( 1,986,195 )",
    "Teams": "What The Nelli( Ben Cordingley )",
    "SXL": "ENG",
    "Latp": "2",
    "Player_1": "Raya CRY",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Mu\u00F1oz ARS",
    "Player_14": "Grealish TOT",
    "Player_7": "Kudus EVE",
    "Player_2": "Virgil BRE",
    "Player_5": "Van de",
    "Player_6": "Semenyo NFO",
    "Player_3": "Gabriel CRY",
    "Player_4": "Senesi NFO",
    "Player_8": "Reijnders AVL",
    "Player_9": "Gy\u00F6keres CRY",
    "Player_15": "Anderson BOU"
  },
  {
    "manager_Name": "467( 2,077,614 )",
    "Teams": "Mo With The Flo( Tom Atkinson )",
    "SXL": "MLT",
    "Latp": "5",
    "Player_1": "D\u00FAbravka WOL",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland AVL",
    "Player_12": "Petrovi\u0107 NFO",
    "Player_13": "Tarkowski TOT",
    "Player_14": "Bassey 1",
    "Player_7": "Reijnders AVL",
    "Player_2": "Chalobah 1",
    "Player_5": "Anderson BOU",
    "Player_6": "Kudus EVE",
    "Player_3": "Gu\u00E9hi ARS",
    "Player_4": "Burn 2",
    "Player_8": "M.Salah BRE",
    "Player_9": "Semenyo NFO",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "464( 2,225,922 )",
    "Teams": "NoRelegationPls( Haykel Mansour )",
    "SXL": "MLT",
    "Latp": "9",
    "Player_1": "Raya CRY",
    "Player_11": "Woltemade 2",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Keane TOT",
    "Player_14": "Stach 0",
    "Player_7": "Semenyo NFO",
    "Player_2": "Senesi NFO",
    "Player_5": "Gvardiol AVL",
    "Player_6": "Neto 5",
    "Player_3": "James 1",
    "Player_4": "Virgil BRE",
    "Player_8": "Saka CRY",
    "Player_9": "B.Fernandes 1",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "463( 2,257,132 )",
    "Teams": "Mc Bryde FC( Mark Mc Bryde )",
    "SXL": "MLT",
    "Latp": "4",
    "Player_1": "S\u00E1nchez 1",
    "Player_11": "Haaland AVL",
    "Player_10": "Gy\u00F6keres CRY",
    "Player_12": "Sels BOU",
    "Player_13": "Tarkowski TOT",
    "Player_14": "Reijnders AVL",
    "Player_7": "Kudus EVE",
    "Player_2": "James 1",
    "Player_5": "Anthony WOL",
    "Player_6": "Gakpo BRE",
    "Player_3": "Calafiori CRY",
    "Player_4": "Senesi NFO",
    "Player_8": "Semenyo NFO",
    "Player_9": "Woltemade 2",
    "Player_15": "Gu\u00E9hi ARS"
  },
  {
    "manager_Name": "460( 2,448,874 )",
    "Teams": "21X.....( John Tiltmann )",
    "SXL": "MLT",
    "Latp": "6",
    "Player_1": "Roefs 4",
    "Player_11": "Haaland AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Petrovi\u0107 NFO",
    "Player_13": "Richarlison EVE",
    "Player_14": "Reijnders AVL",
    "Player_7": "J.Palhinha EVE",
    "Player_2": "Senesi NFO",
    "Player_5": "Van de",
    "Player_6": "Garner TOT",
    "Player_3": "J.Timber CRY",
    "Player_4": "Gu\u00E9hi ARS",
    "Player_8": "Semenyo NFO",
    "Player_9": "M.Salah BRE",
    "Player_15": "Alderete 0"
  },
  {
    "manager_Name": "460( 2,448,874 )",
    "Teams": "Culture FC( CHIDIEBERE OGBUCHI )",
    "SXL": "FRA",
    "Latp": "3",
    "Player_1": "Sels BOU",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland AVL",
    "Player_12": "Henderson ARS",
    "Player_13": "Reijnders AVL",
    "Player_14": "Konsa MCI",
    "Player_7": "Mbeumo 1",
    "Player_2": "Van de",
    "Player_5": "Semenyo NFO",
    "Player_6": "Kudus EVE",
    "Player_3": "Est\u00E8ve WOL",
    "Player_4": "J.Timber CRY",
    "Player_8": "Grealish TOT",
    "Player_9": "Gy\u00F6keres CRY",
    "Player_15": "Wan-Bissaka 1"
  },
  {
    "manager_Name": "457( 2,608,712 )",
    "Teams": "Haribo Scharmix( Conor Maguire )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "Pope 3",
    "Player_11": "Woltemade 2",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Van de",
    "Player_14": "Diouf 1",
    "Player_7": "Saka CRY",
    "Player_2": "Senesi NFO",
    "Player_5": "Kudus EVE",
    "Player_6": "Anderson BOU",
    "Player_3": "Keane TOT",
    "Player_4": "Gabriel CRY",
    "Player_8": "Semenyo NFO",
    "Player_9": "Mateta ARS",
    "Player_15": "Dewsbury-Hall TOT"
  },
  {
    "manager_Name": "455( 2,724,643 )",
    "Teams": "Change Name( Alexander Oyangen Johansen )",
    "SXL": "MLT",
    "Latp": "2",
    "Player_1": "Raya CRY",
    "Player_11": "Haaland AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Mateta ARS",
    "Player_14": "Minteh 1",
    "Player_7": "Reijnders AVL",
    "Player_2": "J.Timber CRY",
    "Player_5": "Virgil BRE",
    "Player_6": "Tarkowski TOT",
    "Player_3": "Gabriel CRY",
    "Player_4": "Van de",
    "Player_8": "Foden AVL",
    "Player_9": "Gakpo BRE",
    "Player_15": "Stach 0"
  },
  {
    "manager_Name": "454( 2,794,850 )",
    "Teams": "wonderkids( Marko Veselinov )",
    "SXL": "MLT",
    "Latp": "7",
    "Player_1": "Pickford TOT",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Woltemade 2",
    "Player_12": "Petrovi\u0107 NFO",
    "Player_13": "Kudus EVE",
    "Player_14": "Mu\u00F1oz ARS",
    "Player_7": "Semenyo NFO",
    "Player_2": "J.Timber CRY",
    "Player_5": "Saka CRY",
    "Player_6": "Grealish TOT",
    "Player_3": "Cucurella 1",
    "Player_4": "Burn 2",
    "Player_8": "Foden AVL",
    "Player_9": "Ekitik\u00E9 BRE",
    "Player_15": "Spence EVE"
  },
  {
    "manager_Name": "452( 2,892,803 )",
    "Teams": "Starship( Olumide Okedusi )",
    "SXL": "EST",
    "Latp": "3",
    "Player_1": "Donnarumma AVL",
    "Player_11": "Haaland AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "P.M.Sarr EVE",
    "Player_14": "Anderson 0",
    "Player_7": "Saka CRY",
    "Player_2": "James 1",
    "Player_5": "Tarkowski TOT",
    "Player_6": "Semenyo NFO",
    "Player_3": "Gabriel CRY",
    "Player_4": "Gu\u00E9hi ARS",
    "Player_8": "Dewsbury-Hall TOT",
    "Player_9": "Reijnders AVL",
    "Player_15": "Foster WOL"
  },
  {
    "manager_Name": "451( 2,960,400 )",
    "Teams": "EarthWindandMaguire( Owen Mawer )",
    "SXL": "ENG",
    "Latp": "7",
    "Player_1": "Raya CRY",
    "Player_11": "Haaland AVL",
    "Player_10": "Woltemade 2",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Chalobah 1",
    "Player_14": "King 1",
    "Player_7": "B.Fernandes 1",
    "Player_2": "Van de",
    "Player_5": "Est\u00E8ve WOL",
    "Player_6": "Enzo 2",
    "Player_3": "Gu\u00E9hi ARS",
    "Player_4": "J.Timber CRY",
    "Player_8": "Semenyo NFO",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Grealish TOT"
  },
  {
    "manager_Name": "449( 3,067,028 )",
    "Teams": "MoPalah FC( Christian Borg )",
    "SXL": "MLT",
    "Latp": "5",
    "Player_1": "S\u00E1nchez 1",
    "Player_11": "Gy\u00F6keres CRY",
    "Player_10": "Haaland AVL",
    "Player_12": "Austin EVE",
    "Player_13": "Clyne ARS",
    "Player_14": "Est\u00E8ve WOL",
    "Player_7": "Caicedo 2",
    "Player_2": "Virgil BRE",
    "Player_5": "M.Salah BRE",
    "Player_6": "Reijnders AVL",
    "Player_3": "Van de",
    "Player_4": "Calafiori CRY",
    "Player_8": "Enzo 2",
    "Player_9": "Rice CRY",
    "Player_15": "Barnes WOL"
  },
  {
    "manager_Name": "448( 3,150,426 )",
    "Teams": "Southmalm Strikers( Johan Hammarstrom )",
    "SXL": "SWE",
    "Latp": "5",
    "Player_1": "S\u00E1nchez 1",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Mateta ARS",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Konsa MCI",
    "Player_14": "Anderson BOU",
    "Player_7": "Kudus EVE",
    "Player_2": "Gabriel CRY",
    "Player_5": "Caicedo 2",
    "Player_6": "Semenyo NFO",
    "Player_3": "N.Williams BOU",
    "Player_4": "Van de",
    "Player_8": "Reijnders AVL",
    "Player_9": "Haaland AVL",
    "Player_15": "Andersen 0"
  },
  {
    "manager_Name": "445( 3,300,847 )",
    "Teams": "Danish Dynamite( Marcus Weicher )",
    "SXL": "DNK",
    "Latp": "4",
    "Player_1": "A.Becker BRE",
    "Player_11": "Gy\u00F6keres CRY",
    "Player_10": "Haaland AVL",
    "Player_12": "Areola 2",
    "Player_13": "Emerson 0",
    "Player_14": "Stamenic BOU",
    "Player_7": "Iwobi 1",
    "Player_2": "Maguire 0",
    "Player_5": "Cash MCI",
    "Player_6": "Amad 1",
    "Player_3": "R\u00FAben AVL",
    "Player_4": "Cucurella 1",
    "Player_8": "Damsgaard LIV",
    "Player_9": "\u0160e\u0161ko 1",
    "Player_15": "Palmer 0"
  },
  {
    "manager_Name": "445( 3,319,269 )",
    "Teams": "Wirtz Case Scenario( Ross Higgens )",
    "SXL": "ENG",
    "Latp": "7",
    "Player_1": "Raya CRY",
    "Player_11": "Ekitik\u00E9 BRE",
    "Player_10": "Woltemade 2",
    "Player_12": "Petrovi\u0107 NFO",
    "Player_13": "Reijnders AVL",
    "Player_14": "Gibbs-White BOU",
    "Player_7": "Kudus EVE",
    "Player_2": "Gabriel CRY",
    "Player_5": "Virgil BRE",
    "Player_6": "Semenyo NFO",
    "Player_3": "Van de",
    "Player_4": "Gvardiol AVL",
    "Player_8": "Cunha 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Gu\u00E9hi ARS"
  }
];