var s = [
  {
    "manager_Name": "511( 408,297 )",
    "Teams": "\u00C7er\u00E7izi Jeshil( Armando Lula )",
    "SXL": "ALB",
    "Latp": "17",
    "Player_1": "Raya CRY",
    "Player_11": "Haaland AVL",
    "Player_10": "Woltemade 2",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Stach 0",
    "Player_14": "Andersen 0",
    "Player_7": "Ndiaye TOT",
    "Player_2": "Gabriel CRY",
    "Player_5": "Saka CRY",
    "Player_6": "Semenyo NFO",
    "Player_3": "Rodon 13",
    "Player_4": "Senesi NFO",
    "Player_8": "Reijnders AVL",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Richards ARS"
  },
  {
    "manager_Name": "501( 647,135 )",
    "Teams": "Tepelena( Joan Hasanmema )",
    "SXL": "ALB",
    "Latp": "7",
    "Player_1": "Raya CRY",
    "Player_11": "Woltemade 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Donnarumma AVL",
    "Player_13": "Reijnders AVL",
    "Player_14": "Gu\u00E9hi ARS",
    "Player_7": "Semenyo NFO",
    "Player_2": "Senesi NFO",
    "Player_5": "Saka CRY",
    "Player_6": "Caicedo 2",
    "Player_3": "James 1",
    "Player_4": "Gabriel CRY",
    "Player_8": "Kudus EVE",
    "Player_9": "Haaland AVL",
    "Player_15": "Alderete 0"
  },
  {
    "manager_Name": "484( 1,230,652 )",
    "Teams": "Renaissance( Sidrit Minxhozi )",
    "SXL": "DNK",
    "Latp": "9",
    "Player_1": "Pope 3",
    "Player_11": "Haaland AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Xhaka 2",
    "Player_14": "Est\u00E8ve WOL",
    "Player_7": "Kudus EVE",
    "Player_2": "J.Timber CRY",
    "Player_5": "Saka CRY",
    "Player_6": "Semenyo NFO",
    "Player_3": "Van de",
    "Player_4": "R\u00FAben AVL",
    "Player_8": "Enzo 2",
    "Player_9": "Woltemade 2",
    "Player_15": "N.Williams BOU"
  },
  {
    "manager_Name": "462( 2,350,588 )",
    "Teams": "Supercampeones( Ronny Nelkenbaum )",
    "SXL": "FRA",
    "Latp": "6",
    "Player_1": "D\u00FAbravka WOL",
    "Player_11": "Woltemade 2",
    "Player_10": "Haaland AVL",
    "Player_12": "Sels BOU",
    "Player_13": "Reijnders AVL",
    "Player_14": "Diouf 1",
    "Player_7": "Semenyo NFO",
    "Player_2": "James 1",
    "Player_5": "Dewsbury-Hall TOT",
    "Player_6": "Kudus EVE",
    "Player_3": "J.Timber CRY",
    "Player_4": "Cucurella 1",
    "Player_8": "Saka CRY",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Alderete 0"
  },
  {
    "manager_Name": "468( 2,000,589 )",
    "Teams": "Park The Bus( Lorin Minxhozi )",
    "SXL": "ENG",
    "Latp": "21",
    "Player_1": "Raya CRY",
    "Player_11": "Kroupi.Jr NFO",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Mateta ARS",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Mbeumo 12",
    "Player_2": "Senesi NFO",
    "Player_5": "B.Fernandes 4",
    "Player_6": "Semenyo NFO",
    "Player_3": "Virgil 3",
    "Player_4": "Burn 2",
    "Player_8": "Reijnders AVL",
    "Player_9": "Saka CRY",
    "Player_15": "Richards ARS"
  },
  {
    "manager_Name": "467( 2,064,218 )",
    "Teams": "5-D( Erald Haxhiu )",
    "SXL": "USA",
    "Latp": "9",
    "Player_1": "Donnarumma AVL",
    "Player_11": "Haaland AVL",
    "Player_10": "Woltemade 2",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Senesi NFO",
    "Player_14": "Xhaka 2",
    "Player_7": "Semenyo NFO",
    "Player_2": "Dorgu -1",
    "Player_5": "Caicedo 2",
    "Player_6": "M.Salah 6",
    "Player_3": "Gu\u00E9hi ARS",
    "Player_4": "Van de",
    "Player_8": "P.M.Sarr EVE",
    "Player_9": "Gy\u00F6keres CRY",
    "Player_15": "Mukiele 2"
  },
  {
    "manager_Name": "451( 2,952,299 )",
    "Teams": "BlueBoys( Ilir Bazaiti )",
    "SXL": "ENG",
    "Latp": "11",
    "Player_1": "D\u00FAbravka WOL",
    "Player_11": "Woltemade 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Areola 2",
    "Player_13": "Diouf 1",
    "Player_14": "L.Miley 2",
    "Player_7": "Semenyo NFO",
    "Player_2": "Senesi NFO",
    "Player_5": "M.Salah 6",
    "Player_6": "Reijnders AVL",
    "Player_3": "James 1",
    "Player_4": "Tuanzebe WOL",
    "Player_8": "Eze CRY",
    "Player_9": "Haaland AVL",
    "Player_15": "Mukiele 2"
  },
  {
    "manager_Name": "461( 2,381,240 )",
    "Teams": "Team name( Sunit Patel )",
    "SXL": "ENG",
    "Latp": "20",
    "Player_1": "Raya CRY",
    "Player_11": "Haaland AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Reijnders AVL",
    "Player_14": "Van de",
    "Player_7": "Saka CRY",
    "Player_2": "Gabriel CRY",
    "Player_5": "Semenyo NFO",
    "Player_6": "Sarr ARS",
    "Player_3": "Senesi NFO",
    "Player_4": "Rodon 13",
    "Player_8": "Kudus EVE",
    "Player_9": "Bowen 5",
    "Player_15": "Andersen 0"
  },
  {
    "manager_Name": "391( 6,639,232 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "14",
    "Player_1": "Raya CRY",
    "Player_11": "Haaland AVL",
    "Player_10": "Gy\u00F6keres CRY",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Xhaka 2",
    "Player_14": "Mukiele 2",
    "Player_7": "Reijnders AVL",
    "Player_2": "Gabriel CRY",
    "Player_5": "Gudmundsson 1",
    "Player_6": "L.Paquet\u00E1 1",
    "Player_3": "Cucurella 1",
    "Player_4": "Senesi NFO",
    "Player_8": "M.Salah 6",
    "Player_9": "Thiago 5",
    "Player_15": "L.Miley 2"
  },
  {
    "manager_Name": "485( 1,212,319 )",
    "Teams": "Zhampagne Football( Camilla Nurkhanov )",
    "SXL": "ENG",
    "Latp": "4",
    "Player_1": "D\u00FAbravka WOL",
    "Player_11": "Foster WOL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "S\u00E1nchez 1",
    "Player_13": "Van de",
    "Player_14": "E.Le F\u00E9e",
    "Player_7": "Semenyo NFO",
    "Player_2": "Gu\u00E9hi ARS",
    "Player_5": "Doku AVL",
    "Player_6": "Kudus EVE",
    "Player_3": "Senesi NFO",
    "Player_4": "Gabriel CRY",
    "Player_8": "Caicedo 2",
    "Player_9": "Haaland AVL",
    "Player_15": "Konsa MCI"
  },
  {
    "manager_Name": "481( 1,359,772 )",
    "Teams": "MAGA( Eni Shtini )",
    "SXL": "ALB",
    "Latp": "8",
    "Player_1": "Raya CRY",
    "Player_11": "Haaland AVL",
    "Player_10": "Mateta ARS",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Marc Guiu",
    "Player_14": "King 1",
    "Player_7": "M.Salah 6",
    "Player_2": "Van de",
    "Player_5": "Senesi NFO",
    "Player_6": "Semenyo NFO",
    "Player_3": "J.Timber CRY",
    "Player_4": "Gu\u00E9hi ARS",
    "Player_8": "Kudus EVE",
    "Player_9": "Gordon 2",
    "Player_15": "Est\u00E8ve WOL"
  },
  {
    "manager_Name": "474( 1,712,652 )",
    "Teams": "\uFFFD( Magi Muco )",
    "SXL": "ALB",
    "Latp": "3",
    "Player_1": "Raya CRY",
    "Player_11": "Gy\u00F6keres CRY",
    "Player_10": "Haaland AVL",
    "Player_12": "Verbruggen 1",
    "Player_13": "Minteh 5",
    "Player_14": "Bassey 1",
    "Player_7": "Enzo 2",
    "Player_2": "Senesi NFO",
    "Player_5": "Foden AVL",
    "Player_6": "Grealish TOT",
    "Player_3": "Dorgu -1",
    "Player_4": "Van de",
    "Player_8": "Saka CRY",
    "Player_9": "Woltemade 2",
    "Player_15": "Rodon 13"
  },
  {
    "manager_Name": "459( 2,486,343 )",
    "Teams": "Kokeqethurit( Daver Berberi )",
    "SXL": "ALB",
    "Latp": "11",
    "Player_1": "Donnarumma AVL",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland AVL",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Dewsbury-Hall TOT",
    "Player_14": "Dorgu -1",
    "Player_7": "Ndiaye TOT",
    "Player_2": "Virgil 3",
    "Player_5": "Lacroix ARS",
    "Player_6": "M.Salah 6",
    "Player_3": "Est\u00E8ve WOL",
    "Player_4": "Pedro Porro",
    "Player_8": "Reijnders AVL",
    "Player_9": "Semenyo NFO",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "457( 2,638,113 )",
    "Teams": "Glasner all over!( Ben Bushby )",
    "SXL": "ENG",
    "Latp": "7",
    "Player_1": "D\u00FAbravka WOL",
    "Player_11": "Haaland AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Vicario EVE",
    "Player_13": "Reijnders AVL",
    "Player_14": "Konsa MCI",
    "Player_7": "Ndiaye TOT",
    "Player_2": "Mu\u00F1oz ARS",
    "Player_5": "Kudus EVE",
    "Player_6": "Saka CRY",
    "Player_3": "Van de",
    "Player_4": "Est\u00E8ve WOL",
    "Player_8": "Neto 5",
    "Player_9": "Gy\u00F6keres CRY",
    "Player_15": "Rodon 13"
  },
  {
    "manager_Name": "522( 216,947 )",
    "Teams": "robby_baggio( Marin Jano )",
    "SXL": "ALB",
    "Latp": "17",
    "Player_1": "Raya CRY",
    "Player_11": "Haaland AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Ndiaye TOT",
    "Player_14": "Calvert-Lewin 2",
    "Player_7": "Eze CRY",
    "Player_2": "Gabriel CRY",
    "Player_5": "Gu\u00E9hi ARS",
    "Player_6": "Kudus EVE",
    "Player_3": "Virgil 3",
    "Player_4": "Pedro Porro",
    "Player_8": "Mbeumo 12",
    "Player_9": "Semenyo NFO",
    "Player_15": "Est\u00E8ve WOL"
  },
  {
    "manager_Name": "401( 6,053,093 )",
    "Teams": "FantaRog( Roger Shehu )",
    "SXL": "NLD",
    "Latp": "7",
    "Player_1": "Raya CRY",
    "Player_11": "Haaland AVL",
    "Player_10": "Mateta ARS",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Reijnders AVL",
    "Player_14": "Gu\u00E9hi ARS",
    "Player_7": "Eze CRY",
    "Player_2": "Pedro Porro",
    "Player_5": "Semenyo NFO",
    "Player_6": "Xavi EVE",
    "Player_3": "Senesi NFO",
    "Player_4": "Cucurella 1",
    "Player_8": "Wirtz 2",
    "Player_9": "Woltemade 4",
    "Player_15": "Est\u00E8ve WOL"
  },
  {
    "manager_Name": "328( 9,640,796 )",
    "Teams": "mayuluuu 5-0( Enio Minxhozi )",
    "SXL": "ALB",
    "Latp": "12",
    "Player_1": "Vicario EVE",
    "Player_11": "Haaland AVL",
    "Player_10": "Woltemade 2",
    "Player_12": "Dennis NFO",
    "Player_13": "Clyne ARS",
    "Player_14": "De Cuyper",
    "Player_7": "Semenyo NFO",
    "Player_2": "R\u00FAben AVL",
    "Player_5": "Eze CRY",
    "Player_6": "B.Fernandes 4",
    "Player_3": "Cucurella 1",
    "Player_4": "Trippier 2",
    "Player_8": "Elanga 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Young MCI"
  },
  {
    "manager_Name": "411( 5,415,028 )",
    "Teams": "Wiggler FC( Andrew Carr )",
    "SXL": "ENG",
    "Latp": "8",
    "Player_1": "Sels BOU",
    "Player_11": "Mateta ARS",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka WOL",
    "Player_13": "Alderete 0",
    "Player_14": "Romero EVE",
    "Player_7": "Anderson BOU",
    "Player_2": "Richards ARS",
    "Player_5": "Reijnders AVL",
    "Player_6": "M.Salah 6",
    "Player_3": "Est\u00E8ve WOL",
    "Player_4": "Pedro Porro",
    "Player_8": "Semenyo NFO",
    "Player_9": "Haaland AVL",
    "Player_15": "Dewsbury-Hall TOT"
  },
  {
    "manager_Name": "311( 10,135,342 )",
    "Teams": "Albi alexander( Bardhyl Minxhozi )",
    "SXL": "ALB",
    "Latp": "32",
    "Player_1": "Raya CRY",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Broja WOL",
    "Player_12": "A.Becker 0",
    "Player_13": "Konsa MCI",
    "Player_14": "Hoever BUR",
    "Player_7": "L.Paquet\u00E1 1",
    "Player_2": "Gvardiol AVL",
    "Player_5": "Elanga 1",
    "Player_6": "M.Salah 12",
    "Player_3": "Cucurella 1",
    "Player_4": "Virgil 3",
    "Player_8": "Mbeumo 12",
    "Player_9": "Johnson EVE",
    "Player_15": "Muniz 0"
  }
];