var s =[
   {
      "manager_Name":"Sahil Lampard",
      "Teams":"MarxUnited",
      "Player_1":"Ramsdale 9",
      "Player_2":"Cancelo 7",
      "Player_3":"White 7",
      "Player_4":"Alexander-Arnold 6",
      "Player_5":"Bernardo 3",
      "Player_6":"Salah 2$ captain",
      "Player_7":"Benrahma 1",
      "Player_8":"Son 7",
      "Player_9":"Hudson-Odoi -",
      "Player_10":"Maupay -",
      "Player_11":"Dennis 2",
      "Player_12":"Sánchez -",
      "Player_13":"Livramento 0",
      "Player_14":"Archer 0",
      "Player_15":"James -",
      "SXL":"44",
      "Bench":"1248",
      "Count  ":"2,107,109"
   },
   {
      "manager_Name":"Saurabh Tamang",
      "Teams":"Lucky FC",
      "Player_1":"Guaita 2",
      "Player_2":"Alexander-Arnold 6",
      "Player_3":"Coady 2",
      "Player_4":"Cancelo 7",
      "Player_5":"Gallagher 1",
      "Player_6":"Bowen 11",
      "Player_7":"Smith Rowe 1",
      "Player_8":"Bernardo 3",
      "Player_9":"Gray 1",
      "Player_10":"Ronaldo 2$ captain",
      "Player_11":"Dennis 2",
      "Player_12":"Sánchez -",
      "Player_13":"Livramento 0",
      "Player_14":"Omobamidele 0",
      "Player_15":"Archer 0",
      "SXL":"38",
      "Bench":"1171",
      "Count  ":"3,341,338"
   },
   {
      "manager_Name":"Pranesh Sharma",
      "Teams":"Immortal FC",
      "Player_1":"Foster 2",
      "Player_2":"Coufal 5",
      "Player_3":"White 7",
      "Player_4":"Alexander-Arnold 6",
      "Player_5":"Raphinha 2",
      "Player_6":"Gallagher 1",
      "Player_7":"De Bruyne 11",
      "Player_8":"Foden 6$ captain",
      "Player_9":"Edouard 1",
      "Player_10":"Dennis 2",
      "Player_11":"Ronaldo 1",
      "Player_12":"Sánchez -",
      "Player_13":"Dier 0",
      "Player_14":"Tsimikas 0",
      "Player_15":"Mount -",
      "SXL":"44",
      "Bench":"1351",
      "Count  ":"824,224"
   },
   {
      "manager_Name":"Sanjeev Kumar",
      "Teams":"GAROBADHA UNITED",
      "Player_1":"Lloris 3",
      "Player_2":"Cancelo 7",
      "Player_3":"Alexander-Arnold 6",
      "Player_4":"Tierney 6",
      "Player_5":"Dalot 2",
      "Player_6":"De Bruyne 22$ captain",
      "Player_7":"Bowen 11",
      "Player_8":"Jota 16",
      "Player_9":"Gallagher 1",
      "Player_10":"Maddison 2",
      "Player_11":"Edouard 1",
      "Player_12":"Foster 2",
      "Player_13":"White 7",
      "Player_14":"Broja 6",
      "Player_15":"Dennis 2",
      "SXL":"77",
      "Bench":"1427",
      "Count  ":"299,061"
   },
   {
      "manager_Name":"Kumar Anku",
      "Teams":"The Børderland Fc",
      "Player_1":"Guaita 2",
      "Player_2":"Alexander-Arnold 6",
      "Player_3":"Mings 1",
      "Player_4":"Varane 2",
      "Player_5":"Cancelo 7",
      "Player_6":"Davies 1",
      "Player_7":"Winks 2",
      "Player_8":"Fernandes 2",
      "Player_9":"King 2",
      "Player_10":"Kane 4$ captain",
      "Player_11":"Ronaldo 1",
      "Player_12":"Bachmann 0",
      "Player_13":"Mbeumo 1",
      "Player_14":"Sissoko 2",
      "Player_15":"Mac Allister -",
      "SXL":"30",
      "Bench":"1290",
      "Count  ":"1,513,268"
   },
   {
      "manager_Name":"Kushal Sahota",
      "Teams":"FC ASSASSINS",
      "Player_1":"Ramsdale 9",
      "Player_2":"Dias 6",
      "Player_3":"Reguilón 1",
      "Player_4":"Duffy -",
      "Player_5":"Jota 16",
      "Player_6":"Bowen 11",
      "Player_7":"Gallagher 1",
      "Player_8":"Salah 1",
      "Player_9":"Dennis 2",
      "Player_10":"Antonio 2",
      "Player_11":"Ronaldo 2$ captain",
      "Player_12":"Steele -",
      "Player_13":"Allan 1",
      "Player_14":"Tsimikas 0",
      "Player_15":"Livramento 0",
      "SXL":"51",
      "Bench":"1170",
      "Count  ":"3,358,931"
   },
   {
      "manager_Name":"Regean Lama",
      "Teams":"BUSBY BABIES 2",
      "Player_1":"Sánchez -",
      "Player_2":"Tierney 6",
      "Player_3":"Coufal 5",
      "Player_4":"Alexander-Arnold 6",
      "Player_5":"Bowen 11",
      "Player_6":"Jota 16",
      "Player_7":"Bernardo 3",
      "Player_8":"Maddison 2",
      "Player_9":"King 4$ captain",
      "Player_10":"Ronaldo 1",
      "Player_11":"Kane 2",
      "Player_12":"Carson 0",
      "Player_13":"Veltman -",
      "Player_14":"Pinnock 1",
      "Player_15":"Ødegaard 3",
      "SXL":"56",
      "Bench":"1363",
      "Count  ":"719,192"
   },
   {
      "manager_Name":"pranam rai",
      "Teams":"SYAKREE FC",
      "Player_1":"Lloris 3",
      "Player_2":"Alexander-Arnold 6",
      "Player_3":"Saïss 1",
      "Player_4":"Dias 6",
      "Player_5":"Ødegaard 3",
      "Player_6":"Bernardo 3",
      "Player_7":"Salah 1",
      "Player_8":"Højbjerg 4",
      "Player_9":"Antonio 2",
      "Player_10":"Dennis 2",
      "Player_11":"Ronaldo 2$ captain",
      "Player_12":"Sánchez -",
      "Player_13":"Mount -",
      "Player_14":"Tsimikas 0",
      "Player_15":"Manquillo 1",
      "SXL":"33",
      "Bench":"1303",
      "Count  ":"1,342,176"
   },
   {
      "manager_Name":"Ashim Lama",
      "Teams":"⚔️FURY⚔️",
      "Player_1":"Lloris 3",
      "Player_2":"Gabriel 14",
      "Player_3":"Cancelo 7",
      "Player_4":"Alexander-Arnold 6",
      "Player_5":"Reguilón 1",
      "Player_6":"Bowen 22$ captain",
      "Player_7":"Coutinho 16",
      "Player_8":"Martinelli 0",
      "Player_9":"Gallagher 1",
      "Player_10":"Antonio 2",
      "Player_11":"Ronaldo 1",
      "Player_12":"Ward 0",
      "Player_13":"Dennis 2",
      "Player_14":"Gray 1",
      "Player_15":"Jansson 1",
      "SXL":"73",
      "Bench":"1354",
      "Count  ":"794,468"
   },
   {
      "manager_Name":"Vivek Pradhan",
      "Teams":"PEPPERBOX83",
      "Player_1":"Raya 2",
      "Player_2":"Cancelo 7",
      "Player_3":"Alexander-Arnold 6",
      "Player_4":"Reguilón 1",
      "Player_5":"Dias 6",
      "Player_6":"Smith Rowe 1",
      "Player_7":"Sissoko 2",
      "Player_8":"Jota 16",
      "Player_9":"Son 14$ captain",
      "Player_10":"Dennis 2",
      "Player_11":"King 2",
      "Player_12":"Sánchez -",
      "Player_13":"Toney 0",
      "Player_14":"Salah 1",
      "Player_15":"Pinnock 1",
      "SXL":"59",
      "Bench":"1397",
      "Count  ":"463,473"
   },
   {
      "manager_Name":"Sibin _",
      "Teams":"F95",
      "Player_1":"Ramsdale 9",
      "Player_2":"Dias 6",
      "Player_3":"Robertson 6",
      "Player_4":"Reguilón 1",
      "Player_5":"Bowen 11",
      "Player_6":"Smith Rowe 1",
      "Player_7":"Bernardo 6$ captain",
      "Player_8":"Lucas Moura 5",
      "Player_9":"Gallagher 1",
      "Player_10":"King 2",
      "Player_11":"Ronaldo 1",
      "Player_12":"Ederson 6",
      "Player_13":"Dennis 2",
      "Player_14":"Alonso -",
      "Player_15":"Rüdiger -",
      "SXL":"49",
      "Bench":"1375",
      "Count  ":"620,622"
   },
   {
      "manager_Name":"Omkar Subba",
      "Teams":"Omk09",
      "Player_1":"Ederson 6",
      "Player_2":"Laporte 6",
      "Player_3":"Robertson 6",
      "Player_4":"Cancelo 7",
      "Player_5":"Coufal 5",
      "Player_6":"Son 7",
      "Player_7":"Coutinho 16",
      "Player_8":"Gallagher 1",
      "Player_9":"Bowen 11",
      "Player_10":"Salah 2$ captain",
      "Player_11":"Saint-Maximin 5",
      "Player_12":"Ramsdale 9",
      "Player_13":"Tierney 6",
      "Player_14":"Dennis 2",
      "Player_15":"Broja 6",
      "SXL":"72",
      "Bench":"1317",
      "Count  ":"1,178,425"
   },
   {
      "manager_Name":"Indrajeet Singh",
      "Teams":"Kung Fu Pandoos",
      "Player_1":"Lloris 3",
      "Player_2":"Tierney 6",
      "Player_3":"Laporte 6",
      "Player_4":"van Dijk 10",
      "Player_5":"Matip 11",
      "Player_6":"Raphinha 2",
      "Player_7":"Sancho 2",
      "Player_8":"Jota 16",
      "Player_9":"Sterling 9",
      "Player_10":"Kane 4$ captain",
      "Player_11":"King 2",
      "Player_12":"Foster 2",
      "Player_13":"White 7",
      "Player_14":"Maupay -",
      "Player_15":"Gilmour 1",
      "SXL":"71",
      "Bench":"1285",
      "Count  ":"1,575,773"
   },
   {
      "manager_Name":"Rishi Thulung",
      "Teams":"PL CG FC",
      "Player_1":"de Gea 4$ captain",
      "Player_2":"Robertson 6",
      "Player_3":"Alexander-Arnold 6",
      "Player_4":"Cancelo 7",
      "Player_5":"Bowen 11",
      "Player_6":"Raphinha 2",
      "Player_7":"Lucas Moura 5",
      "Player_8":"Jota 16",
      "Player_9":"Antonio 2",
      "Player_10":"Dennis 2",
      "Player_11":"King 2",
      "Player_12":"Ramsdale 9",
      "Player_13":"Lamptey -",
      "Player_14":"Marçal 2",
      "Player_15":"Mount -",
      "SXL":"63",
      "Bench":"1350",
      "Count  ":"831,495"
   },
   {
      "manager_Name":"Dipen Thapa",
      "Teams":"BW4_11",
      "Player_1":"Sá 2",
      "Player_2":"Gabriel 14",
      "Player_3":"Alexander-Arnold 6",
      "Player_4":"Dias 6",
      "Player_5":"Gallagher 1",
      "Player_6":"Jota 16",
      "Player_7":"Bernardo 3",
      "Player_8":"Fernandes 2",
      "Player_9":"Dennis 4$ captain",
      "Player_10":"Watkins 2",
      "Player_11":"Antonio 2",
      "Player_12":"Sánchez -",
      "Player_13":"Livramento 0",
      "Player_14":"Tomiyasu 0",
      "Player_15":"Soucek 3",
      "SXL":"58",
      "Bench":"1303",
      "Count  ":"1,346,525"
   },
   {
      "manager_Name":"Nishant Singh",
      "Teams":"beta",
      "Player_1":"Ramsdale 9",
      "Player_2":"Reguilón 1",
      "Player_3":"Cancelo 7",
      "Player_4":"Alexander-Arnold 6",
      "Player_5":"Digne 1",
      "Player_6":"Bowen 11",
      "Player_7":"Fernandes 4$ captain",
      "Player_8":"Jota 16",
      "Player_9":"Foden 3",
      "Player_10":"King 2",
      "Player_11":"Dennis 2",
      "Player_12":"Sánchez -",
      "Player_13":"Smith Rowe 1",
      "Player_14":"Antonio 2",
      "Player_15":"Tomiyasu 0",
      "SXL":"62",
      "Bench":"1307",
      "Count  ":"1,298,608"
   },
   {
      "manager_Name":"Ashish Subba",
      "Teams":"Gustavous Gunner",
      "Player_1":"Ramsdale 9",
      "Player_2":"Maguire 1",
      "Player_3":"Cancelo 7",
      "Player_4":"Alexander-Arnold 6",
      "Player_5":"Gallagher 1",
      "Player_6":"Bernardo 3",
      "Player_7":"Fernandes 2",
      "Player_8":"Raphinha 2",
      "Player_9":"Maddison 2",
      "Player_10":"Dennis 2",
      "Player_11":"Antonio 4$ captain",
      "Player_12":"Foster 2",
      "Player_13":"Lowton 0",
      "Player_14":"Rüdiger -",
      "Player_15":"Obafemi 0",
      "SXL":"39",
      "Bench":"1337",
      "Count  ":"958,934"
   },
   {
      "manager_Name":"Rohan Rai",
      "Teams":"False 9",
      "Player_1":"de Gea 2",
      "Player_2":"Coufal 5",
      "Player_3":"Cancelo 7",
      "Player_4":"Laporte 6",
      "Player_5":"Jota 16",
      "Player_6":"De Bruyne 22$ captain",
      "Player_7":"Raphinha 2",
      "Player_8":"Fernandes 2",
      "Player_9":"Bowen 11",
      "Player_10":"Antonio 2",
      "Player_11":"Dennis 2",
      "Player_12":"Ramsdale 9",
      "Player_13":"Toney 0",
      "Player_14":"Tomiyasu 0",
      "Player_15":"Livramento 0",
      "SXL":"77",
      "Bench":"1492",
      "Count  ":"82,416"
   },
   {
      "manager_Name":"Raj Kanango",
      "Teams":"Weightloss Coach",
      "Player_1":"de Gea 2",
      "Player_2":"Cancelo 7",
      "Player_3":"Alexander-Arnold 6",
      "Player_4":"Tierney 6",
      "Player_5":"Davies 1",
      "Player_6":"De Bruyne 22$ captain",
      "Player_7":"Fernandes 2",
      "Player_8":"Bowen 11",
      "Player_9":"Jota 16",
      "Player_10":"Antonio 2",
      "Player_11":"Dennis 2",
      "Player_12":"Carson 0",
      "Player_13":"Amartey 1",
      "Player_14":"King 2",
      "Player_15":"Bissouma -",
      "SXL":"77",
      "Bench":"1412",
      "Count  ":"377,878"
   },
   {
      "manager_Name":"Gaurav Shrestha",
      "Teams":"Fußball-Mannschaft",
      "Player_1":"de Gea 2",
      "Player_2":"Alexander-Arnold 6",
      "Player_3":"Cancelo 7",
      "Player_4":"Tierney 6",
      "Player_5":"Digne 1",
      "Player_6":"Bowen 11",
      "Player_7":"Gallagher 1",
      "Player_8":"Foden 3",
      "Player_9":"Jota 32$ captain",
      "Player_10":"Raphinha 2",
      "Player_11":"Ronaldo 1",
      "Player_12":"Foster 2",
      "Player_13":"Watkins 2",
      "Player_14":"Antonio 2",
      "Player_15":"Livramento 0",
      "SXL":"72",
      "Bench":"1482",
      "Count  ":"104,358"
   },
   {
      "manager_Name":"Bishal Rai",
      "Teams":"Gooner for Life 037",
      "Player_1":"Ramsdale 9",
      "Player_2":"Alexander-Arnold 6",
      "Player_3":"Coufal 5",
      "Player_4":"Cancelo 7",
      "Player_5":"Foden 3",
      "Player_6":"Gray 1",
      "Player_7":"Jota 16",
      "Player_8":"Bowen 22$ captain",
      "Player_9":"King 2",
      "Player_10":"Antonio 2",
      "Player_11":"Dennis 2",
      "Player_12":"de Gea 2",
      "Player_13":"Trossard -",
      "Player_14":"Rüdiger -",
      "Player_15":"Alonso -",
      "SXL":"75",
      "Bench":"1465",
      "Count  ":"152,337"
   },
   {
      "manager_Name":"RAJIYUNG Sun",
      "Teams":"hansing",
      "Player_1":"Alisson 6",
      "Player_2":"Alexander-Arnold 6",
      "Player_3":"Laporte 6",
      "Player_4":"Cancelo 7",
      "Player_5":"Reguilón 1",
      "Player_6":"Bowen 11",
      "Player_7":"Fernandes 2",
      "Player_8":"Saka 3",
      "Player_9":"De Bruyne 22$ captain",
      "Player_10":"Gallagher 1",
      "Player_11":"Antonio 2",
      "Player_12":"Steer 0",
      "Player_13":"White 7",
      "Player_14":"Dennis 2",
      "Player_15":"Broja 6",
      "SXL":"67",
      "Bench":"1386",
      "Count  ":"540,691"
   },
   {
      "manager_Name":"Ashish Rai",
      "Teams":"Deadhead",
      "Player_1":"Ramsdale 9",
      "Player_2":"Cancelo 7",
      "Player_3":"Digne 1",
      "Player_4":"Alexander-Arnold 6",
      "Player_5":"Bowen 11",
      "Player_6":"Zaha 6",
      "Player_7":"Jota 16",
      "Player_8":"Bernardo 3",
      "Player_9":"Jiménez 2",
      "Player_10":"Kane 4$ captain",
      "Player_11":"João Pedro 1",
      "Player_12":"Foster 2",
      "Player_13":"Smith Rowe 1",
      "Player_14":"Williams 1",
      "Player_15":"Livramento 0",
      "SXL":"66",
      "Bench":"1424",
      "Count  ":"316,002"
   },
   {
      "manager_Name":"prabin kumar",
      "Teams":"Prabin Singh",
      "Player_1":"Foster 2",
      "Player_2":"Dias 6",
      "Player_3":"Shaw 6",
      "Player_4":"Rüdiger -",
      "Player_5":"Townsend 2",
      "Player_6":"Benrahma 1",
      "Player_7":"Son 7",
      "Player_8":"Greenwood 0",
      "Player_9":"Antonio 2",
      "Player_10":"Aubameyang 0$ captain",
      "Player_11":"Jiménez 2",
      "Player_12":"Mendy -",
      "Player_13":"Alonso -",
      "Player_14":"Tsimikas 0",
      "Player_15":"Bissouma -",
      "SXL":"28",
      "Bench":"1000",
      "Count  ":"5,986,614"
   },
   {
      "manager_Name":"Ravish Verma",
      "Teams":"Little Chilli FC",
      "Player_1":"Ramsdale 9",
      "Player_2":"Cancelo 7",
      "Player_3":"Alexander-Arnold 6",
      "Player_4":"Cash 3",
      "Player_5":"White 7",
      "Player_6":"Gallagher 1",
      "Player_7":"Jota 16",
      "Player_8":"Bowen 22$ captain",
      "Player_9":"Fernandes 2",
      "Player_10":"Antonio 2",
      "Player_11":"Ronaldo 1",
      "Player_12":"Guaita 2",
      "Player_13":"King 2",
      "Player_14":"Ramsey 14",
      "Player_15":"Livramento 0",
      "SXL":"76",
      "Bench":"1442",
      "Count  ":"233,331"
   },
   {
      "manager_Name":"Prayash Thapa",
      "Teams":"abcde FC",
      "Player_1":"de Gea 2",
      "Player_2":"Cancelo 7",
      "Player_3":"Alexander-Arnold 6",
      "Player_4":"Laporte 6",
      "Player_5":"Bowen 11",
      "Player_6":"Jota 32$ captain",
      "Player_7":"Fernandes 2",
      "Player_8":"Gray 1",
      "Player_9":"Dennis 2",
      "Player_10":"King 2",
      "Player_11":"Antonio 2",
      "Player_12":"Foster 2",
      "Player_13":"Reguilón 1",
      "Player_14":"Douglas Luiz 2",
      "Player_15":"Alonso -",
      "SXL":"73",
      "Bench":"1527",
      "Count  ":"29,857"
   },
   {
      "manager_Name":"Tenzing Ninjey",
      "Teams":"One Step Beyond 026*",
      "Player_1":"Ramsdale 9",
      "Player_2":"Cancelo 7",
      "Player_3":"Robertson 6",
      "Player_4":"Alexander-Arnold 6",
      "Player_5":"Digne 1",
      "Player_6":"De Bruyne 22$ captain",
      "Player_7":"Fernandes 2",
      "Player_8":"Martinelli 0",
      "Player_9":"Bowen 11",
      "Player_10":"Edouard 1",
      "Player_11":"Watkins 2",
      "Player_12":"Sánchez -",
      "Player_13":"Broja 6",
      "Player_14":"Ait Nouri 1",
      "Player_15":"Ramsey 14",
      "SXL":"67",
      "Bench":"1371",
      "Count  ":"654,994"
   },
   {
      "manager_Name":"Harsh Raval",
      "Teams":"Up the Bees",
      "Player_1":"de Gea 2",
      "Player_2":"Dias 6",
      "Player_3":"Tierney 6",
      "Player_4":"Cancelo 7",
      "Player_5":"Alexander-Arnold 6",
      "Player_6":"Gray 1",
      "Player_7":"Jota 16",
      "Player_8":"Bowen 11",
      "Player_9":"Harrison 2",
      "Player_10":"Watkins 4$ captain",
      "Player_11":"Ronaldo 1",
      "Player_12":"Foster 2",
      "Player_13":"Calvert-Lewin 0",
      "Player_14":"Keane 1",
      "Player_15":"Ramsey 14",
      "SXL":"62",
      "Bench":"1478",
      "Count  ":"115,151"
   },
   {
      "manager_Name":"PRAYAS BAJGAI",
      "Teams":"MCFC@1894",
      "Player_1":"de Gea 2",
      "Player_2":"Alexander-Arnold 6",
      "Player_3":"Dalot 2",
      "Player_4":"Cancelo 7",
      "Player_5":"Davies 1",
      "Player_6":"Gallagher 1",
      "Player_7":"Bowen 11",
      "Player_8":"Jota 16",
      "Player_9":"De Bruyne 11",
      "Player_10":"Martinelli 0",
      "Player_11":"Kane 4$ captain",
      "Player_12":"Foster 2",
      "Player_13":"King 2",
      "Player_14":"Dennis 2",
      "Player_15":"James -",
      "SXL":"61",
      "Bench":"1489",
      "Count  ":"89,449"
   },
   {
      "manager_Name":"AVIJIT DAS",
      "Teams":"Roing FC",
      "Player_1":"de Gea 2",
      "Player_2":"Laporte 6",
      "Player_3":"Cancelo 7",
      "Player_4":"Alexander-Arnold 6",
      "Player_5":"Fernandes 2",
      "Player_6":"Jota 32$ captain",
      "Player_7":"Bowen 11",
      "Player_8":"Gray 1",
      "Player_9":"Dennis 2",
      "Player_10":"Watkins 2",
      "Player_11":"Ronaldo 1",
      "Player_12":"Foster 2",
      "Player_13":"Smith Rowe 1",
      "Player_14":"Burn 0",
      "Player_15":"Livramento 0",
      "SXL":"72",
      "Bench":"1454",
      "Count  ":"189,298"
   },
   {
      "manager_Name":"Abhijeet Singh",
      "Teams":"WEIGHTLOSS COACH",
      "Player_1":"Lloris 3",
      "Player_2":"Dias 6",
      "Player_3":"Cancelo 7",
      "Player_4":"Alexander-Arnold 6",
      "Player_5":"De Bruyne 11",
      "Player_6":"Bowen 11",
      "Player_7":"Jota 16",
      "Player_8":"Raphinha 2",
      "Player_9":"Lacazette 10$ captain",
      "Player_10":"Antonio 2",
      "Player_11":"Dennis 2",
      "Player_12":"Foster 2",
      "Player_13":"Gallagher 1",
      "Player_14":"Manquillo 1",
      "Player_15":"James -",
      "SXL":"76",
      "Bench":"1508",
      "Count  ":"53,510"
   },
   {
      "manager_Name":"SATYAM RAI",
      "Teams":"PINE",
      "Player_1":"Ramsdale 9",
      "Player_2":"Digne 1",
      "Player_3":"Cancelo 7",
      "Player_4":"Alexander-Arnold 6",
      "Player_5":"Jota 16",
      "Player_6":"Gray 1",
      "Player_7":"De Bruyne 22$ captain",
      "Player_8":"Bowen 11",
      "Player_9":"Gallagher 1",
      "Player_10":"Ronaldo 1",
      "Player_11":"King 2",
      "Player_12":"Foster 2",
      "Player_13":"Dennis 2",
      "Player_14":"Alonso -",
      "Player_15":"Livramento 0",
      "SXL":"77",
      "Bench":"1487",
      "Count  ":"93,631"
   }
]