var s = [
  {
    "manager_Name": "927( 56,652 )",
    "Teams": "Rice Rice Baby( kaisler Schembri )",
    "SXL": "MLT",
    "Latp": "57",
    "Player_1": "S\u00E1nchez 10",
    "Player_11": "Haaland 4",
    "Player_10": "Woltemade 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Rogers 2",
    "Player_14": "J.Timber 3",
    "Player_7": "Saka 4",
    "Player_2": "Calafiori 1",
    "Player_5": "Foden 12",
    "Player_6": "Szoboszlai 8",
    "Player_3": "Gu\u00E9hi 8",
    "Player_4": "Thiaw 2",
    "Player_8": "Anderson 4",
    "Player_9": "Thiago 2",
    "Player_15": "Gudmundsson 0"
  },
  {
    "manager_Name": "910( 134,817 )",
    "Teams": "Charlie\u0027s Angels( Charlie Smith )",
    "SXL": "ENG",
    "Latp": "57",
    "Player_1": "Raya 2",
    "Player_11": "Thiago 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Saliba 0",
    "Player_14": "P.M.Sarr 1",
    "Player_7": "Minteh 3",
    "Player_2": "Mukiele 1",
    "Player_5": "Lacroix 2",
    "Player_6": "Saka 4",
    "Player_3": "Cucurella 6",
    "Player_4": "R\u00FAben 14",
    "Player_8": "B.Fernandes 18",
    "Player_9": "Reijnders 1",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "891( 302,622 )",
    "Teams": "Arteta Ball FC( Dylan Camilleri )",
    "SXL": "MLT",
    "Latp": "46",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 4",
    "Player_10": "Welbeck 2",
    "Player_12": "Sels 2",
    "Player_13": "Rice 6",
    "Player_14": "Mu\u00F1oz 0",
    "Player_7": "Ndiaye 8",
    "Player_2": "J.Timber 3",
    "Player_5": "Semenyo 3",
    "Player_6": "Mbeumo 8",
    "Player_3": "Tarkowski 9",
    "Player_4": "Konsa 2",
    "Player_8": "Doku 3",
    "Player_9": "Woltemade 2",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "886( 359,327 )",
    "Teams": "Bend it like Boogie( Ryan Bonello Gatt )",
    "SXL": "MLT",
    "Latp": "74",
    "Player_1": "Sels 2",
    "Player_11": "Mateta 2",
    "Player_10": "Haaland 4",
    "Player_12": "Kelleher 2",
    "Player_13": "Saliba 0",
    "Player_14": "Kroupi.Jr 0",
    "Player_7": "Semenyo 3",
    "Player_2": "Gu\u00E9hi 8",
    "Player_5": "Mbeumo 8",
    "Player_6": "Dewsbury-Hall 16",
    "Player_3": "R\u00FAben 14",
    "Player_4": "J.Timber 3",
    "Player_8": "Gordon 10",
    "Player_9": "Saka 4",
    "Player_15": "Wan-Bissaka 4"
  },
  {
    "manager_Name": "876( 523,173 )",
    "Teams": "TetasSexyReds( Gary Pace )",
    "SXL": "MLT",
    "Latp": "43",
    "Player_1": "Sels 2",
    "Player_11": "Woltemade 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Garnacho 3",
    "Player_14": "Mu\u00F1oz 0",
    "Player_7": "Doku 3",
    "Player_2": "J.Timber 3",
    "Player_5": "Rice 6",
    "Player_6": "Minteh 3",
    "Player_3": "Pedro Porro",
    "Player_4": "Diouf 6",
    "Player_8": "Mbeumo 8",
    "Player_9": "Gy\u00F6keres 1",
    "Player_15": "O\u0027Reilly 6"
  },
  {
    "manager_Name": "875( 540,845 )",
    "Teams": "Taggers FC( Karl Caruana )",
    "SXL": "MLT",
    "Latp": "53",
    "Player_1": "Petrovi\u0107 7",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Semenyo 3",
    "Player_14": "Digne 0",
    "Player_7": "Minteh 3",
    "Player_2": "Mukiele 1",
    "Player_5": "Mbeumo 8",
    "Player_6": "Ndiaye 8",
    "Player_3": "James 6",
    "Player_4": "Gu\u00E9hi 8",
    "Player_8": "Saka 4",
    "Player_9": "Thiago 2",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "871( 602,006 )",
    "Teams": "Ellul FC( Andrew Ellul )",
    "SXL": "MLT",
    "Latp": "50",
    "Player_1": "Henderson 3",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago 2",
    "Player_12": "Pope 0",
    "Player_13": "Gabriel 0",
    "Player_14": "Mitoma 0",
    "Player_7": "Mbeumo 8",
    "Player_2": "Gu\u00E9hi 8",
    "Player_5": "Van de",
    "Player_6": "Rice 6",
    "Player_3": "Milenkovi\u0107 0",
    "Player_4": "Burn 7",
    "Player_8": "Semenyo 6",
    "Player_9": "Mateta 2",
    "Player_15": "Caicedo 0"
  },
  {
    "manager_Name": "871( 604,349 )",
    "Teams": "diavoli 11( Paul Micallef )",
    "SXL": "MLT",
    "Latp": "67",
    "Player_1": "Donnarumma 6",
    "Player_11": "Thiago 2",
    "Player_10": "Haaland 4",
    "Player_12": "Setford 0",
    "Player_13": "Caicedo 0",
    "Player_14": "Mu\u00F1oz 0",
    "Player_7": "Bruno G.",
    "Player_2": "J.Timber 3",
    "Player_5": "Reijnders 1",
    "Player_6": "Semenyo 3",
    "Player_3": "Senesi 8",
    "Player_4": "Chalobah 11",
    "Player_8": "B.Fernandes 18",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Byram 0"
  },
  {
    "manager_Name": "868( 662,367 )",
    "Teams": "Bench Warmers( kevin dalli )",
    "SXL": "MLT",
    "Latp": "51",
    "Player_1": "Petrovi\u0107 7",
    "Player_11": "Haaland 4",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Kelleher 2",
    "Player_13": "Thiago 2",
    "Player_14": "Gusto 7",
    "Player_7": "Gakpo 2",
    "Player_2": "Gu\u00E9hi 8",
    "Player_5": "Merino 1",
    "Player_6": "Saka 4",
    "Player_3": "Gvardiol 12",
    "Player_4": "Van de",
    "Player_8": "Doku 3",
    "Player_9": "Semenyo 3",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "863( 774,500 )",
    "Teams": "MaltArsenal FC( Claude Spiteri )",
    "SXL": "MLT",
    "Latp": "46",
    "Player_1": "Donnarumma 6",
    "Player_11": "Welbeck 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Semenyo 3",
    "Player_14": "Senesi 8",
    "Player_7": "Enzo 3",
    "Player_2": "J.Timber 3",
    "Player_5": "Mbeumo 8",
    "Player_6": "Grealish 3",
    "Player_3": "Calafiori 1",
    "Player_4": "Gu\u00E9hi 8",
    "Player_8": "Rice 6",
    "Player_9": "Mateta 2",
    "Player_15": "Gudmundsson 0"
  },
  {
    "manager_Name": "861( 819,809 )",
    "Teams": "Slika FC( Kyle Gatt )",
    "SXL": "MLT",
    "Latp": "44",
    "Player_1": "Lammens 2",
    "Player_11": "Gy\u00F6keres 1",
    "Player_10": "Woltemade 2",
    "Player_12": "Darlow 0",
    "Player_13": "Szoboszlai 8",
    "Player_14": "Pedro Porro",
    "Player_7": "Ndiaye 8",
    "Player_2": "Virgil 2",
    "Player_5": "Reijnders 1",
    "Player_6": "Eze 1",
    "Player_3": "Cucurella 6",
    "Player_4": "R\u00FAben 14",
    "Player_8": "Enzo 3",
    "Player_9": "Haaland 4",
    "Player_15": "Hartman 0"
  },
  {
    "manager_Name": "859( 867,409 )",
    "Teams": "RZM765( Cedrik Dalli )",
    "SXL": "MLT",
    "Latp": "46",
    "Player_1": "Verbruggen 3",
    "Player_11": "Woltemade 2",
    "Player_10": "Mateta 2",
    "Player_12": "Roefs 1",
    "Player_13": "Rice 6",
    "Player_14": "Mu\u00F1oz 0",
    "Player_7": "Foden 12",
    "Player_2": "Van de",
    "Player_5": "Bruno G.",
    "Player_6": "Grealish 3",
    "Player_3": "Calafiori 1",
    "Player_4": "Rodon 1",
    "Player_8": "Neto 2",
    "Player_9": "Haaland 4",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "855( 986,901 )",
    "Teams": "Kind FC( Richard Kind )",
    "SXL": "MLT",
    "Latp": "40",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta 2",
    "Player_12": "Henderson 3",
    "Player_13": "Rodon 1",
    "Player_14": "Jo\u00E3o Pedro",
    "Player_7": "Grealish 3",
    "Player_2": "Dunk 1",
    "Player_5": "Reijnders 1",
    "Player_6": "Eze 1",
    "Player_3": "Milenkovi\u0107 0",
    "Player_4": "Lacroix 2",
    "Player_8": "Mbeumo 8",
    "Player_9": "Dewsbury-Hall 16",
    "Player_15": "Cucurella 6"
  },
  {
    "manager_Name": "854( 999,892 )",
    "Teams": "kurt slika( Kurt Gatt )",
    "SXL": "MLT",
    "Latp": "63",
    "Player_1": "Raya 2",
    "Player_11": "Gy\u00F6keres 1",
    "Player_10": "Welbeck 2",
    "Player_12": "Jos\u00E9 S\u00E1",
    "Player_13": "J.Palhinha 1",
    "Player_14": "Cucurella 6",
    "Player_7": "Dewsbury-Hall 16",
    "Player_2": "Gu\u00E9hi 8",
    "Player_5": "Mbeumo 8",
    "Player_6": "Semenyo 3",
    "Player_3": "Virgil 2",
    "Player_4": "R\u00FAben 14",
    "Player_8": "Doku 3",
    "Player_9": "Haaland 4",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "837( 1,526,643 )",
    "Teams": "Gozo Gunners( Jonathan Portelli )",
    "SXL": "MLT",
    "Latp": "46",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Mu\u00F1oz 0",
    "Player_14": "Senesi 8",
    "Player_7": "Bruno G.",
    "Player_2": "Virgil 2",
    "Player_5": "Rice 6",
    "Player_6": "Reijnders 1",
    "Player_3": "Burn 7",
    "Player_4": "James 6",
    "Player_8": "Saka 4",
    "Player_9": "Welbeck 2",
    "Player_15": "Stach 12"
  },
  {
    "manager_Name": "832( 1,709,218 )",
    "Teams": "Let him cook( Henry Adjei )",
    "SXL": "MLT",
    "Latp": "34",
    "Player_1": "Raya 2",
    "Player_11": "Thiago 2",
    "Player_10": "Haaland 4",
    "Player_12": "Kelleher 2",
    "Player_13": "Mu\u00F1oz 0",
    "Player_14": "Xhaka 2",
    "Player_7": "Semenyo 3",
    "Player_2": "Gu\u00E9hi 8",
    "Player_5": "P.M.Sarr 1",
    "Player_6": "Saka 4",
    "Player_3": "Est\u00E8ve 3",
    "Player_4": "Virgil 2",
    "Player_8": "Kudus 3",
    "Player_9": "Mateta 2",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "826( 1,918,944 )",
    "Teams": "The Invincibles 49( Clive Caruana )",
    "SXL": "MLT",
    "Latp": "49",
    "Player_1": "Raya 2",
    "Player_11": "Woltemade 2",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Mbeumo 8",
    "Player_14": "Mu\u00F1oz 0",
    "Player_7": "Rice 6",
    "Player_2": "J.Timber 3",
    "Player_5": "Semenyo 3",
    "Player_6": "Minteh 3",
    "Player_3": "Van de",
    "Player_4": "O\u0027Reilly 6",
    "Player_8": "Foden 12",
    "Player_9": "Haaland 4",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "825( 1,957,509 )",
    "Teams": "gunner_xi( Justin kind )",
    "SXL": "MLT",
    "Latp": "36",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Reinildo 0",
    "Player_14": "Sarr 0",
    "Player_7": "Gakpo 2",
    "Player_2": "Calafiori 1",
    "Player_5": "Doku 3",
    "Player_6": "Enzo 3",
    "Player_3": "Cucurella 6",
    "Player_4": "Gu\u00E9hi 8",
    "Player_8": "Kudus 3",
    "Player_9": "Woltemade 2",
    "Player_15": "Senesi 8"
  },
  {
    "manager_Name": "825( 1,960,103 )",
    "Teams": "Old Havertz Kai Hard( Andy Bonaci )",
    "SXL": "MLT",
    "Latp": "40",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Dewsbury-Hall 16",
    "Player_14": "Mu\u00F1oz 0",
    "Player_7": "Enzo 3",
    "Player_2": "Virgil 2",
    "Player_5": "Mbeumo 8",
    "Player_6": "Anderson 4",
    "Player_3": "Senesi 8",
    "Player_4": "J.Timber 3",
    "Player_8": "Semenyo 3",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Mukiele 1"
  },
  {
    "manager_Name": "813( 2,466,264 )",
    "Teams": "Noni your business( Owen Farrugia )",
    "SXL": "MLT",
    "Latp": "39",
    "Player_1": "Raya 2",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Rice 6",
    "Player_14": "Andersen 1",
    "Player_7": "Amad 6",
    "Player_2": "J.Timber 3",
    "Player_5": "Doku 3",
    "Player_6": "Ndiaye 8",
    "Player_3": "James 6",
    "Player_4": "Kerkez 1",
    "Player_8": "Grealish 3",
    "Player_9": "Haaland 4",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "810( 2,583,065 )",
    "Teams": "Gunz( Kurt Zammit )",
    "SXL": "MLT",
    "Latp": "54",
    "Player_1": "Donnarumma 6",
    "Player_11": "Haaland 2",
    "Player_10": "Woltemade 4",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Isidor 1",
    "Player_14": "Senesi 8",
    "Player_7": "Semenyo 3",
    "Player_2": "Gvardiol 12",
    "Player_5": "Saka 4",
    "Player_6": "Rice 6",
    "Player_3": "Gu\u00E9hi 8",
    "Player_4": "J.Timber 3",
    "Player_8": "Tavernier 5",
    "Player_9": "Anthony 1",
    "Player_15": "Cash 9"
  },
  {
    "manager_Name": "809( 2,616,194 )",
    "Teams": "Hamrun Gunners( Mark Monseigneur )",
    "SXL": "MLT",
    "Latp": "42",
    "Player_1": "Pickford 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 2",
    "Player_12": "Henderson 3",
    "Player_13": "Walker 0",
    "Player_14": "Virgil 2",
    "Player_7": "Cullen 2",
    "Player_2": "Mykolenko 5",
    "Player_5": "Rice 6",
    "Player_6": "Saka 4",
    "Player_3": "Toti 1",
    "Player_4": "Pedro Porro",
    "Player_8": "Trossard 6",
    "Player_9": "Woltemade 4",
    "Player_15": "Sarr 0"
  },
  {
    "manager_Name": "804( 2,847,089 )",
    "Teams": "GunnerPorts( Matthew Portelli )",
    "SXL": "MLT",
    "Latp": "48",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Haaland 4",
    "Player_10": "Woltemade 2",
    "Player_12": "Pope 0",
    "Player_13": "Semenyo 3",
    "Player_14": "Senesi 8",
    "Player_7": "Eze 1",
    "Player_2": "Hincapie 3",
    "Player_5": "Minteh 3",
    "Player_6": "Mbeumo 8",
    "Player_3": "Gvardiol 12",
    "Player_4": "Lacroix 2",
    "Player_8": "Ndiaye 8",
    "Player_9": "Mateta 2",
    "Player_15": "Gudmundsson 0"
  },
  {
    "manager_Name": "804( 2,858,760 )",
    "Teams": "Sultan Army( Julian Sultana )",
    "SXL": "MLT",
    "Latp": "59",
    "Player_1": "Pickford 6",
    "Player_11": "Welbeck 2",
    "Player_10": "Thiago 4",
    "Player_12": "Donnarumma 6",
    "Player_13": "Gabriel 0",
    "Player_14": "Mu\u00F1oz 0",
    "Player_7": "Doku 3",
    "Player_2": "Thiaw 2",
    "Player_5": "Gakpo 2",
    "Player_6": "Mbeumo 8",
    "Player_3": "Calafiori 1",
    "Player_4": "Chalobah 11",
    "Player_8": "B.Fernandes 18",
    "Player_9": "Mateta 2",
    "Player_15": "Semenyo 3"
  },
  {
    "manager_Name": "804( 2,862,297 )",
    "Teams": "Senglea Gunners( Daryl Ebejer )",
    "SXL": "MLT",
    "Latp": "42",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 2",
    "Player_10": "Haaland 4",
    "Player_12": "Moore 0",
    "Player_13": "Rice 6",
    "Player_14": "Alderete 1",
    "Player_7": "King 1",
    "Player_2": "Virgil 2",
    "Player_5": "Neto 2",
    "Player_6": "Semenyo 3",
    "Player_3": "R\u00FAben 14",
    "Player_4": "Gu\u00E9hi 8",
    "Player_8": "Xhaka 2",
    "Player_9": "Welbeck 2",
    "Player_15": "Gabriel 0"
  },
  {
    "manager_Name": "803( 2,891,097 )",
    "Teams": "Select Team Name( Kurt Bonnici )",
    "SXL": "MLT",
    "Latp": "38",
    "Player_1": "Donnarumma 6",
    "Player_11": "Haaland 4",
    "Player_10": "Woltemade 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Mu\u00F1oz 0",
    "Player_14": "Xhaka 2",
    "Player_7": "Saka 4",
    "Player_2": "Virgil 2",
    "Player_5": "Anderson 4",
    "Player_6": "Semenyo 3",
    "Player_3": "Thiaw 2",
    "Player_4": "J.Timber 3",
    "Player_8": "Rice 6",
    "Player_9": "Thiago 2",
    "Player_15": "Gudmundsson 0"
  },
  {
    "manager_Name": "802( 2,942,775 )",
    "Teams": "Very Rice( Jake Caruana )",
    "SXL": "MLT",
    "Latp": "52",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Semenyo 3",
    "Player_14": "Senesi 8",
    "Player_7": "Doku 3",
    "Player_2": "J.Timber 3",
    "Player_5": "Saka 4",
    "Player_6": "Bruno G.",
    "Player_3": "Chalobah 11",
    "Player_4": "Gu\u00E9hi 8",
    "Player_8": "Minteh 3",
    "Player_9": "Welbeck 2",
    "Player_15": "Gudmundsson 0"
  },
  {
    "manager_Name": "797( 3,154,289 )",
    "Teams": "Sammygooner****( Sammy Vella )",
    "SXL": "MLT",
    "Latp": "36",
    "Player_1": "S\u00E1nchez 10",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Konsa 2",
    "Player_14": "Hume 1",
    "Player_7": "Semenyo 3",
    "Player_2": "Virgil 2",
    "Player_5": "Eze 1",
    "Player_6": "Reijnders 1",
    "Player_3": "J.Timber 3",
    "Player_4": "Van de",
    "Player_8": "Kudus 3",
    "Player_9": "Gy\u00F6keres 1",
    "Player_15": "Sarr 0"
  },
  {
    "manager_Name": "793( 3,353,237 )",
    "Teams": "Eze Come Eze Go( Theo Magro )",
    "SXL": "MLT",
    "Latp": "38",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 2",
    "Player_12": "Petrovi\u0107 7",
    "Player_13": "Mu\u00F1oz 0",
    "Player_14": "Anthony 1",
    "Player_7": "Semenyo 3",
    "Player_2": "Lacroix 2",
    "Player_5": "Xhaka 2",
    "Player_6": "Saka 4",
    "Player_3": "Chalobah 11",
    "Player_4": "J.Timber 3",
    "Player_8": "Doku 3",
    "Player_9": "Mateta 2",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "792( 3,393,512 )",
    "Teams": "Zubi-Dooby Doo( Malcolm Vella Vidal )",
    "SXL": "MLT",
    "Latp": "52",
    "Player_1": "Henderson 3",
    "Player_11": "Bowen 9",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Tavernier 5",
    "Player_14": "Acheampong 0",
    "Player_7": "Foden 12",
    "Player_2": "Virgil 2",
    "Player_5": "Saka 4",
    "Player_6": "Enzo 3",
    "Player_3": "J.Timber 3",
    "Player_4": "Cash 9",
    "Player_8": "Reijnders 1",
    "Player_9": "Thiago 2",
    "Player_15": "S.Bueno 0"
  },
  {
    "manager_Name": "790( 3,466,873 )",
    "Teams": "Clarky FC( Carl Clark )",
    "SXL": "ENG",
    "Latp": "25",
    "Player_1": "Leno 2",
    "Player_11": "Haaland 4",
    "Player_10": "Gy\u00F6keres 1",
    "Player_12": "Slonina 0",
    "Player_13": "Mayenda 0",
    "Player_14": "Murillo 0",
    "Player_7": "Saka 4",
    "Player_2": "Konat\u00E9 1",
    "Player_5": "Cullen 2",
    "Player_6": "Enzo 3",
    "Player_3": "Sch\u00E4r 2",
    "Player_4": "Mitchell 2",
    "Player_8": "Semenyo 3",
    "Player_9": "Eze 1",
    "Player_15": "Spence 6"
  },
  {
    "manager_Name": "790( 3,478,370 )",
    "Teams": "matthew 14( matthew borg )",
    "SXL": "MLT",
    "Latp": "45",
    "Player_1": "Ramsdale 2",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta 2",
    "Player_12": "King 0",
    "Player_13": "Pedro Lima",
    "Player_14": "Caicedo 0",
    "Player_7": "Wirtz 3",
    "Player_2": "Tarkowski 9",
    "Player_5": "Cunha 5",
    "Player_6": "Grealish 3",
    "Player_3": "Pedro Porro",
    "Player_4": "Burn 7",
    "Player_8": "Semenyo 3",
    "Player_9": "Woltemade 2",
    "Player_15": "Konsa 2"
  },
  {
    "manager_Name": "784( 3,766,996 )",
    "Teams": "Kanokk 118( Rodney Azzopardi )",
    "SXL": "MLT",
    "Latp": "49",
    "Player_1": "Donnarumma 6",
    "Player_11": "Thiago 2",
    "Player_10": "Watkins 2",
    "Player_12": "Henderson 3",
    "Player_13": "Evanilson 2",
    "Player_14": "Mu\u00F1oz 0",
    "Player_7": "Reijnders 1",
    "Player_2": "Cucurella 6",
    "Player_5": "Semenyo 3",
    "Player_6": "Enzo 3",
    "Player_3": "J.Timber 3",
    "Player_4": "Cash 9",
    "Player_8": "Saka 8",
    "Player_9": "Rice 6",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "775( 4,208,663 )",
    "Teams": "SC CARBINE( yan cutajar )",
    "SXL": "MLT",
    "Latp": "51",
    "Player_1": "Raya 2",
    "Player_11": "Woltemade 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Mu\u00F1oz 0",
    "Player_14": "Caicedo 0",
    "Player_7": "Semenyo 3",
    "Player_2": "Cucurella 6",
    "Player_5": "Milenkovi\u0107 0",
    "Player_6": "B.Fernandes 18",
    "Player_3": "Wan-Bissaka 4",
    "Player_4": "Gu\u00E9hi 8",
    "Player_8": "Gibbs-White 2",
    "Player_9": "Thiago 2",
    "Player_15": "Baleba 1"
  },
  {
    "manager_Name": "773( 4,292,763 )",
    "Teams": "Dial Square( Liam Carabott )",
    "SXL": "MLT",
    "Latp": "46",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Thiago 2",
    "Player_10": "Haaland 4",
    "Player_12": "Roefs 1",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Mu\u00F1oz 0",
    "Player_7": "Minteh 3",
    "Player_2": "J.Timber 3",
    "Player_5": "Bruno G.",
    "Player_6": "Semenyo 3",
    "Player_3": "Van de",
    "Player_4": "Burn 7",
    "Player_8": "Zubimendi 2",
    "Player_9": "Enzo 3",
    "Player_15": "Wan-Bissaka 4"
  },
  {
    "manager_Name": "757( 5,041,304 )",
    "Teams": "Lions( Daniel Ferriggi )",
    "SXL": "MLT",
    "Latp": "45",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 2",
    "Player_10": "Haaland 4",
    "Player_12": "Verbruggen 3",
    "Player_13": "Enzo 3",
    "Player_14": "Mu\u00F1oz 0",
    "Player_7": "Semenyo 3",
    "Player_2": "O\u0027Reilly 6",
    "Player_5": "Rice 6",
    "Player_6": "Bruno G.",
    "Player_3": "Gusto 7",
    "Player_4": "Lacroix 2",
    "Player_8": "Merino 1",
    "Player_9": "Thiago 2",
    "Player_15": "Keane 9"
  },
  {
    "manager_Name": "755( 5,125,106 )",
    "Teams": "Mandra United( Steven Silvio )",
    "SXL": "MLT",
    "Latp": "38",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 2",
    "Player_10": "Thiago 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Virgil 2",
    "Player_14": "Tavernier 5",
    "Player_7": "Foden 12",
    "Player_2": "Calafiori 1",
    "Player_5": "Enzo 3",
    "Player_6": "Semenyo 3",
    "Player_3": "J.Timber 3",
    "Player_4": "Mitchell 2",
    "Player_8": "Anderson 4",
    "Player_9": "Haaland 4",
    "Player_15": "Senesi 8"
  },
  {
    "manager_Name": "746( 5,554,970 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "32",
    "Player_1": "Raya 2",
    "Player_11": "Thiago 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Mu\u00F1oz 0",
    "Player_7": "Rice 6",
    "Player_2": "Gudmundsson 0",
    "Player_5": "Gakpo 2",
    "Player_6": "Saka 4",
    "Player_3": "Mitchell 2",
    "Player_4": "Cucurella 6",
    "Player_8": "L.Miley 1",
    "Player_9": "Doku 3",
    "Player_15": "Mukiele 1"
  },
  {
    "manager_Name": "741( 5,776,755 )",
    "Teams": "Lassie fc( Kirsten Tanti )",
    "SXL": "MLT",
    "Latp": "42",
    "Player_1": "Raya 2",
    "Player_11": "Isidor 1",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Mu\u00F1oz 0",
    "Player_14": "Gu\u00E9hi 8",
    "Player_7": "Ndiaye 8",
    "Player_2": "Pedro Porro",
    "Player_5": "Saka 4",
    "Player_6": "Reijnders 1",
    "Player_3": "Van de",
    "Player_4": "Cucurella 6",
    "Player_8": "Semenyo 3",
    "Player_9": "Mateta 2",
    "Player_15": "Anderson 4"
  },
  {
    "manager_Name": "731( 6,212,794 )",
    "Teams": "Henry\u2019s Heroes( Jean Azzopardi )",
    "SXL": "MLT",
    "Latp": "41",
    "Player_1": "A.Becker 1",
    "Player_11": "Haaland 2",
    "Player_10": "Woltemade 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Thiago 2",
    "Player_14": "Gu\u00E9hi 8",
    "Player_7": "Reijnders 1",
    "Player_2": "Calafiori 1",
    "Player_5": "Eze 1",
    "Player_6": "Gravenberch 5",
    "Player_3": "J.Timber 3",
    "Player_4": "Cucurella 6",
    "Player_8": "Mbeumo 16",
    "Player_9": "Semenyo 3",
    "Player_15": "Alderete 1"
  },
  {
    "manager_Name": "730( 6,247,908 )",
    "Teams": "Rice Rice Baby( Ian Falzon )",
    "SXL": "MLT",
    "Latp": "47",
    "Player_1": "Donnarumma 6",
    "Player_11": "Haaland 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Caicedo 0",
    "Player_14": "Van de",
    "Player_7": "Neto 2",
    "Player_2": "Virgil 2",
    "Player_5": "Semenyo 3",
    "Player_6": "Mbeumo 16",
    "Player_3": "J.Timber 3",
    "Player_4": "Senesi 8",
    "Player_8": "Xhaka 2",
    "Player_9": "Woltemade 2",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "726( 6,416,612 )",
    "Teams": "Gy\u00F6keres14( Zack Vella )",
    "SXL": "MLT",
    "Latp": "17",
    "Player_1": "Raya 2",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 4",
    "Player_12": "Heaton 0",
    "Player_13": "M.Salah 0",
    "Player_14": "Reinildo 0",
    "Player_7": "King 1",
    "Player_2": "Est\u00E8ve 3",
    "Player_5": "Gudmundsson 0",
    "Player_6": "Eze 1",
    "Player_3": "Ballard 1",
    "Player_4": "Konsa 2",
    "Player_8": "Reijnders 1",
    "Player_9": "Isak 1",
    "Player_15": "Matete 0"
  },
  {
    "manager_Name": "724( 6,491,054 )",
    "Teams": "NLD( Jordi Farrugia )",
    "SXL": "MLT",
    "Latp": "41",
    "Player_1": "Raya 2",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Saka 4",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Gabriel 0",
    "Player_14": "\u0160e\u0161ko 0",
    "Player_7": "Gibbs-White 2",
    "Player_2": "Cucurella 6",
    "Player_5": "James 6",
    "Player_6": "Eze 1",
    "Player_3": "Romero 6",
    "Player_4": "Burn 7",
    "Player_8": "Rogers 2",
    "Player_9": "Elanga 4",
    "Player_15": "Evanilson 2"
  },
  {
    "manager_Name": "692( 7,757,293 )",
    "Teams": "Mihawha( Matthew Paris )",
    "SXL": "MLT",
    "Latp": "45",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 2",
    "Player_10": "Welbeck 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Mu\u00F1oz 0",
    "Player_14": "Xhaka 2",
    "Player_7": "Foden 12",
    "Player_2": "Van de",
    "Player_5": "Calafiori 1",
    "Player_6": "Semenyo 3",
    "Player_3": "James 6",
    "Player_4": "Mukiele 1",
    "Player_8": "Rice 6",
    "Player_9": "Haaland 4",
    "Player_15": "Ndiaye 8"
  },
  {
    "manager_Name": "688( 7,885,890 )",
    "Teams": "InvinciblesCOYG( Clayton Camilleri )",
    "SXL": "MLT",
    "Latp": "45",
    "Player_1": "Raya 4",
    "Player_11": "Wilson 4",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Kelleher 2",
    "Player_13": "M.Salah 0",
    "Player_14": "A\u00EFt-Nouri 0",
    "Player_7": "Grealish 3",
    "Player_2": "Cucurella 6",
    "Player_5": "Saka 4",
    "Player_6": "Dewsbury-Hall 16",
    "Player_3": "Kerkez 1",
    "Player_4": "Est\u00E8ve 3",
    "Player_8": "Xhaka 2",
    "Player_9": "Gy\u00F6keres 1",
    "Player_15": "Reinildo 0"
  },
  {
    "manager_Name": "680( 8,159,133 )",
    "Teams": "Zubi dubi doo( Julia Schembri )",
    "SXL": "MLT",
    "Latp": "42",
    "Player_1": "Kelleher 2",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Beto 1",
    "Player_12": "Verbruggen 3",
    "Player_13": "Saliba 0",
    "Player_14": "M.Salah 0",
    "Player_7": "Elanga 2",
    "Player_2": "Wan-Bissaka 4",
    "Player_5": "Eze 1",
    "Player_6": "Dewsbury-Hall 16",
    "Player_3": "Konsa 2",
    "Player_4": "Gu\u00E9hi 8",
    "Player_8": "Semenyo 3",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "667( 8,583,844 )",
    "Teams": "Gorsil Gunners( Gordon Silvio )",
    "SXL": "MLT",
    "Latp": "39",
    "Player_1": "Raya 2",
    "Player_11": "Thiago 2",
    "Player_10": "Haaland 4",
    "Player_12": "Sels 2",
    "Player_13": "Kluivert 3",
    "Player_14": "Konsa 2",
    "Player_7": "Semenyo 3",
    "Player_2": "James 6",
    "Player_5": "Wan-Bissaka 4",
    "Player_6": "Eze 1",
    "Player_3": "Gu\u00E9hi 8",
    "Player_4": "Van de",
    "Player_8": "Neto 2",
    "Player_9": "Marmoush 1",
    "Player_15": "Beto 1"
  },
  {
    "manager_Name": "665( 8,638,464 )",
    "Teams": "Harambe FC( Glenn Gauci Borda )",
    "SXL": "MLT",
    "Latp": "48",
    "Player_1": "S\u00E1nchez 10",
    "Player_11": "Bowen 9",
    "Player_10": "Wood 0",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Reinildo 0",
    "Player_14": "M.Salah 0",
    "Player_7": "Reijnders 1",
    "Player_2": "Van de",
    "Player_5": "Est\u00E8ve 3",
    "Player_6": "Semenyo 3",
    "Player_3": "Konsa 2",
    "Player_4": "Wan-Bissaka 4",
    "Player_8": "Mbeumo 8",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "664( 8,685,450 )",
    "Teams": "Viktooooooor( Fredrick Buhagiar )",
    "SXL": "MLT",
    "Latp": "37",
    "Player_1": "S\u00E1nchez 10",
    "Player_11": "Thiago 2",
    "Player_10": "Gy\u00F6keres 1",
    "Player_12": "Vicario 6",
    "Player_13": "Reinildo 0",
    "Player_14": "Richards 4",
    "Player_7": "Enzo 3",
    "Player_2": "Mitchell 2",
    "Player_5": "Saka 4",
    "Player_6": "Eze 1",
    "Player_3": "Milenkovi\u0107 0",
    "Player_4": "Gu\u00E9hi 8",
    "Player_8": "Xhaka 2",
    "Player_9": "Haaland 4",
    "Player_15": "Ndiaye 8"
  },
  {
    "manager_Name": "650( 9,073,915 )",
    "Teams": "Boca Seniors FC( Jake Bonnici )",
    "SXL": "MLT",
    "Latp": "59",
    "Player_1": "Vicario 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Beto 1",
    "Player_12": "Ramsdale 2",
    "Player_13": "M.Salah 0",
    "Player_14": "Lewis-Skelly 1",
    "Player_7": "Saka 4",
    "Player_2": "Kerkez 1",
    "Player_5": "Cherki 12",
    "Player_6": "Rogers 2",
    "Player_3": "Bassey 3",
    "Player_4": "Spence 6",
    "Player_8": "Wharton 9",
    "Player_9": "Ekitik\u00E9 13",
    "Player_15": "Aina 0"
  }
];