var s = [
  {
    "manager_Name": "344( 1,327,304 )",
    "Teams": "5-D( Erald Haxhiu )",
    "SXL": "USA",
    "Latp": "61",
    "Player_1": "Donnarumma 2",
    "Player_11": "Haaland 32",
    "Player_10": "Woltemade 7",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Senesi 7",
    "Player_14": "Tonali 6",
    "Player_7": "Gakpo 1",
    "Player_2": "Dorgu 0",
    "Player_5": "Caicedo 2",
    "Player_6": "M.Salah 2",
    "Player_3": "Gu\u00E9hi 7",
    "Player_4": "Van de Ven 2",
    "Player_8": "P.M.Sarr 4",
    "Player_9": "Gy\u00F6keres 2",
    "Player_15": "Mukiele 6"
  },
  {
    "manager_Name": "345( 1,283,418 )",
    "Teams": "Glasner all over!( Ben Bushby )",
    "SXL": "ENG",
    "Latp": "50",
    "Player_1": "Vicario 2",
    "Player_11": "Haaland 32",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Rodon 7",
    "Player_14": "Est\u00E8ve -2",
    "Player_7": "Ndiaye WHU (H)",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "Kudus 2",
    "Player_6": "M.Salah 2",
    "Player_3": "Van de Ven 2",
    "Player_4": "Konsa 2",
    "Player_8": "Reijnders 2",
    "Player_9": "Wood 2",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "331( 2,077,608 )",
    "Teams": "BlueBoys( Ilir Bazaiti )",
    "SXL": "ENG",
    "Latp": "60",
    "Player_1": "Areola EVE (A)",
    "Player_11": "Richarlison 2",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Diouf EVE (A)",
    "Player_14": "L.Miley 0",
    "Player_7": "Semenyo 7",
    "Player_2": "Senesi 7",
    "Player_5": "M.Salah 2",
    "Player_6": "Reijnders 2",
    "Player_3": "Gvardiol 2",
    "Player_4": "Van de Ven 2",
    "Player_8": "Eze 2",
    "Player_9": "Haaland 32",
    "Player_15": "Tuanzebe 0"
  },
  {
    "manager_Name": "344( 1,327,304 )",
    "Teams": "\u00C7er\u00E7izi Jeshil( Armando Lula )",
    "SXL": "ALB",
    "Latp": "66",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 32",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Stach 2",
    "Player_14": "Andersen 3",
    "Player_7": "Ndiaye WHU (H)",
    "Player_2": "Gabriel 13",
    "Player_5": "B.Fernandes -1",
    "Player_6": "Semenyo 7",
    "Player_3": "Tarkowski WHU (H)",
    "Player_4": "Senesi 7",
    "Player_8": "Reijnders 2",
    "Player_9": "Jo\u00E3o Pedro 2",
    "Player_15": "Richards 4"
  },
  {
    "manager_Name": "376( 235,096 )",
    "Teams": "Tepelena( Joan Hasanmema )",
    "SXL": "ALB",
    "Latp": "54",
    "Player_1": "Donnarumma 2",
    "Player_11": "Richarlison 2",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "Raya 2",
    "Player_13": "Caicedo 2",
    "Player_14": "Rodon 7",
    "Player_7": "Semenyo 7",
    "Player_2": "Senesi 7",
    "Player_5": "B.Fernandes -1",
    "Player_6": "Reijnders 2",
    "Player_3": "Chalobah -3",
    "Player_4": "Van de Ven 2",
    "Player_8": "Kudus 2",
    "Player_9": "Haaland 32",
    "Player_15": "Gu\u00E9hi 7"
  },
  {
    "manager_Name": "360( 636,782 )",
    "Teams": "\uFFFD( Magi Muco )",
    "SXL": "ALB",
    "Latp": "67",
    "Player_1": "Raya 2",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Haaland 32",
    "Player_12": "Verbruggen 2",
    "Player_13": "Grealish WHU (H)",
    "Player_14": "Bassey 0",
    "Player_7": "Enzo 9",
    "Player_2": "Senesi 7",
    "Player_5": "Wirtz 2",
    "Player_6": "Ndoye 1",
    "Player_3": "Dorgu 0",
    "Player_4": "Van de Ven 2",
    "Player_8": "Est\u00EAv\u00E3o 3",
    "Player_9": "Woltemade 7",
    "Player_15": "Rodon 7"
  },
  {
    "manager_Name": "351( 955,127 )",
    "Teams": "MAGA( Eni Shtini )",
    "SXL": "ALB",
    "Latp": "65",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 32",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Dewsbury-Hall WHU (H)",
    "Player_14": "King 1",
    "Player_7": "M.Salah 2",
    "Player_2": "Van de Ven 2",
    "Player_5": "Senesi 7",
    "Player_6": "Semenyo 7",
    "Player_3": "Virgil 2",
    "Player_4": "Gu\u00E9hi 7",
    "Player_8": "L.Paquet\u00E1 EVE (A)",
    "Player_9": "Jo\u00E3o Pedro 2",
    "Player_15": "Est\u00E8ve -2"
  },
  {
    "manager_Name": "321( 2,819,630 )",
    "Teams": "Supercampeones( Ronny Nelkenbaum )",
    "SXL": "FRA",
    "Latp": "57",
    "Player_1": "Sels 2",
    "Player_11": "Haaland 32",
    "Player_10": "Watkins 8",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Virgil 2",
    "Player_14": "Diouf EVE (A)",
    "Player_7": "Semenyo 7",
    "Player_2": "Pedro Porro 1",
    "Player_5": "Reijnders 2",
    "Player_6": "Kudus 2",
    "Player_3": "Cucurella 0",
    "Player_4": "N.Williams 1",
    "Player_8": "Dewsbury-Hall WHU (H)",
    "Player_9": "Jo\u00E3o Pedro 2",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "333( 1,954,829 )",
    "Teams": "Renaissance( Sidrit Minxhozi )",
    "SXL": "DNK",
    "Latp": "68",
    "Player_1": "Pickford WHU (H)",
    "Player_11": "Richarlison 2",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Gabriel 13",
    "Player_14": "Baleba 2",
    "Player_7": "Kudus 2",
    "Player_2": "N.Williams 1",
    "Player_5": "B.Fernandes -1",
    "Player_6": "Semenyo 7",
    "Player_3": "Van de Ven 2",
    "Player_4": "De Ligt 3",
    "Player_8": "Mbeumo 2",
    "Player_9": "Haaland 48",
    "Player_15": "Est\u00E8ve -2"
  },
  {
    "manager_Name": "276( 6,594,793 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "36",
    "Player_1": "Raya 2",
    "Player_11": "Jo\u00E3o Pedro 2",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "L.Paquet\u00E1 EVE (A)",
    "Player_14": "Mateta 2",
    "Player_7": "M.Salah 4",
    "Player_2": "Gabriel 13",
    "Player_5": "Senesi 7",
    "Player_6": "Reijnders 2",
    "Player_3": "Virgil 2",
    "Player_4": "Gudmundsson 1",
    "Player_8": "Grealish WHU (H)",
    "Player_9": "Gakpo 1",
    "Player_15": "Andersen 3"
  },
  {
    "manager_Name": "288( 5,575,647 )",
    "Teams": "Team name( Sunit Patel )",
    "SXL": "ENG",
    "Latp": "70",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 32",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Dewsbury-Hall WHU (H)",
    "Player_14": "Andersen 3",
    "Player_7": "B.Fernandes -1",
    "Player_2": "Gabriel 13",
    "Player_5": "Semenyo 7",
    "Player_6": "Reijnders 2",
    "Player_3": "Senesi 7",
    "Player_4": "Van de Ven 2",
    "Player_8": "Kudus 2",
    "Player_9": "Gy\u00F6keres 2",
    "Player_15": "Rodon 7"
  },
  {
    "manager_Name": "332( 2,050,366 )",
    "Teams": "Kokeqethurit( Daver Berberi )",
    "SXL": "ALB",
    "Latp": "50",
    "Player_1": "Donnarumma 2",
    "Player_11": "Haaland 32",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Lacroix 4",
    "Player_14": "Est\u00E8ve -2",
    "Player_7": "Dewsbury-Hall WHU (H)",
    "Player_2": "Virgil 2",
    "Player_5": "M.Salah 2",
    "Player_6": "Ndiaye WHU (H)",
    "Player_3": "Dorgu 0",
    "Player_4": "Pedro Porro 1",
    "Player_8": "Reijnders 2",
    "Player_9": "Semenyo 7",
    "Player_15": "Marc Guiu 0"
  },
  {
    "manager_Name": "347( 1,173,201 )",
    "Teams": "Zhampagne Football( Camilla Nurkhanov )",
    "SXL": "ENG",
    "Latp": "67",
    "Player_1": "S\u00E1nchez 1",
    "Player_11": "Jo\u00E3o Pedro 2",
    "Player_10": "Haaland 32",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Konsa 2",
    "Player_14": "E.Le F\u00E9e 3",
    "Player_7": "Kudus 2",
    "Player_2": "Gu\u00E9hi 7",
    "Player_5": "Van de Ven 2",
    "Player_6": "Wirtz 2",
    "Player_3": "Senesi 7",
    "Player_4": "Gabriel 13",
    "Player_8": "Palmer 0",
    "Player_9": "B.Fernandes -1",
    "Player_15": "Foster 2"
  },
  {
    "manager_Name": "285( 5,838,749 )",
    "Teams": "Wiggler FC( Andrew Carr )",
    "SXL": "ENG",
    "Latp": "27",
    "Player_1": "Sels 2",
    "Player_11": "Mateta 2",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Dewsbury-Hall WHU (H)",
    "Player_14": "Richards 4",
    "Player_7": "Anderson 3",
    "Player_2": "Cucurella 0",
    "Player_5": "Reijnders 2",
    "Player_6": "M.Salah 4",
    "Player_3": "Romero 2",
    "Player_4": "Pedro Porro 1",
    "Player_8": "Semenyo 7",
    "Player_9": "Evanilson 2",
    "Player_15": "Est\u00E8ve -2"
  },
  {
    "manager_Name": "313( 3,431,562 )",
    "Teams": "Park The Bus( Lorin Minxhozi )",
    "SXL": "ENG",
    "Latp": "58",
    "Player_1": "Raya 2",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Gudmundsson 1",
    "Player_14": "Burn 0",
    "Player_7": "Mbeumo 2",
    "Player_2": "Pedro Porro 1",
    "Player_5": "B.Fernandes -1",
    "Player_6": "Semenyo 7",
    "Player_3": "Virgil 2",
    "Player_4": "Senesi 7",
    "Player_8": "Reijnders 2",
    "Player_9": "Haaland 32",
    "Player_15": "King 1"
  },
  {
    "manager_Name": "231( 9,472,257 )",
    "Teams": "mayuluuu 5-0( Enio Minxhozi )",
    "SXL": "ALB",
    "Latp": "23",
    "Player_1": "Vicario 2",
    "Player_11": "Mateta 2",
    "Player_10": "Woltemade 7",
    "Player_12": "Dennis 0",
    "Player_13": "Clyne 0",
    "Player_14": "De Cuyper 8",
    "Player_7": "Wirtz 2",
    "Player_2": "Frimpong 1",
    "Player_5": "Eze 2",
    "Player_6": "M.Salah 4",
    "Player_3": "Cucurella 0",
    "Player_4": "Trippier 0",
    "Player_8": "Elanga 1",
    "Player_9": "Jo\u00E3o Pedro 2",
    "Player_15": "Young 0"
  },
  {
    "manager_Name": "257( 8,084,616 )",
    "Teams": "FantaRog( Roger Shehu )",
    "SXL": "NLD",
    "Latp": "43",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Haaland 16",
    "Player_10": "Richarlison 2",
    "Player_12": "Raya 2",
    "Player_13": "Reijnders 2",
    "Player_14": "Senesi 7",
    "Player_7": "Eze 2",
    "Player_2": "Pedro Porro 1",
    "Player_5": "Semenyo 7",
    "Player_6": "Xavi 1",
    "Player_3": "Cucurella 0",
    "Player_4": "Gu\u00E9hi 7",
    "Player_8": "Wirtz 4",
    "Player_9": "Mateta 2",
    "Player_15": "Est\u00E8ve -2"
  },
  {
    "manager_Name": "332( 2,011,398 )",
    "Teams": "robby_baggio( Marin Jano )",
    "SXL": "ALB",
    "Latp": "65",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 32",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Gu\u00E9hi 7",
    "Player_14": "Muniz 0",
    "Player_7": "Mbeumo 2",
    "Player_2": "Gabriel 13",
    "Player_5": "Kudus 2",
    "Player_6": "Eze 2",
    "Player_3": "Virgil 2",
    "Player_4": "Pedro Porro 1",
    "Player_8": "Semenyo 7",
    "Player_9": "Ndiaye WHU (H)",
    "Player_15": "Est\u00E8ve -2"
  },
  {
    "manager_Name": "221( 9,836,771 )",
    "Teams": "Albi alexander( Bardhyl Minxhozi )",
    "SXL": "ALB",
    "Latp": "16",
    "Player_1": "A.Becker 2",
    "Player_11": "Jo\u00E3o Pedro 2",
    "Player_10": "Muniz 0",
    "Player_12": "Raya 2",
    "Player_13": "Konsa 2",
    "Player_14": "Hoever 0",
    "Player_7": "L.Paquet\u00E1 EVE (A)",
    "Player_2": "Gvardiol 2",
    "Player_5": "Elanga 1",
    "Player_6": "M.Salah 4",
    "Player_3": "Cucurella 0",
    "Player_4": "Virgil 2",
    "Player_8": "Mbeumo 2",
    "Player_9": "Johnson 1",
    "Player_15": "Broja 1"
  }
];