var s = [
  {
    "manager_Name": "284( 1,767,239 )",
    "Teams": "5-D( Erald Haxhiu )",
    "SXL": "USA",
    "Latp": "40",
    "Player_1": "Donnarumma 2",
    "Player_11": "Haaland 26",
    "Player_10": "Woltemade ARS (H)",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Senesi 6",
    "Player_14": "Tonali ARS (H)",
    "Player_7": "Gakpo 1",
    "Player_2": "Dorgu 0",
    "Player_5": "Caicedo 2",
    "Player_6": "M.Salah 2",
    "Player_3": "Gu\u00E9hi 7",
    "Player_4": "Van de Ven WOL (H)",
    "Player_8": "P.M.Sarr WOL (H)",
    "Player_9": "Gy\u00F6keres NEW (A)",
    "Player_15": "Mukiele 6"
  },
  {
    "manager_Name": "299( 778,977 )",
    "Teams": "Glasner all over!( Ben Bushby )",
    "SXL": "ENG",
    "Latp": "36",
    "Player_1": "Vicario WOL (H)",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Rodon 9",
    "Player_14": "Est\u00E8ve -2",
    "Player_7": "Ndiaye WHU (H)",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "Kudus WOL (H)",
    "Player_6": "M.Salah 2",
    "Player_3": "Van de Ven WOL (H)",
    "Player_4": "Konsa FUL (H)",
    "Player_8": "Reijnders 2",
    "Player_9": "Wood 2",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "271( 2,985,039 )",
    "Teams": "BlueBoys( Ilir Bazaiti )",
    "SXL": "ENG",
    "Latp": "47",
    "Player_1": "Areola EVE (A)",
    "Player_11": "Richarlison WOL (H)",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Diouf EVE (A)",
    "Player_14": "L.Miley ARS (H)",
    "Player_7": "Semenyo 7",
    "Player_2": "Senesi 6",
    "Player_5": "M.Salah 2",
    "Player_6": "Reijnders 2",
    "Player_3": "Gvardiol 2",
    "Player_4": "Van de Ven WOL (H)",
    "Player_8": "Eze NEW (A)",
    "Player_9": "Haaland 26",
    "Player_15": "Tuanzebe 0"
  },
  {
    "manager_Name": "281( 2,030,269 )",
    "Teams": "\u00C7er\u00E7izi Jeshil( Armando Lula )",
    "SXL": "ALB",
    "Latp": "42",
    "Player_1": "Raya NEW (A)",
    "Player_11": "Haaland 26",
    "Player_10": "Gy\u00F6keres NEW (A)",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Stach 2",
    "Player_14": "Andersen AVL (A)",
    "Player_7": "Ndiaye WHU (H)",
    "Player_2": "Gabriel NEW (A)",
    "Player_5": "B.Fernandes -1",
    "Player_6": "Semenyo 7",
    "Player_3": "Tarkowski WHU (H)",
    "Player_4": "Senesi 6",
    "Player_8": "Reijnders 2",
    "Player_9": "Jo\u00E3o Pedro 2",
    "Player_15": "Richards 4"
  },
  {
    "manager_Name": "322( 135,938 )",
    "Teams": "Tepelena( Joan Hasanmema )",
    "SXL": "ALB",
    "Latp": "41",
    "Player_1": "Donnarumma 2",
    "Player_11": "Richarlison WOL (H)",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "Raya NEW (A)",
    "Player_13": "Caicedo 2",
    "Player_14": "Rodon 9",
    "Player_7": "Semenyo 7",
    "Player_2": "Senesi 6",
    "Player_5": "B.Fernandes -1",
    "Player_6": "Reijnders 2",
    "Player_3": "Chalobah -3",
    "Player_4": "Van de Ven WOL (H)",
    "Player_8": "Kudus WOL (H)",
    "Player_9": "Haaland 26",
    "Player_15": "Gu\u00E9hi 7"
  },
  {
    "manager_Name": "294( 1,042,326 )",
    "Teams": "\uFFFD( Magi Muco )",
    "SXL": "ALB",
    "Latp": "45",
    "Player_1": "Raya NEW (A)",
    "Player_11": "Gy\u00F6keres NEW (A)",
    "Player_10": "Haaland 26",
    "Player_12": "Verbruggen 2",
    "Player_13": "Grealish WHU (H)",
    "Player_14": "Bassey AVL (A)",
    "Player_7": "Enzo 7",
    "Player_2": "Senesi 6",
    "Player_5": "Wirtz 2",
    "Player_6": "Ndoye 1",
    "Player_3": "Dorgu 0",
    "Player_4": "Van de Ven WOL (H)",
    "Player_8": "Est\u00EAv\u00E3o 3",
    "Player_9": "Woltemade ARS (H)",
    "Player_15": "Rodon 9"
  },
  {
    "manager_Name": "286( 1,543,078 )",
    "Teams": "MAGA( Eni Shtini )",
    "SXL": "ALB",
    "Latp": "52",
    "Player_1": "Raya NEW (A)",
    "Player_11": "Haaland 26",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Dewsbury-Hall WHU (H)",
    "Player_14": "King AVL (A)",
    "Player_7": "M.Salah 2",
    "Player_2": "Van de Ven WOL (H)",
    "Player_5": "Senesi 6",
    "Player_6": "Semenyo 7",
    "Player_3": "Virgil 0",
    "Player_4": "Gu\u00E9hi 7",
    "Player_8": "L.Paquet\u00E1 EVE (A)",
    "Player_9": "Jo\u00E3o Pedro 2",
    "Player_15": "Est\u00E8ve -2"
  },
  {
    "manager_Name": "266( 3,551,859 )",
    "Teams": "Supercampeones( Ronny Nelkenbaum )",
    "SXL": "FRA",
    "Latp": "40",
    "Player_1": "Sels 2",
    "Player_11": "Haaland 26",
    "Player_10": "Watkins FUL (H)",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Virgil 0",
    "Player_14": "Diouf EVE (A)",
    "Player_7": "Semenyo 7",
    "Player_2": "Pedro Porro WOL (H)",
    "Player_5": "Reijnders 2",
    "Player_6": "Kudus WOL (H)",
    "Player_3": "Cucurella 0",
    "Player_4": "N.Williams 1",
    "Player_8": "Dewsbury-Hall WHU (H)",
    "Player_9": "Jo\u00E3o Pedro 2",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "265( 3,668,735 )",
    "Teams": "Renaissance( Sidrit Minxhozi )",
    "SXL": "DNK",
    "Latp": "51",
    "Player_1": "Pickford WHU (H)",
    "Player_11": "Richarlison WOL (H)",
    "Player_10": "Gy\u00F6keres NEW (A)",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Gabriel NEW (A)",
    "Player_14": "Baleba 2",
    "Player_7": "Kudus WOL (H)",
    "Player_2": "N.Williams 1",
    "Player_5": "B.Fernandes -1",
    "Player_6": "Semenyo 7",
    "Player_3": "Van de Ven WOL (H)",
    "Player_4": "De Ligt 3",
    "Player_8": "Mbeumo 2",
    "Player_9": "Haaland 39",
    "Player_15": "Est\u00E8ve -2"
  },
  {
    "manager_Name": "243( 6,234,983 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "16",
    "Player_1": "Raya NEW (A)",
    "Player_11": "Jo\u00E3o Pedro 2",
    "Player_10": "Gy\u00F6keres NEW (A)",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "L.Paquet\u00E1 EVE (A)",
    "Player_14": "Mateta 2",
    "Player_7": "M.Salah 4",
    "Player_2": "Gabriel NEW (A)",
    "Player_5": "Senesi 6",
    "Player_6": "Reijnders 2",
    "Player_3": "Virgil 0",
    "Player_4": "Gudmundsson 1",
    "Player_8": "Grealish WHU (H)",
    "Player_9": "Gakpo 1",
    "Player_15": "Andersen AVL (A)"
  },
  {
    "manager_Name": "221( 8,249,315 )",
    "Teams": "Team name( Sunit Patel )",
    "SXL": "ENG",
    "Latp": "42",
    "Player_1": "Raya NEW (A)",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Dewsbury-Hall WHU (H)",
    "Player_14": "Andersen AVL (A)",
    "Player_7": "B.Fernandes -1",
    "Player_2": "Gabriel NEW (A)",
    "Player_5": "Semenyo 7",
    "Player_6": "Reijnders 2",
    "Player_3": "Senesi 6",
    "Player_4": "Van de Ven WOL (H)",
    "Player_8": "Kudus WOL (H)",
    "Player_9": "Gy\u00F6keres NEW (A)",
    "Player_15": "Rodon 9"
  },
  {
    "manager_Name": "286( 1,557,881 )",
    "Teams": "Kokeqethurit( Daver Berberi )",
    "SXL": "ALB",
    "Latp": "41",
    "Player_1": "Donnarumma 2",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Lacroix 4",
    "Player_14": "Est\u00E8ve -2",
    "Player_7": "Dewsbury-Hall WHU (H)",
    "Player_2": "Virgil 0",
    "Player_5": "M.Salah 2",
    "Player_6": "Ndiaye WHU (H)",
    "Player_3": "Dorgu 0",
    "Player_4": "Pedro Porro WOL (H)",
    "Player_8": "Reijnders 2",
    "Player_9": "Semenyo 7",
    "Player_15": "Marc Guiu 0"
  },
  {
    "manager_Name": "283( 1,852,466 )",
    "Teams": "Zhampagne Football( Camilla Nurkhanov )",
    "SXL": "ENG",
    "Latp": "43",
    "Player_1": "S\u00E1nchez 1",
    "Player_11": "Jo\u00E3o Pedro 2",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Konsa FUL (H)",
    "Player_14": "E.Le F\u00E9e 3",
    "Player_7": "Kudus WOL (H)",
    "Player_2": "Gu\u00E9hi 7",
    "Player_5": "Van de Ven WOL (H)",
    "Player_6": "Wirtz 2",
    "Player_3": "Senesi 6",
    "Player_4": "Gabriel NEW (A)",
    "Player_8": "Palmer 0",
    "Player_9": "B.Fernandes -1",
    "Player_15": "Foster 2"
  },
  {
    "manager_Name": "258( 4,487,136 )",
    "Teams": "Wiggler FC( Andrew Carr )",
    "SXL": "ENG",
    "Latp": "24",
    "Player_1": "Sels 2",
    "Player_11": "Mateta 2",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Dewsbury-Hall WHU (H)",
    "Player_14": "Richards 4",
    "Player_7": "Anderson 3",
    "Player_2": "Cucurella 0",
    "Player_5": "Reijnders 2",
    "Player_6": "M.Salah 4",
    "Player_3": "Romero WOL (H)",
    "Player_4": "Pedro Porro WOL (H)",
    "Player_8": "Semenyo 7",
    "Player_9": "Evanilson 2",
    "Player_15": "Est\u00E8ve -2"
  },
  {
    "manager_Name": "255( 4,842,451 )",
    "Teams": "Park The Bus( Lorin Minxhozi )",
    "SXL": "ENG",
    "Latp": "44",
    "Player_1": "Raya NEW (A)",
    "Player_11": "Gy\u00F6keres NEW (A)",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Gudmundsson 1",
    "Player_14": "Burn ARS (H)",
    "Player_7": "Mbeumo 2",
    "Player_2": "Pedro Porro WOL (H)",
    "Player_5": "B.Fernandes -1",
    "Player_6": "Semenyo 7",
    "Player_3": "Virgil 0",
    "Player_4": "Senesi 6",
    "Player_8": "Reijnders 2",
    "Player_9": "Haaland 26",
    "Player_15": "King AVL (A)"
  },
  {
    "manager_Name": "209( 9,017,156 )",
    "Teams": "mayuluuu 5-0( Enio Minxhozi )",
    "SXL": "ALB",
    "Latp": "11",
    "Player_1": "Vicario WOL (H)",
    "Player_11": "Mateta 2",
    "Player_10": "Woltemade ARS (H)",
    "Player_12": "Dennis 0",
    "Player_13": "Clyne 0",
    "Player_14": "De Cuyper 7",
    "Player_7": "Wirtz 2",
    "Player_2": "Frimpong 1",
    "Player_5": "Eze NEW (A)",
    "Player_6": "M.Salah 4",
    "Player_3": "Cucurella 0",
    "Player_4": "Trippier ARS (H)",
    "Player_8": "Elanga ARS (H)",
    "Player_9": "Jo\u00E3o Pedro 2",
    "Player_15": "Young FUL (H)"
  },
  {
    "manager_Name": "230( 7,537,705 )",
    "Teams": "FantaRog( Roger Shehu )",
    "SXL": "NLD",
    "Latp": "34",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Haaland 13",
    "Player_10": "Richarlison WOL (H)",
    "Player_12": "Raya NEW (A)",
    "Player_13": "Reijnders 2",
    "Player_14": "Senesi 6",
    "Player_7": "Eze NEW (A)",
    "Player_2": "Pedro Porro WOL (H)",
    "Player_5": "Semenyo 7",
    "Player_6": "Xavi WOL (H)",
    "Player_3": "Cucurella 0",
    "Player_4": "Gu\u00E9hi 7",
    "Player_8": "Wirtz 4",
    "Player_9": "Mateta 2",
    "Player_15": "Est\u00E8ve -2"
  },
  {
    "manager_Name": "270( 3,095,966 )",
    "Teams": "robby_baggio( Marin Jano )",
    "SXL": "ALB",
    "Latp": "37",
    "Player_1": "Raya NEW (A)",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Gu\u00E9hi 7",
    "Player_14": "Muniz AVL (A)",
    "Player_7": "Mbeumo 2",
    "Player_2": "Gabriel NEW (A)",
    "Player_5": "Kudus WOL (H)",
    "Player_6": "Eze NEW (A)",
    "Player_3": "Virgil 0",
    "Player_4": "Pedro Porro WOL (H)",
    "Player_8": "Semenyo 7",
    "Player_9": "Ndiaye WHU (H)",
    "Player_15": "Est\u00E8ve -2"
  },
  {
    "manager_Name": "205( 9,207,904 )",
    "Teams": "Albi alexander( Bardhyl Minxhozi )",
    "SXL": "ALB",
    "Latp": "12",
    "Player_1": "A.Becker 2",
    "Player_11": "Jo\u00E3o Pedro 2",
    "Player_10": "Muniz AVL (A)",
    "Player_12": "Raya NEW (A)",
    "Player_13": "Konsa FUL (H)",
    "Player_14": "Hoever TOT (A)",
    "Player_7": "L.Paquet\u00E1 EVE (A)",
    "Player_2": "Gvardiol 2",
    "Player_5": "Elanga ARS (H)",
    "Player_6": "M.Salah 4",
    "Player_3": "Cucurella 0",
    "Player_4": "Virgil 0",
    "Player_8": "Mbeumo 2",
    "Player_9": "Johnson WOL (H)",
    "Player_15": "Broja 1"
  }
];