// Fetches current weather for every capital in countries.json and writes
// the result to weatherData.json, which the page reads at load time. This
// is a periodic snapshot generated by hand-running this script, not a
// live per-visitor API call — otherwise every page load would fire 38
// requests against the same free-tier OpenWeather key ../fetch.js uses.
//
// Run manually from this folder: `node scrapeWeather.js`
//
// Stores only raw numbers (epoch seconds, timezone offset, day-length
// seconds) rather than pre-formatted strings — app.js does the formatting,
// the same way ui.js formats raw API data for the main Weather.JS app.
// That also lets app.js keep the Local Time column ticking live between
// scrapes, off the browser's own clock plus the stored timezone offset.

const fs = require("fs");
const path = require("path");

// Same free-tier key ../fetch.js already ships to every browser — reusing
// it here doesn't expose anything that isn't already public in this repo.
const API_KEY = "39a9a737b07b4b703e3d1cd1e231eedc";
const DELAY_MS = 1100; // keeps us under OpenWeather's free-tier 60-calls/minute limit

const COUNTRIES_PATH = path.join(__dirname, "countries.json");
const OUTPUT_PATH = path.join(__dirname, "weatherData.json");

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function fetchWeather(country) {
  // Queried by lat/lon (not the capital's name) so a name OpenWeather
  // can't resolve cleanly — e.g. "Nuku'alofa" — can't silently 404.
  const url =
    `https://api.openweathermap.org/data/2.5/weather` +
    `?lat=${country.lat}&lon=${country.lon}&units=metric&appid=${API_KEY}`;

  const response = await fetch(url);
  const data = await response.json();

  if (!response.ok) {
    throw new Error(data.message || `Request failed (${response.status})`);
  }

  return {
    temp: data.main.temp,
    description: data.weather[0] ? data.weather[0].description : "",
    timezone: data.timezone,
    sunrise: data.sys.sunrise,
    sunset: data.sys.sunset,
    dayLengthSeconds: data.sys.sunset - data.sys.sunrise,
  };
}

async function main() {
  const countries = JSON.parse(fs.readFileSync(COUNTRIES_PATH, "utf8"));
  const existing = fs.existsSync(OUTPUT_PATH)
    ? JSON.parse(fs.readFileSync(OUTPUT_PATH, "utf8"))
    : { generatedAt: null, byIso2: {} };

  const byIso2 = { ...existing.byIso2 };
  let failures = 0;

  for (const country of countries) {
    process.stdout.write(`${country.country} (${country.iso2})... `);
    try {
      byIso2[country.iso2] = await fetchWeather(country);
      console.log("ok");
    } catch (err) {
      // Keep whatever this country had from the last successful scrape
      // rather than blanking its row out over one flaky request.
      failures += 1;
      console.log(`FAILED (${err.message}) — keeping previous data`);
    }
    await sleep(DELAY_MS);
  }

  const output = { generatedAt: Math.floor(Date.now() / 1000), byIso2 };
  fs.writeFileSync(OUTPUT_PATH, JSON.stringify(output, null, 2) + "\n");
  console.log(`\nWrote ${Object.keys(byIso2).length} entries to ${OUTPUT_PATH}` +
    (failures ? ` (${failures} failed this run, old data kept for those)` : ""));
}

main();
