var s = [
  {
    "manager_Name": "615( 629,100 )",
    "Teams": "\u00C7er\u00E7izi Jeshil( Armando Lula )",
    "SXL": "ALB",
    "Latp": "73",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Woltemade 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Reijnders 1",
    "Player_14": "Rodon 1",
    "Player_7": "Ndiaye SUN",
    "Player_2": "Gabriel 12",
    "Player_5": "Saka 3",
    "Player_6": "Semenyo 2",
    "Player_3": "Andersen 6",
    "Player_4": "Richards 6",
    "Player_8": "Enzo 2",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Senesi 3"
  },
  {
    "manager_Name": "621( 481,790 )",
    "Teams": "Tepelena( Joan Hasanmema )",
    "SXL": "ALB",
    "Latp": "87",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 1",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Donnarumma 2",
    "Player_13": "Reijnders 1",
    "Player_14": "Senesi 3",
    "Player_7": "Semenyo 2",
    "Player_2": "Gu\u00E9hi 10",
    "Player_5": "Saka 3",
    "Player_6": "Caicedo 10",
    "Player_3": "James 7",
    "Player_4": "Gabriel 12",
    "Player_8": "Kudus 1",
    "Player_9": "Haaland 26",
    "Player_15": "Alderete EVE"
  },
  {
    "manager_Name": "581( 1,859,486 )",
    "Teams": "Renaissance( Sidrit Minxhozi )",
    "SXL": "DNK",
    "Latp": "52",
    "Player_1": "Pope 3",
    "Player_11": "Haaland 26",
    "Player_10": "Welbeck 6",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Enzo 2",
    "Player_14": "Cash 0",
    "Player_7": "Kudus 1",
    "Player_2": "J.Timber 6",
    "Player_5": "Saka 3",
    "Player_6": "Semenyo 2",
    "Player_3": "Van de",
    "Player_4": "R\u00FAben 2",
    "Player_8": "Xhaka EVE",
    "Player_9": "Woltemade 1",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "580( 1,900,097 )",
    "Teams": "Park The Bus( Lorin Minxhozi )",
    "SXL": "ENG",
    "Latp": "66",
    "Player_1": "Raya 6",
    "Player_11": "Mateta 9",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Senesi 3",
    "Player_14": "Kroupi.Jr 2",
    "Player_7": "Mbeumo 2",
    "Player_2": "Richards 6",
    "Player_5": "B.Fernandes 5",
    "Player_6": "Semenyo 2",
    "Player_3": "Virgil 5",
    "Player_4": "Burn 1",
    "Player_8": "Reijnders 1",
    "Player_9": "Saka 3",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "607( 839,227 )",
    "Teams": "MAGA( Eni Shtini )",
    "SXL": "ALB",
    "Latp": "68",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Mateta 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Marc Guiu",
    "Player_14": "Senesi 3",
    "Player_7": "Kudus 1",
    "Player_2": "Van de",
    "Player_5": "Semenyo 2",
    "Player_6": "Mbeumo 2",
    "Player_3": "J.Timber 6",
    "Player_4": "Gu\u00E9hi 10",
    "Player_8": "Gordon 1",
    "Player_9": "Eze 3",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "573( 2,271,419 )",
    "Teams": "\uFFFD( Magi Muco )",
    "SXL": "ALB",
    "Latp": "57",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 7",
    "Player_10": "Haaland 26",
    "Player_12": "Verbruggen 6",
    "Player_13": "Minteh 9",
    "Player_14": "Senesi 3",
    "Player_7": "Enzo 2",
    "Player_2": "Bassey 6",
    "Player_5": "Foden 4",
    "Player_6": "Grealish SUN",
    "Player_3": "Mukiele EVE",
    "Player_4": "Van de",
    "Player_8": "Saka 3",
    "Player_9": "Woltemade 1",
    "Player_15": "Rodon 1"
  },
  {
    "manager_Name": "592( 1,394,081 )",
    "Teams": "5-D( Erald Haxhiu )",
    "SXL": "USA",
    "Latp": "78",
    "Player_1": "Donnarumma 2",
    "Player_11": "Haaland 26",
    "Player_10": "Woltemade 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Senesi 3",
    "Player_14": "Xhaka EVE",
    "Player_7": "Semenyo 2",
    "Player_2": "Gabriel 12",
    "Player_5": "Caicedo 10",
    "Player_6": "Cunha 4",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "Van de",
    "Player_8": "Mbeumo 2",
    "Player_9": "Gy\u00F6keres 7",
    "Player_15": "Mukiele EVE"
  },
  {
    "manager_Name": "557( 3,142,162 )",
    "Teams": "Glasner all over!( Ben Bushby )",
    "SXL": "ENG",
    "Latp": "54",
    "Player_1": "Vicario 4",
    "Player_11": "Haaland 26",
    "Player_10": "Woltemade 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Kudus 1",
    "Player_14": "Konsa 1",
    "Player_7": "Ndiaye SUN",
    "Player_2": "Mu\u00F1oz 6",
    "Player_5": "Reijnders 1",
    "Player_6": "Saka 3",
    "Player_3": "Van de",
    "Player_4": "Rodon 1",
    "Player_8": "Neto 3",
    "Player_9": "Gy\u00F6keres 7",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "550( 3,521,903 )",
    "Teams": "Team name( Sunit Patel )",
    "SXL": "ENG",
    "Latp": "55",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 13",
    "Player_10": "Bowen 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Rodon 1",
    "Player_14": "Kroupi.Jr 2",
    "Player_7": "Saka 6",
    "Player_2": "Gabriel 12",
    "Player_5": "Semenyo 2",
    "Player_6": "Sarr 3",
    "Player_3": "Andersen 6",
    "Player_4": "Van de",
    "Player_8": "Kudus 1",
    "Player_9": "Mbeumo 2",
    "Player_15": "Senesi 3"
  },
  {
    "manager_Name": "547( 3,707,861 )",
    "Teams": "Supercampeones( Ronny Nelkenbaum )",
    "SXL": "FRA",
    "Latp": "62",
    "Player_1": "Sels 2",
    "Player_11": "Woltemade 1",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "James 7",
    "Player_14": "Dewsbury-Hall SUN",
    "Player_7": "Sarr 3",
    "Player_2": "Diouf 2",
    "Player_5": "Semenyo 2",
    "Player_6": "Kudus 1",
    "Player_3": "J.Timber 6",
    "Player_4": "Cucurella 7",
    "Player_8": "Saka 3",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Alderete EVE"
  },
  {
    "manager_Name": "543( 3,905,512 )",
    "Teams": "BlueBoys( Ilir Bazaiti )",
    "SXL": "ENG",
    "Latp": "57",
    "Player_1": "Areola 3",
    "Player_11": "Woltemade 1",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "James 7",
    "Player_14": "L.Miley 0",
    "Player_7": "Semenyo 2",
    "Player_2": "Senesi 3",
    "Player_5": "M.Salah 20",
    "Player_6": "Reijnders 1",
    "Player_3": "Mukiele EVE",
    "Player_4": "Diouf 2",
    "Player_8": "Eze 3",
    "Player_9": "Haaland 13",
    "Player_15": "Tuanzebe 3"
  },
  {
    "manager_Name": "497( 6,516,629 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "74",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Gy\u00F6keres 7",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "L.Paquet\u00E1 9",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Reijnders 1",
    "Player_2": "Gabriel 12",
    "Player_5": "Mukiele EVE",
    "Player_6": "Xhaka EVE",
    "Player_3": "Cucurella 7",
    "Player_4": "Senesi 3",
    "Player_8": "M.Salah 10",
    "Player_9": "Thiago 2",
    "Player_15": "L.Miley 0"
  },
  {
    "manager_Name": "663( 49,484 )",
    "Teams": "robby_baggio( Marin Jano )",
    "SXL": "ALB",
    "Latp": "76",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 2",
    "Player_14": "Calvert-Lewin 2",
    "Player_7": "Eze 3",
    "Player_2": "Gabriel 12",
    "Player_5": "Pedro Porro",
    "Player_6": "Kudus 1",
    "Player_3": "Virgil 5",
    "Player_4": "Gu\u00E9hi 10",
    "Player_8": "Mbeumo 2",
    "Player_9": "Ndiaye SUN",
    "Player_15": "Est\u00E8ve 1"
  }
];