var s = [
  {
    "manager_Name": "783( 1 )",
    "Teams": "(Wes) Brownie Points( Kumar Isaac )",
    "SXL": "USA",
    "Latp": "98",
    "Player_1": "Raya 6",
    "Player_11": "\u0160e\u0161ko 2",
    "Player_10": "Haaland 39",
    "Player_12": "Pope 3",
    "Player_13": "Yoro 1",
    "Player_14": "Thiago 2",
    "Player_7": "Rice 13",
    "Player_2": "Van de",
    "Player_5": "Gu\u00E9hi 10",
    "Player_6": "Mbeumo 2",
    "Player_3": "Gabriel 12",
    "Player_4": "Cash 0",
    "Player_8": "Caicedo 10",
    "Player_9": "Semenyo 2",
    "Player_15": "Palmer 0"
  },
  {
    "manager_Name": "780( 2 )",
    "Teams": "ZayceCFC( Zay McGuire )",
    "SXL": "USA",
    "Latp": "94",
    "Player_1": "Pope 3",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Petrovi\u0107 2",
    "Player_13": "Kudus 1",
    "Player_14": "Ndiaye 9",
    "Player_7": "Caicedo 10",
    "Player_2": "Cucurella 7",
    "Player_5": "Gabriel 12",
    "Player_6": "Rice 13",
    "Player_3": "Virgil 5",
    "Player_4": "J.Timber 6",
    "Player_8": "Semenyo 2",
    "Player_9": "Woltemade 1",
    "Player_15": "Gu\u00E9hi 10"
  },
  {
    "manager_Name": "770( 3 )",
    "Teams": "Calafiorication( Aryan Kumar )",
    "SXL": "BHR",
    "Latp": "98",
    "Player_1": "Raya 6",
    "Player_11": "Mateta 9",
    "Player_10": "Haaland 26",
    "Player_12": "Sels 2",
    "Player_13": "Virgil 5",
    "Player_14": "Onana 1",
    "Player_7": "Enzo 2",
    "Player_2": "Gu\u00E9hi 10",
    "Player_5": "Tarkowski 2",
    "Player_6": "Semenyo 2",
    "Player_3": "Mu\u00F1oz 6",
    "Player_4": "Gabriel 12",
    "Player_8": "Rice 13",
    "Player_9": "Caicedo 10",
    "Player_15": "Ekitik\u00E9 2"
  },
  {
    "manager_Name": "768( 4 )",
    "Teams": "Shiver Me Timber( Mike Tomlin )",
    "SXL": "ENG",
    "Latp": "100",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 13",
    "Player_10": "Mateta 9",
    "Player_12": "Sels 2",
    "Player_13": "Murillo 3",
    "Player_14": "Damsgaard 2",
    "Player_7": "Rice 26",
    "Player_2": "Gu\u00E9hi 10",
    "Player_5": "Gabriel 12",
    "Player_6": "B.Fernandes 5",
    "Player_3": "Senesi 3",
    "Player_4": "Mu\u00F1oz 6",
    "Player_8": "Bruno G.",
    "Player_9": "Welbeck 6",
    "Player_15": "Semenyo 2"
  },
  {
    "manager_Name": "766( 5 )",
    "Teams": "Ballo fc( Ade Bayo )",
    "SXL": "NGA",
    "Latp": "105",
    "Player_1": "Martinez 1",
    "Player_11": "Haaland 26",
    "Player_10": "Welbeck 6",
    "Player_12": "Petrovi\u0107 2",
    "Player_13": "Saliba 6",
    "Player_14": "Tonali 2",
    "Player_7": "Kudus 1",
    "Player_2": "Gu\u00E9hi 10",
    "Player_5": "Van de",
    "Player_6": "Szoboszlai 2",
    "Player_3": "Senesi 3",
    "Player_4": "Gabriel 12",
    "Player_8": "Rice 13",
    "Player_9": "Caicedo 10",
    "Player_15": "Jo\u00E3o Pedro"
  },
  {
    "manager_Name": "765( 6 )",
    "Teams": "saka nuts( lucas clarke )",
    "SXL": "NZL",
    "Latp": "87",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 7",
    "Player_10": "Mateta 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Est\u00E8ve 1",
    "Player_14": "King 3",
    "Player_7": "Minteh 9",
    "Player_2": "Mu\u00F1oz 6",
    "Player_5": "Semenyo 2",
    "Player_6": "B.Fernandes 5",
    "Player_3": "Senesi 3",
    "Player_4": "Gabriel 12",
    "Player_8": "Mbeumo 2",
    "Player_9": "Haaland 26",
    "Player_15": "Reinildo 2"
  },
  {
    "manager_Name": "764( 7 )",
    "Teams": "Manchester City( Javier Rufo )",
    "SXL": "ESP",
    "Latp": "88",
    "Player_1": "Donnarumma 2",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "Vicario 4",
    "Player_13": "Gu\u00E9hi 10",
    "Player_14": "Palmer 0",
    "Player_7": "Caicedo 10",
    "Player_2": "Saliba 6",
    "Player_5": "J.Timber 6",
    "Player_6": "Yeremy 3",
    "Player_3": "Gabriel 12",
    "Player_4": "Pedro Porro",
    "Player_8": "Cherki 10",
    "Player_9": "Semenyo 2",
    "Player_15": "Nmecha 1"
  },
  {
    "manager_Name": "763( 8 )",
    "Teams": "teddy\u0027s xv( C McQuade )",
    "SXL": "ENG",
    "Latp": "72",
    "Player_1": "Raya 6",
    "Player_11": "Mateta 9",
    "Player_10": "Haaland 26",
    "Player_12": "Verbruggen 6",
    "Player_13": "Lacroix 8",
    "Player_14": "Bowen 2",
    "Player_7": "Semenyo 2",
    "Player_2": "Mu\u00F1oz 6",
    "Player_5": "Gabriel 12",
    "Player_6": "Bruno G.",
    "Player_3": "Burn 1",
    "Player_4": "Van de",
    "Player_8": "Kudus 1",
    "Player_9": "Eze 3",
    "Player_15": "Enzo 2"
  },
  {
    "manager_Name": "763( 9 )",
    "Teams": "lambo( Thomas Lamb )",
    "SXL": "ENG",
    "Latp": "83",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 2",
    "Player_10": "Woltemade 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Caicedo 10",
    "Player_14": "Trippier 0",
    "Player_7": "Casemiro 12",
    "Player_2": "Gabriel 12",
    "Player_5": "Rice 13",
    "Player_6": "M.Salah 10",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "Van de",
    "Player_8": "Kudus 1",
    "Player_9": "Haaland 13",
    "Player_15": "Konsa 1"
  },
  {
    "manager_Name": "762( 10 )",
    "Teams": "Ode08fc( Enoch Lariba )",
    "SXL": "GHA",
    "Latp": "92",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "Sels 2",
    "Player_13": "Frimpong 0",
    "Player_14": "Gibbs-White 8",
    "Player_7": "Rice 13",
    "Player_2": "Van de",
    "Player_5": "Walker 1",
    "Player_6": "Semenyo 2",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "Gabriel 12",
    "Player_8": "Kudus 1",
    "Player_9": "Caicedo 10",
    "Player_15": "Bowen 2"
  },
  {
    "manager_Name": "762( 10 )",
    "Teams": "Saka spuds!( Jack Hall )",
    "SXL": "ENG",
    "Latp": "99",
    "Player_1": "Pope 3",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "Raya 6",
    "Player_13": "Livramento 0",
    "Player_14": "Gravenberch 11",
    "Player_7": "Bruno G.",
    "Player_2": "Cash 0",
    "Player_5": "Cucurella 7",
    "Player_6": "B.Fernandes 5",
    "Player_3": "Gabriel 12",
    "Player_4": "Gu\u00E9hi 10",
    "Player_8": "Rice 13",
    "Player_9": "Caicedo 10",
    "Player_15": "Watkins 2"
  },
  {
    "manager_Name": "762( 12 )",
    "Teams": "Angeball( Oscar Pernehed )",
    "SXL": "SWE",
    "Latp": "79",
    "Player_1": "Pickford 2",
    "Player_11": "Haaland 26",
    "Player_10": "Gy\u00F6keres 7",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "King 3",
    "Player_14": "Senesi 3",
    "Player_7": "B.Fernandes 5",
    "Player_2": "Tarkowski 2",
    "Player_5": "J.Timber 6",
    "Player_6": "Mbeumo 2",
    "Player_3": "Gabriel 12",
    "Player_4": "Mu\u00F1oz 6",
    "Player_8": "L.Paquet\u00E1 9",
    "Player_9": "Semenyo 2",
    "Player_15": "Barnes 0"
  },
  {
    "manager_Name": "762( 13 )",
    "Teams": "The Honest Trundlers( Ian Foster )",
    "SXL": "GBR",
    "Latp": "75",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 2",
    "Player_10": "Ekitik\u00E9 2",
    "Player_12": "Pope 3",
    "Player_13": "Semenyo 2",
    "Player_14": "Mu\u00F1oz 6",
    "Player_7": "Tonali 2",
    "Player_2": "Gabriel 12",
    "Player_5": "Van Hecke",
    "Player_6": "Rice 13",
    "Player_3": "Pedro Porro",
    "Player_4": "Thiaw 1",
    "Player_8": "Grealish 2",
    "Player_9": "Haaland 26",
    "Player_15": "Szoboszlai 2"
  },
  {
    "manager_Name": "760( 14 )",
    "Teams": "g7412877( George McNicholas )",
    "SXL": "ENG",
    "Latp": "106",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Awoniyi 1",
    "Player_14": "Bates 0",
    "Player_7": "Rice 13",
    "Player_2": "Gabriel 12",
    "Player_5": "Burn 1",
    "Player_6": "M.Salah 10",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "James 7",
    "Player_8": "Semenyo 2",
    "Player_9": "Caicedo 10",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "760( 14 )",
    "Teams": "\uFFFD( Vincent Ngula )",
    "SXL": "KEN",
    "Latp": "77",
    "Player_1": "Donnarumma 2",
    "Player_11": "Gy\u00F6keres 7",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Cherki 10",
    "Player_14": "Caicedo 10",
    "Player_7": "Mbeumo 2",
    "Player_2": "J.Timber 6",
    "Player_5": "Yoro 1",
    "Player_6": "Cunha 4",
    "Player_3": "Gabriel 12",
    "Player_4": "Van Hecke",
    "Player_8": "Bruno G.",
    "Player_9": "Welbeck 6",
    "Player_15": "Burn 1"
  },
  {
    "manager_Name": "760( 16 )",
    "Teams": "cabdixaafidmaxamed( Cabdi Jeeriya )",
    "SXL": "SOM",
    "Latp": "80",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Thiago 2",
    "Player_12": "Vicario 4",
    "Player_13": "Senesi 3",
    "Player_14": "Foden 4",
    "Player_7": "Caicedo 10",
    "Player_2": "Gabriel 12",
    "Player_5": "Mbeumo 2",
    "Player_6": "Rice 13",
    "Player_3": "Mukiele 1",
    "Player_4": "Virgil 5",
    "Player_8": "Semenyo 2",
    "Player_9": "Woltemade 1",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "759( 17 )",
    "Teams": "TheYellowFlash( Brent Paulse )",
    "SXL": "ZAF",
    "Latp": "90",
    "Player_1": "Pope 3",
    "Player_11": "Haaland 26",
    "Player_10": "Mateta 9",
    "Player_12": "S\u00E1nchez 6",
    "Player_13": "Burn 1",
    "Player_14": "Welbeck 6",
    "Player_7": "Semenyo 2",
    "Player_2": "Gabriel 12",
    "Player_5": "Ndiaye 9",
    "Player_6": "Sarr 3",
    "Player_3": "Mitchell 6",
    "Player_4": "Van de",
    "Player_8": "Mbeumo 2",
    "Player_9": "Eze 3",
    "Player_15": "Cash 0"
  },
  {
    "manager_Name": "758( 18 )",
    "Teams": "MI fc( Kagujje Thanos )",
    "SXL": "UGA",
    "Latp": "78",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Mateta 9",
    "Player_12": "Jos\u00E9 S\u00E1",
    "Player_13": "Van de",
    "Player_14": "Xhaka 10",
    "Player_7": "Eze 3",
    "Player_2": "Mitchell 6",
    "Player_5": "Sarr 3",
    "Player_6": "Semenyo 2",
    "Player_3": "Romero 1",
    "Player_4": "Gabriel 12",
    "Player_8": "Kudus 1",
    "Player_9": "Haaland 26",
    "Player_15": "Chalobah 7"
  },
  {
    "manager_Name": "758( 19 )",
    "Teams": "Jurgenmeister( Simon Herbert )",
    "SXL": "ENG",
    "Latp": "81",
    "Player_1": "Raya 6",
    "Player_11": "Mateta 9",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Senesi 3",
    "Player_14": "Caicedo 10",
    "Player_7": "Semenyo 2",
    "Player_2": "Gabriel 12",
    "Player_5": "Ndiaye 9",
    "Player_6": "Kudus 1",
    "Player_3": "Mu\u00F1oz 6",
    "Player_4": "Cucurella 7",
    "Player_8": "Mbeumo 2",
    "Player_9": "Woltemade 1",
    "Player_15": "Hoever 1"
  },
  {
    "manager_Name": "757( 20 )",
    "Teams": "Saliba the solution( Jacob Davis )",
    "SXL": "ENG",
    "Latp": "99",
    "Player_1": "Raya 6",
    "Player_11": "Mateta 9",
    "Player_10": "Haaland 26",
    "Player_12": "A.Becker 0",
    "Player_13": "Livramento 0",
    "Player_14": "Edozie 0",
    "Player_7": "Rice 13",
    "Player_2": "Gabriel 12",
    "Player_5": "Gu\u00E9hi 10",
    "Player_6": "Foden 4",
    "Player_3": "Burn 1",
    "Player_4": "Cucurella 7",
    "Player_8": "Semenyo 2",
    "Player_9": "Richarlison 1",
    "Player_15": "J.Murphy 8"
  },
  {
    "manager_Name": "757( 21 )",
    "Teams": "Up on the Roefs( Matthew Coggin )",
    "SXL": "ENG",
    "Latp": "104",
    "Player_1": "Roefs 2",
    "Player_11": "Haaland 26",
    "Player_10": "Mateta 9",
    "Player_12": "Vicario 4",
    "Player_13": "Tarkowski 2",
    "Player_14": "Semenyo 2",
    "Player_7": "Eze 3",
    "Player_2": "Gu\u00E9hi 10",
    "Player_5": "Van de",
    "Player_6": "Xhaka 10",
    "Player_3": "Gabriel 12",
    "Player_4": "Cucurella 7",
    "Player_8": "Rice 13",
    "Player_9": "Caicedo 10",
    "Player_15": "Woltemade 1"
  },
  {
    "manager_Name": "757( 22 )",
    "Teams": "gnik fc( Gnik Paul )",
    "SXL": "KEN",
    "Latp": "88",
    "Player_1": "Raya 6",
    "Player_11": "\u0160e\u0161ko 2",
    "Player_10": "Haaland 26",
    "Player_12": "Pickford 2",
    "Player_13": "Bassey 6",
    "Player_14": "Baleba 3",
    "Player_7": "Semenyo 2",
    "Player_2": "J.Timber 6",
    "Player_5": "Cucurella 7",
    "Player_6": "Mbeumo 2",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "Gabriel 12",
    "Player_8": "Caicedo 10",
    "Player_9": "B.Fernandes 5",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "757( 23 )",
    "Teams": "Croydon Eagles( Luke Townsend )",
    "SXL": "ENG",
    "Latp": "79",
    "Player_1": "Pope 3",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Gy\u00F6keres 7",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Reijnders 1",
    "Player_14": "Van de",
    "Player_7": "Enzo 2",
    "Player_2": "Mu\u00F1oz 6",
    "Player_5": "Mbeumo 2",
    "Player_6": "Semenyo 2",
    "Player_3": "Mukiele 1",
    "Player_4": "Gabriel 12",
    "Player_8": "Ndiaye 9",
    "Player_9": "Haaland 26",
    "Player_15": "Senesi 3"
  },
  {
    "manager_Name": "757( 24 )",
    "Teams": "FatKRATOS( Ryan Madigan )",
    "SXL": "ENG",
    "Latp": "71",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 1",
    "Player_10": "Haaland 26",
    "Player_12": "Hermansen 0",
    "Player_13": "Van de",
    "Player_14": "Tonali 2",
    "Player_7": "Gakpo 3",
    "Player_2": "Gu\u00E9hi 10",
    "Player_5": "Kudus 1",
    "Player_6": "Semenyo 2",
    "Player_3": "Calafiori 6",
    "Player_4": "Gabriel 12",
    "Player_8": "Mbeumo 2",
    "Player_9": "Bowen 2",
    "Player_15": "Diouf 2"
  },
  {
    "manager_Name": "756( 25 )",
    "Teams": "Pain in Dias( Dougie Shukie )",
    "SXL": "ENG",
    "Latp": "98",
    "Player_1": "Donnarumma 2",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Wieffer 10",
    "Player_14": "Marc Guiu",
    "Player_7": "Ndiaye 9",
    "Player_2": "Gabriel 12",
    "Player_5": "Gu\u00E9hi 10",
    "Player_6": "Mbeumo 2",
    "Player_3": "Saliba 6",
    "Player_4": "Van de",
    "Player_8": "M.Salah 10",
    "Player_9": "Caicedo 10",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "756( 26 )",
    "Teams": "losksjsns( Alex Simons )",
    "SXL": "ENG",
    "Latp": "83",
    "Player_1": "Pickford 2",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Ramsdale 0",
    "Player_13": "Grealish 2",
    "Player_14": "Van de",
    "Player_7": "Semenyo 2",
    "Player_2": "Gabriel 12",
    "Player_5": "Enzo 2",
    "Player_6": "Eze 3",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "Senesi 3",
    "Player_8": "Rice 13",
    "Player_9": "Woltemade 1",
    "Player_15": "Richards 6"
  },
  {
    "manager_Name": "755( 27 )",
    "Teams": "Jonas Fc( Jonas Bernotas )",
    "SXL": "IRL",
    "Latp": "104",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "S\u00E1nchez 6",
    "Player_13": "Pedro Porro",
    "Player_14": "Semenyo 2",
    "Player_7": "Rice 13",
    "Player_2": "Gabriel 12",
    "Player_5": "Gu\u00E9hi 10",
    "Player_6": "Kudus 1",
    "Player_3": "Virgil 5",
    "Player_4": "Gvardiol 2",
    "Player_8": "Caicedo 10",
    "Player_9": "Xhaka 10",
    "Player_15": "Watkins 2"
  },
  {
    "manager_Name": "755( 28 )",
    "Teams": "ThomasTheFrankEngine( Chris Masters )",
    "SXL": "ENG",
    "Latp": "84",
    "Player_1": "Raya 6",
    "Player_11": "Mateta 9",
    "Player_10": "Bowen 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Enzo 2",
    "Player_14": "Ndiaye 9",
    "Player_7": "Semenyo 2",
    "Player_2": "Van de",
    "Player_5": "Calafiori 6",
    "Player_6": "Rice 13",
    "Player_3": "Mu\u00F1oz 6",
    "Player_4": "Gu\u00E9hi 10",
    "Player_8": "Mbeumo 2",
    "Player_9": "Haaland 26",
    "Player_15": "Spence 2"
  },
  {
    "manager_Name": "754( 29 )",
    "Teams": "Team 26( Andrew Jennings )",
    "SXL": "ENG",
    "Latp": "90",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 2",
    "Player_10": "Haaland 26",
    "Player_12": "Verbruggen 6",
    "Player_13": "Lacroix 8",
    "Player_14": "Grealish 2",
    "Player_7": "Semenyo 2",
    "Player_2": "Mu\u00F1oz 6",
    "Player_5": "Gabriel 12",
    "Player_6": "Rice 13",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "Van de",
    "Player_8": "Caicedo 10",
    "Player_9": "Woltemade 1",
    "Player_15": "Anthony 2"
  },
  {
    "manager_Name": "752( 30 )",
    "Teams": "Buffelsfontein FC( JEFF ABSALOM )",
    "SXL": "ZAF",
    "Latp": "98",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 39",
    "Player_12": "Henderson 6",
    "Player_13": "Ballard 4",
    "Player_14": "Eze 3",
    "Player_7": "B.Fernandes 5",
    "Player_2": "Pedro Porro",
    "Player_5": "Chalobah 7",
    "Player_6": "Caicedo 10",
    "Player_3": "Virgil 5",
    "Player_4": "Gabriel 12",
    "Player_8": "Semenyo 2",
    "Player_9": "Kudus 1",
    "Player_15": "Fraser 0"
  },
  {
    "manager_Name": "752( 31 )",
    "Teams": "Stevens Team( Steven Murphy )",
    "SXL": "IRL",
    "Latp": "100",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Mateta 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "O\u2019Reilly 8",
    "Player_14": "Gu\u00E9hi 10",
    "Player_7": "Kudus 1",
    "Player_2": "Pedro Porro",
    "Player_5": "Eze 3",
    "Player_6": "Semenyo 2",
    "Player_3": "Virgil 5",
    "Player_4": "Gabriel 12",
    "Player_8": "Mbeumo 2",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "King 3"
  },
  {
    "manager_Name": "752( 32 )",
    "Teams": "Absolutely Fabregas( Kia Anglin )",
    "SXL": "IRL",
    "Latp": "88",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 1",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Van de",
    "Player_14": "Senesi 3",
    "Player_7": "Gakpo 3",
    "Player_2": "Gu\u00E9hi 10",
    "Player_5": "Caicedo 10",
    "Player_6": "B.Fernandes 5",
    "Player_3": "Gabriel 12",
    "Player_4": "Ballard 4",
    "Player_8": "Semenyo 2",
    "Player_9": "Mateta 9",
    "Player_15": "Reijnders 1"
  },
  {
    "manager_Name": "752( 33 )",
    "Teams": "Vamos!!( Gaurav Sareen )",
    "SXL": "IND",
    "Latp": "91",
    "Player_1": "Henderson 6",
    "Player_11": "Gy\u00F6keres 7",
    "Player_10": "Mateta 9",
    "Player_12": "Vicario 4",
    "Player_13": "Konsa 1",
    "Player_14": "Reijnders 1",
    "Player_7": "Semenyo 2",
    "Player_2": "Van de",
    "Player_5": "Mbeumo 2",
    "Player_6": "Rice 13",
    "Player_3": "Gabriel 12",
    "Player_4": "Gu\u00E9hi 10",
    "Player_8": "Enzo 2",
    "Player_9": "Haaland 26",
    "Player_15": "R\u00FAben 2"
  },
  {
    "manager_Name": "751( 34 )",
    "Teams": "Bigos most hated( Josh Cut )",
    "SXL": "ENG",
    "Latp": "94",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "Heaton 0",
    "Player_13": "Silcott-Duberry 0",
    "Player_14": "A\u00EFt-Nouri 1",
    "Player_7": "Caicedo 10",
    "Player_2": "R\u00FAben 2",
    "Player_5": "Van Hecke",
    "Player_6": "M.Salah 10",
    "Player_3": "Gabriel 12",
    "Player_4": "J.Timber 6",
    "Player_8": "Semenyo 2",
    "Player_9": "J.Palhinha 4",
    "Player_15": "Obi 0"
  },
  {
    "manager_Name": "751( 35 )",
    "Teams": "Hals XI( Eoghan Hallissey )",
    "SXL": "IRL",
    "Latp": "104",
    "Player_1": "Raya 6",
    "Player_11": "Welbeck 6",
    "Player_10": "Mateta 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "R\u00FAben 2",
    "Player_14": "Wan-Bissaka 7",
    "Player_7": "Semenyo 2",
    "Player_2": "Gu\u00E9hi 10",
    "Player_5": "Mbeumo 2",
    "Player_6": "Kudus 1",
    "Player_3": "Senesi 3",
    "Player_4": "Gabriel 12",
    "Player_8": "Rice 13",
    "Player_9": "Haaland 26",
    "Player_15": "Sarr 3"
  },
  {
    "manager_Name": "751( 35 )",
    "Teams": "Al_Mo7nk( Montadher Mohammed )",
    "SXL": "IRQ",
    "Latp": "78",
    "Player_1": "Pope 3",
    "Player_11": "Mateta 9",
    "Player_10": "Haaland 26",
    "Player_12": "Petrovi\u0107 2",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Caicedo 10",
    "Player_7": "Semenyo 2",
    "Player_2": "J.Timber 6",
    "Player_5": "Senesi 3",
    "Player_6": "Gu\u00E9hi 10",
    "Player_3": "Gabriel 12",
    "Player_4": "Burn 1",
    "Player_8": "Gakpo 3",
    "Player_9": "Sarr 3",
    "Player_15": "Kudus 1"
  },
  {
    "manager_Name": "751( 37 )",
    "Teams": "N5( Graham Allen )",
    "SXL": "ENG",
    "Latp": "112",
    "Player_1": "Sels 2",
    "Player_11": "Welbeck 6",
    "Player_10": "Mateta 9",
    "Player_12": "Darlow 0",
    "Player_13": "Reinildo 2",
    "Player_14": "Semenyo 2",
    "Player_7": "Minteh 9",
    "Player_2": "Gu\u00E9hi 10",
    "Player_5": "Saka 3",
    "Player_6": "Rice 13",
    "Player_3": "Gabriel 12",
    "Player_4": "Cucurella 7",
    "Player_8": "Mbeumo 2",
    "Player_9": "Haaland 39",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "751( 38 )",
    "Teams": "simers snipers( omally robin )",
    "SXL": "DMA",
    "Latp": "91",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Welbeck 6",
    "Player_12": "Roefs 2",
    "Player_13": "Mitchell 6",
    "Player_14": "Enzo 2",
    "Player_7": "Semenyo 2",
    "Player_2": "Gabriel 12",
    "Player_5": "Gu\u00E9hi 10",
    "Player_6": "Kudus 1",
    "Player_3": "J.Timber 6",
    "Player_4": "Van de",
    "Player_8": "Gakpo 3",
    "Player_9": "B.Fernandes 5",
    "Player_15": "Calvert-Lewin 2"
  },
  {
    "manager_Name": "751( 39 )",
    "Teams": "Fifmer( Micha\u0142 Jastrz\u0119bski )",
    "SXL": "POL",
    "Latp": "87",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Welbeck 6",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Caicedo 10",
    "Player_14": "Virgil 5",
    "Player_7": "Zubimendi 3",
    "Player_2": "Gabriel 12",
    "Player_5": "Mu\u00F1oz 6",
    "Player_6": "B.Fernandes 5",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "Van de",
    "Player_8": "Mbeumo 2",
    "Player_9": "Mateta 9",
    "Player_15": "Semenyo 2"
  },
  {
    "manager_Name": "750( 40 )",
    "Teams": "Change Name( Joshua Butcher )",
    "SXL": "AUS",
    "Latp": "98",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Darlow 0",
    "Player_13": "Wan-Bissaka 7",
    "Player_14": "A.Ramsey 0",
    "Player_7": "Semenyo 2",
    "Player_2": "Virgil 5",
    "Player_5": "Van de",
    "Player_6": "M.Salah 10",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "Gabriel 12",
    "Player_8": "Iwobi 3",
    "Player_9": "Rice 13",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "750( 41 )",
    "Teams": "Change Name( Elijah Cookson )",
    "SXL": "CAN",
    "Latp": "100",
    "Player_1": "Henderson 6",
    "Player_11": "Mateta 9",
    "Player_10": "Haaland 26",
    "Player_12": "Vicario 4",
    "Player_13": "Cucurella 7",
    "Player_14": "Ndiaye 9",
    "Player_7": "Bruno G.",
    "Player_2": "Gvardiol 2",
    "Player_5": "J.Timber 6",
    "Player_6": "Caicedo 10",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "Gabriel 12",
    "Player_8": "Rice 13",
    "Player_9": "Semenyo 2",
    "Player_15": "Woltemade 1"
  },
  {
    "manager_Name": "750( 42 )",
    "Teams": "Rice Rice Baby( Lewis Young )",
    "SXL": "ENG",
    "Latp": "103",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "Kinsky 0",
    "Player_13": "Reijnders 1",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "M.Salah 10",
    "Player_2": "Gabriel 12",
    "Player_5": "Gu\u00E9hi 10",
    "Player_6": "Semenyo 2",
    "Player_3": "Senesi 3",
    "Player_4": "Van de",
    "Player_8": "Caicedo 10",
    "Player_9": "Rice 13",
    "Player_15": "Kroupi.Jr 2"
  },
  {
    "manager_Name": "750( 42 )",
    "Teams": "Lallanas in Pyjamas( Catrina Macarthur )",
    "SXL": "ENG",
    "Latp": "85",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Rodon 1",
    "Player_14": "Rogers 1",
    "Player_7": "Semenyo 2",
    "Player_2": "Gabriel 12",
    "Player_5": "Gakpo 3",
    "Player_6": "Ndiaye 9",
    "Player_3": "Pedro Porro",
    "Player_4": "Van de",
    "Player_8": "B.Fernandes 5",
    "Player_9": "Mateta 9",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "750( 44 )",
    "Teams": "HavertzYourWay( Joel Rogers )",
    "SXL": "WAL",
    "Latp": "88",
    "Player_1": "Petrovi\u0107 2",
    "Player_11": "Mateta 9",
    "Player_10": "Haaland 26",
    "Player_12": "Kelleher 1",
    "Player_13": "Grealish 2",
    "Player_14": "Buend\u00EDa 0",
    "Player_7": "Kudus 1",
    "Player_2": "Gabriel 12",
    "Player_5": "Mu\u00F1oz 6",
    "Player_6": "Semenyo 2",
    "Player_3": "J.Timber 6",
    "Player_4": "Gu\u00E9hi 10",
    "Player_8": "Rice 13",
    "Player_9": "Woltemade 1",
    "Player_15": "Branthwaite 0"
  },
  {
    "manager_Name": "750( 44 )",
    "Teams": "Eyob( Eyob Admasu )",
    "SXL": "ETH",
    "Latp": "85",
    "Player_1": "Raya 6",
    "Player_11": "Mateta 9",
    "Player_10": "Haaland 26",
    "Player_12": "Martinez 1",
    "Player_13": "Burn 1",
    "Player_14": "Dunk 6",
    "Player_7": "Kudus 1",
    "Player_2": "J.Timber 6",
    "Player_5": "Minteh 9",
    "Player_6": "Neto 3",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "Gabriel 12",
    "Player_8": "Mbeumo 2",
    "Player_9": "Woltemade 1",
    "Player_15": "Caicedo 10"
  },
  {
    "manager_Name": "749( 46 )",
    "Teams": "bowen 747( harry dale )",
    "SXL": "ENG",
    "Latp": "83",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Bowen 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Caicedo 10",
    "Player_14": "Diouf 2",
    "Player_7": "B.Fernandes 5",
    "Player_2": "Van de",
    "Player_5": "Gu\u00E9hi 10",
    "Player_6": "Gakpo 3",
    "Player_3": "Gabriel 12",
    "Player_4": "J.Timber 6",
    "Player_8": "Semenyo 2",
    "Player_9": "Haaland 26",
    "Player_15": "Baleba 3"
  },
  {
    "manager_Name": "749( 47 )",
    "Teams": "Expect Toulouse FC( Bailey Armstrong )",
    "SXL": "ENG",
    "Latp": "111",
    "Player_1": "Donnarumma 2",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "S\u00E1nchez 6",
    "Player_13": "Senesi 3",
    "Player_14": "Van de",
    "Player_7": "Enzo 2",
    "Player_2": "Gabriel 12",
    "Player_5": "Reijnders 1",
    "Player_6": "Rice 13",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "Mu\u00F1oz 6",
    "Player_8": "Semenyo 2",
    "Player_9": "Gy\u00F6keres 7",
    "Player_15": "Xhaka 10"
  },
  {
    "manager_Name": "749( 47 )",
    "Teams": "tongue wagglers( Jack Pascall )",
    "SXL": "ENG",
    "Latp": "65",
    "Player_1": "Raya 6",
    "Player_11": "Mateta 9",
    "Player_10": "Haaland 26",
    "Player_12": "Pope 3",
    "Player_13": "Gu\u00E9hi 10",
    "Player_14": "Ndiaye 9",
    "Player_7": "Eze 3",
    "Player_2": "Burn 1",
    "Player_5": "Kudus 1",
    "Player_6": "Mbeumo 2",
    "Player_3": "Gabriel 12",
    "Player_4": "Van de",
    "Player_8": "Semenyo 2",
    "Player_9": "Woltemade 1",
    "Player_15": "Richards 6"
  },
  {
    "manager_Name": "749( 47 )",
    "Teams": "Left 4 Djed( Oliver Lovegrove )",
    "SXL": "ENG",
    "Latp": "97",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Leno 7",
    "Player_13": "Mu\u00F1oz 6",
    "Player_14": "Gakpo 3",
    "Player_7": "Kudus 1",
    "Player_2": "Cucurella 7",
    "Player_5": "Gu\u00E9hi 10",
    "Player_6": "Semenyo 2",
    "Player_3": "Gabriel 12",
    "Player_4": "Gvardiol 2",
    "Player_8": "Rice 13",
    "Player_9": "Ndiaye 9",
    "Player_15": "Calvert-Lewin 2"
  },
  {
    "manager_Name": "749( 50 )",
    "Teams": "Cancelo culture( Samuel Greathead )",
    "SXL": "NZL",
    "Latp": "93",
    "Player_1": "Roefs 2",
    "Player_11": "Mateta 9",
    "Player_10": "Haaland 26",
    "Player_12": "Raya 6",
    "Player_13": "Kerkez 0",
    "Player_14": "Reijnders 1",
    "Player_7": "Caicedo 10",
    "Player_2": "Gabriel 12",
    "Player_5": "Burn 1",
    "Player_6": "Kudus 1",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "Sch\u00E4r 1",
    "Player_8": "Eze 3",
    "Player_9": "Semenyo 2",
    "Player_15": "Jo\u00E3o Pedro"
  }
];