var s = [
  {
    "manager_Name": "692( 6,093 )",
    "Teams": "cavac215( Ankit Chhetri )",
    "SXL": "IND",
    "Latp": "83",
    "Player_1": "Pope 3",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Chalobah 7",
    "Player_14": "Calvert-Lewin 2",
    "Player_7": "Rice 13",
    "Player_2": "Gu\u00E9hi 10",
    "Player_5": "Kudus 1",
    "Player_6": "Saka 3",
    "Player_3": "Gabriel 12",
    "Player_4": "Van de",
    "Player_8": "Semenyo 2",
    "Player_9": "Mbeumo 2",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "656( 77,819 )",
    "Teams": "False 9( Rohan Rai )",
    "SXL": "IND",
    "Latp": "68",
    "Player_1": "Pope 3",
    "Player_11": "Gy\u00F6keres 7",
    "Player_10": "Woltemade 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Anthony 2",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Saka 3",
    "Player_2": "Mukiele EVE",
    "Player_5": "Kudus 1",
    "Player_6": "Sarr 3",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "Gabriel 12",
    "Player_8": "Semenyo 2",
    "Player_9": "Haaland 26",
    "Player_15": "Senesi 3"
  },
  {
    "manager_Name": "645( 148,967 )",
    "Teams": "PWS( Z S )",
    "SXL": "IND",
    "Latp": "83",
    "Player_1": "Donnarumma 2",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Reijnders 1",
    "Player_14": "Van de",
    "Player_7": "Gakpo 3",
    "Player_2": "Dorgu 1",
    "Player_5": "Rice 13",
    "Player_6": "Semenyo 2",
    "Player_3": "Gabriel 12",
    "Player_4": "J.Timber 6",
    "Player_8": "Grealish SUN",
    "Player_9": "Mateta 9",
    "Player_15": "Senesi 3"
  },
  {
    "manager_Name": "618( 543,620 )",
    "Teams": "error404( Duri Tadu )",
    "SXL": "IND",
    "Latp": "72",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Woltemade 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Andersen 6",
    "Player_14": "Rodon 1",
    "Player_7": "Semenyo 2",
    "Player_2": "Richards 6",
    "Player_5": "Enzo 2",
    "Player_6": "Saka 3",
    "Player_3": "Gabriel 12",
    "Player_4": "Virgil 5",
    "Player_8": "Ndiaye SUN",
    "Player_9": "Mateta 9",
    "Player_15": "Stach 1"
  },
  {
    "manager_Name": "614( 658,019 )",
    "Teams": "RIP-DIOGO.20( pranam rai )",
    "SXL": "IND",
    "Latp": "65",
    "Player_1": "Vicario 4",
    "Player_11": "\u0160e\u0161ko 2",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Cucurella 7",
    "Player_14": "Malen 1",
    "Player_7": "Gakpo 3",
    "Player_2": "Mu\u00F1oz 6",
    "Player_5": "Kudus 1",
    "Player_6": "Semenyo 2",
    "Player_3": "Gabriel 12",
    "Player_4": "J.Timber 6",
    "Player_8": "Mbeumo 2",
    "Player_9": "Woltemade 1",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "611( 722,933 )",
    "Teams": "Kung fu Pandoos( Indrajeet Singh )",
    "SXL": "IND",
    "Latp": "50",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Woltemade 1",
    "Player_10": "Haaland 26",
    "Player_12": "Kelleher 1",
    "Player_13": "Pedro Porro",
    "Player_14": "Walker 1",
    "Player_7": "Semenyo 2",
    "Player_2": "Virgil 5",
    "Player_5": "Grealish SUN",
    "Player_6": "Sarr 3",
    "Player_3": "Gvardiol 2",
    "Player_4": "De Ligt",
    "Player_8": "Mbeumo 2",
    "Player_9": "Bowen 2",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "610( 750,896 )",
    "Teams": "abcde FC( Prayash Thapa )",
    "SXL": "IND",
    "Latp": "77",
    "Player_1": "Roefs EVE",
    "Player_11": "Mateta 9",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Marc Guiu",
    "Player_14": "Senesi 3",
    "Player_7": "Mbeumo 2",
    "Player_2": "J.Timber 6",
    "Player_5": "Minteh 9",
    "Player_6": "Sarr 3",
    "Player_3": "Mu\u00F1oz 6",
    "Player_4": "Gabriel 12",
    "Player_8": "Enzo 2",
    "Player_9": "Semenyo 2",
    "Player_15": "James 7"
  },
  {
    "manager_Name": "609( 786,585 )",
    "Teams": "11 n over( Ashish Rai )",
    "SXL": "IND",
    "Latp": "70",
    "Player_1": "Raya 6",
    "Player_11": "Welbeck 6",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "O.Dango 2",
    "Player_7": "Minteh 9",
    "Player_2": "Diouf 2",
    "Player_5": "Gvardiol 2",
    "Player_6": "Kudus 1",
    "Player_3": "Mu\u00F1oz 6",
    "Player_4": "J.Timber 6",
    "Player_8": "Gakpo 3",
    "Player_9": "Saka 3",
    "Player_15": "Rodon 1"
  },
  {
    "manager_Name": "607( 839,227 )",
    "Teams": "Top Gooner( VibhutiHang Subba )",
    "SXL": "IND",
    "Latp": "61",
    "Player_1": "Raya 6",
    "Player_11": "Bowen 2",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Reijnders 1",
    "Player_14": "Pedro Porro",
    "Player_7": "Semenyo 2",
    "Player_2": "Mukiele EVE",
    "Player_5": "Mbeumo 2",
    "Player_6": "Eze 3",
    "Player_3": "Senesi 3",
    "Player_4": "Lacroix 8",
    "Player_8": "Saka 3",
    "Player_9": "Welbeck 6",
    "Player_15": "Rodon 1"
  },
  {
    "manager_Name": "595( 1,263,894 )",
    "Teams": "Blue Brigade( Bhuman Basnet )",
    "SXL": "IND",
    "Latp": "70",
    "Player_1": "Vicario 4",
    "Player_11": "Haaland 26",
    "Player_10": "Mateta 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Gudmundsson 1",
    "Player_14": "Tuanzebe 3",
    "Player_7": "Enzo 2",
    "Player_2": "Senesi 3",
    "Player_5": "Semenyo 2",
    "Player_6": "Kudus 1",
    "Player_3": "Calafiori 6",
    "Player_4": "Gabriel 12",
    "Player_8": "Sarr 3",
    "Player_9": "Mbeumo 2",
    "Player_15": "Barnes 0"
  },
  {
    "manager_Name": "595( 1,263,894 )",
    "Teams": "Alpha11( AVIJIT DAS )",
    "SXL": "IND",
    "Latp": "84",
    "Player_1": "Vicario 4",
    "Player_11": "Mateta 9",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Senesi 3",
    "Player_14": "King 3",
    "Player_7": "Saka 3",
    "Player_2": "Lacroix 8",
    "Player_5": "Enzo 2",
    "Player_6": "Semenyo 2",
    "Player_3": "Gabriel 12",
    "Player_4": "Chalobah 7",
    "Player_8": "Mbeumo 2",
    "Player_9": "Haaland 26",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "593( 1,342,879 )",
    "Teams": "\u0160e\u0161ko and Destroy( Pema Lepcha )",
    "SXL": "IND",
    "Latp": "48",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 13",
    "Player_10": "Woltemade 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Senesi 3",
    "Player_14": "Semenyo 2",
    "Player_7": "Mbeumo 4",
    "Player_2": "Mu\u00F1oz 6",
    "Player_5": "Gakpo 3",
    "Player_6": "Zubimendi 3",
    "Player_3": "Acheampong 0",
    "Player_4": "Calafiori 6",
    "Player_8": "Grealish SUN",
    "Player_9": "Welbeck 6",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "588( 1,533,224 )",
    "Teams": "MANCHESTER IS BLUE( PRAYAS BAJGAI )",
    "SXL": "IND",
    "Latp": "73",
    "Player_1": "Pope 3",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Calvert-Lewin 2",
    "Player_14": "Rodon 1",
    "Player_7": "Gordon 1",
    "Player_2": "Andersen 6",
    "Player_5": "Saka 3",
    "Player_6": "Enzo 2",
    "Player_3": "Gabriel 12",
    "Player_4": "J.Timber 6",
    "Player_8": "Semenyo 2",
    "Player_9": "Sarr 3",
    "Player_15": "Senesi 3"
  },
  {
    "manager_Name": "586( 1,630,657 )",
    "Teams": "F.C. ASSASSINS( Kushal Sahota )",
    "SXL": "IND",
    "Latp": "79",
    "Player_1": "Roefs EVE",
    "Player_11": "Haaland 26",
    "Player_10": "Richarlison 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Senesi 3",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "Caicedo 10",
    "Player_2": "Gu\u00E9hi 10",
    "Player_5": "Sarr 3",
    "Player_6": "M.Salah 10",
    "Player_3": "J.Timber 6",
    "Player_4": "Van de",
    "Player_8": "Semenyo 2",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "King 3"
  },
  {
    "manager_Name": "581( 1,881,654 )",
    "Teams": "Comet FC( Pranesh Sharma )",
    "SXL": "IND",
    "Latp": "59",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Haaland 26",
    "Player_10": "Woltemade 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Anthony 2",
    "Player_14": "Senesi 3",
    "Player_7": "Kudus 1",
    "Player_2": "Calafiori 6",
    "Player_5": "Saka 3",
    "Player_6": "Semenyo 2",
    "Player_3": "Cash 0",
    "Player_4": "Andersen 6",
    "Player_8": "Mbeumo 2",
    "Player_9": "Welbeck 6",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "577( 2,052,182 )",
    "Teams": "ASHLAD FC( Ashim Lama )",
    "SXL": "IND",
    "Latp": "75",
    "Player_1": "Roefs EVE",
    "Player_11": "Haaland 26",
    "Player_10": "Mateta 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Van de",
    "Player_14": "Senesi 3",
    "Player_7": "Ndiaye SUN",
    "Player_2": "Gvardiol 2",
    "Player_5": "Rice 13",
    "Player_6": "Mbeumo 2",
    "Player_3": "Gabriel 12",
    "Player_4": "J.Timber 6",
    "Player_8": "Semenyo 2",
    "Player_9": "Sarr 3",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "576( 2,112,204 )",
    "Teams": "Lu Lu( Nishant Lohagun )",
    "SXL": "IND",
    "Latp": "68",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 1",
    "Player_10": "Marc Guiu",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Reijnders 1",
    "Player_14": "Richards 6",
    "Player_7": "Enzo 2",
    "Player_2": "Andersen 6",
    "Player_5": "B.Fernandes 5",
    "Player_6": "Semenyo 2",
    "Player_3": "Gabriel 24",
    "Player_4": "Mu\u00F1oz 6",
    "Player_8": "Saka 3",
    "Player_9": "Haaland 13",
    "Player_15": "Senesi 3"
  },
  {
    "manager_Name": "574( 2,195,707 )",
    "Teams": "PINE( SATYAM RAI )",
    "SXL": "IND",
    "Latp": "63",
    "Player_1": "Raya 6",
    "Player_11": "Mateta 9",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Van de",
    "Player_14": "Marc Guiu",
    "Player_7": "Semenyo 2",
    "Player_2": "Gabriel 12",
    "Player_5": "Mbeumo 2",
    "Player_6": "Ndiaye SUN",
    "Player_3": "Mukiele EVE",
    "Player_4": "Burn 1",
    "Player_8": "Saka 3",
    "Player_9": "Enzo 2",
    "Player_15": "Senesi 3"
  },
  {
    "manager_Name": "559( 3,026,709 )",
    "Teams": "G\u00CBNJ\u00CF\u00CF UNITED( Pema Bhutia )",
    "SXL": "IND",
    "Latp": "69",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Mateta 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Stach 1",
    "Player_14": "Senesi 3",
    "Player_7": "Semenyo 2",
    "Player_2": "Van de",
    "Player_5": "Richards 6",
    "Player_6": "Saka 3",
    "Player_3": "Gabriel 12",
    "Player_4": "Alderete EVE",
    "Player_8": "Mbeumo 2",
    "Player_9": "Woltemade 1",
    "Player_15": "Anthony 2"
  },
  {
    "manager_Name": "557( 3,124,488 )",
    "Teams": "Liverpool FC( Sunil Rai )",
    "SXL": "IND",
    "Latp": "84",
    "Player_1": "Leno 7",
    "Player_11": "Haaland 26",
    "Player_10": "Mateta 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Mukiele EVE",
    "Player_14": "Rodon 1",
    "Player_7": "Mbeumo 2",
    "Player_2": "Mu\u00F1oz 6",
    "Player_5": "Sarr 3",
    "Player_6": "Saka 3",
    "Player_3": "Gabriel 12",
    "Player_4": "J.Timber 6",
    "Player_8": "Minteh 9",
    "Player_9": "Woltemade 1",
    "Player_15": "King 3"
  },
  {
    "manager_Name": "556( 3,155,403 )",
    "Teams": "Fu\u00DFball-Mannschaft( Gaurav Shrestha )",
    "SXL": "IND",
    "Latp": "68",
    "Player_1": "Donnarumma 2",
    "Player_11": "Gy\u00F6keres 7",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Stach 1",
    "Player_14": "Andersen 6",
    "Player_7": "Ndiaye SUN",
    "Player_2": "Gabriel 12",
    "Player_5": "B.Fernandes 5",
    "Player_6": "Semenyo 2",
    "Player_3": "Senesi 3",
    "Player_4": "Rodon 1",
    "Player_8": "Reijnders 1",
    "Player_9": "Haaland 26",
    "Player_15": "Tarkowski SUN"
  },
  {
    "manager_Name": "551( 3,464,526 )",
    "Teams": "Native United( Monlom Rongong )",
    "SXL": "IND",
    "Latp": "66",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Mateta 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Gu\u00E9hi 10",
    "Player_14": "Senesi 3",
    "Player_7": "Semenyo 2",
    "Player_2": "Rodon 1",
    "Player_5": "Mbeumo 2",
    "Player_6": "Ndiaye SUN",
    "Player_3": "Gabriel 12",
    "Player_4": "J.Timber 6",
    "Player_8": "Kudus 1",
    "Player_9": "Woltemade 1",
    "Player_15": "King 3"
  },
  {
    "manager_Name": "548( 3,616,385 )",
    "Teams": "GustavousGooner( Ashish Subba )",
    "SXL": "IND",
    "Latp": "70",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Gy\u00F6keres 7",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Senesi 3",
    "Player_14": "Cullen 1",
    "Player_7": "Enzo 2",
    "Player_2": "Gu\u00E9hi 10",
    "Player_5": "Szoboszlai 2",
    "Player_6": "Semenyo 2",
    "Player_3": "Gudmundsson 1",
    "Player_4": "Pedro Porro",
    "Player_8": "Saka 3",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Livramento 0"
  },
  {
    "manager_Name": "547( 3,684,775 )",
    "Teams": "Bruno-nly Fans( Bejoy M Shrestha\u00B2\u2076\u2074 )",
    "SXL": "IND",
    "Latp": "65",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 1",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Van de",
    "Player_14": "King 3",
    "Player_7": "Ndiaye SUN",
    "Player_2": "Burn 1",
    "Player_5": "Saka 3",
    "Player_6": "Semenyo 2",
    "Player_3": "Gabriel 12",
    "Player_4": "Senesi 3",
    "Player_8": "Mbeumo 2",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "546( 3,742,227 )",
    "Teams": "Cheesygarlic( Rishi Thulung )",
    "SXL": "IND",
    "Latp": "56",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Mukiele EVE",
    "Player_14": "Senesi 3",
    "Player_7": "Saka 3",
    "Player_2": "J.Timber 6",
    "Player_5": "Mbeumo 2",
    "Player_6": "Semenyo 2",
    "Player_3": "Tarkowski SUN",
    "Player_4": "Botman -1",
    "Player_8": "Enzo 2",
    "Player_9": "Reijnders 1",
    "Player_15": "Kroupi.Jr 2"
  },
  {
    "manager_Name": "540( 4,112,109 )",
    "Teams": "The Regista.( Passang T Sherpa )",
    "SXL": "IND",
    "Latp": "71",
    "Player_1": "Roefs EVE",
    "Player_11": "Woltemade 1",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Grealish SUN",
    "Player_14": "Reijnders 1",
    "Player_7": "Semenyo 2",
    "Player_2": "Cucurella 7",
    "Player_5": "Gu\u00E9hi 10",
    "Player_6": "Mbeumo 2",
    "Player_3": "Calafiori 6",
    "Player_4": "Gabriel 12",
    "Player_8": "Eze 3",
    "Player_9": "Thiago 2",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "534( 4,437,214 )",
    "Teams": "Hooligans25( Pradhyumna Subba )",
    "SXL": "IND",
    "Latp": "52",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 13",
    "Player_10": "Woltemade 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Van de",
    "Player_14": "Reijnders 1",
    "Player_7": "Sarr 3",
    "Player_2": "Gabriel 12",
    "Player_5": "Neto 3",
    "Player_6": "Mbeumo 2",
    "Player_3": "Reinildo EVE",
    "Player_4": "J.Timber 6",
    "Player_8": "Doku 2",
    "Player_9": "Ekitik\u00E9 4",
    "Player_15": "Richards 6"
  },
  {
    "manager_Name": "527( 4,863,228 )",
    "Teams": "Busby Baby( Regean Lama )",
    "SXL": "IND",
    "Latp": "55",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Woltemade 1",
    "Player_10": "Isidor EVE",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Reijnders 1",
    "Player_14": "Dorgu 1",
    "Player_7": "Kudus 1",
    "Player_2": "Van de",
    "Player_5": "Grealish SUN",
    "Player_6": "Semenyo 2",
    "Player_3": "J.Timber 6",
    "Player_4": "Mu\u00F1oz 6",
    "Player_8": "B.Fernandes 5",
    "Player_9": "Haaland 26",
    "Player_15": "Alex Moreno"
  },
  {
    "manager_Name": "526( 4,894,243 )",
    "Teams": "I_am_done_XI( Dipen Thapa )",
    "SXL": "IND",
    "Latp": "75",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 14",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Wood 0",
    "Player_14": "Senesi 3",
    "Player_7": "M.Salah 10",
    "Player_2": "Konsa 1",
    "Player_5": "Semenyo 2",
    "Player_6": "Caicedo 10",
    "Player_3": "Gu\u00E9hi 10",
    "Player_4": "Gabriel 12",
    "Player_8": "Grealish SUN",
    "Player_9": "Kudus 1",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "522( 5,137,516 )",
    "Teams": "GODFATHER FC( Riwaj Rai )",
    "SXL": "IND",
    "Latp": "69",
    "Player_1": "D\u00FAbravka 2",
    "Player_11": "Haaland 26",
    "Player_10": "Isidor EVE",
    "Player_12": "Sels 2",
    "Player_13": "Cash 0",
    "Player_14": "Reijnders 1",
    "Player_7": "Caicedo 10",
    "Player_2": "Gu\u00E9hi 10",
    "Player_5": "Kudus 1",
    "Player_6": "O.Dango 2",
    "Player_3": "Cucurella 7",
    "Player_4": "Pedro Porro",
    "Player_8": "Grealish SUN",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "521( 5,194,624 )",
    "Teams": "Imperial Blues( Saurabh Tamang )",
    "SXL": "IND",
    "Latp": "75",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Mateta 9",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Senesi 3",
    "Player_14": "Foster 0",
    "Player_7": "Mbeumo 2",
    "Player_2": "Gabriel 12",
    "Player_5": "Caicedo 10",
    "Player_6": "Semenyo 2",
    "Player_3": "Richards 6",
    "Player_4": "Botman -1",
    "Player_8": "Ndiaye SUN",
    "Player_9": "Zubimendi 3",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "507( 5,986,925 )",
    "Teams": "GUNNERS( Omkar Subba )",
    "SXL": "IND",
    "Latp": "86",
    "Player_1": "Vicario 4",
    "Player_11": "Thiago 2",
    "Player_10": "Haaland 26",
    "Player_12": "Verbruggen 6",
    "Player_13": "Van de",
    "Player_14": "Senesi 3",
    "Player_7": "Gravenberch 11",
    "Player_2": "Gu\u00E9hi 10",
    "Player_5": "Caicedo 10",
    "Player_6": "Semenyo 2",
    "Player_3": "Virgil 5",
    "Player_4": "Gabriel 12",
    "Player_8": "Zubimendi 3",
    "Player_9": "Woltemade 1",
    "Player_15": "Anthony 2"
  },
  {
    "manager_Name": "502( 6,254,174 )",
    "Teams": "Hangkim_0011( ABHINANDAN RAI )",
    "SXL": "IND",
    "Latp": "67",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Est\u00E8ve 1",
    "Player_14": "Ndiaye SUN",
    "Player_7": "Gakpo 3",
    "Player_2": "Pedro Porro",
    "Player_5": "Reijnders 1",
    "Player_6": "Rice 13",
    "Player_3": "Burn 1",
    "Player_4": "R\u00FAben 2",
    "Player_8": "Semenyo 2",
    "Player_9": "Ekitik\u00E9 2",
    "Player_15": "Konsa 1"
  },
  {
    "manager_Name": "497( 6,516,629 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "74",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Gy\u00F6keres 7",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "L.Paquet\u00E1 9",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Reijnders 1",
    "Player_2": "Gabriel 12",
    "Player_5": "Mukiele EVE",
    "Player_6": "Xhaka EVE",
    "Player_3": "Cucurella 7",
    "Player_4": "Senesi 3",
    "Player_8": "M.Salah 10",
    "Player_9": "Thiago 2",
    "Player_15": "L.Miley 0"
  },
  {
    "manager_Name": "486( 7,094,280 )",
    "Teams": "Jorebungalow YFC( Vivek Lama )",
    "SXL": "IND",
    "Latp": "60",
    "Player_1": "Mamardashvili 7",
    "Player_11": "Woltemade 1",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "L.Miley 0",
    "Player_14": "James 7",
    "Player_7": "Semenyo 2",
    "Player_2": "Calafiori 6",
    "Player_5": "Kudus 1",
    "Player_6": "Saka 3",
    "Player_3": "Van de",
    "Player_4": "Trippier 0",
    "Player_8": "Gakpo 3",
    "Player_9": "Haaland 26",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "479( 7,437,543 )",
    "Teams": "Let MEE COOK( \u00CFaraplang Pompyrthat )",
    "SXL": "IND",
    "Latp": "43",
    "Player_1": "Pope 3",
    "Player_11": "Haaland 13",
    "Player_10": "Woltemade 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Kudus 1",
    "Player_14": "Rodon 1",
    "Player_7": "Xhaka EVE",
    "Player_2": "J.Timber 6",
    "Player_5": "Mbeumo 2",
    "Player_6": "Semenyo 2",
    "Player_3": "Senesi 3",
    "Player_4": "Burn 1",
    "Player_8": "Enzo 2",
    "Player_9": "Mateta 9",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "464( 8,129,579 )",
    "Teams": "Boehly Blues( Aditya Bhandari )",
    "SXL": "IND",
    "Latp": "60",
    "Player_1": "D\u00FAbravka 2",
    "Player_11": "Haaland 13",
    "Player_10": "Woltemade 1",
    "Player_12": "Petrovi\u0107 2",
    "Player_13": "Stach 1",
    "Player_14": "Senesi 3",
    "Player_7": "Saka 6",
    "Player_2": "J.Timber 6",
    "Player_5": "Enzo 2",
    "Player_6": "Anthony 2",
    "Player_3": "James 7",
    "Player_4": "Gu\u00E9hi 10",
    "Player_8": "Semenyo 2",
    "Player_9": "Mateta 9",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "433( 9,296,302 )",
    "Teams": "Invincibles( Bishal Rai )",
    "SXL": "IND",
    "Latp": "58",
    "Player_1": "Raya 6",
    "Player_11": "Ekitik\u00E9 2",
    "Player_10": "Mateta 9",
    "Player_12": "Kinsky 0",
    "Player_13": "Johnson 1",
    "Player_14": "Wood 0",
    "Player_7": "Semenyo 2",
    "Player_2": "Mu\u00F1oz 6",
    "Player_5": "Gabriel 12",
    "Player_6": "Enzo 2",
    "Player_3": "J.Timber 12",
    "Player_4": "Pedro Porro",
    "Player_8": "Mbeumo 2",
    "Player_9": "Neto 3",
    "Player_15": "Milenkovi\u0107 1"
  }
];