var s = [
  {
    "manager_Name": "3760( 80 )",
    "Teams": "Sound of Da Tzolis( VibhutiHang Subba )",
    "SXL": "IN",
    "Latp": "80\nTotal Points",
    "Player_1": "Kinsky 2",
    "Player_2": "White 11",
    "Player_3": "Calafiori 9",
    "Player_4": "Ballard 0",
    "Player_5": "Schade 3",
    "Player_6": "Mbeumo 2",
    "Player_7": "Tzolis 6",
    "Player_8": "B.Fernandes 2",
    "Player_9": "Calvert-Lewin 1",
    "Player_10": "Brobbey 2",
    "Player_11": "Haaland 2",
    "Player_12": "Verbruggen 6",
    "Player_13": "Maguire 1",
    "Player_14": "De Cuyper 17",
    "Player_15": "M.Sangaré 14"
  },
  {
    "manager_Name": "9648( 76 )",
    "Teams": "Devil’s Magic( Pranoy basnett )",
    "SXL": "IN",
    "Latp": "76\nTotal Points",
    "Player_1": "Kinsky 2",
    "Player_2": "Maguire 1",
    "Player_3": "Calafiori 9",
    "Player_4": "Muharemović 6",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Mbeumo 2",
    "Player_7": "M.Sangaré 14",
    "Player_8": "Tzolis 6",
    "Player_9": "Szoboszlai 8",
    "Player_10": "Haaland 2",
    "Player_11": "Calvert-Lewin 1",
    "Player_12": "Verbruggen 6",
    "Player_13": "F.Kadıoğlu 0",
    "Player_14": "Kayode 13",
    "Player_15": "Brobbey 2"
  },
  {
    "manager_Name": "93106( 65 )",
    "Teams": "Deadline Day Squad( Abhinandan Rai )",
    "SXL": "IN",
    "Latp": "65\nTotal Points",
    "Player_1": "Kinsky 2",
    "Player_2": "Calafiori 9",
    "Player_3": "Ballard 0",
    "Player_4": "Shaw 1",
    "Player_5": "Szoboszlai 8",
    "Player_6": "Groß 2",
    "Player_7": "E.Le Fée 2",
    "Player_8": "B.Fernandes 2",
    "Player_9": "Haaland 2",
    "Player_10": "Havertz 6",
    "Player_11": "Calvert-Lewin 1",
    "Player_12": "Verbruggen 6",
    "Player_13": "Ndiaye 9",
    "Player_14": "N.Williams 2",
    "Player_15": "White 11"
  },
  {
    "manager_Name": "235021( 60 )",
    "Teams": "Sweet Chin Music( Nishant Lohagun )",
    "SXL": "IN",
    "Latp": "60\nTotal Points",
    "Player_1": "Kinsky 2",
    "Player_2": "Maguire 1",
    "Player_3": "White 11",
    "Player_4": "Calafiori 9",
    "Player_5": "Mbeumo 2",
    "Player_6": "B.Fernandes 2",
    "Player_7": "Tzolis 6",
    "Player_8": "Szoboszlai 8",
    "Player_9": "Brobbey 2",
    "Player_10": "Haaland 2",
    "Player_11": "Calvert-Lewin 1",
    "Player_12": "Verbruggen 6",
    "Player_13": "Groß 2",
    "Player_14": "Hume 2",
    "Player_15": "Diop 2"
  },
  {
    "manager_Name": "412959( 56 )",
    "Teams": "error404( Duri Tadu )",
    "SXL": "IN",
    "Latp": "56\nTotal Points",
    "Player_1": "Verbruggen 6",
    "Player_2": "Shaw 1",
    "Player_3": "Calafiori 9",
    "Player_4": "Rodon 6",
    "Player_5": "Mbeumo 2",
    "Player_6": "Szoboszlai 8",
    "Player_7": "B.Fernandes 2",
    "Player_8": "Ndiaye 9",
    "Player_9": "Calvert-Lewin 1",
    "Player_10": "Haaland 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Kinsky 2",
    "Player_13": "Groß 2",
    "Player_14": "Ballard 0",
    "Player_15": "O'Shea 4"
  },
  {
    "manager_Name": "472566( 55 )",
    "Teams": "Iraolaball LFC( Lobsang Tshering Bhutia )",
    "SXL": "IN",
    "Latp": "55\nTotal Points",
    "Player_1": "Verbruggen 6",
    "Player_2": "Maguire 1",
    "Player_3": "Ajer 8",
    "Player_4": "Calafiori 9",
    "Player_5": "Mbeumo 2",
    "Player_6": "Szoboszlai 8",
    "Player_7": "B.Fernandes 2",
    "Player_8": "E.Le Fée 2",
    "Player_9": "Calvert-Lewin 1",
    "Player_10": "Haaland 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Kinsky 2",
    "Player_13": "Davis 2",
    "Player_14": "Hume 2",
    "Player_15": "Gomez 6"
  },
  {
    "manager_Name": "472566( 55 )",
    "Teams": "PINE( SATYAM RAI )",
    "SXL": "IN",
    "Latp": "55\nTotal Points",
    "Player_1": "Verbruggen 6",
    "Player_2": "Calafiori 9",
    "Player_3": "Maguire 1",
    "Player_4": "Ballard 0",
    "Player_5": "N.Williams 2",
    "Player_6": "Szoboszlai 8",
    "Player_7": "B.Fernandes 2",
    "Player_8": "Semenyo 2",
    "Player_9": "Mbeumo 2",
    "Player_10": "Tzolis 6",
    "Player_11": "Isak 2",
    "Player_12": "Roefs 1",
    "Player_13": "João Pedro 0",
    "Player_14": "White 11",
    "Player_15": "Calvert-Lewin 1"
  },
  {
    "manager_Name": "707347( 52 )",
    "Teams": "Fußballmannschaft( Gaurav Shrestha )",
    "SXL": "IN",
    "Latp": "52\nTotal Points",
    "Player_1": "Kinsky 2",
    "Player_2": "N.Williams 2",
    "Player_3": "Maguire 1",
    "Player_4": "Calafiori 9",
    "Player_5": "Tzolis 6",
    "Player_6": "B.Fernandes 2",
    "Player_7": "Szoboszlai 8",
    "Player_8": "Mbeumo 2",
    "Player_9": "Haaland 2",
    "Player_10": "João Pedro 0",
    "Player_11": "Calvert-Lewin 1",
    "Player_12": "Verbruggen 6",
    "Player_13": "Gomez 6",
    "Player_14": "Diop 2",
    "Player_15": "O'Nien 1"
  },
  {
    "manager_Name": "804585( 51 )",
    "Teams": "Sesk on the Beach( Bejoy M Shrestha )",
    "SXL": "IN",
    "Latp": "51\nTotal Points",
    "Player_1": "Verbruggen 6",
    "Player_2": "Calafiori 9",
    "Player_3": "Shaw 1",
    "Player_4": "Gabriel 5",
    "Player_5": "Mbeumo 2",
    "Player_6": "E.Le Fée 2",
    "Player_7": "Szoboszlai 8",
    "Player_8": "B.Fernandes 2",
    "Player_9": "Semenyo 2",
    "Player_10": "Isak 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Kinsky 2",
    "Player_13": "Hume 2",
    "Player_14": "Calvert-Lewin 1",
    "Player_15": "Aina 5"
  },
  {
    "manager_Name": "1036979( 49 )",
    "Teams": "MANCHESTER IS BLUE( PRAYAS BAJGAI )",
    "SXL": "IN",
    "Latp": "49\nTotal Points",
    "Player_1": "Verbruggen 6",
    "Player_2": "Calafiori 9",
    "Player_3": "Maguire 1",
    "Player_4": "Palestra 0",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Tzolis 6",
    "Player_7": "E.Le Fée 2",
    "Player_8": "Mbeumo 2",
    "Player_9": "Calvert-Lewin 1",
    "Player_10": "Isak 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Raya 6",
    "Player_13": "O'Reilly 2",
    "Player_14": "Ballard 0",
    "Player_15": "Szoboszlai 8"
  },
  {
    "manager_Name": "1181641( 48 )",
    "Teams": "diNgolo Kante( Sibin - )",
    "SXL": "IN",
    "Latp": "48\nTotal Points",
    "Player_1": "Raya 6",
    "Player_2": "Maguire 1",
    "Player_3": "Dalot 1",
    "Player_4": "Gvardiol 9",
    "Player_5": "Cunha 2",
    "Player_6": "Cherki 8",
    "Player_7": "Szoboszlai 8",
    "Player_8": "Rice 3",
    "Player_9": "Tzolis 6",
    "Player_10": "Gonzalo 0",
    "Player_11": "Haaland 2",
    "Player_12": "Forster 0",
    "Player_13": "Pedro Porro 0",
    "Player_14": "Mukiele 0",
    "Player_15": "Scarlett 0"
  },
  {
    "manager_Name": "1181641( 48 )",
    "Teams": "Fc khukuri( Suchan Tamang )",
    "SXL": "NP",
    "Latp": "48\nTotal Points",
    "Player_1": "Petrović 2",
    "Player_2": "Gabriel 5",
    "Player_3": "Pau 0",
    "Player_4": "Targett 1",
    "Player_5": "Szoboszlai 8",
    "Player_6": "Enzo 0",
    "Player_7": "Gibbs-White 2",
    "Player_8": "Cherki 8",
    "Player_9": "Havertz 6",
    "Player_10": "Isak 2",
    "Player_11": "Haaland 2",
    "Player_12": "Forster 0",
    "Player_13": "Mendy 15",
    "Player_14": "Ouattara 1",
    "Player_15": "Barco 0"
  },
  {
    "manager_Name": "1339326( 47 )",
    "Teams": "11 n over( Ashish Rai )",
    "SXL": "IN",
    "Latp": "47\nTotal Points",
    "Player_1": "Roefs 1",
    "Player_2": "Calafiori 9",
    "Player_3": "Robertson 3",
    "Player_4": "James 0",
    "Player_5": "O'Reilly 2",
    "Player_6": "Dewsbury-Hall 11",
    "Player_7": "Wirtz 2",
    "Player_8": "O.Dango 3",
    "Player_9": "Mbeumo 2",
    "Player_10": "Haaland 2",
    "Player_11": "Brobbey 2",
    "Player_12": "Kinsky 2",
    "Player_13": "F.Kadıoğlu 0",
    "Player_14": "Tzolis 6",
    "Player_15": "João Pedro 0"
  },
  {
    "manager_Name": "1519558( 46 )",
    "Teams": "Don't Salah me again( Andy Gazmer )",
    "SXL": "IN",
    "Latp": "46\nTotal Points",
    "Player_1": "Raya 6",
    "Player_2": "Calafiori 9",
    "Player_3": "Shaw 1",
    "Player_4": "Maguire 1",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Ødegaard 11",
    "Player_7": "E.Le Fée 2",
    "Player_8": "Szoboszlai 8",
    "Player_9": "João Pedro 0",
    "Player_10": "Richarlison 2",
    "Player_11": "Haaland 2",
    "Player_12": "Kinsky 2",
    "Player_13": "Schade 3",
    "Player_14": "Thomas 3",
    "Player_15": "van Ewijk 1"
  },
  {
    "manager_Name": "1711462( 45 )",
    "Teams": "Genjii United( Pema Bhutia )",
    "SXL": "IN",
    "Latp": "45\nTotal Points",
    "Player_1": "Verbruggen 6",
    "Player_2": "Gabriel 5",
    "Player_3": "Maguire 1",
    "Player_4": "Calafiori 9",
    "Player_5": "Semenyo 2",
    "Player_6": "B.Fernandes 2",
    "Player_7": "Mbeumo 2",
    "Player_8": "Tzolis 6",
    "Player_9": "Szoboszlai 8",
    "Player_10": "João Pedro 0",
    "Player_11": "Isak 2",
    "Player_12": "Kinsky 2",
    "Player_13": "Calvert-Lewin 1",
    "Player_14": "O'Shea 4",
    "Player_15": "van Ewijk 1"
  },
  {
    "manager_Name": "1711462( 45 )",
    "Teams": "cavac215( Ankit Chhetri )",
    "SXL": "IN",
    "Latp": "45\nTotal Points",
    "Player_1": "Raya 6",
    "Player_2": "Calafiori 9",
    "Player_3": "Shaw 1",
    "Player_4": "Gvardiol 9",
    "Player_5": "O'Shea 4",
    "Player_6": "B.Fernandes 2",
    "Player_7": "Tzolis 6",
    "Player_8": "Semenyo 2",
    "Player_9": "Wirtz 2",
    "Player_10": "Haaland 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Palmer 0",
    "Player_13": "Reed 0",
    "Player_14": "Kusi-Asare 0",
    "Player_15": "van Ewijk 1"
  },
  {
    "manager_Name": "1926931( 44 )",
    "Teams": "JETMCC( CHEWANG SHERPA )",
    "SXL": "IN",
    "Latp": "44\nTotal Points",
    "Player_1": "Lammens 1",
    "Player_2": "Shaw 1",
    "Player_3": "Mosquera 6",
    "Player_4": "Ballard 0",
    "Player_5": "Frimpong 0",
    "Player_6": "B.Fernandes 2",
    "Player_7": "Xhaka 9",
    "Player_8": "Szoboszlai 8",
    "Player_9": "Haaland 2",
    "Player_10": "Richarlison 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Kinsky 2",
    "Player_13": "Anderson 2",
    "Player_14": "Muharemović 6",
    "Player_15": "Rudoni 1"
  },
  {
    "manager_Name": "1926931( 44 )",
    "Teams": "#ThankYouMessi( AVIJIT DAS )",
    "SXL": "IN",
    "Latp": "44\nTotal Points",
    "Player_1": "Raya 6",
    "Player_2": "Gvardiol 9",
    "Player_3": "Calafiori 9",
    "Player_4": "Shaw 1",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Szoboszlai 8",
    "Player_7": "Mbeumo 2",
    "Player_8": "Groß 2",
    "Player_9": "João Pedro 0",
    "Player_10": "Haaland 2",
    "Player_11": "Calvert-Lewin 1",
    "Player_12": "Dubravka 0",
    "Player_13": "Hume 2",
    "Player_14": "Slater 6",
    "Player_15": "Thomas 3"
  },
  {
    "manager_Name": "1926931( 44 )",
    "Teams": "Gustavous Gooner 45( Ashish Subba )",
    "SXL": "IN",
    "Latp": "44\nTotal Points",
    "Player_1": "Lammens 1",
    "Player_2": "O'Reilly 2",
    "Player_3": "Calafiori 9",
    "Player_4": "Kerkez 0",
    "Player_5": "Tzolis 6",
    "Player_6": "Szoboszlai 8",
    "Player_7": "Ndiaye 9",
    "Player_8": "B.Fernandes 2",
    "Player_9": "E.Le Fée 2",
    "Player_10": "Calvert-Lewin 1",
    "Player_11": "Haaland 2",
    "Player_12": "Woodman 0",
    "Player_13": "Brobbey 2",
    "Player_14": "Konsa 0",
    "Player_15": "van Ewijk 1"
  },
  {
    "manager_Name": "2163514( 43 )",
    "Teams": "RipDiogo_20( pranam rai )",
    "SXL": "IN",
    "Latp": "43\nTotal Points",
    "Player_1": "Lammens 1",
    "Player_2": "Jacquet 1",
    "Player_3": "N.Williams 2",
    "Player_4": "Calafiori 9",
    "Player_5": "Senesi 3",
    "Player_6": "B.Fernandes 2",
    "Player_7": "Mbeumo 2",
    "Player_8": "Ødegaard 11",
    "Player_9": "Wirtz 2",
    "Player_10": "Tzolis 6",
    "Player_11": "Isak 2",
    "Player_12": "Sánchez 0",
    "Player_13": "Cash -1",
    "Player_14": "João Pedro 0",
    "Player_15": "Brobbey 2"
  },
  {
    "manager_Name": "2685574( 41 )",
    "Teams": "Kuch_Bhi_X1( Dipen Thapa )",
    "SXL": "IN",
    "Latp": "41\nTotal Points",
    "Player_1": "Martinez 0",
    "Player_2": "Gabriel 5",
    "Player_3": "Shaw 1",
    "Player_4": "Calafiori 9",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Ødegaard 11",
    "Player_7": "Semenyo 2",
    "Player_8": "Rogers 0",
    "Player_9": "Thiago 0",
    "Player_10": "Watkins 0",
    "Player_11": "João Pedro 0",
    "Player_12": "Verbruggen 6",
    "Player_13": "Ndiaye 9",
    "Player_14": "Diop 2",
    "Player_15": "Konsa 0"
  },
  {
    "manager_Name": "2685574( 41 )",
    "Teams": "Subbed at 59( Rishi Thulung )",
    "SXL": "IN",
    "Latp": "41\nTotal Points",
    "Player_1": "Lammens 1",
    "Player_2": "N.Williams 2",
    "Player_3": "Calafiori 9",
    "Player_4": "Gvardiol 9",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Mbeumo 2",
    "Player_7": "Szoboszlai 8",
    "Player_8": "Groß 2",
    "Player_9": "Brobbey 2",
    "Player_10": "Haaland 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Kinsky 2",
    "Player_13": "I.Sangaré 2",
    "Player_14": "O'Shea 4",
    "Player_15": "Thomas 3"
  },
  {
    "manager_Name": "2994009( 40 )",
    "Teams": "COMET FC( Pranesh Sharma )",
    "SXL": "IN",
    "Latp": "40\nTotal Points",
    "Player_1": "Lammens 1",
    "Player_2": "Kerkez 0",
    "Player_3": "Kipré 0",
    "Player_4": "Nedeljkovic 0",
    "Player_5": "Ajayi 14",
    "Player_6": "Saka 9",
    "Player_7": "Semenyo 2",
    "Player_8": "Gibbs-White 2",
    "Player_9": "Szoboszlai 8",
    "Player_10": "Haaland 2",
    "Player_11": "Gyökeres 0",
    "Player_12": "Palmer 0",
    "Player_13": "Giles 6",
    "Player_14": "Mac Allister 1",
    "Player_15": "João Pedro 0"
  },
  {
    "manager_Name": "2994009( 40 )",
    "Teams": "FC Native( Monlom Rongong )",
    "SXL": "IN",
    "Latp": "40\nTotal Points",
    "Player_1": "Kinsky 2",
    "Player_2": "Maguire 1",
    "Player_3": "Calafiori 9",
    "Player_4": "N.Williams 2",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Szoboszlai 8",
    "Player_7": "Mbeumo 2",
    "Player_8": "Ndiaye 9",
    "Player_9": "Calvert-Lewin 1",
    "Player_10": "Haaland 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Verbruggen 6",
    "Player_13": "Groß 2",
    "Player_14": "van Ewijk 1",
    "Player_15": "Diop 2"
  },
  {
    "manager_Name": "3617007( 38 )",
    "Teams": "killerkün16 FC( Neelambar Rai )",
    "SXL": "IN",
    "Latp": "38\nTotal Points",
    "Player_1": "Kinsky 2",
    "Player_2": "Maguire 1",
    "Player_3": "Gvardiol 9",
    "Player_4": "Calafiori 9",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Tzolis 6",
    "Player_7": "Mbeumo 2",
    "Player_8": "Groß 2",
    "Player_9": "João Pedro 0",
    "Player_10": "Haaland 2",
    "Player_11": "Calvert-Lewin 1",
    "Player_12": "Verbruggen 6",
    "Player_13": "Thomas 3",
    "Player_14": "O'Shea 4",
    "Player_15": "E.Le Fée 2"
  },
  {
    "manager_Name": "3944954( 37 )",
    "Teams": "KungFuPandoos( Indrajeet Singh )",
    "SXL": "IN",
    "Latp": "37\nTotal Points",
    "Player_1": "Raya 6",
    "Player_2": "Senesi 3",
    "Player_3": "Virgil 2",
    "Player_4": "Gvardiol 9",
    "Player_5": "Calafiori 9",
    "Player_6": "Mbeumo 2",
    "Player_7": "Palmer 0",
    "Player_8": "Rogers 0",
    "Player_9": "Cunha 2",
    "Player_10": "Semenyo 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Dubravka 0",
    "Player_13": "Shaw 1",
    "Player_14": "Calvert-Lewin 1",
    "Player_15": "Mateta 2"
  },
  {
    "manager_Name": "3944954( 37 )",
    "Teams": "Gunners are Back( Bishal Rai )",
    "SXL": "IN",
    "Latp": "37\nTotal Points",
    "Player_1": "Lammens 1",
    "Player_2": "Gabriel 5",
    "Player_3": "Calafiori 9",
    "Player_4": "Frimpong 0",
    "Player_5": "Szoboszlai 8",
    "Player_6": "B.Fernandes 2",
    "Player_7": "Tzolis 6",
    "Player_8": "Semenyo 2",
    "Player_9": "Mbeumo 2",
    "Player_10": "João Pedro 0",
    "Player_11": "Thiago 0",
    "Player_12": "Verbruggen 6",
    "Player_13": "Hume 2",
    "Player_14": "Mitchell 1",
    "Player_15": "Walle Egeli 1"
  },
  {
    "manager_Name": "3944954( 37 )",
    "Teams": "Blue Brigade( Bhuman Basnet )",
    "SXL": "IN",
    "Latp": "37\nTotal Points",
    "Player_1": "Verbruggen 6",
    "Player_2": "Calafiori 9",
    "Player_3": "Shaw 1",
    "Player_4": "Muharemović 6",
    "Player_5": "Tzolis 6",
    "Player_6": "Rogers 0",
    "Player_7": "B.Fernandes 2",
    "Player_8": "Semenyo 2",
    "Player_9": "João Pedro 0",
    "Player_10": "Calvert-Lewin 1",
    "Player_11": "Haaland 2",
    "Player_12": "Kinsky 2",
    "Player_13": "van Ewijk 1",
    "Player_14": "Hughes 0",
    "Player_15": "Diop 2"
  },
  {
    "manager_Name": "4296658( 36 )",
    "Teams": "Afc( Nishant Singh )",
    "SXL": "IN",
    "Latp": "36\nTotal Points",
    "Player_1": "Raya 6",
    "Player_2": "Calafiori 9",
    "Player_3": "Shaw 1",
    "Player_4": "Hume 2",
    "Player_5": "Tzolis 6",
    "Player_6": "Wilson 3",
    "Player_7": "Mbeumo 2",
    "Player_8": "B.Fernandes 2",
    "Player_9": "Calvert-Lewin 1",
    "Player_10": "Haaland 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Verbruggen 6",
    "Player_13": "Rodon 6",
    "Player_14": "Thomas 3",
    "Player_15": "Slater 6"
  },
  {
    "manager_Name": "4296658( 36 )",
    "Teams": "Busby Baby( Regean Lama )",
    "SXL": "IN",
    "Latp": "36\nTotal Points",
    "Player_1": "Verbruggen 6",
    "Player_2": "Mitchell 1",
    "Player_3": "Shaw 1",
    "Player_4": "Calafiori 9",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Szoboszlai 8",
    "Player_7": "Groß 2",
    "Player_8": "Mbeumo 2",
    "Player_9": "Haaland 2",
    "Player_10": "João Pedro 0",
    "Player_11": "Calvert-Lewin 1",
    "Player_12": "Phillips 0",
    "Player_13": "N.Williams 2",
    "Player_14": "Ndiaye 9",
    "Player_15": "van Ewijk 1"
  },
  {
    "manager_Name": "4296658( 36 )",
    "Teams": "OMK( Omkar Subba )",
    "SXL": "IN",
    "Latp": "36\nTotal Points",
    "Player_1": "Raya 6",
    "Player_2": "Guéhi 10",
    "Player_3": "Virgil 2",
    "Player_4": "Gabriel 5",
    "Player_5": "Shaw 1",
    "Player_6": "Mbeumo 2",
    "Player_7": "Rice 3",
    "Player_8": "Semenyo 2",
    "Player_9": "Okafor 1",
    "Player_10": "Watkins 0",
    "Player_11": "Calvert-Lewin 1",
    "Player_12": "Donnarumma 3",
    "Player_13": "Tarkowski 6",
    "Player_14": "Ayari 2",
    "Player_15": "Thiago 0"
  },
  {
    "manager_Name": "4641308( 35 )",
    "Teams": "The Regista( Passang T Sherpa )",
    "SXL": "IN",
    "Latp": "35\nTotal Points",
    "Player_1": "Roefs 1",
    "Player_2": "Palestra 0",
    "Player_3": "Calafiori 9",
    "Player_4": "Shaw 1",
    "Player_5": "Ndiaye 9",
    "Player_6": "Rogers 0",
    "Player_7": "B.Fernandes 2",
    "Player_8": "Szoboszlai 8",
    "Player_9": "Calvert-Lewin 1",
    "Player_10": "Haaland 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Petrović 2",
    "Player_13": "Andrey Santos 2",
    "Player_14": "van Ewijk 1",
    "Player_15": "Thomas 3"
  },
  {
    "manager_Name": "4998362( 34 )",
    "Teams": "OldMonks( Mingma R Sherpa )",
    "SXL": "IN",
    "Latp": "34\nTotal Points",
    "Player_1": "Raya 6",
    "Player_2": "Maguire 1",
    "Player_3": "Calafiori 9",
    "Player_4": "Mitchell 1",
    "Player_5": "Mykolenko 6",
    "Player_6": "B.Fernandes 2",
    "Player_7": "Wirtz 2",
    "Player_8": "Mbeumo 2",
    "Player_9": "Wood 1",
    "Player_10": "Haaland 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Dubravka 0",
    "Player_13": "Hughes 0",
    "Player_14": "O'Shea 4",
    "Player_15": "Groß 2"
  },
  {
    "manager_Name": "6006024( 31 )",
    "Teams": "YNWA2727( Chetan Darnal )",
    "SXL": "IN",
    "Latp": "31\nTotal Points",
    "Player_1": "Kinsky 2",
    "Player_2": "Gabriel 5",
    "Player_3": "Gvardiol 9",
    "Player_4": "Maguire 1",
    "Player_5": "Mbeumo 2",
    "Player_6": "B.Fernandes 2",
    "Player_7": "E.Le Fée 2",
    "Player_8": "Groß 2",
    "Player_9": "João Pedro 0",
    "Player_10": "Haaland 2",
    "Player_11": "Igor Jesus 2",
    "Player_12": "Dubravka 0",
    "Player_13": "Egan 8",
    "Player_14": "Thomas 3",
    "Player_15": "Hughes 0"
  },
  {
    "manager_Name": "6006024( 31 )",
    "Teams": "Rahuland( Rahul Gurung )",
    "SXL": "IN",
    "Latp": "31\nTotal Points",
    "Player_1": "Sánchez 0",
    "Player_2": "Calafiori 9",
    "Player_3": "Shaw 1",
    "Player_4": "White 11",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Palmer 0",
    "Player_7": "Semenyo 2",
    "Player_8": "Mbeumo 2",
    "Player_9": "Wirtz 2",
    "Player_10": "Thiago 0",
    "Player_11": "João Pedro 0",
    "Player_12": "Rushworth 1",
    "Player_13": "Calvert-Lewin 1",
    "Player_14": "Thomas 3",
    "Player_15": "van Ewijk 1"
  },
  {
    "manager_Name": "6006024( 31 )",
    "Teams": "False 9( Rohan Rai )",
    "SXL": "IN",
    "Latp": "31\nTotal Points",
    "Player_1": "Raya 6",
    "Player_2": "Calafiori 9",
    "Player_3": "James 0",
    "Player_4": "Maguire 1",
    "Player_5": "Semenyo 2",
    "Player_6": "B.Fernandes 2",
    "Player_7": "Tzolis 6",
    "Player_8": "Palmer 0",
    "Player_9": "João Pedro 0",
    "Player_10": "Calvert-Lewin 1",
    "Player_11": "Isak 2",
    "Player_12": "Kinsky 2",
    "Player_13": "M.Sangaré 14",
    "Player_14": "van Ewijk 1",
    "Player_15": "Ajer 8"
  },
  {
    "manager_Name": "6332122( 30 )",
    "Teams": "Ashlad FC( Ashim Lama )",
    "SXL": "IN",
    "Latp": "30\nTotal Points",
    "Player_1": "Kinsky 2",
    "Player_2": "Calafiori 9",
    "Player_3": "Maguire 1",
    "Player_4": "Van Hecke 1",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Mbeumo 2",
    "Player_7": "Groß 2",
    "Player_8": "Tzolis 6",
    "Player_9": "Haaland 2",
    "Player_10": "João Pedro 0",
    "Player_11": "Calvert-Lewin 1",
    "Player_12": "Verbruggen 6",
    "Player_13": "Rodon 6",
    "Player_14": "M.Sangaré 14",
    "Player_15": "Thomas 3"
  },
  {
    "manager_Name": "7421863( 26 )",
    "Teams": "FC ASSASSINS( Kushal Sahota )",
    "SXL": "IN",
    "Latp": "26\nTotal Points",
    "Player_1": "Donnarumma 3",
    "Player_2": "Gabriel 5",
    "Player_3": "Dalot 1",
    "Player_4": "Van Hecke 1",
    "Player_5": "Mukiele 0",
    "Player_6": "Yarmoliuk 1",
    "Player_7": "Zubimendi 1",
    "Player_8": "B.Fernandes 2",
    "Player_9": "Anderson 2",
    "Player_10": "Georginio 5",
    "Player_11": "João Pedro 0",
    "Player_12": "Kinsky 2",
    "Player_13": "Diop 2",
    "Player_14": "Gomez 6",
    "Player_15": "Haaland 2"
  }
];
