var s = [
  {
    "manager_Name": "1926931( 44 )",
    "Teams": "Saja Boys( Lorin Minxhozi )",
    "SXL": "EN",
    "Latp": "44\nTotal Points",
    "Player_1": "Verbruggen 6",
    "Player_2": "Maguire 1",
    "Player_3": "Muharemović 6",
    "Player_4": "O'Reilly 2",
    "Player_5": "Schade 3",
    "Player_6": "Mbeumo 2",
    "Player_7": "Rogers 0",
    "Player_8": "Tzolis 6",
    "Player_9": "Haaland 2",
    "Player_10": "João Pedro 0",
    "Player_11": "Thiago 0",
    "Player_12": "Kinsky 2",
    "Player_13": "Szoboszlai 8",
    "Player_14": "Hume 2",
    "Player_15": "Davis 2"
  },
  {
    "manager_Name": "707347( 52 )",
    "Teams": "Back2Back( Sidrit Minxhozi )",
    "SXL": "DK",
    "Latp": "52\nTotal Points",
    "Player_1": "Kelleher 7",
    "Player_2": "Calafiori 9",
    "Player_3": "Shaw 1",
    "Player_4": "O'Reilly 2",
    "Player_5": "Cash -1",
    "Player_6": "B.Fernandes 2",
    "Player_7": "Szoboszlai 8",
    "Player_8": "Mbeumo 2",
    "Player_9": "Gakpo 12",
    "Player_10": "Haaland 2",
    "Player_11": "Havertz 6",
    "Player_12": "Dubravka 0",
    "Player_13": "Kusi-Asare 0",
    "Player_14": "Hughes 0",
    "Player_15": "Thomas 3"
  },
  {
    "manager_Name": "1036979( 49 )",
    "Teams": "Mr.T( Eni Shtini )",
    "SXL": "AL",
    "Latp": "49\nTotal Points",
    "Player_1": "Raya 6",
    "Player_2": "Calafiori 9",
    "Player_3": "N.Williams 2",
    "Player_4": "Gvardiol 9",
    "Player_5": "Gibbs-White 2",
    "Player_6": "Tzolis 6",
    "Player_7": "Ndiaye 9",
    "Player_8": "Mbeumo 2",
    "Player_9": "Thiago 0",
    "Player_10": "Haaland 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Dubravka 0",
    "Player_13": "Groß 2",
    "Player_14": "Jacquet 1",
    "Player_15": "van Ewijk 1"
  },
  {
    "manager_Name": "6006024( 31 )",
    "Teams": "robby_baggio10( Marin Jano )",
    "SXL": "AL",
    "Latp": "31\nTotal Points",
    "Player_1": "Kinsky 2",
    "Player_2": "Calafiori 9",
    "Player_3": "Van Hecke 1",
    "Player_4": "O'Reilly 2",
    "Player_5": "N.Williams 2",
    "Player_6": "Rogers 0",
    "Player_7": "Rice 3",
    "Player_8": "Mbeumo 2",
    "Player_9": "Tzolis 6",
    "Player_10": "Haaland 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Verbruggen 6",
    "Player_13": "Shaw 1",
    "Player_14": "Calvert-Lewin 1",
    "Player_15": "Groß 2"
  },
  {
    "manager_Name": "77834( 66 )",
    "Teams": "Kokeqethurit( Daver Berberi )",
    "SXL": "AL",
    "Latp": "66\nTotal Points",
    "Player_1": "Verbruggen 6",
    "Player_2": "De Cuyper 17",
    "Player_3": "Hume 2",
    "Player_4": "Calafiori 9",
    "Player_5": "Maguire 1",
    "Player_6": "Mbeumo 2",
    "Player_7": "B.Fernandes 2",
    "Player_8": "Ndiaye 9",
    "Player_9": "Haaland 2",
    "Player_10": "João Pedro 0",
    "Player_11": "Calvert-Lewin 1",
    "Player_12": "Kinsky 2",
    "Player_13": "Diop 2",
    "Player_14": "Schade 3",
    "Player_15": "Tzolis 6"
  },
  {
    "manager_Name": "131991( 63 )",
    "Teams": "Lula XI( Aksarlao Lula )",
    "SXL": "AL",
    "Latp": "63\nTotal Points",
    "Player_1": "Kinsky 2",
    "Player_2": "Rodon 6",
    "Player_3": "Calafiori 9",
    "Player_4": "Maguire 1",
    "Player_5": "Szoboszlai 8",
    "Player_6": "Mbeumo 2",
    "Player_7": "B.Fernandes 2",
    "Player_8": "Tzolis 6",
    "Player_9": "Haaland 2",
    "Player_10": "João Pedro 0",
    "Player_11": "Calvert-Lewin 1",
    "Player_12": "Verbruggen 6",
    "Player_13": "Gomez 6",
    "Player_14": "Ajer 8",
    "Player_15": "Diop 2"
  },
  {
    "manager_Name": "5338152( 33 )",
    "Teams": "albi( Bardhyl Minxhozi )",
    "SXL": "AL",
    "Latp": "33\nTotal Points",
    "Player_1": "Donnarumma 3",
    "Player_2": "James 0",
    "Player_3": "White 11",
    "Player_4": "Gvardiol 9",
    "Player_5": "Pedro Porro 0",
    "Player_6": "Palmer 0",
    "Player_7": "Mbeumo 2",
    "Player_8": "Rice 3",
    "Player_9": "Wirtz 2",
    "Player_10": "Thiago 0",
    "Player_11": "João Pedro 0",
    "Player_12": "A.Becker 2",
    "Player_13": "Collins 6",
    "Player_14": "Cherki 8",
    "Player_15": "Emersonn 9"
  },
  {
    "manager_Name": "1519558( 46 )",
    "Teams": "123 prova( Magi Muco )",
    "SXL": "AL",
    "Latp": "46\nTotal Points",
    "Player_1": "Donnarumma 3",
    "Player_2": "Van de Ven 0",
    "Player_3": "De Cuyper 17",
    "Player_4": "Maatsen 0",
    "Player_5": "Gvardiol 9",
    "Player_6": "Elanga 9",
    "Player_7": "Palmer 0",
    "Player_8": "Wirtz 2",
    "Player_9": "João Pedro 0",
    "Player_10": "Haaland 2",
    "Player_11": "Isak 2",
    "Player_12": "Dubravka 0",
    "Player_13": "Vuskovic 6",
    "Player_14": "Maeda 2",
    "Player_15": "Schlager 1"
  },
  {
    "manager_Name": "1181641( 48 )",
    "Teams": "diNgolo Kante( Sibin - )",
    "SXL": "IN",
    "Latp": "48\nTotal Points",
    "Player_1": "Raya 6",
    "Player_2": "Maguire 1",
    "Player_3": "Dalot 1",
    "Player_4": "Gvardiol 9",
    "Player_5": "Cunha 2",
    "Player_6": "Cherki 8",
    "Player_7": "Szoboszlai 8",
    "Player_8": "Rice 3",
    "Player_9": "Tzolis 6",
    "Player_10": "Gonzalo 0",
    "Player_11": "Haaland 2",
    "Player_12": "Forster 0",
    "Player_13": "Pedro Porro 0",
    "Player_14": "Mukiele 0",
    "Player_15": "Scarlett 0"
  },
  {
    "manager_Name": "8014240( 23 )",
    "Teams": "DinamoCity( Ilir Bazaiti )",
    "SXL": "EN",
    "Latp": "23\nTotal Points",
    "Player_1": "Pickford 7",
    "Player_2": "Gabriel 5",
    "Player_3": "Lacroix 0",
    "Player_4": "Tarkowski 6",
    "Player_5": "Senesi 3",
    "Player_6": "Gibbs-White 2",
    "Player_7": "Bruno G. 0",
    "Player_8": "Doku 0",
    "Player_9": "Rogers 0",
    "Player_10": "Watkins 0",
    "Player_11": "Gyökeres 0",
    "Player_12": "Sánchez 0",
    "Player_13": "Yoro 0",
    "Player_14": "Cherki 8",
    "Player_15": "Nketiah 1"
  },
  {
    "manager_Name": "1926931( 44 )",
    "Teams": "Haaland & Shoulders( Nina Konstantinidou )",
    "SXL": "EN",
    "Latp": "44\nTotal Points",
    "Player_1": "Raya 6",
    "Player_2": "Shaw 1",
    "Player_3": "Muharemović 6",
    "Player_4": "Calafiori 9",
    "Player_5": "Mbeumo 2",
    "Player_6": "Tzolis 6",
    "Player_7": "Semenyo 2",
    "Player_8": "Wirtz 2",
    "Player_9": "Haaland 2",
    "Player_10": "Calvert-Lewin 1",
    "Player_11": "João Pedro 0",
    "Player_12": "Dovin 0",
    "Player_13": "Van Hecke 1",
    "Player_14": "Groß 2",
    "Player_15": "O'Shea 4"
  },
  {
    "manager_Name": "4641308( 35 )",
    "Teams": "Curtis Jones( Florian Toslluku )",
    "SXL": "AL",
    "Latp": "35\nTotal Points",
    "Player_1": "Kinsky 2",
    "Player_2": "Gabriel 5",
    "Player_3": "Mosquera 6",
    "Player_4": "Maguire 1",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Mbeumo 2",
    "Player_7": "Tzolis 6",
    "Player_8": "Slater 6",
    "Player_9": "Calvert-Lewin 1",
    "Player_10": "Haaland 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Verbruggen 6",
    "Player_13": "Thomas 3",
    "Player_14": "Shepherd 0",
    "Player_15": "Greaves 2"
  },
  {
    "manager_Name": "4296658( 36 )",
    "Teams": "Monarch United FC( Geri Muho )",
    "SXL": "US",
    "Latp": "36\nTotal Points",
    "Player_1": "Kelleher 7",
    "Player_2": "Senesi 3",
    "Player_3": "Udogie 1",
    "Player_4": "Kipré 0",
    "Player_5": "Mendy 15",
    "Player_6": "Palmer 0",
    "Player_7": "Semenyo 2",
    "Player_8": "Gibbs-White 2",
    "Player_9": "Cunha 2",
    "Player_10": "Haaland 2",
    "Player_11": "Watkins 0",
    "Player_12": "Phillips 0",
    "Player_13": "O'Nien 1",
    "Player_14": "Yirenkyi 1",
    "Player_15": "Solanke 1"
  },
  {
    "manager_Name": "7180584( 27 )",
    "Teams": "Vikings( Ermir K )",
    "SXL": "US",
    "Latp": "27\nTotal Points",
    "Player_1": "Martinez 0",
    "Player_2": "O'Reilly 2",
    "Player_3": "Virgil 2",
    "Player_4": "Gabriel 5",
    "Player_5": "Senesi 3",
    "Player_6": "Mbeumo 2",
    "Player_7": "Rogers 0",
    "Player_8": "Rice 3",
    "Player_9": "Cherki 8",
    "Player_10": "Watkins 0",
    "Player_11": "Nmecha 0",
    "Player_12": "Pickford 7",
    "Player_13": "Yoro 0",
    "Player_14": "Amad 0",
    "Player_15": "Gyökeres 0"
  },
  {
    "manager_Name": "619972( 53 )",
    "Teams": "Real Madrid( Real Madrid )",
    "SXL": "AL",
    "Latp": "53\nTotal Points",
    "Player_1": "Verbruggen 6",
    "Player_2": "Senesi 3",
    "Player_3": "Kerkez 0",
    "Player_4": "N.Williams 2",
    "Player_5": "Robertson 3",
    "Player_6": "Palmer 0",
    "Player_7": "Szoboszlai 8",
    "Player_8": "B.Fernandes 2",
    "Player_9": "João Pedro 0",
    "Player_10": "Brobbey 2",
    "Player_11": "Isak 2",
    "Player_12": "Raya 6",
    "Player_13": "Ayari 2",
    "Player_14": "Calafiori 9",
    "Player_15": "Tzolis 6"
  },
  {
    "manager_Name": "8612869( 18 )",
    "Teams": "my sadik( Denis Brahilika )",
    "SXL": "AL",
    "Latp": "18\nTotal Points",
    "Player_1": "Raya 6",
    "Player_2": "Pedro Porro 0",
    "Player_3": "Shaw 1",
    "Player_4": "F.Kadıoğlu 0",
    "Player_5": "Anderson 2",
    "Player_6": "Rice 3",
    "Player_7": "Mehmeti 0",
    "Player_8": "Palmer 0",
    "Player_9": "Isak 2",
    "Player_10": "João Pedro 0",
    "Player_11": "Haaland 2",
    "Player_12": "Verbruggen 6",
    "Player_13": "Diop 2",
    "Player_14": "Barnes 2",
    "Player_15": "Konsa 0"
  },
  {
    "manager_Name": "2685574( 41 )",
    "Teams": "Tepelena( Joan Hasanmema )",
    "SXL": "AL",
    "Latp": "41\nTotal Points",
    "Player_1": "Kinsky 2",
    "Player_2": "Maguire 1",
    "Player_3": "Gabriel 5",
    "Player_4": "Gvardiol 9",
    "Player_5": "Tzolis 6",
    "Player_6": "B.Fernandes 2",
    "Player_7": "Mbeumo 2",
    "Player_8": "Groß 2",
    "Player_9": "João Pedro 0",
    "Player_10": "Haaland 2",
    "Player_11": "Barry 8",
    "Player_12": "Palmer 0",
    "Player_13": "Slater 6",
    "Player_14": "Targett 1",
    "Player_15": "Thomas 3"
  },
  {
    "manager_Name": "2413330( 42 )",
    "Teams": "Quantitative Eze-ing( Camilla Nurkhanov )",
    "SXL": "EN",
    "Latp": "42\nTotal Points",
    "Player_1": "Lammens 1",
    "Player_2": "Gabriel 5",
    "Player_3": "Diop 2",
    "Player_4": "Guéhi 10",
    "Player_5": "Tarkowski 6",
    "Player_6": "Semenyo 2",
    "Player_7": "Gibbs-White 2",
    "Player_8": "Szoboszlai 8",
    "Player_9": "B.Fernandes 2",
    "Player_10": "Isak 2",
    "Player_11": "João Pedro 0",
    "Player_12": "Kinsky 2",
    "Player_13": "De Cuyper 17",
    "Player_14": "Iwobi 0",
    "Player_15": "Kusi-Asare 0"
  },
  {
    "manager_Name": "8427168( 20 )",
    "Teams": "Mitoma123( Enio Minxhozi )",
    "SXL": "AL",
    "Latp": "20\nTotal Points",
    "Player_1": "A.Becker 2",
    "Player_2": "Pedro Porro 0",
    "Player_3": "Virgil 2",
    "Player_4": "Jacquet 1",
    "Player_5": "Calafiori 9",
    "Player_6": "Palmer 0",
    "Player_7": "Rayan 2",
    "Player_8": "Cunha 2",
    "Player_9": "Gonzalo 0",
    "Player_10": "João Pedro 0",
    "Player_11": "Haaland 2",
    "Player_12": "Dubravka 0",
    "Player_13": "Schade 3",
    "Player_14": "Kamada 3",
    "Player_15": "O.Richards 0"
  },
  {
    "manager_Name": "7838445( 24 )",
    "Teams": "Supercampeones( Ronny Nelkenbaum )",
    "SXL": "FR",
    "Latp": "24\nTotal Points",
    "Player_1": "Kinsky 2",
    "Player_2": "Shaw 1",
    "Player_3": "Diop 2",
    "Player_4": "Konsa 0",
    "Player_5": "Davis 2",
    "Player_6": "Rice 3",
    "Player_7": "Yates 0",
    "Player_8": "Szoboszlai 8",
    "Player_9": "Rogers 0",
    "Player_10": "Haaland 2",
    "Player_11": "Brobbey 2",
    "Player_12": "Dubravka 0",
    "Player_13": "Van Hecke 1",
    "Player_14": "Mbeumo 2",
    "Player_15": "João Pedro 0"
  },
  {
    "manager_Name": "6915910( 28 )",
    "Teams": "RAMA 5( Erald Haxhiu )",
    "SXL": "US",
    "Latp": "28\nTotal Points",
    "Player_1": "Lammens 1",
    "Player_2": "Cash -1",
    "Player_3": "Pedro Porro 0",
    "Player_4": "Gvardiol 9",
    "Player_5": "Szoboszlai 8",
    "Player_6": "Semenyo 2",
    "Player_7": "Wilson 3",
    "Player_8": "Mbeumo 2",
    "Player_9": "Gonzalo 0",
    "Player_10": "João Pedro 0",
    "Player_11": "Haaland 2",
    "Player_12": "Dubravka 0",
    "Player_13": "Frimpong 0",
    "Player_14": "McGinn 1",
    "Player_15": "James 0"
  },
  {
    "manager_Name": "1926931( 44 )",
    "Teams": "xhovi fc( Xhovi Ali )",
    "SXL": "EN",
    "Latp": "44\nTotal Points",
    "Player_1": "Raya 6",
    "Player_2": "Gabriel 5",
    "Player_3": "F.Kadıoğlu 0",
    "Player_4": "Tarkowski 6",
    "Player_5": "O'Reilly 2",
    "Player_6": "Wirtz 2",
    "Player_7": "Rice 3",
    "Player_8": "Szoboszlai 8",
    "Player_9": "Mbeumo 2",
    "Player_10": "João Pedro 0",
    "Player_11": "Isak 2",
    "Player_12": "Verbruggen 6",
    "Player_13": "Senesi 3",
    "Player_14": "Fernandes 1",
    "Player_15": "Brobbey 2"
  }
];
