var s = [
  {
    "manager_Name": "771( 445 ) TotalXfr : 11",
    "Teams": "Don\u0027t panic( Lyle Moseley )",
    "SXL": "ZA",
    "Latp": "91",
    "Player_1": "Ederson M. 1",
    "Player_11": "Cunha 12",
    "Player_10": "Isak 11",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Semenyo 2",
    "Player_14": "Aina 1",
    "Player_7": "M.Salah 28",
    "Player_2": "A\u00EFt-Nouri 6",
    "Player_5": "Palmer 2",
    "Player_6": "B.Fernandes 17",
    "Player_3": "Alexander-Arnold 1",
    "Player_4": "Konat\u00E9 6",
    "Player_8": "Mbeumo 5",
    "Player_9": "Wood 2",
    "Player_15": "Faes 1"
  },
  {
    "manager_Name": "770( 457 ) TotalXfr : 6",
    "Teams": "Okoli Dokely( Ski Karde )",
    "SXL": "S1",
    "Latp": "67",
    "Player_1": "Raya 2",
    "Player_11": "Watkins 2",
    "Player_10": "Wissa 13",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Rogers 1",
    "Player_14": "Milenkovi\u0107 1",
    "Player_7": "Palmer 2",
    "Player_2": "Pedro Porro 4",
    "Player_5": "Johnson 2",
    "Player_6": "M.Salah 28",
    "Player_3": "Robinson 6",
    "Player_4": "Alexander-Arnold 1",
    "Player_8": "Mbeumo 5",
    "Player_9": "Solanke 2",
    "Player_15": "Lewis 0"
  },
  {
    "manager_Name": "770( 460 ) TotalXfr : 8",
    "Teams": "Boltons Boys( Nigel Bolton )",
    "SXL": "WA",
    "Latp": "77",
    "Player_1": "Raya 2",
    "Player_11": "Watkins 2",
    "Player_10": "Solanke 2",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Rogers 1",
    "Player_14": "Dunk 0",
    "Player_7": "B.Fernandes 34",
    "Player_2": "Alexander-Arnold 1",
    "Player_5": "M.Salah 14",
    "Player_6": "Palmer 2",
    "Player_3": "Aina 1",
    "Player_4": "Konsa 1",
    "Player_8": "Mbeumo 5",
    "Player_9": "Wissa 13",
    "Player_15": "Greaves 0"
  },
  {
    "manager_Name": "767( 609 ) TotalXfr : 8",
    "Teams": "JCFC( James Coupland )",
    "SXL": "EN",
    "Latp": "78",
    "Player_1": "Flekken 1",
    "Player_11": "Solanke 2",
    "Player_10": "Wood 2",
    "Player_12": "Verbruggen 3",
    "Player_13": "Gu\u00E9hi 1",
    "Player_14": "Dunk 0",
    "Player_7": "B.Fernandes 34",
    "Player_2": "De Ligt 6",
    "Player_5": "Son 2",
    "Player_6": "M.Salah 14",
    "Player_3": "A\u00EFt-Nouri 6",
    "Player_4": "Pedro Porro 4",
    "Player_8": "Mbeumo 5",
    "Player_9": "Palmer 2",
    "Player_15": "Chiwome 0"
  },
  {
    "manager_Name": "759( 1,319 ) TotalXfr : 9",
    "Teams": "Angen\u00E4mt!( Filip Nilsson )",
    "SXL": "SE",
    "Latp": "71",
    "Player_1": "Fabianski 9",
    "Player_11": "Cunha 12",
    "Player_10": "Solanke 4",
    "Player_12": "Martinez 2",
    "Player_13": "Harwood-Bellis 0",
    "Player_14": "Faes 1",
    "Player_7": "Palmer 2",
    "Player_2": "Pedro Porro 4",
    "Player_5": "Johnson 2",
    "Player_6": "M.Salah 14",
    "Player_3": "Alexander-Arnold 1",
    "Player_4": "Dalot 1",
    "Player_8": "B.Fernandes 17",
    "Player_9": "Mbeumo 5",
    "Player_15": "Chiwome 0"
  },
  {
    "manager_Name": "757( 1,576 ) TotalXfr : 9",
    "Teams": "NR29( Nic Onions )",
    "SXL": "EN",
    "Latp": "72",
    "Player_1": "Fabianski 9",
    "Player_11": "Wissa 13",
    "Player_10": "Watkins 2",
    "Player_12": "Henderson 2",
    "Player_13": "Rogers 1",
    "Player_14": "Digne 2",
    "Player_7": "Saka 2",
    "Player_2": "Alexander-Arnold 1",
    "Player_5": "Palmer 2",
    "Player_6": "M.Salah 28",
    "Player_3": "Robinson 6",
    "Player_4": "Gabriel 2",
    "Player_8": "Mbeumo 5",
    "Player_9": "Strand Larsen 2",
    "Player_15": "Greaves 0"
  },
  {
    "manager_Name": "757( 1,653 ) TotalXfr : 11",
    "Teams": "Green Eggs and Sam( bigSAM \uD83D\uDC9A )",
    "SXL": "IO",
    "Latp": "86",
    "Player_1": "Fabianski 9",
    "Player_11": "Cunha 12",
    "Player_10": "Solanke 2",
    "Player_12": "Flekken 1",
    "Player_13": "Winks 2",
    "Player_14": "Harwood-Bellis 0",
    "Player_7": "Mbeumo 5",
    "Player_2": "Gvardiol 1",
    "Player_5": "Rogers 1",
    "Player_6": "M.Salah 28",
    "Player_3": "A\u00EFt-Nouri 6",
    "Player_4": "Lewis 0",
    "Player_8": "B.Fernandes 17",
    "Player_9": "Haaland 5",
    "Player_15": "Faes 1"
  },
  {
    "manager_Name": "755( 1,840 ) TotalXfr : 8",
    "Teams": "Paqueta Gear FC( Craig Sapsford Solsvik )",
    "SXL": "NO",
    "Latp": "74",
    "Player_1": "Fabianski 9",
    "Player_11": "Cunha 12",
    "Player_10": "Ra\u00FAl 5",
    "Player_12": "Raya 2",
    "Player_13": "Rogers 1",
    "Player_14": "Lewis 0",
    "Player_7": "M.Salah 28",
    "Player_2": "Gvardiol 1",
    "Player_5": "Son 2",
    "Player_6": "Mbeumo 5",
    "Player_3": "A\u00EFt-Nouri 6",
    "Player_4": "Gabriel 2",
    "Player_8": "Palmer 2",
    "Player_9": "Wood 2",
    "Player_15": "Van den Berg 1"
  }
];