var s = [
  {
    "manager_Name": "800( 1 ) TotalXfr : 10",
    "Teams": "BB GW1( Ayoub NACIR \uD83C\uDDF2\uD83C\uDDE6 )",
    "SXL": "MA",
    "Latp": "78",
    "Player_1": "Fabianski\r 8",
    "Player_11": "Solanke\r 2",
    "Player_10": "Cunha\r 12",
    "Player_12": "Henderson\r 2",
    "Player_13": "Rogers\r 1",
    "Player_14": "Van de Ven\r 0",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Aina\r 1",
    "Player_5": "B.Fernandes\r 14",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "A\u00EFt-Nouri\r 6",
    "Player_4": "Gabriel\r CHE (A)",
    "Player_8": "Palmer\r ARS (H)",
    "Player_9": "Wood\r 2",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "799( 2 ) TotalXfr : 8",
    "Teams": "\u0627\u0644\u062E\u0648\u0641 \u0645\u0634 \u0645\u0646 \u0627\u0644\u0644\u064A \u062C\u0627\u064A( Sayed Said )",
    "SXL": "EG",
    "Latp": "76",
    "Player_1": "Fabianski\r 8",
    "Player_11": "Solanke\r 2",
    "Player_10": "Wissa\r 13",
    "Player_12": "Ederson M.\r 1",
    "Player_13": "Winks\r 2",
    "Player_14": "Pau\r 1",
    "Player_7": "M.Salah\r 14",
    "Player_2": "Aina\r 1",
    "Player_5": "Smith Rowe\r 11",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "Konat\u00E9\r 6",
    "Player_4": "Mazraoui\r 6",
    "Player_8": "Saka\r CHE (A)",
    "Player_9": "Haaland\r 10",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "797( 3 ) TotalXfr : 10",
    "Teams": "djilo06( Djalil Laouer \uD83C\uDDE9\uD83C\uDDFF )",
    "SXL": "DZ",
    "Latp": "63",
    "Player_1": "Flekken\r 1",
    "Player_11": "Watkins\r 2",
    "Player_10": "Wood\r 2",
    "Player_12": "Ederson M.\r 1",
    "Player_13": "Aina\r 1",
    "Player_14": "Rogers\r 1",
    "Player_7": "Palmer\r ARS (H)",
    "Player_2": "Pedro Porro\r 4",
    "Player_5": "Johnson\r 2",
    "Player_6": "M.Salah\r 14",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "A\u00EFt-Nouri\r 6",
    "Player_8": "Mbeumo\r 5",
    "Player_9": "Wissa\r 26",
    "Player_15": "Justin\r 1"
  },
  {
    "manager_Name": "797( 3 ) TotalXfr : 10",
    "Teams": "I AM PANDA( Fahad Al kharafi\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC )",
    "SXL": "KW",
    "Latp": "59",
    "Player_1": "Henderson\r 2",
    "Player_11": "Ra\u00FAl\r 5",
    "Player_10": "Haaland\r 5",
    "Player_12": "Fabianski\r 8",
    "Player_13": "Digne\r 2",
    "Player_14": "Winks\r 2",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Keane\r 0",
    "Player_5": "McNeil\r 0",
    "Player_6": "Palmer\r ARS (H)",
    "Player_3": "Aina\r 1",
    "Player_4": "Dalot\r 1",
    "Player_8": "Mbeumo\r 5",
    "Player_9": "Cunha\r 12",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "796( 5 ) TotalXfr : 10",
    "Teams": "Stella Rosa( Kristijan Anicic )",
    "SXL": "BA",
    "Latp": "67",
    "Player_1": "Pickford\r 11",
    "Player_11": "Solanke\r 2",
    "Player_10": "N.Jackson\r ARS (H)",
    "Player_12": "Turner\r 0",
    "Player_13": "Burn\r 1",
    "Player_14": "Faes\r 1",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Robinson\r 6",
    "Player_5": "Mbeumo\r 5",
    "Player_6": "Saka\r CHE (A)",
    "Player_3": "A\u00EFt-Nouri\r 6",
    "Player_4": "Konat\u00E9\r 6",
    "Player_8": "Luis D\u00EDaz\r 3",
    "Player_9": "Palmer\r ARS (H)",
    "Player_15": "Fraser\r 0"
  },
  {
    "manager_Name": "795( 6 ) TotalXfr : 9",
    "Teams": "Dream Team( zeyad alaa )",
    "SXL": "EG",
    "Latp": "71",
    "Player_1": "Pickford\r 11",
    "Player_11": "Solanke\r 2",
    "Player_10": "Wood\r 2",
    "Player_12": "Verbruggen\r 3",
    "Player_13": "Digne\r 2",
    "Player_14": "Rogers\r 1",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Robinson\r 6",
    "Player_5": "Palmer\r ARS (H)",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Foden\r 2",
    "Player_9": "Wissa\r 13",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "793( 7 ) TotalXfr : 11",
    "Teams": "Kobs on the Job( Harry Jones )",
    "SXL": "AU",
    "Latp": "77",
    "Player_1": "Flekken\r 1",
    "Player_11": "Wood\r 2",
    "Player_10": "Wissa\r 13",
    "Player_12": "Hermansen\r 1",
    "Player_13": "Rogers\r 1",
    "Player_14": "Young\r 5",
    "Player_7": "Johnson\r 2",
    "Player_2": "Dalot\r 1",
    "Player_5": "M.Salah\r 28",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "Aina\r 1",
    "Player_4": "Robinson\r 6",
    "Player_8": "Garnacho\r 6",
    "Player_9": "Cunha\r 12",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "792( 8 ) TotalXfr : 7",
    "Teams": "Blueberries( Alex Hirkjolen )",
    "SXL": "NO",
    "Latp": "66",
    "Player_1": "Fabianski\r 8",
    "Player_11": "Cunha\r 12",
    "Player_10": "Wood\r 2",
    "Player_12": "Flekken\r 1",
    "Player_13": "Rogers\r 1",
    "Player_14": "Faes\r 1",
    "Player_7": "Saka\r CHE (A)",
    "Player_2": "Pedro Porro\r 4",
    "Player_5": "Gabriel\r CHE (A)",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "A\u00EFt-Nouri\r 6",
    "Player_8": "M.Salah\r 28",
    "Player_9": "Palmer\r ARS (H)",
    "Player_15": "Chiwome\r 0"
  },
  {
    "manager_Name": "791( 9 ) TotalXfr : 9",
    "Teams": "LIV( Dudu Lio messi )",
    "SXL": "ET",
    "Latp": "61",
    "Player_1": "Kelleher\r 6",
    "Player_11": "Ra\u00FAl\r 5",
    "Player_10": "Cunha\r 12",
    "Player_12": "Areola\r 0",
    "Player_13": "Veltman\r 2",
    "Player_14": "Lewis\r 0",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Gabriel\r CHE (A)",
    "Player_5": "Mbeumo\r 5",
    "Player_6": "Bowen\r 3",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Bednarek\r 1",
    "Player_8": "Saka\r CHE (A)",
    "Player_9": "Palmer\r ARS (H)",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "790( 10 ) TotalXfr : 7",
    "Teams": "HA HA NO SALAH( Joshua Jones )",
    "SXL": "EN",
    "Latp": "54",
    "Player_1": "Henderson\r 2",
    "Player_11": "Strand Larsen\r 2",
    "Player_10": "Haaland\r 5",
    "Player_12": "Muric\r 3",
    "Player_13": "Davis\r 2",
    "Player_14": "Delap\r 8",
    "Player_7": "Johnson\r 2",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "M.Salah\r 28",
    "Player_6": "Semenyo\r 2",
    "Player_3": "Aina\r 1",
    "Player_4": "Pinnock\r 1",
    "Player_8": "Mbeumo\r 5",
    "Player_9": "Palmer\r ARS (H)",
    "Player_15": "Bednarek\r 1"
  },
  {
    "manager_Name": "790( 11 ) TotalXfr : 11",
    "Teams": "\u0644\u064A\u0641\u0631\u0628\u0648\u0644( tawfek tawfek )",
    "SXL": "EG",
    "Latp": "66",
    "Player_1": "Flekken\r 1",
    "Player_11": "N.Jackson\r ARS (H)",
    "Player_10": "Wissa\r 13",
    "Player_12": "Sels\r 2",
    "Player_13": "Okoli\r 0",
    "Player_14": "Greaves\r 0",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Gvardiol\r 1",
    "Player_5": "Smith Rowe\r 11",
    "Player_6": "Saka\r CHE (A)",
    "Player_3": "De Ligt\r 6",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Mbeumo\r 5",
    "Player_9": "Palmer\r ARS (H)",
    "Player_15": "Chiwome\r 0"
  },
  {
    "manager_Name": "787( 12 ) TotalXfr : 6",
    "Teams": "doc MO( Mohamed Amr )",
    "SXL": "EG",
    "Latp": "67",
    "Player_1": "Fabianski\r 8",
    "Player_11": "Haaland\r 10",
    "Player_10": "Wissa\r 13",
    "Player_12": "Verbruggen\r 3",
    "Player_13": "Keane\r 0",
    "Player_14": "Winks\r 2",
    "Player_7": "M.Salah\r 14",
    "Player_2": "Virgil\r 6",
    "Player_5": "Rogers\r 1",
    "Player_6": "Smith Rowe\r 11",
    "Player_3": "Aina\r 1",
    "Player_4": "Gvardiol\r 1",
    "Player_8": "Palmer\r ARS (H)",
    "Player_9": "Solanke\r 2",
    "Player_15": "Nedeljkovic\r 0"
  },
  {
    "manager_Name": "787( 13 ) TotalXfr : 8",
    "Teams": "The Seniors( Radhi Alqaisi )",
    "SXL": "EG",
    "Latp": "83",
    "Player_1": "Sels\r 2",
    "Player_11": "Solanke\r 2",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Flekken\r 1",
    "Player_13": "Keane\r 0",
    "Player_14": "Rogers\r 1",
    "Player_7": "Palmer\r ARS (H)",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "Mbeumo\r 5",
    "Player_6": "B.Fernandes\r 14",
    "Player_3": "Mazraoui\r 6",
    "Player_4": "Konat\u00E9\r 6",
    "Player_8": "M.Salah\r 28",
    "Player_9": "Cunha\r 12",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "787( 14 ) TotalXfr : 9",
    "Teams": "THE BOSS( Mohamed Alhosani\uD83C\uDDE6\uD83C\uDDEA )",
    "SXL": "AE",
    "Latp": "69",
    "Player_1": "Fabianski\r 8",
    "Player_11": "Solanke\r 4",
    "Player_10": "Cunha\r 12",
    "Player_12": "S\u00E1nchez\r ARS (H)",
    "Player_13": "Rogers\r 1",
    "Player_14": "Konsa\r 1",
    "Player_7": "Mbeumo\r 5",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "Palmer\r ARS (H)",
    "Player_6": "Smith Rowe\r 11",
    "Player_3": "Robinson\r 6",
    "Player_4": "Aina\r 1",
    "Player_8": "M.Salah\r 14",
    "Player_9": "Wood\r 2",
    "Player_15": "Johnson\r 1"
  },
  {
    "manager_Name": "786( 15 ) TotalXfr : 7",
    "Teams": "ELGA7DEEN( AhmedAlaa Alaa )",
    "SXL": "EG",
    "Latp": "57",
    "Player_1": "Pickford\r 11",
    "Player_11": "Wood\r 2",
    "Player_10": "Haaland\r 10",
    "Player_12": "Sels\r 2",
    "Player_13": "Robinson\r 6",
    "Player_14": "Van den Berg\r 1",
    "Player_7": "Palmer\r ARS (H)",
    "Player_2": "Mazraoui\r 6",
    "Player_5": "B.Fernandes\r 14",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "Konat\u00E9\r 6",
    "Player_8": "McNeil\r 0",
    "Player_9": "Solanke\r 2",
    "Player_15": "Rogers\r 1"
  },
  {
    "manager_Name": "786( 16 ) TotalXfr : 9",
    "Teams": "Goldenme.( Goldenme\uD83C\uDDF0\uD83C\uDDEA Ng\u0027ang\u0027a )",
    "SXL": "KE",
    "Latp": "48",
    "Player_1": "Raya\r CHE (A)",
    "Player_11": "Solanke\r 2",
    "Player_10": "Wood\r 2",
    "Player_12": "S\u00E1nchez\r ARS (H)",
    "Player_13": "Burn\r 1",
    "Player_14": "Digne\r 2",
    "Player_7": "Johnson\r 2",
    "Player_2": "Virgil\r 6",
    "Player_5": "M.Salah\r 28",
    "Player_6": "Palmer\r ARS (H)",
    "Player_3": "Gabriel\r CHE (A)",
    "Player_4": "Gvardiol\r 1",
    "Player_8": "Mbeumo\r 5",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Kova\u010Di\u0107\r 3"
  },
  {
    "manager_Name": "786( 17 ) TotalXfr : 10",
    "Teams": "\u0643\u0631\u0648\u0628 \u0627\u0644\u0641\u064A\u0633\u0628\u0648\u0643( Fantasy Premier League Iraq 43K )",
    "SXL": "IQ",
    "Latp": "83",
    "Player_1": "Martinez\r 2",
    "Player_11": "Haaland\r 5",
    "Player_10": "Wissa\r 13",
    "Player_12": "Neto\r CHE (A)",
    "Player_13": "Kilman\r 6",
    "Player_14": "Keane\r 0",
    "Player_7": "Johnson\r 2",
    "Player_2": "Konat\u00E9\r 6",
    "Player_5": "Smith Rowe\r 11",
    "Player_6": "M.Salah\r 14",
    "Player_3": "Lewis\r 0",
    "Player_4": "Mazraoui\r 6",
    "Player_8": "Saka\r CHE (A)",
    "Player_9": "Cunha\r 24",
    "Player_15": "Rogers\r 1"
  },
  {
    "manager_Name": "785( 18 ) TotalXfr : 7",
    "Teams": "Bukayo\u0027s Sadza( Brendan Sylvester )",
    "SXL": "NL",
    "Latp": "31",
    "Player_1": "Raya\r CHE (A)",
    "Player_11": "Watkins\r 2",
    "Player_10": "Wood\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Aina\r 1",
    "Player_14": "Greaves\r 0",
    "Player_7": "Mbeumo\r 5",
    "Player_2": "Gvardiol\r 1",
    "Player_5": "Rogers\r 1",
    "Player_6": "M.Salah\r 14",
    "Player_3": "Robinson\r 6",
    "Player_4": "Gabriel\r CHE (A)",
    "Player_8": "Saka\r CHE (A)",
    "Player_9": "Palmer\r ARS (H)",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "785( 19 ) TotalXfr : 8",
    "Teams": "LATAKIA UTD( Mont Latakia )",
    "SXL": "UA",
    "Latp": "65",
    "Player_1": "Raya\r CHE (A)",
    "Player_11": "Cunha\r 12",
    "Player_10": "Wood\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Burn\r 1",
    "Player_14": "Rogers\r 1",
    "Player_7": "Saka\r CHE (A)",
    "Player_2": "Konat\u00E9\r 6",
    "Player_5": "Mbeumo\r 5",
    "Player_6": "Palmer\r ARS (H)",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "A\u00EFt-Nouri\r 6",
    "Player_8": "M.Salah\r 28",
    "Player_9": "Ra\u00FAl\r 5",
    "Player_15": "Konsa\r 1"
  },
  {
    "manager_Name": "785( 20 ) TotalXfr : 9",
    "Teams": "ASG( Auwal SG )",
    "SXL": "NG",
    "Latp": "68",
    "Player_1": "Fabianski\r 8",
    "Player_11": "Haaland\r 10",
    "Player_10": "Watkins\r 2",
    "Player_12": "S\u00E1nchez\r ARS (H)",
    "Player_13": "Rogers\r 1",
    "Player_14": "Faes\r 1",
    "Player_7": "Winks\r 2",
    "Player_2": "Konsa\r 1",
    "Player_5": "B.Fernandes\r 14",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "Pedro Porro\r 4",
    "Player_4": "Konat\u00E9\r 6",
    "Player_8": "M.Salah\r 14",
    "Player_9": "Strand Larsen\r 2",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "785( 20 ) TotalXfr : 9",
    "Teams": "Holy Boehly( james delaney )",
    "SXL": "EN",
    "Latp": "64",
    "Player_1": "Martinez\r 2",
    "Player_11": "Cunha\r 12",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Robinson\r 6",
    "Player_14": "Johnson\r 1",
    "Player_7": "Foden\r 2",
    "Player_2": "Gvardiol\r 1",
    "Player_5": "Palmer\r ARS (H)",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "A\u00EFt-Nouri\r 6",
    "Player_4": "Mazraoui\r 6",
    "Player_8": "M.Salah\r 28",
    "Player_9": "Saka\r CHE (A)",
    "Player_15": "Jebbison\r 0"
  },
  {
    "manager_Name": "785( 20 ) TotalXfr : 9",
    "Teams": "7OoOda( Mahmoud Ibrahim )",
    "SXL": "EG",
    "Latp": "73",
    "Player_1": "S\u00E1nchez\r ARS (H)",
    "Player_11": "N.Jackson\r ARS (H)",
    "Player_10": "Cunha\r 12",
    "Player_12": "Turner\r 0",
    "Player_13": "Vardy\r 0",
    "Player_14": "Lewis\r 0",
    "Player_7": "Palmer\r ARS (H)",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "Foden\r 2",
    "Player_6": "M.Salah\r 28",
    "Player_3": "Robinson\r 6",
    "Player_4": "Keane\r 0",
    "Player_8": "Mbeumo\r 5",
    "Player_9": "B.Fernandes\r 14",
    "Player_15": "Dunk\r 0"
  },
  {
    "manager_Name": "785( 20 ) TotalXfr : 9",
    "Teams": "chin tapak dam dam( Hala Madrid )",
    "SXL": "BD",
    "Latp": "76",
    "Player_1": "Pickford\r 11",
    "Player_11": "Haaland\r 5",
    "Player_10": "Wood\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Rogers\r 1",
    "Player_14": "Faes\r 1",
    "Player_7": "Smith Rowe\r 11",
    "Player_2": "Aina\r 1",
    "Player_5": "Mbeumo\r 5",
    "Player_6": "Palmer\r ARS (H)",
    "Player_3": "Lewis\r 0",
    "Player_4": "Dalot\r 1",
    "Player_8": "M.Salah\r 28",
    "Player_9": "Cunha\r 12",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "785( 24 ) TotalXfr : 11",
    "Teams": "TENOXMENOXROUTE81( Hurtta Saksipotku )",
    "SXL": "FI",
    "Latp": "69",
    "Player_1": "Sels\r 2",
    "Player_11": "Haaland\r 5",
    "Player_10": "Ra\u00FAl\r 5",
    "Player_12": "Fabianski\r 8",
    "Player_13": "Semenyo\r 2",
    "Player_14": "Keane\r 0",
    "Player_7": "Mbeumo\r 5",
    "Player_2": "Digne\r 2",
    "Player_5": "Johnson\r 2",
    "Player_6": "Palmer\r ARS (H)",
    "Player_3": "A\u00EFt-Nouri\r 6",
    "Player_4": "Gvardiol\r 1",
    "Player_8": "M.Salah\r 28",
    "Player_9": "Wissa\r 13",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "784( 25 ) TotalXfr : 8",
    "Teams": "Holy Boehly( Niels Pretorius )",
    "SXL": "NO",
    "Latp": "66",
    "Player_1": "Flekken\r 1",
    "Player_11": "Cunha\r 12",
    "Player_10": "Solanke\r 2",
    "Player_12": "Fabianski\r 8",
    "Player_13": "Mykolenko\r 6",
    "Player_14": "Rogers\r 1",
    "Player_7": "Palmer\r ARS (H)",
    "Player_2": "Aina\r 1",
    "Player_5": "Mbeumo\r 5",
    "Player_6": "McNeil\r 0",
    "Player_3": "Robinson\r 6",
    "Player_4": "A\u00EFt-Nouri\r 6",
    "Player_8": "M.Salah\r 28",
    "Player_9": "Haaland\r 5",
    "Player_15": "Van den Berg\r 1"
  },
  {
    "manager_Name": "784( 25 ) TotalXfr : 8",
    "Teams": "ugly squad( abdullah alanazi )",
    "SXL": "SA",
    "Latp": "80",
    "Player_1": "Pickford\r 11",
    "Player_11": "Wood\r 2",
    "Player_10": "Ra\u00FAl\r 5",
    "Player_12": "Fabianski\r 8",
    "Player_13": "Maddison\r 1",
    "Player_14": "Greaves\r 0",
    "Player_7": "B.Fernandes\r 14",
    "Player_2": "Collins\r 1",
    "Player_5": "Palmer\r ARS (H)",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Milenkovi\u0107\r 1",
    "Player_8": "M.Salah\r 28",
    "Player_9": "Cunha\r 12",
    "Player_15": "Gabriel\r CHE (A)"
  },
  {
    "manager_Name": "784( 25 ) TotalXfr : 8",
    "Teams": "THIS IS ANFIELD\uFFFD\uFFFD\uFFFD( Savvas Fili )",
    "SXL": "CY",
    "Latp": "80",
    "Player_1": "Leno\r 9",
    "Player_11": "Cunha\r 24",
    "Player_10": "Wissa\r 13",
    "Player_12": "Sels\r 2",
    "Player_13": "Garnacho\r 6",
    "Player_14": "Mykolenko\r 6",
    "Player_7": "Mbeumo\r 5",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "M.Salah\r 14",
    "Player_6": "Saka\r CHE (A)",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Robinson\r 6",
    "Player_8": "Palmer\r ARS (H)",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Digne\r 2"
  },
  {
    "manager_Name": "784( 28 ) TotalXfr : 9",
    "Teams": "Pipat FC( Pipat Boss )",
    "SXL": "TH",
    "Latp": "87",
    "Player_1": "Fabianski\r 8",
    "Player_11": "Wood\r 2",
    "Player_10": "Cunha\r 12",
    "Player_12": "Raya\r CHE (A)",
    "Player_13": "Konat\u00E9\r 6",
    "Player_14": "Welbeck\r 2",
    "Player_7": "Mbeumo\r 5",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "Palmer\r ARS (H)",
    "Player_6": "Son\r 2",
    "Player_3": "Mazraoui\r 6",
    "Player_4": "Pedro Porro\r 4",
    "Player_8": "M.Salah\r 28",
    "Player_9": "B.Fernandes\r 14",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "784( 28 ) TotalXfr : 9",
    "Teams": "3ala allah( yassine hilmi )",
    "SXL": "MA",
    "Latp": "93",
    "Player_1": "Onana\r 7",
    "Player_11": "Wood\r 2",
    "Player_10": "Cunha\r 12",
    "Player_12": "Pickford\r 11",
    "Player_13": "Palmer\r ARS (H)",
    "Player_14": "Taylor\r 0",
    "Player_7": "Kulusevski\r 2",
    "Player_2": "Virgil\r 6",
    "Player_5": "M.Salah\r 28",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "Pedro Porro\r 4",
    "Player_4": "Gabriel\r CHE (A)",
    "Player_8": "B.Fernandes\r 14",
    "Player_9": "Wissa\r 13",
    "Player_15": "Johnson\r 1"
  },
  {
    "manager_Name": "784( 28 ) TotalXfr : 9",
    "Teams": "abdo abdo( abdallah ali ali )",
    "SXL": "EG",
    "Latp": "76",
    "Player_1": "Flekken\r 1",
    "Player_11": "Strand Larsen\r 2",
    "Player_10": "Wissa\r 13",
    "Player_12": "Fabianski\r 8",
    "Player_13": "B.Fernandes\r 14",
    "Player_14": "Dalot\r 1",
    "Player_7": "Mbeumo\r 5",
    "Player_2": "Pedro Porro\r 4",
    "Player_5": "M.Salah\r 28",
    "Player_6": "Johnson\r 2",
    "Player_3": "A\u00EFt-Nouri\r 6",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Son\r 2",
    "Player_9": "Cunha\r 12",
    "Player_15": "Robinson\r 6"
  },
  {
    "manager_Name": "784( 31 ) TotalXfr : 10",
    "Teams": "Womp, womp.( Stephen Blakemore )",
    "SXL": "EN",
    "Latp": "91",
    "Player_1": "Fabianski\r 8",
    "Player_11": "Cunha\r 12",
    "Player_10": "Wissa\r 13",
    "Player_12": "Pickford\r 11",
    "Player_13": "Rogers\r 1",
    "Player_14": "Davis\r 1",
    "Player_7": "Mbeumo\r 5",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "Palmer\r ARS (H)",
    "Player_6": "Johnson\r 2",
    "Player_3": "Robinson\r 6",
    "Player_4": "Mykolenko\r 6",
    "Player_8": "M.Salah\r 28",
    "Player_9": "Haaland\r 5",
    "Player_15": "Dunk\r 0"
  },
  {
    "manager_Name": "783( 32 ) TotalXfr : 10",
    "Teams": "Team( Mo Med )",
    "SXL": "DZ",
    "Latp": "90",
    "Player_1": "S\u00E1nchez\r ARS (H)",
    "Player_11": "Cunha\r 12",
    "Player_10": "Haaland\r 5",
    "Player_12": "Steele\r 0",
    "Player_13": "Lewis\r 0",
    "Player_14": "Madueke\r ARS (H)",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Robinson\r 6",
    "Player_5": "Smith Rowe\r 11",
    "Player_6": "Foden\r 2",
    "Player_3": "A\u00EFt-Nouri\r 6",
    "Player_4": "Livramento\r 2",
    "Player_8": "Mbeumo\r 5",
    "Player_9": "Wissa\r 13",
    "Player_15": "Cucurella\r ARS (H)"
  },
  {
    "manager_Name": "783( 33 ) TotalXfr : 11",
    "Teams": "scofild( Marouan ben djeloul )",
    "SXL": "DZ",
    "Latp": "67",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 5",
    "Player_10": "Wood\r 2",
    "Player_12": "Martinez\r 2",
    "Player_13": "Adama\r 1",
    "Player_14": "Lewis\r 0",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Robinson\r 6",
    "Player_5": "Palmer\r ARS (H)",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "Aina\r 1",
    "Player_4": "A\u00EFt-Nouri\r 6",
    "Player_8": "McNeil\r 0",
    "Player_9": "Wissa\r 13",
    "Player_15": "Digne\r 2"
  },
  {
    "manager_Name": "781( 34 ) TotalXfr : 9",
    "Teams": "C@V@LIERS( Nikola Cosovic )",
    "SXL": "ME",
    "Latp": "68",
    "Player_1": "Fabianski\r 8",
    "Player_11": "Solanke\r 2",
    "Player_10": "Haaland\r 10",
    "Player_12": "S\u00E1nchez\r ARS (H)",
    "Player_13": "Faes\r 1",
    "Player_14": "Lankshear\r 0",
    "Player_7": "Mbeumo\r 5",
    "Player_2": "Robinson\r 6",
    "Player_5": "Rogers\r 1",
    "Player_6": "Smith Rowe\r 11",
    "Player_3": "Pedro Porro\r 4",
    "Player_4": "Aina\r 1",
    "Player_8": "M.Salah\r 14",
    "Player_9": "Garnacho\r 6",
    "Player_15": "Digne\r 2"
  },
  {
    "manager_Name": "780( 35 ) TotalXfr : 8",
    "Teams": "Real madrid( Bouakkaz Abdelrahim )",
    "SXL": "DZ",
    "Latp": "73",
    "Player_1": "Leno\r 9",
    "Player_11": "Watkins\r 2",
    "Player_10": "Delap\r 8",
    "Player_12": "Martinez\r 2",
    "Player_13": "Buonanotte\r 1",
    "Player_14": "Hall\r 2",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Mazraoui\r 6",
    "Player_5": "Saka\r CHE (A)",
    "Player_6": "Palmer\r ARS (H)",
    "Player_3": "Robinson\r 6",
    "Player_4": "Gvardiol\r 1",
    "Player_8": "Mbeumo\r 5",
    "Player_9": "Evanilson\r 8",
    "Player_15": "Digne\r 2"
  },
  {
    "manager_Name": "780( 35 ) TotalXfr : 8",
    "Teams": "Mk( Mhamad Kahil )",
    "SXL": "LB",
    "Latp": "70",
    "Player_1": "Pickford\r 11",
    "Player_11": "Cunha\r 24",
    "Player_10": "Haaland\r 5",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Rogers\r 1",
    "Player_14": "Van den Berg\r 1",
    "Player_7": "Palmer\r ARS (H)",
    "Player_2": "Robinson\r 6",
    "Player_5": "Mbeumo\r 5",
    "Player_6": "Semenyo\r 2",
    "Player_3": "Lewis\r 0",
    "Player_4": "Aina\r 1",
    "Player_8": "M.Salah\r 14",
    "Player_9": "Wood\r 2",
    "Player_15": "Konsa\r 1"
  },
  {
    "manager_Name": "780( 37 ) TotalXfr : 9",
    "Teams": "Dexter( miro Belmerabet )",
    "SXL": "DZ",
    "Latp": "57",
    "Player_1": "Pickford\r 11",
    "Player_11": "Haaland\r 5",
    "Player_10": "Strand Larsen\r 2",
    "Player_12": "Fabianski\r 8",
    "Player_13": "Rogers\r 1",
    "Player_14": "Harwood-Bellis\r 0",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Aina\r 1",
    "Player_5": "Palmer\r ARS (H)",
    "Player_6": "Semenyo\r 2",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "Lewis\r 0",
    "Player_8": "Mbeumo\r 5",
    "Player_9": "Wood\r 2",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "780( 37 ) TotalXfr : 9",
    "Teams": "\u0627\u0628\u0648 \u0633\u0646\u062F( Mousa Amer )",
    "SXL": "SA",
    "Latp": "66",
    "Player_1": "Raya\r CHE (A)",
    "Player_11": "Wissa\r 13",
    "Player_10": "Wood\r 2",
    "Player_12": "Zych\r 0",
    "Player_13": "Okoli\r 0",
    "Player_14": "Yarmoliuk\r 1",
    "Player_7": "Jones\r 3",
    "Player_2": "Virgil\r 6",
    "Player_5": "Bowen\r 3",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "Gabriel\r CHE (A)",
    "Player_8": "M.Salah\r 28",
    "Player_9": "Haaland\r 5",
    "Player_15": "Burgess\r 2"
  },
  {
    "manager_Name": "780( 37 ) TotalXfr : 9",
    "Teams": "Marescapetovictory( Simon Baker )",
    "SXL": "EN",
    "Latp": "59",
    "Player_1": "Pickford\r 11",
    "Player_11": "Vardy\r 0",
    "Player_10": "Wood\r 2",
    "Player_12": "J.Virginia\r 0",
    "Player_13": "Harwood-Bellis\r 0",
    "Player_14": "Faes\r 1",
    "Player_7": "Saka\r CHE (A)",
    "Player_2": "Gabriel\r CHE (A)",
    "Player_5": "M.Salah\r 28",
    "Player_6": "Palmer\r ARS (H)",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Gvardiol\r 1",
    "Player_8": "Mbeumo\r 5",
    "Player_9": "Smith Rowe\r 11",
    "Player_15": "Delap\r 8"
  },
  {
    "manager_Name": "780( 40 ) TotalXfr : 10",
    "Teams": "kurdistan \uFFFD( muhamad burhan )",
    "SXL": "IQ",
    "Latp": "79",
    "Player_1": "Pickford\r 11",
    "Player_11": "Solanke\r 2",
    "Player_10": "Watkins\r 2",
    "Player_12": "Ramsdale\r 0",
    "Player_13": "Vardy\r 0",
    "Player_14": "Rogers\r 1",
    "Player_7": "Palmer\r ARS (H)",
    "Player_2": "Konat\u00E9\r 6",
    "Player_5": "A\u00EFt-Nouri\r 6",
    "Player_6": "B.Fernandes\r 14",
    "Player_3": "Pedro Porro\r 4",
    "Player_4": "Collins\r 1",
    "Player_8": "M.Salah\r 28",
    "Player_9": "Mbeumo\r 5",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "780( 41 ) TotalXfr : 12",
    "Teams": "rezeki kita( afiya Hasanah )",
    "SXL": "MY",
    "Latp": "77",
    "Player_1": "Flekken\r 1",
    "Player_11": "Solanke\r 2",
    "Player_10": "Cunha\r 12",
    "Player_12": "Raya\r CHE (A)",
    "Player_13": "Smith Rowe\r 11",
    "Player_14": "Lewis\r 0",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Mazraoui\r 6",
    "Player_5": "Bowen\r 3",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "Konat\u00E9\r 6",
    "Player_8": "Palmer\r ARS (H)",
    "Player_9": "Wissa\r 13",
    "Player_15": "Gabriel\r CHE (A)"
  },
  {
    "manager_Name": "779( 42 ) TotalXfr : 8",
    "Teams": "Jesus\u0027 Disciples( Kristiaan Thomas )",
    "SXL": "EN",
    "Latp": "113",
    "Player_1": "Pickford\r 11",
    "Player_11": "Cunha\r 12",
    "Player_10": "Wissa\r 13",
    "Player_12": "Lumley\r 0",
    "Player_13": "Bowen\r 3",
    "Player_14": "Watkins\r 2",
    "Player_7": "Mbeumo\r 5",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Mykolenko\r 6",
    "Player_6": "M.Salah\r 42",
    "Player_3": "Virgil\r 6",
    "Player_4": "Robinson\r 6",
    "Player_8": "Smith Rowe\r 11",
    "Player_9": "McNeil\r 0",
    "Player_15": "Thomas\r 0"
  },
  {
    "manager_Name": "779( 43 ) TotalXfr : 9",
    "Teams": "BanoTeam( Hussein Noun )",
    "SXL": "LB",
    "Latp": "65",
    "Player_1": "Fabianski\r 8",
    "Player_11": "Isak\r 9",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Martinez\r 2",
    "Player_13": "Welbeck\r 2",
    "Player_14": "Dunk\r 0",
    "Player_7": "Son\r 2",
    "Player_2": "Konat\u00E9\r 6",
    "Player_5": "Bowen\r 3",
    "Player_6": "M.Salah\r 28",
    "Player_3": "Digne\r 2",
    "Player_4": "Keane\r 0",
    "Player_8": "Palmer\r ARS (H)",
    "Player_9": "Mbeumo\r 5",
    "Player_15": "Tuanzebe\r 1"
  },
  {
    "manager_Name": "779( 43 ) TotalXfr : 9",
    "Teams": "fantasy team( Vitsa champion\uD83D\uDE09 hafiydu_ibrohim )",
    "SXL": "UZ",
    "Latp": "77",
    "Player_1": "Sels\r 2",
    "Player_11": "Wissa\r 13",
    "Player_10": "Wood\r 2",
    "Player_12": "Raya\r CHE (A)",
    "Player_13": "Lewis\r 0",
    "Player_14": "McNeil\r 0",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Young\r 5",
    "Player_5": "Luis D\u00EDaz\r 3",
    "Player_6": "Palmer\r ARS (H)",
    "Player_3": "A\u00EFt-Nouri\r 6",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Mbeumo\r 5",
    "Player_9": "Cunha\r 12",
    "Player_15": "Digne\r 2"
  },
  {
    "manager_Name": "779( 43 ) TotalXfr : 9",
    "Teams": "Like_aboss( karim zaki )",
    "SXL": "EG",
    "Latp": "79",
    "Player_1": "Leno\r 9",
    "Player_11": "Wood\r 2",
    "Player_10": "Haaland\r 5",
    "Player_12": "King\r 0",
    "Player_13": "Rogers\r 1",
    "Player_14": "Keane\r 0",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Milenkovi\u0107\r 1",
    "Player_5": "Mbeumo\r 5",
    "Player_6": "Smith Rowe\r 11",
    "Player_3": "Lewis\r 0",
    "Player_4": "A\u00EFt-Nouri\r 6",
    "Player_8": "Saka\r CHE (A)",
    "Player_9": "Cunha\r 12",
    "Player_15": "Justin\r 1"
  },
  {
    "manager_Name": "779( 46 ) TotalXfr : 10",
    "Teams": "DiLman ahmad( Ahmad Sami botani )",
    "SXL": "IQ",
    "Latp": "67",
    "Player_1": "Fabianski\r 8",
    "Player_11": "Wood\r 2",
    "Player_10": "Isak\r 9",
    "Player_12": "Ederson M.\r 1",
    "Player_13": "Iwobi\r 5",
    "Player_14": "Digne\r 2",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Konat\u00E9\r 6",
    "Player_5": "Garnacho\r 6",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "Stephens\r 0",
    "Player_4": "Udogie\r 1",
    "Player_8": "Palmer\r ARS (H)",
    "Player_9": "Solanke\r 2",
    "Player_15": "Tuanzebe\r 1"
  },
  {
    "manager_Name": "779( 47 ) TotalXfr : 11",
    "Teams": "Unknown Winner( Eden Hazaris )",
    "SXL": "MY",
    "Latp": "73",
    "Player_1": "Sels\r 2",
    "Player_11": "Haaland\r 5",
    "Player_10": "Cunha\r 12",
    "Player_12": "Fabianski\r 8",
    "Player_13": "Digne\r 2",
    "Player_14": "Faes\r 1",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Konat\u00E9\r 6",
    "Player_5": "Rogers\r 1",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "A\u00EFt-Nouri\r 6",
    "Player_4": "Robinson\r 6",
    "Player_8": "Johnson\r 2",
    "Player_9": "Palmer\r ARS (H)",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "778( 48 ) TotalXfr : 8",
    "Teams": "Virgil Van Chai( Esa kheratkar )",
    "SXL": "S1",
    "Latp": "46",
    "Player_1": "Flekken\r 1",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Wood\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Andersen\r 7",
    "Player_14": "Brereton D\u00EDaz\r 1",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Gabriel\r CHE (A)",
    "Player_5": "Palmer\r ARS (H)",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "Gvardiol\r 1",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Adama\r 1",
    "Player_9": "Ra\u00FAl\r 5",
    "Player_15": "Mazraoui\r 6"
  },
  {
    "manager_Name": "778( 48 ) TotalXfr : 8",
    "Teams": "\u0E22\u0E2D\u0E14\u0E17\u0E35\u0E21United( Thanan Nuannukun )",
    "SXL": "TH",
    "Latp": "55",
    "Player_1": "Ramsdale\r 0",
    "Player_11": "Wood\r 2",
    "Player_10": "Wissa\r 13",
    "Player_12": "S\u00E1nchez\r ARS (H)",
    "Player_13": "Welbeck\r 2",
    "Player_14": "Harwood-Bellis\r 0",
    "Player_7": "M.Salah\r 28",
    "Player_2": "Mazraoui\r 6",
    "Player_5": "McNeil\r 0",
    "Player_6": "Mbeumo\r 5",
    "Player_3": "Gabriel\r CHE (A)",
    "Player_4": "Gvardiol\r 1",
    "Player_8": "Palmer\r ARS (H)",
    "Player_9": "Saka\r CHE (A)",
    "Player_15": "Cresswell\r 0"
  },
  {
    "manager_Name": "778( 48 ) TotalXfr : 8",
    "Teams": "Khenchela team \uFFFD( souhaib Alg\u00E9rie )",
    "SXL": "DZ",
    "Latp": "67",
    "Player_1": "Sels\r 2",
    "Player_11": "Wissa\r 13",
    "Player_10": "Wood\r 2",
    "Player_12": "Raya\r CHE (A)",
    "Player_13": "Palmer\r ARS (H)",
    "Player_14": "Gabriel\r CHE (A)",
    "Player_7": "Saka\r CHE (A)",
    "Player_2": "Aina\r 1",
    "Player_5": "Mbeumo\r 5",
    "Player_6": "M.Salah\r 28",
    "Player_3": "Robinson\r 6",
    "Player_4": "Konat\u00E9\r 6",
    "Player_8": "Johnson\r 2",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Lewis\r 0"
  }
];