var s = [
   {
      "manager_Name":"Sahil Lampard",
      "Teams":"MarxUnited",
      "Player_1":"Ramsdale WHU (A)",
      "Player_2":"Alexander-Arnold 0",
      "Player_3":"James 1",
      "Player_4":"Cancelo 5",
      "Player_5":"Son 4",
      "Player_6":"Benrahma ARS (H)",
      "Player_7":"Bernardo 1",
      "Player_8":"Salah 2$ captain",
      "Player_9":"Hudson-Odoi 0",
      "Player_10":"Dennis 2",
      "Player_11":"Maupay 0",
      "Player_12":"Sánchez 6",
      "Player_13":"Livramento 0",
      "Player_14":"Archer 0",
      "Player_15":"White WHU (A)",
      "SXL":"15",
      "Bench":"1814",
      "Count  ":"2,591,885"
   },
   {
      "manager_Name":"Saurabh Tamang",
      "Teams":"Lucky FC",
      "Player_1":"Guaita 2",
      "Player_2":"Cancelo 5",
      "Player_3":"Alexander-Arnold 0",
      "Player_4":"Andersen 2",
      "Player_5":"Amartey 1",
      "Player_6":"Salah 1",
      "Player_7":"Son 8$ captain",
      "Player_8":"Gallagher 2",
      "Player_9":"Saka WHU (A)",
      "Player_10":"Cucho 0",
      "Player_11":"Kane 5",
      "Player_12":"Sánchez 6",
      "Player_13":"Douglas Luiz 1",
      "Player_14":"Tsimikas 0",
      "Player_15":"Gelhardt 1",
      "SXL":"26",
      "Bench":"1769",
      "Count  ":"3,090,410"
   },
   {
      "manager_Name":"Pranesh Sharma",
      "Teams":"Immortal FC",
      "Player_1":"Sánchez 6",
      "Player_2":"James 1",
      "Player_3":"Robertson 6",
      "Player_4":"Alexander-Arnold 0",
      "Player_5":"Ramsey 2",
      "Player_6":"Maddison 0",
      "Player_7":"Son 4",
      "Player_8":"Saka WHU (A)",
      "Player_9":"Coutinho 3",
      "Player_10":"Kane 10$ captain",
      "Player_11":"Weghorst 1",
      "Player_12":"Foster 2",
      "Player_13":"Coady 0",
      "Player_14":"White WHU (A)",
      "Player_15":"Young-Coombes MUN (A)",
      "SXL":"33",
      "Bench":"2132",
      "Count  ":"306,447"
   },
   {
      "manager_Name":"Sanjeev Kumar",
      "Teams":"GAROBADHA UNITED",
      "Player_1":"Schmeichel 1",
      "Player_2":"James 1",
      "Player_3":"Alexander-Arnold 0",
      "Player_4":"Cancelo 5",
      "Player_5":"Robertson 6",
      "Player_6":"Saka WHU (A)",
      "Player_7":"Salah 2$ captain",
      "Player_8":"Maddison 0",
      "Player_9":"Havertz 1",
      "Player_10":"Watkins 9",
      "Player_11":"Adams 2",
      "Player_12":"Foster 2",
      "Player_13":"White WHU (A)",
      "Player_14":"Broja 1",
      "Player_15":"Gordon 1",
      "SXL":"27",
      "Bench":"2121",
      "Count  ":"341,878"
   },
   {
      "manager_Name":"Kumar Anku",
      "Teams":"The Borderland Fc",
      "Player_1":"Bachmann 0",
      "Player_2":"Cancelo 5",
      "Player_3":"Taylor 6",
      "Player_4":"Alonso 1",
      "Player_5":"Alexander-Arnold 0",
      "Player_6":"Davies 0",
      "Player_7":"Maddison 0",
      "Player_8":"Salah 1",
      "Player_9":"Saka WHU (A)",
      "Player_10":"Coutinho 6$ captain",
      "Player_11":"Kane 5",
      "Player_12":"Schmeichel 1",
      "Player_13":"Elanga BRE (H)",
      "Player_14":"Wood 1",
      "Player_15":"Rodriguez 0",
      "SXL":"24",
      "Bench":"2068",
      "Count  ":"552,089"
   },
   {
      "manager_Name":"Kushal Sahota",
      "Teams":"FC ASSASSINS",
      "Player_1":"Ramsdale WHU (A)",
      "Player_2":"Dias 12",
      "Player_3":"Reguilón 0",
      "Player_4":"Duffy 0",
      "Player_5":"Jota 5",
      "Player_6":"Bowen ARS (H)",
      "Player_7":"Gallagher 2",
      "Player_8":"Salah 2$ captain",
      "Player_9":"Dennis 2",
      "Player_10":"Antonio ARS (H)",
      "Player_11":"Ronaldo BRE (H)",
      "Player_12":"Steele 0",
      "Player_13":"Tsimikas 0",
      "Player_14":"Allan 0",
      "Player_15":"Livramento 0",
      "SXL":"23",
      "Bench":"1674",
      "Count  ":"4,181,839"
   },
   {
      "manager_Name":"Regean Lama",
      "Teams":"BUSBY BABIES 2",
      "Player_1":"Dubravka 7",
      "Player_2":"White WHU (A)",
      "Player_3":"Veltman 6",
      "Player_4":"Robertson 6",
      "Player_5":"Martinelli WHU (A)",
      "Player_6":"Son 4",
      "Player_7":"Havertz 1",
      "Player_8":"Salah 1",
      "Player_9":"Ramsey 2",
      "Player_10":"Kane 10$ captain",
      "Player_11":"Richarlison 1",
      "Player_12":"Carson 0",
      "Player_13":"Doherty 0",
      "Player_14":"Pinnock MUN (A)",
      "Player_15":"Gelhardt 1",
      "SXL":"0",
      "Bench":"2146",
      "Count  ":"266,345"
   },
   {
      "manager_Name":"pranam rai",
      "Teams":"SYAKREE FC",
      "Player_1":"Lloris 1",
      "Player_2":"Alexander-Arnold 0",
      "Player_3":"Manquillo 0",
      "Player_4":"Matip 6",
      "Player_5":"Salah 2$ captain",
      "Player_6":"Ødegaard WHU (A)",
      "Player_7":"Kulusevski 0",
      "Player_8":"Bernardo 1",
      "Player_9":"Toney MUN (A)",
      "Player_10":"Kane 5",
      "Player_11":"Nketiah WHU (A)",
      "Player_12":"Sánchez 6",
      "Player_13":"Harrison 2",
      "Player_14":"Ajer MUN (A)",
      "Player_15":"Rüdiger 0",
      "SXL":"15",
      "Bench":"1909",
      "Count  ":"1,645,108"
   },
   {
      "manager_Name":"Ashim Lama",
      "Teams":"⚔️FURY⚔️",
      "Player_1":"Ramsdale WHU (A)",
      "Player_2":"Gabriel WHU (A)",
      "Player_3":"Cash 6",
      "Player_4":"Alexander-Arnold 0",
      "Player_5":"Cancelo 5",
      "Player_6":"Kulusevski 0",
      "Player_7":"Maddison 0",
      "Player_8":"Salah 2$ captain",
      "Player_9":"Havertz 1",
      "Player_10":"Dennis 2",
      "Player_11":"Werner 1",
      "Player_12":"Pope 2",
      "Player_13":"Edouard 0",
      "Player_14":"Justin 0",
      "Player_15":"Ramsey 2",
      "SXL":"17",
      "Bench":"1956",
      "Count  ":"1,249,105"
   },
   {
      "manager_Name":"Vivek Pradhan",
      "Teams":"PEPPERBOX83",
      "Player_1":"Sánchez 6",
      "Player_2":"Cancelo 5",
      "Player_3":"Rüdiger 0",
      "Player_4":"van Dijk 6",
      "Player_5":"Gray 2$ captain",
      "Player_6":"Salah 1",
      "Player_7":"Sissoko 2",
      "Player_8":"Son 4",
      "Player_9":"Brownhill 10",
      "Player_10":"Weghorst 1",
      "Player_11":"Dennis 2",
      "Player_12":"Raya MUN (A)",
      "Player_13":"King 0",
      "Player_14":"Alexander-Arnold 0",
      "Player_15":"Mee 0",
      "SXL":"0",
      "Bench":"2018",
      "Count  ":"816,104"
   },
   {
      "manager_Name":"Sibin _",
      "Teams":"F95",
      "Player_1":"Ramsdale WHU (A)",
      "Player_2":"Robertson 6",
      "Player_3":"Dier 1",
      "Player_4":"James 1",
      "Player_5":"White WHU (A)",
      "Player_6":"Ødegaard WHU (A)",
      "Player_7":"Jota 5",
      "Player_8":"Salah 1",
      "Player_9":"Ramsey 2",
      "Player_10":"Broja 1",
      "Player_11":"Ronaldo BRE (H)$ captain",
      "Player_12":"Sá 3",
      "Player_13":"Hwang 1",
      "Player_14":"Dalot BRE (H)",
      "Player_15":"Mount 0",
      "SXL":"17",
      "Bench":"2096",
      "Count  ":"432,412"
   },
   {
      "manager_Name":"Omkar Subba",
      "Teams":"Omk09",
      "Player_1":"Ramsdale WHU (A)",
      "Player_2":"Gabriel WHU (A)",
      "Player_3":"van Dijk 6",
      "Player_4":"Robertson 6",
      "Player_5":"Alonso 1",
      "Player_6":"Son 4",
      "Player_7":"Salah 2$ captain",
      "Player_8":"Saka WHU (A)",
      "Player_9":"Kulusevski 0",
      "Player_10":"Coutinho 3",
      "Player_11":"Dennis 2",
      "Player_12":"Foster 2",
      "Player_13":"Weghorst 1",
      "Player_14":"Toney MUN (A)",
      "Player_15":"Livramento 0",
      "SXL":"24",
      "Bench":"2098",
      "Count  ":"424,742"
   },
   {
      "manager_Name":"Indrajeet Singh",
      "Teams":"Kung Fu Pandoos",
      "Player_1":"de Gea BRE (H)",
      "Player_2":"Matip 6",
      "Player_3":"Schär 2",
      "Player_4":"Laporte 6",
      "Player_5":"Ward-Prowse 5",
      "Player_6":"Fernandes BRE (H)$ captain",
      "Player_7":"Saka WHU (A)",
      "Player_8":"Maddison 0",
      "Player_9":"Watkins 9",
      "Player_10":"Kane 5",
      "Player_11":"Richarlison 1",
      "Player_12":"Foster 2",
      "Player_13":"Tierney WHU (A)",
      "Player_14":"Mee 0",
      "Player_15":"Gilmour 2",
      "SXL":"0",
      "Bench":"1972",
      "Count  ":"1,126,511"
   },
   {
      "manager_Name":"Rishi Thulung",
      "Teams":"PL CG FC",
      "Player_1":"Ederson 6",
      "Player_2":"Cancelo 5",
      "Player_3":"Alonso 1",
      "Player_4":"Robertson 6",
      "Player_5":"Cucurella 6",
      "Player_6":"Jota 5",
      "Player_7":"Son 8$ captain",
      "Player_8":"De Bruyne 0",
      "Player_9":"Mount 0",
      "Player_10":"Nketiah WHU (A)",
      "Player_11":"Werner 1",
      "Player_12":"Foster 2",
      "Player_13":"Brownhill 10",
      "Player_14":"Tsimikas 0",
      "Player_15":"Young-Coombes MUN (A)",
      "SXL":"38",
      "Bench":"2050",
      "Count  ":"639,956"
   },
   {
      "manager_Name":"Dipen Thapa",
      "Teams":"BW4_11",
      "Player_1":"Sá 3",
      "Player_2":"Gabriel WHU (A)",
      "Player_3":"Alexander-Arnold 0",
      "Player_4":"Tomiyasu WHU (A)",
      "Player_5":"Bernardo 1",
      "Player_6":"Jota 10$ captain",
      "Player_7":"Fernandes BRE (H)",
      "Player_8":"Soucek ARS (H)",
      "Player_9":"Dennis 2",
      "Player_10":"Antonio ARS (H)",
      "Player_11":"Watkins 9",
      "Player_12":"Sánchez 6",
      "Player_13":"Livramento 0",
      "Player_14":"Gallagher 2",
      "Player_15":"Dias 12",
      "SXL":"25",
      "Bench":"1802",
      "Count  ":"2,723,414"
   },
   {
      "manager_Name":"Nishant Singh",
      "Teams":"beta",
      "Player_1":"Ramsdale WHU (A)",
      "Player_2":"Alexander-Arnold 0",
      "Player_3":"Cash 6",
      "Player_4":"Cancelo 10$ captain",
      "Player_5":"James 1",
      "Player_6":"Salah 1",
      "Player_7":"Saka WHU (A)",
      "Player_8":"Kulusevski 0",
      "Player_9":"Maddison 0",
      "Player_10":"Mount 0",
      "Player_11":"Maupay 0",
      "Player_12":"Sánchez 6",
      "Player_13":"Weghorst 1",
      "Player_14":"Pukki 2",
      "Player_15":"Tsimikas 0",
      "SXL":"18",
      "Bench":"1973",
      "Count  ":"1,122,823"
   },
   {
      "manager_Name":"Ashish Subba",
      "Teams":"Gustavous Gunner",
      "Player_1":"Foster 2",
      "Player_2":"Alexander-Arnold 0",
      "Player_3":"Dier 1",
      "Player_4":"Cancelo 5",
      "Player_5":"Coutinho 3",
      "Player_6":"Havertz 1",
      "Player_7":"Salah 2$ captain",
      "Player_8":"Saka WHU (A)",
      "Player_9":"Kulusevski 0",
      "Player_10":"Richarlison 1",
      "Player_11":"Nketiah WHU (A)",
      "Player_12":"Schmeichel 1",
      "Player_13":"Tomiyasu WHU (A)",
      "Player_14":"Cash 6",
      "Player_15":"Dennis 2",
      "SXL":"15",
      "Bench":"1991",
      "Count  ":"991,552"
   },
   {
      "manager_Name":"Rohan Rai",
      "Teams":"False 9",
      "Player_1":"Sá 3",
      "Player_2":"Davies 0",
      "Player_3":"Robertson 6",
      "Player_4":"Alonso 1",
      "Player_5":"Maddison 0",
      "Player_6":"Salah 2$ captain",
      "Player_7":"Saka WHU (A)",
      "Player_8":"Mount 0",
      "Player_9":"Coutinho 3",
      "Player_10":"Dennis 2",
      "Player_11":"Kane 5",
      "Player_12":"Ramsdale WHU (A)",
      "Player_13":"Broja 1",
      "Player_14":"White WHU (A)",
      "Player_15":"Kilman 0",
      "SXL":"22",
      "Bench":"2270",
      "Count  ":"45,525"
   },
   {
      "manager_Name":"Raj Kanango",
      "Teams":"Weightloss Coach",
      "Player_1":"Forster 2",
      "Player_2":"Alonso 1",
      "Player_3":"Robertson 6",
      "Player_4":"Laporte 6",
      "Player_5":"Mount 0",
      "Player_6":"Salah 1",
      "Player_7":"Son 4",
      "Player_8":"Saka WHU (A)",
      "Player_9":"De Bruyne 0$ captain",
      "Player_10":"Pukki 2",
      "Player_11":"Nketiah WHU (A)",
      "Player_12":"Raya MUN (A)",
      "Player_13":"Veltman 6",
      "Player_14":"Dobbin 0",
      "Player_15":"Tsimikas 0",
      "SXL":"22",
      "Bench":"2154",
      "Count  ":"244,624"
   },
   {
      "manager_Name":"Gaurav Shrestha",
      "Teams":"Fußball-Mannschaft",
      "Player_1":"Ramsdale WHU (A)",
      "Player_2":"Alexander-Arnold 0",
      "Player_3":"Laporte 6",
      "Player_4":"Alonso 1",
      "Player_5":"Robertson 6",
      "Player_6":"Salah 1",
      "Player_7":"Saka WHU (A)",
      "Player_8":"Kulusevski 0",
      "Player_9":"Havertz 1",
      "Player_10":"Kane 10$ captain",
      "Player_11":"Weghorst 1",
      "Player_12":"Foster 2",
      "Player_13":"Broja 1",
      "Player_14":"Dewsbury-Hall 0",
      "Player_15":"Amartey 1",
      "SXL":"26",
      "Bench":"2288",
      "Count  ":"31,437"
   },
   {
      "manager_Name":"Bishal Rai",
      "Teams":"Gooner for Life 037",
      "Player_1":"Ramsdale WHU (A)",
      "Player_2":"Robertson 6",
      "Player_3":"James 1",
      "Player_4":"Gabriel WHU (A)",
      "Player_5":"Cancelo 5",
      "Player_6":"Cash 6",
      "Player_7":"Coutinho 3",
      "Player_8":"Salah 2$ captain",
      "Player_9":"Saka WHU (A)",
      "Player_10":"Ramsey 2",
      "Player_11":"Kane 5",
      "Player_12":"Foster 2",
      "Player_13":"Kulusevski 0",
      "Player_14":"Broja 1",
      "Player_15":"Cucho 0",
      "SXL":"30",
      "Bench":"2220",
      "Count  ":"106,136"
   },
   {
      "manager_Name":"RAJIYUNG Sun",
      "Teams":"hansing",
      "Player_1":"Raya MUN (A)",
      "Player_2":"White WHU (A)",
      "Player_3":"Cancelo 5",
      "Player_4":"Laporte 6",
      "Player_5":"Alexander-Arnold 0",
      "Player_6":"Bowen ARS (H)",
      "Player_7":"Jota 5",
      "Player_8":"De Bruyne 0$ captain",
      "Player_9":"Son 4",
      "Player_10":"Saka WHU (A)",
      "Player_11":"Toney MUN (A)",
      "Player_12":"Alisson 9",
      "Player_13":"Dennis 2",
      "Player_14":"Shaw BRE (H)",
      "Player_15":"Broja 1",
      "SXL":"20",
      "Bench":"2014",
      "Count  ":"842,140"
   },
   {
      "manager_Name":"Ashish Rai",
      "Teams":"Deadhead",
      "Player_1":"Ramsdale WHU (A)",
      "Player_2":"van Dijk 6",
      "Player_3":"Cash 6",
      "Player_4":"Alonso 1",
      "Player_5":"Zaha 6",
      "Player_6":"Saka WHU (A)",
      "Player_7":"Salah 1",
      "Player_8":"Mount 0",
      "Player_9":"Maddison 0",
      "Player_10":"Dennis 2",
      "Player_11":"Kane 10$ captain",
      "Player_12":"Foster 2",
      "Player_13":"Mitchell 0",
      "Player_14":"Taylor 6",
      "Player_15":"Delap 0",
      "SXL":"32",
      "Bench":"2134",
      "Count  ":"302,057"
   },
   {
      "manager_Name":"prabin kumar",
      "Teams":"Prabin Singh",
      "Player_1":"Mendy 1",
      "Player_2":"Rüdiger 0",
      "Player_3":"Alonso 1",
      "Player_4":"Dias 12",
      "Player_5":"Benrahma ARS (H)",
      "Player_6":"Greenwood BRE (H)",
      "Player_7":"Townsend 0",
      "Player_8":"Son 4",
      "Player_9":"Jiménez 1",
      "Player_10":"Antonio ARS (H)",
      "Player_11":"Aubameyang WHU (A)$ captain",
      "Player_12":"Foster 2",
      "Player_13":"Shaw BRE (H)",
      "Player_14":"Tsimikas 0",
      "Player_15":"Bissouma 11",
      "SXL":"19",
      "Bench":"1339",
      "Count  ":"7,376,070"
   },
   {
      "manager_Name":"Ravish Verma",
      "Teams":"Little Chilli FC",
      "Player_1":"Foster 2",
      "Player_2":"Alexander-Arnold 0",
      "Player_3":"James 1",
      "Player_4":"Cancelo 5",
      "Player_5":"Laporte 6",
      "Player_6":"Sterling 3",
      "Player_7":"Havertz 1",
      "Player_8":"Mount 0",
      "Player_9":"Saka WHU (A)",
      "Player_10":"Salah 2$ captain",
      "Player_11":"Pukki 2",
      "Player_12":"Schmeichel 1",
      "Player_13":"Davies 0",
      "Player_14":"Richardson 0",
      "Player_15":"Dobbin 0",
      "SXL":"22",
      "Bench":"2160",
      "Count  ":"228,065"
   },
   {
      "manager_Name":"Prayash Thapa",
      "Teams":"abcde FC",
      "Player_1":"Pope 2",
      "Player_2":"Alexander-Arnold 0",
      "Player_3":"Alonso 1",
      "Player_4":"Cancelo 5",
      "Player_5":"White WHU (A)",
      "Player_6":"Salah 1",
      "Player_7":"Son 8$ captain",
      "Player_8":"Mount 0",
      "Player_9":"Barnes 0",
      "Player_10":"Broja 1",
      "Player_11":"Weghorst 1",
      "Player_12":"Dubravka 7",
      "Player_13":"Saka WHU (A)",
      "Player_14":"Amartey 1",
      "Player_15":"Wood 1",
      "SXL":"19",
      "Bench":"2273",
      "Count  ":"43,289"
   },
   {
      "manager_Name":"Tenzing Ninjey",
      "Teams":"One Step Beyond 026*",
      "Player_1":"Ramsdale WHU (A)",
      "Player_2":"James 1",
      "Player_3":"Alonso 1",
      "Player_4":"Robertson 6",
      "Player_5":"Kulusevski 0",
      "Player_6":"Saka WHU (A)",
      "Player_7":"Mount 0",
      "Player_8":"Salah 1",
      "Player_9":"Raphinha 2",
      "Player_10":"Kane 10$ captain",
      "Player_11":"Weghorst 1",
      "Player_12":"Dubravka 7",
      "Player_13":"Broja 1",
      "Player_14":"Doherty 0",
      "Player_15":"Ait Nouri 1",
      "SXL":"22",
      "Bench":"2135",
      "Count  ":"299,052"
   },
   {
      "manager_Name":"Harsh Raval",
      "Teams":"Up the Bees",
      "Player_1":"Foster 2",
      "Player_2":"Cancelo 5",
      "Player_3":"Alexander-Arnold 0",
      "Player_4":"Laporte 6",
      "Player_5":"Alonso 1",
      "Player_6":"Cash 6",
      "Player_7":"Mount 0",
      "Player_8":"Bernardo 1",
      "Player_9":"Luis Díaz 3",
      "Player_10":"Salah 2$ captain",
      "Player_11":"Werner 1",
      "Player_12":"Schmeichel 1",
      "Player_13":"Dennis 2",
      "Player_14":"Nketiah WHU (A)",
      "Player_15":"Gordon 1",
      "SXL":"27",
      "Bench":"2224",
      "Count  ":"100,210"
   },
   {
      "manager_Name":"PRAYAS BAJGAI",
      "Teams":"MCFC@1894",
      "Player_1":"Ramsdale WHU (A)",
      "Player_2":"Robertson 6",
      "Player_3":"Cancelo 5",
      "Player_4":"Alexander-Arnold 0",
      "Player_5":"Rüdiger 0",
      "Player_6":"Cash 6",
      "Player_7":"Son 8$ captain",
      "Player_8":"Kulusevski 0",
      "Player_9":"Saka WHU (A)",
      "Player_10":"Salah 1",
      "Player_11":"Weghorst 1",
      "Player_12":"Foster 2",
      "Player_13":"Ramsey 2",
      "Player_14":"Wood 1",
      "Player_15":"Broja 1",
      "SXL":"27",
      "Bench":"2305",
      "Count  ":"21,575"
   },
   {
      "manager_Name":"AVIJIT DAS",
      "Teams":"Roing FC",
      "Player_1":"Pope View player information",
      "Player_2":"Alexander-Arnold 0",
      "Player_3":"Alonso 1",
      "Player_4":"Rüdiger 0",
      "Player_5":"White WHU (A)",
      "Player_6":"Maddison 0",
      "Player_7":"Son 4",
      "Player_8":"Kulusevski 0",
      "Player_9":"Saka WHU (A)",
      "Player_10":"Werner 1",
      "Player_11":"Kane 10$ captain",
      "Player_12":"Foster 2",
      "Player_13":"Broja 1",
      "Player_14":"Schär 2",
      "Player_15":"Raphinha 2",
      "SXL":"18",
      "Bench":"2191",
      "Count  ":"158,400"
   },
   {
      "manager_Name":"Abhijeet Singh",
      "Teams":"WEIGHTLOSS COACH",
      "Player_1":"Ramsdale WHU (A)",
      "Player_2":"Matip 6",
      "Player_3":"Cancelo 5",
      "Player_4":"Thiago Silva 1",
      "Player_5":"Kulusevski 0",
      "Player_6":"Saka WHU (A)",
      "Player_7":"De Bruyne 0",
      "Player_8":"Salah 2$ captain",
      "Player_9":"Mount 0",
      "Player_10":"Weghorst 1",
      "Player_11":"Pukki 2",
      "Player_12":"Forster 2",
      "Player_13":"Wood 1",
      "Player_14":"Amartey 1",
      "Player_15":"Tierney WHU (A)",
      "SXL":"17",
      "Bench":"2213",
      "Count  ":"118,110"
   },
   {
      "manager_Name":"SATYAM RAI",
      "Teams":"PINE",
      "Player_1":"Foster 2",
      "Player_2":"Cancelo 5",
      "Player_3":"Alonso 1",
      "Player_4":"Robertson 6",
      "Player_5":"Laporte 6",
      "Player_6":"Alexander-Arnold 0",
      "Player_7":"Saka WHU (A)",
      "Player_8":"Salah 2$ captain",
      "Player_9":"Coutinho 3",
      "Player_10":"Mount 0",
      "Player_11":"Watkins 9",
      "Player_12":"Schmeichel 1",
      "Player_13":"Nketiah WHU (A)",
      "Player_14":"Pukki 2",
      "Player_15":"Dewsbury-Hall 0",
      "SXL":"34",
      "Bench":"2266",
      "Count  ":"49,347"
   }
]