var s = [{
	"manager_Name": "Nishant Singh",
	"Teams": "beta 11",
	"Player_1": "Martínez 10",
	"Player_2": "Robertson WBA (H)",
	"Player_3": "Cresswell BHA (H)",
	"Player_4": "Zouma 1",
	"Player_5": "Grealish 2",
	"Player_6": "Salah WBA (H)$ captain",
	"Player_7": "Son WOL (A)",
	"Player_8": "Zaha 1",
	"Player_9": "Adams 2",
	"Player_10": "Kane WOL (A)",
	"Player_11": "Calvert-Lewin 1",
	"Player_12": "McCarthy 6",
	"Player_13": "Vestergaard 0",
	"Player_14": "Alzate WHU (A)",
	"Player_15": "Douglas 0",
	"SXL": "17",
	"Bench": "6",
	"Count  ": "2( 1+1 )"
}, {
	"manager_Name": "Rohan Rai",
	"Teams": "FALSE 9",
	"Player_1": "Martínez 10",
	"Player_2": "Coufal BHA (H)",
	"Player_3": "Taylor 1",
	"Player_4": "Justin 1",
	"Player_5": "Fernandes 12",
	"Player_6": "De Bruyne 3",
	"Player_7": "Salah WBA (H)$ captain",
	"Player_8": "Podence TOT (H)",
	"Player_9": "Grealish 2",
	"Player_10": "Calvert-Lewin 1",
	"Player_11": "Bamford 5",
	"Player_12": "Ryan WHU (A)",
	"Player_13": "Marçal TOT (H)",
	"Player_14": "Dunne 0",
	"Player_15": "Davis 0",
	"SXL": "35",
	"Bench": "0",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "Avijit Das",
	"Teams": "WeAreTheArsenal",
	"Player_1": "Martínez 10",
	"Player_2": "Dier WOL (A)",
	"Player_3": "Walker-Peters 8",
	"Player_4": "Cancelo 7",
	"Player_5": "Salah WBA (H)$ captain",
	"Player_6": "Son WOL (A)",
	"Player_7": "Fernandes 12",
	"Player_8": "Grealish 2",
	"Player_9": "Bamford 5",
	"Player_10": "Calvert-Lewin 1",
	"Player_11": "Kane WOL (A)",
	"Player_12": "Steer 0",
	"Player_13": "Ayling 1",
	"Player_14": "Bissouma WHU (A)",
	"Player_15": "Mitchell 0",
	"SXL": "45",
	"Bench": "1",
	"Count  ": "5( 5+0 )"
}, {
	"manager_Name": "Gaurav Shrestha",
	"Teams": "Fußball-Mannschaft",
	"Player_1": "Martínez 10",
	"Player_2": "Zouma 1",
	"Player_3": "Robertson WBA (H)",
	"Player_4": "Dallas 1",
	"Player_5": "Salah WBA (H)$ captain",
	"Player_6": "De Bruyne 3",
	"Player_7": "Fernandes 12",
	"Player_8": "Grealish 2",
	"Player_9": "Calvert-Lewin 1",
	"Player_10": "Bamford 5",
	"Player_11": "Watkins 11",
	"Player_12": "Forster 0",
	"Player_13": "Soucek BHA (H)",
	"Player_14": "Coufal BHA (H)",
	"Player_15": "Mitchell 0",
	"SXL": "46",
	"Bench": "0",
	"Count  ": "4( 4+0 )"
}, {
	"manager_Name": "Dipen Thapa",
	"Teams": "Lokipower Reloaded",
	"Player_1": "Martínez 10",
	"Player_2": "Walker-Peters 8",
	"Player_3": "Mings -2",
	"Player_4": "Taylor 1",
	"Player_5": "Salah WBA (H)$ captain",
	"Player_6": "Fernandes 12",
	"Player_7": "Soucek BHA (H)",
	"Player_8": "Son WOL (A)",
	"Player_9": "Calvert-Lewin 1",
	"Player_10": "Vardy 5",
	"Player_11": "Bamford 5",
	"Player_12": "McCarthy 6",
	"Player_13": "Neto TOT (H)",
	"Player_14": "Gabriel 0",
	"Player_15": "Furlong LIV (A)",
	"SXL": "40",
	"Bench": "6",
	"Count  ": "6( 5+1 )"
}, {
	"manager_Name": "Sibin _",
	"Teams": "FortunaDüsseldorfer",
	"Player_1": "Martínez 10",
	"Player_2": "Alderweireld WOL (A)",
	"Player_3": "Dias 6",
	"Player_4": "Keane 8",
	"Player_5": "Matip WBA (H)",
	"Player_6": "Zaha 1",
	"Player_7": "Son WOL (A)",
	"Player_8": "Grealish 2",
	"Player_9": "Fernandes 12",
	"Player_10": "Bamford 5",
	"Player_11": "Kane WOL (A)$ captain",
	"Player_12": "Guaita 3",
	"Player_13": "Richarlison 0",
	"Player_14": "Mengi 0",
	"Player_15": "Oriol Romeu 0",
	"SXL": "44",
	"Bench": "3",
	"Count  ": "5( 5+0 )"
}, {
	"manager_Name": "Kushal Sahota",
	"Teams": "FC ASSASSINS",
	"Player_1": "Schmeichel 1",
	"Player_2": "Lamptey WHU (A)",
	"Player_3": "Zouma 1",
	"Player_4": "Alioski 1",
	"Player_5": "Ward-Prowse 3",
	"Player_6": "Son WOL (A)",
	"Player_7": "Grealish 2",
	"Player_8": "Salah WBA (H)$ captain",
	"Player_9": "Calvert-Lewin 1",
	"Player_10": "Kane WOL (A)",
	"Player_11": "Werner 1",
	"Player_12": "Ryan WHU (A)",
	"Player_13": "Oriol Romeu 0",
	"Player_14": "Neco Williams WBA (H)",
	"Player_15": "Bernardo WHU (A)",
	"SXL": "10",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "SATYAM RAI",
	"Teams": "PINE",
	"Player_1": "Martínez 10",
	"Player_2": "Cancelo 7",
	"Player_3": "Robertson WBA (H)",
	"Player_4": "Coufal BHA (H)",
	"Player_5": "Fernandes 12",
	"Player_6": "Soucek BHA (H)",
	"Player_7": "Salah WBA (H)$ captain",
	"Player_8": "De Bruyne 3",
	"Player_9": "Neto TOT (H)",
	"Player_10": "Bamford 5",
	"Player_11": "Watkins 11",
	"Player_12": "Peacock-Farrell 0",
	"Player_13": "Wilson 0",
	"Player_14": "Justin 1",
	"Player_15": "Neco Williams WBA (H)",
	"SXL": "48",
	"Bench": "1",
	"Count  ": "5( 5+0 )"
}, {
	"manager_Name": "ashim lama",
	"Teams": "⚔️FURY⚔️",
	"Player_1": "Martínez 10",
	"Player_2": "Walker-Peters 8",
	"Player_3": "Taylor 1",
	"Player_4": "Robertson WBA (H)",
	"Player_5": "Justin 1",
	"Player_6": "De Bruyne 6$ captain",
	"Player_7": "Son WOL (A)",
	"Player_8": "Bowen BHA (H)",
	"Player_9": "Kane WOL (A)",
	"Player_10": "Calvert-Lewin 1",
	"Player_11": "Watkins 11",
	"Player_12": "Martin BHA (H)",
	"Player_13": "Mahrez 0",
	"Player_14": "Podence TOT (H)",
	"Player_15": "Mitchell 0",
	"SXL": "38",
	"Bench": "0",
	"Count  ": "4( 4+0 )"
}, {
	"manager_Name": "Indrajeet Singh",
	"Teams": "Kung fu Pandoos",
	"Player_1": "Meslier 1",
	"Player_2": "Targett 6",
	"Player_3": "Zouma 1",
	"Player_4": "Walker 0",
	"Player_5": "Salah WBA (H)$ captain",
	"Player_6": "Son WOL (A)",
	"Player_7": "Podence TOT (H)",
	"Player_8": "Maddison 4",
	"Player_9": "Vardy 5",
	"Player_10": "Bamford 5",
	"Player_11": "Kane WOL (A)",
	"Player_12": "Henderson 0",
	"Player_13": "Webster WHU (A)",
	"Player_14": "Walker-Peters 8",
	"Player_15": "Reed 3",
	"SXL": "22",
	"Bench": "11",
	"Count  ": "4( 3+1 )"
}, {
	"manager_Name": "Vivek Lama",
	"Teams": "JOJOs LFC",
	"Player_1": "Alisson WBA (H)",
	"Player_2": "Saïss TOT (H)",
	"Player_3": "Alexander-Arnold WBA (H)",
	"Player_4": "Walker-Peters 8",
	"Player_5": "Tielemans 3",
	"Player_6": "Son WOL (A)",
	"Player_7": "Sterling 6",
	"Player_8": "Mané WBA (H)$ captain",
	"Player_9": "Connolly WHU (A)",
	"Player_10": "Adams 2",
	"Player_11": "Bamford 5",
	"Player_12": "Ryan WHU (A)",
	"Player_13": "Saint-Maximin 0",
	"Player_14": "Egan 2",
	"Player_15": "Dunne 0",
	"SXL": "24",
	"Bench": "2",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "Prabin Singh",
	"Teams": "Random XI",
	"Player_1": "Ederson 6",
	"Player_2": "Justin 1",
	"Player_3": "Vestergaard 0",
	"Player_4": "Cancelo 7",
	"Player_5": "Ward-Prowse 3",
	"Player_6": "Son WOL (A)",
	"Player_7": "Mahrez 0$ captain",
	"Player_8": "Grealish 2",
	"Player_9": "Bamford 5",
	"Player_10": "Calvert-Lewin 1",
	"Player_11": "Werner 1",
	"Player_12": "Macey 0",
	"Player_13": "Aubameyang 0",
	"Player_14": "Gabriel 0",
	"Player_15": "Dunne 0",
	"SXL": "26",
	"Bench": "0",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "Kumar Anku",
	"Teams": "Galaxies Stars",
	"Player_1": "Forster 0",
	"Player_2": "Aurier WOL (A)",
	"Player_3": "Cancelo 7",
	"Player_4": "Targett 6",
	"Player_5": "Henderson WBA (H)",
	"Player_6": "Sterling 12$ captain",
	"Player_7": "Son WOL (A)",
	"Player_8": "Mahrez 0",
	"Player_9": "Watkins 11",
	"Player_10": "Firmino WBA (H)",
	"Player_11": "Kane WOL (A)",
	"Player_12": "Mendy 2",
	"Player_13": "Walker-Peters 8",
	"Player_14": "Kilman TOT (H)",
	"Player_15": "Ritchie 1",
	"SXL": "36",
	"Bench": "11",
	"Count  ": "5( 4+1 )"
}, {
	"manager_Name": "Okdenri Longchari",
	"Teams": "Happy Williams",
	"Player_1": "McCarthy 6",
	"Player_2": "Dias 6",
	"Player_3": "Walker-Peters 8",
	"Player_4": "Dier WOL (A)",
	"Player_5": "Salah WBA (H)$ captain",
	"Player_6": "Fernandes 12",
	"Player_7": "Sterling 6",
	"Player_8": "Grealish 2",
	"Player_9": "Soucek BHA (H)",
	"Player_10": "Bamford 5",
	"Player_11": "Calvert-Lewin 1",
	"Player_12": "Martínez 10",
	"Player_13": "Wilson 0",
	"Player_14": "Coufal BHA (H)",
	"Player_15": "Lamptey WHU (A)",
	"SXL": "46",
	"Bench": "10",
	"Count  ": "7( 6+1 )"
}, {
	"manager_Name": "Omkar Subba",
	"Teams": "Omk09",
	"Player_1": "McCarthy 6",
	"Player_2": "James 1",
	"Player_3": "Robertson WBA (H)",
	"Player_4": "Zouma 1",
	"Player_5": "Salah WBA (H)$ captain",
	"Player_6": "Grealish 2",
	"Player_7": "Son WOL (A)",
	"Player_8": "Fernandes 12",
	"Player_9": "Ward-Prowse 3",
	"Player_10": "Bamford 5",
	"Player_11": "Calvert-Lewin 1",
	"Player_12": "Nyland 0",
	"Player_13": "Justin 1",
	"Player_14": "Wilson 0",
	"Player_15": "Kilman TOT (H)",
	"SXL": "31",
	"Bench": "1",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "Abhijeet Singh",
	"Teams": "Impact Creators",
	"Player_1": "McCarthy 6",
	"Player_2": "Vestergaard 0",
	"Player_3": "Cresswell BHA (H)",
	"Player_4": "Zouma 1",
	"Player_5": "Fernandes 12",
	"Player_6": "Grealish 2",
	"Player_7": "Son WOL (A)",
	"Player_8": "Salah WBA (H)$ captain",
	"Player_9": "Kane WOL (A)",
	"Player_10": "Calvert-Lewin 1",
	"Player_11": "Bamford 5",
	"Player_12": "Martin BHA (H)",
	"Player_13": "Riedewald 1",
	"Player_14": "Johnson BHA (H)",
	"Player_15": "Kilman TOT (H)",
	"SXL": "27",
	"Bench": "1",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "Ashish Subba",
	"Teams": "GUSTAVOUS GUNNER",
	"Player_1": "Martínez 10",
	"Player_2": "Justin 1",
	"Player_3": "Cresswell BHA (H)",
	"Player_4": "Vestergaard 0",
	"Player_5": "Klich 1",
	"Player_6": "Grealish 2",
	"Player_7": "Ward-Prowse 3",
	"Player_8": "Mané WBA (H)$ captain",
	"Player_9": "De Bruyne 3",
	"Player_10": "Bamford 5",
	"Player_11": "Kane WOL (A)",
	"Player_12": "Pickford 5",
	"Player_13": "Dallas 1",
	"Player_14": "Chilwell 1",
	"Player_15": "Davis 0",
	"SXL": "25",
	"Bench": "7",
	"Count  ": "3( 2+1 )"
}, {
	"manager_Name": "Nitesh Singh",
	"Teams": "Danapur United",
	"Player_1": "Martínez 10",
	"Player_2": "Justin 1",
	"Player_3": "Chilwell 1",
	"Player_4": "Robertson WBA (H)",
	"Player_5": "Grealish 2",
	"Player_6": "Maddison 4",
	"Player_7": "Son WOL (A)",
	"Player_8": "Fernandes 12",
	"Player_9": "Bamford 10$ captain",
	"Player_10": "Calvert-Lewin 1",
	"Player_11": "Kane WOL (A)",
	"Player_12": "Ryan WHU (A)",
	"Player_13": "Struijk 1",
	"Player_14": "Harper LIV (A)",
	"Player_15": "Buur TOT (H)",
	"SXL": "41",
	"Bench": "1",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "Raj Kanango",
	"Teams": "Dream Killer",
	"Player_1": "Martínez 10",
	"Player_2": "Stones 6",
	"Player_3": "Bednarek 9",
	"Player_4": "Dallas 1",
	"Player_5": "De Bruyne 3",
	"Player_6": "Grealish 2",
	"Player_7": "Salah WBA (H)$ captain",
	"Player_8": "Son WOL (A)",
	"Player_9": "Firmino WBA (H)",
	"Player_10": "Bamford 5",
	"Player_11": "Calvert-Lewin 1",
	"Player_12": "Steer 0",
	"Player_13": "Dier WOL (A)",
	"Player_14": "Burke 1",
	"Player_15": "Neco Williams WBA (H)",
	"SXL": "37",
	"Bench": "1",
	"Count  ": "4( 4+0 )"
}, {
	"manager_Name": "Sahil Lampard",
	"Teams": "Marx 11",
	"Player_1": "Martínez 10",
	"Player_2": "Bertrand 6",
	"Player_3": "Reguilón WOL (A)",
	"Player_4": "Robertson WBA (H)",
	"Player_5": "Grealish 2",
	"Player_6": "Mahrez 0",
	"Player_7": "Son WOL (A)",
	"Player_8": "Fernandes 24$ captain",
	"Player_9": "Klich 1",
	"Player_10": "Calvert-Lewin 1",
	"Player_11": "Kane WOL (A)",
	"Player_12": "Ryan WHU (A)",
	"Player_13": "Justin 1",
	"Player_14": "Delap 0",
	"Player_15": "Casey 0",
	"SXL": "44",
	"Bench": "1",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "Pema Sherpa",
	"Teams": "CottonMouth XI",
	"Player_1": "Martínez 10",
	"Player_2": "Saïss TOT (H)",
	"Player_3": "Castagne 1",
	"Player_4": "Cancelo 7",
	"Player_5": "Son WOL (A)",
	"Player_6": "Pulisic 2",
	"Player_7": "Sigurdsson 11",
	"Player_8": "Salah WBA (H)$ captain",
	"Player_9": "Bamford 5",
	"Player_10": "Kane WOL (A)",
	"Player_11": "Calvert-Lewin 1",
	"Player_12": "Button LIV (A)",
	"Player_13": "Phillips 1",
	"Player_14": "Chilwell 1",
	"Player_15": "Mitchell 0",
	"SXL": "37",
	"Bench": "2",
	"Count  ": "4( 4+0 )"
}, {
	"manager_Name": "pranam rai",
	"Teams": "SYAKREE F.C.",
	"Player_1": "Martínez 10",
	"Player_2": "Kilman TOT (H)",
	"Player_3": "Chilwell 1",
	"Player_4": "Robertson WBA (H)",
	"Player_5": "Fernandes 12",
	"Player_6": "Podence TOT (H)",
	"Player_7": "Grealish 2",
	"Player_8": "Son WOL (A)",
	"Player_9": "Bamford 5",
	"Player_10": "Kane WOL (A)",
	"Player_11": "Calvert-Lewin 2$ captain",
	"Player_12": "Guaita 3",
	"Player_13": "Oriol Romeu 0",
	"Player_14": "James 1",
	"Player_15": "Lamptey WHU (A)",
	"SXL": "32",
	"Bench": "4",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "Regean Lama",
	"Teams": "Busby Baby",
	"Player_1": "McCarthy 6",
	"Player_2": "Dallas 1",
	"Player_3": "Walker-Peters 8",
	"Player_4": "Justin 1",
	"Player_5": "De Bruyne 6$ captain",
	"Player_6": "Son WOL (A)",
	"Player_7": "Grealish 2",
	"Player_8": "Fernandes 12",
	"Player_9": "Podence TOT (H)",
	"Player_10": "Bamford 5",
	"Player_11": "Kane WOL (A)",
	"Player_12": "Steer 0",
	"Player_13": "Taylor 1",
	"Player_14": "Brewster 2",
	"Player_15": "Douglas 0",
	"SXL": "41",
	"Bench": "3",
	"Count  ": "5( 5+0 )"
}, {
	"manager_Name": "Han Sing",
	"Teams": "hansing",
	"Player_1": "McCarthy 6",
	"Player_2": "Coufal BHA (H)",
	"Player_3": "Dias 6",
	"Player_4": "Zouma 1",
	"Player_5": "Grealish 2",
	"Player_6": "Salah WBA (H)$ captain",
	"Player_7": "Fernandes 12",
	"Player_8": "Son WOL (A)",
	"Player_9": "Calvert-Lewin 1",
	"Player_10": "Bamford 5",
	"Player_11": "Kane WOL (A)",
	"Player_12": "Nyland 0",
	"Player_13": "Vestergaard 0",
	"Player_14": "Soucek BHA (H)",
	"Player_15": "Lowton 1",
	"SXL": "33",
	"Bench": "1",
	"Count  ": "4( 4+0 )"
}, {
	"manager_Name": "Sanjeev Kumar",
	"Teams": "mendal11",
	"Player_1": "Mendy 2",
	"Player_2": "Vestergaard 0",
	"Player_3": "James 1",
	"Player_4": "Coufal BHA (H)",
	"Player_5": "Zaha 1",
	"Player_6": "Ward-Prowse 3",
	"Player_7": "Son WOL (A)",
	"Player_8": "Salah WBA (H)$ captain",
	"Player_9": "Bamford 5",
	"Player_10": "Kane WOL (A)",
	"Player_11": "Adams 2",
	"Player_12": "Steer 0",
	"Player_13": "Grealish 2",
	"Player_14": "Targett 6",
	"Player_15": "Justin 1",
	"SXL": "14",
	"Bench": "9",
	"Count  ": "2( 1+1 )"
}, {
	"manager_Name": "Ashish Rai",
	"Teams": "goooooooners",
	"Player_1": "Leno 8",
	"Player_2": "Cresswell BHA (H)",
	"Player_3": "Dallas 1",
	"Player_4": "Bertrand 6",
	"Player_5": "Mahrez 0",
	"Player_6": "Grealish 2",
	"Player_7": "Sterling 12$ captain",
	"Player_8": "Salah WBA (H)",
	"Player_9": "Watkins 11",
	"Player_10": "Bamford 5",
	"Player_11": "Vardy 5",
	"Player_12": "Nyland 0",
	"Player_13": "Oriol Romeu 0",
	"Player_14": "Lascelles 0",
	"Player_15": "Branthwaite 0",
	"SXL": "50",
	"Bench": "0",
	"Count  ": "6( 6+0 )"
}, {
	"manager_Name": "Ravish Verma",
	"Teams": "Jatt Da Muqaabla FC",
	"Player_1": "Sánchez WHU (A)",
	"Player_2": "Walker-Peters 8",
	"Player_3": "Targett 6",
	"Player_4": "Dallas 1",
	"Player_5": "Fernandes 12",
	"Player_6": "Grealish 2",
	"Player_7": "De Bruyne 3",
	"Player_8": "Salah WBA (H)$ captain",
	"Player_9": "Adams 2",
	"Player_10": "Bamford 5",
	"Player_11": "Kane WOL (A)",
	"Player_12": "Button LIV (A)",
	"Player_13": "Neco Williams WBA (H)",
	"Player_14": "Bellerín 2",
	"Player_15": "Burke 1",
	"SXL": "39",
	"Bench": "3",
	"Count  ": "4( 4+0 )"
}, {
	"manager_Name": "Bishal Rai",
	"Teams": "Gooner for Life",
	"Player_1": "Martínez 10",
	"Player_2": "Justin 1",
	"Player_3": "Robertson WBA (H)",
	"Player_4": "Targett 6",
	"Player_5": "Raphinha 1",
	"Player_6": "Fernandes 12",
	"Player_7": "Son WOL (A)",
	"Player_8": "Salah WBA (H)$ captain",
	"Player_9": "Grealish 2",
	"Player_10": "Bamford 5",
	"Player_11": "Calvert-Lewin 1",
	"Player_12": "Ryan WHU (A)",
	"Player_13": "Wilson 0",
	"Player_14": "Chilwell 1",
	"Player_15": "Branthwaite 0",
	"SXL": "38",
	"Bench": "1",
	"Count  ": "4( 4+0 )"
}]