var s = [
  {
    "manager_Name": "1,321( 63,541 )",
    "Teams": "YoureAToneyNoMore( Brendan Kehoe )",
    "SXL": "ENG",
    "Latp": "35",
    "Player_1": "A.Becker 2",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 2",
    "Player_12": "Petrovi\u0107 2",
    "Player_13": "Garner 4",
    "Player_14": "O\u0027Brien 9",
    "Player_7": "Foden 1",
    "Player_2": "Thiaw 9",
    "Player_5": "Wilson 2",
    "Player_6": "Rice 3",
    "Player_3": "Virgil 2",
    "Player_4": "J.Timber 5",
    "Player_8": "Bruno G.",
    "Player_9": "Ekitik\u00E9 2",
    "Player_15": "Dorgu 15"
  },
  {
    "manager_Name": "1,308( 109,278 )",
    "Teams": "Wirtz Nightmare( Adam Owens )",
    "SXL": "WAL",
    "Latp": "29",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 2",
    "Player_10": "Ekitik\u00E9 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Grealish 3",
    "Player_14": "Andersen 2",
    "Player_7": "Gordon 3",
    "Player_2": "Van de",
    "Player_5": "Saka 1",
    "Player_6": "Foden 1",
    "Player_3": "Mukiele 6",
    "Player_4": "Konat\u00E9 2",
    "Player_8": "Wilson 2",
    "Player_9": "Haaland 4",
    "Player_15": "Dalot 5"
  },
  {
    "manager_Name": "1,302( 138,163 )",
    "Teams": "Kings of Leon Osman( Declan Reilly )",
    "SXL": "ENG",
    "Latp": "40",
    "Player_1": "Pickford 10",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Kroupi.Jr 2",
    "Player_14": "O\u0027Reilly -1",
    "Player_7": "Saka 1",
    "Player_2": "Gabriel 8",
    "Player_5": "Wilson 2",
    "Player_6": "Rice 3",
    "Player_3": "Van de",
    "Player_4": "Alderete 1",
    "Player_8": "Foden 1",
    "Player_9": "Tavernier 8",
    "Player_15": "Tarkowski 8"
  },
  {
    "manager_Name": "1,292( 202,573 )",
    "Teams": "Los Blancos( Eamonn Mifsud )",
    "SXL": "MLT",
    "Latp": "45",
    "Player_1": "Raya 6",
    "Player_11": "Ekitik\u00E9 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Andersen 2",
    "Player_14": "Rodon 6",
    "Player_7": "Enzo 6",
    "Player_2": "O\u0027Reilly -1",
    "Player_5": "Rice 3",
    "Player_6": "Semenyo 2",
    "Player_3": "Virgil 2",
    "Player_4": "Gabriel 8",
    "Player_8": "Bruno G.",
    "Player_9": "B.Fernandes 10",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,292( 203,950 )",
    "Teams": "What The Nelli( Ben Cordingley )",
    "SXL": "ENG",
    "Latp": "31",
    "Player_1": "Raya 6",
    "Player_11": "Calvert-Lewin 2",
    "Player_10": "Thiago 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Andersen 2",
    "Player_14": "Tarkowski 8",
    "Player_7": "Szoboszlai 0",
    "Player_2": "O\u0027Reilly -1",
    "Player_5": "Saka 1",
    "Player_6": "Foden 1",
    "Player_3": "J.Timber 5",
    "Player_4": "Thiaw 9",
    "Player_8": "Wilson 2",
    "Player_9": "Haaland 4",
    "Player_15": "Anderson 5"
  },
  {
    "manager_Name": "1,288( 234,188 )",
    "Teams": "Hltex Lykoi( Ioannis Poulios )",
    "SXL": "GRC",
    "Latp": "47",
    "Player_1": "Verbruggen 2",
    "Player_11": "Woltemade 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Alderete 1",
    "Player_14": "Dorgu 15",
    "Player_7": "Szoboszlai 0",
    "Player_2": "Hall 9",
    "Player_5": "Rice 3",
    "Player_6": "Enzo 6",
    "Player_3": "Virgil 2",
    "Player_4": "Gabriel 8",
    "Player_8": "Palmer 9",
    "Player_9": "Watkins 2",
    "Player_15": "Dewsbury-Hall 0"
  },
  {
    "manager_Name": "1,284( 268,835 )",
    "Teams": "Glazebrook FC( Sam Frankland )",
    "SXL": "ENG",
    "Latp": "42",
    "Player_1": "Sels 10",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Foden 1",
    "Player_14": "Gu\u00E9hi 0",
    "Player_7": "Rogers 4",
    "Player_2": "Cash 2",
    "Player_5": "Saka 1",
    "Player_6": "Wilson 2",
    "Player_3": "Van Hecke",
    "Player_4": "Konat\u00E9 2",
    "Player_8": "Bruno G.",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Matheus N."
  },
  {
    "manager_Name": "1,277( 330,558 )",
    "Teams": "Haribo Scharmix( Conor Maguire )",
    "SXL": "ENG",
    "Latp": "36",
    "Player_1": "Kelleher 1",
    "Player_11": "Ekitik\u00E9 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Gu\u00E9hi 0",
    "Player_14": "Anderson 5",
    "Player_7": "Saka 1",
    "Player_2": "Senesi 3",
    "Player_5": "Wilson 2",
    "Player_6": "Rogers 2",
    "Player_3": "Chalobah 8",
    "Player_4": "Gabriel 8",
    "Player_8": "Barnes 3",
    "Player_9": "Thiago 2",
    "Player_15": "Keane 0"
  },
  {
    "manager_Name": "1,277( 337,967 )",
    "Teams": "For Better or Wirtz( Theo Dixon )",
    "SXL": "ENG",
    "Latp": "37",
    "Player_1": "Kelleher 1",
    "Player_11": "Ekitik\u00E9 4",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Anderson 5",
    "Player_14": "Dorgu 15",
    "Player_7": "Gordon 3",
    "Player_2": "Gabriel 8",
    "Player_5": "Enzo 6",
    "Player_6": "Rogers 2",
    "Player_3": "Mukiele 6",
    "Player_4": "Andersen 2",
    "Player_8": "Foden 1",
    "Player_9": "Mateta 2",
    "Player_15": "O\u0027Reilly -1"
  },
  {
    "manager_Name": "1,276( 347,914 )",
    "Teams": "Maggnificent15( Derren Maggs )",
    "SXL": "ENG",
    "Latp": "39",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 4",
    "Player_10": "Ekitik\u00E9 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Kroupi.Jr 2",
    "Player_14": "Gudmundsson 6",
    "Player_7": "Enzo 6",
    "Player_2": "Collins 1",
    "Player_5": "Gabriel 8",
    "Player_6": "Foden 1",
    "Player_3": "O\u0027Reilly -1",
    "Player_4": "Hall 9",
    "Player_8": "Saka 1",
    "Player_9": "Wilson 2",
    "Player_15": "Anderson 5"
  },
  {
    "manager_Name": "1,274( 365,000 )",
    "Teams": "IK S\u00E4tra( Filip Larsson )",
    "SXL": "MLT",
    "Latp": "38",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 2",
    "Player_10": "Thiago 2",
    "Player_12": "Verbruggen 2",
    "Player_13": "Tarkowski 8",
    "Player_14": "Minteh 1",
    "Player_7": "Neto 3",
    "Player_2": "Thiaw 9",
    "Player_5": "Wilson 2",
    "Player_6": "Foden 1",
    "Player_3": "O\u0027Reilly -1",
    "Player_4": "Chalobah 8",
    "Player_8": "Gakpo 2",
    "Player_9": "Haaland 4",
    "Player_15": "Collins 1"
  },
  {
    "manager_Name": "1,274( 366,554 )",
    "Teams": "NoRelegationPls( Haykel Mansour )",
    "SXL": "MLT",
    "Latp": "46",
    "Player_1": "Henderson 2",
    "Player_11": "Watkins 2",
    "Player_10": "Ekitik\u00E9 4",
    "Player_12": "Kelleher 1",
    "Player_13": "Cucurella 5",
    "Player_14": "Mitoma 2",
    "Player_7": "Rogers 2",
    "Player_2": "J.Timber 5",
    "Player_5": "B.Fernandes 10",
    "Player_6": "Rice 3",
    "Player_3": "Gabriel 8",
    "Player_4": "Cash 2",
    "Player_8": "Enzo 6",
    "Player_9": "Thiago 2",
    "Player_15": "Mu\u00F1oz 0"
  },
  {
    "manager_Name": "1,270( 417,808 )",
    "Teams": "Alpha Academy( Jamie Davies )",
    "SXL": "ENG",
    "Latp": "49",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 4",
    "Player_10": "Ekitik\u00E9 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Matheus N.",
    "Player_14": "Zubimendi 3",
    "Player_7": "Gordon 3",
    "Player_2": "Dorgu 15",
    "Player_5": "Gomez 2",
    "Player_6": "Rogers 2",
    "Player_3": "Frimpong 2",
    "Player_4": "Thiaw 9",
    "Player_8": "Semenyo 2",
    "Player_9": "Thiago 2",
    "Player_15": "Lewis-Skelly 0"
  },
  {
    "manager_Name": "1,264( 488,615 )",
    "Teams": "XG Stats XI( Will Gunn )",
    "SXL": "ENG",
    "Latp": "34",
    "Player_1": "Verbruggen 2",
    "Player_11": "Haaland 2",
    "Player_10": "Ekitik\u00E9 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Garner 4",
    "Player_14": "Richards 2",
    "Player_7": "Saka 1",
    "Player_2": "Tarkowski 8",
    "Player_5": "Virgil 2",
    "Player_6": "Semenyo 2",
    "Player_3": "Alderete 1",
    "Player_4": "Gabriel 8",
    "Player_8": "Rice 3",
    "Player_9": "Foden 1",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,261( 539,237 )",
    "Teams": "kinder mbeumo( Gianluca Tanti )",
    "SXL": "MLT",
    "Latp": "47",
    "Player_1": "Raya 6",
    "Player_11": "Ekitik\u00E9 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Tete 0",
    "Player_14": "Thiago 2",
    "Player_7": "B.Fernandes 10",
    "Player_2": "Konsa 2",
    "Player_5": "Wilson 2",
    "Player_6": "Rogers 2",
    "Player_3": "J.Timber 5",
    "Player_4": "Lacroix 1",
    "Player_8": "Rice 3",
    "Player_9": "Wirtz 10",
    "Player_15": "Dalot 5"
  },
  {
    "manager_Name": "1,258( 572,851 )",
    "Teams": "DBA Utd( Jim Lennox )",
    "SXL": "ENG",
    "Latp": "47",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Richards 2",
    "Player_14": "Van de",
    "Player_7": "Enzo 6",
    "Player_2": "Gabriel 8",
    "Player_5": "Yeremy 9",
    "Player_6": "Saka 1",
    "Player_3": "Mukiele 6",
    "Player_4": "Andersen 2",
    "Player_8": "Semenyo 2",
    "Player_9": "Cherki 1",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,256( 609,244 )",
    "Teams": "Mo With The Flo( Tom Atkinson )",
    "SXL": "MLT",
    "Latp": "37",
    "Player_1": "Donnarumma 2",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Gu\u00E9hi 0",
    "Player_14": "Cunha 4",
    "Player_7": "Rogers 2",
    "Player_2": "Chalobah 8",
    "Player_5": "Andersen 2",
    "Player_6": "Reijnders 1",
    "Player_3": "Virgil 2",
    "Player_4": "Gabriel 8",
    "Player_8": "Anderson 5",
    "Player_9": "Saka 1",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,253( 651,456 )",
    "Teams": "House TarGoalyen( Matteo Farrugia )",
    "SXL": "MLT",
    "Latp": "50",
    "Player_1": "Raya 6",
    "Player_11": "Watkins 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Est\u00E8ve 2",
    "Player_14": "Konsa 2",
    "Player_7": "Mbeumo 9",
    "Player_2": "Saliba 8",
    "Player_5": "Semenyo 2",
    "Player_6": "B.Fernandes 10",
    "Player_3": "Virgil 2",
    "Player_4": "Van de",
    "Player_8": "Anderson 5",
    "Player_9": "Rogers 2",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,246( 778,480 )",
    "Teams": "The Bees( Tove Ronneb\u00E4ck )",
    "SXL": "MLT",
    "Latp": "43",
    "Player_1": "S\u00E1nchez 11",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Lewis-Potter 1",
    "Player_14": "Marc Guiu",
    "Player_7": "Bruno G.",
    "Player_2": "Gabriel 8",
    "Player_5": "Tavernier 8",
    "Player_6": "Cunha 4",
    "Player_3": "O\u0027Reilly -1",
    "Player_4": "Virgil 2",
    "Player_8": "Saka 1",
    "Player_9": "Foden 1",
    "Player_15": "Est\u00E8ve 2"
  },
  {
    "manager_Name": "1,246( 785,100 )",
    "Teams": "KERAMACTICOS \u26A1( Michael Keramas )",
    "SXL": "GRC",
    "Latp": "54",
    "Player_1": "Verbruggen 2",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago 2",
    "Player_12": "Kelleher 1",
    "Player_13": "Cherki 1",
    "Player_14": "Lewis-Potter 1",
    "Player_7": "Rice 3",
    "Player_2": "Mukiele 6",
    "Player_5": "B.Fernandes 10",
    "Player_6": "Enzo 6",
    "Player_3": "Hall 9",
    "Player_4": "Gabriel 8",
    "Player_8": "Wilson 2",
    "Player_9": "Ekitik\u00E9 4",
    "Player_15": "Mu\u00F1oz 0"
  },
  {
    "manager_Name": "1,245( 797,114 )",
    "Teams": "Joga Bonito FC( Christophe Peixoto )",
    "SXL": "HUN",
    "Latp": "37",
    "Player_1": "Raya 6",
    "Player_11": "Ekitik\u00E9 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Andersen 2",
    "Player_14": "Gudmundsson 6",
    "Player_7": "Foden 1",
    "Player_2": "Van de",
    "Player_5": "Szoboszlai 0",
    "Player_6": "Enzo 6",
    "Player_3": "Thiaw 9",
    "Player_4": "J.Timber 5",
    "Player_8": "Saka 1",
    "Player_9": "Gordon 3",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,241( 879,273 )",
    "Teams": "DinamoB( Pietro Menna )",
    "SXL": "MLT",
    "Latp": "45",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 4",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Vicario 1",
    "Player_13": "Anthony 2",
    "Player_14": "Gu\u00E9hi 0",
    "Player_7": "Wilson 2",
    "Player_2": "Gabriel 8",
    "Player_5": "Semenyo 2",
    "Player_6": "Rice 3",
    "Player_3": "Chalobah 8",
    "Player_4": "O\u0027Reilly -1",
    "Player_8": "Bruno G.",
    "Player_9": "Thiago 2",
    "Player_15": "Keane 0"
  },
  {
    "manager_Name": "1,240( 894,525 )",
    "Teams": "Lallish United( Melwin Holst )",
    "SXL": "SWE",
    "Latp": "35",
    "Player_1": "Raya 6",
    "Player_11": "Calvert-Lewin 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Gu\u00E9hi 0",
    "Player_14": "Marc Guiu",
    "Player_7": "Saka 1",
    "Player_2": "Thiaw 9",
    "Player_5": "Semenyo 2",
    "Player_6": "Rogers 2",
    "Player_3": "J.Timber 5",
    "Player_4": "Matheus N.",
    "Player_8": "Stach 0",
    "Player_9": "Cunha 4",
    "Player_15": "Keane 0"
  },
  {
    "manager_Name": "1,233( 1,045,520 )",
    "Teams": "Ronalbinho( Albin Jonsson )",
    "SXL": "MLT",
    "Latp": "44",
    "Player_1": "Donnarumma 2",
    "Player_11": "Haaland 4",
    "Player_10": "Woltemade 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Schade 1",
    "Player_14": "Dalot 5",
    "Player_7": "L.Miley 1",
    "Player_2": "Virgil 2",
    "Player_5": "Rogers 2",
    "Player_6": "Palmer 9",
    "Player_3": "Lacroix 1",
    "Player_4": "Thiaw 9",
    "Player_8": "Wirtz 10",
    "Player_9": "Thiago 2",
    "Player_15": "Gudmundsson 6"
  },
  {
    "manager_Name": "1,233( 1,058,838 )",
    "Teams": "Ctrl Alt Attack( Laimonas Zukas )",
    "SXL": "LTU",
    "Latp": "47",
    "Player_1": "Verbruggen 2",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Anderson 5",
    "Player_14": "Senesi 3",
    "Player_7": "Enzo 6",
    "Player_2": "Gabriel 8",
    "Player_5": "Cunha 4",
    "Player_6": "Foden 1",
    "Player_3": "Van Hecke",
    "Player_4": "Thiaw 9",
    "Player_8": "Rice 3",
    "Player_9": "Ekitik\u00E9 2",
    "Player_15": "Est\u00E8ve 2"
  },
  {
    "manager_Name": "1,231( 1,089,217 )",
    "Teams": "Rekegutt United( Eirik Presttun )",
    "SXL": "MLT",
    "Latp": "37",
    "Player_1": "S\u00E1nchez 11",
    "Player_11": "Bowen 3",
    "Player_10": "Calvert-Lewin 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Gu\u00E9hi 0",
    "Player_14": "Matheus N.",
    "Player_7": "Gakpo 2",
    "Player_2": "James 7",
    "Player_5": "Semenyo 2",
    "Player_6": "Foden 1",
    "Player_3": "Cash 2",
    "Player_4": "Hincapie 0",
    "Player_8": "Bruno G.",
    "Player_9": "Haaland 4",
    "Player_15": "Cullen 0"
  },
  {
    "manager_Name": "1,230( 1,127,911 )",
    "Teams": "Saksa FC( Neil Mifsud )",
    "SXL": "MLT",
    "Latp": "47",
    "Player_1": "Pickford 10",
    "Player_11": "Ekitik\u00E9 2",
    "Player_10": "Woltemade 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Dalot 5",
    "Player_14": "Dewsbury-Hall 0",
    "Player_7": "Wirtz 10",
    "Player_2": "Thiaw 9",
    "Player_5": "Wilson 2",
    "Player_6": "Rice 3",
    "Player_3": "Richards 2",
    "Player_4": "Virgil 2",
    "Player_8": "Foden 1",
    "Player_9": "Haaland 4",
    "Player_15": "Heaven 1"
  },
  {
    "manager_Name": "1,229( 1,142,155 )",
    "Teams": "Bebenciukai( Marius z )",
    "SXL": "LTU",
    "Latp": "32",
    "Player_1": "Pope 6",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Reijnders 1",
    "Player_14": "Keane 0",
    "Player_7": "Barnes 3",
    "Player_2": "J.Timber 5",
    "Player_5": "Wilson 2",
    "Player_6": "Saka 1",
    "Player_3": "Van de",
    "Player_4": "Gudmundsson 6",
    "Player_8": "Foden 1",
    "Player_9": "Ekitik\u00E9 4",
    "Player_15": "Dorgu 15"
  },
  {
    "manager_Name": "1,228( 1,165,754 )",
    "Teams": "FC Cantona( Nelson Schutt )",
    "SXL": "SWE",
    "Latp": "50",
    "Player_1": "S\u00E1nchez 11",
    "Player_11": "Thiago 2",
    "Player_10": "Haaland 6",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "King 1",
    "Player_7": "Wilson 2",
    "Player_2": "James 7",
    "Player_5": "Andersen 2",
    "Player_6": "Cunha 4",
    "Player_3": "O\u0027Reilly -1",
    "Player_4": "Dorgu 15",
    "Player_8": "Saka 1",
    "Player_9": "Foden 1",
    "Player_15": "Patterson 0"
  },
  {
    "manager_Name": "1,226( 1,214,283 )",
    "Teams": "Gedward City FC( Graham Edwards )",
    "SXL": "ENG",
    "Latp": "34",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 2",
    "Player_10": "Haaland 2",
    "Player_12": "S\u00E1nchez 11",
    "Player_13": "O\u0027Reilly -1",
    "Player_14": "Devenny 2",
    "Player_7": "Semenyo 2",
    "Player_2": "Gabriel 8",
    "Player_5": "Rogers 4",
    "Player_6": "Cunha 4",
    "Player_3": "Virgil 2",
    "Player_4": "Van de",
    "Player_8": "Wilson 2",
    "Player_9": "Woltemade 2",
    "Player_15": "Justin 9"
  },
  {
    "manager_Name": "1,224( 1,266,706 )",
    "Teams": "Starship( Olumide Okedusi )",
    "SXL": "EST",
    "Latp": "35",
    "Player_1": "Donnarumma 2",
    "Player_11": "Thiago 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "L.Miley 1",
    "Player_14": "Gu\u00E9hi 0",
    "Player_7": "Foden 1",
    "Player_2": "J.Timber 5",
    "Player_5": "Rogers 2",
    "Player_6": "Saka 1",
    "Player_3": "Mukiele 6",
    "Player_4": "Tarkowski 8",
    "Player_8": "Wilson 2",
    "Player_9": "Calvert-Lewin 2",
    "Player_15": "Est\u00E8ve 2"
  },
  {
    "manager_Name": "1,222( 1,323,293 )",
    "Teams": "Goalless( Panagiotis Sfikas )",
    "SXL": "GRC",
    "Latp": "34",
    "Player_1": "Petrovi\u0107 2",
    "Player_11": "Ekitik\u00E9 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Tarkowski 8",
    "Player_14": "Dorgu 15",
    "Player_7": "Szoboszlai 0",
    "Player_2": "J.Timber 5",
    "Player_5": "Gordon 3",
    "Player_6": "Rice 3",
    "Player_3": "Virgil 2",
    "Player_4": "Van Hecke",
    "Player_8": "Enzo 6",
    "Player_9": "Foden 1",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,221( 1,334,595 )",
    "Teams": "COYS( Zachary Black )",
    "SXL": "CAN",
    "Latp": "38",
    "Player_1": "A.Becker 2",
    "Player_11": "Haaland 4",
    "Player_10": "Wilson 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Gu\u00E9hi 0",
    "Player_14": "Obi 0",
    "Player_7": "\u00D8degaard 1",
    "Player_2": "Gabriel 8",
    "Player_5": "Mukiele 6",
    "Player_6": "Palmer 9",
    "Player_3": "Van de",
    "Player_4": "Pedro Porro",
    "Player_8": "Saka 1",
    "Player_9": "Foden 1",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,212( 1,580,867 )",
    "Teams": "Southmalm Strikers( Johan Hammarstrom )",
    "SXL": "SWE",
    "Latp": "33",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 2",
    "Player_10": "Watkins 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Cunha 4",
    "Player_14": "Andersen 2",
    "Player_7": "Rogers 2",
    "Player_2": "Alderete 1",
    "Player_5": "Wilson 2",
    "Player_6": "Bruno G.",
    "Player_3": "Gabriel 8",
    "Player_4": "Van de",
    "Player_8": "Rice 3",
    "Player_9": "Thiago 2",
    "Player_15": "Dorgu 15"
  },
  {
    "manager_Name": "1,211( 1,604,101 )",
    "Teams": "Change Name( Alexander Oyangen Johansen )",
    "SXL": "MLT",
    "Latp": "42",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Tarkowski 8",
    "Player_14": "Cunha 4",
    "Player_7": "Bruno G.",
    "Player_2": "Van de",
    "Player_5": "J.Timber 5",
    "Player_6": "Rogers 2",
    "Player_3": "Pedro Porro",
    "Player_4": "Chalobah 8",
    "Player_8": "Enzo 6",
    "Player_9": "Mateta 2",
    "Player_15": "Dewsbury-Hall 0"
  },
  {
    "manager_Name": "1,211( 1,608,889 )",
    "Teams": "Toasted Ekitike( Ollie Hatfield )",
    "SXL": "WAL",
    "Latp": "34",
    "Player_1": "Roefs 2",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Gravenberch 2",
    "Player_14": "Keane 0",
    "Player_7": "Bruno G.",
    "Player_2": "James 7",
    "Player_5": "Saka 1",
    "Player_6": "Rice 3",
    "Player_3": "Gabriel 8",
    "Player_4": "Van de",
    "Player_8": "Rogers 2",
    "Player_9": "Calvert-Lewin 2",
    "Player_15": "Alderete 1"
  },
  {
    "manager_Name": "1,210( 1,629,386 )",
    "Teams": "Ctrl Alt De Ligt( Marlon Vella )",
    "SXL": "MLT",
    "Latp": "35",
    "Player_1": "Petrovi\u0107 2",
    "Player_11": "Thiago 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Marc Guiu",
    "Player_14": "Gu\u00E9hi 0",
    "Player_7": "B.Fernandes 10",
    "Player_2": "Alderete 1",
    "Player_5": "Rice 3",
    "Player_6": "Bruno G.",
    "Player_3": "Andersen 2",
    "Player_4": "J.Timber 5",
    "Player_8": "Wilson 2",
    "Player_9": "Foden 1",
    "Player_15": "Hincapie 0"
  },
  {
    "manager_Name": "1,208( 1,698,684 )",
    "Teams": "21X.....( John Tiltmann )",
    "SXL": "MLT",
    "Latp": "46",
    "Player_1": "Pickford 10",
    "Player_11": "Thiago 2",
    "Player_10": "Haaland 2",
    "Player_12": "Petrovi\u0107 2",
    "Player_13": "Gu\u00E9hi 0",
    "Player_14": "Foden 1",
    "Player_7": "Wilson 2",
    "Player_2": "Chalobah 8",
    "Player_5": "Rice 3",
    "Player_6": "Bruno G.",
    "Player_3": "Tarkowski 8",
    "Player_4": "Alderete 1",
    "Player_8": "Rogers 2",
    "Player_9": "Woltemade 2",
    "Player_15": "Hartman 0"
  },
  {
    "manager_Name": "1,204( 1,802,811 )",
    "Teams": "Black \u0026 Blue( Mark Zammit )",
    "SXL": "MLT",
    "Latp": "40",
    "Player_1": "Raya 6",
    "Player_11": "Calvert-Lewin 2",
    "Player_10": "Haaland 4",
    "Player_12": "Roefs 2",
    "Player_13": "Wilson 2",
    "Player_14": "Gu\u00E9hi 0",
    "Player_7": "Bruno G.",
    "Player_2": "Chalobah 8",
    "Player_5": "Gravenberch 2",
    "Player_6": "Rice 3",
    "Player_3": "Gabriel 8",
    "Player_4": "Alderete 1",
    "Player_8": "Foden 1",
    "Player_9": "Thiago 2",
    "Player_15": "Lewis-Potter 1"
  },
  {
    "manager_Name": "1,201( 1,893,655 )",
    "Teams": "Gambit( Nicola Frasca )",
    "SXL": "MLT",
    "Latp": "40",
    "Player_1": "S\u00E1nchez 11",
    "Player_11": "Mateta 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Verbruggen 2",
    "Player_13": "Gu\u00E9hi 0",
    "Player_14": "Gudmundsson 6",
    "Player_7": "Rogers 2",
    "Player_2": "Virgil 2",
    "Player_5": "Reijnders 1",
    "Player_6": "Semenyo 2",
    "Player_3": "J.Timber 5",
    "Player_4": "Van de",
    "Player_8": "Rice 3",
    "Player_9": "Haaland 4",
    "Player_15": "Wilson 2"
  },
  {
    "manager_Name": "1,196( 2,054,677 )",
    "Teams": "Massilia( Daniel Borg )",
    "SXL": "MLT",
    "Latp": "44",
    "Player_1": "Petrovi\u0107 2",
    "Player_11": "Thiago 2",
    "Player_10": "Calvert-Lewin 2",
    "Player_12": "Sels 10",
    "Player_13": "Gu\u00E9hi 0",
    "Player_14": "Stach 0",
    "Player_7": "Wirtz 20",
    "Player_2": "Van de",
    "Player_5": "Lewis-Potter 1",
    "Player_6": "Foden 1",
    "Player_3": "Senesi 3",
    "Player_4": "Chalobah 8",
    "Player_8": "Bruno G.",
    "Player_9": "Haaland 2",
    "Player_15": "Anderson 5"
  },
  {
    "manager_Name": "1,193( 2,158,744 )",
    "Teams": "MDJ XI( Matthew James )",
    "SXL": "ENG",
    "Latp": "50",
    "Player_1": "S\u00E1nchez 11",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Wharton 1",
    "Player_14": "Hickey 1",
    "Player_7": "Saka 1",
    "Player_2": "Chalobah 8",
    "Player_5": "Cunha 4",
    "Player_6": "Bruno G.",
    "Player_3": "Thiaw 9",
    "Player_4": "Pedro Porro",
    "Player_8": "Wilson 2",
    "Player_9": "Watkins 2",
    "Player_15": "Est\u00E8ve 2"
  },
  {
    "manager_Name": "1,192( 2,190,624 )",
    "Teams": "Cozier Vibes( D-J O\u0027Loughlin )",
    "SXL": "ENG",
    "Latp": "29",
    "Player_1": "Donnarumma 2",
    "Player_11": "Bowen 3",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Stach 0",
    "Player_14": "Andersen 2",
    "Player_7": "Minteh 1",
    "Player_2": "Gabriel 8",
    "Player_5": "Foden 1",
    "Player_6": "Rogers 4",
    "Player_3": "Richards 2",
    "Player_4": "Senesi 3",
    "Player_8": "Saka 1",
    "Player_9": "Thiago 2",
    "Player_15": "Gudmundsson 6"
  },
  {
    "manager_Name": "1,189( 2,282,318 )",
    "Teams": "Mc Bryde FC( Mark Mc Bryde )",
    "SXL": "MLT",
    "Latp": "40",
    "Player_1": "S\u00E1nchez 11",
    "Player_11": "Ekitik\u00E9 2",
    "Player_10": "Haaland 4",
    "Player_12": "Sels 10",
    "Player_13": "Stach 0",
    "Player_14": "Gu\u00E9hi 0",
    "Player_7": "Tel 2",
    "Player_2": "James 7",
    "Player_5": "Neto 3",
    "Player_6": "Rogers 2",
    "Player_3": "Senesi 3",
    "Player_4": "Frimpong 2",
    "Player_8": "Wilson 2",
    "Player_9": "Woltemade 2",
    "Player_15": "Tarkowski 8"
  },
  {
    "manager_Name": "1,189( 2,288,737 )",
    "Teams": "Gimby( Piotr Kluczynski )",
    "SXL": "MLT",
    "Latp": "50",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Kroupi.Jr 2",
    "Player_14": "Virgil 2",
    "Player_7": "Rogers 2",
    "Player_2": "Cash 2",
    "Player_5": "Wirtz 10",
    "Player_6": "Saka 1",
    "Player_3": "Van de",
    "Player_4": "J.Timber 5",
    "Player_8": "Cherki 1",
    "Player_9": "Wilson 2",
    "Player_15": "Van Hecke"
  },
  {
    "manager_Name": "1,186( 2,367,615 )",
    "Teams": "Malta Knights( Martin Knight )",
    "SXL": "MLT",
    "Latp": "38",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 2",
    "Player_10": "Bowen 6",
    "Player_12": "Pope 6",
    "Player_13": "Diouf 0",
    "Player_14": "Gu\u00E9hi 0",
    "Player_7": "Caicedo 5",
    "Player_2": "Konsa 2",
    "Player_5": "Semenyo 2",
    "Player_6": "Rice 3",
    "Player_3": "Gabriel 8",
    "Player_4": "Lacroix 1",
    "Player_8": "Mac Allister",
    "Player_9": "Ekitik\u00E9 2",
    "Player_15": "Sarr 0"
  },
  {
    "manager_Name": "1,186( 2,393,806 )",
    "Teams": "A Cunha Mateta( Jon Briscoe White )",
    "SXL": "MLT",
    "Latp": "34",
    "Player_1": "Roefs 2",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Wilson 2",
    "Player_14": "Chalobah 8",
    "Player_7": "Bruno G.",
    "Player_2": "Gabriel 8",
    "Player_5": "Semenyo 2",
    "Player_6": "Rogers 2",
    "Player_3": "Van de",
    "Player_4": "Mukiele 6",
    "Player_8": "Rice 3",
    "Player_9": "Calvert-Lewin 2",
    "Player_15": "Gu\u00E9hi 0"
  },
  {
    "manager_Name": "1,183( 2,479,949 )",
    "Teams": "Charli xGx( Charlie Rogers )",
    "SXL": "ENG",
    "Latp": "33",
    "Player_1": "S\u00E1nchez 11",
    "Player_11": "Welbeck 1",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Reijnders 1",
    "Player_14": "Kayode 1",
    "Player_7": "Rogers 2",
    "Player_2": "Cash 2",
    "Player_5": "Saka 1",
    "Player_6": "Foden 1",
    "Player_3": "J.Timber 5",
    "Player_4": "Virgil 2",
    "Player_8": "Wilson 2",
    "Player_9": "Thiago 2",
    "Player_15": "Est\u00E8ve 2"
  },
  {
    "manager_Name": "1,182( 2,511,764 )",
    "Teams": "Soccertainment( Adam Lismore )",
    "SXL": "ENG",
    "Latp": "42",
    "Player_1": "Kelleher 1",
    "Player_11": "Haaland 4",
    "Player_10": "Kroupi.Jr 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Gudmundsson 6",
    "Player_14": "Cunha 4",
    "Player_7": "Cherki 1",
    "Player_2": "Gabriel 8",
    "Player_5": "Rice 3",
    "Player_6": "Garner 4",
    "Player_3": "Hall 9",
    "Player_4": "J.Timber 5",
    "Player_8": "Gordon 3",
    "Player_9": "Ekitik\u00E9 2",
    "Player_15": "Dorgu 15"
  },
  {
    "manager_Name": "1,172( 2,845,158 )",
    "Teams": "AlpayFC( Alpay Al\u0131n )",
    "SXL": "TUR",
    "Latp": "53",
    "Player_1": "Sels 10",
    "Player_11": "Thiago 2",
    "Player_10": "Haaland 4",
    "Player_12": "Trafford 0",
    "Player_13": "Calafiori 0",
    "Player_14": "J.Palhinha 0",
    "Player_7": "Joelinton 3",
    "Player_2": "Saliba 8",
    "Player_5": "Cucurella 5",
    "Player_6": "Cherki 1",
    "Player_3": "James 7",
    "Player_4": "Virgil 2",
    "Player_8": "B.Fernandes 10",
    "Player_9": "Solanke 1",
    "Player_15": "Sarr 0"
  }
];