var s = [
  {
    "manager_Name": "1,175( 1,530,449 )",
    "Teams": "yoo( Nishant Singh )",
    "SXL": "IND",
    "Latp": "21",
    "Player_1": "Donnarumma 2",
    "Player_11": "Haaland 4",
    "Player_10": "Watkins EVE",
    "Player_12": "Kelleher 1",
    "Player_13": "Mukiele 6",
    "Player_14": "Xhaka 2",
    "Player_7": "Rogers EVE",
    "Player_2": "J.Timber 5",
    "Player_5": "Tarkowski AVL",
    "Player_6": "Cherki 1",
    "Player_3": "Gabriel 6",
    "Player_4": "Thiaw WOL",
    "Player_8": "Saka 1",
    "Player_9": "Thiago 2",
    "Player_15": "Devenny 2"
  },
  {
    "manager_Name": "1,147( 2,395,732 )",
    "Teams": "WMB( Raj Kanango )",
    "SXL": "IND",
    "Latp": "21",
    "Player_1": "Donnarumma 2",
    "Player_11": "Haaland 4",
    "Player_10": "Bowen 3",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Dalot 5",
    "Player_14": "Dorgu 12",
    "Player_7": "Saka 1",
    "Player_2": "Senesi BHA",
    "Player_5": "Wilson 2",
    "Player_6": "Rogers EVE",
    "Player_3": "Thiaw WOL",
    "Player_4": "J.Timber 5",
    "Player_8": "Semenyo 2",
    "Player_9": "Thiago 2",
    "Player_15": "Cullen 0"
  },
  {
    "manager_Name": "1,096( 4,214,212 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "26",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 2",
    "Player_12": "Petrovi\u0107 BHA",
    "Player_13": "Stach 0",
    "Player_14": "L.Miley WOL",
    "Player_7": "Saka 1",
    "Player_2": "Mukiele 6",
    "Player_5": "Thiaw WOL",
    "Player_6": "Foden 1",
    "Player_3": "Cash EVE",
    "Player_4": "Alderete 1",
    "Player_8": "Rice 3",
    "Player_9": "Ekitik\u00E9 2",
    "Player_15": "Mitchell 0"
  },
  {
    "manager_Name": "1,041( 6,105,012 )",
    "Teams": "DUFC( Nitesh Kumar Singh )",
    "SXL": "IND",
    "Latp": "13",
    "Player_1": "Pickford AVL",
    "Player_11": "Richarlison 0",
    "Player_10": "Woltemade WOL",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Mitchell 0",
    "Player_14": "Tavernier BHA",
    "Player_7": "Bruno G.",
    "Player_2": "Gu\u00E9hi 0",
    "Player_5": "Foden 1",
    "Player_6": "Rogers EVE",
    "Player_3": "Chalobah 8",
    "Player_4": "Tarkowski AVL",
    "Player_8": "Garner AVL",
    "Player_9": "Haaland 4",
    "Player_15": "Mukiele 6"
  }
];