var s = [
  {
    "manager_Name": "1,179( 14,656 )",
    "Teams": "Rice Rice Baby( kaisler Schembri )",
    "SXL": "MLT",
    "Latp": "55",
    "Player_1": "Donnarumma 2",
    "Player_11": "Haaland 2",
    "Player_10": "Ekitik\u00E9 10",
    "Player_12": "Matthews 0",
    "Player_13": "Gonzalez 0",
    "Player_14": "Calafiori 0",
    "Player_7": "Wirtz 10",
    "Player_2": "Virgil 2",
    "Player_5": "Saka 7",
    "Player_6": "Grealish 0",
    "Player_3": "Heaven 8",
    "Player_4": "Keane 10",
    "Player_8": "Foden 2",
    "Player_9": "Bowen 2",
    "Player_15": "Hoever 0"
  },
  {
    "manager_Name": "1,115( 286,880 )",
    "Teams": "Charlie\u0027s Angels( Charlie Smith )",
    "SXL": "ENG",
    "Latp": "34",
    "Player_1": "Roefs 3",
    "Player_11": "Kroupi.Jr 1",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 11",
    "Player_13": "Mukiele 4",
    "Player_14": "Est\u00E8ve 0",
    "Player_7": "Saka 7",
    "Player_2": "Cucurella 2",
    "Player_5": "Palmer 2",
    "Player_6": "Foden 2",
    "Player_3": "R\u00FAben 3",
    "Player_4": "Lacroix 3",
    "Player_8": "Gordon 2",
    "Player_9": "Wilson 5",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,114( 292,119 )",
    "Teams": "MaltArsenal FC( Claude Spiteri )",
    "SXL": "MLT",
    "Latp": "40",
    "Player_1": "Donnarumma 2",
    "Player_11": "Richarlison 5",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 11",
    "Player_13": "J.Timber 0",
    "Player_14": "Enzo 1",
    "Player_7": "Gordon 2",
    "Player_2": "Senesi 2",
    "Player_5": "Rice 5",
    "Player_6": "Foden 2",
    "Player_3": "Gu\u00E9hi 2",
    "Player_4": "Gudmundsson 2",
    "Player_8": "Semenyo 9",
    "Player_9": "Thiago 5",
    "Player_15": "Calafiori 0"
  },
  {
    "manager_Name": "1,105( 391,597 )",
    "Teams": "Bend it like Boogie( Ryan Bonello Gatt )",
    "SXL": "MLT",
    "Latp": "42",
    "Player_1": "Kelleher 4",
    "Player_11": "Thiago 5",
    "Player_10": "Haaland 4",
    "Player_12": "Sels 0",
    "Player_13": "J.Timber 0",
    "Player_14": "Xhaka 6",
    "Player_7": "Saka 7",
    "Player_2": "Saliba 2",
    "Player_5": "Gordon 2",
    "Player_6": "Foden 2",
    "Player_3": "Mukiele 4",
    "Player_4": "Gu\u00E9hi 2",
    "Player_8": "Semenyo 9",
    "Player_9": "Kroupi.Jr 1",
    "Player_15": "R\u00FAben 3"
  },
  {
    "manager_Name": "1,105( 394,701 )",
    "Teams": "diavoli 11( Paul Micallef )",
    "SXL": "MLT",
    "Latp": "34",
    "Player_1": "Donnarumma 2",
    "Player_11": "Ekitik\u00E9 5",
    "Player_10": "Haaland 4",
    "Player_12": "Setford 0",
    "Player_13": "J.Timber 0",
    "Player_14": "Calvert-Lewin 8",
    "Player_7": "Semenyo 9",
    "Player_2": "Gu\u00E9hi 2",
    "Player_5": "Foden 2",
    "Player_6": "Rice 5",
    "Player_3": "Senesi 2",
    "Player_4": "Chalobah 0",
    "Player_8": "Bruno G.",
    "Player_9": "Rogers 1",
    "Player_15": "Byram 0"
  },
  {
    "manager_Name": "1,100( 460,967 )",
    "Teams": "Arteta Ball FC( Dylan Camilleri )",
    "SXL": "MLT",
    "Latp": "42",
    "Player_1": "Raya 2",
    "Player_11": "Kroupi.Jr 1",
    "Player_10": "Ekitik\u00E9 5",
    "Player_12": "D\u00FAbravka 11",
    "Player_13": "Stach 4",
    "Player_14": "Heaven 8",
    "Player_7": "Saka 7",
    "Player_2": "Tarkowski 8",
    "Player_5": "Foden 2",
    "Player_6": "Semenyo 9",
    "Player_3": "Virgil 2",
    "Player_4": "Cash 1",
    "Player_8": "Rogers 1",
    "Player_9": "Haaland 4",
    "Player_15": "Est\u00E8ve 0"
  },
  {
    "manager_Name": "1,085( 699,356 )",
    "Teams": "Slika FC( Kyle Gatt )",
    "SXL": "MLT",
    "Latp": "45",
    "Player_1": "D\u00FAbravka 11",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Woltemade 2",
    "Player_12": "Lammens 9",
    "Player_13": "Pedro Porro",
    "Player_14": "Wilson 5",
    "Player_7": "Rice 5",
    "Player_2": "Cucurella 2",
    "Player_5": "Gravenberch 11",
    "Player_6": "Cunha 2",
    "Player_3": "Virgil 2",
    "Player_4": "R\u00FAben 3",
    "Player_8": "Enzo 1",
    "Player_9": "Haaland 4",
    "Player_15": "Hartman 0"
  },
  {
    "manager_Name": "1,082( 752,733 )",
    "Teams": "Bench Warmers( kevin dalli )",
    "SXL": "MLT",
    "Latp": "65",
    "Player_1": "Kelleher 4",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 5",
    "Player_12": "Petrovi\u0107 -1",
    "Player_13": "Merino 2",
    "Player_14": "Gusto 1",
    "Player_7": "Semenyo 9",
    "Player_2": "Gu\u00E9hi 2",
    "Player_5": "Saka 7",
    "Player_6": "Foden 2",
    "Player_3": "Van de",
    "Player_4": "Gvardiol 8",
    "Player_8": "Wilson 5",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Est\u00E8ve 0"
  },
  {
    "manager_Name": "1,081( 787,552 )",
    "Teams": "Taggers FC( Karl Caruana )",
    "SXL": "MLT",
    "Latp": "39",
    "Player_1": "Kelleher 4",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 11",
    "Player_13": "Minteh 1",
    "Player_14": "Wilson 5",
    "Player_7": "Foden 2",
    "Player_2": "Virgil 2",
    "Player_5": "Mukiele 4",
    "Player_6": "Saka 7",
    "Player_3": "James 6",
    "Player_4": "Gu\u00E9hi 2",
    "Player_8": "Rogers 1",
    "Player_9": "Thiago 5",
    "Player_15": "Est\u00E8ve 0"
  },
  {
    "manager_Name": "1,059( 1,286,815 )",
    "Teams": "Gunz( Kurt Zammit )",
    "SXL": "MLT",
    "Latp": "51",
    "Player_1": "D\u00FAbravka 11",
    "Player_11": "Mateta 2",
    "Player_10": "Haaland 4",
    "Player_12": "S\u00E1nchez 3",
    "Player_13": "J.Timber 0",
    "Player_14": "Ballard 0",
    "Player_7": "Cherki 13",
    "Player_2": "James 6",
    "Player_5": "Anthony 1",
    "Player_6": "Rice 5",
    "Player_3": "Gu\u00E9hi 2",
    "Player_4": "Cash 1",
    "Player_8": "Rogers 1",
    "Player_9": "Ekitik\u00E9 5",
    "Player_15": "Merino 2"
  },
  {
    "manager_Name": "1,057( 1,330,895 )",
    "Teams": "Ellul FC( Andrew Ellul )",
    "SXL": "MLT",
    "Latp": "47",
    "Player_1": "Henderson 3",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago 5",
    "Player_12": "Pope 0",
    "Player_13": "Burn 0",
    "Player_14": "Mitoma 0",
    "Player_7": "Caicedo 3",
    "Player_2": "Gu\u00E9hi 2",
    "Player_5": "Van de",
    "Player_6": "Rice 5",
    "Player_3": "Gabriel 2",
    "Player_4": "Milenkovi\u0107 3",
    "Player_8": "Semenyo 9",
    "Player_9": "Mateta 2",
    "Player_15": "Mbeumo 0"
  },
  {
    "manager_Name": "1,056( 1,361,435 )",
    "Teams": "RZM765( Cedrik Dalli )",
    "SXL": "MLT",
    "Latp": "42",
    "Player_1": "Roefs 3",
    "Player_11": "Haaland 4",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Verbruggen 1",
    "Player_13": "Mateta 2",
    "Player_14": "Rodon 1",
    "Player_7": "Rogers 1",
    "Player_2": "Van de",
    "Player_5": "Rice 5",
    "Player_6": "Neto 2",
    "Player_3": "Chalobah 0",
    "Player_4": "Tete 6",
    "Player_8": "Bruno G.",
    "Player_9": "Foden 2",
    "Player_15": "Est\u00E8ve 0"
  },
  {
    "manager_Name": "1,053( 1,454,816 )",
    "Teams": "Let him cook( Henry Adjei )",
    "SXL": "MLT",
    "Latp": "53",
    "Player_1": "Raya 2",
    "Player_11": "Ekitik\u00E9 5",
    "Player_10": "Haaland 4",
    "Player_12": "Kelleher 4",
    "Player_13": "Kudus 3",
    "Player_14": "Thiago 5",
    "Player_7": "Wilson 5",
    "Player_2": "Chalobah 0",
    "Player_5": "R\u00FAben 3",
    "Player_6": "Saka 7",
    "Player_3": "Gu\u00E9hi 2",
    "Player_4": "Mukiele 4",
    "Player_8": "Foden 2",
    "Player_9": "Xhaka 6",
    "Player_15": "Cash 1"
  },
  {
    "manager_Name": "1,051( 1,520,733 )",
    "Teams": "Sultan Army( Julian Sultana )",
    "SXL": "MLT",
    "Latp": "61",
    "Player_1": "Pickford 6",
    "Player_11": "Watkins 12",
    "Player_10": "Calvert-Lewin 16",
    "Player_12": "Donnarumma 2",
    "Player_13": "J.Timber 0",
    "Player_14": "Mateta 2",
    "Player_7": "Rogers 1",
    "Player_2": "Cash 1",
    "Player_5": "Chalobah 0",
    "Player_6": "Foden 2",
    "Player_3": "Thiaw 2",
    "Player_4": "Gabriel 1",
    "Player_8": "Cherki 13",
    "Player_9": "Saka 7",
    "Player_15": "Semenyo 9"
  }
];