var s = [
  {
    "manager_Name": "26( \u00A3102.7m )",
    "Teams": "yoo( Nishant Singh )",
    "SXL": "IND",
    "Latp": "44",
    "Player_1": "Donnarumma 8",
    "Player_11": "Haaland 1",
    "Player_10": "Thiago 4",
    "Player_12": "Kelleher 1",
    "Player_13": "Thiaw 1",
    "Player_14": "Xhaka 0",
    "Player_7": "Saka 2",
    "Player_2": "J.Timber 1",
    "Player_5": "Mukiele 4",
    "Player_6": "Rogers 8",
    "Player_3": "Gabriel 1",
    "Player_4": "Tarkowski 4",
    "Player_8": "Cherki 3",
    "Player_9": "Watkins 8",
    "Player_15": "Devenny 0"
  },
  {
    "manager_Name": "28( \u00A3100.2m )",
    "Teams": "WMB( Raj Kanango )",
    "SXL": "IND",
    "Latp": "68",
    "Player_1": "Donnarumma 8",
    "Player_11": "Haaland 2",
    "Player_10": "Bowen 12",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Senesi 3",
    "Player_14": "Dalot 1",
    "Player_7": "B.Fernandes 5",
    "Player_2": "Dorgu 8",
    "Player_5": "Wilson 10",
    "Player_6": "Rogers 8",
    "Player_3": "Chalobah 4",
    "Player_4": "J.Timber 1",
    "Player_8": "Semenyo 8",
    "Player_9": "Thiago 2",
    "Player_15": "Cullen 0"
  },
  {
    "manager_Name": "27( \u00A3102.0m )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "20",
    "Player_1": "Raya 1",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago 2",
    "Player_12": "Petrovi\u0107 1",
    "Player_13": "Cash 6",
    "Player_14": "L.Miley 2",
    "Player_7": "Saka 2",
    "Player_2": "Mukiele 4",
    "Player_5": "Mitchell 1",
    "Player_6": "Foden 1",
    "Player_3": "Thiaw 1",
    "Player_4": "Chalobah 4",
    "Player_8": "Rice 1",
    "Player_9": "Ekitik\u00E9 1",
    "Player_15": "Stach 8"
  },
  {
    "manager_Name": "26( \u00A398.1m )",
    "Teams": "DUFC( Nitesh Kumar Singh )",
    "SXL": "IND",
    "Latp": "36",
    "Player_1": "Pickford 3",
    "Player_11": "Woltemade 1",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 5",
    "Player_13": "Bruno G.",
    "Player_14": "Tavernier 0",
    "Player_7": "Garner 2",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Mitchell 1",
    "Player_6": "Mukiele 4",
    "Player_3": "Tarkowski 4",
    "Player_4": "Chalobah 4",
    "Player_8": "Foden 1",
    "Player_9": "Rogers 8",
    "Player_15": "Richarlison 0"
  }
];