var s = [
  {
    "manager_Name": "1,394( 1,122 )",
    "Teams": "cavac215( Ankit Chhetri )",
    "SXL": "IND",
    "Latp": "15",
    "Player_1": "Donnarumma 6",
    "Player_11": "Thiago NFO",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Garner LEE",
    "Player_14": "Calvert-Lewin EVE",
    "Player_7": "Rice MUN",
    "Player_2": "Chalobah CRY",
    "Player_5": "Tarkowski LEE",
    "Player_6": "Wirtz 1",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "J.Timber MUN",
    "Player_8": "B.Fernandes ARS",
    "Player_9": "Bruno G.",
    "Player_15": "Pau NEW"
  },
  {
    "manager_Name": "1,321( 64,143 )",
    "Teams": "False 9( Rohan Rai )",
    "SXL": "IND",
    "Latp": "7",
    "Player_1": "Kelleher NFO",
    "Player_11": "Thiago NFO",
    "Player_10": "Watkins NEW",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "L.Miley AVL",
    "Player_14": "Gudmundsson EVE",
    "Player_7": "Saka MUN",
    "Player_2": "Chalobah CRY",
    "Player_5": "Foden 1",
    "Player_6": "Rogers NEW",
    "Player_3": "Mukiele 4",
    "Player_4": "Gabriel MUN",
    "Player_8": "Enzo CRY",
    "Player_9": "Haaland 2",
    "Player_15": "Dalot ARS"
  },
  {
    "manager_Name": "1,314( 85,877 )",
    "Teams": "Kung fu Pandoos( Indrajeet Singh )",
    "SXL": "IND",
    "Latp": "10",
    "Player_1": "Kelleher NFO",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago NFO",
    "Player_12": "S\u00E1nchez CRY",
    "Player_13": "Matheus N.",
    "Player_14": "Dorgu ARS",
    "Player_7": "Palmer CRY",
    "Player_2": "Chalobah CRY",
    "Player_5": "Wilson 7",
    "Player_6": "Saka MUN",
    "Player_3": "Pedro Porro",
    "Player_4": "Thiaw AVL",
    "Player_8": "Mbeumo ARS",
    "Player_9": "Calvert-Lewin EVE",
    "Player_15": "Devenny CHE"
  },
  {
    "manager_Name": "1,311( 98,108 )",
    "Teams": "PWS( Z S )",
    "SXL": "IND",
    "Latp": "15",
    "Player_1": "Roefs 1",
    "Player_11": "Calvert-Lewin EVE",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Hall AVL",
    "Player_14": "Casemiro ARS",
    "Player_7": "Wirtz 1",
    "Player_2": "Van de",
    "Player_5": "Cherki 3",
    "Player_6": "Rice MUN",
    "Player_3": "Gabriel MUN",
    "Player_4": "J.Timber MUN",
    "Player_8": "Foden 1",
    "Player_9": "Ekitik\u00E9 0",
    "Player_15": "Dorgu ARS"
  },
  {
    "manager_Name": "1,283( 273,773 )",
    "Teams": "abcde FC( Prayash Thapa )",
    "SXL": "IND",
    "Latp": "30",
    "Player_1": "D\u00FAbravka 4",
    "Player_11": "Thiago NFO",
    "Player_10": "Haaland 2",
    "Player_12": "Roefs 1",
    "Player_13": "Andersen 7",
    "Player_14": "Truffert 1",
    "Player_7": "Saka MUN",
    "Player_2": "O\u0027Reilly 6",
    "Player_5": "Rogers NEW",
    "Player_6": "Wilson 7",
    "Player_3": "Virgil 1",
    "Player_4": "J.Timber MUN",
    "Player_8": "Foden 1",
    "Player_9": "Bowen 9",
    "Player_15": "Devenny CHE"
  },
  {
    "manager_Name": "1,278( 323,394 )",
    "Teams": "Alpha11( AVIJIT DAS )",
    "SXL": "IND",
    "Latp": "25",
    "Player_1": "D\u00FAbravka 4",
    "Player_11": "Thiago NFO",
    "Player_10": "Ekitik\u00E9 0",
    "Player_12": "Henderson CHE",
    "Player_13": "E.Le F\u00E9e",
    "Player_14": "Keane LEE",
    "Player_7": "Rogers NEW",
    "Player_2": "Mukiele 4",
    "Player_5": "Semenyo 16",
    "Player_6": "Saka MUN",
    "Player_3": "Chalobah CRY",
    "Player_4": "Gabriel MUN",
    "Player_8": "Enzo CRY",
    "Player_9": "Haaland 1",
    "Player_15": "Dorgu ARS"
  },
  {
    "manager_Name": "1,272( 386,838 )",
    "Teams": "11 n over( Ashish Rai )",
    "SXL": "IND",
    "Latp": "22",
    "Player_1": "Raya MUN",
    "Player_11": "Haaland 1",
    "Player_10": "Ekitik\u00E9 0",
    "Player_12": "Darlow EVE",
    "Player_13": "Alderete 1",
    "Player_14": "Dorgu ARS",
    "Player_7": "\u00D8degaard MUN",
    "Player_2": "Kerkez 1",
    "Player_5": "Ayari 9",
    "Player_6": "Cherki 3",
    "Player_3": "J.Timber MUN",
    "Player_4": "Matheus N.",
    "Player_8": "Palmer CRY",
    "Player_9": "Schade NFO",
    "Player_15": "Man\u00E9 2"
  },
  {
    "manager_Name": "1,270( 413,087 )",
    "Teams": "Top Gooner( VibhutiHang Subba )",
    "SXL": "IND",
    "Latp": "22",
    "Player_1": "Raya MUN",
    "Player_11": "Ekitik\u00E9 0",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Andersen 7",
    "Player_14": "Rodon EVE",
    "Player_7": "Rice MUN",
    "Player_2": "Gabriel MUN",
    "Player_5": "Foden 1",
    "Player_6": "Semenyo 8",
    "Player_3": "Chalobah CRY",
    "Player_4": "Mukiele 4",
    "Player_8": "Bruno G.",
    "Player_9": "Wilson 7",
    "Player_15": "Obi ARS"
  },
  {
    "manager_Name": "1,255( 629,665 )",
    "Teams": "MANCHESTER IS BLUE( PRAYAS BAJGAI )",
    "SXL": "IND",
    "Latp": "15",
    "Player_1": "A.Becker 1",
    "Player_11": "Ekitik\u00E9 0",
    "Player_10": "Cherki 3",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Haaland 1",
    "Player_14": "Foden 1",
    "Player_7": "Rogers NEW",
    "Player_2": "J.Timber MUN",
    "Player_5": "Mukiele 4",
    "Player_6": "Dorgu ARS",
    "Player_3": "Gabriel MUN",
    "Player_4": "Andersen 7",
    "Player_8": "Rice MUN",
    "Player_9": "Gordon AVL",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,237( 965,082 )",
    "Teams": "Blue Brigade( Bhuman Basnet )",
    "SXL": "IND",
    "Latp": "20",
    "Player_1": "Vicario 1",
    "Player_11": "Calvert-Lewin EVE",
    "Player_10": "Thiago NFO",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Foden 1",
    "Player_14": "Cash NEW",
    "Player_7": "Wilson 7",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Saka MUN",
    "Player_6": "Enzo CRY",
    "Player_3": "Frimpong 1",
    "Player_4": "Mukiele 4",
    "Player_8": "Bruno G.",
    "Player_9": "Haaland 1",
    "Player_15": "Keane LEE"
  },
  {
    "manager_Name": "1,234( 1,027,373 )",
    "Teams": "RIP-DIOGO.20( pranam rai )",
    "SXL": "IND",
    "Latp": "14",
    "Player_1": "Donnarumma 6",
    "Player_11": "Woltemade AVL",
    "Player_10": "Haaland 1",
    "Player_12": "Vicario 1",
    "Player_13": "Collins NFO",
    "Player_14": "Semenyo 8",
    "Player_7": "Wilson 7",
    "Player_2": "J.Timber MUN",
    "Player_5": "Rogers NEW",
    "Player_6": "Stach EVE",
    "Player_3": "Tarkowski LEE",
    "Player_4": "James CRY",
    "Player_8": "Saka MUN",
    "Player_9": "Calvert-Lewin EVE",
    "Player_15": "Dorgu ARS"
  },
  {
    "manager_Name": "1,230( 1,126,540 )",
    "Teams": "Lu Lu( Nishant Lohagun )",
    "SXL": "IND",
    "Latp": "19",
    "Player_1": "Raya MUN",
    "Player_11": "Welbeck 2",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Dorgu ARS",
    "Player_14": "Man\u00E9 2",
    "Player_7": "Anderson BRE",
    "Player_2": "Andersen 7",
    "Player_5": "Rogers NEW",
    "Player_6": "Semenyo 8",
    "Player_3": "Gabriel MUN",
    "Player_4": "Chalobah CRY",
    "Player_8": "Palmer CRY",
    "Player_9": "B.Fernandes ARS",
    "Player_15": "Senesi 1"
  },
  {
    "manager_Name": "1,227( 1,189,705 )",
    "Teams": "error404( Duri Tadu )",
    "SXL": "IND",
    "Latp": "17",
    "Player_1": "Raya MUN",
    "Player_11": "Ekitik\u00E9 0",
    "Player_10": "Thiago NFO",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Haaland 1",
    "Player_14": "Alderete 1",
    "Player_7": "Rice MUN",
    "Player_2": "Gabriel MUN",
    "Player_5": "Enzo CRY",
    "Player_6": "B.Fernandes ARS",
    "Player_3": "Andersen 7",
    "Player_4": "Virgil 1",
    "Player_8": "Wilson 7",
    "Player_9": "E.Le F\u00E9e",
    "Player_15": "Dalot ARS"
  },
  {
    "manager_Name": "1,226( 1,214,283 )",
    "Teams": "Cheesygarlic( Rishi Thulung )",
    "SXL": "IND",
    "Latp": "12",
    "Player_1": "S\u00E1nchez CRY",
    "Player_11": "Haaland 2",
    "Player_10": "Kroupi.Jr 1",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Thiago NFO",
    "Player_14": "Mukiele 4",
    "Player_7": "Wilson 7",
    "Player_2": "Virgil 1",
    "Player_5": "Gabriel MUN",
    "Player_6": "Foden 1",
    "Player_3": "Chalobah CRY",
    "Player_4": "Thiaw AVL",
    "Player_8": "Rice MUN",
    "Player_9": "Palmer CRY",
    "Player_15": "Xhaka 0"
  },
  {
    "manager_Name": "1,223( 1,301,521 )",
    "Teams": "Comet FC( Pranesh Sharma )",
    "SXL": "IND",
    "Latp": "15",
    "Player_1": "S\u00E1nchez CRY",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago NFO",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Andersen 7",
    "Player_14": "Devenny CHE",
    "Player_7": "Rogers NEW",
    "Player_2": "Gabriel MUN",
    "Player_5": "Wirtz 1",
    "Player_6": "Palmer CRY",
    "Player_3": "Frimpong 1",
    "Player_4": "Mukiele 4",
    "Player_8": "Wilson 7",
    "Player_9": "Ekitik\u00E9 0",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "1,222( 1,319,672 )",
    "Teams": "Bruno-nly Fans( Bejoy M Shrestha\u00B2\u2076\u2074 )",
    "SXL": "IND",
    "Latp": "4",
    "Player_1": "Raya MUN",
    "Player_11": "Thiago NFO",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "King 4",
    "Player_14": "Andersen 7",
    "Player_7": "Wirtz 1",
    "Player_2": "Tarkowski LEE",
    "Player_5": "B.Fernandes ARS",
    "Player_6": "Rogers NEW",
    "Player_3": "Gabriel MUN",
    "Player_4": "Collins NFO",
    "Player_8": "Foden 1",
    "Player_9": "Calvert-Lewin EVE",
    "Player_15": "Gudmundsson EVE"
  },
  {
    "manager_Name": "1,222( 1,321,646 )",
    "Teams": "Liverpool FC( Sunil Rai )",
    "SXL": "IND",
    "Latp": "17",
    "Player_1": "S\u00E1nchez CRY",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago NFO",
    "Player_12": "Raya MUN",
    "Player_13": "Foden 1",
    "Player_14": "Rodon EVE",
    "Player_7": "Wilson 7",
    "Player_2": "Gabriel MUN",
    "Player_5": "Bruno G.",
    "Player_6": "Enzo CRY",
    "Player_3": "Van de",
    "Player_4": "Chalobah CRY",
    "Player_8": "Minteh 1",
    "Player_9": "Calvert-Lewin EVE",
    "Player_15": "Senesi 1"
  },
  {
    "manager_Name": "1,216( 1,484,288 )",
    "Teams": "G\u00CBNJ\u00CF\u00CF UNITED( Pema Bhutia )",
    "SXL": "IND",
    "Latp": "10",
    "Player_1": "Raya MUN",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago NFO",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "L.Miley AVL",
    "Player_14": "Dorgu ARS",
    "Player_7": "B.Fernandes ARS",
    "Player_2": "Gabriel MUN",
    "Player_5": "Wilson 7",
    "Player_6": "Foden 1",
    "Player_3": "Thiaw AVL",
    "Player_4": "Tarkowski LEE",
    "Player_8": "Mbeumo ARS",
    "Player_9": "Calvert-Lewin EVE",
    "Player_15": "Senesi 1"
  },
  {
    "manager_Name": "1,204( 1,815,501 )",
    "Teams": "Fu\u00DFball-Mannschaft( Gaurav Shrestha )",
    "SXL": "IND",
    "Latp": "5",
    "Player_1": "Raya MUN",
    "Player_11": "Ekitik\u00E9 0",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Anderson BRE",
    "Player_14": "Marc Guiu",
    "Player_7": "Foden 1",
    "Player_2": "Virgil 1",
    "Player_5": "Alderete 1",
    "Player_6": "Saka MUN",
    "Player_3": "Thiaw AVL",
    "Player_4": "Chalobah CRY",
    "Player_8": "Bruno G.",
    "Player_9": "Enzo CRY",
    "Player_15": "Rodon EVE"
  },
  {
    "manager_Name": "1,202( 1,872,272 )",
    "Teams": "ASHLAD FC( Ashim Lama )",
    "SXL": "IND",
    "Latp": "19",
    "Player_1": "Roefs 1",
    "Player_11": "Thiago NFO",
    "Player_10": "Haaland 1",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Alderete 1",
    "Player_14": "Kroupi.Jr 1",
    "Player_7": "Rogers NEW",
    "Player_2": "Chalobah CRY",
    "Player_5": "Foden 1",
    "Player_6": "Semenyo 8",
    "Player_3": "J.Timber MUN",
    "Player_4": "Senesi 1",
    "Player_8": "Bruno G.",
    "Player_9": "Wilson 7",
    "Player_15": "Tarkowski LEE"
  },
  {
    "manager_Name": "1,200( 1,925,455 )",
    "Teams": "PINE( SATYAM RAI )",
    "SXL": "IND",
    "Latp": "13",
    "Player_1": "Raya MUN",
    "Player_11": "Haaland 1",
    "Player_10": "Ekitik\u00E9 0",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Stach EVE",
    "Player_14": "Dalot ARS",
    "Player_7": "Wilson 7",
    "Player_2": "Mukiele 4",
    "Player_5": "Saka MUN",
    "Player_6": "Enzo CRY",
    "Player_3": "Virgil 1",
    "Player_4": "J.Timber MUN",
    "Player_8": "Rogers NEW",
    "Player_9": "Calvert-Lewin EVE",
    "Player_15": "Rodon EVE"
  },
  {
    "manager_Name": "1,188( 2,310,314 )",
    "Teams": "F.C. ASSASSINS( Kushal Sahota )",
    "SXL": "IND",
    "Latp": "10",
    "Player_1": "S\u00E1nchez CRY",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago NFO",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Wilson 7",
    "Player_14": "Van de",
    "Player_7": "Bruno G.",
    "Player_2": "Thiaw AVL",
    "Player_5": "B.Fernandes ARS",
    "Player_6": "Saka MUN",
    "Player_3": "J.Timber MUN",
    "Player_4": "Matheus N.",
    "Player_8": "Rogers NEW",
    "Player_9": "Calvert-Lewin EVE",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "1,181( 2,554,452 )",
    "Teams": "\u0160e\u0161ko and Destroy( Pema Lepcha )",
    "SXL": "IND",
    "Latp": "24",
    "Player_1": "D\u00FAbravka 4",
    "Player_11": "Haaland 2",
    "Player_10": "Woltemade AVL",
    "Player_12": "Raya MUN",
    "Player_13": "Cherki 3",
    "Player_14": "Van Hecke",
    "Player_7": "Rice MUN",
    "Player_2": "Senesi 1",
    "Player_5": "Wilson 7",
    "Player_6": "Rogers NEW",
    "Player_3": "Virgil 1",
    "Player_4": "Lewis-Potter NFO",
    "Player_8": "Cunha ARS",
    "Player_9": "Bowen 9",
    "Player_15": "Gvardiol 0"
  },
  {
    "manager_Name": "1,178( 2,657,082 )",
    "Teams": "Busby Baby( Regean Lama )",
    "SXL": "IND",
    "Latp": "20",
    "Player_1": "S\u00E1nchez CRY",
    "Player_11": "Ekitik\u00E9 0",
    "Player_10": "Haaland 1",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Calvert-Lewin EVE",
    "Player_14": "Heaven ARS",
    "Player_7": "Szoboszlai 1",
    "Player_2": "Van de",
    "Player_5": "Saka MUN",
    "Player_6": "Foden 1",
    "Player_3": "Gabriel MUN",
    "Player_4": "Dorgu ARS",
    "Player_8": "Reijnders 3",
    "Player_9": "Wilson 7",
    "Player_15": "Senesi 1"
  },
  {
    "manager_Name": "1,166( 3,072,233 )",
    "Teams": "Imperial Blues( Saurabh Tamang )",
    "SXL": "IND",
    "Latp": "15",
    "Player_1": "S\u00E1nchez CRY",
    "Player_11": "Thiago NFO",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Mukiele 4",
    "Player_14": "Est\u00E8ve 3",
    "Player_7": "Wilson 7",
    "Player_2": "Chalobah CRY",
    "Player_5": "B.Fernandes ARS",
    "Player_6": "Bruno G.",
    "Player_3": "J.Timber MUN",
    "Player_4": "O\u0027Reilly 6",
    "Player_8": "Rogers NEW",
    "Player_9": "Saka MUN",
    "Player_15": "Foster 5"
  },
  {
    "manager_Name": "1,161( 3,250,585 )",
    "Teams": "Hooligans25( Pradhyumna Subba )",
    "SXL": "IND",
    "Latp": "14",
    "Player_1": "Raya MUN",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago NFO",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Reinildo -1",
    "Player_14": "Dorgu ARS",
    "Player_7": "Cherki 3",
    "Player_2": "Kerkez 1",
    "Player_5": "Neto CRY",
    "Player_6": "Wirtz 1",
    "Player_3": "Van de",
    "Player_4": "Konsa NEW",
    "Player_8": "Saka MUN",
    "Player_9": "Schade NFO",
    "Player_15": "Isidor 1"
  },
  {
    "manager_Name": "1,156( 3,433,992 )",
    "Teams": "GustavousGooner( Ashish Subba )",
    "SXL": "IND",
    "Latp": "17",
    "Player_1": "S\u00E1nchez CRY",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago NFO",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Ra\u00FAl 2",
    "Player_14": "Gudmundsson EVE",
    "Player_7": "Semenyo 8",
    "Player_2": "Chalobah CRY",
    "Player_5": "Bruno G.",
    "Player_6": "Saka MUN",
    "Player_3": "Van Hecke",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Rogers NEW",
    "Player_9": "Rice MUN",
    "Player_15": "Dalot ARS"
  },
  {
    "manager_Name": "1,142( 3,962,243 )",
    "Teams": "GUNNERS( Omkar Subba )",
    "SXL": "IND",
    "Latp": "18",
    "Player_1": "Pickford LEE",
    "Player_11": "Ekitik\u00E9 0",
    "Player_10": "Haaland 1",
    "Player_12": "Verbruggen 1",
    "Player_13": "Alderete 1",
    "Player_14": "Calvert-Lewin EVE",
    "Player_7": "Gravenberch 1",
    "Player_2": "Gabriel MUN",
    "Player_5": "Rice MUN",
    "Player_6": "Bruno G.",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Tarkowski LEE",
    "Player_8": "Semenyo 8",
    "Player_9": "Wirtz 2",
    "Player_15": "Keane LEE"
  },
  {
    "manager_Name": "1,141( 3,993,060 )",
    "Teams": "The Regista.( Passang T Sherpa )",
    "SXL": "IND",
    "Latp": "18",
    "Player_1": "Roefs 1",
    "Player_11": "Haaland 2",
    "Player_10": "Ekitik\u00E9 0",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Rogers NEW",
    "Player_14": "Mukiele 4",
    "Player_7": "Semenyo 8",
    "Player_2": "Tarkowski LEE",
    "Player_5": "Bruno G.",
    "Player_6": "Rice MUN",
    "Player_3": "James CRY",
    "Player_4": "Gabriel MUN",
    "Player_8": "Wilson 7",
    "Player_9": "Calvert-Lewin EVE",
    "Player_15": "Dalot ARS"
  },
  {
    "manager_Name": "1,133( 4,284,662 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "7",
    "Player_1": "Raya MUN",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago NFO",
    "Player_12": "Petrovi\u0107 1",
    "Player_13": "Cash NEW",
    "Player_14": "L.Miley AVL",
    "Player_7": "Saka MUN",
    "Player_2": "Mukiele 4",
    "Player_5": "Mitchell CHE",
    "Player_6": "Foden 1",
    "Player_3": "Thiaw AVL",
    "Player_4": "Chalobah CRY",
    "Player_8": "Rice MUN",
    "Player_9": "Ekitik\u00E9 0",
    "Player_15": "Stach EVE"
  },
  {
    "manager_Name": "1,127( 4,495,241 )",
    "Teams": "Native United( Monlom Rongong )",
    "SXL": "IND",
    "Latp": "12",
    "Player_1": "D\u00FAbravka 4",
    "Player_11": "Haaland 1",
    "Player_10": "Thiago NFO",
    "Player_12": "Raya MUN",
    "Player_13": "Woltemade AVL",
    "Player_14": "Senesi 1",
    "Player_7": "Mbeumo ARS",
    "Player_2": "Dorgu ARS",
    "Player_5": "Rogers NEW",
    "Player_6": "Wilson 7",
    "Player_3": "J.Timber MUN",
    "Player_4": "Chalobah CRY",
    "Player_8": "Rice MUN",
    "Player_9": "Garner LEE",
    "Player_15": "Rodon EVE"
  },
  {
    "manager_Name": "1,109( 5,160,876 )",
    "Teams": "Boehly Blues( Aditya Bhandari )",
    "SXL": "IND",
    "Latp": "13",
    "Player_1": "Petrovi\u0107 1",
    "Player_11": "Thiago NFO",
    "Player_10": "Ekitik\u00E9 0",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Haaland 1",
    "Player_14": "Bruno G.",
    "Player_7": "Wirtz 1",
    "Player_2": "Gabriel MUN",
    "Player_5": "Ballard 4",
    "Player_6": "Wilson 7",
    "Player_3": "Chalobah CRY",
    "Player_4": "J.Timber MUN",
    "Player_8": "Rogers NEW",
    "Player_9": "Rice MUN",
    "Player_15": "Gu\u00E9hi 6"
  },
  {
    "manager_Name": "1,107( 5,227,395 )",
    "Teams": "Let MEE COOK( \u00CFaraplang Pompyrthat )",
    "SXL": "IND",
    "Latp": "7",
    "Player_1": "Verbruggen 1",
    "Player_11": "Haaland 1",
    "Player_10": "Ekitik\u00E9 0",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Gordon AVL",
    "Player_14": "Est\u00E8ve 3",
    "Player_7": "Saka MUN",
    "Player_2": "J.Timber MUN",
    "Player_5": "Mukiele 4",
    "Player_6": "Xhaka 0",
    "Player_3": "Gabriel MUN",
    "Player_4": "Mykolenko LEE",
    "Player_8": "Foden 1",
    "Player_9": "Rogers NEW",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,086( 5,938,383 )",
    "Teams": "Hangkim_0011( ABHINANDAN RAI )",
    "SXL": "IND",
    "Latp": "5",
    "Player_1": "Pickford LEE",
    "Player_11": "Calvert-Lewin EVE",
    "Player_10": "Ekitik\u00E9 0",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Tarkowski LEE",
    "Player_14": "L.Paquet\u00E1 0",
    "Player_7": "Cherki 3",
    "Player_2": "Gabriel MUN",
    "Player_5": "Trossard MUN",
    "Player_6": "Rogers NEW",
    "Player_3": "Pedro Porro",
    "Player_4": "Konsa NEW",
    "Player_8": "Bruno G.",
    "Player_9": "Haaland 1",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "1,082( 6,066,798 )",
    "Teams": "GODFATHER FC( Riwaj Rai )",
    "SXL": "IND",
    "Latp": "26",
    "Player_1": "Pickford LEE",
    "Player_11": "Haaland 2",
    "Player_10": "Bowen 9",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Wilson 7",
    "Player_14": "Digne NEW",
    "Player_7": "Mbeumo ARS",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Tarkowski LEE",
    "Player_6": "Semenyo 8",
    "Player_3": "Cash NEW",
    "Player_4": "J.Timber MUN",
    "Player_8": "Gravenberch 1",
    "Player_9": "Garner LEE",
    "Player_15": "Isidor 1"
  },
  {
    "manager_Name": "1,056( 6,875,532 )",
    "Teams": "I_am_done_XI( Dipen Thapa )",
    "SXL": "IND",
    "Latp": "25",
    "Player_1": "Raya MUN",
    "Player_11": "Haaland 2",
    "Player_10": "Watkins NEW",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "Gravenberch 1",
    "Player_14": "Konsa NEW",
    "Player_7": "\u00D8degaard MUN",
    "Player_2": "Gabriel MUN",
    "Player_5": "Rogers NEW",
    "Player_6": "Cherki 3",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Van de",
    "Player_8": "Wilson 7",
    "Player_9": "Woltemade AVL",
    "Player_15": "Senesi 1"
  },
  {
    "manager_Name": "1,043( 7,245,295 )",
    "Teams": "Jorebungalow YFC( Vivek Lama )",
    "SXL": "IND",
    "Latp": "33",
    "Player_1": "Areola 2",
    "Player_11": "Watkins NEW",
    "Player_10": "Ekitik\u00E9 0",
    "Player_12": "D\u00FAbravka 4",
    "Player_13": "L.Miley AVL",
    "Player_14": "Thiaw AVL",
    "Player_7": "Semenyo 8",
    "Player_2": "Cash NEW",
    "Player_5": "Foden 1",
    "Player_6": "Rogers NEW",
    "Player_3": "Van de",
    "Player_4": "O\u0027Reilly 6",
    "Player_8": "Wilson 7",
    "Player_9": "Haaland 2",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "1,036( 7,435,986 )",
    "Teams": "Invincibles( Bishal Rai )",
    "SXL": "IND",
    "Latp": "15",
    "Player_1": "Raya MUN",
    "Player_11": "Thiago NFO",
    "Player_10": "Mateta CHE",
    "Player_12": "Kinsky 0",
    "Player_13": "Neto CRY",
    "Player_14": "Pedro Porro",
    "Player_7": "Foden 1",
    "Player_2": "J.Timber MUN",
    "Player_5": "Enzo CRY",
    "Player_6": "Bruno G.",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Gabriel MUN",
    "Player_8": "Semenyo 8",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Milenkovi\u0107 BRE"
  }
];