var s = [{
	"Teams": "beta 11",
	"Player_1": "McCarthy 0",
	"Player_2": "Alexander-Arnold 7",
	"Player_3": "Egan -2",
	"Player_4": "Doherty 0",
	"Player_5": "Aubameyang 10",
	"Player_6": "Salah 3",
	"Player_7": "Saint-Maximin 1",
	"Player_8": "Son 24",
	"Player_9": "Wilson 2",
	"Player_10": "Calvert-Lewin 17",
	"Player_11": "Mitrović 12",
	"Player_12": "Nyland 0",
	"Player_13": "Bernardo 0",
	"Player_14": "Douglas 0",
	"Player_15": "Stephens 0",
	"SXL": "74",
	"Bench": "0"
}, {
	"Teams": "FALSE 9",
	"Player_1": "Ryan 6",
	"Player_2": "Justin 7",
	"Player_3": "Coleman 1",
	"Player_4": "Holding 2",
	"Player_5": "Aubameyang 10",
	"Player_6": "Son 24",
	"Player_7": "Salah 3",
	"Player_8": "Saint-Maximin 1",
	"Player_9": "Barnes 13",
	"Player_10": "Werner 2",
	"Player_11": "Mitrović 12",
	"Player_12": "McCarthy 0",
	"Player_13": "Davis 1",
	"Player_14": "Saliba 0",
	"Player_15": "Bernardo 0",
	"SXL": "81",
	"Bench": "1"
}, {
	"Teams": "WeAreTheArsenal",
	"Player_1": "McCarthy 0",
	"Player_2": "Davies 1",
	"Player_3": "Egan -2",
	"Player_4": "Alexander-Arnold 7",
	"Player_5": "Saint-Maximin 1",
	"Player_6": "Aubameyang 10",
	"Player_7": "Salah 3",
	"Player_8": "Son 24",
	"Player_9": "Calvert-Lewin 17",
	"Player_10": "Werner 2",
	"Player_11": "Mitrović 12",
	"Player_12": "Button 0",
	"Player_13": "Bissouma 0",
	"Player_14": "Taylor 3",
	"Player_15": "Ferguson 0",
	"SXL": "75",
	"Bench": "3"
}, {
	"Teams": "Fußball-Mannschaft",
	"Player_1": "McCarthy 0",
	"Player_2": "Alexander-Arnold 7",
	"Player_3": "Dier 1",
	"Player_4": "Saïss 1",
	"Player_5": "Walker-Peters 3",
	"Player_6": "Salah 3",
	"Player_7": "Havertz 1",
	"Player_8": "Saint-Maximin 1",
	"Player_9": "Aubameyang 10",
	"Player_10": "Ings 11",
	"Player_11": "Werner 2",
	"Player_12": "Steer 0",
	"Player_13": "Bissouma 0",
	"Player_14": "Davis 1",
	"Player_15": "Ferguson 0",
	"SXL": "40",
	"Bench": "1"
}, {
	"Teams": "Lokipower Reloaded",
	"Player_1": "Leno 2",
	"Player_2": "Doherty 0",
	"Player_3": "Taylor 3",
	"Player_4": "Holding 2",
	"Player_5": "Lundstram -1",
	"Player_6": "Willian 2",
	"Player_7": "Son 24",
	"Player_8": "Salah 6",
	"Player_9": "Ings 11",
	"Player_10": "Richarlison 12",
	"Player_11": "Werner 2",
	"Player_12": "McCarthy 0",
	"Player_13": "Wan-Bissaka 0",
	"Player_14": "Bednarek 0",
	"Player_15": "Rice 2",
	"SXL": "63",
	"Bench": "2"
}, {
	"Teams": "FortunaDüsseldorfer",
	"Player_1": "Alisson 14",
	"Player_2": "Alexander-Arnold 7",
	"Player_3": "Keane 7",
	"Player_4": "Azpilicueta 0",
	"Player_5": "McCarthy 2",
	"Player_6": "Oriol Romeu 0",
	"Player_7": "Salah 3",
	"Player_8": "Zaha 15",
	"Player_9": "Aubameyang 10",
	"Player_10": "Antonio 6",
	"Player_11": "Bamford 14",
	"Player_12": "Button 0",
	"Player_13": "Tierney 0",
	"Player_14": "Alderweireld 0",
	"Player_15": "Davis 1",
	"SXL": "78",
	"Bench": "1"
}, {
	"Teams": "FC ASSASSINS",
	"Player_1": "Schmeichel 2",
	"Player_2": "van Dijk 7",
	"Player_3": "Stevens 2",
	"Player_4": "Lamptey 4",
	"Player_5": "Alioski 1",
	"Player_6": "Aubameyang 5",
	"Player_7": "Saint-Maximin 1",
	"Player_8": "Oriol Romeu 0",
	"Player_9": "Salah 6",
	"Player_10": "Ings 11",
	"Player_11": "Werner 2",
	"Player_12": "Ryan 6",
	"Player_13": "Pulisic 0",
	"Player_14": "Bernardo 0",
	"Player_15": "Brewster 0",
	"SXL": "41",
	"Bench": "6"
}, {
	"Teams": "PINE",
	"Player_1": "McCarthy 0",
	"Player_2": "Alexander-Arnold 7",
	"Player_3": "Justin 7",
	"Player_4": "Egan -2",
	"Player_5": "Salah 3",
	"Player_6": "Aubameyang 10",
	"Player_7": "Fernandes 2",
	"Player_8": "Bissouma 0",
	"Player_9": "Mitrović 12",
	"Player_10": "Vardy 2",
	"Player_11": "Wilson 2",
	"Player_12": "Steer 0",
	"Player_13": "Taylor 3",
	"Player_14": "Ferguson 0",
	"Player_15": "Gordon 0",
	"SXL": "43",
	"Bench": "3"
}, {
	"Teams": "⚔️FURY⚔️",
	"Player_1": "McCarthy 0",
	"Player_2": "Alexander-Arnold 7",
	"Player_3": "Justin 7",
	"Player_4": "James 1",
	"Player_5": "Walker-Peters 3",
	"Player_6": "Salah 3",
	"Player_7": "Aubameyang 10",
	"Player_8": "Saint-Maximin 1",
	"Player_9": "Werner 2",
	"Player_10": "Ings 11",
	"Player_11": "Mitrović 12",
	"Player_12": "Steer 0",
	"Player_13": "Alli 0",
	"Player_14": "Lemina 1",
	"Player_15": "Douglas 0",
	"SXL": "57",
	"Bench": "1"
}, {
	"Teams": "Kung fu Pandoos",
	"Player_1": "Pickford 1",
	"Player_2": "James 1",
	"Player_3": "Dier 1",
	"Player_4": "Holding 2",
	"Player_5": "Sterling 5",
	"Player_6": "Pereira 10",
	"Player_7": "Rodríguez 12",
	"Player_8": "Salah 3",
	"Player_9": "Jiménez 6",
	"Player_10": "Kane 42",
	"Player_11": "Bamford 14",
	"Player_12": "Meslier 2",
	"Player_13": "Wan-Bissaka 0",
	"Player_14": "Walker-Peters 3",
	"Player_15": "Reed 2",
	"SXL": "97",
	"Bench": "7"
}, {
	"Teams": "JOJOs LFC",
	"Player_1": "Alisson 14",
	"Player_2": "Alexander-Arnold 7",
	"Player_3": "Egan -2",
	"Player_4": "Walker-Peters 3",
	"Player_5": "Zaha 15",
	"Player_6": "Mané 16",
	"Player_7": "Aubameyang 5",
	"Player_8": "Lundstram -1",
	"Player_9": "Saint-Maximin 1",
	"Player_10": "Mitrović 12",
	"Player_11": "Martial 4",
	"Player_12": "Ryan 6",
	"Player_13": "Antonio 6",
	"Player_14": "Douglas 0",
	"Player_15": "Saïss 1",
	"SXL": "74",
	"Bench": "13"
}, {
	"Teams": "Random XI",
	"Player_1": "Schmeichel 2",
	"Player_2": "Baldock 2",
	"Player_3": "Söyüncü 1",
	"Player_4": "Lascelles 0",
	"Player_5": "Coleman 1",
	"Player_6": "Son 24",
	"Player_7": "Aubameyang 5",
	"Player_8": "Saint-Maximin 1",
	"Player_9": "Vardy 2",
	"Player_10": "Martial 4",
	"Player_11": "Werner 2",
	"Player_12": "McCarthy 0",
	"Player_13": "Saka 2",
	"Player_14": "Stephens 0",
	"Player_15": "Bernardo 0",
	"SXL": "44",
	"Bench": "2"
}, {
	"Teams": "Galaxies Stars",
	"Player_1": "Patrício 3",
	"Player_2": "Robertson 6",
	"Player_3": "Davies 1",
	"Player_4": "Koch 1",
	"Player_5": "Son 48",
	"Player_6": "Aubameyang 5",
	"Player_7": "Mount 2",
	"Player_8": "Salah 3",
	"Player_9": "Werner 2",
	"Player_10": "Davis 1",
	"Player_11": "Rodrigo 1",
	"Player_12": "Casilla 0",
	"Player_13": "Buur 0",
	"Player_14": "Oriol Romeu 0",
	"Player_15": "Thomas 0",
	"SXL": "73",
	"Bench": "0"
}, {
	"Teams": "Happy Williams",
	"Player_1": "McCarthy 0",
	"Player_2": "Dallas 1",
	"Player_3": "Lindelöf 1",
	"Player_4": "Davies 1",
	"Player_5": "Aubameyang 10",
	"Player_6": "Salah 3",
	"Player_7": "Greenwood 1",
	"Player_8": "Saint-Maximin 1",
	"Player_9": "Mitrović 12",
	"Player_10": "Jiménez 6",
	"Player_11": "Martial 2",
	"Player_12": "Johnstone 0",
	"Player_13": "Soucek 2",
	"Player_14": "Bednarek 0",
	"Player_15": "Mitchell 5",
	"SXL": "38",
	"Bench": "7"
}, {
	"Teams": "Omk09",
	"Player_1": "Leno 2",
	"Player_2": "Söyüncü 1",
	"Player_3": "Robertson 6",
	"Player_4": "Gabriel 2",
	"Player_5": "Højbjerg 2",
	"Player_6": "Salah 3",
	"Player_7": "Aubameyang 5",
	"Player_8": "Lundstram -1",
	"Player_9": "Fernandes 4",
	"Player_10": "Davis 1",
	"Player_11": "Vardy 2",
	"Player_12": "Nyland 0",
	"Player_13": "Vinagre 1",
	"Player_14": "Origi 0",
	"Player_15": "Branthwaite 0",
	"SXL": "27",
	"Bench": "1"
}, {
	"Teams": "Impact Creators",
	"Player_1": "McCarthy 0",
	"Player_2": "Alexander-Arnold 7",
	"Player_3": "Lascelles 0",
	"Player_4": "Egan -2",
	"Player_5": "Pereira 10",
	"Player_6": "Salah 3",
	"Player_7": "Aubameyang 10",
	"Player_8": "Son 24",
	"Player_9": "Adams 1",
	"Player_10": "Werner 2",
	"Player_11": "Mitrović 12",
	"Player_12": "Martin 0",
	"Player_13": "Taylor 3",
	"Player_14": "Douglas 0",
	"Player_15": "Stephens 0",
	"SXL": "67",
	"Bench": "3"
}, {
	"Teams": "GUSTAVOUS GUNNER",
	"Player_1": "Ramsdale 2",
	"Player_2": "Alexander-Arnold 7",
	"Player_3": "Egan -2",
	"Player_4": "Lascelles 0",
	"Player_5": "Justin 7",
	"Player_6": "Saint-Maximin 1",
	"Player_7": "Salah 3",
	"Player_8": "Aubameyang 10",
	"Player_9": "Son 24",
	"Player_10": "Antonio 6",
	"Player_11": "Martial 2",
	"Player_12": "Martin 0",
	"Player_13": "Dendoncker 1",
	"Player_14": "Davis 1",
	"Player_15": "Vinagre 1",
	"SXL": "60",
	"Bench": "3"
}, {
	"Teams": "Danapur United",
	"Player_1": "Alisson 14",
	"Player_2": "Stevens 2",
	"Player_3": "van Dijk 7",
	"Player_4": "Söyüncü 1",
	"Player_5": "Egan -2",
	"Player_6": "Rodríguez 12",
	"Player_7": "Mount 2",
	"Player_8": "Salah 3",
	"Player_9": "Lundstram -1",
	"Player_10": "Ings 11",
	"Player_11": "Kane 42",
	"Player_12": "Button 0",
	"Player_13": "Fabio Silva 1",
	"Player_14": "Jota 0",
	"Player_15": "Carter-Vickers 0",
	"SXL": "91",
	"Bench": "1"
}, {
	"Teams": "66866",
	"Player_1": "Pope 1",
	"Player_2": "Alexander-Arnold 7",
	"Player_3": "Justin 7",
	"Player_4": "Walker 2",
	"Player_5": "Saint-Maximin 1",
	"Player_6": "Havertz 1",
	"Player_7": "Mané 16",
	"Player_8": "De Bruyne 26",
	"Player_9": "Mitrović 12",
	"Player_10": "Wilson 2",
	"Player_11": "Martial 2",
	"Player_12": "Johnstone 0",
	"Player_13": "Bardsley -1",
	"Player_14": "Oriol Romeu 0",
	"Player_15": "Branthwaite 0",
	"SXL": "77",
	"Bench": "-1"
}, {
	"Teams": "Marx 11",
	"Player_1": "Martínez 13",
	"Player_2": "Alexander-Arnold 7",
	"Player_3": "Doherty 0",
	"Player_4": "Bertrand -1",
	"Player_5": "Rice 2",
	"Player_6": "Traoré 2",
	"Player_7": "De Bruyne 13",
	"Player_8": "Aubameyang 10",
	"Player_9": "Henderson 1",
	"Player_10": "Werner 2",
	"Player_11": "Long 1",
	"Player_12": "Pope 1",
	"Player_13": "Chilwell 0",
	"Player_14": "Wan-Bissaka 0",
	"Player_15": "Muto 0",
	"SXL": "50",
	"Bench": "1"
}, {
	"Teams": "CottonMouth XI",
	"Player_1": "Schmeichel 2",
	"Player_2": "Doherty 0",
	"Player_3": "Mitchell 5",
	"Player_4": "Azpilicueta 0",
	"Player_5": "Ceballos 8",
	"Player_6": "Aubameyang 10",
	"Player_7": "Son 24",
	"Player_8": "Lundstram -1",
	"Player_9": "Mitrović 12",
	"Player_10": "Jiménez 6",
	"Player_11": "Werner 2",
	"Player_12": "Button 0",
	"Player_13": "Pulisic 0",
	"Player_14": "Douglas 0",
	"Player_15": "Gomez 0",
	"SXL": "68",
	"Bench": "0"
}, {
	"Teams": "SYAKREE F.C.",
	"Player_1": "McCarthy 0",
	"Player_2": "Castagne 9",
	"Player_3": "James 1",
	"Player_4": "Alexander-Arnold 7",
	"Player_5": "Saint-Maximin 1",
	"Player_6": "Son 24",
	"Player_7": "Aubameyang 10",
	"Player_8": "Salah 3",
	"Player_9": "Mitrović 12",
	"Player_10": "Rodrigo 1",
	"Player_11": "Werner 2",
	"Player_12": "Nyland 0",
	"Player_13": "Douglas 0",
	"Player_14": "Soucek 2",
	"Player_15": "Vinagre 1",
	"SXL": "70",
	"Bench": "3"
}, {
	"Teams": "Busby Baby",
	"Player_1": "McCarthy 0",
	"Player_2": "Justin 7",
	"Player_3": "Alexander-Arnold 7",
	"Player_4": "Walker-Peters 3",
	"Player_5": "Salah 3",
	"Player_6": "Mané 16",
	"Player_7": "Saint-Maximin 1",
	"Player_8": "Aubameyang 10",
	"Player_9": "Soucek 2",
	"Player_10": "Mitrović 12",
	"Player_11": "Martial 2",
	"Player_12": "Steer 0",
	"Player_13": "Taylor 3",
	"Player_14": "Davis 1",
	"Player_15": "Douglas 0",
	"SXL": "63",
	"Bench": "4"
}, {
	"Teams": "hansing",
	"Player_1": "McCarthy 0",
	"Player_2": "Lewis 0",
	"Player_3": "Doherty 0",
	"Player_4": "Justin 7",
	"Player_5": "Hendrick 2",
	"Player_6": "Son 24",
	"Player_7": "Aubameyang 5",
	"Player_8": "Barnes 13",
	"Player_9": "Vardy 2",
	"Player_10": "Ings 11",
	"Player_11": "Martial 4",
	"Player_12": "Nyland 0",
	"Player_13": "Alexander-Arnold 7",
	"Player_14": "Mitchell 5",
	"Player_15": "Bissouma 0",
	"SXL": "68",
	"Bench": "12"
}, {
	"Teams": "mendal11",
	"Player_1": "Ramsdale 2",
	"Player_2": "Alexander-Arnold 7",
	"Player_3": "Mitchell 5",
	"Player_4": "Walker-Peters 3",
	"Player_5": "Mina 1",
	"Player_6": "Aubameyang 10",
	"Player_7": "Havertz 1",
	"Player_8": "Salah 3",
	"Player_9": "Saint-Maximin 1",
	"Player_10": "Werner 2",
	"Player_11": "Wilson 2",
	"Player_12": "Rodák 0",
	"Player_13": "Taylor 3",
	"Player_14": "Saka 2",
	"Player_15": "Brewster 0",
	"SXL": "37",
	"Bench": "5"
}, {
	"Teams": "goooooooners",
	"Player_1": "Ryan 6",
	"Player_2": "Dallas 1",
	"Player_3": "Lascelles 0",
	"Player_4": "Coady 1",
	"Player_5": "Saint-Maximin 1",
	"Player_6": "Salah 3",
	"Player_7": "Aubameyang 10",
	"Player_8": "De Bruyne 13",
	"Player_9": "Wood 6",
	"Player_10": "Ayew 5",
	"Player_11": "Kane 21",
	"Player_12": "Nyland 0",
	"Player_13": "Oriol Romeu 0",
	"Player_14": "Bednarek 0",
	"Player_15": "Branthwaite 0",
	"SXL": "67",
	"Bench": "0"
}, {
	"Teams": "Jatt Da Muqaabla FC",
	"Player_1": "Ramsdale 2",
	"Player_2": "Alexander-Arnold 7",
	"Player_3": "Mitchell 5",
	"Player_4": "Justin 7",
	"Player_5": "Saint-Maximin 1",
	"Player_6": "Aubameyang 10",
	"Player_7": "Son 24",
	"Player_8": "Salah 3",
	"Player_9": "Wood 6",
	"Player_10": "Maupay 16",
	"Player_11": "Kane 21",
	"Player_12": "Steer 0",
	"Player_13": "Walker-Peters 3",
	"Player_14": "Douglas 0",
	"Player_15": "Reed 2",
	"SXL": "102",
	"Bench": "5"
}, {
	"Teams": "Gooner for Life",
	"Player_1": "McCarthy 0",
	"Player_2": "Alexander-Arnold 7",
	"Player_3": "van Dijk 7",
	"Player_4": "Walker-Peters 3",
	"Player_5": "Alzate 3",
	"Player_6": "Aubameyang 10",
	"Player_7": "Salah 3",
	"Player_8": "Rodríguez 12",
	"Player_9": "Ward-Prowse 2",
	"Player_10": "Werner 2",
	"Player_11": "Mitrović 12",
	"Player_12": "Nyland 0",
	"Player_13": "Tierney 0",
	"Player_14": "Bernardo 0",
	"Player_15": "Davis 1",
	"SXL": "61",
	"Bench": "1"
}]