var s = [
  {
    "manager_Name": "754( 31,209 ) TotalXfr : 7",
    "Teams": "Lorrainesson( Lorraine Busuttil )",
    "SXL": "Malta",
    "Latp": "45",
    "Player_1": "Sels\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Strand Larsen\r 5",
    "Player_12": "Lumley\r 0",
    "Player_13": "Davis\r MUN (H)",
    "Player_14": "Dibling\r 2",
    "Player_7": "Palmer\r 2",
    "Player_2": "Mykolenko\r 6",
    "Player_5": "Semenyo\r 1",
    "Player_6": "Mbeumo\r 3",
    "Player_3": "Gabriel\r 6",
    "Player_4": "A\u00EFt-Nouri\r 2",
    "Player_8": "M.Salah\r 14",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Okoli\r 1"
  },
  {
    "manager_Name": "750( 42,235 ) TotalXfr : 12",
    "Teams": "FC Pek( Erik Lindberg )",
    "SXL": "Sweden",
    "Latp": "43",
    "Player_1": "Henderson\r 7",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wissa\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "A\u00EFt-Nouri\r 2",
    "Player_14": "Faes\r 0",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Gvardiol\r 0",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "M.Salah\r 14",
    "Player_3": "Digne\r 1",
    "Player_4": "Gabriel\r 6",
    "Player_8": "Rogers\r 2",
    "Player_9": "Solanke\r 5",
    "Player_15": "Winks\r 1"
  },
  {
    "manager_Name": "724( 176,322 ) TotalXfr : 11",
    "Teams": "The Bees( Tove Ronneb\u00E4ck )",
    "SXL": "Malta",
    "Latp": "51",
    "Player_1": "Raya\r 6",
    "Player_11": "Isak\r WHU (H)",
    "Player_10": "Wissa\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Smith Rowe\r 1",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Konat\u00E9\r 0",
    "Player_5": "Palmer\r 2",
    "Player_6": "Rogers\r 2",
    "Player_3": "Gvardiol\r 0",
    "Player_4": "Gabriel\r 6",
    "Player_8": "M.Salah\r 14",
    "Player_9": "Cunha\r 16",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "709( 348,342 ) TotalXfr : 10",
    "Teams": "NoHopeFC( John Maguire )",
    "SXL": "Malta",
    "Latp": "34",
    "Player_1": "Flekken\r 9",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Haaland\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Davis\r MUN (H)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Palmer\r 2",
    "Player_2": "Robinson\r 0",
    "Player_5": "Mbeumo\r 3",
    "Player_6": "M.Salah\r 14",
    "Player_3": "Konat\u00E9\r 0",
    "Player_4": "Digne\r 1",
    "Player_8": "B.Fernandes\r IPS (A)",
    "Player_9": "Winks\r 1",
    "Player_15": "Marc Guiu\r 0"
  },
  {
    "manager_Name": "706( 395,403 ) TotalXfr : 10",
    "Teams": "Los Blancos( Eamonn Mifsud )",
    "SXL": "Malta",
    "Latp": "63",
    "Player_1": "Raya\r 6",
    "Player_11": "Cunha\r 16",
    "Player_10": "Isak\r WHU (H)",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "Ra\u00FAl\r 2",
    "Player_14": "Lewis\r 0",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "A\u00EFt-Nouri\r 2",
    "Player_5": "Rogers\r 2",
    "Player_6": "M.Salah\r 14",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Van den Berg\r 6",
    "Player_8": "Son\r 6",
    "Player_9": "Palmer\r 2",
    "Player_15": "Konsa\r 0"
  },
  {
    "manager_Name": "705( 412,105 ) TotalXfr : 10",
    "Teams": "Fantasikonungen( Albin Jonsson )",
    "SXL": "Malta",
    "Latp": "53",
    "Player_1": "Jos\u00E9 S\u00E1\r 2",
    "Player_11": "N.Jackson\r 12",
    "Player_10": "Jo\u00E3o Pedro\r 12",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "Hall\r WHU (H)",
    "Player_14": "A\u00EFt-Nouri\r 2",
    "Player_7": "Palmer\r 2",
    "Player_2": "Konat\u00E9\r 0",
    "Player_5": "Mbeumo\r 3",
    "Player_6": "Semenyo\r 1",
    "Player_3": "Digne\r 1",
    "Player_4": "Gabriel\r 6",
    "Player_8": "B.Fernandes\r IPS (A)",
    "Player_9": "M.Salah\r 14",
    "Player_15": "Delap\r MUN (H)"
  },
  {
    "manager_Name": "701( 480,331 ) TotalXfr : 8",
    "Teams": "Lallish United( Melwin Holst )",
    "SXL": "Sweden",
    "Latp": "57",
    "Player_1": "Raya\r 6",
    "Player_11": "H\u00F8jlund\r IPS (A)",
    "Player_10": "Cunha\r 16",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "Welbeck\r 2",
    "Player_14": "Van den Berg\r 6",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "A\u00EFt-Nouri\r 2",
    "Player_5": "Son\r 6",
    "Player_6": "Rogers\r 2",
    "Player_3": "Dalot\r IPS (A)",
    "Player_4": "Gabriel\r 6",
    "Player_8": "M.Salah\r 14",
    "Player_9": "Palmer\r 2",
    "Player_15": "Davis\r MUN (H)"
  },
  {
    "manager_Name": "696( 586,959 ) TotalXfr : 10",
    "Teams": "Udogie\u0027s Doggies( Claude Taliana )",
    "SXL": "Malta",
    "Latp": "49",
    "Player_1": "Flekken\r 9",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 1",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "Strand Larsen\r 5",
    "Player_14": "Aina\r 0",
    "Player_7": "Georginio\r 5",
    "Player_2": "Robinson\r 0",
    "Player_5": "M.Salah\r 14",
    "Player_6": "Palmer\r 2",
    "Player_3": "Pedro Porro\r 14",
    "Player_4": "Dalot\r IPS (A)",
    "Player_8": "Rogers\r 2",
    "Player_9": "Barnes\r WHU (H)",
    "Player_15": "Lewis\r 0"
  },
  {
    "manager_Name": "685( 877,256 ) TotalXfr : 12",
    "Teams": "Guglielmo( Jonas Megert )",
    "SXL": "Sweden",
    "Latp": "40",
    "Player_1": "Martinez\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Wood\r 1",
    "Player_12": "Turner\r 0",
    "Player_13": "Winks\r 1",
    "Player_14": "Konsa\r 0",
    "Player_7": "M.Salah\r 7",
    "Player_2": "Pedro Porro\r 14",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "Son\r 6",
    "Player_3": "Quansah\r 0",
    "Player_4": "Lewis\r 0",
    "Player_8": "Mbeumo\r 3",
    "Player_9": "Evanilson\r 2",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "683( 936,676 ) TotalXfr : 12",
    "Teams": "ThereWeLand( Haykel Mansour )",
    "SXL": "Malta",
    "Latp": "39",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Cunha\r 16",
    "Player_10": "Isak\r WHU (H)",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Kulusevski\r 6",
    "Player_14": "Lewis\r 0",
    "Player_7": "Smith Rowe\r 1",
    "Player_2": "Gabriel\r 6",
    "Player_5": "Mbeumo\r 3",
    "Player_6": "Palmer\r 4",
    "Player_3": "Collins\r 6",
    "Player_4": "Konsa\r 0",
    "Player_8": "Rashford\r IPS (A)",
    "Player_9": "Haaland\r 2",
    "Player_15": "Nedeljkovic\r 0"
  },
  {
    "manager_Name": "680( 1,030,270 ) TotalXfr : 12",
    "Teams": "Salahvation Army( Tom Atkinson )",
    "SXL": "Malta",
    "Latp": "44",
    "Player_1": "Pope\r WHU (H)",
    "Player_11": "Isak\r WHU (H)",
    "Player_10": "Haaland\r 2",
    "Player_12": "Slicker\r MUN (H)",
    "Player_13": "Lewis\r 0",
    "Player_14": "Winks\r 1",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Gvardiol\r 0",
    "Player_5": "Rogers\r 2",
    "Player_6": "Mitoma\r 9",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Collins\r 6",
    "Player_8": "M.Salah\r 14",
    "Player_9": "Calvert-Lewin\r 2",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "678( 1,083,105 ) TotalXfr : 10",
    "Teams": "MainooInTheBank( Thanasis Fouras )",
    "SXL": "Greece",
    "Latp": "39",
    "Player_1": "Henderson\r 7",
    "Player_11": "Solanke\r 5",
    "Player_10": "Haaland\r 2",
    "Player_12": "Matthews\r 0",
    "Player_13": "Faes\r 0",
    "Player_14": "Winks\r 1",
    "Player_7": "Johnson\r 6",
    "Player_2": "Digne\r 1",
    "Player_5": "Gordon\r WHU (H)",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "A\u00EFt-Nouri\r 2",
    "Player_4": "Robinson\r 0",
    "Player_8": "M.Salah\r 14",
    "Player_9": "Wood\r 1",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "675( 1,185,703 ) TotalXfr : 10",
    "Teams": "klopp notch( Tobias Nocke )",
    "SXL": "Sweden",
    "Latp": "41",
    "Player_1": "Kelleher\r 7",
    "Player_11": "Isak\r WHU (H)",
    "Player_10": "Solanke\r 5",
    "Player_12": "Verbruggen\r 3",
    "Player_13": "Ayari\r 3",
    "Player_14": "Van den Berg\r 6",
    "Player_7": "\u00D8degaard\r 6",
    "Player_2": "Konat\u00E9\r 0",
    "Player_5": "Palmer\r 2",
    "Player_6": "Foden\r 2",
    "Player_3": "Estupi\u00F1an\r 2",
    "Player_4": "Digne\r 1",
    "Player_8": "M.Salah\r 14",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "675( 1,192,851 ) TotalXfr : 11",
    "Teams": "Crvena Zvezda( Dejan Mrdanov )",
    "SXL": "Malta",
    "Latp": "48",
    "Player_1": "Raya\r 6",
    "Player_11": "Isak\r WHU (H)",
    "Player_10": "Wood\r 1",
    "Player_12": "Areola\r NEW (A)",
    "Player_13": "Hudson-Odoi\r 2",
    "Player_14": "Colwill\r 2",
    "Player_7": "Garnacho\r IPS (A)",
    "Player_2": "Tarkowski\r 7",
    "Player_5": "Mbeumo\r 3",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Digne\r 1",
    "Player_4": "Gabriel\r 6",
    "Player_8": "M.Salah\r 7",
    "Player_9": "Cunha\r 16",
    "Player_15": "Pedro Porro\r 14"
  },
  {
    "manager_Name": "675( 1,202,235 ) TotalXfr : 13",
    "Teams": "Ajax CT( Dimitrios Siderakis )",
    "SXL": "Malta",
    "Latp": "63",
    "Player_1": "Sels\r 2",
    "Player_11": "N.Jackson\r 12",
    "Player_10": "Watkins\r 7",
    "Player_12": "S\u00E1nchez\r 1",
    "Player_13": "Carvalho\r 0",
    "Player_14": "Welbeck\r 2",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Gu\u00E9hi\r 1",
    "Player_5": "Pedro Porro\r 14",
    "Player_6": "Mbeumo\r 3",
    "Player_3": "Mazraoui\r IPS (A)",
    "Player_4": "Saliba\r 7",
    "Player_8": "Palmer\r 2",
    "Player_9": "M.Salah\r 14",
    "Player_15": "Murillo\r 1"
  },
  {
    "manager_Name": "672( 1,293,617 ) TotalXfr : 10",
    "Teams": "Gambit( Nicola Frasca )",
    "SXL": "Malta",
    "Latp": "48",
    "Player_1": "Pickford\r 6",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "Greaves\r MUN (H)",
    "Player_14": "Winks\r 1",
    "Player_7": "Yarmoliuk\r 1",
    "Player_2": "Gvardiol\r 0",
    "Player_5": "Pedro Porro\r 14",
    "Player_6": "Palmer\r 2",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Martinez\r IPS (A)",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "M.Salah\r 14",
    "Player_15": "Ings\r NEW (A)"
  },
  {
    "manager_Name": "670( 1,361,836 ) TotalXfr : 8",
    "Teams": "JDT Out( Filip Larsson )",
    "SXL": "Malta",
    "Latp": "39",
    "Player_1": "Flekken\r 9",
    "Player_11": "Wood\r 1",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "Semenyo\r 1",
    "Player_14": "Aina\r 0",
    "Player_7": "Rogers\r 2",
    "Player_2": "Lewis\r 0",
    "Player_5": "Mbeumo\r 3",
    "Player_6": "B.Fernandes\r IPS (A)",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Konat\u00E9\r 0",
    "Player_8": "M.Salah\r 14",
    "Player_9": "Haaland\r 2",
    "Player_15": "Greaves\r MUN (H)"
  },
  {
    "manager_Name": "670( 1,382,629 ) TotalXfr : 12",
    "Teams": "Starship( Olumide Okedusi )",
    "SXL": "Estonia",
    "Latp": "33",
    "Player_1": "Raya\r 6",
    "Player_11": "Haaland\r 4",
    "Player_10": "N.Jackson\r 12",
    "Player_12": "Turner\r 0",
    "Player_13": "Pedro Porro\r 14",
    "Player_14": "Kova\u010Di\u0107\r 0",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Virgil\r 1",
    "Player_5": "Adama\r 1",
    "Player_6": "Palmer\r 2",
    "Player_3": "Robinson\r 0",
    "Player_4": "A\u00EFt-Nouri\r 2",
    "Player_8": "Rogers\r 2",
    "Player_9": "Isak\r WHU (H)",
    "Player_15": "Burn\r WHU (H)"
  },
  {
    "manager_Name": "669( 1,421,314 ) TotalXfr : 12",
    "Teams": "Gidia KK( Aggelos Flamiatos )",
    "SXL": "Greece",
    "Latp": "34",
    "Player_1": "Flekken\r 9",
    "Player_11": "Haaland\r 2",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Verbruggen\r 3",
    "Player_13": "McNeil\r 3",
    "Player_14": "Murillo\r 1",
    "Player_7": "M.Salah\r 14",
    "Player_2": "Robinson\r 0",
    "Player_5": "Mazraoui\r IPS (A)",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Burn\r WHU (H)",
    "Player_4": "Virgil\r 1",
    "Player_8": "Mbeumo\r 3",
    "Player_9": "Rogers\r 2",
    "Player_15": "Solanke\r 5"
  },
  {
    "manager_Name": "665( 1,562,082 ) TotalXfr : 9",
    "Teams": "Kinder Mbeumo( Gerson Seguna )",
    "SXL": "Malta",
    "Latp": "44",
    "Player_1": "Raya\r 6",
    "Player_11": "Wissa\r 2",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "Harwood-Bellis\r 1",
    "Player_14": "Rogers\r 2",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Alexander-Arnold\r 0",
    "Player_5": "Palmer\r 2",
    "Player_6": "Saka\r 13",
    "Player_3": "Konsa\r 0",
    "Player_4": "Robinson\r 0",
    "Player_8": "M.Salah\r 14",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Andersen\r 0"
  },
  {
    "manager_Name": "663( 1,649,872 ) TotalXfr : 10",
    "Teams": "Blue Core( Avinash Chatlani )",
    "SXL": "Malta",
    "Latp": "45",
    "Player_1": "Sels\r 2",
    "Player_11": "N.Jackson\r 12",
    "Player_10": "Delap\r MUN (H)",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "Winks\r 1",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "M.Salah\r 7",
    "Player_2": "Lewis\r 0",
    "Player_5": "Palmer\r 2",
    "Player_6": "Mbeumo\r 3",
    "Player_3": "Pedro Porro\r 14",
    "Player_4": "Aina\r 0",
    "Player_8": "Adama\r 1",
    "Player_9": "Haaland\r 4",
    "Player_15": "Vestergaard\r 0"
  },
  {
    "manager_Name": "660( 1,801,533 ) TotalXfr : 14",
    "Teams": "Biancoverde Utd 4.0( Michael Keramas )",
    "SXL": "Greece",
    "Latp": "38",
    "Player_1": "Flekken\r 9",
    "Player_11": "Ra\u00FAl\r 2",
    "Player_10": "Isak\r WHU (H)",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Welbeck\r 2",
    "Player_14": "Aina\r 0",
    "Player_7": "M.Salah\r 14",
    "Player_2": "Gvardiol\r 0",
    "Player_5": "B.Fernandes\r IPS (A)",
    "Player_6": "Palmer\r 2",
    "Player_3": "A\u00EFt-Nouri\r 2",
    "Player_4": "Robinson\r 0",
    "Player_8": "Kulusevski\r 6",
    "Player_9": "Mbeumo\r 3",
    "Player_15": "Johnson\r MUN (H)"
  },
  {
    "manager_Name": "658( 1,876,841 ) TotalXfr : 11",
    "Teams": "Tourinho FC( Alexis Touris )",
    "SXL": "Greece",
    "Latp": "33",
    "Player_1": "Martinez\r 2",
    "Player_11": "Isak\r WHU (H)",
    "Player_10": "Watkins\r 7",
    "Player_12": "Henderson\r 7",
    "Player_13": "Adama\r 1",
    "Player_14": "Pedro Porro\r 14",
    "Player_7": "Bowen\r NEW (A)",
    "Player_2": "Dalot\r IPS (A)",
    "Player_5": "Johnson\r 6",
    "Player_6": "M.Salah\r 14",
    "Player_3": "Andersen\r 0",
    "Player_4": "Gvardiol\r 0",
    "Player_8": "Mbeumo\r 3",
    "Player_9": "Wood\r 1",
    "Player_15": "Burn\r WHU (H)"
  },
  {
    "manager_Name": "656( 1,979,210 ) TotalXfr : 13",
    "Teams": "Im Sorry Nic Jackson( Jon Briscoe White )",
    "SXL": "Malta",
    "Latp": "54",
    "Player_1": "Henderson\r 7",
    "Player_11": "N.Jackson\r 12",
    "Player_10": "Solanke\r 5",
    "Player_12": "Turner\r 0",
    "Player_13": "Wood\r 1",
    "Player_14": "Vestergaard\r 0",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Dalot\r IPS (A)",
    "Player_5": "Rogers\r 2",
    "Player_6": "Palmer\r 2",
    "Player_3": "Gabriel\r 6",
    "Player_4": "A\u00EFt-Nouri\r 2",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "M.Salah\r 14",
    "Player_15": "Pedro Porro\r 14"
  },
  {
    "manager_Name": "655( 1,995,975 ) TotalXfr : 7",
    "Teams": "BienRayados( Luis Ricardo J\u00E1uregui V )",
    "SXL": "England",
    "Latp": "31",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Ra\u00FAl\r 2",
    "Player_10": "Duran\r 1",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "J.Araujo\r 0",
    "Player_14": "Pau\r 1",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Stones\r 0",
    "Player_5": "Madueke\r 3",
    "Player_6": "M.Salah\r 14",
    "Player_3": "Virgil\r 1",
    "Player_4": "Gabriel\r 6",
    "Player_8": "Kova\u010Di\u0107\r 0",
    "Player_9": "Palmer\r 2",
    "Player_15": "Havertz\r 0"
  },
  {
    "manager_Name": "654( 2,052,524 ) TotalXfr : 10",
    "Teams": "Joga Bonito( Christophe Peixoto )",
    "SXL": "Hungary",
    "Latp": "44",
    "Player_1": "Flekken\r 9",
    "Player_11": "Solanke\r 5",
    "Player_10": "Isak\r WHU (H)",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "Semenyo\r 1",
    "Player_14": "Pedro Porro\r 14",
    "Player_7": "M.Salah\r 14",
    "Player_2": "Hall\r WHU (H)",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "Palmer\r 2",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Colwill\r 2",
    "Player_8": "Mbeumo\r 3",
    "Player_9": "Calvert-Lewin\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "651( 2,195,459 ) TotalXfr : 10",
    "Teams": "Hakuna Mateta( Jason Evans )",
    "SXL": "Malta",
    "Latp": "54",
    "Player_1": "Martinez\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 12",
    "Player_10": "N.Jackson\r 12",
    "Player_12": "Turner\r 0",
    "Player_13": "Carvalho\r 0",
    "Player_14": "Barco\r 0",
    "Player_7": "M.Salah\r 14",
    "Player_2": "Alexander-Arnold\r 0",
    "Player_5": "Mitoma\r 9",
    "Player_6": "Rogers\r 2",
    "Player_3": "Gvardiol\r 0",
    "Player_4": "Romero\r 0",
    "Player_8": "Semenyo\r 1",
    "Player_9": "Haaland\r 2",
    "Player_15": "Thomas\r 0"
  },
  {
    "manager_Name": "650( 2,230,881 ) TotalXfr : 5",
    "Teams": "Nachos( Melvin Xuereb )",
    "SXL": "Malta",
    "Latp": "32",
    "Player_1": "Areola\r NEW (A)",
    "Player_11": "Haaland\r 2",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "Semenyo\r 1",
    "Player_14": "Estupi\u00F1an\r 2",
    "Player_7": "M.Salah\r 14",
    "Player_2": "Mazraoui\r IPS (A)",
    "Player_5": "Eze\r 0",
    "Player_6": "Palmer\r 2",
    "Player_3": "Andersen\r 0",
    "Player_4": "Saliba\r 7",
    "Player_8": "Damsgaard\r 3",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "650( 2,267,030 ) TotalXfr : 14",
    "Teams": "LxFxC( Ervin Rigo )",
    "SXL": "Malta",
    "Latp": "27",
    "Player_1": "Pope\r WHU (H)",
    "Player_11": "Isak\r WHU (H)",
    "Player_10": "Wissa\r 2",
    "Player_12": "Jos\u00E9 S\u00E1\r 2",
    "Player_13": "Semenyo\r 1",
    "Player_14": "Gvardiol\r 0",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Virgil\r 1",
    "Player_5": "Martinelli\r 0",
    "Player_6": "Palmer\r 2",
    "Player_3": "Digne\r 1",
    "Player_4": "A\u00EFt-Nouri\r 2",
    "Player_8": "M.Salah\r 14",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Pedro Porro\r 14"
  },
  {
    "manager_Name": "648( 2,350,260 ) TotalXfr : 11",
    "Teams": "Ctrl Alt De Ligt( Marlon Vella )",
    "SXL": "Malta",
    "Latp": "30",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "Faes\r 0",
    "Player_14": "Ra\u00FAl\r 2",
    "Player_7": "Rogers\r 2",
    "Player_2": "A\u00EFt-Nouri\r 2",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "Mbeumo\r 3",
    "Player_3": "Milenkovi\u0107\r 1",
    "Player_4": "Lewis\r 0",
    "Player_8": "Palmer\r 2",
    "Player_9": "M.Salah\r 14",
    "Player_15": "Mazraoui\r IPS (A)"
  },
  {
    "manager_Name": "638( 2,842,310 ) TotalXfr : 6",
    "Teams": "Matteo fc( Matteo Vella )",
    "SXL": "Malta",
    "Latp": "54",
    "Player_1": "Pope\r WHU (H)",
    "Player_11": "Jo\u00E3o Pedro\r 12",
    "Player_10": "Isak\r WHU (H)",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "Burn\r WHU (H)",
    "Player_14": "Johnson\r 6",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Pedro Porro\r 14",
    "Player_5": "Palmer\r 2",
    "Player_6": "Rogers\r 2",
    "Player_3": "Konsa\r 0",
    "Player_4": "Gvardiol\r 0",
    "Player_8": "M.Salah\r 14",
    "Player_9": "Watkins\r 7",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "638( 2,843,990 ) TotalXfr : 7",
    "Teams": "St Peters FC( Clayton Borda )",
    "SXL": "Malta",
    "Latp": "25",
    "Player_1": "Pope\r WHU (H)",
    "Player_11": "Mateta\r 5",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "Andersen\r 0",
    "Player_14": "Chiwome\r 0",
    "Player_7": "Palmer\r 2",
    "Player_2": "Burn\r WHU (H)",
    "Player_5": "B.Fernandes\r IPS (A)",
    "Player_6": "Bruno G.\r WHU (H)",
    "Player_3": "Konsa\r 0",
    "Player_4": "De Ligt\r IPS (A)",
    "Player_8": "Saka\r 13",
    "Player_9": "Smith Rowe\r 1",
    "Player_15": "Kristiansen\r 1"
  },
  {
    "manager_Name": "638( 2,854,622 ) TotalXfr : 10",
    "Teams": "FC Lokomotiv Sliema( Philip H\u00E5kansson )",
    "SXL": "Malta",
    "Latp": "30",
    "Player_1": "Raya\r 6",
    "Player_11": "Haaland\r 4",
    "Player_10": "Strand Larsen\r 5",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Johnson\r 6",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Neto\r 0",
    "Player_2": "Virgil\r 1",
    "Player_5": "Rogers\r 2",
    "Player_6": "Garnacho\r IPS (A)",
    "Player_3": "Mazraoui\r IPS (A)",
    "Player_4": "Lewis\r 0",
    "Player_8": "M.Salah\r 7",
    "Player_9": "Solanke\r 5",
    "Player_15": "Romero\r 0"
  },
  {
    "manager_Name": "636( 2,960,392 ) TotalXfr : 10",
    "Teams": "FC Qvantas( Johan Hammarstrom )",
    "SXL": "Sweden",
    "Latp": "38",
    "Player_1": "Raya\r 6",
    "Player_11": "Haaland\r 4",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Sels\r 2",
    "Player_13": "Faes\r 0",
    "Player_14": "Winks\r 1",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Saliba\r 7",
    "Player_5": "Johnson\r 6",
    "Player_6": "Palmer\r 2",
    "Player_3": "Keane\r 0",
    "Player_4": "Gabriel\r 6",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "Wood\r 1",
    "Player_15": "Burn\r WHU (H)"
  },
  {
    "manager_Name": "634( 3,061,549 ) TotalXfr : 9",
    "Teams": "Massilia( Daniel Borg )",
    "SXL": "Malta",
    "Latp": "39",
    "Player_1": "Martinez\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Delap\r MUN (H)",
    "Player_12": "Flekken\r 9",
    "Player_13": "Johnson\r 6",
    "Player_14": "Konsa\r 0",
    "Player_7": "Rogers\r 2",
    "Player_2": "A\u00EFt-Nouri\r 2",
    "Player_5": "Semenyo\r 1",
    "Player_6": "Mbeumo\r 3",
    "Player_3": "Virgil\r 1",
    "Player_4": "Keane\r 0",
    "Player_8": "M.Salah\r 14",
    "Player_9": "N.Jackson\r 12",
    "Player_15": "Aina\r 0"
  },
  {
    "manager_Name": "633( 3,120,878 ) TotalXfr : 10",
    "Teams": "20x MU( John Tiltmann )",
    "SXL": "Malta",
    "Latp": "42",
    "Player_1": "Fabianski\r NEW (A)",
    "Player_11": "Haaland\r 2",
    "Player_10": "Cunha\r 16",
    "Player_12": "Martinez\r 2",
    "Player_13": "Keane\r 0",
    "Player_14": "Alexander-Arnold\r 0",
    "Player_7": "Smith Rowe\r 1",
    "Player_2": "Digne\r 1",
    "Player_5": "Madueke\r 3",
    "Player_6": "M.Salah\r 14",
    "Player_3": "Robinson\r 0",
    "Player_4": "Mazraoui\r IPS (A)",
    "Player_8": "Mbeumo\r 3",
    "Player_9": "Welbeck\r 2",
    "Player_15": "McNeil\r 3"
  },
  {
    "manager_Name": "632( 3,174,492 ) TotalXfr : 10",
    "Teams": "\u0106umura\u0161i( Aleksandar Deletic )",
    "SXL": "Serbia",
    "Latp": "53",
    "Player_1": "Raya\r 6",
    "Player_11": "Ra\u00FAl\r 2",
    "Player_10": "Watkins\r 7",
    "Player_12": "S\u00E1nchez\r 1",
    "Player_13": "Mbeumo\r 3",
    "Player_14": "Hall\r WHU (H)",
    "Player_7": "Rogers\r 2",
    "Player_2": "Gabriel\r 6",
    "Player_5": "Virgil\r 1",
    "Player_6": "M.Salah\r 14",
    "Player_3": "Digne\r 1",
    "Player_4": "Andersen\r 0",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "Saka\r 13",
    "Player_15": "Welbeck\r 2"
  },
  {
    "manager_Name": "632( 3,190,138 ) TotalXfr : 12",
    "Teams": "Rekegutt United( Eirik Presttun )",
    "SXL": "Malta",
    "Latp": "37",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Haaland\r 2",
    "Player_10": "N.Jackson\r 12",
    "Player_12": "Henderson\r 7",
    "Player_13": "Dibling\r 2",
    "Player_14": "Faes\r 0",
    "Player_7": "Madueke\r 3",
    "Player_2": "Dalot\r IPS (A)",
    "Player_5": "Garnacho\r IPS (A)",
    "Player_6": "M.Salah\r 14",
    "Player_3": "Gvardiol\r 0",
    "Player_4": "Mazraoui\r IPS (A)",
    "Player_8": "Mbeumo\r 3",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "631( 3,217,887 ) TotalXfr : 7",
    "Teams": "HUNdorito( Adam Rajki )",
    "SXL": "Hungary",
    "Latp": "55",
    "Player_1": "Raya\r 6",
    "Player_11": "Ra\u00FAl\r 2",
    "Player_10": "Wood\r 1",
    "Player_12": "Turner\r 0",
    "Player_13": "Nelson\r 2",
    "Player_14": "Winks\r 1",
    "Player_7": "M.Salah\r 7",
    "Player_2": "Pedro Porro\r 14",
    "Player_5": "Calafiori\r 6",
    "Player_6": "Szoboszlai\r 7",
    "Player_3": "Gvardiol\r 0",
    "Player_4": "Saliba\r 7",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "Haaland\r 4",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "628( 3,399,788 ) TotalXfr : 11",
    "Teams": "Nketiah_\u0393\u03B1\u03C1\u03BC\u03C0\u03AE( Dimitris Tselikas )",
    "SXL": "Greece",
    "Latp": "37",
    "Player_1": "Flekken\r 9",
    "Player_11": "Haaland\r 4",
    "Player_10": "N.Jackson\r 12",
    "Player_12": "Areola\r NEW (A)",
    "Player_13": "Faes\r 0",
    "Player_14": "Pedro Porro\r 14",
    "Player_7": "Rogers\r 2",
    "Player_2": "Digne\r 1",
    "Player_5": "M.Salah\r 7",
    "Player_6": "Martinelli\r 0",
    "Player_3": "Lewis\r 0",
    "Player_4": "Robertson\r 1",
    "Player_8": "Garnacho\r IPS (A)",
    "Player_9": "Smith Rowe\r 1",
    "Player_15": "Archer\r 0"
  },
  {
    "manager_Name": "623( 3,682,036 ) TotalXfr : 12",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "India",
    "Latp": "42",
    "Player_1": "Fabianski\r NEW (A)",
    "Player_11": "Cunha\r 16",
    "Player_10": "Havertz\r 0",
    "Player_12": "Henderson\r 7",
    "Player_13": "Johnson\r 6",
    "Player_14": "Faes\r 0",
    "Player_7": "M.Salah\r 14",
    "Player_2": "Keane\r 0",
    "Player_5": "Saliba\r 7",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Konat\u00E9\r 0",
    "Player_4": "W.Fofana\r 2",
    "Player_8": "Palmer\r 2",
    "Player_9": "B.Fernandes\r IPS (A)",
    "Player_15": "Wheatley\r IPS (A)"
  },
  {
    "manager_Name": "622( 3,699,606 ) TotalXfr : 0",
    "Teams": "KAMACIO FC( Francisco Camacho )",
    "SXL": "Malta",
    "Latp": "53",
    "Player_1": "Fabianski\r NEW (A)",
    "Player_11": "Watkins\r 7",
    "Player_10": "Havertz\r 0",
    "Player_12": "Areola\r NEW (A)",
    "Player_13": "Jo\u00E3o Pedro\r 12",
    "Player_14": "Hill\r 0",
    "Player_7": "Foden\r 2",
    "Player_2": "Mykolenko\r 6",
    "Player_5": "Bowen\r NEW (A)",
    "Player_6": "Palmer\r 4",
    "Player_3": "Saliba\r 7",
    "Player_4": "Pedro Porro\r 14",
    "Player_8": "Saka\r 13",
    "Player_9": "Gordon\r WHU (H)",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "622( 3,704,678 ) TotalXfr : 3",
    "Teams": "Unseen Academicals( Kurt Bugeja Coster )",
    "SXL": "Malta",
    "Latp": "40",
    "Player_1": "Ederson M.\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "Wissa\r 2",
    "Player_12": "Areola\r NEW (A)",
    "Player_13": "Trippier\r WHU (H)",
    "Player_14": "Jo\u00E3o Pedro\r 12",
    "Player_7": "Saka\r 13",
    "Player_2": "Estupi\u00F1an\r 2",
    "Player_5": "Pedro Porro\r 14",
    "Player_6": "Onana\r 0",
    "Player_3": "Chilwell\r 0",
    "Player_4": "Konat\u00E9\r 0",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "Mbeumo\r 3",
    "Player_15": "Eze\r 0"
  },
  {
    "manager_Name": "622( 3,716,861 ) TotalXfr : 9",
    "Teams": "Red Tigers FC( George Vepkhvadze )",
    "SXL": "Georgia",
    "Latp": "43",
    "Player_1": "Pope\r WHU (H)",
    "Player_11": "Havertz\r 0",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r NEW (A)",
    "Player_13": "Wood\r 1",
    "Player_14": "Gusto\r 0",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Van den Berg\r 6",
    "Player_5": "Saka\r 26",
    "Player_6": "Bowen\r NEW (A)",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Kerkez\r 1",
    "Player_8": "Gordon\r WHU (H)",
    "Player_9": "Semenyo\r 1",
    "Player_15": "Greaves\r MUN (H)"
  },
  {
    "manager_Name": "619( 3,887,589 ) TotalXfr : 10",
    "Teams": "Maniacs( Alvaro Garcia )",
    "SXL": "Malta",
    "Latp": "16",
    "Player_1": "Onana\r IPS (A)",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Raya\r 6",
    "Player_13": "Palmer\r 2",
    "Player_14": "Antonio\r NEW (A)",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Konat\u00E9\r 0",
    "Player_5": "Gvardiol\r 0",
    "Player_6": "Georginio\r 5",
    "Player_3": "Virgil\r 1",
    "Player_4": "Dalot\r IPS (A)",
    "Player_8": "Mbeumo\r 3",
    "Player_9": "Casemiro\r IPS (A)",
    "Player_15": "Burgess\r MUN (H)"
  },
  {
    "manager_Name": "613( 4,215,262 ) TotalXfr : 10",
    "Teams": "Mimz( Emma Zammit )",
    "SXL": "Malta",
    "Latp": "22",
    "Player_1": "Pickford\r 6",
    "Player_11": "Duran\r 1",
    "Player_10": "Haaland\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Sou\u010Dek\r NEW (A)",
    "Player_14": "Faes\r 0",
    "Player_7": "Smith Rowe\r 1",
    "Player_2": "Virgil\r 1",
    "Player_5": "Palmer\r 2",
    "Player_6": "Mbeumo\r 3",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Martinez\r IPS (A)",
    "Player_8": "Garnacho\r IPS (A)",
    "Player_9": "Isak\r WHU (H)",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "608( 4,500,286 ) TotalXfr : 12",
    "Teams": "Rolling Fernander( Adam Ruggier )",
    "SXL": "Malta",
    "Latp": "34",
    "Player_1": "Raya\r 6",
    "Player_11": "Haaland\r 2",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Harwood-Bellis\r 1",
    "Player_14": "Barco\r 0",
    "Player_7": "M.Salah\r 14",
    "Player_2": "Konat\u00E9\r 0",
    "Player_5": "Palmer\r 2",
    "Player_6": "Semenyo\r 1",
    "Player_3": "De Ligt\r IPS (A)",
    "Player_4": "Gabriel\r 6",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "Wheatley\r IPS (A)",
    "Player_15": "Yarmoliuk\r 1"
  },
  {
    "manager_Name": "606( 4,594,949 ) TotalXfr : 10",
    "Teams": "kabana( Sebastian Agius )",
    "SXL": "Malta",
    "Latp": "32",
    "Player_1": "Raya\r 6",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Watkins\r 7",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Robinson\r 0",
    "Player_14": "Pedro Porro\r 14",
    "Player_7": "Smith Rowe\r 1",
    "Player_2": "Mazraoui\r IPS (A)",
    "Player_5": "Palmer\r 2",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Saliba\r 7",
    "Player_4": "Alexander-Arnold\r 0",
    "Player_8": "Rogers\r 2",
    "Player_9": "Haaland\r 4",
    "Player_15": "Ugochukwu\r 1"
  },
  {
    "manager_Name": "605( 4,625,218 ) TotalXfr : 0",
    "Teams": "Pierosson( Pietro Ramellini )",
    "SXL": "Malta",
    "Latp": "14",
    "Player_1": "A.Becker\r 0",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 1",
    "Player_12": "Kelleher\r 7",
    "Player_13": "Ajer\r 0",
    "Player_14": "Eze\r 0",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Van Hecke\r 1",
    "Player_5": "Justin\r 1",
    "Player_6": "Kudus\r NEW (A)",
    "Player_3": "Aina\r 0",
    "Player_4": "Martinez\r IPS (A)",
    "Player_8": "Kulusevski\r 6",
    "Player_9": "Bernardo\r 1",
    "Player_15": "Isak\r WHU (H)"
  },
  {
    "manager_Name": "605( 4,655,490 ) TotalXfr : 11",
    "Teams": "Wan Utd( Mindaugas Grigaitis )",
    "SXL": "Lithuania",
    "Latp": "47",
    "Player_1": "Raya\r 6",
    "Player_11": "Cunha\r 16",
    "Player_10": "Havertz\r 0",
    "Player_12": "Vicario\r 8",
    "Player_13": "Johnson\r 6",
    "Player_14": "Aina\r 0",
    "Player_7": "M.Salah\r 14",
    "Player_2": "Robinson\r 0",
    "Player_5": "Bowen\r NEW (A)",
    "Player_6": "Mbeumo\r 3",
    "Player_3": "Gvardiol\r 0",
    "Player_4": "Saliba\r 7",
    "Player_8": "Garnacho\r IPS (A)",
    "Player_9": "Wood\r 1",
    "Player_15": "Pedro Porro\r 14"
  }
];