var s = [
  {
    "manager_Name": "748( 205,830 ) TotalXfr : 11",
    "Teams": "Fernandes and Sons( Shahnawaz Hussain )",
    "SXL": "Germany",
    "Latp": "74",
    "Player_1": "Onana\r 3",
    "Player_11": "Cunha\r 16",
    "Player_10": "Isak\r 2",
    "Player_12": "Fabianski\r 6",
    "Player_13": "Jo\u00E3o Pedro\r 12",
    "Player_14": "Hall\r 1",
    "Player_7": "Rogers\r 2",
    "Player_2": "A\u00EFt-Nouri\r 2",
    "Player_5": "M.Salah\r 26",
    "Player_6": "Palmer\r 2",
    "Player_3": "Konat\u00E9\r 0",
    "Player_4": "Gabriel\r 6",
    "Player_8": "B.Fernandes\r 2",
    "Player_9": "Saka\r 13",
    "Player_15": "O\u0027Shea\r 2"
  },
  {
    "manager_Name": "696( 1,305,354 ) TotalXfr : 11",
    "Teams": "BB( Sai Prasad )",
    "SXL": "India",
    "Latp": "62",
    "Player_1": "Pickford\r 6",
    "Player_11": "Isak\r 2",
    "Player_10": "Cunha\r 16",
    "Player_12": "Henderson\r 7",
    "Player_13": "Johnson\r 6",
    "Player_14": "Keane\r 0",
    "Player_7": "Palmer\r 2",
    "Player_2": "Robinson\r 0",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "Mbeumo\r 3",
    "Player_3": "Gvardiol\r 0",
    "Player_4": "Okoli\r 1",
    "Player_8": "M.Salah\r 26",
    "Player_9": "Solanke\r 5",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "670( 2,314,359 ) TotalXfr : 4",
    "Teams": "AlMoonjaha( Arjun Venugopal )",
    "SXL": "USA",
    "Latp": "73",
    "Player_1": "Ederson M.\r 1",
    "Player_11": "Jo\u00E3o Pedro\r 12",
    "Player_10": "Solanke\r 5",
    "Player_12": "Fabianski\r 6",
    "Player_13": "Alexander-Arnold\r 0",
    "Player_14": "Van de Ven\r 0",
    "Player_7": "Gordon\r 2",
    "Player_2": "Saliba\r 7",
    "Player_5": "M.Salah\r 26",
    "Player_6": "B.Fernandes\r 2",
    "Player_3": "Ak\u00E9\r 0",
    "Player_4": "Chilwell\r 0",
    "Player_8": "Maddison\r 16",
    "Player_9": "Antonio\r 2",
    "Player_15": "Diogo J.\r 0"
  },
  {
    "manager_Name": "663( 2,660,012 ) TotalXfr : 12",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "India",
    "Latp": "68",
    "Player_1": "Fabianski\r 6",
    "Player_11": "Cunha\r 16",
    "Player_10": "Palmer\r 2",
    "Player_12": "Henderson\r 7",
    "Player_13": "Keane\r 0",
    "Player_14": "Havertz\r 0",
    "Player_7": "B.Fernandes\r 2",
    "Player_2": "Konat\u00E9\r 0",
    "Player_5": "Faes\r 0",
    "Player_6": "Johnson\r 6",
    "Player_3": "Saliba\r 7",
    "Player_4": "W.Fofana\r 2",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "M.Salah\r 26",
    "Player_15": "Wheatley\r 0"
  },
  {
    "manager_Name": "656( 2,969,592 ) TotalXfr : 7",
    "Teams": "MundinaSaalaCupNamde( Ashwin Z )",
    "SXL": "India",
    "Latp": "38",
    "Player_1": "Ederson M.\r 1",
    "Player_11": "Vardy\r 2",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Henderson\r 7",
    "Player_13": "Gusto\r 0",
    "Player_14": "Dennis\r 0",
    "Player_7": "Palmer\r 4",
    "Player_2": "Gabriel\r 6",
    "Player_5": "Mbeumo\r 3",
    "Player_6": "G\u00FCndogan\r 2",
    "Player_3": "Digne\r 1",
    "Player_4": "Davis\r 2",
    "Player_8": "M.Salah\r 13",
    "Player_9": "B.Fernandes\r 2",
    "Player_15": "Alexander-Arnold\r 0"
  },
  {
    "manager_Name": "651( 3,230,961 ) TotalXfr : 11",
    "Teams": "Like a Virgil( Alberto Acuna )",
    "SXL": "Netherlands",
    "Latp": "68",
    "Player_1": "Flekken\r 9",
    "Player_11": "Cunha\r 16",
    "Player_10": "Ra\u00FAl\r 2",
    "Player_12": "Fabianski\r 6",
    "Player_13": "Johnson\r 6",
    "Player_14": "Keane\r 0",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Digne\r 1",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "Rogers\r 2",
    "Player_3": "Lewis\r 0",
    "Player_4": "Gabriel\r 6",
    "Player_8": "M.Salah\r 26",
    "Player_9": "Haaland\r 2",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "644( 3,572,329 ) TotalXfr : 10",
    "Teams": "Gunners( Maheshkumar Arumugam )",
    "SXL": "India",
    "Latp": "64",
    "Player_1": "Flekken\r 9",
    "Player_11": "Ra\u00FAl\r 2",
    "Player_10": "Ndiaye\r 2",
    "Player_12": "Areola\r 0",
    "Player_13": "Matheus N.\r 0",
    "Player_14": "Bednarek\r 0",
    "Player_7": "M.Salah\r 26",
    "Player_2": "Pau\r 1",
    "Player_5": "Saka\r 13",
    "Player_6": "Johnson\r 6",
    "Player_3": "Aina\r 0",
    "Player_4": "Gvardiol\r 0",
    "Player_8": "Madueke\r 3",
    "Player_9": "Haaland\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "641( 3,724,158 ) TotalXfr : 10",
    "Teams": "united( Midhunjith Rajendrakumar )",
    "SXL": "Netherlands",
    "Latp": "48",
    "Player_1": "Kelleher\r 7",
    "Player_11": "Darwin\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Sels\r 2",
    "Player_13": "Keane\r 0",
    "Player_14": "McNeil\r 3",
    "Player_7": "Palmer\r 2",
    "Player_2": "Digne\r 1",
    "Player_5": "Mbeumo\r 3",
    "Player_6": "Saka\r 13",
    "Player_3": "A\u00EFt-Nouri\r 2",
    "Player_4": "Van den Berg\r 6",
    "Player_8": "Johnson\r 6",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Van de Ven\r 0"
  },
  {
    "manager_Name": "639( 3,824,732 ) TotalXfr : 10",
    "Teams": "Raj( Rajesh shibu )",
    "SXL": "Bahrain",
    "Latp": "59",
    "Player_1": "Onana\r 3",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Ra\u00FAl\r 2",
    "Player_12": "Fabianski\r 6",
    "Player_13": "Van den Berg\r 6",
    "Player_14": "O\u0027Shea\r 2",
    "Player_7": "Saka\r 13",
    "Player_2": "Virgil\r 1",
    "Player_5": "Palmer\r 2",
    "Player_6": "M.Salah\r 26",
    "Player_3": "J.Timber\r 6",
    "Player_4": "Gvardiol\r 0",
    "Player_8": "Garnacho\r 2",
    "Player_9": "Rogers\r 2",
    "Player_15": "Solanke\r 5"
  },
  {
    "manager_Name": "631( 4,245,504 ) TotalXfr : 13",
    "Teams": "BloodWorkB7( Benin Paul )",
    "SXL": "Netherlands",
    "Latp": "50",
    "Player_1": "Henderson\r 7",
    "Player_11": "Calvert-Lewin\r 2",
    "Player_10": "Solanke\r 5",
    "Player_12": "Pickford\r 6",
    "Player_13": "Alexander-Arnold\r 0",
    "Player_14": "Muniz\r 1",
    "Player_7": "Rogers\r 2",
    "Player_2": "Robinson\r 0",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "Mbeumo\r 3",
    "Player_3": "Gvardiol\r 0",
    "Player_4": "A\u00EFt-Nouri\r 2",
    "Player_8": "Palmer\r 2",
    "Player_9": "M.Salah\r 26",
    "Player_15": "Quansah\r 0"
  },
  {
    "manager_Name": "586( 6,365,905 ) TotalXfr : 10",
    "Teams": "Terminators FC( Geo Paul )",
    "SXL": "India",
    "Latp": "23",
    "Player_1": "Martinez\r 2",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Wood\r 1",
    "Player_12": "Vicario\r 8",
    "Player_13": "Manning\r 0",
    "Player_14": "Konat\u00E9\r 0",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Gabriel\r 6",
    "Player_5": "Luis D\u00EDaz\r 1",
    "Player_6": "Winks\r 1",
    "Player_3": "Digne\r 1",
    "Player_4": "Lewis\r 0",
    "Player_8": "Palmer\r 4",
    "Player_9": "Haaland\r 2",
    "Player_15": "Sou\u010Dek\r 10"
  },
  {
    "manager_Name": "501( 8,847,218 ) TotalXfr : 15",
    "Teams": "\u0D31\u0D2E\u0D26\u0D3E\u0D2A\u0D33\u0D4D\u0D33\u0D3F \u0D1F\u0D40\u0D02( SARATH \uD83E\uDD13 )",
    "SXL": "India",
    "Latp": "17",
    "Player_1": "Martinez\r 2",
    "Player_11": "Isak\r 2",
    "Player_10": "Wood\r 1",
    "Player_12": "D\u00FAbravka\r 0",
    "Player_13": "Romero\r 0",
    "Player_14": "Mu\u00F1oz\r 1",
    "Player_7": "Rogers\r 2",
    "Player_2": "Robinson\r 0",
    "Player_5": "Mbeumo\r 3",
    "Player_6": "Semenyo\r 1",
    "Player_3": "Gvardiol\r 0",
    "Player_4": "Andersen\r 0",
    "Player_8": "B.Fernandes\r 4",
    "Player_9": "Haaland\r 2",
    "Player_15": "Buonanotte\r 0"
  }
];