var s = [
   {
      "itemID":"1",
      "ItemName":"LemonCake",
      "dayOfPurchase":"1st week of June",
      "expiryDate":"28/06/2021",
      "consumedFlag":"0",
      "Comment":"middle rack of closet"
   },
   {
      "itemID":"2",
      "ItemName":"PlumCake",
      "dayOfPurchase":"2nd week of june",
      "expiryDate":"23/06/2021",
      "consumedFlag":"0",
      "Comment":"inside kitchen - "
   },
   {
      "itemID":"3",
      "ItemName":"FrenchButterBread",
      "dayOfPurchase":"TBD",
      "expiryDate":"TBD",
      "consumedFlag":"TBD",
      "Comment":"TBD"
   },
   {
      "itemID":"4",
      "ItemName":"EggTrayRewe",
      "dayOfPurchase":"TBD",
      "expiryDate":"TBD",
      "consumedFlag":"TBD",
      "Comment":"TBD"
   },
   {
      "itemID":"5",
      "ItemName":"EggTrayAldi",
      "dayOfPurchase":"TBD",
      "expiryDate":"TBD",
      "consumedFlag":"TBD",
      "Comment":"NA"
   },
   {
      "itemID":"6",
      "ItemName":"BeerCarlsburg",
      "dayOfPurchase":"TBD",
      "expiryDate":"TBD",
      "consumedFlag":"TBD",
      "Comment":"TBD"
   },
   {
      "itemID":"7",
      "ItemName":"BeerRadler",
      "dayOfPurchase":"TBD",
      "expiryDate":"TBD",
      "consumedFlag":"TBD",
      "Comment":"NA"
   },
   {
      "itemID":"8",
      "ItemName":"BeerPils",
      "dayOfPurchase":"TBD",
      "expiryDate":"TBD",
      "consumedFlag":"TBD",
      "Comment":"TBD"
   },
   {
      "itemID":"9",
      "ItemName":"KornerBalanceGreenLarge_L",
      "dayOfPurchase":"TBD",
      "expiryDate":"TBD",
      "consumedFlag":"TBD",
      "Comment":"NA"
   },
   {
      "itemID":"10",
      "ItemName":"KornerBalanceGreenLarge_S",
      "dayOfPurchase":"TBD",
      "expiryDate":"TBD",
      "consumedFlag":"TBD",
      "Comment":"TBD"
   }
]