var s = [{
	"manager_Name": "Nishant Singh",
	"Teams": "beta 11",
	"Player_1": "Pope CHE (A)",
	"Player_2": "Stones SHU (H)",
	"Player_3": "Justin LEE (H)",
	"Player_4": "Cancelo SHU (H)",
	"Player_5": "Foden SHU (H)",
	"Player_6": "Salah WHU (A)$ captain",
	"Player_7": "Fernandes ARS (A)",
	"Player_8": "Soucek LIV (H)",
	"Player_9": "Bamford LEI (A)",
	"Player_10": "Watkins SOU (A)",
	"Player_11": "Antonio LIV (H)",
	"Player_12": "Fabianski LIV (H)",
	"Player_13": "Harrison LEI (A)",
	"Player_14": "Mee CHE (A)",
	"Player_15": "Dallas LEI (A)",
	"SXL": "0",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Rohan Rai",
	"Teams": "FALSE 9",
	"Player_1": "Martínez SOU (A)",
	"Player_2": "Stones SHU (H)",
	"Player_3": "Mitchell WOL (H)",
	"Player_4": "James BUR (H)",
	"Player_5": "Fernandes ARS (A)",
	"Player_6": "Sterling SHU (H)$ captain",
	"Player_7": "Salah WHU (A)",
	"Player_8": "Son BHA (A)",
	"Player_9": "Maddison LEE (H)",
	"Player_10": "Antonio LIV (H)",
	"Player_11": "Watkins SOU (A)",
	"Player_12": "Sánchez TOT (H)",
	"Player_13": "Holding MUN (H)",
	"Player_14": "Coufal LIV (H)",
	"Player_15": "Brewster MCI (A)",
	"SXL": "0",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Avijit Das",
	"Teams": "WeAreTheArsenal",
	"Player_1": "Martínez SOU (A)",
	"Player_2": "Mitchell WOL (H)",
	"Player_3": "Wan-Bissaka ARS (A)",
	"Player_4": "Cancelo SHU (H)",
	"Player_5": "Maddison LEE (H)",
	"Player_6": "Soucek LIV (H)",
	"Player_7": "Fernandes ARS (A)",
	"Player_8": "Salah WHU (A)",
	"Player_9": "Sterling SHU (H)$ captain",
	"Player_10": "Bamford LEI (A)",
	"Player_11": "Calvert-Lewin 1",
	"Player_12": "Steer SOU (A)",
	"Player_13": "Wilson 1",
	"Player_14": "Cresswell LIV (H)",
	"Player_15": "Ayling LEI (A)",
	"SXL": "1",
	"Bench": "1",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Gaurav Shrestha",
	"Teams": "Fußball-Mannschaft",
	"Player_1": "Martínez SOU (A)",
	"Player_2": "Stones SHU (H)",
	"Player_3": "Dallas LEI (A)",
	"Player_4": "Cancelo SHU (H)",
	"Player_5": "Fernandes ARS (A)",
	"Player_6": "Raphinha LEI (A)",
	"Player_7": "Salah WHU (A)",
	"Player_8": "Sterling SHU (H)$ captain",
	"Player_9": "Bamford LEI (A)",
	"Player_10": "Calvert-Lewin 1",
	"Player_11": "Antonio LIV (H)",
	"Player_12": "Forster AVL (H)",
	"Player_13": "Soucek LIV (H)",
	"Player_14": "Mitchell WOL (H)",
	"Player_15": "Coufal LIV (H)",
	"SXL": "1",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Dipen Thapa",
	"Teams": "Lokipower Reloaded",
	"Player_1": "McCarthy AVL (H)",
	"Player_2": "Cancelo SHU (H)",
	"Player_3": "Justin LEE (H)",
	"Player_4": "Mings SOU (A)",
	"Player_5": "Salah WHU (A)",
	"Player_6": "Zaha WOL (H)$ captain",
	"Player_7": "Son BHA (A)",
	"Player_8": "Barnes LEE (H)",
	"Player_9": "Calvert-Lewin 2",
	"Player_10": "Antonio LIV (H)",
	"Player_11": "Watkins SOU (A)",
	"Player_12": "Martínez SOU (A)",
	"Player_13": "Fernandes ARS (A)",
	"Player_14": "Taylor CHE (A)",
	"Player_15": "Kilman CRY (A)",
	"SXL": "2",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Sibin _",
	"Teams": "FortunaDüsseldorfer",
	"Player_1": "Ederson SHU (H)",
	"Player_2": "Stones SHU (H)",
	"Player_3": "Dias SHU (H)",
	"Player_4": "Davies BHA (A)",
	"Player_5": "Son BHA (A)",
	"Player_6": "Salah WHU (A)$ captain",
	"Player_7": "Raphinha LEI (A)",
	"Player_8": "Fernandes ARS (A)",
	"Player_9": "Adams AVL (H)",
	"Player_10": "Bamford LEI (A)",
	"Player_11": "Werner BUR (H)",
	"Player_12": "Johnstone FUL (H)",
	"Player_13": "Smith Rowe MUN (H)",
	"Player_14": "Walker-Peters AVL (H)",
	"Player_15": "Coufal LIV (H)",
	"SXL": "0",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Kushal Sahota",
	"Teams": "FC ASSASSINS",
	"Player_1": "Lloris BHA (A)",
	"Player_2": "Cresswell LIV (H)",
	"Player_3": "Cancelo SHU (H)",
	"Player_4": "Alioski LEI (A)",
	"Player_5": "Foden SHU (H)",
	"Player_6": "Son BHA (A)$ captain",
	"Player_7": "Fernandes ARS (A)",
	"Player_8": "Salah WHU (A)",
	"Player_9": "Wilson 2",
	"Player_10": "Calvert-Lewin 2",
	"Player_11": "Bamford LEI (A)",
	"Player_12": "Macey MUN (H)",
	"Player_13": "Neco Williams WHU (A)",
	"Player_14": "Bernardo TOT (H)",
	"Player_15": "Oriol Romeu AVL (H)",
	"SXL": "4",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "SATYAM RAI",
	"Teams": "PINE",
	"Player_1": "Martínez SOU (A)",
	"Player_2": "Cancelo SHU (H)",
	"Player_3": "Chilwell BUR (H)",
	"Player_4": "Justin LEE (H)",
	"Player_5": "Soucek LIV (H)",
	"Player_6": "Gündogan SHU (H)",
	"Player_7": "Fernandes ARS (A)",
	"Player_8": "Sterling SHU (H)$ captain",
	"Player_9": "Salah WHU (A)",
	"Player_10": "Bamford LEI (A)",
	"Player_11": "Antonio LIV (H)",
	"Player_12": "Peacock-Farrell CHE (A)",
	"Player_13": "Wilson 2",
	"Player_14": "Shaw ARS (A)",
	"Player_15": "Coufal LIV (H)",
	"SXL": "0",
	"Bench": "2",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "ashim lama",
	"Teams": "⚔️FURY⚔️",
	"Player_1": "Martínez SOU (A)",
	"Player_2": "Mitchell WOL (H)",
	"Player_3": "Stones SHU (H)",
	"Player_4": "Justin LEE (H)",
	"Player_5": "Dias SHU (H)",
	"Player_6": "Sterling SHU (H)$ captain",
	"Player_7": "Son BHA (A)",
	"Player_8": "Saka MUN (H)",
	"Player_9": "Fernandes ARS (A)",
	"Player_10": "Bowen LIV (H)",
	"Player_11": "Watkins SOU (A)",
	"Player_12": "Martin LIV (H)",
	"Player_13": "Brewster MCI (A)",
	"Player_14": "Taylor CHE (A)",
	"Player_15": "Kane BHA (A)",
	"SXL": "0",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Indrajeet Singh",
	"Teams": "Kung fu Pandoos",
	"Player_1": "Meslier LEI (A)",
	"Player_2": "Bellerín MUN (H)",
	"Player_3": "Zouma BUR (H)",
	"Player_4": "Cresswell LIV (H)",
	"Player_5": "Salah WHU (A)",
	"Player_6": "Son BHA (A)",
	"Player_7": "Maddison LEE (H)",
	"Player_8": "Pereira FUL (H)",
	"Player_9": "Sterling SHU (H)$ captain",
	"Player_10": "Calvert-Lewin 2",
	"Player_11": "Bamford LEI (A)",
	"Player_12": "Henderson WOL (H)",
	"Player_13": "Wilson 2",
	"Player_14": "Webster TOT (H)",
	"Player_15": "Walker-Peters AVL (H)",
	"SXL": "2",
	"Bench": "2",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Vivek Lama",
	"Teams": "JOJOs LFC",
	"Player_1": "Alisson WHU (A)",
	"Player_2": "Saïss CRY (A)",
	"Player_3": "Alexander-Arnold WHU (A)",
	"Player_4": "Walker-Peters AVL (H)",
	"Player_5": "Tielemans LEE (H)",
	"Player_6": "Son BHA (A)",
	"Player_7": "Sterling SHU (H)",
	"Player_8": "Mané WHU (A)$ captain",
	"Player_9": "Connolly TOT (H)",
	"Player_10": "Adams AVL (H)",
	"Player_11": "Bamford LEI (A)",
	"Player_12": "Ryan MUN (H)",
	"Player_13": "Saint-Maximin 0",
	"Player_14": "Egan MCI (A)",
	"Player_15": "Dunne CHE (A)",
	"SXL": "0",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Prabin Singh",
	"Teams": "Random XI",
	"Player_1": "Ederson SHU (H)",
	"Player_2": "Cancelo SHU (H)",
	"Player_3": "Holding MUN (H)",
	"Player_4": "Justin LEE (H)",
	"Player_5": "Son BHA (A)$ captain",
	"Player_6": "Mahrez SHU (H)",
	"Player_7": "Zaha WOL (H)",
	"Player_8": "Grealish SOU (A)",
	"Player_9": "Ward-Prowse AVL (H)",
	"Player_10": "Wilson 2",
	"Player_11": "Antonio LIV (H)",
	"Player_12": "Macey MUN (H)",
	"Player_13": "Shaw ARS (A)",
	"Player_14": "Kane BHA (A)",
	"Player_15": "Dunne CHE (A)",
	"SXL": "2",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Kumar Anku",
	"Teams": "Galaxies Stars",
	"Player_1": "Forster AVL (H)",
	"Player_2": "Konsa SOU (A)",
	"Player_3": "Cancelo SHU (H)",
	"Player_4": "Digne 6",
	"Player_5": "Salah WHU (A)$ captain",
	"Player_6": "Zaha WOL (H)",
	"Player_7": "Sterling SHU (H)",
	"Player_8": "Son BHA (A)",
	"Player_9": "Sigurdsson 2",
	"Player_10": "Watkins SOU (A)",
	"Player_11": "Martial ARS (A)",
	"Player_12": "Leno MUN (H)",
	"Player_13": "Kilman CRY (A)",
	"Player_14": "Brewster MCI (A)",
	"Player_15": "Walker-Peters AVL (H)",
	"SXL": "8",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "Okdenri Longchari",
	"Teams": "Happy Williams",
	"Player_1": "Martínez SOU (A)",
	"Player_2": "Dias SHU (H)",
	"Player_3": "Dier BHA (A)",
	"Player_4": "Mitchell WOL (H)",
	"Player_5": "Soucek LIV (H)",
	"Player_6": "Salah WHU (A)",
	"Player_7": "Fernandes ARS (A)",
	"Player_8": "Sterling SHU (H)$ captain",
	"Player_9": "Grealish SOU (A)",
	"Player_10": "Wilson 2",
	"Player_11": "Antonio LIV (H)",
	"Player_12": "McCarthy AVL (H)",
	"Player_13": "Bamford LEI (A)",
	"Player_14": "Dunk TOT (H)",
	"Player_15": "Coufal LIV (H)",
	"SXL": "2",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Omkar Subba",
	"Teams": "Omk09",
	"Player_1": "Lloris BHA (A)",
	"Player_2": "Stones SHU (H)",
	"Player_3": "Bednarek AVL (H)",
	"Player_4": "Justin LEE (H)",
	"Player_5": "Robertson WHU (A)",
	"Player_6": "Salah WHU (A)",
	"Player_7": "Grealish SOU (A)",
	"Player_8": "Son BHA (A)",
	"Player_9": "Fernandes ARS (A)",
	"Player_10": "Gündogan SHU (H)$ captain",
	"Player_11": "Calvert-Lewin 2",
	"Player_12": "Nyland SOU (A)",
	"Player_13": "Wilson 2",
	"Player_14": "Bamford LEI (A)",
	"Player_15": "Kilman CRY (A)",
	"SXL": "2",
	"Bench": "2",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Abhijeet Singh",
	"Teams": "Impact Creators",
	"Player_1": "McCarthy AVL (H)",
	"Player_2": "Justin LEE (H)",
	"Player_3": "Cresswell LIV (H)",
	"Player_4": "Maguire ARS (A)",
	"Player_5": "Kilman CRY (A)",
	"Player_6": "Fernandes ARS (A)",
	"Player_7": "Maddison LEE (H)",
	"Player_8": "Salah WHU (A)",
	"Player_9": "Sterling SHU (H)$ captain",
	"Player_10": "Bamford LEI (A)",
	"Player_11": "Calvert-Lewin 2",
	"Player_12": "Martin LIV (H)",
	"Player_13": "Wilson 2",
	"Player_14": "Riedewald WOL (H)",
	"Player_15": "Johnson LIV (H)",
	"SXL": "2",
	"Bench": "2",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Ashish Subba",
	"Teams": "GUSTAVOUS GUNNER",
	"Player_1": "McCarthy AVL (H)",
	"Player_2": "Cresswell LIV (H)",
	"Player_3": "Chilwell BUR (H)",
	"Player_4": "Justin LEE (H)",
	"Player_5": "Barnes LEE (H)",
	"Player_6": "Grealish SOU (A)",
	"Player_7": "Maddison LEE (H)",
	"Player_8": "Mané WHU (A)",
	"Player_9": "Fernandes ARS (A)",
	"Player_10": "Bamford LEI (A)",
	"Player_11": "Lacazette MUN (H)$ captain",
	"Player_12": "Martínez SOU (A)",
	"Player_13": "Dallas LEI (A)",
	"Player_14": "Alioski LEI (A)",
	"Player_15": "Davis SOU (A)",
	"SXL": "0",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Nitesh Singh",
	"Teams": "Danapur United",
	"Player_1": "Martínez SOU (A)",
	"Player_2": "Mee CHE (A)",
	"Player_3": "Dier BHA (A)",
	"Player_4": "Saïss CRY (A)",
	"Player_5": "Cresswell LIV (H)",
	"Player_6": "Salah WHU (A)$ captain",
	"Player_7": "Grealish SOU (A)",
	"Player_8": "Son BHA (A)",
	"Player_9": "Fernandes ARS (A)",
	"Player_10": "Saka MUN (H)",
	"Player_11": "Bamford LEI (A)",
	"Player_12": "Areola WBA (A)",
	"Player_13": "Keane 5",
	"Player_14": "Huggins LEI (A)",
	"Player_15": "Diaby FUL (H)",
	"SXL": "0",
	"Bench": "5",
	"Count  ": "1( 0+1 )"
}, {
	"manager_Name": "Raj Kanango",
	"Teams": "Dream Killer",
	"Player_1": "Martínez SOU (A)",
	"Player_2": "Cancelo SHU (H)",
	"Player_3": "Dier BHA (A)",
	"Player_4": "Stones SHU (H)",
	"Player_5": "Fernandes ARS (A)",
	"Player_6": "Grealish SOU (A)",
	"Player_7": "Salah WHU (A)$ captain",
	"Player_8": "Foden SHU (H)",
	"Player_9": "Firmino WHU (A)",
	"Player_10": "Bamford LEI (A)",
	"Player_11": "Calvert-Lewin 2",
	"Player_12": "Steer SOU (A)",
	"Player_13": "Dallas LEI (A)",
	"Player_14": "Burke MCI (A)",
	"Player_15": "Neco Williams WHU (A)",
	"SXL": "2",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Sahil Lampard",
	"Teams": "Marx 11",
	"Player_1": "Martínez SOU (A)",
	"Player_2": "Bertrand AVL (H)",
	"Player_3": "Reguilón BHA (A)",
	"Player_4": "Robertson WHU (A)",
	"Player_5": "Grealish SOU (A)",
	"Player_6": "Mahrez SHU (H)",
	"Player_7": "Son BHA (A)",
	"Player_8": "Fernandes ARS (A)$ captain",
	"Player_9": "Klich LEI (A)",
	"Player_10": "Bamford LEI (A)",
	"Player_11": "Kane BHA (A)",
	"Player_12": "Ryan MUN (H)",
	"Player_13": "Justin LEE (H)",
	"Player_14": "Delap SHU (H)",
	"Player_15": "Casey LEI (A)",
	"SXL": "0",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Pema Sherpa",
	"Teams": "CottonMouth XI",
	"Player_1": "Martínez SOU (A)",
	"Player_2": "Justin LEE (H)",
	"Player_3": "Stones SHU (H)",
	"Player_4": "Cancelo SHU (H)",
	"Player_5": "Son BHA (A)",
	"Player_6": "Bernardo Silva SHU (H)",
	"Player_7": "Barnes LEE (H)",
	"Player_8": "Fernandes ARS (A)",
	"Player_9": "Bamford LEI (A)",
	"Player_10": "Werner BUR (H)$ captain",
	"Player_11": "Antonio LIV (H)",
	"Player_12": "Button FUL (H)",
	"Player_13": "Maddison LEE (H)",
	"Player_14": "Tierney MUN (H)",
	"Player_15": "Cresswell LIV (H)",
	"SXL": "0",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "pranam rai",
	"Teams": "SYAKREE F.C.",
	"Player_1": "Guaita WOL (H)",
	"Player_2": "Chilwell BUR (H)",
	"Player_3": "Stones SHU (H)",
	"Player_4": "Targett SOU (A)",
	"Player_5": "Robertson WHU (A)",
	"Player_6": "Foden SHU (H)",
	"Player_7": "Barnes LEE (H)",
	"Player_8": "Mané WHU (A)",
	"Player_9": "Son BHA (A)",
	"Player_10": "Saka MUN (H)",
	"Player_11": "Lacazette MUN (H)$ captain",
	"Player_12": "Martínez SOU (A)",
	"Player_13": "Johnson LIV (H)",
	"Player_14": "Bamford LEI (A)",
	"Player_15": "Davis SOU (A)",
	"SXL": "0",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Regean Lama",
	"Teams": "Busby Baby",
	"Player_1": "Meslier LEI (A)",
	"Player_2": "Dallas LEI (A)",
	"Player_3": "Coufal LIV (H)",
	"Player_4": "Justin LEE (H)",
	"Player_5": "Salah WHU (A)",
	"Player_6": "Sterling SHU (H)$ captain",
	"Player_7": "Soucek LIV (H)",
	"Player_8": "Fernandes ARS (A)",
	"Player_9": "Son BHA (A)",
	"Player_10": "Bamford LEI (A)",
	"Player_11": "Antonio LIV (H)",
	"Player_12": "McCarthy AVL (H)",
	"Player_13": "Brewster MCI (A)",
	"Player_14": "Walker-Peters AVL (H)",
	"Player_15": "Taylor CHE (A)",
	"SXL": "0",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Han Sing",
	"Teams": "hansing",
	"Player_1": "de Gea ARS (A)",
	"Player_2": "Mitchell WOL (H)",
	"Player_3": "Dias SHU (H)",
	"Player_4": "Stones SHU (H)",
	"Player_5": "Fernandes ARS (A)",
	"Player_6": "Salah WHU (A)",
	"Player_7": "Foden SHU (H)",
	"Player_8": "Son BHA (A)$ captain",
	"Player_9": "Soucek LIV (H)",
	"Player_10": "Calvert-Lewin 2",
	"Player_11": "Bamford LEI (A)",
	"Player_12": "Nyland SOU (A)",
	"Player_13": "Kane BHA (A)",
	"Player_14": "Lowton CHE (A)",
	"Player_15": "Coufal LIV (H)",
	"SXL": "2",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Sanjeev Kumar",
	"Teams": "mendal11",
	"Player_1": "Ederson SHU (H)",
	"Player_2": "Justin LEE (H)",
	"Player_3": "James BUR (H)",
	"Player_4": "Stones SHU (H)",
	"Player_5": "Grealish SOU (A)",
	"Player_6": "Son BHA (A)$ captain",
	"Player_7": "Fernandes ARS (A)",
	"Player_8": "Rashford ARS (A)",
	"Player_9": "Gündogan SHU (H)",
	"Player_10": "Watkins SOU (A)",
	"Player_11": "Kane BHA (A)",
	"Player_12": "Martin LIV (H)",
	"Player_13": "Adams AVL (H)",
	"Player_14": "Coufal LIV (H)",
	"Player_15": "Mitchell WOL (H)",
	"SXL": "0",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Ashish Rai",
	"Teams": "goooooooners",
	"Player_1": "Areola WBA (A)",
	"Player_2": "Cresswell LIV (H)",
	"Player_3": "Alexander-Arnold WHU (A)",
	"Player_4": "Cancelo SHU (H)",
	"Player_5": "Son BHA (A)$ captain",
	"Player_6": "Lookman WBA (A)",
	"Player_7": "Maddison LEE (H)",
	"Player_8": "Foden SHU (H)",
	"Player_9": "Salah WHU (A)",
	"Player_10": "Calvert-Lewin 2",
	"Player_11": "Bamford LEI (A)",
	"Player_12": "Johnstone FUL (H)",
	"Player_13": "Antonio LIV (H)",
	"Player_14": "Robinson WBA (A)",
	"Player_15": "Pieters CHE (A)",
	"SXL": "2",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Ravish Verma",
	"Teams": "Little Chilli FC",
	"Player_1": "Sánchez TOT (H)",
	"Player_2": "Dias SHU (H)",
	"Player_3": "Neco Williams WHU (A)",
	"Player_4": "Dallas LEI (A)",
	"Player_5": "Fernandes ARS (A)",
	"Player_6": "Gündogan SHU (H)",
	"Player_7": "Son BHA (A)",
	"Player_8": "Salah WHU (A)",
	"Player_9": "Wilson 2",
	"Player_10": "Bamford LEI (A)",
	"Player_11": "Calvert-Lewin 4$ captain",
	"Player_12": "Button FUL (H)",
	"Player_13": "Walker-Peters AVL (H)",
	"Player_14": "Cresswell LIV (H)",
	"Player_15": "Burke MCI (A)",
	"SXL": "6",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Bishal Rai",
	"Teams": "Gooner for Life",
	"Player_1": "Martínez SOU (A)",
	"Player_2": "Chilwell BUR (H)",
	"Player_3": "Dias SHU (H)",
	"Player_4": "Robertson WHU (A)",
	"Player_5": "Raphinha LEI (A)",
	"Player_6": "Fernandes ARS (A)",
	"Player_7": "Son BHA (A)",
	"Player_8": "Salah WHU (A)$ captain",
	"Player_9": "Grealish SOU (A)",
	"Player_10": "Bamford LEI (A)",
	"Player_11": "Watkins SOU (A)",
	"Player_12": "Fabianski LIV (H)",
	"Player_13": "Justin LEE (H)",
	"Player_14": "Cresswell LIV (H)",
	"Player_15": "Brewster MCI (A)",
	"SXL": "0",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}]