var s = [
  {
    "manager_Name": "1,250( 23,478 ) TotalXfr : 17",
    "Teams": "Lorrainesson( Lorraine Busuttil )",
    "SXL": "Malta",
    "Latp": "81",
    "Player_1": "Sels\r 8",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Lumley\r 0",
    "Player_13": "Semenyo\r 3",
    "Player_14": "A\u00EFt-Nouri\r 6",
    "Player_7": "Palmer\r 10",
    "Player_2": "J.Timber\r 9",
    "Player_5": "Gordon\r 10",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Hall\r 6",
    "Player_8": "Amad\r 2",
    "Player_9": "Isak\r 8",
    "Player_15": "Okoli\r 1"
  },
  {
    "manager_Name": "1,226( 69,908 ) TotalXfr : 14",
    "Teams": "The Bees( Tove Ronneb\u00E4ck )",
    "SXL": "Malta",
    "Latp": "60",
    "Player_1": "Raya\r 6",
    "Player_11": "Isak\r 8",
    "Player_10": "G.Jesus\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Luis D\u00EDaz\r 0",
    "Player_14": "Hall\r 6",
    "Player_7": "Enzo\r 2",
    "Player_2": "Gabriel\r 6",
    "Player_5": "Palmer\r 10",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Alexander-Arnold\r 2",
    "Player_4": "Gvardiol\r 2",
    "Player_8": "Rogers\r 2",
    "Player_9": "Wissa\r 2",
    "Player_15": "Harwood-Bellis\r 2"
  },
  {
    "manager_Name": "1,199( 195,194 ) TotalXfr : 17",
    "Teams": "Udogie\u0027s Doggies( Claude Taliana )",
    "SXL": "Malta",
    "Latp": "60",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Haaland\r 0",
    "Player_10": "Wood\r 2",
    "Player_12": "Flekken\r 3",
    "Player_13": "Enzo\r 2",
    "Player_14": "Pedro Porro\r 1",
    "Player_7": "Amad\r 2",
    "Player_2": "J.Timber\r 9",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Palmer\r 10",
    "Player_3": "Kerkez\r 6",
    "Player_4": "Aina\r 6",
    "Player_8": "Bruno G.\r 3",
    "Player_9": "Strand Larsen\r 2",
    "Player_15": "Young\r 0"
  },
  {
    "manager_Name": "1,181( 341,960 ) TotalXfr : 15",
    "Teams": "Los Blancos( Eamonn Mifsud )",
    "SXL": "Malta",
    "Latp": "71",
    "Player_1": "Raya\r 6",
    "Player_11": "Isak\r 8",
    "Player_10": "Cunha\r 12",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Jo\u00E3o Pedro\r 2",
    "Player_14": "Konsa\r 1",
    "Player_7": "Palmer\r 10",
    "Player_2": "Lewis\r 2",
    "Player_5": "Rogers\r 2",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Robinson\r 1",
    "Player_8": "\u00D8degaard\r 3",
    "Player_9": "Mbeumo\r 3",
    "Player_15": "Van den Berg\r 0"
  },
  {
    "manager_Name": "1,173( 433,627 ) TotalXfr : 19",
    "Teams": "NoHopeFC( John Maguire )",
    "SXL": "Malta",
    "Latp": "65",
    "Player_1": "Flekken\r 3",
    "Player_11": "Isak\r 8",
    "Player_10": "Cunha\r 12",
    "Player_12": "Valdimarsson\r 1",
    "Player_13": "Robinson\r 1",
    "Player_14": "Davis\r 1",
    "Player_7": "B.Fernandes\r -2",
    "Player_2": "Colwill\r 4",
    "Player_5": "Mbeumo\r 3",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Harwood-Bellis\r 2",
    "Player_4": "Saliba\r 7",
    "Player_8": "Maddison\r 0",
    "Player_9": "Palmer\r 10",
    "Player_15": "Vardy\r 0"
  },
  {
    "manager_Name": "1,165( 530,685 ) TotalXfr : 17",
    "Teams": "FC Pek( Erik Lindberg )",
    "SXL": "Sweden",
    "Latp": "55",
    "Player_1": "Raya\r 6",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Mu\u00F1oz\r 6",
    "Player_14": "Hall\r 6",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Saliba\r 7",
    "Player_5": "Martinelli\r 3",
    "Player_6": "Enzo\r 2",
    "Player_3": "Alexander-Arnold\r 2",
    "Player_4": "Gomez\r 1",
    "Player_8": "Palmer\r 10",
    "Player_9": "Foden\r 2",
    "Player_15": "Lankshear\r 0"
  },
  {
    "manager_Name": "1,156( 660,874 ) TotalXfr : 17",
    "Teams": "Salahvation Army( Tom Atkinson )",
    "SXL": "Malta",
    "Latp": "61",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Isak\r 8",
    "Player_10": "N.Jackson\r 2",
    "Player_12": "Slicker\r 0",
    "Player_13": "Lewis\r 2",
    "Player_14": "Winks\r 2",
    "Player_7": "Palmer\r 10",
    "Player_2": "Gvardiol\r 2",
    "Player_5": "Rogers\r 2",
    "Player_6": "Mitoma\r 3",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Collins\r 6",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "1,152( 725,127 ) TotalXfr : 17",
    "Teams": "Ajax CT( Dimitrios Siderakis )",
    "SXL": "Malta",
    "Latp": "66",
    "Player_1": "Sels\r 8",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Watkins\r 1",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "Carvalho\r 0",
    "Player_14": "Welbeck\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Saliba\r 7",
    "Player_5": "Mazraoui\r 1",
    "Player_6": "Murillo\r 8",
    "Player_3": "Pedro Porro\r 1",
    "Player_4": "Gu\u00E9hi\r 7",
    "Player_8": "Palmer\r 10",
    "Player_9": "Mbeumo\r 3",
    "Player_15": "Luis D\u00EDaz\r 0"
  },
  {
    "manager_Name": "1,149( 780,471 ) TotalXfr : 19",
    "Teams": "Joga Bonito( Christophe Peixoto )",
    "SXL": "Hungary",
    "Latp": "64",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Isak\r 8",
    "Player_12": "Flekken\r 3",
    "Player_13": "Evanilson\r 1",
    "Player_14": "Castagne\r 5",
    "Player_7": "Palmer\r 10",
    "Player_2": "Gabriel\r 6",
    "Player_5": "Alexander-Arnold\r 2",
    "Player_6": "\u00D8degaard\r 3",
    "Player_3": "Colwill\r 4",
    "Player_4": "Hall\r 6",
    "Player_8": "Mitoma\r 3",
    "Player_9": "M.Salah\r 18",
    "Player_15": "Smith Rowe\r 0"
  },
  {
    "manager_Name": "1,143( 885,208 ) TotalXfr : 18",
    "Teams": "Ctrl Alt De Ligt( Marlon Vella )",
    "SXL": "Malta",
    "Latp": "59",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Ra\u00FAl\r 2",
    "Player_10": "Isak\r 8",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Faes\r 0",
    "Player_14": "Welbeck\r 0",
    "Player_7": "Rogers\r 2",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "B.Fernandes\r -2",
    "Player_6": "Mbeumo\r 3",
    "Player_3": "J.Timber\r 9",
    "Player_4": "Milenkovi\u0107\r 6",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Palmer\r 10",
    "Player_15": "A\u00EFt-Nouri\r 6"
  },
  {
    "manager_Name": "1,142( 903,607 ) TotalXfr : 18",
    "Teams": "JDT Out( Filip Larsson )",
    "SXL": "Malta",
    "Latp": "63",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Isak\r 8",
    "Player_10": "G.Jesus\r 2",
    "Player_12": "Flekken\r 3",
    "Player_13": "Luis D\u00EDaz\r 0",
    "Player_14": "Aina\r 6",
    "Player_7": "J.Murphy\r 6",
    "Player_2": "Lewis\r 2",
    "Player_5": "Palmer\r 10",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Gabriel\r 6",
    "Player_4": "J.Timber\r 9",
    "Player_8": "B.Fernandes\r -2",
    "Player_9": "Strand Larsen\r 2",
    "Player_15": "Greaves\r 2"
  },
  {
    "manager_Name": "1,138( 974,158 ) TotalXfr : 15",
    "Teams": "Kinder Mbeumo( Gerson Seguna )",
    "SXL": "Malta",
    "Latp": "70",
    "Player_1": "Raya\r 6",
    "Player_11": "Isak\r 8",
    "Player_10": "Cunha\r 12",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Rogers\r 2",
    "Player_14": "Hall\r 6",
    "Player_7": "Palmer\r 10",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Gvardiol\r 2",
    "Player_6": "I.Sarr\r 3",
    "Player_3": "Gomez\r 1",
    "Player_4": "Gabriel\r 6",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Wood\r 2",
    "Player_15": "Dibling\r 1"
  },
  {
    "manager_Name": "1,135( 1,036,812 ) TotalXfr : 17",
    "Teams": "Tourinho FC( Alexis Touris )",
    "SXL": "Greece",
    "Latp": "46",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Wood\r 2",
    "Player_10": "Isak\r 8",
    "Player_12": "Henderson\r 7",
    "Player_13": "Saka\r 0",
    "Player_14": "Adama\r 2",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Pedro Porro\r 1",
    "Player_5": "Aina\r 6",
    "Player_6": "Johnson\r 2",
    "Player_3": "Dalot\r 1",
    "Player_4": "Gvardiol\r 2",
    "Player_8": "Mbeumo\r 3",
    "Player_9": "Evanilson\r 1",
    "Player_15": "Andersen\r 1"
  },
  {
    "manager_Name": "1,133( 1,075,785 ) TotalXfr : 16",
    "Teams": "Blue Core( Avinash Chatlani )",
    "SXL": "Malta",
    "Latp": "70",
    "Player_1": "Sels\r 8",
    "Player_11": "Isak\r 8",
    "Player_10": "N.Jackson\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Luis D\u00EDaz\r 0",
    "Player_14": "Robinson\r 1",
    "Player_7": "Enzo\r 2",
    "Player_2": "Gabriel\r 6",
    "Player_5": "Palmer\r 10",
    "Player_6": "Amad\r 2",
    "Player_3": "Hall\r 6",
    "Player_4": "Aina\r 6",
    "Player_8": "M.Salah\r 18",
    "Player_9": "G.Jesus\r 2",
    "Player_15": "Harwood-Bellis\r 2"
  },
  {
    "manager_Name": "1,132( 1,098,830 ) TotalXfr : 17",
    "Teams": "Fantasikonungen( Albin Jonsson )",
    "SXL": "Malta",
    "Latp": "59",
    "Player_1": "Fabianski\r 2",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Forster\r 2",
    "Player_13": "Semenyo\r 3",
    "Player_14": "Castagne\r 5",
    "Player_7": "Son\r 2",
    "Player_2": "Hall\r 6",
    "Player_5": "Bowen\r 8",
    "Player_6": "Palmer\r 10",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Cucurella\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "G.Jesus\r 2",
    "Player_15": "A\u00EFt-Nouri\r 6"
  },
  {
    "manager_Name": "1,130( 1,140,952 ) TotalXfr : 17",
    "Teams": "Lallish United( Melwin Holst )",
    "SXL": "Sweden",
    "Latp": "65",
    "Player_1": "Raya\r 6",
    "Player_11": "Isak\r 8",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Rogers\r 2",
    "Player_14": "Van Hecke\r 9",
    "Player_7": "Palmer\r 10",
    "Player_2": "Mu\u00F1oz\r 6",
    "Player_5": "I.Sarr\r 3",
    "Player_6": "Amad\r 2",
    "Player_3": "Virgil\r 2",
    "Player_4": "Gabriel\r 6",
    "Player_8": "M.Salah\r 18",
    "Player_9": "N.Jackson\r 2",
    "Player_15": "Davis\r 1"
  },
  {
    "manager_Name": "1,127( 1,213,300 ) TotalXfr : 20",
    "Teams": "klopp notch( Tobias Nocke )",
    "SXL": "Sweden",
    "Latp": "65",
    "Player_1": "Verbruggen\r 9",
    "Player_11": "G.Jesus\r 2",
    "Player_10": "Isak\r 8",
    "Player_12": "Kelleher\r 0",
    "Player_13": "Ra\u00FAl\r 2",
    "Player_14": "Estupi\u00F1an\r 6",
    "Player_7": "Mitoma\r 3",
    "Player_2": "Harwood-Bellis\r 2",
    "Player_5": "Palmer\r 10",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Colwill\r 4",
    "Player_4": "Gomez\r 1",
    "Player_8": "Maddison\r 0",
    "Player_9": "Bowen\r 8",
    "Player_15": "Van den Berg\r 0"
  },
  {
    "manager_Name": "1,121( 1,353,682 ) TotalXfr : 24",
    "Teams": "Biancoverde Utd 4.0( Michael Keramas )",
    "SXL": "Greece",
    "Latp": "71",
    "Player_1": "Raya\r 6",
    "Player_11": "Isak\r 8",
    "Player_10": "Cunha\r 12",
    "Player_12": "Valdimarsson\r 1",
    "Player_13": "Jo\u00E3o Pedro\r 2",
    "Player_14": "Aina\r 6",
    "Player_7": "I.Sarr\r 3",
    "Player_2": "Saliba\r 7",
    "Player_5": "B.Fernandes\r -2",
    "Player_6": "Palmer\r 10",
    "Player_3": "Robinson\r 1",
    "Player_4": "Kerkez\r 6",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Kulusevski\r 2",
    "Player_15": "Johnson\r 2"
  },
  {
    "manager_Name": "1,119( 1,398,831 ) TotalXfr : 22",
    "Teams": "Im Sorry Nic Jackson( Jon Briscoe White )",
    "SXL": "Malta",
    "Latp": "61",
    "Player_1": "Sels\r 8",
    "Player_11": "Isak\r 8",
    "Player_10": "G.Jesus\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Luis D\u00EDaz\r 0",
    "Player_14": "A\u00EFt-Nouri\r 6",
    "Player_7": "Palmer\r 10",
    "Player_2": "Pedro Porro\r 1",
    "Player_5": "Semenyo\r 3",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Dalot\r 1",
    "Player_8": "Rogers\r 2",
    "Player_9": "Wood\r 2",
    "Player_15": "Vestergaard\r 0"
  },
  {
    "manager_Name": "1,115( 1,491,192 ) TotalXfr : 20",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "India",
    "Latp": "68",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Cunha\r 12",
    "Player_10": "G.Jesus\r 2",
    "Player_12": "Henderson\r 7",
    "Player_13": "Armstrong\r 2",
    "Player_14": "Dalot\r 1",
    "Player_7": "M.Salah\r 18",
    "Player_2": "J.Timber\r 9",
    "Player_5": "Johnson\r 2",
    "Player_6": "Kluivert\r 2",
    "Player_3": "Burn\r 6",
    "Player_4": "Saliba\r 7",
    "Player_8": "Palmer\r 10",
    "Player_9": "B.Fernandes\r -2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "1,114( 1,502,312 ) TotalXfr : 13",
    "Teams": "Matteo fc( Matteo Vella )",
    "SXL": "Malta",
    "Latp": "60",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Havertz\r 7",
    "Player_10": "Isak\r 8",
    "Player_12": "Leno\r 4",
    "Player_13": "Pedro Porro\r 1",
    "Player_14": "Konsa\r 1",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Gvardiol\r 2",
    "Player_5": "Rogers\r 2",
    "Player_6": "Palmer\r 10",
    "Player_3": "Hall\r 6",
    "Player_4": "Dalot\r 1",
    "Player_8": "Amad\r 2",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Mbeumo\r 3"
  },
  {
    "manager_Name": "1,114( 1,507,085 ) TotalXfr : 17",
    "Teams": "Crvena Zvezda( Dejan Mrdanov )",
    "SXL": "Malta",
    "Latp": "65",
    "Player_1": "Raya\r 6",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Wood\r 2",
    "Player_12": "Arrizabalaga\r 8",
    "Player_13": "Luis D\u00EDaz\r 0",
    "Player_14": "Pedro Porro\r 1",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Gabriel\r 6",
    "Player_5": "Mbeumo\r 3",
    "Player_6": "Maddison\r 0",
    "Player_3": "Milenkovi\u0107\r 6",
    "Player_4": "Colwill\r 4",
    "Player_8": "Gibbs-White\r 6",
    "Player_9": "Cunha\r 12",
    "Player_15": "Tarkowski\r 2"
  },
  {
    "manager_Name": "1,111( 1,584,491 ) TotalXfr : 18",
    "Teams": "\u0106umura\u0161i( Aleksandar Deletic )",
    "SXL": "Serbia",
    "Latp": "83",
    "Player_1": "Raya\r 6",
    "Player_11": "Wood\r 2",
    "Player_10": "Cunha\r 12",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "Digne\r 1",
    "Player_14": "Ra\u00FAl\r 2",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Virgil\r 2",
    "Player_5": "M.Salah\r 27",
    "Player_6": "Palmer\r 10",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Hall\r 6",
    "Player_8": "J.Murphy\r 6",
    "Player_9": "Mitoma\r 3",
    "Player_15": "Gu\u00E9hi\r 7"
  },
  {
    "manager_Name": "1,109( 1,630,995 ) TotalXfr : 17",
    "Teams": "MainooInTheBank( Thanasis Fouras )",
    "SXL": "Greece",
    "Latp": "56",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "N.Jackson\r 2",
    "Player_12": "Matthews\r 0",
    "Player_13": "Rogers\r 2",
    "Player_14": "Robinson\r 1",
    "Player_7": "Palmer\r 10",
    "Player_2": "Pedro Porro\r 1",
    "Player_5": "B.Fernandes\r -2",
    "Player_6": "Amad\r 2",
    "Player_3": "Hall\r 6",
    "Player_4": "Saliba\r 7",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Isak\r 8",
    "Player_15": "Greaves\r 2"
  },
  {
    "manager_Name": "1,107( 1,674,982 ) TotalXfr : 5",
    "Teams": "Nachos( Melvin Xuereb )",
    "SXL": "Malta",
    "Latp": "52",
    "Player_1": "Areola\r 1",
    "Player_11": "Haaland\r 0",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Semenyo\r 3",
    "Player_14": "Andersen\r 1",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Eze\r 2",
    "Player_6": "Palmer\r 10",
    "Player_3": "Estupi\u00F1an\r 6",
    "Player_4": "Saliba\r 7",
    "Player_8": "Damsgaard\r 3",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "1,104( 1,767,450 ) TotalXfr : 20",
    "Teams": "LxFxC( Ervin Rigo )",
    "SXL": "Malta",
    "Latp": "61",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Isak\r 8",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Jos\u00E9 S\u00E1\r 8",
    "Player_13": "Pedro Porro\r 1",
    "Player_14": "Kerkez\r 6",
    "Player_7": "Johnson\r 2",
    "Player_2": "J.Timber\r 9",
    "Player_5": "Mbeumo\r 3",
    "Player_6": "Semenyo\r 3",
    "Player_3": "Virgil\r 2",
    "Player_4": "Gvardiol\r 2",
    "Player_8": "Palmer\r 10",
    "Player_9": "M.Salah\r 18",
    "Player_15": "Wissa\r 2"
  },
  {
    "manager_Name": "1,095( 2,001,905 ) TotalXfr : 18",
    "Teams": "Wan Utd( Mindaugas Grigaitis )",
    "SXL": "Lithuania",
    "Latp": "71",
    "Player_1": "Raya\r 6",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Havertz\r 7",
    "Player_12": "Vicario\r 0",
    "Player_13": "Pedro Porro\r 1",
    "Player_14": "Iwobi\r 2",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Kerkez\r 6",
    "Player_5": "Szoboszlai\r 0",
    "Player_6": "Mitoma\r 3",
    "Player_3": "Gvardiol\r 2",
    "Player_4": "Saliba\r 7",
    "Player_8": "Bowen\r 8",
    "Player_9": "Cunha\r 12",
    "Player_15": "Robinson\r 1"
  },
  {
    "manager_Name": "1,093( 2,046,509 ) TotalXfr : 10",
    "Teams": "BienRayados( Luis Ricardo J\u00E1uregui V )",
    "SXL": "England",
    "Latp": "54",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Havertz\r 7",
    "Player_10": "Ra\u00FAl\r 2",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "J.Araujo\r 0",
    "Player_14": "McNeil\r 0",
    "Player_7": "Saka\r 0",
    "Player_2": "Gabriel\r 6",
    "Player_5": "Virgil\r 2",
    "Player_6": "Palmer\r 10",
    "Player_3": "Murillo\r 8",
    "Player_4": "Pau\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Duran\r -2",
    "Player_15": "Madueke\r 0"
  },
  {
    "manager_Name": "1,087( 2,219,222 ) TotalXfr : 17",
    "Teams": "FC Qvantas( Johan Hammarstrom )",
    "SXL": "Sweden",
    "Latp": "89",
    "Player_1": "Raya\r 6",
    "Player_11": "Wissa\r 2",
    "Player_10": "Cunha\r 12",
    "Player_12": "Sels\r 8",
    "Player_13": "Madueke\r 0",
    "Player_14": "Burn\r 6",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Saliba\r 7",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Palmer\r 10",
    "Player_3": "Robinson\r 1",
    "Player_4": "Gabriel\r 6",
    "Player_8": "Rogers\r 2",
    "Player_9": "Wood\r 2",
    "Player_15": "Aina\r 6"
  },
  {
    "manager_Name": "1,082( 2,356,299 ) TotalXfr : 15",
    "Teams": "Cursed Technique( Ini Etienam )",
    "SXL": "Estonia",
    "Latp": "58",
    "Player_1": "Pickford\r 9",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Cunha\r 12",
    "Player_12": "Flekken\r 3",
    "Player_13": "Luis D\u00EDaz\r 0",
    "Player_14": "Saka\r 0",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Virgil\r 2",
    "Player_5": "Martinez\r 1",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Pedro Porro\r 1",
    "Player_4": "Aina\r 6",
    "Player_8": "Kulusevski\r 2",
    "Player_9": "Wood\r 2",
    "Player_15": "Digne\r 1"
  },
  {
    "manager_Name": "1,078( 2,483,688 ) TotalXfr : 20",
    "Teams": "Guglielmo( Jonas Megert )",
    "SXL": "Sweden",
    "Latp": "65",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Wood\r 2",
    "Player_10": "Isak\r 8",
    "Player_12": "Turner\r 0",
    "Player_13": "Luis D\u00EDaz\r 0",
    "Player_14": "Winks\r 2",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Konsa\r 1",
    "Player_5": "Lewis\r 2",
    "Player_6": "Rogers\r 2",
    "Player_3": "Alexander-Arnold\r 2",
    "Player_4": "Gabriel\r 6",
    "Player_8": "Palmer\r 10",
    "Player_9": "Cunha\r 12",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "1,077( 2,507,243 ) TotalXfr : 18",
    "Teams": "20x MU( John Tiltmann )",
    "SXL": "Malta",
    "Latp": "57",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Cunha\r 12",
    "Player_10": "Isak\r 8",
    "Player_12": "Martinez\r 2",
    "Player_13": "Madueke\r 0",
    "Player_14": "Saka\r 0",
    "Player_7": "Enzo\r 2",
    "Player_2": "Virgil\r 2",
    "Player_5": "Saliba\r 7",
    "Player_6": "Mazraoui\r 1",
    "Player_3": "Robinson\r 1",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Wood\r 2",
    "Player_15": "McNeil\r 0"
  },
  {
    "manager_Name": "1,076( 2,542,926 ) TotalXfr : 21",
    "Teams": "Gidia KK( Aggelos Flamiatos )",
    "SXL": "Greece",
    "Latp": "61",
    "Player_1": "Verbruggen\r 9",
    "Player_11": "Isak\r 8",
    "Player_10": "N.Jackson\r 2",
    "Player_12": "Flekken\r 3",
    "Player_13": "Robinson\r 1",
    "Player_14": "Murillo\r 8",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Burn\r 6",
    "Player_5": "Rogers\r 2",
    "Player_6": "Mbeumo\r 3",
    "Player_3": "Virgil\r 2",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Palmer\r 10",
    "Player_9": "Maddison\r 0",
    "Player_15": "Delap\r 2"
  },
  {
    "manager_Name": "1,065( 2,847,892 ) TotalXfr : 15",
    "Teams": "HUNdorito( Adam Rajki )",
    "SXL": "Hungary",
    "Latp": "70",
    "Player_1": "Raya\r 6",
    "Player_11": "Cunha\r 12",
    "Player_10": "Wood\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Kluivert\r 2",
    "Player_14": "Sou\u010Dek\r 2",
    "Player_7": "M.Salah\r 9",
    "Player_2": "Pedro Porro\r 1",
    "Player_5": "Kerkez\r 6",
    "Player_6": "Mitoma\r 3",
    "Player_3": "Gvardiol\r 2",
    "Player_4": "Saliba\r 7",
    "Player_8": "Palmer\r 20",
    "Player_9": "N.Jackson\r 2",
    "Player_15": "Milenkovi\u0107\r 6"
  },
  {
    "manager_Name": "1,060( 2,996,238 ) TotalXfr : 16",
    "Teams": "Hakuna Mateta( Jason Evans )",
    "SXL": "Malta",
    "Latp": "52",
    "Player_1": "Raya\r 6",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Isak\r 8",
    "Player_12": "Turner\r 0",
    "Player_13": "Armstrong\r 0",
    "Player_14": "Burgess\r 0",
    "Player_7": "Saka\r 0",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Amad\r 2",
    "Player_6": "Semenyo\r 3",
    "Player_3": "Gvardiol\r 2",
    "Player_4": "Saliba\r 7",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Thomas\r 0"
  },
  {
    "manager_Name": "1,054( 3,179,145 ) TotalXfr : 18",
    "Teams": "Starship( Olumide Okedusi )",
    "SXL": "Estonia",
    "Latp": "58",
    "Player_1": "Raya\r 6",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Amad\r 2",
    "Player_14": "Burn\r 6",
    "Player_7": "Rogers\r 2",
    "Player_2": "Virgil\r 2",
    "Player_5": "Palmer\r 10",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Pedro Porro\r 1",
    "Player_4": "Robinson\r 1",
    "Player_8": "Foden\r 2",
    "Player_9": "Cunha\r 12",
    "Player_15": "A\u00EFt-Nouri\r 6"
  },
  {
    "manager_Name": "1,039( 3,620,351 ) TotalXfr : 18",
    "Teams": "Red Tigers FC( George Vepkhvadze )",
    "SXL": "Georgia",
    "Latp": "71",
    "Player_1": "D\u00FAbravka\r 6",
    "Player_11": "Havertz\r 7",
    "Player_10": "Isak\r 8",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Robinson\r 1",
    "Player_14": "Van den Berg\r 0",
    "Player_7": "Gordon\r 10",
    "Player_2": "Gabriel\r 6",
    "Player_5": "\u00D8degaard\r 6",
    "Player_6": "Palmer\r 10",
    "Player_3": "Kerkez\r 6",
    "Player_4": "Gusto\r 1",
    "Player_8": "Bowen\r 8",
    "Player_9": "Semenyo\r 3",
    "Player_15": "Watkins\r 1"
  },
  {
    "manager_Name": "1,034( 3,761,147 ) TotalXfr : 16",
    "Teams": "Massilia( Daniel Borg )",
    "SXL": "Malta",
    "Latp": "71",
    "Player_1": "Flekken\r 3",
    "Player_11": "Cunha\r 12",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Martinez\r 2",
    "Player_13": "Rogers\r 2",
    "Player_14": "Konsa\r 1",
    "Player_7": "Palmer\r 20",
    "Player_2": "Aina\r 6",
    "Player_5": "Mbeumo\r 3",
    "Player_6": "J.Murphy\r 6",
    "Player_3": "Virgil\r 2",
    "Player_4": "Gabriel\r 6",
    "Player_8": "M.Salah\r 9",
    "Player_9": "N.Jackson\r 2",
    "Player_15": "A\u00EFt-Nouri\r 6"
  },
  {
    "manager_Name": "1,028( 3,935,090 ) TotalXfr : 16",
    "Teams": "FC Lokomotiv Sliema( Philip H\u00E5kansson )",
    "SXL": "Malta",
    "Latp": "47",
    "Player_1": "Raya\r 6",
    "Player_11": "Strand Larsen\r 2",
    "Player_10": "Solanke\r 2",
    "Player_12": "Valdimarsson\r 1",
    "Player_13": "Virgil\r 2",
    "Player_14": "Harwood-Bellis\r 2",
    "Player_7": "Johnson\r 2",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Semenyo\r 3",
    "Player_6": "Mitoma\r 3",
    "Player_3": "Colwill\r 4",
    "Player_4": "Gabriel\r 6",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Haaland\r 0",
    "Player_15": "Rogers\r 2"
  },
  {
    "manager_Name": "1,025( 4,012,916 ) TotalXfr : 0",
    "Teams": "KAMACIO FC( Francisco Camacho )",
    "SXL": "Malta",
    "Latp": "61",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Watkins\r 1",
    "Player_10": "Havertz\r 7",
    "Player_12": "Areola\r 1",
    "Player_13": "Saka\r 0",
    "Player_14": "Hill\r 0",
    "Player_7": "Gordon\r 10",
    "Player_2": "Mykolenko\r 1",
    "Player_5": "Palmer\r 20",
    "Player_6": "Foden\r 2",
    "Player_3": "Saliba\r 7",
    "Player_4": "Pedro Porro\r 1",
    "Player_8": "Bowen\r 8",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "1,024( 4,058,414 ) TotalXfr : 19",
    "Teams": "ThereWeLand( Haykel Mansour )",
    "SXL": "Malta",
    "Latp": "50",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 0",
    "Player_10": "Cunha\r 12",
    "Player_12": "Valdimarsson\r 1",
    "Player_13": "Smith Rowe\r 0",
    "Player_14": "Collins\r 6",
    "Player_7": "Gordon\r 10",
    "Player_2": "Gabriel\r 6",
    "Player_5": "\u00D8degaard\r 3",
    "Player_6": "Kulusevski\r 2",
    "Player_3": "Lewis\r 2",
    "Player_4": "Robinson\r 1",
    "Player_8": "Palmer\r 10",
    "Player_9": "N.Jackson\r 2",
    "Player_15": "Nedeljkovic\r 1"
  },
  {
    "manager_Name": "1,023( 4,079,647 ) TotalXfr : 16",
    "Teams": "Gambit( Nicola Frasca )",
    "SXL": "Malta",
    "Latp": "37",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "N.Jackson\r 4",
    "Player_12": "Pickford\r 9",
    "Player_13": "Ings\r 0",
    "Player_14": "Choudhury\r 0",
    "Player_7": "Palmer\r 10",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Pedro Porro\r 1",
    "Player_6": "Greaves\r 2",
    "Player_3": "Gvardiol\r 2",
    "Player_4": "Martinez\r 1",
    "Player_8": "M.Salah\r 9",
    "Player_9": "Son\r 2",
    "Player_15": "Smith Rowe\r 0"
  },
  {
    "manager_Name": "1,021( 4,129,255 ) TotalXfr : 2",
    "Teams": "Sparta( Andrew Spiteri )",
    "SXL": "Malta",
    "Latp": "48",
    "Player_1": "Raya\r 6",
    "Player_11": "Havertz\r 7",
    "Player_10": "Isak\r 8",
    "Player_12": "Steele\r 0",
    "Player_13": "Welbeck\r 0",
    "Player_14": "Zinchenko\r 0",
    "Player_7": "Foden\r 2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Nkunku\r 1",
    "Player_3": "Andersen\r 1",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Diogo J.\r 1",
    "Player_9": "Tielemans\r 1",
    "Player_15": "Cash\r 0"
  },
  {
    "manager_Name": "1,002( 4,665,191 ) TotalXfr : 0",
    "Teams": "Thebackstreetmoyes( Dave Clarke )",
    "SXL": "Ireland",
    "Latp": "43",
    "Player_1": "Raya\r 6",
    "Player_11": "Watkins\r 1",
    "Player_10": "Isak\r 16",
    "Player_12": "Bettinelli\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Cash\r 0",
    "Player_7": "B.Fernandes\r -2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Burn\r 6",
    "Player_6": "Eze\r 2",
    "Player_3": "Gvardiol\r 2",
    "Player_4": "Saliba\r 7",
    "Player_8": "Diogo J.\r 1",
    "Player_9": "Mainoo\r 2",
    "Player_15": "Cunha\r 12"
  },
  {
    "manager_Name": "998( 4,797,110 ) TotalXfr : 22",
    "Teams": "grenbenzen( Gren Kallasmaa )",
    "SXL": "Estonia",
    "Latp": "64",
    "Player_1": "Raya\r 6",
    "Player_11": "N.Jackson\r 2",
    "Player_10": "Gakpo\r 12",
    "Player_12": "Turner\r 0",
    "Player_13": "Tuanzebe\r 0",
    "Player_14": "Saka\r 0",
    "Player_7": "Gravenberch\r 2",
    "Player_2": "J.Timber\r 9",
    "Player_5": "Martinez\r 1",
    "Player_6": "Palmer\r 10",
    "Player_3": "Robinson\r 1",
    "Player_4": "Pedro Porro\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Wood\r 2",
    "Player_15": "McAteer\r 0"
  },
  {
    "manager_Name": "996( 4,847,205 ) TotalXfr : 18",
    "Teams": "Rekegutt United( Eirik Presttun )",
    "SXL": "Malta",
    "Latp": "30",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 0",
    "Player_10": "Isak\r 8",
    "Player_12": "Henderson\r 7",
    "Player_13": "Dibling\r 1",
    "Player_14": "A\u00EFt-Nouri\r 6",
    "Player_7": "Rogers\r 2",
    "Player_2": "Dalot\r 1",
    "Player_5": "Maddison\r 0",
    "Player_6": "M.Salah\r 9",
    "Player_3": "Harwood-Bellis\r 2",
    "Player_4": "Gvardiol\r 2",
    "Player_8": "Kluivert\r 2",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "983( 5,194,488 ) TotalXfr : 8",
    "Teams": "Maximum Efferton( Jonathan Harding )",
    "SXL": "Malta",
    "Latp": "51",
    "Player_1": "Areola\r 1",
    "Player_11": "Mateta\r 2",
    "Player_10": "Watkins\r 1",
    "Player_12": "Neto\r 0",
    "Player_13": "Romero\r 0",
    "Player_14": "Vardy\r 0",
    "Player_7": "Palmer\r 10",
    "Player_2": "Tarkowski\r 2",
    "Player_5": "Kova\u010Di\u0107\r 2",
    "Player_6": "Bowen\r 8",
    "Player_3": "Castagne\r 5",
    "Player_4": "Lewis\r 2",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Luis D\u00EDaz\r 0",
    "Player_15": "Van de Ven\r 0"
  },
  {
    "manager_Name": "978( 5,323,369 ) TotalXfr : 0",
    "Teams": "Chris FC( Chris Koufokotsios )",
    "SXL": "Greece",
    "Latp": "45",
    "Player_1": "Henderson\r 7",
    "Player_11": "Isak\r 16",
    "Player_10": "Haaland\r 0",
    "Player_12": "Valdimarsson\r 1",
    "Player_13": "Barco\r 0",
    "Player_14": "Saka\r 0",
    "Player_7": "Jota Silva\r 1",
    "Player_2": "Saliba\r 7",
    "Player_5": "Robinson\r 1",
    "Player_6": "Rogers\r 2",
    "Player_3": "Aina\r 6",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Eze\r 2",
    "Player_9": "Nkunku\r 1",
    "Player_15": "Wood\r 2"
  },
  {
    "manager_Name": "975( 5,422,076 ) TotalXfr : 20",
    "Teams": "Rolling Fernander( Adam Ruggier )",
    "SXL": "Malta",
    "Latp": "55",
    "Player_1": "Raya\r 6",
    "Player_11": "Wood\r 2",
    "Player_10": "N.Jackson\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Harwood-Bellis\r 2",
    "Player_14": "Barco\r 0",
    "Player_7": "Amad\r 2",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "M.Salah\r 9",
    "Player_6": "Palmer\r 20",
    "Player_3": "Saliba\r 7",
    "Player_4": "Gabriel\r 6",
    "Player_8": "B.Fernandes\r -2",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Yarmoliuk\r 0"
  },
  {
    "manager_Name": "973( 5,470,242 ) TotalXfr : 17",
    "Teams": "Bruno Fernax FC( Chris Zammit )",
    "SXL": "Malta",
    "Latp": "65",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Cunha\r 12",
    "Player_10": "Isak\r 8",
    "Player_12": "Pope\r 0",
    "Player_13": "Livramento\r 0",
    "Player_14": "Welbeck\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Kluivert\r 2",
    "Player_6": "Mbeumo\r 3",
    "Player_3": "Lewis\r 2",
    "Player_4": "Wan-Bissaka\r 9",
    "Player_8": "Palmer\r 10",
    "Player_9": "B.Fernandes\r -2",
    "Player_15": "Van de Ven\r 0"
  }
];