var s = [
  {
    "manager_Name": "1631294",
    "Teams": "REZEKI ZZDD",
    "SXL": "MY",
    "Latp": "27",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Watkins\r MUN (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Smith Rowe\r 1",
    "Player_14": "Faes\r 6",
    "Player_7": "Saka\r 8",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Mbeumo\r 7",
    "Player_6": "Palmer\r NFO (H)",
    "Player_3": "O\u0027Shea\r 0",
    "Player_4": "Konat\u00E9\r 6",
    "Player_8": "Winks\r 0",
    "Player_9": "Wood\r CHE (A)",
    "Player_15": "Aina\r CHE (A)"
  },
  {
    "manager_Name": "2686992",
    "Teams": "GuiuTakingTheMykh?!",
    "SXL": "US",
    "Latp": "29",
    "Player_1": "Raya\r 2",
    "Player_11": "Watkins\r MUN (H)",
    "Player_10": "Havertz\r 6",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Welbeck\r TOT (H)",
    "Player_14": "Nedeljkovic\r MUN (H)",
    "Player_7": "Eze\r 2",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "M.Salah\r 3",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Robinson\r 1",
    "Player_8": "Palmer\r NFO (H)",
    "Player_9": "Rogers\r MUN (H)",
    "Player_15": "Faes\r 6"
  },
  {
    "manager_Name": "1658398",
    "Teams": "ARC FC",
    "SXL": "IN",
    "Latp": "27",
    "Player_1": "Raya\r 2",
    "Player_11": "Vardy\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Ward\r 0",
    "Player_13": "Robinson\r 1",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "M.Salah\r 3",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Mbeumo\r 7",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Faes\r 6",
    "Player_4": "Mazraoui\r AVL (A)",
    "Player_8": "Palmer\r NFO (H)",
    "Player_9": "Rogers\r MUN (H)",
    "Player_15": "Jo\u00E3o Pedro\r TOT (H)"
  },
  {
    "manager_Name": "27171",
    "Teams": "ZA Superstarz",
    "SXL": "ZA",
    "Latp": "31",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r MUN (H)",
    "Player_12": "Ward\r 0",
    "Player_13": "Ndiaye\r NEW (H)",
    "Player_14": "Robinson\r 1",
    "Player_7": "Martinelli\r 6",
    "Player_2": "Pedro Porro\r BHA (A)",
    "Player_5": "Diogo J.\r 8",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Gvardiol\r 2",
    "Player_4": "Lewis\r 2",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Palmer\r NFO (H)",
    "Player_15": "Nedeljkovic\r MUN (H)"
  },
  {
    "manager_Name": "31660",
    "Teams": "A Few Good Men",
    "SXL": "EN",
    "Latp": "38",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Calvert-Lewin\r NEW (H)",
    "Player_12": "Bentley\r 0",
    "Player_13": "Jo\u00E3o Pedro\r TOT (H)",
    "Player_14": "Smith Rowe\r 1",
    "Player_7": "Rogers\r MUN (H)",
    "Player_2": "Lewis\r 2",
    "Player_5": "Van den Berg\r 1",
    "Player_6": "Palmer\r NFO (H)",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Saka\r 16",
    "Player_9": "Mbeumo\r 7",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "334682",
    "Teams": "Terry Makelele",
    "SXL": "IN",
    "Latp": "18",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Calvert-Lewin\r NEW (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Slicker\r 0",
    "Player_13": "Welbeck\r TOT (H)",
    "Player_14": "Bednarek\r 0",
    "Player_7": "Rogers\r MUN (H)",
    "Player_2": "Faes\r 6",
    "Player_5": "Madueke\r NFO (H)",
    "Player_6": "M.Salah\r 3",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Robertson\r 1",
    "Player_8": "Palmer\r NFO (H)",
    "Player_9": "Semenyo\r 2",
    "Player_15": "Robinson\r 1"
  },
  {
    "manager_Name": "2149817",
    "Teams": "Kloppenheaven",
    "SXL": "BD",
    "Latp": "30",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Haaland\r 4",
    "Player_10": "N.Jackson\r NFO (H)",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Jo\u00E3o Pedro\r TOT (H)",
    "Player_14": "Stephens\r 0",
    "Player_7": "Diogo J.\r 8",
    "Player_2": "Lewis\r 2",
    "Player_5": "Rogers\r MUN (H)",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Van de Ven\r BHA (A)",
    "Player_4": "Alexander-Arnold\r 6",
    "Player_8": "M.Salah\r 3",
    "Player_9": "Johnson\r BHA (A)",
    "Player_15": "Mosquera\r 0"
  },
  {
    "manager_Name": "1954902",
    "Teams": "Dn\u0027t promo viol\u0027s*",
    "SXL": "TH",
    "Latp": "23",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Evanilson\r 2",
    "Player_12": "Hermansen\r 6",
    "Player_13": "Robinson\r 1",
    "Player_14": "Sangar\u00E9\r CHE (A)",
    "Player_7": "Palmer\r NFO (H)",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Pedro Porro\r BHA (A)",
    "Player_6": "M.Salah\r 3",
    "Player_3": "Faes\r 6",
    "Player_4": "Pau\r MUN (H)",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Eze\r 2",
    "Player_15": "Jebbison\r 0"
  },
  {
    "manager_Name": "1124757",
    "Teams": "Dirty Ashe \u0026 da Boyz",
    "SXL": "US",
    "Latp": "22",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r MUN (H)",
    "Player_12": "Lumley\r 0",
    "Player_13": "Van den Berg\r 1",
    "Player_14": "Vestergaard\r 0",
    "Player_7": "Rogers\r MUN (H)",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Martinelli\r 6",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Pedro Porro\r BHA (A)",
    "Player_4": "Gabriel\r 2",
    "Player_8": "M.Salah\r 3",
    "Player_9": "Calvert-Lewin\r NEW (H)",
    "Player_15": "White\r EVE (A)"
  },
  {
    "manager_Name": "9790",
    "Teams": "BUFFY",
    "SXL": "TR",
    "Latp": "24",
    "Player_1": "Henderson\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "Solanke\r BHA (A)",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Greaves\r 0",
    "Player_14": "Robinson\r 1",
    "Player_7": "Semenyo\r 2",
    "Player_2": "Pedro Porro\r BHA (A)",
    "Player_5": "Palmer\r NFO (H)",
    "Player_6": "Rogers\r MUN (H)",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Gvardiol\r 2",
    "Player_8": "Mbeumo\r 7",
    "Player_9": "Watkins\r MUN (H)",
    "Player_15": "Sangar\u00E9\r CHE (A)"
  },
  {
    "manager_Name": "575228",
    "Teams": "Joely the house cat",
    "SXL": "NZ",
    "Latp": "31",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Calvert-Lewin\r NEW (H)",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Dunk\r TOT (H)",
    "Player_14": "Greaves\r 0",
    "Player_7": "Johnson\r BHA (A)",
    "Player_2": "Saliba\r 2",
    "Player_5": "Rogers\r MUN (H)",
    "Player_6": "Diogo J.\r 8",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Alexander-Arnold\r 6",
    "Player_8": "Palmer\r NFO (H)",
    "Player_9": "Mbeumo\r 7",
    "Player_15": "Jo\u00E3o Pedro\r TOT (H)"
  },
  {
    "manager_Name": "7150940",
    "Teams": "Desslehem",
    "SXL": "S1",
    "Latp": "43",
    "Player_1": "Flekken\r 1",
    "Player_11": "Havertz\r 12",
    "Player_10": "Watkins\r MUN (H)",
    "Player_12": "Pickford\r NEW (H)",
    "Player_13": "Rogers\r MUN (H)",
    "Player_14": "Greaves\r 0",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Pedro Porro\r BHA (A)",
    "Player_6": "Semenyo\r 2",
    "Player_3": "Gvardiol\r 2",
    "Player_4": "Saliba\r 2",
    "Player_8": "Saka\r 8",
    "Player_9": "M.Salah\r 3",
    "Player_15": "Stewart\r 1"
  },
  {
    "manager_Name": "469667",
    "Teams": "Don\u0027t panic",
    "SXL": "ZA",
    "Latp": "47",
    "Player_1": "Ederson M.\r 2",
    "Player_11": "Havertz\r 6",
    "Player_10": "Haaland\r 4",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Wood\r CHE (A)",
    "Player_14": "Aina\r CHE (A)",
    "Player_7": "Semenyo\r 2",
    "Player_2": "Konat\u00E9\r 6",
    "Player_5": "Bowen\r 10",
    "Player_6": "Johnson\r BHA (A)",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Alexander-Arnold\r 6",
    "Player_8": "Mbeumo\r 7",
    "Player_9": "Tavernier\r 2",
    "Player_15": "Faes\r 6"
  },
  {
    "manager_Name": "1112357",
    "Teams": "ZirkzeeAndIKnowIt",
    "SXL": "NO",
    "Latp": "32",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Solanke\r BHA (A)",
    "Player_12": "Ward\r 0",
    "Player_13": "Smith Rowe\r 1",
    "Player_14": "Robinson\r 1",
    "Player_7": "Rogers\r MUN (H)",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Faes\r 6",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Lewis\r 2",
    "Player_4": "Robertson\r 1",
    "Player_8": "Saka\r 8",
    "Player_9": "Palmer\r NFO (H)",
    "Player_15": "Ui-jo\r CHE (A)"
  },
  {
    "manager_Name": "913275",
    "Teams": "Real Fester C.F",
    "SXL": "EN",
    "Latp": "25",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Calvert-Lewin\r NEW (H)",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Welbeck\r TOT (H)",
    "Player_14": "Faes\r 6",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Konsa\r MUN (H)",
    "Player_5": "Mbeumo\r 7",
    "Player_6": "M.Salah\r 3",
    "Player_3": "Collins\r 10",
    "Player_4": "Colwill\r NFO (H)",
    "Player_8": "Palmer\r NFO (H)",
    "Player_9": "Rogers\r MUN (H)",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "33852",
    "Teams": "EGYPTIAN KING",
    "SXL": "IN",
    "Latp": "27",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "Havertz\r 6",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Rogers\r MUN (H)",
    "Player_14": "Mazraoui\r AVL (A)",
    "Player_7": "M.Salah\r 3",
    "Player_2": "Lewis\r 2",
    "Player_5": "McNeil\r NEW (H)",
    "Player_6": "Rashford\r AVL (A)",
    "Player_3": "J.Timber\r 0",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Mbeumo\r 7",
    "Player_9": "Vardy\r 2",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "256924",
    "Teams": "Marcel0scar",
    "SXL": "MY",
    "Latp": "29",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Evanilson\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Robinson\r 1",
    "Player_14": "Nedeljkovic\r MUN (H)",
    "Player_7": "Rogers\r MUN (H)",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Semenyo\r 2",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Faes\r 6",
    "Player_4": "Van den Berg\r 1",
    "Player_8": "Palmer\r NFO (H)",
    "Player_9": "M.Salah\r 3",
    "Player_15": "Jo\u00E3o Pedro\r TOT (H)"
  },
  {
    "manager_Name": "10625",
    "Teams": "The Trinity",
    "SXL": "MA",
    "Latp": "35",
    "Player_1": "Raya\r 2",
    "Player_11": "Delap\r 6",
    "Player_10": "Watkins\r MUN (H)",
    "Player_12": "Begovic\r NEW (H)",
    "Player_13": "Smith Rowe\r 1",
    "Player_14": "Robinson\r 1",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Mazraoui\r AVL (A)",
    "Player_5": "Saka\r 8",
    "Player_6": "Palmer\r NFO (H)",
    "Player_3": "Lewis\r 2",
    "Player_4": "Konat\u00E9\r 6",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Haaland\r 4",
    "Player_15": "Nedeljkovic\r MUN (H)"
  },
  {
    "manager_Name": "4069730",
    "Teams": "Garudwaar",
    "SXL": "IN",
    "Latp": "26",
    "Player_1": "Sels\r CHE (A)",
    "Player_11": "N.Jackson\r NFO (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Turner\r 0",
    "Player_13": "Smith Rowe\r 1",
    "Player_14": "Barco\r TOT (H)",
    "Player_7": "Diogo J.\r 8",
    "Player_2": "Van de Ven\r BHA (A)",
    "Player_5": "Luis D\u00EDaz\r 1",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Martinez\r AVL (A)",
    "Player_4": "Alexander-Arnold\r 6",
    "Player_8": "Palmer\r NFO (H)",
    "Player_9": "Wood\r CHE (A)",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "1820750",
    "Teams": "Pimpin\u0027 ain\u0027t Eze",
    "SXL": "EN",
    "Latp": "14",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r MUN (H)",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Smith Rowe\r 1",
    "Player_14": "Andersen\r 1",
    "Player_7": "Johnson\r BHA (A)",
    "Player_2": "Pedro Porro\r BHA (A)",
    "Player_5": "Rogers\r MUN (H)",
    "Player_6": "Palmer\r NFO (H)",
    "Player_3": "Mazraoui\r AVL (A)",
    "Player_4": "Gvardiol\r 2",
    "Player_8": "McNeil\r NEW (H)",
    "Player_9": "Havertz\r 6",
    "Player_15": "O\u0027Shea\r 0"
  },
  {
    "manager_Name": "340402",
    "Teams": "Melchester Rovers",
    "SXL": "EN",
    "Latp": "35",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Havertz\r 6",
    "Player_12": "Neto\r 0",
    "Player_13": "Jo\u00E3o Pedro\r TOT (H)",
    "Player_14": "Dunk\r TOT (H)",
    "Player_7": "Palmer\r NFO (H)",
    "Player_2": "Greaves\r 0",
    "Player_5": "Diogo J.\r 8",
    "Player_6": "Rogers\r MUN (H)",
    "Player_3": "Robertson\r 1",
    "Player_4": "Alexander-Arnold\r 6",
    "Player_8": "Mbeumo\r 7",
    "Player_9": "Smith Rowe\r 1",
    "Player_15": "Robinson\r 1"
  },
  {
    "manager_Name": "5259130",
    "Teams": "Vazball",
    "SXL": "IN",
    "Latp": "32",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "N.Jackson\r NFO (H)",
    "Player_12": "Iversen\r 0",
    "Player_13": "Faes\r 6",
    "Player_14": "Winks\r 0",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Lewis\r 2",
    "Player_5": "Diogo J.\r 8",
    "Player_6": "Rogers\r MUN (H)",
    "Player_3": "Gvardiol\r 2",
    "Player_4": "Robertson\r 1",
    "Player_8": "Palmer\r NFO (H)",
    "Player_9": "Havertz\r 6",
    "Player_15": "Barco\r TOT (H)"
  },
  {
    "manager_Name": "1431796",
    "Teams": "Take a Nap o\u0027 Leon",
    "SXL": "CA",
    "Latp": "13",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Haaland\r 2",
    "Player_10": "Havertz\r 6",
    "Player_12": "Ward\r 0",
    "Player_13": "Faes\r 6",
    "Player_14": "Sangar\u00E9\r CHE (A)",
    "Player_7": "M.Salah\r 3",
    "Player_2": "Pedro Porro\r BHA (A)",
    "Player_5": "Rogers\r MUN (H)",
    "Player_6": "Palmer\r NFO (H)",
    "Player_3": "Lewis\r 2",
    "Player_4": "Mazraoui\r AVL (A)",
    "Player_8": "McNeil\r NEW (H)",
    "Player_9": "N.Jackson\r NFO (H)",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "77395",
    "Teams": "Palli L\u00F6gga",
    "SXL": "IS",
    "Latp": "33",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Calvert-Lewin\r NEW (H)",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Rogers\r MUN (H)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Saka\r 8",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Semenyo\r 2",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Van de Ven\r BHA (A)",
    "Player_4": "Gvardiol\r 2",
    "Player_8": "Palmer\r NFO (H)",
    "Player_9": "Evanilson\r 2",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "30919",
    "Teams": "Manchester deLigt-ed",
    "SXL": "MY",
    "Latp": "39",
    "Player_1": "Henderson\r 3",
    "Player_11": "Watkins\r MUN (H)",
    "Player_10": "Haaland\r 2",
    "Player_12": "Matthews\r 0",
    "Player_13": "Robinson\r 1",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Saka\r 16",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Davis\r 0",
    "Player_4": "Gvardiol\r 2",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Havertz\r 6",
    "Player_15": "Winks\r 0"
  },
  {
    "manager_Name": "161000",
    "Teams": "Real Sociopath",
    "SXL": "EN",
    "Latp": "22",
    "Player_1": "Fabianski\r 0",
    "Player_11": "Haaland\r 4",
    "Player_10": "N.Jackson\r NFO (H)",
    "Player_12": "Ramsdale\r 1",
    "Player_13": "Faes\r 6",
    "Player_14": "Robinson\r 1",
    "Player_7": "M.Salah\r 3",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "McNeil\r NEW (H)",
    "Player_6": "Rogers\r MUN (H)",
    "Player_3": "Lewis\r 2",
    "Player_4": "Gvardiol\r 2",
    "Player_8": "Palmer\r NFO (H)",
    "Player_9": "Ra\u00FAl\r 5",
    "Player_15": "Iroegbunam\r NEW (H)"
  },
  {
    "manager_Name": "199070",
    "Teams": "FPL Kayman",
    "SXL": "EN",
    "Latp": "40",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Delap\r 6",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Wood\r CHE (A)",
    "Player_14": "Greaves\r 0",
    "Player_7": "Saka\r 8",
    "Player_2": "Lewis\r 2",
    "Player_5": "Semenyo\r 2",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Konat\u00E9\r 6",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "M.Salah\r 3",
    "Player_15": "Mykolenko\r NEW (H)"
  },
  {
    "manager_Name": "54123",
    "Teams": "SonsOfPitches",
    "SXL": "US",
    "Latp": "25",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Vardy\r 2",
    "Player_12": "Flekken\r 1",
    "Player_13": "Welbeck\r TOT (H)",
    "Player_14": "Burn\r EVE (A)",
    "Player_7": "Palmer\r NFO (H)",
    "Player_2": "Lewis\r 2",
    "Player_5": "Rogers\r MUN (H)",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Konsa\r MUN (H)",
    "Player_4": "Faes\r 6",
    "Player_8": "Saka\r 8",
    "Player_9": "Foden\r 2",
    "Player_15": "Robinson\r 1"
  },
  {
    "manager_Name": "10904",
    "Teams": "JohnBhoys",
    "SXL": "S1",
    "Latp": "19",
    "Player_1": "Raya\r 2",
    "Player_11": "Calvert-Lewin\r NEW (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Dennis\r 0",
    "Player_13": "Winks\r 0",
    "Player_14": "Faes\r 6",
    "Player_7": "Smith Rowe\r 1",
    "Player_2": "Robertson\r 1",
    "Player_5": "M.Salah\r 3",
    "Player_6": "Palmer\r NFO (H)",
    "Player_3": "Konsa\r MUN (H)",
    "Player_4": "Lewis\r 2",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Havertz\r 6",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "2123901",
    "Teams": "Looser FC",
    "SXL": "IN",
    "Latp": "42",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "Ra\u00FAl\r 5",
    "Player_12": "Turner\r 0",
    "Player_13": "Smith Rowe\r 1",
    "Player_14": "Lewis\r 2",
    "Player_7": "Semenyo\r 2",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Saka\r 8",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Davis\r 0",
    "Player_8": "Mbeumo\r 7",
    "Player_9": "Havertz\r 6",
    "Player_15": "Konsa\r MUN (H)"
  },
  {
    "manager_Name": "7978288",
    "Teams": "GvardiolsOfTheGalaxy",
    "SXL": "EN",
    "Latp": "22",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r MUN (H)",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Luis D\u00EDaz\r 1",
    "Player_14": "Aina\r CHE (A)",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Konsa\r MUN (H)",
    "Player_5": "Van den Berg\r 1",
    "Player_6": "Rogers\r MUN (H)",
    "Player_3": "Lewis\r 2",
    "Player_4": "Alexander-Arnold\r 6",
    "Player_8": "Johnson\r BHA (A)",
    "Player_9": "Palmer\r NFO (H)",
    "Player_15": "Lankshear\r BHA (A)"
  },
  {
    "manager_Name": "1189062",
    "Teams": "FC R\u00E4k\u00E4pallo",
    "SXL": "FI",
    "Latp": "39",
    "Player_1": "Sels\r CHE (A)",
    "Player_11": "Solanke\r BHA (A)",
    "Player_10": "Watkins\r MUN (H)",
    "Player_12": "Henderson\r 3",
    "Player_13": "Wood\r CHE (A)",
    "Player_14": "Robinson\r 1",
    "Player_7": "M.Salah\r 3",
    "Player_2": "Konsa\r MUN (H)",
    "Player_5": "Rogers\r MUN (H)",
    "Player_6": "Diogo J.\r 8",
    "Player_3": "Pedro Porro\r BHA (A)",
    "Player_4": "Alexander-Arnold\r 6",
    "Player_8": "Mbeumo\r 14",
    "Player_9": "Saka\r 8",
    "Player_15": "Barco\r TOT (H)"
  },
  {
    "manager_Name": "43141",
    "Teams": "FFP yeah you know me",
    "SXL": "US",
    "Latp": "35",
    "Player_1": "Fabianski\r 0",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r MUN (H)",
    "Player_12": "Henderson\r 3",
    "Player_13": "Smith Rowe\r 1",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Trossard\r 1",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Saka\r 8",
    "Player_6": "Diogo J.\r 8",
    "Player_3": "Pedro Porro\r BHA (A)",
    "Player_4": "Alexander-Arnold\r 6",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Delap\r 6",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "4728991",
    "Teams": "END RENEWED SHEGE",
    "SXL": "NG",
    "Latp": "17",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Watkins\r MUN (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Turner\r 0",
    "Player_13": "Murillo\r CHE (A)",
    "Player_14": "Adama\r 2",
    "Player_7": "M.Salah\r 3",
    "Player_2": "Pedro Porro\r BHA (A)",
    "Player_5": "Burn\r EVE (A)",
    "Player_6": "Minteh\r TOT (H)",
    "Player_3": "Robertson\r 1",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Madueke\r NFO (H)",
    "Player_9": "Mbeumo\r 7",
    "Player_15": "Ui-jo\r CHE (A)"
  },
  {
    "manager_Name": "8479435",
    "Teams": "Valkyries",
    "SXL": "IN",
    "Latp": "30",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Watkins\r MUN (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Greaves\r 0",
    "Player_14": "Armstrong\r 1",
    "Player_7": "McNeil\r NEW (H)",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Mbeumo\r 7",
    "Player_6": "Saka\r 8",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Lewis\r 2",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Smith Rowe\r 1",
    "Player_15": "Mosquera\r 0"
  },
  {
    "manager_Name": "1435806",
    "Teams": "El Gato grande",
    "SXL": "CA",
    "Latp": "38",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Welbeck\r TOT (H)",
    "Player_10": "Watkins\r MUN (H)",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Greaves\r 0",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "Saka\r 8",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Gvardiol\r 2",
    "Player_8": "Diogo J.\r 8",
    "Player_9": "Haaland\r 4",
    "Player_15": "Sangar\u00E9\r CHE (A)"
  },
  {
    "manager_Name": "5300",
    "Teams": "Mount Rashmore",
    "SXL": "EN",
    "Latp": "45",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 2",
    "Player_10": "Havertz\r 6",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Jo\u00E3o Pedro\r TOT (H)",
    "Player_14": "Robinson\r 1",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Faes\r 6",
    "Player_5": "Rogers\r MUN (H)",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Konsa\r MUN (H)",
    "Player_4": "Alexander-Arnold\r 6",
    "Player_8": "Saka\r 16",
    "Player_9": "Palmer\r NFO (H)",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "2791",
    "Teams": "McLaren Mercedes FC",
    "SXL": "AU",
    "Latp": "26",
    "Player_1": "Onana\r AVL (A)",
    "Player_11": "Welbeck\r TOT (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Martinez\r MUN (H)",
    "Player_13": "Mazraoui\r AVL (A)",
    "Player_14": "Robinson\r 1",
    "Player_7": "Palmer\r NFO (H)",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Rogers\r MUN (H)",
    "Player_6": "Martinelli\r 6",
    "Player_3": "Veltman\r TOT (H)",
    "Player_4": "Konsa\r MUN (H)",
    "Player_8": "Bowen\r 10",
    "Player_9": "Calvert-Lewin\r NEW (H)",
    "Player_15": "Smith Rowe\r 1"
  },
  {
    "manager_Name": "3307872",
    "Teams": "Saka Potatoes",
    "SXL": "EN",
    "Latp": "28",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Welbeck\r TOT (H)",
    "Player_12": "Arrizabalaga\r 2",
    "Player_13": "Harwood-Bellis\r 1",
    "Player_14": "Johnson\r 0",
    "Player_7": "Semenyo\r 2",
    "Player_2": "Konsa\r MUN (H)",
    "Player_5": "Saka\r 8",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "M.Salah\r 3",
    "Player_15": "Ladapo\r 0"
  },
  {
    "manager_Name": "8937",
    "Teams": "Licha\u0027s Fine Cuts",
    "SXL": "MY",
    "Latp": "30",
    "Player_1": "Raya\r 2",
    "Player_11": "Calvert-Lewin\r NEW (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Benda\r 0",
    "Player_13": "Wood\r CHE (A)",
    "Player_14": "Robinson\r 1",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Johnson\r BHA (A)",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Aina\r CHE (A)",
    "Player_8": "Saka\r 8",
    "Player_9": "Rogers\r MUN (H)",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "139400",
    "Teams": "BMT Squad",
    "SXL": "ZA",
    "Latp": "22",
    "Player_1": "Martinez\r MUN (H)",
    "Player_11": "Solanke\r BHA (A)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Smith Rowe\r 1",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Gvardiol\r 2",
    "Player_5": "Semenyo\r 2",
    "Player_6": "Rogers\r MUN (H)",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Robinson\r 1",
    "Player_8": "Palmer\r NFO (H)",
    "Player_9": "Watkins\r MUN (H)",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "658446",
    "Teams": "Gangster\u0027s Allardyce",
    "SXL": "EN",
    "Latp": "28",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r MUN (H)",
    "Player_12": "Verbruggen\r TOT (H)",
    "Player_13": "Nedeljkovic\r MUN (H)",
    "Player_14": "Jo\u00E3o Pedro\r TOT (H)",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Konat\u00E9\r 6",
    "Player_5": "Rogers\r MUN (H)",
    "Player_6": "Eze\r 2",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Lewis\r 2",
    "Player_8": "Carvalho\r 0",
    "Player_9": "M.Salah\r 3",
    "Player_15": "Robinson\r 1"
  },
  {
    "manager_Name": "49882",
    "Teams": "AFC Richmandem",
    "SXL": "EN",
    "Latp": "29",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Evanilson\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Greaves\r 0",
    "Player_14": "Stewart\r 1",
    "Player_7": "Palmer\r NFO (H)",
    "Player_2": "Faes\r 6",
    "Player_5": "Dibling\r 1",
    "Player_6": "Saka\r 8",
    "Player_3": "Robertson\r 1",
    "Player_4": "Lewis\r 2",
    "Player_8": "M.Salah\r 3",
    "Player_9": "Rogers\r MUN (H)",
    "Player_15": "Nedeljkovic\r MUN (H)"
  },
  {
    "manager_Name": "1047579",
    "Teams": "Donkey Magic",
    "SXL": "EN",
    "Latp": "26",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Calvert-Lewin\r NEW (H)",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Johnson\r 0",
    "Player_14": "Robinson\r 1",
    "Player_7": "Palmer\r NFO (H)",
    "Player_2": "Lewis\r 2",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "Saka\r 8",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Van de Ven\r BHA (A)",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Mbeumo\r 7",
    "Player_15": "Jo\u00E3o Pedro\r TOT (H)"
  },
  {
    "manager_Name": "460235",
    "Teams": "FPL_Nilz",
    "SXL": "NZ",
    "Latp": "33",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r MUN (H)",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Winks\r 0",
    "Player_14": "Jo\u00E3o Pedro\r TOT (H)",
    "Player_7": "Eze\r 2",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Gvardiol\r 2",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Hall\r EVE (A)",
    "Player_4": "Alexander-Arnold\r 6",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Saka\r 8",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "6189",
    "Teams": "MohunBagan",
    "SXL": "US",
    "Latp": "24",
    "Player_1": "Martinez\r MUN (H)",
    "Player_11": "Havertz\r 6",
    "Player_10": "Haaland\r 4",
    "Player_12": "Begovic\r NEW (H)",
    "Player_13": "Dunk\r TOT (H)",
    "Player_14": "Robinson\r 1",
    "Player_7": "Semenyo\r 2",
    "Player_2": "Digne\r MUN (H)",
    "Player_5": "Trossard\r 1",
    "Player_6": "Palmer\r NFO (H)",
    "Player_3": "Lewis\r 2",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Mbeumo\r 7",
    "Player_9": "Watkins\r MUN (H)",
    "Player_15": "Winks\r 0"
  },
  {
    "manager_Name": "1134008",
    "Teams": "SlottsMachines",
    "SXL": "IE",
    "Latp": "25",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Eze\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Konsa\r MUN (H)",
    "Player_14": "Cannon\r 0",
    "Player_7": "Johnson\r BHA (A)",
    "Player_2": "Saliba\r 2",
    "Player_5": "Gabriel\r 2",
    "Player_6": "Rogers\r MUN (H)",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Pedro Porro\r BHA (A)",
    "Player_8": "Mbeumo\r 7",
    "Player_9": "Palmer\r NFO (H)",
    "Player_15": "Fraser\r 0"
  },
  {
    "manager_Name": "4265681",
    "Teams": "The Molly Maguires",
    "SXL": "EN",
    "Latp": "15",
    "Player_1": "Raya\r 2",
    "Player_11": "Watkins\r MUN (H)",
    "Player_10": "Calvert-Lewin\r NEW (H)",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Lewis\r 2",
    "Player_14": "Winks\r 0",
    "Player_7": "M.Salah\r 3",
    "Player_2": "Gvardiol\r 2",
    "Player_5": "Rogers\r MUN (H)",
    "Player_6": "McNeil\r NEW (H)",
    "Player_3": "Gabriel\r 2",
    "Player_4": "J.Timber\r 0",
    "Player_8": "Eze\r 2",
    "Player_9": "Haaland\r 4",
    "Player_15": "Barco\r TOT (H)"
  },
  {
    "manager_Name": "727316",
    "Teams": "House of Dragusin",
    "SXL": "AU",
    "Latp": "23",
    "Player_1": "Pickford\r NEW (H)",
    "Player_11": "Watkins\r MUN (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Bentley\r 0",
    "Player_13": "Robinson\r 1",
    "Player_14": "Bergvall\r BHA (A)",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Rogers\r MUN (H)",
    "Player_6": "M.Salah\r 3",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Davis\r 0",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "Calvert-Lewin\r NEW (H)",
    "Player_15": "Barco\r TOT (H)"
  },
  {
    "manager_Name": "16589",
    "Teams": "Hapoel katz",
    "SXL": "IL",
    "Latp": "20",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Welbeck\r TOT (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Turner\r 0",
    "Player_13": "Adama\r 2",
    "Player_14": "Faes\r 6",
    "Player_7": "Johnson\r BHA (A)",
    "Player_2": "Van de Ven\r BHA (A)",
    "Player_5": "Mbeumo\r 7",
    "Player_6": "M.Salah\r 3",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Konsa\r MUN (H)",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Watkins\r MUN (H)",
    "Player_15": "Robinson\r 1"
  },
  {
    "manager_Name": "8094703",
    "Teams": "Abhisekh Kharel",
    "SXL": "NP",
    "Latp": "37",
    "Player_1": "Flekken\r 1",
    "Player_11": "Havertz\r 6",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Mykolenko\r NEW (H)",
    "Player_14": "Greaves\r 0",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Lewis\r 2",
    "Player_5": "Saka\r 8",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Calvert-Lewin\r NEW (H)",
    "Player_15": "Dibling\r 1"
  },
  {
    "manager_Name": "27732",
    "Teams": "Matthias Ammon",
    "SXL": "EN",
    "Latp": "30",
    "Player_1": "Flekken\r 1",
    "Player_11": "Vardy\r 2",
    "Player_10": "Havertz\r 6",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Quansah\r 0",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Palmer\r NFO (H)",
    "Player_6": "Saka\r 8",
    "Player_3": "Pedro Porro\r BHA (A)",
    "Player_4": "Konsa\r MUN (H)",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Haaland\r 4",
    "Player_15": "Sangar\u00E9\r CHE (A)"
  },
  {
    "manager_Name": "3222617",
    "Teams": "Sheldon Ferns",
    "SXL": "EN",
    "Latp": "36",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "Havertz\r 6",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Mykolenko\r NEW (H)",
    "Player_14": "Greaves\r 0",
    "Player_7": "McNeil\r NEW (H)",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Mbeumo\r 7",
    "Player_6": "Saka\r 8",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Lewis\r 2",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Solanke\r BHA (A)",
    "Player_15": "Dibling\r 1"
  },
  {
    "manager_Name": "331074",
    "Teams": "tom fraser",
    "SXL": "EN",
    "Latp": "20",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r MUN (H)",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Greaves\r 0",
    "Player_14": "Robinson\r 1",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Colwill\r NFO (H)",
    "Player_5": "Palmer\r NFO (H)",
    "Player_6": "Saka\r 8",
    "Player_3": "Robertson\r 1",
    "Player_4": "Van de Ven\r BHA (A)",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Calvert-Lewin\r NEW (H)",
    "Player_15": "Sangar\u00E9\r CHE (A)"
  },
  {
    "manager_Name": "2224679",
    "Teams": "Thato Tlhaole",
    "SXL": "ZA",
    "Latp": "44",
    "Player_1": "Flekken\r 1",
    "Player_11": "Havertz\r 6",
    "Player_10": "Delap\r 6",
    "Player_12": "Carson\r 0",
    "Player_13": "Dibling\r 1",
    "Player_14": "Greaves\r 0",
    "Player_7": "Rogers\r MUN (H)",
    "Player_2": "Lewis\r 2",
    "Player_5": "Saka\r 16",
    "Player_6": "M.Salah\r 3",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Konat\u00E9\r 6",
    "Player_8": "McNeil\r NEW (H)",
    "Player_9": "Haaland\r 2",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "1330635",
    "Teams": "S M Ishtiak Hossain",
    "SXL": "NO",
    "Latp": "18",
    "Player_1": "Flekken\r 1",
    "Player_11": "Watkins\r MUN (H)",
    "Player_10": "N.Jackson\r NFO (H)",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Semenyo\r 2",
    "Player_14": "Faes\r 6",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Rogers\r MUN (H)",
    "Player_6": "McNeil\r NEW (H)",
    "Player_3": "Colwill\r NFO (H)",
    "Player_4": "Robertson\r 1",
    "Player_8": "M.Salah\r 3",
    "Player_9": "Haaland\r 4",
    "Player_15": "Nedeljkovic\r MUN (H)"
  },
  {
    "manager_Name": "2186835",
    "Teams": "Tom Caton",
    "SXL": "EN",
    "Latp": "32",
    "Player_1": "Martinez\r MUN (H)",
    "Player_11": "Calvert-Lewin\r NEW (H)",
    "Player_10": "Watkins\r MUN (H)",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Semenyo\r 2",
    "Player_14": "Aina\r CHE (A)",
    "Player_7": "M.Salah\r 3",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Saka\r 8",
    "Player_6": "Rogers\r MUN (H)",
    "Player_3": "Gvardiol\r 2",
    "Player_4": "Mykolenko\r NEW (H)",
    "Player_8": "Mbeumo\r 7",
    "Player_9": "Havertz\r 6",
    "Player_15": "Robinson\r 1"
  },
  {
    "manager_Name": "7140577",
    "Teams": "Jessica Hmeidan",
    "SXL": "AU",
    "Latp": "48",
    "Player_1": "Ederson M.\r 2",
    "Player_11": "Calvert-Lewin\r NEW (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Rogers\r MUN (H)",
    "Player_14": "Konsa\r MUN (H)",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Luis D\u00EDaz\r 1",
    "Player_6": "Semenyo\r 2",
    "Player_3": "Virgil\r 6",
    "Player_4": "Collins\r 10",
    "Player_8": "Saka\r 8",
    "Player_9": "Havertz\r 6",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "9881245",
    "Teams": "Chetan Gupta",
    "SXL": "IN",
    "Latp": "29",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "Calvert-Lewin\r NEW (H)",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Rogers\r MUN (H)",
    "Player_14": "Greaves\r 0",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Lewis\r 2",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Colwill\r NFO (H)",
    "Player_8": "Palmer\r NFO (H)",
    "Player_9": "Havertz\r 6",
    "Player_15": "Dibling\r 1"
  },
  {
    "manager_Name": "324254",
    "Teams": "Max Askew",
    "SXL": "ES",
    "Latp": "28",
    "Player_1": "Raya\r 2",
    "Player_11": "Watkins\r MUN (H)",
    "Player_10": "Calvert-Lewin\r NEW (H)",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Smith Rowe\r 1",
    "Player_14": "Greaves\r 0",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "McNeil\r NEW (H)",
    "Player_6": "Palmer\r NFO (H)",
    "Player_3": "Pinnock\r 7",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Haaland\r 4",
    "Player_15": "Robinson\r 1"
  },
  {
    "manager_Name": "5390475",
    "Teams": "Kamlesh Pawar",
    "SXL": "IN",
    "Latp": "18",
    "Player_1": "S\u00E1nchez\r NFO (H)",
    "Player_11": "Solanke\r BHA (A)",
    "Player_10": "N.Jackson\r NFO (H)",
    "Player_12": "Sels\r CHE (A)",
    "Player_13": "De Ligt\r AVL (A)",
    "Player_14": "Mykolenko\r NEW (H)",
    "Player_7": "Barnes\r EVE (A)",
    "Player_2": "Konsa\r MUN (H)",
    "Player_5": "M.Salah\r 3",
    "Player_6": "Palmer\r NFO (H)",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Alexander-Arnold\r 6",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Mbeumo\r 7",
    "Player_15": "Wood\r CHE (A)"
  },
  {
    "manager_Name": "18718",
    "Teams": "Varun Khanna",
    "SXL": "IN",
    "Latp": "32",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "N.Jackson\r NFO (H)",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Rogers\r MUN (H)",
    "Player_14": "Luis D\u00EDaz\r 1",
    "Player_7": "Saka\r 8",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Lewis\r 2",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Pedro Porro\r BHA (A)",
    "Player_8": "Semenyo\r 2",
    "Player_9": "Calvert-Lewin\r NEW (H)",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "3491179",
    "Teams": "Jamie Fitzpatrick",
    "SXL": "EN",
    "Latp": "38",
    "Player_1": "Flekken\r 1",
    "Player_11": "Havertz\r 6",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Calvert-Lewin\r NEW (H)",
    "Player_14": "Greaves\r 0",
    "Player_7": "Semenyo\r 2",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Saka\r 8",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Lewis\r 2",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Maddison\r BHA (A)",
    "Player_9": "Rogers\r MUN (H)",
    "Player_15": "Mykolenko\r NEW (H)"
  },
  {
    "manager_Name": "886323",
    "Teams": "Shaunak K",
    "SXL": "IN",
    "Latp": "41",
    "Player_1": "Henderson\r 3",
    "Player_11": "Solanke\r BHA (A)",
    "Player_10": "Havertz\r 6",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Davis\r 0",
    "Player_14": "Dibling\r 1",
    "Player_7": "Mavididi\r 3",
    "Player_2": "Lewis\r 2",
    "Player_5": "Garnacho\r AVL (A)",
    "Player_6": "Saka\r 16",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Saliba\r 2",
    "Player_8": "M.Salah\r 3",
    "Player_9": "Watkins\r MUN (H)",
    "Player_15": "Robinson\r 1"
  },
  {
    "manager_Name": "19818",
    "Teams": "Akshay Hariharan",
    "SXL": "IN",
    "Latp": "27",
    "Player_1": "Flekken\r 1",
    "Player_11": "Solanke\r BHA (A)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Sels\r CHE (A)",
    "Player_13": "Van den Berg\r 1",
    "Player_14": "Winks\r 0",
    "Player_7": "Saka\r 8",
    "Player_2": "Pedro Porro\r BHA (A)",
    "Player_5": "Rogers\r MUN (H)",
    "Player_6": "Johnson\r BHA (A)",
    "Player_3": "Gvardiol\r 2",
    "Player_4": "Faes\r 6",
    "Player_8": "Palmer\r NFO (H)",
    "Player_9": "Havertz\r 6",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "4811404",
    "Teams": "Sahil Kumar Sahu",
    "SXL": "IN",
    "Latp": "30",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "Havertz\r 6",
    "Player_12": "Turner\r 0",
    "Player_13": "Onana\r MUN (H)",
    "Player_14": "Keane\r NEW (H)",
    "Player_7": "Palmer\r NFO (H)",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Faes\r 6",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Gvardiol\r 2",
    "Player_4": "Konsa\r MUN (H)",
    "Player_8": "Rogers\r MUN (H)",
    "Player_9": "Saka\r 8",
    "Player_15": "Jo\u00E3o Pedro\r TOT (H)"
  },
  {
    "manager_Name": "824008",
    "Teams": "Aryan Sumbly",
    "SXL": "IN",
    "Latp": "35",
    "Player_1": "Sels\r CHE (A)",
    "Player_11": "Haaland\r 2",
    "Player_10": "Solanke\r BHA (A)",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Luis D\u00EDaz\r 1",
    "Player_14": "Lewis\r 5",
    "Player_7": "Semenyo\r 2",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Rogers\r MUN (H)",
    "Player_6": "Saka\r 16",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Pedro Porro\r BHA (A)",
    "Player_8": "Mbeumo\r 7",
    "Player_9": "Calvert-Lewin\r NEW (H)",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "4986668",
    "Teams": "Bror Christian Melands\u00F8",
    "SXL": "NO",
    "Latp": "42",
    "Player_1": "Pickford\r NEW (H)",
    "Player_11": "N.Jackson\r NFO (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Colwill\r NFO (H)",
    "Player_14": "Smith Rowe\r 1",
    "Player_7": "Saka\r 8",
    "Player_2": "Lewis\r 5",
    "Player_5": "Diogo J.\r 8",
    "Player_6": "Semenyo\r 2",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Alexander-Arnold\r 6",
    "Player_8": "Mbeumo\r 7",
    "Player_9": "Calvert-Lewin\r NEW (H)",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "40190",
    "Teams": "kunal yadav",
    "SXL": "IN",
    "Latp": "20",
    "Player_1": "Raya\r 2",
    "Player_11": "Solanke\r BHA (A)",
    "Player_10": "Havertz\r 6",
    "Player_12": "Verbruggen\r TOT (H)",
    "Player_13": "Jo\u00E3o Pedro\r TOT (H)",
    "Player_14": "Mu\u00F1oz\r 1",
    "Player_7": "Eze\r 2",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Palmer\r NFO (H)",
    "Player_6": "M.Salah\r 3",
    "Player_3": "Konsa\r MUN (H)",
    "Player_4": "Hall\r EVE (A)",
    "Player_8": "Minteh\r TOT (H)",
    "Player_9": "Luis D\u00EDaz\r 1",
    "Player_15": "Robinson\r 1"
  }
];