var s = [
  {
    "manager_Name": "1,114( 1 ) TotalXfr : 13",
    "Teams": "3ALLA ALLAH( yassine hilmi )",
    "SXL": "Morocco",
    "Latp": "20",
    "Player_1": "Onana\r MCI (A)",
    "Player_11": "Cunha\r 6",
    "Player_10": "Evanilson\r WHU (H)",
    "Player_12": "Pickford\r 6",
    "Player_13": "Wissa\r CHE (A)",
    "Player_14": "Johnson\r 1",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "Virgil\r 1",
    "Player_5": "Kulusevski\r SOU (A)",
    "Player_6": "Bowen\r BOU (A)",
    "Player_3": "Pedro Porro\r SOU (A)",
    "Player_4": "Estupi\u00F1an\r CRY (H)",
    "Player_8": "Saka\r 3",
    "Player_9": "M.Salah\r 10",
    "Player_15": "Taylor\r TOT (H)"
  },
  {
    "manager_Name": "1,101( 2 ) TotalXfr : 14",
    "Teams": "BB GW1( Ayoub NACIR \uD83C\uDDF2\uD83C\uDDE6 )",
    "SXL": "Morocco",
    "Latp": "32",
    "Player_1": "Henderson\r BHA (A)",
    "Player_11": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_10": "Isak\r 9",
    "Player_12": "Fabianski\r BOU (A)",
    "Player_13": "Rogers\r 2",
    "Player_14": "Aina\r 2",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "A\u00EFt-Nouri\r -2",
    "Player_5": "B.Fernandes\r MCI (A)",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Kerkez\r WHU (H)",
    "Player_4": "Gabriel\r 6",
    "Player_8": "Saka\r 3",
    "Player_9": "Cunha\r 6",
    "Player_15": "Barco\r CRY (H)"
  },
  {
    "manager_Name": "1,097( 3 ) TotalXfr : 14",
    "Teams": "Holy Boehly( Niels Pretorius )",
    "SXL": "Norway",
    "Latp": "28",
    "Player_1": "Fabianski\r BOU (A)",
    "Player_11": "Isak\r 9",
    "Player_10": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_12": "Flekken\r CHE (A)",
    "Player_13": "Rogers\r 2",
    "Player_14": "Robinson\r 6",
    "Player_7": "Bowen\r BOU (A)",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Saka\r 3",
    "Player_6": "M.Salah\r 5",
    "Player_3": "J.Timber\r 6",
    "Player_4": "A\u00EFt-Nouri\r -2",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Cunha\r 6",
    "Player_15": "Van den Berg\r CHE (A)"
  },
  {
    "manager_Name": "1,097( 3 ) TotalXfr : 13",
    "Teams": "LIV( Dani Lio messi \uD83C\uDDEA\uD83C\uDDF9 )",
    "SXL": "Ethiopia",
    "Latp": "25",
    "Player_1": "Martinez\r 2",
    "Player_11": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_10": "Cunha\r 6",
    "Player_12": "Henderson\r BHA (A)",
    "Player_13": "Bowen\r BOU (A)",
    "Player_14": "Greaves\r 0",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "J.Timber\r 6",
    "Player_5": "B.Fernandes\r MCI (A)",
    "Player_6": "Saka\r 3",
    "Player_3": "A\u00EFt-Nouri\r -2",
    "Player_4": "Kerkez\r WHU (H)",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Evanilson\r WHU (H)",
    "Player_15": "Bella-Kotchap\r TOT (H)"
  },
  {
    "manager_Name": "1,095( 5 ) TotalXfr : 16",
    "Teams": "hazardous behaviour( Ollie Stannard )",
    "SXL": "England",
    "Latp": "30",
    "Player_1": "Sels\r 2",
    "Player_11": "Cunha\r 6",
    "Player_10": "N.Jackson\r BRE (H)",
    "Player_12": "Valdimarsson\r CHE (A)",
    "Player_13": "Damsgaard\r CHE (A)",
    "Player_14": "Faes\r 0",
    "Player_7": "M.Salah\r 5",
    "Player_2": "A\u00EFt-Nouri\r -2",
    "Player_5": "Johnson\r SOU (A)",
    "Player_6": "Palmer\r BRE (H)",
    "Player_3": "Virgil\r 1",
    "Player_4": "Saliba\r 6",
    "Player_8": "Saka\r 3",
    "Player_9": "Isak\r 9",
    "Player_15": "Barco\r CRY (H)"
  },
  {
    "manager_Name": "1,094( 6 ) TotalXfr : 15",
    "Teams": "abdo VanDijk( abdallah mohammed ali )",
    "SXL": "Egypt",
    "Latp": "18",
    "Player_1": "Fabianski\r BOU (A)",
    "Player_11": "N.Jackson\r BRE (H)",
    "Player_10": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_12": "Flekken\r CHE (A)",
    "Player_13": "Wissa\r CHE (A)",
    "Player_14": "Robinson\r 6",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "A\u00EFt-Nouri\r -2",
    "Player_5": "Saka\r 3",
    "Player_6": "Gordon\r 6",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Colwill\r BRE (H)",
    "Player_8": "Bowen\r BOU (A)",
    "Player_9": "M.Salah\r 5",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "1,091( 7 ) TotalXfr : 12",
    "Teams": "Obi Wan - Kenobi Nil( Johnny Rouge )",
    "SXL": "England",
    "Latp": "17",
    "Player_1": "Martinez\r 2",
    "Player_11": "Wood\r 2",
    "Player_10": "N.Jackson\r BRE (H)",
    "Player_12": "Fabianski\r BOU (A)",
    "Player_13": "Rogers\r 2",
    "Player_14": "Milenkovi\u0107\r 8",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Gabriel\r 6",
    "Player_5": "Palmer\r BRE (H)",
    "Player_6": "B.Fernandes\r MCI (A)",
    "Player_3": "Gvardiol\r MUN (H)",
    "Player_4": "Robertson\r -3",
    "Player_8": "Mbeumo\r CHE (A)",
    "Player_9": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "1,089( 8 ) TotalXfr : 13",
    "Teams": "ugly squad( abdullah alanazi )",
    "SXL": "Saudi Arabia",
    "Latp": "35",
    "Player_1": "Fabianski\r BOU (A)",
    "Player_11": "Welbeck\r CRY (H)",
    "Player_10": "Cunha\r 6",
    "Player_12": "Pickford\r 6",
    "Player_13": "Delap\r 2",
    "Player_14": "Greaves\r 0",
    "Player_7": "Saka\r 3",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Palmer\r BRE (H)",
    "Player_6": "Gordon\r 6",
    "Player_3": "Milenkovi\u0107\r 8",
    "Player_4": "Gabriel\r 6",
    "Player_8": "M.Salah\r 5",
    "Player_9": "Enzo\r BRE (H)",
    "Player_15": "Collins\r CHE (A)"
  },
  {
    "manager_Name": "1,088( 9 ) TotalXfr : 14",
    "Teams": "The Notorious D.U.G( Doug Yellowley )",
    "SXL": "Scotland",
    "Latp": "25",
    "Player_1": "Kelleher\r 0",
    "Player_11": "Wood\r 2",
    "Player_10": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_12": "Fabianski\r BOU (A)",
    "Player_13": "Konsa\r 1",
    "Player_14": "Greaves\r 0",
    "Player_7": "Rogers\r 2",
    "Player_2": "Gabriel\r 6",
    "Player_5": "Saka\r 3",
    "Player_6": "Palmer\r BRE (H)",
    "Player_3": "Pedro Porro\r SOU (A)",
    "Player_4": "Virgil\r 1",
    "Player_8": "M.Salah\r 5",
    "Player_9": "Cunha\r 6",
    "Player_15": "Mbeumo\r CHE (A)"
  },
  {
    "manager_Name": "1,088( 9 ) TotalXfr : 13",
    "Teams": "J\u00FCrgen Klopp( Abdullah AlGhfeli )",
    "SXL": "United Arab Emirates",
    "Latp": "41",
    "Player_1": "Raya\r 6",
    "Player_11": "Cunha\r 6",
    "Player_10": "Isak\r 9",
    "Player_12": "J.Virginia\r 0",
    "Player_13": "Burn\r 6",
    "Player_14": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_7": "M.Salah\r 10",
    "Player_2": "J.Timber\r 6",
    "Player_5": "Kudus\r BOU (A)",
    "Player_6": "Saka\r 3",
    "Player_3": "Lamptey\r CRY (H)",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Dibling\r TOT (H)",
    "Player_15": "Johnson\r 1"
  },
  {
    "manager_Name": "1,088( 9 ) TotalXfr : 13",
    "Teams": "Snoop Udogie Dogg( Sion Nierada )",
    "SXL": "England",
    "Latp": "37",
    "Player_1": "Sels\r 2",
    "Player_11": "Wood\r 2",
    "Player_10": "Isak\r 9",
    "Player_12": "Fabianski\r BOU (A)",
    "Player_13": "Gabriel\r 6",
    "Player_14": "Van den Berg\r CHE (A)",
    "Player_7": "M.Salah\r 5",
    "Player_2": "Gomez\r 1",
    "Player_5": "Semenyo\r WHU (H)",
    "Player_6": "Saka\r 3",
    "Player_3": "Milenkovi\u0107\r 8",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Cunha\r 6",
    "Player_15": "Winks\r 0"
  },
  {
    "manager_Name": "1,087( 12 ) TotalXfr : 15",
    "Teams": "\u0645\u0635\u0637\u0641\u0649 \u0641\u0624\u0627\u062F( Mustafa YNWA )",
    "SXL": "Iraq",
    "Latp": "32",
    "Player_1": "Raya\r 6",
    "Player_11": "N.Jackson\r BRE (H)",
    "Player_10": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_12": "Ward\r 1",
    "Player_13": "Aina\r 2",
    "Player_14": "Mbeumo\r CHE (A)",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "Cucurella\r BRE (H)",
    "Player_5": "Saka\r 3",
    "Player_6": "Rogers\r 2",
    "Player_3": "Veltman\r CRY (H)",
    "Player_4": "Davis\r 2",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Isak\r 9",
    "Player_15": "Konsa\r 1"
  },
  {
    "manager_Name": "1,087( 12 ) TotalXfr : 13",
    "Teams": "Pipat FC( Pipat Boss )",
    "SXL": "Thailand",
    "Latp": "23",
    "Player_1": "Raya\r 6",
    "Player_11": "Wood\r 2",
    "Player_10": "Cunha\r 6",
    "Player_12": "Fabianski\r BOU (A)",
    "Player_13": "Mbeumo\r CHE (A)",
    "Player_14": "Mazraoui\r MCI (A)",
    "Player_7": "M.Salah\r 5",
    "Player_2": "Gvardiol\r MUN (H)",
    "Player_5": "Semenyo\r WHU (H)",
    "Player_6": "Saka\r 6",
    "Player_3": "A\u00EFt-Nouri\r -2",
    "Player_4": "Pedro Porro\r SOU (A)",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Welbeck\r CRY (H)",
    "Player_15": "Harwood-Bellis\r TOT (H)"
  },
  {
    "manager_Name": "1,087( 12 ) TotalXfr : 13",
    "Teams": "BurnDemAll( Dara Bbat )",
    "SXL": "Nigeria",
    "Latp": "24",
    "Player_1": "Sels\r 2",
    "Player_11": "Wood\r 2",
    "Player_10": "N.Jackson\r BRE (H)",
    "Player_12": "Fabianski\r BOU (A)",
    "Player_13": "Rogers\r 2",
    "Player_14": "Robinson\r 6",
    "Player_7": "M.Salah\r 5",
    "Player_2": "Mazraoui\r MCI (A)",
    "Player_5": "Saka\r 3",
    "Player_6": "B.Fernandes\r MCI (A)",
    "Player_3": "J.Timber\r 6",
    "Player_4": "Cucurella\r BRE (H)",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Cunha\r 6",
    "Player_15": "Taylor\r TOT (H)"
  },
  {
    "manager_Name": "1,086( 15 ) TotalXfr : 13",
    "Teams": "Pep a pig( abdul hendricks )",
    "SXL": "South Africa",
    "Latp": "24",
    "Player_1": "Flekken\r CHE (A)",
    "Player_11": "Cunha\r 6",
    "Player_10": "Evanilson\r WHU (H)",
    "Player_12": "Turner\r BHA (A)",
    "Player_13": "Rogers\r 2",
    "Player_14": "Harwood-Bellis\r TOT (H)",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "A\u00EFt-Nouri\r -2",
    "Player_5": "M.Salah\r 10",
    "Player_6": "Bowen\r BOU (A)",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Saliba\r 6",
    "Player_8": "Saka\r 3",
    "Player_9": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_15": "Mazraoui\r MCI (A)"
  },
  {
    "manager_Name": "1,086( 16 ) TotalXfr : 17",
    "Teams": "ASG( Auwal SG )",
    "SXL": "Nigeria",
    "Latp": "34",
    "Player_1": "Fabianski\r BOU (A)",
    "Player_11": "Strand Larsen\r 2",
    "Player_10": "Isak\r 9",
    "Player_12": "S\u00E1nchez\r BRE (H)",
    "Player_13": "Winks\r 0",
    "Player_14": "Harwood-Bellis\r TOT (H)",
    "Player_7": "Saka\r 3",
    "Player_2": "Hall\r 12",
    "Player_5": "Palmer\r BRE (H)",
    "Player_6": "Bowen\r BOU (A)",
    "Player_3": "Pedro Porro\r SOU (A)",
    "Player_4": "J.Timber\r 6",
    "Player_8": "Son\r SOU (A)",
    "Player_9": "Havertz\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "1,086( 17 ) TotalXfr : 18",
    "Teams": "Kobs on the Job( Harry Jones )",
    "SXL": "Australia",
    "Latp": "36",
    "Player_1": "S\u00E1nchez\r BRE (H)",
    "Player_11": "Isak\r 9",
    "Player_10": "Cunha\r 6",
    "Player_12": "Flekken\r CHE (A)",
    "Player_13": "Amad\r MCI (A)",
    "Player_14": "Young\r 5",
    "Player_7": "M.Salah\r 5",
    "Player_2": "Saliba\r 6",
    "Player_5": "Saka\r 6",
    "Player_6": "Palmer\r BRE (H)",
    "Player_3": "Dalot\r MCI (A)",
    "Player_4": "Aina\r 2",
    "Player_8": "Rogers\r 2",
    "Player_9": "N.Jackson\r BRE (H)",
    "Player_15": "Robinson\r 6"
  },
  {
    "manager_Name": "1,085( 18 ) TotalXfr : 14",
    "Teams": "Debel lebeD( Kostadin Chinov )",
    "SXL": "Bulgaria",
    "Latp": "30",
    "Player_1": "Raya\r 6",
    "Player_11": "Wood\r 2",
    "Player_10": "N.Jackson\r BRE (H)",
    "Player_12": "Fabianski\r BOU (A)",
    "Player_13": "Semenyo\r WHU (H)",
    "Player_14": "Wan-Bissaka\r BOU (A)",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Virgil\r 1",
    "Player_5": "Saka\r 3",
    "Player_6": "Enzo\r BRE (H)",
    "Player_3": "Gvardiol\r MUN (H)",
    "Player_4": "Saliba\r 6",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Strand Larsen\r 2",
    "Player_15": "Mazraoui\r MCI (A)"
  },
  {
    "manager_Name": "1,084( 19 ) TotalXfr : 12",
    "Teams": "Erin\u2019s XI( Erin Robinson )",
    "SXL": "England",
    "Latp": "35",
    "Player_1": "Arrizabalaga\r WHU (H)",
    "Player_11": "Solanke\r SOU (A)",
    "Player_10": "Cunha\r 6",
    "Player_12": "Lumley\r TOT (H)",
    "Player_13": "Mbeumo\r CHE (A)",
    "Player_14": "Rogers\r 2",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "Saliba\r 6",
    "Player_5": "Hall\r 12",
    "Player_6": "B.Fernandes\r MCI (A)",
    "Player_3": "Pedro Porro\r SOU (A)",
    "Player_4": "Gabriel\r 6",
    "Player_8": "M.Salah\r 5",
    "Player_9": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "1,084( 20 ) TotalXfr : 13",
    "Teams": "Neville Wears Prada( Elijah Lamb )",
    "SXL": "England",
    "Latp": "18",
    "Player_1": "Arrizabalaga\r WHU (H)",
    "Player_11": "Solanke\r SOU (A)",
    "Player_10": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_12": "Verbruggen\r CRY (H)",
    "Player_13": "Mbeumo\r CHE (A)",
    "Player_14": "Vardy\r 1",
    "Player_7": "Semenyo\r WHU (H)",
    "Player_2": "Colwill\r BRE (H)",
    "Player_5": "Alexander-Arnold\r 1",
    "Player_6": "B.Fernandes\r MCI (A)",
    "Player_3": "J.Timber\r 6",
    "Player_4": "Gabriel\r 6",
    "Player_8": "M.Salah\r 5",
    "Player_9": "Palmer\r BRE (H)",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "1,084( 21 ) TotalXfr : 13",
    "Teams": "Bukayo\u0027s Sadza( Brendan Sylvester )",
    "SXL": "Netherlands",
    "Latp": "27",
    "Player_1": "Raya\r 6",
    "Player_11": "N.Jackson\r BRE (H)",
    "Player_10": "Cunha\r 6",
    "Player_12": "Valdimarsson\r CHE (A)",
    "Player_13": "Robinson\r 6",
    "Player_14": "Amad\r MCI (A)",
    "Player_7": "M.Salah\r 5",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Saka\r 3",
    "Player_6": "Rogers\r 2",
    "Player_3": "A\u00EFt-Nouri\r -2",
    "Player_4": "Gabriel\r 6",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "1,083( 22 ) TotalXfr : 2",
    "Teams": "\u0627\u0644\u0627\u0633\u0637\u064A( Medo Styen )",
    "SXL": "Egypt",
    "Latp": "20",
    "Player_1": "Raya\r 6",
    "Player_11": "Watkins\r 1",
    "Player_10": "Wood\r 2",
    "Player_12": "Turner\r BHA (A)",
    "Player_13": "Gibbs-White\r 5",
    "Player_14": "Robinson\r 6",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Pedro Porro\r SOU (A)",
    "Player_5": "Kulusevski\r SOU (A)",
    "Player_6": "Mbeumo\r CHE (A)",
    "Player_3": "Gvardiol\r MUN (H)",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_15": "Barco\r CRY (H)"
  },
  {
    "manager_Name": "1,083( 23 ) TotalXfr : 13",
    "Teams": "Max O\u2019Deary( Harrison Lenihan )",
    "SXL": "England",
    "Latp": "40",
    "Player_1": "S\u00E1nchez\r BRE (H)",
    "Player_11": "Wood\r 2",
    "Player_10": "Cunha\r 6",
    "Player_12": "Bentley\r 0",
    "Player_13": "Gvardiol\r MUN (H)",
    "Player_14": "Semenyo\r WHU (H)",
    "Player_7": "Saka\r 3",
    "Player_2": "Saliba\r 6",
    "Player_5": "Bowen\r BOU (A)",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Hall\r 12",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_15": "Mykolenko\r 6"
  },
  {
    "manager_Name": "1,083( 24 ) TotalXfr : 15",
    "Teams": "Blueberries( Alex Hirkjolen )",
    "SXL": "Norway",
    "Latp": "38",
    "Player_1": "Fabianski\r BOU (A)",
    "Player_11": "Cunha\r 6",
    "Player_10": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_12": "S\u00E1nchez\r BRE (H)",
    "Player_13": "Palmer\r BRE (H)",
    "Player_14": "Alexander-Arnold\r 1",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Hall\r 12",
    "Player_5": "Gabriel\r 6",
    "Player_6": "Bowen\r BOU (A)",
    "Player_3": "Dunk\r CRY (H)",
    "Player_4": "A\u00EFt-Nouri\r -2",
    "Player_8": "Rogers\r 2",
    "Player_9": "N.Jackson\r BRE (H)",
    "Player_15": "Saka\r 3"
  },
  {
    "manager_Name": "1,081( 25 ) TotalXfr : 14",
    "Teams": "Studentgra\u0111anin( vjeran horvat )",
    "SXL": "Croatia",
    "Latp": "46",
    "Player_1": "S\u00E1nchez\r BRE (H)",
    "Player_11": "Cunha\r 6",
    "Player_10": "Isak\r 9",
    "Player_12": "Fabianski\r BOU (A)",
    "Player_13": "B.Fernandes\r MCI (A)",
    "Player_14": "Robinson\r 6",
    "Player_7": "Saka\r 6",
    "Player_2": "Hall\r 12",
    "Player_5": "Rogers\r 2",
    "Player_6": "Palmer\r BRE (H)",
    "Player_3": "Saliba\r 6",
    "Player_4": "Estupi\u00F1an\r CRY (H)",
    "Player_8": "M.Salah\r 5",
    "Player_9": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_15": "Burgess\r 2"
  },
  {
    "manager_Name": "1,080( 26 ) TotalXfr : 17",
    "Teams": "Que Salah Salah( Derek SHANKS )",
    "SXL": "USA",
    "Latp": "21",
    "Player_1": "Forster\r SOU (A)",
    "Player_11": "Wood\r 2",
    "Player_10": "Cunha\r 6",
    "Player_12": "Turner\r BHA (A)",
    "Player_13": "Keane\r 0",
    "Player_14": "Faes\r 0",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "Gabriel\r 6",
    "Player_5": "Saka\r 3",
    "Player_6": "Amad\r MCI (A)",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "A\u00EFt-Nouri\r -2",
    "Player_8": "M.Salah\r 5",
    "Player_9": "Semenyo\r WHU (H)",
    "Player_15": "Ra\u00FAl\r 2"
  },
  {
    "manager_Name": "1,079( 27 ) TotalXfr : 13",
    "Teams": "\u0E22\u0E2D\u0E14\u0E17\u0E35\u0E21United( Thanan Nuannukun )",
    "SXL": "Thailand",
    "Latp": "21",
    "Player_1": "Henderson\r BHA (A)",
    "Player_11": "Wood\r 2",
    "Player_10": "Welbeck\r CRY (H)",
    "Player_12": "S\u00E1nchez\r BRE (H)",
    "Player_13": "Wissa\r CHE (A)",
    "Player_14": "Mazraoui\r MCI (A)",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "Wan-Bissaka\r BOU (A)",
    "Player_5": "Mbeumo\r CHE (A)",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Gvardiol\r MUN (H)",
    "Player_8": "Saka\r 3",
    "Player_9": "Kulusevski\r SOU (A)",
    "Player_15": "Pedro Porro\r SOU (A)"
  },
  {
    "manager_Name": "1,079( 28 ) TotalXfr : 14",
    "Teams": "KobbieManU( JAMIE WALKER )",
    "SXL": "England",
    "Latp": "27",
    "Player_1": "Raya\r 6",
    "Player_11": "N.Jackson\r BRE (H)",
    "Player_10": "Cunha\r 6",
    "Player_12": "Fabianski\r BOU (A)",
    "Player_13": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_14": "Rogers\r 2",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "Gabriel\r 6",
    "Player_5": "A\u00EFt-Nouri\r -2",
    "Player_6": "Bowen\r BOU (A)",
    "Player_3": "Pedro Porro\r SOU (A)",
    "Player_4": "Gvardiol\r MUN (H)",
    "Player_8": "M.Salah\r 5",
    "Player_9": "Gordon\r 6",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "1,079( 29 ) TotalXfr : 16",
    "Teams": "OlympiqueCliftonHill( Ignaz Vrobel )",
    "SXL": "Australia",
    "Latp": "24",
    "Player_1": "Raya\r 6",
    "Player_11": "Havertz\r 2",
    "Player_10": "Wood\r 2",
    "Player_12": "Fabianski\r BOU (A)",
    "Player_13": "Wissa\r CHE (A)",
    "Player_14": "Mazraoui\r MCI (A)",
    "Player_7": "Saka\r 3",
    "Player_2": "Dunk\r CRY (H)",
    "Player_5": "M.Salah\r 10",
    "Player_6": "Palmer\r BRE (H)",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Colwill\r BRE (H)",
    "Player_8": "Mbeumo\r CHE (A)",
    "Player_9": "Enzo\r BRE (H)",
    "Player_15": "Barco\r CRY (H)"
  },
  {
    "manager_Name": "1,079( 29 ) TotalXfr : 16",
    "Teams": "Kaluno City( Innocent Kalukuta )",
    "SXL": "Malawi",
    "Latp": "28",
    "Player_1": "Raya\r 6",
    "Player_11": "Cunha\r 6",
    "Player_10": "Wood\r 2",
    "Player_12": "S\u00E1nchez\r BRE (H)",
    "Player_13": "Mbeumo\r CHE (A)",
    "Player_14": "Veltman\r CRY (H)",
    "Player_7": "M.Salah\r 5",
    "Player_2": "Huijsen\r WHU (H)",
    "Player_5": "Saka\r 6",
    "Player_6": "B.Fernandes\r MCI (A)",
    "Player_3": "Gomez\r 1",
    "Player_4": "Digne\r 2",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_15": "Davis\r 2"
  },
  {
    "manager_Name": "1,078( 31 ) TotalXfr : 13",
    "Teams": "The Seniors( Radhi Alqaisi )",
    "SXL": "Egypt",
    "Latp": "40",
    "Player_1": "Sels\r 2",
    "Player_11": "Isak\r 9",
    "Player_10": "Cunha\r 6",
    "Player_12": "Flekken\r CHE (A)",
    "Player_13": "Rogers\r 2",
    "Player_14": "Faes\r 0",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "A\u00EFt-Nouri\r -2",
    "Player_5": "Mbeumo\r CHE (A)",
    "Player_6": "Saka\r 3",
    "Player_3": "J.Timber\r 6",
    "Player_4": "Gabriel\r 6",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "1,078( 31 ) TotalXfr : 14",
    "Teams": "Stella Rosa( Kristijan Anicic )",
    "SXL": "Bosnia-Herzegovina",
    "Latp": "23",
    "Player_1": "Verbruggen\r CRY (H)",
    "Player_11": "Isak\r 9",
    "Player_10": "Evanilson\r WHU (H)",
    "Player_12": "Fabianski\r BOU (A)",
    "Player_13": "Rogers\r 2",
    "Player_14": "Burn\r 6",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "J.Timber\r 6",
    "Player_5": "Saka\r 3",
    "Player_6": "Bowen\r BOU (A)",
    "Player_3": "Gvardiol\r MUN (H)",
    "Player_4": "Kerkez\r WHU (H)",
    "Player_8": "M.Salah\r 5",
    "Player_9": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_15": "Van den Berg\r CHE (A)"
  },
  {
    "manager_Name": "1,078( 33 ) TotalXfr : 14",
    "Teams": "AW( Adrian Wagstyl )",
    "SXL": "Poland",
    "Latp": "23",
    "Player_1": "Sels\r 2",
    "Player_11": "Cunha\r 6",
    "Player_10": "N.Jackson\r BRE (H)",
    "Player_12": "Fabianski\r BOU (A)",
    "Player_13": "Wood\r 2",
    "Player_14": "Mazraoui\r MCI (A)",
    "Player_7": "Saka\r 3",
    "Player_2": "Justin\r 0",
    "Player_5": "Palmer\r BRE (H)",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Aina\r 2",
    "Player_4": "Pedro Porro\r SOU (A)",
    "Player_8": "Mitoma\r CRY (H)",
    "Player_9": "Mbeumo\r CHE (A)",
    "Player_15": "Robinson\r 6"
  },
  {
    "manager_Name": "1,078( 34 ) TotalXfr : 17",
    "Teams": "I AM PANDA( Fahad Al kharafi\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC )",
    "SXL": "Kuwait",
    "Latp": "47",
    "Player_1": "Fabianski\r BOU (A)",
    "Player_11": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_10": "Isak\r 9",
    "Player_12": "Henderson\r BHA (A)",
    "Player_13": "Digne\r 2",
    "Player_14": "Faes\r 0",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "Hall\r 12",
    "Player_5": "Mbeumo\r CHE (A)",
    "Player_6": "Saka\r 3",
    "Player_3": "J.Timber\r 6",
    "Player_4": "Gabriel\r 6",
    "Player_8": "M.Salah\r 5",
    "Player_9": "Cunha\r 6",
    "Player_15": "McNeil\r 0"
  },
  {
    "manager_Name": "1,077( 35 ) TotalXfr : 12",
    "Teams": "7OoOda( Mahmoud Ibrahim )",
    "SXL": "Egypt",
    "Latp": "17",
    "Player_1": "S\u00E1nchez\r BRE (H)",
    "Player_11": "N.Jackson\r BRE (H)",
    "Player_10": "Cunha\r 6",
    "Player_12": "Turner\r BHA (A)",
    "Player_13": "Lewis\r MUN (H)",
    "Player_14": "Vardy\r 1",
    "Player_7": "Bowen\r BOU (A)",
    "Player_2": "A\u00EFt-Nouri\r -2",
    "Player_5": "Saka\r 3",
    "Player_6": "Palmer\r BRE (H)",
    "Player_3": "Dunk\r CRY (H)",
    "Player_4": "Wan-Bissaka\r BOU (A)",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Mbeumo\r CHE (A)",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "1,077( 36 ) TotalXfr : 15",
    "Teams": "back of the Neto( marwen fathallah )",
    "SXL": "Tunisia",
    "Latp": "33",
    "Player_1": "Sels\r 2",
    "Player_11": "Cunha\r 6",
    "Player_10": "N.Jackson\r BRE (H)",
    "Player_12": "Fabianski\r BOU (A)",
    "Player_13": "Delap\r 2",
    "Player_14": "Digne\r 2",
    "Player_7": "Gordon\r 6",
    "Player_2": "J.Timber\r 6",
    "Player_5": "Palmer\r BRE (H)",
    "Player_6": "Saka\r 3",
    "Player_3": "Davis\r 2",
    "Player_4": "A\u00EFt-Nouri\r -2",
    "Player_8": "M.Salah\r 10",
    "Player_9": "B.Fernandes\r MCI (A)",
    "Player_15": "Van den Berg\r CHE (A)"
  },
  {
    "manager_Name": "1,076( 37 ) TotalXfr : 12",
    "Teams": "Gus@lito.( You guy My guy. )",
    "SXL": "Kenya",
    "Latp": "27",
    "Player_1": "S\u00E1nchez\r BRE (H)",
    "Player_11": "Isak\r 9",
    "Player_10": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_12": "Kelleher\r 0",
    "Player_13": "Vardy\r 1",
    "Player_14": "Mykolenko\r 6",
    "Player_7": "Saka\r 3",
    "Player_2": "Saliba\r 6",
    "Player_5": "M.Salah\r 5",
    "Player_6": "Palmer\r BRE (H)",
    "Player_3": "Livramento\r 6",
    "Player_4": "A\u00EFt-Nouri\r -2",
    "Player_8": "Kudus\r BOU (A)",
    "Player_9": "B.Fernandes\r MCI (A)",
    "Player_15": "Lewis\r MUN (H)"
  },
  {
    "manager_Name": "1,075( 38 ) TotalXfr : 13",
    "Teams": "Charlie\u2019s team( Charlie Shepherd )",
    "SXL": "England",
    "Latp": "36",
    "Player_1": "Raya\r 6",
    "Player_11": "Cunha\r 6",
    "Player_10": "Solanke\r SOU (A)",
    "Player_12": "Dennis\r WHU (H)",
    "Player_13": "Rogers\r 2",
    "Player_14": "Robinson\r 6",
    "Player_7": "M.Salah\r 5",
    "Player_2": "Gabriel\r 6",
    "Player_5": "Semenyo\r WHU (H)",
    "Player_6": "Saka\r 3",
    "Player_3": "Pedro Porro\r SOU (A)",
    "Player_4": "Konsa\r 1",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Isak\r 9",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "1,075( 38 ) TotalXfr : 12",
    "Teams": "NYC Whites( Andrew Warriner )",
    "SXL": "England",
    "Latp": "30",
    "Player_1": "Verbruggen\r CRY (H)",
    "Player_11": "Isak\r 9",
    "Player_10": "Cunha\r 6",
    "Player_12": "Flekken\r CHE (A)",
    "Player_13": "Rogers\r 2",
    "Player_14": "Greaves\r 0",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "A\u00EFt-Nouri\r -2",
    "Player_5": "Saka\r 3",
    "Player_6": "Johnson\r SOU (A)",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Gomez\r 1",
    "Player_8": "M.Salah\r 5",
    "Player_9": "Wood\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "1,075( 38 ) TotalXfr : 13",
    "Teams": "Elkabiri mohamed( Mohamed elkabiri )",
    "SXL": "Morocco",
    "Latp": "39",
    "Player_1": "Raya\r 6",
    "Player_11": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_10": "Cunha\r 6",
    "Player_12": "Turner\r BHA (A)",
    "Player_13": "Rogers\r 2",
    "Player_14": "Konat\u00E9\r 0",
    "Player_7": "Saka\r 3",
    "Player_2": "A\u00EFt-Nouri\r -2",
    "Player_5": "Bowen\r BOU (A)",
    "Player_6": "M.Salah\r 5",
    "Player_3": "Robinson\r 6",
    "Player_4": "Mykolenko\r 6",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Isak\r 9",
    "Player_15": "Lewis\r MUN (H)"
  },
  {
    "manager_Name": "1,075( 41 ) TotalXfr : 13",
    "Teams": "Big Football( the Big studio Ug )",
    "SXL": "Uganda",
    "Latp": "21",
    "Player_1": "Flekken\r CHE (A)",
    "Player_11": "Cunha\r 6",
    "Player_10": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_12": "Onana\r MCI (A)",
    "Player_13": "Doku\r MUN (H)",
    "Player_14": "Dalot\r MCI (A)",
    "Player_7": "Saka\r 3",
    "Player_2": "Gvardiol\r MUN (H)",
    "Player_5": "Palmer\r BRE (H)",
    "Player_6": "Mbeumo\r CHE (A)",
    "Player_3": "A\u00EFt-Nouri\r -2",
    "Player_4": "Murillo\r 2",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Strand Larsen\r 2",
    "Player_15": "Robinson\r 6"
  },
  {
    "manager_Name": "1,075( 41 ) TotalXfr : 14",
    "Teams": "H\u0026M( hossam Mohamed )",
    "SXL": "Egypt",
    "Latp": "20",
    "Player_1": "Raya\r 6",
    "Player_11": "Cunha\r 6",
    "Player_10": "Evanilson\r WHU (H)",
    "Player_12": "Onana\r MCI (A)",
    "Player_13": "Wissa\r CHE (A)",
    "Player_14": "Digne\r 2",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Estupi\u00F1an\r CRY (H)",
    "Player_5": "Mitoma\r CRY (H)",
    "Player_6": "Mbeumo\r CHE (A)",
    "Player_3": "A\u00EFt-Nouri\r -2",
    "Player_4": "Pedro Porro\r SOU (A)",
    "Player_8": "B.Fernandes\r MCI (A)",
    "Player_9": "Palmer\r BRE (H)",
    "Player_15": "Dalot\r MCI (A)"
  },
  {
    "manager_Name": "1,075( 41 ) TotalXfr : 13",
    "Teams": "Remon FC( Remon Radany )",
    "SXL": "Egypt",
    "Latp": "37",
    "Player_1": "S\u00E1nchez\r BRE (H)",
    "Player_11": "Isak\r 9",
    "Player_10": "N.Jackson\r BRE (H)",
    "Player_12": "Pickford\r 6",
    "Player_13": "Rogers\r 2",
    "Player_14": "Collins\r CHE (A)",
    "Player_7": "Bowen\r BOU (A)",
    "Player_2": "Hall\r 12",
    "Player_5": "Saka\r 3",
    "Player_6": "Palmer\r BRE (H)",
    "Player_3": "Aina\r 2",
    "Player_4": "J.Timber\r 6",
    "Player_8": "M.Salah\r 5",
    "Player_9": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_15": "Robinson\r 6"
  },
  {
    "manager_Name": "1,075( 41 ) TotalXfr : 14",
    "Teams": "The Leader Yaser( Yaser Hameed )",
    "SXL": "Yemen",
    "Latp": "21",
    "Player_1": "Martinez\r 2",
    "Player_11": "Cunha\r 6",
    "Player_10": "Welbeck\r CRY (H)",
    "Player_12": "Onana\r MCI (A)",
    "Player_13": "Bree\r TOT (H)",
    "Player_14": "Taylor\r TOT (H)",
    "Player_7": "Saka\r 3",
    "Player_2": "Virgil\r 1",
    "Player_5": "M.Salah\r 10",
    "Player_6": "Palmer\r BRE (H)",
    "Player_3": "A\u00EFt-Nouri\r -2",
    "Player_4": "Pedro Porro\r SOU (A)",
    "Player_8": "Mbeumo\r CHE (A)",
    "Player_9": "Vardy\r 1",
    "Player_15": "Sou\u010Dek\r BOU (A)"
  },
  {
    "manager_Name": "1,075( 45 ) TotalXfr : 15",
    "Teams": "TAAnnihilation( Tom Warlow )",
    "SXL": "England",
    "Latp": "15",
    "Player_1": "Fabianski\r BOU (A)",
    "Player_11": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_10": "N.Jackson\r BRE (H)",
    "Player_12": "Flekken\r CHE (A)",
    "Player_13": "Cunha\r 6",
    "Player_14": "Colwill\r BRE (H)",
    "Player_7": "Bowen\r BOU (A)",
    "Player_2": "Konsa\r 1",
    "Player_5": "Saka\r 3",
    "Player_6": "Palmer\r BRE (H)",
    "Player_3": "Gvardiol\r MUN (H)",
    "Player_4": "Gabriel\r 6",
    "Player_8": "M.Salah\r 5",
    "Player_9": "Semenyo\r WHU (H)",
    "Player_15": "Van den Berg\r CHE (A)"
  },
  {
    "manager_Name": "1,075( 46 ) TotalXfr : 17",
    "Teams": "Muthe #1 SSK( Agustio Faizy )",
    "SXL": "Indonesia",
    "Latp": "21",
    "Player_1": "Onana\r MCI (A)",
    "Player_11": "Cunha\r 6",
    "Player_10": "Wissa\r CHE (A)",
    "Player_12": "Flekken\r CHE (A)",
    "Player_13": "Sancho\r BRE (H)",
    "Player_14": "Martinez\r MCI (A)",
    "Player_7": "Palmer\r BRE (H)",
    "Player_2": "Lacroix\r BHA (A)",
    "Player_5": "Johnson\r SOU (A)",
    "Player_6": "Saka\r 3",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Colwill\r BRE (H)",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Vardy\r 1",
    "Player_15": "Gu\u00E9hi\r BHA (A)"
  },
  {
    "manager_Name": "1,075( 47 ) TotalXfr : 18",
    "Teams": "Joelinton Enjoyer( James White )",
    "SXL": "New Zealand",
    "Latp": "42",
    "Player_1": "Verbruggen\r CRY (H)",
    "Player_11": "Cunha\r 6",
    "Player_10": "Isak\r 9",
    "Player_12": "Dennis\r WHU (H)",
    "Player_13": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_14": "Mykolenko\r 6",
    "Player_7": "\u00D8degaard\r 3",
    "Player_2": "A\u00EFt-Nouri\r -2",
    "Player_5": "Palmer\r BRE (H)",
    "Player_6": "Saka\r 3",
    "Player_3": "Gabriel\r 6",
    "Player_4": "Hall\r 12",
    "Player_8": "M.Salah\r 5",
    "Player_9": "Enzo\r BRE (H)",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "1,074( 48 ) TotalXfr : 12",
    "Teams": "The Vampires( Andrew Monaghan )",
    "SXL": "England",
    "Latp": "32",
    "Player_1": "S\u00E1nchez\r BRE (H)",
    "Player_11": "Delap\r 2",
    "Player_10": "N.Jackson\r BRE (H)",
    "Player_12": "Sels\r 2",
    "Player_13": "Rogers\r 2",
    "Player_14": "Smith Rowe\r 1",
    "Player_7": "Saka\r 3",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Hall\r 12",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Saliba\r 6",
    "Player_4": "A\u00EFt-Nouri\r -2",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_15": "Robinson\r 6"
  },
  {
    "manager_Name": "1,074( 49 ) TotalXfr : 15",
    "Teams": "Fly me to the Muniz( Sarah Henshaw )",
    "SXL": "England",
    "Latp": "25",
    "Player_1": "Flekken\r CHE (A)",
    "Player_11": "Strand Larsen\r 2",
    "Player_10": "Wood\r 2",
    "Player_12": "Areola\r BOU (A)",
    "Player_13": "Aina\r 2",
    "Player_14": "Robinson\r 6",
    "Player_7": "Saka\r 3",
    "Player_2": "Saliba\r 6",
    "Player_5": "M.Salah\r 10",
    "Player_6": "Mbeumo\r CHE (A)",
    "Player_3": "Gvardiol\r MUN (H)",
    "Player_4": "Digne\r 2",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Jo\u00E3o Pedro\r CRY (H)",
    "Player_15": "Smith Rowe\r 1"
  },
  {
    "manager_Name": "1,074( 49 ) TotalXfr : 13",
    "Teams": "Vee Fc( Oluchukwu Obiyo )",
    "SXL": "Nigeria",
    "Latp": "27",
    "Player_1": "Jos\u00E9 S\u00E1\r 0",
    "Player_11": "Wissa\r CHE (A)",
    "Player_10": "N.Jackson\r BRE (H)",
    "Player_12": "Flekken\r CHE (A)",
    "Player_13": "Doku\r MUN (H)",
    "Player_14": "O\u0027Shea\r 2",
    "Player_7": "Rashford\r MCI (A)",
    "Player_2": "A\u00EFt-Nouri\r -2",
    "Player_5": "M.Salah\r 5",
    "Player_6": "Saka\r 6",
    "Player_3": "Martinez\r MCI (A)",
    "Player_4": "Hall\r 12",
    "Player_8": "Palmer\r BRE (H)",
    "Player_9": "Cunha\r 6",
    "Player_15": "Young\r 5"
  }
];