var s = [
  {
    "manager_Name": "682( 11 ) TotalXfr : 5",
    "Teams": "Holy Boehly( james delaney )",
    "SXL": "EN",
    "Latp": "72",
    "Player_1": "Martinez\r 2",
    "Player_11": "Calvert-Lewin\r 2",
    "Player_10": "Watkins\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Saka\r 9",
    "Player_14": "Johnson\r 0",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Gvardiol\r 9",
    "Player_5": "Robinson\r 2",
    "Player_6": "Bernardo\r 3",
    "Player_3": "Faes\r 1",
    "Player_4": "Lewis\r 6",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Palmer\r 20",
    "Player_15": "Jebbison\r 0"
  },
  {
    "manager_Name": "665( 86 ) TotalXfr : 6",
    "Teams": "The Crabs( Ryan Breen )",
    "SXL": "EN",
    "Latp": "63",
    "Player_1": "Ederson M.\r 6",
    "Player_11": "Vardy\r 8",
    "Player_10": "N.Jackson\r 9",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Faes\r 1",
    "Player_14": "Cresswell\r 0",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Palmer\r 10",
    "Player_6": "Foden\r 6",
    "Player_3": "Van de Ven\r 1",
    "Player_4": "Konsa\r 2",
    "Player_8": "Luis D\u00EDaz\r 5",
    "Player_9": "Delap\r 5",
    "Player_15": "Moder\r 0"
  },
  {
    "manager_Name": "665( 91 ) TotalXfr : 7",
    "Teams": "Nku\u00B2( Luke Mason )",
    "SXL": "EN",
    "Latp": "84",
    "Player_1": "Martinez\r 2",
    "Player_11": "Ra\u00FAl\r 2",
    "Player_10": "Haaland\r 12",
    "Player_12": "Sels\r 5",
    "Player_13": "Smith Rowe\r 6",
    "Player_14": "Dunk\r 0",
    "Player_7": "Palmer\r 10",
    "Player_2": "Gvardiol\r 9",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "Buonanotte\r 2",
    "Player_3": "Harwood-Bellis\r 2",
    "Player_4": "Digne\r 7",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Wood\r 13",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "660( 164 ) TotalXfr : 8",
    "Teams": "U petr cech yourself( danny jones )",
    "SXL": "EN",
    "Latp": "78",
    "Player_1": "Sels\r 5",
    "Player_11": "N.Jackson\r 9",
    "Player_10": "Watkins\r 2",
    "Player_12": "S\u00E1nchez\r 1",
    "Player_13": "Son\r 0",
    "Player_14": "Gabriel\r 1",
    "Player_7": "Saka\r 9",
    "Player_2": "Konsa\r 2",
    "Player_5": "Mbeumo\r 30",
    "Player_6": "Foden\r 3",
    "Player_3": "Robinson\r 2",
    "Player_4": "Lewis\r 6",
    "Player_8": "Rogers\r 1",
    "Player_9": "Cunha\r 9",
    "Player_15": "Konat\u00E9\r 1"
  },
  {
    "manager_Name": "656( 240 ) TotalXfr : 6",
    "Teams": "Neville Wears Prada( Elijah Lamb )",
    "SXL": "EN",
    "Latp": "64",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Solanke\r 2",
    "Player_12": "Ward\r 0",
    "Player_13": "Dunk\r 0",
    "Player_14": "Alex Moreno\r 1",
    "Player_7": "Eze\r 6",
    "Player_2": "Van Hecke\r 1",
    "Player_5": "Foden\r 3",
    "Player_6": "Palmer\r 10",
    "Player_3": "Pinnock\r 1",
    "Player_4": "Lewis\r 6",
    "Player_8": "Bowen\r 7",
    "Player_9": "Mbeumo\r 15",
    "Player_15": "Chiwome\r 0"
  },
  {
    "manager_Name": "656( 248 ) TotalXfr : 7",
    "Teams": "Ctrl Alt De Ligt( Anil Benji )",
    "SXL": "EN",
    "Latp": "78",
    "Player_1": "Flekken\r 1",
    "Player_11": "Watkins\r 2",
    "Player_10": "Wood\r 13",
    "Player_12": "Verbruggen\r 2",
    "Player_13": "Son\r 0",
    "Player_14": "Aina\r 2",
    "Player_7": "Palmer\r 10",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "M.Salah\r 10",
    "Player_6": "Rogers\r 1",
    "Player_3": "Robinson\r 2",
    "Player_4": "Lewis\r 6",
    "Player_8": "Mbeumo\r 30",
    "Player_9": "Calvert-Lewin\r 2",
    "Player_15": "Nedeljkovic\r 0"
  },
  {
    "manager_Name": "656( 248 ) TotalXfr : 7",
    "Teams": "GegenDepressing( Taha Ahmed )",
    "SXL": "PK",
    "Latp": "69",
    "Player_1": "Sels\r 5",
    "Player_11": "Watkins\r 2",
    "Player_10": "Solanke\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Son\r 0",
    "Player_14": "Faes\r 1",
    "Player_7": "Palmer\r 10",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Collins\r 1",
    "Player_6": "M.Salah\r 20",
    "Player_3": "Lewis\r 6",
    "Player_4": "A\u00EFt-Nouri\r 6",
    "Player_8": "Rogers\r 1",
    "Player_9": "Mbeumo\r 15",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "655( 275 ) TotalXfr : 7",
    "Teams": "Im Sorry Nic Jackson( Matthew Burton )",
    "SXL": "EN",
    "Latp": "56",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Watkins\r 2",
    "Player_10": "Haaland\r 12",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Mazraoui\r 2",
    "Player_14": "Faes\r 1",
    "Player_7": "Bernardo\r 3",
    "Player_2": "Romero\r 2",
    "Player_5": "Palmer\r 10",
    "Player_6": "Mbeumo\r 15",
    "Player_3": "Digne\r 7",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Rogers\r 1",
    "Player_9": "Solanke\r 2",
    "Player_15": "Bergvall\r 0"
  },
  {
    "manager_Name": "654( 292 ) TotalXfr : 4",
    "Teams": "Kobbie Dobbie Doo( Oliver Thompson )",
    "SXL": "EN",
    "Latp": "74",
    "Player_1": "Henderson\r 8",
    "Player_11": "Watkins\r 2",
    "Player_10": "Haaland\r 12",
    "Player_12": "Turner\r 0",
    "Player_13": "Harwood-Bellis\r 2",
    "Player_14": "Faes\r 1",
    "Player_7": "Luis D\u00EDaz\r 5",
    "Player_2": "Mazraoui\r 2",
    "Player_5": "Smith Rowe\r 6",
    "Player_6": "Mbeumo\r 15",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "Hall\r 4",
    "Player_8": "Saka\r 9",
    "Player_9": "Palmer\r 10",
    "Player_15": "Jebbison\r 0"
  },
  {
    "manager_Name": "654( 298 ) TotalXfr : 7",
    "Teams": "TAAnnihilation( Tom Warlow )",
    "SXL": "EN",
    "Latp": "79",
    "Player_1": "Flekken\r 1",
    "Player_11": "Wood\r 13",
    "Player_10": "Haaland\r 12",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Son\r 0",
    "Player_14": "Van den Berg\r 1",
    "Player_7": "Palmer\r 10",
    "Player_2": "Gvardiol\r 9",
    "Player_5": "McNeil\r 2",
    "Player_6": "Mbeumo\r 15",
    "Player_3": "Lewis\r 6",
    "Player_4": "Konsa\r 2",
    "Player_8": "Rogers\r 1",
    "Player_9": "Vardy\r 8",
    "Player_15": "Gabriel\r 1"
  },
  {
    "manager_Name": "654( 298 ) TotalXfr : 7",
    "Teams": "Banbury United( Ismail Hussain )",
    "SXL": "EN",
    "Latp": "81",
    "Player_1": "Martinez\r 2",
    "Player_11": "Wood\r 13",
    "Player_10": "Delap\r 5",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Robinson\r 2",
    "Player_14": "Faes\r 1",
    "Player_7": "M.Salah\r 20",
    "Player_2": "Dalot\r 1",
    "Player_5": "Palmer\r 10",
    "Player_6": "Eze\r 6",
    "Player_3": "Lewis\r 6",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Solanke\r 2",
    "Player_15": "Winks\r 4"
  },
  {
    "manager_Name": "654( 318 ) TotalXfr : 9",
    "Teams": "Back of the Neto( Jack Berry )",
    "SXL": "EN",
    "Latp": "90",
    "Player_1": "Henderson\r 8",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Rogers\r 1",
    "Player_14": "Johnson\r 0",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "Palmer\r 10",
    "Player_6": "Maddison\r 2",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Foden\r 3",
    "Player_9": "Wissa\r 10",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "653( 353 ) TotalXfr : 9",
    "Teams": "Super Frank( Thomas Goodey )",
    "SXL": "EN",
    "Latp": "71",
    "Player_1": "Flekken\r 1",
    "Player_11": "Watkins\r 2",
    "Player_10": "Haaland\r 12",
    "Player_12": "Raya\r 0",
    "Player_13": "Smith Rowe\r 6",
    "Player_14": "Faes\r 1",
    "Player_7": "Johnson\r 1",
    "Player_2": "Dalot\r 1",
    "Player_5": "Palmer\r 10",
    "Player_6": "Mbeumo\r 15",
    "Player_3": "Lewis\r 6",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Rogers\r 1",
    "Player_9": "Wood\r 13",
    "Player_15": "Gabriel\r 1"
  },
  {
    "manager_Name": "653( 354 ) TotalXfr : 10",
    "Teams": "too easy( cammy finnie )",
    "SXL": "S1",
    "Latp": "79",
    "Player_1": "Sels\r 5",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Greaves\r 0",
    "Player_14": "Stewart\r 0",
    "Player_7": "McNeil\r 2",
    "Player_2": "Pinnock\r 1",
    "Player_5": "Rogers\r 1",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Saka\r 9",
    "Player_15": "Tuanzebe\r 0"
  },
  {
    "manager_Name": "652( 358 ) TotalXfr : 6",
    "Teams": "Holy Boehly( Niels Pretorius )",
    "SXL": "NO",
    "Latp": "61",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 18",
    "Player_10": "Watkins\r 2",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Saka\r 9",
    "Player_14": "Mykolenko\r 2",
    "Player_7": "Rogers\r 1",
    "Player_2": "Aina\r 2",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "McNeil\r 2",
    "Player_3": "Robinson\r 2",
    "Player_4": "A\u00EFt-Nouri\r 6",
    "Player_8": "Palmer\r 10",
    "Player_9": "Solanke\r 2",
    "Player_15": "Van den Berg\r 1"
  },
  {
    "manager_Name": "652( 390 ) TotalXfr : 8",
    "Teams": "Habibis FC( ivan rovinskiy )",
    "SXL": "DK",
    "Latp": "68",
    "Player_1": "Flekken\r 1",
    "Player_11": "Havertz\r 2",
    "Player_10": "Watkins\r 2",
    "Player_12": "Verbruggen\r 2",
    "Player_13": "Dunk\r 0",
    "Player_14": "Greaves\r 0",
    "Player_7": "Saka\r 9",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Mbeumo\r 30",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Milenkovi\u0107\r 1",
    "Player_4": "Pinnock\r 1",
    "Player_8": "Rogers\r 1",
    "Player_9": "Palmer\r 10",
    "Player_15": "Jo\u00E3o Pedro\r 0"
  },
  {
    "manager_Name": "651( 426 ) TotalXfr : 7",
    "Teams": "Specy UTD \uFFFD( Robert Maftei )",
    "SXL": "EN",
    "Latp": "78",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Wood\r 13",
    "Player_10": "Haaland\r 12",
    "Player_12": "Iversen\r 0",
    "Player_13": "Son\r 0",
    "Player_14": "M.Salah\r 10",
    "Player_7": "Rogers\r 1",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Robinson\r 2",
    "Player_6": "Digne\r 7",
    "Player_3": "Aina\r 2",
    "Player_4": "Lewis\r 6",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Welbeck\r 7",
    "Player_15": "Semenyo\r 1"
  },
  {
    "manager_Name": "651( 426 ) TotalXfr : 7",
    "Teams": "FPL Champ( Vetle Henriksen )",
    "SXL": "NO",
    "Latp": "60",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Konat\u00E9\r 1",
    "Player_14": "Nedeljkovic\r 0",
    "Player_7": "Palmer\r 10",
    "Player_2": "Dalot\r 1",
    "Player_5": "Smith Rowe\r 6",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Robinson\r 2",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "McNeil\r 2",
    "Player_9": "Kova\u010Di\u0107\r 2",
    "Player_15": "Ui-jo\r 0"
  },
  {
    "manager_Name": "650( 456 ) TotalXfr : 5",
    "Teams": "VARdy time( Toby Perkins )",
    "SXL": "EN",
    "Latp": "76",
    "Player_1": "Flekken\r 1",
    "Player_11": "Watkins\r 2",
    "Player_10": "Vardy\r 8",
    "Player_12": "Verbruggen\r 2",
    "Player_13": "Son\r 0",
    "Player_14": "Dunk\r 0",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Gabriel\r 1",
    "Player_5": "M.Salah\r 10",
    "Player_6": "Palmer\r 20",
    "Player_3": "Konsa\r 2",
    "Player_4": "Robinson\r 2",
    "Player_8": "McNeil\r 2",
    "Player_9": "Wood\r 13",
    "Player_15": "Davis\r 2"
  },
  {
    "manager_Name": "650( 489 ) TotalXfr : 8",
    "Teams": "PeakyBlinders( Kishan Solanki )",
    "SXL": "EN",
    "Latp": "67",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Calvert-Lewin\r 2",
    "Player_10": "Watkins\r 2",
    "Player_12": "Iversen\r 0",
    "Player_13": "Mazraoui\r 2",
    "Player_14": "Son\r 0",
    "Player_7": "Mbeumo\r 30",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Palmer\r 10",
    "Player_6": "Rogers\r 1",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Konsa\r 2",
    "Player_8": "Foden\r 3",
    "Player_9": "Wood\r 13",
    "Player_15": "Harwood-Bellis\r 2"
  },
  {
    "manager_Name": "650( 496 ) TotalXfr : 9",
    "Teams": "Change Name( Steven L )",
    "SXL": "AU",
    "Latp": "56",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Solanke\r 2",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Faes\r 1",
    "Player_14": "Greaves\r 0",
    "Player_7": "Adama\r 3",
    "Player_2": "Lewis\r 6",
    "Player_5": "Johnson\r 1",
    "Player_6": "Rogers\r 1",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "Palmer\r 10",
    "Player_9": "M.Salah\r 10",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "649( 508 ) TotalXfr : 6",
    "Teams": "cheesy fc( Eoin Kinsella )",
    "SXL": "IE",
    "Latp": "85",
    "Player_1": "Pope\r 2",
    "Player_11": "Vardy\r 8",
    "Player_10": "Watkins\r 2",
    "Player_12": "J.Virginia\r 0",
    "Player_13": "Dalot\r 1",
    "Player_14": "Choudhury\r 0",
    "Player_7": "M.Salah\r 20",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "Bowen\r 7",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Akanji\r 6",
    "Player_8": "Palmer\r 10",
    "Player_9": "Wood\r 13",
    "Player_15": "Burgess\r 0"
  },
  {
    "manager_Name": "649( 520 ) TotalXfr : 7",
    "Teams": "Tyler( Tyler Jeffreys )",
    "SXL": "EN",
    "Latp": "74",
    "Player_1": "Sels\r 5",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Van den Berg\r 1",
    "Player_14": "Mosquera\r 0",
    "Player_7": "Foden\r 3",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Palmer\r 10",
    "Player_6": "Garnacho\r 2",
    "Player_3": "Aina\r 2",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Mitoma\r 2",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "649( 520 ) TotalXfr : 7",
    "Teams": "Leo messi( Leo Messi )",
    "SXL": "EG",
    "Latp": "74",
    "Player_1": "Flekken\r 1",
    "Player_11": "Watkins\r 2",
    "Player_10": "Welbeck\r 7",
    "Player_12": "Ramsdale\r 4",
    "Player_13": "Calvert-Lewin\r 2",
    "Player_14": "Robinson\r 2",
    "Player_7": "Mbeumo\r 30",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Palmer\r 10",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Aina\r 2",
    "Player_8": "Rogers\r 1",
    "Player_9": "Semenyo\r 1",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "649( 553 ) TotalXfr : 9",
    "Teams": "Sakas sauce and rice( Reece King )",
    "SXL": "EN",
    "Latp": "85",
    "Player_1": "Henderson\r 8",
    "Player_11": "Watkins\r 2",
    "Player_10": "Vardy\r 8",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Dunk\r 0",
    "Player_14": "Jo\u00E3o Pedro\r 0",
    "Player_7": "Palmer\r 10",
    "Player_2": "Davis\r 2",
    "Player_5": "Rogers\r 1",
    "Player_6": "Foden\r 3",
    "Player_3": "Konsa\r 2",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Mbeumo\r 30",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "647( 638 ) TotalXfr : 7",
    "Teams": "Lepp\u00E4vaara Fc( \uB204\uC544 \uBC14\uB2E5 )",
    "SXL": "FI",
    "Latp": "69",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Solanke\r 2",
    "Player_10": "Haaland\r 18",
    "Player_12": "Bentley\r 0",
    "Player_13": "Rogers\r 1",
    "Player_14": "Gabriel\r 1",
    "Player_7": "Smith Rowe\r 6",
    "Player_2": "Van de Ven\r 1",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "Palmer\r 10",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Robinson\r 2",
    "Player_8": "Foden\r 3",
    "Player_9": "Calvert-Lewin\r 2",
    "Player_15": "Bella-Kotchap\r 0"
  },
  {
    "manager_Name": "647( 638 ) TotalXfr : 7",
    "Teams": "Tramiro Alt( Tramiro Backup )",
    "SXL": "EN",
    "Latp": "66",
    "Player_1": "Raya\r 0",
    "Player_11": "Watkins\r 2",
    "Player_10": "Wood\r 13",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Son\r 0",
    "Player_14": "Saka\r 9",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Collins\r 1",
    "Player_5": "Dalot\r 1",
    "Player_6": "Palmer\r 20",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Rogers\r 1",
    "Player_9": "Solanke\r 2",
    "Player_15": "Livramento\r 1"
  },
  {
    "manager_Name": "647( 662 ) TotalXfr : 8",
    "Teams": "Pain in Dias( Mikolaj Pietluch )",
    "SXL": "EN",
    "Latp": "95",
    "Player_1": "Sels\r 5",
    "Player_11": "Wood\r 13",
    "Player_10": "Wissa\r 10",
    "Player_12": "Begovic\r 0",
    "Player_13": "Strand Larsen\r 1",
    "Player_14": "Alexander-Arnold\r 1",
    "Player_7": "Saka\r 9",
    "Player_2": "Gvardiol\r 9",
    "Player_5": "McNeil\r 2",
    "Player_6": "Mbeumo\r 15",
    "Player_3": "Van den Berg\r 1",
    "Player_4": "Gabriel\r 1",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Palmer\r 20",
    "Player_15": "De Ligt\r 0"
  },
  {
    "manager_Name": "646( 704 ) TotalXfr : 7",
    "Teams": "FC Bo2( Ayden Doyle )",
    "SXL": "EN",
    "Latp": "82",
    "Player_1": "Sels\r 5",
    "Player_11": "Ndiaye\r 2",
    "Player_10": "Wood\r 13",
    "Player_12": "Flekken\r 1",
    "Player_13": "Keane\r 2",
    "Player_14": "Dibling\r 1",
    "Player_7": "Palmer\r 20",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Colwill\r 2",
    "Player_4": "Digne\r 7",
    "Player_8": "Rogers\r 1",
    "Player_9": "Haaland\r 6",
    "Player_15": "Davis\r 2"
  },
  {
    "manager_Name": "646( 728 ) TotalXfr : 8",
    "Teams": "Hugh Smefner( Luke Smethurst )",
    "SXL": "EN",
    "Latp": "87",
    "Player_1": "Flekken\r 1",
    "Player_11": "Wood\r 13",
    "Player_10": "Haaland\r 12",
    "Player_12": "Ward\r 0",
    "Player_13": "Mykolenko\r 2",
    "Player_14": "Faes\r 1",
    "Player_7": "Saka\r 9",
    "Player_2": "Lewis\r 6",
    "Player_5": "Palmer\r 10",
    "Player_6": "Georginio\r 5",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Smith Rowe\r 6",
    "Player_15": "Cannon\r 0"
  },
  {
    "manager_Name": "645( 812 ) TotalXfr : 9",
    "Teams": "Sch\u00E4r Wars: New Pope( Craig Dennis )",
    "SXL": "EN",
    "Latp": "68",
    "Player_1": "Flekken\r 1",
    "Player_11": "Watkins\r 2",
    "Player_10": "Wood\r 13",
    "Player_12": "S\u00E1nchez\r 1",
    "Player_13": "Rogers\r 1",
    "Player_14": "Mazraoui\r 2",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Foden\r 3",
    "Player_6": "Buonanotte\r 2",
    "Player_3": "Robinson\r 2",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "McNeil\r 2",
    "Player_9": "Haaland\r 18",
    "Player_15": "J.Timber\r 2"
  },
  {
    "manager_Name": "645( 823 ) TotalXfr : 12",
    "Teams": "Kinder Mbuemo( Rory O\u0027Neill )",
    "SXL": "IE",
    "Latp": "109",
    "Player_1": "Martinez\r 2",
    "Player_11": "N.Jackson\r 9",
    "Player_10": "Wood\r 13",
    "Player_12": "A.Becker\r 0",
    "Player_13": "Gabriel\r 1",
    "Player_14": "Cunha\r 9",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Keane\r 2",
    "Player_5": "Palmer\r 10",
    "Player_6": "Mbeumo\r 45",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Smith Rowe\r 6",
    "Player_9": "McNeil\r 2",
    "Player_15": "Bednarek\r 2"
  },
  {
    "manager_Name": "644( 828 ) TotalXfr : 5",
    "Teams": "Charvas( Shak Islam )",
    "SXL": "EN",
    "Latp": "73",
    "Player_1": "Raya\r 0",
    "Player_11": "Ra\u00FAl\r 2",
    "Player_10": "Haaland\r 12",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Smith Rowe\r 6",
    "Player_14": "Faes\r 1",
    "Player_7": "Rogers\r 1",
    "Player_2": "Robinson\r 2",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "Palmer\r 10",
    "Player_3": "Konsa\r 2",
    "Player_4": "Lewis\r 6",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Wood\r 13",
    "Player_15": "Harwood-Bellis\r 2"
  },
  {
    "manager_Name": "644( 845 ) TotalXfr : 7",
    "Teams": "360 no pope( Cruz Everett )",
    "SXL": "S1",
    "Latp": "86",
    "Player_1": "Martinez\r 2",
    "Player_11": "Cunha\r 9",
    "Player_10": "Wissa\r 10",
    "Player_12": "Areola\r 0",
    "Player_13": "Keane\r 2",
    "Player_14": "Dunk\r 0",
    "Player_7": "Mbeumo\r 30",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Rogers\r 1",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Robinson\r 2",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Palmer\r 10",
    "Player_9": "Watkins\r 2",
    "Player_15": "Semenyo\r 1"
  },
  {
    "manager_Name": "644( 845 ) TotalXfr : 7",
    "Teams": "konate kid( jack standeven )",
    "SXL": "EN",
    "Latp": "84",
    "Player_1": "Raya\r 0",
    "Player_11": "Watkins\r 2",
    "Player_10": "Mbeumo\r 30",
    "Player_12": "Turner\r 0",
    "Player_13": "Havertz\r 2",
    "Player_14": "Harwood-Bellis\r 2",
    "Player_7": "McNeil\r 2",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Lewis\r 6",
    "Player_6": "Palmer\r 10",
    "Player_3": "Digne\r 7",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Bowen\r 7",
    "Player_9": "M.Salah\r 10",
    "Player_15": "Jebbison\r 0"
  },
  {
    "manager_Name": "643( 915 ) TotalXfr : 6",
    "Teams": "Greggors FC( Harry Appleton-Gregg )",
    "SXL": "EN",
    "Latp": "57",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Vardy\r 8",
    "Player_10": "Haaland\r 12",
    "Player_12": "Ward\r 0",
    "Player_13": "Saka\r 9",
    "Player_14": "Konat\u00E9\r 1",
    "Player_7": "Palmer\r 10",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "Rogers\r 1",
    "Player_3": "Robinson\r 2",
    "Player_4": "Mykolenko\r 2",
    "Player_8": "McNeil\r 2",
    "Player_9": "Watkins\r 2",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "643( 915 ) TotalXfr : 6",
    "Teams": "Livin\u2019 Saliba Loca( Hasan Abid )",
    "SXL": "EN",
    "Latp": "64",
    "Player_1": "Henderson\r 8",
    "Player_11": "Watkins\r 2",
    "Player_10": "Haaland\r 12",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Dunk\r 0",
    "Player_14": "Welbeck\r 7",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Udogie\r 2",
    "Player_5": "M.Salah\r 10",
    "Player_6": "McNeil\r 2",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Konsa\r 2",
    "Player_8": "Madueke\r 1",
    "Player_9": "Rogers\r 1",
    "Player_15": "Gu\u00E9hi\r 6"
  },
  {
    "manager_Name": "643( 935 ) TotalXfr : 7",
    "Teams": "Under my Cucurella( Sershen Naidoo )",
    "SXL": "ZA",
    "Latp": "73",
    "Player_1": "Martinez\r 2",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Bentley\r 0",
    "Player_13": "Son\r 0",
    "Player_14": "Faes\r 1",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Lewis\r 6",
    "Player_5": "Martinelli\r 2",
    "Player_6": "Palmer\r 10",
    "Player_3": "Robertson\r 1",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Rogers\r 1",
    "Player_9": "Ndiaye\r 2",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "643( 935 ) TotalXfr : 7",
    "Teams": "HorrificallyGorgeous( David Conlon )",
    "SXL": "AU",
    "Latp": "92",
    "Player_1": "Martinez\r 2",
    "Player_11": "N.Jackson\r 9",
    "Player_10": "Wood\r 13",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Cucurella\r 1",
    "Player_14": "Havertz\r 2",
    "Player_7": "Mbeumo\r 30",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Bowen\r 7",
    "Player_6": "Saka\r 9",
    "Player_3": "Mykolenko\r 2",
    "Player_4": "Digne\r 7",
    "Player_8": "Palmer\r 10",
    "Player_9": "Garnacho\r 2",
    "Player_15": "Robertson\r 1"
  },
  {
    "manager_Name": "643( 959 ) TotalXfr : 8",
    "Teams": "moh17( Mohammed Lamih )",
    "SXL": "IN",
    "Latp": "68",
    "Player_1": "Sels\r 5",
    "Player_11": "Watkins\r 2",
    "Player_10": "Haaland\r 12",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Van den Berg\r 1",
    "Player_14": "Winks\r 4",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Smith Rowe\r 6",
    "Player_6": "Mbeumo\r 15",
    "Player_3": "Lewis\r 6",
    "Player_4": "Aina\r 2",
    "Player_8": "Rogers\r 1",
    "Player_9": "Vardy\r 8",
    "Player_15": "Harwood-Bellis\r 2"
  },
  {
    "manager_Name": "643( 959 ) TotalXfr : 8",
    "Teams": "Stuck in the Mudryk( zak Fraser-Grante )",
    "SXL": "EN",
    "Latp": "81",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Turner\r 0",
    "Player_13": "Harwood-Bellis\r 2",
    "Player_14": "Chiwome\r 0",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "McNeil\r 2",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Aina\r 2",
    "Player_8": "Palmer\r 10",
    "Player_9": "Rogers\r 1",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "643( 985 ) TotalXfr : 10",
    "Teams": "\u0645\u062D\u0645\u062F \u0639\u0644\u064A \u0643\u0644\u0627\u064A( Tark Kaili )",
    "SXL": "DZ",
    "Latp": "56",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Calvert-Lewin\r 2",
    "Player_10": "Haaland\r 6",
    "Player_12": "Areola\r 0",
    "Player_13": "Son\r 0",
    "Player_14": "Dunk\r 0",
    "Player_7": "Rashford\r 1",
    "Player_2": "Konsa\r 2",
    "Player_5": "Rogers\r 1",
    "Player_6": "Foden\r 3",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Colwill\r 2",
    "Player_8": "Mbeumo\r 30",
    "Player_9": "Welbeck\r 7",
    "Player_15": "Konat\u00E9\r 1"
  },
  {
    "manager_Name": "642( 1,032 ) TotalXfr : 7",
    "Teams": "Starboy( Badr Hassneiah )",
    "SXL": "NZ",
    "Latp": "86",
    "Player_1": "Sels\r 5",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wissa\r 10",
    "Player_12": "Turner\r 0",
    "Player_13": "Buonanotte\r 2",
    "Player_14": "A\u00EFt-Nouri\r 6",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Lewis\r 6",
    "Player_5": "McNeil\r 2",
    "Player_6": "Bowen\r 7",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Van den Berg\r 1",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Cunha\r 9",
    "Player_15": "Mykolenko\r 2"
  },
  {
    "manager_Name": "642( 1,032 ) TotalXfr : 7",
    "Teams": "ALQAHTANI( Muhannad Alqahtani )",
    "SXL": "SA",
    "Latp": "82",
    "Player_1": "Raya\r 0",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Turner\r 0",
    "Player_13": "Adama\r 3",
    "Player_14": "Konat\u00E9\r 1",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Lewis\r 6",
    "Player_5": "Rogers\r 1",
    "Player_6": "Palmer\r 10",
    "Player_3": "Van de Ven\r 1",
    "Player_4": "Robinson\r 2",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Welbeck\r 7",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "642( 1,032 ) TotalXfr : 7",
    "Teams": "Pizdino selo( Marino Dre\u017Enjak )",
    "SXL": "HR",
    "Latp": "74",
    "Player_1": "Raya\r 0",
    "Player_11": "Watkins\r 2",
    "Player_10": "Solanke\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Smith Rowe\r 6",
    "Player_14": "Burn\r 1",
    "Player_7": "Palmer\r 10",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "McNeil\r 2",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Robinson\r 2",
    "Player_8": "Mbeumo\r 30",
    "Player_9": "Wood\r 13",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "641( 1,105 ) TotalXfr : 4",
    "Teams": "Banda Avdia( Daniel Avdia )",
    "SXL": "EN",
    "Latp": "73",
    "Player_1": "Raya\r 0",
    "Player_11": "Delap\r 5",
    "Player_10": "Wood\r 13",
    "Player_12": "Turner\r 0",
    "Player_13": "Dalot\r 1",
    "Player_14": "Andersen\r 0",
    "Player_7": "Palmer\r 20",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Eze\r 6",
    "Player_6": "Saka\r 9",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Pinnock\r 1",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Welbeck\r 7",
    "Player_15": "McGinn\r 2"
  },
  {
    "manager_Name": "641( 1,138 ) TotalXfr : 7",
    "Teams": "Happy World of Aribo( Freddie Harris )",
    "SXL": "EN",
    "Latp": "58",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Solanke\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Faes\r 1",
    "Player_14": "Mosquera\r 0",
    "Player_7": "McNeil\r 2",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Foden\r 3",
    "Player_6": "Rogers\r 1",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Konsa\r 2",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Palmer\r 10",
    "Player_15": "Ui-jo\r 0"
  },
  {
    "manager_Name": "640( 1,241 ) TotalXfr : 6",
    "Teams": "Christie FC( Jaryd Christie )",
    "SXL": "BB",
    "Latp": "82",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Smith Rowe\r 6",
    "Player_14": "Konsa\r 2",
    "Player_7": "Palmer\r 10",
    "Player_2": "Robinson\r 2",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "Buonanotte\r 2",
    "Player_3": "Lewis\r 6",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Calvert-Lewin\r 2",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "640( 1,241 ) TotalXfr : 6",
    "Teams": "Tiki Taka FC( emmanuel maupa )",
    "SXL": "ZW",
    "Latp": "67",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Welbeck\r 7",
    "Player_12": "Turner\r 0",
    "Player_13": "Konat\u00E9\r 1",
    "Player_14": "Burn\r 1",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Keane\r 2",
    "Player_5": "Smith Rowe\r 6",
    "Player_6": "Semenyo\r 1",
    "Player_3": "Mazraoui\r 2",
    "Player_4": "Faes\r 1",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Palmer\r 10",
    "Player_15": "Lankshear\r 0"
  },
  {
    "manager_Name": "640( 1,259 ) TotalXfr : 7",
    "Teams": "BackDoorSlotsIX( Daniel Latham )",
    "SXL": "WA",
    "Latp": "75",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Vardy\r 8",
    "Player_10": "Palmer\r 10",
    "Player_12": "Ramsdale\r 4",
    "Player_13": "Havertz\r 2",
    "Player_14": "Son\r 0",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Keane\r 2",
    "Player_5": "Alexander-Arnold\r 1",
    "Player_6": "Van de Ven\r 1",
    "Player_3": "Lewis\r 6",
    "Player_4": "Faes\r 1",
    "Player_8": "Mbeumo\r 30",
    "Player_9": "Luis D\u00EDaz\r 5",
    "Player_15": "Welbeck\r 7"
  }
];