var s = [
  {
    "manager_Name": "666( 80 ) TotalXfr : 6",
    "Teams": "Joelinton Enjoyer( James White )",
    "SXL": "NZ",
    "Latp": "69",
    "Player_1": "Martinez\r 2",
    "Player_11": "Watkins\r 2",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Dennis\r 0",
    "Player_13": "Dunk\r 0",
    "Player_14": "Dibling\r 1",
    "Player_7": "McNeil\r 2",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Collins\r 1",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "B.Fernandes\r 2",
    "Player_9": "Haaland\r 18",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "660( 159 ) TotalXfr : 6",
    "Teams": "Charlie\u2019s team( Charlie Shepherd )",
    "SXL": "EN",
    "Latp": "72",
    "Player_1": "Raya\r 0",
    "Player_11": "Cunha\r 9",
    "Player_10": "Delap\r 5",
    "Player_12": "Dennis\r 0",
    "Player_13": "Gabriel\r 1",
    "Player_14": "Son\r 0",
    "Player_7": "Palmer\r 10",
    "Player_2": "Konsa\r 2",
    "Player_5": "M.Salah\r 10",
    "Player_6": "Rogers\r 1",
    "Player_3": "Robinson\r 2",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "Mbeumo\r 30",
    "Player_9": "Watkins\r 2",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "658( 213 ) TotalXfr : 10",
    "Teams": "Levenshulme Utd( Max Littleproud )",
    "SXL": "EN",
    "Latp": "70",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Watkins\r 2",
    "Player_12": "Matthews\r 0",
    "Player_13": "Son\r 0",
    "Player_14": "Gabriel\r 1",
    "Player_7": "McNeil\r 2",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "Palmer\r 10",
    "Player_6": "Rogers\r 1",
    "Player_3": "Young\r 6",
    "Player_4": "Aina\r 2",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Wood\r 13",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "654( 298 ) TotalXfr : 7",
    "Teams": "Peaky Grinders II( Mongezi Mweli )",
    "SXL": "ZA",
    "Latp": "72",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Watkins\r 4",
    "Player_10": "N.Jackson\r 9",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Alexander-Arnold\r 1",
    "Player_14": "A\u00EFt-Nouri\r 6",
    "Player_7": "Palmer\r 10",
    "Player_2": "Digne\r 7",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "McNeil\r 2",
    "Player_3": "Lewis\r 6",
    "Player_4": "Faes\r 1",
    "Player_8": "Bowen\r 7",
    "Player_9": "Wissa\r 10",
    "Player_15": "Son\r 0"
  },
  {
    "manager_Name": "652( 390 ) TotalXfr : 8",
    "Teams": "SC Villa Jogoo( Godfrey Lusiba )",
    "SXL": "UG",
    "Latp": "85",
    "Player_1": "Pickford\r 2",
    "Player_11": "Havertz\r 2",
    "Player_10": "Evanilson\r 8",
    "Player_12": "Turner\r 0",
    "Player_13": "Diogo J.\r 0",
    "Player_14": "Robinson\r 2",
    "Player_7": "Smith Rowe\r 6",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "Saka\r 9",
    "Player_6": "Mbeumo\r 30",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Dalot\r 1",
    "Player_8": "M.Salah\r 10",
    "Player_9": "N.Jackson\r 9",
    "Player_15": "Davis\r 2"
  },
  {
    "manager_Name": "651( 449 ) TotalXfr : 9",
    "Teams": "druMMer bOYs unITed( Kwaku Ankama-Asamoah )",
    "SXL": "US",
    "Latp": "68",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Ra\u00FAl\r 2",
    "Player_10": "Haaland\r 12",
    "Player_12": "Benda\r 0",
    "Player_13": "Winks\r 4",
    "Player_14": "Nedeljkovic\r 0",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Mykolenko\r 2",
    "Player_5": "Palmer\r 10",
    "Player_6": "Rogers\r 1",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Delap\r 5",
    "Player_15": "Harwood-Bellis\r 2"
  },
  {
    "manager_Name": "650( 467 ) TotalXfr : 7",
    "Teams": "Ian\u0027s Idiots( ian scott )",
    "SXL": "S1",
    "Latp": "72",
    "Player_1": "Flekken\r 1",
    "Player_11": "Watkins\r 2",
    "Player_10": "N.Jackson\r 9",
    "Player_12": "Ramsdale\r 4",
    "Player_13": "Wood\r 13",
    "Player_14": "Robinson\r 2",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Rogers\r 1",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Van de Ven\r 1",
    "Player_8": "Palmer\r 20",
    "Player_9": "Bernardo\r 3",
    "Player_15": "Harwood-Bellis\r 2"
  },
  {
    "manager_Name": "649( 520 ) TotalXfr : 7",
    "Teams": "Trust the Process ;)( Robb Lacey )",
    "SXL": "EN",
    "Latp": "62",
    "Player_1": "Pickford\r 2",
    "Player_11": "Watkins\r 4",
    "Player_10": "Ndiaye\r 2",
    "Player_12": "Johnstone\r 0",
    "Player_13": "Maddison\r 2",
    "Player_14": "Mykolenko\r 2",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Van den Berg\r 1",
    "Player_5": "Bowen\r 7",
    "Player_6": "Mbeumo\r 15",
    "Player_3": "Pinnock\r 1",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Saka\r 9",
    "Player_9": "Solanke\r 2",
    "Player_15": "A\u00EFt-Nouri\r 6"
  },
  {
    "manager_Name": "649( 543 ) TotalXfr : 8",
    "Teams": "FPL_Sarki( Yusuf Muhammad Bello )",
    "SXL": "NG",
    "Latp": "90",
    "Player_1": "Flekken\r 1",
    "Player_11": "Watkins\r 2",
    "Player_10": "Wissa\r 10",
    "Player_12": "Verbruggen\r 2",
    "Player_13": "Ra\u00FAl\r 2",
    "Player_14": "Calafiori\r 0",
    "Player_7": "Saka\r 9",
    "Player_2": "Veltman\r 1",
    "Player_5": "Mbeumo\r 30",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Digne\r 7",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Palmer\r 10",
    "Player_9": "Rogers\r 1",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "646( 704 ) TotalXfr : 7",
    "Teams": "Arne Slotmachine( Wayne Jenkinson )",
    "SXL": "AU",
    "Latp": "77",
    "Player_1": "Flekken\r 1",
    "Player_11": "Havertz\r 2",
    "Player_10": "Wood\r 13",
    "Player_12": "Henderson\r 8",
    "Player_13": "Jo\u00E3o Pedro\r 0",
    "Player_14": "Robinson\r 2",
    "Player_7": "Foden\r 3",
    "Player_2": "Van den Berg\r 1",
    "Player_5": "McNeil\r 2",
    "Player_6": "Mbeumo\r 15",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Palmer\r 20",
    "Player_15": "Nedeljkovic\r 0"
  },
  {
    "manager_Name": "644( 878 ) TotalXfr : 8",
    "Teams": "Blue Order Remix( Matthew Davies )",
    "SXL": "EN",
    "Latp": "85",
    "Player_1": "Sels\r 5",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Pau\r 2",
    "Player_14": "Jo\u00E3o Pedro\r 0",
    "Player_7": "Rogers\r 1",
    "Player_2": "Keane\r 2",
    "Player_5": "Palmer\r 10",
    "Player_6": "Mbeumo\r 15",
    "Player_3": "A\u00EFt-Nouri\r 6",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "M.Salah\r 10",
    "Player_9": "McNeil\r 2",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "643( 935 ) TotalXfr : 7",
    "Teams": "werbnahpets( Stephan Brew )",
    "SXL": "GH",
    "Latp": "69",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Duran\r 1",
    "Player_12": "Pickford\r 2",
    "Player_13": "Robinson\r 2",
    "Player_14": "Winks\r 4",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Lewis\r 6",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "Rogers\r 1",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Konsa\r 2",
    "Player_8": "Palmer\r 10",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "643( 959 ) TotalXfr : 8",
    "Teams": "moh17( Mohammed Lamih )",
    "SXL": "IN",
    "Latp": "68",
    "Player_1": "Sels\r 5",
    "Player_11": "Watkins\r 2",
    "Player_10": "Haaland\r 12",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Van den Berg\r 1",
    "Player_14": "Winks\r 4",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Smith Rowe\r 6",
    "Player_6": "Mbeumo\r 15",
    "Player_3": "Lewis\r 6",
    "Player_4": "Aina\r 2",
    "Player_8": "Rogers\r 1",
    "Player_9": "Vardy\r 8",
    "Player_15": "Harwood-Bellis\r 2"
  },
  {
    "manager_Name": "643( 959 ) TotalXfr : 8",
    "Teams": "Child \u26BDF Prophecy( Roshane Simpson )",
    "SXL": "JM",
    "Latp": "81",
    "Player_1": "Sels\r 5",
    "Player_11": "N.Jackson\r 9",
    "Player_10": "Haaland\r 18",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Faes\r 1",
    "Player_14": "Winks\r 4",
    "Player_7": "Rogers\r 1",
    "Player_2": "Aina\r 2",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Virgil\r 7",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Foden\r 3",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Harwood-Bellis\r 2"
  },
  {
    "manager_Name": "642( 1,032 ) TotalXfr : 7",
    "Teams": "Invisibles\u26BD\uFE0F( Ikenna Godslove )",
    "SXL": "NG",
    "Latp": "57",
    "Player_1": "Martinez\r 2",
    "Player_11": "Haaland\r 6",
    "Player_10": "Watkins\r 2",
    "Player_12": "Matthews\r 0",
    "Player_13": "Mazraoui\r 2",
    "Player_14": "Andersen\r 0",
    "Player_7": "Trossard\r 2",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "Rogers\r 1",
    "Player_3": "Lewis\r 6",
    "Player_4": "J.Timber\r 2",
    "Player_8": "Saka\r 18",
    "Player_9": "McNeil\r 2",
    "Player_15": "Wheatley\r 0"
  },
  {
    "manager_Name": "641( 1,116 ) TotalXfr : 6",
    "Teams": "soncity( Kai Dallan-Jones )",
    "SXL": "AU",
    "Latp": "70",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Cunha\r 9",
    "Player_12": "Turner\r 0",
    "Player_13": "Yarmoliuk\r 0",
    "Player_14": "Konsa\r 2",
    "Player_7": "Foden\r 3",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "Smith Rowe\r 6",
    "Player_3": "Dalot\r 1",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Palmer\r 10",
    "Player_9": "Solanke\r 2",
    "Player_15": "Davis\r 2"
  },
  {
    "manager_Name": "641( 1,138 ) TotalXfr : 7",
    "Teams": "Inter-bred( ashley whomes )",
    "SXL": "WA",
    "Latp": "73",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Fabianski\r 3",
    "Player_13": "McNeil\r 2",
    "Player_14": "Keane\r 2",
    "Player_7": "Garnacho\r 2",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Johnson\r 1",
    "Player_6": "Palmer\r 10",
    "Player_3": "Lewis\r 6",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Watkins\r 2",
    "Player_15": "Harwood-Bellis\r 2"
  },
  {
    "manager_Name": "641( 1,138 ) TotalXfr : 7",
    "Teams": "Missing Thursdays( Alan Edwards )",
    "SXL": "EN",
    "Latp": "75",
    "Player_1": "Henderson\r 8",
    "Player_11": "Haaland\r 18",
    "Player_10": "Ndiaye\r 2",
    "Player_12": "Raya\r 0",
    "Player_13": "Van Hecke\r 1",
    "Player_14": "Faes\r 1",
    "Player_7": "Palmer\r 10",
    "Player_2": "Lewis\r 6",
    "Player_5": "Rogers\r 1",
    "Player_6": "Foden\r 3",
    "Player_3": "Digne\r 7",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Smith Rowe\r 6",
    "Player_9": "Wood\r 13",
    "Player_15": "Winks\r 4"
  },
  {
    "manager_Name": "641( 1,175 ) TotalXfr : 8",
    "Teams": "Robsdale XI( Robert Burt )",
    "SXL": "EN",
    "Latp": "93",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Wood\r 13",
    "Player_10": "Watkins\r 2",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Saka\r 9",
    "Player_14": "De Ligt\r 0",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Bowen\r 7",
    "Player_6": "Mbeumo\r 45",
    "Player_3": "Veltman\r 1",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "McNeil\r 2",
    "Player_9": "N.Jackson\r 9",
    "Player_15": "Tuanzebe\r 0"
  },
  {
    "manager_Name": "640( 1,226 ) TotalXfr : 4",
    "Teams": "Da Flame \uFFFD( Taku Muvingi )",
    "SXL": "ZW",
    "Latp": "65",
    "Player_1": "Raya\r 0",
    "Player_11": "Haaland\r 12",
    "Player_10": "Watkins\r 2",
    "Player_12": "S\u00E1nchez\r 1",
    "Player_13": "Bissouma\r 2",
    "Player_14": "Dunk\r 0",
    "Player_7": "Luis D\u00EDaz\r 5",
    "Player_2": "Akanji\r 6",
    "Player_5": "Saka\r 9",
    "Player_6": "Smith Rowe\r 6",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Robinson\r 2",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Welbeck\r 7",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "640( 1,259 ) TotalXfr : 7",
    "Teams": "Cyprian_Utd( Cyprian Peter )",
    "SXL": "NG",
    "Latp": "84",
    "Player_1": "Onana\r 1",
    "Player_11": "Welbeck\r 7",
    "Player_10": "Watkins\r 2",
    "Player_12": "Raya\r 0",
    "Player_13": "Faes\r 1",
    "Player_14": "Amad\r 1",
    "Player_7": "Luis D\u00EDaz\r 5",
    "Player_2": "Gvardiol\r 9",
    "Player_5": "M.Salah\r 20",
    "Player_6": "Saka\r 9",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Mazraoui\r 2",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Wood\r 13",
    "Player_15": "Aina\r 2"
  },
  {
    "manager_Name": "640( 1,309 ) TotalXfr : 8",
    "Teams": "Nats County( Manuel Pop )",
    "SXL": "RO",
    "Latp": "85",
    "Player_1": "Sels\r 5",
    "Player_11": "N.Jackson\r 9",
    "Player_10": "Wood\r 13",
    "Player_12": "Henderson\r 8",
    "Player_13": "Ndiaye\r 2",
    "Player_14": "Keane\r 2",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Mbeumo\r 30",
    "Player_6": "Palmer\r 10",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Bernardo\r 3",
    "Player_9": "Rogers\r 1",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "639( 1,360 ) TotalXfr : 4",
    "Teams": "Stop War In Sudan( Mustafa Diouf \uD83C\uDDF8\uD83C\uDDE9\uD83D\uDC94 )",
    "SXL": "SD",
    "Latp": "75",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Aina\r 2",
    "Player_14": "Konat\u00E9\r 1",
    "Player_7": "McNeil\r 2",
    "Player_2": "Cash\r 1",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Van de Ven\r 1",
    "Player_4": "Van den Berg\r 1",
    "Player_8": "Palmer\r 10",
    "Player_9": "Cunha\r 9",
    "Player_15": "M.Fran\u00E7a\r 0"
  },
  {
    "manager_Name": "639( 1,463 ) TotalXfr : 8",
    "Teams": "Boom Xhakalala( Karol Pinczynski )",
    "SXL": "EN",
    "Latp": "77",
    "Player_1": "Henderson\r 8",
    "Player_11": "Wissa\r 10",
    "Player_10": "Haaland\r 12",
    "Player_12": "Turner\r 0",
    "Player_13": "Smith Rowe\r 6",
    "Player_14": "Faes\r 1",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Saka\r 9",
    "Player_6": "Rogers\r 1",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "Keane\r 2",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Vardy\r 8",
    "Player_15": "Harwood-Bellis\r 2"
  },
  {
    "manager_Name": "638( 1,560 ) TotalXfr : 7",
    "Teams": "Womp, womp.( Stephen Blakemore )",
    "SXL": "EN",
    "Latp": "72",
    "Player_1": "Pickford\r 2",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wissa\r 10",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Dunk\r 0",
    "Player_14": "Sancho\r 0",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Mykolenko\r 2",
    "Player_5": "Davis\r 2",
    "Player_6": "Palmer\r 10",
    "Player_3": "Robinson\r 2",
    "Player_4": "Lewis\r 6",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Rogers\r 1",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "637( 1,674 ) TotalXfr : 5",
    "Teams": "Ramy - Dash( Ramy Egypt )",
    "SXL": "EG",
    "Latp": "73",
    "Player_1": "Ederson M.\r 6",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Wissa\r 10",
    "Player_14": "Robinson\r 2",
    "Player_7": "Palmer\r 10",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Johnson\r 1",
    "Player_6": "Mbeumo\r 15",
    "Player_3": "Aina\r 2",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Rogers\r 1",
    "Player_9": "Garnacho\r 2",
    "Player_15": "Konsa\r 2"
  },
  {
    "manager_Name": "636( 1,880 ) TotalXfr : 6",
    "Teams": "Sofiane FC( sofiane djebbour )",
    "SXL": "DZ",
    "Latp": "74",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "N.Jackson\r 9",
    "Player_10": "Ndiaye\r 2",
    "Player_12": "Steele\r 0",
    "Player_13": "Dunk\r 0",
    "Player_14": "Saliba\r 0",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Aina\r 2",
    "Player_5": "Saka\r 9",
    "Player_6": "M.Salah\r 20",
    "Player_3": "Konsa\r 2",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "McNeil\r 2",
    "Player_9": "Palmer\r 10",
    "Player_15": "Vardy\r 8"
  },
  {
    "manager_Name": "636( 1,929 ) TotalXfr : 7",
    "Teams": "Siones side quest( Jai Reedy )",
    "SXL": "NZ",
    "Latp": "74",
    "Player_1": "Flekken\r 1",
    "Player_11": "Watkins\r 2",
    "Player_10": "Wood\r 13",
    "Player_12": "Whiteman\r 0",
    "Player_13": "Son\r 0",
    "Player_14": "Winks\r 4",
    "Player_7": "Palmer\r 10",
    "Player_2": "Konsa\r 2",
    "Player_5": "Robinson\r 2",
    "Player_6": "Mbeumo\r 15",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Lewis\r 6",
    "Player_8": "McNeil\r 2",
    "Player_9": "Haaland\r 12",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "636( 1,929 ) TotalXfr : 7",
    "Teams": "Mickey( Vladimir Petrov )",
    "SXL": "MK",
    "Latp": "55",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Watkins\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Winks\r 4",
    "Player_14": "Konat\u00E9\r 1",
    "Player_7": "Rogers\r 1",
    "Player_2": "Faes\r 1",
    "Player_5": "Palmer\r 10",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Aina\r 2",
    "Player_4": "Lewis\r 6",
    "Player_8": "Bernardo\r 3",
    "Player_9": "Welbeck\r 7",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "636( 1,929 ) TotalXfr : 7",
    "Teams": "Zero Darwin Chair-ty( Javier Cabrera )",
    "SXL": "US",
    "Latp": "71",
    "Player_1": "Flekken\r 1",
    "Player_11": "N.Jackson\r 9",
    "Player_10": "Haaland\r 12",
    "Player_12": "Iversen\r 0",
    "Player_13": "Johnson\r 1",
    "Player_14": "Tete\r 2",
    "Player_7": "Rogers\r 1",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "G\u00FCndogan\r 1",
    "Player_3": "Pinnock\r 1",
    "Player_4": "Lewis\r 6",
    "Player_8": "Palmer\r 10",
    "Player_9": "Wood\r 13",
    "Player_15": "A\u00EFt-Nouri\r 6"
  },
  {
    "manager_Name": "636( 1,999 ) TotalXfr : 8",
    "Teams": "MICKY( Michael Adeolu )",
    "SXL": "NG",
    "Latp": "81",
    "Player_1": "Raya\r 0",
    "Player_11": "Vardy\r 8",
    "Player_10": "Wood\r 13",
    "Player_12": "Turner\r 0",
    "Player_13": "Semenyo\r 1",
    "Player_14": "Davis\r 2",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "M.Salah\r 20",
    "Player_6": "Palmer\r 10",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Rogers\r 1",
    "Player_9": "Watkins\r 2",
    "Player_15": "Burn\r 1"
  },
  {
    "manager_Name": "635( 2,210 ) TotalXfr : 8",
    "Teams": "JAKE 11( jake okai )",
    "SXL": "GH",
    "Latp": "71",
    "Player_1": "Flekken\r 1",
    "Player_11": "Welbeck\r 7",
    "Player_10": "N.Jackson\r 9",
    "Player_12": "Ward\r 0",
    "Player_13": "M.Fran\u00E7a\r 0",
    "Player_14": "Greaves\r 0",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Konat\u00E9\r 1",
    "Player_5": "McNeil\r 2",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Keane\r 2",
    "Player_4": "Colwill\r 2",
    "Player_8": "Palmer\r 10",
    "Player_9": "Haaland\r 12",
    "Player_15": "Mazraoui\r 2"
  },
  {
    "manager_Name": "635( 2,210 ) TotalXfr : 8",
    "Teams": "Barca( Yassine Ouali )",
    "SXL": "TN",
    "Latp": "80",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "N.Jackson\r 9",
    "Player_10": "Watkins\r 2",
    "Player_12": "Ramsdale\r 4",
    "Player_13": "Konsa\r 2",
    "Player_14": "Johnson\r 0",
    "Player_7": "McNeil\r 2",
    "Player_2": "Robinson\r 2",
    "Player_5": "M.Salah\r 10",
    "Player_6": "Luis D\u00EDaz\r 5",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Digne\r 7",
    "Player_8": "Palmer\r 10",
    "Player_9": "Mbeumo\r 30",
    "Player_15": "Lankshear\r 0"
  },
  {
    "manager_Name": "635( 2,294 ) TotalXfr : 10",
    "Teams": "FC Spartak Liverpool( Adam \u00C1gh )",
    "SXL": "SK",
    "Latp": "96",
    "Player_1": "Henderson\r 8",
    "Player_11": "Watkins\r 2",
    "Player_10": "Wood\r 13",
    "Player_12": "Hermansen\r 1",
    "Player_13": "McNeil\r 2",
    "Player_14": "Virgil\r 7",
    "Player_7": "Mbeumo\r 30",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Smith Rowe\r 6",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Lewis\r 6",
    "Player_4": "Konsa\r 2",
    "Player_8": "Palmer\r 10",
    "Player_9": "Welbeck\r 7",
    "Player_15": "Burn\r 1"
  },
  {
    "manager_Name": "634( 2,336 ) TotalXfr : 6",
    "Teams": "Gtk fc( Pritam Shrestha )",
    "SXL": "IN",
    "Latp": "67",
    "Player_1": "Leno\r 3",
    "Player_11": "Ndiaye\r 2",
    "Player_10": "Solanke\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Harwood-Bellis\r 2",
    "Player_14": "Faes\r 1",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "Rogers\r 1",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Robinson\r 2",
    "Player_8": "Palmer\r 20",
    "Player_9": "Watkins\r 2",
    "Player_15": "Luis D\u00EDaz\r 5"
  },
  {
    "manager_Name": "634( 2,388 ) TotalXfr : 7",
    "Teams": "T.K TEAM( thankgod Emmanuel )",
    "SXL": "NG",
    "Latp": "65",
    "Player_1": "Sels\r 5",
    "Player_11": "Watkins\r 2",
    "Player_10": "Solanke\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Buonanotte\r 2",
    "Player_14": "Faes\r 1",
    "Player_7": "Smith Rowe\r 6",
    "Player_2": "Van de Ven\r 1",
    "Player_5": "Palmer\r 10",
    "Player_6": "Mbeumo\r 15",
    "Player_3": "Tarkowski\r 1",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "McNeil\r 2",
    "Player_9": "Haaland\r 12",
    "Player_15": "Bednarek\r 2"
  },
  {
    "manager_Name": "634( 2,388 ) TotalXfr : 7",
    "Teams": "El Bicho9( Big Manuel )",
    "SXL": "NG",
    "Latp": "68",
    "Player_1": "Raya\r 0",
    "Player_11": "Haaland\r 12",
    "Player_10": "Welbeck\r 7",
    "Player_12": "Turner\r 0",
    "Player_13": "Amad\r 1",
    "Player_14": "Saka\r 9",
    "Player_7": "Palmer\r 10",
    "Player_2": "Robinson\r 2",
    "Player_5": "Murillo\r 2",
    "Player_6": "Rogers\r 1",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Faes\r 1",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "N.Jackson\r 9",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "634( 2,388 ) TotalXfr : 7",
    "Teams": "Szoboszlai\u2019s Zobo( Ayo Alesh )",
    "SXL": "NG",
    "Latp": "65",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Haaland\r 18",
    "Player_10": "Wissa\r 10",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Harwood-Bellis\r 2",
    "Player_14": "Nedeljkovic\r 0",
    "Player_7": "McNeil\r 2",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "Foden\r 3",
    "Player_6": "Rogers\r 1",
    "Player_3": "Aina\r 2",
    "Player_4": "Davis\r 2",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Palmer\r 10",
    "Player_15": "Wheatley\r 0"
  },
  {
    "manager_Name": "634( 2,388 ) TotalXfr : 7",
    "Teams": "Here we go again( Sam Williams )",
    "SXL": "EN",
    "Latp": "66",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Ra\u00FAl\r 2",
    "Player_10": "Haaland\r 12",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Konat\u00E9\r 1",
    "Player_14": "Bednarek\r 2",
    "Player_7": "M.Salah\r 10",
    "Player_2": "Keane\r 2",
    "Player_5": "Palmer\r 10",
    "Player_6": "McNeil\r 2",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Rogers\r 1",
    "Player_15": "Wheatley\r 0"
  },
  {
    "manager_Name": "634( 2,388 ) TotalXfr : 7",
    "Teams": "The Big Breakfast( Blake G )",
    "SXL": "AU",
    "Latp": "84",
    "Player_1": "Raya\r 0",
    "Player_11": "Haaland\r 12",
    "Player_10": "Welbeck\r 7",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Smith Rowe\r 6",
    "Player_14": "Stephens\r 2",
    "Player_7": "Rogers\r 1",
    "Player_2": "Van de Ven\r 1",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "Palmer\r 10",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Lewis\r 6",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Wood\r 13",
    "Player_15": "Vestergaard\r 0"
  },
  {
    "manager_Name": "634( 2,388 ) TotalXfr : 7",
    "Teams": "NR29( Nic Onions )",
    "SXL": "EN",
    "Latp": "76",
    "Player_1": "Henderson\r 8",
    "Player_11": "Calvert-Lewin\r 2",
    "Player_10": "Watkins\r 2",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Strand Larsen\r 1",
    "Player_14": "Alexander-Arnold\r 1",
    "Player_7": "Mbeumo\r 30",
    "Player_2": "Digne\r 7",
    "Player_5": "Rogers\r 1",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Robinson\r 2",
    "Player_4": "Gabriel\r 1",
    "Player_8": "Palmer\r 10",
    "Player_9": "Foden\r 3",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "634( 2,457 ) TotalXfr : 8",
    "Teams": "DE BRUYNE IDENTITY( Ray Sawyer )",
    "SXL": "EN",
    "Latp": "72",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Watkins\r 2",
    "Player_10": "Haaland\r 12",
    "Player_12": "Pickford\r 2",
    "Player_13": "Georginio\r 5",
    "Player_14": "Keane\r 2",
    "Player_7": "Foden\r 3",
    "Player_2": "Pinnock\r 1",
    "Player_5": "Palmer\r 10",
    "Player_6": "Rogers\r 1",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Digne\r 7",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Wissa\r 10",
    "Player_15": "Coleman\r 0"
  },
  {
    "manager_Name": "634( 2,457 ) TotalXfr : 8",
    "Teams": "NZS United( Maksim Tsurkov )",
    "SXL": "AZ",
    "Latp": "64",
    "Player_1": "Pickford\r 2",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Raya\r 0",
    "Player_13": "Hudson-Odoi\r 2",
    "Player_14": "Hall\r 4",
    "Player_7": "Palmer\r 10",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Smith Rowe\r 6",
    "Player_6": "McNeil\r 2",
    "Player_3": "Mazraoui\r 2",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Luis D\u00EDaz\r 5",
    "Player_9": "N.Jackson\r 9",
    "Player_15": "Davis\r 2"
  },
  {
    "manager_Name": "634( 2,457 ) TotalXfr : 8",
    "Teams": "Merchants of Chaos( Zephyr Brown )",
    "SXL": "NZ",
    "Latp": "82",
    "Player_1": "Sels\r 5",
    "Player_11": "Wood\r 13",
    "Player_10": "Solanke\r 2",
    "Player_12": "Muric\r 2",
    "Player_13": "Son\r 0",
    "Player_14": "Gabriel\r 1",
    "Player_7": "McNeil\r 2",
    "Player_2": "Faes\r 1",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "Palmer\r 20",
    "Player_3": "A\u00EFt-Nouri\r 6",
    "Player_4": "Alexander-Arnold\r 1",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Welbeck\r 7",
    "Player_15": "Aina\r 2"
  },
  {
    "manager_Name": "634( 2,550 ) TotalXfr : 10",
    "Teams": "adham el moftry 1( Adham Karama )",
    "SXL": "EG",
    "Latp": "76",
    "Player_1": "Sels\r 5",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Faes\r 1",
    "Player_14": "J.Timber\r 2",
    "Player_7": "McNeil\r 2",
    "Player_2": "Lewis\r 6",
    "Player_5": "M.Salah\r 10",
    "Player_6": "Rogers\r 1",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "Van den Berg\r 1",
    "Player_8": "Palmer\r 10",
    "Player_9": "Mbeumo\r 15",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "633( 2,651 ) TotalXfr : 7",
    "Teams": "Sb3 team( Ahmed Abu lafi )",
    "SXL": "AE",
    "Latp": "62",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Haaland\r 12",
    "Player_10": "Antonio\r 2",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Carvalho\r 1",
    "Player_14": "Keane\r 2",
    "Player_7": "Palmer\r 10",
    "Player_2": "Digne\r 7",
    "Player_5": "Foden\r 3",
    "Player_6": "M.Salah\r 10",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "Lewis\r 6",
    "Player_8": "Garnacho\r 2",
    "Player_9": "Welbeck\r 7",
    "Player_15": "Tuanzebe\r 0"
  },
  {
    "manager_Name": "633( 2,737 ) TotalXfr : 8",
    "Teams": "D.O.T.S( Adenusi David )",
    "SXL": "NG",
    "Latp": "77",
    "Player_1": "Flekken\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Wood\r 13",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Havertz\r 2",
    "Player_14": "Faes\r 1",
    "Player_7": "Smith Rowe\r 6",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Saka\r 9",
    "Player_6": "Palmer\r 10",
    "Player_3": "Robinson\r 2",
    "Player_4": "Lewis\r 6",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Rogers\r 1",
    "Player_15": "Harwood-Bellis\r 2"
  },
  {
    "manager_Name": "633( 2,798 ) TotalXfr : 9",
    "Teams": "RedsSs( Moe Sweid )",
    "SXL": "BR",
    "Latp": "77",
    "Player_1": "Henderson\r 8",
    "Player_11": "Wood\r 13",
    "Player_10": "Haaland\r 12",
    "Player_12": "Fabianski\r 3",
    "Player_13": "Son\r 0",
    "Player_14": "Konsa\r 2",
    "Player_7": "Rogers\r 1",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Luis D\u00EDaz\r 5",
    "Player_6": "Palmer\r 10",
    "Player_3": "Keane\r 2",
    "Player_4": "Aina\r 2",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Welbeck\r 7",
    "Player_15": "Bednarek\r 2"
  },
  {
    "manager_Name": "633( 2,834 ) TotalXfr : 11",
    "Teams": "Anfield Athletic( Glen Bonnie )",
    "SXL": "IE",
    "Latp": "67",
    "Player_1": "Martinez\r 2",
    "Player_11": "Solanke\r 2",
    "Player_10": "Ndiaye\r 2",
    "Player_12": "J.Virginia\r 0",
    "Player_13": "Robinson\r 2",
    "Player_14": "Greaves\r 0",
    "Player_7": "Smith Rowe\r 6",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "Bowen\r 7",
    "Player_3": "Van den Berg\r 1",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "M.Salah\r 20",
    "Player_9": "Palmer\r 10",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "632( 2,854 ) TotalXfr : 5",
    "Teams": "Ahmed7( Ahmed Tarek )",
    "SXL": "EG",
    "Latp": "81",
    "Player_1": "Sels\r 5",
    "Player_11": "Wood\r 13",
    "Player_10": "Haaland\r 12",
    "Player_12": "S\u00E1nchez\r 1",
    "Player_13": "Welbeck\r 7",
    "Player_14": "Faes\r 1",
    "Player_7": "Palmer\r 10",
    "Player_2": "Konsa\r 2",
    "Player_5": "Mbeumo\r 15",
    "Player_6": "Rogers\r 1",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Keane\r 2",
    "Player_8": "McNeil\r 2",
    "Player_9": "M.Salah\r 10",
    "Player_15": "Konat\u00E9\r 1"
  },
  {
    "manager_Name": "477( 5,268,044 ) TotalXfr : 26",
    "Teams": "Dre Wall( Dre Wall )",
    "SXL": "JM",
    "Latp": "63",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Watkins\r 2",
    "Player_10": "Haaland\r 18",
    "Player_12": "Fabianski\r 3",
    "Player_13": "McNeil\r 2",
    "Player_14": "Harwood-Bellis\r 2",
    "Player_7": "Johnson\r 1",
    "Player_2": "Keane\r 2",
    "Player_5": "Foden\r 3",
    "Player_6": "Palmer\r 10",
    "Player_3": "Faes\r 1",
    "Player_4": "Van den Berg\r 1",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "N.Jackson\r 9",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "556( 695,967 ) TotalXfr : 8",
    "Teams": "MIH Bobby( MIH Bobby )",
    "SXL": "BD",
    "Latp": "58",
    "Player_1": "Raya\r 0",
    "Player_11": "Wood\r 13",
    "Player_10": "Watkins\r 2",
    "Player_12": "J.Virginia\r 0",
    "Player_13": "Stewart\r 0",
    "Player_14": "Son\r 0",
    "Player_7": "Smith Rowe\r 6",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Gabriel\r 1",
    "Player_6": "Rogers\r 1",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Gvardiol\r 9",
    "Player_8": "Palmer\r 20",
    "Player_9": "Foden\r 3",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "545( 1,123,350 ) TotalXfr : 15",
    "Teams": "dylan highet( dylan highet )",
    "SXL": "EN",
    "Latp": "60",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Haaland\r 18",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Begovic\r 0",
    "Player_13": "Smith Rowe\r 6",
    "Player_14": "Faes\r 1",
    "Player_7": "Garnacho\r 2",
    "Player_2": "Alexander-Arnold\r 1",
    "Player_5": "M.Salah\r 10",
    "Player_6": "Palmer\r 10",
    "Player_3": "Lewis\r 6",
    "Player_4": "Robinson\r 2",
    "Player_8": "Rogers\r 1",
    "Player_9": "Welbeck\r 7",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "623( 7,396 ) TotalXfr : 8",
    "Teams": "anouska highet( anouska highet )",
    "SXL": "EN",
    "Latp": "54",
    "Player_1": "S\u00E1nchez\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Watkins\r 2",
    "Player_12": "Ramsdale\r 4",
    "Player_13": "Smith Rowe\r 6",
    "Player_14": "Mazraoui\r 2",
    "Player_7": "Mbeumo\r 15",
    "Player_2": "Keane\r 2",
    "Player_5": "McNeil\r 2",
    "Player_6": "Rogers\r 1",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Lewis\r 6",
    "Player_8": "M.Salah\r 10",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Robinson\r 2"
  },
  {
    "manager_Name": "549( 941,919 ) TotalXfr : 8",
    "Teams": "George Owino( George Owino )",
    "SXL": "KE",
    "Latp": "59",
    "Player_1": "Onana\r 1",
    "Player_11": "Haaland\r 12",
    "Player_10": "Ra\u00FAl\r 2",
    "Player_12": "Bentley\r 0",
    "Player_13": "Welbeck\r 7",
    "Player_14": "Harwood-Bellis\r 2",
    "Player_7": "M.Salah\r 10",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "Smith Rowe\r 6",
    "Player_6": "Mbeumo\r 15",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Robinson\r 2",
    "Player_8": "Foden\r 3",
    "Player_9": "Rogers\r 1",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "540( 1,309,206 ) TotalXfr : 5",
    "Teams": "Dijhaune Mcken( Dijhaune Mcken )",
    "SXL": "JM",
    "Latp": "47",
    "Player_1": "Flekken\r 1",
    "Player_11": "Solanke\r 2",
    "Player_10": "Haaland\r 12",
    "Player_12": "Leno\r 3",
    "Player_13": "McNeil\r 2",
    "Player_14": "Andreas\r 3",
    "Player_7": "Foden\r 3",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Digne\r 7",
    "Player_6": "Rogers\r 1",
    "Player_3": "Alexander-Arnold\r 1",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Mbeumo\r 15",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Harwood-Bellis\r 2"
  },
  {
    "manager_Name": "474( 5,444,071 ) TotalXfr : 19",
    "Teams": "Titobi Ogunsaju( Titobi Ogunsaju )",
    "SXL": "EN",
    "Latp": "63",
    "Player_1": "Hermansen\r 1",
    "Player_11": "Ra\u00FAl\r 2",
    "Player_10": "Watkins\r 2",
    "Player_12": "Pickford\r 2",
    "Player_13": "Gabriel\r 1",
    "Player_14": "Madueke\r 1",
    "Player_7": "Mbeumo\r 30",
    "Player_2": "Dalot\r 1",
    "Player_5": "Georginio\r 5",
    "Player_6": "Johnson\r 1",
    "Player_3": "Gvardiol\r 9",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Rogers\r 1",
    "Player_9": "Cunha\r 9",
    "Player_15": "Konat\u00E9\r 1"
  },
  {
    "manager_Name": "517( 2,643,530 ) TotalXfr : 8",
    "Teams": "Matthew Simms( Matthew Simms )",
    "SXL": "EN",
    "Latp": "87",
    "Player_1": "Raya\r 0",
    "Player_11": "Calvert-Lewin\r 2",
    "Player_10": "Cunha\r 9",
    "Player_12": "Ward\r 0",
    "Player_13": "Son\r 0",
    "Player_14": "Gabriel\r 1",
    "Player_7": "Smith Rowe\r 6",
    "Player_2": "A\u00EFt-Nouri\r 6",
    "Player_5": "M.Salah\r 10",
    "Player_6": "Mbeumo\r 30",
    "Player_3": "Konsa\r 2",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Palmer\r 10",
    "Player_9": "Wissa\r 10",
    "Player_15": "Robinson\r 2"
  }
];