var s = [
  {
    "manager_Name": "776( 14,705 )",
    "Teams": "Charlie\u0027s Angels( Charlie Smith )",
    "SXL": "ENG",
    "Latp": "7",
    "Player_1": "Raya CHE",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Mukiele 0",
    "Player_14": "P.M.Sarr FUL",
    "Player_7": "M.Salah WHU",
    "Player_2": "Cucurella ARS",
    "Player_5": "Saliba CHE",
    "Player_6": "Minteh NFO",
    "Player_3": "R\u00FAben 1",
    "Player_4": "Lacroix MUN",
    "Player_8": "Sarr MUN",
    "Player_9": "Reijnders 2",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "744( 114,131 )",
    "Teams": "Arteta Ball FC( Dylan Camilleri )",
    "SXL": "MLT",
    "Latp": "6",
    "Player_1": "Raya CHE",
    "Player_11": "Welbeck NFO",
    "Player_10": "Haaland 4",
    "Player_12": "Sels BHA",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Tarkowski 0",
    "Player_7": "Mbeumo CRY",
    "Player_2": "J.Timber CHE",
    "Player_5": "Sarr MUN",
    "Player_6": "Rice CHE",
    "Player_3": "Konsa WOL",
    "Player_4": "Mu\u00F1oz MUN",
    "Player_8": "Ndiaye 1",
    "Player_9": "Semenyo 1",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "738( 157,207 )",
    "Teams": "TetasSexyReds( Gary Pace )",
    "SXL": "MLT",
    "Latp": "10",
    "Player_1": "Sels BHA",
    "Player_11": "Haaland 6",
    "Player_10": "Mateta MUN",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Garnacho ARS",
    "Player_14": "Pedro Porro",
    "Player_7": "Mbeumo CRY",
    "Player_2": "J.Timber CHE",
    "Player_5": "Grealish 1",
    "Player_6": "Rice CHE",
    "Player_3": "Diouf LIV",
    "Player_4": "Mu\u00F1oz MUN",
    "Player_8": "Doku 2",
    "Player_9": "Woltemade 1",
    "Player_15": "Senesi 2"
  },
  {
    "manager_Name": "735( 178,392 )",
    "Teams": "Rice Rice Baby( kaisler Schembri )",
    "SXL": "MLT",
    "Latp": "29",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Haaland 6",
    "Player_10": "Thiago 10",
    "Player_12": "S\u00E1nchez ARS",
    "Player_13": "Thiaw 7",
    "Player_14": "Jo\u00E3o Pedro",
    "Player_7": "Szoboszlai WHU",
    "Player_2": "Calafiori CHE",
    "Player_5": "Foden 12",
    "Player_6": "Sarr MUN",
    "Player_3": "J.Timber CHE",
    "Player_4": "Gu\u00E9hi MUN",
    "Player_8": "Saka CHE",
    "Player_9": "Rogers WOL",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "735( 179,121 )",
    "Teams": "Slika FC( Kyle Gatt )",
    "SXL": "MLT",
    "Latp": "11",
    "Player_1": "Pope 0",
    "Player_11": "Woltemade 1",
    "Player_10": "Haaland 6",
    "Player_12": "Darlow 0",
    "Player_13": "Gy\u00F6keres CHE",
    "Player_14": "Hartman 3",
    "Player_7": "Ndiaye 1",
    "Player_2": "Virgil WHU",
    "Player_5": "Szoboszlai WHU",
    "Player_6": "Eze CHE",
    "Player_3": "Pedro Porro",
    "Player_4": "R\u00FAben 1",
    "Player_8": "Reijnders 2",
    "Player_9": "Enzo ARS",
    "Player_15": "Cucurella ARS"
  },
  {
    "manager_Name": "721( 351,634 )",
    "Teams": "MaltArsenal FC( Claude Spiteri )",
    "SXL": "MLT",
    "Latp": "21",
    "Player_1": "Donnarumma 5",
    "Player_11": "Thiago 10",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Mukiele 0",
    "Player_14": "Kroupi.Jr 1",
    "Player_7": "Doku 2",
    "Player_2": "Cash WOL",
    "Player_5": "Merino CHE",
    "Player_6": "Saka CHE",
    "Player_3": "Calafiori CHE",
    "Player_4": "Digne WOL",
    "Player_8": "Rogers WOL",
    "Player_9": "M.Salah WHU",
    "Player_15": "Heaven CRY"
  },
  {
    "manager_Name": "720( 371,441 )",
    "Teams": "Taggers FC( Karl Caruana )",
    "SXL": "MLT",
    "Latp": "17",
    "Player_1": "Petrovi\u0107 2",
    "Player_11": "Mateta MUN",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Mukiele 0",
    "Player_14": "Semenyo 1",
    "Player_7": "Ndiaye 1",
    "Player_2": "Digne WOL",
    "Player_5": "Saka CHE",
    "Player_6": "Mbeumo CRY",
    "Player_3": "Van de",
    "Player_4": "Gu\u00E9hi MUN",
    "Player_8": "Minteh NFO",
    "Player_9": "Thiago 10",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "719( 380,945 )",
    "Teams": "Ellul FC( Andrew Ellul )",
    "SXL": "MLT",
    "Latp": "20",
    "Player_1": "Pope 0",
    "Player_11": "Mateta MUN",
    "Player_10": "Haaland 4",
    "Player_12": "Henderson MUN",
    "Player_13": "Milenkovi\u0107 BHA",
    "Player_14": "Minteh NFO",
    "Player_7": "Mbeumo CRY",
    "Player_2": "Gu\u00E9hi MUN",
    "Player_5": "Van de",
    "Player_6": "Rice CHE",
    "Player_3": "Senesi 2",
    "Player_4": "Burn 4",
    "Player_8": "Eze CHE",
    "Player_9": "Thiago 10",
    "Player_15": "Caicedo ARS"
  },
  {
    "manager_Name": "708( 594,873 )",
    "Teams": "kurt slika( Kurt Gatt )",
    "SXL": "MLT",
    "Latp": "6",
    "Player_1": "Raya CHE",
    "Player_11": "Welbeck NFO",
    "Player_10": "Haaland 4",
    "Player_12": "Jos\u00E9 S\u00E1",
    "Player_13": "Gy\u00F6keres CHE",
    "Player_14": "Cucurella ARS",
    "Player_7": "Semenyo 1",
    "Player_2": "Gu\u00E9hi MUN",
    "Player_5": "R\u00FAben 1",
    "Player_6": "Mbeumo CRY",
    "Player_3": "Virgil WHU",
    "Player_4": "Van de",
    "Player_8": "Zubimendi CHE",
    "Player_9": "J.Palhinha FUL",
    "Player_15": "Caicedo ARS"
  },
  {
    "manager_Name": "706( 643,203 )",
    "Teams": "RZM765( Cedrik Dalli )",
    "SXL": "MLT",
    "Latp": "9",
    "Player_1": "Verbruggen NFO",
    "Player_11": "Haaland 6",
    "Player_10": "Bowen LIV",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Reijnders 2",
    "Player_14": "Est\u00E8ve 3",
    "Player_7": "Tavernier 1",
    "Player_2": "Van de",
    "Player_5": "Anderson BHA",
    "Player_6": "Grealish 1",
    "Player_3": "R\u00FAben 1",
    "Player_4": "Mu\u00F1oz MUN",
    "Player_8": "Rice CHE",
    "Player_9": "Mateta MUN",
    "Player_15": "Rodon 0"
  },
  {
    "manager_Name": "699( 829,430 )",
    "Teams": "diavoli 11( Paul Micallef )",
    "SXL": "MLT",
    "Latp": "25",
    "Player_1": "Donnarumma 5",
    "Player_11": "Haaland 6",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Setford CHE",
    "Player_13": "Semenyo 1",
    "Player_14": "Chalobah ARS",
    "Player_7": "Caicedo ARS",
    "Player_2": "Gu\u00E9hi MUN",
    "Player_5": "Mbeumo CRY",
    "Player_6": "B.Fernandes CRY",
    "Player_3": "Senesi 2",
    "Player_4": "J.Timber CHE",
    "Player_8": "Reijnders 2",
    "Player_9": "Thiago 10",
    "Player_15": "Byram 0"
  },
  {
    "manager_Name": "698( 853,426 )",
    "Teams": "Bend it like Boogie( Ryan Bonello Gatt )",
    "SXL": "MLT",
    "Latp": "16",
    "Player_1": "Kelleher 2",
    "Player_11": "Mateta MUN",
    "Player_10": "Haaland 6",
    "Player_12": "Sels BHA",
    "Player_13": "Kroupi.Jr 1",
    "Player_14": "Gu\u00E9hi MUN",
    "Player_7": "Gakpo WHU",
    "Player_2": "Saliba CHE",
    "Player_5": "Mbeumo CRY",
    "Player_6": "Xhaka 5",
    "Player_3": "R\u00FAben 1",
    "Player_4": "J.Timber CHE",
    "Player_8": "Doku 2",
    "Player_9": "Saka CHE",
    "Player_15": "Wan-Bissaka LIV"
  },
  {
    "manager_Name": "696( 917,029 )",
    "Teams": "Old Havertz Kai Hard( Andy Bonaci )",
    "SXL": "MLT",
    "Latp": "7",
    "Player_1": "Raya CHE",
    "Player_11": "Haaland 4",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "J.Timber CHE",
    "Player_14": "Dewsbury-Hall 1",
    "Player_7": "Semenyo 1",
    "Player_2": "Senesi 2",
    "Player_5": "Mbeumo CRY",
    "Player_6": "Enzo ARS",
    "Player_3": "Mu\u00F1oz MUN",
    "Player_4": "Mukiele 0",
    "Player_8": "Sarr MUN",
    "Player_9": "Mateta MUN",
    "Player_15": "Virgil WHU"
  },
  {
    "manager_Name": "695( 959,559 )",
    "Teams": "Kind FC( Richard Kind )",
    "SXL": "MLT",
    "Latp": "5",
    "Player_1": "Raya CHE",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta MUN",
    "Player_12": "Henderson MUN",
    "Player_13": "Rodon 0",
    "Player_14": "Jo\u00E3o Pedro",
    "Player_7": "Grealish 1",
    "Player_2": "Dunk NFO",
    "Player_5": "Cucurella ARS",
    "Player_6": "Eze CHE",
    "Player_3": "Saliba CHE",
    "Player_4": "Lacroix MUN",
    "Player_8": "Mbeumo CRY",
    "Player_9": "Malen WOL",
    "Player_15": "Reijnders 2"
  },
  {
    "manager_Name": "694( 967,663 )",
    "Teams": "Clarky FC( Carl Clark )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "Leno TOT",
    "Player_11": "Haaland 2",
    "Player_10": "Gy\u00F6keres CHE",
    "Player_12": "Slonina ARS",
    "Player_13": "Konat\u00E9 WHU",
    "Player_14": "Mayenda 0",
    "Player_7": "Saka CHE",
    "Player_2": "Sch\u00E4r 0",
    "Player_5": "Cullen 2",
    "Player_6": "Enzo ARS",
    "Player_3": "Murillo BHA",
    "Player_4": "Mitchell MUN",
    "Player_8": "Semenyo 1",
    "Player_9": "Eze CHE",
    "Player_15": "Spence FUL"
  },
  {
    "manager_Name": "682( 1,393,083 )",
    "Teams": "The Invincibles 49( Clive Caruana )",
    "SXL": "MLT",
    "Latp": "12",
    "Player_1": "Raya CHE",
    "Player_11": "Mateta MUN",
    "Player_10": "Woltemade 1",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Kudus FUL",
    "Player_14": "Mbeumo CRY",
    "Player_7": "Semenyo 1",
    "Player_2": "Van de",
    "Player_5": "O\u2019Reilly 4",
    "Player_6": "Minteh NFO",
    "Player_3": "J.Timber CHE",
    "Player_4": "Mu\u00F1oz MUN",
    "Player_8": "Rice CHE",
    "Player_9": "Haaland 6",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "680( 1,466,530 )",
    "Teams": "Bench Warmers( kevin dalli )",
    "SXL": "MLT",
    "Latp": "26",
    "Player_1": "Kelleher 2",
    "Player_11": "Haaland 6",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Petrovi\u0107 2",
    "Player_13": "Semenyo 1",
    "Player_14": "Gusto ARS",
    "Player_7": "Gakpo WHU",
    "Player_2": "Gu\u00E9hi MUN",
    "Player_5": "Merino CHE",
    "Player_6": "Saka CHE",
    "Player_3": "Gvardiol 6",
    "Player_4": "Van de",
    "Player_8": "Doku 2",
    "Player_9": "Thiago 10",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "672( 1,796,584 )",
    "Teams": "Hamrun Gunners( Mark Monseigneur )",
    "SXL": "MLT",
    "Latp": "6",
    "Player_1": "Pickford 0",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 2",
    "Player_12": "Henderson MUN",
    "Player_13": "Walker 3",
    "Player_14": "Virgil WHU",
    "Player_7": "Cullen 2",
    "Player_2": "Mykolenko 0",
    "Player_5": "Rice CHE",
    "Player_6": "Saka CHE",
    "Player_3": "Toti AVL",
    "Player_4": "Pedro Porro",
    "Player_8": "Trossard CHE",
    "Player_9": "Woltemade 2",
    "Player_15": "Sarr MUN"
  },
  {
    "manager_Name": "671( 1,871,503 )",
    "Teams": "Noni your business( Owen Farrugia )",
    "SXL": "MLT",
    "Latp": "11",
    "Player_1": "Raya CHE",
    "Player_11": "Mateta MUN",
    "Player_10": "Haaland 6",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Andersen TOT",
    "Player_7": "Rice CHE",
    "Player_2": "J.Timber CHE",
    "Player_5": "Semenyo 1",
    "Player_6": "Ndiaye 1",
    "Player_3": "James ARS",
    "Player_4": "Senesi 2",
    "Player_8": "Grealish 1",
    "Player_9": "Amad CRY",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "670( 1,885,426 )",
    "Teams": "gunner_xi( Justin kind )",
    "SXL": "MLT",
    "Latp": "11",
    "Player_1": "Raya CHE",
    "Player_11": "Mateta MUN",
    "Player_10": "Haaland 6",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Enzo ARS",
    "Player_14": "Reinildo 4",
    "Player_7": "Gakpo WHU",
    "Player_2": "Calafiori CHE",
    "Player_5": "Doku 2",
    "Player_6": "Kudus FUL",
    "Player_3": "Cucurella ARS",
    "Player_4": "Senesi 2",
    "Player_8": "Sarr MUN",
    "Player_9": "Woltemade 1",
    "Player_15": "Romero FUL"
  },
  {
    "manager_Name": "666( 2,100,183 )",
    "Teams": "Senglea Gunners( Daryl Ebejer )",
    "SXL": "MLT",
    "Latp": "13",
    "Player_1": "Raya CHE",
    "Player_11": "Mateta MUN",
    "Player_10": "Haaland 6",
    "Player_12": "Moore 0",
    "Player_13": "Gabriel CHE",
    "Player_14": "Alderete 0",
    "Player_7": "Rice CHE",
    "Player_2": "Virgil WHU",
    "Player_5": "Mbeumo CRY",
    "Player_6": "Semenyo 1",
    "Player_3": "R\u00FAben 1",
    "Player_4": "Gu\u00E9hi MUN",
    "Player_8": "Xhaka 5",
    "Player_9": "Welbeck NFO",
    "Player_15": "King TOT"
  },
  {
    "manager_Name": "664( 2,179,515 )",
    "Teams": "Gunz( Kurt Zammit )",
    "SXL": "MLT",
    "Latp": "20",
    "Player_1": "Donnarumma 5",
    "Player_11": "Isidor 2",
    "Player_10": "Haaland 6",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Anthony 4",
    "Player_14": "Senesi 2",
    "Player_7": "Rice CHE",
    "Player_2": "Gvardiol 6",
    "Player_5": "J.Timber CHE",
    "Player_6": "Saka CHE",
    "Player_3": "Gu\u00E9hi MUN",
    "Player_4": "Cash WOL",
    "Player_8": "Semenyo 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Tavernier 1"
  },
  {
    "manager_Name": "660( 2,361,606 )",
    "Teams": "GunnerPorts( Matthew Portelli )",
    "SXL": "MLT",
    "Latp": "17",
    "Player_1": "Pope 0",
    "Player_11": "Haaland 6",
    "Player_10": "Woltemade 1",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Caicedo ARS",
    "Player_14": "James ARS",
    "Player_7": "Eze CHE",
    "Player_2": "Senesi 2",
    "Player_5": "Semenyo 1",
    "Player_6": "Mbeumo CRY",
    "Player_3": "Gvardiol 6",
    "Player_4": "Lacroix MUN",
    "Player_8": "Ndiaye 1",
    "Player_9": "Mateta MUN",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "658( 2,453,475 )",
    "Teams": "Sammygooner****( Sammy Vella )",
    "SXL": "MLT",
    "Latp": "8",
    "Player_1": "S\u00E1nchez ARS",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta MUN",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Reijnders 2",
    "Player_14": "Hume 0",
    "Player_7": "Semenyo 1",
    "Player_2": "Virgil WHU",
    "Player_5": "Eze CHE",
    "Player_6": "Sarr MUN",
    "Player_3": "Van de",
    "Player_4": "Konsa WOL",
    "Player_8": "Kudus FUL",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "J.Timber CHE"
  },
  {
    "manager_Name": "656( 2,575,398 )",
    "Teams": "Let him cook( Henry Adjei )",
    "SXL": "MLT",
    "Latp": "24",
    "Player_1": "Kelleher 2",
    "Player_11": "Thiago 10",
    "Player_10": "Mateta MUN",
    "Player_12": "Raya CHE",
    "Player_13": "P.M.Sarr FUL",
    "Player_14": "Semenyo 1",
    "Player_7": "Saka CHE",
    "Player_2": "Virgil WHU",
    "Player_5": "Est\u00E8ve 3",
    "Player_6": "Kudus FUL",
    "Player_3": "Gu\u00E9hi MUN",
    "Player_4": "Van de",
    "Player_8": "Xhaka 5",
    "Player_9": "Haaland 4",
    "Player_15": "Gabriel CHE"
  },
  {
    "manager_Name": "655( 2,609,761 )",
    "Teams": "Very Rice( Jake Caruana )",
    "SXL": "MLT",
    "Latp": "11",
    "Player_1": "Raya CHE",
    "Player_11": "Haaland 6",
    "Player_10": "Mateta MUN",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Chalobah ARS",
    "Player_14": "Caicedo ARS",
    "Player_7": "Sarr MUN",
    "Player_2": "J.Timber CHE",
    "Player_5": "Saka CHE",
    "Player_6": "Semenyo 1",
    "Player_3": "Senesi 2",
    "Player_4": "Gu\u00E9hi MUN",
    "Player_8": "Doku 2",
    "Player_9": "Welbeck NFO",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "654( 2,660,185 )",
    "Teams": "Select Team Name( Kurt Bonnici )",
    "SXL": "MLT",
    "Latp": "15",
    "Player_1": "Donnarumma 5",
    "Player_11": "Woltemade 1",
    "Player_10": "Mateta MUN",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Anderson BHA",
    "Player_14": "Xhaka 5",
    "Player_7": "Saka CHE",
    "Player_2": "J.Timber CHE",
    "Player_5": "Senesi 2",
    "Player_6": "Semenyo 1",
    "Player_3": "Mu\u00F1oz MUN",
    "Player_4": "Virgil WHU",
    "Player_8": "Sarr MUN",
    "Player_9": "Haaland 6",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "653( 2,710,817 )",
    "Teams": "Gozo Gunners( Jonathan Portelli )",
    "SXL": "MLT",
    "Latp": "24",
    "Player_1": "Raya CHE",
    "Player_11": "Thiago 10",
    "Player_10": "Haaland 6",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Caicedo ARS",
    "Player_14": "James ARS",
    "Player_7": "Rice CHE",
    "Player_2": "Virgil WHU",
    "Player_5": "Senesi 2",
    "Player_6": "Saka CHE",
    "Player_3": "Burn 4",
    "Player_4": "Mu\u00F1oz MUN",
    "Player_8": "Reijnders 2",
    "Player_9": "Mateta MUN",
    "Player_15": "Stach 0"
  },
  {
    "manager_Name": "650( 2,873,658 )",
    "Teams": "Eze Come Eze Go( Theo Magro )",
    "SXL": "MLT",
    "Latp": "19",
    "Player_1": "Raya CHE",
    "Player_11": "Thiago 10",
    "Player_10": "Mateta MUN",
    "Player_12": "Petrovi\u0107 2",
    "Player_13": "Chalobah ARS",
    "Player_14": "Anthony 4",
    "Player_7": "Saka CHE",
    "Player_2": "Mu\u00F1oz MUN",
    "Player_5": "Mbeumo CRY",
    "Player_6": "Caicedo ARS",
    "Player_3": "Lacroix MUN",
    "Player_4": "J.Timber CHE",
    "Player_8": "Xhaka 5",
    "Player_9": "Haaland 4",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "642( 3,284,698 )",
    "Teams": "Zubi-Dooby Doo( Malcolm Vella Vidal )",
    "SXL": "MLT",
    "Latp": "7",
    "Player_1": "Henderson MUN",
    "Player_11": "Bowen LIV",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Acheampong ARS",
    "Player_7": "Eze CHE",
    "Player_2": "Virgil WHU",
    "Player_5": "Saka CHE",
    "Player_6": "Enzo ARS",
    "Player_3": "J.Timber CHE",
    "Player_4": "Cash WOL",
    "Player_8": "Tavernier 1",
    "Player_9": "Reijnders 2",
    "Player_15": "S.Bueno AVL"
  },
  {
    "manager_Name": "634( 3,710,126 )",
    "Teams": "Dial Square( Liam Carabott )",
    "SXL": "MLT",
    "Latp": "20",
    "Player_1": "Roefs 1",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 10",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Virgil WHU",
    "Player_14": "Jo\u00E3o Pedro",
    "Player_7": "Enzo ARS",
    "Player_2": "J.Timber CHE",
    "Player_5": "Minteh NFO",
    "Player_6": "Semenyo 1",
    "Player_3": "Mu\u00F1oz MUN",
    "Player_4": "Van de",
    "Player_8": "Zubimendi CHE",
    "Player_9": "Anthony 4",
    "Player_15": "Wan-Bissaka LIV"
  },
  {
    "manager_Name": "631( 3,873,735 )",
    "Teams": "matthew 14( matthew borg )",
    "SXL": "MLT",
    "Latp": "6",
    "Player_1": "Pope 0",
    "Player_11": "Haaland 4",
    "Player_10": "Bowen LIV",
    "Player_12": "King 0",
    "Player_13": "Gu\u00E9hi MUN",
    "Player_14": "Wirtz WHU",
    "Player_7": "Minteh NFO",
    "Player_2": "Tarkowski 0",
    "Player_5": "Grealish 1",
    "Player_6": "Caicedo ARS",
    "Player_3": "Pedro Porro",
    "Player_4": "Konsa WOL",
    "Player_8": "B.Fernandes CRY",
    "Player_9": "Woltemade 1",
    "Player_15": "Burn 4"
  },
  {
    "manager_Name": "631( 3,879,763 )",
    "Teams": "Kanokk 118( Rodney Azzopardi )",
    "SXL": "MLT",
    "Latp": "21",
    "Player_1": "Donnarumma 5",
    "Player_11": "Thiago 10",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Henderson MUN",
    "Player_13": "Reijnders 2",
    "Player_14": "Senesi 2",
    "Player_7": "Saka CHE",
    "Player_2": "J.Timber CHE",
    "Player_5": "Rice CHE",
    "Player_6": "Semenyo 1",
    "Player_3": "Mu\u00F1oz MUN",
    "Player_4": "Cucurella ARS",
    "Player_8": "Enzo ARS",
    "Player_9": "Evanilson 5",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "625( 4,208,216 )",
    "Teams": "Sultan Army( Julian Sultana )",
    "SXL": "MLT",
    "Latp": "27",
    "Player_1": "Donnarumma 5",
    "Player_11": "Thiago 20",
    "Player_10": "Welbeck NFO",
    "Player_12": "Pickford 0",
    "Player_13": "Gabriel CHE",
    "Player_14": "Gakpo WHU",
    "Player_7": "B.Fernandes CRY",
    "Player_2": "Saliba CHE",
    "Player_5": "Mu\u00F1oz MUN",
    "Player_6": "Doku 2",
    "Player_3": "Murillo BHA",
    "Player_4": "Calafiori CHE",
    "Player_8": "Mbeumo CRY",
    "Player_9": "Mateta MUN",
    "Player_15": "Semenyo 1"
  },
  {
    "manager_Name": "617( 4,647,988 )",
    "Teams": "Henry\u2019s Heroes( Jean Azzopardi )",
    "SXL": "MLT",
    "Latp": "6",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Haaland 2",
    "Player_10": "Woltemade 1",
    "Player_12": "Vicario FUL",
    "Player_13": "Senesi 2",
    "Player_14": "Semenyo 1",
    "Player_7": "Reijnders 2",
    "Player_2": "Calafiori CHE",
    "Player_5": "Eze CHE",
    "Player_6": "Gravenberch WHU",
    "Player_3": "Gu\u00E9hi MUN",
    "Player_4": "Alderete 0",
    "Player_8": "Mbeumo CRY",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Cucurella ARS"
  },
  {
    "manager_Name": "616( 4,693,781 )",
    "Teams": "Mandra United( Steven Silvio )",
    "SXL": "MLT",
    "Latp": "17",
    "Player_1": "Raya CHE",
    "Player_11": "Mateta MUN",
    "Player_10": "Thiago 10",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Anderson BHA",
    "Player_14": "Semenyo 1",
    "Player_7": "Sarr MUN",
    "Player_2": "Virgil WHU",
    "Player_5": "Senesi 2",
    "Player_6": "Enzo ARS",
    "Player_3": "J.Timber CHE",
    "Player_4": "Mitchell MUN",
    "Player_8": "Tavernier 1",
    "Player_9": "Haaland 4",
    "Player_15": "Gabriel CHE"
  },
  {
    "manager_Name": "615( 4,775,214 )",
    "Teams": "SC CARBINE( yan cutajar )",
    "SXL": "MLT",
    "Latp": "16",
    "Player_1": "Raya CHE",
    "Player_11": "Woltemade 1",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Wan-Bissaka LIV",
    "Player_14": "Grealish 1",
    "Player_7": "Caicedo ARS",
    "Player_2": "Cucurella ARS",
    "Player_5": "Gu\u00E9hi MUN",
    "Player_6": "Semenyo 1",
    "Player_3": "Van de",
    "Player_4": "Mu\u00F1oz MUN",
    "Player_8": "Gibbs-White BHA",
    "Player_9": "Thiago 10",
    "Player_15": "Baleba NFO"
  },
  {
    "manager_Name": "612( 4,910,049 )",
    "Teams": "Gy\u00F6keres14( Zack Vella )",
    "SXL": "MLT",
    "Latp": "12",
    "Player_1": "Raya CHE",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 4",
    "Player_12": "Heaton CRY",
    "Player_13": "Gudmundsson 1",
    "Player_14": "Reinildo 4",
    "Player_7": "King TOT",
    "Player_2": "Est\u00E8ve 3",
    "Player_5": "Eze CHE",
    "Player_6": "M.Salah WHU",
    "Player_3": "Ballard 3",
    "Player_4": "Konsa WOL",
    "Player_8": "Reijnders 2",
    "Player_9": "Isak WHU",
    "Player_15": "Matete 0"
  },
  {
    "manager_Name": "611( 4,982,822 )",
    "Teams": "Lassie fc( Kirsten Tanti )",
    "SXL": "MLT",
    "Latp": "10",
    "Player_1": "Raya CHE",
    "Player_11": "Isidor 2",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Van de",
    "Player_14": "Senesi 2",
    "Player_7": "Xhaka 5",
    "Player_2": "Pedro Porro",
    "Player_5": "Saka CHE",
    "Player_6": "Anderson BHA",
    "Player_3": "J.Timber CHE",
    "Player_4": "Cucurella ARS",
    "Player_8": "Ndiaye 1",
    "Player_9": "Mateta MUN",
    "Player_15": "Semenyo 1"
  },
  {
    "manager_Name": "609( 5,084,425 )",
    "Teams": "Rice Rice Baby( Ian Falzon )",
    "SXL": "MLT",
    "Latp": "15",
    "Player_1": "Donnarumma 5",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Woltemade 1",
    "Player_14": "Van de",
    "Player_7": "Neto ARS",
    "Player_2": "Senesi 2",
    "Player_5": "Caicedo ARS",
    "Player_6": "Mbeumo CRY",
    "Player_3": "Virgil WHU",
    "Player_4": "J.Timber CHE",
    "Player_8": "Xhaka 5",
    "Player_9": "Semenyo 1",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "606( 5,253,446 )",
    "Teams": "Lions( Daniel Ferriggi )",
    "SXL": "MLT",
    "Latp": "14",
    "Player_1": "Kelleher 2",
    "Player_11": "Watkins WOL",
    "Player_10": "Mateta MUN",
    "Player_12": "Pickford 0",
    "Player_13": "Milenkovi\u0107 BHA",
    "Player_14": "P.M.Sarr FUL",
    "Player_7": "Rice CHE",
    "Player_2": "Senesi 2",
    "Player_5": "Casemiro CRY",
    "Player_6": "Caicedo ARS",
    "Player_3": "Virgil WHU",
    "Player_4": "Mu\u00F1oz MUN",
    "Player_8": "M.Salah WHU",
    "Player_9": "Thiago 10",
    "Player_15": "Burn 4"
  },
  {
    "manager_Name": "604( 5,367,044 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "21",
    "Player_1": "Raya CHE",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 10",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Saka CHE",
    "Player_2": "Mitchell MUN",
    "Player_5": "Mukiele 0",
    "Player_6": "Xhaka 5",
    "Player_3": "Cucurella ARS",
    "Player_4": "Senesi 2",
    "Player_8": "Rice CHE",
    "Player_9": "L.Paquet\u00E1 LIV",
    "Player_15": "L.Miley 9"
  },
  {
    "manager_Name": "587( 6,230,956 )",
    "Teams": "NLD( Jordi Farrugia )",
    "SXL": "MLT",
    "Latp": "6",
    "Player_1": "Raya CHE",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "\u0160e\u0161ko CRY",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Romero FUL",
    "Player_14": "Saka CHE",
    "Player_7": "Eze CHE",
    "Player_2": "Cucurella ARS",
    "Player_5": "James ARS",
    "Player_6": "Elanga 2",
    "Player_3": "Gabriel CHE",
    "Player_4": "Burn 4",
    "Player_8": "Gibbs-White BHA",
    "Player_9": "Rogers WOL",
    "Player_15": "Evanilson 5"
  },
  {
    "manager_Name": "578( 6,686,303 )",
    "Teams": "Zubi dubi doo( Julia Schembri )",
    "SXL": "MLT",
    "Latp": "4",
    "Player_1": "Kelleher 2",
    "Player_11": "Beto 0",
    "Player_10": "Gy\u00F6keres CHE",
    "Player_12": "Verbruggen NFO",
    "Player_13": "Wan-Bissaka LIV",
    "Player_14": "Dewsbury-Hall 1",
    "Player_7": "Semenyo 1",
    "Player_2": "Konsa WOL",
    "Player_5": "Eze CHE",
    "Player_6": "M.Salah WHU",
    "Player_3": "Saliba CHE",
    "Player_4": "Gu\u00E9hi MUN",
    "Player_8": "Elanga 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "565( 7,325,164 )",
    "Teams": "Mihawha( Matthew Paris )",
    "SXL": "MLT",
    "Latp": "10",
    "Player_1": "Donnarumma 5",
    "Player_11": "Mateta MUN",
    "Player_10": "Welbeck NFO",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Van de",
    "Player_14": "Xhaka 5",
    "Player_7": "Rice CHE",
    "Player_2": "Mukiele 0",
    "Player_5": "Gabriel CHE",
    "Player_6": "Semenyo 1",
    "Player_3": "James ARS",
    "Player_4": "Calafiori CHE",
    "Player_8": "Mbeumo CRY",
    "Player_9": "Haaland 4",
    "Player_15": "Ndiaye 1"
  },
  {
    "manager_Name": "560( 7,539,234 )",
    "Teams": "InvinciblesCOYG( Clayton Camilleri )",
    "SXL": "MLT",
    "Latp": "9",
    "Player_1": "Raya CHE",
    "Player_11": "Wilson LIV",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Kelleher 2",
    "Player_13": "Dewsbury-Hall 1",
    "Player_14": "A\u00EFt-Nouri 0",
    "Player_7": "Xhaka 5",
    "Player_2": "Cucurella ARS",
    "Player_5": "M.Salah WHU",
    "Player_6": "Grealish 1",
    "Player_3": "Kerkez WHU",
    "Player_4": "Est\u00E8ve 3",
    "Player_8": "Saka CHE",
    "Player_9": "Gy\u00F6keres CHE",
    "Player_15": "Reinildo 4"
  },
  {
    "manager_Name": "553( 7,842,880 )",
    "Teams": "Harambe FC( Glenn Gauci Borda )",
    "SXL": "MLT",
    "Latp": "7",
    "Player_1": "S\u00E1nchez ARS",
    "Player_11": "Bowen LIV",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Wan-Bissaka LIV",
    "Player_14": "Est\u00E8ve 3",
    "Player_7": "Reijnders 2",
    "Player_2": "Van de",
    "Player_5": "Semenyo 1",
    "Player_6": "M.Salah WHU",
    "Player_3": "Konsa WOL",
    "Player_4": "Reinildo 4",
    "Player_8": "Mbeumo CRY",
    "Player_9": "Wood BHA",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "547( 8,103,268 )",
    "Teams": "Jack Nigret( Jack Gatt )",
    "SXL": "MLT",
    "Latp": "9",
    "Player_1": "Donnarumma 5",
    "Player_11": "Gy\u00F6keres CHE",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Verbruggen NFO",
    "Player_13": "Rogers WOL",
    "Player_14": "Adams 7",
    "Player_7": "Doku 2",
    "Player_2": "Van de",
    "Player_5": "Konat\u00E9 WHU",
    "Player_6": "Reijnders 2",
    "Player_3": "Gabriel CHE",
    "Player_4": "Frimpong WHU",
    "Player_8": "Palmer ARS",
    "Player_9": "\u0160e\u0161ko CRY",
    "Player_15": "Mu\u00F1oz MUN"
  },
  {
    "manager_Name": "546( 8,140,537 )",
    "Teams": "Gorsil Gunners( Gordon Silvio )",
    "SXL": "MLT",
    "Latp": "6",
    "Player_1": "Raya CHE",
    "Player_11": "\u0160e\u0161ko CRY",
    "Player_10": "Haaland 4",
    "Player_12": "Sels BHA",
    "Player_13": "Kluivert 1",
    "Player_14": "Konsa WOL",
    "Player_7": "Semenyo 1",
    "Player_2": "James ARS",
    "Player_5": "Wan-Bissaka LIV",
    "Player_6": "Eze CHE",
    "Player_3": "Gu\u00E9hi MUN",
    "Player_4": "Van de",
    "Player_8": "Sarr MUN",
    "Player_9": "Marmoush 1",
    "Player_15": "Beto 0"
  },
  {
    "manager_Name": "542( 8,316,890 )",
    "Teams": "Viktooooooor( Fredrick Buhagiar )",
    "SXL": "MLT",
    "Latp": "14",
    "Player_1": "Vicario FUL",
    "Player_11": "Marc Guiu",
    "Player_10": "Haaland 4",
    "Player_12": "S\u00E1nchez ARS",
    "Player_13": "Gy\u00F6keres CHE",
    "Player_14": "Enzo ARS",
    "Player_7": "Eze CHE",
    "Player_2": "Reinildo 4",
    "Player_5": "Gu\u00E9hi MUN",
    "Player_6": "Saka CHE",
    "Player_3": "Mitchell MUN",
    "Player_4": "Milenkovi\u0107 BHA",
    "Player_8": "Ndiaye 1",
    "Player_9": "Xhaka 5",
    "Player_15": "Rodon 0"
  }
];