var s = [
  {
    "manager_Name": "804( 10,922 )",
    "Teams": "cavac215( Ankit Chhetri )",
    "SXL": "IND",
    "Latp": "25",
    "Player_1": "Pope 0",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Chalobah 9",
    "Player_14": "Calvert-Lewin 7",
    "Player_7": "Semenyo 1",
    "Player_2": "Gu\u00E9hi 0",
    "Player_5": "Saka 5",
    "Player_6": "Rice 4",
    "Player_3": "Van de",
    "Player_4": "Pau 6",
    "Player_8": "Mbeumo 1",
    "Player_9": "Minteh 3",
    "Player_15": "Gabriel 0"
  },
  {
    "manager_Name": "761( 154,112 )",
    "Teams": "False 9( Rohan Rai )",
    "SXL": "IND",
    "Latp": "40",
    "Player_1": "Pope 0",
    "Player_11": "Thiago 13",
    "Player_10": "Woltemade 7",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Anthony 4",
    "Player_14": "Mukiele 0",
    "Player_7": "Saka 5",
    "Player_2": "Senesi 2",
    "Player_5": "Mbeumo 1",
    "Player_6": "Sarr 1",
    "Player_3": "Gu\u00E9hi 0",
    "Player_4": "Virgil 6",
    "Player_8": "Semenyo 1",
    "Player_9": "Haaland 4",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "758( 177,332 )",
    "Teams": "11 n over( Ashish Rai )",
    "SXL": "IND",
    "Latp": "62",
    "Player_1": "Raya 3",
    "Player_11": "Welbeck 2",
    "Player_10": "Haaland 6",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Diouf 1",
    "Player_7": "O.Dango 12",
    "Player_2": "Mu\u00F1oz 1",
    "Player_5": "Gakpo 14",
    "Player_6": "Minteh 3",
    "Player_3": "J.Timber 2",
    "Player_4": "Cash 6",
    "Player_8": "Saka 5",
    "Player_9": "Kudus 8",
    "Player_15": "Rodon 0"
  },
  {
    "manager_Name": "751( 245,605 )",
    "Teams": "abcde FC( Prayash Thapa )",
    "SXL": "IND",
    "Latp": "69",
    "Player_1": "Martinez 7",
    "Player_11": "Thiago 13",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Keane 2",
    "Player_14": "Est\u00E8ve 3",
    "Player_7": "Foden 15",
    "Player_2": "Cash 6",
    "Player_5": "Schade 3",
    "Player_6": "M.Salah 0",
    "Player_3": "Collins 4",
    "Player_4": "Mukiele 0",
    "Player_8": "Gakpo 14",
    "Player_9": "Rogers 3",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "747( 297,949 )",
    "Teams": "Alpha11( AVIJIT DAS )",
    "SXL": "IND",
    "Latp": "65",
    "Player_1": "Kelleher 2",
    "Player_11": "Thiago 13",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Mukiele 0",
    "Player_14": "Est\u00E8ve 3",
    "Player_7": "M.Salah 0",
    "Player_2": "Mu\u00F1oz 1",
    "Player_5": "Rogers 3",
    "Player_6": "Gakpo 14",
    "Player_3": "Cash 6",
    "Player_4": "O\u2019Reilly 4",
    "Player_8": "Schade 3",
    "Player_9": "Foden 15",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "747( 304,327 )",
    "Teams": "RIP-DIOGO.20( pranam rai )",
    "SXL": "IND",
    "Latp": "56",
    "Player_1": "Vicario 1",
    "Player_11": "Thiago 13",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Cucurella 1",
    "Player_14": "Mbeumo 1",
    "Player_7": "Malen 3",
    "Player_2": "Mu\u00F1oz 1",
    "Player_5": "Est\u00EAv\u00E3o 1",
    "Player_6": "Gakpo 14",
    "Player_3": "R\u00FAben 1",
    "Player_4": "Est\u00E8ve 3",
    "Player_8": "Kudus 8",
    "Player_9": "Woltemade 7",
    "Player_15": "J.Timber 2"
  },
  {
    "manager_Name": "739( 415,219 )",
    "Teams": "Kung fu Pandoos( Indrajeet Singh )",
    "SXL": "IND",
    "Latp": "53",
    "Player_1": "Kelleher 2",
    "Player_11": "Welbeck 2",
    "Player_10": "Haaland 4",
    "Player_12": "S\u00E1nchez 3",
    "Player_13": "Grealish 2",
    "Player_14": "Walker 3",
    "Player_7": "Foden 15",
    "Player_2": "Virgil 6",
    "Player_5": "Pedro Porro",
    "Player_6": "Semenyo 1",
    "Player_3": "Gvardiol 6",
    "Player_4": "De Ligt",
    "Player_8": "Mbeumo 1",
    "Player_9": "Thiago 13",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "739( 418,951 )",
    "Teams": "PWS( Z S )",
    "SXL": "IND",
    "Latp": "55",
    "Player_1": "Donnarumma 5",
    "Player_11": "Haaland 6",
    "Player_10": "Thiago 13",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Richards 1",
    "Player_14": "Van de",
    "Player_7": "Caicedo -2",
    "Player_2": "Senesi 2",
    "Player_5": "Rice 4",
    "Player_6": "Semenyo 1",
    "Player_3": "O\u2019Reilly 4",
    "Player_4": "J.Timber 2",
    "Player_8": "Gakpo 14",
    "Player_9": "Mateta 6",
    "Player_15": "Grealish 2"
  },
  {
    "manager_Name": "737( 445,365 )",
    "Teams": "error404( Duri Tadu )",
    "SXL": "IND",
    "Latp": "35",
    "Player_1": "Raya 3",
    "Player_11": "Haaland 6",
    "Player_10": "Mateta 6",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Andersen 4",
    "Player_14": "Marc Guiu",
    "Player_7": "Saka 5",
    "Player_2": "J.Timber 2",
    "Player_5": "Sarr 1",
    "Player_6": "Enzo 2",
    "Player_3": "Richards 1",
    "Player_4": "Virgil 6",
    "Player_8": "Semenyo 1",
    "Player_9": "Ndiaye 2",
    "Player_15": "Rodon 0"
  },
  {
    "manager_Name": "736( 470,676 )",
    "Teams": "MANCHESTER IS BLUE( PRAYAS BAJGAI )",
    "SXL": "IND",
    "Latp": "56",
    "Player_1": "A.Becker 6",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 13",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Dewsbury-Hall 7",
    "Player_14": "Andersen 4",
    "Player_7": "Semenyo 1",
    "Player_2": "Richards 1",
    "Player_5": "Saka 5",
    "Player_6": "Foden 15",
    "Player_3": "Senesi 2",
    "Player_4": "J.Timber 2",
    "Player_8": "Sarr 1",
    "Player_9": "Mateta 6",
    "Player_15": "Rodon 0"
  },
  {
    "manager_Name": "722( 761,466 )",
    "Teams": "Top Gooner( VibhutiHang Subba )",
    "SXL": "IND",
    "Latp": "29",
    "Player_1": "Raya 3",
    "Player_11": "Mateta 6",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Reijnders 3",
    "Player_14": "Pedro Porro",
    "Player_7": "Semenyo 1",
    "Player_2": "Mukiele 0",
    "Player_5": "Mbeumo 1",
    "Player_6": "Eze 2",
    "Player_3": "Senesi 2",
    "Player_4": "Lacroix 3",
    "Player_8": "Saka 5",
    "Player_9": "Welbeck 2",
    "Player_15": "Rodon 0"
  },
  {
    "manager_Name": "719( 839,201 )",
    "Teams": "Fu\u00DFball-Mannschaft( Gaurav Shrestha )",
    "SXL": "IND",
    "Latp": "79",
    "Player_1": "Kelleher 2",
    "Player_11": "Thiago 13",
    "Player_10": "Haaland 4",
    "Player_12": "Kinsky 0",
    "Player_13": "Reinildo 4",
    "Player_14": "Heaven 0",
    "Player_7": "Rogers 3",
    "Player_2": "Virgil 6",
    "Player_5": "M.Salah 0",
    "Player_6": "Gakpo 14",
    "Player_3": "O\u2019Reilly 4",
    "Player_4": "Cash 6",
    "Player_8": "Foden 15",
    "Player_9": "O.Dango 12",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "715( 970,921 )",
    "Teams": "Comet FC( Pranesh Sharma )",
    "SXL": "IND",
    "Latp": "50",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Haaland 4",
    "Player_10": "Welbeck 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Semenyo 1",
    "Player_14": "Andersen 4",
    "Player_7": "Mbeumo 1",
    "Player_2": "Virgil 6",
    "Player_5": "Saka 5",
    "Player_6": "Ndiaye 2",
    "Player_3": "Cash 6",
    "Player_4": "Senesi 2",
    "Player_8": "Rogers 3",
    "Player_9": "Woltemade 7",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "703( 1,351,741 )",
    "Teams": "Blue Brigade( Bhuman Basnet )",
    "SXL": "IND",
    "Latp": "42",
    "Player_1": "Vicario 1",
    "Player_11": "Thiago 13",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Sarr 1",
    "Player_14": "Calafiori 0",
    "Player_7": "Enzo 2",
    "Player_2": "O\u2019Reilly 4",
    "Player_5": "Semenyo 1",
    "Player_6": "Kudus 8",
    "Player_3": "Gu\u00E9hi 0",
    "Player_4": "Senesi 2",
    "Player_8": "Mbeumo 1",
    "Player_9": "Mateta 6",
    "Player_15": "Tuanzebe 0"
  },
  {
    "manager_Name": "701( 1,423,222 )",
    "Teams": "\u0160e\u0161ko and Destroy( Pema Lepcha )",
    "SXL": "IND",
    "Latp": "42",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Haaland 6",
    "Player_10": "Welbeck 2",
    "Player_12": "Raya 3",
    "Player_13": "Zubimendi 0",
    "Player_14": "Cucurella 1",
    "Player_7": "Semenyo 1",
    "Player_2": "Van de",
    "Player_5": "Gakpo 14",
    "Player_6": "Grealish 2",
    "Player_3": "Senesi 2",
    "Player_4": "Virgil 6",
    "Player_8": "Mbeumo 1",
    "Player_9": "Woltemade 7",
    "Player_15": "Mu\u00F1oz 1"
  },
  {
    "manager_Name": "683( 2,144,319 )",
    "Teams": "ASHLAD FC( Ashim Lama )",
    "SXL": "IND",
    "Latp": "48",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Thiago 13",
    "Player_10": "Haaland 6",
    "Player_12": "Roefs 1",
    "Player_13": "J.Timber 2",
    "Player_14": "Van de",
    "Player_7": "Sarr 1",
    "Player_2": "Senesi 2",
    "Player_5": "Rice 4",
    "Player_6": "Ndiaye 2",
    "Player_3": "Virgil 6",
    "Player_4": "Gvardiol 6",
    "Player_8": "Semenyo 1",
    "Player_9": "Mateta 6",
    "Player_15": "Caicedo -2"
  },
  {
    "manager_Name": "682( 2,202,459 )",
    "Teams": "Liverpool FC( Sunil Rai )",
    "SXL": "IND",
    "Latp": "34",
    "Player_1": "Pope 0",
    "Player_11": "Haaland 6",
    "Player_10": "Woltemade 7",
    "Player_12": "S\u00E1nchez 3",
    "Player_13": "Mu\u00F1oz 1",
    "Player_14": "Jo\u00E3o Pedro",
    "Player_7": "Mbeumo 1",
    "Player_2": "Senesi 2",
    "Player_5": "Van de",
    "Player_6": "Grealish 2",
    "Player_3": "Gvardiol 6",
    "Player_4": "Virgil 6",
    "Player_8": "Minteh 3",
    "Player_9": "Tavernier 1",
    "Player_15": "Enzo 2"
  },
  {
    "manager_Name": "680( 2,286,598 )",
    "Teams": "Lu Lu( Nishant Lohagun )",
    "SXL": "IND",
    "Latp": "42",
    "Player_1": "Raya 3",
    "Player_11": "Mateta 6",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Andersen 4",
    "Player_14": "Reijnders 3",
    "Player_7": "Semenyo 1",
    "Player_2": "Senesi 2",
    "Player_5": "Richards 1",
    "Player_6": "B.Fernandes 11",
    "Player_3": "Virgil 6",
    "Player_4": "Mu\u00F1oz 1",
    "Player_8": "Doku 2",
    "Player_9": "Saka 5",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "680( 2,286,598 )",
    "Teams": "Bruno-nly Fans( Bejoy M Shrestha\u00B2\u2076\u2074 )",
    "SXL": "IND",
    "Latp": "46",
    "Player_1": "Raya 3",
    "Player_11": "Woltemade 7",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "King 5",
    "Player_14": "Van de",
    "Player_7": "Ndiaye 2",
    "Player_2": "Gu\u00E9hi 0",
    "Player_5": "Saka 5",
    "Player_6": "Minteh 3",
    "Player_3": "Virgil 6",
    "Player_4": "Senesi 2",
    "Player_8": "Mbeumo 1",
    "Player_9": "Thiago 13",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "675( 2,533,044 )",
    "Teams": "G\u00CBNJ\u00CF\u00CF UNITED( Pema Bhutia )",
    "SXL": "IND",
    "Latp": "54",
    "Player_1": "Raya 3",
    "Player_11": "Haaland 6",
    "Player_10": "Thiago 13",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Woltemade 7",
    "Player_14": "Richards 1",
    "Player_7": "Semenyo 1",
    "Player_2": "Senesi 2",
    "Player_5": "Minteh 3",
    "Player_6": "Rice 4",
    "Player_3": "Virgil 6",
    "Player_4": "Van de",
    "Player_8": "Mbeumo 1",
    "Player_9": "Foden 15",
    "Player_15": "Alderete 0"
  },
  {
    "manager_Name": "673( 2,604,450 )",
    "Teams": "F.C. ASSASSINS( Kushal Sahota )",
    "SXL": "IND",
    "Latp": "17",
    "Player_1": "Roefs 1",
    "Player_11": "Haaland 6",
    "Player_10": "Welbeck 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Van de",
    "Player_14": "Est\u00E8ve 3",
    "Player_7": "Caicedo -2",
    "Player_2": "Gu\u00E9hi 0",
    "Player_5": "Sarr 1",
    "Player_6": "Mbeumo 1",
    "Player_3": "J.Timber 2",
    "Player_4": "O\u2019Reilly 4",
    "Player_8": "Semenyo 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "King 5"
  },
  {
    "manager_Name": "671( 2,690,700 )",
    "Teams": "PINE( SATYAM RAI )",
    "SXL": "IND",
    "Latp": "33",
    "Player_1": "Raya 3",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta 6",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Mukiele 0",
    "Player_14": "Burn 5",
    "Player_7": "Ndiaye 2",
    "Player_2": "Senesi 2",
    "Player_5": "Rogers 3",
    "Player_6": "Mbeumo 1",
    "Player_3": "Virgil 6",
    "Player_4": "Van de",
    "Player_8": "Semenyo 1",
    "Player_9": "Saka 5",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "664( 3,031,138 )",
    "Teams": "Cheesygarlic( Rishi Thulung )",
    "SXL": "IND",
    "Latp": "25",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Reijnders 3",
    "Player_14": "Mukiele 0",
    "Player_7": "Saka 5",
    "Player_2": "J.Timber 2",
    "Player_5": "Mbeumo 1",
    "Player_6": "Semenyo 1",
    "Player_3": "Tarkowski 3",
    "Player_4": "Senesi 2",
    "Player_8": "Enzo 2",
    "Player_9": "Kroupi.Jr 1",
    "Player_15": "Botman 0"
  },
  {
    "manager_Name": "663( 3,110,711 )",
    "Teams": "Busby Baby( Regean Lama )",
    "SXL": "IND",
    "Latp": "57",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Woltemade 7",
    "Player_10": "Thiago 13",
    "Player_12": "S\u00E1nchez 3",
    "Player_13": "Reijnders 3",
    "Player_14": "Dorgu 1",
    "Player_7": "Mbeumo 1",
    "Player_2": "Van de",
    "Player_5": "Grealish 2",
    "Player_6": "Foden 15",
    "Player_3": "J.Timber 2",
    "Player_4": "Mu\u00F1oz 1",
    "Player_8": "B.Fernandes 11",
    "Player_9": "Haaland 4",
    "Player_15": "Alex Moreno"
  },
  {
    "manager_Name": "657( 3,417,014 )",
    "Teams": "The Regista.( Passang T Sherpa )",
    "SXL": "IND",
    "Latp": "34",
    "Player_1": "Roefs 1",
    "Player_11": "Haaland 6",
    "Player_10": "Thiago 13",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Rice 4",
    "Player_14": "Woltemade 7",
    "Player_7": "Mbeumo 1",
    "Player_2": "Cucurella 1",
    "Player_5": "Keane 2",
    "Player_6": "Grealish 2",
    "Player_3": "O\u2019Reilly 4",
    "Player_4": "Gu\u00E9hi 0",
    "Player_8": "Semenyo 1",
    "Player_9": "Minteh 3",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "649( 3,803,058 )",
    "Teams": "GustavousGooner( Ashish Subba )",
    "SXL": "IND",
    "Latp": "31",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Mateta 6",
    "Player_10": "Haaland 4",
    "Player_12": "S\u00E1nchez 3",
    "Player_13": "Senesi 2",
    "Player_14": "Cullen 2",
    "Player_7": "Saka 5",
    "Player_2": "Gu\u00E9hi 0",
    "Player_5": "Szoboszlai 3",
    "Player_6": "Rice 4",
    "Player_3": "Livramento 2",
    "Player_4": "O\u2019Reilly 4",
    "Player_8": "Semenyo 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "644( 4,076,036 )",
    "Teams": "Imperial Blues( Saurabh Tamang )",
    "SXL": "IND",
    "Latp": "29",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Mateta 6",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Foster 2",
    "Player_14": "Botman 0",
    "Player_7": "Mbeumo 1",
    "Player_2": "J.Timber 2",
    "Player_5": "Doku 2",
    "Player_6": "Semenyo 1",
    "Player_3": "Richards 1",
    "Player_4": "Senesi 2",
    "Player_8": "Ndiaye 2",
    "Player_9": "Saka 5",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "643( 4,115,255 )",
    "Teams": "Native United( Monlom Rongong )",
    "SXL": "IND",
    "Latp": "26",
    "Player_1": "Raya 3",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta 6",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Rodon 0",
    "Player_14": "Gabriel 0",
    "Player_7": "Ndiaye 2",
    "Player_2": "Senesi 2",
    "Player_5": "Caicedo -2",
    "Player_6": "Mbeumo 1",
    "Player_3": "J.Timber 2",
    "Player_4": "Gu\u00E9hi 0",
    "Player_8": "Semenyo 1",
    "Player_9": "Woltemade 7",
    "Player_15": "King 5"
  },
  {
    "manager_Name": "637( 4,428,280 )",
    "Teams": "GODFATHER FC( Riwaj Rai )",
    "SXL": "IND",
    "Latp": "30",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Haaland 4",
    "Player_10": "Isidor 2",
    "Player_12": "Sels 2",
    "Player_13": "Cash 6",
    "Player_14": "Semenyo 1",
    "Player_7": "Caicedo -2",
    "Player_2": "Gu\u00E9hi 0",
    "Player_5": "Kudus 8",
    "Player_6": "O.Dango 12",
    "Player_3": "Cucurella 1",
    "Player_4": "Pedro Porro",
    "Player_8": "Grealish 2",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "632( 4,693,798 )",
    "Teams": "Hooligans25( Pradhyumna Subba )",
    "SXL": "IND",
    "Latp": "24",
    "Player_1": "Raya 3",
    "Player_11": "Haaland 4",
    "Player_10": "Woltemade 7",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Richards 1",
    "Player_14": "Reinildo 4",
    "Player_7": "Sarr 1",
    "Player_2": "Mitchell 1",
    "Player_5": "Neto 2",
    "Player_6": "Mbeumo 1",
    "Player_3": "Van de",
    "Player_4": "J.Timber 2",
    "Player_8": "Eze 2",
    "Player_9": "Ekitik\u00E9 1",
    "Player_15": "Reijnders 3"
  },
  {
    "manager_Name": "628( 4,908,070 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "37",
    "Player_1": "Raya 3",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 13",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Saka 5",
    "Player_2": "Mitchell 1",
    "Player_5": "Mukiele 0",
    "Player_6": "Xhaka 5",
    "Player_3": "Cucurella 1",
    "Player_4": "Senesi 2",
    "Player_8": "Rice 4",
    "Player_9": "L.Paquet\u00E1 -1",
    "Player_15": "L.Miley 15"
  },
  {
    "manager_Name": "605( 6,081,052 )",
    "Teams": "GUNNERS( Omkar Subba )",
    "SXL": "IND",
    "Latp": "43",
    "Player_1": "Raya 3",
    "Player_11": "Thiago 13",
    "Player_10": "Haaland 4",
    "Player_12": "Verbruggen 7",
    "Player_13": "Semenyo 1",
    "Player_14": "Senesi 2",
    "Player_7": "Gravenberch 3",
    "Player_2": "Gu\u00E9hi 0",
    "Player_5": "Mu\u00F1oz 1",
    "Player_6": "Rice 4",
    "Player_3": "Virgil 6",
    "Player_4": "O\u2019Reilly 4",
    "Player_8": "Caicedo -2",
    "Player_9": "Woltemade 7",
    "Player_15": "Anthony 4"
  },
  {
    "manager_Name": "600( 6,313,646 )",
    "Teams": "I_am_done_XI( Dipen Thapa )",
    "SXL": "IND",
    "Latp": "40",
    "Player_1": "Raya 3",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Mateta 6",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Caicedo -2",
    "Player_14": "Senesi 2",
    "Player_7": "M.Salah 0",
    "Player_2": "Gu\u00E9hi 0",
    "Player_5": "Eze 4",
    "Player_6": "Kudus 8",
    "Player_3": "Hincapie 1",
    "Player_4": "Konsa 8",
    "Player_8": "Grealish 2",
    "Player_9": "Woltemade 7",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "595( 6,564,417 )",
    "Teams": "Let MEE COOK( \u00CFaraplang Pompyrthat )",
    "SXL": "IND",
    "Latp": "50",
    "Player_1": "Pope 0",
    "Player_11": "Haaland 6",
    "Player_10": "Woltemade 7",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Xhaka 5",
    "Player_14": "Rodon 0",
    "Player_7": "Rogers 3",
    "Player_2": "J.Timber 2",
    "Player_5": "Mbeumo 1",
    "Player_6": "Foden 15",
    "Player_3": "Senesi 2",
    "Player_4": "Virgil 6",
    "Player_8": "Enzo 2",
    "Player_9": "Mateta 6",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "594( 6,608,869 )",
    "Teams": "Hangkim_0011( ABHINANDAN RAI )",
    "SXL": "IND",
    "Latp": "31",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Welbeck 2",
    "Player_10": "Haaland 4",
    "Player_12": "S\u00E1nchez 3",
    "Player_13": "Burn 5",
    "Player_14": "Semenyo 1",
    "Player_7": "Mbeumo 1",
    "Player_2": "Gu\u00E9hi 0",
    "Player_5": "Neto 2",
    "Player_6": "Doku 2",
    "Player_3": "Est\u00E8ve 3",
    "Player_4": "Digne 7",
    "Player_8": "Szoboszlai 3",
    "Player_9": "Mateta 6",
    "Player_15": "Konsa 8"
  },
  {
    "manager_Name": "567( 7,800,254 )",
    "Teams": "Jorebungalow YFC( Vivek Lama )",
    "SXL": "IND",
    "Latp": "38",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Mateta 6",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Areola 2",
    "Player_13": "L.Miley 15",
    "Player_14": "Trippier 0",
    "Player_7": "Semenyo 1",
    "Player_2": "Calafiori 0",
    "Player_5": "Caicedo -2",
    "Player_6": "Saka 5",
    "Player_3": "Van de",
    "Player_4": "James 8",
    "Player_8": "Gakpo 14",
    "Player_9": "Haaland 4",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "563( 7,968,953 )",
    "Teams": "Boehly Blues( Aditya Bhandari )",
    "SXL": "IND",
    "Latp": "50",
    "Player_1": "Petrovi\u0107 2",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 13",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Senesi 2",
    "Player_14": "Gu\u00E9hi 0",
    "Player_7": "Saka 5",
    "Player_2": "O\u2019Reilly 4",
    "Player_5": "Minteh 3",
    "Player_6": "Enzo 2",
    "Player_3": "James 8",
    "Player_4": "J.Timber 2",
    "Player_8": "Semenyo 1",
    "Player_9": "Mateta 6",
    "Player_15": "Stach 0"
  },
  {
    "manager_Name": "547( 8,565,197 )",
    "Teams": "Invincibles( Bishal Rai )",
    "SXL": "IND",
    "Latp": "46",
    "Player_1": "Raya 3",
    "Player_11": "Mateta 6",
    "Player_10": "Thiago 26",
    "Player_12": "Kinsky 0",
    "Player_13": "Neto 2",
    "Player_14": "Enzo 2",
    "Player_7": "Mbeumo 1",
    "Player_2": "Mu\u00F1oz 1",
    "Player_5": "Milenkovi\u0107 1",
    "Player_6": "Semenyo 1",
    "Player_3": "J.Timber 2",
    "Player_4": "Pedro Porro",
    "Player_8": "Minteh 3",
    "Player_9": "Ekitik\u00E9 1",
    "Player_15": "Gabriel 0"
  }
];