var s = [
  {
    "manager_Name": "820( 1,375,181 ) TotalXfr : 17",
    "Teams": "Erik ten ki Aag( Aditya Desai )",
    "SXL": "India",
    "Latp": "53",
    "Player_1": "Henderson\r 7",
    "Player_11": "Haaland\r 5",
    "Player_10": "Strand Larsen\r 2",
    "Player_12": "Flekken\r 3",
    "Player_13": "Konat\u00E9\r 0",
    "Player_14": "Smith Rowe\r BHA (H)",
    "Player_7": "J.Gomes\r 2",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "B.Fernandes\r 2",
    "Player_6": "Palmer\r 14",
    "Player_3": "Lewis\r 1",
    "Player_4": "Hall\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Jo\u00E3o Pedro\r FUL (A)",
    "Player_15": "Barco\r FUL (A)"
  },
  {
    "manager_Name": "803( 1,902,219 ) TotalXfr : 9",
    "Teams": "Mateta Vada( Amogh Ranadive )",
    "SXL": "India",
    "Latp": "31",
    "Player_1": "Flekken\r 3",
    "Player_11": "Cunha\r 2",
    "Player_10": "Wissa\r 2",
    "Player_12": "S\u00E1nchez\r 0",
    "Player_13": "Rogers\r 8",
    "Player_14": "Garnacho\r 1",
    "Player_7": "Palmer\r 7",
    "Player_2": "Keane\r 0",
    "Player_5": "Alexander-Arnold\r 6",
    "Player_6": "Johnson\r BOU (A)",
    "Player_3": "Gabriel\r 0",
    "Player_4": "Davis\r 2",
    "Player_8": "Mbeumo\r 4",
    "Player_9": "Haaland\r 5",
    "Player_15": "Konsa\r 2"
  },
  {
    "manager_Name": "785( 2,564,759 ) TotalXfr : 11",
    "Teams": "AmPaduDhaan( Aravind SA )",
    "SXL": "India",
    "Latp": "54",
    "Player_1": "Flekken\r 3",
    "Player_11": "Haaland\r 5",
    "Player_10": "Watkins\r 12",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Colwill\r 0",
    "Player_14": "Okoli\r 0",
    "Player_7": "Saka\r 3",
    "Player_2": "Gabriel\r 0",
    "Player_5": "Rogers\r 8",
    "Player_6": "Georginio\r FUL (A)",
    "Player_3": "Van den Berg\r 1",
    "Player_4": "Calafiori\r 0",
    "Player_8": "Palmer\r 14",
    "Player_9": "Gordon\r 8",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "777( 2,880,810 ) TotalXfr : 12",
    "Teams": "Change Name( \u010C\u022B\u0271\u03FB\u04D1\u1D28\u0257\u03AD\u01A6 \u010A\u00F6\u0159\u024D\u0268\u03AC\u1D70\u1E0B\u1E17\u0212 )",
    "SXL": "India",
    "Latp": "63",
    "Player_1": "Flekken\r 3",
    "Player_11": "Wood\r 2",
    "Player_10": "Welbeck\r FUL (A)",
    "Player_12": "S\u00E1nchez\r 0",
    "Player_13": "Smith Rowe\r BHA (H)",
    "Player_14": "Kilman\r 1",
    "Player_7": "Palmer\r 7",
    "Player_2": "Gabriel\r 0",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Saka\r 6",
    "Player_3": "Van den Berg\r 1",
    "Player_4": "Tarkowski\r 7",
    "Player_8": "Rogers\r 8",
    "Player_9": "Isak\r 11",
    "Player_15": "Andersen\r BHA (H)"
  },
  {
    "manager_Name": "769( 3,201,510 ) TotalXfr : 12",
    "Teams": "Lavia ka Baal( The Banat )",
    "SXL": "India",
    "Latp": "30",
    "Player_1": "Sels\r 2",
    "Player_11": "Haaland\r 5",
    "Player_10": "Wood\r 2",
    "Player_12": "Raya\r 6",
    "Player_13": "Dibling\r 0",
    "Player_14": "Faes\r 1",
    "Player_7": "Palmer\r 14",
    "Player_2": "Dalot\r 1",
    "Player_5": "Smith Rowe\r BHA (H)",
    "Player_6": "B.Fernandes\r 2",
    "Player_3": "Pedro Porro\r BOU (A)",
    "Player_4": "Digne\r 2",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "N.Jackson\r 0",
    "Player_15": "Greaves\r 1"
  },
  {
    "manager_Name": "724( 5,049,423 ) TotalXfr : 4",
    "Teams": "RicePlate( Tushar Abhichandani )",
    "SXL": "India",
    "Latp": "59",
    "Player_1": "Raya\r 6",
    "Player_11": "Isak\r 11",
    "Player_10": "Haaland\r 10",
    "Player_12": "Matthews\r 0",
    "Player_13": "Barco\r FUL (A)",
    "Player_14": "Rogers\r 8",
    "Player_7": "Onana\r 0",
    "Player_2": "Pedro Porro\r BOU (A)",
    "Player_5": "Bernardo\r 8",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Gvardiol\r 6",
    "Player_4": "Quansah\r 0",
    "Player_8": "Diogo J.\r 0",
    "Player_9": "Beto\r 0",
    "Player_15": "Robinson\r BHA (H)"
  }
];