var s = [
  {
    "manager_Name": "924( 38,273 ) TotalXfr : 12",
    "Teams": "Humbesi( ~ Kopi ~ )",
    "SXL": "Albania",
    "Latp": "55",
    "Player_1": "Raya 6",
    "Player_11": "Cunha 2",
    "Player_10": "Jo\u00E3o Pedro 5",
    "Player_12": "Fabianski 2",
    "Player_13": "N.Jackson 0",
    "Player_14": "Gabriel 0",
    "Player_7": "Palmer 14",
    "Player_2": "A\u00EFt-Nouri 0",
    "Player_5": "Saka 3",
    "Player_6": "Mbeumo 2",
    "Player_3": "Lewis 1",
    "Player_4": "Greaves 1",
    "Player_8": "M.Salah 18",
    "Player_9": "Semenyo 3",
    "Player_15": "Mykolenko 11"
  },
  {
    "manager_Name": "747( 4,444,298 ) TotalXfr : 14",
    "Teams": "Supercampeones( Ronny Nelkenbaum )",
    "SXL": "France",
    "Latp": "39",
    "Player_1": "Fabianski 2",
    "Player_11": "Haaland 10",
    "Player_10": "Wood 2",
    "Player_12": "Sels 2",
    "Player_13": "Gabriel 0",
    "Player_14": "Colwill 0",
    "Player_7": "Saka 3",
    "Player_2": "Hall 1",
    "Player_5": "Martinelli 3",
    "Player_6": "Palmer 7",
    "Player_3": "A\u00EFt-Nouri 0",
    "Player_4": "Mazraoui 1",
    "Player_8": "Mbeumo 2",
    "Player_9": "Rogers 8",
    "Player_15": "Lankshear 0"
  },
  {
    "manager_Name": "881( 295,020 ) TotalXfr : 15",
    "Teams": "Wiggler FC( Andrew Carr )",
    "SXL": "England",
    "Latp": "61",
    "Player_1": "Henderson 7",
    "Player_11": "Wood 2",
    "Player_10": "Cunha 2",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Pau 0",
    "Player_14": "Lankshear 0",
    "Player_7": "Madueke 13",
    "Player_2": "Gabriel 0",
    "Player_5": "Son 1",
    "Player_6": "M.Salah 18",
    "Player_3": "A\u00EFt-Nouri 0",
    "Player_4": "Lewis 1",
    "Player_8": "Palmer 14",
    "Player_9": "Saka 3",
    "Player_15": "Bednarek 0"
  },
  {
    "manager_Name": "855( 700,436 ) TotalXfr : 16",
    "Teams": "Jelly Flood( Lorin Minxhozi )",
    "SXL": "England",
    "Latp": "67",
    "Player_1": "Verbruggen 1",
    "Player_11": "Cunha 2",
    "Player_10": "Jo\u00E3o Pedro 5",
    "Player_12": "Fabianski 2",
    "Player_13": "N.Jackson 0",
    "Player_14": "Gabriel 0",
    "Player_7": "Mbeumo 2",
    "Player_2": "Davis 2",
    "Player_5": "Saka 3",
    "Player_6": "M.Salah 18",
    "Player_3": "Mykolenko 11",
    "Player_4": "Lewis 1",
    "Player_8": "Palmer 14",
    "Player_9": "Rogers 8",
    "Player_15": "Greaves 1"
  },
  {
    "manager_Name": "794( 2,527,702 ) TotalXfr : 10",
    "Teams": "#SorareMarin( Marin Jano )",
    "SXL": "Albania",
    "Latp": "50",
    "Player_1": "Flekken 3",
    "Player_11": "Haaland 10",
    "Player_10": "Cunha 2",
    "Player_12": "Areola 0",
    "Player_13": "Gabriel 0",
    "Player_14": "A\u00EFt-Nouri 0",
    "Player_7": "Maddison 2",
    "Player_2": "Lewis 1",
    "Player_5": "Palmer 7",
    "Player_6": "Mbeumo 2",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Pedro Porro 1",
    "Player_8": "Rogers 8",
    "Player_9": "Gordon 8",
    "Player_15": "Chiwome 0"
  },
  {
    "manager_Name": "787( 2,796,701 ) TotalXfr : 9",
    "Teams": "Sniper( Florian Toslluku )",
    "SXL": "Albania",
    "Latp": "63",
    "Player_1": "Henderson 7",
    "Player_11": "Archer 2",
    "Player_10": "Haaland 10",
    "Player_12": "Ederson M. 0",
    "Player_13": "Welbeck 0",
    "Player_14": "Mazraoui 1",
    "Player_7": "Thomas 6",
    "Player_2": "Alexander-Arnold 6",
    "Player_5": "Maddison 2",
    "Player_6": "Gordon 8",
    "Player_3": "Alex Moreno 1",
    "Player_4": "Akanji 1",
    "Player_8": "Smith Rowe 2",
    "Player_9": "M.Salah 18",
    "Player_15": "Andersen 0"
  },
  {
    "manager_Name": "815( 1,774,874 ) TotalXfr : 11",
    "Teams": "Data Crisis( Camilla Nurkhanov )",
    "SXL": "England",
    "Latp": "88",
    "Player_1": "Raya 6",
    "Player_11": "Calvert-Lewin 5",
    "Player_10": "Delap 2",
    "Player_12": "Turner 0",
    "Player_13": "McNeil 9",
    "Player_14": "Hall 1",
    "Player_7": "Andreas 3",
    "Player_2": "Gvardiol 6",
    "Player_5": "Young 15",
    "Player_6": "Martinelli 3",
    "Player_3": "Alexander-Arnold 6",
    "Player_4": "Pedro Porro 1",
    "Player_8": "M.Salah 36",
    "Player_9": "Haaland 5",
    "Player_15": "Damsgaard 9"
  },
  {
    "manager_Name": "790( 2,701,040 ) TotalXfr : 15",
    "Teams": "Iwobi Wan-Kenobi( Sunit Patel )",
    "SXL": "England",
    "Latp": "68",
    "Player_1": "Raya 6",
    "Player_11": "Watkins 12",
    "Player_10": "Cunha 2",
    "Player_12": "Fabianski 2",
    "Player_13": "Semenyo 3",
    "Player_14": "Mykolenko 11",
    "Player_7": "M.Salah 18",
    "Player_2": "Lewis 1",
    "Player_5": "Mbeumo 2",
    "Player_6": "Palmer 14",
    "Player_3": "A\u00EFt-Nouri 0",
    "Player_4": "Gvardiol 6",
    "Player_8": "B.Fernandes 2",
    "Player_9": "Jo\u00E3o Pedro 5",
    "Player_15": "Greaves 1"
  },
  {
    "manager_Name": "768( 3,567,436 ) TotalXfr : 12",
    "Teams": "Enter Team Name( teo teo )",
    "SXL": "Italy",
    "Latp": "84",
    "Player_1": "Flekken 3",
    "Player_11": "Watkins 12",
    "Player_10": "Jo\u00E3o Pedro 5",
    "Player_12": "S\u00E1nchez 0",
    "Player_13": "Calvert-Lewin 5",
    "Player_14": "Konsa 2",
    "Player_7": "Rogers 8",
    "Player_2": "Gvardiol 6",
    "Player_5": "Smith Rowe 2",
    "Player_6": "Saka 3",
    "Player_3": "Virgil 1",
    "Player_4": "Lewis 1",
    "Player_8": "Palmer 7",
    "Player_9": "M.Salah 36",
    "Player_15": "Tuanzebe 0"
  },
  {
    "manager_Name": "754( 4,138,060 ) TotalXfr : 9",
    "Teams": "Ibis Warriors( Harmeet Chana )",
    "SXL": "England",
    "Latp": "63",
    "Player_1": "Raya 6",
    "Player_11": "Welbeck 0",
    "Player_10": "Haaland 10",
    "Player_12": "Turner 0",
    "Player_13": "Onana 0",
    "Player_14": "Harwood-Bellis 0",
    "Player_7": "Adama 1",
    "Player_2": "Digne 2",
    "Player_5": "Palmer 7",
    "Player_6": "Smith Rowe 2",
    "Player_3": "Robertson 1",
    "Player_4": "Saliba 15",
    "Player_8": "M.Salah 18",
    "Player_9": "Ra\u00FAl 1",
    "Player_15": "Barco 0"
  },
  {
    "manager_Name": "706( 6,065,103 ) TotalXfr : 5",
    "Teams": "Inceneratori( Geri Muho )",
    "SXL": "USA",
    "Latp": "28",
    "Player_1": "Fabianski 2",
    "Player_11": "Vardy 4",
    "Player_10": "Haaland 10",
    "Player_12": "Ederson M. 0",
    "Player_13": "N.Jackson 0",
    "Player_14": "Greaves 1",
    "Player_7": "Mbeumo 2",
    "Player_2": "A\u00EFt-Nouri 0",
    "Player_5": "Saka 3",
    "Player_6": "B.Fernandes 2",
    "Player_3": "Robertson 1",
    "Player_4": "Lewis 1",
    "Player_8": "Bowen 2",
    "Player_9": "B.Soumar\u00E9 1",
    "Player_15": "Harwood-Bellis 0"
  },
  {
    "manager_Name": "809( 1,980,891 ) TotalXfr : 11",
    "Teams": "Blue Boys \uFFFD( Ilir B )",
    "SXL": "England",
    "Latp": "71",
    "Player_1": "Fabianski 2",
    "Player_11": "Haaland 5",
    "Player_10": "Jo\u00E3o Pedro 5",
    "Player_12": "S\u00E1nchez 0",
    "Player_13": "Winks 0",
    "Player_14": "Keane 0",
    "Player_7": "Mbeumo 2",
    "Player_2": "O\u0027Shea 1",
    "Player_5": "M.Salah 36",
    "Player_6": "Smith Rowe 2",
    "Player_3": "Aina 1",
    "Player_4": "Disasi 8",
    "Player_8": "Palmer 7",
    "Player_9": "Cunha 2",
    "Player_15": "Harwood-Bellis 0"
  },
  {
    "manager_Name": "805( 2,139,596 ) TotalXfr : 15",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "India",
    "Latp": "75",
    "Player_1": "Henderson 7",
    "Player_11": "Cunha 2",
    "Player_10": "Armstrong 1",
    "Player_12": "Fabianski 2",
    "Player_13": "Konat\u00E9 0",
    "Player_14": "W.Fofana 0",
    "Player_7": "M.Salah 18",
    "Player_2": "J.Timber 14",
    "Player_5": "Johnson 2",
    "Player_6": "Saka 6",
    "Player_3": "Faes 1",
    "Player_4": "Saliba 15",
    "Player_8": "Palmer 7",
    "Player_9": "B.Fernandes 2",
    "Player_15": "Wheatley 0"
  },
  {
    "manager_Name": "696( 6,434,279 ) TotalXfr : 5",
    "Teams": "RoboKoop( Enio Minxhozi )",
    "SXL": "Albania",
    "Latp": "56",
    "Player_1": "Fabianski 2",
    "Player_11": "Haaland 10",
    "Player_10": "Watkins 12",
    "Player_12": "Vicario 0",
    "Player_13": "Harwood-Bellis 0",
    "Player_14": "Chiwome 0",
    "Player_7": "Eze 6",
    "Player_2": "Alexander-Arnold 6",
    "Player_5": "Mbeumo 2",
    "Player_6": "Rogers 8",
    "Player_3": "A\u00EFt-Nouri 0",
    "Player_4": "Gvardiol 6",
    "Player_8": "Son 1",
    "Player_9": "Buonanotte 3",
    "Player_15": "A.Phillips 0"
  },
  {
    "manager_Name": "777( 3,207,069 ) TotalXfr : 13",
    "Teams": "Herr Direktor( Roger Shehu )",
    "SXL": "Netherlands",
    "Latp": "59",
    "Player_1": "Fabianski 2",
    "Player_11": "Ra\u00FAl 1",
    "Player_10": "Jo\u00E3o Pedro 5",
    "Player_12": "Jos\u00E9 S\u00E1 0",
    "Player_13": "N.Jackson 0",
    "Player_14": "Robinson 6",
    "Player_7": "Mbeumo 2",
    "Player_2": "A\u00EFt-Nouri 0",
    "Player_5": "Saka 3",
    "Player_6": "M.Salah 18",
    "Player_3": "Mykolenko 11",
    "Player_4": "Davis 2",
    "Player_8": "Palmer 14",
    "Player_9": "Garnacho 1",
    "Player_15": "Bednarek 0"
  },
  {
    "manager_Name": "714( 5,771,288 ) TotalXfr : 12",
    "Teams": "Tokenized Maxi \u26A1\uFE0F( Eni Shtini )",
    "SXL": "Albania",
    "Latp": "38",
    "Player_1": "Martinez 2",
    "Player_11": "Cunha 2",
    "Player_10": "Solanke 2",
    "Player_12": "Fabianski 2",
    "Player_13": "Semenyo 3",
    "Player_14": "Keane 0",
    "Player_7": "Mbeumo 2",
    "Player_2": "Gabriel 0",
    "Player_5": "Rogers 8",
    "Player_6": "B.Fernandes 2",
    "Player_3": "Mazraoui 1",
    "Player_4": "A\u00EFt-Nouri 0",
    "Player_8": "Palmer 14",
    "Player_9": "Haaland 5",
    "Player_15": "Mosquera 0"
  },
  {
    "manager_Name": "710( 5,932,987 ) TotalXfr : 15",
    "Teams": "5-D( Erald Haxhiu )",
    "SXL": "USA",
    "Latp": "31",
    "Player_1": "Onana 2",
    "Player_11": "Haaland 10",
    "Player_10": "Wissa 2",
    "Player_12": "Cahill 0",
    "Player_13": "Welbeck 0",
    "Player_14": "Hall 1",
    "Player_7": "Smith Rowe 2",
    "Player_2": "Lewis 1",
    "Player_5": "Mbeumo 2",
    "Player_6": "Luis D\u00EDaz 1",
    "Player_3": "Alexander-Arnold 6",
    "Player_4": "Pedro Porro 1",
    "Player_8": "Saka 3",
    "Player_9": "Rashford 1",
    "Player_15": "Mykolenko 11"
  },
  {
    "manager_Name": "631( 8,330,852 ) TotalXfr : 15",
    "Teams": "Yaya( Bardhyl Minxhozi )",
    "SXL": "Albania",
    "Latp": "80",
    "Player_1": "Henderson 7",
    "Player_11": "Watkins 12",
    "Player_10": "Mitoma 2",
    "Player_12": "Ederson M. 0",
    "Player_13": "Romero 0",
    "Player_14": "Ferguson 1",
    "Player_7": "Luis D\u00EDaz 1",
    "Player_2": "Saliba 15",
    "Player_5": "Digne 2",
    "Player_6": "Trossard 1",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Robertson 1",
    "Player_8": "M.Salah 36",
    "Player_9": "B.Fernandes 2",
    "Player_15": "Scarlett 0"
  },
  {
    "manager_Name": "713( 5,807,409 ) TotalXfr : 11",
    "Teams": "Kokeqethurit( Daver Berberi )",
    "SXL": "Albania",
    "Latp": "42",
    "Player_1": "Flekken 3",
    "Player_11": "Haaland 10",
    "Player_10": "Wood 2",
    "Player_12": "Raya 6",
    "Player_13": "Gabriel 0",
    "Player_14": "Welbeck 0",
    "Player_7": "Mbeumo 2",
    "Player_2": "Lewis 1",
    "Player_5": "Gvardiol 6",
    "Player_6": "Rogers 8",
    "Player_3": "A\u00EFt-Nouri 0",
    "Player_4": "Hall 1",
    "Player_8": "Palmer 7",
    "Player_9": "Smith Rowe 2",
    "Player_15": "McNeil 9"
  },
  {
    "manager_Name": "676( 7,124,630 ) TotalXfr : 13",
    "Teams": "Leftisti( Magi Muco )",
    "SXL": "Albania",
    "Latp": "47",
    "Player_1": "Areola 0",
    "Player_11": "Strand Larsen 2",
    "Player_10": "Haaland 10",
    "Player_12": "S\u00E1nchez 0",
    "Player_13": "Adama 1",
    "Player_14": "Hall 1",
    "Player_7": "Luis D\u00EDaz 1",
    "Player_2": "Faes 1",
    "Player_5": "Madueke 13",
    "Player_6": "Palmer 7",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Lewis 1",
    "Player_8": "McNeil 9",
    "Player_9": "Havertz 2",
    "Player_15": "Quansah 0"
  }
];