var s = [
  {
    "manager_Name": "961( 3,213 ) TotalXfr : 12",
    "Teams": "Gunners 24( Suumit Bhardwaj )",
    "SXL": "India",
    "Latp": "60",
    "Player_1": "Raya\r 6",
    "Player_11": "Strand Larsen\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 5",
    "Player_12": "Flekken\r 3",
    "Player_13": "Wissa\r 2",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Saka\r 3",
    "Player_2": "Robinson\r 6",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Mitoma\r 2",
    "Player_3": "Virgil\r 1",
    "Player_4": "Lewis\r 1",
    "Player_8": "Palmer\r 14",
    "Player_9": "Bowen\r 2",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "931( 25,583 ) TotalXfr : 13",
    "Teams": "YoroOYoro( Rajdeep Gupta )",
    "SXL": "India",
    "Latp": "59",
    "Player_1": "Raya\r 6",
    "Player_11": "Jo\u00E3o Pedro\r 5",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "N.Jackson\r 0",
    "Player_14": "Burgess\r 0",
    "Player_7": "Rogers\r 8",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Palmer\r 14",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Hall\r 1",
    "Player_4": "Gabriel\r 0",
    "Player_8": "Saka\r 3",
    "Player_9": "B.Fernandes\r 2",
    "Player_15": "Colwill\r 0"
  },
  {
    "manager_Name": "895( 165,013 ) TotalXfr : 16",
    "Teams": "DangerDon( Rohit Nate )",
    "SXL": "India",
    "Latp": "65",
    "Player_1": "Flekken\r 3",
    "Player_11": "Haaland\r 5",
    "Player_10": "Jo\u00E3o Pedro\r 5",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "McNeil\r 9",
    "Player_14": "Hall\r 1",
    "Player_7": "Rogers\r 8",
    "Player_2": "Faes\r 1",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Palmer\r 14",
    "Player_3": "Robinson\r 6",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Saka\r 3",
    "Player_9": "Strand Larsen\r 2",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "885( 250,112 ) TotalXfr : 13",
    "Teams": "Dwiz Mania( Dhawal Toppo )",
    "SXL": "India",
    "Latp": "65",
    "Player_1": "Raya\r 6",
    "Player_11": "Strand Larsen\r 2",
    "Player_10": "Luis D\u00EDaz\r 1",
    "Player_12": "Henderson\r 7",
    "Player_13": "N.Jackson\r 0",
    "Player_14": "Welbeck\r 0",
    "Player_7": "Palmer\r 7",
    "Player_2": "Gvardiol\r 6",
    "Player_5": "Aina\r 1",
    "Player_6": "Digne\r 2",
    "Player_3": "Pedro Porro\r 1",
    "Player_4": "Virgil\r 1",
    "Player_8": "M.Salah\r 36",
    "Player_9": "Mbeumo\r 2",
    "Player_15": "Iwobi\r 15"
  },
  {
    "manager_Name": "881( 292,037 ) TotalXfr : 16",
    "Teams": "Gooner_Psy( Saiprasad Shankar )",
    "SXL": "India",
    "Latp": "49",
    "Player_1": "Verbruggen\r 1",
    "Player_11": "Jo\u00E3o Pedro\r 5",
    "Player_10": "Cunha\r 2",
    "Player_12": "S\u00E1nchez\r 0",
    "Player_13": "Neto\r 0",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Garnacho\r 1",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Saka\r 3",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Digne\r 2",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Palmer\r 14",
    "Player_9": "Wissa\r 2",
    "Player_15": "Hall\r 1"
  },
  {
    "manager_Name": "880( 307,104 ) TotalXfr : 18",
    "Teams": "amp( Aditya Patil )",
    "SXL": "India",
    "Latp": "73",
    "Player_1": "Onana\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 5",
    "Player_10": "Wissa\r 2",
    "Player_12": "Flekken\r 3",
    "Player_13": "Gabriel\r 0",
    "Player_14": "Archer\r 2",
    "Player_7": "Palmer\r 7",
    "Player_2": "Hall\r 1",
    "Player_5": "M.Salah\r 36",
    "Player_6": "Saka\r 3",
    "Player_3": "Gvardiol\r 6",
    "Player_4": "Lewis\r 1",
    "Player_8": "Johnson\r 2",
    "Player_9": "Rogers\r 8",
    "Player_15": "Quansah\r 0"
  },
  {
    "manager_Name": "876( 346,998 ) TotalXfr : 14",
    "Teams": "Kishore\u2019s Rascals( Nandakishore K )",
    "SXL": "India",
    "Latp": "68",
    "Player_1": "Flekken\r 3",
    "Player_11": "Haaland\r 5",
    "Player_10": "Jo\u00E3o Pedro\r 5",
    "Player_12": "Fabianski\r 2",
    "Player_13": "B.Fernandes\r 2",
    "Player_14": "Van den Berg\r 1",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Saliba\r 15",
    "Player_5": "Rogers\r 8",
    "Player_6": "Palmer\r 14",
    "Player_3": "Mykolenko\r 11",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Saka\r 3",
    "Player_9": "Strand Larsen\r 2",
    "Player_15": "Greaves\r 1"
  },
  {
    "manager_Name": "875( 358,879 ) TotalXfr : 10",
    "Teams": "Deys Knights( Rohan Dey )",
    "SXL": "India",
    "Latp": "73",
    "Player_1": "Henderson\r 7",
    "Player_11": "Cunha\r 2",
    "Player_10": "Havertz\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Rogers\r 8",
    "Player_14": "Konsa\r 2",
    "Player_7": "Palmer\r 7",
    "Player_2": "Robinson\r 6",
    "Player_5": "M.Salah\r 36",
    "Player_6": "Saka\r 3",
    "Player_3": "Gvardiol\r 6",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Smith Rowe\r 2",
    "Player_9": "Solanke\r 2",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "868( 457,132 ) TotalXfr : 9",
    "Teams": "Narayan Narayan!( Rakeshlal Gopiram nathani )",
    "SXL": "India",
    "Latp": "43",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Evanilson\r 2",
    "Player_10": "Haaland\r 10",
    "Player_12": "Lumley\r 2",
    "Player_13": "N.Jackson\r 0",
    "Player_14": "Harwood-Bellis\r 0",
    "Player_7": "Amad\r 1",
    "Player_2": "Pedro Porro\r 1",
    "Player_5": "Emerson\r 1",
    "Player_6": "Saka\r 3",
    "Player_3": "Robertson\r 1",
    "Player_4": "Gvardiol\r 6",
    "Player_8": "McNeil\r 9",
    "Player_9": "Palmer\r 7",
    "Player_15": "Dibling\r 0"
  },
  {
    "manager_Name": "868( 460,325 ) TotalXfr : 14",
    "Teams": "RED_DEVils_XI( Devraj Redkar )",
    "SXL": "England",
    "Latp": "63",
    "Player_1": "Raya\r 6",
    "Player_11": "Wood\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Sels\r 2",
    "Player_13": "N.Jackson\r 0",
    "Player_14": "Robinson\r 6",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Gvardiol\r 6",
    "Player_5": "Mitoma\r 2",
    "Player_6": "Rogers\r 8",
    "Player_3": "Faes\r 1",
    "Player_4": "Emerson\r 1",
    "Player_8": "Palmer\r 14",
    "Player_9": "Saka\r 3",
    "Player_15": "Konsa\r 2"
  },
  {
    "manager_Name": "865( 513,829 ) TotalXfr : 14",
    "Teams": "Banter FC( Johann Duckworth )",
    "SXL": "India",
    "Latp": "73",
    "Player_1": "Flekken\r 3",
    "Player_11": "Cunha\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 5",
    "Player_12": "Ward\r 0",
    "Player_13": "N.Jackson\r 0",
    "Player_14": "Hall\r 1",
    "Player_7": "M.Salah\r 18",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Palmer\r 14",
    "Player_6": "Rogers\r 8",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Mykolenko\r 11",
    "Player_8": "Saka\r 3",
    "Player_9": "Semenyo\r 3",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "860( 602,400 ) TotalXfr : 16",
    "Teams": "FALSE 9( Rohan Rai )",
    "SXL": "India",
    "Latp": "57",
    "Player_1": "Fabianski\r 2",
    "Player_11": "N.Jackson\r 0",
    "Player_10": "Cunha\r 2",
    "Player_12": "Henderson\r 7",
    "Player_13": "Welbeck\r 0",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Digne\r 2",
    "Player_5": "Palmer\r 14",
    "Player_6": "Saka\r 3",
    "Player_3": "Colwill\r 0",
    "Player_4": "Robinson\r 6",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Rogers\r 8",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "857( 648,226 ) TotalXfr : 13",
    "Teams": "kalafiori( Adarsh Pakala )",
    "SXL": "Hong Kong",
    "Latp": "59",
    "Player_1": "Raya\r 6",
    "Player_11": "Delap\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 5",
    "Player_12": "S\u00E1nchez\r 0",
    "Player_13": "Keane\r 0",
    "Player_14": "Andersen\r 0",
    "Player_7": "Palmer\r 7",
    "Player_2": "Gabriel\r 0",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Smith Rowe\r 2",
    "Player_3": "Van Hecke\r 1",
    "Player_4": "Virgil\r 1",
    "Player_8": "Saka\r 6",
    "Player_9": "Isak\r 11",
    "Player_15": "Dibling\r 0"
  },
  {
    "manager_Name": "857( 657,229 ) TotalXfr : 14",
    "Teams": "Holding Ream Cash( Karan Thorat )",
    "SXL": "India",
    "Latp": "66",
    "Player_1": "Raya\r 6",
    "Player_11": "Cunha\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 5",
    "Player_12": "Muric\r 2",
    "Player_13": "N.Jackson\r 0",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Semenyo\r 3",
    "Player_2": "Mykolenko\r 11",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Saka\r 3",
    "Player_3": "Lewis\r 1",
    "Player_4": "Greaves\r 1",
    "Player_8": "Palmer\r 14",
    "Player_9": "B.Fernandes\r 2",
    "Player_15": "Hall\r 1"
  },
  {
    "manager_Name": "857( 659,256 ) TotalXfr : 16",
    "Teams": "Change Name( Puneet Gupta )",
    "SXL": "India",
    "Latp": "73",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Haaland\r 5",
    "Player_10": "Strand Larsen\r 2",
    "Player_12": "Sels\r 2",
    "Player_13": "Amad\r 1",
    "Player_14": "Keane\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "J.Timber\r 14",
    "Player_5": "Rogers\r 8",
    "Player_6": "Saka\r 3",
    "Player_3": "Hall\r 1",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Palmer\r 14",
    "Player_9": "Jo\u00E3o Pedro\r 5",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "854( 714,169 ) TotalXfr : 14",
    "Teams": "lakaka( Kabeer Bhagat )",
    "SXL": "India",
    "Latp": "51",
    "Player_1": "Flekken\r 3",
    "Player_11": "Wissa\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 5",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Smith Rowe\r 2",
    "Player_14": "Burgess\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Saka\r 3",
    "Player_6": "Palmer\r 14",
    "Player_3": "Van den Berg\r 1",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "B.Fernandes\r 2",
    "Player_9": "Cunha\r 2",
    "Player_15": "Konsa\r 2"
  },
  {
    "manager_Name": "854( 714,169 ) TotalXfr : 14",
    "Teams": "WengerBoys( Sanket Marwah )",
    "SXL": "India",
    "Latp": "76",
    "Player_1": "Pope\r 0",
    "Player_11": "Watkins\r 12",
    "Player_10": "Wood\r 2",
    "Player_12": "Areola\r 0",
    "Player_13": "Rogers\r 8",
    "Player_14": "Harwood-Bellis\r 0",
    "Player_7": "Johnson\r 2",
    "Player_2": "Pedro Porro\r 1",
    "Player_5": "Palmer\r 7",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Gvardiol\r 6",
    "Player_4": "Robinson\r 6",
    "Player_8": "M.Salah\r 36",
    "Player_9": "Cunha\r 2",
    "Player_15": "Okoli\r 0"
  },
  {
    "manager_Name": "853( 728,577 ) TotalXfr : 12",
    "Teams": "kopside( Hemanth SD )",
    "SXL": "India",
    "Latp": "58",
    "Player_1": "Flekken\r 3",
    "Player_11": "Ra\u00FAl\r 1",
    "Player_10": "Wood\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Colwill\r 0",
    "Player_14": "Solanke\r 2",
    "Player_7": "Palmer\r 14",
    "Player_2": "Virgil\r 1",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Rogers\r 8",
    "Player_3": "Gvardiol\r 6",
    "Player_4": "Pedro Porro\r 1",
    "Player_8": "Mitoma\r 2",
    "Player_9": "M.Salah\r 18",
    "Player_15": "Gabriel\r 0"
  },
  {
    "manager_Name": "850( 795,447 ) TotalXfr : 12",
    "Teams": "GoonerXI( Siddharth Kamath )",
    "SXL": "USA",
    "Latp": "39",
    "Player_1": "Flekken\r 3",
    "Player_11": "Wood\r 2",
    "Player_10": "Welbeck\r 0",
    "Player_12": "Turner\r 0",
    "Player_13": "Winks\r 0",
    "Player_14": "Barco\r 0",
    "Player_7": "Saka\r 6",
    "Player_2": "Gabriel\r 0",
    "Player_5": "J.Gomes\r 2",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Hall\r 1",
    "Player_4": "Wan-Bissaka\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Haaland\r 5",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "843( 957,803 ) TotalXfr : 12",
    "Teams": "Predators( Ruchik Shirode )",
    "SXL": "India",
    "Latp": "64",
    "Player_1": "Onana\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 5",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Evanilson\r 2",
    "Player_14": "Colwill\r 0",
    "Player_7": "B.Fernandes\r 2",
    "Player_2": "Hall\r 1",
    "Player_5": "Semenyo\r 3",
    "Player_6": "Saka\r 3",
    "Player_3": "J.Timber\r 14",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Palmer\r 14",
    "Player_9": "M.Salah\r 18",
    "Player_15": "Milenkovi\u0107\r 0"
  },
  {
    "manager_Name": "842( 977,723 ) TotalXfr : 13",
    "Teams": "Va Va Voom( Piyush R )",
    "SXL": "USA",
    "Latp": "67",
    "Player_1": "Flekken\r 3",
    "Player_11": "Wood\r 2",
    "Player_10": "Solanke\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Keane\r 0",
    "Player_14": "Rogers\r 8",
    "Player_7": "Smith Rowe\r 2",
    "Player_2": "Gabriel\r 0",
    "Player_5": "M.Salah\r 36",
    "Player_6": "Saka\r 3",
    "Player_3": "Gvardiol\r 6",
    "Player_4": "Konat\u00E9\r 0",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Isak\r 11",
    "Player_15": "Van de Ven\r 0"
  },
  {
    "manager_Name": "842( 982,612 ) TotalXfr : 12",
    "Teams": "Arsenal( Kunal Modi )",
    "SXL": "India",
    "Latp": "55",
    "Player_1": "Henderson\r 7",
    "Player_11": "Wood\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 5",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Dibling\r 0",
    "Player_14": "Gabriel\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Wan-Bissaka\r 1",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Rogers\r 8",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Saka\r 6",
    "Player_9": "Haaland\r 5",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "841( 1,012,320 ) TotalXfr : 14",
    "Teams": "Don\u2019t Jimmy Me Jules( Raunak Lamsal )",
    "SXL": "Nepal",
    "Latp": "60",
    "Player_1": "Raya\r 6",
    "Player_11": "Cunha\r 2",
    "Player_10": "Wissa\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Rogers\r 8",
    "Player_14": "Gabriel\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Mykolenko\r 11",
    "Player_5": "Saka\r 6",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Lewis\r 1",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Palmer\r 7",
    "Player_9": "Jo\u00E3o Pedro\r 5",
    "Player_15": "Greaves\r 1"
  },
  {
    "manager_Name": "836( 1,138,624 ) TotalXfr : 14",
    "Teams": "Jaanbaaz Shikari( Saurabh Mittal )",
    "SXL": "India",
    "Latp": "48",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Delap\r 2",
    "Player_10": "Wissa\r 2",
    "Player_12": "Henderson\r 7",
    "Player_13": "Wood\r 2",
    "Player_14": "Gabriel\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Virgil\r 1",
    "Player_5": "Smith Rowe\r 2",
    "Player_6": "Saka\r 3",
    "Player_3": "Aina\r 1",
    "Player_4": "Lewis\r 1",
    "Player_8": "Maddison\r 2",
    "Player_9": "Palmer\r 14",
    "Player_15": "Greaves\r 1"
  },
  {
    "manager_Name": "833( 1,226,294 ) TotalXfr : 13",
    "Teams": "Blistering Barnacles( Sushanta Mondal )",
    "SXL": "India",
    "Latp": "60",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Havertz\r 2",
    "Player_12": "Flekken\r 3",
    "Player_13": "Rogers\r 8",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Saka\r 3",
    "Player_2": "Mykolenko\r 11",
    "Player_5": "Mitoma\r 2",
    "Player_6": "M.Salah\r 18",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Lewis\r 1",
    "Player_8": "Palmer\r 14",
    "Player_9": "Jo\u00E3o Pedro\r 5",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "832( 1,265,210 ) TotalXfr : 17",
    "Teams": "Kounde Bhajji( Ronak Kapadia )",
    "SXL": "India",
    "Latp": "66",
    "Player_1": "Verbruggen\r 1",
    "Player_11": "Wissa\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Jo\u00E3o Pedro\r 5",
    "Player_14": "Burgess\r 0",
    "Player_7": "Saka\r 3",
    "Player_2": "J.Timber\r 14",
    "Player_5": "M.Salah\r 18",
    "Player_6": "B.Fernandes\r 2",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Udogie\r 2",
    "Player_8": "Rogers\r 8",
    "Player_9": "Palmer\r 14",
    "Player_15": "Colwill\r 0"
  },
  {
    "manager_Name": "831( 1,283,412 ) TotalXfr : 14",
    "Teams": "Ashburton Grove FC( Zafar Khan )",
    "SXL": "India",
    "Latp": "54",
    "Player_1": "S\u00E1nchez\r 0",
    "Player_11": "Welbeck\r 0",
    "Player_10": "Cunha\r 2",
    "Player_12": "Ward\r 0",
    "Player_13": "N.Jackson\r 0",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Palmer\r 14",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Robinson\r 6",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Saka\r 3",
    "Player_9": "Rogers\r 8",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "831( 1,292,650 ) TotalXfr : 18",
    "Teams": "miskharege fc( Jordan D\u0027Almeida )",
    "SXL": "India",
    "Latp": "59",
    "Player_1": "Flekken\r 3",
    "Player_11": "Cunha\r 2",
    "Player_10": "Semenyo\r 3",
    "Player_12": "Fabianski\r 2",
    "Player_13": "N.Jackson\r 0",
    "Player_14": "Keane\r 0",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Virgil\r 1",
    "Player_5": "Greaves\r 1",
    "Player_6": "Saka\r 3",
    "Player_3": "Mazraoui\r 1",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Palmer\r 7",
    "Player_9": "M.Salah\r 36",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "830( 1,312,204 ) TotalXfr : 14",
    "Teams": "AK59( Atul Kasbekar )",
    "SXL": "India",
    "Latp": "61",
    "Player_1": "Raya\r 6",
    "Player_11": "Evanilson\r 2",
    "Player_10": "Watkins\r 12",
    "Player_12": "Sels\r 2",
    "Player_13": "McNeil\r 9",
    "Player_14": "Murillo\r 0",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Gvardiol\r 6",
    "Player_5": "Maddison\r 2",
    "Player_6": "Palmer\r 14",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Robinson\r 6",
    "Player_8": "Saka\r 3",
    "Player_9": "Strand Larsen\r 2",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "829( 1,355,034 ) TotalXfr : 21",
    "Teams": "XGALX( Dhearika Ramadhanty )",
    "SXL": "Indonesia",
    "Latp": "76",
    "Player_1": "Raya\r 6",
    "Player_11": "Ra\u00FAl\r 1",
    "Player_10": "Cunha\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Welbeck\r 0",
    "Player_14": "Keane\r 0",
    "Player_7": "B.Fernandes\r 2",
    "Player_2": "Young\r 15",
    "Player_5": "Palmer\r 7",
    "Player_6": "Saka\r 3",
    "Player_3": "Pedro Porro\r 1",
    "Player_4": "Wan-Bissaka\r 1",
    "Player_8": "Johnson\r 2",
    "Player_9": "M.Salah\r 36",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "828( 1,375,646 ) TotalXfr : 16",
    "Teams": "Danzig( Engelbert Dsilva )",
    "SXL": "Chinese Taipei",
    "Latp": "58",
    "Player_1": "Henderson\r 7",
    "Player_11": "Cunha\r 4",
    "Player_10": "Wissa\r 2",
    "Player_12": "S\u00E1nchez\r 0",
    "Player_13": "Neto\r 0",
    "Player_14": "Faes\r 1",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Pedro Porro\r 1",
    "Player_5": "Saka\r 3",
    "Player_6": "Rogers\r 8",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Emerson\r 1",
    "Player_8": "McNeil\r 9",
    "Player_9": "Haaland\r 5",
    "Player_15": "Hall\r 1"
  },
  {
    "manager_Name": "828( 1,383,407 ) TotalXfr : 19",
    "Teams": "Captain\u00D8( Jebarwocky JD )",
    "SXL": "USA",
    "Latp": "46",
    "Player_1": "S\u00E1nchez\r 0",
    "Player_11": "Cunha\r 2",
    "Player_10": "Wood\r 2",
    "Player_12": "Ramsdale\r 0",
    "Player_13": "Welbeck\r 0",
    "Player_14": "Faes\r 1",
    "Player_7": "Palmer\r 14",
    "Player_2": "Wan-Bissaka\r 1",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Aina\r 1",
    "Player_8": "Saka\r 3",
    "Player_9": "\u00D8degaard\r 3",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "827( 1,405,796 ) TotalXfr : 14",
    "Teams": "Sakalicous( Sachin thakur )",
    "SXL": "India",
    "Latp": "40",
    "Player_1": "Kelleher\r 2",
    "Player_11": "Haaland\r 10",
    "Player_10": "Jo\u00E3o Pedro\r 5",
    "Player_12": "Sels\r 2",
    "Player_13": "Lavia\r 0",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Saka\r 3",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Palmer\r 7",
    "Player_6": "Johnson\r 2",
    "Player_3": "Gvardiol\r 6",
    "Player_4": "Aina\r 1",
    "Player_8": "Smith Rowe\r 2",
    "Player_9": "Cunha\r 2",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "827( 1,411,005 ) TotalXfr : 17",
    "Teams": "PCsHWGA11( Prabal Chandran )",
    "SXL": "India",
    "Latp": "70",
    "Player_1": "Kelleher\r 2",
    "Player_11": "Wood\r 2",
    "Player_10": "Wissa\r 2",
    "Player_12": "Martinez\r 2",
    "Player_13": "Keane\r 0",
    "Player_14": "Veltman\r 0",
    "Player_7": "Gordon\r 8",
    "Player_2": "Pedro Porro\r 1",
    "Player_5": "M.Salah\r 36",
    "Player_6": "Saka\r 3",
    "Player_3": "Emerson\r 1",
    "Player_4": "Virgil\r 1",
    "Player_8": "Maddison\r 2",
    "Player_9": "Watkins\r 12",
    "Player_15": "Garnacho\r 1"
  },
  {
    "manager_Name": "826( 1,439,177 ) TotalXfr : 18",
    "Teams": "Mushrooms of Europe( Nicholas Neyt )",
    "SXL": "Belgium",
    "Latp": "57",
    "Player_1": "Henderson\r 7",
    "Player_11": "Ra\u00FAl\r 1",
    "Player_10": "Cunha\r 2",
    "Player_12": "S\u00E1nchez\r 0",
    "Player_13": "Isak\r 11",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Saka\r 3",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Palmer\r 14",
    "Player_3": "Lewis\r 1",
    "Player_4": "Hall\r 1",
    "Player_8": "Rogers\r 8",
    "Player_9": "Mbeumo\r 2",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "823( 1,535,537 ) TotalXfr : 19",
    "Teams": "Emile\u0027s Mitron( Rohit Nair )",
    "SXL": "India",
    "Latp": "70",
    "Player_1": "Raya\r 6",
    "Player_11": "Cunha\r 2",
    "Player_10": "Wood\r 2",
    "Player_12": "Ramsdale\r 0",
    "Player_13": "Welbeck\r 0",
    "Player_14": "Aina\r 1",
    "Player_7": "Palmer\r 7",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Saka\r 3",
    "Player_3": "Virgil\r 1",
    "Player_4": "Van den Berg\r 1",
    "Player_8": "M.Salah\r 36",
    "Player_9": "McNeil\r 9",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "822( 1,547,062 ) TotalXfr : 13",
    "Teams": "RYSing Red Devils( Rikin Shah )",
    "SXL": "India",
    "Latp": "61",
    "Player_1": "Henderson\r 7",
    "Player_11": "Cunha\r 4",
    "Player_10": "Vardy\r 4",
    "Player_12": "Turner\r 0",
    "Player_13": "N.Jackson\r 0",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Saka\r 3",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Palmer\r 7",
    "Player_6": "Smith Rowe\r 2",
    "Player_3": "Robinson\r 6",
    "Player_4": "Virgil\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Rogers\r 8",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "822( 1,563,247 ) TotalXfr : 15",
    "Teams": "Amigo\u0027s_13( Rakesh Dake )",
    "SXL": "India",
    "Latp": "68",
    "Player_1": "Flekken\r 3",
    "Player_11": "Havertz\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 5",
    "Player_12": "Turner\r 0",
    "Player_13": "Strand Larsen\r 2",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Johnson\r 2",
    "Player_2": "Kerkez\r 8",
    "Player_5": "Schade\r 5",
    "Player_6": "Saka\r 6",
    "Player_3": "Mu\u00F1oz\r 6",
    "Player_4": "Gvardiol\r 6",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Palmer\r 7",
    "Player_15": "Aina\r 1"
  },
  {
    "manager_Name": "821( 1,578,737 ) TotalXfr : 12",
    "Teams": "AlibagFC( ONKAR POSANE )",
    "SXL": "India",
    "Latp": "44",
    "Player_1": "Pope\r 0",
    "Player_11": "Cunha\r 2",
    "Player_10": "Solanke\r 2",
    "Player_12": "Pickford\r 6",
    "Player_13": "Welbeck\r 0",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Bowen\r 2",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Gvardiol\r 6",
    "Player_6": "B.Fernandes\r 2",
    "Player_3": "Digne\r 2",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Mbeumo\r 4",
    "Player_9": "M.Salah\r 18",
    "Player_15": "Smith Rowe\r 2"
  },
  {
    "manager_Name": "820( 1,613,937 ) TotalXfr : 12",
    "Teams": "SakaWakaXI( Deepti D )",
    "SXL": "India",
    "Latp": "58",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Wood\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "S\u00E1nchez\r 0",
    "Player_13": "Rogers\r 8",
    "Player_14": "Gabriel\r 0",
    "Player_7": "Saka\r 3",
    "Player_2": "Lewis\r 1",
    "Player_5": "M.Salah\r 36",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Hall\r 1",
    "Player_4": "Justin\r 2",
    "Player_8": "Smith Rowe\r 2",
    "Player_9": "Jo\u00E3o Pedro\r 5",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "820( 1,629,263 ) TotalXfr : 17",
    "Teams": "CannonXI( rohith engu )",
    "SXL": "USA",
    "Latp": "62",
    "Player_1": "Henderson\r 7",
    "Player_11": "Cunha\r 2",
    "Player_10": "Haaland\r 10",
    "Player_12": "Raya\r 6",
    "Player_13": "Gabriel\r 0",
    "Player_14": "Welbeck\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Cucurella\r 2",
    "Player_5": "Faes\r 1",
    "Player_6": "Saka\r 3",
    "Player_3": "Pinnock\r 0",
    "Player_4": "Gu\u00E9hi\r 6",
    "Player_8": "Rogers\r 8",
    "Player_9": "Enzo\r 5",
    "Player_15": "Winks\r 0"
  },
  {
    "manager_Name": "819( 1,651,602 ) TotalXfr : 14",
    "Teams": "TYSM11( Tasdique Yasin )",
    "SXL": "India",
    "Latp": "56",
    "Player_1": "Flekken\r 3",
    "Player_11": "Cunha\r 2",
    "Player_10": "Vardy\r 4",
    "Player_12": "Sels\r 2",
    "Player_13": "Welbeck\r 0",
    "Player_14": "Mazraoui\r 1",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Aina\r 1",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Palmer\r 14",
    "Player_3": "Robinson\r 6",
    "Player_4": "Robertson\r 1",
    "Player_8": "Saka\r 3",
    "Player_9": "Smith Rowe\r 2",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "819( 1,663,326 ) TotalXfr : 18",
    "Teams": "Bear XI( Adi Patil )",
    "SXL": "India",
    "Latp": "57",
    "Player_1": "Raya\r 6",
    "Player_11": "Wood\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Archer\r 2",
    "Player_14": "Konsa\r 2",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Aina\r 1",
    "Player_5": "Johnson\r 2",
    "Player_6": "Saka\r 3",
    "Player_3": "Robinson\r 6",
    "Player_4": "Lewis\r 1",
    "Player_8": "Palmer\r 14",
    "Player_9": "B.Fernandes\r 2",
    "Player_15": "Konat\u00E9\r 0"
  },
  {
    "manager_Name": "818( 1,688,887 ) TotalXfr : 16",
    "Teams": "Jurgen\u0027s Kop( Prathamesh Manjrekar )",
    "SXL": "India",
    "Latp": "47",
    "Player_1": "Verbruggen\r 1",
    "Player_11": "Delap\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Flekken\r 3",
    "Player_13": "N.Jackson\r 0",
    "Player_14": "Faes\r 1",
    "Player_7": "Palmer\r 14",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Saka\r 3",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Pedro Porro\r 1",
    "Player_4": "Lewis\r 1",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Smith Rowe\r 2",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "818( 1,692,071 ) TotalXfr : 15",
    "Teams": "Space Invader( Amar Chandramohan )",
    "SXL": "India",
    "Latp": "53",
    "Player_1": "Raya\r 6",
    "Player_11": "Jo\u00E3o Pedro\r 5",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Gabriel\r 0",
    "Player_14": "Aina\r 1",
    "Player_7": "Bowen\r 2",
    "Player_2": "Van den Berg\r 1",
    "Player_5": "Saka\r 3",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Gomez\r 1",
    "Player_4": "Davis\r 2",
    "Player_8": "Buonanotte\r 3",
    "Player_9": "Haaland\r 10",
    "Player_15": "Dibling\r 0"
  },
  {
    "manager_Name": "816( 1,764,359 ) TotalXfr : 20",
    "Teams": "Shadows FC( Altab Rahi )",
    "SXL": "India",
    "Latp": "70",
    "Player_1": "Kelleher\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 5",
    "Player_10": "Cunha\r 2",
    "Player_12": "Sels\r 2",
    "Player_13": "Mbeumo\r 2",
    "Player_14": "Milenkovi\u0107\r 0",
    "Player_7": "Saka\r 3",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Rogers\r 8",
    "Player_6": "M.Salah\r 18",
    "Player_3": "J.Timber\r 14",
    "Player_4": "Davis\r 2",
    "Player_8": "Palmer\r 14",
    "Player_9": "Wood\r 2",
    "Player_15": "Robinson\r 6"
  },
  {
    "manager_Name": "815( 1,774,874 ) TotalXfr : 12",
    "Teams": "Here for Beer( Gaurav K )",
    "SXL": "India",
    "Latp": "46",
    "Player_1": "Henderson\r 7",
    "Player_11": "Wood\r 2",
    "Player_10": "N.Jackson\r 0",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Gabriel\r 0",
    "Player_14": "Dibling\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Saka\r 6",
    "Player_3": "Mazraoui\r 1",
    "Player_4": "Gomez\r 1",
    "Player_8": "Palmer\r 7",
    "Player_9": "Cunha\r 2",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "809( 1,984,452 ) TotalXfr : 14",
    "Teams": "Slumdog Mignolet( Xerxes Khambatta )",
    "SXL": "India",
    "Latp": "61",
    "Player_1": "Raya\r 6",
    "Player_11": "Jo\u00E3o Pedro\r 5",
    "Player_10": "Wissa\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Colwill\r 0",
    "Player_14": "Greaves\r 1",
    "Player_7": "Rogers\r 8",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Rashford\r 1",
    "Player_3": "Aina\r 1",
    "Player_4": "Lewis\r 1",
    "Player_8": "Palmer\r 14",
    "Player_9": "Haaland\r 5",
    "Player_15": "Semenyo\r 3"
  },
  {
    "manager_Name": "805( 2,120,679 ) TotalXfr : 10",
    "Teams": "redfoxchallenger( Rajas Prasannakumar Thakur )",
    "SXL": "USA",
    "Latp": "65",
    "Player_1": "Raya\r 6",
    "Player_11": "Isak\r 11",
    "Player_10": "Haaland\r 5",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Veltman\r 0",
    "Player_14": "A\u00EFt-Nouri\r 0",
    "Player_7": "Saka\r 3",
    "Player_2": "Mykolenko\r 11",
    "Player_5": "Palmer\r 14",
    "Player_6": "Semenyo\r 3",
    "Player_3": "Lewis\r 1",
    "Player_4": "Greaves\r 1",
    "Player_8": "Rogers\r 8",
    "Player_9": "Mbeumo\r 2",
    "Player_15": "Wood\r 2"
  },
  {
    "manager_Name": "805( 2,139,596 ) TotalXfr : 16",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "India",
    "Latp": "75",
    "Player_1": "Henderson\r 7",
    "Player_11": "Cunha\r 2",
    "Player_10": "Armstrong\r 1",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Konat\u00E9\r 0",
    "Player_14": "W.Fofana\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "J.Timber\r 14",
    "Player_5": "Johnson\r 2",
    "Player_6": "Saka\r 6",
    "Player_3": "Faes\r 1",
    "Player_4": "Saliba\r 15",
    "Player_8": "Palmer\r 7",
    "Player_9": "B.Fernandes\r 2",
    "Player_15": "Wheatley\r 0"
  }
];