var s = [
  {
    "manager_Name": "753( 1 ) TotalXfr : 7",
    "Teams": "Bukayo\u0027s Sadza( Brendan Sylvester )",
    "SXL": "NL",
    "Latp": "68",
    "Player_1": "Raya\r 3",
    "Player_11": "Watkins\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "Valdimarsson\r FUL (A)",
    "Player_13": "Robinson\r BRE (H)",
    "Player_14": "Greaves\r 0",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Rogers\r 9",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Aina\r 15",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Saka\r 2",
    "Player_9": "Palmer\r 3",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "735( 8 ) TotalXfr : 9",
    "Teams": "I AM PANDA( Fahad Al kharafi\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC )",
    "SXL": "KW",
    "Latp": "51",
    "Player_1": "Henderson\r 2",
    "Player_11": "Ra\u00FAl\r BRE (H)",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Winks\r 2",
    "Player_14": "Digne\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Keane\r 1",
    "Player_5": "McNeil\r 2",
    "Player_6": "Palmer\r 3",
    "Player_3": "Aina\r 15",
    "Player_4": "Faes\r 2",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Cunha\r 6",
    "Player_15": "Dunk\r 0"
  },
  {
    "manager_Name": "734( 9 ) TotalXfr : 7",
    "Teams": "MANO XXd( \u0639\u0628\u062F\u0627\u0644\u0631\u062D\u0645\u0646 \u0634\u0639\u064A\u0634\u0639 )",
    "SXL": "EG",
    "Latp": "61",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r 1",
    "Player_10": "Welbeck\r 5",
    "Player_12": "Turner\r 0",
    "Player_13": "Barco\r 0",
    "Player_14": "Burn\r 6",
    "Player_7": "Palmer\r 3",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Lewis\r 1",
    "Player_4": "Mazraoui\r 2",
    "Player_8": "Saka\r 2",
    "Player_9": "Solanke\r 16",
    "Player_15": "Rogers\r 9"
  },
  {
    "manager_Name": "728( 14 ) TotalXfr : 7",
    "Teams": "legend( ibrahim soliman )",
    "SXL": "EG",
    "Latp": "69",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Strand Larsen\r 8",
    "Player_10": "Wood\r 7",
    "Player_12": "Valdimarsson\r FUL (A)",
    "Player_13": "McNeil\r 2",
    "Player_14": "Mazraoui\r 2",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Keane\r 1",
    "Player_5": "Foden\r 2",
    "Player_6": "Rogers\r 9",
    "Player_3": "Aina\r 15",
    "Player_4": "Gvardiol\r 7",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Haaland\r 2",
    "Player_15": "Digne\r 0"
  },
  {
    "manager_Name": "728( 16 ) TotalXfr : 11",
    "Teams": "yeah buddy( tunjay ozer )",
    "SXL": "AU",
    "Latp": "54",
    "Player_1": "Sels\r 6",
    "Player_11": "Haaland\r 4",
    "Player_10": "Welbeck\r 5",
    "Player_12": "Flekken\r FUL (A)",
    "Player_13": "Collins\r FUL (A)",
    "Player_14": "Beto\r 1",
    "Player_7": "Madueke\r 2",
    "Player_2": "Keane\r 1",
    "Player_5": "Johnson\r 8",
    "Player_6": "M.Salah\r 9",
    "Player_3": "Aina\r 15",
    "Player_4": "A\u00EFt-Nouri\r 1",
    "Player_8": "Palmer\r 3",
    "Player_9": "Mbeumo\r FUL (A)",
    "Player_15": "Veltman\r 1"
  },
  {
    "manager_Name": "727( 18 ) TotalXfr : 9",
    "Teams": "DiLman ahmad( Ahmad Sami Botani )",
    "SXL": "IQ",
    "Latp": "62",
    "Player_1": "Ederson M.\r 2",
    "Player_11": "Wood\r 7",
    "Player_10": "Solanke\r 16",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Barnes\r 1",
    "Player_14": "Udogie\r 2",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Konat\u00E9\r 1",
    "Player_5": "Iwobi\r BRE (H)",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Stephens\r 6",
    "Player_4": "Digne\r 0",
    "Player_8": "Palmer\r 3",
    "Player_9": "Isak\r 9",
    "Player_15": "Tuanzebe\r 0"
  },
  {
    "manager_Name": "726( 20 ) TotalXfr : 7",
    "Teams": "jar jar winks( Calum Strachan )",
    "SXL": "S1",
    "Latp": "60",
    "Player_1": "S\u00E1nchez\r 3",
    "Player_11": "Wood\r 7",
    "Player_10": "Welbeck\r 5",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Gabriel\r 2",
    "Player_14": "Woolfenden\r 0",
    "Player_7": "B.Fernandes\r 10",
    "Player_2": "Dalot\r 1",
    "Player_5": "Palmer\r 3",
    "Player_6": "Saka\r 2",
    "Player_3": "Alexander-Arnold\r 2",
    "Player_4": "Gvardiol\r 7",
    "Player_8": "M.Salah\r 18",
    "Player_9": "McNeil\r 2",
    "Player_15": "Lankshear\r 0"
  },
  {
    "manager_Name": "726( 22 ) TotalXfr : 11",
    "Teams": "GoodBoy Gunner \uFFFD( Hridesh Wagle )",
    "SXL": "NP",
    "Latp": "43",
    "Player_1": "Sels\r 6",
    "Player_11": "Watkins\r 2",
    "Player_10": "Havertz\r 1",
    "Player_12": "Turner\r 0",
    "Player_13": "Winks\r 2",
    "Player_14": "Dunk\r 0",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Keane\r 1",
    "Player_5": "Rogers\r 9",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Lewis\r 1",
    "Player_4": "Colwill\r 2",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Haaland\r 2",
    "Player_15": "Tuanzebe\r 0"
  },
  {
    "manager_Name": "725( 23 ) TotalXfr : 7",
    "Teams": "Blueberries( Alex Hirkjolen )",
    "SXL": "NO",
    "Latp": "55",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Cunha\r 6",
    "Player_10": "Wood\r 7",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Pedro Porro\r 1",
    "Player_14": "Faes\r 2",
    "Player_7": "Saka\r 2",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Rogers\r 9",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "A\u00EFt-Nouri\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Palmer\r 3",
    "Player_15": "Chiwome\r 0"
  },
  {
    "manager_Name": "722( 40 ) TotalXfr : 9",
    "Teams": "Stella Rosa( Kristijan Anicic )",
    "SXL": "BA",
    "Latp": "47",
    "Player_1": "Pickford\r 2",
    "Player_11": "Solanke\r 16",
    "Player_10": "N.Jackson\r 1",
    "Player_12": "Turner\r 0",
    "Player_13": "Faes\r 2",
    "Player_14": "Burn\r 6",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Robinson\r BRE (H)",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Saka\r 2",
    "Player_3": "Mu\u00F1oz\r 3",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "Palmer\r 3",
    "Player_15": "Fraser\r 0"
  },
  {
    "manager_Name": "721( 44 ) TotalXfr : 7",
    "Teams": "\u0627\u0644\u0634\u0631\u0642\u0627\u0648\u064A( \u0645\u062D\u0645\u062F \u0627\u0644\u0634\u0631\u0642\u0627\u0648\u064A )",
    "SXL": "EG",
    "Latp": "41",
    "Player_1": "Pickford\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "Dennis\r 0",
    "Player_13": "Rogers\r 9",
    "Player_14": "Keane\r 1",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Bednarek\r 5",
    "Player_5": "Palmer\r 3",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Lewis\r 1",
    "Player_4": "Faes\r 2",
    "Player_8": "Smith Rowe\r BRE (H)",
    "Player_9": "N.Jackson\r 1",
    "Player_15": "Digne\r 0"
  },
  {
    "manager_Name": "719( 59 ) TotalXfr : 9",
    "Teams": "Mandem All-Stars( Mike Babs )",
    "SXL": "EN",
    "Latp": "62",
    "Player_1": "Ederson M.\r 2",
    "Player_11": "Vardy\r 5",
    "Player_10": "Watkins\r 2",
    "Player_12": "Jaros\r 0",
    "Player_13": "Adama\r BRE (H)",
    "Player_14": "Okoli\r 0",
    "Player_7": "Bowen\r 2",
    "Player_2": "Aina\r 15",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Lewis\r 1",
    "Player_4": "Gvardiol\r 7",
    "Player_8": "Palmer\r 3",
    "Player_9": "Wood\r 7",
    "Player_15": "O\u0027Shea\r 2"
  },
  {
    "manager_Name": "717( 66 ) TotalXfr : 8",
    "Teams": "Essam jubran( Jubran Jubran )",
    "SXL": "PS",
    "Latp": "37",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r 2",
    "Player_12": "Arrizabalaga\r 0",
    "Player_13": "Greaves\r 0",
    "Player_14": "Winks\r 2",
    "Player_7": "M.Salah\r 9",
    "Player_2": "Robertson\r 0",
    "Player_5": "Semenyo\r 10",
    "Player_6": "McNeil\r 2",
    "Player_3": "Saliba\r 2",
    "Player_4": "Keane\r 1",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Wood\r 7",
    "Player_15": "Collins\r FUL (A)"
  },
  {
    "manager_Name": "715( 84 ) TotalXfr : 11",
    "Teams": "Fr3wN( Mohamad Darwish )",
    "SXL": "EG",
    "Latp": "61",
    "Player_1": "Sels\r 6",
    "Player_11": "Cunha\r 6",
    "Player_10": "Watkins\r 2",
    "Player_12": "Dennis\r 0",
    "Player_13": "Luis D\u00EDaz\r 1",
    "Player_14": "Collins\r FUL (A)",
    "Player_7": "Palmer\r 3",
    "Player_2": "Keane\r 1",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Lewis\r 1",
    "Player_4": "Aina\r 15",
    "Player_8": "Foden\r 2",
    "Player_9": "Wood\r 7",
    "Player_15": "Digne\r 0"
  },
  {
    "manager_Name": "714( 91 ) TotalXfr : 8",
    "Teams": "K@k-t@k( Dmitriy Chernyshev )",
    "SXL": "KZ",
    "Latp": "49",
    "Player_1": "Martinez\r 0",
    "Player_11": "Haaland\r 4",
    "Player_10": "Ra\u00FAl\r BRE (H)",
    "Player_12": "Matthews\r 0",
    "Player_13": "Van den Berg\r FUL (A)",
    "Player_14": "Carvalho\r FUL (A)",
    "Player_7": "Palmer\r 3",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "A\u00EFt-Nouri\r 1",
    "Player_6": "Rogers\r 9",
    "Player_3": "Aina\r 15",
    "Player_4": "Lewis\r 1",
    "Player_8": "M.Salah\r 9",
    "Player_9": "Mbeumo\r FUL (A)",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "713( 97 ) TotalXfr : 7",
    "Teams": "Abbas( \u0634\u06CE\u0631\u06D5\u06A9\u06D5\u06CC \u0633\u0645\u0648\u062F )",
    "SXL": "IQ",
    "Latp": "48",
    "Player_1": "Pickford\r 2",
    "Player_11": "Wood\r 7",
    "Player_10": "Haaland\r 2",
    "Player_12": "Ward\r 0",
    "Player_13": "Robinson\r BRE (H)",
    "Player_14": "Burn\r 6",
    "Player_7": "Palmer\r 3",
    "Player_2": "Mykolenko\r 2",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Bowen\r 2",
    "Player_3": "Faes\r 2",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "Rogers\r 9",
    "Player_9": "M.Salah\r 18",
    "Player_15": "Ui-jo\r 0"
  },
  {
    "manager_Name": "712( 105 ) TotalXfr : 5",
    "Teams": "BDK FC( Kishaaen Sundralingam )",
    "SXL": "MY",
    "Latp": "49",
    "Player_1": "Raya\r 3",
    "Player_11": "Watkins\r 2",
    "Player_10": "Rogers\r 9",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Evanilson\r 7",
    "Player_14": "Nedeljkovic\r 0",
    "Player_7": "Palmer\r 3",
    "Player_2": "Mykolenko\r 2",
    "Player_5": "Gvardiol\r 7",
    "Player_6": "Saka\r 2",
    "Player_3": "Lewis\r 1",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "M.Salah\r 18",
    "Player_15": "Chiwome\r 0"
  },
  {
    "manager_Name": "712( 108 ) TotalXfr : 8",
    "Teams": "Sayed.samy( sayed samy )",
    "SXL": "EG",
    "Latp": "43",
    "Player_1": "Sels\r 6",
    "Player_11": "Delap\r 2",
    "Player_10": "N.Jackson\r 1",
    "Player_12": "S\u00E1nchez\r 3",
    "Player_13": "Rogers\r 9",
    "Player_14": "Mazraoui\r 2",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Digne\r 0",
    "Player_5": "A\u00EFt-Nouri\r 1",
    "Player_6": "Saka\r 2",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Udogie\r 2",
    "Player_8": "Palmer\r 3",
    "Player_9": "Havertz\r 1",
    "Player_15": "Semenyo\r 10"
  },
  {
    "manager_Name": "712( 114 ) TotalXfr : 11",
    "Teams": "scofild( Marouan ben djeloul )",
    "SXL": "DZ",
    "Latp": "49",
    "Player_1": "Martinez\r 0",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "Flekken\r FUL (A)",
    "Player_13": "Wissa\r FUL (A)",
    "Player_14": "Robinson\r BRE (H)",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Lewis\r 1",
    "Player_5": "Palmer\r 3",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Aina\r 15",
    "Player_4": "A\u00EFt-Nouri\r 1",
    "Player_8": "Adama\r BRE (H)",
    "Player_9": "McNeil\r 2",
    "Player_15": "Digne\r 0"
  },
  {
    "manager_Name": "711( 118 ) TotalXfr : 8",
    "Teams": "Quelle BUT( Yahia Ltf )",
    "SXL": "DZ",
    "Latp": "50",
    "Player_1": "S\u00E1nchez\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "Solanke\r 16",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Adama\r BRE (H)",
    "Player_14": "Konsa\r 0",
    "Player_7": "Palmer\r 3",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Rogers\r 9",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Collins\r FUL (A)",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "Cunha\r 6",
    "Player_15": "Burn\r 6"
  },
  {
    "manager_Name": "711( 125 ) TotalXfr : 10",
    "Teams": "Jimmy Sallivinho( anthony fennell )",
    "SXL": "IE",
    "Latp": "61",
    "Player_1": "Raya\r 3",
    "Player_11": "Solanke\r 16",
    "Player_10": "Watkins\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Andersen\r BRE (H)",
    "Player_14": "Winks\r 2",
    "Player_7": "Trossard\r 2",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Palmer\r 3",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Wood\r 7",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "710( 138 ) TotalXfr : 10",
    "Teams": "Sof( Soufiane Benhouda )",
    "SXL": "DZ",
    "Latp": "51",
    "Player_1": "Jos\u00E9 S\u00E1\r 2",
    "Player_11": "Watkins\r 2",
    "Player_10": "Wissa\r FUL (A)",
    "Player_12": "S\u00E1nchez\r 3",
    "Player_13": "Rogers\r 9",
    "Player_14": "Van de Ven\r 0",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Martinelli\r 2",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Konsa\r 0",
    "Player_4": "Lewis\r 1",
    "Player_8": "Palmer\r 3",
    "Player_9": "Solanke\r 16",
    "Player_15": "Burn\r 6"
  },
  {
    "manager_Name": "709( 148 ) TotalXfr : 9",
    "Teams": "Aaltowailea( Abdulaziz Altowailea )",
    "SXL": "KW",
    "Latp": "44",
    "Player_1": "S\u00E1nchez\r 3",
    "Player_11": "Calvert-Lewin\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "Raya\r 3",
    "Player_13": "Aina\r 15",
    "Player_14": "Rogers\r 9",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Palmer\r 3",
    "Player_3": "Akanji\r 1",
    "Player_4": "A\u00EFt-Nouri\r 1",
    "Player_8": "Saka\r 2",
    "Player_9": "Ra\u00FAl\r BRE (H)",
    "Player_15": "Digne\r 0"
  },
  {
    "manager_Name": "709( 152 ) TotalXfr : 11",
    "Teams": "\u0628\u0627\u0633\u0628\u0627\u0631( \u0639\u0628\u062F\u0627\u0644\u0644\u0647 \u0628\u0627\u0633\u0628\u0627\u0631 )",
    "SXL": "SD",
    "Latp": "38",
    "Player_1": "Henderson\r 2",
    "Player_11": "Wissa\r FUL (A)",
    "Player_10": "Watkins\r 2",
    "Player_12": "Flekken\r FUL (A)",
    "Player_13": "Rogers\r 9",
    "Player_14": "Digne\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Keane\r 1",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Palmer\r 3",
    "Player_3": "Lewis\r 1",
    "Player_4": "Robinson\r BRE (H)",
    "Player_8": "Son\r 4",
    "Player_9": "Wood\r 7",
    "Player_15": "Bednarek\r 5"
  },
  {
    "manager_Name": "708( 155 ) TotalXfr : 6",
    "Teams": "Nizar( Nizar Kurdi )",
    "SXL": "IQ",
    "Latp": "46",
    "Player_1": "Martinez\r 0",
    "Player_11": "Watkins\r 2",
    "Player_10": "Antonio\r 1",
    "Player_12": "Steele\r 0",
    "Player_13": "Welbeck\r 5",
    "Player_14": "Robinson\r BRE (H)",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Palmer\r 3",
    "Player_3": "Lewis\r 1",
    "Player_4": "Pinnock\r FUL (A)",
    "Player_8": "Rogers\r 9",
    "Player_9": "Semenyo\r 10",
    "Player_15": "Dunk\r 0"
  },
  {
    "manager_Name": "708( 162 ) TotalXfr : 8",
    "Teams": "Balls of Steele( Dan Mclellan )",
    "SXL": "EN",
    "Latp": "57",
    "Player_1": "S\u00E1nchez\r 3",
    "Player_11": "Isak\r 9",
    "Player_10": "Watkins\r 2",
    "Player_12": "Bentley\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 0",
    "Player_14": "Wan-Bissaka\r 1",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Davis\r 10",
    "Player_5": "Rogers\r 9",
    "Player_6": "Palmer\r 3",
    "Player_3": "Konsa\r 0",
    "Player_4": "Lewis\r 1",
    "Player_8": "Foden\r 2",
    "Player_9": "Mbeumo\r FUL (A)",
    "Player_15": "Harwood-Bellis\r 6"
  },
  {
    "manager_Name": "708( 162 ) TotalXfr : 8",
    "Teams": "\u00D8deparfum( Micky Dore )",
    "SXL": "EN",
    "Latp": "53",
    "Player_1": "Raya\r 3",
    "Player_11": "Solanke\r 16",
    "Player_10": "Wood\r 7",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Rogers\r 9",
    "Player_14": "Faes\r 2",
    "Player_7": "Palmer\r 3",
    "Player_2": "Lewis\r 1",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Pedro Porro\r 1",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Saka\r 2",
    "Player_9": "Ra\u00FAl\r BRE (H)",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "708( 162 ) TotalXfr : 8",
    "Teams": "Diffe litt mindre( Iver Vattoy )",
    "SXL": "NO",
    "Latp": "63",
    "Player_1": "Sels\r 6",
    "Player_11": "Solanke\r 16",
    "Player_10": "Vardy\r 5",
    "Player_12": "Turner\r 0",
    "Player_13": "Faes\r 2",
    "Player_14": "Van den Berg\r FUL (A)",
    "Player_7": "Foden\r 2",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Son\r 4",
    "Player_6": "Palmer\r 3",
    "Player_3": "Lewis\r 1",
    "Player_4": "A\u00EFt-Nouri\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Mbeumo\r FUL (A)",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "708( 171 ) TotalXfr : 9",
    "Teams": "chin tapak dam dam( Hala Madrid )",
    "SXL": "BD",
    "Latp": "55",
    "Player_1": "Pickford\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "Turner\r 0",
    "Player_13": "Rogers\r 9",
    "Player_14": "Faes\r 2",
    "Player_7": "Smith Rowe\r BRE (H)",
    "Player_2": "Aina\r 15",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Palmer\r 3",
    "Player_3": "Lewis\r 1",
    "Player_4": "Dalot\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Cunha\r 6",
    "Player_15": "Harwood-Bellis\r 6"
  },
  {
    "manager_Name": "708( 171 ) TotalXfr : 9",
    "Teams": "W( Shabaaz Bajar )",
    "SXL": "EN",
    "Latp": "43",
    "Player_1": "S\u00E1nchez\r 3",
    "Player_11": "Havertz\r 1",
    "Player_10": "Wood\r 7",
    "Player_12": "Turner\r 0",
    "Player_13": "Faes\r 2",
    "Player_14": "Choudhury\r 0",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Virgil\r 5",
    "Player_5": "Saka\r 2",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Lewis\r 1",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Palmer\r 3",
    "Player_9": "N.Jackson\r 1",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "707( 187 ) TotalXfr : 8",
    "Teams": "Hakuna Mateta( Jack Brennan )",
    "SXL": "EN",
    "Latp": "60",
    "Player_1": "S\u00E1nchez\r 3",
    "Player_11": "Cunha\r 6",
    "Player_10": "Watkins\r 2",
    "Player_12": "Valdimarsson\r FUL (A)",
    "Player_13": "Delap\r 2",
    "Player_14": "Robinson\r BRE (H)",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Aina\r 15",
    "Player_5": "Palmer\r 3",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Gvardiol\r 7",
    "Player_8": "Foden\r 2",
    "Player_9": "McNeil\r 2",
    "Player_15": "Nedeljkovic\r 0"
  },
  {
    "manager_Name": "706( 201 ) TotalXfr : 7",
    "Teams": "Ronaldinhovic( Ajdin Selimovic )",
    "SXL": "NO",
    "Latp": "38",
    "Player_1": "Raya\r 3",
    "Player_11": "Calvert-Lewin\r 2",
    "Player_10": "Solanke\r 16",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Tuanzebe\r 0",
    "Player_14": "Gabriel\r 2",
    "Player_7": "Palmer\r 3",
    "Player_2": "Lewis\r 1",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "McNeil\r 2",
    "Player_3": "Keane\r 1",
    "Player_4": "Digne\r 0",
    "Player_8": "Son\r 8",
    "Player_9": "Haaland\r 2",
    "Player_15": "Dibling\r 0"
  },
  {
    "manager_Name": "706( 205 ) TotalXfr : 8",
    "Teams": "abo jojo \u2764\uFE0F( jojo \u0026 Lolo )",
    "SXL": "EG",
    "Latp": "69",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Watkins\r 2",
    "Player_10": "Haaland\r 2",
    "Player_12": "Henderson\r 2",
    "Player_13": "Dibling\r 0",
    "Player_14": "Digne\r 0",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Aina\r 15",
    "Player_5": "Rogers\r 9",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Gu\u00E9hi\r 7",
    "Player_4": "Keane\r 1",
    "Player_8": "B.Fernandes\r 10",
    "Player_9": "Welbeck\r 5",
    "Player_15": "Mazraoui\r 2"
  },
  {
    "manager_Name": "706( 213 ) TotalXfr : 9",
    "Teams": "Kaluno City( Innocent Kalukuta )",
    "SXL": "MW",
    "Latp": "44",
    "Player_1": "Raya\r 3",
    "Player_11": "Watkins\r 2",
    "Player_10": "Vardy\r 5",
    "Player_12": "S\u00E1nchez\r 3",
    "Player_13": "L.Paquet\u00E1\r 1",
    "Player_14": "Mazraoui\r 2",
    "Player_7": "Palmer\r 3",
    "Player_2": "Lewis\r 1",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Saka\r 2",
    "Player_3": "Faes\r 2",
    "Player_4": "Keane\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Wood\r 7",
    "Player_15": "Digne\r 0"
  },
  {
    "manager_Name": "705( 229 ) TotalXfr : 8",
    "Teams": "SakofRice( George Coghlan )",
    "SXL": "EN",
    "Latp": "59",
    "Player_1": "S\u00E1nchez\r 3",
    "Player_11": "Watkins\r 2",
    "Player_10": "Cunha\r 6",
    "Player_12": "Areola\r 0",
    "Player_13": "Justin\r 0",
    "Player_14": "Harwood-Bellis\r 6",
    "Player_7": "Rogers\r 9",
    "Player_2": "Konat\u00E9\r 1",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Palmer\r 3",
    "Player_3": "Aina\r 15",
    "Player_4": "Robinson\r BRE (H)",
    "Player_8": "Saka\r 2",
    "Player_9": "Mbeumo\r FUL (A)",
    "Player_15": "Jo\u00E3o Pedro\r 0"
  },
  {
    "manager_Name": "705( 229 ) TotalXfr : 8",
    "Teams": "Icons( Dany Icon )",
    "SXL": "LB",
    "Latp": "43",
    "Player_1": "S\u00E1nchez\r 3",
    "Player_11": "Ra\u00FAl\r BRE (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Ramsdale\r 9",
    "Player_13": "Mazraoui\r 2",
    "Player_14": "Greaves\r 0",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Konat\u00E9\r 1",
    "Player_5": "Palmer\r 3",
    "Player_6": "Johnson\r 8",
    "Player_3": "Keane\r 1",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Kulusevski\r 5",
    "Player_9": "Solanke\r 16",
    "Player_15": "Moder\r 1"
  },
  {
    "manager_Name": "704( 238 ) TotalXfr : 5",
    "Teams": "\u062C\u0648\u0632\u064A\u0641( yossef Abkar )",
    "SXL": "SD",
    "Latp": "79",
    "Player_1": "Sels\r 6",
    "Player_11": "Solanke\r 16",
    "Player_10": "Haaland\r 2",
    "Player_12": "Ward\r 0",
    "Player_13": "Damsgaard\r FUL (A)",
    "Player_14": "Cresswell\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Lewis\r 1",
    "Player_5": "Palmer\r 3",
    "Player_6": "Rogers\r 9",
    "Player_3": "Aina\r 15",
    "Player_4": "A\u00EFt-Nouri\r 1",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Strand Larsen\r 8",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "704( 240 ) TotalXfr : 7",
    "Teams": "SabKiMaarteta( Shaurabh Patel )",
    "SXL": "IN",
    "Latp": "55",
    "Player_1": "S\u00E1nchez\r 3",
    "Player_11": "Wood\r 7",
    "Player_10": "N.Jackson\r 1",
    "Player_12": "Zych\r 0",
    "Player_13": "McNeil\r 2",
    "Player_14": "Woolfenden\r 0",
    "Player_7": "Johnson\r 8",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Palmer\r 3",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "Gvardiol\r 7",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Havertz\r 1",
    "Player_15": "Burgess\r 2"
  },
  {
    "manager_Name": "704( 247 ) TotalXfr : 8",
    "Teams": "M. D.( Yasser Saad )",
    "SXL": "IQ",
    "Latp": "42",
    "Player_1": "Raya\r 3",
    "Player_11": "Wissa\r FUL (A)",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Mazraoui\r 2",
    "Player_14": "Mosquera\r 0",
    "Player_7": "Palmer\r 3",
    "Player_2": "Robinson\r BRE (H)",
    "Player_5": "Rogers\r 9",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "A\u00EFt-Nouri\r 1",
    "Player_4": "Keane\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Vardy\r 5",
    "Player_15": "M.Fran\u00E7a\r 0"
  },
  {
    "manager_Name": "703( 264 ) TotalXfr : 5",
    "Teams": "vin( vin . )",
    "SXL": "SG",
    "Latp": "50",
    "Player_1": "Henderson\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Vardy\r 10",
    "Player_12": "Bentley\r 0",
    "Player_13": "Adama\r BRE (H)",
    "Player_14": "Dalot\r 1",
    "Player_7": "Rogers\r 9",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "M.Salah\r 9",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "R\u00FAben\r 0",
    "Player_8": "McNeil\r 2",
    "Player_9": "Wood\r 7",
    "Player_15": "Faes\r 2"
  },
  {
    "manager_Name": "703( 272 ) TotalXfr : 8",
    "Teams": "Special one \u261D\uFE0F( HADY Ezzat )",
    "SXL": "EG",
    "Latp": "46",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Cunha\r 6",
    "Player_12": "Henderson\r 2",
    "Player_13": "Robinson\r BRE (H)",
    "Player_14": "Welbeck\r 5",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Lewis\r 1",
    "Player_5": "McNeil\r 2",
    "Player_6": "Palmer\r 3",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "Faes\r 2",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Rogers\r 9",
    "Player_15": "Konsa\r 0"
  },
  {
    "manager_Name": "703( 272 ) TotalXfr : 8",
    "Teams": "Specy UTD \uFFFD( Robert Maftei )",
    "SXL": "EN",
    "Latp": "52",
    "Player_1": "S\u00E1nchez\r 3",
    "Player_11": "Wood\r 7",
    "Player_10": "Haaland\r 4",
    "Player_12": "Iversen\r 0",
    "Player_13": "Digne\r 0",
    "Player_14": "Welbeck\r 5",
    "Player_7": "Rogers\r 9",
    "Player_2": "Lewis\r 1",
    "Player_5": "Gabriel\r 2",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Aina\r 15",
    "Player_4": "Robinson\r BRE (H)",
    "Player_8": "M.Salah\r 9",
    "Player_9": "Saka\r 2",
    "Player_15": "Semenyo\r 10"
  },
  {
    "manager_Name": "703( 272 ) TotalXfr : 8",
    "Teams": "Heemo Elect33( Abdalrhim mohamed )",
    "SXL": "SD",
    "Latp": "42",
    "Player_1": "S\u00E1nchez\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "Vardy\r 5",
    "Player_12": "Turner\r 0",
    "Player_13": "Burn\r 6",
    "Player_14": "Amad\r 0",
    "Player_7": "Rogers\r 9",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Smith Rowe\r BRE (H)",
    "Player_6": "Palmer\r 3",
    "Player_3": "Stones\r 0",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "M.Salah\r 9",
    "Player_9": "Antonio\r 1",
    "Player_15": "Johnson\r 2"
  },
  {
    "manager_Name": "703( 285 ) TotalXfr : 11",
    "Teams": "Harimau Malaya FC( TC Chong )",
    "SXL": "HK",
    "Latp": "49",
    "Player_1": "Sels\r 6",
    "Player_11": "Watkins\r 2",
    "Player_10": "Vardy\r 5",
    "Player_12": "Turner\r 0",
    "Player_13": "Luis D\u00EDaz\r 1",
    "Player_14": "Van de Ven\r 0",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Udogie\r 2",
    "Player_5": "Son\r 4",
    "Player_6": "Palmer\r 3",
    "Player_3": "Lewis\r 1",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Wood\r 7",
    "Player_15": "Cresswell\r 0"
  },
  {
    "manager_Name": "702( 297 ) TotalXfr : 8",
    "Teams": "Pain in Dias( Mikolaj Pietluch )",
    "SXL": "EN",
    "Latp": "55",
    "Player_1": "Sels\r 6",
    "Player_11": "Strand Larsen\r 8",
    "Player_10": "Wissa\r FUL (A)",
    "Player_12": "Begovic\r 0",
    "Player_13": "De Ligt\r 2",
    "Player_14": "McNeil\r 2",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Palmer\r 3",
    "Player_3": "Alexander-Arnold\r 2",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Saka\r 2",
    "Player_9": "Wood\r 7",
    "Player_15": "Van den Berg\r FUL (A)"
  },
  {
    "manager_Name": "702( 297 ) TotalXfr : 8",
    "Teams": "Abdo( Abdo Khaled )",
    "SXL": "EG",
    "Latp": "61",
    "Player_1": "Ederson M.\r 2",
    "Player_11": "Wood\r 7",
    "Player_10": "Solanke\r 16",
    "Player_12": "Turner\r 0",
    "Player_13": "Burn\r 6",
    "Player_14": "Andersen\r BRE (H)",
    "Player_7": "Palmer\r 3",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Garnacho\r 2",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Faes\r 2",
    "Player_8": "Saka\r 2",
    "Player_9": "M.Salah\r 18",
    "Player_15": "Fraser\r 0"
  },
  {
    "manager_Name": "702( 305 ) TotalXfr : 9",
    "Teams": "relax party( roshan sherchan )",
    "SXL": "NP",
    "Latp": "58",
    "Player_1": "Raya\r 3",
    "Player_11": "Wood\r 7",
    "Player_10": "Cunha\r 6",
    "Player_12": "Flekken\r FUL (A)",
    "Player_13": "Welbeck\r 5",
    "Player_14": "Gabriel\r 2",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Harwood-Bellis\r 6",
    "Player_5": "Saka\r 2",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Garnacho\r 2",
    "Player_9": "Kulusevski\r 5",
    "Player_15": "Collins\r FUL (A)"
  },
  {
    "manager_Name": "702( 305 ) TotalXfr : 9",
    "Teams": "ayoub RCA( Ayoub Khali )",
    "SXL": "MA",
    "Latp": "59",
    "Player_1": "Ramsdale\r 9",
    "Player_11": "Watkins\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Palmer\r 3",
    "Player_14": "Rogers\r 9",
    "Player_7": "M.Salah\r 9",
    "Player_2": "Keane\r 1",
    "Player_5": "Harwood-Bellis\r 6",
    "Player_6": "Garnacho\r 2",
    "Player_3": "Faes\r 2",
    "Player_4": "Gvardiol\r 7",
    "Player_8": "Matheus N.\r 2",
    "Player_9": "Antonio\r 1",
    "Player_15": "Digne\r 0"
  },
  {
    "manager_Name": "702( 309 ) TotalXfr : 10",
    "Teams": "Select Team Name( Kurt Bonnici )",
    "SXL": "MT",
    "Latp": "52",
    "Player_1": "Henderson\r 2",
    "Player_11": "Watkins\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "Valdimarsson\r FUL (A)",
    "Player_13": "McNeil\r 2",
    "Player_14": "Livramento\r 7",
    "Player_7": "Johnson\r 8",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Palmer\r 3",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Lewis\r 1",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Saka\r 2",
    "Player_9": "Ra\u00FAl\r BRE (H)",
    "Player_15": "Johnson\r 2"
  },
  {
    "manager_Name": "702( 313 ) TotalXfr : 12",
    "Teams": "Empire of Fire\uFFFD( Hamza amri )",
    "SXL": "DZ",
    "Latp": "73",
    "Player_1": "Pope\r 5",
    "Player_11": "Solanke\r 16",
    "Player_10": "Vardy\r 5",
    "Player_12": "Turner\r 0",
    "Player_13": "Smith Rowe\r BRE (H)",
    "Player_14": "Robinson\r BRE (H)",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Palmer\r 3",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Akanji\r 1",
    "Player_8": "Rogers\r 9",
    "Player_9": "Wood\r 7",
    "Player_15": "Burn\r 6"
  }
];