var s = [
  {
    "manager_Name": "642( 24,897 ) TotalXfr : 5",
    "Teams": "Lorrainesson( Lorraine Busuttil )",
    "SXL": "MT",
    "Latp": "33",
    "Player_1": "Sels\r 6",
    "Player_11": "Haaland\r 2",
    "Player_10": "Delap\r 2",
    "Player_12": "Lumley\r 0",
    "Player_13": "Davis\r 10",
    "Player_14": "Dibling\r 0",
    "Player_7": "Palmer\r MUN (A)",
    "Player_2": "Mykolenko\r 2",
    "Player_5": "Johnson\r AVL (H)",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Gabriel\r 2",
    "Player_4": "A\u00EFt-Nouri\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Ra\u00FAl\r BRE (H)",
    "Player_15": "Okoli\r 0"
  },
  {
    "manager_Name": "622( 104,960 ) TotalXfr : 10",
    "Teams": "FC Pek( Erik Lindberg )",
    "SXL": "SE",
    "Latp": "34",
    "Player_1": "Henderson\r 2",
    "Player_11": "Solanke\r AVL (H)",
    "Player_10": "Haaland\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Faes\r 2",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Lewis\r 1",
    "Player_6": "Smith Rowe\r BRE (H)",
    "Player_3": "Alexander-Arnold\r 2",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Wissa\r FUL (A)",
    "Player_15": "Winks\r 2"
  },
  {
    "manager_Name": "608( 229,235 ) TotalXfr : 7",
    "Teams": "The Bees( Tove Ronneb\u00E4ck )",
    "SXL": "MT",
    "Latp": "18",
    "Player_1": "Raya\r 3",
    "Player_11": "Wissa\r FUL (A)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Valdimarsson\r FUL (A)",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Harwood-Bellis\r 6",
    "Player_7": "Kulusevski\r AVL (H)",
    "Player_2": "Konat\u00E9\r 1",
    "Player_5": "Palmer\r MUN (A)",
    "Player_6": "Smith Rowe\r BRE (H)",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Havertz\r 1",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "597( 410,197 ) TotalXfr : 9",
    "Teams": "Fantasikonungen( Albin Jonsson )",
    "SXL": "MT",
    "Latp": "18",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Delap\r 2",
    "Player_12": "Valdimarsson\r FUL (A)",
    "Player_13": "Bergvall\r AVL (H)",
    "Player_14": "Van de Ven\r AVL (H)",
    "Player_7": "Palmer\r MUN (A)",
    "Player_2": "Keane\r 1",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Smith Rowe\r BRE (H)",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Kulusevski\r AVL (H)",
    "Player_9": "Calvert-Lewin\r 2",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "593( 494,020 ) TotalXfr : 9",
    "Teams": "Guglielmo( Jonas Megert )",
    "SXL": "SE",
    "Latp": "21",
    "Player_1": "Martinez\r TOT (A)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Wood\r 7",
    "Player_12": "Turner\r 0",
    "Player_13": "Winks\r 2",
    "Player_14": "Quansah\r 0",
    "Player_7": "M.Salah\r 9",
    "Player_2": "Pedro Porro\r AVL (H)",
    "Player_5": "Adama\r BRE (H)",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Konsa\r TOT (A)",
    "Player_4": "Lewis\r 1",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Ra\u00FAl\r BRE (H)",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "594( 466,655 ) TotalXfr : 8",
    "Teams": "NoHopeFC( John Maguire )",
    "SXL": "MT",
    "Latp": "31",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "Valdimarsson\r FUL (A)",
    "Player_13": "Welbeck\r 5",
    "Player_14": "Robinson\r BRE (H)",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Digne\r TOT (A)",
    "Player_5": "M.Salah\r 9",
    "Player_6": "Winks\r 2",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "Davis\r 10",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "Johnson\r AVL (H)",
    "Player_15": "Harwood-Bellis\r 6"
  },
  {
    "manager_Name": "588( 610,166 ) TotalXfr : 8",
    "Teams": "ThereWeLand( Haykel Mansour )",
    "SXL": "MT",
    "Latp": "10",
    "Player_1": "S\u00E1nchez\r MUN (A)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r TOT (A)",
    "Player_12": "Valdimarsson\r FUL (A)",
    "Player_13": "Smith Rowe\r BRE (H)",
    "Player_14": "Konsa\r TOT (A)",
    "Player_7": "McNeil\r 2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Collins\r FUL (A)",
    "Player_4": "Lewis\r 1",
    "Player_8": "Kulusevski\r AVL (H)",
    "Player_9": "Havertz\r 1",
    "Player_15": "Nedeljkovic\r TOT (A)"
  },
  {
    "manager_Name": "588( 606,272 ) TotalXfr : 7",
    "Teams": "MainooInTheBank( Thanasis Fouras )",
    "SXL": "GR",
    "Latp": "29",
    "Player_1": "Henderson\r 2",
    "Player_11": "Solanke\r AVL (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Matthews\r 0",
    "Player_13": "Faes\r 2",
    "Player_14": "Winks\r 2",
    "Player_7": "Johnson\r AVL (H)",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Gordon\r 6",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Robinson\r BRE (H)",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "Wood\r 7",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "594( 463,412 ) TotalXfr : 7",
    "Teams": "Udogie\u0027s Doggies( Claude Taliana )",
    "SXL": "MT",
    "Latp": "46",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Wood\r 7",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Barnes\r 1",
    "Player_14": "Pedro Porro\r AVL (H)",
    "Player_7": "Georginio\r 2",
    "Player_2": "Aina\r 15",
    "Player_5": "M.Salah\r 9",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Lewis\r 1",
    "Player_4": "Justin\r 0",
    "Player_8": "Rogers\r TOT (A)",
    "Player_9": "Strand Larsen\r 8",
    "Player_15": "Dalot\r CHE (H)"
  },
  {
    "manager_Name": "587( 648,712 ) TotalXfr : 10",
    "Teams": "Salahvation Army( Tom Atkinson )",
    "SXL": "MT",
    "Latp": "32",
    "Player_1": "Pope\r 5",
    "Player_11": "Watkins\r TOT (A)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Slicker\r 0",
    "Player_13": "Winks\r 2",
    "Player_14": "Collins\r FUL (A)",
    "Player_7": "Rogers\r TOT (A)",
    "Player_2": "Lewis\r 1",
    "Player_5": "McNeil\r 2",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Gabriel\r 2",
    "Player_8": "M.Salah\r 9",
    "Player_9": "Calvert-Lewin\r 2",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "576( 978,173 ) TotalXfr : 6",
    "Teams": "JDT Out( Filip Larsson )",
    "SXL": "MT",
    "Latp": "30",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Welbeck\r 5",
    "Player_10": "Wood\r 7",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Aina\r 15",
    "Player_14": "Semenyo\r 10",
    "Player_7": "Kulusevski\r AVL (H)",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Rogers\r TOT (A)",
    "Player_3": "Lewis\r 1",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "M.Salah\r 9",
    "Player_9": "Haaland\r 4",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "575( 1,017,838 ) TotalXfr : 7",
    "Teams": "BienRayados( Luis Ricardo J\u00E1uregui V )",
    "SXL": "EN",
    "Latp": "28",
    "Player_1": "S\u00E1nchez\r MUN (A)",
    "Player_11": "Ra\u00FAl\r BRE (H)",
    "Player_10": "Duran\r TOT (A)",
    "Player_12": "Fabianski\r 2",
    "Player_13": "J.Araujo\r 0",
    "Player_14": "Pau\r TOT (A)",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Stones\r 0",
    "Player_5": "Madueke\r MUN (A)",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Virgil\r 5",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Kova\u010Di\u0107\r 2",
    "Player_9": "Palmer\r MUN (A)",
    "Player_15": "Havertz\r 1"
  },
  {
    "manager_Name": "572( 1,155,397 ) TotalXfr : 10",
    "Teams": "Im Sorry Nic Jackson( Jon Briscoe White )",
    "SXL": "MT",
    "Latp": "16",
    "Player_1": "Henderson\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r TOT (A)",
    "Player_12": "Turner\r 0",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Gabriel\r 2",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Dalot\r CHE (H)",
    "Player_5": "Buonanotte\r 1",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Pedro Porro\r AVL (H)",
    "Player_4": "A\u00EFt-Nouri\r 1",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "Wood\r 7",
    "Player_15": "Vestergaard\r 2"
  },
  {
    "manager_Name": "568( 1,299,229 ) TotalXfr : 7",
    "Teams": "Ctrl Alt De Ligt( Marlon Vella )",
    "SXL": "MT",
    "Latp": "7",
    "Player_1": "S\u00E1nchez\r MUN (A)",
    "Player_11": "Ra\u00FAl\r BRE (H)",
    "Player_10": "Watkins\r TOT (A)",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Faes\r 2",
    "Player_14": "Winks\r 2",
    "Player_7": "Rogers\r TOT (A)",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Smith Rowe\r BRE (H)",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Pedro Porro\r AVL (H)",
    "Player_4": "Lewis\r 1",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "Haaland\r 4",
    "Player_15": "Mazraoui\r CHE (H)"
  },
  {
    "manager_Name": "566( 1,381,953 ) TotalXfr : 5",
    "Teams": "Lallish United( Melwin Holst )",
    "SXL": "SE",
    "Latp": "17",
    "Player_1": "Raya\r 3",
    "Player_11": "H\u00F8jlund\r CHE (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Davis\r 10",
    "Player_14": "Dibling\r 0",
    "Player_7": "Palmer\r MUN (A)",
    "Player_2": "A\u00EFt-Nouri\r 1",
    "Player_5": "Son\r AVL (H)",
    "Player_6": "Rogers\r TOT (A)",
    "Player_3": "Lewis\r 1",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Cunha\r 6",
    "Player_15": "Van den Berg\r FUL (A)"
  },
  {
    "manager_Name": "564( 1,508,003 ) TotalXfr : 11",
    "Teams": "Starship( Olumide Okedusi )",
    "SXL": "EE",
    "Latp": "16",
    "Player_1": "Raya\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "N.Jackson\r MUN (A)",
    "Player_12": "Turner\r 0",
    "Player_13": "Pedro Porro\r AVL (H)",
    "Player_14": "Adama\r BRE (H)",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "A\u00EFt-Nouri\r 1",
    "Player_5": "Kova\u010Di\u0107\r 2",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Virgil\r 5",
    "Player_4": "Robinson\r BRE (H)",
    "Player_8": "Rogers\r TOT (A)",
    "Player_9": "Havertz\r 1",
    "Player_15": "Burn\r 6"
  },
  {
    "manager_Name": "571( 1,179,457 ) TotalXfr : 8",
    "Teams": "Tourinho FC( Alexis Touris )",
    "SXL": "GR",
    "Latp": "46",
    "Player_1": "Ederson M.\r 2",
    "Player_11": "Isak\r 9",
    "Player_10": "Watkins\r TOT (A)",
    "Player_12": "Henderson\r 2",
    "Player_13": "Adama\r BRE (H)",
    "Player_14": "Burn\r 6",
    "Player_7": "Bowen\r 2",
    "Player_2": "Dalot\r CHE (H)",
    "Player_5": "Luis D\u00EDaz\r 1",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Pedro Porro\r AVL (H)",
    "Player_4": "Gvardiol\r 7",
    "Player_8": "Eze\r 0",
    "Player_9": "Wood\r 7",
    "Player_15": "Andersen\r BRE (H)"
  },
  {
    "manager_Name": "562( 1,589,841 ) TotalXfr : 9",
    "Teams": "klopp notch( Tobias Nocke )",
    "SXL": "SE",
    "Latp": "21",
    "Player_1": "Areola\r 0",
    "Player_11": "Haaland\r 4",
    "Player_10": "Solanke\r AVL (H)",
    "Player_12": "Valdimarsson\r FUL (A)",
    "Player_13": "Winks\r 2",
    "Player_14": "Harwood-Bellis\r 6",
    "Player_7": "Smith Rowe\r BRE (H)",
    "Player_2": "Konat\u00E9\r 1",
    "Player_5": "Palmer\r MUN (A)",
    "Player_6": "Gordon\r 6",
    "Player_3": "Van de Ven\r AVL (H)",
    "Player_4": "Wan-Bissaka\r 1",
    "Player_8": "M.Salah\r 9",
    "Player_9": "Ra\u00FAl\r BRE (H)",
    "Player_15": "Cresswell\r 0"
  },
  {
    "manager_Name": "561( 1,621,772 ) TotalXfr : 7",
    "Teams": "Gambit( Nicola Frasca )",
    "SXL": "MT",
    "Latp": "29",
    "Player_1": "Pickford\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Vardy\r 5",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Greaves\r 0",
    "Player_14": "Winks\r 2",
    "Player_7": "Yarmoliuk\r FUL (A)",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Pedro Porro\r AVL (H)",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Martinez\r CHE (H)",
    "Player_8": "Smith Rowe\r BRE (H)",
    "Player_9": "M.Salah\r 9",
    "Player_15": "Ings\r 0"
  },
  {
    "manager_Name": "561( 1,647,192 ) TotalXfr : 10",
    "Teams": "Biancoverde Utd 4.0( Michael Keramas )",
    "SXL": "GR",
    "Latp": "26",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 14",
    "Player_12": "Valdimarsson\r FUL (A)",
    "Player_13": "Welbeck\r 5",
    "Player_14": "Aina\r 15",
    "Player_7": "Smith Rowe\r BRE (H)",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Saka\r 2",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "A\u00EFt-Nouri\r 1",
    "Player_4": "Robinson\r BRE (H)",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Kulusevski\r AVL (H)",
    "Player_15": "Johnson\r 2"
  },
  {
    "manager_Name": "561( 1,647,192 ) TotalXfr : 10",
    "Teams": "Blue Core( Avinash Chatlani )",
    "SXL": "MT",
    "Latp": "37",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r MUN (A)",
    "Player_10": "Delap\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Winks\r 2",
    "Player_14": "Harwood-Bellis\r 6",
    "Player_7": "M.Salah\r 9",
    "Player_2": "Lewis\r 1",
    "Player_5": "Palmer\r MUN (A)",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Pedro Porro\r AVL (H)",
    "Player_4": "Aina\r 15",
    "Player_8": "Adama\r BRE (H)",
    "Player_9": "Haaland\r 4",
    "Player_15": "Vestergaard\r 2"
  },
  {
    "manager_Name": "556( 1,902,997 ) TotalXfr : 10",
    "Teams": "Ajax CT( Dimitrios Siderakis )",
    "SXL": "MT",
    "Latp": "28",
    "Player_1": "Sels\r 6",
    "Player_11": "Havertz\r 1",
    "Player_10": "Watkins\r TOT (A)",
    "Player_12": "S\u00E1nchez\r MUN (A)",
    "Player_13": "Carvalho\r FUL (A)",
    "Player_14": "Welbeck\r 5",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Martinez\r CHE (H)",
    "Player_5": "Pedro Porro\r AVL (H)",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Mazraoui\r CHE (H)",
    "Player_4": "Saliba\r 2",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "M.Salah\r 18",
    "Player_15": "Van de Ven\r AVL (H)"
  },
  {
    "manager_Name": "551( 2,147,278 ) TotalXfr : 7",
    "Teams": "Los Blancos( Eamonn Mifsud )",
    "SXL": "MT",
    "Latp": "11",
    "Player_1": "Raya\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "Solanke\r AVL (H)",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Konsa\r TOT (A)",
    "Player_14": "Van den Berg\r FUL (A)",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "A\u00EFt-Nouri\r 1",
    "Player_5": "Rogers\r TOT (A)",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Lewis\r 1",
    "Player_8": "Son\r AVL (H)",
    "Player_9": "Ra\u00FAl\r BRE (H)",
    "Player_15": "Dibling\r 0"
  },
  {
    "manager_Name": "561( 1,651,921 ) TotalXfr : 11",
    "Teams": "LxFxC( Ervin Rigo )",
    "SXL": "MT",
    "Latp": "48",
    "Player_1": "Jos\u00E9 S\u00E1\r 2",
    "Player_11": "Isak\r 9",
    "Player_10": "Wissa\r FUL (A)",
    "Player_12": "Pope\r 5",
    "Player_13": "Welbeck\r 5",
    "Player_14": "Pedro Porro\r AVL (H)",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Justin\r 0",
    "Player_5": "Semenyo\r 10",
    "Player_6": "Bowen\r 2",
    "Player_3": "Virgil\r 5",
    "Player_4": "Saliba\r 2",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Palmer\r MUN (A)",
    "Player_15": "Digne\r TOT (A)"
  },
  {
    "manager_Name": "548( 2,305,981 ) TotalXfr : 2",
    "Teams": "Notified( Edd Eddie )",
    "SXL": "KE",
    "Latp": "24",
    "Player_1": "A.Becker\r 0",
    "Player_11": "Havertz\r 1",
    "Player_10": "Watkins\r TOT (A)",
    "Player_12": "Turner\r 0",
    "Player_13": "Taylor\r 0",
    "Player_14": "Christie\r 2",
    "Player_7": "Palmer\r MUN (A)",
    "Player_2": "White\r 1",
    "Player_5": "Virgil\r 5",
    "Player_6": "Saka\r 2",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Mitchell\r 1",
    "Player_8": "Luis D\u00EDaz\r 2",
    "Player_9": "Welbeck\r 5",
    "Player_15": "Kudus\r 0"
  },
  {
    "manager_Name": "548( 2,324,316 ) TotalXfr : 8",
    "Teams": "Maniacs( Alvaro Garcia )",
    "SXL": "MT",
    "Latp": "25",
    "Player_1": "Onana\r CHE (H)",
    "Player_11": "Welbeck\r 5",
    "Player_10": "Haaland\r 4",
    "Player_12": "Raya\r 3",
    "Player_13": "Golding\r 0",
    "Player_14": "Antonio\r 1",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Konat\u00E9\r 1",
    "Player_5": "Gvardiol\r 7",
    "Player_6": "Georginio\r 2",
    "Player_3": "Virgil\r 5",
    "Player_4": "Dalot\r CHE (H)",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Palmer\r MUN (A)",
    "Player_15": "Andersen\r BRE (H)"
  },
  {
    "manager_Name": "552( 2,109,675 ) TotalXfr : 9",
    "Teams": "Kinder Mbeumo( Gerson Seguna )",
    "SXL": "MT",
    "Latp": "27",
    "Player_1": "Raya\r 3",
    "Player_11": "Wissa\r FUL (A)",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Harwood-Bellis\r 6",
    "Player_14": "Rogers\r TOT (A)",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Palmer\r MUN (A)",
    "Player_6": "Saka\r 2",
    "Player_3": "Konsa\r TOT (A)",
    "Player_4": "Robinson\r BRE (H)",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Ra\u00FAl\r BRE (H)",
    "Player_15": "Andersen\r BRE (H)"
  },
  {
    "manager_Name": "553( 2,054,834 ) TotalXfr : 9",
    "Teams": "Crvena Zvezda( Dejan Mrdanov )",
    "SXL": "MT",
    "Latp": "37",
    "Player_1": "Raya\r 3",
    "Player_11": "Wood\r 7",
    "Player_10": "Solanke\r AVL (H)",
    "Player_12": "Areola\r 0",
    "Player_13": "Tarkowski\r 1",
    "Player_14": "Colwill\r MUN (A)",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Digne\r TOT (A)",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Garnacho\r CHE (H)",
    "Player_3": "Pedro Porro\r AVL (H)",
    "Player_4": "Gabriel\r 2",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Cunha\r 6",
    "Player_15": "Eze\r 0"
  },
  {
    "manager_Name": "548( 2,345,134 ) TotalXfr : 10",
    "Teams": "Gidia KK( Aggelos Flamiatos )",
    "SXL": "GR",
    "Latp": "21",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Solanke\r AVL (H)",
    "Player_12": "Verbruggen\r 3",
    "Player_13": "Welbeck\r 5",
    "Player_14": "Saliba\r 2",
    "Player_7": "Rogers\r TOT (A)",
    "Player_2": "Robinson\r BRE (H)",
    "Player_5": "Smith Rowe\r BRE (H)",
    "Player_6": "McNeil\r 2",
    "Player_3": "Lewis\r 1",
    "Player_4": "Virgil\r 5",
    "Player_8": "M.Salah\r 9",
    "Player_9": "Mbeumo\r FUL (A)",
    "Player_15": "Burn\r 6"
  },
  {
    "manager_Name": "546( 2,423,843 ) TotalXfr : 4",
    "Teams": "Nachos( Melvin Xuereb )",
    "SXL": "MT",
    "Latp": "17",
    "Player_1": "Areola\r 0",
    "Player_11": "Haaland\r 4",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Semenyo\r 10",
    "Player_14": "Estupi\u00F1an\r 1",
    "Player_7": "M.Salah\r 9",
    "Player_2": "Mazraoui\r CHE (H)",
    "Player_5": "Eze\r 0",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Andersen\r BRE (H)",
    "Player_4": "Saliba\r 2",
    "Player_8": "Onana\r TOT (A)",
    "Player_9": "Ra\u00FAl\r BRE (H)",
    "Player_15": "Faes\r 2"
  },
  {
    "manager_Name": "545( 2,498,352 ) TotalXfr : 8",
    "Teams": "Red Tigers FC( George Vepkhvadze )",
    "SXL": "GE",
    "Latp": "33",
    "Player_1": "Pope\r 5",
    "Player_11": "Havertz\r 1",
    "Player_10": "Wood\r 7",
    "Player_12": "Arrizabalaga\r 0",
    "Player_13": "Semenyo\r 10",
    "Player_14": "Gordon\r 6",
    "Player_7": "Bowen\r 2",
    "Player_2": "Van den Berg\r FUL (A)",
    "Player_5": "Kerkez\r 9",
    "Player_6": "Saka\r 4",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Gusto\r MUN (A)",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "Haaland\r 2",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "541( 2,730,466 ) TotalXfr : 7",
    "Teams": "Joga Bonito( Christophe Peixoto )",
    "SXL": "HU",
    "Latp": "12",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Solanke\r AVL (H)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Flekken\r FUL (A)",
    "Player_13": "Faes\r 2",
    "Player_14": "Colwill\r MUN (A)",
    "Player_7": "Johnson\r AVL (H)",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Smith Rowe\r BRE (H)",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Pedro Porro\r AVL (H)",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Calvert-Lewin\r 2",
    "Player_15": "Semenyo\r 10"
  },
  {
    "manager_Name": "540( 2,791,281 ) TotalXfr : 7",
    "Teams": "St Peters FC( Clayton Borda )",
    "SXL": "MT",
    "Latp": "22",
    "Player_1": "Pope\r 5",
    "Player_11": "Mateta\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Andersen\r BRE (H)",
    "Player_14": "Chiwome\r 0",
    "Player_7": "Palmer\r MUN (A)",
    "Player_2": "Burn\r 6",
    "Player_5": "B.Fernandes\r CHE (H)",
    "Player_6": "Bruno G.\r 3",
    "Player_3": "Konsa\r TOT (A)",
    "Player_4": "De Ligt\r CHE (H)",
    "Player_8": "Saka\r 2",
    "Player_9": "Smith Rowe\r BRE (H)",
    "Player_15": "Kristiansen\r 2"
  },
  {
    "manager_Name": "542( 2,688,371 ) TotalXfr : 9",
    "Teams": "Rekegutt United( Eirik Presttun )",
    "SXL": "MT",
    "Latp": "28",
    "Player_1": "Henderson\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "N.Jackson\r MUN (A)",
    "Player_12": "S\u00E1nchez\r MUN (A)",
    "Player_13": "Taylor\r 0",
    "Player_14": "Dibling\r 0",
    "Player_7": "Matheus N.\r 2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Eze\r 0",
    "Player_6": "M.Salah\r 9",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Faes\r 2",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Ra\u00FAl\r BRE (H)",
    "Player_15": "Mazraoui\r CHE (H)"
  },
  {
    "manager_Name": "542( 2,677,330 ) TotalXfr : 8",
    "Teams": "Hakuna Mateta( Jason Evans )",
    "SXL": "MT",
    "Latp": "26",
    "Player_1": "Martinez\r TOT (A)",
    "Player_11": "Jo\u00E3o Pedro\r 0",
    "Player_10": "N.Jackson\r MUN (A)",
    "Player_12": "Turner\r 0",
    "Player_13": "Eze\r 0",
    "Player_14": "Barco\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Mitoma\r 2",
    "Player_6": "Rogers\r TOT (A)",
    "Player_3": "Saliba\r 2",
    "Player_4": "Romero\r AVL (H)",
    "Player_8": "Carvalho\r FUL (A)",
    "Player_9": "Haaland\r 2",
    "Player_15": "Thomas\r 0"
  },
  {
    "manager_Name": "539( 2,852,254 ) TotalXfr : 7",
    "Teams": "HUNdorito( Adam Rajki )",
    "SXL": "HU",
    "Latp": "35",
    "Player_1": "Raya\r 3",
    "Player_11": "Ra\u00FAl\r BRE (H)",
    "Player_10": "Wood\r 7",
    "Player_12": "Turner\r 0",
    "Player_13": "Nelson\r BRE (H)",
    "Player_14": "Winks\r 2",
    "Player_7": "M.Salah\r 9",
    "Player_2": "Pedro Porro\r AVL (H)",
    "Player_5": "Calafiori\r 0",
    "Player_6": "Szoboszlai\r 2",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Saliba\r 2",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "Haaland\r 4",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "536( 3,044,666 ) TotalXfr : 8",
    "Teams": "FC Qvantas( Johan Hammarstrom )",
    "SXL": "SE",
    "Latp": "15",
    "Player_1": "Raya\r 3",
    "Player_11": "Watkins\r TOT (A)",
    "Player_10": "Haaland\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Winks\r 2",
    "Player_14": "Burn\r 6",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Saliba\r 2",
    "Player_5": "Johnson\r AVL (H)",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Keane\r 1",
    "Player_4": "Faes\r 2",
    "Player_8": "Smith Rowe\r BRE (H)",
    "Player_9": "Welbeck\r 5",
    "Player_15": "Gabriel\r 2"
  },
  {
    "manager_Name": "534( 3,154,433 ) TotalXfr : 5",
    "Teams": "Matteo fc( Matteo Vella )",
    "SXL": "MT",
    "Latp": "12",
    "Player_1": "Raya\r 3",
    "Player_11": "Watkins\r TOT (A)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Barco\r 0",
    "Player_14": "Jo\u00E3o Pedro\r 0",
    "Player_7": "Rogers\r TOT (A)",
    "Player_2": "Pedro Porro\r AVL (H)",
    "Player_5": "Saka\r 2",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Konsa\r TOT (A)",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Andreas\r BRE (H)",
    "Player_15": "Okoli\r 0"
  },
  {
    "manager_Name": "536( 3,044,666 ) TotalXfr : 8",
    "Teams": "Massilia( Daniel Borg )",
    "SXL": "MT",
    "Latp": "22",
    "Player_1": "Martinez\r TOT (A)",
    "Player_11": "Haaland\r 4",
    "Player_10": "N.Jackson\r MUN (A)",
    "Player_12": "Flekken\r FUL (A)",
    "Player_13": "Aina\r 15",
    "Player_14": "Konsa\r TOT (A)",
    "Player_7": "Rogers\r TOT (A)",
    "Player_2": "A\u00EFt-Nouri\r 1",
    "Player_5": "Smith Rowe\r BRE (H)",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Virgil\r 5",
    "Player_4": "Keane\r 1",
    "Player_8": "M.Salah\r 9",
    "Player_9": "Delap\r 2",
    "Player_15": "Semenyo\r 10"
  },
  {
    "manager_Name": "536( 3,032,889 ) TotalXfr : 6",
    "Teams": "Rolling Fernander( Adam Ruggier )",
    "SXL": "MT",
    "Latp": "22",
    "Player_1": "Raya\r 3",
    "Player_11": "Haaland\r 2",
    "Player_10": "Solanke\r AVL (H)",
    "Player_12": "Turner\r 0",
    "Player_13": "Harwood-Bellis\r 6",
    "Player_14": "Barco\r 0",
    "Player_7": "Palmer\r MUN (A)",
    "Player_2": "Konat\u00E9\r 1",
    "Player_5": "Diogo J.\r 0",
    "Player_6": "Semenyo\r 10",
    "Player_3": "Saliba\r 2",
    "Player_4": "Gabriel\r 2",
    "Player_8": "McNeil\r 2",
    "Player_9": "N.Jackson\r MUN (A)",
    "Player_15": "Sangar\u00E9\r 0"
  },
  {
    "manager_Name": "536( 3,044,666 ) TotalXfr : 8",
    "Teams": "FC Lokomotiv Sliema( Philip H\u00E5kansson )",
    "SXL": "MT",
    "Latp": "33",
    "Player_1": "Raya\r 3",
    "Player_11": "Solanke\r AVL (H)",
    "Player_10": "Haaland\r 2",
    "Player_12": "Valdimarsson\r FUL (A)",
    "Player_13": "Strand Larsen\r 8",
    "Player_14": "Romero\r AVL (H)",
    "Player_7": "Rogers\r TOT (A)",
    "Player_2": "Virgil\r 5",
    "Player_5": "Johnson\r AVL (H)",
    "Player_6": "Garnacho\r CHE (H)",
    "Player_3": "Faes\r 2",
    "Player_4": "Lewis\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Bowen\r 2",
    "Player_15": "Harwood-Bellis\r 6"
  },
  {
    "manager_Name": "532( 3,314,528 ) TotalXfr : 10",
    "Teams": "\u0106umura\u0161i( Aleksandar Deletic )",
    "SXL": "RS",
    "Latp": "25",
    "Player_1": "Raya\r 3",
    "Player_11": "Wood\r 7",
    "Player_10": "Watkins\r TOT (A)",
    "Player_12": "S\u00E1nchez\r MUN (A)",
    "Player_13": "Bailey\r TOT (A)",
    "Player_14": "Coufal\r 0",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Virgil\r 10",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Digne\r TOT (A)",
    "Player_4": "Andersen\r BRE (H)",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Saka\r 2",
    "Player_15": "Welbeck\r 5"
  },
  {
    "manager_Name": "534( 3,179,995 ) TotalXfr : 9",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "IN",
    "Latp": "27",
    "Player_1": "Henderson\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Havertz\r 1",
    "Player_12": "Fabianski\r 2",
    "Player_13": "W.Fofana\r MUN (A)",
    "Player_14": "Ajer\r FUL (A)",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Keane\r 1",
    "Player_5": "Dibling\r 0",
    "Player_6": "Smith Rowe\r BRE (H)",
    "Player_3": "Faes\r 2",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "Johnson\r AVL (H)",
    "Player_15": "Wheatley\r CHE (H)"
  },
  {
    "manager_Name": "533( 3,207,883 ) TotalXfr : 0",
    "Teams": "Pierosson( Pietro Ramellini )",
    "SXL": "MT",
    "Latp": "29",
    "Player_1": "A.Becker\r 0",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "Kelleher\r 3",
    "Player_13": "Ajer\r FUL (A)",
    "Player_14": "Eze\r 0",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Van Hecke\r 1",
    "Player_5": "Justin\r 0",
    "Player_6": "Kudus\r 0",
    "Player_3": "Aina\r 15",
    "Player_4": "Martinez\r CHE (H)",
    "Player_8": "Kulusevski\r AVL (H)",
    "Player_9": "Bernardo\r 2",
    "Player_15": "Isak\r 9"
  },
  {
    "manager_Name": "529( 3,475,342 ) TotalXfr : 7",
    "Teams": "Mimz( Emma Zammit )",
    "SXL": "MT",
    "Latp": "21",
    "Player_1": "Pickford\r 2",
    "Player_11": "Duran\r TOT (A)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Turner\r 0",
    "Player_13": "Sou\u010Dek\r 0",
    "Player_14": "Faes\r 2",
    "Player_7": "Eze\r 0",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Palmer\r MUN (A)",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Martinez\r CHE (H)",
    "Player_8": "McNeil\r 2",
    "Player_9": "Isak\r 9",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "523( 3,835,229 ) TotalXfr : 0",
    "Teams": "KAMACIO FC( Francisco Camacho )",
    "SXL": "MT",
    "Latp": "19",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Watkins\r TOT (A)",
    "Player_10": "Havertz\r 1",
    "Player_12": "Areola\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 0",
    "Player_14": "Hill\r 0",
    "Player_7": "Foden\r 2",
    "Player_2": "Mykolenko\r 2",
    "Player_5": "Bowen\r 2",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Saliba\r 2",
    "Player_4": "Pedro Porro\r AVL (H)",
    "Player_8": "Saka\r 2",
    "Player_9": "Gordon\r 6",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "526( 3,671,327 ) TotalXfr : 8",
    "Teams": "Nketiah_\u0393\u03B1\u03C1\u03BC\u03C0\u03AE( Dimitris Tselikas )",
    "SXL": "GR",
    "Latp": "25",
    "Player_1": "Areola\r 0",
    "Player_11": "Haaland\r 2",
    "Player_10": "Solanke\r AVL (H)",
    "Player_12": "Flekken\r FUL (A)",
    "Player_13": "Faes\r 2",
    "Player_14": "Digne\r TOT (A)",
    "Player_7": "Bernardo\r 2",
    "Player_2": "Pedro Porro\r AVL (H)",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Smith Rowe\r BRE (H)",
    "Player_3": "Lewis\r 1",
    "Player_4": "Robertson\r 0",
    "Player_8": "Garnacho\r CHE (H)",
    "Player_9": "Archer\r 2",
    "Player_15": "Tavernier\r 2"
  },
  {
    "manager_Name": "520( 4,049,085 ) TotalXfr : 8",
    "Teams": "Bruno Fernax FC( Chris Zammit )",
    "SXL": "MT",
    "Latp": "24",
    "Player_1": "Pope\r 5",
    "Player_11": "Haaland\r 2",
    "Player_10": "Vardy\r 5",
    "Player_12": "S\u00E1nchez\r MUN (A)",
    "Player_13": "Onana\r TOT (A)",
    "Player_14": "Livramento\r 7",
    "Player_7": "Smith Rowe\r BRE (H)",
    "Player_2": "Mazraoui\r CHE (H)",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Son\r AVL (H)",
    "Player_3": "Lewis\r 1",
    "Player_4": "Harwood-Bellis\r 6",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "Welbeck\r 5",
    "Player_15": "Van de Ven\r AVL (H)"
  },
  {
    "manager_Name": "518( 4,163,427 ) TotalXfr : 6",
    "Teams": "Korta All Stars( Magnus Hammerstad )",
    "SXL": "MT",
    "Latp": "32",
    "Player_1": "Raya\r 3",
    "Player_11": "Watkins\r TOT (A)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Enzo\r MUN (A)",
    "Player_14": "Dalot\r CHE (H)",
    "Player_7": "Kulusevski\r AVL (H)",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Semenyo\r 10",
    "Player_6": "Rogers\r TOT (A)",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Burn\r 6",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "Vardy\r 5",
    "Player_15": "Robinson\r BRE (H)"
  },
  {
    "manager_Name": "514( 4,404,051 ) TotalXfr : 3",
    "Teams": "Unseen Academicals( Kurt Bugeja Coster )",
    "SXL": "MT",
    "Latp": "9",
    "Player_1": "Ederson M.\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Wissa\r FUL (A)",
    "Player_12": "Areola\r 0",
    "Player_13": "Trippier\r 0",
    "Player_14": "Jo\u00E3o Pedro\r 0",
    "Player_7": "Eze\r 0",
    "Player_2": "Estupi\u00F1an\r 1",
    "Player_5": "Pedro Porro\r AVL (H)",
    "Player_6": "Onana\r TOT (A)",
    "Player_3": "Chilwell\r MUN (A)",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "Mbeumo\r FUL (A)",
    "Player_15": "Saka\r 2"
  }
];