var s = [
  {
    "manager_Name": "698( 151 ) TotalXfr : 8",
    "Teams": "Child \u26BDF Prophecy( Roshane Simpson )",
    "SXL": "JM",
    "Latp": "55",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r MUN (A)",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Harwood-Bellis\r 6",
    "Player_14": "Winks\r 2",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Aina\r 15",
    "Player_5": "Rogers\r TOT (A)",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Virgil\r 5",
    "Player_4": "Gvardiol\r 7",
    "Player_8": "Foden\r 2",
    "Player_9": "Ra\u00FAl\r BRE (H)",
    "Player_15": "Faes\r 2"
  },
  {
    "manager_Name": "697( 163 ) TotalXfr : 7",
    "Teams": "Cyprian_Utd( Cyprian Peter )",
    "SXL": "NG",
    "Latp": "57",
    "Player_1": "Onana\r CHE (H)",
    "Player_11": "Welbeck\r 5",
    "Player_10": "Watkins\r TOT (A)",
    "Player_12": "Raya\r 3",
    "Player_13": "Faes\r 2",
    "Player_14": "Amad\r CHE (H)",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Saka\r 2",
    "Player_3": "Alexander-Arnold\r 2",
    "Player_4": "Aina\r 15",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Wood\r 7",
    "Player_15": "Mazraoui\r CHE (H)"
  },
  {
    "manager_Name": "696( 182 ) TotalXfr : 7",
    "Teams": "Arne Slotmachine( Wayne Jenkinson )",
    "SXL": "AU",
    "Latp": "50",
    "Player_1": "Henderson\r 2",
    "Player_11": "Havertz\r 1",
    "Player_10": "Wood\r 7",
    "Player_12": "Flekken\r FUL (A)",
    "Player_13": "Van den Berg\r FUL (A)",
    "Player_14": "Jo\u00E3o Pedro\r 0",
    "Player_7": "Foden\r 2",
    "Player_2": "Robinson\r BRE (H)",
    "Player_5": "McNeil\r 2",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "M.Salah\r 27",
    "Player_9": "Palmer\r MUN (A)",
    "Player_15": "Nedeljkovic\r TOT (A)"
  },
  {
    "manager_Name": "695( 207 ) TotalXfr : 8",
    "Teams": "Ian\u0027s Idiots( ian scott )",
    "SXL": "S1",
    "Latp": "45",
    "Player_1": "Ramsdale\r 8",
    "Player_11": "Watkins\r TOT (A)",
    "Player_10": "N.Jackson\r MUN (A)",
    "Player_12": "Flekken\r FUL (A)",
    "Player_13": "Robinson\r BRE (H)",
    "Player_14": "Harwood-Bellis\r 6",
    "Player_7": "Palmer\r MUN (A)",
    "Player_2": "Gabriel\r 2",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "A\u00EFt-Nouri\r 1",
    "Player_8": "Bernardo\r 2",
    "Player_9": "Wood\r 7",
    "Player_15": "Rogers\r TOT (A)"
  },
  {
    "manager_Name": "694( 220 ) TotalXfr : 7",
    "Teams": "Charlie\u2019s team( Charlie Shepherd )",
    "SXL": "EN",
    "Latp": "34",
    "Player_1": "Raya\r 3",
    "Player_11": "Delap\r 2",
    "Player_10": "Cunha\r 6",
    "Player_12": "Dennis\r 0",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Konsa\r TOT (A)",
    "Player_7": "Palmer\r MUN (A)",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Foden\r 2",
    "Player_3": "Robinson\r BRE (H)",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Watkins\r TOT (A)",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "694( 220 ) TotalXfr : 7",
    "Teams": "Stop War In Sudan( Mustafa Diouf \uD83C\uDDF8\uD83C\uDDE9\uD83D\uDC94 )",
    "SXL": "SD",
    "Latp": "55",
    "Player_1": "Kelleher\r 3",
    "Player_11": "Wood\r 7",
    "Player_10": "Cunha\r 6",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Keane\r 1",
    "Player_14": "Van den Berg\r FUL (A)",
    "Player_7": "Palmer\r MUN (A)",
    "Player_2": "A\u00EFt-Nouri\r 1",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "McNeil\r 2",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "Aina\r 15",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Haaland\r 2",
    "Player_15": "M.Fran\u00E7a\r 0"
  },
  {
    "manager_Name": "692( 267 ) TotalXfr : 8",
    "Teams": "Inter-bred( ashley whomes )",
    "SXL": "WA",
    "Latp": "51",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Keane\r 1",
    "Player_14": "Winks\r 2",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Alexander-Arnold\r 2",
    "Player_6": "Saka\r 2",
    "Player_3": "A\u00EFt-Nouri\r 1",
    "Player_4": "Aina\r 15",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "McNeil\r 2",
    "Player_15": "Chiwome\r 0"
  },
  {
    "manager_Name": "689( 385 ) TotalXfr : 10",
    "Teams": "Levenshulme Utd( Max Littleproud )",
    "SXL": "EN",
    "Latp": "31",
    "Player_1": "S\u00E1nchez\r MUN (A)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r TOT (A)",
    "Player_12": "Matthews\r 0",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Gabriel\r 2",
    "Player_7": "McNeil\r 2",
    "Player_2": "A\u00EFt-Nouri\r 1",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Son\r AVL (H)",
    "Player_3": "Young\r 2",
    "Player_4": "Aina\r 15",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "Wood\r 7",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "688( 418 ) TotalXfr : 9",
    "Teams": "Blue Order Remix( Matthew Davies )",
    "SXL": "EN",
    "Latp": "44",
    "Player_1": "Sels\r 6",
    "Player_11": "Haaland\r 2",
    "Player_10": "Ra\u00FAl\r BRE (H)",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Pau\r TOT (A)",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Keane\r 1",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "McNeil\r 2",
    "Player_3": "A\u00EFt-Nouri\r 1",
    "Player_4": "Gvardiol\r 7",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "Wood\r 7",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "688( 418 ) TotalXfr : 9",
    "Teams": "Merchants of Chaos( Zephyr Brown )",
    "SXL": "NZ",
    "Latp": "54",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r MUN (A)",
    "Player_10": "Wood\r 7",
    "Player_12": "Muric\r 2",
    "Player_13": "McNeil\r 2",
    "Player_14": "Gabriel\r 2",
    "Player_7": "M.Salah\r 18",
    "Player_2": "A\u00EFt-Nouri\r 1",
    "Player_5": "Son\r AVL (H)",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Alexander-Arnold\r 2",
    "Player_4": "Aina\r 15",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Welbeck\r 5",
    "Player_15": "Faes\r 2"
  },
  {
    "manager_Name": "686( 524 ) TotalXfr : 10",
    "Teams": "druMMer bOYs unITed( Kwaku Ankama-Asamoah )",
    "SXL": "US",
    "Latp": "35",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Ra\u00FAl\r BRE (H)",
    "Player_10": "Delap\r 2",
    "Player_12": "S\u00E1nchez\r MUN (A)",
    "Player_13": "Winks\r 2",
    "Player_14": "Harwood-Bellis\r 6",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Rogers\r TOT (A)",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Mykolenko\r 2",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Haaland\r 2",
    "Player_15": "Nedeljkovic\r TOT (A)"
  },
  {
    "manager_Name": "686( 526 ) TotalXfr : 11",
    "Teams": "Joelinton Enjoyer( James White )",
    "SXL": "NZ",
    "Latp": "36",
    "Player_1": "Martinez\r TOT (A)",
    "Player_11": "Wissa\r FUL (A)",
    "Player_10": "Cunha\r 6",
    "Player_12": "Dennis\r 0",
    "Player_13": "Calvert-Lewin\r 2",
    "Player_14": "Collins\r FUL (A)",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Mykolenko\r 2",
    "Player_5": "Palmer\r MUN (A)",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "A\u00EFt-Nouri\r 1",
    "Player_4": "Gvardiol\r 7",
    "Player_8": "B.Fernandes\r CHE (H)",
    "Player_9": "Saka\r 2",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "684( 594 ) TotalXfr : 7",
    "Teams": "Szoboszlai\u2019s Zobo( Ayo Alesh )",
    "SXL": "NG",
    "Latp": "50",
    "Player_1": "S\u00E1nchez\r MUN (A)",
    "Player_11": "Wissa\r FUL (A)",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Harwood-Bellis\r 6",
    "Player_14": "Nedeljkovic\r TOT (A)",
    "Player_7": "McNeil\r 2",
    "Player_2": "A\u00EFt-Nouri\r 1",
    "Player_5": "Foden\r 2",
    "Player_6": "Rogers\r TOT (A)",
    "Player_3": "Aina\r 15",
    "Player_4": "Davis\r 10",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "M.Salah\r 18",
    "Player_15": "Wheatley\r CHE (H)"
  },
  {
    "manager_Name": "683( 644 ) TotalXfr : 7",
    "Teams": "Trust the Process ;)( Robb Lacey )",
    "SXL": "EN",
    "Latp": "34",
    "Player_1": "Johnstone\r 0",
    "Player_11": "Solanke\r AVL (H)",
    "Player_10": "Ndiaye\r 2",
    "Player_12": "Pickford\r 2",
    "Player_13": "Maddison\r AVL (H)",
    "Player_14": "Pinnock\r FUL (A)",
    "Player_7": "Saka\r 2",
    "Player_2": "Mykolenko\r 2",
    "Player_5": "Bowen\r 2",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "A\u00EFt-Nouri\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Watkins\r TOT (A)",
    "Player_15": "Van den Berg\r FUL (A)"
  },
  {
    "manager_Name": "683( 656 ) TotalXfr : 8",
    "Teams": "The Big Breakfast( Blake G )",
    "SXL": "AU",
    "Latp": "49",
    "Player_1": "Raya\r 3",
    "Player_11": "Welbeck\r 5",
    "Player_10": "Wood\r 7",
    "Player_12": "Valdimarsson\r FUL (A)",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Stephens\r 6",
    "Player_7": "Palmer\r MUN (A)",
    "Player_2": "Murillo\r 6",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Smith Rowe\r BRE (H)",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Lewis\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Haaland\r 2",
    "Player_15": "Vestergaard\r 2"
  },
  {
    "manager_Name": "683( 690 ) TotalXfr : 10",
    "Teams": "moh17( Mohammed Lamih )",
    "SXL": "IN",
    "Latp": "44",
    "Player_1": "Sels\r 6",
    "Player_11": "Wissa\r FUL (A)",
    "Player_10": "Haaland\r 4",
    "Player_12": "Bentley\r 0",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Van den Berg\r FUL (A)",
    "Player_7": "M.Salah\r 9",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Smith Rowe\r BRE (H)",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Lewis\r 1",
    "Player_4": "Aina\r 15",
    "Player_8": "Winks\r 2",
    "Player_9": "Vardy\r 5",
    "Player_15": "Harwood-Bellis\r 6"
  },
  {
    "manager_Name": "683( 690 ) TotalXfr : 10",
    "Teams": "Nats County( Manuel Pop )",
    "SXL": "RO",
    "Latp": "43",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r MUN (A)",
    "Player_10": "Wood\r 7",
    "Player_12": "Henderson\r 2",
    "Player_13": "Ndiaye\r 2",
    "Player_14": "Rogers\r TOT (A)",
    "Player_7": "Palmer\r MUN (A)",
    "Player_2": "Pedro Porro\r AVL (H)",
    "Player_5": "Keane\r 1",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Saka\r 2",
    "Player_15": "Faes\r 2"
  },
  {
    "manager_Name": "682( 724 ) TotalXfr : 8",
    "Teams": "lankans Rule( Mulitha De Silva )",
    "SXL": "AU",
    "Latp": "57",
    "Player_1": "Henderson\r 2",
    "Player_11": "Cunha\r 6",
    "Player_10": "Havertz\r 1",
    "Player_12": "Ward\r 0",
    "Player_13": "Robinson\r BRE (H)",
    "Player_14": "Rogers\r TOT (A)",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Aina\r 15",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "Son\r AVL (H)",
    "Player_9": "Wood\r 7",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "680( 888 ) TotalXfr : 8",
    "Teams": "Alpha Squad( Tariq Auguste )",
    "SXL": "AU",
    "Latp": "55",
    "Player_1": "S\u00E1nchez\r MUN (A)",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "Turner\r 0",
    "Player_13": "Welbeck\r 5",
    "Player_14": "Livramento\r 7",
    "Player_7": "Maddison\r AVL (H)",
    "Player_2": "Aina\r 15",
    "Player_5": "McNeil\r 2",
    "Player_6": "M.Salah\r 18",
    "Player_3": "J.Timber\r 1",
    "Player_4": "Davis\r 10",
    "Player_8": "Rashford\r CHE (H)",
    "Player_9": "Mbeumo\r FUL (A)",
    "Player_15": "Van de Ven\r AVL (H)"
  },
  {
    "manager_Name": "678( 1,101 ) TotalXfr : 9",
    "Teams": "MICKY( Michael Adeolu )",
    "SXL": "NG",
    "Latp": "42",
    "Player_1": "Raya\r 3",
    "Player_11": "Vardy\r 5",
    "Player_10": "Wood\r 7",
    "Player_12": "Turner\r 0",
    "Player_13": "Semenyo\r 10",
    "Player_14": "Davis\r 10",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Pedro Porro\r AVL (H)",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Alexander-Arnold\r 2",
    "Player_4": "Gvardiol\r 7",
    "Player_8": "Smith Rowe\r BRE (H)",
    "Player_9": "Watkins\r TOT (A)",
    "Player_15": "Burn\r 6"
  },
  {
    "manager_Name": "678( 1,101 ) TotalXfr : 9",
    "Teams": "Ninja skrtels( Mujahied Dramat )",
    "SXL": "ZA",
    "Latp": "46",
    "Player_1": "S\u00E1nchez\r MUN (A)",
    "Player_11": "Watkins\r TOT (A)",
    "Player_10": "Delap\r 2",
    "Player_12": "Valdimarsson\r FUL (A)",
    "Player_13": "Kerkez\r 9",
    "Player_14": "Pau\r TOT (A)",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Davis\r 10",
    "Player_4": "Gvardiol\r 7",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "Cunha\r 6",
    "Player_15": "McNeil\r 2"
  },
  {
    "manager_Name": "677( 1,143 ) TotalXfr : 6",
    "Teams": "Ahmed7( Ahmed Tarek )",
    "SXL": "EG",
    "Latp": "45",
    "Player_1": "Sels\r 6",
    "Player_11": "Wood\r 7",
    "Player_10": "Haaland\r 2",
    "Player_12": "S\u00E1nchez\r MUN (A)",
    "Player_13": "Faes\r 2",
    "Player_14": "Rogers\r TOT (A)",
    "Player_7": "Palmer\r MUN (A)",
    "Player_2": "A\u00EFt-Nouri\r 1",
    "Player_5": "Konat\u00E9\r 1",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Keane\r 1",
    "Player_8": "McNeil\r 2",
    "Player_9": "M.Salah\r 18",
    "Player_15": "Welbeck\r 5"
  },
  {
    "manager_Name": "677( 1,178 ) TotalXfr : 8",
    "Teams": "FPL_Sarki( Yusuf Muhammad Bello )",
    "SXL": "NG",
    "Latp": "28",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Watkins\r TOT (A)",
    "Player_10": "Ra\u00FAl\r BRE (H)",
    "Player_12": "Verbruggen\r 3",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Calafiori\r 0",
    "Player_7": "Saka\r 2",
    "Player_2": "Veltman\r 1",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Digne\r TOT (A)",
    "Player_4": "Gvardiol\r 7",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "Wissa\r FUL (A)",
    "Player_15": "Faes\r 2"
  },
  {
    "manager_Name": "676( 1,354 ) TotalXfr : 9",
    "Teams": "SC Villa Jogoo( Godfrey Lusiba )",
    "SXL": "UG",
    "Latp": "24",
    "Player_1": "Pickford\r 2",
    "Player_11": "Havertz\r 1",
    "Player_10": "N.Jackson\r MUN (A)",
    "Player_12": "Turner\r 0",
    "Player_13": "Davis\r 10",
    "Player_14": "Dalot\r CHE (H)",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Robinson\r BRE (H)",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Saka\r 2",
    "Player_3": "A\u00EFt-Nouri\r 1",
    "Player_4": "Pedro Porro\r AVL (H)",
    "Player_8": "B.Fernandes\r CHE (H)",
    "Player_9": "Smith Rowe\r BRE (H)",
    "Player_15": "Evanilson\r 8"
  },
  {
    "manager_Name": "675( 1,427 ) TotalXfr : 7",
    "Teams": "TUFC( Talhah Umar )",
    "SXL": "EN",
    "Latp": "47",
    "Player_1": "Pickford\r 2",
    "Player_11": "Wood\r 7",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Mazraoui\r CHE (H)",
    "Player_14": "Faes\r 2",
    "Player_7": "Palmer\r MUN (A)",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Rogers\r TOT (A)",
    "Player_6": "Garnacho\r CHE (H)",
    "Player_3": "A\u00EFt-Nouri\r 1",
    "Player_4": "Aina\r 15",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Mbeumo\r FUL (A)",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "675( 1,427 ) TotalXfr : 7",
    "Teams": "team name( Eli Wood )",
    "SXL": "CA",
    "Latp": "56",
    "Player_1": "Sels\r 6",
    "Player_11": "Watkins\r TOT (A)",
    "Player_10": "Wood\r 7",
    "Player_12": "S\u00E1nchez\r MUN (A)",
    "Player_13": "Adama\r BRE (H)",
    "Player_14": "Digne\r TOT (A)",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Aina\r 15",
    "Player_5": "Palmer\r MUN (A)",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Lewis\r 1",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Foden\r 2",
    "Player_9": "Vardy\r 5",
    "Player_15": "O\u0027Shea\r 2"
  },
  {
    "manager_Name": "675( 1,452 ) TotalXfr : 8",
    "Teams": "werbnahpets( Stephan Brew )",
    "SXL": "GH",
    "Latp": "32",
    "Player_1": "Pickford\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wissa\r FUL (A)",
    "Player_12": "Flekken\r FUL (A)",
    "Player_13": "Winks\r 2",
    "Player_14": "Robinson\r BRE (H)",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Lewis\r 1",
    "Player_5": "Rogers\r TOT (A)",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Faes\r 2",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "Ra\u00FAl\r BRE (H)",
    "Player_15": "Konsa\r TOT (A)"
  },
  {
    "manager_Name": "674( 1,547 ) TotalXfr : 5",
    "Teams": "Legend fc( Umar Faruq )",
    "SXL": "NG",
    "Latp": "43",
    "Player_1": "Raya\r 3",
    "Player_11": "Vardy\r 5",
    "Player_10": "Haaland\r 4",
    "Player_12": "S\u00E1nchez\r MUN (A)",
    "Player_13": "Faes\r 2",
    "Player_14": "Mazraoui\r CHE (H)",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Dalot\r CHE (H)",
    "Player_5": "M.Salah\r 9",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Robinson\r BRE (H)",
    "Player_4": "Aina\r 15",
    "Player_8": "McNeil\r 2",
    "Player_9": "Welbeck\r 5",
    "Player_15": "Rogers\r TOT (A)"
  },
  {
    "manager_Name": "674( 1,590 ) TotalXfr : 8",
    "Teams": "Deez Nutmegs( Geoffrey Langham )",
    "SXL": "US",
    "Latp": "37",
    "Player_1": "Sels\r 6",
    "Player_11": "Wood\r 7",
    "Player_10": "Wissa\r FUL (A)",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Solanke\r AVL (H)",
    "Player_14": "Aina\r 15",
    "Player_7": "Saka\r 2",
    "Player_2": "Lewis\r 1",
    "Player_5": "Johnson\r AVL (H)",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Gabriel\r 2",
    "Player_4": "A\u00EFt-Nouri\r 1",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "M.Salah\r 18",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "674( 1,637 ) TotalXfr : 9",
    "Teams": "For CHRIST Sake( Chris Eva )",
    "SXL": "EN",
    "Latp": "47",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Welbeck\r 5",
    "Player_10": "Wood\r 7",
    "Player_12": "Ramsdale\r 8",
    "Player_13": "Smith Rowe\r BRE (H)",
    "Player_14": "Konsa\r TOT (A)",
    "Player_7": "Georginio\r 2",
    "Player_2": "Young\r 2",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Saka\r 2",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Faes\r 2",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Haaland\r 2",
    "Player_15": "Tuanzebe\r 0"
  },
  {
    "manager_Name": "674( 1,689 ) TotalXfr : 12",
    "Teams": "adham el moftry 1( Adham Karama )",
    "SXL": "EG",
    "Latp": "44",
    "Player_1": "Sels\r 6",
    "Player_11": "Cunha\r 6",
    "Player_10": "Wood\r 7",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Van den Berg\r FUL (A)",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Lewis\r 1",
    "Player_5": "McNeil\r 2",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "A\u00EFt-Nouri\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Haaland\r 2",
    "Player_15": "Faes\r 2"
  },
  {
    "manager_Name": "673( 1,714 ) TotalXfr : 7",
    "Teams": "Mickey( Vladimir Petrov )",
    "SXL": "MK",
    "Latp": "37",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r TOT (A)",
    "Player_12": "Turner\r 0",
    "Player_13": "Winks\r 2",
    "Player_14": "Faes\r 2",
    "Player_7": "Rogers\r TOT (A)",
    "Player_2": "Konat\u00E9\r 1",
    "Player_5": "Palmer\r MUN (A)",
    "Player_6": "M.Salah\r 9",
    "Player_3": "Aina\r 15",
    "Player_4": "Lewis\r 1",
    "Player_8": "Bernardo\r 2",
    "Player_9": "Welbeck\r 5",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "673( 1,714 ) TotalXfr : 7",
    "Teams": "Maadwiz\uFFFD( Maada Moiwah Ansumana )",
    "SXL": "SL",
    "Latp": "60",
    "Player_1": "Pickford\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Semenyo\r 10",
    "Player_14": "Rogers\r TOT (A)",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "A\u00EFt-Nouri\r 1",
    "Player_6": "McNeil\r 2",
    "Player_3": "Dalot\r CHE (H)",
    "Player_4": "Aina\r 15",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Cunha\r 6",
    "Player_15": "Harwood-Bellis\r 6"
  },
  {
    "manager_Name": "673( 1,806 ) TotalXfr : 9",
    "Teams": "Invisibles\u26BD\uFE0F( Ikenna Godslove )",
    "SXL": "NG",
    "Latp": "31",
    "Player_1": "Martinez\r TOT (A)",
    "Player_11": "Watkins\r TOT (A)",
    "Player_10": "Welbeck\r 5",
    "Player_12": "Matthews\r 0",
    "Player_13": "Mazraoui\r CHE (H)",
    "Player_14": "Andersen\r BRE (H)",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Rogers\r TOT (A)",
    "Player_3": "Lewis\r 1",
    "Player_4": "J.Timber\r 1",
    "Player_8": "McNeil\r 2",
    "Player_9": "Saka\r 2",
    "Player_15": "Wheatley\r CHE (H)"
  },
  {
    "manager_Name": "673( 1,806 ) TotalXfr : 9",
    "Teams": "Womp, womp.( Stephen Blakemore )",
    "SXL": "EN",
    "Latp": "39",
    "Player_1": "Pickford\r 2",
    "Player_11": "Cunha\r 6",
    "Player_10": "Wissa\r FUL (A)",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Mykolenko\r 2",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Lewis\r 1",
    "Player_5": "Palmer\r MUN (A)",
    "Player_6": "Johnson\r AVL (H)",
    "Player_3": "Robinson\r BRE (H)",
    "Player_4": "Davis\r 10",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Haaland\r 2",
    "Player_15": "Dunk\r 0"
  },
  {
    "manager_Name": "672( 1,925 ) TotalXfr : 8",
    "Teams": "Boom Xhakalala( Karol Pinczynski )",
    "SXL": "EN",
    "Latp": "33",
    "Player_1": "Henderson\r 2",
    "Player_11": "Wissa\r FUL (A)",
    "Player_10": "Vardy\r 5",
    "Player_12": "Turner\r 0",
    "Player_13": "Smith Rowe\r BRE (H)",
    "Player_14": "Faes\r 2",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Saka\r 2",
    "Player_6": "Rogers\r TOT (A)",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "Keane\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Haaland\r 2",
    "Player_15": "Harwood-Bellis\r 6"
  },
  {
    "manager_Name": "672( 1,972 ) TotalXfr : 9",
    "Teams": "whitepanther( Oyefusi Wisdom )",
    "SXL": "NG",
    "Latp": "51",
    "Player_1": "Sels\r 6",
    "Player_11": "Haaland\r 2",
    "Player_10": "Strand Larsen\r 8",
    "Player_12": "Flekken\r FUL (A)",
    "Player_13": "Dibling\r 0",
    "Player_14": "Mykolenko\r 2",
    "Player_7": "Semenyo\r 10",
    "Player_2": "A\u00EFt-Nouri\r 1",
    "Player_5": "M.Salah\r 18",
    "Player_6": "McNeil\r 2",
    "Player_3": "Alexander-Arnold\r 2",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "Ra\u00FAl\r BRE (H)",
    "Player_15": "Harwood-Bellis\r 6"
  },
  {
    "manager_Name": "671( 2,074 ) TotalXfr : 7",
    "Teams": "FreakySlugKicks( Hugo Beattie )",
    "SXL": "EN",
    "Latp": "41",
    "Player_1": "Raya\r 3",
    "Player_11": "Cunha\r 6",
    "Player_10": "Wood\r 7",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Welbeck\r 5",
    "Player_14": "Digne\r TOT (A)",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Saka\r 2",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "A\u00EFt-Nouri\r 1",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "Rogers\r TOT (A)",
    "Player_15": "Stephens\r 6"
  },
  {
    "manager_Name": "671( 2,119 ) TotalXfr : 8",
    "Teams": "NZS United( Maksim Tsurkov )",
    "SXL": "AZ",
    "Latp": "37",
    "Player_1": "Raya\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "Wood\r 7",
    "Player_12": "Pickford\r 2",
    "Player_13": "McNeil\r 2",
    "Player_14": "Hall\r 8",
    "Player_7": "Palmer\r MUN (A)",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Smith Rowe\r BRE (H)",
    "Player_6": "Hudson-Odoi\r 10",
    "Player_3": "Davis\r 10",
    "Player_4": "Pedro Porro\r AVL (H)",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "N.Jackson\r MUN (A)",
    "Player_15": "Mazraoui\r CHE (H)"
  },
  {
    "manager_Name": "671( 2,119 ) TotalXfr : 8",
    "Teams": "TheDutchMilkmans( Fontaine A )",
    "SXL": "AU",
    "Latp": "43",
    "Player_1": "Raya\r 3",
    "Player_11": "Wood\r 7",
    "Player_10": "Haaland\r 2",
    "Player_12": "Matthews\r 0",
    "Player_13": "Aina\r 15",
    "Player_14": "Solanke\r AVL (H)",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "McNeil\r 2",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Alexander-Arnold\r 2",
    "Player_4": "Lewis\r 1",
    "Player_8": "Buonanotte\r 1",
    "Player_9": "Rogers\r TOT (A)",
    "Player_15": "Faes\r 2"
  },
  {
    "manager_Name": "671( 2,249 ) TotalXfr : 10",
    "Teams": "rhys( Rhys Hancock )",
    "SXL": "EN",
    "Latp": "53",
    "Player_1": "Flekken\r FUL (A)",
    "Player_11": "Haaland\r 4",
    "Player_10": "Vardy\r 5",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Welbeck\r 5",
    "Player_14": "Aina\r 15",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Gu\u00E9hi\r 7",
    "Player_5": "Keane\r 1",
    "Player_6": "Buonanotte\r 1",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "Faes\r 2",
    "Player_8": "M.Salah\r 9",
    "Player_9": "Palmer\r MUN (A)",
    "Player_15": "Luis D\u00EDaz\r 1"
  },
  {
    "manager_Name": "671( 2,272 ) TotalXfr : 11",
    "Teams": "FC Spartak Liverpool( Adam \u00C1gh )",
    "SXL": "SK",
    "Latp": "36",
    "Player_1": "Hermansen\r 2",
    "Player_11": "Wood\r 7",
    "Player_10": "Watkins\r TOT (A)",
    "Player_12": "Henderson\r 2",
    "Player_13": "Welbeck\r 5",
    "Player_14": "Konsa\r TOT (A)",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "A\u00EFt-Nouri\r 1",
    "Player_5": "Smith Rowe\r BRE (H)",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Lewis\r 1",
    "Player_4": "Virgil\r 5",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "McNeil\r 2",
    "Player_15": "Pedro Porro\r AVL (H)"
  },
  {
    "manager_Name": "671( 2,272 ) TotalXfr : 11",
    "Teams": "Anfield Athletic( Glen Bonnie )",
    "SXL": "IE",
    "Latp": "38",
    "Player_1": "Sels\r 6",
    "Player_11": "Cunha\r 6",
    "Player_10": "Ndiaye\r 2",
    "Player_12": "J.Virginia\r 0",
    "Player_13": "Gvardiol\r 7",
    "Player_14": "Greaves\r 0",
    "Player_7": "Saka\r 2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Mbeumo\r FUL (A)",
    "Player_6": "Johnson\r AVL (H)",
    "Player_3": "A\u00EFt-Nouri\r 1",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Palmer\r MUN (A)",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "670( 2,307 ) TotalXfr : 7",
    "Teams": "LameLaLLana( Valdemar M. )",
    "SXL": "TR",
    "Latp": "49",
    "Player_1": "Sels\r 6",
    "Player_11": "Wood\r 7",
    "Player_10": "Ra\u00FAl\r BRE (H)",
    "Player_12": "Verbruggen\r 3",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Gabriel\r 2",
    "Player_7": "Foden\r 2",
    "Player_2": "A\u00EFt-Nouri\r 1",
    "Player_5": "McNeil\r 2",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Lewis\r 1",
    "Player_4": "Davis\r 10",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Haaland\r 2",
    "Player_15": "Van den Berg\r FUL (A)"
  },
  {
    "manager_Name": "670( 2,346 ) TotalXfr : 8",
    "Teams": "\uFFFD Roger Blue \uFFFD\uFE0F( Vish _ )",
    "SXL": "IN",
    "Latp": "38",
    "Player_1": "Henderson\r 2",
    "Player_11": "Welbeck\r 5",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Konsa\r TOT (A)",
    "Player_14": "Jo\u00E3o Pedro\r 0",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Lewis\r 1",
    "Player_4": "Keane\r 1",
    "Player_8": "Rogers\r TOT (A)",
    "Player_9": "McNeil\r 2",
    "Player_15": "Mazraoui\r CHE (H)"
  },
  {
    "manager_Name": "670( 2,346 ) TotalXfr : 8",
    "Teams": "Bunch of Slots( Jon Bartlett )",
    "SXL": "EN",
    "Latp": "40",
    "Player_1": "Raya\r 3",
    "Player_11": "Watkins\r TOT (A)",
    "Player_10": "Wood\r 7",
    "Player_12": "Martinez\r TOT (A)",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Mazraoui\r CHE (H)",
    "Player_7": "Smith Rowe\r BRE (H)",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "A\u00EFt-Nouri\r 1",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Saka\r 2",
    "Player_9": "N.Jackson\r MUN (A)",
    "Player_15": "Johnson\r 2"
  },
  {
    "manager_Name": "670( 2,346 ) TotalXfr : 8",
    "Teams": "Ben( Farhan Mustafa )",
    "SXL": "MY",
    "Latp": "48",
    "Player_1": "Henderson\r 2",
    "Player_11": "Wissa\r FUL (A)",
    "Player_10": "Wood\r 7",
    "Player_12": "Valdimarsson\r FUL (A)",
    "Player_13": "Barco\r 0",
    "Player_14": "Rogers\r TOT (A)",
    "Player_7": "Foden\r 2",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Smith Rowe\r BRE (H)",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "Pedro Porro\r AVL (H)",
    "Player_4": "Davis\r 10",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Haaland\r 2",
    "Player_15": "Faes\r 2"
  },
  {
    "manager_Name": "670( 2,346 ) TotalXfr : 8",
    "Teams": "Petronija FC( Petar Stojanovski )",
    "SXL": "MK",
    "Latp": "56",
    "Player_1": "Sels\r 6",
    "Player_11": "Ra\u00FAl\r BRE (H)",
    "Player_10": "Cunha\r 6",
    "Player_12": "Onana\r CHE (H)",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Udogie\r AVL (H)",
    "Player_7": "Foden\r 2",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Palmer\r MUN (A)",
    "Player_6": "M.Salah\r 18",
    "Player_3": "Robinson\r BRE (H)",
    "Player_4": "Davis\r 10",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "Wood\r 7",
    "Player_15": "Mazraoui\r CHE (H)"
  },
  {
    "manager_Name": "670( 2,435 ) TotalXfr : 9",
    "Teams": "Robsdale XI( Robert Burt )",
    "SXL": "EN",
    "Latp": "29",
    "Player_1": "S\u00E1nchez\r MUN (A)",
    "Player_11": "Wood\r 7",
    "Player_10": "Watkins\r TOT (A)",
    "Player_12": "Fabianski\r 2",
    "Player_13": "McNeil\r 2",
    "Player_14": "Veltman\r 1",
    "Player_7": "B.Fernandes\r CHE (H)",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Bowen\r 2",
    "Player_6": "M.Salah\r 18",
    "Player_3": "De Ligt\r CHE (H)",
    "Player_4": "Pedro Porro\r AVL (H)",
    "Player_8": "Mbeumo\r FUL (A)",
    "Player_9": "N.Jackson\r MUN (A)",
    "Player_15": "Tuanzebe\r 0"
  },
  {
    "manager_Name": "669( 2,586 ) TotalXfr : 8",
    "Teams": "Viva Garnacho( Andrew Prater )",
    "SXL": "AT",
    "Latp": "42",
    "Player_1": "Sels\r 6",
    "Player_11": "Delap\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "S\u00E1nchez\r MUN (A)",
    "Player_13": "Calafiori\r 0",
    "Player_14": "Dibling\r 0",
    "Player_7": "Adama\r BRE (H)",
    "Player_2": "Virgil\r 5",
    "Player_5": "Rogers\r TOT (A)",
    "Player_6": "Palmer\r MUN (A)",
    "Player_3": "Keane\r 1",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Haaland\r 2",
    "Player_15": "Tuanzebe\r 0"
  },
  {
    "manager_Name": "589( 601,225 ) TotalXfr : 19",
    "Teams": "Shanice \u2122( Shanice \u2122 )",
    "SXL": "KE",
    "Latp": "32",
    "Player_1": "Raya\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "Vardy\r 5",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Lewis\r 1",
    "Player_14": "Sou\u010Dek\r 0",
    "Player_7": "McNeil\r 2",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Palmer\r MUN (A)",
    "Player_6": "Mbeumo\r FUL (A)",
    "Player_3": "A\u00EFt-Nouri\r 1",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "Saka\r 2",
    "Player_9": "Wood\r 7",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "667( 3,176 ) TotalXfr : 9",
    "Teams": "Mr. Selv\u00E5g( Mr. Selv\u00E5g )",
    "SXL": "SE",
    "Latp": "43",
    "Player_1": "Ederson M.\r 2",
    "Player_11": "Vardy\r 5",
    "Player_10": "Havertz\r 1",
    "Player_12": "Iversen\r 0",
    "Player_13": "Rogers\r TOT (A)",
    "Player_14": "Hall\r 8",
    "Player_7": "Mbeumo\r FUL (A)",
    "Player_2": "Mu\u00F1oz\r 3",
    "Player_5": "Virgil\r 5",
    "Player_6": "Foden\r 2",
    "Player_3": "Gvardiol\r 7",
    "Player_4": "Robinson\r BRE (H)",
    "Player_8": "Palmer\r MUN (A)",
    "Player_9": "M.Salah\r 18",
    "Player_15": "Welbeck\r 5"
  }
];