var s = [
  {
    "manager_Name": "580( 1,500,414 ) TotalXfr : 9",
    "Teams": "Doylempiacos( Matt Doyle )",
    "SXL": "EN",
    "Latp": "46",
    "Player_1": "Sels\r 6",
    "Player_11": "Delap\r 2",
    "Player_10": "Wissa\r 2",
    "Player_12": "Flekken\r 4",
    "Player_13": "Adama\r 4",
    "Player_14": "Van de Ven\r 0",
    "Player_7": "McNeil\r 2",
    "Player_2": "Lewis\r 1",
    "Player_5": "M.Salah\r 18",
    "Player_6": "Mbeumo\r 3",
    "Player_3": "Burn\r 6",
    "Player_4": "A\u00EFt-Nouri\r 1",
    "Player_8": "Palmer\r 3",
    "Player_9": "Haaland\r 2",
    "Player_15": "Okoli\r 0"
  },
  {
    "manager_Name": "571( 1,954,604 ) TotalXfr : 10",
    "Teams": "Jelly Flood( Lorin Minxhozi )",
    "SXL": "EN",
    "Latp": "63",
    "Player_1": "Ederson M.\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Cunha\r 6",
    "Player_12": "Fabianski\r 2",
    "Player_13": "Mykolenko\r 2",
    "Player_14": "Dibling\r 0",
    "Player_7": "Mbeumo\r 3",
    "Player_2": "Lewis\r 1",
    "Player_5": "Rogers\r 9",
    "Player_6": "Johnson\r 8",
    "Player_3": "Davis\r 10",
    "Player_4": "Gabriel\r 2",
    "Player_8": "M.Salah\r 18",
    "Player_9": "Watkins\r 2",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "550( 3,140,002 ) TotalXfr : 8",
    "Teams": "Insane in De Bruyne( Patrick Harrison-Harvey )",
    "SXL": "EN",
    "Latp": "32",
    "Player_1": "Flekken\r 4",
    "Player_11": "Haaland\r 4",
    "Player_10": "Welbeck\r 5",
    "Player_12": "Areola\r 0",
    "Player_13": "Burn\r 6",
    "Player_14": "Duran\r 1",
    "Player_7": "Saka\r 2",
    "Player_2": "Digne\r 0",
    "Player_5": "Luis D\u00EDaz\r 1",
    "Player_6": "Smith Rowe\r 2",
    "Player_3": "Dalot\r 1",
    "Player_4": "Gvardiol\r 7",
    "Player_8": "Palmer\r 3",
    "Player_9": "Szmodics\r 3",
    "Player_15": "Harwood-Bellis\r 6"
  },
  {
    "manager_Name": "547( 3,332,890 ) TotalXfr : 9",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "IN",
    "Latp": "40",
    "Player_1": "Henderson\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Havertz\r 1",
    "Player_12": "Fabianski\r 2",
    "Player_13": "W.Fofana\r 2",
    "Player_14": "Ajer\r 0",
    "Player_7": "M.Salah\r 18",
    "Player_2": "Keane\r 1",
    "Player_5": "Dibling\r 0",
    "Player_6": "Smith Rowe\r 2",
    "Player_3": "Faes\r 2",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "Palmer\r 3",
    "Player_9": "Johnson\r 8",
    "Player_15": "Wheatley\r 0"
  },
  {
    "manager_Name": "541( 3,708,576 ) TotalXfr : 10",
    "Teams": "Hawk Tchouameni( Joshua Ong )",
    "SXL": "EN",
    "Latp": "27",
    "Player_1": "Fabianski\r 2",
    "Player_11": "Watkins\r 2",
    "Player_10": "Ra\u00FAl\r 2",
    "Player_12": "Areola\r 0",
    "Player_13": "Rogers\r 9",
    "Player_14": "Konat\u00E9\r 1",
    "Player_7": "Smith Rowe\r 2",
    "Player_2": "Mykolenko\r 2",
    "Player_5": "Luis D\u00EDaz\r 1",
    "Player_6": "Mbeumo\r 3",
    "Player_3": "Robinson\r 6",
    "Player_4": "Lewis\r 1",
    "Player_8": "Foden\r 2",
    "Player_9": "Haaland\r 4",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "527( 4,550,951 ) TotalXfr : 9",
    "Teams": "Enter Team Name( teo teo )",
    "SXL": "IT",
    "Latp": "40",
    "Player_1": "Flekken\r 4",
    "Player_11": "Calvert-Lewin\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "S\u00E1nchez\r 3",
    "Player_13": "Adama\r 4",
    "Player_14": "Konsa\r 0",
    "Player_7": "Rogers\r 9",
    "Player_2": "Gvardiol\r 7",
    "Player_5": "Smith Rowe\r 2",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Virgil\r 5",
    "Player_4": "Lewis\r 1",
    "Player_8": "Palmer\r 3",
    "Player_9": "Watkins\r 2",
    "Player_15": "Tuanzebe\r 0"
  }
];