// Fetches current weather for every city in cities.json and writes the
// result to weatherData.json, which the page reads at load time. Same
// pattern as ../scrapeWeather.js — a periodic snapshot generated by
// hand-running this script, not a live per-visitor API call.
//
// Run manually from this folder: `node scrapeWeather.js`
//
// Keyed by `rank` rather than `iso2`: several of these cities share a
// country (Bolivia, Colombia, China all appear more than once in the top
// 35), so iso2 can't uniquely identify a row the way it does for
// ../countries.json (one capital per country).

const fs = require("fs");
const path = require("path");

// Same free-tier key ../scrapeWeather.js and ../../fetch.js already ship
// to every browser — reusing it here doesn't expose anything new.
const API_KEY = "39a9a737b07b4b703e3d1cd1e231eedc";
const DELAY_MS = 1100; // keeps us under OpenWeather's free-tier 60-calls/minute limit

const CITIES_PATH = path.join(__dirname, "cities.json");
const OUTPUT_PATH = path.join(__dirname, "weatherData.json");

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function fetchWeather(city) {
  const url =
    `https://api.openweathermap.org/data/2.5/weather` +
    `?lat=${city.lat}&lon=${city.lon}&units=metric&appid=${API_KEY}`;

  const response = await fetch(url);
  const data = await response.json();

  if (!response.ok) {
    throw new Error(data.message || `Request failed (${response.status})`);
  }

  return {
    temp: data.main.temp,
    description: data.weather[0] ? data.weather[0].description : "",
    timezone: data.timezone,
    sunrise: data.sys.sunrise,
    sunset: data.sys.sunset,
    dayLengthSeconds: data.sys.sunset - data.sys.sunrise,
  };
}

async function main() {
  const cities = JSON.parse(fs.readFileSync(CITIES_PATH, "utf8"));
  const existing = fs.existsSync(OUTPUT_PATH)
    ? JSON.parse(fs.readFileSync(OUTPUT_PATH, "utf8"))
    : { generatedAt: null, byRank: {} };

  const byRank = { ...existing.byRank };
  let failures = 0;

  for (const city of cities) {
    process.stdout.write(`${city.city}, ${city.country} (#${city.rank})... `);
    try {
      byRank[city.rank] = await fetchWeather(city);
      console.log("ok");
    } catch (err) {
      // Keep whatever this city had from the last successful scrape
      // rather than blanking its row out over one flaky request.
      failures += 1;
      console.log(`FAILED (${err.message}) — keeping previous data`);
    }
    await sleep(DELAY_MS);
  }

  const output = { generatedAt: Math.floor(Date.now() / 1000), byRank };
  fs.writeFileSync(OUTPUT_PATH, JSON.stringify(output, null, 2) + "\n");
  console.log(`\nWrote ${Object.keys(byRank).length} entries to ${OUTPUT_PATH}` +
    (failures ? ` (${failures} failed this run, old data kept for those)` : ""));
}

main();
