var s =[
   {
      "manager_Name":"Sahil Lampard",
      "Teams":"MarxUnited",
      "Player_1":"Ramsdale -",
      "Player_2":"Alexander-Arnold 2",
      "Player_3":"James BHA (H)",
      "Player_4":"Cancelo BRE (A)",
      "Player_5":"Son 6",
      "Player_6":"Benrahma 8",
      "Player_7":"Bernardo BRE (A)",
      "Player_8":"Salah 0$ captain",
      "Player_9":"Hudson-Odoi BHA (H)",
      "Player_10":"Dennis 7",
      "Player_11":"Maupay CHE (A)",
      "Player_12":"Sánchez CHE (A)",
      "Player_13":"Livramento 0",
      "Player_14":"Archer -",
      "Player_15":"White -",
      "SXL":"23",
      "Bench":"1069",
      "Count  ":"1,445,721"
   },
   {
      "manager_Name":"Saurabh Tamang",
      "Teams":"Lucky FC",
      "Player_1":"Sánchez CHE (A)",
      "Player_2":"Livramento 0",
      "Player_3":"Cancelo BRE (A)",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"James BHA (H)",
      "Player_6":"Smith Rowe -",
      "Player_7":"Salah 0",
      "Player_8":"Gallagher 0",
      "Player_9":"Bernardo BRE (A)",
      "Player_10":"Dennis 7",
      "Player_11":"Ronaldo BUR (H)$ captain",
      "Player_12":"Guaita 6",
      "Player_13":"Gray -",
      "Player_14":"Omobamidele 0",
      "Player_15":"Archer -",
      "SXL":"9",
      "Bench":"984",
      "Count  ":"3,004,206"
   },
   {
      "manager_Name":"Pranesh Sharma",
      "Teams":"Immortal FC",
      "Player_1":"Sánchez CHE (A)",
      "Player_2":"James BHA (H)",
      "Player_3":"Tsimikas 2",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Dier 2",
      "Player_6":"Mount BHA (H)",
      "Player_7":"Salah 0$ captain",
      "Player_8":"Foden BRE (A)",
      "Player_9":"Gallagher 0",
      "Player_10":"Dennis 7",
      "Player_11":"Ronaldo BUR (H)",
      "Player_12":"Foster 0",
      "Player_13":"Watkins -",
      "Player_14":"White -",
      "Player_15":"Smith Rowe -",
      "SXL":"13",
      "Bench":"1134",
      "Count  ":"618,011"
   },
   {
      "manager_Name":"Sanjeev Kumar",
      "Teams":"GAROBADHA UNITED",
      "Player_1":"de Gea BUR (H)",
      "Player_2":"Cancelo BRE (A)",
      "Player_3":"Alonso BHA (H)",
      "Player_4":"Dalot BUR (H)",
      "Player_5":"Son 6",
      "Player_6":"Bowen 14",
      "Player_7":"Gallagher 0$ captain",
      "Player_8":"Højbjerg 2",
      "Player_9":"Pukki 0",
      "Player_10":"Broja 1",
      "Player_11":"Ronaldo BUR (H)",
      "Player_12":"Foster 0",
      "Player_13":"White -",
      "Player_14":"Smith Rowe -",
      "Player_15":"Tierney -",
      "SXL":"23",
      "Bench":"1123",
      "Count  ":"731,177"
   },
   {
      "manager_Name":"Kumar Anku",
      "Teams":"The Borderland Fc",
      "Player_1":"Dubravka -",
      "Player_2":"Cancelo BRE (A)",
      "Player_3":"Alexander-Arnold 2",
      "Player_4":"Coufal 2",
      "Player_5":"Alonso BHA (H)",
      "Player_6":"Reguilón 0",
      "Player_7":"Son 6",
      "Player_8":"Hudson-Odoi BHA (H)",
      "Player_9":"Salah 0$ captain",
      "Player_10":"Gray -",
      "Player_11":"Ronaldo BUR (H)",
      "Player_12":"Ramsdale -",
      "Player_13":"Origi 0",
      "Player_14":"Smith Rowe -",
      "Player_15":"Gelhardt -",
      "SXL":"10",
      "Bench":"1070",
      "Count  ":"1,433,671"
   },
   {
      "manager_Name":"Kushal Sahota",
      "Teams":"FC ASSASSINS",
      "Player_1":"Mendy BHA (H)",
      "Player_2":"Livramento 0",
      "Player_3":"Dias BRE (A)",
      "Player_4":"James BHA (H)",
      "Player_5":"Duffy CHE (A)",
      "Player_6":"Jota 2",
      "Player_7":"Bowen 14",
      "Player_8":"Gallagher 0",
      "Player_9":"Allan -",
      "Player_10":"Vardy 2",
      "Player_11":"Ronaldo BUR (H)$ captain",
      "Player_12":"Steele CHE (A)",
      "Player_13":"Dennis 7",
      "Player_14":"Tsimikas 2",
      "Player_15":"Salah 0",
      "SXL":"18",
      "Bench":"966",
      "Count  ":"3,356,573"
   },
   {
      "manager_Name":"Regean Lama",
      "Teams":"BUSBY BABIES 2",
      "Player_1":"Sánchez CHE (A)",
      "Player_2":"Rüdiger BHA (H)",
      "Player_3":"Alexander-Arnold 2",
      "Player_4":"Livramento 0",
      "Player_5":"Jota 2",
      "Player_6":"Gallagher 0",
      "Player_7":"Bernardo BRE (A)",
      "Player_8":"Salah 0$ captain",
      "Player_9":"Antonio 5",
      "Player_10":"Ronaldo BUR (H)",
      "Player_11":"Scarlett 0",
      "Player_12":"Carson BRE (A)",
      "Player_13":"Ødegaard -",
      "Player_14":"Veltman CHE (A)",
      "Player_15":"Tierney -",
      "SXL":"9",
      "Bench":"1124",
      "Count  ":"721,142"
   },
   {
      "manager_Name":"pranam rai",
      "Teams":"SYAKREE FC",
      "Player_1":"Sánchez CHE (A)",
      "Player_2":"Alexander-Arnold 4$ captain",
      "Player_3":"Dias BRE (A)",
      "Player_4":"James BHA (H)",
      "Player_5":"Bernardo BRE (A)",
      "Player_6":"Salah 0",
      "Player_7":"Maddison 3",
      "Player_8":"Højbjerg 2",
      "Player_9":"Dennis 7",
      "Player_10":"Ronaldo BUR (H)",
      "Player_11":"Antonio 5",
      "Player_12":"Lloris 2",
      "Player_13":"Ødegaard -",
      "Player_14":"Tsimikas 2",
      "Player_15":"Manquillo -",
      "SXL":"21",
      "Bench":"1141",
      "Count  ":"552,481"
   },
   {
      "manager_Name":"Ashim Lama",
      "Teams":"⚔️FURY⚔️",
      "Player_1":"Lloris 2",
      "Player_2":"Jansson MCI (H)",
      "Player_3":"James BHA (H)",
      "Player_4":"Reguilón 0",
      "Player_5":"Alexander-Arnold 2",
      "Player_6":"Bowen 14",
      "Player_7":"Gallagher 0",
      "Player_8":"Gray -",
      "Player_9":"Salah 0$ captain",
      "Player_10":"Antonio 5",
      "Player_11":"Ronaldo BUR (H)",
      "Player_12":"Ward 0",
      "Player_13":"Dennis 7",
      "Player_14":"Martinelli -",
      "Player_15":"Gabriel -",
      "SXL":"23",
      "Bench":"1064",
      "Count  ":"1,525,194"
   },
   {
      "manager_Name":"Vivek Pradhan",
      "Teams":"PEPPERBOX83",
      "Player_1":"Sánchez CHE (A)",
      "Player_2":"Alexander-Arnold 2",
      "Player_3":"Cancelo BRE (A)",
      "Player_4":"Dias BRE (A)",
      "Player_5":"Reguilón 0",
      "Player_6":"Jota 2",
      "Player_7":"Bernardo BRE (A)",
      "Player_8":"Salah 0$ captain",
      "Player_9":"Antonio 5",
      "Player_10":"Toney MCI (H)",
      "Player_11":"Dennis 7",
      "Player_12":"Raya MCI (H)",
      "Player_13":"Smith Rowe -",
      "Player_14":"Raphinha -",
      "Player_15":"Pinnock MCI (H)",
      "SXL":"16",
      "Bench":"1165",
      "Count  ":"365,348"
   },
   {
      "manager_Name":"Sibin _",
      "Teams":"F95",
      "Player_1":"Ederson BRE (A)",
      "Player_2":"Dias BRE (A)",
      "Player_3":"Rüdiger BHA (H)",
      "Player_4":"James BHA (H)",
      "Player_5":"Reguilón 0",
      "Player_6":"Gallagher 0",
      "Player_7":"Son 6",
      "Player_8":"Bernardo BRE (A)",
      "Player_9":"Mount BHA (H)",
      "Player_10":"Dennis 7",
      "Player_11":"Ronaldo BUR (H)$ captain",
      "Player_12":"Ramsdale -",
      "Player_13":"Dier 2",
      "Player_14":"Smith Rowe -",
      "Player_15":"Hwang -",
      "SXL":"13",
      "Bench":"1124",
      "Count  ":"719,783"
   },
   {
      "manager_Name":"Omkar Subba",
      "Teams":"Omk09",
      "Player_1":"Alisson 2",
      "Player_2":"James BHA (H)",
      "Player_3":"Rüdiger BHA (H)",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Fred BUR (H)",
      "Player_6":"Mount BHA (H)",
      "Player_7":"Gallagher 0",
      "Player_8":"Højbjerg 2",
      "Player_9":"Salah 0$ captain",
      "Player_10":"Dennis 7",
      "Player_11":"Ronaldo BUR (H)",
      "Player_12":"Ramsdale -",
      "Player_13":"Toney MCI (H)",
      "Player_14":"Jansson MCI (H)",
      "Player_15":"Tierney -",
      "SXL":"13",
      "Bench":"1058",
      "Count  ":"1,627,419"
   },
   {
      "manager_Name":"Indrajeet Singh",
      "Teams":"Kung Fu Pandoos",
      "Player_1":"Lloris 2",
      "Player_2":"Tierney -",
      "Player_3":"Laporte BRE (A)",
      "Player_4":"Matip 1",
      "Player_5":"James BHA (H)",
      "Player_6":"Bernardo BRE (A)",
      "Player_7":"Son 6",
      "Player_8":"Salah 0$ captain",
      "Player_9":"Saint-Maximin -",
      "Player_10":"Maupay CHE (A)",
      "Player_11":"Kane 6",
      "Player_12":"Foster 0",
      "Player_13":"White -",
      "Player_14":"Bissouma CHE (A)",
      "Player_15":"Gilmour 2",
      "SXL":"15",
      "Bench":"1023",
      "Count  ":"2,251,491"
   },
   {
      "manager_Name":"Rishi Thulung",
      "Teams":"PL CG FC",
      "Player_1":"Ramsdale -",
      "Player_2":"James BHA (H)",
      "Player_3":"Livramento 0",
      "Player_4":"Lamptey CHE (A)",
      "Player_5":"Cancelo BRE (A)",
      "Player_6":"Alexander-Arnold 2",
      "Player_7":"Son 6",
      "Player_8":"Jota 2",
      "Player_9":"Antonio 5",
      "Player_10":"Dennis 7",
      "Player_11":"Ronaldo BUR (H)$ captain",
      "Player_12":"Foster 0",
      "Player_13":"Smith Rowe -",
      "Player_14":"Martinelli -",
      "Player_15":"Douglas Luiz -",
      "SXL":"22",
      "Bench":"1144",
      "Count  ":"527,468"
   },
   {
      "manager_Name":"Dipen Thapa",
      "Teams":"BW4_11",
      "Player_1":"Sánchez CHE (A)",
      "Player_2":"Livramento 0",
      "Player_3":"Dias BRE (A)",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Benrahma 8",
      "Player_6":"Gallagher 0",
      "Player_7":"Son 6",
      "Player_8":"Trossard CHE (A)",
      "Player_9":"Salah 0$ captain",
      "Player_10":"Dennis 7",
      "Player_11":"Antonio 5",
      "Player_12":"Sá -",
      "Player_13":"Gabriel -",
      "Player_14":"Watkins -",
      "Player_15":"Tomiyasu -",
      "SXL":"28",
      "Bench":"1135",
      "Count  ":"610,526"
   },
   {
      "manager_Name":"Nishant Singh",
      "Teams":"beta",
      "Player_1":"Sánchez CHE (A)",
      "Player_2":"James BHA (H)",
      "Player_3":"Cancelo BRE (A)",
      "Player_4":"Livramento 0",
      "Player_5":"Alexander-Arnold 2",
      "Player_6":"Salah 0$ captain",
      "Player_7":"Jota 2",
      "Player_8":"Foden BRE (A)",
      "Player_9":"King 5",
      "Player_10":"Jesus BRE (A)",
      "Player_11":"Dennis 7",
      "Player_12":"Ramsdale -",
      "Player_13":"Allan -",
      "Player_14":"Smith Rowe -",
      "Player_15":"Tomiyasu -",
      "SXL":"16",
      "Bench":"1077",
      "Count  ":"1,325,301"
   },
   {
      "manager_Name":"Ashish Subba",
      "Teams":"Gustavous Gunner",
      "Player_1":"Ramsdale -",
      "Player_2":"Alexander-Arnold 2",
      "Player_3":"Duffy CHE (A)",
      "Player_4":"Rüdiger BHA (H)",
      "Player_5":"Cancelo BRE (A)",
      "Player_6":"Bernardo BRE (A)",
      "Player_7":"Fernandes BUR (H)",
      "Player_8":"Gallagher 0$ captain",
      "Player_9":"Son 6",
      "Player_10":"Antonio 5",
      "Player_11":"Dennis 7",
      "Player_12":"Foster 0",
      "Player_13":"Raphinha -",
      "Player_14":"White -",
      "Player_15":"Obafemi 0",
      "SXL":"20",
      "Bench":"1079",
      "Count  ":"1,291,328"
   },
   {
      "manager_Name":"Rohan Rai",
      "Teams":"False 9",
      "Player_1":"de Gea BUR (H)",
      "Player_2":"James BHA (H)",
      "Player_3":"Cancelo BRE (A)",
      "Player_4":"Reguilón 0",
      "Player_5":"Livramento 0",
      "Player_6":"Son 6",
      "Player_7":"De Bruyne BRE (A)$ captain",
      "Player_8":"Jota 2",
      "Player_9":"Brownhill MUN (A)",
      "Player_10":"Toney MCI (H)",
      "Player_11":"Antonio 5",
      "Player_12":"Ramsdale -",
      "Player_13":"Watkins -",
      "Player_14":"Tomiyasu -",
      "Player_15":"Raphinha -",
      "SXL":"13",
      "Bench":"1166",
      "Count  ":"361,302"
   },
   {
      "manager_Name":"Raj Kanango",
      "Teams":"Weightloss Coach",
      "Player_1":"de Gea BUR (H)",
      "Player_2":"James BHA (H)",
      "Player_3":"Cancelo BRE (A)",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Davies 2",
      "Player_6":"Lucas Moura 1",
      "Player_7":"Jota 2",
      "Player_8":"Gallagher 0",
      "Player_9":"Son 12$ captain",
      "Player_10":"Dennis 7",
      "Player_11":"Ronaldo BUR (H)",
      "Player_12":"Carson BRE (A)",
      "Player_13":"Bissouma CHE (A)",
      "Player_14":"Amartey 8",
      "Player_15":"Lacazette -",
      "SXL":"26",
      "Bench":"1140",
      "Count  ":"565,979"
   },
   {
      "manager_Name":"Gaurav Shrestha",
      "Teams":"Fußball-Mannschaft",
      "Player_1":"de Gea BUR (H)",
      "Player_2":"Alexander-Arnold 2",
      "Player_3":"James BHA (H)",
      "Player_4":"Livramento 0",
      "Player_5":"Cancelo BRE (A)",
      "Player_6":"Bowen 14",
      "Player_7":"Gallagher 0",
      "Player_8":"Foden BRE (A)",
      "Player_9":"Jota 4$ captain",
      "Player_10":"Antonio 5",
      "Player_11":"Ronaldo BUR (H)",
      "Player_12":"Foster 0",
      "Player_13":"Tierney -",
      "Player_14":"Watkins -",
      "Player_15":"Raphinha -",
      "SXL":"25",
      "Bench":"1209",
      "Count  ":"141,828"
   },
   {
      "manager_Name":"Bishal Rai",
      "Teams":"Gooner for Life 037",
      "Player_1":"de Gea BUR (H)",
      "Player_2":"Alexander-Arnold 4$ captain",
      "Player_3":"James BHA (H)",
      "Player_4":"Alonso BHA (H)",
      "Player_5":"Cancelo BRE (A)",
      "Player_6":"Foden BRE (A)",
      "Player_7":"Jota 2",
      "Player_8":"Bowen 14",
      "Player_9":"Gallagher 0",
      "Player_10":"Son 6",
      "Player_11":"Dennis 7",
      "Player_12":"Ramsdale -",
      "Player_13":"Rüdiger BHA (H)",
      "Player_14":"Benteke 1",
      "Player_15":"Richardson MUN (A)",
      "SXL":"33",
      "Bench":"1199",
      "Count  ":"182,030"
   },
   {
      "manager_Name":"RAJIYUNG Sun",
      "Teams":"hansing",
      "Player_1":"Alisson 2",
      "Player_2":"Alexander-Arnold 2",
      "Player_3":"Laporte BRE (A)",
      "Player_4":"Cancelo BRE (A)",
      "Player_5":"Reguilón 0",
      "Player_6":"Saka -",
      "Player_7":"Gallagher 0",
      "Player_8":"Salah 0$ captain",
      "Player_9":"Son 6",
      "Player_10":"Antonio 5",
      "Player_11":"Dennis 7",
      "Player_12":"Steer -",
      "Player_13":"White -",
      "Player_14":"Smith Rowe -",
      "Player_15":"Watkins -",
      "SXL":"22",
      "Bench":"1136",
      "Count  ":"602,347"
   },
   {
      "manager_Name":"Ashish Rai",
      "Teams":"Deadhead",
      "Player_1":"Ramsdale -",
      "Player_2":"Cancelo BRE (A)",
      "Player_3":"James BHA (H)",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Williams 1",
      "Player_6":"Gallagher 0",
      "Player_7":"Mount BHA (H)$ captain",
      "Player_8":"Jota 2",
      "Player_9":"Bernardo BRE (A)",
      "Player_10":"Kane 6",
      "Player_11":"Antonio 5",
      "Player_12":"Foster 0",
      "Player_13":"Livramento 0",
      "Player_14":"Jiménez -",
      "Player_15":"Smith Rowe -",
      "SXL":"16",
      "Bench":"1153",
      "Count  ":"458,201"
   },
   {
      "manager_Name":"prabin kumar",
      "Teams":"Prabin Singh",
      "Player_1":"Mendy BHA (H)",
      "Player_2":"Rüdiger BHA (H)",
      "Player_3":"Alonso BHA (H)",
      "Player_4":"Dias BRE (A)",
      "Player_5":"Benrahma 8",
      "Player_6":"Greenwood BUR (H)",
      "Player_7":"Townsend -",
      "Player_8":"Son 6",
      "Player_9":"Jiménez -",
      "Player_10":"Antonio 5",
      "Player_11":"Aubameyang -$ captain",
      "Player_12":"Foster 0",
      "Player_13":"Shaw BUR (H)",
      "Player_14":"Tsimikas 2",
      "Player_15":"Bissouma CHE (A)",
      "SXL":"19",
      "Bench":"810",
      "Count  ":"6,072,550"
   },
   {
      "manager_Name":"Ravish Verma",
      "Teams":"Marijuana Fields FC",
      "Player_1":"Guaita 6",
      "Player_2":"Cancelo BRE (A)",
      "Player_3":"James BHA (H)",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Gallagher 0",
      "Player_6":"Jota 4$ captain",
      "Player_7":"Bowen 14",
      "Player_8":"Gündogan BRE (A)",
      "Player_9":"Foden BRE (A)",
      "Player_10":"King 5",
      "Player_11":"Ronaldo BUR (H)",
      "Player_12":"Ramsdale -",
      "Player_13":"Livramento 0",
      "Player_14":"Lacazette -",
      "Player_15":"White -",
      "SXL":"31",
      "Bench":"1150",
      "Count  ":"478,612"
   },
   {
      "manager_Name":"Prayash Thapa",
      "Teams":"abcde FC",
      "Player_1":"de Gea BUR (H)",
      "Player_2":"Reguilón 0",
      "Player_3":"Cancelo BRE (A)",
      "Player_4":"James BHA (H)",
      "Player_5":"Alexander-Arnold 2",
      "Player_6":"Bowen 14",
      "Player_7":"Jota 2",
      "Player_8":"Salah 0$ captain",
      "Player_9":"Foden BRE (A)",
      "Player_10":"King 5",
      "Player_11":"Antonio 5",
      "Player_12":"Foster 0",
      "Player_13":"Laporte BRE (A)",
      "Player_14":"Lacazette -",
      "Player_15":"Douglas Luiz -",
      "SXL":"28",
      "Bench":"1262",
      "Count  ":"24,290"
   },
   {
      "manager_Name":"Tenzing Ninjey",
      "Teams":"One Step Beyond 026*",
      "Player_1":"Bachmann 0",
      "Player_2":"Cancelo BRE (A)",
      "Player_3":"Rüdiger BHA (H)",
      "Player_4":"Reguilón 0",
      "Player_5":"Alexander-Arnold 2",
      "Player_6":"Gündogan BRE (A)",
      "Player_7":"Son 12$ captain",
      "Player_8":"Jota 2",
      "Player_9":"Broja 1",
      "Player_10":"Antonio 5",
      "Player_11":"Ronaldo BUR (H)",
      "Player_12":"Ramsdale -",
      "Player_13":"Gilmour 2",
      "Player_14":"Livramento 0",
      "Player_15":"Martinelli -",
      "SXL":"22",
      "Bench":"1151",
      "Count  ":"473,972"
   },
   {
      "manager_Name":"Harsh Raval",
      "Teams":"Up the Bees",
      "Player_1":"de Gea BUR (H)",
      "Player_2":"Tierney -",
      "Player_3":"Cancelo BRE (A)",
      "Player_4":"Dias BRE (A)",
      "Player_5":"James BHA (H)",
      "Player_6":"Ramsey -",
      "Player_7":"Bernardo BRE (A)",
      "Player_8":"Gray -",
      "Player_9":"Davis -",
      "Player_10":"Kane 6",
      "Player_11":"Ronaldo BUR (H)$ captain",
      "Player_12":"Foster 0",
      "Player_13":"Bowen 14",
      "Player_14":"Alexander-Arnold 2",
      "Player_15":"Jota 2",
      "SXL":"6",
      "Bench":"1178",
      "Count  ":"286,790"
   },
   {
      "manager_Name":"PRAYAS BAJGAI",
      "Teams":"MCFC@1894",
      "Player_1":"de Gea BUR (H)",
      "Player_2":"Alexander-Arnold 2",
      "Player_3":"James BHA (H)",
      "Player_4":"Cancelo BRE (A)",
      "Player_5":"Dalot BUR (H)",
      "Player_6":"Gallagher 0",
      "Player_7":"Jota 2",
      "Player_8":"Bowen 14",
      "Player_9":"Foden BRE (A)",
      "Player_10":"Kane 12$ captain",
      "Player_11":"Ronaldo BUR (H)",
      "Player_12":"Foster 0",
      "Player_13":"King 5",
      "Player_14":"Davies 2",
      "Player_15":"Martinelli -",
      "SXL":"30",
      "Bench":"1207",
      "Count  ":"150,996"
   },
   {
      "manager_Name":"AVIJIT DAS",
      "Teams":"Roing FC",
      "Player_1":"de Gea BUR (H)",
      "Player_2":"James BHA (H)",
      "Player_3":"Cancelo BRE (A)",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Dier 2",
      "Player_6":"Jota 4$ captain",
      "Player_7":"Bowen 14",
      "Player_8":"Bernardo BRE (A)",
      "Player_9":"Foden BRE (A)",
      "Player_10":"Dennis 7",
      "Player_11":"Ronaldo BUR (H)",
      "Player_12":"Foster 0",
      "Player_13":"Livramento 0",
      "Player_14":"Smith Rowe -",
      "Player_15":"Watkins -",
      "SXL":"29",
      "Bench":"1172",
      "Count  ":"324,844"
   },
   {
      "manager_Name":"Abhijeet Singh",
      "Teams":"WEIGHTLOSS COACH",
      "Player_1":"Lloris 2",
      "Player_2":"James BHA (H)",
      "Player_3":"Dias BRE (A)",
      "Player_4":"Cancelo BRE (A)",
      "Player_5":"Alexander-Arnold 2",
      "Player_6":"Son 12$ captain",
      "Player_7":"Gallagher 0",
      "Player_8":"Bernardo BRE (A)",
      "Player_9":"Mount BHA (H)",
      "Player_10":"Antonio 5",
      "Player_11":"Dennis 7",
      "Player_12":"Foster 0",
      "Player_13":"Manquillo -",
      "Player_14":"Lacazette -",
      "Player_15":"Smith Rowe -",
      "SXL":"28",
      "Bench":"1217",
      "Count  ":"114,353"
   },
   {
      "manager_Name":"SATYAM RAI",
      "Teams":"PINE",
      "Player_1":"Ramsdale -",
      "Player_2":"James BHA (H)",
      "Player_3":"Alonso BHA (H)",
      "Player_4":"Cancelo BRE (A)",
      "Player_5":"Alexander-Arnold 2",
      "Player_6":"Jota 2",
      "Player_7":"Gallagher 0",
      "Player_8":"Foden BRE (A)",
      "Player_9":"Bowen 14",
      "Player_10":"Ronaldo BUR (H)$ captain",
      "Player_11":"King 5",
      "Player_12":"Foster 0",
      "Player_13":"Lacazette -",
      "Player_14":"Livramento 0",
      "Player_15":"Smith Rowe -",
      "SXL":"23",
      "Bench":"1198",
      "Count  ":"186,263"
   }
]