var s = [
  {
    "manager_Name": "825( 11,740 )",
    "Teams": "cavac215( Ankit Chhetri )",
    "SXL": "IND",
    "Latp": "29",
    "Player_1": "D\u00FAbravka CRY",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 24",
    "Player_12": "Pope 0",
    "Player_13": "Pau BHA",
    "Player_14": "Calvert-Lewin CHE",
    "Player_7": "Semenyo 4",
    "Player_2": "Gu\u00E9hi BUR",
    "Player_5": "Saka BRE",
    "Player_6": "Rice BRE",
    "Player_3": "Livramento 1",
    "Player_4": "Chalobah LEE",
    "Player_8": "Mbeumo WHU",
    "Player_9": "Minteh AVL",
    "Player_15": "Gabriel BRE"
  },
  {
    "manager_Name": "794( 82,421 )",
    "Teams": "11 n over( Ashish Rai )",
    "SXL": "IND",
    "Latp": "26",
    "Player_1": "Raya BRE",
    "Player_11": "Welbeck AVL",
    "Player_10": "Haaland 24",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "O.Dango ARS",
    "Player_14": "Rodon CHE",
    "Player_7": "Saka BRE",
    "Player_2": "Mu\u00F1oz BUR",
    "Player_5": "Gakpo SUN",
    "Player_6": "Minteh AVL",
    "Player_3": "J.Timber BRE",
    "Player_4": "De Ligt",
    "Player_8": "Kudus 1",
    "Player_9": "Evanilson 1",
    "Player_15": "Diouf MUN"
  },
  {
    "manager_Name": "783( 146,216 )",
    "Teams": "abcde FC( Prayash Thapa )",
    "SXL": "IND",
    "Latp": "28",
    "Player_1": "D\u00FAbravka CRY",
    "Player_11": "Mateta BUR",
    "Player_10": "Haaland 24",
    "Player_12": "Roefs LIV",
    "Player_13": "Marc Guiu",
    "Player_14": "Sarr BUR",
    "Player_7": "Minteh AVL",
    "Player_2": "J.Timber BRE",
    "Player_5": "James LEE",
    "Player_6": "Enzo LEE",
    "Player_3": "Mu\u00F1oz BUR",
    "Player_4": "Virgil SUN",
    "Player_8": "Mbeumo WHU",
    "Player_9": "Semenyo 4",
    "Player_15": "Senesi 0"
  },
  {
    "manager_Name": "775( 216,796 )",
    "Teams": "False 9( Rohan Rai )",
    "SXL": "IND",
    "Latp": "29",
    "Player_1": "D\u00FAbravka CRY",
    "Player_11": "Thiago ARS",
    "Player_10": "Woltemade 1",
    "Player_12": "Pope 0",
    "Player_13": "Anthony CRY",
    "Player_14": "Gudmundsson CHE",
    "Player_7": "Saka BRE",
    "Player_2": "Mukiele LIV",
    "Player_5": "Mbeumo WHU",
    "Player_6": "Minteh AVL",
    "Player_3": "Gu\u00E9hi BUR",
    "Player_4": "Virgil SUN",
    "Player_8": "Semenyo 4",
    "Player_9": "Haaland 24",
    "Player_15": "Senesi 0"
  },
  {
    "manager_Name": "771( 259,046 )",
    "Teams": "Alpha11( AVIJIT DAS )",
    "SXL": "IND",
    "Latp": "28",
    "Player_1": "Henderson BUR",
    "Player_11": "Mateta BUR",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Senesi 0",
    "Player_14": "King 1",
    "Player_7": "Mbeumo WHU",
    "Player_2": "Lacroix BUR",
    "Player_5": "Semenyo 4",
    "Player_6": "Saka BRE",
    "Player_3": "Chalobah LEE",
    "Player_4": "Virgil SUN",
    "Player_8": "Enzo LEE",
    "Player_9": "Haaland 24",
    "Player_15": "Gudmundsson CHE"
  },
  {
    "manager_Name": "766( 326,426 )",
    "Teams": "RIP-DIOGO.20( pranam rai )",
    "SXL": "IND",
    "Latp": "41",
    "Player_1": "Areola MUN",
    "Player_11": "Haaland 24",
    "Player_10": "Eze BRE",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Woltemade 1",
    "Player_14": "Thiago ARS",
    "Player_7": "B.Fernandes WHU",
    "Player_2": "Mu\u00F1oz BUR",
    "Player_5": "Cucurella LEE",
    "Player_6": "Est\u00EAv\u00E3o LEE",
    "Player_3": "Matheus N.",
    "Player_4": "Est\u00E8ve CRY",
    "Player_8": "Foden 14",
    "Player_9": "Kudus 1",
    "Player_15": "Tarkowski 6"
  },
  {
    "manager_Name": "763( 358,119 )",
    "Teams": "error404( Duri Tadu )",
    "SXL": "IND",
    "Latp": "31",
    "Player_1": "Raya BRE",
    "Player_11": "Haaland 24",
    "Player_10": "Mateta BUR",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Andersen 0",
    "Player_14": "Marc Guiu",
    "Player_7": "Saka BRE",
    "Player_2": "J.Timber BRE",
    "Player_5": "Minteh AVL",
    "Player_6": "Enzo LEE",
    "Player_3": "Richards BUR",
    "Player_4": "Virgil SUN",
    "Player_8": "Semenyo 4",
    "Player_9": "Ndiaye 3",
    "Player_15": "Rodon CHE"
  },
  {
    "manager_Name": "763( 364,389 )",
    "Teams": "PWS( Z S )",
    "SXL": "IND",
    "Latp": "28",
    "Player_1": "Donnarumma 0",
    "Player_11": "Haaland 24",
    "Player_10": "Thiago ARS",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Senesi 0",
    "Player_14": "Van de",
    "Player_7": "B.Fernandes WHU",
    "Player_2": "Richards BUR",
    "Player_5": "Rice BRE",
    "Player_6": "Semenyo 4",
    "Player_3": "O\u2019Reilly 0",
    "Player_4": "J.Timber BRE",
    "Player_8": "Gakpo SUN",
    "Player_9": "Mateta BUR",
    "Player_15": "Caicedo LEE"
  },
  {
    "manager_Name": "757( 458,823 )",
    "Teams": "MANCHESTER IS BLUE( PRAYAS BAJGAI )",
    "SXL": "IND",
    "Latp": "45",
    "Player_1": "A.Becker SUN",
    "Player_11": "Haaland 24",
    "Player_10": "Mateta BUR",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Thiago ARS",
    "Player_14": "Senesi 0",
    "Player_7": "Dewsbury-Hall 3",
    "Player_2": "Richards BUR",
    "Player_5": "Saka BRE",
    "Player_6": "Foden 14",
    "Player_3": "Andersen 0",
    "Player_4": "J.Timber BRE",
    "Player_8": "Semenyo 4",
    "Player_9": "Minteh AVL",
    "Player_15": "Rodon CHE"
  },
  {
    "manager_Name": "752( 540,196 )",
    "Teams": "Fu\u00DFball-Mannschaft( Gaurav Shrestha )",
    "SXL": "IND",
    "Latp": "19",
    "Player_1": "Raya BRE",
    "Player_11": "Mateta BUR",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Andersen 0",
    "Player_14": "Rodon CHE",
    "Player_7": "Minteh AVL",
    "Player_2": "Virgil SUN",
    "Player_5": "Saka BRE",
    "Player_6": "Semenyo 4",
    "Player_3": "Senesi 0",
    "Player_4": "Richards BUR",
    "Player_8": "Ndiaye 3",
    "Player_9": "Haaland 12",
    "Player_15": "Stach CHE"
  },
  {
    "manager_Name": "750( 585,848 )",
    "Teams": "Kung fu Pandoos( Indrajeet Singh )",
    "SXL": "IND",
    "Latp": "43",
    "Player_1": "S\u00E1nchez LEE",
    "Player_11": "Welbeck AVL",
    "Player_10": "Haaland 24",
    "Player_12": "Kelleher ARS",
    "Player_13": "Grealish 8",
    "Player_14": "Walker CRY",
    "Player_7": "Foden 14",
    "Player_2": "Virgil SUN",
    "Player_5": "Pedro Porro",
    "Player_6": "Semenyo 4",
    "Player_3": "Gvardiol 0",
    "Player_4": "De Ligt",
    "Player_8": "Mbeumo WHU",
    "Player_9": "Thiago ARS",
    "Player_15": "A.Ramsey CRY"
  },
  {
    "manager_Name": "744( 709,970 )",
    "Teams": "Top Gooner( VibhutiHang Subba )",
    "SXL": "IND",
    "Latp": "28",
    "Player_1": "Raya BRE",
    "Player_11": "Mateta BUR",
    "Player_10": "Haaland 24",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Minteh AVL",
    "Player_14": "Senesi 0",
    "Player_7": "Semenyo 4",
    "Player_2": "Mukiele LIV",
    "Player_5": "Mbeumo WHU",
    "Player_6": "Anderson WOL",
    "Player_3": "J.Timber BRE",
    "Player_4": "Lacroix BUR",
    "Player_8": "Saka BRE",
    "Player_9": "Welbeck AVL",
    "Player_15": "Rodon CHE"
  },
  {
    "manager_Name": "741( 799,593 )",
    "Teams": "Comet FC( Pranesh Sharma )",
    "SXL": "IND",
    "Latp": "29",
    "Player_1": "S\u00E1nchez LEE",
    "Player_11": "Haaland 24",
    "Player_10": "Welbeck AVL",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Ndiaye 3",
    "Player_14": "Andersen 0",
    "Player_7": "Neto LEE",
    "Player_2": "Virgil SUN",
    "Player_5": "Saka BRE",
    "Player_6": "Semenyo 4",
    "Player_3": "Cash BHA",
    "Player_4": "J.Timber BRE",
    "Player_8": "Rogers BHA",
    "Player_9": "Woltemade 1",
    "Player_15": "Est\u00E8ve CRY"
  },
  {
    "manager_Name": "724( 1,291,038 )",
    "Teams": "\u0160e\u0161ko and Destroy( Pema Lepcha )",
    "SXL": "IND",
    "Latp": "37",
    "Player_1": "D\u00FAbravka CRY",
    "Player_11": "Haaland 24",
    "Player_10": "Welbeck AVL",
    "Player_12": "Raya BRE",
    "Player_13": "Zubimendi BRE",
    "Player_14": "Cucurella LEE",
    "Player_7": "Semenyo 4",
    "Player_2": "Van de",
    "Player_5": "Gakpo SUN",
    "Player_6": "Grealish 8",
    "Player_3": "Senesi 0",
    "Player_4": "Virgil SUN",
    "Player_8": "Mbeumo WHU",
    "Player_9": "Woltemade 1",
    "Player_15": "Mu\u00F1oz BUR"
  },
  {
    "manager_Name": "713( 1,690,173 )",
    "Teams": "Lu Lu( Nishant Lohagun )",
    "SXL": "IND",
    "Latp": "36",
    "Player_1": "Raya BRE",
    "Player_11": "Mateta BUR",
    "Player_10": "Haaland 24",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Senesi 0",
    "Player_14": "Reijnders 7",
    "Player_7": "Semenyo 4",
    "Player_2": "Andersen 0",
    "Player_5": "Richards BUR",
    "Player_6": "B.Fernandes WHU",
    "Player_3": "Virgil SUN",
    "Player_4": "Mu\u00F1oz BUR",
    "Player_8": "Doku 8",
    "Player_9": "Saka BRE",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "712( 1,729,545 )",
    "Teams": "Blue Brigade( Bhuman Basnet )",
    "SXL": "IND",
    "Latp": "28",
    "Player_1": "D\u00FAbravka CRY",
    "Player_11": "Thiago ARS",
    "Player_10": "Haaland 24",
    "Player_12": "Vicario 1",
    "Player_13": "Senesi 0",
    "Player_14": "Kudus 1",
    "Player_7": "Enzo LEE",
    "Player_2": "O\u2019Reilly 0",
    "Player_5": "Semenyo 4",
    "Player_6": "Bruno G.",
    "Player_3": "Gu\u00E9hi BUR",
    "Player_4": "Calafiori BRE",
    "Player_8": "Mbeumo WHU",
    "Player_9": "Mateta BUR",
    "Player_15": "Tuanzebe CRY"
  },
  {
    "manager_Name": "700( 2,225,241 )",
    "Teams": "ASHLAD FC( Ashim Lama )",
    "SXL": "IND",
    "Latp": "31",
    "Player_1": "D\u00FAbravka CRY",
    "Player_11": "Thiago ARS",
    "Player_10": "Haaland 24",
    "Player_12": "Roefs LIV",
    "Player_13": "J.Timber BRE",
    "Player_14": "Van de",
    "Player_7": "Sarr BUR",
    "Player_2": "Senesi 0",
    "Player_5": "Rice BRE",
    "Player_6": "Ndiaye 3",
    "Player_3": "Virgil SUN",
    "Player_4": "Gvardiol 0",
    "Player_8": "Semenyo 4",
    "Player_9": "Mateta BUR",
    "Player_15": "Caicedo LEE"
  },
  {
    "manager_Name": "698( 2,322,645 )",
    "Teams": "Bruno-nly Fans( Bejoy M Shrestha\u00B2\u2076\u2074 )",
    "SXL": "IND",
    "Latp": "16",
    "Player_1": "Raya BRE",
    "Player_11": "Woltemade 1",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "King 1",
    "Player_14": "Senesi 0",
    "Player_7": "Ndiaye 3",
    "Player_2": "Gu\u00E9hi BUR",
    "Player_5": "Saka BRE",
    "Player_6": "Minteh AVL",
    "Player_3": "Virgil SUN",
    "Player_4": "Van de",
    "Player_8": "Mbeumo WHU",
    "Player_9": "Thiago ARS",
    "Player_15": "Gudmundsson CHE"
  },
  {
    "manager_Name": "695( 2,442,660 )",
    "Teams": "PINE( SATYAM RAI )",
    "SXL": "IND",
    "Latp": "17",
    "Player_1": "Raya BRE",
    "Player_11": "Haaland 12",
    "Player_10": "Mateta BUR",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Mukiele LIV",
    "Player_14": "Rodon CHE",
    "Player_7": "Anderson WOL",
    "Player_2": "J.Timber BRE",
    "Player_5": "Rogers BHA",
    "Player_6": "Mbeumo WHU",
    "Player_3": "Virgil SUN",
    "Player_4": "Burn 1",
    "Player_8": "Semenyo 4",
    "Player_9": "Saka BRE",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "695( 2,465,899 )",
    "Teams": "Liverpool FC( Sunil Rai )",
    "SXL": "IND",
    "Latp": "25",
    "Player_1": "S\u00E1nchez LEE",
    "Player_11": "Haaland 24",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Pope 0",
    "Player_13": "Tavernier 1",
    "Player_14": "Van de",
    "Player_7": "Minteh AVL",
    "Player_2": "Senesi 0",
    "Player_5": "Virgil SUN",
    "Player_6": "Mbeumo WHU",
    "Player_3": "Gvardiol 0",
    "Player_4": "Mu\u00F1oz BUR",
    "Player_8": "Enzo LEE",
    "Player_9": "Woltemade 1",
    "Player_15": "Grealish 8"
  },
  {
    "manager_Name": "692( 2,614,695 )",
    "Teams": "G\u00CBNJ\u00CF\u00CF UNITED( Pema Bhutia )",
    "SXL": "IND",
    "Latp": "40",
    "Player_1": "Raya BRE",
    "Player_11": "Haaland 24",
    "Player_10": "Woltemade 1",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Thiago ARS",
    "Player_14": "Van de",
    "Player_7": "B.Fernandes WHU",
    "Player_2": "Thiaw 1",
    "Player_5": "Minteh AVL",
    "Player_6": "Rice BRE",
    "Player_3": "Virgil SUN",
    "Player_4": "Richards BUR",
    "Player_8": "Mbeumo WHU",
    "Player_9": "Foden 14",
    "Player_15": "Alderete LIV"
  },
  {
    "manager_Name": "678( 3,267,133 )",
    "Teams": "Cheesygarlic( Rishi Thulung )",
    "SXL": "IND",
    "Latp": "36",
    "Player_1": "S\u00E1nchez LEE",
    "Player_11": "Kroupi.Jr 2",
    "Player_10": "Haaland 24",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Thiago ARS",
    "Player_14": "Mukiele LIV",
    "Player_7": "Saka BRE",
    "Player_2": "J.Timber BRE",
    "Player_5": "Mbeumo WHU",
    "Player_6": "Semenyo 4",
    "Player_3": "Tarkowski 6",
    "Player_4": "Mu\u00F1oz BUR",
    "Player_8": "Enzo LEE",
    "Player_9": "Xhaka LIV",
    "Player_15": "Botman 0"
  },
  {
    "manager_Name": "678( 3,278,927 )",
    "Teams": "F.C. ASSASSINS( Kushal Sahota )",
    "SXL": "IND",
    "Latp": "28",
    "Player_1": "Roefs LIV",
    "Player_11": "Haaland 24",
    "Player_10": "Welbeck AVL",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Van de",
    "Player_14": "King 1",
    "Player_7": "Mbeumo WHU",
    "Player_2": "Gu\u00E9hi BUR",
    "Player_5": "Est\u00E8ve CRY",
    "Player_6": "Saka BRE",
    "Player_3": "J.Timber BRE",
    "Player_4": "O\u2019Reilly 0",
    "Player_8": "Semenyo 4",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Caicedo LEE"
  },
  {
    "manager_Name": "678( 3,296,715 )",
    "Teams": "Busby Baby( Regean Lama )",
    "SXL": "IND",
    "Latp": "47",
    "Player_1": "D\u00FAbravka CRY",
    "Player_11": "Woltemade 1",
    "Player_10": "Thiago ARS",
    "Player_12": "S\u00E1nchez LEE",
    "Player_13": "Reijnders 7",
    "Player_14": "Dorgu WHU",
    "Player_7": "Mbeumo WHU",
    "Player_2": "Van de",
    "Player_5": "Grealish 8",
    "Player_6": "Foden 14",
    "Player_3": "J.Timber BRE",
    "Player_4": "Mu\u00F1oz BUR",
    "Player_8": "B.Fernandes WHU",
    "Player_9": "Haaland 24",
    "Player_15": "Alex Moreno"
  },
  {
    "manager_Name": "668( 3,788,863 )",
    "Teams": "GustavousGooner( Ashish Subba )",
    "SXL": "IND",
    "Latp": "17",
    "Player_1": "D\u00FAbravka CRY",
    "Player_11": "Mateta BUR",
    "Player_10": "Haaland 12",
    "Player_12": "S\u00E1nchez LEE",
    "Player_13": "Cullen CRY",
    "Player_14": "Gudmundsson CHE",
    "Player_7": "Saka BRE",
    "Player_2": "Gu\u00E9hi BUR",
    "Player_5": "Szoboszlai SUN",
    "Player_6": "Rice BRE",
    "Player_3": "Livramento 1",
    "Player_4": "O\u2019Reilly 0",
    "Player_8": "Semenyo 4",
    "Player_9": "Thiago ARS",
    "Player_15": "Senesi 0"
  },
  {
    "manager_Name": "662( 4,116,855 )",
    "Teams": "Imperial Blues( Saurabh Tamang )",
    "SXL": "IND",
    "Latp": "39",
    "Player_1": "S\u00E1nchez LEE",
    "Player_11": "Mateta BUR",
    "Player_10": "Haaland 24",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Foster CRY",
    "Player_14": "Botman 0",
    "Player_7": "Mbeumo WHU",
    "Player_2": "J.Timber BRE",
    "Player_5": "Doku 8",
    "Player_6": "Semenyo 4",
    "Player_3": "Richards BUR",
    "Player_4": "O\u2019Reilly 0",
    "Player_8": "Ndiaye 3",
    "Player_9": "Saka BRE",
    "Player_15": "Est\u00E8ve CRY"
  },
  {
    "manager_Name": "662( 4,129,753 )",
    "Teams": "The Regista.( Passang T Sherpa )",
    "SXL": "IND",
    "Latp": "21",
    "Player_1": "D\u00FAbravka CRY",
    "Player_11": "Haaland 12",
    "Player_10": "Woltemade 1",
    "Player_12": "Roefs LIV",
    "Player_13": "Grealish 8",
    "Player_14": "Thiago ARS",
    "Player_7": "Mbeumo WHU",
    "Player_2": "Cucurella LEE",
    "Player_5": "Keane 0",
    "Player_6": "Rice BRE",
    "Player_3": "O\u2019Reilly 0",
    "Player_4": "Gu\u00E9hi BUR",
    "Player_8": "Semenyo 8",
    "Player_9": "Minteh AVL",
    "Player_15": "Est\u00E8ve CRY"
  },
  {
    "manager_Name": "653( 4,581,937 )",
    "Teams": "Native United( Monlom Rongong )",
    "SXL": "IND",
    "Latp": "33",
    "Player_1": "Raya BRE",
    "Player_11": "Haaland 24",
    "Player_10": "Mateta BUR",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Senesi 0",
    "Player_14": "Gabriel BRE",
    "Player_7": "Ndiaye 3",
    "Player_2": "Rodon CHE",
    "Player_5": "King 1",
    "Player_6": "Mbeumo WHU",
    "Player_3": "J.Timber BRE",
    "Player_4": "Gu\u00E9hi BUR",
    "Player_8": "Semenyo 4",
    "Player_9": "Woltemade 1",
    "Player_15": "Caicedo LEE"
  },
  {
    "manager_Name": "645( 5,011,487 )",
    "Teams": "Hooligans25( Pradhyumna Subba )",
    "SXL": "IND",
    "Latp": "26",
    "Player_1": "Raya BRE",
    "Player_11": "Haaland 24",
    "Player_10": "Woltemade 1",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Reijnders 7",
    "Player_14": "Van de",
    "Player_7": "Cherki 1",
    "Player_2": "Mitchell BUR",
    "Player_5": "Neto LEE",
    "Player_6": "Mbeumo WHU",
    "Player_3": "Richards BUR",
    "Player_4": "J.Timber BRE",
    "Player_8": "Eze BRE",
    "Player_9": "Ekitik\u00E9 SUN",
    "Player_15": "Reinildo LIV"
  },
  {
    "manager_Name": "641( 5,229,574 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "25",
    "Player_1": "Raya BRE",
    "Player_11": "Haaland 24",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Mukiele LIV",
    "Player_14": "Gudmundsson CHE",
    "Player_7": "Rice BRE",
    "Player_2": "Mitchell BUR",
    "Player_5": "Xhaka LIV",
    "Player_6": "Saka BRE",
    "Player_3": "Cucurella LEE",
    "Player_4": "Mu\u00F1oz BUR",
    "Player_8": "Gakpo SUN",
    "Player_9": "L.Miley 1",
    "Player_15": "Thiago ARS"
  },
  {
    "manager_Name": "637( 5,429,005 )",
    "Teams": "GODFATHER FC( Riwaj Rai )",
    "SXL": "IND",
    "Latp": "34",
    "Player_1": "D\u00FAbravka CRY",
    "Player_11": "Haaland 24",
    "Player_10": "Isidor LIV",
    "Player_12": "Sels WOL",
    "Player_13": "Cash BHA",
    "Player_14": "Semenyo 4",
    "Player_7": "Caicedo LEE",
    "Player_2": "Gu\u00E9hi BUR",
    "Player_5": "Kudus 1",
    "Player_6": "O.Dango ARS",
    "Player_3": "Cucurella LEE",
    "Player_4": "Pedro Porro",
    "Player_8": "Grealish 8",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Est\u00E8ve CRY"
  },
  {
    "manager_Name": "621( 6,257,391 )",
    "Teams": "I_am_done_XI( Dipen Thapa )",
    "SXL": "IND",
    "Latp": "10",
    "Player_1": "Raya BRE",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Mateta BUR",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Caicedo LEE",
    "Player_14": "Senesi 0",
    "Player_7": "M.Salah SUN",
    "Player_2": "Gu\u00E9hi BUR",
    "Player_5": "Eze BRE",
    "Player_6": "Kudus 1",
    "Player_3": "Hincapie BRE",
    "Player_4": "Konsa BHA",
    "Player_8": "Grealish 8",
    "Player_9": "Woltemade 1",
    "Player_15": "Est\u00E8ve CRY"
  },
  {
    "manager_Name": "620( 6,319,052 )",
    "Teams": "GUNNERS( Omkar Subba )",
    "SXL": "IND",
    "Latp": "39",
    "Player_1": "Raya BRE",
    "Player_11": "Thiago ARS",
    "Player_10": "Haaland 24",
    "Player_12": "Verbruggen AVL",
    "Player_13": "Semenyo 4",
    "Player_14": "Senesi 0",
    "Player_7": "Gravenberch SUN",
    "Player_2": "Gu\u00E9hi BUR",
    "Player_5": "Mu\u00F1oz BUR",
    "Player_6": "Rice BRE",
    "Player_3": "Virgil SUN",
    "Player_4": "O\u2019Reilly 0",
    "Player_8": "Foden 14",
    "Player_9": "Woltemade 1",
    "Player_15": "Anthony CRY"
  },
  {
    "manager_Name": "616( 6,516,943 )",
    "Teams": "Let MEE COOK( \u00CFaraplang Pompyrthat )",
    "SXL": "IND",
    "Latp": "39",
    "Player_1": "Pope 0",
    "Player_11": "Haaland 24",
    "Player_10": "Woltemade 1",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Xhaka LIV",
    "Player_14": "Rodon CHE",
    "Player_7": "Rogers BHA",
    "Player_2": "J.Timber BRE",
    "Player_5": "Mbeumo WHU",
    "Player_6": "Foden 14",
    "Player_3": "Lacroix BUR",
    "Player_4": "Virgil SUN",
    "Player_8": "Enzo LEE",
    "Player_9": "Mateta BUR",
    "Player_15": "Est\u00E8ve CRY"
  },
  {
    "manager_Name": "615( 6,563,044 )",
    "Teams": "Hangkim_0011( ABHINANDAN RAI )",
    "SXL": "IND",
    "Latp": "36",
    "Player_1": "S\u00E1nchez LEE",
    "Player_11": "Welbeck AVL",
    "Player_10": "Haaland 24",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "Burn 1",
    "Player_14": "Szoboszlai SUN",
    "Player_7": "Mbeumo WHU",
    "Player_2": "Gu\u00E9hi BUR",
    "Player_5": "Neto LEE",
    "Player_6": "Doku 8",
    "Player_3": "Konsa BHA",
    "Player_4": "Gvardiol 0",
    "Player_8": "Semenyo 4",
    "Player_9": "Mateta BUR",
    "Player_15": "Est\u00E8ve CRY"
  },
  {
    "manager_Name": "599( 7,318,362 )",
    "Teams": "Jorebungalow YFC( Vivek Lama )",
    "SXL": "IND",
    "Latp": "18",
    "Player_1": "D\u00FAbravka CRY",
    "Player_11": "Mateta BUR",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Areola MUN",
    "Player_13": "L.Miley 1",
    "Player_14": "Thiaw 1",
    "Player_7": "Semenyo 4",
    "Player_2": "Calafiori BRE",
    "Player_5": "Minteh AVL",
    "Player_6": "Saka BRE",
    "Player_3": "Van de",
    "Player_4": "O\u2019Reilly 0",
    "Player_8": "Gakpo SUN",
    "Player_9": "Haaland 12",
    "Player_15": "Est\u00E8ve CRY"
  },
  {
    "manager_Name": "589( 7,764,957 )",
    "Teams": "Boehly Blues( Aditya Bhandari )",
    "SXL": "IND",
    "Latp": "28",
    "Player_1": "Petrovi\u0107 2",
    "Player_11": "Haaland 24",
    "Player_10": "Mateta BUR",
    "Player_12": "D\u00FAbravka CRY",
    "Player_13": "James LEE",
    "Player_14": "Devenny BUR",
    "Player_7": "Palmer LEE",
    "Player_2": "Gvardiol 0",
    "Player_5": "Minteh AVL",
    "Player_6": "Bruno G.",
    "Player_3": "Mu\u00F1oz BUR",
    "Player_4": "J.Timber BRE",
    "Player_8": "Mbeumo WHU",
    "Player_9": "Woltemade 1",
    "Player_15": "Heaven WHU"
  },
  {
    "manager_Name": "565( 8,692,829 )",
    "Teams": "Invincibles( Bishal Rai )",
    "SXL": "IND",
    "Latp": "5",
    "Player_1": "Raya BRE",
    "Player_11": "Mateta BUR",
    "Player_10": "Thiago ARS",
    "Player_12": "Kinsky 0",
    "Player_13": "Neto LEE",
    "Player_14": "Enzo LEE",
    "Player_7": "Mbeumo WHU",
    "Player_2": "Mu\u00F1oz BUR",
    "Player_5": "Milenkovi\u0107 WOL",
    "Player_6": "Semenyo 4",
    "Player_3": "J.Timber BRE",
    "Player_4": "Pedro Porro",
    "Player_8": "Minteh AVL",
    "Player_9": "Ekitik\u00E9 SUN",
    "Player_15": "Gabriel BRE"
  }
];