var s = [
  {
    "manager_Name": "1,814( 1,298,178 ) TotalXfr : 32",
    "Teams": "AmPaduDhaan( Aravind SA )",
    "SXL": "countryCode",
    "Latp": "26",
    "Player_1": "Fabianski 0",
    "Player_11": "Haaland 14",
    "Player_10": "Beto 2",
    "Player_12": "Henderson -",
    "Player_13": "Rogers -",
    "Player_14": "Isak -",
    "Player_7": "Palmer ARS (A)",
    "Player_2": "Virgil -",
    "Player_5": "Murillo 1",
    "Player_6": "Bowen 5",
    "Player_3": "Colwill ARS (A)",
    "Player_4": "Mykolenko 2",
    "Player_8": "O.Dango 1",
    "Player_9": "Semenyo 1",
    "Player_15": "Mu\u00F1oz -"
  },
  {
    "manager_Name": "1,791( 1,695,561 ) TotalXfr : 34",
    "Teams": "Ruben\u0027s Ammonition( Aditya Desai )",
    "SXL": "countryCode",
    "Latp": "8",
    "Player_1": "Raya CHE (H)",
    "Player_11": "Wood 4",
    "Player_10": "M.Salah -",
    "Player_12": "Fabianski 0",
    "Player_13": "Rogers -",
    "Player_14": "Nketiah -",
    "Player_7": "O.Dango 1",
    "Player_2": "Gvardiol 1",
    "Player_5": "Huijsen 1",
    "Player_6": "N.Williams 1",
    "Player_3": "Robinson TOT (H)",
    "Player_4": "Colwill ARS (A)",
    "Player_8": "Nwaneri CHE (H)",
    "Player_9": "Palmer ARS (A)",
    "Player_15": "Isak -"
  },
  {
    "manager_Name": "1,785( 1,797,682 ) TotalXfr : 27",
    "Teams": "Mateta Vada( Amogh Ranadive )",
    "SXL": "countryCode",
    "Latp": "44",
    "Player_1": "Pickford 3",
    "Player_11": "Haaland 7",
    "Player_10": "Wissa 8",
    "Player_12": "Ward MUN (H)",
    "Player_13": "Son FUL (A)",
    "Player_14": "Kerkez 4",
    "Player_7": "Gibbs-White 5",
    "Player_2": "Cucurella ARS (A)",
    "Player_5": "B.Fernandes LEI (A)",
    "Player_6": "Kluivert 2",
    "Player_3": "Milenkovi\u0107 11",
    "Player_4": "Dalot LEI (A)",
    "Player_8": "Mbeumo 6",
    "Player_9": "Wood 2",
    "Player_15": "Vestergaard MUN (H)"
  },
  {
    "manager_Name": "1,737( 2,729,516 ) TotalXfr : 23",
    "Teams": "Lavia ka Baal( The Banat )",
    "SXL": "countryCode",
    "Latp": "11",
    "Player_1": "A.Becker -",
    "Player_11": "Gakpo -",
    "Player_10": "Wood 2",
    "Player_12": "Sels 1",
    "Player_13": "Dibling 5",
    "Player_14": "Faes MUN (H)",
    "Player_7": "Palmer ARS (A)",
    "Player_2": "Aina 1",
    "Player_5": "M.Salah -",
    "Player_6": "Kluivert 2",
    "Player_3": "Saliba CHE (H)",
    "Player_4": "Hall -",
    "Player_8": "Mbeumo 6",
    "Player_9": "Isak -",
    "Player_15": "Greaves 0"
  },
  {
    "manager_Name": "1,714( 3,188,905 ) TotalXfr : 18",
    "Teams": "Change Name( \u010C\u022B\u0271\u03FB\u04D1\u1D28\u0257\u03AD\u01A6 \u010A\u00F6\u0159\u024D\u0268\u03AC\u1D70\u1E0B\u1E17\u0212 )",
    "SXL": "countryCode",
    "Latp": "24",
    "Player_1": "Flekken 3",
    "Player_11": "Wissa 8",
    "Player_10": "Isak -",
    "Player_12": "S\u00E1nchez ARS (A)",
    "Player_13": "Tarkowski 2",
    "Player_14": "Kilman 2",
    "Player_7": "Palmer ARS (A)",
    "Player_2": "Gabriel CHE (H)",
    "Player_5": "M.Salah -",
    "Player_6": "\u00D8degaard CHE (H)",
    "Player_3": "Hall -",
    "Player_4": "Milenkovi\u0107 11",
    "Player_8": "Smith Rowe TOT (H)",
    "Player_9": "Wood 2",
    "Player_15": "Rogers -"
  },
  {
    "manager_Name": "1,499( 6,452,391 ) TotalXfr : 4",
    "Teams": "RicePlate( Tushar Abhichandani )",
    "SXL": "countryCode",
    "Latp": "18",
    "Player_1": "Raya CHE (H)",
    "Player_11": "Isak -",
    "Player_10": "Haaland 14",
    "Player_12": "Matthews -",
    "Player_13": "Barco 0",
    "Player_14": "Rogers -",
    "Player_7": "Onana -",
    "Player_2": "Pedro Porro FUL (A)",
    "Player_5": "Bernardo 1",
    "Player_6": "M.Salah -",
    "Player_3": "Gvardiol 1",
    "Player_4": "Quansah -",
    "Player_8": "Diogo J. -",
    "Player_9": "Beto 2",
    "Player_15": "Robinson TOT (H)"
  }
];