var s = [
  {
    "manager_Name": "553( 24,457 )",
    "Teams": "Charlie\u0027s Angels( Charlie Smith )",
    "SXL": "ENG",
    "Latp": "84",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "P.M.Sarr 1",
    "Player_14": "King 2",
    "Player_7": "M.Salah 2",
    "Player_2": "Mukiele 17",
    "Player_5": "Van de",
    "Player_6": "Saliba 6",
    "Player_3": "Cucurella 8",
    "Player_4": "Gabriel 12",
    "Player_8": "Semenyo 4",
    "Player_9": "Reijnders 1",
    "Player_15": "Abdullahi 0"
  },
  {
    "manager_Name": "532( 112,624 )",
    "Teams": "Rice Rice Baby( kaisler Schembri )",
    "SXL": "MLT",
    "Latp": "69",
    "Player_1": "Donnarumma 6",
    "Player_11": "Haaland 26",
    "Player_10": "Woltemade 8",
    "Player_12": "Darlow 1",
    "Player_13": "Mbeumo 9",
    "Player_14": "Est\u00E8ve 8",
    "Player_7": "Reijnders 1",
    "Player_2": "Tarkowski 3",
    "Player_5": "Ndiaye 4",
    "Player_6": "Semenyo 4",
    "Player_3": "Gabriel 12",
    "Player_4": "Van de",
    "Player_8": "Eze 3",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Wan-Bissaka 1"
  },
  {
    "manager_Name": "525( 174,279 )",
    "Teams": "Arteta Ball FC( Dylan Camilleri )",
    "SXL": "MLT",
    "Latp": "75",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "Sels 2",
    "Player_13": "Ndiaye 4",
    "Player_14": "Tarkowski 3",
    "Player_7": "Kudus 2",
    "Player_2": "Gabriel 12",
    "Player_5": "Semenyo 4",
    "Player_6": "Reijnders 1",
    "Player_3": "Est\u00E8ve 8",
    "Player_4": "Mu\u00F1oz 10",
    "Player_8": "Sarr 2",
    "Player_9": "Gy\u00F6keres 2",
    "Player_15": "Konsa 2"
  },
  {
    "manager_Name": "522( 213,583 )",
    "Teams": "Taggers FC( Karl Caruana )",
    "SXL": "MLT",
    "Latp": "86",
    "Player_1": "D\u00FAbravka 9",
    "Player_11": "Woltemade 8",
    "Player_10": "Haaland 26",
    "Player_12": "Kelleher 6",
    "Player_13": "Est\u00E8ve 8",
    "Player_14": "Konsa 2",
    "Player_7": "Ndiaye 4",
    "Player_2": "Gabriel 12",
    "Player_5": "M.Salah 2",
    "Player_6": "Kudus 2",
    "Player_3": "Van de",
    "Player_4": "Mukiele 17",
    "Player_8": "Semenyo 4",
    "Player_9": "Minteh 2",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "518( 261,300 )",
    "Teams": "MaltArsenal FC( Claude Spiteri )",
    "SXL": "MLT",
    "Latp": "88",
    "Player_1": "Pope 2",
    "Player_11": "Woltemade 8",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Enzo 0",
    "Player_14": "B.Fernandes 8",
    "Player_7": "Kudus 2",
    "Player_2": "Gudmundsson 1",
    "Player_5": "Calafiori 6",
    "Player_6": "Est\u00E8ve 8",
    "Player_3": "Gabriel 12",
    "Player_4": "Senesi 2",
    "Player_8": "Semenyo 4",
    "Player_9": "Mateta 17",
    "Player_15": "Grealish 0"
  },
  {
    "manager_Name": "518( 265,040 )",
    "Teams": "TetasSexyReds( Gary Pace )",
    "SXL": "MLT",
    "Latp": "67",
    "Player_1": "D\u00FAbravka 9",
    "Player_11": "Haaland 26",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Sels 2",
    "Player_13": "Mbeumo 9",
    "Player_14": "Grealish 0",
    "Player_7": "Reijnders 1",
    "Player_2": "Gabriel 12",
    "Player_5": "Diouf 1",
    "Player_6": "Rice 3",
    "Player_3": "Pedro Porro",
    "Player_4": "Senesi 2",
    "Player_8": "Kudus 2",
    "Player_9": "Woltemade 8",
    "Player_15": "Andersen 1"
  },
  {
    "manager_Name": "514( 324,252 )",
    "Teams": "Bend it like Boogie( Ryan Bonello Gatt )",
    "SXL": "MLT",
    "Latp": "81",
    "Player_1": "Kelleher 6",
    "Player_11": "Isidor 2",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Sels 2",
    "Player_13": "Reijnders 1",
    "Player_14": "Wan-Bissaka 1",
    "Player_7": "Semenyo 4",
    "Player_2": "Gabriel 12",
    "Player_5": "Virgil 3",
    "Player_6": "Mbeumo 9",
    "Player_3": "R\u00FAben 6",
    "Player_4": "Gu\u00E9hi 4",
    "Player_8": "Gakpo 7",
    "Player_9": "Haaland 26",
    "Player_15": "Grealish 0"
  },
  {
    "manager_Name": "513( 336,948 )",
    "Teams": "Ellul FC( Andrew Ellul )",
    "SXL": "MLT",
    "Latp": "54",
    "Player_1": "Pope 2",
    "Player_11": "Haaland 13",
    "Player_10": "Richarlison 1",
    "Player_12": "Henderson 1",
    "Player_13": "Romero 0",
    "Player_14": "Mitoma 0",
    "Player_7": "Zubimendi 3",
    "Player_2": "Gu\u00E9hi 4",
    "Player_5": "Van de",
    "Player_6": "Rice 3",
    "Player_3": "Gabriel 12",
    "Player_4": "Milenkovi\u0107 1",
    "Player_8": "Semenyo 8",
    "Player_9": "Gakpo 7",
    "Player_15": "Evanilson 0"
  },
  {
    "manager_Name": "508( 440,771 )",
    "Teams": "Slika FC( Kyle Gatt )",
    "SXL": "MLT",
    "Latp": "67",
    "Player_1": "Pope 2",
    "Player_11": "Haaland 26",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Darlow 1",
    "Player_13": "Enzo 0",
    "Player_14": "Sch\u00E4r 0",
    "Player_7": "Eze 3",
    "Player_2": "Hartman 6",
    "Player_5": "Ndiaye 4",
    "Player_6": "Kudus 2",
    "Player_3": "Pedro Porro",
    "Player_4": "Gabriel 12",
    "Player_8": "Reijnders 1",
    "Player_9": "Woltemade 8",
    "Player_15": "Gvardiol 0"
  },
  {
    "manager_Name": "506( 485,401 )",
    "Teams": "diavoli 11( Paul Micallef )",
    "SXL": "MLT",
    "Latp": "73",
    "Player_1": "Donnarumma 6",
    "Player_11": "Haaland 26",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Setford 0",
    "Player_13": "Caicedo 1",
    "Player_14": "Kudus 2",
    "Player_7": "Semenyo 4",
    "Player_2": "Gu\u00E9hi 4",
    "Player_5": "Gabriel 12",
    "Player_6": "B.Fernandes 8",
    "Player_3": "Senesi 2",
    "Player_4": "Chalobah 6",
    "Player_8": "Reijnders 1",
    "Player_9": "Bowen 2",
    "Player_15": "Byram 0"
  },
  {
    "manager_Name": "498( 696,670 )",
    "Teams": "Old Havertz Kai Hard( Andy Bonaci )",
    "SXL": "MLT",
    "Latp": "69",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Caicedo 1",
    "Player_14": "Senesi 2",
    "Player_7": "Semenyo 4",
    "Player_2": "Lacroix 1",
    "Player_5": "Gabriel 12",
    "Player_6": "Sarr 2",
    "Player_3": "Mu\u00F1oz 10",
    "Player_4": "Virgil 3",
    "Player_8": "Reijnders 1",
    "Player_9": "Isak 2",
    "Player_15": "Dewsbury-Hall 2"
  },
  {
    "manager_Name": "496( 752,913 )",
    "Teams": "gunner_xi( Justin kind )",
    "SXL": "MLT",
    "Latp": "70",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Romero 0",
    "Player_14": "Ndoye 0",
    "Player_7": "Gakpo 7",
    "Player_2": "Gabriel 12",
    "Player_5": "Sarr 2",
    "Player_6": "Kudus 2",
    "Player_3": "Cucurella 8",
    "Player_4": "Senesi 2",
    "Player_8": "Reijnders 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Reinildo 0"
  },
  {
    "manager_Name": "494( 812,778 )",
    "Teams": "Bench Warmers( kevin dalli )",
    "SXL": "MLT",
    "Latp": "56",
    "Player_1": "Petrovi\u0107 2",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Kelleher 6",
    "Player_13": "Doku 1",
    "Player_14": "Burn 2",
    "Player_7": "Gakpo 7",
    "Player_2": "Gu\u00E9hi 4",
    "Player_5": "Kudus 2",
    "Player_6": "Semenyo 4",
    "Player_3": "Calafiori 6",
    "Player_4": "Pedro Porro",
    "Player_8": "Reijnders 1",
    "Player_9": "Ekitik\u00E9 1",
    "Player_15": "Est\u00E8ve 8"
  },
  {
    "manager_Name": "488( 1,034,171 )",
    "Teams": "Kind FC( Richard Kind )",
    "SXL": "MLT",
    "Latp": "66",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Henderson 1",
    "Player_13": "Rodon 1",
    "Player_14": "Gravenberch 2",
    "Player_7": "Kudus 2",
    "Player_2": "Dunk 2",
    "Player_5": "Cucurella 8",
    "Player_6": "Reijnders 1",
    "Player_3": "Gabriel 12",
    "Player_4": "Lacroix 1",
    "Player_8": "Semenyo 4",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Grealish 0"
  },
  {
    "manager_Name": "486( 1,127,930 )",
    "Teams": "Noni your business( Owen Farrugia )",
    "SXL": "MLT",
    "Latp": "60",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Ndiaye 4",
    "Player_14": "Andersen 1",
    "Player_7": "Kudus 2",
    "Player_2": "Gabriel 12",
    "Player_5": "Semenyo 4",
    "Player_6": "Xavi 2",
    "Player_3": "Pedro Porro",
    "Player_4": "Senesi 2",
    "Player_8": "Reijnders 1",
    "Player_9": "Haaland 26",
    "Player_15": "Est\u00E8ve 8"
  },
  {
    "manager_Name": "484( 1,193,639 )",
    "Teams": "The Invincibles 49( Clive Caruana )",
    "SXL": "MLT",
    "Latp": "82",
    "Player_1": "Raya 6",
    "Player_11": "Mateta 17",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Grealish 0",
    "Player_7": "Semenyo 4",
    "Player_2": "Virgil 3",
    "Player_5": "J.Timber 6",
    "Player_6": "Reijnders 1",
    "Player_3": "Mu\u00F1oz 10",
    "Player_4": "Van de",
    "Player_8": "Gakpo 7",
    "Player_9": "Kudus 2",
    "Player_15": "Est\u00E8ve 8"
  },
  {
    "manager_Name": "484( 1,209,995 )",
    "Teams": "matthew 14( matthew borg )",
    "SXL": "MLT",
    "Latp": "61",
    "Player_1": "Pope 2",
    "Player_11": "Mateta 17",
    "Player_10": "Haaland 26",
    "Player_12": "Foderingham 0",
    "Player_13": "Pedro Lima",
    "Player_14": "Hughes 0",
    "Player_7": "Wirtz 1",
    "Player_2": "Burn 2",
    "Player_5": "Tarkowski 3",
    "Player_6": "Semenyo 4",
    "Player_3": "Konsa 2",
    "Player_4": "Pedro Porro",
    "Player_8": "Kudus 2",
    "Player_9": "Ekitik\u00E9 1",
    "Player_15": "Grealish 0"
  },
  {
    "manager_Name": "483( 1,242,438 )",
    "Teams": "Hamrun Gunners( Mark Monseigneur )",
    "SXL": "MLT",
    "Latp": "72",
    "Player_1": "Henderson 1",
    "Player_11": "Woltemade 16",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Pickford 2",
    "Player_13": "Grealish 0",
    "Player_14": "Walker 14",
    "Player_7": "Sarr 2",
    "Player_2": "Pedro Porro",
    "Player_5": "Gakpo 7",
    "Player_6": "Neto 12",
    "Player_3": "Virgil 3",
    "Player_4": "Gabriel 12",
    "Player_8": "Rice 3",
    "Player_9": "Haaland 13",
    "Player_15": "Toti 0"
  },
  {
    "manager_Name": "477( 1,521,143 )",
    "Teams": "kurt slika( Kurt Gatt )",
    "SXL": "MLT",
    "Latp": "60",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Jos\u00E9 S\u00E1",
    "Player_13": "J.Palhinha 9",
    "Player_14": "Cucurella 8",
    "Player_7": "Zubimendi 3",
    "Player_2": "Gu\u00E9hi 4",
    "Player_5": "Mbeumo 9",
    "Player_6": "Semenyo 4",
    "Player_3": "Van de",
    "Player_4": "Virgil 3",
    "Player_8": "Reijnders 1",
    "Player_9": "Haaland 26",
    "Player_15": "Senesi 2"
  },
  {
    "manager_Name": "474( 1,647,584 )",
    "Teams": "GunnerPorts( Matthew Portelli )",
    "SXL": "MLT",
    "Latp": "55",
    "Player_1": "Pope 2",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Ndiaye 4",
    "Player_14": "Gvardiol 0",
    "Player_7": "Caicedo 1",
    "Player_2": "Senesi 2",
    "Player_5": "Reijnders 1",
    "Player_6": "Eze 3",
    "Player_3": "Van de",
    "Player_4": "Gabriel 12",
    "Player_8": "Semenyo 4",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "473( 1,687,769 )",
    "Teams": "Clarky FC( Carl Clark )",
    "SXL": "ENG",
    "Latp": "55",
    "Player_1": "Pope 2",
    "Player_11": "Haaland 13",
    "Player_10": "Ekitik\u00E9 1",
    "Player_12": "Leno 3",
    "Player_13": "Mayenda 1",
    "Player_14": "Murillo 1",
    "Player_7": "Saka 7",
    "Player_2": "J.Timber 12",
    "Player_5": "Cullen 3",
    "Player_6": "Caicedo 1",
    "Player_3": "Konat\u00E9 3",
    "Player_4": "Alderete 6",
    "Player_8": "Semenyo 4",
    "Player_9": "Eze 3",
    "Player_15": "Mitchell 1"
  },
  {
    "manager_Name": "471( 1,830,868 )",
    "Teams": "Senglea Gunners( Daryl Ebejer )",
    "SXL": "MLT",
    "Latp": "75",
    "Player_1": "Pope 2",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "Moore 0",
    "Player_13": "Virgil 3",
    "Player_14": "Alderete 6",
    "Player_7": "Eze 3",
    "Player_2": "R\u00FAben 6",
    "Player_5": "Anthony 2",
    "Player_6": "Semenyo 4",
    "Player_3": "Gabriel 12",
    "Player_4": "Lacroix 1",
    "Player_8": "Xhaka 5",
    "Player_9": "Ekitik\u00E9 1",
    "Player_15": "King 2"
  },
  {
    "manager_Name": "468( 1,953,876 )",
    "Teams": "Very Rice( Jake Caruana )",
    "SXL": "MLT",
    "Latp": "56",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Reijnders 1",
    "Player_14": "Van de",
    "Player_7": "Semenyo 4",
    "Player_2": "J.Timber 6",
    "Player_5": "Gu\u00E9hi 4",
    "Player_6": "Caicedo 1",
    "Player_3": "Senesi 2",
    "Player_4": "Gudmundsson 1",
    "Player_8": "M.Salah 2",
    "Player_9": "Kudus 2",
    "Player_15": "Foster 0"
  },
  {
    "manager_Name": "467( 2,000,317 )",
    "Teams": "Gozo Gunners( Jonathan Portelli )",
    "SXL": "MLT",
    "Latp": "63",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Isidor 2",
    "Player_14": "Stach 2",
    "Player_7": "Caicedo 1",
    "Player_2": "Tarkowski 3",
    "Player_5": "Van de",
    "Player_6": "M.Salah 2",
    "Player_3": "Senesi 2",
    "Player_4": "Burn 2",
    "Player_8": "Semenyo 4",
    "Player_9": "Reijnders 1",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "466( 2,067,798 )",
    "Teams": "RZM765( Cedrik Dalli )",
    "SXL": "MLT",
    "Latp": "83",
    "Player_1": "D\u00FAbravka 9",
    "Player_11": "Haaland 26",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Verbruggen 2",
    "Player_13": "Est\u00E8ve 8",
    "Player_14": "Rodon 1",
    "Player_7": "Reijnders 1",
    "Player_2": "Van de",
    "Player_5": "Anderson 4",
    "Player_6": "Foden 3",
    "Player_3": "Cucurella 8",
    "Player_4": "Mu\u00F1oz 10",
    "Player_8": "Rice 3",
    "Player_9": "Mateta 17",
    "Player_15": "Grealish 0"
  },
  {
    "manager_Name": "451( 2,937,312 )",
    "Teams": "Gunz( Kurt Zammit )",
    "SXL": "MLT",
    "Latp": "68",
    "Player_1": "Donnarumma 6",
    "Player_11": "Haaland 26",
    "Player_10": "Isidor 2",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Cash 2",
    "Player_14": "Anthony 2",
    "Player_7": "Saka 7",
    "Player_2": "Est\u00E8ve 8",
    "Player_5": "Senesi 2",
    "Player_6": "Reijnders 1",
    "Player_3": "Virgil 3",
    "Player_4": "Gu\u00E9hi 4",
    "Player_8": "Xhaka 5",
    "Player_9": "Semenyo 4",
    "Player_15": "Jo\u00E3o Pedro"
  },
  {
    "manager_Name": "446( 3,213,793 )",
    "Teams": "Select Team Name( Kurt Bonnici )",
    "SXL": "MLT",
    "Latp": "58",
    "Player_1": "Donnarumma 6",
    "Player_11": "Woltemade 8",
    "Player_10": "Gy\u00F6keres 4",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Anderson 4",
    "Player_14": "Tarkowski 3",
    "Player_7": "Semenyo 4",
    "Player_2": "Van de",
    "Player_5": "Gudmundsson 1",
    "Player_6": "Reijnders 1",
    "Player_3": "Senesi 2",
    "Player_4": "Gabriel 12",
    "Player_8": "Saka 7",
    "Player_9": "Haaland 13",
    "Player_15": "Grealish 0"
  },
  {
    "manager_Name": "446( 3,237,821 )",
    "Teams": "Let him cook( Henry Adjei )",
    "SXL": "MLT",
    "Latp": "59",
    "Player_1": "Henderson 1",
    "Player_11": "Haaland 26",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Kelleher 6",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Est\u00E8ve 8",
    "Player_7": "Ndiaye 4",
    "Player_2": "Virgil 3",
    "Player_5": "Gu\u00E9hi 4",
    "Player_6": "Semenyo 4",
    "Player_3": "Gabriel 12",
    "Player_4": "Van de",
    "Player_8": "Reijnders 1",
    "Player_9": "Kudus 2",
    "Player_15": "Anthony 2"
  },
  {
    "manager_Name": "439( 3,647,565 )",
    "Teams": "Sammygooner****( Sammy Vella )",
    "SXL": "MLT",
    "Latp": "64",
    "Player_1": "D\u00FAbravka 9",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Haaland 26",
    "Player_12": "S\u00E1nchez 5",
    "Player_13": "Beto 2",
    "Player_14": "Konsa 2",
    "Player_7": "Cunha 2",
    "Player_2": "Virgil 3",
    "Player_5": "Eze 3",
    "Player_6": "Kudus 2",
    "Player_3": "Van de",
    "Player_4": "Gabriel 12",
    "Player_8": "Semenyo 4",
    "Player_9": "Reijnders 1",
    "Player_15": "A\u00EFt-Nouri 0"
  },
  {
    "manager_Name": "438( 3,738,085 )",
    "Teams": "Sultan Army( Julian Sultana )",
    "SXL": "MLT",
    "Latp": "49",
    "Player_1": "Donnarumma 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Richarlison 1",
    "Player_12": "Pickford 2",
    "Player_13": "Cucurella 8",
    "Player_14": "Gibbs-White 2",
    "Player_7": "Xavi 2",
    "Player_2": "Saliba 6",
    "Player_5": "Gabriel 12",
    "Player_6": "Semenyo 8",
    "Player_3": "Virgil 3",
    "Player_4": "Calafiori 6",
    "Player_8": "Doku 1",
    "Player_9": "Kudus 2",
    "Player_15": "Ekitik\u00E9 1"
  },
  {
    "manager_Name": "426( 4,456,481 )",
    "Teams": "Zubi-Dooby Doo( Malcolm Vella Vidal )",
    "SXL": "MLT",
    "Latp": "55",
    "Player_1": "Mamardashvili 1",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Bowen 2",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Reijnders 1",
    "Player_14": "Mukiele 17",
    "Player_7": "Eze 3",
    "Player_2": "Diouf 1",
    "Player_5": "Saka 7",
    "Player_6": "Sarr 2",
    "Player_3": "J.Timber 6",
    "Player_4": "Botman 1",
    "Player_8": "Semenyo 4",
    "Player_9": "Haaland 26",
    "Player_15": "S.Bueno 1"
  },
  {
    "manager_Name": "424( 4,599,652 )",
    "Teams": "Dial Square( Liam Carabott )",
    "SXL": "MLT",
    "Latp": "73",
    "Player_1": "D\u00FAbravka 9",
    "Player_11": "Watkins 1",
    "Player_10": "Haaland 26",
    "Player_12": "Sels 2",
    "Player_13": "Enzo 0",
    "Player_14": "Virgil 3",
    "Player_7": "Zubimendi 3",
    "Player_2": "Gabriel 12",
    "Player_5": "Anthony 2",
    "Player_6": "Semenyo 4",
    "Player_3": "Mu\u00F1oz 10",
    "Player_4": "Van de",
    "Player_8": "Iwobi 4",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Wan-Bissaka 1"
  },
  {
    "manager_Name": "423( 4,652,217 )",
    "Teams": "Kanokk 118( Rodney Azzopardi )",
    "SXL": "MLT",
    "Latp": "54",
    "Player_1": "Donnarumma 6",
    "Player_11": "Ekitik\u00E9 1",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Henderson 1",
    "Player_13": "Evanilson 0",
    "Player_14": "Enzo 0",
    "Player_7": "Reijnders 1",
    "Player_2": "Cucurella 8",
    "Player_5": "Senesi 2",
    "Player_6": "Semenyo 4",
    "Player_3": "Gabriel 12",
    "Player_4": "Frimpong 1",
    "Player_8": "Saka 14",
    "Player_9": "Rice 3",
    "Player_15": "Milenkovi\u0107 1"
  },
  {
    "manager_Name": "421( 4,763,553 )",
    "Teams": "Mandra United( Steven Silvio )",
    "SXL": "MLT",
    "Latp": "60",
    "Player_1": "Raya 6",
    "Player_11": "Bowen 2",
    "Player_10": "Watkins 1",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Enzo 0",
    "Player_14": "Mitchell 1",
    "Player_7": "Gravenberch 2",
    "Player_2": "J.Timber 6",
    "Player_5": "Virgil 3",
    "Player_6": "Semenyo 4",
    "Player_3": "Senesi 2",
    "Player_4": "Saliba 6",
    "Player_8": "Sarr 2",
    "Player_9": "Haaland 26",
    "Player_15": "Kamara 2"
  },
  {
    "manager_Name": "421( 4,770,359 )",
    "Teams": "Rice Rice Baby( Ian Falzon )",
    "SXL": "MLT",
    "Latp": "47",
    "Player_1": "Donnarumma 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Isak 4",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Anthony 2",
    "Player_14": "Senesi 2",
    "Player_7": "Reijnders 1",
    "Player_2": "Van de",
    "Player_5": "Semenyo 4",
    "Player_6": "Mbeumo 9",
    "Player_3": "Virgil 3",
    "Player_4": "Richards 3",
    "Player_8": "Kudus 2",
    "Player_9": "Haaland 13",
    "Player_15": "Est\u00E8ve 8"
  },
  {
    "manager_Name": "420( 4,849,849 )",
    "Teams": "Lassie fc( Kirsten Tanti )",
    "SXL": "MLT",
    "Latp": "71",
    "Player_1": "Raya 6",
    "Player_11": "Isidor 2",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Senesi 2",
    "Player_14": "Xhaka 5",
    "Player_7": "Reijnders 1",
    "Player_2": "Pedro Porro",
    "Player_5": "Saka 7",
    "Player_6": "Semenyo 4",
    "Player_3": "Gabriel 12",
    "Player_4": "Cucurella 8",
    "Player_8": "Kudus 2",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "413( 5,285,393 )",
    "Teams": "Henry\u2019s Heroes( Jean Azzopardi )",
    "SXL": "MLT",
    "Latp": "58",
    "Player_1": "Vicario 1",
    "Player_11": "Haaland 26",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Gu\u00E9hi 4",
    "Player_14": "Rice 3",
    "Player_7": "Semenyo 4",
    "Player_2": "Alderete 6",
    "Player_5": "Eze 3",
    "Player_6": "Gravenberch 2",
    "Player_3": "Cucurella 8",
    "Player_4": "Virgil 3",
    "Player_8": "Reijnders 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Senesi 2"
  },
  {
    "manager_Name": "407( 5,664,341 )",
    "Teams": "SC CARBINE( yan cutajar )",
    "SXL": "MLT",
    "Latp": "42",
    "Player_1": "Raya 6",
    "Player_11": "\u0160e\u0161ko 1",
    "Player_10": "Haaland 13",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Romero 0",
    "Player_14": "Wan-Bissaka 1",
    "Player_7": "Caicedo 1",
    "Player_2": "Konsa 2",
    "Player_5": "Baleba 3",
    "Player_6": "Semenyo 8",
    "Player_3": "Gu\u00E9hi 4",
    "Player_4": "Van de",
    "Player_8": "Kudus 2",
    "Player_9": "Gy\u00F6keres 2",
    "Player_15": "Grealish 0"
  },
  {
    "manager_Name": "406( 5,725,764 )",
    "Teams": "Eze Come Eze Go( Theo Magro )",
    "SXL": "MLT",
    "Latp": "55",
    "Player_1": "Henderson 1",
    "Player_11": "Mateta 17",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Petrovi\u0107 2",
    "Player_13": "Xhaka 5",
    "Player_14": "Trippier 1",
    "Player_7": "Anthony 2",
    "Player_2": "Van de",
    "Player_5": "Semenyo 4",
    "Player_6": "M.Salah 4",
    "Player_3": "Mu\u00F1oz 10",
    "Player_4": "Gabriel 12",
    "Player_8": "Caicedo 1",
    "Player_9": "Gy\u00F6keres 2",
    "Player_15": "Kerkez 1"
  },
  {
    "manager_Name": "403( 5,886,212 )",
    "Teams": "Gy\u00F6keres14( Zack Vella )",
    "SXL": "MLT",
    "Latp": "57",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "Heaton 0",
    "Player_13": "Gudmundsson 1",
    "Player_14": "Reinildo 0",
    "Player_7": "King 2",
    "Player_2": "Est\u00E8ve 8",
    "Player_5": "Eze 3",
    "Player_6": "M.Salah 2",
    "Player_3": "Cash 2",
    "Player_4": "Virgil 3",
    "Player_8": "Reijnders 1",
    "Player_9": "Gy\u00F6keres 2",
    "Player_15": "Matete 0"
  },
  {
    "manager_Name": "402( 5,962,326 )",
    "Teams": "Lions( Daniel Ferriggi )",
    "SXL": "MLT",
    "Latp": "34",
    "Player_1": "Kelleher 6",
    "Player_11": "Bowen 2",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Pickford 2",
    "Player_13": "Virgil 3",
    "Player_14": "P.M.Sarr 1",
    "Player_7": "Caicedo 1",
    "Player_2": "Senesi 2",
    "Player_5": "M.Salah 4",
    "Player_6": "Kudus 2",
    "Player_3": "Burn 2",
    "Player_4": "Mu\u00F1oz 10",
    "Player_8": "Reijnders 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Milenkovi\u0107 1"
  },
  {
    "manager_Name": "389( 6,733,168 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "65",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Xhaka 5",
    "Player_14": "L.Miley 4",
    "Player_7": "Reijnders 1",
    "Player_2": "Gabriel 12",
    "Player_5": "Gudmundsson 1",
    "Player_6": "L.Paquet\u00E1 2",
    "Player_3": "Virgil 3",
    "Player_4": "Senesi 2",
    "Player_8": "M.Salah 2",
    "Player_9": "Thiago 8",
    "Player_15": "Andersen 1"
  },
  {
    "manager_Name": "388( 6,774,001 )",
    "Teams": "NLD( Jordi Farrugia )",
    "SXL": "MLT",
    "Latp": "63",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "\u0160e\u0161ko 1",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Romero 0",
    "Player_14": "Saka 7",
    "Player_7": "Eze 3",
    "Player_2": "Cucurella 8",
    "Player_5": "James 18",
    "Player_6": "Elanga 2",
    "Player_3": "Gabriel 12",
    "Player_4": "Burn 2",
    "Player_8": "Gibbs-White 2",
    "Player_9": "Rogers 7",
    "Player_15": "Evanilson 0"
  },
  {
    "manager_Name": "387( 6,836,652 )",
    "Teams": "Zubi dubi doo( Julia Schembri )",
    "SXL": "MLT",
    "Latp": "36",
    "Player_1": "Kelleher 6",
    "Player_11": "Beto 2",
    "Player_10": "Gy\u00F6keres 4",
    "Player_12": "Verbruggen 2",
    "Player_13": "Wan-Bissaka 1",
    "Player_14": "Dewsbury-Hall 2",
    "Player_7": "Semenyo 4",
    "Player_2": "Konsa 2",
    "Player_5": "Eze 3",
    "Player_6": "M.Salah 2",
    "Player_3": "Saliba 6",
    "Player_4": "Gu\u00E9hi 4",
    "Player_8": "Elanga 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "381( 7,194,340 )",
    "Teams": "Mihawha( Matthew Paris )",
    "SXL": "MLT",
    "Latp": "42",
    "Player_1": "Donnarumma 6",
    "Player_11": "Gy\u00F6keres 4",
    "Player_10": "Watkins 1",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Milenkovi\u0107 1",
    "Player_14": "De Cuyper",
    "Player_7": "M.Salah 2",
    "Player_2": "Van de",
    "Player_5": "Semenyo 4",
    "Player_6": "Reijnders 1",
    "Player_3": "Pedro Porro",
    "Player_4": "Senesi 2",
    "Player_8": "Anderson 4",
    "Player_9": "Mateta 17",
    "Player_15": "Ndiaye 4"
  },
  {
    "manager_Name": "363( 8,145,605 )",
    "Teams": "Harambe FC( Glenn Gauci Borda )",
    "SXL": "MLT",
    "Latp": "30",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "Bowen 2",
    "Player_10": "Wood 2",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Reinildo 0",
    "Player_14": "Est\u00E8ve 8",
    "Player_7": "Reijnders 1",
    "Player_2": "Van de",
    "Player_5": "Semenyo 4",
    "Player_6": "M.Salah 2",
    "Player_3": "Konsa 2",
    "Player_4": "Wan-Bissaka 1",
    "Player_8": "Mbeumo 9",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "355( 8,541,053 )",
    "Teams": "InvinciblesCOYG( Clayton Camilleri )",
    "SXL": "MLT",
    "Latp": "45",
    "Player_1": "Raya 6",
    "Player_11": "Wilson 0",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Kelleher 6",
    "Player_13": "Grealish 0",
    "Player_14": "A\u00EFt-Nouri 0",
    "Player_7": "Dewsbury-Hall 2",
    "Player_2": "Cucurella 8",
    "Player_5": "Saka 7",
    "Player_6": "M.Salah 2",
    "Player_3": "Kerkez 1",
    "Player_4": "Est\u00E8ve 8",
    "Player_8": "Xhaka 5",
    "Player_9": "Gy\u00F6keres 4",
    "Player_15": "Reinildo 0"
  },
  {
    "manager_Name": "353( 8,627,628 )",
    "Teams": "Gorsil Gunners( Gordon Silvio )",
    "SXL": "MLT",
    "Latp": "52",
    "Player_1": "Raya 12",
    "Player_11": "\u0160e\u0161ko 1",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Sels 2",
    "Player_13": "Palmer 0",
    "Player_14": "Konsa 2",
    "Player_7": "Saka 7",
    "Player_2": "James 18",
    "Player_5": "Wan-Bissaka 1",
    "Player_6": "Eze 3",
    "Player_3": "Gu\u00E9hi 4",
    "Player_4": "Van de",
    "Player_8": "Kluivert 2",
    "Player_9": "Beto 2",
    "Player_15": "Marmoush 0"
  },
  {
    "manager_Name": "353( 8,643,618 )",
    "Teams": "Jack Nigret( Jack Gatt )",
    "SXL": "MLT",
    "Latp": "38",
    "Player_1": "Donnarumma 6",
    "Player_11": "\u0160e\u0161ko 1",
    "Player_10": "Gy\u00F6keres 4",
    "Player_12": "Verbruggen 2",
    "Player_13": "Palmer 0",
    "Player_14": "Adams 3",
    "Player_7": "Doku 1",
    "Player_2": "Gabriel 12",
    "Player_5": "Van de",
    "Player_6": "Reijnders 1",
    "Player_3": "Frimpong 1",
    "Player_4": "Konat\u00E9 3",
    "Player_8": "Rogers 7",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Mu\u00F1oz 10"
  },
  {
    "manager_Name": "352( 8,670,656 )",
    "Teams": "Boca Seniors FC( Jake Bonnici )",
    "SXL": "MLT",
    "Latp": "29",
    "Player_1": "Vicario 1",
    "Player_11": "Beto 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Ramsdale 0",
    "Player_13": "Cherki 1",
    "Player_14": "Lewis-Skelly 0",
    "Player_7": "Saka 7",
    "Player_2": "Kerkez 1",
    "Player_5": "M.Salah 2",
    "Player_6": "Rogers 7",
    "Player_3": "Bassey 1",
    "Player_4": "Spence 1",
    "Player_8": "Wharton 2",
    "Player_9": "Ekitik\u00E9 1",
    "Player_15": "Aina 0"
  }
];