var s = [
  {
    "manager_Name": "538( 19,171 )",
    "Teams": "cavac215( Ankit Chhetri )",
    "SXL": "IND",
    "Latp": "66",
    "Player_1": "D\u00FAbravka 7",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 20",
    "Player_12": "Pope 2",
    "Player_13": "Chalobah 6",
    "Player_14": "Mbeumo LIV",
    "Player_7": "Reijnders 1",
    "Player_2": "Burn 2",
    "Player_5": "Kudus AVL",
    "Player_6": "Saka 5",
    "Player_3": "Van de",
    "Player_4": "Gabriel 9",
    "Player_8": "Semenyo 4",
    "Player_9": "Richarlison AVL",
    "Player_15": "Est\u00E8ve 8"
  },
  {
    "manager_Name": "539( 17,587 )",
    "Teams": "False 9( Rohan Rai )",
    "SXL": "IND",
    "Latp": "75",
    "Player_1": "Pope 2",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Doku 1",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Saka 5",
    "Player_2": "Gu\u00E9hi 4",
    "Player_5": "Kudus AVL",
    "Player_6": "Anthony 2",
    "Player_3": "Senesi 2",
    "Player_4": "Gabriel 9",
    "Player_8": "Semenyo 4",
    "Player_9": "Haaland 20",
    "Player_15": "Mukiele 14"
  },
  {
    "manager_Name": "496( 339,144 )",
    "Teams": "Kung fu Pandoos( Indrajeet Singh )",
    "SXL": "IND",
    "Latp": "40",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "\u0160e\u0161ko LIV",
    "Player_10": "Haaland 20",
    "Player_12": "Kelleher WHU",
    "Player_13": "De Ligt",
    "Player_14": "Grealish 0",
    "Player_7": "Semenyo 4",
    "Player_2": "Virgil MUN",
    "Player_5": "Walker 11",
    "Player_6": "Kudus AVL",
    "Player_3": "Pedro Porro",
    "Player_4": "Gvardiol 0",
    "Player_8": "Mbeumo LIV",
    "Player_9": "Bowen BRE",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "481( 693,890 )",
    "Teams": "Blue Brigade( Bhuman Basnet )",
    "SXL": "IND",
    "Latp": "37",
    "Player_1": "Vicario AVL",
    "Player_11": "Haaland 20",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Gudmundsson 1",
    "Player_14": "Tuanzebe 8",
    "Player_7": "M.Salah MUN",
    "Player_2": "Senesi 2",
    "Player_5": "Semenyo 4",
    "Player_6": "Kudus AVL",
    "Player_3": "Calafiori 6",
    "Player_4": "Van de",
    "Player_8": "Reijnders 1",
    "Player_9": "Sarr 2",
    "Player_15": "Barnes 1"
  },
  {
    "manager_Name": "486( 558,453 )",
    "Teams": "PWS( Z S )",
    "SXL": "IND",
    "Latp": "44",
    "Player_1": "Donnarumma 6",
    "Player_11": "Haaland 20",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "J.Timber 6",
    "Player_14": "Anderson 4",
    "Player_7": "Gakpo MUN",
    "Player_2": "Senesi 2",
    "Player_5": "Semenyo 4",
    "Player_6": "Reijnders 1",
    "Player_3": "Gabriel 9",
    "Player_4": "Van de",
    "Player_8": "Grealish 0",
    "Player_9": "Isak MUN",
    "Player_15": "Dorgu LIV"
  },
  {
    "manager_Name": "498( 300,457 )",
    "Teams": "error404( Duri Tadu )",
    "SXL": "IND",
    "Latp": "57",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 20",
    "Player_10": "Woltemade 6",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Stach 2",
    "Player_14": "Rodon 1",
    "Player_7": "Semenyo 4",
    "Player_2": "Gvardiol 0",
    "Player_5": "Reijnders 1",
    "Player_6": "Saka 5",
    "Player_3": "Gabriel 9",
    "Player_4": "Virgil MUN",
    "Player_8": "Ndiaye 4",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Andersen 1"
  },
  {
    "manager_Name": "467( 1,204,675 )",
    "Teams": "abcde FC( Prayash Thapa )",
    "SXL": "IND",
    "Latp": "44",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 20",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "N.Williams 1",
    "Player_14": "Est\u00E8ve 8",
    "Player_7": "Semenyo 4",
    "Player_2": "Van de",
    "Player_5": "Reijnders 1",
    "Player_6": "B.Fernandes LIV",
    "Player_3": "Richards 3",
    "Player_4": "Gabriel 9",
    "Player_8": "Wirtz MUN",
    "Player_9": "Bowen BRE",
    "Player_15": "Dewsbury-Hall 2"
  },
  {
    "manager_Name": "475( 899,191 )",
    "Teams": "Alpha11( AVIJIT DAS )",
    "SXL": "IND",
    "Latp": "52",
    "Player_1": "Vicario AVL",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Gudmundsson 1",
    "Player_14": "King 2",
    "Player_7": "Semenyo 4",
    "Player_2": "Senesi 2",
    "Player_5": "Chalobah 6",
    "Player_6": "Reijnders 1",
    "Player_3": "Gabriel 9",
    "Player_4": "Lacroix 1",
    "Player_8": "Saka 5",
    "Player_9": "Haaland 20",
    "Player_15": "Grealish 0"
  },
  {
    "manager_Name": "459( 1,574,539 )",
    "Teams": "ASHLAD FC( Ashim Lama )",
    "SXL": "IND",
    "Latp": "39",
    "Player_1": "D\u00FAbravka 7",
    "Player_11": "Haaland 20",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Roefs 7",
    "Player_13": "Est\u00E8ve 8",
    "Player_14": "Marc Guiu",
    "Player_7": "Ndiaye 4",
    "Player_2": "Senesi 2",
    "Player_5": "M.Salah MUN",
    "Player_6": "Gakpo MUN",
    "Player_3": "Virgil MUN",
    "Player_4": "Van de",
    "Player_8": "Semenyo 4",
    "Player_9": "P.M.Sarr AVL",
    "Player_15": "Dorgu LIV"
  },
  {
    "manager_Name": "477( 836,277 )",
    "Teams": "\u0160e\u0161ko and Destroy( Pema Lepcha )",
    "SXL": "IND",
    "Latp": "58",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 20",
    "Player_10": "Woltemade 6",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Gakpo MUN",
    "Player_14": "Grealish 0",
    "Player_7": "Semenyo 4",
    "Player_2": "Senesi 2",
    "Player_5": "Calafiori 6",
    "Player_6": "Zubimendi 3",
    "Player_3": "Mu\u00F1oz 9",
    "Player_4": "Pedro Porro",
    "Player_8": "Mbeumo LIV",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "470( 1,088,266 )",
    "Teams": "Top Gooner( VibhutiHang Subba )",
    "SXL": "IND",
    "Latp": "57",
    "Player_1": "Raya 6",
    "Player_11": "Bowen BRE",
    "Player_10": "Haaland 20",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Reijnders 1",
    "Player_14": "Pedro Porro",
    "Player_7": "Semenyo 4",
    "Player_2": "Mukiele 14",
    "Player_5": "Kudus AVL",
    "Player_6": "Eze 3",
    "Player_3": "Senesi 2",
    "Player_4": "Rodon 1",
    "Player_8": "Saka 5",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Lacroix 1"
  },
  {
    "manager_Name": "468( 1,169,207 )",
    "Teams": "MANCHESTER IS BLUE( PRAYAS BAJGAI )",
    "SXL": "IND",
    "Latp": "53",
    "Player_1": "Pope 2",
    "Player_11": "Haaland 20",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Andersen 1",
    "Player_14": "Senesi 2",
    "Player_7": "Gordon 2",
    "Player_2": "Rodon 1",
    "Player_5": "Saka 5",
    "Player_6": "Enzo 0",
    "Player_3": "Gabriel 9",
    "Player_4": "J.Timber 6",
    "Player_8": "Semenyo 4",
    "Player_9": "Sarr 2",
    "Player_15": "Calvert-Lewin 2"
  },
  {
    "manager_Name": "472( 1,026,053 )",
    "Teams": "11 n over( Ashish Rai )",
    "SXL": "IND",
    "Latp": "58",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 20",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "O.Dango WHU",
    "Player_14": "Rodon 1",
    "Player_7": "Gakpo MUN",
    "Player_2": "Diouf BRE",
    "Player_5": "Kudus AVL",
    "Player_6": "Minteh 2",
    "Player_3": "Mu\u00F1oz 9",
    "Player_4": "J.Timber 6",
    "Player_8": "Saka 5",
    "Player_9": "Richarlison AVL",
    "Player_15": "Gvardiol 0"
  },
  {
    "manager_Name": "449( 2,101,411 )",
    "Teams": "Cheesygarlic( Rishi Thulung )",
    "SXL": "IND",
    "Latp": "36",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 20",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Xhaka 5",
    "Player_14": "N.Williams 1",
    "Player_7": "M.Salah MUN",
    "Player_2": "Dorgu LIV",
    "Player_5": "Van de",
    "Player_6": "Semenyo 4",
    "Player_3": "Virgil MUN",
    "Player_4": "Tarkowski 3",
    "Player_8": "Caicedo 1",
    "Player_9": "Reijnders 1",
    "Player_15": "Kroupi.Jr 10"
  },
  {
    "manager_Name": "494( 387,993 )",
    "Teams": "RIP-DIOGO.20( pranam rai )",
    "SXL": "IND",
    "Latp": "81",
    "Player_1": "D\u00FAbravka 7",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 20",
    "Player_12": "Vicario AVL",
    "Player_13": "Est\u00E8ve 8",
    "Player_14": "Malen TOT",
    "Player_7": "Gakpo MUN",
    "Player_2": "Cucurella 8",
    "Player_5": "Kudus AVL",
    "Player_6": "Semenyo 4",
    "Player_3": "Gabriel 9",
    "Player_4": "J.Timber 6",
    "Player_8": "Minteh 2",
    "Player_9": "Woltemade 6",
    "Player_15": "Mu\u00F1oz 9"
  },
  {
    "manager_Name": "461( 1,502,216 )",
    "Teams": "Comet FC( Pranesh Sharma )",
    "SXL": "IND",
    "Latp": "52",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "Haaland 20",
    "Player_10": "Woltemade 6",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Andersen 1",
    "Player_7": "Kudus AVL",
    "Player_2": "Pedro Porro",
    "Player_5": "Saka 5",
    "Player_6": "Semenyo 4",
    "Player_3": "Est\u00E8ve 8",
    "Player_4": "Senesi 2",
    "Player_8": "Mbeumo LIV",
    "Player_9": "Anthony 2",
    "Player_15": "Cash TOT"
  },
  {
    "manager_Name": "452( 1,916,506 )",
    "Teams": "Lu Lu( Nishant Lohagun )",
    "SXL": "IND",
    "Latp": "47",
    "Player_1": "Raya 6",
    "Player_11": "Richarlison AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Doku 1",
    "Player_14": "Ndiaye 4",
    "Player_7": "Semenyo 4",
    "Player_2": "Senesi 2",
    "Player_5": "Richards 3",
    "Player_6": "B.Fernandes LIV",
    "Player_3": "Gabriel 9",
    "Player_4": "Virgil MUN",
    "Player_8": "Reijnders 1",
    "Player_9": "Haaland 20",
    "Player_15": "Andersen 1"
  },
  {
    "manager_Name": "460( 1,512,666 )",
    "Teams": "PINE( SATYAM RAI )",
    "SXL": "IND",
    "Latp": "65",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 20",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Stach 2",
    "Player_14": "Van de",
    "Player_7": "Saka 5",
    "Player_2": "Gabriel 9",
    "Player_5": "Mukiele 14",
    "Player_6": "Semenyo 4",
    "Player_3": "Senesi 2",
    "Player_4": "Burn 2",
    "Player_8": "Reijnders 1",
    "Player_9": "Richarlison AVL",
    "Player_15": "Ndiaye 4"
  },
  {
    "manager_Name": "432( 3,073,207 )",
    "Teams": "F.C. ASSASSINS( Kushal Sahota )",
    "SXL": "IND",
    "Latp": "42",
    "Player_1": "D\u00FAbravka 7",
    "Player_11": "Haaland 20",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Sels 2",
    "Player_13": "Est\u00E8ve 8",
    "Player_14": "Van de",
    "Player_7": "M.Salah MUN",
    "Player_2": "Gu\u00E9hi 4",
    "Player_5": "Sarr 2",
    "Player_6": "Caicedo 1",
    "Player_3": "Virgil MUN",
    "Player_4": "Senesi 2",
    "Player_8": "Semenyo 4",
    "Player_9": "Richarlison AVL",
    "Player_15": "King 2"
  },
  {
    "manager_Name": "427( 3,388,023 )",
    "Teams": "Liverpool FC( Sunil Rai )",
    "SXL": "IND",
    "Latp": "40",
    "Player_1": "Pope 2",
    "Player_11": "Richarlison AVL",
    "Player_10": "Haaland 20",
    "Player_12": "S\u00E1nchez 5",
    "Player_13": "Tavernier 5",
    "Player_14": "Grealish 0",
    "Player_7": "Semenyo 4",
    "Player_2": "Pedro Porro",
    "Player_5": "Mu\u00F1oz 9",
    "Player_6": "Reijnders 1",
    "Player_3": "Virgil MUN",
    "Player_4": "Gvardiol 0",
    "Player_8": "Anthony 2",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "427( 3,364,362 )",
    "Teams": "GustavousGooner( Ashish Subba )",
    "SXL": "IND",
    "Latp": "43",
    "Player_1": "D\u00FAbravka 7",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Haaland 20",
    "Player_12": "S\u00E1nchez 5",
    "Player_13": "Enzo 0",
    "Player_14": "Mbeumo LIV",
    "Player_7": "Szoboszlai MUN",
    "Player_2": "Senesi 2",
    "Player_5": "Pedro Porro",
    "Player_6": "Semenyo 4",
    "Player_3": "Gudmundsson 1",
    "Player_4": "Gu\u00E9hi 4",
    "Player_8": "Reijnders 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Livramento 0"
  },
  {
    "manager_Name": "430( 3,179,065 )",
    "Teams": "Fu\u00DFball-Mannschaft( Gaurav Shrestha )",
    "SXL": "IND",
    "Latp": "51",
    "Player_1": "Donnarumma 6",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Stach 2",
    "Player_14": "Andersen 1",
    "Player_7": "Ndiaye 4",
    "Player_2": "Gabriel 9",
    "Player_5": "B.Fernandes LIV",
    "Player_6": "Semenyo 4",
    "Player_3": "Senesi 2",
    "Player_4": "Rodon 1",
    "Player_8": "Reijnders 1",
    "Player_9": "Haaland 20",
    "Player_15": "Tarkowski 3"
  },
  {
    "manager_Name": "429( 3,255,088 )",
    "Teams": "Native United( Monlom Rongong )",
    "SXL": "IND",
    "Latp": "54",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 20",
    "Player_10": "Bowen BRE",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Reijnders 1",
    "Player_14": "Gu\u00E9hi 4",
    "Player_7": "Kudus AVL",
    "Player_2": "Senesi 2",
    "Player_5": "Rodon 1",
    "Player_6": "Semenyo 4",
    "Player_3": "Gabriel 9",
    "Player_4": "J.Timber 6",
    "Player_8": "Gravenberch MUN",
    "Player_9": "Woltemade 6",
    "Player_15": "Ndiaye 4"
  },
  {
    "manager_Name": "426( 3,448,670 )",
    "Teams": "The Regista.( Passang T Sherpa )",
    "SXL": "IND",
    "Latp": "52",
    "Player_1": "Vicario AVL",
    "Player_11": "Woltemade 6",
    "Player_10": "Haaland 20",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Est\u00E8ve 8",
    "Player_7": "Reijnders 1",
    "Player_2": "Cucurella 8",
    "Player_5": "Gu\u00E9hi 4",
    "Player_6": "Enzo 0",
    "Player_3": "Calafiori 6",
    "Player_4": "Van de",
    "Player_8": "Eze 3",
    "Player_9": "Semenyo 4",
    "Player_15": "Grealish 0"
  },
  {
    "manager_Name": "429( 3,266,513 )",
    "Teams": "G\u00CBNJ\u00CF\u00CF UNITED( Pema Bhutia )",
    "SXL": "IND",
    "Latp": "56",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 20",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Alderete 6",
    "Player_14": "Anthony 2",
    "Player_7": "Semenyo 4",
    "Player_2": "Van de",
    "Player_5": "Chalobah 6",
    "Player_6": "Reijnders 1",
    "Player_3": "Senesi 2",
    "Player_4": "Gabriel 9",
    "Player_8": "B.Fernandes LIV",
    "Player_9": "Woltemade 6",
    "Player_15": "Stach 2"
  },
  {
    "manager_Name": "426( 3,437,564 )",
    "Teams": "Bruno-nly Fans( Bejoy M Shrestha\u00B2\u2076\u2074 )",
    "SXL": "IND",
    "Latp": "57",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 6",
    "Player_10": "Haaland 20",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "King 2",
    "Player_14": "Van de",
    "Player_7": "Reijnders 1",
    "Player_2": "Burn 2",
    "Player_5": "Saka 5",
    "Player_6": "Semenyo 4",
    "Player_3": "Gabriel 9",
    "Player_4": "Senesi 2",
    "Player_8": "B.Fernandes LIV",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "397( 5,226,564 )",
    "Teams": "I_am_done_XI( Dipen Thapa )",
    "SXL": "IND",
    "Latp": "32",
    "Player_1": "Raya 6",
    "Player_11": "Wood 1",
    "Player_10": "Gy\u00F6keres 4",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Grealish 0",
    "Player_14": "Senesi 2",
    "Player_7": "M.Salah MUN",
    "Player_2": "Est\u00E8ve 8",
    "Player_5": "Semenyo 4",
    "Player_6": "Eze 3",
    "Player_3": "Gu\u00E9hi 4",
    "Player_4": "Pedro Porro",
    "Player_8": "Kudus AVL",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Konsa TOT"
  },
  {
    "manager_Name": "402( 4,912,383 )",
    "Teams": "Imperial Blues( Saurabh Tamang )",
    "SXL": "IND",
    "Latp": "38",
    "Player_1": "Vicario AVL",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 20",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Foster 0",
    "Player_14": "Caicedo 1",
    "Player_7": "M.Salah MUN",
    "Player_2": "Virgil MUN",
    "Player_5": "Richards 3",
    "Player_6": "Semenyo 4",
    "Player_3": "Senesi 2",
    "Player_4": "Romero AVL",
    "Player_8": "Ndiaye 4",
    "Player_9": "Zubimendi 3",
    "Player_15": "Est\u00E8ve 8"
  },
  {
    "manager_Name": "406( 4,700,895 )",
    "Teams": "Busby Baby( Regean Lama )",
    "SXL": "IND",
    "Latp": "47",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "Woltemade 6",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Dorgu LIV",
    "Player_14": "Grealish 0",
    "Player_7": "Kudus AVL",
    "Player_2": "Van de",
    "Player_5": "Reijnders 1",
    "Player_6": "Semenyo 4",
    "Player_3": "Konsa TOT",
    "Player_4": "Mu\u00F1oz 9",
    "Player_8": "B.Fernandes LIV",
    "Player_9": "Haaland 20",
    "Player_15": "Alex Moreno"
  },
  {
    "manager_Name": "401( 4,978,504 )",
    "Teams": "Hooligans25( Pradhyumna Subba )",
    "SXL": "IND",
    "Latp": "51",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 20",
    "Player_10": "Woltemade 6",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Richards 3",
    "Player_14": "Marc Guiu",
    "Player_7": "Sarr 2",
    "Player_2": "Gabriel 9",
    "Player_5": "Buend\u00EDa TOT",
    "Player_6": "M.Salah MUN",
    "Player_3": "Van de",
    "Player_4": "J.Timber 6",
    "Player_8": "Reijnders 1",
    "Player_9": "Doku 1",
    "Player_15": "Reinildo 0"
  },
  {
    "manager_Name": "378( 6,390,800 )",
    "Teams": "GUNNERS( Omkar Subba )",
    "SXL": "IND",
    "Latp": "29",
    "Player_1": "Vicario AVL",
    "Player_11": "Haaland 10",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Verbruggen 2",
    "Player_13": "Zubimendi 3",
    "Player_14": "Van de",
    "Player_7": "Semenyo 8",
    "Player_2": "Senesi 2",
    "Player_5": "Caicedo 1",
    "Player_6": "Anthony 2",
    "Player_3": "Gu\u00E9hi 4",
    "Player_4": "Virgil MUN",
    "Player_8": "Gravenberch MUN",
    "Player_9": "Ekitik\u00E9 MUN",
    "Player_15": "Spence AVL"
  },
  {
    "manager_Name": "399( 5,119,078 )",
    "Teams": "GODFATHER FC( Riwaj Rai )",
    "SXL": "IND",
    "Latp": "50",
    "Player_1": "D\u00FAbravka 7",
    "Player_11": "Isidor 2",
    "Player_10": "Haaland 20",
    "Player_12": "Sels 2",
    "Player_13": "Cash TOT",
    "Player_14": "Grealish 0",
    "Player_7": "Reijnders 1",
    "Player_2": "Gu\u00E9hi 4",
    "Player_5": "Est\u00E8ve 8",
    "Player_6": "Kudus AVL",
    "Player_3": "Cucurella 8",
    "Player_4": "Pedro Porro",
    "Player_8": "O.Dango WHU",
    "Player_9": "M.Salah MUN",
    "Player_15": "F\u00FCllkrug BRE"
  },
  {
    "manager_Name": "387( 5,867,473 )",
    "Teams": "Hangkim_0011( ABHINANDAN RAI )",
    "SXL": "IND",
    "Latp": "43",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "Haaland 20",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Est\u00E8ve 8",
    "Player_14": "Ndiaye 4",
    "Player_7": "Gakpo MUN",
    "Player_2": "Pedro Porro",
    "Player_5": "Reijnders 1",
    "Player_6": "Rice 3",
    "Player_3": "Burn 2",
    "Player_4": "R\u00FAben 6",
    "Player_8": "Semenyo 4",
    "Player_9": "Ekitik\u00E9 MUN",
    "Player_15": "Konsa TOT"
  },
  {
    "manager_Name": "381( 6,221,402 )",
    "Teams": "Let MEE COOK( \u00CFaraplang Pompyrthat )",
    "SXL": "IND",
    "Latp": "37",
    "Player_1": "Pope 2",
    "Player_11": "Haaland 10",
    "Player_10": "Woltemade 6",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Est\u00E8ve 8",
    "Player_14": "Rodon 1",
    "Player_7": "Semenyo 4",
    "Player_2": "J.Timber 6",
    "Player_5": "Kudus AVL",
    "Player_6": "M.Salah MUN",
    "Player_3": "Senesi 2",
    "Player_4": "Burn 2",
    "Player_8": "Xhaka 5",
    "Player_9": "Enzo 0",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "383( 6,110,383 )",
    "Teams": "Jorebungalow YFC( Vivek Lama )",
    "SXL": "IND",
    "Latp": "40",
    "Player_1": "Verbruggen 2",
    "Player_11": "Richarlison AVL",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "De Cuyper",
    "Player_14": "Est\u00E8ve 8",
    "Player_7": "M.Salah MUN",
    "Player_2": "Calafiori 6",
    "Player_5": "Kudus AVL",
    "Player_6": "King 2",
    "Player_3": "Cucurella 8",
    "Player_4": "Van de",
    "Player_8": "Gakpo MUN",
    "Player_9": "Haaland 20",
    "Player_15": "L.Miley 4"
  },
  {
    "manager_Name": "365( 7,131,628 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "41",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 20",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Xhaka 5",
    "Player_14": "L.Miley 4",
    "Player_7": "Reijnders 1",
    "Player_2": "Gabriel 9",
    "Player_5": "Gudmundsson 1",
    "Player_6": "L.Paquet\u00E1 BRE",
    "Player_3": "Virgil MUN",
    "Player_4": "Senesi 2",
    "Player_8": "M.Salah MUN",
    "Player_9": "Thiago WHU",
    "Player_15": "Andersen 1"
  },
  {
    "manager_Name": "357( 7,590,689 )",
    "Teams": "Boehly Blues( Aditya Bhandari )",
    "SXL": "IND",
    "Latp": "54",
    "Player_1": "Petrovi\u0107 2",
    "Player_11": "Haaland 20",
    "Player_10": "Woltemade 6",
    "Player_12": "D\u00FAbravka 7",
    "Player_13": "Stach 2",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Saka 5",
    "Player_2": "Senesi 2",
    "Player_5": "Reijnders 1",
    "Player_6": "Anthony 2",
    "Player_3": "Gu\u00E9hi 4",
    "Player_4": "J.Timber 6",
    "Player_8": "Semenyo 4",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Est\u00E8ve 8"
  },
  {
    "manager_Name": "337( 8,561,089 )",
    "Teams": "Invincibles( Bishal Rai )",
    "SXL": "IND",
    "Latp": "32",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "Ekitik\u00E9 MUN",
    "Player_10": "Wood 1",
    "Player_12": "Kinsky AVL",
    "Player_13": "Wirtz MUN",
    "Player_14": "Neto 11",
    "Player_7": "Semenyo 8",
    "Player_2": "Mu\u00F1oz 9",
    "Player_5": "Milenkovi\u0107 1",
    "Player_6": "Enzo 0",
    "Player_3": "Saliba 6",
    "Player_4": "Pedro Porro",
    "Player_8": "Johnson AVL",
    "Player_9": "Gy\u00F6keres 2",
    "Player_15": "A\u00EFt-Nouri 0"
  }
];