var s = [
  {
    "manager_Name": "563( 8,915 )",
    "Teams": "cavac215( Ankit Chhetri )",
    "SXL": "IND",
    "Latp": "91",
    "Player_1": "D\u00FAbravka 9",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "Pope 2",
    "Player_13": "Chalobah 6",
    "Player_14": "Mbeumo 9",
    "Player_7": "Reijnders 1",
    "Player_2": "Burn 2",
    "Player_5": "Kudus 2",
    "Player_6": "Saka 7",
    "Player_3": "Van de",
    "Player_4": "Gabriel 12",
    "Player_8": "Semenyo 4",
    "Player_9": "Richarlison 1",
    "Player_15": "Est\u00E8ve 8"
  },
  {
    "manager_Name": "557( 15,089 )",
    "Teams": "False 9( Rohan Rai )",
    "SXL": "IND",
    "Latp": "93",
    "Player_1": "Pope 2",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Doku 1",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Saka 7",
    "Player_2": "Gu\u00E9hi 4",
    "Player_5": "Kudus 2",
    "Player_6": "Anthony 2",
    "Player_3": "Senesi 2",
    "Player_4": "Gabriel 12",
    "Player_8": "Semenyo 4",
    "Player_9": "Haaland 26",
    "Player_15": "Mukiele 17"
  },
  {
    "manager_Name": "521( 200,130 )",
    "Teams": "Kung fu Pandoos( Indrajeet Singh )",
    "SXL": "IND",
    "Latp": "67",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "\u0160e\u0161ko 1",
    "Player_10": "Haaland 26",
    "Player_12": "Kelleher 6",
    "Player_13": "De Ligt",
    "Player_14": "Grealish 0",
    "Player_7": "Semenyo 4",
    "Player_2": "Virgil 3",
    "Player_5": "Walker 14",
    "Player_6": "Kudus 2",
    "Player_3": "Pedro Porro",
    "Player_4": "Gvardiol 0",
    "Player_8": "Mbeumo 9",
    "Player_9": "Bowen 2",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "520( 219,293 )",
    "Teams": "RIP-DIOGO.20( pranam rai )",
    "SXL": "IND",
    "Latp": "107",
    "Player_1": "D\u00FAbravka 9",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "Vicario 1",
    "Player_13": "Est\u00E8ve 8",
    "Player_14": "Malen 2",
    "Player_7": "Gakpo 7",
    "Player_2": "Cucurella 8",
    "Player_5": "Kudus 2",
    "Player_6": "Semenyo 4",
    "Player_3": "Gabriel 12",
    "Player_4": "J.Timber 6",
    "Player_8": "Minteh 2",
    "Player_9": "Woltemade 8",
    "Player_15": "Mu\u00F1oz 10"
  },
  {
    "manager_Name": "514( 292,097 )",
    "Teams": "error404( Duri Tadu )",
    "SXL": "IND",
    "Latp": "73",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Woltemade 8",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Stach 2",
    "Player_14": "Rodon 1",
    "Player_7": "Semenyo 4",
    "Player_2": "Gvardiol 0",
    "Player_5": "Reijnders 1",
    "Player_6": "Saka 7",
    "Player_3": "Gabriel 12",
    "Player_4": "Virgil 3",
    "Player_8": "Ndiaye 4",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Andersen 1"
  },
  {
    "manager_Name": "504( 491,864 )",
    "Teams": "PWS( Z S )",
    "SXL": "IND",
    "Latp": "62",
    "Player_1": "Donnarumma 6",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "J.Timber 6",
    "Player_14": "Anderson 4",
    "Player_7": "Gakpo 7",
    "Player_2": "Senesi 2",
    "Player_5": "Semenyo 4",
    "Player_6": "Reijnders 1",
    "Player_3": "Gabriel 12",
    "Player_4": "Van de",
    "Player_8": "Grealish 0",
    "Player_9": "Isak 2",
    "Player_15": "Dorgu 1"
  },
  {
    "manager_Name": "496( 711,685 )",
    "Teams": "\u0160e\u0161ko and Destroy( Pema Lepcha )",
    "SXL": "IND",
    "Latp": "77",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Woltemade 8",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Gakpo 7",
    "Player_14": "Grealish 0",
    "Player_7": "Semenyo 4",
    "Player_2": "Senesi 2",
    "Player_5": "Calafiori 6",
    "Player_6": "Zubimendi 3",
    "Player_3": "Mu\u00F1oz 10",
    "Player_4": "Pedro Porro",
    "Player_8": "Mbeumo 9",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "493( 812,133 )",
    "Teams": "11 n over( Ashish Rai )",
    "SXL": "IND",
    "Latp": "83",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "O.Dango 3",
    "Player_14": "Rodon 1",
    "Player_7": "Gakpo 7",
    "Player_2": "Diouf 1",
    "Player_5": "Kudus 2",
    "Player_6": "Minteh 2",
    "Player_3": "Mu\u00F1oz 10",
    "Player_4": "J.Timber 6",
    "Player_8": "Saka 7",
    "Player_9": "Richarlison 1",
    "Player_15": "Gvardiol 0"
  },
  {
    "manager_Name": "492( 827,301 )",
    "Teams": "Blue Brigade( Bhuman Basnet )",
    "SXL": "IND",
    "Latp": "48",
    "Player_1": "Vicario 1",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Gudmundsson 1",
    "Player_14": "Tuanzebe 8",
    "Player_7": "M.Salah 2",
    "Player_2": "Senesi 2",
    "Player_5": "Semenyo 4",
    "Player_6": "Kudus 2",
    "Player_3": "Calafiori 6",
    "Player_4": "Van de",
    "Player_8": "Reijnders 1",
    "Player_9": "Sarr 2",
    "Player_15": "Barnes 1"
  },
  {
    "manager_Name": "487( 1,010,276 )",
    "Teams": "Alpha11( AVIJIT DAS )",
    "SXL": "IND",
    "Latp": "64",
    "Player_1": "Vicario 1",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Gudmundsson 1",
    "Player_14": "King 2",
    "Player_7": "Semenyo 4",
    "Player_2": "Senesi 2",
    "Player_5": "Chalobah 6",
    "Player_6": "Reijnders 1",
    "Player_3": "Gabriel 12",
    "Player_4": "Lacroix 1",
    "Player_8": "Saka 7",
    "Player_9": "Haaland 26",
    "Player_15": "Grealish 0"
  },
  {
    "manager_Name": "485( 1,079,874 )",
    "Teams": "abcde FC( Prayash Thapa )",
    "SXL": "IND",
    "Latp": "64",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "N.Williams 1",
    "Player_14": "Est\u00E8ve 8",
    "Player_7": "Semenyo 4",
    "Player_2": "Van de",
    "Player_5": "Reijnders 1",
    "Player_6": "B.Fernandes 8",
    "Player_3": "Richards 3",
    "Player_4": "Gabriel 12",
    "Player_8": "Wirtz 1",
    "Player_9": "Bowen 2",
    "Player_15": "Dewsbury-Hall 2"
  },
  {
    "manager_Name": "483( 1,166,487 )",
    "Teams": "Top Gooner( VibhutiHang Subba )",
    "SXL": "IND",
    "Latp": "72",
    "Player_1": "Raya 6",
    "Player_11": "Bowen 2",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Reijnders 1",
    "Player_14": "Pedro Porro",
    "Player_7": "Semenyo 4",
    "Player_2": "Mukiele 17",
    "Player_5": "Kudus 2",
    "Player_6": "Eze 3",
    "Player_3": "Senesi 2",
    "Player_4": "Rodon 1",
    "Player_8": "Saka 7",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Lacroix 1"
  },
  {
    "manager_Name": "483( 1,187,261 )",
    "Teams": "Comet FC( Pranesh Sharma )",
    "SXL": "IND",
    "Latp": "74",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "Haaland 26",
    "Player_10": "Woltemade 8",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Andersen 1",
    "Player_7": "Kudus 2",
    "Player_2": "Pedro Porro",
    "Player_5": "Saka 7",
    "Player_6": "Semenyo 4",
    "Player_3": "Est\u00E8ve 8",
    "Player_4": "Senesi 2",
    "Player_8": "Mbeumo 9",
    "Player_9": "Anthony 2",
    "Player_15": "Cash 2"
  },
  {
    "manager_Name": "480( 1,291,940 )",
    "Teams": "ASHLAD FC( Ashim Lama )",
    "SXL": "IND",
    "Latp": "60",
    "Player_1": "D\u00FAbravka 9",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Roefs 7",
    "Player_13": "Est\u00E8ve 8",
    "Player_14": "Marc Guiu",
    "Player_7": "Ndiaye 4",
    "Player_2": "Senesi 2",
    "Player_5": "M.Salah 2",
    "Player_6": "Gakpo 7",
    "Player_3": "Virgil 3",
    "Player_4": "Van de",
    "Player_8": "Semenyo 4",
    "Player_9": "P.M.Sarr 1",
    "Player_15": "Dorgu 1"
  },
  {
    "manager_Name": "479( 1,335,120 )",
    "Teams": "MANCHESTER IS BLUE( PRAYAS BAJGAI )",
    "SXL": "IND",
    "Latp": "64",
    "Player_1": "Pope 2",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Andersen 1",
    "Player_14": "Senesi 2",
    "Player_7": "Gordon 2",
    "Player_2": "Rodon 1",
    "Player_5": "Saka 7",
    "Player_6": "Enzo 0",
    "Player_3": "Gabriel 12",
    "Player_4": "J.Timber 6",
    "Player_8": "Semenyo 4",
    "Player_9": "Sarr 2",
    "Player_15": "Calvert-Lewin 2"
  },
  {
    "manager_Name": "475( 1,502,680 )",
    "Teams": "PINE( SATYAM RAI )",
    "SXL": "IND",
    "Latp": "80",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Stach 2",
    "Player_14": "Van de",
    "Player_7": "Saka 7",
    "Player_2": "Gabriel 12",
    "Player_5": "Mukiele 17",
    "Player_6": "Semenyo 4",
    "Player_3": "Senesi 2",
    "Player_4": "Burn 2",
    "Player_8": "Reijnders 1",
    "Player_9": "Richarlison 1",
    "Player_15": "Ndiaye 4"
  },
  {
    "manager_Name": "473( 1,599,243 )",
    "Teams": "Lu Lu( Nishant Lohagun )",
    "SXL": "IND",
    "Latp": "68",
    "Player_1": "Raya 6",
    "Player_11": "Richarlison 1",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Doku 1",
    "Player_14": "Ndiaye 4",
    "Player_7": "Semenyo 4",
    "Player_2": "Senesi 2",
    "Player_5": "Richards 3",
    "Player_6": "B.Fernandes 8",
    "Player_3": "Gabriel 12",
    "Player_4": "Virgil 3",
    "Player_8": "Reijnders 1",
    "Player_9": "Haaland 26",
    "Player_15": "Andersen 1"
  },
  {
    "manager_Name": "461( 2,241,783 )",
    "Teams": "Cheesygarlic( Rishi Thulung )",
    "SXL": "IND",
    "Latp": "48",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Xhaka 5",
    "Player_14": "N.Williams 1",
    "Player_7": "M.Salah 2",
    "Player_2": "Dorgu 1",
    "Player_5": "Van de",
    "Player_6": "Semenyo 4",
    "Player_3": "Virgil 3",
    "Player_4": "Tarkowski 3",
    "Player_8": "Caicedo 1",
    "Player_9": "Reijnders 1",
    "Player_15": "Kroupi.Jr 12"
  },
  {
    "manager_Name": "448( 2,985,355 )",
    "Teams": "G\u00CBNJ\u00CF\u00CF UNITED( Pema Bhutia )",
    "SXL": "IND",
    "Latp": "75",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Alderete 6",
    "Player_14": "Anthony 2",
    "Player_7": "Semenyo 4",
    "Player_2": "Van de",
    "Player_5": "Chalobah 6",
    "Player_6": "Reijnders 1",
    "Player_3": "Senesi 2",
    "Player_4": "Gabriel 12",
    "Player_8": "B.Fernandes 8",
    "Player_9": "Woltemade 8",
    "Player_15": "Stach 2"
  },
  {
    "manager_Name": "447( 3,018,216 )",
    "Teams": "Fu\u00DFball-Mannschaft( Gaurav Shrestha )",
    "SXL": "IND",
    "Latp": "68",
    "Player_1": "Donnarumma 6",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Stach 2",
    "Player_14": "Andersen 1",
    "Player_7": "Ndiaye 4",
    "Player_2": "Gabriel 12",
    "Player_5": "B.Fernandes 8",
    "Player_6": "Semenyo 4",
    "Player_3": "Senesi 2",
    "Player_4": "Rodon 1",
    "Player_8": "Reijnders 1",
    "Player_9": "Haaland 26",
    "Player_15": "Tarkowski 3"
  },
  {
    "manager_Name": "447( 3,033,261 )",
    "Teams": "Bruno-nly Fans( Bejoy M Shrestha\u00B2\u2076\u2074 )",
    "SXL": "IND",
    "Latp": "78",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 8",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "King 2",
    "Player_14": "Van de",
    "Player_7": "Reijnders 1",
    "Player_2": "Burn 2",
    "Player_5": "Saka 7",
    "Player_6": "Semenyo 4",
    "Player_3": "Gabriel 12",
    "Player_4": "Senesi 2",
    "Player_8": "B.Fernandes 8",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "446( 3,092,541 )",
    "Teams": "F.C. ASSASSINS( Kushal Sahota )",
    "SXL": "IND",
    "Latp": "56",
    "Player_1": "D\u00FAbravka 9",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Sels 2",
    "Player_13": "Est\u00E8ve 8",
    "Player_14": "Van de",
    "Player_7": "M.Salah 2",
    "Player_2": "Gu\u00E9hi 4",
    "Player_5": "Sarr 2",
    "Player_6": "Caicedo 1",
    "Player_3": "Virgil 3",
    "Player_4": "Senesi 2",
    "Player_8": "Semenyo 4",
    "Player_9": "Richarlison 1",
    "Player_15": "King 2"
  },
  {
    "manager_Name": "444( 3,211,211 )",
    "Teams": "Native United( Monlom Rongong )",
    "SXL": "IND",
    "Latp": "71",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Bowen 2",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Reijnders 1",
    "Player_14": "Gu\u00E9hi 4",
    "Player_7": "Kudus 2",
    "Player_2": "Senesi 2",
    "Player_5": "Rodon 1",
    "Player_6": "Semenyo 4",
    "Player_3": "Gabriel 12",
    "Player_4": "J.Timber 6",
    "Player_8": "Gravenberch 2",
    "Player_9": "Woltemade 8",
    "Player_15": "Ndiaye 4"
  },
  {
    "manager_Name": "440( 3,440,022 )",
    "Teams": "GustavousGooner( Ashish Subba )",
    "SXL": "IND",
    "Latp": "56",
    "Player_1": "D\u00FAbravka 9",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Haaland 26",
    "Player_12": "S\u00E1nchez 5",
    "Player_13": "Enzo 0",
    "Player_14": "Mbeumo 9",
    "Player_7": "Szoboszlai 4",
    "Player_2": "Senesi 2",
    "Player_5": "Pedro Porro",
    "Player_6": "Semenyo 4",
    "Player_3": "Gudmundsson 1",
    "Player_4": "Gu\u00E9hi 4",
    "Player_8": "Reijnders 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Livramento 0"
  },
  {
    "manager_Name": "439( 3,523,499 )",
    "Teams": "Liverpool FC( Sunil Rai )",
    "SXL": "IND",
    "Latp": "52",
    "Player_1": "Pope 2",
    "Player_11": "Richarlison 1",
    "Player_10": "Haaland 26",
    "Player_12": "S\u00E1nchez 5",
    "Player_13": "Tavernier 5",
    "Player_14": "Grealish 0",
    "Player_7": "Semenyo 4",
    "Player_2": "Pedro Porro",
    "Player_5": "Mu\u00F1oz 10",
    "Player_6": "Reijnders 1",
    "Player_3": "Virgil 3",
    "Player_4": "Gvardiol 0",
    "Player_8": "Anthony 2",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "435( 3,765,701 )",
    "Teams": "The Regista.( Passang T Sherpa )",
    "SXL": "IND",
    "Latp": "61",
    "Player_1": "Vicario 1",
    "Player_11": "Woltemade 8",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Est\u00E8ve 8",
    "Player_7": "Reijnders 1",
    "Player_2": "Cucurella 8",
    "Player_5": "Gu\u00E9hi 4",
    "Player_6": "Enzo 0",
    "Player_3": "Calafiori 6",
    "Player_4": "Van de",
    "Player_8": "Eze 3",
    "Player_9": "Semenyo 4",
    "Player_15": "Grealish 0"
  },
  {
    "manager_Name": "427( 4,269,064 )",
    "Teams": "Busby Baby( Regean Lama )",
    "SXL": "IND",
    "Latp": "68",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "Woltemade 8",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Dorgu 1",
    "Player_14": "Grealish 0",
    "Player_7": "Kudus 2",
    "Player_2": "Van de",
    "Player_5": "Reijnders 1",
    "Player_6": "Semenyo 4",
    "Player_3": "Konsa 2",
    "Player_4": "Mu\u00F1oz 10",
    "Player_8": "B.Fernandes 8",
    "Player_9": "Haaland 26",
    "Player_15": "Alex Moreno"
  },
  {
    "manager_Name": "421( 4,604,137 )",
    "Teams": "Hooligans25( Pradhyumna Subba )",
    "SXL": "IND",
    "Latp": "71",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Woltemade 8",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Richards 3",
    "Player_14": "Marc Guiu",
    "Player_7": "Sarr 2",
    "Player_2": "Gabriel 12",
    "Player_5": "Buend\u00EDa 7",
    "Player_6": "M.Salah 2",
    "Player_3": "Van de",
    "Player_4": "J.Timber 6",
    "Player_8": "Reijnders 1",
    "Player_9": "Doku 1",
    "Player_15": "Reinildo 0"
  },
  {
    "manager_Name": "414( 5,029,614 )",
    "Teams": "Imperial Blues( Saurabh Tamang )",
    "SXL": "IND",
    "Latp": "50",
    "Player_1": "Vicario 1",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 26",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Foster 0",
    "Player_14": "Caicedo 1",
    "Player_7": "M.Salah 2",
    "Player_2": "Virgil 3",
    "Player_5": "Richards 3",
    "Player_6": "Semenyo 4",
    "Player_3": "Senesi 2",
    "Player_4": "Romero 0",
    "Player_8": "Ndiaye 4",
    "Player_9": "Zubimendi 3",
    "Player_15": "Est\u00E8ve 8"
  },
  {
    "manager_Name": "412( 5,172,176 )",
    "Teams": "GODFATHER FC( Riwaj Rai )",
    "SXL": "IND",
    "Latp": "66",
    "Player_1": "D\u00FAbravka 9",
    "Player_11": "Isidor 2",
    "Player_10": "Haaland 26",
    "Player_12": "Sels 2",
    "Player_13": "Cash 2",
    "Player_14": "Grealish 0",
    "Player_7": "Reijnders 1",
    "Player_2": "Gu\u00E9hi 4",
    "Player_5": "Est\u00E8ve 8",
    "Player_6": "Kudus 2",
    "Player_3": "Cucurella 8",
    "Player_4": "Pedro Porro",
    "Player_8": "O.Dango 3",
    "Player_9": "M.Salah 2",
    "Player_15": "F\u00FCllkrug 0"
  },
  {
    "manager_Name": "402( 5,762,036 )",
    "Teams": "I_am_done_XI( Dipen Thapa )",
    "SXL": "IND",
    "Latp": "37",
    "Player_1": "Raya 6",
    "Player_11": "Wood 1",
    "Player_10": "Gy\u00F6keres 4",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Grealish 0",
    "Player_14": "Senesi 2",
    "Player_7": "M.Salah 2",
    "Player_2": "Est\u00E8ve 8",
    "Player_5": "Semenyo 4",
    "Player_6": "Eze 3",
    "Player_3": "Gu\u00E9hi 4",
    "Player_4": "Pedro Porro",
    "Player_8": "Kudus 2",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Konsa 2"
  },
  {
    "manager_Name": "402( 5,790,327 )",
    "Teams": "Hangkim_0011( ABHINANDAN RAI )",
    "SXL": "IND",
    "Latp": "58",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Est\u00E8ve 8",
    "Player_14": "Ndiaye 4",
    "Player_7": "Gakpo 7",
    "Player_2": "Pedro Porro",
    "Player_5": "Reijnders 1",
    "Player_6": "Rice 3",
    "Player_3": "Burn 2",
    "Player_4": "R\u00FAben 6",
    "Player_8": "Semenyo 4",
    "Player_9": "Ekitik\u00E9 1",
    "Player_15": "Konsa 2"
  },
  {
    "manager_Name": "401( 5,853,313 )",
    "Teams": "Jorebungalow YFC( Vivek Lama )",
    "SXL": "IND",
    "Latp": "58",
    "Player_1": "Verbruggen 2",
    "Player_11": "Richarlison 1",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "De Cuyper",
    "Player_14": "Est\u00E8ve 8",
    "Player_7": "M.Salah 2",
    "Player_2": "Calafiori 6",
    "Player_5": "Kudus 2",
    "Player_6": "King 2",
    "Player_3": "Cucurella 8",
    "Player_4": "Van de",
    "Player_8": "Gakpo 7",
    "Player_9": "Haaland 26",
    "Player_15": "L.Miley 4"
  },
  {
    "manager_Name": "392( 6,377,888 )",
    "Teams": "Let MEE COOK( \u00CFaraplang Pompyrthat )",
    "SXL": "IND",
    "Latp": "48",
    "Player_1": "Pope 2",
    "Player_11": "Haaland 13",
    "Player_10": "Woltemade 8",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Est\u00E8ve 8",
    "Player_14": "Rodon 1",
    "Player_7": "Semenyo 4",
    "Player_2": "J.Timber 6",
    "Player_5": "Kudus 2",
    "Player_6": "M.Salah 4",
    "Player_3": "Senesi 2",
    "Player_4": "Burn 2",
    "Player_8": "Xhaka 5",
    "Player_9": "Enzo 0",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "388( 6,602,248 )",
    "Teams": "GUNNERS( Omkar Subba )",
    "SXL": "IND",
    "Latp": "39",
    "Player_1": "Vicario 1",
    "Player_11": "Haaland 13",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Verbruggen 2",
    "Player_13": "Zubimendi 3",
    "Player_14": "Van de",
    "Player_7": "Semenyo 8",
    "Player_2": "Senesi 2",
    "Player_5": "Caicedo 1",
    "Player_6": "Anthony 2",
    "Player_3": "Gu\u00E9hi 4",
    "Player_4": "Virgil 3",
    "Player_8": "Gravenberch 2",
    "Player_9": "Ekitik\u00E9 1",
    "Player_15": "Spence 1"
  },
  {
    "manager_Name": "379( 7,106,985 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "63",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Xhaka 5",
    "Player_14": "L.Miley 4",
    "Player_7": "Reijnders 1",
    "Player_2": "Gabriel 12",
    "Player_5": "Gudmundsson 1",
    "Player_6": "L.Paquet\u00E1 2",
    "Player_3": "Virgil 3",
    "Player_4": "Senesi 2",
    "Player_8": "M.Salah 2",
    "Player_9": "Thiago 6",
    "Player_15": "Andersen 1"
  },
  {
    "manager_Name": "367( 7,774,922 )",
    "Teams": "Boehly Blues( Aditya Bhandari )",
    "SXL": "IND",
    "Latp": "64",
    "Player_1": "Petrovi\u0107 2",
    "Player_11": "Haaland 26",
    "Player_10": "Woltemade 8",
    "Player_12": "D\u00FAbravka 9",
    "Player_13": "Stach 2",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Saka 7",
    "Player_2": "Senesi 2",
    "Player_5": "Reijnders 1",
    "Player_6": "Anthony 2",
    "Player_3": "Gu\u00E9hi 4",
    "Player_4": "J.Timber 6",
    "Player_8": "Semenyo 4",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Est\u00E8ve 8"
  },
  {
    "manager_Name": "341( 8,968,908 )",
    "Teams": "Invincibles( Bishal Rai )",
    "SXL": "IND",
    "Latp": "36",
    "Player_1": "S\u00E1nchez 5",
    "Player_11": "Ekitik\u00E9 1",
    "Player_10": "Wood 1",
    "Player_12": "Kinsky 0",
    "Player_13": "Wirtz 1",
    "Player_14": "Neto 12",
    "Player_7": "Semenyo 8",
    "Player_2": "Mu\u00F1oz 10",
    "Player_5": "Milenkovi\u0107 1",
    "Player_6": "Enzo 0",
    "Player_3": "Saliba 6",
    "Player_4": "Pedro Porro",
    "Player_8": "Johnson 1",
    "Player_9": "Gy\u00F6keres 2",
    "Player_15": "A\u00EFt-Nouri 0"
  }
];