var s = [
  {
    "manager_Name": "469( 68,004 )",
    "Teams": "Charlie\u0027s Angels( Charlie Smith )",
    "SXL": "ENG",
    "Latp": "67",
    "Player_1": "Raya 6",
    "Player_11": "Watkins 2",
    "Player_10": "Haaland 16",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "P.M.Sarr 1",
    "Player_14": "King 3",
    "Player_7": "M.Salah 2",
    "Player_2": "Digne 1",
    "Player_5": "Van de",
    "Player_6": "Saliba 6",
    "Player_3": "Cash 2",
    "Player_4": "Gabriel 9",
    "Player_8": "Semenyo 18",
    "Player_9": "Reijnders 3",
    "Player_15": "Abdullahi 0"
  },
  {
    "manager_Name": "463( 109,768 )",
    "Teams": "Rice Rice Baby( kaisler Schembri )",
    "SXL": "MLT",
    "Latp": "84",
    "Player_1": "Donnarumma 6",
    "Player_11": "Haaland 16",
    "Player_10": "Woltemade 6",
    "Player_12": "Darlow 1",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "Semenyo 18",
    "Player_2": "Tarkowski 5",
    "Player_5": "Mbeumo 6",
    "Player_6": "Ndiaye 7",
    "Player_3": "Gabriel 9",
    "Player_4": "Van de",
    "Player_8": "Reijnders 3",
    "Player_9": "Eze 6",
    "Player_15": "Wan-Bissaka 1"
  },
  {
    "manager_Name": "459( 140,617 )",
    "Teams": "Ellul FC( Andrew Ellul )",
    "SXL": "MLT",
    "Latp": "83",
    "Player_1": "Pope 7",
    "Player_11": "Evanilson 2",
    "Player_10": "Haaland 8",
    "Player_12": "Henderson 2",
    "Player_13": "Milenkovi\u0107 3",
    "Player_14": "Mitoma 0",
    "Player_7": "Zubimendi 3",
    "Player_2": "Gu\u00E9hi 3",
    "Player_5": "Van de",
    "Player_6": "Rice 11",
    "Player_3": "Gabriel 9",
    "Player_4": "Romero 1",
    "Player_8": "Semenyo 36",
    "Player_9": "Richarlison 1",
    "Player_15": "Gakpo 7"
  },
  {
    "manager_Name": "451( 242,142 )",
    "Teams": "TetasSexyReds( Gary Pace )",
    "SXL": "MLT",
    "Latp": "74",
    "Player_1": "D\u00FAbravka 2",
    "Player_11": "Haaland 8",
    "Player_10": "Gy\u00F6keres 4",
    "Player_12": "Sels 3",
    "Player_13": "Andersen 3",
    "Player_14": "Beto 1",
    "Player_7": "Reijnders 3",
    "Player_2": "Gabriel 9",
    "Player_5": "Mbeumo 6",
    "Player_6": "Rice 11",
    "Player_3": "Pedro Porro",
    "Player_4": "Senesi 2",
    "Player_8": "Kudus 12",
    "Player_9": "Grealish 10",
    "Player_15": "Diouf 3"
  },
  {
    "manager_Name": "450( 253,153 )",
    "Teams": "Arteta Ball FC( Dylan Camilleri )",
    "SXL": "MLT",
    "Latp": "87",
    "Player_1": "Sels 3",
    "Player_11": "Haaland 16",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "S\u00E1nchez 2",
    "Player_13": "Jo\u00E3o Pedro",
    "Player_14": "Tarkowski 5",
    "Player_7": "Reijnders 3",
    "Player_2": "Gabriel 9",
    "Player_5": "Semenyo 18",
    "Player_6": "Ndiaye 7",
    "Player_3": "Konsa 2",
    "Player_4": "Mu\u00F1oz 8",
    "Player_8": "Kudus 12",
    "Player_9": "Sarr 7",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "441( 429,931 )",
    "Teams": "Slika FC( Kyle Gatt )",
    "SXL": "MLT",
    "Latp": "64",
    "Player_1": "Martinez 1",
    "Player_11": "Haaland 16",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Darlow 1",
    "Player_13": "Sch\u00E4r 0",
    "Player_14": "Mitoma 0",
    "Player_7": "Reijnders 3",
    "Player_2": "N.Williams 0",
    "Player_5": "Gabriel 9",
    "Player_6": "Enzo 2",
    "Player_3": "Pedro Porro",
    "Player_4": "Gvardiol 12",
    "Player_8": "Ndiaye 7",
    "Player_9": "Isak 5",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "438( 490,069 )",
    "Teams": "Bench Warmers( kevin dalli )",
    "SXL": "MLT",
    "Latp": "82",
    "Player_1": "Petrovi\u0107 3",
    "Player_11": "Haaland 16",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Kelleher 3",
    "Player_13": "Ekitik\u00E9 1",
    "Player_14": "Gakpo 7",
    "Player_7": "Semenyo 18",
    "Player_2": "Gu\u00E9hi 3",
    "Player_5": "Burn 11",
    "Player_6": "Kudus 12",
    "Player_3": "Calafiori 6",
    "Player_4": "Pedro Porro",
    "Player_8": "Doku 1",
    "Player_9": "Reijnders 3",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "436( 563,753 )",
    "Teams": "Taggers FC( Karl Caruana )",
    "SXL": "MLT",
    "Latp": "79",
    "Player_1": "Kelleher 3",
    "Player_11": "Woltemade 6",
    "Player_10": "Haaland 16",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Mukiele 3",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "Ndiaye 7",
    "Player_2": "Gabriel 9",
    "Player_5": "M.Salah 2",
    "Player_6": "Kudus 12",
    "Player_3": "Van de",
    "Player_4": "Konsa 2",
    "Player_8": "Semenyo 18",
    "Player_9": "Ndoye 2",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "433( 629,396 )",
    "Teams": "diavoli 11( Paul Micallef )",
    "SXL": "MLT",
    "Latp": "57",
    "Player_1": "Donnarumma 6",
    "Player_11": "Haaland 16",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Setford 0",
    "Player_13": "Xavi 2",
    "Player_14": "Mings 0",
    "Player_7": "Semenyo 18",
    "Player_2": "Gu\u00E9hi 3",
    "Player_5": "B.Fernandes 3",
    "Player_6": "Enzo 2",
    "Player_3": "Senesi 2",
    "Player_4": "Chalobah 0",
    "Player_8": "Reijnders 3",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Byram 0"
  },
  {
    "manager_Name": "433( 637,988 )",
    "Teams": "Bend it like Boogie( Ryan Bonello Gatt )",
    "SXL": "MLT",
    "Latp": "80",
    "Player_1": "Kelleher 3",
    "Player_11": "Gy\u00F6keres 4",
    "Player_10": "Haaland 8",
    "Player_12": "Sels 3",
    "Player_13": "Virgil 1",
    "Player_14": "Wan-Bissaka 1",
    "Player_7": "Reijnders 3",
    "Player_2": "Gabriel 9",
    "Player_5": "Mbeumo 6",
    "Player_6": "Semenyo 18",
    "Player_3": "R\u00FAben 9",
    "Player_4": "Gu\u00E9hi 3",
    "Player_8": "Gakpo 7",
    "Player_9": "Grealish 10",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "430( 729,096 )",
    "Teams": "MaltArsenal FC( Claude Spiteri )",
    "SXL": "MLT",
    "Latp": "87",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 8",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Gudmundsson 1",
    "Player_14": "Enzo 2",
    "Player_7": "B.Fernandes 3",
    "Player_2": "Gabriel 18",
    "Player_5": "Semenyo 18",
    "Player_6": "Grealish 10",
    "Player_3": "Senesi 2",
    "Player_4": "Calafiori 6",
    "Player_8": "Kudus 12",
    "Player_9": "Mateta 2",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "429( 768,881 )",
    "Teams": "Old Havertz Kai Hard( Andy Bonaci )",
    "SXL": "MLT",
    "Latp": "74",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 16",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Caicedo 10",
    "Player_14": "Virgil 1",
    "Player_7": "Semenyo 18",
    "Player_2": "Lacroix 3",
    "Player_5": "Gabriel 9",
    "Player_6": "Xavi 2",
    "Player_3": "Mu\u00F1oz 8",
    "Player_4": "Senesi 2",
    "Player_8": "Reijnders 3",
    "Player_9": "Isak 5",
    "Player_15": "Dewsbury-Hall 0"
  },
  {
    "manager_Name": "426( 872,983 )",
    "Teams": "gunner_xi( Justin kind )",
    "SXL": "MLT",
    "Latp": "67",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Haaland 16",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Ndoye 2",
    "Player_14": "Livramento 0",
    "Player_7": "Gakpo 7",
    "Player_2": "Gabriel 9",
    "Player_5": "Sarr 7",
    "Player_6": "Kudus 12",
    "Player_3": "Romero 1",
    "Player_4": "Senesi 2",
    "Player_8": "Reijnders 3",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Reinildo 0"
  },
  {
    "manager_Name": "426( 896,616 )",
    "Teams": "Noni your business( Owen Farrugia )",
    "SXL": "MLT",
    "Latp": "74",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Kudus 12",
    "Player_14": "Andersen 3",
    "Player_7": "Xavi 2",
    "Player_2": "Gabriel 9",
    "Player_5": "Semenyo 18",
    "Player_6": "Ndiaye 7",
    "Player_3": "Pedro Porro",
    "Player_4": "Senesi 2",
    "Player_8": "Reijnders 3",
    "Player_9": "Haaland 16",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "423( 1,008,440 )",
    "Teams": "matthew 14( matthew borg )",
    "SXL": "MLT",
    "Latp": "81",
    "Player_1": "Pope 7",
    "Player_11": "Haaland 16",
    "Player_10": "Mateta 2",
    "Player_12": "Foderingham 0",
    "Player_13": "Pedro Lima",
    "Player_14": "Hughes 0",
    "Player_7": "Semenyo 18",
    "Player_2": "Burn 11",
    "Player_5": "Tarkowski 5",
    "Player_6": "Wirtz 1",
    "Player_3": "Pedro Porro",
    "Player_4": "Konsa 2",
    "Player_8": "Neto 2",
    "Player_9": "Grealish 10",
    "Player_15": "Ekitik\u00E9 1"
  },
  {
    "manager_Name": "422( 1,033,364 )",
    "Teams": "Kind FC( Richard Kind )",
    "SXL": "MLT",
    "Latp": "70",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 16",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Henderson 2",
    "Player_13": "Rodon 1",
    "Player_14": "Gravenberch 2",
    "Player_7": "Mbeumo 6",
    "Player_2": "Dunk 1",
    "Player_5": "Reijnders 3",
    "Player_6": "Kudus 12",
    "Player_3": "Gabriel 9",
    "Player_4": "Lacroix 3",
    "Player_8": "Grealish 10",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Cucurella 7"
  },
  {
    "manager_Name": "419( 1,165,359 )",
    "Teams": "GunnerPorts( Matthew Portelli )",
    "SXL": "MLT",
    "Latp": "79",
    "Player_1": "Pope 7",
    "Player_11": "Haaland 16",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Caicedo 10",
    "Player_14": "Van de",
    "Player_7": "Reijnders 3",
    "Player_2": "Gabriel 9",
    "Player_5": "Semenyo 18",
    "Player_6": "Ndiaye 7",
    "Player_3": "Gvardiol 12",
    "Player_4": "Senesi 2",
    "Player_8": "Cunha 1",
    "Player_9": "Gy\u00F6keres 2",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "418( 1,203,950 )",
    "Teams": "Clarky FC( Carl Clark )",
    "SXL": "ENG",
    "Latp": "62",
    "Player_1": "Leno 2",
    "Player_11": "Haaland 16",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Slonina 0",
    "Player_13": "Mayenda 1",
    "Player_14": "Murillo 0",
    "Player_7": "Saka 8",
    "Player_2": "Mitchell 1",
    "Player_5": "Cullen 6",
    "Player_6": "Enzo 2",
    "Player_3": "Konat\u00E9 1",
    "Player_4": "Spence 0",
    "Player_8": "Semenyo 18",
    "Player_9": "Eze 6",
    "Player_15": "Sch\u00E4r 0"
  },
  {
    "manager_Name": "417( 1,277,380 )",
    "Teams": "kurt slika( Kurt Gatt )",
    "SXL": "MLT",
    "Latp": "57",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 4",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Jos\u00E9 S\u00E1",
    "Player_13": "J.Palhinha 1",
    "Player_14": "Cucurella 7",
    "Player_7": "Zubimendi 3",
    "Player_2": "Gu\u00E9hi 3",
    "Player_5": "Mbeumo 6",
    "Player_6": "Semenyo 18",
    "Player_3": "Van de",
    "Player_4": "Senesi 2",
    "Player_8": "Reijnders 3",
    "Player_9": "Haaland 8",
    "Player_15": "Livramento 0"
  },
  {
    "manager_Name": "412( 1,515,562 )",
    "Teams": "Very Rice( Jake Caruana )",
    "SXL": "MLT",
    "Latp": "84",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 16",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Reijnders 3",
    "Player_14": "Foster 1",
    "Player_7": "M.Salah 2",
    "Player_2": "J.Timber 11",
    "Player_5": "Gu\u00E9hi 3",
    "Player_6": "Semenyo 18",
    "Player_3": "Van de",
    "Player_4": "Senesi 2",
    "Player_8": "Kudus 12",
    "Player_9": "Caicedo 10",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "411( 1,580,323 )",
    "Teams": "Hamrun Gunners( Mark Monseigneur )",
    "SXL": "MLT",
    "Latp": "82",
    "Player_1": "Pickford 3",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 8",
    "Player_12": "Henderson 2",
    "Player_13": "Sarr 7",
    "Player_14": "Walker 1",
    "Player_7": "Grealish 10",
    "Player_2": "Gabriel 9",
    "Player_5": "Rice 11",
    "Player_6": "Gakpo 7",
    "Player_3": "Pedro Porro",
    "Player_4": "Virgil 1",
    "Player_8": "Neto 2",
    "Player_9": "Woltemade 12",
    "Player_15": "Toti 0"
  },
  {
    "manager_Name": "404( 1,948,502 )",
    "Teams": "Gozo Gunners( Jonathan Portelli )",
    "SXL": "MLT",
    "Latp": "77",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 16",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Isidor 1",
    "Player_14": "Stach 2",
    "Player_7": "Caicedo 10",
    "Player_2": "Tarkowski 5",
    "Player_5": "Van de",
    "Player_6": "M.Salah 2",
    "Player_3": "Senesi 2",
    "Player_4": "Burn 11",
    "Player_8": "Semenyo 18",
    "Player_9": "Reijnders 3",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "402( 2,082,721 )",
    "Teams": "The Invincibles 49( Clive Caruana )",
    "SXL": "MLT",
    "Latp": "79",
    "Player_1": "Raya 6",
    "Player_11": "Mateta 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Gakpo 7",
    "Player_14": "Kudus 12",
    "Player_7": "Semenyo 18",
    "Player_2": "Virgil 1",
    "Player_5": "J.Timber 11",
    "Player_6": "Reijnders 3",
    "Player_3": "Mu\u00F1oz 8",
    "Player_4": "Van de",
    "Player_8": "Grealish 10",
    "Player_9": "Haaland 16",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "396( 2,495,858 )",
    "Teams": "Senglea Gunners( Daryl Ebejer )",
    "SXL": "MLT",
    "Latp": "67",
    "Player_1": "Pope 7",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 16",
    "Player_12": "Moore 0",
    "Player_13": "Alderete 0",
    "Player_14": "R\u00FAben 9",
    "Player_7": "Eze 6",
    "Player_2": "Virgil 1",
    "Player_5": "Anthony 1",
    "Player_6": "Semenyo 18",
    "Player_3": "Gabriel 9",
    "Player_4": "Lacroix 3",
    "Player_8": "Xhaka 3",
    "Player_9": "Ekitik\u00E9 1",
    "Player_15": "King 3"
  },
  {
    "manager_Name": "389( 2,951,928 )",
    "Teams": "Sultan Army( Julian Sultana )",
    "SXL": "MLT",
    "Latp": "79",
    "Player_1": "Pickford 3",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Richarlison 1",
    "Player_12": "Sels 3",
    "Player_13": "Cucurella 7",
    "Player_14": "Gibbs-White 4",
    "Player_7": "Xavi 2",
    "Player_2": "Saliba 6",
    "Player_5": "Gabriel 9",
    "Player_6": "Semenyo 36",
    "Player_3": "Virgil 1",
    "Player_4": "Calafiori 6",
    "Player_8": "Doku 1",
    "Player_9": "Kudus 12",
    "Player_15": "Ekitik\u00E9 1"
  },
  {
    "manager_Name": "388( 2,984,542 )",
    "Teams": "Select Team Name( Kurt Bonnici )",
    "SXL": "MLT",
    "Latp": "91",
    "Player_1": "Donnarumma 6",
    "Player_11": "Woltemade 6",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Anderson 1",
    "Player_14": "Tarkowski 5",
    "Player_7": "Semenyo 18",
    "Player_2": "Van de",
    "Player_5": "Grealish 10",
    "Player_6": "Reijnders 3",
    "Player_3": "Senesi 2",
    "Player_4": "Gabriel 9",
    "Player_8": "Saka 8",
    "Player_9": "Haaland 16",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "383( 3,342,009 )",
    "Teams": "RZM765( Cedrik Dalli )",
    "SXL": "MLT",
    "Latp": "64",
    "Player_1": "Verbruggen 1",
    "Player_11": "Haaland 16",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Wood 2",
    "Player_14": "Rodon 1",
    "Player_7": "Grealish 10",
    "Player_2": "Van de",
    "Player_5": "Anderson 1",
    "Player_6": "Foden 3",
    "Player_3": "Cucurella 7",
    "Player_4": "Mu\u00F1oz 8",
    "Player_8": "Reijnders 3",
    "Player_9": "Rice 11",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "383( 3,356,123 )",
    "Teams": "Gunz( Kurt Zammit )",
    "SXL": "MLT",
    "Latp": "56",
    "Player_1": "Donnarumma 6",
    "Player_11": "Haaland 16",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Est\u00E8ve 1",
    "Player_14": "Xhaka 3",
    "Player_7": "M.Salah 2",
    "Player_2": "Cash 2",
    "Player_5": "Senesi 2",
    "Player_6": "Reijnders 3",
    "Player_3": "Virgil 1",
    "Player_4": "Gu\u00E9hi 3",
    "Player_8": "Anthony 1",
    "Player_9": "Semenyo 18",
    "Player_15": "Isidor 1"
  },
  {
    "manager_Name": "375( 3,915,923 )",
    "Teams": "Sammygooner****( Sammy Vella )",
    "SXL": "MLT",
    "Latp": "66",
    "Player_1": "S\u00E1nchez 2",
    "Player_11": "Gy\u00F6keres 4",
    "Player_10": "Haaland 8",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Beto 1",
    "Player_14": "Van de",
    "Player_7": "Cunha 1",
    "Player_2": "Virgil 1",
    "Player_5": "Eze 6",
    "Player_6": "Kudus 12",
    "Player_3": "Konsa 2",
    "Player_4": "Gabriel 9",
    "Player_8": "Semenyo 18",
    "Player_9": "Reijnders 3",
    "Player_15": "A\u00EFt-Nouri 0"
  },
  {
    "manager_Name": "374( 3,988,997 )",
    "Teams": "Rice Rice Baby( Ian Falzon )",
    "SXL": "MLT",
    "Latp": "73",
    "Player_1": "Donnarumma 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Isak 5",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Richards 3",
    "Player_14": "Anthony 1",
    "Player_7": "Reijnders 3",
    "Player_2": "Van de",
    "Player_5": "Semenyo 18",
    "Player_6": "Mbeumo 6",
    "Player_3": "Virgil 1",
    "Player_4": "Senesi 2",
    "Player_8": "Kudus 12",
    "Player_9": "Haaland 16",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "371( 4,208,256 )",
    "Teams": "Zubi-Dooby Doo( Malcolm Vella Vidal )",
    "SXL": "MLT",
    "Latp": "55",
    "Player_1": "S\u00E1nchez 2",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Haaland 16",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Diouf 3",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "M.Salah 2",
    "Player_2": "Milenkovi\u0107 3",
    "Player_5": "Buend\u00EDa 0",
    "Player_6": "Kudus 12",
    "Player_3": "Pedro Porro",
    "Player_4": "Richards 3",
    "Player_8": "Rogers 5",
    "Player_9": "Reijnders 3",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "369( 4,346,480 )",
    "Teams": "Kanokk 118( Rodney Azzopardi )",
    "SXL": "MLT",
    "Latp": "61",
    "Player_1": "Henderson 2",
    "Player_11": "Evanilson 2",
    "Player_10": "Ekitik\u00E9 2",
    "Player_12": "Sels 3",
    "Player_13": "Frimpong 0",
    "Player_14": "A\u00EFt-Nouri 0",
    "Player_7": "Reijnders 3",
    "Player_2": "Cucurella 7",
    "Player_5": "Semenyo 18",
    "Player_6": "Enzo 2",
    "Player_3": "Gabriel 9",
    "Player_4": "Milenkovi\u0107 3",
    "Player_8": "Rice 11",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Saka 8"
  },
  {
    "manager_Name": "368( 4,442,057 )",
    "Teams": "Lions( Daniel Ferriggi )",
    "SXL": "MLT",
    "Latp": "52",
    "Player_1": "Pickford 3",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Kelleher 3",
    "Player_13": "Virgil 1",
    "Player_14": "Bowen 2",
    "Player_7": "Caicedo 10",
    "Player_2": "Senesi 2",
    "Player_5": "M.Salah 4",
    "Player_6": "Kudus 12",
    "Player_3": "Tarkowski 5",
    "Player_4": "Mu\u00F1oz 8",
    "Player_8": "Reijnders 3",
    "Player_9": "P.M.Sarr 1",
    "Player_15": "Milenkovi\u0107 3"
  },
  {
    "manager_Name": "365( 4,663,204 )",
    "Teams": "SC CARBINE( yan cutajar )",
    "SXL": "MLT",
    "Latp": "69",
    "Player_1": "Raya 6",
    "Player_11": "\u0160e\u0161ko 9",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Konsa 2",
    "Player_14": "Wan-Bissaka 1",
    "Player_7": "Semenyo 18",
    "Player_2": "Romero 1",
    "Player_5": "Grealish 10",
    "Player_6": "Kudus 12",
    "Player_3": "Van de",
    "Player_4": "Gu\u00E9hi 3",
    "Player_8": "M.Salah 2",
    "Player_9": "Gy\u00F6keres 2",
    "Player_15": "Baleba 0"
  },
  {
    "manager_Name": "361( 4,932,734 )",
    "Teams": "Mandra United( Steven Silvio )",
    "SXL": "MLT",
    "Latp": "72",
    "Player_1": "Raya 6",
    "Player_11": "Watkins 2",
    "Player_10": "Haaland 16",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Bowen 2",
    "Player_14": "Gravenberch 2",
    "Player_7": "Semenyo 18",
    "Player_2": "Virgil 1",
    "Player_5": "Saliba 6",
    "Player_6": "J.Timber 11",
    "Player_3": "Mitchell 1",
    "Player_4": "Senesi 2",
    "Player_8": "Enzo 2",
    "Player_9": "Sarr 7",
    "Player_15": "Kamara 5"
  },
  {
    "manager_Name": "355( 5,404,035 )",
    "Teams": "Henry\u2019s Heroes( Jean Azzopardi )",
    "SXL": "MLT",
    "Latp": "71",
    "Player_1": "Vicario 3",
    "Player_11": "Haaland 8",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Gravenberch 2",
    "Player_14": "Alderete 0",
    "Player_7": "Semenyo 18",
    "Player_2": "Gu\u00E9hi 3",
    "Player_5": "Eze 12",
    "Player_6": "Elanga 3",
    "Player_3": "Senesi 2",
    "Player_4": "Cucurella 7",
    "Player_8": "Rice 11",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Virgil 1"
  },
  {
    "manager_Name": "351( 5,673,687 )",
    "Teams": "Zubi dubi doo( Julia Schembri )",
    "SXL": "MLT",
    "Latp": "50",
    "Player_1": "Kelleher 3",
    "Player_11": "Beto 1",
    "Player_10": "Gy\u00F6keres 4",
    "Player_12": "Verbruggen 1",
    "Player_13": "Wan-Bissaka 1",
    "Player_14": "Dewsbury-Hall 0",
    "Player_7": "Semenyo 18",
    "Player_2": "Konsa 2",
    "Player_5": "Eze 6",
    "Player_6": "M.Salah 2",
    "Player_3": "Saliba 6",
    "Player_4": "Gu\u00E9hi 3",
    "Player_8": "Elanga 3",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "351( 5,687,443 )",
    "Teams": "Eze Come Eze Go( Theo Magro )",
    "SXL": "MLT",
    "Latp": "47",
    "Player_1": "Henderson 2",
    "Player_11": "Mateta 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Petrovi\u0107 3",
    "Player_13": "Xhaka 3",
    "Player_14": "Scott 4",
    "Player_7": "M.Salah 2",
    "Player_2": "Van de",
    "Player_5": "Gabriel 9",
    "Player_6": "Gakpo 7",
    "Player_3": "Mu\u00F1oz 8",
    "Player_4": "Trippier 6",
    "Player_8": "Reijnders 3",
    "Player_9": "Gy\u00F6keres 4",
    "Player_15": "Kerkez 1"
  },
  {
    "manager_Name": "351( 5,699,244 )",
    "Teams": "Dial Square( Liam Carabott )",
    "SXL": "MLT",
    "Latp": "57",
    "Player_1": "D\u00FAbravka 2",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 16",
    "Player_12": "Sels 3",
    "Player_13": "Enzo 2",
    "Player_14": "Wan-Bissaka 1",
    "Player_7": "Iwobi 2",
    "Player_2": "Virgil 1",
    "Player_5": "Anthony 1",
    "Player_6": "Semenyo 18",
    "Player_3": "Mu\u00F1oz 8",
    "Player_4": "Van de",
    "Player_8": "Zubimendi 3",
    "Player_9": "Watkins 2",
    "Player_15": "Livramento 0"
  },
  {
    "manager_Name": "349( 5,855,449 )",
    "Teams": "Lassie fc( Kirsten Tanti )",
    "SXL": "MLT",
    "Latp": "62",
    "Player_1": "D\u00FAbravka 2",
    "Player_11": "Gy\u00F6keres 4",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "A.Becker 0",
    "Player_13": "Gabriel 9",
    "Player_14": "Baleba 0",
    "Player_7": "Semenyo 18",
    "Player_2": "Pedro Porro",
    "Player_5": "Saliba 6",
    "Player_6": "M.Salah 2",
    "Player_3": "Van de",
    "Player_4": "Konsa 2",
    "Player_8": "Rogers 5",
    "Player_9": "Kudus 12",
    "Player_15": "Nmecha 1"
  },
  {
    "manager_Name": "346( 6,052,346 )",
    "Teams": "Gy\u00F6keres14( Zack Vella )",
    "SXL": "MLT",
    "Latp": "44",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 16",
    "Player_12": "Heaton 0",
    "Player_13": "Gudmundsson 1",
    "Player_14": "Reinildo 0",
    "Player_7": "King 3",
    "Player_2": "Est\u00E8ve 1",
    "Player_5": "Eze 6",
    "Player_6": "M.Salah 2",
    "Player_3": "Cash 2",
    "Player_4": "Virgil 1",
    "Player_8": "Reijnders 3",
    "Player_9": "Gy\u00F6keres 2",
    "Player_15": "Matete 0"
  },
  {
    "manager_Name": "339( 6,563,334 )",
    "Teams": "Mihawha( Matthew Paris )",
    "SXL": "MLT",
    "Latp": "49",
    "Player_1": "Donnarumma 6",
    "Player_11": "Gy\u00F6keres 4",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Milenkovi\u0107 3",
    "Player_14": "De Cuyper",
    "Player_7": "M.Salah 2",
    "Player_2": "Van de",
    "Player_5": "Semenyo 18",
    "Player_6": "Reijnders 3",
    "Player_3": "Pedro Porro",
    "Player_4": "Senesi 2",
    "Player_8": "Anderson 1",
    "Player_9": "Mateta 2",
    "Player_15": "Ndiaye 7"
  },
  {
    "manager_Name": "333( 6,953,256 )",
    "Teams": "Harambe FC( Glenn Gauci Borda )",
    "SXL": "MLT",
    "Latp": "44",
    "Player_1": "S\u00E1nchez 2",
    "Player_11": "Bowen 2",
    "Player_10": "Wood 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Reinildo 0",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "Reijnders 3",
    "Player_2": "Van de",
    "Player_5": "Semenyo 18",
    "Player_6": "M.Salah 2",
    "Player_3": "Konsa 2",
    "Player_4": "Wan-Bissaka 1",
    "Player_8": "Mbeumo 6",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "325( 7,480,199 )",
    "Teams": "NLD( Jordi Farrugia )",
    "SXL": "MLT",
    "Latp": "69",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "\u0160e\u0161ko 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Romero 1",
    "Player_14": "Saka 8",
    "Player_7": "Eze 6",
    "Player_2": "Cucurella 7",
    "Player_5": "James 4",
    "Player_6": "Elanga 6",
    "Player_3": "Gabriel 9",
    "Player_4": "Burn 11",
    "Player_8": "Gibbs-White 4",
    "Player_9": "Rogers 5",
    "Player_15": "Evanilson 2"
  },
  {
    "manager_Name": "324( 7,569,354 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "47",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 16",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "L.Miley 1",
    "Player_14": "Andersen 3",
    "Player_7": "M.Salah 2",
    "Player_2": "Gabriel 9",
    "Player_5": "Senesi 2",
    "Player_6": "Reijnders 3",
    "Player_3": "Virgil 1",
    "Player_4": "Gudmundsson 1",
    "Player_8": "Xhaka 3",
    "Player_9": "Thiago 2",
    "Player_15": "L.Paquet\u00E1 1"
  },
  {
    "manager_Name": "323( 7,607,423 )",
    "Teams": "Boca Seniors FC( Jake Bonnici )",
    "SXL": "MLT",
    "Latp": "30",
    "Player_1": "Vicario 3",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Beto 1",
    "Player_12": "Ramsdale 0",
    "Player_13": "Cherki 0",
    "Player_14": "Spence 0",
    "Player_7": "Saka 8",
    "Player_2": "Kerkez 1",
    "Player_5": "M.Salah 2",
    "Player_6": "Rogers 5",
    "Player_3": "Bassey 1",
    "Player_4": "Lewis-Skelly 1",
    "Player_8": "Wharton 3",
    "Player_9": "Ekitik\u00E9 1",
    "Player_15": "Aina 0"
  },
  {
    "manager_Name": "318( 7,920,424 )",
    "Teams": "Zubi Zubi Zooo( Andrew Brincat Ruffini )",
    "SXL": "MLT",
    "Latp": "54",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Gy\u00F6keres 4",
    "Player_12": "Darlow 1",
    "Player_13": "A\u00EFt-Nouri 0",
    "Player_14": "Palmer 0",
    "Player_7": "Semenyo 18",
    "Player_2": "Frimpong 0",
    "Player_5": "Eze 6",
    "Player_6": "Elanga 3",
    "Player_3": "Lewis 0",
    "Player_4": "Pedro Porro",
    "Player_8": "Ndiaye 7",
    "Player_9": "Marc Guiu",
    "Player_15": "Alex Moreno"
  },
  {
    "manager_Name": "315( 8,118,017 )",
    "Teams": "Jack Nigret( Jack Gatt )",
    "SXL": "MLT",
    "Latp": "44",
    "Player_1": "Donnarumma 6",
    "Player_11": "\u0160e\u0161ko 9",
    "Player_10": "Gy\u00F6keres 4",
    "Player_12": "Verbruggen 1",
    "Player_13": "Frimpong 0",
    "Player_14": "Palmer 0",
    "Player_7": "Doku 1",
    "Player_2": "Gabriel 9",
    "Player_5": "Rogers 5",
    "Player_6": "Reijnders 3",
    "Player_3": "Konat\u00E9 1",
    "Player_4": "Van de",
    "Player_8": "Adams 2",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Mu\u00F1oz 8"
  },
  {
    "manager_Name": "310( 8,381,780 )",
    "Teams": "InvinciblesCOYG( Clayton Camilleri )",
    "SXL": "MLT",
    "Latp": "44",
    "Player_1": "Raya 6",
    "Player_11": "Wilson 0",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Kelleher 3",
    "Player_13": "Dewsbury-Hall 0",
    "Player_14": "A\u00EFt-Nouri 0",
    "Player_7": "Xhaka 3",
    "Player_2": "Cucurella 7",
    "Player_5": "M.Salah 2",
    "Player_6": "Grealish 10",
    "Player_3": "Kerkez 1",
    "Player_4": "Est\u00E8ve 1",
    "Player_8": "Saka 8",
    "Player_9": "Gy\u00F6keres 4",
    "Player_15": "Reinildo 0"
  },
  {
    "manager_Name": "301( 8,837,330 )",
    "Teams": "Gorsil Gunners( Gordon Silvio )",
    "SXL": "MLT",
    "Latp": "56",
    "Player_1": "Raya 12",
    "Player_11": "\u0160e\u0161ko 9",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "Sels 3",
    "Player_13": "Palmer 0",
    "Player_14": "Wan-Bissaka 1",
    "Player_7": "Saka 8",
    "Player_2": "James 4",
    "Player_5": "Konsa 2",
    "Player_6": "Eze 6",
    "Player_3": "Gu\u00E9hi 3",
    "Player_4": "Van de",
    "Player_8": "Kluivert 7",
    "Player_9": "Beto 1",
    "Player_15": "Marmoush 0"
  }
];