var s = [
  {
    "manager_Name": "423( 1,008,440 )",
    "Teams": "\u00C7er\u00E7izi Jeshil( Armando Lula )",
    "SXL": "ALB",
    "Latp": "73",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 16",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Richards 3",
    "Player_14": "Andersen 3",
    "Player_7": "Ndiaye 7",
    "Player_2": "Gabriel 9",
    "Player_5": "B.Fernandes 3",
    "Player_6": "Semenyo 18",
    "Player_3": "Tarkowski 5",
    "Player_4": "Senesi 2",
    "Player_8": "Reijnders 3",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Stach 2"
  },
  {
    "manager_Name": "444( 355,880 )",
    "Teams": "Tepelena( Joan Hasanmema )",
    "SXL": "ALB",
    "Latp": "68",
    "Player_1": "Raya 6",
    "Player_11": "Richarlison 1",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Donnarumma 6",
    "Player_13": "Caicedo 10",
    "Player_14": "Alderete 0",
    "Player_7": "Semenyo 18",
    "Player_2": "Senesi 2",
    "Player_5": "B.Fernandes 3",
    "Player_6": "Reijnders 3",
    "Player_3": "Gu\u00E9hi 3",
    "Player_4": "Van de",
    "Player_8": "Kudus 12",
    "Player_9": "Haaland 16",
    "Player_15": "Rodon 1"
  },
  {
    "manager_Name": "423( 991,813 )",
    "Teams": "Renaissance( Sidrit Minxhozi )",
    "SXL": "DNK",
    "Latp": "88",
    "Player_1": "Pope 7",
    "Player_11": "Richarlison 1",
    "Player_10": "Haaland 16",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "N.Williams 0",
    "Player_14": "Xhaka 3",
    "Player_7": "Kudus 12",
    "Player_2": "J.Timber 11",
    "Player_5": "Saka 8",
    "Player_6": "Semenyo 18",
    "Player_3": "Van de",
    "Player_4": "R\u00FAben 9",
    "Player_8": "Enzo 2",
    "Player_9": "Gy\u00F6keres 2",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "412( 1,543,455 )",
    "Teams": "5-D( Erald Haxhiu )",
    "SXL": "USA",
    "Latp": "67",
    "Player_1": "Donnarumma 6",
    "Player_11": "Haaland 16",
    "Player_10": "Woltemade 6",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Senesi 2",
    "Player_14": "Xhaka 3",
    "Player_7": "Semenyo 18",
    "Player_2": "Dorgu 1",
    "Player_5": "Caicedo 10",
    "Player_6": "M.Salah 2",
    "Player_3": "Gu\u00E9hi 3",
    "Player_4": "Van de",
    "Player_8": "P.M.Sarr 1",
    "Player_9": "Gy\u00F6keres 2",
    "Player_15": "Mukiele 3"
  },
  {
    "manager_Name": "400( 2,191,632 )",
    "Teams": "BlueBoys( Ilir Bazaiti )",
    "SXL": "ENG",
    "Latp": "66",
    "Player_1": "D\u00FAbravka 2",
    "Player_11": "Richarlison 1",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Areola 2",
    "Player_13": "Diouf 3",
    "Player_14": "L.Miley 1",
    "Player_7": "Semenyo 18",
    "Player_2": "Senesi 2",
    "Player_5": "M.Salah 2",
    "Player_6": "Reijnders 3",
    "Player_3": "Gvardiol 12",
    "Player_4": "Van de",
    "Player_8": "Eze 6",
    "Player_9": "Haaland 16",
    "Player_15": "Tuanzebe 1"
  },
  {
    "manager_Name": "366( 4,567,066 )",
    "Teams": "Team name( Sunit Patel )",
    "SXL": "ENG",
    "Latp": "75",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 16",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Dewsbury-Hall 0",
    "Player_14": "Andersen 3",
    "Player_7": "B.Fernandes 3",
    "Player_2": "Gabriel 9",
    "Player_5": "Semenyo 18",
    "Player_6": "Reijnders 3",
    "Player_3": "Senesi 2",
    "Player_4": "Van de",
    "Player_8": "Kudus 12",
    "Player_9": "Gy\u00F6keres 2",
    "Player_15": "Rodon 1"
  },
  {
    "manager_Name": "417( 1,286,601 )",
    "Teams": "\uFFFD( Magi Muco )",
    "SXL": "ALB",
    "Latp": "56",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Haaland 16",
    "Player_12": "Verbruggen 1",
    "Player_13": "Ndoye 2",
    "Player_14": "Bassey 1",
    "Player_7": "Enzo 2",
    "Player_2": "Senesi 2",
    "Player_5": "Wirtz 1",
    "Player_6": "Grealish 10",
    "Player_3": "Dorgu 1",
    "Player_4": "Van de",
    "Player_8": "Saka 8",
    "Player_9": "Woltemade 6",
    "Player_15": "Rodon 1"
  },
  {
    "manager_Name": "410( 1,606,927 )",
    "Teams": "MAGA( Eni Shtini )",
    "SXL": "ALB",
    "Latp": "55",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 16",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Dewsbury-Hall 0",
    "Player_14": "King 3",
    "Player_7": "M.Salah 2",
    "Player_2": "Van de",
    "Player_5": "Senesi 2",
    "Player_6": "Semenyo 18",
    "Player_3": "Virgil 1",
    "Player_4": "Gu\u00E9hi 3",
    "Player_8": "L.Paquet\u00E1 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "406( 1,874,567 )",
    "Teams": "Glasner all over!( Ben Bushby )",
    "SXL": "ENG",
    "Latp": "59",
    "Player_1": "Vicario 3",
    "Player_11": "Haaland 16",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Rodon 1",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "Ndiaye 7",
    "Player_2": "Mu\u00F1oz 8",
    "Player_5": "Kudus 12",
    "Player_6": "M.Salah 2",
    "Player_3": "Van de",
    "Player_4": "Konsa 2",
    "Player_8": "Reijnders 3",
    "Player_9": "Wood 2",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "404( 1,975,329 )",
    "Teams": "Supercampeones( Ronny Nelkenbaum )",
    "SXL": "FRA",
    "Latp": "80",
    "Player_1": "D\u00FAbravka 2",
    "Player_11": "Haaland 16",
    "Player_10": "Watkins 2",
    "Player_12": "Sels 3",
    "Player_13": "Dewsbury-Hall 0",
    "Player_14": "Diouf 3",
    "Player_7": "Kudus 12",
    "Player_2": "Pedro Porro",
    "Player_5": "N.Williams 0",
    "Player_6": "Reijnders 3",
    "Player_3": "J.Timber 11",
    "Player_4": "Cucurella 7",
    "Player_8": "Semenyo 18",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "389( 2,915,920 )",
    "Teams": "Park The Bus( Lorin Minxhozi )",
    "SXL": "ENG",
    "Latp": "76",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 2",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Virgil 1",
    "Player_14": "King 3",
    "Player_7": "Mbeumo 6",
    "Player_2": "Pedro Porro",
    "Player_5": "B.Fernandes 3",
    "Player_6": "Semenyo 18",
    "Player_3": "Burn 11",
    "Player_4": "Senesi 2",
    "Player_8": "Reijnders 3",
    "Player_9": "Haaland 16",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "324( 7,569,354 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "47",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 16",
    "Player_10": "Gy\u00F6keres 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "L.Miley 1",
    "Player_14": "Andersen 3",
    "Player_7": "M.Salah 2",
    "Player_2": "Gabriel 9",
    "Player_5": "Senesi 2",
    "Player_6": "Reijnders 3",
    "Player_3": "Virgil 1",
    "Player_4": "Gudmundsson 1",
    "Player_8": "Xhaka 3",
    "Player_9": "Thiago 2",
    "Player_15": "L.Paquet\u00E1 1"
  },
  {
    "manager_Name": "422( 1,064,958 )",
    "Teams": "Zhampagne Football( Camilla Nurkhanov )",
    "SXL": "ENG",
    "Latp": "70",
    "Player_1": "D\u00FAbravka 2",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 16",
    "Player_12": "S\u00E1nchez 2",
    "Player_13": "Konsa 2",
    "Player_14": "E.Le F\u00E9e",
    "Player_7": "Kudus 12",
    "Player_2": "Gu\u00E9hi 3",
    "Player_5": "Van de",
    "Player_6": "Doku 1",
    "Player_3": "Senesi 2",
    "Player_4": "Gabriel 9",
    "Player_8": "Semenyo 18",
    "Player_9": "B.Fernandes 3",
    "Player_15": "Foster 1"
  },
  {
    "manager_Name": "401( 2,157,551 )",
    "Teams": "Kokeqethurit( Daver Berberi )",
    "SXL": "ALB",
    "Latp": "66",
    "Player_1": "Donnarumma 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 16",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Dewsbury-Hall 0",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "Ndiaye 7",
    "Player_2": "Virgil 1",
    "Player_5": "Lacroix 3",
    "Player_6": "M.Salah 2",
    "Player_3": "Dorgu 1",
    "Player_4": "Pedro Porro",
    "Player_8": "Reijnders 3",
    "Player_9": "Semenyo 18",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "427( 835,003 )",
    "Teams": "robby_baggio( Marin Jano )",
    "SXL": "ALB",
    "Latp": "90",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 16",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Gu\u00E9hi 3",
    "Player_14": "Calvert-Lewin 2",
    "Player_7": "Mbeumo 6",
    "Player_2": "Gabriel 9",
    "Player_5": "Kudus 12",
    "Player_6": "Eze 6",
    "Player_3": "Virgil 1",
    "Player_4": "Pedro Porro",
    "Player_8": "Semenyo 18",
    "Player_9": "Ndiaye 7",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "343( 6,279,916 )",
    "Teams": "Wiggler FC( Andrew Carr )",
    "SXL": "ENG",
    "Latp": "58",
    "Player_1": "Sels 3",
    "Player_11": "Mateta 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Alderete 0",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "Anderson 1",
    "Player_2": "Richards 3",
    "Player_5": "Reijnders 3",
    "Player_6": "M.Salah 2",
    "Player_3": "Romero 1",
    "Player_4": "Pedro Porro",
    "Player_8": "Semenyo 18",
    "Player_9": "Haaland 16",
    "Player_15": "Dewsbury-Hall 0"
  },
  {
    "manager_Name": "323( 7,646,389 )",
    "Teams": "FantaRog( Roger Shehu )",
    "SXL": "NLD",
    "Latp": "66",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 16",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Richarlison 1",
    "Player_14": "Cucurella 7",
    "Player_7": "Eze 6",
    "Player_2": "Pedro Porro",
    "Player_5": "Semenyo 18",
    "Player_6": "Xavi 2",
    "Player_3": "Senesi 2",
    "Player_4": "Gu\u00E9hi 3",
    "Player_8": "Wirtz 1",
    "Player_9": "Reijnders 3",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "273( 9,940,065 )",
    "Teams": "mayuluuu 5-0( Enio Minxhozi )",
    "SXL": "ALB",
    "Latp": "41",
    "Player_1": "Vicario 3",
    "Player_11": "Mateta 2",
    "Player_10": "Woltemade 6",
    "Player_12": "Dennis 0",
    "Player_13": "Clyne 0",
    "Player_14": "Frimpong 0",
    "Player_7": "Wirtz 1",
    "Player_2": "Cucurella 7",
    "Player_5": "Eze 6",
    "Player_6": "M.Salah 4",
    "Player_3": "Trippier 6",
    "Player_4": "De Cuyper",
    "Player_8": "Elanga 3",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Young 0"
  },
  {
    "manager_Name": "271( 9,995,710 )",
    "Teams": "Albi alexander( Bardhyl Minxhozi )",
    "SXL": "ALB",
    "Latp": "44",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Broja 1",
    "Player_12": "A.Becker 0",
    "Player_13": "Konsa 2",
    "Player_14": "Hoever 0",
    "Player_7": "L.Paquet\u00E1 1",
    "Player_2": "Gvardiol 12",
    "Player_5": "Elanga 3",
    "Player_6": "M.Salah 4",
    "Player_3": "Cucurella 7",
    "Player_4": "Virgil 1",
    "Player_8": "Mbeumo 6",
    "Player_9": "Johnson 1",
    "Player_15": "Muniz 0"
  }
];