var s = [
  {
    "manager_Name": "152( 37,929 )",
    "Teams": "Sultan Army( Julian Sultana )",
    "SXL": "countryCode",
    "Latp": "94",
    "Player_1": "Pickford 15",
    "Player_11": "Jo\u00E3o Pedro 30",
    "Player_10": "Ekitik\u00E9 9",
    "Player_12": "Sels 2",
    "Player_13": "Virgil 3",
    "Player_14": "Gibbs-White 2",
    "Player_7": "Ndiaye 8",
    "Player_2": "Cucurella 5",
    "Player_5": "Gabriel 6",
    "Player_6": "Johnson 9",
    "Player_3": "Saliba 6",
    "Player_4": "Murillo 1",
    "Player_8": "Cunha 2",
    "Player_9": "Kudus 3",
    "Player_15": "Bowen 2"
  },
  {
    "manager_Name": "148( 64,636 )",
    "Teams": "gunner_xi( Justin kind )",
    "SXL": "countryCode",
    "Latp": "66",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 24",
    "Player_10": "Watkins 2",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Acheampong 0",
    "Player_14": "Palmer 0",
    "Player_7": "Semenyo 6",
    "Player_2": "Cash 2",
    "Player_5": "Reinildo 3",
    "Player_6": "Reijnders 2",
    "Player_3": "Gabriel 6",
    "Player_4": "Truffert 6",
    "Player_8": "Neto 7",
    "Player_9": "Haaland 2",
    "Player_15": "Reed 0"
  },
  {
    "manager_Name": "136( 348,294 )",
    "Teams": "Charlie\u0027s Angels( Charlie Smith )",
    "SXL": "countryCode",
    "Latp": "61",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Gy\u00F6keres 24",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Mykolenko 0",
    "Player_14": "Abdullahi 0",
    "Player_7": "Reijnders 2",
    "Player_2": "Pedro Porro 5",
    "Player_5": "P.M.Sarr 3",
    "Player_6": "M.Salah 5",
    "Player_3": "Cash 2",
    "Player_4": "Est\u00E8ve 6",
    "Player_8": "Saka 6",
    "Player_9": "Zubimendi 3",
    "Player_15": "Alex Moreno 0"
  },
  {
    "manager_Name": "136( 348,294 )",
    "Teams": "Slika FC( Kyle Gatt )",
    "SXL": "countryCode",
    "Latp": "66",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Haaland 2",
    "Player_10": "Gy\u00F6keres 24",
    "Player_12": "Darlow 0",
    "Player_13": "Pedro Porro 5",
    "Player_14": "Frimpong 0",
    "Player_7": "Reijnders 2",
    "Player_2": "N.Williams 2",
    "Player_5": "Neto 7",
    "Player_6": "Mitoma 2",
    "Player_3": "Gabriel 6",
    "Player_4": "A\u00EFt-Nouri 1",
    "Player_8": "Ndiaye 8",
    "Player_9": "Ekitik\u00E9 9",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "133( 495,800 )",
    "Teams": "Boca Seniors FC( Jake Bonnici )",
    "SXL": "countryCode",
    "Latp": "72",
    "Player_1": "Vicario 9",
    "Player_11": "Beto 0",
    "Player_10": "Jo\u00E3o Pedro 30",
    "Player_12": "Ramsdale 0",
    "Player_13": "Cherki 1",
    "Player_14": "Lewis-Skelly 1",
    "Player_7": "Saka 6",
    "Player_2": "Kerkez 1",
    "Player_5": "M.Salah 5",
    "Player_6": "Rogers 2",
    "Player_3": "Bassey 2",
    "Player_4": "Spence 6",
    "Player_8": "Wharton 2",
    "Player_9": "Ekitik\u00E9 9",
    "Player_15": "Aina 1"
  },
  {
    "manager_Name": "130( 688,267 )",
    "Teams": "TetasSexyReds( Gary Pace )",
    "SXL": "countryCode",
    "Latp": "52",
    "Player_1": "Sels 2",
    "Player_11": "Beto 0",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Palmer 0",
    "Player_14": "Diouf 3",
    "Player_7": "Kudus 3",
    "Player_2": "Gabriel 6",
    "Player_5": "Rice 6",
    "Player_6": "Reijnders 2",
    "Player_3": "Ballard 1",
    "Player_4": "Andersen 4",
    "Player_8": "Wirtz 2",
    "Player_9": "Gy\u00F6keres 24",
    "Player_15": "Pedro Porro 5"
  },
  {
    "manager_Name": "127( 934,865 )",
    "Teams": "Noni your business( Owen Farrugia )",
    "SXL": "countryCode",
    "Latp": "50",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Gy\u00F6keres 12",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Frimpong 0",
    "Player_14": "Marc Guiu 1",
    "Player_7": "Saka 6",
    "Player_2": "Wan-Bissaka 0",
    "Player_5": "Mbeumo 2",
    "Player_6": "Ndiaye 8",
    "Player_3": "Cucurella 5",
    "Player_4": "Pedro Porro 5",
    "Player_8": "Kudus 3",
    "Player_9": "Reijnders 2",
    "Player_15": "Alex Moreno 0"
  },
  {
    "manager_Name": "126( 984,663 )",
    "Teams": "Rice Rice Baby( kaisler Schembri )",
    "SXL": "countryCode",
    "Latp": "52",
    "Player_1": "Verbruggen 1",
    "Player_11": "Haaland 4",
    "Player_10": "Jo\u00E3o Pedro 15",
    "Player_12": "Darlow 0",
    "Player_13": "Palmer 0",
    "Player_14": "Van de Ven 6",
    "Player_7": "Reijnders 2",
    "Player_2": "Cucurella 5",
    "Player_5": "Wirtz 2",
    "Player_6": "Rogers 2",
    "Player_3": "Est\u00E8ve 6",
    "Player_4": "Gabriel 6",
    "Player_8": "Ndiaye 8",
    "Player_9": "Ra\u00FAl 1",
    "Player_15": "Wan-Bissaka 0"
  },
  {
    "manager_Name": "126( 984,663 )",
    "Teams": "Lions( Daniel Ferriggi )",
    "SXL": "countryCode",
    "Latp": "71",
    "Player_1": "Pickford 15",
    "Player_11": "Wood 2",
    "Player_10": "Jo\u00E3o Pedro 15",
    "Player_12": "Kelleher 5",
    "Player_13": "Palmer 0",
    "Player_14": "Wan-Bissaka 0",
    "Player_7": "Wirtz 2",
    "Player_2": "Mu\u00F1oz 5",
    "Player_5": "Milenkovi\u0107 2",
    "Player_6": "M.Salah 10",
    "Player_3": "Tarkowski 8",
    "Player_4": "Murillo 1",
    "Player_8": "Caicedo 8",
    "Player_9": "P.M.Sarr 3",
    "Player_15": "Marc Guiu 1"
  },
  {
    "manager_Name": "125( 1,132,734 )",
    "Teams": "GunnerPorts( Matthew Portelli )",
    "SXL": "countryCode",
    "Latp": "61",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Ekitik\u00E9 9",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Konsa 0",
    "Player_14": "Palmer 0",
    "Player_7": "Dewsbury-Hall 2",
    "Player_2": "De Cuyper 0",
    "Player_5": "M.Salah 10",
    "Player_6": "Gakpo 10",
    "Player_3": "N.Williams 2",
    "Player_4": "Van de Ven 6",
    "Player_8": "Reijnders 2",
    "Player_9": "Jo\u00E3o Pedro 15",
    "Player_15": "Diouf 3"
  },
  {
    "manager_Name": "123( 1,303,815 )",
    "Teams": "InvinciblesCOYG( Clayton Camilleri )",
    "SXL": "countryCode",
    "Latp": "73",
    "Player_1": "Raya 6",
    "Player_11": "Marc Guiu 1",
    "Player_10": "Jo\u00E3o Pedro 30",
    "Player_12": "Kelleher 5",
    "Player_13": "Est\u00E8ve 6",
    "Player_14": "Alex Moreno 0",
    "Player_7": "Xhaka 4",
    "Player_2": "Cucurella 5",
    "Player_5": "M.Salah 5",
    "Player_6": "Wirtz 2",
    "Player_3": "A\u00EFt-Nouri 1",
    "Player_4": "Kerkez 1",
    "Player_8": "Saka 6",
    "Player_9": "Gy\u00F6keres 12",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "123( 1,303,815 )",
    "Teams": "Bend it like Boogie( Ryan Bonello Gatt )",
    "SXL": "countryCode",
    "Latp": "51",
    "Player_1": "Sels 2",
    "Player_11": "Jo\u00E3o Pedro 15",
    "Player_10": "Haaland 4",
    "Player_12": "Kelleher 5",
    "Player_13": "Palmer 0",
    "Player_14": "Marc Guiu 1",
    "Player_7": "Tonali 2",
    "Player_2": "Gabriel 6",
    "Player_5": "Gu\u00E9hi 2",
    "Player_6": "Saka 6",
    "Player_3": "R\u00FAben 1",
    "Player_4": "Aina 1",
    "Player_8": "Reijnders 2",
    "Player_9": "Gakpo 10",
    "Player_15": "Wan-Bissaka 0"
  },
  {
    "manager_Name": "121( 1,551,969 )",
    "Teams": "kurt slika( Kurt Gatt )",
    "SXL": "countryCode",
    "Latp": "51",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 12",
    "Player_10": "Jo\u00E3o Pedro 15",
    "Player_12": "Jos\u00E9 S\u00E1 3",
    "Player_13": "J.Palhinha 11",
    "Player_14": "A.Ramsey 0",
    "Player_7": "Mbeumo 2",
    "Player_2": "Cucurella 5",
    "Player_5": "A\u00EFt-Nouri 1",
    "Player_6": "Wirtz 2",
    "Player_3": "Wan-Bissaka 0",
    "Player_4": "Aina 1",
    "Player_8": "Zubimendi 3",
    "Player_9": "Haaland 4",
    "Player_15": "Frimpong 0"
  },
  {
    "manager_Name": "120( 1,755,577 )",
    "Teams": "Mandra United( Steven Silvio )",
    "SXL": "countryCode",
    "Latp": "64",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro 15",
    "Player_10": "Watkins 2",
    "Player_12": "Lecomte 0",
    "Player_13": "Tonali 2",
    "Player_14": "Konsa 0",
    "Player_7": "Enzo 10",
    "Player_2": "Saliba 6",
    "Player_5": "Cherki 1",
    "Player_6": "M.Salah 10",
    "Player_3": "Murillo 1",
    "Player_4": "Burn 2",
    "Player_8": "Mitoma 2",
    "Player_9": "Ekitik\u00E9 9",
    "Player_15": "Wan-Bissaka 0"
  },
  {
    "manager_Name": "120( 1,755,577 )",
    "Teams": "Gunz( Kurt Zammit )",
    "SXL": "countryCode",
    "Latp": "69",
    "Player_1": "D\u00FAbravka 6",
    "Player_11": "Jo\u00E3o Pedro 30",
    "Player_10": "Ekitik\u00E9 9",
    "Player_12": "Sels 2",
    "Player_13": "Palmer 0",
    "Player_14": "A.Ramsey 0",
    "Player_7": "Xhaka 4",
    "Player_2": "A\u00EFt-Nouri 1",
    "Player_5": "Est\u00E8ve 6",
    "Player_6": "Pedro Porro 5",
    "Player_3": "Aina 1",
    "Player_4": "Wan-Bissaka 0",
    "Player_8": "M.Salah 5",
    "Player_9": "Mbeumo 2",
    "Player_15": "Welbeck 0"
  },
  {
    "manager_Name": "120( 1,755,577 )",
    "Teams": "RZM765( Cedrik Dalli )",
    "SXL": "countryCode",
    "Latp": "40",
    "Player_1": "Verbruggen 1",
    "Player_11": "Watkins 2",
    "Player_10": "Wood 2",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Palmer 0",
    "Player_14": "Rodon 2",
    "Player_7": "Reijnders 2",
    "Player_2": "Van de Ven 6",
    "Player_5": "Rogers 2",
    "Player_6": "Johnson 9",
    "Player_3": "Cucurella 5",
    "Player_4": "Mu\u00F1oz 5",
    "Player_8": "Anderson 2",
    "Player_9": "Haaland 4",
    "Player_15": "Est\u00E8ve 6"
  },
  {
    "manager_Name": "120( 1,755,577 )",
    "Teams": "matthew 14( matthew borg )",
    "SXL": "countryCode",
    "Latp": "42",
    "Player_1": "Pope 4",
    "Player_11": "Richarlison 4",
    "Player_10": "Haaland 4",
    "Player_12": "Foderingham 0",
    "Player_13": "Pedro Lima 0",
    "Player_14": "Konsa 0",
    "Player_7": "Elanga 2",
    "Player_2": "Burn 2",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Hughes 1",
    "Player_3": "Tarkowski 8",
    "Player_4": "Pedro Porro 5",
    "Player_8": "Baleba 1",
    "Player_9": "Ekitik\u00E9 9",
    "Player_15": "Palmer 0"
  },
  {
    "manager_Name": "119( 1,902,632 )",
    "Teams": "Sammygooner****( Sammy Vella )",
    "SXL": "countryCode",
    "Latp": "70",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Gy\u00F6keres 24",
    "Player_10": "Ekitik\u00E9 9",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Palmer 0",
    "Player_14": "De Cuyper 0",
    "Player_7": "Semenyo 6",
    "Player_2": "Dorgu 2",
    "Player_5": "Reijnders 2",
    "Player_6": "Gakpo 10",
    "Player_3": "Van de Ven 6",
    "Player_4": "Wan-Bissaka 0",
    "Player_8": "Saka 6",
    "Player_9": "Watkins 2",
    "Player_15": "Konsa 0"
  },
  {
    "manager_Name": "119( 1,902,632 )",
    "Teams": "Hamrun Gunners( Mark Monseigneur )",
    "SXL": "countryCode",
    "Latp": "62",
    "Player_1": "Pickford 15",
    "Player_11": "Gy\u00F6keres 12",
    "Player_10": "Mateta 2",
    "Player_12": "Henderson 2",
    "Player_13": "Clyne 0",
    "Player_14": "Alex Moreno 0",
    "Player_7": "Onana 1",
    "Player_2": "Toti -2",
    "Player_5": "Gakpo 10",
    "Player_6": "Saka 6",
    "Player_3": "Pedro Porro 5",
    "Player_4": "Virgil 3",
    "Player_8": "Rice 6",
    "Player_9": "Haaland 4",
    "Player_15": "Georginio 0"
  },
  {
    "manager_Name": "118( 1,982,826 )",
    "Teams": "Gozo Gunners( Jonathan Portelli )",
    "SXL": "countryCode",
    "Latp": "56",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Watkins 2",
    "Player_10": "Jo\u00E3o Pedro 15",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Palmer 0",
    "Player_14": "Marc Guiu 1",
    "Player_7": "Reijnders 2",
    "Player_2": "Tarkowski 8",
    "Player_5": "Wan-Bissaka 0",
    "Player_6": "Rogers 2",
    "Player_3": "Gabriel 6",
    "Player_4": "Milenkovi\u0107 2",
    "Player_8": "Rice 6",
    "Player_9": "M.Salah 10",
    "Player_15": "Est\u00E8ve 6"
  },
  {
    "manager_Name": "117( 2,139,896 )",
    "Teams": "Arteta Ball FC( Dylan Camilleri )",
    "SXL": "countryCode",
    "Latp": "76",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Gy\u00F6keres 12",
    "Player_10": "Jo\u00E3o Pedro 15",
    "Player_12": "Sels 2",
    "Player_13": "Palmer 0",
    "Player_14": "Est\u00E8ve 6",
    "Player_7": "Ndiaye 8",
    "Player_2": "Gabriel 6",
    "Player_5": "Saka 12",
    "Player_6": "Kudus 3",
    "Player_3": "Tarkowski 8",
    "Player_4": "Mu\u00F1oz 5",
    "Player_8": "Wirtz 2",
    "Player_9": "Thiago 2",
    "Player_15": "Konsa 0"
  },
  {
    "manager_Name": "115( 2,478,284 )",
    "Teams": "Bench Warmers( kevin dalli )",
    "SXL": "countryCode",
    "Latp": "50",
    "Player_1": "Petrovi\u0107 6",
    "Player_11": "Gy\u00F6keres 12",
    "Player_10": "Haaland 4",
    "Player_12": "Kelleher 5",
    "Player_13": "Palmer 0",
    "Player_14": "Est\u00E8ve 6",
    "Player_7": "Reijnders 2",
    "Player_2": "A\u00EFt-Nouri 1",
    "Player_5": "Semenyo 6",
    "Player_6": "\u00D8degaard 1",
    "Player_3": "Gu\u00E9hi 2",
    "Player_4": "Saliba 6",
    "Player_8": "Sarr 8",
    "Player_9": "Mayenda 2",
    "Player_15": "Gudmundsson -1"
  },
  {
    "manager_Name": "115( 2,563,260 )",
    "Teams": "Eze Come Eze Go( Theo Magro )",
    "SXL": "countryCode",
    "Latp": "69",
    "Player_1": "Petrovi\u0107 6",
    "Player_11": "Jo\u00E3o Pedro 15",
    "Player_10": "Gy\u00F6keres 12",
    "Player_12": "Henderson 2",
    "Player_13": "Van de Ven 6",
    "Player_14": "Onana 1",
    "Player_7": "M.Salah 5",
    "Player_2": "Gabriel 6",
    "Player_5": "Trippier 1",
    "Player_6": "Saka 12",
    "Player_3": "Mu\u00F1oz 5",
    "Player_4": "Kerkez 1",
    "Player_8": "Xhaka 4",
    "Player_9": "Reijnders 2",
    "Player_15": "Delap 2"
  },
  {
    "manager_Name": "114( 2,745,267 )",
    "Teams": "diavoli 11( Paul Micallef )",
    "SXL": "countryCode",
    "Latp": "45",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 4",
    "Player_10": "Gy\u00F6keres 12",
    "Player_12": "Foderingham 0",
    "Player_13": "Frimpong 0",
    "Player_14": "Chirewa 0",
    "Player_7": "Palmer 0",
    "Player_2": "Mings 2",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Reijnders 2",
    "Player_3": "Pedro Porro 5",
    "Player_4": "Chalobah 8",
    "Player_8": "Tonali 2",
    "Player_9": "Wood 2",
    "Player_15": "Mepham 0"
  },
  {
    "manager_Name": "113( 2,933,071 )",
    "Teams": "Senglea Gunners( Daryl Ebejer )",
    "SXL": "countryCode",
    "Latp": "67",
    "Player_1": "Pope 4",
    "Player_11": "Jo\u00E3o Pedro 15",
    "Player_10": "Gy\u00F6keres 12",
    "Player_12": "Moore 0",
    "Player_13": "\u00C1lvarez 0",
    "Player_14": "Tuanzebe 0",
    "Player_7": "Wirtz 2",
    "Player_2": "Virgil 3",
    "Player_5": "Milenkovi\u0107 2",
    "Player_6": "M.Salah 10",
    "Player_3": "Gabriel 6",
    "Player_4": "Lacroix 3",
    "Player_8": "Saka 6",
    "Player_9": "Xhaka 4",
    "Player_15": "Abdullahi 0"
  },
  {
    "manager_Name": "112( 3,032,052 )",
    "Teams": "Lassie fc( Kirsten Tanti )",
    "SXL": "countryCode",
    "Latp": "57",
    "Player_1": "A.Becker 1",
    "Player_11": "Gy\u00F6keres 12",
    "Player_10": "Jo\u00E3o Pedro 15",
    "Player_12": "Benitez 0",
    "Player_13": "Konsa 0",
    "Player_14": "Frimpong 0",
    "Player_7": "Baleba 1",
    "Player_2": "Gabriel 6",
    "Player_5": "Rogers 2",
    "Player_6": "M.Salah 10",
    "Player_3": "Saliba 6",
    "Player_4": "A\u00EFt-Nouri 1",
    "Player_8": "Eze 0",
    "Player_9": "Kudus 3",
    "Player_15": "Y.Chermiti 0"
  },
  {
    "manager_Name": "112( 3,032,052 )",
    "Teams": "Zubi dubi doo( Julia Schembri )",
    "SXL": "countryCode",
    "Latp": "69",
    "Player_1": "Verbruggen 1",
    "Player_11": "Gy\u00F6keres 24",
    "Player_10": "Beto 0",
    "Player_12": "Kelleher 5",
    "Player_13": "Konsa 0",
    "Player_14": "Palmer 0",
    "Player_7": "M.Salah 5",
    "Player_2": "Saliba 6",
    "Player_5": "Van de Ven 6",
    "Player_6": "Saka 6",
    "Player_3": "Wan-Bissaka 0",
    "Player_4": "Gu\u00E9hi 2",
    "Player_8": "Xhaka 4",
    "Player_9": "Jo\u00E3o Pedro 15",
    "Player_15": "Dewsbury-Hall 2"
  },
  {
    "manager_Name": "112( 3,126,374 )",
    "Teams": "Kanokk 118( Rodney Azzopardi )",
    "SXL": "countryCode",
    "Latp": "58",
    "Player_1": "Henderson 2",
    "Player_11": "Bowen 2",
    "Player_10": "Jo\u00E3o Pedro 15",
    "Player_12": "Sels 2",
    "Player_13": "Eze 0",
    "Player_14": "Frimpong 0",
    "Player_7": "Reijnders 2",
    "Player_2": "Cucurella 5",
    "Player_5": "Rice 6",
    "Player_6": "Semenyo 6",
    "Player_3": "A\u00EFt-Nouri 1",
    "Player_4": "Gabriel 6",
    "Player_8": "Saka 12",
    "Player_9": "\u0160e\u0161ko 1",
    "Player_15": "Milenkovi\u0107 2"
  },
  {
    "manager_Name": "111( 3,227,368 )",
    "Teams": "Very Rice( Jake Caruana )",
    "SXL": "countryCode",
    "Latp": "43",
    "Player_1": "Sels 2",
    "Player_11": "Wood 2",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Palmer 0",
    "Player_14": "Kroupi.Jr 1",
    "Player_7": "Reijnders 2",
    "Player_2": "Gabriel 6",
    "Player_5": "Est\u00E8ve 6",
    "Player_6": "Minteh 2",
    "Player_3": "Reinildo 3",
    "Player_4": "Aina 1",
    "Player_8": "M.Salah 5",
    "Player_9": "Saka 12",
    "Player_15": "Van de Ven 6"
  },
  {
    "manager_Name": "110( 3,528,824 )",
    "Teams": "Taggers FC( Karl Caruana )",
    "SXL": "countryCode",
    "Latp": "63",
    "Player_1": "D\u00FAbravka 6",
    "Player_11": "Watkins 2",
    "Player_10": "Jo\u00E3o Pedro 15",
    "Player_12": "Kelleher 5",
    "Player_13": "Konsa 0",
    "Player_14": "Palmer 0",
    "Player_7": "Reijnders 2",
    "Player_2": "Gabriel 6",
    "Player_5": "Ndiaye 8",
    "Player_6": "Saka 12",
    "Player_3": "Van de Ven 6",
    "Player_4": "Wan-Bissaka 0",
    "Player_8": "M.Salah 5",
    "Player_9": "Marc Guiu 1",
    "Player_15": "Est\u00E8ve 6"
  },
  {
    "manager_Name": "109( 3,634,170 )",
    "Teams": "Harambe FC( Glenn Gauci Borda )",
    "SXL": "countryCode",
    "Latp": "51",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Bowen 2",
    "Player_10": "Wood 2",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Konsa 0",
    "Player_14": "Palmer 0",
    "Player_7": "Wirtz 2",
    "Player_2": "Van de Ven 6",
    "Player_5": "Est\u00E8ve 6",
    "Player_6": "M.Salah 10",
    "Player_3": "Reinildo 3",
    "Player_4": "Wan-Bissaka 0",
    "Player_8": "Mbeumo 2",
    "Player_9": "Jo\u00E3o Pedro 15",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "109( 3,734,431 )",
    "Teams": "The Invincibles 49( Clive Caruana )",
    "SXL": "countryCode",
    "Latp": "52",
    "Player_1": "Sels 2",
    "Player_11": "Jo\u00E3o Pedro 15",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Palmer 0",
    "Player_14": "Est\u00E8ve 6",
    "Player_7": "Semenyo 12",
    "Player_2": "De Cuyper 0",
    "Player_5": "Van de Ven 6",
    "Player_6": "M.Salah 5",
    "Player_3": "Virgil 3",
    "Player_4": "N.Williams 2",
    "Player_8": "Reijnders 2",
    "Player_9": "Kudus 3",
    "Player_15": "Marc Guiu 1"
  },
  {
    "manager_Name": "109( 3,734,431 )",
    "Teams": "NLD( Jordi Farrugia )",
    "SXL": "countryCode",
    "Latp": "59",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro 15",
    "Player_10": "\u0160e\u0161ko 1",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Eze 0",
    "Player_14": "Elanga 2",
    "Player_7": "Saka 12",
    "Player_2": "Cucurella 5",
    "Player_5": "James 1",
    "Player_6": "Romero 7",
    "Player_3": "Gabriel 6",
    "Player_4": "Burn 2",
    "Player_8": "Gibbs-White 2",
    "Player_9": "Rogers 2",
    "Player_15": "Evanilson 2"
  },
  {
    "manager_Name": "109( 3,734,431 )",
    "Teams": "Zubi Zubi Zooo( Andrew Brincat Ruffini )",
    "SXL": "countryCode",
    "Latp": "65",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro 15",
    "Player_10": "Gy\u00F6keres 12",
    "Player_12": "Darlow 0",
    "Player_13": "Frimpong 0",
    "Player_14": "Palmer 0",
    "Player_7": "Saka 12",
    "Player_2": "A\u00EFt-Nouri 1",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Elanga 2",
    "Player_3": "Lewis 1",
    "Player_4": "Pedro Porro 5",
    "Player_8": "Ndiaye 8",
    "Player_9": "Marc Guiu 1",
    "Player_15": "Alex Moreno 0"
  },
  {
    "manager_Name": "108( 3,840,714 )",
    "Teams": "Clarky FC( Carl Clark )",
    "SXL": "countryCode",
    "Latp": "47",
    "Player_1": "Leno 3",
    "Player_11": "Haaland 6",
    "Player_10": "Gy\u00F6keres 12",
    "Player_12": "Slonina 0",
    "Player_13": "Eze 0",
    "Player_14": "Bryan 0",
    "Player_7": "Saka 6",
    "Player_2": "Saliba 6",
    "Player_5": "Konat\u00E9 0",
    "Player_6": "Mitchell 1",
    "Player_3": "Murillo 1",
    "Player_4": "Sch\u00E4r 1",
    "Player_8": "Kamara 1",
    "Player_9": "Gakpo 10",
    "Player_15": "Osula 5"
  },
  {
    "manager_Name": "108( 3,954,130 )",
    "Teams": "SC CARBINE( yan cutajar )",
    "SXL": "countryCode",
    "Latp": "44",
    "Player_1": "Raya 6",
    "Player_11": "\u0160e\u0161ko 1",
    "Player_10": "Wood 2",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Konsa 0",
    "Player_14": "Frimpong 0",
    "Player_7": "Cherki 1",
    "Player_2": "Wan-Bissaka 0",
    "Player_5": "Wirtz 2",
    "Player_6": "Kudus 3",
    "Player_3": "Van de Ven 6",
    "Player_4": "A\u00EFt-Nouri 1",
    "Player_8": "M.Salah 10",
    "Player_9": "Gy\u00F6keres 12",
    "Player_15": "Baleba 1"
  },
  {
    "manager_Name": "108( 3,954,130 )",
    "Teams": "MaltArsenal FC( Claude Spiteri )",
    "SXL": "countryCode",
    "Latp": "47",
    "Player_1": "Raya 6",
    "Player_11": "Beto 0",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Palmer 0",
    "Player_14": "Gudmundsson -1",
    "Player_7": "Xhaka 4",
    "Player_2": "Gabriel 6",
    "Player_5": "Kudus 3",
    "Player_6": "Saka 12",
    "Player_3": "Est\u00E8ve 6",
    "Player_4": "R\u00FAben 1",
    "Player_8": "Damsgaard 5",
    "Player_9": "Mateta 2",
    "Player_15": "Van de Ven 6"
  },
  {
    "manager_Name": "108( 3,954,130 )",
    "Teams": "Kind FC( Richard Kind )",
    "SXL": "countryCode",
    "Latp": "41",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 4",
    "Player_10": "Gy\u00F6keres 12",
    "Player_12": "Green 0",
    "Player_13": "Iwobi 7",
    "Player_14": "Muniz 0",
    "Player_7": "Mitoma 2",
    "Player_2": "Lacroix 3",
    "Player_5": "Reinildo 3",
    "Player_6": "Wirtz 2",
    "Player_3": "Murillo 1",
    "Player_4": "Cucurella 5",
    "Player_8": "Marmoush 1",
    "Player_9": "Reijnders 2",
    "Player_15": "Pau 2"
  },
  {
    "manager_Name": "104( 4,706,099 )",
    "Teams": "Ellul FC( Andrew Ellul )",
    "SXL": "countryCode",
    "Latp": "56",
    "Player_1": "Pope 4",
    "Player_11": "\u0160e\u0161ko 1",
    "Player_10": "Gy\u00F6keres 24",
    "Player_12": "Henderson 2",
    "Player_13": "Gvardiol 0",
    "Player_14": "Eze 0",
    "Player_7": "Mbeumo 2",
    "Player_2": "Gu\u00E9hi 2",
    "Player_5": "Sch\u00E4r 1",
    "Player_6": "Rice 6",
    "Player_3": "Gabriel 6",
    "Player_4": "Milenkovi\u0107 2",
    "Player_8": "Mitoma 2",
    "Player_9": "Semenyo 6",
    "Player_15": "Watkins 2"
  },
  {
    "manager_Name": "103( 4,919,019 )",
    "Teams": "Gooner( Isaac McCarthy )",
    "SXL": "countryCode",
    "Latp": "44",
    "Player_1": "Sels 2",
    "Player_11": "Jo\u00E3o Pedro 15",
    "Player_10": "\u0160e\u0161ko 1",
    "Player_12": "Verbruggen 1",
    "Player_13": "Frimpong 0",
    "Player_14": "Palmer 0",
    "Player_7": "Reijnders 2",
    "Player_2": "Aina 1",
    "Player_5": "M.Salah 10",
    "Player_6": "Kudus 3",
    "Player_3": "Cucurella 5",
    "Player_4": "Digne 2",
    "Player_8": "Wirtz 2",
    "Player_9": "Marc Guiu 1",
    "Player_15": "Alex Moreno 0"
  },
  {
    "manager_Name": "101( 5,434,641 )",
    "Teams": "Mihawha( Matthew Paris )",
    "SXL": "countryCode",
    "Latp": "42",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Mateta 2",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Palmer 0",
    "Player_14": "Marc Guiu 1",
    "Player_7": "Anderson 2",
    "Player_2": "De Cuyper 0",
    "Player_5": "Van de Ven 6",
    "Player_6": "Ndiaye 8",
    "Player_3": "Pedro Porro 5",
    "Player_4": "Milenkovi\u0107 2",
    "Player_8": "M.Salah 10",
    "Player_9": "Reijnders 2",
    "Player_15": "Wan-Bissaka 0"
  },
  {
    "manager_Name": "99( 5,742,257 )",
    "Teams": "Dial Square( Liam Carabott )",
    "SXL": "countryCode",
    "Latp": "53",
    "Player_1": "Sels 2",
    "Player_11": "Watkins 4",
    "Player_10": "Jo\u00E3o Pedro 15",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Palmer 0",
    "Player_14": "Marc Guiu 1",
    "Player_7": "Iwobi 7",
    "Player_2": "Aina 1",
    "Player_5": "Van de Ven 6",
    "Player_6": "M.Salah 5",
    "Player_3": "Mu\u00F1oz 5",
    "Player_4": "Virgil 3",
    "Player_8": "Zubimendi 3",
    "Player_9": "Rogers 2",
    "Player_15": "Wan-Bissaka 0"
  },
  {
    "manager_Name": "99( 5,839,522 )",
    "Teams": "F95( Sibin - )",
    "SXL": "countryCode",
    "Latp": "46",
    "Player_1": "Sels 2",
    "Player_11": "Jo\u00E3o Pedro 15",
    "Player_10": "Solanke 1",
    "Player_12": "Kinsky 0",
    "Player_13": "Masuaku 0",
    "Player_14": "Palmer 0",
    "Player_7": "Reijnders 2",
    "Player_2": "Pedro Porro 5",
    "Player_5": "Aina 1",
    "Player_6": "Wirtz 2",
    "Player_3": "Van Hecke 1",
    "Player_4": "Saliba 6",
    "Player_8": "M.Salah 10",
    "Player_9": "Adingra 1",
    "Player_15": "Marc Guiu 1"
  },
  {
    "manager_Name": "98( 5,939,885 )",
    "Teams": "Zubi-Dooby Doo( Malcolm Vella Vidal )",
    "SXL": "countryCode",
    "Latp": "42",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "F\u00FCllkrug 1",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Palmer 0",
    "Player_14": "Diouf 3",
    "Player_7": "Reijnders 2",
    "Player_2": "Richards 2",
    "Player_5": "Est\u00E8ve 6",
    "Player_6": "Rogers 2",
    "Player_3": "Milenkovi\u0107 2",
    "Player_4": "Pedro Porro 5",
    "Player_8": "Saka 12",
    "Player_9": "M.Salah 5",
    "Player_15": "Marc Guiu 1"
  },
  {
    "manager_Name": "96( 6,409,688 )",
    "Teams": "Henry\u2019s Heroes( Jean Azzopardi )",
    "SXL": "countryCode",
    "Latp": "59",
    "Player_1": "Kelleher 5",
    "Player_11": "Gy\u00F6keres 12",
    "Player_10": "Jo\u00E3o Pedro 15",
    "Player_12": "Verbruggen 1",
    "Player_13": "Palmer 0",
    "Player_14": "Est\u00E8ve 6",
    "Player_7": "Mbeumo 2",
    "Player_2": "Virgil 3",
    "Player_5": "De Cuyper 0",
    "Player_6": "Saka 12",
    "Player_3": "R\u00FAben 1",
    "Player_4": "A\u00EFt-Nouri 1",
    "Player_8": "Wirtz 2",
    "Player_9": "Rice 6",
    "Player_15": "Marc Guiu 1"
  },
  {
    "manager_Name": "95( 6,501,807 )",
    "Teams": "Gy\u00F6keres14( Zack Vella )",
    "SXL": "countryCode",
    "Latp": "67",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro 15",
    "Player_10": "Haaland 2",
    "Player_12": "Heaton 0",
    "Player_13": "Acheampong 0",
    "Player_14": "Palmer 0",
    "Player_7": "Wirtz 2",
    "Player_2": "Est\u00E8ve 6",
    "Player_5": "Gudmundsson -1",
    "Player_6": "Saka 6",
    "Player_3": "Cash 2",
    "Player_4": "Reinildo 3",
    "Player_8": "Reijnders 2",
    "Player_9": "Gy\u00F6keres 24",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "95( 6,590,147 )",
    "Teams": "Old Havertz Kai Hard( Andy Bonaci )",
    "SXL": "countryCode",
    "Latp": "47",
    "Player_1": "Sels 2",
    "Player_11": "Watkins 2",
    "Player_10": "Jo\u00E3o Pedro 15",
    "Player_12": "Green 0",
    "Player_13": "Marc Guiu 1",
    "Player_14": "Pedro Porro 5",
    "Player_7": "Reijnders 2",
    "Player_2": "Gabriel 6",
    "Player_5": "Dewsbury-Hall 2",
    "Player_6": "M.Salah 10",
    "Player_3": "De Cuyper 0",
    "Player_4": "Wan-Bissaka 0",
    "Player_8": "Wirtz 2",
    "Player_9": "Rice 6",
    "Player_15": "Konsa 0"
  },
  {
    "manager_Name": "92( 7,012,665 )",
    "Teams": "Select Team Name( Kurt Bonnici )",
    "SXL": "countryCode",
    "Latp": "53",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Watkins 2",
    "Player_10": "Gy\u00F6keres 24",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Palmer 0",
    "Player_14": "Heaven 1",
    "Player_7": "Reijnders 2",
    "Player_2": "Tosin 2",
    "Player_5": "Saka 6",
    "Player_6": "B.Fernandes 2",
    "Player_3": "Gabriel 6",
    "Player_4": "Reinildo 3",
    "Player_8": "Wirtz 2",
    "Player_9": "Ra\u00FAl 1",
    "Player_15": "Wan-Bissaka 0"
  },
  {
    "manager_Name": "91( 7,170,947 )",
    "Teams": "Jack Nigret( Jack Gatt )",
    "SXL": "countryCode",
    "Latp": "44",
    "Player_1": "Raya 6",
    "Player_11": "Wood 2",
    "Player_10": "Welbeck 0",
    "Player_12": "Verbruggen 1",
    "Player_13": "Frimpong 0",
    "Player_14": "Eze 0",
    "Player_7": "Saka 12",
    "Player_2": "Gabriel 6",
    "Player_5": "Mu\u00F1oz 5",
    "Player_6": "Rogers 2",
    "Player_3": "R\u00FAben 1",
    "Player_4": "Van de Ven 6",
    "Player_8": "Adams 2",
    "Player_9": "Bowen 2",
    "Player_15": "Palmer 0"
  },
  {
    "manager_Name": "85( 7,974,800 )",
    "Teams": "Rice Rice Baby( Ian Falzon )",
    "SXL": "countryCode",
    "Latp": "41",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Strand Larsen 2",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 6",
    "Player_13": "Palmer 0",
    "Player_14": "Est\u00E8ve 6",
    "Player_7": "B.Fernandes 2",
    "Player_2": "Pedro Porro 5",
    "Player_5": "Van de Ven 6",
    "Player_6": "M.Salah 10",
    "Player_3": "Murillo 1",
    "Player_4": "Truffert 6",
    "Player_8": "Wirtz 2",
    "Player_9": "Minteh 2",
    "Player_15": "Marc Guiu 1"
  }
];