var s = [
  {
    "manager_Name": "609( 23,972 ) TotalXfr : 5",
    "Teams": "Lorrainesson( Lorraine Busuttil )",
    "SXL": "MT",
    "Latp": "51",
    "Player_1": "Sels\r 11",
    "Player_11": "Haaland\r 4",
    "Player_10": "Delap\r 2",
    "Player_12": "Lumley\r 0",
    "Player_13": "Dibling\r 1",
    "Player_14": "Okoli\r 1",
    "Player_7": "Palmer\r 2",
    "Player_2": "Mykolenko\r 7",
    "Player_5": "Johnson\r 2",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Davis\r 1",
    "Player_8": "M.Salah\r 12",
    "Player_9": "Ra\u00FAl\r 7",
    "Player_15": "A\u00EFt-Nouri\r 1"
  },
  {
    "manager_Name": "590( 99,237 ) TotalXfr : 6",
    "Teams": "The Bees( Tove Ronneb\u00E4ck )",
    "SXL": "MT",
    "Latp": "32",
    "Player_1": "Raya\r 1",
    "Player_11": "Havertz\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Harwood-Bellis\r 0",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Diogo J.\r 1",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "Gvardiol\r 10",
    "Player_8": "Rogers\r 6",
    "Player_9": "Calvert-Lewin\r 2",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "588( 117,110 ) TotalXfr : 8",
    "Teams": "FC Pek( Erik Lindberg )",
    "SXL": "SE",
    "Latp": "44",
    "Player_1": "Henderson\r 3",
    "Player_11": "Solanke\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Turner\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Winks\r 3",
    "Player_7": "M.Salah\r 12",
    "Player_2": "Gvardiol\r 10",
    "Player_5": "Lewis\r 2",
    "Player_6": "Faes\r 1",
    "Player_3": "Robertson\r 2",
    "Player_4": "Gabriel\r 1",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "Rogers\r 6",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "579( 206,676 ) TotalXfr : 8",
    "Teams": "Fantasikonungen( Albin Jonsson )",
    "SXL": "MT",
    "Latp": "38",
    "Player_1": "Flekken\r 4",
    "Player_11": "Delap\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Bergvall\r 0",
    "Player_7": "Palmer\r 2",
    "Player_2": "Calafiori\r 1",
    "Player_5": "Van de Ven\r 1",
    "Player_6": "Kulusevski\r 9",
    "Player_3": "Gvardiol\r 10",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "Calvert-Lewin\r 2",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "578( 219,555 ) TotalXfr : 8",
    "Teams": "ThereWeLand( Haykel Mansour )",
    "SXL": "MT",
    "Latp": "26",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Havertz\r 2",
    "Player_10": "Watkins\r 8",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Konsa\r 0",
    "Player_14": "Ugochukwu\r 0",
    "Player_7": "Saka\r 0",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "McNeil\r 6",
    "Player_3": "Saliba\r -3",
    "Player_4": "Lewis\r 2",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Haaland\r 4",
    "Player_15": "Nedeljkovic\r 0"
  },
  {
    "manager_Name": "572( 303,479 ) TotalXfr : 6",
    "Teams": "Guglielmo( Jonas Megert )",
    "SXL": "SE",
    "Latp": "49",
    "Player_1": "Martinez\r 8",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Haaland\r 4",
    "Player_12": "Turner\r 0",
    "Player_13": "Mainoo\r 0",
    "Player_14": "Quansah\r 0",
    "Player_7": "Johnson\r 2",
    "Player_2": "Lewis\r 2",
    "Player_5": "Palmer\r 2",
    "Player_6": "M.Salah\r 12",
    "Player_3": "Taylor\r 1",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Winks\r 3",
    "Player_9": "Ra\u00FAl\r 7",
    "Player_15": "Konsa\r 0"
  },
  {
    "manager_Name": "563( 499,701 ) TotalXfr : 8",
    "Teams": "NoHopeFC( John Maguire )",
    "SXL": "MT",
    "Latp": "43",
    "Player_1": "Flekken\r 4",
    "Player_11": "Welbeck\r 9",
    "Player_10": "Wood\r 7",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Digne\r 4",
    "Player_14": "Robinson\r 1",
    "Player_7": "Palmer\r 4",
    "Player_2": "Davis\r 1",
    "Player_5": "Barnes\r 1",
    "Player_6": "M.Salah\r 12",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "Harwood-Bellis\r 0",
    "Player_8": "Johnson\r 2",
    "Player_9": "Haaland\r 2",
    "Player_15": "Winks\r 3"
  },
  {
    "manager_Name": "561( 544,545 ) TotalXfr : 7",
    "Teams": "Ctrl Alt De Ligt( Marlon Vella )",
    "SXL": "MT",
    "Latp": "39",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Ra\u00FAl\r 7",
    "Player_10": "Watkins\r 8",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Winks\r 3",
    "Player_7": "Palmer\r 2",
    "Player_2": "Lewis\r 2",
    "Player_5": "Faes\r 1",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Alexander-Arnold\r 2",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Rogers\r 6",
    "Player_9": "Haaland\r 6",
    "Player_15": "Mazraoui\r 1"
  },
  {
    "manager_Name": "559( 599,120 ) TotalXfr : 7",
    "Teams": "MainooInTheBank( Thanasis Fouras )",
    "SXL": "GR",
    "Latp": "35",
    "Player_1": "Henderson\r 3",
    "Player_11": "Solanke\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "Matthews\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Winks\r 3",
    "Player_7": "Gordon\r 2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Faes\r 1",
    "Player_6": "Johnson\r 2",
    "Player_3": "Robinson\r 1",
    "Player_4": "Gvardiol\r 10",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "Haaland\r 4",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "556( 702,744 ) TotalXfr : 9",
    "Teams": "Im Sorry Nic Jackson( Jon Briscoe White )",
    "SXL": "MT",
    "Latp": "37",
    "Player_1": "Henderson\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r 8",
    "Player_12": "Turner\r 0",
    "Player_13": "Rogers\r 6",
    "Player_14": "Vestergaard\r 0",
    "Player_7": "Palmer\r 2",
    "Player_2": "Dalot\r 1",
    "Player_5": "Buonanotte\r 6",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Gabriel\r 1",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "Wood\r 7",
    "Player_15": "Roerslev\r 1"
  },
  {
    "manager_Name": "555( 734,900 ) TotalXfr : 9",
    "Teams": "Salahvation Army( Tom Atkinson )",
    "SXL": "MT",
    "Latp": "47",
    "Player_1": "Pope\r 3",
    "Player_11": "Calvert-Lewin\r 2",
    "Player_10": "Watkins\r 8",
    "Player_12": "Slicker\r 0",
    "Player_13": "Winks\r 3",
    "Player_14": "Konsa\r 0",
    "Player_7": "M.Salah\r 12",
    "Player_2": "Lewis\r 2",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Rogers\r 6",
    "Player_3": "Taylor\r 1",
    "Player_4": "Gabriel\r 1",
    "Player_8": "McNeil\r 6",
    "Player_9": "Haaland\r 4",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "549( 924,282 ) TotalXfr : 5",
    "Teams": "Lallish United( Melwin Holst )",
    "SXL": "SE",
    "Latp": "30",
    "Player_1": "Raya\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "H\u00F8jlund\r 8",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "A\u00EFt-Nouri\r 1",
    "Player_7": "Rogers\r 6",
    "Player_2": "Lewis\r 2",
    "Player_5": "Van den Berg\r 1",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Davis\r 1",
    "Player_8": "Palmer\r 2",
    "Player_9": "Cunha\r 2",
    "Player_15": "Dibling\r 1"
  },
  {
    "manager_Name": "548( 972,020 ) TotalXfr : 7",
    "Teams": "Udogie\u0027s Doggies( Claude Taliana )",
    "SXL": "MT",
    "Latp": "31",
    "Player_1": "Flekken\r 4",
    "Player_11": "Haaland\r 4",
    "Player_10": "Welbeck\r 9",
    "Player_12": "Turner\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Robinson\r 1",
    "Player_7": "Diogo J.\r 1",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Aina\r 6",
    "Player_6": "Gordon\r 2",
    "Player_3": "Saliba\r -3",
    "Player_4": "Lewis\r 2",
    "Player_8": "Palmer\r 2",
    "Player_9": "Delap\r 2",
    "Player_15": "Winks\r 3"
  },
  {
    "manager_Name": "548( 981,320 ) TotalXfr : 8",
    "Teams": "Starship( Olumide Okedusi )",
    "SXL": "EE",
    "Latp": "25",
    "Player_1": "Raya\r 1",
    "Player_11": "Havertz\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Turner\r 0",
    "Player_13": "Adama\r 2",
    "Player_14": "Baleba\r 3",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Burn\r 1",
    "Player_6": "Onana\r 2",
    "Player_3": "Virgil\r 2",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Palmer\r 2",
    "Player_9": "N.Jackson\r 6",
    "Player_15": "Robinson\r 1"
  },
  {
    "manager_Name": "547( 1,012,321 ) TotalXfr : 7",
    "Teams": "BienRayados( Luis Ricardo J\u00E1uregui V )",
    "SXL": "EN",
    "Latp": "36",
    "Player_1": "Onana\r 4",
    "Player_11": "Ra\u00FAl\r 7",
    "Player_10": "M.Salah\r 12",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Akanji\r 0",
    "Player_14": "Duran\r 1",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Virgil\r 2",
    "Player_6": "Palmer\r 2",
    "Player_3": "J.Araujo\r 1",
    "Player_4": "Pau\r 2",
    "Player_8": "Madueke\r 2",
    "Player_9": "Bowen\r 2",
    "Player_15": "Havertz\r 2"
  },
  {
    "manager_Name": "546( 1,047,020 ) TotalXfr : 6",
    "Teams": "JDT Out( Filip Larsson )",
    "SXL": "MT",
    "Latp": "35",
    "Player_1": "Flekken\r 4",
    "Player_11": "Welbeck\r 9",
    "Player_10": "Havertz\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Aina\r 6",
    "Player_7": "Rogers\r 6",
    "Player_2": "Lewis\r 2",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Semenyo\r 2",
    "Player_9": "Haaland\r 4",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "541( 1,283,285 ) TotalXfr : 8",
    "Teams": "klopp notch( Tobias Nocke )",
    "SXL": "SE",
    "Latp": "31",
    "Player_1": "Areola\r -1",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Solanke\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Cresswell\r 0",
    "Player_14": "Saka\r 0",
    "Player_7": "L.Paquet\u00E1\r 1",
    "Player_2": "Van de Ven\r 1",
    "Player_5": "Winks\r 3",
    "Player_6": "M.Salah\r 12",
    "Player_3": "Burn\r 1",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "Haaland\r 4",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "540( 1,319,685 ) TotalXfr : 7",
    "Teams": "Los Blancos( Eamonn Mifsud )",
    "SXL": "MT",
    "Latp": "31",
    "Player_1": "Raya\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "Solanke\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Konsa\r 0",
    "Player_7": "Dibling\r 1",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Semenyo\r 2",
    "Player_6": "Rogers\r 6",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Lewis\r 2",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Watkins\r 8",
    "Player_15": "Van den Berg\r 1"
  },
  {
    "manager_Name": "539( 1,378,470 ) TotalXfr : 8",
    "Teams": "Biancoverde Utd 4.0( Michael Keramas )",
    "SXL": "GR",
    "Latp": "35",
    "Player_1": "Flekken\r 4",
    "Player_11": "Welbeck\r 9",
    "Player_10": "Haaland\r 6",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Armstrong\r 0",
    "Player_7": "Smith Rowe\r 1",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Aina\r 6",
    "Player_6": "Palmer\r 2",
    "Player_3": "A\u00EFt-Nouri\r 1",
    "Player_4": "Robinson\r 1",
    "Player_8": "Johnson\r 2",
    "Player_9": "Mbeumo\r 2",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "532( 1,729,379 ) TotalXfr : 7",
    "Teams": "Gambit( Nicola Frasca )",
    "SXL": "MT",
    "Latp": "33",
    "Player_1": "Pickford\r 6",
    "Player_11": "Haaland\r 4",
    "Player_10": "Ings\r 0",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Greaves\r 0",
    "Player_14": "Saka\r 0",
    "Player_7": "Smith Rowe\r 1",
    "Player_2": "Gvardiol\r 10",
    "Player_5": "Pedro Porro\r 2",
    "Player_6": "Palmer\r 2",
    "Player_3": "Alexander-Arnold\r 2",
    "Player_4": "Martinez\r 2",
    "Player_8": "Diogo J.\r 1",
    "Player_9": "Winks\r 3",
    "Player_15": "Jo\u00E3o Pedro\r 0"
  },
  {
    "manager_Name": "529( 1,883,325 ) TotalXfr : 4",
    "Teams": "Nachos( Melvin Xuereb )",
    "SXL": "MT",
    "Latp": "26",
    "Player_1": "Areola\r -1",
    "Player_11": "Haaland\r 2",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Semenyo\r 2",
    "Player_14": "Estupi\u00F1an\r 1",
    "Player_7": "M.Salah\r 12",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Eze\r 2",
    "Player_6": "Palmer\r 4",
    "Player_3": "Andersen\r -2",
    "Player_4": "Saliba\r -3",
    "Player_8": "Onana\r 2",
    "Player_9": "Ra\u00FAl\r 7",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "529( 1,897,926 ) TotalXfr : 7",
    "Teams": "Joga Bonito( Christophe Peixoto )",
    "SXL": "HU",
    "Latp": "25",
    "Player_1": "Flekken\r 4",
    "Player_11": "Haaland\r 4",
    "Player_10": "Solanke\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Semenyo\r 2",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Faes\r 1",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Gabriel\r 1",
    "Player_8": "Maddison\r 4",
    "Player_9": "Calvert-Lewin\r 2",
    "Player_15": "Colwill\r 1"
  },
  {
    "manager_Name": "528( 1,983,502 ) TotalXfr : 10",
    "Teams": "Ajax CT( Dimitrios Siderakis )",
    "SXL": "MT",
    "Latp": "51",
    "Player_1": "Sels\r 11",
    "Player_11": "Havertz\r 2",
    "Player_10": "Watkins\r 8",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "Welbeck\r 9",
    "Player_14": "Carvalho\r 1",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Van de Ven\r 1",
    "Player_5": "Pedro Porro\r 2",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Mazraoui\r 1",
    "Player_4": "Saliba\r -3",
    "Player_8": "Palmer\r 2",
    "Player_9": "M.Salah\r 24",
    "Player_15": "Martinez\r 2"
  },
  {
    "manager_Name": "527( 2,036,308 ) TotalXfr : 9",
    "Teams": "Gidia KK( Aggelos Flamiatos )",
    "SXL": "GR",
    "Latp": "42",
    "Player_1": "Verbruggen\r 10",
    "Player_11": "Haaland\r 4",
    "Player_10": "Solanke\r 2",
    "Player_12": "Flekken\r 4",
    "Player_13": "Virgil\r 2",
    "Player_14": "Robinson\r 1",
    "Player_7": "McNeil\r 6",
    "Player_2": "Saliba\r -3",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Lewis\r 2",
    "Player_4": "Burn\r 1",
    "Player_8": "Rogers\r 6",
    "Player_9": "M.Salah\r 12",
    "Player_15": "Jo\u00E3o Pedro\r 0"
  },
  {
    "manager_Name": "525( 2,118,763 ) TotalXfr : 5",
    "Teams": "Kinder Mbeumo( Gerson Seguna )",
    "SXL": "MT",
    "Latp": "33",
    "Player_1": "Raya\r 1",
    "Player_11": "Calvert-Lewin\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Konsa\r 0",
    "Player_14": "Jo\u00E3o Pedro\r 0",
    "Player_7": "Eze\r 2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "M.Salah\r 12",
    "Player_3": "Harwood-Bellis\r 0",
    "Player_4": "Robinson\r 1",
    "Player_8": "Rogers\r 6",
    "Player_9": "Mbeumo\r 2",
    "Player_15": "Andersen\r -2"
  },
  {
    "manager_Name": "525( 2,143,879 ) TotalXfr : 8",
    "Teams": "Tourinho FC( Alexis Touris )",
    "SXL": "GR",
    "Latp": "61",
    "Player_1": "Ederson M.\r 2",
    "Player_11": "Isak\r 2",
    "Player_10": "Watkins\r 8",
    "Player_12": "Henderson\r 3",
    "Player_13": "Amad\r 0",
    "Player_14": "Burn\r 1",
    "Player_7": "Bowen\r 2",
    "Player_2": "Dalot\r 1",
    "Player_5": "Luis D\u00EDaz\r 1",
    "Player_6": "M.Salah\r 24",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Gvardiol\r 10",
    "Player_8": "Eze\r 2",
    "Player_9": "Wood\r 7",
    "Player_15": "Andersen\r -2"
  },
  {
    "manager_Name": "524( 2,173,065 ) TotalXfr : 2",
    "Teams": "Notified( Edd Eddie )",
    "SXL": "KE",
    "Latp": "38",
    "Player_1": "A.Becker\r 0",
    "Player_11": "Welbeck\r 9",
    "Player_10": "Havertz\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Christie\r 6",
    "Player_7": "Palmer\r 2",
    "Player_2": "White\r 0",
    "Player_5": "Virgil\r 2",
    "Player_6": "Taylor\r 1",
    "Player_3": "Gvardiol\r 10",
    "Player_4": "Mitchell\r 2",
    "Player_8": "Luis D\u00EDaz\r 2",
    "Player_9": "Watkins\r 8",
    "Player_15": "Kudus\r 4"
  },
  {
    "manager_Name": "524( 2,191,874 ) TotalXfr : 7",
    "Teams": "Blue Core( Avinash Chatlani )",
    "SXL": "MT",
    "Latp": "39",
    "Player_1": "Flekken\r 4",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Delap\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Winks\r 3",
    "Player_14": "Harwood-Bellis\r 0",
    "Player_7": "M.Salah\r 12",
    "Player_2": "Saliba\r -3",
    "Player_5": "Palmer\r 2",
    "Player_6": "Madueke\r 2",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Aina\r 6",
    "Player_8": "Adama\r 2",
    "Player_9": "Haaland\r 4",
    "Player_15": "Vestergaard\r 0"
  },
  {
    "manager_Name": "523( 2,265,410 ) TotalXfr : 8",
    "Teams": "Maniacs( Alvaro Garcia )",
    "SXL": "MT",
    "Latp": "27",
    "Player_1": "Raya\r 1",
    "Player_11": "Welbeck\r 9",
    "Player_10": "Haaland\r 4",
    "Player_12": "A.Becker\r 0",
    "Player_13": "Golding\r 0",
    "Player_14": "Jo\u00E3o Pedro\r 0",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Romero\r 2",
    "Player_5": "Gabriel\r 1",
    "Player_6": "Adama\r 2",
    "Player_3": "Virgil\r 2",
    "Player_4": "Dalot\r 1",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Palmer\r 2",
    "Player_15": "Andersen\r -2"
  },
  {
    "manager_Name": "522( 2,297,144 ) TotalXfr : 3",
    "Teams": "Matteo fc( Matteo Vella )",
    "SXL": "MT",
    "Latp": "27",
    "Player_1": "Raya\r 1",
    "Player_11": "Watkins\r 8",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Barco\r 0",
    "Player_14": "Jo\u00E3o Pedro\r 0",
    "Player_7": "Madueke\r 2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Saka\r 0",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Burn\r 1",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Rogers\r 6",
    "Player_9": "Andreas\r 0",
    "Player_15": "Konsa\r 0"
  },
  {
    "manager_Name": "521( 2,389,670 ) TotalXfr : 8",
    "Teams": "FC Qvantas( Johan Hammarstrom )",
    "SXL": "SE",
    "Latp": "27",
    "Player_1": "Raya\r 1",
    "Player_11": "Watkins\r 8",
    "Player_10": "Haaland\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Winks\r 3",
    "Player_14": "Faes\r 1",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Johnson\r 4",
    "Player_6": "Palmer\r 2",
    "Player_3": "Burn\r 1",
    "Player_4": "Saliba\r -3",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "Welbeck\r 9",
    "Player_15": "Andersen\r -2"
  },
  {
    "manager_Name": "518( 2,553,242 ) TotalXfr : 5",
    "Teams": "Rekegutt United( Eirik Presttun )",
    "SXL": "MT",
    "Latp": "39",
    "Player_1": "Henderson\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "N.Jackson\r 6",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "Mazraoui\r 1",
    "Player_14": "Dibling\r 1",
    "Player_7": "G\u00FCndogan\r 2",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Luis D\u00EDaz\r 1",
    "Player_6": "Palmer\r 2",
    "Player_3": "Gvardiol\r 10",
    "Player_4": "Faes\r 1",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Ra\u00FAl\r 7",
    "Player_15": "Taylor\r 1"
  },
  {
    "manager_Name": "518( 2,553,242 ) TotalXfr : 5",
    "Teams": "St Peters FC( Clayton Borda )",
    "SXL": "MT",
    "Latp": "27",
    "Player_1": "Pope\r 3",
    "Player_11": "Mateta\r 1",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Chiwome\r 0",
    "Player_7": "Kudus\r 4",
    "Player_2": "Burn\r 1",
    "Player_5": "Andersen\r -2",
    "Player_6": "B.Fernandes\r 5",
    "Player_3": "Dunk\r 6",
    "Player_4": "De Ligt\r 2",
    "Player_8": "Palmer\r 2",
    "Player_9": "Smith Rowe\r 1",
    "Player_15": "Kristiansen\r 0"
  },
  {
    "manager_Name": "517( 2,654,463 ) TotalXfr : 9",
    "Teams": "LxFxC( Ervin Rigo )",
    "SXL": "MT",
    "Latp": "37",
    "Player_1": "Pope\r 3",
    "Player_11": "Welbeck\r 9",
    "Player_10": "Solanke\r 2",
    "Player_12": "Jos\u00E9 S\u00E1\r 2",
    "Player_13": "Isak\r 2",
    "Player_14": "Semenyo\r 2",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Justin\r 1",
    "Player_5": "Digne\r 4",
    "Player_6": "Barnes\r 1",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Saliba\r -3",
    "Player_8": "M.Salah\r 12",
    "Player_9": "Palmer\r 4",
    "Player_15": "Virgil\r 2"
  },
  {
    "manager_Name": "516( 2,687,099 ) TotalXfr : 6",
    "Teams": "Crvena Zvezda( Dejan Mrdanov )",
    "SXL": "MT",
    "Latp": "39",
    "Player_1": "Raya\r 1",
    "Player_11": "Duran\r 1",
    "Player_10": "Solanke\r 2",
    "Player_12": "Areola\r -1",
    "Player_13": "Tarkowski\r 6",
    "Player_14": "Colwill\r 1",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Calafiori\r 1",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Eze\r 2",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Gabriel\r 1",
    "Player_8": "M.Salah\r 24",
    "Player_9": "Cunha\r 2",
    "Player_15": "Madueke\r 2"
  },
  {
    "manager_Name": "516( 2,695,397 ) TotalXfr : 7",
    "Teams": "Hakuna Mateta( Jason Evans )",
    "SXL": "MT",
    "Latp": "47",
    "Player_1": "Martinez\r 8",
    "Player_11": "Solanke\r 2",
    "Player_10": "Haaland\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 0",
    "Player_14": "Barco\r 0",
    "Player_7": "Rogers\r 6",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Eze\r 2",
    "Player_6": "Mitoma\r 1",
    "Player_3": "Saliba\r -3",
    "Player_4": "Romero\r 2",
    "Player_8": "M.Salah\r 24",
    "Player_9": "Carvalho\r 1",
    "Player_15": "Thomas\r 0"
  },
  {
    "manager_Name": "514( 2,817,104 ) TotalXfr : 6",
    "Teams": "Rolling Fernander( Adam Ruggier )",
    "SXL": "MT",
    "Latp": "23",
    "Player_1": "Raya\r 1",
    "Player_11": "Haaland\r 2",
    "Player_10": "Solanke\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Harwood-Bellis\r 0",
    "Player_14": "Barco\r 0",
    "Player_7": "Palmer\r 4",
    "Player_2": "Konat\u00E9\r 1",
    "Player_5": "Diogo J.\r 1",
    "Player_6": "Semenyo\r 2",
    "Player_3": "Saliba\r -3",
    "Player_4": "Gabriel\r 1",
    "Player_8": "McNeil\r 6",
    "Player_9": "N.Jackson\r 6",
    "Player_15": "Sangar\u00E9\r 0"
  },
  {
    "manager_Name": "514( 2,825,572 ) TotalXfr : 7",
    "Teams": "Massilia( Daniel Borg )",
    "SXL": "MT",
    "Latp": "47",
    "Player_1": "Martinez\r 8",
    "Player_11": "Haaland\r 4",
    "Player_10": "N.Jackson\r 6",
    "Player_12": "Flekken\r 4",
    "Player_13": "Konsa\r 0",
    "Player_14": "Stephens\r 0",
    "Player_7": "M.Salah\r 12",
    "Player_2": "Saliba\r -3",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Rogers\r 6",
    "Player_3": "Virgil\r 2",
    "Player_4": "Aina\r 6",
    "Player_8": "Semenyo\r 2",
    "Player_9": "Delap\r 2",
    "Player_15": "Smith Rowe\r 1"
  },
  {
    "manager_Name": "512( 2,948,976 ) TotalXfr : 6",
    "Teams": "Red Tigers FC( George Vepkhvadze )",
    "SXL": "GE",
    "Latp": "24",
    "Player_1": "Pope\r 3",
    "Player_11": "Wood\r 7",
    "Player_10": "Havertz\r 2",
    "Player_12": "Arrizabalaga\r 6",
    "Player_13": "Greaves\r 0",
    "Player_14": "Saka\r 0",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Van den Berg\r 1",
    "Player_5": "Semenyo\r 2",
    "Player_6": "S\u00E1vio\r 1",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Gusto\r 1",
    "Player_8": "Sancho\r 1",
    "Player_9": "Haaland\r 4",
    "Player_15": "Kerkez\r 7"
  },
  {
    "manager_Name": "508( 3,222,973 ) TotalXfr : 7",
    "Teams": "Mimz( Emma Zammit )",
    "SXL": "MT",
    "Latp": "30",
    "Player_1": "Pickford\r 6",
    "Player_11": "Duran\r 1",
    "Player_10": "Haaland\r 4",
    "Player_12": "Turner\r 0",
    "Player_13": "Sou\u010Dek\r 1",
    "Player_14": "Faes\r 1",
    "Player_7": "Eze\r 2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Palmer\r 2",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Martinez\r 2",
    "Player_8": "McNeil\r 6",
    "Player_9": "Isak\r 2",
    "Player_15": "Taylor\r 1"
  },
  {
    "manager_Name": "507( 3,302,058 ) TotalXfr : 8",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "IN",
    "Latp": "43",
    "Player_1": "Henderson\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "Havertz\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "J.Timber\r 0",
    "Player_14": "W.Fofana\r 0",
    "Player_7": "M.Salah\r 12",
    "Player_2": "Van de Ven\r 1",
    "Player_5": "Dibling\r 1",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Keane\r 14",
    "Player_4": "Faes\r 1",
    "Player_8": "Johnson\r 2",
    "Player_9": "Palmer\r 2",
    "Player_15": "Wheatley\r 0"
  },
  {
    "manager_Name": "507( 3,312,834 ) TotalXfr : 9",
    "Teams": "\u0106umura\u0161i( Aleksandar Deletic )",
    "SXL": "RS",
    "Latp": "39",
    "Player_1": "Raya\r 1",
    "Player_11": "Welbeck\r 9",
    "Player_10": "Wood\r 7",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "Saka\r 0",
    "Player_14": "Andersen\r -2",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Bailey\r 1",
    "Player_6": "Palmer\r 2",
    "Player_3": "Virgil\r 2",
    "Player_4": "Digne\r 4",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Watkins\r 8",
    "Player_15": "Coufal\r 0"
  },
  {
    "manager_Name": "505( 3,405,024 ) TotalXfr : 3",
    "Teams": "Unseen Academicals( Kurt Bugeja Coster )",
    "SXL": "MT",
    "Latp": "18",
    "Player_1": "Ederson M.\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 0",
    "Player_10": "Haaland\r 4",
    "Player_12": "Areola\r -1",
    "Player_13": "Trippier\r 0",
    "Player_14": "Chilwell\r 0",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Estupi\u00F1an\r 1",
    "Player_5": "Onana\r 2",
    "Player_6": "Eze\r 2",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Wissa\r 1",
    "Player_15": "Saka\r 0"
  },
  {
    "manager_Name": "504( 3,465,292 ) TotalXfr : 0",
    "Teams": "Pierosson( Pietro Ramellini )",
    "SXL": "MT",
    "Latp": "38",
    "Player_1": "Kelleher\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "A.Becker\r 0",
    "Player_13": "Ajer\r 0",
    "Player_14": "Eze\r 2",
    "Player_7": "Luis D\u00EDaz\r 2",
    "Player_2": "Van Hecke\r 1",
    "Player_5": "Justin\r 1",
    "Player_6": "Kudus\r 4",
    "Player_3": "Aina\r 6",
    "Player_4": "Martinez\r 2",
    "Player_8": "Kulusevski\r 9",
    "Player_9": "Bernardo\r 2",
    "Player_15": "Isak\r 2"
  },
  {
    "manager_Name": "504( 3,465,292 ) TotalXfr : 0",
    "Teams": "KAMACIO FC( Francisco Camacho )",
    "SXL": "MT",
    "Latp": "28",
    "Player_1": "Areola\r -1",
    "Player_11": "Watkins\r 8",
    "Player_10": "Havertz\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 0",
    "Player_14": "Hill\r 0",
    "Player_7": "Foden\r 4",
    "Player_2": "Mykolenko\r 7",
    "Player_5": "Taylor\r 1",
    "Player_6": "Palmer\r 4",
    "Player_3": "Saliba\r -3",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Gordon\r 2",
    "Player_9": "Bowen\r 2",
    "Player_15": "Saka\r 0"
  },
  {
    "manager_Name": "504( 3,490,591 ) TotalXfr : 7",
    "Teams": "HUNdorito( Adam Rajki )",
    "SXL": "HU",
    "Latp": "43",
    "Player_1": "Raya\r 1",
    "Player_11": "Ra\u00FAl\r 7",
    "Player_10": "Wood\r 7",
    "Player_12": "Turner\r 0",
    "Player_13": "Nelson\r 1",
    "Player_14": "Winks\r 3",
    "Player_7": "M.Salah\r 12",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Calafiori\r 1",
    "Player_6": "Szoboszlai\r 1",
    "Player_3": "Gvardiol\r 10",
    "Player_4": "Saliba\r -3",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "Haaland\r 4",
    "Player_15": "Taylor\r 1"
  },
  {
    "manager_Name": "503( 3,549,424 ) TotalXfr : 6",
    "Teams": "FC Lokomotiv Sliema( Philip H\u00E5kansson )",
    "SXL": "MT",
    "Latp": "36",
    "Player_1": "Raya\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "Solanke\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 0",
    "Player_14": "Konsa\r 0",
    "Player_7": "Johnson\r 2",
    "Player_2": "Virgil\r 2",
    "Player_5": "M.Salah\r 12",
    "Player_6": "G\u00FCndogan\r 2",
    "Player_3": "Romero\r 2",
    "Player_4": "Faes\r 1",
    "Player_8": "Bowen\r 2",
    "Player_9": "Rogers\r 6",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "501( 3,691,255 ) TotalXfr : 7",
    "Teams": "Nketiah_\u0393\u03B1\u03C1\u03BC\u03C0\u03AE( Dimitris Tselikas )",
    "SXL": "GR",
    "Latp": "42",
    "Player_1": "Flekken\r 4",
    "Player_11": "Haaland\r 4",
    "Player_10": "Solanke\r 2",
    "Player_12": "Areola\r -1",
    "Player_13": "Tavernier\r 3",
    "Player_14": "Digne\r 4",
    "Player_7": "Bernardo\r 2",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "M.Salah\r 12",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Faes\r 1",
    "Player_4": "Robertson\r 2",
    "Player_8": "Garnacho\r 10",
    "Player_9": "Nketiah\r 2",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "496( 4,024,444 ) TotalXfr : 7",
    "Teams": "Bruno Fernax FC( Chris Zammit )",
    "SXL": "MT",
    "Latp": "31",
    "Player_1": "Pope\r 3",
    "Player_11": "Vardy\r 6",
    "Player_10": "Welbeck\r 9",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "Saka\r 0",
    "Player_14": "Onana\r 2",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Lewis\r 2",
    "Player_5": "Livramento\r 2",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Harwood-Bellis\r 0",
    "Player_4": "Van de Ven\r 1",
    "Player_8": "Palmer\r 2",
    "Player_9": "Haaland\r 4",
    "Player_15": "Mazraoui\r 1"
  },
  {
    "manager_Name": "496( 4,050,840 ) TotalXfr : 10",
    "Teams": "kabana( Sebastian Agius )",
    "SXL": "MT",
    "Latp": "32",
    "Player_1": "Raya\r 1",
    "Player_11": "Welbeck\r 9",
    "Player_10": "Watkins\r 8",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Robinson\r 1",
    "Player_14": "Pedro Porro\r 2",
    "Player_7": "Smith Rowe\r 1",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Palmer\r 2",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Saliba\r -3",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Rogers\r 6",
    "Player_9": "Haaland\r 4",
    "Player_15": "Ugochukwu\r 0"
  }
];