var s = [
  {
    "manager_Name": "580( 194,355 ) TotalXfr : 8",
    "Teams": "BLIND at the BACK( Prayash Thapa )",
    "SXL": "IN",
    "Latp": "31",
    "Player_1": "Flekken\r 4",
    "Player_11": "Havertz\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Dunk\r 6",
    "Player_7": "Smith Rowe\r 1",
    "Player_2": "Faes\r 1",
    "Player_5": "Rogers\r 6",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Robinson\r 1",
    "Player_4": "Milenkovi\u0107\r 6",
    "Player_8": "Palmer\r 2",
    "Player_9": "Solanke\r 2",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "563( 499,701 ) TotalXfr : 8",
    "Teams": "Avijit@afc( AVIJIT DAS )",
    "SXL": "IN",
    "Latp": "35",
    "Player_1": "Pickford\r 6",
    "Player_11": "Solanke\r 2",
    "Player_10": "Wood\r 7",
    "Player_12": "Matthews\r 0",
    "Player_13": "Rogers\r 6",
    "Player_14": "Robinson\r 1",
    "Player_7": "M.Salah\r 12",
    "Player_2": "Van de Ven\r 1",
    "Player_5": "Diogo J.\r 1",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Saliba\r -3",
    "Player_4": "Lewis\r 2",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "Haaland\r 4",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "555( 715,226 ) TotalXfr : 6",
    "Teams": "Blue Brigade( Bhuman Basnet )",
    "SXL": "IN",
    "Latp": "45",
    "Player_1": "Flekken\r 4",
    "Player_11": "Haaland\r 4",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Greaves\r 0",
    "Player_14": "Keane\r 14",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Lewis\r 2",
    "Player_5": "M.Salah\r 12",
    "Player_6": "Johnson\r 2",
    "Player_3": "Aina\r 6",
    "Player_4": "Gabriel\r 1",
    "Player_8": "Rogers\r 6",
    "Player_9": "Foden\r 4",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "555( 727,912 ) TotalXfr : 8",
    "Teams": "The Regista.( Passang T Sherpa )",
    "SXL": "IN",
    "Latp": "32",
    "Player_1": "Pope\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "Wood\r 7",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Welbeck\r 9",
    "Player_14": "Digne\r 4",
    "Player_7": "Palmer\r 2",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Van de Ven\r 1",
    "Player_4": "Aina\r 6",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "Maddison\r 4",
    "Player_15": "Bednarek\r 1"
  },
  {
    "manager_Name": "554( 752,833 ) TotalXfr : 7",
    "Teams": "Mawat( Arwat Lyngdoh )",
    "SXL": "IN",
    "Latp": "36",
    "Player_1": "Henderson\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "Watkins\r 8",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "Welbeck\r 9",
    "Player_14": "Murillo\r 8",
    "Player_7": "Rogers\r 6",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Luis D\u00EDaz\r 1",
    "Player_6": "Palmer\r 2",
    "Player_3": "Burn\r 1",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "McNeil\r 6",
    "Player_9": "Smith Rowe\r 1",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "551( 852,320 ) TotalXfr : 6",
    "Teams": "PR11( pranam rai )",
    "SXL": "IN",
    "Latp": "37",
    "Player_1": "Raya\r 1",
    "Player_11": "Vardy\r 6",
    "Player_10": "N.Jackson\r 6",
    "Player_12": "Areola\r -1",
    "Player_13": "Rogers\r 6",
    "Player_14": "Van de Ven\r 1",
    "Player_7": "McNeil\r 6",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Lewis\r 2",
    "Player_6": "Martinelli\r 1",
    "Player_3": "Gvardiol\r 10",
    "Player_4": "Saliba\r -3",
    "Player_8": "Palmer\r 2",
    "Player_9": "Haaland\r 4",
    "Player_15": "Smith Rowe\r 1"
  },
  {
    "manager_Name": "551( 877,803 ) TotalXfr : 10",
    "Teams": "Bottled FC( Rishi Thulung )",
    "SXL": "IN",
    "Latp": "49",
    "Player_1": "Raya\r 1",
    "Player_11": "Solanke\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Henderson\r 3",
    "Player_13": "Saka\r 0",
    "Player_14": "Virgil\r 2",
    "Player_7": "Rogers\r 6",
    "Player_2": "Van de Ven\r 1",
    "Player_5": "Madueke\r 2",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Keane\r 14",
    "Player_4": "Gvardiol\r 10",
    "Player_8": "Luis D\u00EDaz\r 1",
    "Player_9": "Wood\r 7",
    "Player_15": "Konsa\r 0"
  },
  {
    "manager_Name": "548( 981,320 ) TotalXfr : 8",
    "Teams": "nativ fc( Monlom Rongong )",
    "SXL": "IN",
    "Latp": "38",
    "Player_1": "Henderson\r 3",
    "Player_11": "Wood\r 7",
    "Player_10": "Delap\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Nedeljkovic\r 0",
    "Player_7": "Palmer\r 2",
    "Player_2": "Gvardiol\r 10",
    "Player_5": "Harwood-Bellis\r 0",
    "Player_6": "McNeil\r 6",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Konat\u00E9\r 1",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Haaland\r 4",
    "Player_15": "Winks\r 3"
  },
  {
    "manager_Name": "543( 1,182,051 ) TotalXfr : 7",
    "Teams": "heregoesnothing11!!( Ashish Rai )",
    "SXL": "IN",
    "Latp": "39",
    "Player_1": "Raya\r 1",
    "Player_11": "Havertz\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Taylor\r 1",
    "Player_14": "Barco\r 0",
    "Player_7": "McNeil\r 6",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Rogers\r 6",
    "Player_6": "M.Salah\r 12",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Robertson\r 2",
    "Player_8": "Madueke\r 2",
    "Player_9": "Mitoma\r 1",
    "Player_15": "O\u2019Mahony\r 0"
  },
  {
    "manager_Name": "543( 1,182,051 ) TotalXfr : 7",
    "Teams": "FC ASSASSINS( Kushal Sahota )",
    "SXL": "IN",
    "Latp": "39",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Keane\r 14",
    "Player_14": "Faes\r 1",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Romero\r 2",
    "Player_5": "Adama\r 2",
    "Player_6": "Palmer\r 2",
    "Player_3": "Virgil\r 2",
    "Player_4": "Lewis\r 2",
    "Player_8": "M.Salah\r 12",
    "Player_9": "Ra\u00FAl\r 7",
    "Player_15": "Iroegbunam\r 0"
  },
  {
    "manager_Name": "541( 1,272,749 ) TotalXfr : 7",
    "Teams": "Imperial Blues FC( Saurabh Tamang )",
    "SXL": "IN",
    "Latp": "34",
    "Player_1": "Raya\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "Solanke\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Van den Berg\r 1",
    "Player_7": "Johnson\r 2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Rogers\r 6",
    "Player_6": "McNeil\r 6",
    "Player_3": "Faes\r 1",
    "Player_4": "Gabriel\r 1",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Wood\r 7",
    "Player_15": "Colwill\r 1"
  },
  {
    "manager_Name": "541( 1,301,173 ) TotalXfr : 12",
    "Teams": "KungFuPandoos( Indrajeet Singh )",
    "SXL": "IN",
    "Latp": "71",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Watkins\r 8",
    "Player_10": "Vardy\r 6",
    "Player_12": "Turner\r 0",
    "Player_13": "N.Jackson\r 6",
    "Player_14": "Konat\u00E9\r 1",
    "Player_7": "M.Salah\r 24",
    "Player_2": "Romero\r 2",
    "Player_5": "Martinez\r 2",
    "Player_6": "McNeil\r 6",
    "Player_3": "Dalot\r 1",
    "Player_4": "Gvardiol\r 10",
    "Player_8": "Son\r 8",
    "Player_9": "Palmer\r 2",
    "Player_15": "Winks\r 3"
  },
  {
    "manager_Name": "539( 1,392,654 ) TotalXfr : 10",
    "Teams": "Last Season\u0027s Loser( \u00CFaraplang Pompyrthat )",
    "SXL": "IN",
    "Latp": "51",
    "Player_1": "Henderson\r 3",
    "Player_11": "Vardy\r 6",
    "Player_10": "Haaland\r 4",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Andersen\r -2",
    "Player_7": "Johnson\r 2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Justin\r 1",
    "Player_6": "M.Salah\r 12",
    "Player_3": "Lewis\r 2",
    "Player_4": "Mykolenko\r 7",
    "Player_8": "Rogers\r 6",
    "Player_9": "McNeil\r 6",
    "Player_15": "Cannon\r 0"
  },
  {
    "manager_Name": "538( 1,437,419 ) TotalXfr : 9",
    "Teams": "Blue Moon X1\uFFFD( PRAYAS BAJGAI )",
    "SXL": "IN",
    "Latp": "31",
    "Player_1": "Raya\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Stewart\r 0",
    "Player_14": "Johnson\r 0",
    "Player_7": "Foden\r 4",
    "Player_2": "Mykolenko\r 7",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Palmer\r 2",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Lewis\r 2",
    "Player_8": "Saka\r 0",
    "Player_9": "Rogers\r 6",
    "Player_15": "Nedeljkovic\r 0"
  },
  {
    "manager_Name": "538( 1,437,419 ) TotalXfr : 9",
    "Teams": "ZilchExpectationsXI( Dipen Thapa )",
    "SXL": "IN",
    "Latp": "28",
    "Player_1": "Raya\r 1",
    "Player_11": "Wood\r 7",
    "Player_10": "Havertz\r 2",
    "Player_12": "Flekken\r 4",
    "Player_13": "Konsa\r 0",
    "Player_14": "Saka\r 0",
    "Player_7": "Winks\r 3",
    "Player_2": "Burn\r 1",
    "Player_5": "Palmer\r 2",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Mazraoui\r 1",
    "Player_4": "Harwood-Bellis\r 0",
    "Player_8": "McNeil\r 6",
    "Player_9": "Haaland\r 4",
    "Player_15": "Aina\r 6"
  },
  {
    "manager_Name": "530( 1,841,171 ) TotalXfr : 7",
    "Teams": "Busby Baby( Regean Lama )",
    "SXL": "IN",
    "Latp": "49",
    "Player_1": "Henderson\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "Vardy\r 6",
    "Player_12": "Turner\r 0",
    "Player_13": "Rogers\r 6",
    "Player_14": "Smith Rowe\r 1",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Gvardiol\r 10",
    "Player_6": "Madueke\r 2",
    "Player_3": "Colwill\r 1",
    "Player_4": "Lewis\r 2",
    "Player_8": "M.Salah\r 12",
    "Player_9": "N.Jackson\r 6",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "526( 2,084,276 ) TotalXfr : 8",
    "Teams": "FALSE 9( Rohan Rai )",
    "SXL": "IN",
    "Latp": "34",
    "Player_1": "Henderson\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "Solanke\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Digne\r 4",
    "Player_7": "Eze\r 2",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Smith Rowe\r 1",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Gvardiol\r 10",
    "Player_4": "Robinson\r 1",
    "Player_8": "Rogers\r 6",
    "Player_9": "Calvert-Lewin\r 2",
    "Player_15": "Keane\r 14"
  },
  {
    "manager_Name": "525( 2,123,319 ) TotalXfr : 6",
    "Teams": "Mersali( Bishal Rai )",
    "SXL": "IN",
    "Latp": "46",
    "Player_1": "Raya\r 1",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Watkins\r 8",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Smith Rowe\r 1",
    "Player_14": "Chiwome\r 0",
    "Player_7": "Madueke\r 2",
    "Player_2": "Saliba\r -3",
    "Player_5": "Lewis\r 2",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "Gabriel\r 1",
    "Player_8": "M.Salah\r 24",
    "Player_9": "Palmer\r 2",
    "Player_15": "Taylor\r 1"
  },
  {
    "manager_Name": "522( 2,299,032 ) TotalXfr : 4",
    "Teams": "Jatin( Jatin Ghimiray )",
    "SXL": "IN",
    "Latp": "35",
    "Player_1": "Raya\r 1",
    "Player_11": "Vardy\r 6",
    "Player_10": "Haaland\r 4",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Konsa\r 0",
    "Player_14": "Saka\r 0",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Van den Berg\r 1",
    "Player_6": "M.Salah\r 12",
    "Player_3": "Konat\u00E9\r 1",
    "Player_4": "Gabriel\r 1",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "Rogers\r 6",
    "Player_15": "Jebbison\r 0"
  },
  {
    "manager_Name": "521( 2,389,670 ) TotalXfr : 8",
    "Teams": "FOMO7 FC( Chaje Lokam )",
    "SXL": "IN",
    "Latp": "46",
    "Player_1": "Martinez\r 8",
    "Player_11": "Haaland\r 4",
    "Player_10": "Welbeck\r 9",
    "Player_12": "Turner\r 0",
    "Player_13": "Faes\r 1",
    "Player_14": "Keane\r 14",
    "Player_7": "Diogo J.\r 1",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Rogers\r 6",
    "Player_6": "B.Fernandes\r 5",
    "Player_3": "Saliba\r -3",
    "Player_4": "Gvardiol\r 10",
    "Player_8": "Palmer\r 2",
    "Player_9": "Havertz\r 2",
    "Player_15": "Winks\r 3"
  },
  {
    "manager_Name": "520( 2,439,487 ) TotalXfr : 7",
    "Teams": "\u2694\uFE0FFURY\u2694\uFE0F( Ashim Lama )",
    "SXL": "IN",
    "Latp": "39",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Havertz\r 2",
    "Player_12": "Flekken\r 4",
    "Player_13": "Davis\r 1",
    "Player_14": "Amad\r 0",
    "Player_7": "Smith Rowe\r 1",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Semenyo\r 2",
    "Player_6": "Rogers\r 6",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Gvardiol\r 10",
    "Player_8": "Maddison\r 4",
    "Player_9": "N.Jackson\r 6",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "520( 2,476,296 ) TotalXfr : 13",
    "Teams": "Comet FC( Pranesh Sharma )",
    "SXL": "IN",
    "Latp": "33",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Welbeck\r 9",
    "Player_10": "Haaland\r 4",
    "Player_12": "Henderson\r 3",
    "Player_13": "Cresswell\r 0",
    "Player_14": "Saka\r 0",
    "Player_7": "Bowen\r 2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Taylor\r 1",
    "Player_6": "Gordon\r 2",
    "Player_3": "Robinson\r 1",
    "Player_4": "Digne\r 4",
    "Player_8": "Maddison\r 4",
    "Player_9": "Mbeumo\r 2",
    "Player_15": "Al-Hamadi\r 0"
  },
  {
    "manager_Name": "517( 2,622,483 ) TotalXfr : 6",
    "Teams": "\uFFFD Fields FC( Ravish Verma )",
    "SXL": "CA",
    "Latp": "30",
    "Player_1": "Flekken\r 4",
    "Player_11": "Watkins\r 8",
    "Player_10": "Solanke\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "O\u0027Shea\r 1",
    "Player_7": "Eze\r 2",
    "Player_2": "Lewis\r 2",
    "Player_5": "Semenyo\r 2",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Robertson\r 2",
    "Player_4": "Gabriel\r 1",
    "Player_8": "Dibling\r 1",
    "Player_9": "Haaland\r 4",
    "Player_15": "Van den Berg\r 1"
  },
  {
    "manager_Name": "511( 3,023,391 ) TotalXfr : 7",
    "Teams": "The SAFfron Sword( Milan Singh )",
    "SXL": "IN",
    "Latp": "33",
    "Player_1": "Flekken\r 4",
    "Player_11": "Calvert-Lewin\r 2",
    "Player_10": "Solanke\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Semenyo\r 2",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Mykolenko\r 7",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Lewis\r 2",
    "Player_4": "Gabriel\r 1",
    "Player_8": "Rogers\r 6",
    "Player_9": "Haaland\r 4",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "508( 3,222,973 ) TotalXfr : 7",
    "Teams": "GustavousGooner( Ashish Subba )",
    "SXL": "IN",
    "Latp": "43",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Vardy\r 6",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Greaves\r 0",
    "Player_7": "M.Salah\r 12",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Robinson\r 1",
    "Player_6": "McNeil\r 6",
    "Player_3": "Justin\r 1",
    "Player_4": "Aina\r 6",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Luis D\u00EDaz\r 1",
    "Player_15": "Wheatley\r 0"
  },
  {
    "manager_Name": "507( 3,302,058 ) TotalXfr : 8",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "IN",
    "Latp": "43",
    "Player_1": "Henderson\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "Havertz\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "J.Timber\r 0",
    "Player_14": "W.Fofana\r 0",
    "Player_7": "M.Salah\r 12",
    "Player_2": "Van de Ven\r 1",
    "Player_5": "Dibling\r 1",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Keane\r 14",
    "Player_4": "Faes\r 1",
    "Player_8": "Johnson\r 2",
    "Player_9": "Palmer\r 2",
    "Player_15": "Wheatley\r 0"
  },
  {
    "manager_Name": "506( 3,348,670 ) TotalXfr : 6",
    "Teams": "Error404( Duri Tadu )",
    "SXL": "IN",
    "Latp": "20",
    "Player_1": "Raya\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Semenyo\r 2",
    "Player_7": "Mavididi\r 2",
    "Player_2": "Lewis\r 2",
    "Player_5": "Robinson\r 1",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Virgil\r 2",
    "Player_4": "Gabriel\r 1",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Solanke\r 2",
    "Player_15": "Faes\r 1"
  },
  {
    "manager_Name": "506( 3,348,670 ) TotalXfr : 6",
    "Teams": "Dany11( Avinash DAniel Khawas )",
    "SXL": "IN",
    "Latp": "45",
    "Player_1": "Onana\r 2",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Haaland\r 4",
    "Player_12": "Turner\r 0",
    "Player_13": "Barco\r 0",
    "Player_14": "Mazraoui\r 1",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Konat\u00E9\r 1",
    "Player_5": "M.Salah\r 12",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Faes\r 1",
    "Player_4": "Gabriel\r 1",
    "Player_8": "McNeil\r 6",
    "Player_9": "Welbeck\r 9",
    "Player_15": "Mario Jr.\r 2"
  },
  {
    "manager_Name": "506( 3,357,015 ) TotalXfr : 7",
    "Teams": "Fu\u00DFball-Mannschaft( Gaurav Shrestha )",
    "SXL": "IN",
    "Latp": "28",
    "Player_1": "Flekken\r 4",
    "Player_11": "Solanke\r 2",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Mykolenko\r 7",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Semenyo\r 2",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Lewis\r 2",
    "Player_8": "Rogers\r 6",
    "Player_9": "Haaland\r 4",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "505( 3,424,062 ) TotalXfr : 7",
    "Teams": "100 Yard Line Lords( Abhinay Pradhan )",
    "SXL": "IN",
    "Latp": "36",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Antonio\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Turner\r 0",
    "Player_13": "Winks\r 3",
    "Player_14": "S\u00E1vio\r 1",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Romero\r 2",
    "Player_5": "Andersen\r -2",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Alexander-Arnold\r 2",
    "Player_4": "De Ligt\r 2",
    "Player_8": "M.Salah\r 12",
    "Player_9": "Welbeck\r 9",
    "Player_15": "Mykolenko\r 7"
  },
  {
    "manager_Name": "503( 3,557,632 ) TotalXfr : 7",
    "Teams": "Darjeeling City( Ruben Pradhan )",
    "SXL": "IN",
    "Latp": "42",
    "Player_1": "Pope\r 3",
    "Player_11": "Haaland\r 4",
    "Player_10": "Wood\r 7",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "Bednarek\r 1",
    "Player_14": "Veltman\r 7",
    "Player_7": "Eze\r 2",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Bernardo\r 2",
    "Player_6": "McNeil\r 6",
    "Player_3": "Burn\r 1",
    "Player_4": "Romero\r 2",
    "Player_8": "M.Salah\r 12",
    "Player_9": "Calvert-Lewin\r 2",
    "Player_15": "Diogo J.\r 1"
  },
  {
    "manager_Name": "499( 3,856,375 ) TotalXfr : 11",
    "Teams": "Busby Babes( Pema Lepcha )",
    "SXL": "IN",
    "Latp": "34",
    "Player_1": "Raya\r 1",
    "Player_11": "Haaland\r 4",
    "Player_10": "Wood\r 7",
    "Player_12": "Muric\r 3",
    "Player_13": "Alexander-Arnold\r 2",
    "Player_14": "Faes\r 1",
    "Player_7": "Rogers\r 6",
    "Player_2": "Gabriel\r 1",
    "Player_5": "Dibling\r 1",
    "Player_6": "McNeil\r 6",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Lewis\r 2",
    "Player_8": "Palmer\r 2",
    "Player_9": "Calvert-Lewin\r 2",
    "Player_15": "Semenyo\r 2"
  },
  {
    "manager_Name": "495( 4,116,636 ) TotalXfr : 10",
    "Teams": "YFC Jb( Vivek Lama )",
    "SXL": "IN",
    "Latp": "38",
    "Player_1": "Vicario\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Welbeck\r 9",
    "Player_12": "S\u00E1nchez\r 2",
    "Player_13": "Sou\u010Dek\r 1",
    "Player_14": "Andersen\r -2",
    "Player_7": "M.Salah\r 12",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Robinson\r 1",
    "Player_6": "Johnson\r 2",
    "Player_3": "Dalot\r 1",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Smith Rowe\r 1",
    "Player_9": "Havertz\r 2",
    "Player_15": "Winks\r 3"
  },
  {
    "manager_Name": "493( 4,233,388 ) TotalXfr : 8",
    "Teams": "Hooligans \u00B0\u00B024( Pradhyumna Subba )",
    "SXL": "IN",
    "Latp": "34",
    "Player_1": "S\u00E1nchez\r 2",
    "Player_11": "Solanke\r 2",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Konsa\r 0",
    "Player_14": "Saka\r 0",
    "Player_7": "Rogers\r 6",
    "Player_2": "Aina\r 6",
    "Player_5": "Van den Berg\r 1",
    "Player_6": "Maddison\r 4",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Foden\r 4",
    "Player_9": "Haaland\r 4",
    "Player_15": "Dibling\r 1"
  },
  {
    "manager_Name": "490( 4,411,455 ) TotalXfr : 6",
    "Teams": "PINE( SATYAM RAI )",
    "SXL": "IN",
    "Latp": "28",
    "Player_1": "Flekken\r 4",
    "Player_11": "Solanke\r 2",
    "Player_10": "Calvert-Lewin\r 2",
    "Player_12": "Lis\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Mykolenko\r 7",
    "Player_7": "Rogers\r 6",
    "Player_2": "Lewis\r 2",
    "Player_5": "Semenyo\r 2",
    "Player_6": "Luis D\u00EDaz\r 1",
    "Player_3": "Gabriel\r 1",
    "Player_4": "Alexander-Arnold\r 2",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Haaland\r 4",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "488( 4,527,516 ) TotalXfr : 2",
    "Teams": "Renga FC( William Serto )",
    "SXL": "IN",
    "Latp": "53",
    "Player_1": "Flekken\r 4",
    "Player_11": "Haaland\r 4",
    "Player_10": "N.Jackson\r 6",
    "Player_12": "A.Becker\r 0",
    "Player_13": "Faes\r 1",
    "Player_14": "Semenyo\r 2",
    "Player_7": "M.Salah\r 12",
    "Player_2": "Alexander-Arnold\r 2",
    "Player_5": "Gvardiol\r 10",
    "Player_6": "Adama\r 2",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Robinson\r 1",
    "Player_8": "Tielemans\r 8",
    "Player_9": "Onana\r 2",
    "Player_15": "Jo\u00E3o Pedro\r 0"
  },
  {
    "manager_Name": "485( 4,776,367 ) TotalXfr : 20",
    "Teams": "GUNNERS( Omkar Subba )",
    "SXL": "IN",
    "Latp": "65",
    "Player_1": "Onana\r 2",
    "Player_11": "Welbeck\r 9",
    "Player_10": "N.Jackson\r 6",
    "Player_12": "Raya\r 1",
    "Player_13": "Saka\r 0",
    "Player_14": "Madueke\r 2",
    "Player_7": "Palmer\r 4",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Keane\r 14",
    "Player_6": "M.Salah\r 12",
    "Player_3": "Virgil\r 2",
    "Player_4": "Robinson\r 1",
    "Player_8": "McNeil\r 6",
    "Player_9": "Ra\u00FAl\r 7",
    "Player_15": "Mazraoui\r 1"
  },
  {
    "manager_Name": "445( 6,917,426 ) TotalXfr : 12",
    "Teams": "HEROES11( Obed Hang Subba )",
    "SXL": "IN",
    "Latp": "34",
    "Player_1": "Pope\r 3",
    "Player_11": "Watkins\r 8",
    "Player_10": "N.Jackson\r 6",
    "Player_12": "Bentley\r 0",
    "Player_13": "Saka\r 0",
    "Player_14": "Holgate\r 0",
    "Player_7": "Luis D\u00EDaz\r 1",
    "Player_2": "Dalot\r 1",
    "Player_5": "Emerson\r 0",
    "Player_6": "Palmer\r 2",
    "Player_3": "Mazraoui\r 1",
    "Player_4": "Robertson\r 2",
    "Player_8": "McNeil\r 6",
    "Player_9": "Havertz\r 4",
    "Player_15": "Nwaneri\r 1"
  }
];