var s = [
  {
    "manager_Name": "1,867( 68,424 ) TotalXfr : 31",
    "Teams": "Jelly Flood( Lorin Minxhozi )",
    "SXL": "countryCode",
    "Latp": "107",
    "Player_1": "Verbruggen 6",
    "Player_11": "Isak 13",
    "Player_10": "Cunha 9",
    "Player_12": "Glasner 20",
    "Player_13": "Fabianski 0",
    "Player_14": "Rogers 2",
    "Player_7": "M.Salah 28",
    "Player_2": "Robinson 1",
    "Player_5": "Gordon 2",
    "Player_6": "Mbeumo 14",
    "Player_3": "Kerkez 1",
    "Player_4": "Alexander-Arnold 6",
    "Player_8": "Palmer 2",
    "Player_9": "Wood 5",
    "Player_15": "Mykolenko 1"
  },
  {
    "manager_Name": "1,767( 706,121 ) TotalXfr : 25",
    "Teams": "#SorareMarin( Marin Jano )",
    "SXL": "countryCode",
    "Latp": "78",
    "Player_1": "Flekken 7",
    "Player_11": "Isak 13",
    "Player_10": "Kluivert 2",
    "Player_12": "Emery 8",
    "Player_13": "Sels 0",
    "Player_14": "Hall 9",
    "Player_7": "M.Salah 28",
    "Player_2": "Gu\u00E9hi 5",
    "Player_5": "Gabriel 2",
    "Player_6": "Tielemans 2",
    "Player_3": "Kerkez 1",
    "Player_4": "Alexander-Arnold 6",
    "Player_8": "Palmer 2",
    "Player_9": "Rogers 2",
    "Player_15": "Gakpo 1"
  },
  {
    "manager_Name": "1,868( 65,697 ) TotalXfr : 27",
    "Teams": "Humbesi( ~ Kopi ~ )",
    "SXL": "countryCode",
    "Latp": "77",
    "Player_1": "Pickford 1",
    "Player_11": "Wood 5",
    "Player_10": "Isak 13",
    "Player_12": "Fabianski 0",
    "Player_13": "Gakpo 1",
    "Player_14": "Castagne 1",
    "Player_7": "Kluivert 2",
    "Player_2": "Alexander-Arnold 6",
    "Player_5": "M.Salah 14",
    "Player_6": "Mbeumo 28",
    "Player_3": "Huijsen 2",
    "Player_4": "Gabriel 2",
    "Player_8": "Palmer 2",
    "Player_9": "Rogers 2",
    "Player_15": "Mykolenko 1"
  },
  {
    "manager_Name": "1,754( 875,489 ) TotalXfr : 28",
    "Teams": "Wiggler FC( Andrew Carr )",
    "SXL": "countryCode",
    "Latp": "90",
    "Player_1": "Pickford 1",
    "Player_11": "Wood 5",
    "Player_10": "Isak 13",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Damsgaard 10",
    "Player_14": "Greaves 0",
    "Player_7": "Palmer 2",
    "Player_2": "Hall 9",
    "Player_5": "Gordon 2",
    "Player_6": "M.Salah 28",
    "Player_3": "Alexander-Arnold 6",
    "Player_4": "Mu\u00F1oz 13",
    "Player_8": "O.Dango 2",
    "Player_9": "Cunha 9",
    "Player_15": "Murillo 0"
  },
  {
    "manager_Name": "1,768( 700,881 ) TotalXfr : 33",
    "Teams": "Iwobi Wan-Kenobi( Sunit Patel )",
    "SXL": "countryCode",
    "Latp": "80",
    "Player_1": "Pickford 1",
    "Player_11": "Isak 13",
    "Player_10": "Wood 5",
    "Player_12": "Slot 10",
    "Player_13": "Fabianski 0",
    "Player_14": "Rogers 2",
    "Player_7": "M.Salah 28",
    "Player_2": "Robinson 1",
    "Player_5": "Trossard 2",
    "Player_6": "Palmer 2",
    "Player_3": "J.Timber 2",
    "Player_4": "Alexander-Arnold 6",
    "Player_8": "Kluivert 2",
    "Player_9": "Wissa 8",
    "Player_15": "Mykolenko 1"
  },
  {
    "manager_Name": "1,679( 2,178,113 ) TotalXfr : 29",
    "Teams": "Supercampeones( Ronny Nelkenbaum )",
    "SXL": "countryCode",
    "Latp": "78",
    "Player_1": "Pickford 1",
    "Player_11": "Isak 13",
    "Player_10": "Wood 5",
    "Player_12": "Fabianski 0",
    "Player_13": "Alexander-Arnold 6",
    "Player_14": "Colwill 1",
    "Player_7": "M.Salah 28",
    "Player_2": "Mu\u00F1oz 13",
    "Player_5": "Kluivert 2",
    "Player_6": "Nwaneri 2",
    "Player_3": "Hall 9",
    "Player_4": "Mykolenko 1",
    "Player_8": "Palmer 2",
    "Player_9": "Ra\u00FAl 2",
    "Player_15": "Luis D\u00EDaz 3"
  },
  {
    "manager_Name": "1,660( 2,567,038 ) TotalXfr : 27",
    "Teams": "Data Crisis( Camilla Nurkhanov )",
    "SXL": "countryCode",
    "Latp": "56",
    "Player_1": "Pickford 1",
    "Player_11": "Wood 5",
    "Player_10": "Ra\u00FAl 2",
    "Player_12": "Arteta 0",
    "Player_13": "Turner 0",
    "Player_14": "Haaland 0",
    "Player_7": "O.Dango 2",
    "Player_2": "Aina 0",
    "Player_5": "Young -1",
    "Player_6": "M.Salah 28",
    "Player_3": "Hall 9",
    "Player_4": "Alexander-Arnold 6",
    "Player_8": "Kluivert 2",
    "Player_9": "Iwobi 2",
    "Player_15": "Castagne 1"
  },
  {
    "manager_Name": "1,686( 2,029,708 ) TotalXfr : 24",
    "Teams": "Enter Team Name( teo teo )",
    "SXL": "countryCode",
    "Latp": "68",
    "Player_1": "Henderson 6",
    "Player_11": "Cunha 9",
    "Player_10": "Wood 5",
    "Player_12": "Sels 0",
    "Player_13": "Luis D\u00EDaz 3",
    "Player_14": "Robinson 1",
    "Player_7": "M.Salah 28",
    "Player_2": "Kerkez 1",
    "Player_5": "Collins 6",
    "Player_6": "Palmer 2",
    "Player_3": "Gabriel 2",
    "Player_4": "Gu\u00E9hi 5",
    "Player_8": "Kluivert 2",
    "Player_9": "Ra\u00FAl 2",
    "Player_15": "Elanga 2"
  },
  {
    "manager_Name": "1,622( 3,362,069 ) TotalXfr : 29",
    "Teams": "Herr Direktor( Roger Shehu )",
    "SXL": "countryCode",
    "Latp": "78",
    "Player_1": "Pickford 1",
    "Player_11": "Isak 13",
    "Player_10": "Wissa 8",
    "Player_12": "Fabianski 0",
    "Player_13": "Ra\u00FAl 2",
    "Player_14": "Hall 9",
    "Player_7": "Palmer 2",
    "Player_2": "Dorgu 1",
    "Player_5": "Merino 2",
    "Player_6": "M.Salah 28",
    "Player_3": "Mykolenko 1",
    "Player_4": "Alexander-Arnold 6",
    "Player_8": "Mbeumo 14",
    "Player_9": "Kluivert 2",
    "Player_15": "Davis 0"
  },
  {
    "manager_Name": "1,678( 2,199,360 ) TotalXfr : 30",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "countryCode",
    "Latp": "63",
    "Player_1": "Pickford 1",
    "Player_11": "Isak 13",
    "Player_10": "Wood 5",
    "Player_12": "Henderson 6",
    "Player_13": "Dalot 1",
    "Player_14": "Konat\u00E9 6",
    "Player_7": "M.Salah 28",
    "Player_2": "Burn 1",
    "Player_5": "Palmer 2",
    "Player_6": "Kluivert 2",
    "Player_3": "J.Timber 2",
    "Player_4": "Milenkovi\u0107 5",
    "Player_8": "Nwaneri 2",
    "Player_9": "Watkins 2",
    "Player_15": "Iroegbunam 1"
  },
  {
    "manager_Name": "1,651( 2,751,153 ) TotalXfr : 25",
    "Teams": "5-D( Erald Haxhiu )",
    "SXL": "countryCode",
    "Latp": "89",
    "Player_1": "Raya 2",
    "Player_11": "Cunha 9",
    "Player_10": "Isak 13",
    "Player_12": "Cahill 0",
    "Player_13": "Wissa 8",
    "Player_14": "Lewis 1",
    "Player_7": "M.Salah 28",
    "Player_2": "Pedro Porro 1",
    "Player_5": "Mbeumo 14",
    "Player_6": "Elanga 2",
    "Player_3": "Alexander-Arnold 6",
    "Player_4": "Hall 9",
    "Player_8": "Luis D\u00EDaz 3",
    "Player_9": "Trossard 2",
    "Player_15": "Mykolenko 1"
  },
  {
    "manager_Name": "1,639( 2,999,275 ) TotalXfr : 23",
    "Teams": "Blue Boys \uFFFD( Ilir B )",
    "SXL": "countryCode",
    "Latp": "55",
    "Player_1": "Henderson 6",
    "Player_11": "Wood 5",
    "Player_10": "Mateta 5",
    "Player_12": "Fabianski 0",
    "Player_13": "Haaland 0",
    "Player_14": "Cucurella 1",
    "Player_7": "Mbeumo 14",
    "Player_2": "Bednarek 1",
    "Player_5": "M.Salah 14",
    "Player_6": "O.Dango 4",
    "Player_3": "Aina 0",
    "Player_4": "Huijsen 2",
    "Player_8": "Merino 2",
    "Player_9": "Iwobi 2",
    "Player_15": "Tuanzebe 0"
  },
  {
    "manager_Name": "1,442( 6,333,497 ) TotalXfr : 9",
    "Teams": "Ibis Warriors( Harmeet Chana )",
    "SXL": "countryCode",
    "Latp": "45",
    "Player_1": "Raya 2",
    "Player_11": "Welbeck 0",
    "Player_10": "Haaland 0",
    "Player_12": "Turner 0",
    "Player_13": "Onana 0",
    "Player_14": "Harwood-Bellis 0",
    "Player_7": "Adama 2",
    "Player_2": "Digne 0",
    "Player_5": "Palmer 2",
    "Player_6": "Smith Rowe 1",
    "Player_3": "Robertson 6",
    "Player_4": "Saliba 2",
    "Player_8": "M.Salah 28",
    "Player_9": "Ra\u00FAl 2",
    "Player_15": "Barco 0"
  },
  {
    "manager_Name": "1,643( 2,918,111 ) TotalXfr : 25",
    "Teams": "Kokeqethurit( Daver Berberi )",
    "SXL": "countryCode",
    "Latp": "79",
    "Player_1": "Pickford 1",
    "Player_11": "Cunha 9",
    "Player_10": "Wood 5",
    "Player_12": "Emery 8",
    "Player_13": "Fabianski 0",
    "Player_14": "Enzo 7",
    "Player_7": "Palmer 2",
    "Player_2": "Gabriel 2",
    "Player_5": "M.Salah 28",
    "Player_6": "Rogers 2",
    "Player_3": "Alexander-Arnold 6",
    "Player_4": "Cucurella 1",
    "Player_8": "O.Dango 2",
    "Player_9": "Isak 13",
    "Player_15": "Mykolenko 1"
  },
  {
    "manager_Name": "1,471( 5,943,667 ) TotalXfr : 20",
    "Teams": "Sniper( Florian Toslluku )",
    "SXL": "countryCode",
    "Latp": "67",
    "Player_1": "Henderson 6",
    "Player_11": "Isak 13",
    "Player_10": "Strand Larsen 1",
    "Player_12": "Ederson M. 1",
    "Player_13": "Alex Moreno 0",
    "Player_14": "Amad 0",
    "Player_7": "Gordon 2",
    "Player_2": "Alexander-Arnold 6",
    "Player_5": "Andersen -1",
    "Player_6": "Maddison 4",
    "Player_3": "Virgil 6",
    "Player_4": "Mazraoui 1",
    "Player_8": "Thomas 1",
    "Player_9": "M.Salah 28",
    "Player_15": "N.Jackson 0"
  },
  {
    "manager_Name": "1,392( 6,991,068 ) TotalXfr : 8",
    "Teams": "RoboKoop( Enio Minxhozi )",
    "SXL": "countryCode",
    "Latp": "58",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 0",
    "Player_10": "Isak 13",
    "Player_12": "Fabianski 0",
    "Player_13": "Harwood-Bellis 0",
    "Player_14": "Chiwome 0",
    "Player_7": "Eze 3",
    "Player_2": "Alexander-Arnold 6",
    "Player_5": "Mbeumo 14",
    "Player_6": "Rogers 2",
    "Player_3": "Mazraoui 1",
    "Player_4": "Gvardiol 1",
    "Player_8": "Son 16",
    "Player_9": "Buonanotte 0",
    "Player_15": "A.Phillips 0"
  },
  {
    "manager_Name": "1,619( 3,417,518 ) TotalXfr : 24",
    "Teams": "Tokenized Maxi \u26A1\uFE0F( Eni Shtini )",
    "SXL": "countryCode",
    "Latp": "70",
    "Player_1": "Sels 0",
    "Player_11": "Wood 5",
    "Player_10": "Gakpo 1",
    "Player_12": "Emery 8",
    "Player_13": "Fabianski 0",
    "Player_14": "Amad 0",
    "Player_7": "M.Salah 28",
    "Player_2": "Konat\u00E9 6",
    "Player_5": "Kluivert 2",
    "Player_6": "Rogers 2",
    "Player_3": "Mykolenko 1",
    "Player_4": "Gabriel 2",
    "Player_8": "Palmer 2",
    "Player_9": "Isak 13",
    "Player_15": "N.Williams 0"
  },
  {
    "manager_Name": "1,537( 4,953,162 ) TotalXfr : 21",
    "Teams": "Inceneratori( Geri Muho )",
    "SXL": "countryCode",
    "Latp": "67",
    "Player_1": "Raya 2",
    "Player_11": "Vardy 2",
    "Player_10": "Beto 6",
    "Player_12": "Emery 8",
    "Player_13": "Fabianski 0",
    "Player_14": "Harwood-Bellis 0",
    "Player_7": "B.Fernandes 10",
    "Player_2": "Mykolenko 1",
    "Player_5": "Greaves 0",
    "Player_6": "Palmer 2",
    "Player_3": "Gvardiol 1",
    "Player_4": "Alexander-Arnold 6",
    "Player_8": "M.Salah 28",
    "Player_9": "Gakpo 1",
    "Player_15": "Madueke 0"
  },
  {
    "manager_Name": "1,374( 7,231,675 ) TotalXfr : 28",
    "Teams": "Yaya( Bardhyl Minxhozi )",
    "SXL": "countryCode",
    "Latp": "60",
    "Player_1": "Henderson 6",
    "Player_11": "Welbeck 0",
    "Player_10": "Scarlett 4",
    "Player_12": "Ederson M. 1",
    "Player_13": "Akanji 0",
    "Player_14": "Broja 0",
    "Player_7": "M.Salah 14",
    "Player_2": "Alexander-Arnold 6",
    "Player_5": "Mitoma 8",
    "Player_6": "Eze 3",
    "Player_3": "Pedro Porro 2",
    "Player_4": "Robertson 6",
    "Player_8": "Palmer 2",
    "Player_9": "Kulusevski 9",
    "Player_15": "Digne 0"
  },
  {
    "manager_Name": "1,340( 7,673,136 ) TotalXfr : 28",
    "Teams": "Leftisti( Magi Muco )",
    "SXL": "countryCode",
    "Latp": "57",
    "Player_1": "J\u00F8rgensen 2",
    "Player_11": "Delap 2",
    "Player_10": "Strand Larsen 1",
    "Player_12": "Areola 6",
    "Player_13": "Haaland 0",
    "Player_14": "Bednarek 1",
    "Player_7": "Enzo 7",
    "Player_2": "Quansah 1",
    "Player_5": "Merino 2",
    "Player_6": "Palmer 2",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Hall 9",
    "Player_8": "M.Salah 28",
    "Player_9": "Nwaneri 2",
    "Player_15": "Faes 0"
  }
];