var s = [
  {
    "manager_Name": "1,799( 391,517 ) TotalXfr : 29",
    "Teams": "WMB( Raj Kanango )",
    "SXL": "countryCode",
    "Latp": "65",
    "Player_1": "Henderson 6",
    "Player_11": "Isak 13",
    "Player_10": "Watkins 2",
    "Player_12": "Iraola 0",
    "Player_13": "Fabianski 0",
    "Player_14": "Elanga 2",
    "Player_7": "M.Salah 28",
    "Player_2": "J.Timber 2",
    "Player_5": "Robinson 1",
    "Player_6": "Rogers 2",
    "Player_3": "Alexander-Arnold 6",
    "Player_4": "Tarkowski 1",
    "Player_8": "Palmer 2",
    "Player_9": "Kluivert 2",
    "Player_15": "Mykolenko 1"
  },
  {
    "manager_Name": "1,797( 409,487 ) TotalXfr : 33",
    "Teams": "yoo( Nishant Singh )",
    "SXL": "countryCode",
    "Latp": "75",
    "Player_1": "Flekken 7",
    "Player_11": "Isak 13",
    "Player_10": "Wood 5",
    "Player_12": "Moyes 5",
    "Player_13": "Fabianski 0",
    "Player_14": "Elanga 2",
    "Player_7": "Rogers 2",
    "Player_2": "Gabriel 2",
    "Player_5": "M.Salah 28",
    "Player_6": "Palmer 2",
    "Player_3": "Alexander-Arnold 6",
    "Player_4": "Robinson 1",
    "Player_8": "Kluivert 2",
    "Player_9": "Watkins 2",
    "Player_15": "Mykolenko 1"
  },
  {
    "manager_Name": "1,739( 1,094,681 ) TotalXfr : 33",
    "Teams": "Weightloss Coach( Abhijeet Singh )",
    "SXL": "countryCode",
    "Latp": "69",
    "Player_1": "D\u00FAbravka 0",
    "Player_11": "Wood 5",
    "Player_10": "Isak 13",
    "Player_12": "Fabianski 0",
    "Player_13": "Mykolenko 1",
    "Player_14": "Konat\u00E9 6",
    "Player_7": "M.Salah 28",
    "Player_2": "Alexander-Arnold 6",
    "Player_5": "Mitoma 8",
    "Player_6": "Kluivert 2",
    "Player_3": "Gabriel 2",
    "Player_4": "Robinson 1",
    "Player_8": "Palmer 2",
    "Player_9": "Rogers 2",
    "Player_15": "Ndiaye 0"
  },
  {
    "manager_Name": "1,732( 1,196,217 ) TotalXfr : 25",
    "Teams": "Bihar 11( Sanjeev Kumar )",
    "SXL": "countryCode",
    "Latp": "67",
    "Player_1": "Sels 0",
    "Player_11": "Isak 13",
    "Player_10": "Wood 5",
    "Player_12": "Slot 10",
    "Player_13": "Fabianski 0",
    "Player_14": "I.Sarr 3",
    "Player_7": "Palmer 2",
    "Player_2": "Gabriel 2",
    "Player_5": "Robinson 1",
    "Player_6": "Kluivert 2",
    "Player_3": "Huijsen 2",
    "Player_4": "Kerkez 1",
    "Player_8": "M.Salah 28",
    "Player_9": "Gakpo 1",
    "Player_15": "Amad 0"
  },
  {
    "manager_Name": "1,678( 2,199,360 ) TotalXfr : 30",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "countryCode",
    "Latp": "63",
    "Player_1": "Pickford 1",
    "Player_11": "Isak 13",
    "Player_10": "Wood 5",
    "Player_12": "Henderson 6",
    "Player_13": "Dalot 1",
    "Player_14": "Konat\u00E9 6",
    "Player_7": "M.Salah 28",
    "Player_2": "Burn 1",
    "Player_5": "Palmer 2",
    "Player_6": "Kluivert 2",
    "Player_3": "J.Timber 2",
    "Player_4": "Milenkovi\u0107 5",
    "Player_8": "Nwaneri 2",
    "Player_9": "Watkins 2",
    "Player_15": "Iroegbunam 1"
  },
  {
    "manager_Name": "1,454( 6,178,336 ) TotalXfr : 26",
    "Teams": "Danapur United( Nitesh Kumar Singh )",
    "SXL": "countryCode",
    "Latp": "56",
    "Player_1": "Arrizabalaga 2",
    "Player_11": "Watkins 2",
    "Player_10": "Cunha 9",
    "Player_12": "King 0",
    "Player_13": "Yarmoliuk 1",
    "Player_14": "Keane 0",
    "Player_7": "Iwobi 2",
    "Player_2": "Gvardiol 1",
    "Player_5": "Aina 0",
    "Player_6": "Palmer 2",
    "Player_3": "Alexander-Arnold 6",
    "Player_4": "Pedro Porro 1",
    "Player_8": "M.Salah 28",
    "Player_9": "Schade 3",
    "Player_15": "Strand Larsen 1"
  },
  {
    "manager_Name": "1,220( 9,043,686 ) TotalXfr : 0",
    "Teams": "Prabin Singh( Prabin Singh )",
    "SXL": "countryCode",
    "Latp": "57",
    "Player_1": "Ederson M. 2",
    "Player_11": "Isak 13",
    "Player_10": "Mateta 5",
    "Player_12": "A.Becker 8",
    "Player_13": "Walker 0",
    "Player_14": "Martinelli 0",
    "Player_7": "Sterling 1",
    "Player_2": "Gvardiol 1",
    "Player_5": "Virgil 6",
    "Player_6": "Eze 3",
    "Player_3": "Gabriel 2",
    "Player_4": "Calafiori 1",
    "Player_8": "Mbeumo 14",
    "Player_9": "Rashford 9",
    "Player_15": "Darwin 0"
  }
];