var s = [
  {
    "manager_Name": "198( 134,032 )",
    "Teams": "Hltex Lykoi( Ioannis Poulios )",
    "SXL": "countryCode",
    "Latp": "41",
    "Player_1": "Henderson 6",
    "Player_11": "Woltemade 6",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Andersen 8",
    "Player_14": "Gudmundsson 0",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Lacroix 6",
    "Player_5": "Eze 6",
    "Player_6": "Barnes 3",
    "Player_3": "J.Timber 6",
    "Player_4": "Virgil BUR (A)",
    "Player_8": "Wirtz BUR (A)",
    "Player_9": "Gy\u00F6keres 6",
    "Player_15": "King 1"
  },
  {
    "manager_Name": "198( 134,032 )",
    "Teams": "Rodalleguianos( Sergio Andres P\u00E9rez Fern\u00E1ndez )",
    "SXL": "countryCode",
    "Latp": "27",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Haaland MUN (H)",
    "Player_12": "Sels 1",
    "Player_13": "A.Murphy 0",
    "Player_14": "Enzo BRE (A)",
    "Player_7": "Gakpo BUR (A)",
    "Player_2": "Mu\u00F1oz 5",
    "Player_5": "Walker-Peters 1",
    "Player_6": "B.Fernandes MCI (A)",
    "Player_3": "Milenkovi\u0107 1",
    "Player_4": "J.Timber 6",
    "Player_8": "J.Arias 1",
    "Player_9": "Zubimendi 13",
    "Player_15": "Morgan CHE (H)"
  },
  {
    "manager_Name": "198( 141,254 )",
    "Teams": "Alpha Academy( Jamie Davies )",
    "SXL": "countryCode",
    "Latp": "14",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Ekitik\u00E9 BUR (A)",
    "Player_10": "Gy\u00F6keres 6",
    "Player_12": "Verbruggen 2",
    "Player_13": "P.M.Sarr 1",
    "Player_14": "Matheus N. MUN (H)",
    "Player_7": "Reijnders MUN (H)",
    "Player_2": "Frimpong BUR (A)",
    "Player_5": "Kudus 1",
    "Player_6": "Neto BRE (A)",
    "Player_3": "J.Timber 6",
    "Player_4": "Van de Ven 1",
    "Player_8": "Gakpo BUR (A)",
    "Player_9": "Haaland MUN (H)",
    "Player_15": "De Cuyper 1"
  },
  {
    "manager_Name": "194( 215,029 )",
    "Teams": "FC Cantona( Nelson Schutt )",
    "SXL": "countryCode",
    "Latp": "21",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Watkins 2",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Mepham 0",
    "Player_14": "Anderson 4",
    "Player_7": "Semenyo 10",
    "Player_2": "Boly 0",
    "Player_5": "Van de Ven 1",
    "Player_6": "B.Fernandes MCI (A)",
    "Player_3": "Virgil BUR (A)",
    "Player_4": "Richards 6",
    "Player_8": "M.Salah BUR (A)",
    "Player_9": "Wood 2",
    "Player_15": "Sarr 0"
  },
  {
    "manager_Name": "193( 245,527 )",
    "Teams": "Malta Knights( Martin Knight )",
    "SXL": "countryCode",
    "Latp": "42",
    "Player_1": "Pope 7",
    "Player_11": "Ekitik\u00E9 BUR (A)",
    "Player_10": "Bowen 2",
    "Player_12": "Raya 6",
    "Player_13": "Konsa 6",
    "Player_14": "Mac Allister BUR (A)",
    "Player_7": "Sarr 0",
    "Player_2": "Diouf 1",
    "Player_5": "Burn 6",
    "Player_6": "Semenyo 10",
    "Player_3": "Gabriel 8",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Rice 1",
    "Player_9": "L.Paquet\u00E1 1",
    "Player_15": "Jo\u00E3o Pedro BRE (A)"
  },
  {
    "manager_Name": "189( 369,770 )",
    "Teams": "Gambit( Nicola Frasca )",
    "SXL": "countryCode",
    "Latp": "17",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Haaland MUN (H)",
    "Player_12": "Verbruggen 2",
    "Player_13": "Est\u00E8ve LIV (H)",
    "Player_14": "Reinildo 6",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Gabriel 8",
    "Player_5": "Reijnders MUN (H)",
    "Player_6": "Grealish 2",
    "Player_3": "Wan-Bissaka 0",
    "Player_4": "Van de Ven 1",
    "Player_8": "Caicedo BRE (A)",
    "Player_9": "Gy\u00F6keres 6",
    "Player_15": "L.Miley 0"
  },
  {
    "manager_Name": "187( 449,164 )",
    "Teams": "MDJ XI( Matthew James )",
    "SXL": "countryCode",
    "Latp": "25",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Mateta 4",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Murillo 3",
    "Player_14": "Est\u00E8ve LIV (H)",
    "Player_7": "B.Fernandes MCI (A)",
    "Player_2": "Senesi 3",
    "Player_5": "M.Salah BUR (A)",
    "Player_6": "Mbeumo MCI (A)",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Tarkowski 8",
    "Player_8": "Anderson 4",
    "Player_9": "Ndiaye 5",
    "Player_15": "Marc Guiu BRE (A)"
  },
  {
    "manager_Name": "179( 916,077 )",
    "Teams": "Crvena Zvezda( Dejan Mrdanov )",
    "SXL": "countryCode",
    "Latp": "47",
    "Player_1": "Petrovi\u0107 2",
    "Player_11": "Gy\u00F6keres 6",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "S\u00E1nchez BRE (A)",
    "Player_13": "Kerkez BUR (A)",
    "Player_14": "Ekitik\u00E9 BUR (A)",
    "Player_7": "Bruno G. 2",
    "Player_2": "Trippier 6",
    "Player_5": "Semenyo 10",
    "Player_6": "Gibbs-White 2",
    "Player_3": "J.Timber 6",
    "Player_4": "Tarkowski 8",
    "Player_8": "L.Paquet\u00E1 1",
    "Player_9": "Grealish 4",
    "Player_15": "Milenkovi\u0107 1"
  },
  {
    "manager_Name": "178( 959,586 )",
    "Teams": "For Better or Wirtz( Theo Dixon )",
    "SXL": "countryCode",
    "Latp": "8",
    "Player_1": "Verbruggen 2",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Ekitik\u00E9 BUR (A)",
    "Player_12": "Areola 0",
    "Player_13": "Wood 1",
    "Player_14": "Van de Ven 1",
    "Player_7": "Rogers 3",
    "Player_2": "Frimpong BUR (A)",
    "Player_5": "Wirtz BUR (A)",
    "Player_6": "B.Fernandes MCI (A)",
    "Player_3": "De Cuyper 1",
    "Player_4": "Pedro Porro 1",
    "Player_8": "Palmer BRE (A)",
    "Player_9": "Kudus 1",
    "Player_15": "Murillo 3"
  },
  {
    "manager_Name": "177( 1,075,122 )",
    "Teams": "Corazon( Aurelio Burgio )",
    "SXL": "countryCode",
    "Latp": "37",
    "Player_1": "Martinez 6",
    "Player_11": "Richarlison 0",
    "Player_10": "Gy\u00F6keres 12",
    "Player_12": "M.Bizot 0",
    "Player_13": "Keane 6",
    "Player_14": "Caicedo BRE (A)",
    "Player_7": "Palmer BRE (A)",
    "Player_2": "Romero 1",
    "Player_5": "Eze 6",
    "Player_6": "M.Salah BUR (A)",
    "Player_3": "Trippier 6",
    "Player_4": "Digne 5",
    "Player_8": "L.Paquet\u00E1 1",
    "Player_9": "Jo\u00E3o Pedro BRE (A)",
    "Player_15": "Van de Ven 1"
  },
  {
    "manager_Name": "175( 1,233,653 )",
    "Teams": "DBA Utd( Jim Lennox )",
    "SXL": "countryCode",
    "Latp": "16",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Evanilson 5",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Georginio 1",
    "Player_14": "Dorgu MCI (A)",
    "Player_7": "Reijnders MUN (H)",
    "Player_2": "De Cuyper 1",
    "Player_5": "Palmer BRE (A)",
    "Player_6": "M.Salah BUR (A)",
    "Player_3": "Est\u00E8ve LIV (H)",
    "Player_4": "Andersen 8",
    "Player_8": "B.Fernandes MCI (A)",
    "Player_9": "Strand Larsen 0",
    "Player_15": "Pedro Porro 1"
  },
  {
    "manager_Name": "175( 1,254,049 )",
    "Teams": "Gimby( Piotr Kluczynski )",
    "SXL": "countryCode",
    "Latp": "27",
    "Player_1": "Raya 6",
    "Player_11": "Isak BUR (A)",
    "Player_10": "Gy\u00F6keres 12",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Dewsbury-Hall 2",
    "Player_14": "Van de Ven 1",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Senesi 3",
    "Player_5": "Reijnders MUN (H)",
    "Player_6": "Enzo BRE (A)",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Virgil BUR (A)",
    "Player_8": "Gakpo BUR (A)",
    "Player_9": "Jo\u00E3o Pedro BRE (A)",
    "Player_15": "Yoro MCI (A)"
  },
  {
    "manager_Name": "173( 1,430,318 )",
    "Teams": "The Bees( Tove Ronneb\u00E4ck )",
    "SXL": "countryCode",
    "Latp": "24",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Bowen 1",
    "Player_10": "Gy\u00F6keres 6",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Diouf 1",
    "Player_14": "Est\u00E8ve LIV (H)",
    "Player_7": "Gakpo BUR (A)",
    "Player_2": "Van de Ven 1",
    "Player_5": "Mbeumo MCI (A)",
    "Player_6": "Reijnders MUN (H)",
    "Player_3": "Lacroix 6",
    "Player_4": "Virgil BUR (A)",
    "Player_8": "M.Salah BUR (A)",
    "Player_9": "Semenyo 10",
    "Player_15": "Marc Guiu BRE (A)"
  },
  {
    "manager_Name": "173( 1,430,318 )",
    "Teams": "COYS( Zachary Black )",
    "SXL": "countryCode",
    "Latp": "15",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Haaland MUN (H)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Konsa 6",
    "Player_14": "Est\u00E8ve LIV (H)",
    "Player_7": "P.M.Sarr 1",
    "Player_2": "Cucurella BRE (A)",
    "Player_5": "M.Salah BUR (A)",
    "Player_6": "Kudus 1",
    "Player_3": "Van de Ven 1",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Eze 6",
    "Player_9": "Gakpo BUR (A)",
    "Player_15": "Sherif 0"
  },
  {
    "manager_Name": "173( 1,452,550 )",
    "Teams": "Joga Bonito FC( Christophe Peixoto )",
    "SXL": "countryCode",
    "Latp": "22",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Wood 1",
    "Player_14": "N.Williams 0",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Tarkowski 8",
    "Player_5": "Gakpo BUR (A)",
    "Player_6": "Semenyo 10",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Kerkez BUR (A)",
    "Player_8": "J.Palhinha 1",
    "Player_9": "Reijnders MUN (H)",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "172( 1,559,481 )",
    "Teams": "KERAMACTICOS \u26A1( Michael Keramas )",
    "SXL": "countryCode",
    "Latp": "38",
    "Player_1": "Raya 6",
    "Player_11": "Mateta 2",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Livramento 6",
    "Player_14": "Tosin BRE (A)",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Virgil BUR (A)",
    "Player_5": "Kudus 1",
    "Player_6": "Grealish 2",
    "Player_3": "Mu\u00F1oz 5",
    "Player_4": "Lacroix 6",
    "Player_8": "Semenyo 10",
    "Player_9": "Gy\u00F6keres 6",
    "Player_15": "King 1"
  },
  {
    "manager_Name": "172( 1,559,481 )",
    "Teams": "Vad h\u00E4nde med Fricky( Adam Gabran )",
    "SXL": "countryCode",
    "Latp": "15",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Wood 1",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Reijnders MUN (H)",
    "Player_14": "Gudmundsson 0",
    "Player_7": "B.Fernandes MCI (A)",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Kudus 1",
    "Player_6": "Gakpo BUR (A)",
    "Player_3": "Diouf 1",
    "Player_4": "Virgil BUR (A)",
    "Player_8": "M.Salah BUR (A)",
    "Player_9": "Gy\u00F6keres 6",
    "Player_15": "Konsa 6"
  },
  {
    "manager_Name": "172( 1,559,481 )",
    "Teams": "YoureAToneyNoMore( Brendan Kehoe )",
    "SXL": "countryCode",
    "Latp": "40",
    "Player_1": "Vicario 1",
    "Player_11": "Haaland MUN (H)",
    "Player_10": "Mateta 2",
    "Player_12": "Petrovi\u0107 2",
    "Player_13": "Spence 1",
    "Player_14": "Senesi 3",
    "Player_7": "Dewsbury-Hall 2",
    "Player_2": "Mitchell 6",
    "Player_5": "Kudus 1",
    "Player_6": "Semenyo 10",
    "Player_3": "Gabriel 8",
    "Player_4": "J.Timber 6",
    "Player_8": "Grealish 4",
    "Player_9": "Gakpo BUR (A)",
    "Player_15": "Thiago CHE (H)"
  },
  {
    "manager_Name": "172( 1,605,188 )",
    "Teams": "Saksa FC( Neil Mifsud )",
    "SXL": "countryCode",
    "Latp": "4",
    "Player_1": "Kelleher CHE (H)",
    "Player_11": "Watkins 2",
    "Player_10": "Haaland MUN (H)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Lacroix 6",
    "Player_14": "Rodon 2",
    "Player_7": "Reijnders MUN (H)",
    "Player_2": "Virgil BUR (A)",
    "Player_5": "Kudus 1",
    "Player_6": "Gakpo BUR (A)",
    "Player_3": "Est\u00E8ve LIV (H)",
    "Player_4": "Pedro Porro 1",
    "Player_8": "Mbeumo MCI (A)",
    "Player_9": "Jo\u00E3o Pedro BRE (A)",
    "Player_15": "Potts 0"
  },
  {
    "manager_Name": "171( 1,646,998 )",
    "Teams": "Yoro Wissa Harry( Jay Patel )",
    "SXL": "countryCode",
    "Latp": "27",
    "Player_1": "Sels 1",
    "Player_11": "Gy\u00F6keres 6",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Garner 3",
    "Player_14": "Est\u00E8ve LIV (H)",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "J.Timber 6",
    "Player_5": "Van de Ven 1",
    "Player_6": "Palmer BRE (A)",
    "Player_3": "Mu\u00F1oz 5",
    "Player_4": "Senesi 3",
    "Player_8": "B.Fernandes MCI (A)",
    "Player_9": "Ndiaye 5",
    "Player_15": "Marc Guiu BRE (A)"
  },
  {
    "manager_Name": "170( 1,763,314 )",
    "Teams": "Change Name( Alexander Oyangen Johansen )",
    "SXL": "countryCode",
    "Latp": "2",
    "Player_1": "A.Becker BUR (A)",
    "Player_11": "Ekitik\u00E9 BUR (A)",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Georginio 1",
    "Player_14": "Wan-Bissaka 0",
    "Player_7": "Reijnders MUN (H)",
    "Player_2": "Pedro Porro 1",
    "Player_5": "Palmer BRE (A)",
    "Player_6": "Marmoush MUN (H)",
    "Player_3": "Dorgu MCI (A)",
    "Player_4": "Van de Ven 1",
    "Player_8": "M.Salah BUR (A)",
    "Player_9": "Strand Larsen 0",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "169( 1,884,806 )",
    "Teams": "Halib Frisk( Avinash Chatlani )",
    "SXL": "countryCode",
    "Latp": "16",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Ekitik\u00E9 BUR (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Est\u00E8ve LIV (H)",
    "Player_14": "Gudmundsson 0",
    "Player_7": "Palmer BRE (A)",
    "Player_2": "Wan-Bissaka 0",
    "Player_5": "Reijnders MUN (H)",
    "Player_6": "M.Salah BUR (A)",
    "Player_3": "Van de Ven 1",
    "Player_4": "Gabriel 8",
    "Player_8": "Ndiaye 5",
    "Player_9": "Watkins 2",
    "Player_15": "A.Ramsey LIV (H)"
  },
  {
    "manager_Name": "166( 2,304,325 )",
    "Teams": "Kings of Leon Osman( Declan Reilly )",
    "SXL": "countryCode",
    "Latp": "27",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Watkins 2",
    "Player_10": "Wood 1",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Anderson 4",
    "Player_14": "Diouf 1",
    "Player_7": "Semenyo 10",
    "Player_2": "Virgil BUR (A)",
    "Player_5": "M.Salah BUR (A)",
    "Player_6": "Ndiaye 5",
    "Player_3": "Van de Ven 1",
    "Player_4": "Tarkowski 8",
    "Player_8": "Wirtz BUR (A)",
    "Player_9": "Jo\u00E3o Pedro BRE (A)",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "166( 2,304,325 )",
    "Teams": "kinder mbeumo( Gianluca Tanti )",
    "SXL": "countryCode",
    "Latp": "32",
    "Player_1": "A.Becker BUR (A)",
    "Player_11": "Mateta 2",
    "Player_10": "Gy\u00F6keres 6",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Reijnders MUN (H)",
    "Player_14": "Tuanzebe LIV (H)",
    "Player_7": "Semenyo 10",
    "Player_2": "Mu\u00F1oz 5",
    "Player_5": "Mbeumo MCI (A)",
    "Player_6": "Iwobi 3",
    "Player_3": "Lacroix 6",
    "Player_4": "Virgil BUR (A)",
    "Player_8": "Gakpo BUR (A)",
    "Player_9": "Haaland MUN (H)",
    "Player_15": "Reinildo 6"
  },
  {
    "manager_Name": "166( 2,360,832 )",
    "Teams": "NoRelegationPls( Haykel Mansour )",
    "SXL": "countryCode",
    "Latp": "13",
    "Player_1": "Kelleher CHE (H)",
    "Player_11": "Gy\u00F6keres 6",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Reinildo 6",
    "Player_14": "Xhaka 5",
    "Player_7": "Johnson 0",
    "Player_2": "Cucurella BRE (A)",
    "Player_5": "Rogers 3",
    "Player_6": "Gakpo BUR (A)",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Diouf 1",
    "Player_8": "Wirtz BUR (A)",
    "Player_9": "Haaland MUN (H)",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "165( 2,387,481 )",
    "Teams": "Charli xGx( Charlie Rogers )",
    "SXL": "countryCode",
    "Latp": "23",
    "Player_1": "Petrovi\u0107 2",
    "Player_11": "Mateta 2",
    "Player_10": "Watkins 2",
    "Player_12": "Sels 1",
    "Player_13": "O.Dango CHE (H)",
    "Player_14": "Milenkovi\u0107 1",
    "Player_7": "Ndiaye 5",
    "Player_2": "Mu\u00F1oz 5",
    "Player_5": "Reijnders MUN (H)",
    "Player_6": "Mbeumo MCI (A)",
    "Player_3": "Pedro Porro 1",
    "Player_4": "J.Timber 6",
    "Player_8": "M.Salah BUR (A)",
    "Player_9": "Jo\u00E3o Pedro BRE (A)",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "165( 2,416,114 )",
    "Teams": "Culture FC( CHIDIEBERE OGBUCHI )",
    "SXL": "countryCode",
    "Latp": "37",
    "Player_1": "Henderson 6",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Wood 1",
    "Player_12": "Sels 1",
    "Player_13": "Anderson 4",
    "Player_14": "Est\u00E8ve LIV (H)",
    "Player_7": "Mbeumo MCI (A)",
    "Player_2": "Van de Ven 1",
    "Player_5": "M.Salah BUR (A)",
    "Player_6": "Kudus 1",
    "Player_3": "Tarkowski 8",
    "Player_4": "Konsa 6",
    "Player_8": "Grealish 2",
    "Player_9": "Gy\u00F6keres 12",
    "Player_15": "Wan-Bissaka 0"
  },
  {
    "manager_Name": "164( 2,531,754 )",
    "Teams": "AlpayFC( Alpay Al\u0131n )",
    "SXL": "countryCode",
    "Latp": "3",
    "Player_1": "Trafford MUN (H)",
    "Player_11": "Thiago CHE (H)",
    "Player_10": "Haaland MUN (H)",
    "Player_12": "Sels 1",
    "Player_13": "Calafiori 5",
    "Player_14": "J.Palhinha 1",
    "Player_7": "Sarr 0",
    "Player_2": "Saliba 0",
    "Player_5": "Cucurella BRE (A)",
    "Player_6": "Cherki MUN (H)",
    "Player_3": "James BRE (A)",
    "Player_4": "Virgil BUR (A)",
    "Player_8": "B.Fernandes MCI (A)",
    "Player_9": "Joelinton 3",
    "Player_15": "Solanke 0"
  },
  {
    "manager_Name": "163( 2,708,508 )",
    "Teams": "REMIBOY( Remeez Persent )",
    "SXL": "countryCode",
    "Latp": "18",
    "Player_1": "Raya 6",
    "Player_11": "Ekitik\u00E9 BUR (A)",
    "Player_10": "\u0160e\u0161ko MCI (A)",
    "Player_12": "Kelleher CHE (H)",
    "Player_13": "Ballard 0",
    "Player_14": "Saliba 0",
    "Player_7": "Gibbs-White 2",
    "Player_2": "Gabriel 8",
    "Player_5": "B.Fernandes MCI (A)",
    "Player_6": "Mbeumo MCI (A)",
    "Player_3": "Konat\u00E9 BUR (A)",
    "Player_4": "Cucurella BRE (A)",
    "Player_8": "Caicedo BRE (A)",
    "Player_9": "Watkins 2",
    "Player_15": "Reijnders MUN (H)"
  },
  {
    "manager_Name": "163( 2,708,508 )",
    "Teams": "Wirtz Nightmare( Adam Owens )",
    "SXL": "countryCode",
    "Latp": "23",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Haaland MUN (H)",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "N.Williams 0",
    "Player_14": "Marc Guiu BRE (A)",
    "Player_7": "Reijnders MUN (H)",
    "Player_2": "Van de Ven 1",
    "Player_5": "M.Salah BUR (A)",
    "Player_6": "Semenyo 10",
    "Player_3": "Andersen 8",
    "Player_4": "Pedro Porro 1",
    "Player_8": "Barnes 3",
    "Player_9": "Gakpo BUR (A)",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "163( 2,738,279 )",
    "Teams": "DinamoB( Pietro Menna )",
    "SXL": "countryCode",
    "Latp": "42",
    "Player_1": "Vicario 1",
    "Player_11": "Haaland MUN (H)",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "Darlow 3",
    "Player_13": "Kudus 1",
    "Player_14": "Cucurella BRE (A)",
    "Player_7": "Grealish 2",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Neto BRE (A)",
    "Player_6": "Semenyo 10",
    "Player_3": "J.Timber 6",
    "Player_4": "Calafiori 5",
    "Player_8": "Reijnders MUN (H)",
    "Player_9": "Gy\u00F6keres 12",
    "Player_15": "Senesi 3"
  },
  {
    "manager_Name": "163( 2,738,279 )",
    "Teams": "Massilia( Daniel Borg )",
    "SXL": "countryCode",
    "Latp": "11",
    "Player_1": "Petrovi\u0107 2",
    "Player_11": "Wood 1",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "Sels 1",
    "Player_13": "Milenkovi\u0107 1",
    "Player_14": "Cunha MCI (A)",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Van de Ven 1",
    "Player_5": "Senesi 3",
    "Player_6": "Elanga 1",
    "Player_3": "Chalobah BRE (A)",
    "Player_4": "Frimpong BUR (A)",
    "Player_8": "Adingra 3",
    "Player_9": "Richarlison 0",
    "Player_15": "Sarr 0"
  },
  {
    "manager_Name": "162( 2,952,202 )",
    "Teams": "XG Stats XI( Will Gunn )",
    "SXL": "countryCode",
    "Latp": "11",
    "Player_1": "Sels 1",
    "Player_11": "Watkins 2",
    "Player_10": "Haaland MUN (H)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Anderson 4",
    "Player_14": "Diouf 1",
    "Player_7": "Gakpo BUR (A)",
    "Player_2": "Van de Ven 1",
    "Player_5": "Kudus 1",
    "Player_6": "Reijnders MUN (H)",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Cucurella BRE (A)",
    "Player_8": "B.Fernandes MCI (A)",
    "Player_9": "Evanilson 5",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "161( 3,015,815 )",
    "Teams": "Goalless( Panagiotis Sfikas )",
    "SXL": "countryCode",
    "Latp": "28",
    "Player_1": "Petrovi\u0107 2",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Ekitik\u00E9 BUR (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Konsa 6",
    "Player_14": "Gudmundsson 0",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Gabriel 8",
    "Player_5": "Dewsbury-Hall 2",
    "Player_6": "Rice 1",
    "Player_3": "Mu\u00F1oz 5",
    "Player_4": "Cucurella BRE (A)",
    "Player_8": "Semenyo 10",
    "Player_9": "B.Fernandes MCI (A)",
    "Player_15": "Marc Guiu BRE (A)"
  },
  {
    "manager_Name": "161( 3,015,815 )",
    "Teams": "Gedward City FC( Graham Edwards )",
    "SXL": "countryCode",
    "Latp": "26",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Evanilson 10",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "Sels 1",
    "Player_13": "Diouf 1",
    "Player_14": "Adingra 3",
    "Player_7": "Grealish 2",
    "Player_2": "Mu\u00F1oz 5",
    "Player_5": "Virgil BUR (A)",
    "Player_6": "Palmer BRE (A)",
    "Player_3": "Van de Ven 1",
    "Player_4": "Burn 6",
    "Player_8": "Kudus 1",
    "Player_9": "Bowen 1",
    "Player_15": "Cunha MCI (A)"
  },
  {
    "manager_Name": "160( 3,142,653 )",
    "Teams": "Ctrl Alt De Ligt( Marlon Vella )",
    "SXL": "countryCode",
    "Latp": "20",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "N.Williams 0",
    "Player_14": "Adingra 3",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Mu\u00F1oz 5",
    "Player_5": "Konsa 6",
    "Player_6": "Gakpo BUR (A)",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Senesi 3",
    "Player_8": "B.Fernandes MCI (A)",
    "Player_9": "Rogers 3",
    "Player_15": "Marc Guiu BRE (A)"
  },
  {
    "manager_Name": "160( 3,207,127 )",
    "Teams": "Pruttobert( Jonas Megert )",
    "SXL": "countryCode",
    "Latp": "21",
    "Player_1": "Kelleher CHE (H)",
    "Player_11": "Ekitik\u00E9 BUR (A)",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "Sels 1",
    "Player_13": "Cherki MUN (H)",
    "Player_14": "Wan-Bissaka 0",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Cucurella BRE (A)",
    "Player_5": "Semenyo 10",
    "Player_6": "Kudus 1",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Reinildo 6",
    "Player_8": "P.M.Sarr 1",
    "Player_9": "Watkins 2",
    "Player_15": "Gudmundsson 0"
  },
  {
    "manager_Name": "160( 3,207,127 )",
    "Teams": "Red Devils( Ryan Schembri )",
    "SXL": "countryCode",
    "Latp": "26",
    "Player_1": "Leno 7",
    "Player_11": "Gy\u00F6keres 6",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "Kelleher CHE (H)",
    "Player_13": "Reijnders MUN (H)",
    "Player_14": "\u0160e\u0161ko MCI (A)",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Virgil BUR (A)",
    "Player_6": "Gakpo BUR (A)",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Van de Ven 1",
    "Player_8": "Johnson 0",
    "Player_9": "Ndiaye 5",
    "Player_15": "Gudmundsson 0"
  },
  {
    "manager_Name": "159( 3,374,916 )",
    "Teams": "Ronalbinho( Albin Jonsson )",
    "SXL": "countryCode",
    "Latp": "11",
    "Player_1": "Sels 1",
    "Player_11": "Haaland MUN (H)",
    "Player_10": "Gy\u00F6keres 6",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "F\u00FCllkrug 0",
    "Player_14": "De Cuyper 1",
    "Player_7": "Reijnders MUN (H)",
    "Player_2": "Cucurella BRE (A)",
    "Player_5": "Est\u00EAv\u00E3o BRE (A)",
    "Player_6": "M.Salah BUR (A)",
    "Player_3": "Pedro Porro 1",
    "Player_4": "Gudmundsson 0",
    "Player_8": "Dewsbury-Hall 2",
    "Player_9": "King 1",
    "Player_15": "Wan-Bissaka 0"
  },
  {
    "manager_Name": "158( 3,539,807 )",
    "Teams": "TermFC( Mark Dagostino )",
    "SXL": "countryCode",
    "Latp": "14",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Richards 6",
    "Player_14": "Anderson 4",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Agbadou 4",
    "Player_5": "Est\u00E8ve LIV (H)",
    "Player_6": "Palmer BRE (A)",
    "Player_3": "Pedro Porro 1",
    "Player_4": "N.Williams 0",
    "Player_8": "Bruno G. 2",
    "Player_9": "Ndiaye 5",
    "Player_15": "Marc Guiu BRE (A)"
  },
  {
    "manager_Name": "157( 3,706,425 )",
    "Teams": "RIP FCGB( Victor Rousteau )",
    "SXL": "countryCode",
    "Latp": "20",
    "Player_1": "Sels 1",
    "Player_11": "Ekitik\u00E9 BUR (A)",
    "Player_10": "Mateta 2",
    "Player_12": "Petrovi\u0107 2",
    "Player_13": "Saliba 0",
    "Player_14": "Sarr 0",
    "Player_7": "L.Paquet\u00E1 1",
    "Player_2": "Konat\u00E9 BUR (A)",
    "Player_5": "Spence 1",
    "Player_6": "Ndoye 2",
    "Player_3": "A\u00EFt-Nouri MUN (H)",
    "Player_4": "Gabriel 8",
    "Player_8": "Ndiaye 5",
    "Player_9": "Mbeumo MCI (A)",
    "Player_15": "Isidor 2"
  },
  {
    "manager_Name": "157( 3,706,425 )",
    "Teams": "Bugibba FC 4.0( Adam Azzopardi )",
    "SXL": "countryCode",
    "Latp": "44",
    "Player_1": "Raya 6",
    "Player_11": "Ekitik\u00E9 BUR (A)",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "\u0160e\u0161ko MCI (A)",
    "Player_14": "Wan-Bissaka 0",
    "Player_7": "Kudus 1",
    "Player_2": "Gabriel 8",
    "Player_5": "Est\u00E8ve LIV (H)",
    "Player_6": "Semenyo 10",
    "Player_3": "Van de Ven 1",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Eze 12",
    "Player_9": "M.Salah BUR (A)",
    "Player_15": "A.Ramsey LIV (H)"
  },
  {
    "manager_Name": "156( 3,844,669 )",
    "Teams": "Jarv\u0027s Juggernauts( Daniel Jarvis )",
    "SXL": "countryCode",
    "Latp": "14",
    "Player_1": "Sels 1",
    "Player_11": "Watkins 2",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "N.Williams 0",
    "Player_14": "Est\u00E8ve LIV (H)",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Konsa 6",
    "Player_5": "Reijnders MUN (H)",
    "Player_6": "Barnes 3",
    "Player_3": "Cucurella BRE (A)",
    "Player_4": "Van de Ven 1",
    "Player_8": "Kudus 1",
    "Player_9": "Wirtz BUR (A)",
    "Player_15": "Kroupi.Jr 0"
  },
  {
    "manager_Name": "156( 3,876,509 )",
    "Teams": "Mc Bryde FC( Mark Mc Bryde )",
    "SXL": "countryCode",
    "Latp": "26",
    "Player_1": "Verbruggen 2",
    "Player_11": "Haaland MUN (H)",
    "Player_10": "Gy\u00F6keres 12",
    "Player_12": "Sels 1",
    "Player_13": "Reijnders MUN (H)",
    "Player_14": "De Cuyper 1",
    "Player_7": "Kudus 1",
    "Player_2": "Pedro Porro 1",
    "Player_5": "Elanga 1",
    "Player_6": "Gakpo BUR (A)",
    "Player_3": "Calafiori 5",
    "Player_4": "Senesi 3",
    "Player_8": "Sarr 0",
    "Player_9": "Bowen 1",
    "Player_15": "Wan-Bissaka 0"
  },
  {
    "manager_Name": "156( 3,876,509 )",
    "Teams": "Mo With The Flo( Tom Atkinson )",
    "SXL": "countryCode",
    "Latp": "34",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Isak BUR (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Anderson 4",
    "Player_14": "Marc Guiu BRE (A)",
    "Player_7": "Wirtz BUR (A)",
    "Player_2": "Romero 1",
    "Player_5": "Bassey 6",
    "Player_6": "Kudus 1",
    "Player_3": "Tarkowski 8",
    "Player_4": "Mings 8",
    "Player_8": "M.Salah BUR (A)",
    "Player_9": "Semenyo 10",
    "Player_15": "Murillo 3"
  },
  {
    "manager_Name": "155( 4,046,717 )",
    "Teams": "Haribo Scharmix( Conor Maguire )",
    "SXL": "countryCode",
    "Latp": "23",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Rodon 2",
    "Player_14": "Strand Larsen 0",
    "Player_7": "Anderson 4",
    "Player_2": "Senesi 3",
    "Player_5": "Kudus 1",
    "Player_6": "Elanga 1",
    "Player_3": "Diouf 1",
    "Player_4": "Pedro Porro 1",
    "Player_8": "M.Salah BUR (A)",
    "Player_9": "Semenyo 10",
    "Player_15": "Aina 0"
  },
  {
    "manager_Name": "155( 4,111,264 )",
    "Teams": "Soccertainment( Adam Lismore )",
    "SXL": "countryCode",
    "Latp": "23",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Watkins 2",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Georginio 1",
    "Player_14": "Reinildo 6",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Pedro Porro 1",
    "Player_5": "Andersen 8",
    "Player_6": "Wirtz BUR (A)",
    "Player_3": "Mu\u00F1oz 5",
    "Player_4": "Van de Ven 1",
    "Player_8": "L.Paquet\u00E1 1",
    "Player_9": "Evanilson 5",
    "Player_15": "Marmoush MUN (H)"
  },
  {
    "manager_Name": "154( 4,186,433 )",
    "Teams": "21X.....( John Tiltmann )",
    "SXL": "countryCode",
    "Latp": "11",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Haaland MUN (H)",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "Roefs 7",
    "Player_13": "Reijnders MUN (H)",
    "Player_14": "Ndoye 2",
    "Player_7": "Johnson 0",
    "Player_2": "Senesi 3",
    "Player_5": "Van de Ven 1",
    "Player_6": "M.Salah BUR (A)",
    "Player_3": "Livramento 6",
    "Player_4": "Cucurella BRE (A)",
    "Player_8": "King 1",
    "Player_9": "Richarlison 0",
    "Player_15": "Ballard 0"
  },
  {
    "manager_Name": "153( 4,357,473 )",
    "Teams": "Rekegutt United( Eirik Presttun )",
    "SXL": "countryCode",
    "Latp": "24",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Haaland MUN (H)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "King 1",
    "Player_14": "Cullen LIV (H)",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Richards 6",
    "Player_5": "Senesi 3",
    "Player_6": "Grealish 2",
    "Player_3": "Konsa 6",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Mbeumo MCI (A)",
    "Player_9": "Bowen 1",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "153( 4,389,105 )",
    "Teams": "GreOly( John Vidiadakis )",
    "SXL": "countryCode",
    "Latp": "2",
    "Player_1": "Vicario 1",
    "Player_11": "Richarlison 0",
    "Player_10": "Haaland MUN (H)",
    "Player_12": "Sels 1",
    "Player_13": "Milenkovi\u0107 1",
    "Player_14": "Baleba 0",
    "Player_7": "Palmer BRE (A)",
    "Player_2": "Konat\u00E9 BUR (A)",
    "Player_5": "N.Williams 0",
    "Player_6": "Caicedo BRE (A)",
    "Player_3": "Virgil BUR (A)",
    "Player_4": "Cucurella BRE (A)",
    "Player_8": "Gakpo BUR (A)",
    "Player_9": "Rice 1",
    "Player_15": "Mayenda 0"
  }
];