var s = [
  {
    "manager_Name": "180( 873,166 )",
    "Teams": "\uFFFD( Magi Muco )",
    "SXL": "countryCode",
    "Latp": "14",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 6",
    "Player_10": "Haaland MUN (H)",
    "Player_12": "Verbruggen BOU (A)",
    "Player_13": "Grealish AVL (H)",
    "Player_14": "Frimpong BUR (A)",
    "Player_7": "Enzo BRE (A)",
    "Player_2": "Senesi BHA (H)",
    "Player_5": "Wirtz BUR (A)",
    "Player_6": "Ndoye 2",
    "Player_3": "Dorgu MCI (A)",
    "Player_4": "Van de Ven WHU (A)",
    "Player_8": "Est\u00EAv\u00E3o BRE (A)",
    "Player_9": "Strand Larsen NEW (A)",
    "Player_15": "Rodon FUL (A)"
  },
  {
    "manager_Name": "161( 3,046,843 )",
    "Teams": "5-D( Erald Haxhiu )",
    "SXL": "countryCode",
    "Latp": "6",
    "Player_1": "Trafford MUN (H)",
    "Player_11": "Haaland MUN (H)",
    "Player_10": "Richarlison WHU (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Senesi BHA (H)",
    "Player_14": "Gu\u00E9hi SUN (H)",
    "Player_7": "Gakpo BUR (A)",
    "Player_2": "Dorgu MCI (A)",
    "Player_5": "Malen EVE (A)",
    "Player_6": "M.Salah BUR (A)",
    "Player_3": "Lewis MUN (H)",
    "Player_4": "Van de Ven WHU (A)",
    "Player_8": "P.M.Sarr WHU (A)",
    "Player_9": "Gy\u00F6keres 6",
    "Player_15": "Tonali WOL (H)"
  },
  {
    "manager_Name": "155( 4,046,717 )",
    "Teams": "Supercampeones( Ronny Nelkenbaum )",
    "SXL": "countryCode",
    "Latp": "1",
    "Player_1": "Sels 1",
    "Player_11": "Watkins EVE (A)",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Wood 1",
    "Player_14": "N.Williams 0",
    "Player_7": "Kudus WHU (A)",
    "Player_2": "Virgil BUR (A)",
    "Player_5": "Diouf TOT (H)",
    "Player_6": "M.Salah BUR (A)",
    "Player_3": "Cucurella BRE (A)",
    "Player_4": "Pedro Porro WHU (A)",
    "Player_8": "Dewsbury-Hall AVL (H)",
    "Player_9": "Semenyo BHA (H)",
    "Player_15": "A.Ramsey LIV (H)"
  },
  {
    "manager_Name": "164( 2,590,197 )",
    "Teams": "Kyntrux( Armando Lula )",
    "SXL": "countryCode",
    "Latp": "0",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Watkins EVE (A)",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Wood 1",
    "Player_14": "N.Williams 0",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Pedro Porro WHU (A)",
    "Player_5": "B.Fernandes MCI (A)",
    "Player_6": "L.Paquet\u00E1 TOT (H)",
    "Player_3": "Agbadou NEW (A)",
    "Player_4": "Andersen LEE (H)",
    "Player_8": "Rogers EVE (A)",
    "Player_9": "Reijnders MUN (H)",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "189( 369,770 )",
    "Teams": "Tepelena( Joan Hasanmema )",
    "SXL": "countryCode",
    "Latp": "0",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Haaland MUN (H)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Barnes LIV (H)",
    "Player_14": "Alex Moreno EVE (A)",
    "Player_7": "Johnson WHU (A)",
    "Player_2": "Diouf TOT (H)",
    "Player_5": "Minteh BOU (A)",
    "Player_6": "M.Salah BUR (A)",
    "Player_3": "Andersen LEE (H)",
    "Player_4": "Van de Ven WHU (A)",
    "Player_8": "Reijnders MUN (H)",
    "Player_9": "Kudus WHU (A)",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "178( 993,271 )",
    "Teams": "Glasner all over!( Ben Bushby )",
    "SXL": "countryCode",
    "Latp": "0",
    "Player_1": "Verbruggen BOU (A)",
    "Player_11": "Watkins EVE (A)",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Konsa EVE (A)",
    "Player_14": "Est\u00E8ve LIV (H)",
    "Player_7": "Ndiaye AVL (H)",
    "Player_2": "Mu\u00F1oz SUN (H)",
    "Player_5": "Kudus WHU (A)",
    "Player_6": "M.Salah BUR (A)",
    "Player_3": "Van de Ven WHU (A)",
    "Player_4": "Rodon FUL (A)",
    "Player_8": "Elanga WOL (H)",
    "Player_9": "Ekitik\u00E9 BUR (A)",
    "Player_15": "A.Ramsey LIV (H)"
  },
  {
    "manager_Name": "162( 2,890,952 )",
    "Teams": "BlueBoys( Ilir Bazaiti )",
    "SXL": "countryCode",
    "Latp": "13",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Gy\u00F6keres 12",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "Green LIV (H)",
    "Player_13": "Anderson 4",
    "Player_14": "Abbott 0",
    "Player_7": "Palmer BRE (A)",
    "Player_2": "Senesi BHA (H)",
    "Player_5": "M.Salah BUR (A)",
    "Player_6": "Reijnders MUN (H)",
    "Player_3": "A\u00EFt-Nouri MUN (H)",
    "Player_4": "Van de Ven WHU (A)",
    "Player_8": "Rice 1",
    "Player_9": "Ekitik\u00E9 BUR (A)",
    "Player_15": "Hoever NEW (A)"
  },
  {
    "manager_Name": "149( 5,075,894 )",
    "Teams": "Renaissance( Sidrit Minxhozi )",
    "SXL": "countryCode",
    "Latp": "20",
    "Player_1": "Raya 6",
    "Player_11": "Richarlison WHU (A)",
    "Player_10": "Gy\u00F6keres 6",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Bogarde EVE (A)",
    "Player_14": "A.Ramsey LIV (H)",
    "Player_7": "Kudus WHU (A)",
    "Player_2": "Cucurella BRE (A)",
    "Player_5": "B.Fernandes MCI (A)",
    "Player_6": "Neto BRE (A)",
    "Player_3": "Gabriel 8",
    "Player_4": "James BRE (A)",
    "Player_8": "Mbeumo MCI (A)",
    "Player_9": "Haaland MUN (H)",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "142( 6,213,081 )",
    "Teams": "mayuluuu 5-0( Enio Minxhozi )",
    "SXL": "countryCode",
    "Latp": "6",
    "Player_1": "Vicario WHU (A)",
    "Player_11": "Kolo Muani WHU (A)",
    "Player_10": "Woltemade WOL (H)",
    "Player_12": "Dennis BHA (H)",
    "Player_13": "Clyne SUN (H)",
    "Player_14": "De Cuyper BOU (A)",
    "Player_7": "Wirtz BUR (A)",
    "Player_2": "A\u00EFt-Nouri MUN (H)",
    "Player_5": "Eze 6",
    "Player_6": "M.Salah BUR (A)",
    "Player_3": "Cucurella BRE (A)",
    "Player_4": "Trippier WOL (H)",
    "Player_8": "Elanga WOL (H)",
    "Player_9": "Jo\u00E3o Pedro BRE (A)",
    "Player_15": "Young EVE (A)"
  },
  {
    "manager_Name": "135( 7,189,208 )",
    "Teams": "Team name( Sunit Patel )",
    "SXL": "countryCode",
    "Latp": "1",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Watkins EVE (A)",
    "Player_10": "Wood 1",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Dewsbury-Hall AVL (H)",
    "Player_14": "Reinildo CRY (A)",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "N.Williams 0",
    "Player_5": "Wirtz BUR (A)",
    "Player_6": "Reijnders MUN (H)",
    "Player_3": "Diouf TOT (H)",
    "Player_4": "Pedro Porro WHU (A)",
    "Player_8": "B.Fernandes MCI (A)",
    "Player_9": "Mateta SUN (H)",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "173( 1,409,307 )",
    "Teams": "Kokeqethurit( Daver Berberi )",
    "SXL": "countryCode",
    "Latp": "0",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Watkins EVE (A)",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Dorgu MCI (A)",
    "Player_14": "Est\u00E8ve LIV (H)",
    "Player_7": "Gakpo BUR (A)",
    "Player_2": "Virgil BUR (A)",
    "Player_5": "M.Salah BUR (A)",
    "Player_6": "Ndiaye AVL (H)",
    "Player_3": "Lacroix SUN (H)",
    "Player_4": "Pedro Porro WHU (A)",
    "Player_8": "Reijnders MUN (H)",
    "Player_9": "Semenyo BHA (H)",
    "Player_15": "Marc Guiu BRE (A)"
  },
  {
    "manager_Name": "158( 3,507,939 )",
    "Teams": "Zhampagne Football( Camilla Nurkhanov )",
    "SXL": "countryCode",
    "Latp": "8",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Haaland MUN (H)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Konsa EVE (A)",
    "Player_14": "A.Ramsey LIV (H)",
    "Player_7": "Kudus WHU (A)",
    "Player_2": "Wan-Bissaka TOT (H)",
    "Player_5": "A\u00EFt-Nouri MUN (H)",
    "Player_6": "Wirtz BUR (A)",
    "Player_3": "Aina 0",
    "Player_4": "Gabriel 8",
    "Player_8": "Palmer BRE (A)",
    "Player_9": "B.Fernandes MCI (A)",
    "Player_15": "Marc Guiu BRE (A)"
  },
  {
    "manager_Name": "151( 4,703,284 )",
    "Teams": "Wiggler FC( Andrew Carr )",
    "SXL": "countryCode",
    "Latp": "1",
    "Player_1": "Sels 1",
    "Player_11": "Mateta SUN (H)",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Dewsbury-Hall AVL (H)",
    "Player_14": "Murillo 3",
    "Player_7": "Wirtz BUR (A)",
    "Player_2": "Cucurella BRE (A)",
    "Player_5": "Reijnders MUN (H)",
    "Player_6": "M.Salah BUR (A)",
    "Player_3": "Richards SUN (H)",
    "Player_4": "Pedro Porro WHU (A)",
    "Player_8": "Semenyo BHA (H)",
    "Player_9": "Evanilson BHA (H)",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "150( 4,904,814 )",
    "Teams": "MAGA( Eni Shtini )",
    "SXL": "countryCode",
    "Latp": "6",
    "Player_1": "Raya 6",
    "Player_11": "Haaland MUN (H)",
    "Player_10": "Mateta SUN (H)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Van de Ven WHU (A)",
    "Player_14": "King LEE (H)",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Senesi BHA (H)",
    "Player_5": "Dewsbury-Hall AVL (H)",
    "Player_6": "Semenyo BHA (H)",
    "Player_3": "Virgil BUR (A)",
    "Player_4": "Gu\u00E9hi SUN (H)",
    "Player_8": "L.Paquet\u00E1 TOT (H)",
    "Player_9": "Jo\u00E3o Pedro BRE (A)",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "144( 5,874,661 )",
    "Teams": "FantaRog( Roger Shehu )",
    "SXL": "countryCode",
    "Latp": "0",
    "Player_1": "S\u00E1nchez BRE (A)",
    "Player_11": "Watkins EVE (A)",
    "Player_10": "Richarlison WHU (A)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Ndiaye AVL (H)",
    "Player_14": "De Cuyper BOU (A)",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Pedro Porro WHU (A)",
    "Player_5": "Semenyo BHA (H)",
    "Player_6": "Reijnders MUN (H)",
    "Player_3": "Cucurella BRE (A)",
    "Player_4": "Konsa EVE (A)",
    "Player_8": "Wirtz BUR (A)",
    "Player_9": "Mateta SUN (H)",
    "Player_15": "Est\u00E8ve LIV (H)"
  },
  {
    "manager_Name": "137( 6,930,457 )",
    "Teams": "F95( Sibin - )",
    "SXL": "countryCode",
    "Latp": "20",
    "Player_1": "Raya 6",
    "Player_11": "Mateta SUN (H)",
    "Player_10": "Gy\u00F6keres 6",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "Jo\u00E3o Pedro BRE (A)",
    "Player_14": "Andersen LEE (H)",
    "Player_7": "Gakpo BUR (A)",
    "Player_2": "Gabriel 8",
    "Player_5": "M.Salah BUR (A)",
    "Player_6": "Grealish AVL (H)",
    "Player_3": "Virgil BUR (A)",
    "Player_4": "Senesi BHA (H)",
    "Player_8": "Reijnders MUN (H)",
    "Player_9": "L.Paquet\u00E1 TOT (H)",
    "Player_15": "Gudmundsson FUL (A)"
  },
  {
    "manager_Name": "160( 3,175,669 )",
    "Teams": "robby_baggio( Marin Jano )",
    "SXL": "countryCode",
    "Latp": "14",
    "Player_1": "Verbruggen BOU (A)",
    "Player_11": "Gy\u00F6keres 6",
    "Player_10": "Jo\u00E3o Pedro BRE (A)",
    "Player_12": "Benitez SUN (H)",
    "Player_13": "Bowen TOT (H)",
    "Player_14": "Konsa EVE (A)",
    "Player_7": "M.Salah BUR (A)",
    "Player_2": "Gabriel 8",
    "Player_5": "Kudus WHU (A)",
    "Player_6": "Reijnders MUN (H)",
    "Player_3": "A\u00EFt-Nouri MUN (H)",
    "Player_4": "Pedro Porro WHU (A)",
    "Player_8": "Gakpo BUR (A)",
    "Player_9": "Ndiaye AVL (H)",
    "Player_15": "Alex Moreno EVE (A)"
  },
  {
    "manager_Name": "124( 8,299,812 )",
    "Teams": "Park The Bus( Lorin Minxhozi )",
    "SXL": "countryCode",
    "Latp": "18",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 12",
    "Player_10": "Mateta SUN (H)",
    "Player_12": "D\u00FAbravka LIV (H)",
    "Player_13": "King LEE (H)",
    "Player_14": "Senesi BHA (H)",
    "Player_7": "Semenyo BHA (H)",
    "Player_2": "Pedro Porro WHU (A)",
    "Player_5": "O.Dango CHE (H)",
    "Player_6": "Gakpo BUR (A)",
    "Player_3": "Virgil BUR (A)",
    "Player_4": "Mu\u00F1oz SUN (H)",
    "Player_8": "Mbeumo MCI (A)",
    "Player_9": "Haaland MUN (H)",
    "Player_15": "Gudmundsson FUL (A)"
  },
  {
    "manager_Name": "120( 8,630,147 )",
    "Teams": "Albi alexander( Bardhyl Minxhozi )",
    "SXL": "countryCode",
    "Latp": "3",
    "Player_1": "A.Becker BUR (A)",
    "Player_11": "Jo\u00E3o Pedro BRE (A)",
    "Player_10": "Welbeck BOU (A)",
    "Player_12": "Raya 6",
    "Player_13": "Konsa EVE (A)",
    "Player_14": "Hoever NEW (A)",
    "Player_7": "L.Paquet\u00E1 TOT (H)",
    "Player_2": "Gvardiol MUN (H)",
    "Player_5": "Madueke 3",
    "Player_6": "M.Salah BUR (A)",
    "Player_3": "Cucurella BRE (A)",
    "Player_4": "Virgil BUR (A)",
    "Player_8": "Mbeumo MCI (A)",
    "Player_9": "Johnson WHU (A)",
    "Player_15": "Broja LIV (H)"
  }
];