var s = [
  {
    "manager_Name": "332( 1 )",
    "Teams": "sfdfc( Jo\u00E3o Pereira )",
    "SXL": "PRT",
    "Latp": "100",
    "Player_1": "Henderson 6",
    "Player_11": "Jo\u00E3o Pedro 21",
    "Player_10": "Haaland 13",
    "Player_12": "Pickford 6",
    "Player_13": "Lacroix 6",
    "Player_14": "McGinn 3",
    "Player_7": "Enzo 4",
    "Player_2": "Pedro Porro 6",
    "Player_5": "Mu\u00F1oz 5",
    "Player_6": "Semenyo 13",
    "Player_3": "Romero 12",
    "Player_4": "Livramento 6",
    "Player_8": "Grealish 2",
    "Player_9": "Caicedo 12",
    "Player_15": "\u0160e\u0161ko 2"
  },
  {
    "manager_Name": "327( 2 )",
    "Teams": "COYS1960( Stephen Flood )",
    "SXL": "USA",
    "Latp": "109",
    "Player_1": "A.Becker 6",
    "Player_11": "Jo\u00E3o Pedro 14",
    "Player_10": "Haaland 13",
    "Player_12": "Raya 6",
    "Player_13": "J.Timber 8",
    "Player_14": "Wood 1",
    "Player_7": "Caicedo 12",
    "Player_2": "Romero 12",
    "Player_5": "Mitoma 7",
    "Player_6": "Mbeumo 2",
    "Player_3": "Burn 6",
    "Player_4": "Mu\u00F1oz 5",
    "Player_8": "Eze 6",
    "Player_9": "Kudus 3",
    "Player_15": "Trippier 8"
  },
  {
    "manager_Name": "322( 3 )",
    "Teams": "Lumpy( Kacper G\u0142owacki )",
    "SXL": "POL",
    "Latp": "81",
    "Player_1": "Henderson 6",
    "Player_11": "Jo\u00E3o Pedro 14",
    "Player_10": "Gy\u00F6keres 6",
    "Player_12": "A.Becker 6",
    "Player_13": "Dalot 0",
    "Player_14": "Kudus 3",
    "Player_7": "Bruno G. 2",
    "Player_2": "Livramento 6",
    "Player_5": "J.Timber 8",
    "Player_6": "Enzo 4",
    "Player_3": "Van de Ven 14",
    "Player_4": "Burn 6",
    "Player_8": "Grealish 2",
    "Player_9": "Semenyo 13",
    "Player_15": "Bowen 2"
  },
  {
    "manager_Name": "321( 4 )",
    "Teams": "The new Pep( Marc Nizinskyj )",
    "SXL": "ENG",
    "Latp": "104",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro 7",
    "Player_12": "Gunn 0",
    "Player_13": "Konsa 6",
    "Player_14": "Stach 1",
    "Player_7": "M.Salah 9",
    "Player_2": "Van de Ven 14",
    "Player_5": "Gu\u00E9hi 6",
    "Player_6": "Grealish 2",
    "Player_3": "Romero 12",
    "Player_4": "Gabriel 9",
    "Player_8": "Rice 1",
    "Player_9": "Caicedo 12",
    "Player_15": "Delap 0"
  },
  {
    "manager_Name": "320( 5 )",
    "Teams": "Manchester City( Javier Rufo )",
    "SXL": "ESP",
    "Latp": "96",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro 7",
    "Player_10": "Haaland 26",
    "Player_12": "Vicario 8",
    "Player_13": "A\u00EFt-Nouri 0",
    "Player_14": "Palmer 7",
    "Player_7": "Caicedo 12",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "J.Timber 8",
    "Player_6": "Tonali 3",
    "Player_3": "Gabriel 9",
    "Player_4": "Pedro Porro 6",
    "Player_8": "Cherki 0",
    "Player_9": "Semenyo 13",
    "Player_15": "Nmecha 1"
  },
  {
    "manager_Name": "319( 6 )",
    "Teams": "Change Name( Markus Mollden )",
    "SXL": "SWE",
    "Latp": "75",
    "Player_1": "Pickford 6",
    "Player_11": "Jo\u00E3o Pedro 14",
    "Player_10": "Haaland 13",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Frimpong 4",
    "Player_14": "Wirtz 3",
    "Player_7": "Grealish 2",
    "Player_2": "Pedro Porro 6",
    "Player_5": "Cucurella 1",
    "Player_6": "Kudus 3",
    "Player_3": "Gabriel 9",
    "Player_4": "J.Timber 8",
    "Player_8": "Rice 1",
    "Player_9": "Caicedo 12",
    "Player_15": "Richarlison 1"
  },
  {
    "manager_Name": "319( 7 )",
    "Teams": "Your A Pain In Dias( kobe Idiagbonya )",
    "SXL": "AUS",
    "Latp": "73",
    "Player_1": "Pickford 6",
    "Player_11": "Jo\u00E3o Pedro 14",
    "Player_10": "Gy\u00F6keres 6",
    "Player_12": "Sels 1",
    "Player_13": "Wan-Bissaka 0",
    "Player_14": "L.Paquet\u00E1 2",
    "Player_7": "Semenyo 13",
    "Player_2": "Virgil 8",
    "Player_5": "Gu\u00E9hi 6",
    "Player_6": "Iwobi 3",
    "Player_3": "Lacroix 6",
    "Player_4": "J.Timber 8",
    "Player_8": "Rice 1",
    "Player_9": "Ekitik\u00E9 2",
    "Player_15": "Onana 0"
  },
  {
    "manager_Name": "318( 8 )",
    "Teams": "Ttok _hotelier_( X @Kinuthiamwangi8 )",
    "SXL": "KEN",
    "Latp": "83",
    "Player_1": "S\u00E1nchez 2",
    "Player_11": "Jo\u00E3o Pedro 7",
    "Player_10": "Haaland 13",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Hudson-Odoi 1",
    "Player_14": "Reinildo 6",
    "Player_7": "Ndiaye 5",
    "Player_2": "Romero 12",
    "Player_5": "Rodon 4",
    "Player_6": "M.Salah 18",
    "Player_3": "Pedro Porro 6",
    "Player_4": "Van de Ven 14",
    "Player_8": "King 1",
    "Player_9": "Wood 1",
    "Player_15": "Elanga 1"
  },
  {
    "manager_Name": "316( 9 )",
    "Teams": "Alpha FC( Phamous Alpha )",
    "SXL": "GHA",
    "Latp": "91",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 12",
    "Player_10": "Jo\u00E3o Pedro 7",
    "Player_12": "Vicario 8",
    "Player_13": "Pedro Porro 6",
    "Player_14": "Caicedo 12",
    "Player_7": "Mac Allister 1",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Romero 12",
    "Player_6": "Zubimendi 16",
    "Player_3": "Virgil 8",
    "Player_4": "R\u00FAben 6",
    "Player_8": "Semenyo 13",
    "Player_9": "Enzo 4",
    "Player_15": "Haaland 13"
  },
  {
    "manager_Name": "316( 10 )",
    "Teams": "Change Name( Kori Lee )",
    "SXL": "ENG",
    "Latp": "106",
    "Player_1": "Pope 8",
    "Player_11": "Jo\u00E3o Pedro 14",
    "Player_10": "Haaland 13",
    "Player_12": "Kelleher 2",
    "Player_13": "Dunk 2",
    "Player_14": "Saliba 0",
    "Player_7": "Caicedo 12",
    "Player_2": "Romero 12",
    "Player_5": "Zubimendi 16",
    "Player_6": "M.Salah 9",
    "Player_3": "Van de Ven 14",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Rice 1",
    "Player_9": "Richarlison 1",
    "Player_15": "Baleba 0"
  },
  {
    "manager_Name": "316( 11 )",
    "Teams": "Baker.T( Xitong Zhu )",
    "SXL": "CHN",
    "Latp": "76",
    "Player_1": "Vicario 8",
    "Player_11": "Ekitik\u00E9 4",
    "Player_10": "Haaland 13",
    "Player_12": "Pickford 6",
    "Player_13": "Aina 0",
    "Player_14": "Saliba 0",
    "Player_7": "Rice 1",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Kudus 3",
    "Player_6": "Enzo 4",
    "Player_3": "Romero 12",
    "Player_4": "Calafiori 5",
    "Player_8": "Semenyo 13",
    "Player_9": "Jo\u00E3o Pedro 7",
    "Player_15": "Reijnders 3"
  },
  {
    "manager_Name": "315( 12 )",
    "Teams": "Kien fc( Daniel Kinigoma )",
    "SXL": "NGA",
    "Latp": "99",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro 14",
    "Player_10": "Haaland 13",
    "Player_12": "Vicario 8",
    "Player_13": "Sarr 0",
    "Player_14": "Reijnders 3",
    "Player_7": "Semenyo 13",
    "Player_2": "Romero 12",
    "Player_5": "J.Timber 8",
    "Player_6": "Gabriel 9",
    "Player_3": "Cucurella 1",
    "Player_4": "Van de Ven 14",
    "Player_8": "Enzo 4",
    "Player_9": "Ndiaye 5",
    "Player_15": "Mateta 2"
  },
  {
    "manager_Name": "315( 13 )",
    "Teams": "tongue wagglers( Jack Pascall )",
    "SXL": "ENG",
    "Latp": "90",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 6",
    "Player_10": "Ekitik\u00E9 4",
    "Player_12": "Sels 1",
    "Player_13": "Enzo 4",
    "Player_14": "Van de Ven 14",
    "Player_7": "Kudus 3",
    "Player_2": "Gabriel 9",
    "Player_5": "Semenyo 13",
    "Player_6": "M.Salah 9",
    "Player_3": "Livramento 6",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Tavernier 2",
    "Player_9": "Jo\u00E3o Pedro 7",
    "Player_15": "Clyne 0"
  },
  {
    "manager_Name": "315( 13 )",
    "Teams": "Ready Toulouse( Lomas Dimonsen )",
    "SXL": "DNK",
    "Latp": "94",
    "Player_1": "Pickford 6",
    "Player_11": "Jo\u00E3o Pedro 7",
    "Player_10": "Gy\u00F6keres 12",
    "Player_12": "Verbruggen 2",
    "Player_13": "Gusto 0",
    "Player_14": "Lewis 0",
    "Player_7": "Zubimendi 16",
    "Player_2": "Virgil 8",
    "Player_5": "Kudus 3",
    "Player_6": "Semenyo 13",
    "Player_3": "Van de Ven 14",
    "Player_4": "Kerkez 0",
    "Player_8": "Mbeumo 2",
    "Player_9": "Haaland 13",
    "Player_15": "Caicedo 12"
  },
  {
    "manager_Name": "315( 13 )",
    "Teams": "Havertz Word Ref( Dan Day )",
    "SXL": "ENG",
    "Latp": "82",
    "Player_1": "Raya 6",
    "Player_11": "Ekitik\u00E9 2",
    "Player_10": "Jo\u00E3o Pedro 14",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Dorgu 1",
    "Player_14": "Ndiaye 5",
    "Player_7": "Semenyo 13",
    "Player_2": "Livramento 6",
    "Player_5": "Van de Ven 14",
    "Player_6": "Kudus 3",
    "Player_3": "Mu\u00F1oz 5",
    "Player_4": "Chalobah 3",
    "Player_8": "Reijnders 3",
    "Player_9": "Haaland 13",
    "Player_15": "Saka 0"
  },
  {
    "manager_Name": "315( 13 )",
    "Teams": "Sabur.Mamnd( Sabur Mamnd )",
    "SXL": "IRQ",
    "Latp": "79",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 13",
    "Player_10": "Wood 1",
    "Player_12": "Sels 1",
    "Player_13": "Saliba 0",
    "Player_14": "Baleba 0",
    "Player_7": "Semenyo 13",
    "Player_2": "Cucurella 1",
    "Player_5": "Gakpo 3",
    "Player_6": "Caicedo 12",
    "Player_3": "Mu\u00F1oz 5",
    "Player_4": "Gabriel 9",
    "Player_8": "Grealish 2",
    "Player_9": "Jo\u00E3o Pedro 14",
    "Player_15": "Alex Moreno 0"
  },
  {
    "manager_Name": "314( 17 )",
    "Teams": "pemburu janda( Usop rahim )",
    "SXL": "MYS",
    "Latp": "91",
    "Player_1": "Pope 8",
    "Player_11": "Gy\u00F6keres 12",
    "Player_10": "Haaland 13",
    "Player_12": "Henderson 6",
    "Player_13": "Bobb 1",
    "Player_14": "Mu\u00F1oz 5",
    "Player_7": "Kudus 3",
    "Player_2": "Livramento 6",
    "Player_5": "Enzo 4",
    "Player_6": "Grealish 2",
    "Player_3": "Chalobah 3",
    "Player_4": "Van de Ven 14",
    "Player_8": "Mbeumo 2",
    "Player_9": "Jo\u00E3o Pedro 7",
    "Player_15": "Calafiori 5"
  },
  {
    "manager_Name": "314( 17 )",
    "Teams": "Pec( Pec Bolu )",
    "SXL": "NGA",
    "Latp": "78",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro 14",
    "Player_10": "Ekitik\u00E9 2",
    "Player_12": "Henderson 6",
    "Player_13": "Pedro Porro 6",
    "Player_14": "Mbeumo 2",
    "Player_7": "Semenyo 13",
    "Player_2": "J.Timber 8",
    "Player_5": "Cucurella 1",
    "Player_6": "Grealish 2",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Virgil 8",
    "Player_8": "Caicedo 12",
    "Player_9": "Gy\u00F6keres 6",
    "Player_15": "Kudus 3"
  },
  {
    "manager_Name": "314( 19 )",
    "Teams": "BRIMA Jo( Japhet Ali )",
    "SXL": "NGA",
    "Latp": "68",
    "Player_1": "Pickford 6",
    "Player_11": "Haaland 13",
    "Player_10": "Jo\u00E3o Pedro 14",
    "Player_12": "Raya 6",
    "Player_13": "Amad 2",
    "Player_14": "Gabriel 9",
    "Player_7": "Caicedo 12",
    "Player_2": "Virgil 8",
    "Player_5": "Aina 0",
    "Player_6": "Iwobi 3",
    "Player_3": "Cucurella 1",
    "Player_4": "J.Timber 8",
    "Player_8": "Johnson 1",
    "Player_9": "Welbeck 2",
    "Player_15": "Szoboszlai 3"
  },
  {
    "manager_Name": "314( 20 )",
    "Teams": "KIDUS( kidus yohanes )",
    "SXL": "ETH",
    "Latp": "91",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 26",
    "Player_10": "Jo\u00E3o Pedro 7",
    "Player_12": "Sels 1",
    "Player_13": "A\u00EFt-Nouri 0",
    "Player_14": "Adingra 3",
    "Player_7": "Sarr 0",
    "Player_2": "Tarkowski 8",
    "Player_5": "Cucurella 1",
    "Player_6": "Kudus 3",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Gabriel 9",
    "Player_8": "Caicedo 12",
    "Player_9": "Semenyo 13",
    "Player_15": "Ekitik\u00E9 2"
  },
  {
    "manager_Name": "313( 21 )",
    "Teams": "Fishermen Friends( Carl Shaw )",
    "SXL": "ENG",
    "Latp": "74",
    "Player_1": "Henderson 6",
    "Player_11": "Isak 0",
    "Player_10": "Haaland 13",
    "Player_12": "Roefs 10",
    "Player_13": "Senesi 3",
    "Player_14": "Grealish 2",
    "Player_7": "Semenyo 13",
    "Player_2": "Livramento 6",
    "Player_5": "Madueke 3",
    "Player_6": "Eze 6",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Burn 6",
    "Player_8": "Reijnders 3",
    "Player_9": "Gy\u00F6keres 12",
    "Player_15": "Gudmundsson 0"
  },
  {
    "manager_Name": "313( 21 )",
    "Teams": "nice2michu( Jacob Brown )",
    "SXL": "ENG",
    "Latp": "89",
    "Player_1": "Henderson 6",
    "Player_11": "Jo\u00E3o Pedro 14",
    "Player_10": "Ekitik\u00E9 2",
    "Player_12": "Verbruggen 2",
    "Player_13": "A\u00EFt-Nouri 0",
    "Player_14": "Caicedo 12",
    "Player_7": "Szoboszlai 3",
    "Player_2": "Livramento 6",
    "Player_5": "Romero 12",
    "Player_6": "Semenyo 13",
    "Player_3": "Mu\u00F1oz 5",
    "Player_4": "Pedro Porro 6",
    "Player_8": "Kudus 3",
    "Player_9": "Marmoush 0",
    "Player_15": "Evanilson 5"
  },
  {
    "manager_Name": "313( 23 )",
    "Teams": "Muwedde fc( Job Kiiza )",
    "SXL": "UGA",
    "Latp": "69",
    "Player_1": "Raya 6",
    "Player_11": "Ekitik\u00E9 2",
    "Player_10": "Gy\u00F6keres 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Masuaku 0",
    "Player_14": "A\u00EFt-Nouri 0",
    "Player_7": "Semenyo 13",
    "Player_2": "J.Timber 8",
    "Player_5": "Reijnders 3",
    "Player_6": "M.Salah 9",
    "Player_3": "Gusto 0",
    "Player_4": "Pedro Porro 6",
    "Player_8": "Kudus 3",
    "Player_9": "Jo\u00E3o Pedro 7",
    "Player_15": "P.M.Sarr 8"
  },
  {
    "manager_Name": "313( 24 )",
    "Teams": "\u062C\u0648\u0647\u0631\u064A( \u0627\u062D\u0645\u062F \u0627\u0644\u062C\u0648\u0647\u0631\u064A )",
    "SXL": "EGY",
    "Latp": "69",
    "Player_1": "Pope 8",
    "Player_11": "Gy\u00F6keres 6",
    "Player_10": "Jo\u00E3o Pedro 7",
    "Player_12": "A.Becker 6",
    "Player_13": "Welbeck 2",
    "Player_14": "Diouf 1",
    "Player_7": "Grealish 4",
    "Player_2": "Sch\u00E4r 8",
    "Player_5": "Pedro Porro 6",
    "Player_6": "M.Salah 9",
    "Player_3": "Calafiori 5",
    "Player_4": "Livramento 6",
    "Player_8": "Mitoma 7",
    "Player_9": "Kudus 3",
    "Player_15": "Reijnders 3"
  },
  {
    "manager_Name": "312( 25 )",
    "Teams": "Rob\u2019s winners( Rob Cousins )",
    "SXL": "ENG",
    "Latp": "73",
    "Player_1": "Pope 8",
    "Player_11": "Wood 1",
    "Player_10": "Jo\u00E3o Pedro 14",
    "Player_12": "A.Becker 6",
    "Player_13": "Milenkovi\u0107 1",
    "Player_14": "Hudson-Odoi 1",
    "Player_7": "Grealish 2",
    "Player_2": "Virgil 8",
    "Player_5": "Eze 6",
    "Player_6": "Semenyo 13",
    "Player_3": "Gabriel 9",
    "Player_4": "Burn 6",
    "Player_8": "Enzo 4",
    "Player_9": "Ekitik\u00E9 2",
    "Player_15": "Saliba 0"
  },
  {
    "manager_Name": "312( 26 )",
    "Teams": "Farrells Chaps( Chris Farrell )",
    "SXL": "ENG",
    "Latp": "71",
    "Player_1": "Vicario 8",
    "Player_11": "Haaland 13",
    "Player_10": "Gy\u00F6keres 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Reijnders 3",
    "Player_14": "Pedro Porro 6",
    "Player_7": "Gakpo 3",
    "Player_2": "J.Timber 8",
    "Player_5": "Rice 1",
    "Player_6": "Kudus 3",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Livramento 6",
    "Player_8": "Enzo 4",
    "Player_9": "Jo\u00E3o Pedro 7",
    "Player_15": "Cucurella 1"
  },
  {
    "manager_Name": "312( 26 )",
    "Teams": "SAVAGE( kim wilson )",
    "SXL": "NGA",
    "Latp": "71",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 6",
    "Player_10": "Jo\u00E3o Pedro 14",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Reijnders 3",
    "Player_14": "Haaland 13",
    "Player_7": "Enzo 4",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Pedro Porro 6",
    "Player_6": "Semenyo 13",
    "Player_3": "Gabriel 9",
    "Player_4": "Cucurella 1",
    "Player_8": "Gakpo 3",
    "Player_9": "Gravenberch 3",
    "Player_15": "R\u00FAben 6"
  },
  {
    "manager_Name": "312( 26 )",
    "Teams": "Zoalna Travels( Hatim Khedawiy )",
    "SXL": "SDN",
    "Latp": "69",
    "Player_1": "Pickford 6",
    "Player_11": "Jo\u00E3o Pedro 7",
    "Player_10": "Gy\u00F6keres 6",
    "Player_12": "Dennis 0",
    "Player_13": "Cucurella 1",
    "Player_14": "Collins 3",
    "Player_7": "M.Salah 9",
    "Player_2": "Tarkowski 8",
    "Player_5": "Rice 1",
    "Player_6": "Semenyo 13",
    "Player_3": "Mu\u00F1oz 5",
    "Player_4": "Trippier 8",
    "Player_8": "Grealish 2",
    "Player_9": "Mateta 4",
    "Player_15": "Broggio 0"
  },
  {
    "manager_Name": "312( 29 )",
    "Teams": "Ntaphani FC( Everesto Tafs )",
    "SXL": "ZWE",
    "Latp": "90",
    "Player_1": "Vicario 8",
    "Player_11": "Gy\u00F6keres 12",
    "Player_10": "Jo\u00E3o Pedro 7",
    "Player_12": "Pope 8",
    "Player_13": "Boly 0",
    "Player_14": "Young 0",
    "Player_7": "Zubimendi 16",
    "Player_2": "J.Timber 8",
    "Player_5": "Gu\u00E9hi 6",
    "Player_6": "M.Salah 9",
    "Player_3": "Senesi 3",
    "Player_4": "Livramento 6",
    "Player_8": "L.Paquet\u00E1 2",
    "Player_9": "Haaland 13",
    "Player_15": "P.M.Sarr 8"
  },
  {
    "manager_Name": "312( 30 )",
    "Teams": "Arbitro sporting( CLIFF Richard MULLI )",
    "SXL": "MWI",
    "Latp": "58",
    "Player_1": "Pickford 6",
    "Player_11": "Gy\u00F6keres 6",
    "Player_10": "Jo\u00E3o Pedro 7",
    "Player_12": "Leno 8",
    "Player_13": "Kudus 3",
    "Player_14": "Amad 2",
    "Player_7": "Wirtz 3",
    "Player_2": "Burn 6",
    "Player_5": "J.Timber 8",
    "Player_6": "Neto 2",
    "Player_3": "Trippier 8",
    "Player_4": "Chalobah 3",
    "Player_8": "Ndiaye 5",
    "Player_9": "Ekitik\u00E9 4",
    "Player_15": "Alderete 9"
  },
  {
    "manager_Name": "311( 31 )",
    "Teams": "Willo( Tom Williams )",
    "SXL": "ENG",
    "Latp": "78",
    "Player_1": "Vicario 8",
    "Player_11": "Jo\u00E3o Pedro 14",
    "Player_10": "Gy\u00F6keres 6",
    "Player_12": "Pickford 6",
    "Player_13": "Milenkovi\u0107 1",
    "Player_14": "Gibbs-White 2",
    "Player_7": "Caicedo 12",
    "Player_2": "J.Timber 8",
    "Player_5": "Virgil 8",
    "Player_6": "Rice 1",
    "Player_3": "Van de Ven 14",
    "Player_4": "Chalobah 3",
    "Player_8": "Grealish 2",
    "Player_9": "Dewsbury-Hall 2",
    "Player_15": "Haaland 13"
  },
  {
    "manager_Name": "311( 31 )",
    "Teams": "YNFC( Marcus Djedji )",
    "SXL": "CIV",
    "Latp": "73",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro 14",
    "Player_10": "Ekitik\u00E9 2",
    "Player_12": "Pickford 6",
    "Player_13": "Van de Ven 14",
    "Player_14": "B.Fernandes 2",
    "Player_7": "Enzo 4",
    "Player_2": "Romero 12",
    "Player_5": "Mu\u00F1oz 5",
    "Player_6": "Wirtz 3",
    "Player_3": "Gabriel 9",
    "Player_4": "Saliba 0",
    "Player_8": "Caicedo 12",
    "Player_9": "Eze 6",
    "Player_15": "Wood 1"
  },
  {
    "manager_Name": "311( 33 )",
    "Teams": "Sneeky Sinners( Joacim Eriksson )",
    "SXL": "SWE",
    "Latp": "91",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 6",
    "Player_10": "Haaland 13",
    "Player_12": "Pickford 6",
    "Player_13": "Caicedo 12",
    "Player_14": "Reijnders 3",
    "Player_7": "Ndiaye 5",
    "Player_2": "Trippier 8",
    "Player_5": "Gabriel 18",
    "Player_6": "Gakpo 3",
    "Player_3": "Pedro Porro 6",
    "Player_4": "Burn 6",
    "Player_8": "Semenyo 13",
    "Player_9": "Jo\u00E3o Pedro 7",
    "Player_15": "Digne 5"
  },
  {
    "manager_Name": "311( 33 )",
    "Teams": "1880 St Marks( Paul Taylor )",
    "SXL": "ENG",
    "Latp": "110",
    "Player_1": "Vicario 8",
    "Player_11": "Jo\u00E3o Pedro 7",
    "Player_10": "Ekitik\u00E9 2",
    "Player_12": "Pickford 6",
    "Player_13": "Kudus 3",
    "Player_14": "Mu\u00F1oz 5",
    "Player_7": "Reijnders 3",
    "Player_2": "Chalobah 3",
    "Player_5": "Semenyo 26",
    "Player_6": "Gakpo 3",
    "Player_3": "Livramento 6",
    "Player_4": "Van de Ven 14",
    "Player_8": "Grealish 2",
    "Player_9": "Haaland 13",
    "Player_15": "Gabriel 9"
  },
  {
    "manager_Name": "311( 35 )",
    "Teams": "Chelsea( Michael Nana Dapaah )",
    "SXL": "GHA",
    "Latp": "78",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro 7",
    "Player_10": "Wood 2",
    "Player_12": "Trafford 0",
    "Player_13": "Saliba 0",
    "Player_14": "Evanilson 5",
    "Player_7": "B.Fernandes 2",
    "Player_2": "Romero 12",
    "Player_5": "Caicedo 12",
    "Player_6": "Kudus 3",
    "Player_3": "Tarkowski 8",
    "Player_4": "Livramento 6",
    "Player_8": "Semenyo 13",
    "Player_9": "Palmer 7",
    "Player_15": "Aina 0"
  },
  {
    "manager_Name": "311( 35 )",
    "Teams": "Martin\u0027s B\u00F8degaard( Nnyombi Sylvester )",
    "SXL": "UGA",
    "Latp": "66",
    "Player_1": "Vicario 8",
    "Player_11": "Jo\u00E3o Pedro 7",
    "Player_10": "Gy\u00F6keres 12",
    "Player_12": "S\u00E1nchez 2",
    "Player_13": "Saliba 0",
    "Player_14": "Milenkovi\u0107 1",
    "Player_7": "Eze 6",
    "Player_2": "Rodon 4",
    "Player_5": "Mitoma 7",
    "Player_6": "Gakpo 3",
    "Player_3": "Cash 5",
    "Player_4": "Alderete 9",
    "Player_8": "Kudus 3",
    "Player_9": "Ekitik\u00E9 2",
    "Player_15": "Gnonto 1"
  },
  {
    "manager_Name": "311( 37 )",
    "Teams": "hamaton( Hamaton Achesa )",
    "SXL": "KEN",
    "Latp": "98",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro 7",
    "Player_10": "Haaland 13",
    "Player_12": "Petrovi\u0107 2",
    "Player_13": "Hudson-Odoi 1",
    "Player_14": "P.M.Sarr 8",
    "Player_7": "Semenyo 39",
    "Player_2": "Gabriel 9",
    "Player_5": "Gu\u00E9hi 6",
    "Player_6": "Spence 5",
    "Player_3": "Cucurella 1",
    "Player_4": "Pedro Porro 6",
    "Player_8": "B.Fernandes 2",
    "Player_9": "Enzo 4",
    "Player_15": "Mayenda 0"
  },
  {
    "manager_Name": "311( 37 )",
    "Teams": "acca fc( Colm Kelliher )",
    "SXL": "IRL",
    "Latp": "75",
    "Player_1": "A.Becker 6",
    "Player_11": "Jo\u00E3o Pedro 14",
    "Player_10": "Gy\u00F6keres 6",
    "Player_12": "Leno 8",
    "Player_13": "Wirtz 3",
    "Player_14": "Lewis 0",
    "Player_7": "Caicedo 12",
    "Player_2": "Livramento 6",
    "Player_5": "Mu\u00F1oz 5",
    "Player_6": "Grealish 2",
    "Player_3": "Cucurella 1",
    "Player_4": "J.Timber 8",
    "Player_8": "Semenyo 13",
    "Player_9": "Ekitik\u00E9 2",
    "Player_15": "Minteh 6"
  },
  {
    "manager_Name": "310( 39 )",
    "Teams": "Maina\uFFFD( John Muturi )",
    "SXL": "KEN",
    "Latp": "80",
    "Player_1": "Pope 8",
    "Player_11": "Jo\u00E3o Pedro 14",
    "Player_10": "Haaland 13",
    "Player_12": "A.Becker 6",
    "Player_13": "Gu\u00E9hi 6",
    "Player_14": "Kudus 3",
    "Player_7": "Bruno G. 2",
    "Player_2": "J.Timber 8",
    "Player_5": "Livramento 6",
    "Player_6": "Szoboszlai 3",
    "Player_3": "De Cuyper 1",
    "Player_4": "Van de Ven 14",
    "Player_8": "Enzo 4",
    "Player_9": "Palmer 7",
    "Player_15": "Wissa 0"
  },
  {
    "manager_Name": "310( 40 )",
    "Teams": "Umbea( Mbona Kachelewa )",
    "SXL": "KEN",
    "Latp": "56",
    "Player_1": "A.Becker 6",
    "Player_11": "Jo\u00E3o Pedro 7",
    "Player_10": "Gy\u00F6keres 6",
    "Player_12": "Pickford 6",
    "Player_13": "Tarkowski 8",
    "Player_14": "Wood 1",
    "Player_7": "B.Fernandes 4",
    "Player_2": "J.Timber 8",
    "Player_5": "Wirtz 3",
    "Player_6": "Kudus 3",
    "Player_3": "Mu\u00F1oz 5",
    "Player_4": "Calafiori 5",
    "Player_8": "Ndiaye 5",
    "Player_9": "Enzo 4",
    "Player_15": "James 1"
  },
  {
    "manager_Name": "310( 41 )",
    "Teams": "MubeenJR( Nazrul Mubeenn )",
    "SXL": "MYS",
    "Latp": "105",
    "Player_1": "Raya 6",
    "Player_11": "Gy\u00F6keres 6",
    "Player_10": "Jo\u00E3o Pedro 14",
    "Player_12": "Gunn 0",
    "Player_13": "Mings 9",
    "Player_14": "Mbeumo 2",
    "Player_7": "Zubimendi 16",
    "Player_2": "Mu\u00F1oz 5",
    "Player_5": "Livramento 6",
    "Player_6": "Semenyo 13",
    "Player_3": "Bassey 9",
    "Player_4": "Van de Ven 14",
    "Player_8": "Gakpo 3",
    "Player_9": "Haaland 13",
    "Player_15": "Elanga 1"
  },
  {
    "manager_Name": "310( 42 )",
    "Teams": "JOZEF\u0027s Team( Chabane Youcef )",
    "SXL": "DZA",
    "Latp": "70",
    "Player_1": "Pope 8",
    "Player_11": "Jo\u00E3o Pedro 7",
    "Player_10": "Haaland 13",
    "Player_12": "A.Becker 6",
    "Player_13": "Virgil 8",
    "Player_14": "Rice 1",
    "Player_7": "Grealish 2",
    "Player_2": "Van de Ven 14",
    "Player_5": "Kudus 3",
    "Player_6": "Enzo 4",
    "Player_3": "De Ligt 1",
    "Player_4": "Chalobah 3",
    "Player_8": "Reijnders 3",
    "Player_9": "Gy\u00F6keres 12",
    "Player_15": "Calafiori 5"
  },
  {
    "manager_Name": "309( 43 )",
    "Teams": "Grand Old Team( Elliot Mans )",
    "SXL": "ENG",
    "Latp": "86",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 13",
    "Player_10": "Jo\u00E3o Pedro 7",
    "Player_12": "Verbruggen 2",
    "Player_13": "Senesi 3",
    "Player_14": "Evanilson 5",
    "Player_7": "Semenyo 26",
    "Player_2": "Gabriel 9",
    "Player_5": "Cucurella 1",
    "Player_6": "Reijnders 3",
    "Player_3": "Chalobah 3",
    "Player_4": "Van de Ven 14",
    "Player_8": "Dewsbury-Hall 2",
    "Player_9": "Gibbs-White 2",
    "Player_15": "Mbeumo 2"
  },
  {
    "manager_Name": "309( 43 )",
    "Teams": "GHOST FC( Migele Bernados )",
    "SXL": "KEN",
    "Latp": "65",
    "Player_1": "Henderson 6",
    "Player_11": "Richarlison 1",
    "Player_10": "Jo\u00E3o Pedro 14",
    "Player_12": "Raya 6",
    "Player_13": "Cucurella 1",
    "Player_14": "Lacroix 6",
    "Player_7": "M.Salah 9",
    "Player_2": "Senesi 3",
    "Player_5": "Semenyo 13",
    "Player_6": "\u00D8degaard 1",
    "Player_3": "Calafiori 5",
    "Player_4": "Virgil 8",
    "Player_8": "Enzo 4",
    "Player_9": "Johnson 1",
    "Player_15": "Foster 2"
  },
  {
    "manager_Name": "309( 45 )",
    "Teams": "Leo Dipesh Fc( Dipesh Dahal )",
    "SXL": "NPL",
    "Latp": "86",
    "Player_1": "Raya 6",
    "Player_11": "Jo\u00E3o Pedro 7",
    "Player_10": "Haaland 13",
    "Player_12": "Vicario 8",
    "Player_13": "Baleba 0",
    "Player_14": "Caicedo 12",
    "Player_7": "Semenyo 13",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Chalobah 3",
    "Player_6": "Mbeumo 2",
    "Player_3": "Gabriel 9",
    "Player_4": "Romero 12",
    "Player_8": "Gakpo 3",
    "Player_9": "Gy\u00F6keres 12",
    "Player_15": "Van de Ven 14"
  },
  {
    "manager_Name": "308( 46 )",
    "Teams": "Mntungwa FC( Lloyd S. Khumalo )",
    "SXL": "ZAF",
    "Latp": "97",
    "Player_1": "Henderson 6",
    "Player_11": "Mateta 4",
    "Player_10": "Haaland 13",
    "Player_12": "A.Becker 6",
    "Player_13": "Lewis-Skelly 1",
    "Player_14": "Cherki 0",
    "Player_7": "Zubimendi 16",
    "Player_2": "Livramento 6",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Semenyo 13",
    "Player_3": "Van de Ven 14",
    "Player_4": "Romero 12",
    "Player_8": "Enzo 4",
    "Player_9": "Jo\u00E3o Pedro 7",
    "Player_15": "Virgil 8"
  },
  {
    "manager_Name": "308( 46 )",
    "Teams": "ABK FC( Nash Junior )",
    "SXL": "GHA",
    "Latp": "83",
    "Player_1": "Roefs 10",
    "Player_11": "Jo\u00E3o Pedro 14",
    "Player_10": "Haaland 13",
    "Player_12": "Ramsdale 0",
    "Player_13": "J.Araujo 0",
    "Player_14": "Clyne 0",
    "Player_7": "Semenyo 13",
    "Player_2": "Cucurella 1",
    "Player_5": "Minteh 6",
    "Player_6": "Enzo 4",
    "Player_3": "Saliba 0",
    "Player_4": "Sch\u00E4r 8",
    "Player_8": "M.Salah 9",
    "Player_9": "Xhaka 5",
    "Player_15": "Marc Guiu 0"
  },
  {
    "manager_Name": "308( 48 )",
    "Teams": "liverpool( Avishen Singaravelloo )",
    "SXL": "MUS",
    "Latp": "84",
    "Player_1": "Henderson 6",
    "Player_11": "Isak 0",
    "Player_10": "Haaland 26",
    "Player_12": "A.Becker 6",
    "Player_13": "Mings 9",
    "Player_14": "Dunk 2",
    "Player_7": "Semenyo 13",
    "Player_2": "Gabriel 9",
    "Player_5": "Zubimendi 16",
    "Player_6": "Rice 1",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Cucurella 1",
    "Player_8": "Enzo 4",
    "Player_9": "Ekitik\u00E9 2",
    "Player_15": "Baleba 0"
  },
  {
    "manager_Name": "308( 49 )",
    "Teams": "Nza.zirak( Nza Zirak )",
    "SXL": "IRQ",
    "Latp": "73",
    "Player_1": "Henderson 6",
    "Player_11": "Jo\u00E3o Pedro 7",
    "Player_10": "Haaland 26",
    "Player_12": "Pope 8",
    "Player_13": "Wood 1",
    "Player_14": "O.Dango 1",
    "Player_7": "Elanga 1",
    "Player_2": "Trippier 8",
    "Player_5": "Spence 5",
    "Player_6": "Gakpo 3",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Tarkowski 8",
    "Player_8": "Johnson 1",
    "Player_9": "Mbeumo 2",
    "Player_15": "Dorgu 1"
  },
  {
    "manager_Name": "308( 50 )",
    "Teams": "11 Paths Sage( Preye Princewill )",
    "SXL": "NGA",
    "Latp": "116",
    "Player_1": "Pope 8",
    "Player_11": "Jo\u00E3o Pedro 7",
    "Player_10": "Haaland 13",
    "Player_12": "Henderson 6",
    "Player_13": "Bassey 9",
    "Player_14": "Bruno G. 2",
    "Player_7": "Gakpo 3",
    "Player_2": "J.Timber 8",
    "Player_5": "Livramento 6",
    "Player_6": "Caicedo 12",
    "Player_3": "Pedro Porro 6",
    "Player_4": "Gabriel 9",
    "Player_8": "Eze 12",
    "Player_9": "Semenyo 13",
    "Player_15": "Beto 2"
  }
];