var s = [
   {
      "manager_Name":"Sahil Lampard",
      "Teams":"MarxUnited",
      "Player_1":"Ramsdale -",
      "Player_2":"Alexander-Arnold -",
      "Player_3":"James -",
      "Player_4":"Cancelo 9",
      "Player_5":"Son 9",
      "Player_6":"Benrahma 0",
      "Player_7":"Bernardo 3",
      "Player_8":"Salah -$ captain",
      "Player_9":"Hudson-Odoi -",
      "Player_10":"Dennis 2",
      "Player_11":"Maupay 2",
      "Player_12":"Sánchez 1",
      "Player_13":"Livramento 8",
      "Player_14":"Archer 0",
      "Player_15":"White -",
      "SXL":"25",
      "Bench":"1424",
      "Count  ":"2,169,173"
   },
   {
      "manager_Name":"Saurabh Tamang",
      "Teams":"Lucky FC",
      "Player_1":"Guaita 0",
      "Player_2":"Cancelo 9",
      "Player_3":"Alexander-Arnold -",
      "Player_4":"Coady 2",
      "Player_5":"Salah -$ captain",
      "Player_6":"Smith Rowe -",
      "Player_7":"Bowen 3",
      "Player_8":"Gallagher 2",
      "Player_9":"Mané -",
      "Player_10":"Dennis 2",
      "Player_11":"Adams 6",
      "Player_12":"Sánchez 1",
      "Player_13":"Livramento 8",
      "Player_14":"Omobamidele 0",
      "Player_15":"Archer 0",
      "SXL":"24",
      "Bench":"1385",
      "Count  ":"2,675,136"
   },
   {
      "manager_Name":"Pranesh Sharma",
      "Teams":"Immortal FC",
      "Player_1":"Pope 3, LEI (H)",
      "Player_2":"Walker-Peters 9",
      "Player_3":"Cancelo 9",
      "Player_4":"Roberts 2, LEI (H)",
      "Player_5":"Sterling 3",
      "Player_6":"Mahrez 1",
      "Player_7":"Son 9",
      "Player_8":"Sancho 1",
      "Player_9":"Weghorst 4, LEI (H)$ captain",
      "Player_10":"Broja 2",
      "Player_11":"Kane 11",
      "Player_12":"Matthews 0",
      "Player_13":"Amartey BUR (A)",
      "Player_14":"Williams 0",
      "Player_15":"Dewsbury-Hall BUR (A)",
      "SXL":"54",
      "Bench":"1604",
      "Count  ":"517,838"
   },
   {
      "manager_Name":"Sanjeev Kumar",
      "Teams":"GAROBADHA UNITED",
      "Player_1":"Lloris 6",
      "Player_2":"Tierney -",
      "Player_3":"Alexander-Arnold -",
      "Player_4":"White -",
      "Player_5":"Cancelo 9",
      "Player_6":"Maddison BUR (A)",
      "Player_7":"Bowen 3",
      "Player_8":"Gallagher 4$ captain",
      "Player_9":"Broja 2",
      "Player_10":"Adams 6",
      "Player_11":"Saint-Maximin 0",
      "Player_12":"Foster 10",
      "Player_13":"Saka -",
      "Player_14":"Robertson -",
      "Player_15":"Salah -",
      "SXL":"30",
      "Bench":"1636",
      "Count  ":"362,154"
   },
   {
      "manager_Name":"Kumar Anku",
      "Teams":"The Borderland Fc",
      "Player_1":"Forster 6",
      "Player_2":"Ait Nouri 0",
      "Player_3":"Cancelo 9",
      "Player_4":"Davies 5",
      "Player_5":"Mings 11",
      "Player_6":"Sissoko 3",
      "Player_7":"Winks 3",
      "Player_8":"Fernandes 6$ captain",
      "Player_9":"Hwang 2",
      "Player_10":"Kane 11",
      "Player_11":"Rodriguez 2, LEI (H)",
      "Player_12":"Bachmann 0",
      "Player_13":"Saka -",
      "Player_14":"Alexander-Arnold -",
      "Player_15":"Salah -",
      "SXL":"58",
      "Bench":"1525",
      "Count  ":"1,082,347"
   },
   {
      "manager_Name":"Kushal Sahota",
      "Teams":"FC ASSASSINS",
      "Player_1":"Ramsdale -",
      "Player_2":"Dias 7",
      "Player_3":"Reguilón 0",
      "Player_4":"Duffy 0",
      "Player_5":"Jota -",
      "Player_6":"Bowen 3",
      "Player_7":"Gallagher 2",
      "Player_8":"Salah -$ captain",
      "Player_9":"Dennis 2",
      "Player_10":"Antonio 4",
      "Player_11":"Ronaldo 2",
      "Player_12":"Steele 0",
      "Player_13":"Tsimikas -",
      "Player_14":"Allan 1",
      "Player_15":"Livramento 8",
      "SXL":"20",
      "Bench":"1338",
      "Count  ":"3,315,221"
   },
   {
      "manager_Name":"Regean Lama",
      "Teams":"BUSBY BABIES 2",
      "Player_1":"Foster 10",
      "Player_2":"Veltman 0",
      "Player_3":"Pinnock 1",
      "Player_4":"Semedo 0",
      "Player_5":"Zaha 2",
      "Player_6":"Sarr 3",
      "Player_7":"De Bruyne 3",
      "Player_8":"Bowen 3",
      "Player_9":"Weghorst 4, LEI (H)$ captain",
      "Player_10":"Broja 2",
      "Player_11":"Kane 11",
      "Player_12":"Carson 0",
      "Player_13":"Tierney -",
      "Player_14":"Alexander-Arnold -",
      "Player_15":"Ødegaard -",
      "SXL":"39",
      "Bench":"1575",
      "Count  ":"696,993"
   },
   {
      "manager_Name":"pranam rai",
      "Teams":"SYAKREE FC",
      "Player_1":"Lloris 6",
      "Player_2":"Alexander-Arnold -",
      "Player_3":"Tsimikas -",
      "Player_4":"Saïss 2",
      "Player_5":"Salah -$ captain",
      "Player_6":"Ødegaard -",
      "Player_7":"Bowen 3",
      "Player_8":"Højbjerg 6",
      "Player_9":"Dennis 2",
      "Player_10":"Ronaldo 2",
      "Player_11":"Adams 6",
      "Player_12":"Sánchez 1",
      "Player_13":"Dias 7",
      "Player_14":"Bernardo 3",
      "Player_15":"Manquillo 0",
      "SXL":"27",
      "Bench":"1488",
      "Count  ":"1,434,372"
   },
   {
      "manager_Name":"Ashim Lama",
      "Teams":"⚔️FURY⚔️",
      "Player_1":"Lloris 6",
      "Player_2":"Jansson 1",
      "Player_3":"Cancelo 9",
      "Player_4":"Roberts 2, LEI (H)",
      "Player_5":"Bowen 3",
      "Player_6":"Coutinho 3",
      "Player_7":"Gallagher 2",
      "Player_8":"Salah -",
      "Player_9":"Broja 2",
      "Player_10":"Weghorst 4, LEI (H)$ captain",
      "Player_11":"Dennis 2",
      "Player_12":"Ward BUR (A)",
      "Player_13":"Alexander-Arnold -",
      "Player_14":"Martinelli -",
      "Player_15":"Gabriel -",
      "SXL":"34",
      "Bench":"1563",
      "Count  ":"775,675"
   },
   {
      "manager_Name":"Vivek Pradhan",
      "Teams":"PEPPERBOX83",
      "Player_1":"Sánchez 1",
      "Player_2":"Cancelo 9",
      "Player_3":"Mee 2, LEI (H)",
      "Player_4":"Dias 7",
      "Player_5":"Pinnock 1",
      "Player_6":"McNeil 2, LEI (H)",
      "Player_7":"Sissoko 3",
      "Player_8":"Fernandes 6$ captain",
      "Player_9":"Weghorst 2, LEI (H)",
      "Player_10":"King 2",
      "Player_11":"Dennis 2",
      "Player_12":"Raya 4",
      "Player_13":"Salah -",
      "Player_14":"Smith Rowe -",
      "Player_15":"Alexander-Arnold -",
      "SXL":"37",
      "Bench":"1600",
      "Count  ":"538,872"
   },
   {
      "manager_Name":"Sibin _",
      "Teams":"F95",
      "Player_1":"Ederson 5",
      "Player_2":"Dias 7",
      "Player_3":"Robertson -",
      "Player_4":"van Dijk -",
      "Player_5":"Tarkowski 1, LEI (H)",
      "Player_6":"Varane 6",
      "Player_7":"Bernardo 3",
      "Player_8":"Lucas Moura 0",
      "Player_9":"Bowen 6$ captain",
      "Player_10":"Maupay 2",
      "Player_11":"Dennis 2",
      "Player_12":"Ramsdale -",
      "Player_13":"Smith Rowe -",
      "Player_14":"Salah -",
      "Player_15":"Weghorst 2, LEI (H)",
      "SXL":"32",
      "Bench":"1619",
      "Count  ":"441,246"
   },
   {
      "manager_Name":"Omkar Subba",
      "Teams":"Omk09",
      "Player_1":"Foster 10",
      "Player_2":"Robertson -",
      "Player_3":"Laporte 7",
      "Player_4":"Livramento 8",
      "Player_5":"Tierney -",
      "Player_6":"Son 18$ captain",
      "Player_7":"Coutinho 3",
      "Player_8":"Bowen 3",
      "Player_9":"Saint-Maximin 0",
      "Player_10":"Broja 2",
      "Player_11":"Dennis 2",
      "Player_12":"Ramsdale -",
      "Player_13":"Saka -",
      "Player_14":"van Dijk -",
      "Player_15":"Salah -",
      "SXL":"53",
      "Bench":"1555",
      "Count  ":"836,749"
   },
   {
      "manager_Name":"Indrajeet Singh",
      "Teams":"Kung Fu Pandoos",
      "Player_1":"de Gea 6",
      "Player_2":"Laporte 7",
      "Player_3":"Mee 4, LEI (H)$ captain",
      "Player_4":"Kilman 2",
      "Player_5":"Gilmour 2",
      "Player_6":"Raphinha 2",
      "Player_7":"Ward-Prowse 3",
      "Player_8":"Sterling 3",
      "Player_9":"Kane 11",
      "Player_10":"Maupay 2",
      "Player_11":"Weghorst 2, LEI (H)",
      "Player_12":"Foster 10",
      "Player_13":"Mané -",
      "Player_14":"Matip -",
      "Player_15":"Tierney -",
      "SXL":"44",
      "Bench":"1524",
      "Count  ":"1,088,827"
   },
   {
      "manager_Name":"Rishi Thulung",
      "Teams":"PL CG FC",
      "Player_1":"de Gea 6",
      "Player_2":"Marçal 2",
      "Player_3":"Cancelo 9",
      "Player_4":"Lamptey 1",
      "Player_5":"Bowen 3",
      "Player_6":"Raphinha 2",
      "Player_7":"Lucas Moura 0",
      "Player_8":"Fernandes 6$ captain",
      "Player_9":"Ward-Prowse 3",
      "Player_10":"Antonio 4",
      "Player_11":"Dennis 2",
      "Player_12":"Ramsdale -",
      "Player_13":"King 2",
      "Player_14":"Alexander-Arnold -",
      "Player_15":"Robertson -",
      "SXL":"38",
      "Bench":"1582",
      "Count  ":"646,757"
   },
   {
      "manager_Name":"Dipen Thapa",
      "Teams":"BW4_11",
      "Player_1":"Sá 3",
      "Player_2":"Gabriel -",
      "Player_3":"Alexander-Arnold -",
      "Player_4":"Tomiyasu -",
      "Player_5":"Bernardo 3",
      "Player_6":"Jota -$ captain",
      "Player_7":"Fernandes 3",
      "Player_8":"Soucek 11",
      "Player_9":"Dennis 2",
      "Player_10":"Antonio 4",
      "Player_11":"Watkins 5",
      "Player_12":"Sánchez 1",
      "Player_13":"Livramento 8",
      "Player_14":"Gallagher 2",
      "Player_15":"Dias 7",
      "SXL":"31",
      "Bench":"1468",
      "Count  ":"1,651,510"
   },
   {
      "manager_Name":"Nishant Singh",
      "Teams":"beta",
      "Player_1":"Sánchez 1",
      "Player_2":"Tarkowski 1, LEI (H)",
      "Player_3":"Dias 7",
      "Player_4":"Digne 6",
      "Player_5":"Cancelo 9",
      "Player_6":"Coutinho 3",
      "Player_7":"Bowen 3",
      "Player_8":"Foden 7",
      "Player_9":"Maupay 2",
      "Player_10":"King 2",
      "Player_11":"Dennis 4$ captain",
      "Player_12":"Ramsdale -",
      "Player_13":"Smith Rowe -",
      "Player_14":"Salah -",
      "Player_15":"Alexander-Arnold -",
      "SXL":"45",
      "Bench":"1548",
      "Count  ":"890,742"
   },
   {
      "manager_Name":"Ashish Subba",
      "Teams":"Gustavous Gunner",
      "Player_1":"Foster 10",
      "Player_2":"Bednarek 6",
      "Player_3":"Cancelo 9",
      "Player_4":"Maguire 0",
      "Player_5":"Tierney -",
      "Player_6":"Gallagher 4$ captain",
      "Player_7":"Fernandes 3",
      "Player_8":"Raphinha 2",
      "Player_9":"Maddison BUR (A)",
      "Player_10":"Dennis 2",
      "Player_11":"Antonio 4",
      "Player_12":"Ramsdale -",
      "Player_13":"Salah -",
      "Player_14":"Alexander-Arnold -",
      "Player_15":"Obafemi 0",
      "SXL":"40",
      "Bench":"1559",
      "Count  ":"805,498"
   },
   {
      "manager_Name":"Rohan Rai",
      "Teams":"False 9",
      "Player_1":"de Gea 6",
      "Player_2":"Cancelo 9",
      "Player_3":"Laporte 7",
      "Player_4":"Livramento 8",
      "Player_5":"Coutinho 3",
      "Player_6":"Raphinha 2",
      "Player_7":"Fernandes 3",
      "Player_8":"Bowen 3",
      "Player_9":"Maupay 2",
      "Player_10":"Dennis 2",
      "Player_11":"Weghorst 4, LEI (H)$ captain",
      "Player_12":"Ramsdale -",
      "Player_13":"Coufal 0",
      "Player_14":"Salah -",
      "Player_15":"Tomiyasu -",
      "SXL":"49",
      "Bench":"1756",
      "Count  ":"46,886"
   },
   {
      "manager_Name":"Raj Kanango",
      "Teams":"Weightloss Coach",
      "Player_1":"de Gea 6",
      "Player_2":"Amartey BUR (A)",
      "Player_3":"Davies 5",
      "Player_4":"Cancelo 9",
      "Player_5":"Son 18$ captain",
      "Player_6":"Fernandes 3",
      "Player_7":"Bowen 3",
      "Player_8":"Coutinho 3",
      "Player_9":"Maupay 2",
      "Player_10":"Weghorst 2, LEI (H)",
      "Player_11":"Dennis 2",
      "Player_12":"Carson 0",
      "Player_13":"Tierney -",
      "Player_14":"Saka -",
      "Player_15":"Alexander-Arnold -",
      "SXL":"53",
      "Bench":"1637",
      "Count  ":"359,182"
   },
   {
      "manager_Name":"Gaurav Shrestha",
      "Teams":"Fußball-Mannschaft",
      "Player_1":"de Gea 6",
      "Player_2":"Cancelo 9",
      "Player_3":"Livramento 8",
      "Player_4":"Digne 6",
      "Player_5":"Raphinha 2",
      "Player_6":"Bowen 3",
      "Player_7":"Son 9",
      "Player_8":"Fernandes 3",
      "Player_9":"Gallagher 2",
      "Player_10":"Broja 2",
      "Player_11":"Weghorst 4, LEI (H)$ captain",
      "Player_12":"Foster 10",
      "Player_13":"Alexander-Arnold -",
      "Player_14":"Tierney -",
      "Player_15":"Lacazette -",
      "SXL":"54",
      "Bench":"1758",
      "Count  ":"44,385"
   },
   {
      "manager_Name":"Bishal Rai",
      "Teams":"Gooner for Life 037",
      "Player_1":"Pope 3, LEI (H)",
      "Player_2":"Mee 2, LEI (H)",
      "Player_3":"Cancelo 9",
      "Player_4":"Bednarek 6",
      "Player_5":"Ward-Prowse 3",
      "Player_6":"Fernandes 3",
      "Player_7":"Sancho 1",
      "Player_8":"Son 9",
      "Player_9":"Kane 11",
      "Player_10":"Broja 2",
      "Player_11":"Weghorst 4, LEI (H)$ captain",
      "Player_12":"Foster 10",
      "Player_13":"Dawson 6",
      "Player_14":"Chambers 0",
      "Player_15":"Ramsey 3",
      "SXL":"53",
      "Bench":"1707",
      "Count  ":"132,382"
   },
   {
      "manager_Name":"RAJIYUNG Sun",
      "Teams":"hansing",
      "Player_1":"Alisson -",
      "Player_2":"Laporte 7",
      "Player_3":"Cancelo 9",
      "Player_4":"Shaw 1",
      "Player_5":"Bowen 3",
      "Player_6":"Fernandes 3",
      "Player_7":"De Bruyne 3",
      "Player_8":"Pogba 6$ captain",
      "Player_9":"Broja 2",
      "Player_10":"Dennis 2",
      "Player_11":"Daka BUR (A)",
      "Player_12":"Raya 4",
      "Player_13":"White -",
      "Player_14":"Saka -",
      "Player_15":"Alexander-Arnold -",
      "SXL":"36",
      "Bench":"1613",
      "Count  ":"471,350"
   },
   {
      "manager_Name":"Ashish Rai",
      "Teams":"Deadhead",
      "Player_1":"Foster 10",
      "Player_2":"Emerson Royal 1",
      "Player_3":"Mitchell 2",
      "Player_4":"Digne 6",
      "Player_5":"Saïss 2",
      "Player_6":"Podence 1",
      "Player_7":"Zaha 2",
      "Player_8":"Ward-Prowse 3",
      "Player_9":"Weghorst 4, LEI (H)$ captain",
      "Player_10":"Kane 11",
      "Player_11":"Dennis 2",
      "Player_12":"Ramsdale -",
      "Player_13":"James 2",
      "Player_14":"Salah -",
      "Player_15":"Alexander-Arnold -",
      "SXL":"44",
      "Bench":"1693",
      "Count  ":"167,752"
   },
   {
      "manager_Name":"prabin kumar",
      "Teams":"Prabin Singh",
      "Player_1":"Mendy -",
      "Player_2":"Rüdiger -",
      "Player_3":"Alonso -",
      "Player_4":"Dias 7",
      "Player_5":"Benrahma 0",
      "Player_6":"Greenwood 0",
      "Player_7":"Townsend 0",
      "Player_8":"Son 9",
      "Player_9":"Jiménez 1",
      "Player_10":"Antonio 4",
      "Player_11":"Aubameyang -$ captain",
      "Player_12":"Foster 10",
      "Player_13":"Shaw 1",
      "Player_14":"Tsimikas -",
      "Player_15":"Bissouma 1",
      "SXL":"21",
      "Bench":"1102",
      "Count  ":"6,444,213"
   },
   {
      "manager_Name":"Ravish Verma",
      "Teams":"Little Chilli FC",
      "Player_1":"Pope 3, LEI (H)",
      "Player_2":"Roberts 2, LEI (H)",
      "Player_3":"Johnson 6",
      "Player_4":"Cancelo 9",
      "Player_5":"Mahrez 1",
      "Player_6":"Fernandes 3",
      "Player_7":"Sterling 6$ captain",
      "Player_8":"Son 9",
      "Player_9":"Broja 2",
      "Player_10":"Weghorst 2, LEI (H)",
      "Player_11":"Kane 11",
      "Player_12":"Okonkwo -",
      "Player_13":"Tsimikas -",
      "Player_14":"Amartey BUR (A)",
      "Player_15":"Gordon 3",
      "SXL":"54",
      "Bench":"1683",
      "Count  ":"194,526"
   },
   {
      "manager_Name":"Prayash Thapa",
      "Teams":"abcde FC",
      "Player_1":"Forster 6",
      "Player_2":"Cancelo 9",
      "Player_3":"Mee 2, LEI (H)",
      "Player_4":"Tarkowski 1, LEI (H)",
      "Player_5":"Mahrez 1",
      "Player_6":"Sterling 3",
      "Player_7":"Fernandes 3",
      "Player_8":"Son 9",
      "Player_9":"Broja 2",
      "Player_10":"Weghorst 4, LEI (H)$ captain",
      "Player_11":"Kane 11",
      "Player_12":"Gunn 3",
      "Player_13":"McArthur 3",
      "Player_14":"Livramento 8",
      "Player_15":"Tsimikas -",
      "SXL":"51",
      "Bench":"1744",
      "Count  ":"63,189"
   },
   {
      "manager_Name":"Tenzing Ninjey",
      "Teams":"One Step Beyond 026*",
      "Player_1":"Sánchez 1",
      "Player_2":"Cancelo 9",
      "Player_3":"Digne 6",
      "Player_4":"Ait Nouri 0",
      "Player_5":"Ramsey 3",
      "Player_6":"Son 9",
      "Player_7":"Raphinha 2",
      "Player_8":"Bowen 3",
      "Player_9":"Jiménez 1",
      "Player_10":"Weghorst 4, LEI (H)$ captain",
      "Player_11":"Broja 2",
      "Player_12":"Ramsdale -",
      "Player_13":"Robertson -",
      "Player_14":"Alexander-Arnold -",
      "Player_15":"Salah -",
      "SXL":"40",
      "Bench":"1619",
      "Count  ":"442,594"
   },
   {
      "manager_Name":"Harsh Raval",
      "Teams":"Up the Bees",
      "Player_1":"Pope 3, LEI (H)",
      "Player_2":"Livramento 8",
      "Player_3":"Cancelo 9",
      "Player_4":"Telles 9",
      "Player_5":"Mee 2, LEI (H)",
      "Player_6":"Sterling 3",
      "Player_7":"De Bruyne 3",
      "Player_8":"Son 9",
      "Player_9":"Kane 22$ captain",
      "Player_10":"Weghorst 2, LEI (H)",
      "Player_11":"Broja 2",
      "Player_12":"Foster 10",
      "Player_13":"Elanga 3",
      "Player_14":"Kulusevski 8",
      "Player_15":"Amartey BUR (A)",
      "SXL":"72",
      "Bench":"1767",
      "Count  ":"34,819"
   },
   {
      "manager_Name":"PRAYAS BAJGAI",
      "Teams":"MCFC@1894",
      "Player_1":"Pope 3, LEI (H)",
      "Player_2":"Cresswell 7",
      "Player_3":"Cancelo 9",
      "Player_4":"Mee 2, LEI (H)",
      "Player_5":"Mahrez 1",
      "Player_6":"Sterling 3",
      "Player_7":"Sancho 1",
      "Player_8":"Son 18$ captain",
      "Player_9":"Broja 2",
      "Player_10":"Weghorst 2, LEI (H)",
      "Player_11":"Kane 11",
      "Player_12":"McGovern 0",
      "Player_13":"Elyounoussi 3",
      "Player_14":"Bednarek 6",
      "Player_15":"Tsimikas -",
      "SXL":"59",
      "Bench":"1746",
      "Count  ":"60,084"
   },
   {
      "manager_Name":"AVIJIT DAS",
      "Teams":"Roing FC",
      "Player_1":"Forster 6",
      "Player_2":"Roberts 2, LEI (H)",
      "Player_3":"Mee 2, LEI (H)",
      "Player_4":"Cancelo 9",
      "Player_5":"Fernandes 3",
      "Player_6":"Son 9",
      "Player_7":"Foden 7",
      "Player_8":"Sterling 3",
      "Player_9":"Kane 11",
      "Player_10":"Broja 2",
      "Player_11":"Weghorst 4, LEI (H)$ captain",
      "Player_12":"McGovern 0",
      "Player_13":"Bednarek 6",
      "Player_14":"Gilmour 2",
      "Player_15":"Tsimikas -",
      "SXL":"58",
      "Bench":"1708",
      "Count  ":"130,211"
   },
   {
      "manager_Name":"Abhijeet Singh",
      "Teams":"WEIGHTLOSS COACH",
      "Player_1":"Forster 6",
      "Player_2":"Veltman 0",
      "Player_3":"Alexander-Arnold -",
      "Player_4":"Mee 2, LEI (H)",
      "Player_5":"Bowen 3",
      "Player_6":"Olise 8",
      "Player_7":"Son 9",
      "Player_8":"Coutinho 3",
      "Player_9":"Weghorst 4, LEI (H)$ captain",
      "Player_10":"Adams 6",
      "Player_11":"Jiménez 1",
      "Player_12":"Ramsdale -",
      "Player_13":"Salah -",
      "Player_14":"Matip -",
      "Player_15":"Tierney -",
      "SXL":"42",
      "Bench":"1734",
      "Count  ":"78,346"
   },
   {
      "manager_Name":"SATYAM RAI",
      "Teams":"PINE",
      "Player_1":"Foster 10",
      "Player_2":"Digne 6",
      "Player_3":"Cancelo 9",
      "Player_4":"Livramento 8",
      "Player_5":"Gallagher 2",
      "Player_6":"Son 9",
      "Player_7":"Fernandes 3",
      "Player_8":"Bowen 3",
      "Player_9":"Dennis 2",
      "Player_10":"Jiménez 1",
      "Player_11":"Weghorst 4, LEI (H)$ captain",
      "Player_12":"Ramsdale -",
      "Player_13":"Alonso -",
      "Player_14":"Saka -",
      "Player_15":"Alexander-Arnold -",
      "SXL":"57",
      "Bench":"1738",
      "Count  ":"72,343"
   }
]