var s = [{
	"manager_Name": "Nishant Singh",
	"Teams": "beta 11",
	"Player_1": "Martínez -",
	"Player_2": "Zouma LEE (H)",
	"Player_3": "Chilwell LEE (H)",
	"Player_4": "Cresswell 1",
	"Player_5": "Bellerín TOT (A)",
	"Player_6": "Grealish -",
	"Player_7": "Fernandes 4",
	"Player_8": "Son ARS (H)$ captain",
	"Player_9": "Zaha WBA (A)",
	"Player_10": "Kane ARS (H)",
	"Player_11": "Calvert-Lewin 6",
	"Player_12": "McCarthy BHA (A)",
	"Player_13": "Wilson -",
	"Player_14": "Alzate SOU (H)",
	"Player_15": "Douglas CHE (A)",
	"SXL": "11",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "Rohan Rai",
	"Teams": "FALSE 9",
	"Player_1": "Ryan SOU (H)",
	"Player_2": "Coufal 1",
	"Player_3": "Taylor 2",
	"Player_4": "Justin SHU (A)",
	"Player_5": "Fernandes 4",
	"Player_6": "De Bruyne 22$ captain",
	"Player_7": "Ziyech LEE (H)",
	"Player_8": "Podence LIV (A)",
	"Player_9": "Son ARS (H)",
	"Player_10": "Calvert-Lewin 6",
	"Player_11": "Vardy SHU (A)",
	"Player_12": "Martínez -",
	"Player_13": "Kilman LIV (A)",
	"Player_14": "Dunne 0",
	"Player_15": "Davis -",
	"SXL": "35",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "Avijit Das",
	"Teams": "WeAreTheArsenal",
	"Player_1": "McCarthy BHA (A)",
	"Player_2": "Chilwell LEE (H)",
	"Player_3": "Cancelo 6",
	"Player_4": "Walker-Peters BHA (A)",
	"Player_5": "De Bruyne 22$ captain",
	"Player_6": "Son ARS (H)",
	"Player_7": "Fernandes 4",
	"Player_8": "Ziyech LEE (H)",
	"Player_9": "Bamford CHE (A)",
	"Player_10": "Calvert-Lewin 6",
	"Player_11": "Kane ARS (H)",
	"Player_12": "Steer -",
	"Player_13": "Bissouma SOU (H)",
	"Player_14": "Ayling CHE (A)",
	"Player_15": "Mitchell WBA (A)",
	"SXL": "38",
	"Bench": "0",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "Gaurav Shrestha",
	"Teams": "Fußball-Mannschaft",
	"Player_1": "Martínez -",
	"Player_2": "Zouma LEE (H)",
	"Player_3": "Robertson WOL (H)",
	"Player_4": "Lamptey SOU (H)",
	"Player_5": "Salah WOL (H)",
	"Player_6": "Mahrez 3",
	"Player_7": "De Bruyne 22$ captain",
	"Player_8": "Jota WOL (H)",
	"Player_9": "Grealish -",
	"Player_10": "Watkins -",
	"Player_11": "Calvert-Lewin 6",
	"Player_12": "Forster BHA (A)",
	"Player_13": "Bamford CHE (A)",
	"Player_14": "Dallas CHE (A)",
	"Player_15": "Mitchell WBA (A)",
	"SXL": "31",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "Dipen Thapa",
	"Teams": "Lokipower Reloaded",
	"Player_1": "McCarthy BHA (A)",
	"Player_2": "Taylor 2",
	"Player_3": "Gabriel TOT (A)",
	"Player_4": "Mitchell WBA (A)",
	"Player_5": "Salah WOL (H)$ captain",
	"Player_6": "Fernandes 4",
	"Player_7": "Ward-Prowse BHA (A)",
	"Player_8": "Son ARS (H)",
	"Player_9": "Calvert-Lewin 6",
	"Player_10": "Werner LEE (H)",
	"Player_11": "Bamford CHE (A)",
	"Player_12": "Martínez -",
	"Player_13": "Costa CHE (A)",
	"Player_14": "Mings -",
	"Player_15": "Dunne 0",
	"SXL": "12",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "Sibin _",
	"Teams": "FortunaDüsseldorfer",
	"Player_1": "Guaita WBA (A)",
	"Player_2": "Chilwell LEE (H)",
	"Player_3": "Dias 6",
	"Player_4": "Tierney TOT (A)",
	"Player_5": "Zaha WBA (A)",
	"Player_6": "Son ARS (H)",
	"Player_7": "Jota WOL (H)",
	"Player_8": "Fernandes 8$ captain",
	"Player_9": "Bamford CHE (A)",
	"Player_10": "Kane ARS (H)",
	"Player_11": "Richarlison 5",
	"Player_12": "Ramsdale LEI (H)",
	"Player_13": "Keane 2",
	"Player_14": "Alderweireld ARS (H)",
	"Player_15": "Oriol Romeu BHA (A)",
	"SXL": "19",
	"Bench": "2",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "Kushal Sahota",
	"Teams": "FC ASSASSINS",
	"Player_1": "Schmeichel SHU (A)",
	"Player_2": "Lamptey SOU (H)",
	"Player_3": "Zouma LEE (H)",
	"Player_4": "Alioski CHE (A)",
	"Player_5": "Ward-Prowse BHA (A)",
	"Player_6": "Son ARS (H)",
	"Player_7": "Ziyech LEE (H)",
	"Player_8": "Salah WOL (H)$ captain",
	"Player_9": "Calvert-Lewin 6",
	"Player_10": "Kane ARS (H)",
	"Player_11": "Werner LEE (H)",
	"Player_12": "Ryan SOU (H)",
	"Player_13": "Oriol Romeu BHA (A)",
	"Player_14": "Mitchell WBA (A)",
	"Player_15": "Bernardo SOU (H)",
	"SXL": "6",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "SATYAM RAI",
	"Teams": "PINE",
	"Player_1": "Martínez -",
	"Player_2": "Cancelo 6",
	"Player_3": "Chilwell LEE (H)",
	"Player_4": "Justin SHU (A)",
	"Player_5": "Fernandes 4",
	"Player_6": "Mahrez 3",
	"Player_7": "Ziyech LEE (H)",
	"Player_8": "De Bruyne 22$ captain",
	"Player_9": "Watkins -",
	"Player_10": "Vardy SHU (A)",
	"Player_11": "Calvert-Lewin 6",
	"Player_12": "Peacock-Farrell 0",
	"Player_13": "Soucek 7",
	"Player_14": "Neco Williams WOL (H)",
	"Player_15": "Coufal 1",
	"SXL": "41",
	"Bench": "8",
	"Count  ": "4( 3+1 )"
}, {
	"manager_Name": "ashim lama",
	"Teams": "⚔️FURY⚔️",
	"Player_1": "Martínez -",
	"Player_2": "Walker-Peters BHA (A)",
	"Player_3": "Chilwell LEE (H)",
	"Player_4": "Robertson WOL (H)",
	"Player_5": "Justin SHU (A)",
	"Player_6": "Mitchell WBA (A)",
	"Player_7": "De Bruyne 11",
	"Player_8": "Son ARS (H)",
	"Player_9": "Ziyech LEE (H)$ captain",
	"Player_10": "Werner LEE (H)",
	"Player_11": "Calvert-Lewin 6",
	"Player_12": "Martin 0",
	"Player_13": "Podence LIV (A)",
	"Player_14": "Watkins -",
	"Player_15": "Barkley -",
	"SXL": "17",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "Indrajeet Singh",
	"Teams": "Kung fu Pandoos",
	"Player_1": "Meslier CHE (A)",
	"Player_2": "Walker-Peters BHA (A)",
	"Player_3": "Zouma LEE (H)",
	"Player_4": "Webster SOU (H)",
	"Player_5": "Walker 0",
	"Player_6": "Salah WOL (H)$ captain",
	"Player_7": "Son ARS (H)",
	"Player_8": "Pereira CRY (H)",
	"Player_9": "Aubameyang TOT (A)",
	"Player_10": "Bamford CHE (A)",
	"Player_11": "Kane ARS (H)",
	"Player_12": "Henderson WBA (A)",
	"Player_13": "Wilson -",
	"Player_14": "Targett -",
	"Player_15": "Reed 2",
	"SXL": "0",
	"Bench": "2",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Vivek Lama",
	"Teams": "JOJOs LFC",
	"Player_1": "Alisson WOL (H)",
	"Player_2": "Saïss LIV (A)",
	"Player_3": "Alexander-Arnold WOL (H)",
	"Player_4": "Walker-Peters BHA (A)",
	"Player_5": "Tielemans SHU (A)",
	"Player_6": "Son ARS (H)",
	"Player_7": "Sterling 11",
	"Player_8": "Mané WOL (H)$ captain",
	"Player_9": "Connolly SOU (H)",
	"Player_10": "Adams BHA (A)",
	"Player_11": "Bamford CHE (A)",
	"Player_12": "Ryan SOU (H)",
	"Player_13": "Saint-Maximin -",
	"Player_14": "Egan LEI (H)",
	"Player_15": "Dunne 0",
	"SXL": "11",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "Prabin Singh",
	"Teams": "Random XI",
	"Player_1": "Schmeichel SHU (A)",
	"Player_2": "Vestergaard BHA (A)",
	"Player_3": "Cancelo 6",
	"Player_4": "Justin SHU (A)",
	"Player_5": "Mitchell WBA (A)",
	"Player_6": "Son ARS (H)",
	"Player_7": "Mahrez 3",
	"Player_8": "Costa CHE (A)",
	"Player_9": "Jota WOL (H)",
	"Player_10": "Calvert-Lewin 12$ captain",
	"Player_11": "Kane ARS (H)",
	"Player_12": "Macey TOT (A)",
	"Player_13": "Wilson -",
	"Player_14": "Grealish -",
	"Player_15": "Dunne 0",
	"SXL": "21",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "Kumar Anku",
	"Teams": "Galaxies Stars",
	"Player_1": "Mendy LEE (H)",
	"Player_2": "Bellerín TOT (A)",
	"Player_3": "Laporte 0",
	"Player_4": "Kilman LIV (A)",
	"Player_5": "Walker-Peters BHA (A)",
	"Player_6": "Sterling 11",
	"Player_7": "Son ARS (H)",
	"Player_8": "Jota WOL (H)",
	"Player_9": "Mahrez 3",
	"Player_10": "Vardy SHU (A)$ captain",
	"Player_11": "Werner LEE (H)",
	"Player_12": "Forster BHA (A)",
	"Player_13": "Ritchie -",
	"Player_14": "Targett -",
	"Player_15": "Watkins -",
	"SXL": "14",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "Okdenri Longchari",
	"Teams": "Happy Williams",
	"Player_1": "McCarthy BHA (A)",
	"Player_2": "Walker-Peters BHA (A)",
	"Player_3": "Dias 6",
	"Player_4": "Mitchell WBA (A)",
	"Player_5": "Lamptey SOU (H)",
	"Player_6": "Podence LIV (A)",
	"Player_7": "Salah WOL (H)",
	"Player_8": "Fernandes 8$ captain",
	"Player_9": "Sterling 11",
	"Player_10": "Calvert-Lewin 6",
	"Player_11": "Mitrović 0",
	"Player_12": "Martínez -",
	"Player_13": "Grealish -",
	"Player_14": "Watkins -",
	"Player_15": "Coufal 1",
	"SXL": "31",
	"Bench": "1",
	"Count  ": "4( 4+0 )"
}, {
	"manager_Name": "Omkar Subba",
	"Teams": "Omk09",
	"Player_1": "McCarthy BHA (A)",
	"Player_2": "James LEE (H)",
	"Player_3": "Robertson WOL (H)",
	"Player_4": "Zouma LEE (H)",
	"Player_5": "Justin SHU (A)",
	"Player_6": "Jota WOL (H)",
	"Player_7": "Ziyech LEE (H)",
	"Player_8": "Son ARS (H)",
	"Player_9": "Fernandes 8$ captain",
	"Player_10": "Bamford CHE (A)",
	"Player_11": "Calvert-Lewin 6",
	"Player_12": "Nyland -",
	"Player_13": "Mitchell WBA (A)",
	"Player_14": "Grealish -",
	"Player_15": "Jiménez LIV (A)",
	"SXL": "14",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "Abhijeet Singh",
	"Teams": "Impact Creators",
	"Player_1": "McCarthy BHA (A)",
	"Player_2": "Vestergaard BHA (A)",
	"Player_3": "Cresswell 1",
	"Player_4": "Zouma LEE (H)",
	"Player_5": "Fernandes 4",
	"Player_6": "Ziyech LEE (H)",
	"Player_7": "Son ARS (H)",
	"Player_8": "De Bruyne 22$ captain",
	"Player_9": "Calvert-Lewin 6",
	"Player_10": "Bamford CHE (A)",
	"Player_11": "Kane ARS (H)",
	"Player_12": "Martin 0",
	"Player_13": "Balbuena 1",
	"Player_14": "Riedewald WBA (A)",
	"Player_15": "Kilman LIV (A)",
	"SXL": "33",
	"Bench": "1",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "Ashish Subba",
	"Teams": "GUSTAVOUS GUNNER",
	"Player_1": "Pickford 2",
	"Player_2": "Justin SHU (A)",
	"Player_3": "Chilwell LEE (H)",
	"Player_4": "Vestergaard BHA (A)",
	"Player_5": "Mitchell WBA (A)",
	"Player_6": "Ward-Prowse BHA (A)",
	"Player_7": "Mané WOL (H)",
	"Player_8": "De Bruyne 22$ captain",
	"Player_9": "Klich CHE (A)",
	"Player_10": "Werner LEE (H)",
	"Player_11": "Kane ARS (H)",
	"Player_12": "Martínez -",
	"Player_13": "Dunne 0",
	"Player_14": "Grealish -",
	"Player_15": "Davis -",
	"SXL": "24",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "Nitesh Singh",
	"Teams": "Danapur United",
	"Player_1": "Ryan SOU (H)",
	"Player_2": "Justin SHU (A)",
	"Player_3": "Chilwell LEE (H)",
	"Player_4": "Robertson WOL (H)",
	"Player_5": "Tielemans SHU (A)",
	"Player_6": "Jota WOL (H)",
	"Player_7": "Son ARS (H)",
	"Player_8": "Fernandes 8$ captain",
	"Player_9": "Bamford CHE (A)",
	"Player_10": "Werner LEE (H)",
	"Player_11": "Kane ARS (H)",
	"Player_12": "Martínez -",
	"Player_13": "Struijk CHE (A)",
	"Player_14": "Harper CRY (H)",
	"Player_15": "Buur LIV (A)",
	"SXL": "8",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "Raj Kanango",
	"Teams": "Dream Killer",
	"Player_1": "Johnstone CRY (H)",
	"Player_2": "Chilwell LEE (H)",
	"Player_3": "Walker 0",
	"Player_4": "Justin SHU (A)",
	"Player_5": "Mahrez 3",
	"Player_6": "Jota WOL (H)",
	"Player_7": "Son ARS (H)",
	"Player_8": "Mané WOL (H)",
	"Player_9": "Calvert-Lewin 6",
	"Player_10": "Maupay SOU (H)",
	"Player_11": "Vardy SHU (A)$ captain",
	"Player_12": "Pope 3",
	"Player_13": "Oriol Romeu BHA (A)",
	"Player_14": "Branthwaite 0",
	"Player_15": "Bardsley 0",
	"SXL": "9",
	"Bench": "3",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "Sahil Lampard",
	"Teams": "Marx 11",
	"Player_1": "Ryan SOU (H)",
	"Player_2": "Robertson WOL (H)",
	"Player_3": "Bertrand BHA (A)",
	"Player_4": "Chilwell LEE (H)",
	"Player_5": "Reguilón ARS (H)",
	"Player_6": "Jota WOL (H)",
	"Player_7": "Son ARS (H)",
	"Player_8": "Fernandes 8$ captain",
	"Player_9": "Foden 0",
	"Player_10": "Calvert-Lewin 6",
	"Player_11": "Kane ARS (H)",
	"Player_12": "Martínez -",
	"Player_13": "Grealish -",
	"Player_14": "Delap 0",
	"Player_15": "Casey CHE (A)",
	"SXL": "14",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "Pema Sherpa",
	"Teams": "CottonMouth XI",
	"Player_1": "Martínez -",
	"Player_2": "Mitchell WBA (A)",
	"Player_3": "Chilwell LEE (H)",
	"Player_4": "Cancelo 6",
	"Player_5": "Son ARS (H)",
	"Player_6": "Ziyech LEE (H)",
	"Player_7": "Foden 0",
	"Player_8": "Salah WOL (H)$ captain",
	"Player_9": "Bamford CHE (A)",
	"Player_10": "Kane ARS (H)",
	"Player_11": "Calvert-Lewin 6",
	"Player_12": "Button CRY (H)",
	"Player_13": "Phillips CHE (A)",
	"Player_14": "Castagne SHU (A)",
	"Player_15": "Saïss LIV (A)",
	"SXL": "12",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "pranam rai",
	"Teams": "SYAKREE F.C.",
	"Player_1": "Martínez -",
	"Player_2": "James LEE (H)",
	"Player_3": "Robertson WOL (H)",
	"Player_4": "Lamptey SOU (H)",
	"Player_5": "Fernandes 4",
	"Player_6": "Jota WOL (H)",
	"Player_7": "Grealish -$ captain",
	"Player_8": "Son ARS (H)",
	"Player_9": "Bamford CHE (A)",
	"Player_10": "Werner LEE (H)",
	"Player_11": "Calvert-Lewin 6",
	"Player_12": "Guaita WBA (A)",
	"Player_13": "Foden 0",
	"Player_14": "Kilman LIV (A)",
	"Player_15": "Castagne SHU (A)",
	"SXL": "10",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "Regean Lama",
	"Teams": "Busby Baby",
	"Player_1": "McCarthy BHA (A)",
	"Player_2": "Walker-Peters BHA (A)",
	"Player_3": "Chilwell LEE (H)",
	"Player_4": "Justin SHU (A)",
	"Player_5": "De Bruyne 22$ captain",
	"Player_6": "Son ARS (H)",
	"Player_7": "Rodríguez 2",
	"Player_8": "Fernandes 4",
	"Player_9": "Podence LIV (A)",
	"Player_10": "Bamford CHE (A)",
	"Player_11": "Kane ARS (H)",
	"Player_12": "Steer -",
	"Player_13": "Brewster LEI (H)",
	"Player_14": "Taylor 2",
	"Player_15": "Douglas CHE (A)",
	"SXL": "28",
	"Bench": "2",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "Han Sing",
	"Teams": "hansing",
	"Player_1": "McCarthy BHA (A)",
	"Player_2": "Vestergaard BHA (A)",
	"Player_3": "Chilwell LEE (H)",
	"Player_4": "Zouma LEE (H)",
	"Player_5": "Mitchell WBA (A)",
	"Player_6": "Salah WOL (H)",
	"Player_7": "Fernandes 4",
	"Player_8": "Son ARS (H)$ captain",
	"Player_9": "Calvert-Lewin 6",
	"Player_10": "Bamford CHE (A)",
	"Player_11": "Kane ARS (H)",
	"Player_12": "Nyland -",
	"Player_13": "Coufal 1",
	"Player_14": "Anguissa 2",
	"Player_15": "Grealish -",
	"SXL": "10",
	"Bench": "3",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "Sanjeev Kumar",
	"Teams": "mendal11",
	"Player_1": "Mendy LEE (H)",
	"Player_2": "Vestergaard BHA (A)",
	"Player_3": "Justin SHU (A)",
	"Player_4": "James LEE (H)",
	"Player_5": "Zaha WBA (A)$ captain",
	"Player_6": "Ward-Prowse BHA (A)",
	"Player_7": "Son ARS (H)",
	"Player_8": "Salah WOL (H)",
	"Player_9": "Kane ARS (H)",
	"Player_10": "Adams BHA (A)",
	"Player_11": "Richarlison 5",
	"Player_12": "Steer -",
	"Player_13": "Coufal 1",
	"Player_14": "Grealish -",
	"Player_15": "Targett -",
	"SXL": "5",
	"Bench": "1",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "Ashish Rai",
	"Teams": "goooooooners",
	"Player_1": "Leno TOT (A)",
	"Player_2": "Cresswell 1",
	"Player_3": "Dallas CHE (A)",
	"Player_4": "Bednarek BHA (A)",
	"Player_5": "Bowen 2",
	"Player_6": "Rodríguez 2",
	"Player_7": "Aubameyang TOT (A)",
	"Player_8": "Salah WOL (H)",
	"Player_9": "Oriol Romeu BHA (A)",
	"Player_10": "Werner LEE (H)",
	"Player_11": "Jesus 4$ captain",
	"Player_12": "Nyland -",
	"Player_13": "Watkins -",
	"Player_14": "Lascelles -",
	"Player_15": "Branthwaite 0",
	"SXL": "9",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": "Ravish Verma",
	"Teams": "Jatt Da Muqaabla FC",
	"Player_1": "McCarthy BHA (A)",
	"Player_2": "Walker-Peters BHA (A)",
	"Player_3": "Justin SHU (A)",
	"Player_4": "Walker 0",
	"Player_5": "Fernandes 8$ captain",
	"Player_6": "Grealish -",
	"Player_7": "Jota WOL (H)",
	"Player_8": "Salah WOL (H)",
	"Player_9": "Calvert-Lewin 6",
	"Player_10": "Maupay SOU (H)",
	"Player_11": "Kane ARS (H)",
	"Player_12": "Steer -",
	"Player_13": "Neco Williams WOL (H)",
	"Player_14": "Bellerín TOT (A)",
	"Player_15": "Reed 2",
	"SXL": "14",
	"Bench": "2",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "Bishal Rai",
	"Teams": "Gooner for Life",
	"Player_1": "Ryan SOU (H)",
	"Player_2": "Justin SHU (A)",
	"Player_3": "Chilwell LEE (H)",
	"Player_4": "Lamptey SOU (H)",
	"Player_5": "Zaha WBA (A)",
	"Player_6": "Rodríguez 2",
	"Player_7": "Son ARS (H)",
	"Player_8": "Salah WOL (H)",
	"Player_9": "Bamford CHE (A)",
	"Player_10": "Vardy SHU (A)$ captain",
	"Player_11": "Calvert-Lewin 6",
	"Player_12": "Martínez -",
	"Player_13": "Branthwaite 0",
	"Player_14": "Targett -",
	"Player_15": "Grealish -",
	"SXL": "8",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}]