var s = [
  {
    "manager_Name": "807( 40,493 ) TotalXfr : 13",
    "Teams": "FC Pek( Erik Lindberg )",
    "SXL": "Sweden",
    "Latp": "31",
    "Player_1": "Henderson\r 2",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Wissa\r 6",
    "Player_12": "Turner\r 0",
    "Player_13": "Digne\r CHE (A)",
    "Player_14": "Faes\r 0",
    "Player_7": "Mbeumo\r 4",
    "Player_2": "Gvardiol\r LIV (A)",
    "Player_5": "Mitoma\r 10",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Rogers\r CHE (A)",
    "Player_9": "Solanke\r FUL (H)",
    "Player_15": "Winks\r 0"
  },
  {
    "manager_Name": "825( 12,833 ) TotalXfr : 11",
    "Teams": "Lorrainesson( Lorraine Busuttil )",
    "SXL": "Malta",
    "Latp": "45",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Strand Larsen\r 9",
    "Player_12": "Lumley\r 3",
    "Player_13": "Davis\r 2",
    "Player_14": "Okoli\r 0",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Hall\r 2",
    "Player_5": "Saka\r 15",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Gabriel\r 9",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Semenyo\r 0"
  },
  {
    "manager_Name": "774( 204,231 ) TotalXfr : 11",
    "Teams": "The Bees( Tove Ronneb\u00E4ck )",
    "SXL": "Malta",
    "Latp": "22",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Wissa\r 6",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Konat\u00E9\r MCI (H)",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Rogers\r CHE (A)",
    "Player_3": "Gvardiol\r LIV (A)",
    "Player_4": "Gabriel\r 9",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Cunha\r 2",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "747( 571,033 ) TotalXfr : 12",
    "Teams": "NoHopeFC( John Maguire )",
    "SXL": "Malta",
    "Latp": "10",
    "Player_1": "Flekken\r 2",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Konat\u00E9\r MCI (H)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Robinson\r TOT (A)",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Davis\r 2",
    "Player_4": "Digne\r CHE (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Maddison\r FUL (H)",
    "Player_15": "Marc Guiu\r AVL (H)"
  },
  {
    "manager_Name": "754( 445,860 ) TotalXfr : 11",
    "Teams": "Los Blancos( Eamonn Mifsud )",
    "SXL": "Malta",
    "Latp": "20",
    "Player_1": "Raya\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Konsa\r CHE (A)",
    "Player_7": "Son\r FUL (H)",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Van den Berg\r 2",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Isak\r 1",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "780( 156,992 ) TotalXfr : 11",
    "Teams": "Fantasikonungen( Albin Jonsson )",
    "SXL": "Malta",
    "Latp": "47",
    "Player_1": "Jos\u00E9 S\u00E1\r 0",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Digne\r CHE (A)",
    "Player_14": "Konat\u00E9\r MCI (H)",
    "Player_7": "Saka\r 30",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Hall\r 2",
    "Player_4": "Gabriel\r 9",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Delap\r 2",
    "Player_15": "Semenyo\r 0"
  },
  {
    "manager_Name": "749( 527,155 ) TotalXfr : 9",
    "Teams": "Lallish United( Melwin Holst )",
    "SXL": "Sweden",
    "Latp": "19",
    "Player_1": "Raya\r 2",
    "Player_11": "H\u00F8jlund\r EVE (H)",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Dalot\r EVE (H)",
    "Player_14": "Davis\r 2",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Son\r FUL (H)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Van Hecke\r 2",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Rogers\r CHE (A)"
  },
  {
    "manager_Name": "750( 510,256 ) TotalXfr : 10",
    "Teams": "Udogie\u0027s Doggies( Claude Taliana )",
    "SXL": "Malta",
    "Latp": "25",
    "Player_1": "Flekken\r 2",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Wood\r 6",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Barnes\r 2",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Georginio\r 2",
    "Player_2": "Aina\r 6",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "Dalot\r EVE (H)",
    "Player_8": "Rogers\r CHE (A)",
    "Player_9": "Strand Larsen\r 9",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "741( 695,285 ) TotalXfr : 13",
    "Teams": "Salahvation Army( Tom Atkinson )",
    "SXL": "Malta",
    "Latp": "31",
    "Player_1": "Pope\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Slicker\r 0",
    "Player_13": "Lewis\r LIV (A)",
    "Player_14": "Winks\r 0",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Gvardiol\r LIV (A)",
    "Player_5": "Rogers\r CHE (A)",
    "Player_6": "Mitoma\r 10",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Collins\r 5",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "726( 1,057,202 ) TotalXfr : 10",
    "Teams": "klopp notch( Tobias Nocke )",
    "SXL": "Sweden",
    "Latp": "16",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Solanke\r FUL (H)",
    "Player_12": "Kelleher\r MCI (H)",
    "Player_13": "Ayari\r 2",
    "Player_14": "Konat\u00E9\r MCI (H)",
    "Player_7": "\u00D8degaard\r 7",
    "Player_2": "Van den Berg\r 2",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Foden\r LIV (A)",
    "Player_3": "Estupi\u00F1an\r 4",
    "Player_4": "Digne\r CHE (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Ra\u00FAl\r TOT (A)",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "722( 1,182,901 ) TotalXfr : 12",
    "Teams": "MainooInTheBank( Thanasis Fouras )",
    "SXL": "Greece",
    "Latp": "15",
    "Player_1": "Henderson\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Wood\r 6",
    "Player_12": "Matthews\r 0",
    "Player_13": "Faes\r 0",
    "Player_14": "Winks\r 0",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Digne\r CHE (A)",
    "Player_5": "Gordon\r 5",
    "Player_6": "Johnson\r FUL (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Robinson\r TOT (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Haaland\r LIV (A)",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "715( 1,410,301 ) TotalXfr : 13",
    "Teams": "Gidia KK( Aggelos Flamiatos )",
    "SXL": "Greece",
    "Latp": "14",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Welbeck\r 4",
    "Player_12": "Flekken\r 2",
    "Player_13": "McNeil\r MUN (A)",
    "Player_14": "Burn\r 2",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Murillo\r 6",
    "Player_5": "Maddison\r FUL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Rogers\r CHE (A)",
    "Player_9": "Solanke\r FUL (H)",
    "Player_15": "Robinson\r TOT (A)"
  },
  {
    "manager_Name": "735( 820,290 ) TotalXfr : 9",
    "Teams": "Kinder Mbeumo( Gerson Seguna )",
    "SXL": "Malta",
    "Latp": "43",
    "Player_1": "Raya\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "O\u0027Shea\r 1",
    "Player_14": "Rogers\r CHE (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Alexander-Arnold\r MCI (H)",
    "Player_5": "Mitoma\r 10",
    "Player_6": "Saka\r 15",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Milenkovi\u0107\r 6",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Wood\r 6",
    "Player_15": "Hall\r 2"
  },
  {
    "manager_Name": "715( 1,410,301 ) TotalXfr : 13",
    "Teams": "Ajax CT( Dimitrios Siderakis )",
    "SXL": "Malta",
    "Latp": "11",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Watkins\r CHE (A)",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Carvalho\r 1",
    "Player_14": "Welbeck\r 2",
    "Player_7": "Luis D\u00EDaz\r MCI (H)",
    "Player_2": "Gu\u00E9hi\r 2",
    "Player_5": "Pedro Porro\r FUL (H)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "Saliba\r 1",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "M.Salah\r MCI (H)",
    "Player_15": "Murillo\r 6"
  },
  {
    "manager_Name": "711( 1,531,874 ) TotalXfr : 10",
    "Teams": "Gambit( Nicola Frasca )",
    "SXL": "Malta",
    "Latp": "12",
    "Player_1": "Pickford\r MUN (A)",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Greaves\r 0",
    "Player_14": "Winks\r 0",
    "Player_7": "Yarmoliuk\r 1",
    "Player_2": "Gvardiol\r LIV (A)",
    "Player_5": "Pedro Porro\r FUL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Martinez\r EVE (H)",
    "Player_8": "Smith Rowe\r TOT (A)",
    "Player_9": "Palmer\r AVL (H)",
    "Player_15": "Ings\r 1"
  },
  {
    "manager_Name": "732( 894,526 ) TotalXfr : 9",
    "Teams": "JDT Out( Filip Larsson )",
    "SXL": "Malta",
    "Latp": "34",
    "Player_1": "Flekken\r 2",
    "Player_11": "Wood\r 12",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Lewis\r LIV (A)",
    "Player_14": "Semenyo\r 0",
    "Player_7": "Rogers\r CHE (A)",
    "Player_2": "Aina\r 6",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Gabriel\r 9",
    "Player_4": "J.Timber\r 1",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Haaland\r LIV (A)",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "706( 1,731,520 ) TotalXfr : 14",
    "Teams": "Guglielmo( Jonas Megert )",
    "SXL": "Sweden",
    "Latp": "12",
    "Player_1": "Martinez\r CHE (A)",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Wood\r 6",
    "Player_12": "Turner\r 0",
    "Player_13": "Winks\r 0",
    "Player_14": "Quansah\r MCI (H)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Pedro Porro\r FUL (H)",
    "Player_5": "Smith Rowe\r TOT (A)",
    "Player_6": "Johnson\r FUL (H)",
    "Player_3": "Konsa\r CHE (A)",
    "Player_4": "Lewis\r LIV (A)",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Welbeck\r 4",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "718( 1,301,466 ) TotalXfr : 11",
    "Teams": "Crvena Zvezda( Dejan Mrdanov )",
    "SXL": "Malta",
    "Latp": "23",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 2",
    "Player_10": "Wood\r 6",
    "Player_12": "Areola\r 0",
    "Player_13": "Hudson-Odoi\r 3",
    "Player_14": "Colwill\r AVL (H)",
    "Player_7": "Garnacho\r EVE (H)",
    "Player_2": "Tarkowski\r MUN (A)",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Luis D\u00EDaz\r MCI (H)",
    "Player_3": "Digne\r CHE (A)",
    "Player_4": "Gabriel\r 9",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Cunha\r 2",
    "Player_15": "Pedro Porro\r FUL (H)"
  },
  {
    "manager_Name": "712( 1,507,148 ) TotalXfr : 12",
    "Teams": "Tourinho FC( Alexis Touris )",
    "SXL": "Greece",
    "Latp": "17",
    "Player_1": "Martinez\r CHE (A)",
    "Player_11": "Isak\r 1",
    "Player_10": "Watkins\r CHE (A)",
    "Player_12": "Henderson\r 2",
    "Player_13": "Gvardiol\r LIV (A)",
    "Player_14": "Andersen\r TOT (A)",
    "Player_7": "Bowen\r 2",
    "Player_2": "Dalot\r EVE (H)",
    "Player_5": "Johnson\r FUL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "Aina\r 6",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Wood\r 6",
    "Player_15": "Adama\r TOT (A)"
  },
  {
    "manager_Name": "714( 1,443,826 ) TotalXfr : 13",
    "Teams": "ThereWeLand( Haykel Mansour )",
    "SXL": "Malta",
    "Latp": "21",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Cunha\r 2",
    "Player_10": "Isak\r 1",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "Kulusevski\r FUL (H)",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Mbeumo\r 4",
    "Player_3": "Collins\r 5",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Rashford\r EVE (H)",
    "Player_9": "Haaland\r LIV (A)",
    "Player_15": "Nedeljkovic\r CHE (A)"
  },
  {
    "manager_Name": "689( 2,398,723 ) TotalXfr : 11",
    "Teams": "Hakuna Mateta( Jason Evans )",
    "SXL": "Malta",
    "Latp": "12",
    "Player_1": "Martinez\r CHE (A)",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Turner\r 0",
    "Player_13": "Carvalho\r 1",
    "Player_14": "Barco\r 0",
    "Player_7": "Kulusevski\r FUL (H)",
    "Player_2": "Alexander-Arnold\r MCI (H)",
    "Player_5": "Mitoma\r 10",
    "Player_6": "Rogers\r CHE (A)",
    "Player_3": "Gvardiol\r LIV (A)",
    "Player_4": "Romero\r FUL (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Thomas\r 0"
  },
  {
    "manager_Name": "701( 1,926,387 ) TotalXfr : 16",
    "Teams": "Biancoverde Utd 4.0( Michael Keramas )",
    "SXL": "Greece",
    "Latp": "15",
    "Player_1": "Flekken\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Isak\r 1",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Mbeumo\r 2",
    "Player_14": "Aina\r 6",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gvardiol\r LIV (A)",
    "Player_5": "B.Fernandes\r EVE (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Robinson\r TOT (A)",
    "Player_8": "Kulusevski\r FUL (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "693( 2,218,340 ) TotalXfr : 5",
    "Teams": "Nachos( Melvin Xuereb )",
    "SXL": "Malta",
    "Latp": "8",
    "Player_1": "Areola\r 0",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Calvert-Lewin\r MUN (A)",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Semenyo\r 0",
    "Player_14": "Estupi\u00F1an\r 4",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "Eze\r 2",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Andersen\r TOT (A)",
    "Player_4": "Saliba\r 1",
    "Player_8": "Damsgaard\r 5",
    "Player_9": "Ra\u00FAl\r TOT (A)",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "708( 1,658,171 ) TotalXfr : 14",
    "Teams": "Im Sorry Nic Jackson( Jon Briscoe White )",
    "SXL": "Malta",
    "Latp": "23",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Solanke\r FUL (H)",
    "Player_12": "Turner\r 0",
    "Player_13": "Luis D\u00EDaz\r MCI (H)",
    "Player_14": "A\u00EFt-Nouri\r 0",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Dalot\r EVE (H)",
    "Player_5": "Rogers\r CHE (A)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Wood\r 6",
    "Player_15": "Vestergaard\r 0"
  },
  {
    "manager_Name": "693( 2,220,142 ) TotalXfr : 7",
    "Teams": "BienRayados( Luis Ricardo J\u00E1uregui V )",
    "SXL": "England",
    "Latp": "9",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Ra\u00FAl\r TOT (A)",
    "Player_10": "Duran\r CHE (A)",
    "Player_12": "Fabianski\r -1",
    "Player_13": "J.Araujo\r 0",
    "Player_14": "Pau\r CHE (A)",
    "Player_7": "Luis D\u00EDaz\r MCI (H)",
    "Player_2": "Stones\r LIV (A)",
    "Player_5": "Madueke\r AVL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Kova\u010Di\u0107\r LIV (A)",
    "Player_9": "Palmer\r AVL (H)",
    "Player_15": "Havertz\r 6"
  },
  {
    "manager_Name": "698( 2,043,834 ) TotalXfr : 15",
    "Teams": "LxFxC( Ervin Rigo )",
    "SXL": "Malta",
    "Latp": "16",
    "Player_1": "Pope\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Wissa\r 6",
    "Player_12": "Jos\u00E9 S\u00E1\r 0",
    "Player_13": "Semenyo\r 0",
    "Player_14": "Virgil\r MCI (H)",
    "Player_7": "Mbeumo\r 4",
    "Player_2": "J.Timber\r 1",
    "Player_5": "Martinelli\r 0",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Gvardiol\r LIV (A)"
  },
  {
    "manager_Name": "712( 1,507,148 ) TotalXfr : 12",
    "Teams": "Joga Bonito( Christophe Peixoto )",
    "SXL": "Hungary",
    "Latp": "33",
    "Player_1": "Flekken\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Isak\r 1",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Calvert-Lewin\r MUN (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Hall\r 2",
    "Player_5": "Pedro Porro\r FUL (H)",
    "Player_6": "Saka\r 15",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Colwill\r AVL (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Mbeumo\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "694( 2,188,055 ) TotalXfr : 11",
    "Teams": "Blue Core( Avinash Chatlani )",
    "SXL": "Malta",
    "Latp": "16",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Winks\r 0",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Lewis\r LIV (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "Aina\r 6",
    "Player_8": "Adama\r TOT (A)",
    "Player_9": "Haaland\r LIV (A)",
    "Player_15": "Vestergaard\r 0"
  },
  {
    "manager_Name": "684( 2,617,371 ) TotalXfr : 11",
    "Teams": "Ctrl Alt De Ligt( Marlon Vella )",
    "SXL": "Malta",
    "Latp": "10",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Faes\r 0",
    "Player_14": "Ra\u00FAl\r TOT (A)",
    "Player_7": "Rogers\r CHE (A)",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Smith Rowe\r TOT (A)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Milenkovi\u0107\r 6",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "M.Salah\r MCI (H)",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "682( 2,722,673 ) TotalXfr : 14",
    "Teams": "Starship( Olumide Okedusi )",
    "SXL": "Estonia",
    "Latp": "9",
    "Player_1": "Raya\r 2",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Isak\r 1",
    "Player_12": "Turner\r 0",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Adama\r TOT (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Virgil\r MCI (H)",
    "Player_5": "Burn\r 2",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Cunha\r 2",
    "Player_15": "Robinson\r TOT (A)"
  },
  {
    "manager_Name": "679( 2,831,529 ) TotalXfr : 7",
    "Teams": "Matteo fc( Matteo Vella )",
    "SXL": "Malta",
    "Latp": "11",
    "Player_1": "Pope\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 4",
    "Player_10": "Isak\r 1",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Konsa\r CHE (A)",
    "Player_14": "Rogers\r CHE (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Pedro Porro\r FUL (H)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Johnson\r FUL (H)",
    "Player_3": "Hall\r 2",
    "Player_4": "Gvardiol\r LIV (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Watkins\r CHE (A)",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "675( 3,025,195 ) TotalXfr : 11",
    "Teams": "20x MU( John Tiltmann )",
    "SXL": "Malta",
    "Latp": "8",
    "Player_1": "Fabianski\r -1",
    "Player_11": "Isak\r 1",
    "Player_10": "Cunha\r 4",
    "Player_12": "Martinez\r CHE (A)",
    "Player_13": "McNeil\r MUN (A)",
    "Player_14": "Keane\r MUN (A)",
    "Player_7": "Smith Rowe\r TOT (A)",
    "Player_2": "Digne\r CHE (A)",
    "Player_5": "Madueke\r AVL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Robinson\r TOT (A)",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Alexander-Arnold\r MCI (H)"
  },
  {
    "manager_Name": "699( 1,991,937 ) TotalXfr : 12",
    "Teams": "\u0106umura\u0161i( Aleksandar Deletic )",
    "SXL": "Serbia",
    "Latp": "44",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Welbeck\r 2",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Ra\u00FAl\r TOT (A)",
    "Player_14": "Digne\r CHE (A)",
    "Player_7": "Smith Rowe\r TOT (A)",
    "Player_2": "Gabriel\r 9",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Hall\r 2",
    "Player_4": "Virgil\r MCI (H)",
    "Player_8": "Saka\r 15",
    "Player_9": "Mitoma\r 10",
    "Player_15": "Andersen\r TOT (A)"
  },
  {
    "manager_Name": "668( 3,360,368 ) TotalXfr : 12",
    "Teams": "Rekegutt United( Eirik Presttun )",
    "SXL": "Malta",
    "Latp": "4",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Henderson\r 2",
    "Player_13": "Dibling\r 1",
    "Player_14": "Gvardiol\r LIV (A)",
    "Player_7": "Madueke\r AVL (H)",
    "Player_2": "Dalot\r EVE (H)",
    "Player_5": "Garnacho\r EVE (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Faes\r 0",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Mbeumo\r 4",
    "Player_9": "Ra\u00FAl\r TOT (A)",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "679( 2,842,071 ) TotalXfr : 11",
    "Teams": "Massilia( Daniel Borg )",
    "SXL": "Malta",
    "Latp": "16",
    "Player_1": "Flekken\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Delap\r 2",
    "Player_12": "Martinez\r CHE (A)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Konsa\r CHE (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Johnson\r FUL (H)",
    "Player_6": "Mbeumo\r 4",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "Aina\r 6",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "N.Jackson\r AVL (H)",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "672( 3,177,226 ) TotalXfr : 13",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "India",
    "Latp": "9",
    "Player_1": "Fabianski\r -1",
    "Player_11": "Cunha\r 2",
    "Player_10": "Havertz\r 6",
    "Player_12": "Henderson\r 2",
    "Player_13": "Konat\u00E9\r MCI (H)",
    "Player_14": "Faes\r 0",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "J.Timber\r 1",
    "Player_5": "Johnson\r FUL (H)",
    "Player_6": "Smith Rowe\r TOT (A)",
    "Player_3": "W.Fofana\r AVL (H)",
    "Player_4": "Saliba\r 1",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "B.Fernandes\r EVE (H)",
    "Player_15": "Wheatley\r EVE (H)"
  },
  {
    "manager_Name": "673( 3,113,516 ) TotalXfr : 10",
    "Teams": "FC Lokomotiv Sliema( Philip H\u00E5kansson )",
    "SXL": "Malta",
    "Latp": "11",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Strand Larsen\r 9",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Johnson\r FUL (H)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Neto\r AVL (H)",
    "Player_2": "Virgil\r MCI (H)",
    "Player_5": "Rogers\r CHE (A)",
    "Player_6": "Garnacho\r EVE (H)",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "Lewis\r LIV (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Solanke\r FUL (H)",
    "Player_15": "Romero\r FUL (H)"
  },
  {
    "manager_Name": "664( 3,534,017 ) TotalXfr : 7",
    "Teams": "HUNdorito( Adam Rajki )",
    "SXL": "Hungary",
    "Latp": "9",
    "Player_1": "Raya\r 2",
    "Player_11": "Ra\u00FAl\r TOT (A)",
    "Player_10": "Wood\r 6",
    "Player_12": "Turner\r 0",
    "Player_13": "Nelson\r TOT (A)",
    "Player_14": "Winks\r 0",
    "Player_7": "Luis D\u00EDaz\r MCI (H)",
    "Player_2": "Pedro Porro\r FUL (H)",
    "Player_5": "Calafiori\r 0",
    "Player_6": "Szoboszlai\r MCI (H)",
    "Player_3": "Gvardiol\r LIV (A)",
    "Player_4": "Saliba\r 1",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Haaland\r LIV (A)",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "677( 2,915,103 ) TotalXfr : 0",
    "Teams": "KAMACIO FC( Francisco Camacho )",
    "SXL": "Malta",
    "Latp": "28",
    "Player_1": "Fabianski\r -1",
    "Player_11": "Watkins\r CHE (A)",
    "Player_10": "Havertz\r 6",
    "Player_12": "Areola\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 2",
    "Player_14": "Hill\r 0",
    "Player_7": "Foden\r LIV (A)",
    "Player_2": "Mykolenko\r MUN (A)",
    "Player_5": "Bowen\r 2",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Saliba\r 1",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Saka\r 15",
    "Player_9": "Gordon\r 5",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "670( 3,248,472 ) TotalXfr : 7",
    "Teams": "St Peters FC( Clayton Borda )",
    "SXL": "Malta",
    "Latp": "23",
    "Player_1": "Pope\r 2",
    "Player_11": "Mateta\r 2",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Andersen\r TOT (A)",
    "Player_14": "Chiwome\r 0",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Burn\r 2",
    "Player_5": "B.Fernandes\r EVE (H)",
    "Player_6": "Bruno G.\r 2",
    "Player_3": "Konsa\r CHE (A)",
    "Player_4": "De Ligt\r EVE (H)",
    "Player_8": "Saka\r 15",
    "Player_9": "Smith Rowe\r TOT (A)",
    "Player_15": "Kristiansen\r 0"
  },
  {
    "manager_Name": "673( 3,118,217 ) TotalXfr : 11",
    "Teams": "Wan Utd( Mindaugas Grigaitis )",
    "SXL": "Lithuania",
    "Latp": "27",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 4",
    "Player_10": "Havertz\r 6",
    "Player_12": "Vicario\r FUL (H)",
    "Player_13": "Bowen\r 2",
    "Player_14": "Gvardiol\r LIV (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Pedro Porro\r FUL (H)",
    "Player_5": "Johnson\r FUL (H)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Aina\r 6",
    "Player_4": "Saliba\r 1",
    "Player_8": "Garnacho\r EVE (H)",
    "Player_9": "Wood\r 6",
    "Player_15": "Robinson\r TOT (A)"
  },
  {
    "manager_Name": "646( 4,410,028 ) TotalXfr : 11",
    "Teams": "Nketiah_\u0393\u03B1\u03C1\u03BC\u03C0\u03AE( Dimitris Tselikas )",
    "SXL": "Greece",
    "Latp": "2",
    "Player_1": "Flekken\r 2",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Areola\r 0",
    "Player_13": "Lewis\r LIV (A)",
    "Player_14": "Faes\r 0",
    "Player_7": "Rogers\r CHE (A)",
    "Player_2": "Digne\r CHE (A)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Martinelli\r 0",
    "Player_3": "Robertson\r MCI (H)",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Garnacho\r EVE (H)",
    "Player_9": "Smith Rowe\r TOT (A)",
    "Player_15": "Archer\r 2"
  },
  {
    "manager_Name": "663( 3,576,271 ) TotalXfr : 3",
    "Teams": "Unseen Academicals( Kurt Bugeja Coster )",
    "SXL": "Malta",
    "Latp": "27",
    "Player_1": "Ederson M.\r LIV (A)",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Wissa\r 6",
    "Player_12": "Areola\r 0",
    "Player_13": "Trippier\r 0",
    "Player_14": "Jo\u00E3o Pedro\r 2",
    "Player_7": "Saka\r 15",
    "Player_2": "Estupi\u00F1an\r 4",
    "Player_5": "Pedro Porro\r FUL (H)",
    "Player_6": "Onana\r CHE (A)",
    "Player_3": "Chilwell\r AVL (H)",
    "Player_4": "Konat\u00E9\r MCI (H)",
    "Player_8": "Luis D\u00EDaz\r MCI (H)",
    "Player_9": "Mbeumo\r 2",
    "Player_15": "Eze\r 2"
  },
  {
    "manager_Name": "650( 4,223,551 ) TotalXfr : 12",
    "Teams": "Rolling Fernander( Adam Ruggier )",
    "SXL": "Malta",
    "Latp": "13",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Harwood-Bellis\r 1",
    "Player_14": "Barco\r 0",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Konat\u00E9\r MCI (H)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Semenyo\r 0",
    "Player_3": "De Ligt\r EVE (H)",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Smith Rowe\r TOT (A)",
    "Player_9": "Wheatley\r EVE (H)",
    "Player_15": "Yarmoliuk\r 1"
  },
  {
    "manager_Name": "658( 3,827,629 ) TotalXfr : 10",
    "Teams": "FC Qvantas( Johan Hammarstrom )",
    "SXL": "Sweden",
    "Latp": "22",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Sels\r 6",
    "Player_13": "Faes\r 0",
    "Player_14": "Burn\r 2",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Saliba\r 1",
    "Player_5": "Johnson\r FUL (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Keane\r MUN (A)",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Smith Rowe\r TOT (A)",
    "Player_9": "Wood\r 6",
    "Player_15": "Winks\r 0"
  },
  {
    "manager_Name": "703( 1,829,152 ) TotalXfr : 11",
    "Teams": "Red Tigers FC( George Vepkhvadze )",
    "SXL": "Georgia",
    "Latp": "68",
    "Player_1": "Pope\r 2",
    "Player_11": "Havertz\r 6",
    "Player_10": "Isak\r 1",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Gusto\r AVL (H)",
    "Player_14": "Bowen\r 2",
    "Player_7": "Gordon\r 5",
    "Player_2": "Van den Berg\r 2",
    "Player_5": "Saka\r 30",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Kerkez\r 7",
    "Player_8": "Semenyo\r 0",
    "Player_9": "Wood\r 6",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "633( 5,024,214 ) TotalXfr : 10",
    "Teams": "Maniacs( Alvaro Garcia )",
    "SXL": "Malta",
    "Latp": "6",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Raya\r 2",
    "Player_13": "Palmer\r AVL (H)",
    "Player_14": "Antonio\r 2",
    "Player_7": "Luis D\u00EDaz\r MCI (H)",
    "Player_2": "Konat\u00E9\r MCI (H)",
    "Player_5": "Gvardiol\r LIV (A)",
    "Player_6": "Georginio\r 2",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "Dalot\r EVE (H)",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Casemiro\r EVE (H)",
    "Player_15": "Burgess\r 2"
  },
  {
    "manager_Name": "624( 5,422,645 ) TotalXfr : 1",
    "Teams": "Chris( Christian Borg )",
    "SXL": "Malta",
    "Latp": "3",
    "Player_1": "A.Becker\r MCI (H)",
    "Player_11": "Isak\r 1",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Arrizabalaga\r 1",
    "Player_13": "Solanke\r FUL (H)",
    "Player_14": "J.Timber\r 1",
    "Player_7": "Nkunku\r AVL (H)",
    "Player_2": "Martinez\r EVE (H)",
    "Player_5": "Mykolenko\r MUN (A)",
    "Player_6": "Ramsey\r CHE (A)",
    "Player_3": "Krafth\r 0",
    "Player_4": "Igor\r 2",
    "Player_8": "Smith Rowe\r TOT (A)",
    "Player_9": "M.Salah\r MCI (H)",
    "Player_15": "Buendia\r CHE (A)"
  },
  {
    "manager_Name": "628( 5,241,356 ) TotalXfr : 2",
    "Teams": "Red Devils( Ryan Schembri )",
    "SXL": "Malta",
    "Latp": "7",
    "Player_1": "Areola\r 0",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Watkins\r CHE (A)",
    "Player_12": "Martinez\r CHE (A)",
    "Player_13": "Jo\u00E3o Pedro\r 2",
    "Player_14": "Andersen\r TOT (A)",
    "Player_7": "Luis D\u00EDaz\r MCI (H)",
    "Player_2": "Pedro Porro\r FUL (H)",
    "Player_5": "Smith Rowe\r TOT (A)",
    "Player_6": "Garnacho\r EVE (H)",
    "Player_3": "Faes\r 0",
    "Player_4": "Pau\r CHE (A)",
    "Player_8": "Buonanotte\r 7",
    "Player_9": "M.Salah\r MCI (H)",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "632( 5,070,632 ) TotalXfr : 10",
    "Teams": "Mimz( Emma Zammit )",
    "SXL": "Malta",
    "Latp": "12",
    "Player_1": "Pickford\r MUN (A)",
    "Player_11": "Duran\r CHE (A)",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Turner\r 0",
    "Player_13": "Sou\u010Dek\r 1",
    "Player_14": "Faes\r 0",
    "Player_7": "Smith Rowe\r TOT (A)",
    "Player_2": "Virgil\r MCI (H)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Martinez\r EVE (H)",
    "Player_8": "Garnacho\r EVE (H)",
    "Player_9": "Isak\r 1",
    "Player_15": "Taylor\r 0"
  }
];