var s = [
  {
    "manager_Name": "830( 13,482 ) TotalXfr : 11",
    "Teams": "Lorrainesson( Lorraine Busuttil )",
    "SXL": "Malta",
    "Latp": "89",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Strand Larsen\r 11",
    "Player_12": "Lumley\r 3",
    "Player_13": "Davis\r 2",
    "Player_14": "Okoli\r 0",
    "Player_7": "Palmer\r 11",
    "Player_2": "Hall\r 2",
    "Player_5": "Saka\r 18",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Gabriel\r 9",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "M.Salah\r 22",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Semenyo\r 0"
  },
  {
    "manager_Name": "809( 48,426 ) TotalXfr : 13",
    "Teams": "FC Pek( Erik Lindberg )",
    "SXL": "Sweden",
    "Latp": "48",
    "Player_1": "Henderson\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wissa\r 8",
    "Player_12": "Turner\r 0",
    "Player_13": "Digne\r 1",
    "Player_14": "Faes\r 0",
    "Player_7": "Mbeumo\r 4",
    "Player_2": "Gvardiol\r 0",
    "Player_5": "Mitoma\r 10",
    "Player_6": "M.Salah\r 11",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Rogers\r 2",
    "Player_9": "Solanke\r 0",
    "Player_15": "Winks\r 0"
  },
  {
    "manager_Name": "786( 148,525 ) TotalXfr : 11",
    "Teams": "Fantasikonungen( Albin Jonsson )",
    "SXL": "Malta",
    "Latp": "81",
    "Player_1": "Jos\u00E9 S\u00E1\r 0",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Digne\r 1",
    "Player_14": "Konat\u00E9\r 0",
    "Player_7": "Saka\r 36",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Palmer\r 11",
    "Player_3": "Hall\r 2",
    "Player_4": "Gabriel\r 9",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Delap\r 2",
    "Player_15": "Semenyo\r 0"
  },
  {
    "manager_Name": "776( 228,077 ) TotalXfr : 11",
    "Teams": "The Bees( Tove Ronneb\u00E4ck )",
    "SXL": "Malta",
    "Latp": "59",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Wissa\r 8",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Smith Rowe\r 2",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Palmer\r 22",
    "Player_2": "Konat\u00E9\r 0",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Rogers\r 2",
    "Player_3": "Gvardiol\r 0",
    "Player_4": "Gabriel\r 9",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Cunha\r 2",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "757( 463,932 ) TotalXfr : 10",
    "Teams": "Udogie\u0027s Doggies( Claude Taliana )",
    "SXL": "Malta",
    "Latp": "77",
    "Player_1": "Flekken\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 9",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Barnes\r 2",
    "Player_14": "Robinson\r 2",
    "Player_7": "Georginio\r 2",
    "Player_2": "Aina\r 8",
    "Player_5": "M.Salah\r 22",
    "Player_6": "Palmer\r 11",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Dalot\r 6",
    "Player_8": "Rogers\r 2",
    "Player_9": "Strand Larsen\r 11",
    "Player_15": "Lewis\r 1"
  },
  {
    "manager_Name": "754( 515,742 ) TotalXfr : 11",
    "Teams": "Los Blancos( Eamonn Mifsud )",
    "SXL": "Malta",
    "Latp": "55",
    "Player_1": "Raya\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r 2",
    "Player_14": "Konsa\r 1",
    "Player_7": "Son\r 2",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "M.Salah\r 22",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Van den Berg\r 2",
    "Player_8": "Palmer\r 11",
    "Player_9": "Isak\r 1",
    "Player_15": "Lewis\r 1"
  },
  {
    "manager_Name": "749( 603,583 ) TotalXfr : 9",
    "Teams": "Lallish United( Melwin Holst )",
    "SXL": "Sweden",
    "Latp": "54",
    "Player_1": "Raya\r 2",
    "Player_11": "H\u00F8jlund\r 0",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Dalot\r 6",
    "Player_14": "Davis\r 2",
    "Player_7": "M.Salah\r 22",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Son\r 2",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Van Hecke\r 2",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Palmer\r 11",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Rogers\r 2"
  },
  {
    "manager_Name": "747( 650,621 ) TotalXfr : 12",
    "Teams": "NoHopeFC( John Maguire )",
    "SXL": "Malta",
    "Latp": "55",
    "Player_1": "Flekken\r 2",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Konat\u00E9\r 0",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Palmer\r 11",
    "Player_2": "Robinson\r 2",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "B.Fernandes\r 18",
    "Player_3": "Davis\r 2",
    "Player_4": "Digne\r 1",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Maddison\r 2",
    "Player_15": "Marc Guiu\r 0"
  },
  {
    "manager_Name": "741( 771,507 ) TotalXfr : 9",
    "Teams": "Kinder Mbeumo( Gerson Seguna )",
    "SXL": "Malta",
    "Latp": "88",
    "Player_1": "Raya\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "O\u0027Shea\r 1",
    "Player_14": "Rogers\r 2",
    "Player_7": "Palmer\r 11",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Mitoma\r 10",
    "Player_6": "Saka\r 18",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Milenkovi\u0107\r 6",
    "Player_8": "M.Salah\r 22",
    "Player_9": "Wood\r 9",
    "Player_15": "Hall\r 2"
  },
  {
    "manager_Name": "741( 783,912 ) TotalXfr : 13",
    "Teams": "Salahvation Army( Tom Atkinson )",
    "SXL": "Malta",
    "Latp": "57",
    "Player_1": "Pope\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Haaland\r 2",
    "Player_12": "Slicker\r 0",
    "Player_13": "Lewis\r 1",
    "Player_14": "Winks\r 0",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Gvardiol\r 0",
    "Player_5": "Rogers\r 2",
    "Player_6": "Mitoma\r 10",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Collins\r 5",
    "Player_8": "M.Salah\r 22",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "740( 794,554 ) TotalXfr : 9",
    "Teams": "JDT Out( Filip Larsson )",
    "SXL": "Malta",
    "Latp": "66",
    "Player_1": "Flekken\r 2",
    "Player_11": "Wood\r 18",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Lewis\r 1",
    "Player_14": "Semenyo\r 0",
    "Player_7": "Rogers\r 2",
    "Player_2": "Aina\r 8",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "B.Fernandes\r 9",
    "Player_3": "Gabriel\r 9",
    "Player_4": "J.Timber\r 1",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Haaland\r 2",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "727( 1,135,682 ) TotalXfr : 10",
    "Teams": "klopp notch( Tobias Nocke )",
    "SXL": "Sweden",
    "Latp": "54",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Solanke\r 0",
    "Player_12": "Kelleher\r 7",
    "Player_13": "Ayari\r 2",
    "Player_14": "Konat\u00E9\r 0",
    "Player_7": "\u00D8degaard\r 8",
    "Player_2": "Van den Berg\r 2",
    "Player_5": "Palmer\r 11",
    "Player_6": "Foden\r 1",
    "Player_3": "Estupi\u00F1an\r 4",
    "Player_4": "Digne\r 1",
    "Player_8": "M.Salah\r 22",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "725( 1,203,723 ) TotalXfr : 12",
    "Teams": "MainooInTheBank( Thanasis Fouras )",
    "SXL": "Greece",
    "Latp": "63",
    "Player_1": "Henderson\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Wood\r 9",
    "Player_12": "Matthews\r 0",
    "Player_13": "Faes\r 0",
    "Player_14": "Winks\r 0",
    "Player_7": "M.Salah\r 11",
    "Player_2": "Digne\r 1",
    "Player_5": "Gordon\r 5",
    "Player_6": "Johnson\r 7",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Robinson\r 2",
    "Player_8": "Palmer\r 22",
    "Player_9": "Haaland\r 2",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "721( 1,320,894 ) TotalXfr : 11",
    "Teams": "Crvena Zvezda( Dejan Mrdanov )",
    "SXL": "Malta",
    "Latp": "45",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 2",
    "Player_10": "Wood\r 9",
    "Player_12": "Areola\r 0",
    "Player_13": "Hudson-Odoi\r 3",
    "Player_14": "Colwill\r 6",
    "Player_7": "Garnacho\r 1",
    "Player_2": "Tarkowski\r 0",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Luis D\u00EDaz\r 6",
    "Player_3": "Digne\r 1",
    "Player_4": "Gabriel\r 9",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Cunha\r 2",
    "Player_15": "Pedro Porro\r 2"
  },
  {
    "manager_Name": "717( 1,457,855 ) TotalXfr : 12",
    "Teams": "Tourinho FC( Alexis Touris )",
    "SXL": "Greece",
    "Latp": "62",
    "Player_1": "Martinez\r 1",
    "Player_11": "Isak\r 1",
    "Player_10": "Watkins\r 2",
    "Player_12": "Henderson\r 2",
    "Player_13": "Gvardiol\r 0",
    "Player_14": "Andersen\r 0",
    "Player_7": "Bowen\r 2",
    "Player_2": "Dalot\r 6",
    "Player_5": "Johnson\r 7",
    "Player_6": "M.Salah\r 22",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Aina\r 8",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Wood\r 9",
    "Player_15": "Adama\r 0"
  },
  {
    "manager_Name": "716( 1,496,359 ) TotalXfr : 13",
    "Teams": "Gidia KK( Aggelos Flamiatos )",
    "SXL": "Greece",
    "Latp": "39",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Welbeck\r 4",
    "Player_12": "Flekken\r 2",
    "Player_13": "McNeil\r 2",
    "Player_14": "Burn\r 4",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Murillo\r 7",
    "Player_5": "Maddison\r 2",
    "Player_6": "M.Salah\r 11",
    "Player_3": "Virgil\r 6",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Rogers\r 2",
    "Player_9": "Solanke\r 0",
    "Player_15": "Robinson\r 2"
  },
  {
    "manager_Name": "716( 1,496,359 ) TotalXfr : 13",
    "Teams": "Ajax CT( Dimitrios Siderakis )",
    "SXL": "Malta",
    "Latp": "62",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Watkins\r 2",
    "Player_12": "S\u00E1nchez\r 7",
    "Player_13": "Carvalho\r 1",
    "Player_14": "Welbeck\r 2",
    "Player_7": "Luis D\u00EDaz\r 6",
    "Player_2": "Gu\u00E9hi\r 3",
    "Player_5": "Pedro Porro\r 2",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Mazraoui\r 1",
    "Player_4": "Saliba\r 1",
    "Player_8": "Palmer\r 11",
    "Player_9": "M.Salah\r 22",
    "Player_15": "Murillo\r 7"
  },
  {
    "manager_Name": "715( 1,525,663 ) TotalXfr : 12",
    "Teams": "Joga Bonito( Christophe Peixoto )",
    "SXL": "Hungary",
    "Latp": "77",
    "Player_1": "Flekken\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Isak\r 1",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Smith Rowe\r 2",
    "Player_14": "Calvert-Lewin\r 1",
    "Player_7": "Palmer\r 11",
    "Player_2": "Hall\r 2",
    "Player_5": "Pedro Porro\r 2",
    "Player_6": "Saka\r 18",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Colwill\r 6",
    "Player_8": "M.Salah\r 22",
    "Player_9": "Mbeumo\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "714( 1,565,508 ) TotalXfr : 13",
    "Teams": "ThereWeLand( Haykel Mansour )",
    "SXL": "Malta",
    "Latp": "55",
    "Player_1": "S\u00E1nchez\r 7",
    "Player_11": "Cunha\r 2",
    "Player_10": "Isak\r 1",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Smith Rowe\r 2",
    "Player_14": "Lewis\r 1",
    "Player_7": "Kulusevski\r 1",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Palmer\r 11",
    "Player_6": "Mbeumo\r 4",
    "Player_3": "Collins\r 5",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Rashford\r 13",
    "Player_9": "Haaland\r 2",
    "Player_15": "Nedeljkovic\r 0"
  },
  {
    "manager_Name": "712( 1,624,258 ) TotalXfr : 11",
    "Teams": "Red Tigers FC( George Vepkhvadze )",
    "SXL": "Georgia",
    "Latp": "88",
    "Player_1": "Pope\r 2",
    "Player_11": "Havertz\r 6",
    "Player_10": "Isak\r 1",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Gusto\r 1",
    "Player_14": "Bowen\r 2",
    "Player_7": "Gordon\r 5",
    "Player_2": "Van den Berg\r 2",
    "Player_5": "Saka\r 36",
    "Player_6": "Palmer\r 11",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Kerkez\r 7",
    "Player_8": "Semenyo\r 0",
    "Player_9": "Wood\r 9",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "711( 1,656,157 ) TotalXfr : 10",
    "Teams": "Gambit( Nicola Frasca )",
    "SXL": "Malta",
    "Latp": "56",
    "Player_1": "Pickford\r 0",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Greaves\r 0",
    "Player_14": "Winks\r 0",
    "Player_7": "Yarmoliuk\r 1",
    "Player_2": "Gvardiol\r 0",
    "Player_5": "Pedro Porro\r 2",
    "Player_6": "M.Salah\r 11",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Martinez\r 5",
    "Player_8": "Smith Rowe\r 2",
    "Player_9": "Palmer\r 22",
    "Player_15": "Ings\r 1"
  },
  {
    "manager_Name": "711( 1,675,310 ) TotalXfr : 14",
    "Teams": "Im Sorry Nic Jackson( Jon Briscoe White )",
    "SXL": "Malta",
    "Latp": "75",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Solanke\r 0",
    "Player_12": "Turner\r 0",
    "Player_13": "Luis D\u00EDaz\r 6",
    "Player_14": "A\u00EFt-Nouri\r 0",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Dalot\r 6",
    "Player_5": "Rogers\r 2",
    "Player_6": "Palmer\r 22",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Wood\r 9",
    "Player_15": "Vestergaard\r 0"
  },
  {
    "manager_Name": "709( 1,748,381 ) TotalXfr : 14",
    "Teams": "Guglielmo( Jonas Megert )",
    "SXL": "Sweden",
    "Latp": "42",
    "Player_1": "Martinez\r 1",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 9",
    "Player_12": "Turner\r 0",
    "Player_13": "Winks\r 0",
    "Player_14": "Quansah\r 1",
    "Player_7": "M.Salah\r 11",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Smith Rowe\r 2",
    "Player_6": "Johnson\r 7",
    "Player_3": "Konsa\r 1",
    "Player_4": "Lewis\r 1",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Welbeck\r 4",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "703( 1,980,291 ) TotalXfr : 16",
    "Teams": "Biancoverde Utd 4.0( Michael Keramas )",
    "SXL": "Greece",
    "Latp": "62",
    "Player_1": "Flekken\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Isak\r 1",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Mbeumo\r 2",
    "Player_14": "Aina\r 8",
    "Player_7": "M.Salah\r 11",
    "Player_2": "Gvardiol\r 0",
    "Player_5": "B.Fernandes\r 9",
    "Player_6": "Palmer\r 22",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Robinson\r 2",
    "Player_8": "Kulusevski\r 1",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "702( 2,005,928 ) TotalXfr : 12",
    "Teams": "\u0106umura\u0161i( Aleksandar Deletic )",
    "SXL": "Serbia",
    "Latp": "77",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Welbeck\r 2",
    "Player_12": "S\u00E1nchez\r 7",
    "Player_13": "Ra\u00FAl\r 2",
    "Player_14": "Digne\r 1",
    "Player_7": "Smith Rowe\r 2",
    "Player_2": "Gabriel\r 9",
    "Player_5": "M.Salah\r 22",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Hall\r 2",
    "Player_4": "Virgil\r 6",
    "Player_8": "Saka\r 18",
    "Player_9": "Mitoma\r 10",
    "Player_15": "Andersen\r 0"
  },
  {
    "manager_Name": "700( 2,097,213 ) TotalXfr : 15",
    "Teams": "LxFxC( Ervin Rigo )",
    "SXL": "Malta",
    "Latp": "42",
    "Player_1": "Pope\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Wissa\r 8",
    "Player_12": "Jos\u00E9 S\u00E1\r 0",
    "Player_13": "Semenyo\r 0",
    "Player_14": "Virgil\r 6",
    "Player_7": "Mbeumo\r 4",
    "Player_2": "J.Timber\r 1",
    "Player_5": "Martinelli\r 0",
    "Player_6": "Palmer\r 11",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Gvardiol\r 0"
  },
  {
    "manager_Name": "696( 2,241,953 ) TotalXfr : 11",
    "Teams": "Blue Core( Avinash Chatlani )",
    "SXL": "Malta",
    "Latp": "62",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Winks\r 0",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "M.Salah\r 22",
    "Player_2": "Lewis\r 1",
    "Player_5": "Palmer\r 11",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "Aina\r 8",
    "Player_8": "Adama\r 0",
    "Player_9": "Haaland\r 2",
    "Player_15": "Vestergaard\r 0"
  },
  {
    "manager_Name": "693( 2,355,982 ) TotalXfr : 5",
    "Teams": "Nachos( Melvin Xuereb )",
    "SXL": "Malta",
    "Latp": "47",
    "Player_1": "Areola\r 0",
    "Player_11": "Haaland\r 2",
    "Player_10": "Calvert-Lewin\r 1",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Semenyo\r 0",
    "Player_14": "Estupi\u00F1an\r 4",
    "Player_7": "M.Salah\r 22",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Eze\r 2",
    "Player_6": "Palmer\r 11",
    "Player_3": "Andersen\r 0",
    "Player_4": "Saliba\r 1",
    "Player_8": "Damsgaard\r 5",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "693( 2,357,896 ) TotalXfr : 7",
    "Teams": "BienRayados( Luis Ricardo J\u00E1uregui V )",
    "SXL": "England",
    "Latp": "67",
    "Player_1": "S\u00E1nchez\r 7",
    "Player_11": "Ra\u00FAl\r 2",
    "Player_10": "Duran\r 1",
    "Player_12": "Fabianski\r -1",
    "Player_13": "J.Araujo\r 0",
    "Player_14": "Pau\r 1",
    "Player_7": "Luis D\u00EDaz\r 6",
    "Player_2": "Stones\r 0",
    "Player_5": "Madueke\r 3",
    "Player_6": "M.Salah\r 22",
    "Player_3": "Virgil\r 6",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Kova\u010Di\u0107\r 0",
    "Player_9": "Palmer\r 11",
    "Player_15": "Havertz\r 6"
  },
  {
    "manager_Name": "689( 2,537,731 ) TotalXfr : 11",
    "Teams": "Hakuna Mateta( Jason Evans )",
    "SXL": "Malta",
    "Latp": "52",
    "Player_1": "Martinez\r 1",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Haaland\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Carvalho\r 1",
    "Player_14": "Barco\r 0",
    "Player_7": "Kulusevski\r 1",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Mitoma\r 10",
    "Player_6": "Rogers\r 2",
    "Player_3": "Gvardiol\r 0",
    "Player_4": "Romero\r 0",
    "Player_8": "M.Salah\r 22",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Thomas\r 0"
  },
  {
    "manager_Name": "684( 2,757,479 ) TotalXfr : 11",
    "Teams": "Ctrl Alt De Ligt( Marlon Vella )",
    "SXL": "Malta",
    "Latp": "57",
    "Player_1": "S\u00E1nchez\r 7",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Faes\r 0",
    "Player_14": "Ra\u00FAl\r 2",
    "Player_7": "Rogers\r 2",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Smith Rowe\r 2",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Milenkovi\u0107\r 6",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Palmer\r 11",
    "Player_9": "M.Salah\r 22",
    "Player_15": "Lewis\r 1"
  },
  {
    "manager_Name": "684( 2,773,424 ) TotalXfr : 14",
    "Teams": "Starship( Olumide Okedusi )",
    "SXL": "Estonia",
    "Latp": "58",
    "Player_1": "Raya\r 2",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Isak\r 1",
    "Player_12": "Turner\r 0",
    "Player_13": "Rogers\r 2",
    "Player_14": "Adama\r 0",
    "Player_7": "M.Salah\r 11",
    "Player_2": "Virgil\r 6",
    "Player_5": "Burn\r 4",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Pedro Porro\r 2",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Palmer\r 22",
    "Player_9": "Cunha\r 2",
    "Player_15": "Robinson\r 2"
  },
  {
    "manager_Name": "681( 2,891,712 ) TotalXfr : 11",
    "Teams": "Massilia( Daniel Borg )",
    "SXL": "Malta",
    "Latp": "57",
    "Player_1": "Flekken\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Delap\r 2",
    "Player_12": "Martinez\r 1",
    "Player_13": "Rogers\r 2",
    "Player_14": "Konsa\r 1",
    "Player_7": "B.Fernandes\r 9",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Johnson\r 7",
    "Player_6": "Mbeumo\r 4",
    "Player_3": "Virgil\r 6",
    "Player_4": "Aina\r 8",
    "Player_8": "M.Salah\r 11",
    "Player_9": "N.Jackson\r 6",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "680( 2,918,918 ) TotalXfr : 0",
    "Teams": "KAMACIO FC( Francisco Camacho )",
    "SXL": "Malta",
    "Latp": "57",
    "Player_1": "Fabianski\r -1",
    "Player_11": "Watkins\r 2",
    "Player_10": "Havertz\r 6",
    "Player_12": "Areola\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 2",
    "Player_14": "Hill\r 0",
    "Player_7": "Foden\r 1",
    "Player_2": "Mykolenko\r -1",
    "Player_5": "Bowen\r 2",
    "Player_6": "Palmer\r 22",
    "Player_3": "Saliba\r 1",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Saka\r 18",
    "Player_9": "Gordon\r 5",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "679( 2,972,091 ) TotalXfr : 7",
    "Teams": "Matteo fc( Matteo Vella )",
    "SXL": "Malta",
    "Latp": "44",
    "Player_1": "Pope\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 4",
    "Player_10": "Isak\r 1",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Konsa\r 1",
    "Player_14": "Rogers\r 2",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Palmer\r 11",
    "Player_6": "Johnson\r 7",
    "Player_3": "Hall\r 2",
    "Player_4": "Gvardiol\r 0",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Watkins\r 2",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "678( 3,028,243 ) TotalXfr : 11",
    "Teams": "Wan Utd( Mindaugas Grigaitis )",
    "SXL": "Lithuania",
    "Latp": "53",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 4",
    "Player_10": "Havertz\r 6",
    "Player_12": "Vicario\r 0",
    "Player_13": "Bowen\r 2",
    "Player_14": "Gvardiol\r 0",
    "Player_7": "M.Salah\r 11",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Johnson\r 7",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Aina\r 8",
    "Player_4": "Saliba\r 1",
    "Player_8": "Garnacho\r 1",
    "Player_9": "Wood\r 9",
    "Player_15": "Robinson\r 2"
  },
  {
    "manager_Name": "675( 3,155,575 ) TotalXfr : 7",
    "Teams": "St Peters FC( Clayton Borda )",
    "SXL": "Malta",
    "Latp": "56",
    "Player_1": "Pope\r 2",
    "Player_11": "Mateta\r 2",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Andersen\r 0",
    "Player_14": "Chiwome\r 0",
    "Player_7": "Palmer\r 11",
    "Player_2": "Burn\r 4",
    "Player_5": "B.Fernandes\r 9",
    "Player_6": "Bruno G.\r 2",
    "Player_3": "Konsa\r 1",
    "Player_4": "De Ligt\r 1",
    "Player_8": "Saka\r 18",
    "Player_9": "Smith Rowe\r 2",
    "Player_15": "Kristiansen\r 0"
  },
  {
    "manager_Name": "675( 3,161,726 ) TotalXfr : 10",
    "Teams": "FC Lokomotiv Sliema( Philip H\u00E5kansson )",
    "SXL": "Malta",
    "Latp": "42",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 4",
    "Player_10": "Strand Larsen\r 11",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Johnson\r 7",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Neto\r 3",
    "Player_2": "Virgil\r 6",
    "Player_5": "Rogers\r 2",
    "Player_6": "Garnacho\r 1",
    "Player_3": "Mazraoui\r 1",
    "Player_4": "Lewis\r 1",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Solanke\r 0",
    "Player_15": "Romero\r 0"
  },
  {
    "manager_Name": "675( 3,166,425 ) TotalXfr : 11",
    "Teams": "20x MU( John Tiltmann )",
    "SXL": "Malta",
    "Latp": "28",
    "Player_1": "Fabianski\r -1",
    "Player_11": "Isak\r 1",
    "Player_10": "Cunha\r 4",
    "Player_12": "Martinez\r 1",
    "Player_13": "McNeil\r 2",
    "Player_14": "Keane\r 0",
    "Player_7": "Smith Rowe\r 2",
    "Player_2": "Digne\r 1",
    "Player_5": "Madueke\r 3",
    "Player_6": "M.Salah\r 11",
    "Player_3": "Robinson\r 2",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Alexander-Arnold\r 6"
  },
  {
    "manager_Name": "672( 3,317,597 ) TotalXfr : 13",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "India",
    "Latp": "61",
    "Player_1": "Fabianski\r -1",
    "Player_11": "Cunha\r 2",
    "Player_10": "Havertz\r 6",
    "Player_12": "Henderson\r 2",
    "Player_13": "Konat\u00E9\r 0",
    "Player_14": "Faes\r 0",
    "Player_7": "M.Salah\r 22",
    "Player_2": "J.Timber\r 1",
    "Player_5": "Johnson\r 7",
    "Player_6": "Smith Rowe\r 2",
    "Player_3": "W.Fofana\r 1",
    "Player_4": "Saliba\r 1",
    "Player_8": "Palmer\r 11",
    "Player_9": "B.Fernandes\r 9",
    "Player_15": "Wheatley\r 0"
  },
  {
    "manager_Name": "668( 3,478,378 ) TotalXfr : 3",
    "Teams": "Unseen Academicals( Kurt Bugeja Coster )",
    "SXL": "Malta",
    "Latp": "44",
    "Player_1": "Ederson M.\r 0",
    "Player_11": "Haaland\r 4",
    "Player_10": "Wissa\r 8",
    "Player_12": "Areola\r 0",
    "Player_13": "Trippier\r 0",
    "Player_14": "Jo\u00E3o Pedro\r 2",
    "Player_7": "Saka\r 18",
    "Player_2": "Estupi\u00F1an\r 4",
    "Player_5": "Pedro Porro\r 2",
    "Player_6": "Onana\r 0",
    "Player_3": "Chilwell\r 0",
    "Player_4": "Konat\u00E9\r 0",
    "Player_8": "Luis D\u00EDaz\r 6",
    "Player_9": "Mbeumo\r 2",
    "Player_15": "Eze\r 2"
  },
  {
    "manager_Name": "668( 3,500,561 ) TotalXfr : 12",
    "Teams": "Rekegutt United( Eirik Presttun )",
    "SXL": "Malta",
    "Latp": "43",
    "Player_1": "S\u00E1nchez\r 7",
    "Player_11": "Haaland\r 2",
    "Player_10": "N.Jackson\r 6",
    "Player_12": "Henderson\r 2",
    "Player_13": "Dibling\r 1",
    "Player_14": "Gvardiol\r 0",
    "Player_7": "Madueke\r 3",
    "Player_2": "Dalot\r 6",
    "Player_5": "Garnacho\r 1",
    "Player_6": "M.Salah\r 11",
    "Player_3": "Faes\r 0",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Mbeumo\r 4",
    "Player_9": "Ra\u00FAl\r 2",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "667( 3,530,334 ) TotalXfr : 7",
    "Teams": "HUNdorito( Adam Rajki )",
    "SXL": "Hungary",
    "Latp": "49",
    "Player_1": "Raya\r 2",
    "Player_11": "Ra\u00FAl\r 2",
    "Player_10": "Wood\r 9",
    "Player_12": "Turner\r 0",
    "Player_13": "Nelson\r 2",
    "Player_14": "Winks\r 0",
    "Player_7": "Luis D\u00EDaz\r 6",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Calafiori\r 0",
    "Player_6": "Szoboszlai\r 3",
    "Player_3": "Gvardiol\r 0",
    "Player_4": "Saliba\r 1",
    "Player_8": "M.Salah\r 22",
    "Player_9": "Haaland\r 2",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "661( 3,820,205 ) TotalXfr : 10",
    "Teams": "FC Qvantas( Johan Hammarstrom )",
    "SXL": "Sweden",
    "Latp": "58",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Sels\r 6",
    "Player_13": "Faes\r 0",
    "Player_14": "Burn\r 4",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Saliba\r 1",
    "Player_5": "Johnson\r 7",
    "Player_6": "Palmer\r 22",
    "Player_3": "Keane\r 0",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Smith Rowe\r 2",
    "Player_9": "Wood\r 9",
    "Player_15": "Winks\r 0"
  },
  {
    "manager_Name": "652( 4,266,726 ) TotalXfr : 14",
    "Teams": "Cursed Technique( Ini Etienam )",
    "SXL": "Estonia",
    "Latp": "81",
    "Player_1": "Pickford\r 0",
    "Player_11": "Wood\r 9",
    "Player_10": "Cunha\r 2",
    "Player_12": "Flekken\r 2",
    "Player_13": "McNeil\r 2",
    "Player_14": "Digne\r 1",
    "Player_7": "M.Salah\r 22",
    "Player_2": "Aina\r 8",
    "Player_5": "Saka\r 18",
    "Player_6": "Luis D\u00EDaz\r 6",
    "Player_3": "Virgil\r 6",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "N.Jackson\r 6",
    "Player_15": "Martinez\r 5"
  },
  {
    "manager_Name": "650( 4,353,523 ) TotalXfr : 12",
    "Teams": "Rolling Fernander( Adam Ruggier )",
    "SXL": "Malta",
    "Latp": "51",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Harwood-Bellis\r 1",
    "Player_14": "Barco\r 0",
    "Player_7": "M.Salah\r 22",
    "Player_2": "Konat\u00E9\r 0",
    "Player_5": "Palmer\r 11",
    "Player_6": "Semenyo\r 0",
    "Player_3": "De Ligt\r 1",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Smith Rowe\r 2",
    "Player_9": "Wheatley\r 0",
    "Player_15": "Yarmoliuk\r 1"
  },
  {
    "manager_Name": "649( 4,381,314 ) TotalXfr : 5",
    "Teams": "FC Why-Do-I-Bother( Frode Danielsen )",
    "SXL": "Malta",
    "Latp": "58",
    "Player_1": "Raya\r 2",
    "Player_11": "Strand Larsen\r 11",
    "Player_10": "Haaland\r 4",
    "Player_12": "Turner\r 0",
    "Player_13": "Joelinton\r 2",
    "Player_14": "Tuanzebe\r 1",
    "Player_7": "Trossard\r 12",
    "Player_2": "Gvardiol\r 0",
    "Player_5": "M.Salah\r 11",
    "Player_6": "Sou\u010Dek\r 1",
    "Player_3": "Mazraoui\r 1",
    "Player_4": "Greaves\r 0",
    "Player_8": "Palmer\r 11",
    "Player_9": "Vardy\r 5",
    "Player_15": "Vestergaard\r 0"
  },
  {
    "manager_Name": "646( 4,537,792 ) TotalXfr : 11",
    "Teams": "Nketiah_\u0393\u03B1\u03C1\u03BC\u03C0\u03AE( Dimitris Tselikas )",
    "SXL": "Greece",
    "Latp": "36",
    "Player_1": "Flekken\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "N.Jackson\r 6",
    "Player_12": "Areola\r 0",
    "Player_13": "Lewis\r 1",
    "Player_14": "Faes\r 0",
    "Player_7": "Rogers\r 2",
    "Player_2": "Digne\r 1",
    "Player_5": "M.Salah\r 11",
    "Player_6": "Martinelli\r 0",
    "Player_3": "Robertson\r 6",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Garnacho\r 2",
    "Player_9": "Smith Rowe\r 2",
    "Player_15": "Archer\r 2"
  },
  {
    "manager_Name": "644( 4,610,034 ) TotalXfr : 0",
    "Teams": "Thebackstreetmoyes( Dave Clarke )",
    "SXL": "Ireland",
    "Latp": "44",
    "Player_1": "Raya\r 2",
    "Player_11": "Watkins\r 2",
    "Player_10": "Isak\r 2",
    "Player_12": "Bettinelli\r 0",
    "Player_13": "Burn\r 4",
    "Player_14": "Cash\r 0",
    "Player_7": "B.Fernandes\r 9",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Eze\r 2",
    "Player_6": "Mainoo\r 2",
    "Player_3": "Saliba\r 1",
    "Player_4": "Gvardiol\r 0",
    "Player_8": "Diogo J.\r 0",
    "Player_9": "Saka\r 18",
    "Player_15": "Cunha\r 2"
  },
  {
    "manager_Name": "641( 4,782,366 ) TotalXfr : 13",
    "Teams": "grenbenzen( Gren Kallasmaa )",
    "SXL": "Estonia",
    "Latp": "58",
    "Player_1": "Raya\r 2",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Wood\r 9",
    "Player_12": "Turner\r 0",
    "Player_13": "Tuanzebe\r 1",
    "Player_14": "Martinez\r 5",
    "Player_7": "Saka\r 18",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Bernardo\r 2",
    "Player_6": "Palmer\r 11",
    "Player_3": "Digne\r 1",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Gravenberch\r 2",
    "Player_9": "Haaland\r 4",
    "Player_15": "Onana\r 0"
  }
];