var s = [
  {
    "manager_Name": "914( 7 ) TotalXfr : 11",
    "Teams": "LIV( Dani Lio messi \uD83C\uDDEA\uD83C\uDDF9 )",
    "SXL": "Ethiopia",
    "Latp": "35",
    "Player_1": "Kelleher\r MCI (H)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Areola\r 0",
    "Player_13": "Ra\u00FAl\r TOT (A)",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Bowen\r 2",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "Veltman\r 0",
    "Player_8": "Saka\r 18",
    "Player_9": "Palmer\r AVL (H)",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "894( 48 ) TotalXfr : 11",
    "Teams": "Kodan( Oliyide Daniel )",
    "SXL": "Nigeria",
    "Latp": "62",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Ramsdale\r 0",
    "Player_13": "Konat\u00E9\r MCI (H)",
    "Player_14": "Rogers\r CHE (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Saka\r 36",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Aina\r 8",
    "Player_4": "Robinson\r TOT (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "893( 52 ) TotalXfr : 11",
    "Teams": "\u0627\u0644\u062E\u0648\u0641 \u0645\u0634 \u0645\u0646 \u0627\u0644\u0644\u064A \u062C\u0627\u064A( Sayed Said )",
    "SXL": "Egypt",
    "Latp": "43",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Wissa\r 8",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Pau\r CHE (A)",
    "Player_14": "Greaves\r 0",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Estupi\u00F1an\r 4",
    "Player_5": "Smith Rowe\r TOT (A)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Aina\r 8",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Saka\r 18",
    "Player_9": "Haaland\r LIV (A)",
    "Player_15": "Winks\r 0"
  },
  {
    "manager_Name": "890( 71 ) TotalXfr : 12",
    "Teams": "3laa \uFFFD( 3laa younis )",
    "SXL": "Egypt",
    "Latp": "46",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Wood\r 9",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "Saka\r 18",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Collins\r 5",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Mitoma\r 10",
    "Player_9": "Cunha\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "880( 155 ) TotalXfr : 11",
    "Teams": "New BUILD( Butch K.O )",
    "SXL": "Morocco",
    "Latp": "69",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Strand Larsen\r 11",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Keane\r MUN (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Burn\r 4",
    "Player_5": "Saka\r 36",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Aina\r 8",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Maddison\r FUL (H)",
    "Player_9": "Wissa\r 8",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "878( 186 ) TotalXfr : 10",
    "Teams": "Bakri\uFFFD\u0627\u0644\u062B\u0639\u0644\u0628 \u0627\u0644\u0645\u0627\u0643\u0631( \u0628\u0643\u0631\u064A \u0625\u0628\u0631\u0627\u0647\u064A\u0645 )",
    "SXL": "Sudan",
    "Latp": "56",
    "Player_1": "Flekken\r 2",
    "Player_11": "Wood\r 9",
    "Player_10": "Welbeck\r 2",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "M.Salah\r MCI (H)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Aina\r 8",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Maddison\r FUL (H)",
    "Player_3": "Veltman\r 0",
    "Player_4": "Murillo\r 7",
    "Player_8": "Saka\r 18",
    "Player_9": "Wissa\r 8",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "877( 206 ) TotalXfr : 11",
    "Teams": "CoachSeke( ADESHINA YUSUF )",
    "SXL": "Nigeria",
    "Latp": "55",
    "Player_1": "Sels\r 6",
    "Player_11": "Wissa\r 8",
    "Player_10": "Cunha\r 2",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Saka\r 18",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Aina\r 8",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Delap\r 2",
    "Player_15": "Gvardiol\r LIV (A)"
  },
  {
    "manager_Name": "875( 238 ) TotalXfr : 11",
    "Teams": "\u0623\u0628\u0648 \u0623\u0646\u0633( Osama Moussa )",
    "SXL": "Egypt",
    "Latp": "49",
    "Player_1": "Raya\r 2",
    "Player_11": "H\u00F8jlund\r EVE (H)",
    "Player_10": "Cunha\r 2",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Digne\r CHE (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "Johnson\r FUL (H)",
    "Player_6": "Saka\r 36",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "Veltman\r 0",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Wood\r 9",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "875( 241 ) TotalXfr : 12",
    "Teams": "#\u0645\u0646 \u064A\u0627\u062A\u0648 \u0646\u0627\u062D\u064A\u0629!!( Ali Adlan )",
    "SXL": "Sudan",
    "Latp": "45",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 4",
    "Player_10": "Wood\r 9",
    "Player_12": "Onana\r EVE (H)",
    "Player_13": "Cunha\r 2",
    "Player_14": "Pedro Porro\r FUL (H)",
    "Player_7": "Georginio\r 2",
    "Player_2": "Dalot\r EVE (H)",
    "Player_5": "Saka\r 18",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Aina\r 8",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Son\r FUL (H)",
    "Player_15": "J.Timber\r 1"
  },
  {
    "manager_Name": "874( 247 ) TotalXfr : 8",
    "Teams": "white walker( Pawan Baral )",
    "SXL": "Nepal",
    "Latp": "57",
    "Player_1": "Martinez\r CHE (A)",
    "Player_11": "Cunha\r 2",
    "Player_10": "Wood\r 9",
    "Player_12": "Ward\r 0",
    "Player_13": "Gvardiol\r LIV (A)",
    "Player_14": "Martinelli\r 0",
    "Player_7": "Garnacho\r EVE (H)",
    "Player_2": "Aina\r 8",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Saka\r 36",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Hall\r 2"
  },
  {
    "manager_Name": "874( 253 ) TotalXfr : 11",
    "Teams": "Mr mo \u2665\uFE0F\uFFFD( Mo Ramadan )",
    "SXL": "Egypt",
    "Latp": "49",
    "Player_1": "Flekken\r 2",
    "Player_11": "Cunha\r 4",
    "Player_10": "Wood\r 9",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Georginio\r 2",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "Johnson\r FUL (H)",
    "Player_2": "Pedro Porro\r FUL (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Saka\r 18",
    "Player_3": "Keane\r MUN (A)",
    "Player_4": "Aina\r 8",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Wissa\r 8",
    "Player_15": "Digne\r CHE (A)"
  },
  {
    "manager_Name": "872( 313 ) TotalXfr : 12",
    "Teams": "Scholes United( Sol Scholes )",
    "SXL": "USA",
    "Latp": "39",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Cunha\r 2",
    "Player_10": "Wissa\r 8",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "B.Fernandes\r EVE (H)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Saka\r 18",
    "Player_2": "Robinson\r TOT (A)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Wood\r 9",
    "Player_15": "Konsa\r CHE (A)"
  },
  {
    "manager_Name": "871( 352 ) TotalXfr : 13",
    "Teams": "skibidigyatt_( Raju lama )",
    "SXL": "Nepal",
    "Latp": "49",
    "Player_1": "Henderson\r 2",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Keane\r MUN (A)",
    "Player_14": "Winks\r 0",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Pedro Porro\r FUL (H)",
    "Player_5": "Rogers\r CHE (A)",
    "Player_6": "Saka\r 36",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Collins\r 5",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Cunha\r 2",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "868( 454 ) TotalXfr : 11",
    "Teams": "Tab city( Hossein gd )",
    "SXL": "Iran",
    "Latp": "59",
    "Player_1": "Flekken\r 2",
    "Player_11": "Wood\r 9",
    "Player_10": "Welbeck\r 2",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "N.Jackson\r AVL (H)",
    "Player_14": "Konat\u00E9\r MCI (H)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Saka\r 36",
    "Player_3": "Aina\r 8",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Kulusevski\r FUL (H)",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "868( 464 ) TotalXfr : 12",
    "Teams": "Fly better( m bangili )",
    "SXL": "Kenya",
    "Latp": "29",
    "Player_1": "Turner\r 0",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Jos\u00E9 S\u00E1\r 0",
    "Player_13": "Mykolenko\r MUN (A)",
    "Player_14": "Winks\r 0",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Pinnock\r 2",
    "Player_5": "Rogers\r CHE (A)",
    "Player_6": "Saka\r 18",
    "Player_3": "Saliba\r 1",
    "Player_4": "Hall\r 2",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Cunha\r 2",
    "Player_15": "Woolfenden\r 0"
  },
  {
    "manager_Name": "868( 464 ) TotalXfr : 12",
    "Teams": "Pandas FC( Bernard Mwaura )",
    "SXL": "Kenya",
    "Latp": "53",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "J.Virginia\r MUN (A)",
    "Player_13": "Hall\r 2",
    "Player_14": "Semenyo\r 0",
    "Player_7": "Maddison\r FUL (H)",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Saka\r 36",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "866( 539 ) TotalXfr : 11",
    "Teams": "MO.ZED10( mo3az 3zz95 )",
    "SXL": "Egypt",
    "Latp": "52",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Wood\r 9",
    "Player_12": "Pickford\r MUN (A)",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Konsa\r CHE (A)",
    "Player_7": "Saka\r 18",
    "Player_2": "Aina\r 8",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Robinson\r TOT (A)",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Strand Larsen\r 11",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "866( 539 ) TotalXfr : 11",
    "Teams": "Saka_For_Pain( Janak Jani )",
    "SXL": "India",
    "Latp": "63",
    "Player_1": "Flekken\r 2",
    "Player_11": "Havertz\r 6",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Evanilson\r 12",
    "Player_14": "Davis\r 2",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Estupi\u00F1an\r 4",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Saka\r 36",
    "Player_9": "Georginio\r 2",
    "Player_15": "Nedeljkovic\r CHE (A)"
  },
  {
    "manager_Name": "866( 539 ) TotalXfr : 11",
    "Teams": "Change Name( Bini Mo )",
    "SXL": "Ethiopia",
    "Latp": "68",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Wood\r 9",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Kelleher\r MCI (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Alexander-Arnold\r MCI (H)",
    "Player_7": "Saka\r 36",
    "Player_2": "Aina\r 8",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Smith Rowe\r TOT (A)",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "865( 586 ) TotalXfr : 11",
    "Teams": "Pun FC( Hiramani Pun )",
    "SXL": "Nepal",
    "Latp": "34",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Pickford\r MUN (A)",
    "Player_13": "Evanilson\r 12",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Pedro Porro\r FUL (H)",
    "Player_5": "Mbeumo\r 4",
    "Player_6": "Saka\r 18",
    "Player_3": "Aina\r 8",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Johnson\r FUL (H)",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "865( 604 ) TotalXfr : 12",
    "Teams": "Migo( Ahmed Magdy )",
    "SXL": "Egypt",
    "Latp": "58",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Cunha\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Kelleher\r MCI (H)",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Virgil\r MCI (H)",
    "Player_7": "Saka\r 36",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Maddison\r FUL (H)",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "B.Fernandes\r EVE (H)",
    "Player_9": "Wood\r 9",
    "Player_15": "Veltman\r 0"
  },
  {
    "manager_Name": "865( 623 ) TotalXfr : 16",
    "Teams": "\u0627\u0644\u062B\u0639\u0644\u0640\u0628 \u0627\u0644\u0645\u0627\u0643\u0640\u0631 \u2694\uFE0F\u2620\uFE0F( \u0627\u062D\u0645\u0640\u0640\u062F \u0645\u062D\u0645\u0640\u0640\u0640\u0648\u062F \uD83D\uDD17\uD83E\uDE84\uD83E\uDD77 )",
    "SXL": "England",
    "Latp": "58",
    "Player_1": "Sels\r 6",
    "Player_11": "Isak\r 1",
    "Player_10": "Wissa\r 8",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Adama\r TOT (A)",
    "Player_14": "Vestergaard\r 0",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Robinson\r TOT (A)",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "Collins\r 5",
    "Player_8": "Saka\r 36",
    "Player_9": "Ra\u00FAl\r TOT (A)",
    "Player_15": "Edwards\r 0"
  },
  {
    "manager_Name": "864( 628 ) TotalXfr : 9",
    "Teams": "M@St3R FC( Mohd Natashah Norizan )",
    "SXL": "Malaysia",
    "Latp": "64",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Georginio\r 2",
    "Player_14": "A\u00EFt-Nouri\r 0",
    "Player_7": "Saka\r 36",
    "Player_2": "J.Timber\r 1",
    "Player_5": "Mitoma\r 10",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Davis\r 2",
    "Player_4": "Gabriel\r 9",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Delap\r 2",
    "Player_15": "Mykolenko\r MUN (A)"
  },
  {
    "manager_Name": "864( 653 ) TotalXfr : 11",
    "Teams": "Ctrl\u002BAlt\u002BDe Ligt( Fahad Al kharafi )",
    "SXL": "Kuwait",
    "Latp": "15",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Cunha\r 2",
    "Player_12": "Areola\r 0",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "B.Fernandes\r EVE (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Aina\r 8",
    "Player_4": "Saliba\r 1",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Robertson\r MCI (H)"
  },
  {
    "manager_Name": "864( 653 ) TotalXfr : 11",
    "Teams": "fantasy team( Vitsa champion\uD83D\uDE09 hafiydu_ibrohim )",
    "SXL": "Uzbekistan",
    "Latp": "25",
    "Player_1": "Raya\r 2",
    "Player_11": "Wissa\r 8",
    "Player_10": "Cunha\r 4",
    "Player_12": "Sels\r 6",
    "Player_13": "Luis D\u00EDaz\r MCI (H)",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Young\r MUN (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "B.Fernandes\r EVE (H)",
    "Player_9": "Wood\r 9",
    "Player_15": "Digne\r CHE (A)"
  },
  {
    "manager_Name": "863( 719 ) TotalXfr : 11",
    "Teams": "Juba team( Mostafa Mahgob )",
    "SXL": "Egypt",
    "Latp": "35",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Digne\r CHE (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Hall\r 2",
    "Player_5": "Saka\r 18",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Aina\r 8",
    "Player_4": "Gvardiol\r LIV (A)",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Solanke\r FUL (H)",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "862( 769 ) TotalXfr : 11",
    "Teams": "BLACK BULLS( Mohamed Bentaleb )",
    "SXL": "Morocco",
    "Latp": "53",
    "Player_1": "Pope\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Solanke\r FUL (H)",
    "Player_12": "Turner\r 0",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Digne\r CHE (A)",
    "Player_7": "Saka\r 36",
    "Player_2": "Gabriel\r 9",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Konat\u00E9\r MCI (H)",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "862( 769 ) TotalXfr : 11",
    "Teams": "cudbe#1ifihada**( Eamon Doherty )",
    "SXL": "Austria",
    "Latp": "53",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Wissa\r 16",
    "Player_12": "Matthews\r 0",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Hall\r 2",
    "Player_5": "Gordon\r 5",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Milenkovi\u0107\r 6",
    "Player_8": "Rashford\r EVE (H)",
    "Player_9": "Strand Larsen\r 11",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "862( 801 ) TotalXfr : 12",
    "Teams": "Ditto_04( \u09B0\u09BE\u0995\u09BF\u09AC\u09C1\u09B2 \u09B9\u09BE\u09B8\u09BE\u09A8 )",
    "SXL": "Bangladesh",
    "Latp": "33",
    "Player_1": "Sels\r 6",
    "Player_11": "Cunha\r 2",
    "Player_10": "Watkins\r CHE (A)",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Andersen\r TOT (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Gabriel\r 9",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "Collins\r 5",
    "Player_8": "B.Fernandes\r EVE (H)",
    "Player_9": "Wood\r 9",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "862( 812 ) TotalXfr : 13",
    "Teams": "apdalle( apdalle ahmd )",
    "SXL": "Somalia",
    "Latp": "66",
    "Player_1": "Sels\r 6",
    "Player_11": "Wood\r 9",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Gvardiol\r LIV (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Saka\r 36",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "861( 833 ) TotalXfr : 9",
    "Teams": "FaiYaz FC( Shaikh Jubaer )",
    "SXL": "Bangladesh",
    "Latp": "35",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Wood\r 9",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Welbeck\r 2",
    "Player_14": "Konat\u00E9\r MCI (H)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Igor\r 2",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Van den Berg\r 2",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Saka\r 18",
    "Player_9": "Son\r FUL (H)",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "861( 903 ) TotalXfr : 15",
    "Teams": "Kit2 FC( Prathamesh Ranadive )",
    "SXL": "India",
    "Latp": "43",
    "Player_1": "Sels\r 6",
    "Player_11": "Cunha\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 4",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Georginio\r 2",
    "Player_14": "Keane\r MUN (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "Aina\r 8",
    "Player_8": "Saka\r 18",
    "Player_9": "Watkins\r CHE (A)",
    "Player_15": "Saliba\r 1"
  },
  {
    "manager_Name": "860( 930 ) TotalXfr : 11",
    "Teams": "FC ReaL Madrid \u26BD\uFE0F( \u0639\u0628\u062F\u0627\u0644\u0644\u0647 \u0027\u0027 \u0628\u0633\u0627\u0627\u0637\u064A\u0027\u0027 .. \u26BD\uFE0F \uD83D\uDC51 \uD83C\uDDF8\uD83C\uDDE9 )",
    "SXL": "Saudi Arabia",
    "Latp": "71",
    "Player_1": "Flekken\r 2",
    "Player_11": "Havertz\r 6",
    "Player_10": "Wissa\r 8",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Saka\r 36",
    "Player_2": "Aina\r 8",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Digne\r CHE (A)",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Wood\r 9",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "860( 971 ) TotalXfr : 13",
    "Teams": "\u062E\u0644\u064A\u0644 \u062E\u0644\u064A\u0644( maq swad )",
    "SXL": "Malawi",
    "Latp": "42",
    "Player_1": "Flekken\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Watkins\r CHE (A)",
    "Player_12": "Areola\r 0",
    "Player_13": "Gvardiol\r LIV (A)",
    "Player_14": "Justin\r -1",
    "Player_7": "Son\r FUL (H)",
    "Player_2": "Dalot\r EVE (H)",
    "Player_5": "Saka\r 36",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Young\r MUN (A)",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Garnacho\r EVE (H)",
    "Player_15": "Wheatley\r EVE (H)"
  },
  {
    "manager_Name": "859( 1,020 ) TotalXfr : 11",
    "Teams": "Sirojiddin( Sirojiddin Makhmudov )",
    "SXL": "Uzbekistan",
    "Latp": "41",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Watkins\r CHE (A)",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "N.Semedo\r -1",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Saka\r 36",
    "Player_3": "Alexander-Arnold\r MCI (H)",
    "Player_4": "Digne\r CHE (A)",
    "Player_8": "Son\r FUL (H)",
    "Player_9": "Cunha\r 2",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "859( 1,080 ) TotalXfr : 19",
    "Teams": "Tripple H( Mr. Terrific )",
    "SXL": "Kenya",
    "Latp": "46",
    "Player_1": "Sels\r 6",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Raya\r 2",
    "Player_13": "Lewis\r LIV (A)",
    "Player_14": "Smith Rowe\r TOT (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Gabriel\r 9",
    "Player_8": "\u00D8degaard\r 16",
    "Player_9": "Wood\r 9",
    "Player_15": "Konat\u00E9\r MCI (H)"
  },
  {
    "manager_Name": "858( 1,112 ) TotalXfr : 11",
    "Teams": "KathMadrid( G L Singh )",
    "SXL": "Nepal",
    "Latp": "55",
    "Player_1": "Henderson\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Delap\r 2",
    "Player_14": "Gvardiol\r LIV (A)",
    "Player_7": "Saka\r 36",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Rogers\r CHE (A)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Hall\r 2",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Smith Rowe\r TOT (A)",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "858( 1,166 ) TotalXfr : 13",
    "Teams": "najm( bakri ahmed )",
    "SXL": "Sudan",
    "Latp": "37",
    "Player_1": "Kelleher\r MCI (H)",
    "Player_11": "Wood\r 9",
    "Player_10": "Wissa\r 8",
    "Player_12": "Pickford\r MUN (A)",
    "Player_13": "Mbeumo\r 2",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Saka\r 18",
    "Player_2": "Veltman\r 0",
    "Player_5": "B.Fernandes\r EVE (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Dalot\r EVE (H)",
    "Player_4": "Gvardiol\r LIV (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "858( 1,174 ) TotalXfr : 14",
    "Teams": "Bentoo( Ben Kiptoo )",
    "SXL": "England",
    "Latp": "51",
    "Player_1": "Pope\r 2",
    "Player_11": "Wissa\r 8",
    "Player_10": "Wood\r 9",
    "Player_12": "Johnstone\r 0",
    "Player_13": "Gvardiol\r LIV (A)",
    "Player_14": "Collins\r 5",
    "Player_7": "Saka\r 18",
    "Player_2": "Aina\r 8",
    "Player_5": "Johnson\r FUL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Sch\u00E4r\r 2",
    "Player_4": "Virgil\r MCI (H)",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Cunha\r 2",
    "Player_15": "Semenyo\r 0"
  },
  {
    "manager_Name": "857( 1,214 ) TotalXfr : 11",
    "Teams": "Redpool fc( Bilingstar Kurkalang )",
    "SXL": "India",
    "Latp": "36",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Cunha\r 4",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Ederson M.\r LIV (A)",
    "Player_13": "Palmer\r AVL (H)",
    "Player_14": "Hall\r 2",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Saliba\r 1",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Saka\r 18",
    "Player_3": "Robertson\r MCI (H)",
    "Player_4": "Dalot\r EVE (H)",
    "Player_8": "Amad\r EVE (H)",
    "Player_9": "Wood\r 9",
    "Player_15": "Digne\r CHE (A)"
  },
  {
    "manager_Name": "857( 1,214 ) TotalXfr : 11",
    "Teams": "Chaker bellili( Chaker bellili\uD83C\uDDF9\uD83C\uDDF3 )",
    "SXL": "Tunisia",
    "Latp": "49",
    "Player_1": "Flekken\r 2",
    "Player_11": "Strand Larsen\r 11",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Watkins\r CHE (A)",
    "Player_14": "Digne\r CHE (A)",
    "Player_7": "Mbeumo\r 4",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Garnacho\r EVE (H)",
    "Player_6": "Saka\r 18",
    "Player_3": "Aina\r 8",
    "Player_4": "Estupi\u00F1an\r 4",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Palmer\r AVL (H)",
    "Player_15": "Lacroix\r 2"
  },
  {
    "manager_Name": "857( 1,260 ) TotalXfr : 13",
    "Teams": "\u0627\u0644\u0634\u0631\u0642\u0627\u0648\u064A( \u0645\u062D\u0645\u062F \u0627\u0644\u0634\u0631\u0642\u0627\u0648\u064A )",
    "SXL": "Egypt",
    "Latp": "51",
    "Player_1": "Flekken\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Dennis\r 0",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Keane\r MUN (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Digne\r CHE (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Lewis\r LIV (A)",
    "Player_4": "Faes\r 0",
    "Player_8": "Saka\r 36",
    "Player_9": "Wood\r 9",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "856( 1,324 ) TotalXfr : 11",
    "Teams": "Juligram( \uD83D\uDC51 King Julian )",
    "SXL": "Nigeria",
    "Latp": "44",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Isak\r 1",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Gvardiol\r LIV (A)",
    "Player_14": "Beto\r MUN (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Amad\r EVE (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "J.Timber\r 1",
    "Player_4": "Martinez\r EVE (H)",
    "Player_8": "Saka\r 36",
    "Player_9": "M.Salah\r MCI (H)",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "856( 1,356 ) TotalXfr : 12",
    "Teams": "Peter mkuu( Peter Momanyi )",
    "SXL": "Kenya",
    "Latp": "41",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Wissa\r 8",
    "Player_10": "Strand Larsen\r 11",
    "Player_12": "Turner\r 0",
    "Player_13": "Watkins\r CHE (A)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Dalot\r EVE (H)",
    "Player_5": "Saka\r 18",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Digne\r CHE (A)",
    "Player_4": "Robertson\r MCI (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Kulusevski\r FUL (H)",
    "Player_15": "Tuanzebe\r 1"
  },
  {
    "manager_Name": "855( 1,406 ) TotalXfr : 10",
    "Teams": "Ne\u2B55\uFE0FRusH73\uFFFD( ozzy73 \uD83D\uDE08 )",
    "SXL": "Brunei Darussalam",
    "Latp": "42",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Wood\r 9",
    "Player_10": "Ra\u00FAl\r TOT (A)",
    "Player_12": "Leno\r TOT (A)",
    "Player_13": "Aina\r 8",
    "Player_14": "Smith Rowe\r TOT (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Van Hecke\r 2",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Saka\r 18",
    "Player_9": "Cunha\r 2",
    "Player_15": "Konat\u00E9\r MCI (H)"
  },
  {
    "manager_Name": "855( 1,406 ) TotalXfr : 10",
    "Teams": "Curry Basi( Juergen Curry )",
    "SXL": "Malaysia",
    "Latp": "48",
    "Player_1": "Sels\r 6",
    "Player_11": "Wissa\r 16",
    "Player_10": "H\u00F8jlund\r EVE (H)",
    "Player_12": "Martinez\r CHE (A)",
    "Player_13": "Robinson\r TOT (A)",
    "Player_14": "Vardy\r 5",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Dunk\r 1",
    "Player_5": "Smith Rowe\r TOT (A)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Veltman\r 0",
    "Player_4": "Collins\r 5",
    "Player_8": "Saka\r 18",
    "Player_9": "Palmer\r AVL (H)",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "855( 1,432 ) TotalXfr : 11",
    "Teams": "THE INVADERS( Football Plug Media )",
    "SXL": "Nigeria",
    "Latp": "26",
    "Player_1": "Raya\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Steele\r 0",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Barnes\r 2",
    "Player_6": "Saka\r 18",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "Gvardiol\r LIV (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Cunha\r 2",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "855( 1,502 ) TotalXfr : 13",
    "Teams": "York \uFFFD( Ezra Fantahun )",
    "SXL": "Ethiopia",
    "Latp": "43",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Wood\r 9",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Delap\r 2",
    "Player_14": "Milenkovi\u0107\r 6",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Aina\r 8",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Gvardiol\r LIV (A)",
    "Player_4": "Hall\r 2",
    "Player_8": "Saka\r 18",
    "Player_9": "Maddison\r FUL (H)",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "855( 1,520 ) TotalXfr : 14",
    "Teams": "ATOMIKCITY FC( Sunday Onabanjo )",
    "SXL": "Nigeria",
    "Latp": "58",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Cunha\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Palmer\r AVL (H)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Dalot\r EVE (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Saka\r 36",
    "Player_3": "Aina\r 8",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Wissa\r 8",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "855( 1,530 ) TotalXfr : 15",
    "Teams": "DRM( Saroj Chhetri )",
    "SXL": "Finland",
    "Latp": "44",
    "Player_1": "Pickford\r MUN (A)",
    "Player_11": "Cunha\r 2",
    "Player_10": "Isak\r 1",
    "Player_12": "Turner\r 0",
    "Player_13": "Faes\r 0",
    "Player_14": "Wood\r 9",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Akanji\r LIV (A)",
    "Player_5": "Saka\r 36",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Garnacho\r EVE (H)",
    "Player_9": "Gordon\r 5",
    "Player_15": "Keane\r MUN (A)"
  }
];