var s = [
  {
    "manager_Name": "876( 13 ) TotalXfr : 14",
    "Teams": "Joelinton Enjoyer( James White )",
    "SXL": "New Zealand",
    "Latp": "4",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Dennis\r WOL (A)",
    "Player_13": "Wissa\r LEI (H)",
    "Player_14": "Mykolenko\r MUN (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Collins\r LEI (H)",
    "Player_4": "Hall\r CRY (A)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "Mbeumo\r LEI (H)",
    "Player_15": "Greaves\r NFO (A)"
  },
  {
    "manager_Name": "872( 16 ) TotalXfr : 12",
    "Teams": "SC Villa Jogoo( Godfrey Lusiba )",
    "SXL": "Uganda",
    "Latp": "2",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Pickford\r MUN (A)",
    "Player_13": "Evanilson\r WOL (A)",
    "Player_14": "Davis\r NFO (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Pedro Porro\r FUL (H)",
    "Player_5": "A\u00EFt-Nouri\r BOU (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "Dalot\r EVE (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Saka\r WHU (A)",
    "Player_15": "Smith Rowe\r TOT (A)"
  },
  {
    "manager_Name": "871( 18 ) TotalXfr : 10",
    "Teams": "Trust the Process ;)( Robb Lacey )",
    "SXL": "England",
    "Latp": "4",
    "Player_1": "Verbruggen\r 4",
    "Player_11": "Evanilson\r WOL (A)",
    "Player_10": "Watkins\r CHE (A)",
    "Player_12": "Pickford\r MUN (A)",
    "Player_13": "Bowen\r ARS (H)",
    "Player_14": "Gvardiol\r LIV (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Van den Berg\r LEI (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "Saka\r WHU (A)",
    "Player_3": "Pinnock\r LEI (H)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Solanke\r FUL (H)",
    "Player_15": "Mykolenko\r MUN (A)"
  },
  {
    "manager_Name": "865( 37 ) TotalXfr : 9",
    "Teams": "Alex( Alex Lindholm )",
    "SXL": "Japan",
    "Latp": "4",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "B.Fernandes\r EVE (H)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "F.Kad\u0131o\u011Flu\r 0",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "Konat\u00E9\r MCI (H)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Digne\r CHE (A)"
  },
  {
    "manager_Name": "865( 38 ) TotalXfr : 10",
    "Teams": "Charlie\u2019s team( Charlie Shepherd )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Isak\r CRY (A)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Dennis\r WOL (A)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Konsa\r CHE (A)",
    "Player_7": "Mbeumo\r LEI (H)",
    "Player_2": "Gabriel\r WHU (A)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Robinson\r TOT (A)",
    "Player_4": "Konat\u00E9\r MCI (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Greaves\r NFO (A)"
  },
  {
    "manager_Name": "862( 52 ) TotalXfr : 10",
    "Teams": "Jesus\u0027 Disciples( Kristiaan Thomas )",
    "SXL": "England",
    "Latp": "10",
    "Player_1": "Fabianski\r ARS (H)",
    "Player_11": "Watkins\r CHE (A)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Digne\r CHE (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Gomez\r MCI (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mitoma\r 10",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "Rogers\r CHE (A)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Thomas\r BRE (A)"
  },
  {
    "manager_Name": "856( 83 ) TotalXfr : 9",
    "Teams": "FreakySlugKicks( Hugo Beattie )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Digne\r CHE (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Konat\u00E9\r MCI (H)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Gabriel\r WHU (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Stephens\r 4"
  },
  {
    "manager_Name": "855( 98 ) TotalXfr : 13",
    "Teams": "Womp, womp.( Stephen Blakemore )",
    "SXL": "England",
    "Latp": "3",
    "Player_1": "Pickford\r MUN (A)",
    "Player_11": "Wissa\r LEI (H)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Saka\r WHU (A)",
    "Player_3": "Dunk\r 1",
    "Player_4": "Davis\r NFO (A)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Mykolenko\r MUN (A)"
  },
  {
    "manager_Name": "852( 118 ) TotalXfr : 10",
    "Teams": "Call1800JOELINTON( Leyshon Betts )",
    "SXL": "Australia",
    "Latp": "0",
    "Player_1": "Kelleher\r MCI (H)",
    "Player_11": "Isak\r CRY (A)",
    "Player_10": "Watkins\r CHE (A)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "Rogers\r CHE (A)",
    "Player_3": "Mykolenko\r MUN (A)",
    "Player_4": "Burgess\r NFO (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Andersen\r TOT (A)"
  },
  {
    "manager_Name": "848( 168 ) TotalXfr : 12",
    "Teams": "Ez( Eamon Olama )",
    "SXL": "England",
    "Latp": "0",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Wissa\r LEI (H)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Sels\r IPS (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Konsa\r CHE (A)",
    "Player_7": "Saka\r WHU (A)",
    "Player_2": "Dalot\r EVE (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Aina\r IPS (H)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Wan-Bissaka\r ARS (H)"
  },
  {
    "manager_Name": "847( 195 ) TotalXfr : 14",
    "Teams": "Levenshulme Utd( Max Littleproud )",
    "SXL": "England",
    "Latp": "0",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Wood\r IPS (H)",
    "Player_10": "Isak\r CRY (A)",
    "Player_12": "Matthews\r NEW (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Young\r MUN (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Aina\r IPS (H)",
    "Player_4": "Gabriel\r WHU (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Greaves\r NFO (A)"
  },
  {
    "manager_Name": "846( 198 ) TotalXfr : 10",
    "Teams": "Feel Wood Inc( Jake Poplawski )",
    "SXL": "England",
    "Latp": "0",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Wood\r IPS (H)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Hall\r CRY (A)",
    "Player_14": "Rogers\r CHE (A)",
    "Player_7": "Saka\r WHU (A)",
    "Player_2": "Aina\r IPS (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "B.Fernandes\r EVE (H)",
    "Player_9": "Isak\r CRY (A)",
    "Player_15": "Andersen\r TOT (A)"
  },
  {
    "manager_Name": "846( 198 ) TotalXfr : 10",
    "Teams": "Haven\u2019t Jota Clue( Luke Armitage )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Wissa\r LEI (H)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Flekken\r LEI (H)",
    "Player_13": "Pau\r CHE (A)",
    "Player_14": "Mavididi\r BRE (A)",
    "Player_7": "Mbeumo\r LEI (H)",
    "Player_2": "Gabriel\r WHU (A)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "Colwill\r AVL (H)",
    "Player_8": "B.Fernandes\r EVE (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Mykolenko\r MUN (A)"
  },
  {
    "manager_Name": "845( 220 ) TotalXfr : 9",
    "Teams": "dabaly._( Dabaly Hailu )",
    "SXL": "Kenya",
    "Latp": "12",
    "Player_1": "Kelleher\r MCI (H)",
    "Player_11": "Wissa\r LEI (H)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Faes\r BRE (A)",
    "Player_14": "Gordon\r CRY (A)",
    "Player_7": "Mitoma\r 10",
    "Player_2": "Alexander-Arnold\r MCI (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Veltman\r 0",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Mykolenko\r MUN (A)"
  },
  {
    "manager_Name": "845( 236 ) TotalXfr : 12",
    "Teams": "Jake Ashivor Fc\uFFFD( Jacob Ashivor )",
    "SXL": "Nigeria",
    "Latp": "12",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Sels\r IPS (H)",
    "Player_13": "Ndiaye\r MUN (A)",
    "Player_14": "Cucurella\r AVL (H)",
    "Player_7": "Luis D\u00EDaz\r MCI (H)",
    "Player_2": "Aina\r IPS (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mitoma\r 10",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "Alexander-Arnold\r MCI (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Mbeumo\r LEI (H)",
    "Player_15": "Colwill\r AVL (H)"
  },
  {
    "manager_Name": "844( 253 ) TotalXfr : 11",
    "Teams": "Arne Slotmachine( Wayne Jenkinson )",
    "SXL": "Australia",
    "Latp": "2",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Solanke\r FUL (H)",
    "Player_12": "Henderson\r NEW (H)",
    "Player_13": "McNeil\r MUN (A)",
    "Player_14": "Gvardiol\r LIV (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "Son\r FUL (H)",
    "Player_3": "Van den Berg\r LEI (H)",
    "Player_4": "Gabriel\r WHU (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Wood\r IPS (H)",
    "Player_15": "Nedeljkovic\r CHE (A)"
  },
  {
    "manager_Name": "843( 277 ) TotalXfr : 11",
    "Teams": "Rodri handball( Wei Ping Tan )",
    "SXL": "Singapore",
    "Latp": "12",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Watkins\r CHE (A)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Colwill\r AVL (H)",
    "Player_14": "Keane\r MUN (A)",
    "Player_7": "Mitoma\r 10",
    "Player_2": "Gabriel\r WHU (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Konat\u00E9\r MCI (H)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Dibling\r 1"
  },
  {
    "manager_Name": "842( 305 ) TotalXfr : 10",
    "Teams": "Kuruvi FC( Ragu Subramaniam )",
    "SXL": "Malaysia",
    "Latp": "2",
    "Player_1": "Henderson\r NEW (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Pickford\r MUN (A)",
    "Player_13": "Gabriel\r WHU (A)",
    "Player_14": "Aina\r IPS (H)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Veltman\r 0",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Isak\r CRY (A)",
    "Player_15": "Moder\r 0"
  },
  {
    "manager_Name": "841( 338 ) TotalXfr : 9",
    "Teams": "GOGOSTYLE( Thamsanqa Banda )",
    "SXL": "South Africa",
    "Latp": "0",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Isak\r CRY (A)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Archer\r 2",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Veltman\r 0",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Hall\r CRY (A)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "B.Fernandes\r EVE (H)",
    "Player_15": "O\u0027Shea\r NFO (A)"
  },
  {
    "manager_Name": "840( 388 ) TotalXfr : 11",
    "Teams": "Phantacci\u2B50\uFE0FPro.11( Akwaboah . )",
    "SXL": "Ghana",
    "Latp": "2",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Isak\r CRY (A)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Sels\r IPS (H)",
    "Player_13": "Digne\r CHE (A)",
    "Player_14": "Semenyo\r WOL (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "J.Timber\r WHU (A)",
    "Player_4": "Robinson\r TOT (A)",
    "Player_8": "B.Fernandes\r EVE (H)",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "839( 406 ) TotalXfr : 10",
    "Teams": "Cyprian_Utd( Cyprian Peter )",
    "SXL": "Nigeria",
    "Latp": "2",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Raya\r WHU (A)",
    "Player_13": "Luis D\u00EDaz\r MCI (H)",
    "Player_14": "Faes\r BRE (A)",
    "Player_7": "Mbeumo\r LEI (H)",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Saka\r WHU (A)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "Aina\r IPS (H)",
    "Player_8": "Amad\r EVE (H)",
    "Player_9": "Wood\r IPS (H)",
    "Player_15": "Robertson\r MCI (H)"
  },
  {
    "manager_Name": "838( 455 ) TotalXfr : 11",
    "Teams": "Here we go again-( Daniel Johansson )",
    "SXL": "Sweden",
    "Latp": "4",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Isak\r CRY (A)",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Hall\r CRY (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gabriel\r WHU (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Gvardiol\r LIV (A)"
  },
  {
    "manager_Name": "838( 455 ) TotalXfr : 11",
    "Teams": "lankans Rule( Mulitha De Silva )",
    "SXL": "Australia",
    "Latp": "6",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Isak\r CRY (A)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Konat\u00E9\r MCI (H)",
    "Player_14": "Rogers\r CHE (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Van Hecke\r 2",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Andersen\r TOT (A)"
  },
  {
    "manager_Name": "837( 488 ) TotalXfr : 10",
    "Teams": "Benzinac 44( Andrija Savic )",
    "SXL": "Serbia",
    "Latp": "4",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Isak\r CRY (A)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Semenyo\r WOL (A)",
    "Player_14": "A\u00EFt-Nouri\r BOU (H)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Van Hecke\r 2",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "Hall\r CRY (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Konat\u00E9\r MCI (H)"
  },
  {
    "manager_Name": "837( 507 ) TotalXfr : 12",
    "Teams": "shin tai( Matar Cama )",
    "SXL": "Senegal",
    "Latp": "2",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Solanke\r FUL (H)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Flekken\r LEI (H)",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Mbeumo\r LEI (H)",
    "Player_2": "Gvardiol\r LIV (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "N.Jackson\r AVL (H)",
    "Player_15": "Faes\r BRE (A)"
  },
  {
    "manager_Name": "836( 554 ) TotalXfr : 14",
    "Teams": "Anfield Rovers( Michael Turner )",
    "SXL": "South Africa",
    "Latp": "4",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Gvardiol\r LIV (A)",
    "Player_7": "Saka\r WHU (A)",
    "Player_2": "Robinson\r TOT (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Gabriel\r WHU (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Faes\r BRE (A)"
  },
  {
    "manager_Name": "835( 606 ) TotalXfr : 13",
    "Teams": "Welby Too Well( Peter Firth )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Valdimarsson\r LEI (H)",
    "Player_13": "Lewis\r LIV (A)",
    "Player_14": "Faes\r BRE (A)",
    "Player_7": "Son\r FUL (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "Aina\r IPS (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "M.Salah\r MCI (H)",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "834( 666 ) TotalXfr : 13",
    "Teams": "ArseneKnows FC( Ato Baah )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Arrizabalaga\r WOL (A)",
    "Player_13": "Ra\u00FAl\r TOT (A)",
    "Player_14": "Keane\r MUN (A)",
    "Player_7": "Mbeumo\r LEI (H)",
    "Player_2": "Gabriel\r WHU (A)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Collins\r LEI (H)",
    "Player_4": "Gvardiol\r LIV (A)",
    "Player_8": "B.Fernandes\r EVE (H)",
    "Player_9": "Saka\r WHU (A)",
    "Player_15": "Nedeljkovic\r CHE (A)"
  },
  {
    "manager_Name": "833( 682 ) TotalXfr : 10",
    "Teams": "manshy( \u0645\u0635\u0637\u0641\u0649 \u062D\u0645\u062F\u064A )",
    "SXL": "Egypt",
    "Latp": "4",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Wissa\r LEI (H)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Johnson\r FUL (H)",
    "Player_14": "Digne\r CHE (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Livramento\r CRY (A)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "Saka\r WHU (A)",
    "Player_3": "Estupi\u00F1an\r 4",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Rashford\r EVE (H)",
    "Player_9": "Watkins\r CHE (A)",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "833( 694 ) TotalXfr : 11",
    "Teams": "SG Dynamo Dothraki( Dino Lehmann )",
    "SXL": "Switzerland",
    "Latp": "5",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Evanilson\r WOL (A)",
    "Player_14": "Hall\r CRY (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gabriel\r WHU (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Dunk\r 1",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Saka\r WHU (A)",
    "Player_15": "Konat\u00E9\r MCI (H)"
  },
  {
    "manager_Name": "833( 694 ) TotalXfr : 11",
    "Teams": "Ian\u0027s Idiots( ian scott )",
    "SXL": "Scotland",
    "Latp": "4",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Wissa\r LEI (H)",
    "Player_12": "Ramsdale\r 0",
    "Player_13": "Gvardiol\r LIV (A)",
    "Player_14": "Bernardo\r LIV (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Estupi\u00F1an\r 4",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Gabriel\r WHU (A)",
    "Player_8": "Garnacho\r EVE (H)",
    "Player_9": "Watkins\r CHE (A)",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "833( 720 ) TotalXfr : 13",
    "Teams": "Calum\u2019s XI( Calum Arnold )",
    "SXL": "Australia",
    "Latp": "2",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Isak\r CRY (A)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Robinson\r TOT (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Konsa\r CHE (A)"
  },
  {
    "manager_Name": "832( 732 ) TotalXfr : 10",
    "Teams": "Lila\u2019s Team( Lila Endo )",
    "SXL": "USA",
    "Latp": "0",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Solanke\r FUL (H)",
    "Player_12": "Benda\r TOT (A)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Van den Berg\r LEI (H)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Dalot\r EVE (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Aina\r IPS (H)",
    "Player_4": "Gabriel\r WHU (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Isak\r CRY (A)",
    "Player_15": "Greaves\r NFO (A)"
  },
  {
    "manager_Name": "832( 754 ) TotalXfr : 11",
    "Teams": "Ghalib fc( Abdulsalam Hamzat )",
    "SXL": "Nigeria",
    "Latp": "10",
    "Player_1": "Leno\r TOT (A)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Turner\r NEW (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Tete\r TOT (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Aina\r IPS (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "Mitoma\r 10",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Wood\r IPS (H)",
    "Player_15": "Digne\r CHE (A)"
  },
  {
    "manager_Name": "831( 818 ) TotalXfr : 11",
    "Teams": "Petronija FC( Petar Stojanovski )",
    "SXL": "Macedonia",
    "Latp": "12",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Wood\r IPS (H)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Sels\r IPS (H)",
    "Player_13": "M.Salah\r MCI (H)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Saka\r WHU (A)",
    "Player_2": "Davis\r NFO (A)",
    "Player_5": "Mitoma\r 10",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Udogie\r FUL (H)",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Gvardiol\r LIV (A)"
  },
  {
    "manager_Name": "831( 849 ) TotalXfr : 13",
    "Teams": "MICKY( Michael Adeolu )",
    "SXL": "Nigeria",
    "Latp": "2",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Solanke\r FUL (H)",
    "Player_12": "Turner\r NEW (H)",
    "Player_13": "Gvardiol\r LIV (A)",
    "Player_14": "Alexander-Arnold\r MCI (H)",
    "Player_7": "Saka\r WHU (A)",
    "Player_2": "Pedro Porro\r FUL (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Davis\r NFO (A)",
    "Player_4": "Burn\r CRY (A)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Wood\r IPS (H)",
    "Player_15": "Semenyo\r WOL (A)"
  },
  {
    "manager_Name": "830( 877 ) TotalXfr : 11",
    "Teams": "Woodydagreatest( Robert Wood )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Johnson\r FUL (H)",
    "Player_14": "Hall\r CRY (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Aina\r IPS (H)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "Wood\r IPS (H)",
    "Player_15": "Van den Berg\r LEI (H)"
  },
  {
    "manager_Name": "830( 904 ) TotalXfr : 12",
    "Teams": "Robsdale XI( Robert Burt )",
    "SXL": "England",
    "Latp": "0",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Wood\r IPS (H)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Solanke\r FUL (H)",
    "Player_14": "Veltman\r 0",
    "Player_7": "Saka\r WHU (A)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "De Ligt\r EVE (H)",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Bowen\r ARS (H)",
    "Player_15": "Tuanzebe\r NFO (A)"
  },
  {
    "manager_Name": "830( 904 ) TotalXfr : 12",
    "Teams": "aMouriN\\ho( Virinder Gupta )",
    "SXL": "India",
    "Latp": "0",
    "Player_1": "Steele\r 0",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Wood\r IPS (H)",
    "Player_12": "Flekken\r LEI (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Burn\r CRY (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Andersen\r TOT (A)",
    "Player_5": "B.Fernandes\r EVE (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "Dalot\r EVE (H)",
    "Player_8": "Foden\r LIV (A)",
    "Player_9": "Ra\u00FAl\r TOT (A)",
    "Player_15": "Mykolenko\r MUN (A)"
  },
  {
    "manager_Name": "830( 904 ) TotalXfr : 12",
    "Teams": "Boom Xhakalala( Karol Pinczynski )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Henderson\r NEW (H)",
    "Player_11": "Wissa\r LEI (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Turner\r NEW (H)",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "Rogers\r CHE (A)",
    "Player_3": "Konat\u00E9\r MCI (H)",
    "Player_4": "Virgil\r MCI (H)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Haaland\r LIV (A)",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "829( 941 ) TotalXfr : 9",
    "Teams": "Wally Otkins( Terence Corrigan )",
    "SXL": "England",
    "Latp": "0",
    "Player_1": "Sels\r IPS (H)",
    "Player_11": "Wissa\r LEI (H)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Hall\r CRY (A)",
    "Player_7": "Mbeumo\r LEI (H)",
    "Player_2": "Gabriel\r WHU (A)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Saka\r WHU (A)",
    "Player_3": "Konat\u00E9\r MCI (H)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Isak\r CRY (A)",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "829( 945 ) TotalXfr : 10",
    "Teams": "Deez Nutmegs( Geoffrey Langham )",
    "SXL": "USA",
    "Latp": "0",
    "Player_1": "Sels\r IPS (H)",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Wissa\r LEI (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Konat\u00E9\r MCI (H)",
    "Player_14": "Johnson\r FUL (H)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Aina\r IPS (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "Wood\r IPS (H)",
    "Player_15": "Greaves\r NFO (A)"
  },
  {
    "manager_Name": "829( 958 ) TotalXfr : 11",
    "Teams": "The Interlopers( Edward Lee )",
    "SXL": "Australia",
    "Latp": "0",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Ra\u00FAl\r TOT (A)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Gvardiol\r LIV (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Aina\r IPS (H)",
    "Player_5": "Johnson\r FUL (H)",
    "Player_6": "Saka\r WHU (A)",
    "Player_3": "Van den Berg\r LEI (H)",
    "Player_4": "Gabriel\r WHU (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Isak\r CRY (A)",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "829( 958 ) TotalXfr : 11",
    "Teams": "Ain\u0027t jota clue( Pranavh Chari )",
    "SXL": "New Zealand",
    "Latp": "6",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Isak\r CRY (A)",
    "Player_10": "Jo\u00E3o Pedro\r 4",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Colwill\r AVL (H)",
    "Player_14": "Konat\u00E9\r MCI (H)",
    "Player_7": "Mbeumo\r LEI (H)",
    "Player_2": "Veltman\r 0",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "Hall\r CRY (A)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Semenyo\r WOL (A)"
  },
  {
    "manager_Name": "828( 1,020 ) TotalXfr : 9",
    "Teams": "Dark Knights( Ryan Rajah )",
    "SXL": "South Africa",
    "Latp": "2",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Wissa\r LEI (H)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Garnacho\r EVE (H)",
    "Player_14": "Gvardiol\r LIV (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "Davis\r NFO (A)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "828( 1,029 ) TotalXfr : 10",
    "Teams": "SilvaLining( James Wilson )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Isak\r CRY (A)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Johnson\r FUL (H)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Collins\r LEI (H)",
    "Player_4": "J.Timber\r WHU (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Konsa\r CHE (A)"
  },
  {
    "manager_Name": "828( 1,029 ) TotalXfr : 10",
    "Teams": "Ben( Farhan Mustafa )",
    "SXL": "Malaysia",
    "Latp": "3",
    "Player_1": "Henderson\r NEW (H)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Isak\r CRY (A)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Colwill\r AVL (H)",
    "Player_14": "Rogers\r CHE (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gabriel\r WHU (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Dunk\r 1",
    "Player_4": "Hall\r CRY (A)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "N.Jackson\r AVL (H)",
    "Player_15": "O\u0027Shea\r NFO (A)"
  },
  {
    "manager_Name": "828( 1,029 ) TotalXfr : 10",
    "Teams": "TikiTaka( Sean Bailey )",
    "SXL": "Ireland",
    "Latp": "4",
    "Player_1": "Henderson\r NEW (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Jo\u00E3o Pedro\r 4",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Bowen\r ARS (H)",
    "Player_14": "Konat\u00E9\r MCI (H)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Davis\r NFO (A)",
    "Player_4": "Gabriel\r WHU (A)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "Wood\r IPS (H)",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "828( 1,095 ) TotalXfr : 12",
    "Teams": "Henry Standish Owls( Henry McLeod )",
    "SXL": "England",
    "Latp": "10",
    "Player_1": "Kelleher\r MCI (H)",
    "Player_11": "Evanilson\r WOL (A)",
    "Player_10": "Wissa\r LEI (H)",
    "Player_12": "Henderson\r NEW (H)",
    "Player_13": "Robinson\r TOT (A)",
    "Player_14": "Rogers\r CHE (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Alexander-Arnold\r MCI (H)",
    "Player_5": "Mitoma\r 10",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Aina\r IPS (H)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "Son\r FUL (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Gvardiol\r LIV (A)"
  },
  {
    "manager_Name": "827( 1,130 ) TotalXfr : 9",
    "Teams": "MikeWiLLmadeit( Michael Williams )",
    "SXL": "Kenya",
    "Latp": "2",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Isak\r CRY (A)",
    "Player_12": "Slicker\r NFO (A)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Gvardiol\r LIV (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Dalot\r EVE (H)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Hall\r CRY (A)",
    "Player_4": "Robinson\r TOT (A)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Johnson\r NFO (A)"
  },
  {
    "manager_Name": "487( 9,076,440 ) TotalXfr : 32",
    "Teams": "Mwaura Kennedy( Mwaura Kennedy )",
    "SXL": "Kenya",
    "Latp": "0",
    "Player_1": "Pickford\r MUN (A)",
    "Player_11": "Watkins\r CHE (A)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Martinez\r CHE (A)",
    "Player_13": "Keane\r MUN (A)",
    "Player_14": "Tuanzebe\r NFO (A)",
    "Player_7": "Son\r FUL (H)",
    "Player_2": "Dragusin\r FUL (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Saka\r WHU (A)",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "Veltman\r 0",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Wood\r IPS (H)",
    "Player_15": "Adama\r TOT (A)"
  },
  {
    "manager_Name": "760( 123,941 ) TotalXfr : 12",
    "Teams": "Sye Lohrenz( Sye Lohrenz )",
    "SXL": "Australia",
    "Latp": "2",
    "Player_1": "Sels\r IPS (H)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Wood\r IPS (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Konat\u00E9\r MCI (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "Robinson\r TOT (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "N.Jackson\r AVL (H)",
    "Player_15": "Harwood-Bellis\r 1"
  }
];