var s = [
  {
    "manager_Name": "851( 1,934 ) TotalXfr : 9",
    "Teams": "Gunners 24( Suumit Bhardwaj )",
    "SXL": "India",
    "Latp": "36",
    "Player_1": "Raya\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Wissa\r 6",
    "Player_12": "Flekken\r 2",
    "Player_13": "Strand Larsen\r 9",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Gabriel\r 9",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Saka\r 15",
    "Player_3": "Konat\u00E9\r MCI (H)",
    "Player_4": "Lewis\r LIV (A)",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Rogers\r CHE (A)",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "810( 32,848 ) TotalXfr : 10",
    "Teams": "YoroOYoro( Rajdeep Gupta )",
    "SXL": "India",
    "Latp": "9",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Konat\u00E9\r MCI (H)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Colwill\r AVL (H)",
    "Player_4": "Hall\r 2",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "N.Jackson\r AVL (H)",
    "Player_15": "Burgess\r 2"
  },
  {
    "manager_Name": "782( 146,072 ) TotalXfr : 13",
    "Teams": "Gooner_Psy( Saiprasad Shankar )",
    "SXL": "India",
    "Latp": "36",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Wissa\r 6",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Garnacho\r EVE (H)",
    "Player_14": "Hall\r 2",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Neto\r AVL (H)",
    "Player_3": "Gabriel\r 9",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Saka\r 15",
    "Player_9": "Cunha\r 2",
    "Player_15": "Digne\r CHE (A)"
  },
  {
    "manager_Name": "780( 156,993 ) TotalXfr : 11",
    "Teams": "GoonerXI( Siddharth Kamath )",
    "SXL": "USA",
    "Latp": "53",
    "Player_1": "Flekken\r 2",
    "Player_11": "Wood\r 6",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Winks\r 0",
    "Player_14": "Barco\r 0",
    "Player_7": "Saka\r 30",
    "Player_2": "Gabriel\r 9",
    "Player_5": "J.Gomes\r 2",
    "Player_6": "Luis D\u00EDaz\r MCI (H)",
    "Player_3": "Hall\r 2",
    "Player_4": "Konat\u00E9\r MCI (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Haaland\r LIV (A)",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "778( 174,906 ) TotalXfr : 13",
    "Teams": "DangerDon( Rohit Nate )",
    "SXL": "India",
    "Latp": "30",
    "Player_1": "Flekken\r 2",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "McNeil\r MUN (A)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Rogers\r CHE (A)",
    "Player_2": "Hall\r 2",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Robinson\r TOT (A)",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Saka\r 15",
    "Player_9": "Strand Larsen\r 9",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "777( 182,777 ) TotalXfr : 13",
    "Teams": "FALSE 9( Rohan Rai )",
    "SXL": "India",
    "Latp": "47",
    "Player_1": "Henderson\r 2",
    "Player_11": "Welbeck\r 2",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Digne\r CHE (A)",
    "Player_7": "Saka\r 30",
    "Player_2": "Gvardiol\r LIV (A)",
    "Player_5": "Smith Rowe\r TOT (A)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Robinson\r TOT (A)",
    "Player_4": "Gabriel\r 9",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Cunha\r 2",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "775( 195,636 ) TotalXfr : 11",
    "Teams": "Kishore\u2019s Rascals( Nandakishore K )",
    "SXL": "India",
    "Latp": "48",
    "Player_1": "Flekken\r 2",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Mykolenko\r MUN (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Saliba\r 1",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Saka\r 30",
    "Player_3": "Van den Berg\r 2",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "B.Fernandes\r EVE (H)",
    "Player_9": "Strand Larsen\r 9",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "772( 222,277 ) TotalXfr : 11",
    "Teams": "Sakalicous( Sachin thakur )",
    "SXL": "India",
    "Latp": "42",
    "Player_1": "Sels\r 6",
    "Player_11": "Isak\r 2",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Kelleher\r MCI (H)",
    "Player_13": "McNeil\r MUN (A)",
    "Player_14": "Smith Rowe\r TOT (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Gvardiol\r LIV (A)",
    "Player_6": "Johnson\r FUL (H)",
    "Player_3": "Aina\r 6",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Saka\r 15",
    "Player_9": "Cunha\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "761( 342,507 ) TotalXfr : 9",
    "Teams": "Narayan Narayan!( Rakeshlal Gopiram nathani )",
    "SXL": "India",
    "Latp": "14",
    "Player_1": "Flekken\r 2",
    "Player_11": "Solanke\r FUL (H)",
    "Player_10": "Havertz\r 6",
    "Player_12": "Martinez\r CHE (A)",
    "Player_13": "Virgil\r MCI (H)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "McNeil\r MUN (A)",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "B.Fernandes\r EVE (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Gvardiol\r LIV (A)",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Wissa\r 6",
    "Player_15": "Sangar\u00E9\r 0"
  },
  {
    "manager_Name": "760( 358,395 ) TotalXfr : 11",
    "Teams": "Arsenal( Kunal Modi )",
    "SXL": "India",
    "Latp": "51",
    "Player_1": "Henderson\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Dibling\r 1",
    "Player_14": "Keane\r MUN (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Rogers\r CHE (A)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Saka\r 30",
    "Player_9": "Wood\r 6",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "756( 415,101 ) TotalXfr : 11",
    "Teams": "Dwiz Mania( Dhawal Toppo )",
    "SXL": "India",
    "Latp": "12",
    "Player_1": "Raya\r 2",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Ra\u00FAl\r TOT (A)",
    "Player_12": "Henderson\r 2",
    "Player_13": "Gvardiol\r LIV (A)",
    "Player_14": "Digne\r CHE (A)",
    "Player_7": "Luis D\u00EDaz\r MCI (H)",
    "Player_2": "Aina\r 6",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "Virgil\r MCI (H)",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Winks\r 0"
  },
  {
    "manager_Name": "755( 433,672 ) TotalXfr : 12",
    "Teams": "lakaka( Kabeer Bhagat )",
    "SXL": "India",
    "Latp": "29",
    "Player_1": "Flekken\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Wissa\r 6",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Burgess\r 2",
    "Player_14": "Konsa\r CHE (A)",
    "Player_7": "Smith Rowe\r TOT (A)",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Saka\r 15",
    "Player_3": "Van den Berg\r 2",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Cunha\r 2",
    "Player_15": "Rogers\r CHE (A)"
  },
  {
    "manager_Name": "752( 475,447 ) TotalXfr : 9",
    "Teams": "RED_DEVils_XI( Devraj Redkar )",
    "SXL": "England",
    "Latp": "18",
    "Player_1": "Sels\r 6",
    "Player_11": "Wood\r 6",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Raya\r 2",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Faes\r 0",
    "Player_7": "Mbeumo\r 4",
    "Player_2": "Gvardiol\r LIV (A)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Robinson\r TOT (A)",
    "Player_4": "Robertson\r MCI (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Cunha\r 2",
    "Player_15": "Konsa\r CHE (A)"
  },
  {
    "manager_Name": "752( 476,319 ) TotalXfr : 10",
    "Teams": "Deys Knights( Rohan Dey )",
    "SXL": "India",
    "Latp": "26",
    "Player_1": "Henderson\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Havertz\r 6",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Konsa\r CHE (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Robinson\r TOT (A)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Saka\r 15",
    "Player_3": "Harwood-Bellis\r 1",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Smith Rowe\r TOT (A)",
    "Player_9": "Solanke\r FUL (H)",
    "Player_15": "Gvardiol\r LIV (A)"
  },
  {
    "manager_Name": "750( 519,399 ) TotalXfr : 13",
    "Teams": "Don\u2019t Jimmy Me Jules( Raunak Lamsal )",
    "SXL": "Nepal",
    "Latp": "40",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 4",
    "Player_10": "Wissa\r 6",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Mykolenko\r MUN (A)",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Saka\r 15",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "749( 534,238 ) TotalXfr : 12",
    "Teams": "Banter FC( Johann Duckworth )",
    "SXL": "India",
    "Latp": "10",
    "Player_1": "Flekken\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Ward\r 0",
    "Player_13": "Semenyo\r 0",
    "Player_14": "Faes\r 0",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Mykolenko\r MUN (A)",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Rogers\r CHE (A)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Hall\r 2",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Cunha\r 2",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "748( 558,974 ) TotalXfr : 15",
    "Teams": "amp( Aditya Patil )",
    "SXL": "India",
    "Latp": "34",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Wissa\r 6",
    "Player_12": "Flekken\r 2",
    "Player_13": "Johnson\r FUL (H)",
    "Player_14": "Archer\r 2",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Hall\r 2",
    "Player_5": "Lewis\r LIV (A)",
    "Player_6": "Rogers\r CHE (A)",
    "Player_3": "Gvardiol\r LIV (A)",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Saka\r 15",
    "Player_9": "B.Fernandes\r EVE (H)",
    "Player_15": "Quansah\r MCI (H)"
  },
  {
    "manager_Name": "746( 585,931 ) TotalXfr : 11",
    "Teams": "kalafiori( Adarsh Pakala )",
    "SXL": "Hong Kong",
    "Latp": "33",
    "Player_1": "Raya\r 2",
    "Player_11": "Delap\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Keane\r MUN (A)",
    "Player_14": "Andersen\r TOT (A)",
    "Player_7": "Saka\r 15",
    "Player_2": "Gabriel\r 9",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Smith Rowe\r TOT (A)",
    "Player_3": "Van Hecke\r 2",
    "Player_4": "Virgil\r MCI (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Isak\r 1",
    "Player_15": "Dibling\r 1"
  },
  {
    "manager_Name": "746( 589,965 ) TotalXfr : 12",
    "Teams": "Holding Ream Cash( Karan Thorat )",
    "SXL": "India",
    "Latp": "20",
    "Player_1": "Raya\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Muric\r 3",
    "Player_13": "Semenyo\r 0",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Hall\r 2",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Mykolenko\r MUN (A)",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Isak\r 1",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "745( 609,318 ) TotalXfr : 12",
    "Teams": "Space Invader( Amar Chandramohan )",
    "SXL": "India",
    "Latp": "61",
    "Player_1": "Raya\r 2",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Gvardiol\r LIV (A)",
    "Player_14": "Greaves\r 0",
    "Player_7": "Buonanotte\r 7",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Saka\r 30",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Aina\r 6",
    "Player_4": "Van den Berg\r 2",
    "Player_8": "Dibling\r 1",
    "Player_9": "Cunha\r 2",
    "Player_15": "Winks\r 0"
  },
  {
    "manager_Name": "741( 691,602 ) TotalXfr : 12",
    "Teams": "Blistering Barnacles( Sushanta Mondal )",
    "SXL": "India",
    "Latp": "53",
    "Player_1": "Flekken\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Saka\r 30",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Mykolenko\r MUN (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Havertz\r 6",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "741( 695,291 ) TotalXfr : 13",
    "Teams": "Change Name( Puneet Gupta )",
    "SXL": "India",
    "Latp": "22",
    "Player_1": "Sels\r 6",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Hall\r 2",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "J.Timber\r 1",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Martinelli\r 0",
    "Player_9": "Strand Larsen\r 9",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "741( 695,291 ) TotalXfr : 13",
    "Teams": "Kamada Dragons( Rohan Kapre )",
    "SXL": "India",
    "Latp": "49",
    "Player_1": "Flekken\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Mykolenko\r MUN (A)",
    "Player_7": "Mbeumo\r 4",
    "Player_2": "Tuanzebe\r 1",
    "Player_5": "Gordon\r 5",
    "Player_6": "Saka\r 15",
    "Player_3": "Digne\r CHE (A)",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Evanilson\r 11",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "739( 727,213 ) TotalXfr : 9",
    "Teams": "Va Va Voom( Piyush R )",
    "SXL": "USA",
    "Latp": "35",
    "Player_1": "Flekken\r 2",
    "Player_11": "Wood\r 6",
    "Player_10": "Solanke\r FUL (H)",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Keane\r MUN (A)",
    "Player_14": "Rogers\r CHE (A)",
    "Player_7": "Smith Rowe\r TOT (A)",
    "Player_2": "Gabriel\r 9",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Saka\r 15",
    "Player_3": "Gvardiol\r LIV (A)",
    "Player_4": "Konat\u00E9\r MCI (H)",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Isak\r 1",
    "Player_15": "Van de Ven\r FUL (H)"
  },
  {
    "manager_Name": "737( 776,813 ) TotalXfr : 11",
    "Teams": "AlibagFC( ONKAR POSANE )",
    "SXL": "India",
    "Latp": "12",
    "Player_1": "Pope\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Solanke\r FUL (H)",
    "Player_12": "Pickford\r MUN (A)",
    "Player_13": "Gvardiol\r LIV (A)",
    "Player_14": "Gabriel\r 9",
    "Player_7": "Mbeumo\r 4",
    "Player_2": "Digne\r CHE (A)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Alexander-Arnold\r MCI (H)",
    "Player_8": "Bowen\r 2",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Smith Rowe\r TOT (A)"
  },
  {
    "manager_Name": "735( 820,298 ) TotalXfr : 9",
    "Teams": "Here for Beer( Gaurav K )",
    "SXL": "India",
    "Latp": "40",
    "Player_1": "Henderson\r 2",
    "Player_11": "Cunha\r 4",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Martinez\r EVE (H)",
    "Player_14": "Dibling\r 1",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Saka\r 15",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Wood\r 6",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "734( 853,879 ) TotalXfr : 12",
    "Teams": "WengerBoys( Sanket Marwah )",
    "SXL": "India",
    "Latp": "14",
    "Player_1": "Pope\r 2",
    "Player_11": "Watkins\r CHE (A)",
    "Player_10": "Cunha\r 4",
    "Player_12": "Areola\r 0",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Johnson\r FUL (H)",
    "Player_2": "Pedro Porro\r FUL (H)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Gvardiol\r LIV (A)",
    "Player_4": "Young\r MUN (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Wood\r 6",
    "Player_15": "Okoli\r 0"
  },
  {
    "manager_Name": "733( 870,778 ) TotalXfr : 10",
    "Teams": "kopside( Hemanth SD )",
    "SXL": "India",
    "Latp": "20",
    "Player_1": "Flekken\r 2",
    "Player_11": "Solanke\r FUL (H)",
    "Player_10": "Ra\u00FAl\r TOT (A)",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Gabriel\r 9",
    "Player_14": "Rogers\r CHE (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Virgil\r MCI (H)",
    "Player_5": "Mitoma\r 10",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Wood\r 6",
    "Player_15": "Gvardiol\r LIV (A)"
  },
  {
    "manager_Name": "733( 878,850 ) TotalXfr : 12",
    "Teams": "AK59( Atul Kasbekar )",
    "SXL": "India",
    "Latp": "53",
    "Player_1": "Raya\r 2",
    "Player_11": "Evanilson\r 11",
    "Player_10": "Watkins\r CHE (A)",
    "Player_12": "Sels\r 6",
    "Player_13": "McNeil\r MUN (A)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Gvardiol\r LIV (A)",
    "Player_5": "Maddison\r FUL (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Alexander-Arnold\r MCI (H)",
    "Player_4": "Murillo\r 6",
    "Player_8": "Saka\r 30",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "733( 882,931 ) TotalXfr : 13",
    "Teams": "Danzig( Engelbert Dsilva )",
    "SXL": "Chinese Taipei",
    "Latp": "40",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Wissa\r 6",
    "Player_12": "Henderson\r 2",
    "Player_13": "McNeil\r MUN (A)",
    "Player_14": "Harwood-Bellis\r 1",
    "Player_7": "Saka\r 30",
    "Player_2": "Pedro Porro\r FUL (H)",
    "Player_5": "Rogers\r CHE (A)",
    "Player_6": "Neto\r AVL (H)",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Hall\r 2",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Cunha\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "730( 967,101 ) TotalXfr : 17",
    "Teams": "Captain\u00D8( Jebarwocky JD )",
    "SXL": "USA",
    "Latp": "53",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Cunha\r 2",
    "Player_10": "Wood\r 6",
    "Player_12": "Ramsdale\r 0",
    "Player_13": "Welbeck\r 2",
    "Player_14": "Keane\r MUN (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Aina\r 6",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Dalot\r EVE (H)",
    "Player_8": "Saka\r 30",
    "Player_9": "\u00D8degaard\r 7",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "729( 982,916 ) TotalXfr : 12",
    "Teams": "Jaanbaaz Shikari( Saurabh Mittal )",
    "SXL": "India",
    "Latp": "46",
    "Player_1": "Henderson\r 2",
    "Player_11": "Wissa\r 6",
    "Player_10": "Delap\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Aina\r 6",
    "Player_5": "Maddison\r FUL (H)",
    "Player_6": "Saka\r 15",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Virgil\r MCI (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Wood\r 6",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "729( 987,229 ) TotalXfr : 13",
    "Teams": "Leothrix FC( Tanmay Dey )",
    "SXL": "India",
    "Latp": "36",
    "Player_1": "Sels\r 6",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Cunha\r 2",
    "Player_12": "Henderson\r 2",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Konsa\r CHE (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Robinson\r TOT (A)",
    "Player_5": "Son\r FUL (H)",
    "Player_6": "Saka\r 15",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Smith Rowe\r TOT (A)",
    "Player_9": "Evanilson\r 11",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "726( 1,075,256 ) TotalXfr : 15",
    "Teams": "Emile\u0027s Mitron( Rohit Nair )",
    "SXL": "India",
    "Latp": "37",
    "Player_1": "Raya\r 2",
    "Player_11": "Wood\r 12",
    "Player_10": "Cunha\r 2",
    "Player_12": "Ramsdale\r 0",
    "Player_13": "Gvardiol\r LIV (A)",
    "Player_14": "McNeil\r MUN (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "Maddison\r FUL (H)",
    "Player_6": "Saka\r 15",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "Van den Berg\r 2",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "724( 1,114,648 ) TotalXfr : 10",
    "Teams": "Predators( Ruchik Shirode )",
    "SXL": "India",
    "Latp": "14",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Isak\r 1",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "B.Fernandes\r EVE (H)",
    "Player_14": "Colwill\r AVL (H)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "J.Timber\r 1",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Semenyo\r 0",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Milenkovi\u0107\r 6",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Hall\r 2"
  },
  {
    "manager_Name": "724( 1,123,744 ) TotalXfr : 12",
    "Teams": "Ashburton Grove FC( Zafar Khan )",
    "SXL": "India",
    "Latp": "36",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Wissa\r 6",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Ward\r 0",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Gabriel\r 9",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Saka\r 15",
    "Player_9": "Cunha\r 2",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "723( 1,157,661 ) TotalXfr : 13",
    "Teams": "miskharege fc( Jordan D\u0027Almeida )",
    "SXL": "India",
    "Latp": "11",
    "Player_1": "Flekken\r 2",
    "Player_11": "Wood\r 6",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Greaves\r 0",
    "Player_14": "Semenyo\r 0",
    "Player_7": "Dibling\r 1",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "A\u00EFt-Nouri\r 0",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Keane\r MUN (A)",
    "Player_4": "Virgil\r MCI (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "M.Salah\r MCI (H)",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "722( 1,177,203 ) TotalXfr : 11",
    "Teams": "TYSM11( Tasdique Yasin )",
    "SXL": "India",
    "Latp": "29",
    "Player_1": "Flekken\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Sels\r 6",
    "Player_13": "Semenyo\r 0",
    "Player_14": "Vardy\r 5",
    "Player_7": "Smith Rowe\r TOT (A)",
    "Player_2": "Konat\u00E9\r MCI (H)",
    "Player_5": "Aina\r 6",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "Robinson\r TOT (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Saka\r 15",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "722( 1,187,653 ) TotalXfr : 13",
    "Teams": "Jurgen\u0027s Kop( Prathamesh Manjrekar )",
    "SXL": "India",
    "Latp": "23",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Solanke\r FUL (H)",
    "Player_10": "Cunha\r 2",
    "Player_12": "Flekken\r 2",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Keane\r MUN (A)",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Saka\r 15",
    "Player_9": "Delap\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "722( 1,190,575 ) TotalXfr : 14",
    "Teams": "Go Razzmatazz!( Arjun Aggarwal )",
    "SXL": "India",
    "Latp": "28",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Cunha\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Dibling\r 1",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Murillo\r 6",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Van den Berg\r 2",
    "Player_4": "Gabriel\r 9",
    "Player_8": "B.Fernandes\r EVE (H)",
    "Player_9": "Jo\u00E3o Pedro\r 4",
    "Player_15": "Semenyo\r 0"
  },
  {
    "manager_Name": "721( 1,225,717 ) TotalXfr : 17",
    "Teams": "XGALX( Dhearika Ramadhanty )",
    "SXL": "Indonesia",
    "Latp": "23",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 4",
    "Player_10": "Ra\u00FAl\r TOT (A)",
    "Player_12": "Turner\r 0",
    "Player_13": "Welbeck\r 2",
    "Player_14": "Keane\r MUN (A)",
    "Player_7": "Saka\r 15",
    "Player_2": "Young\r MUN (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Gvardiol\r LIV (A)",
    "Player_4": "Tarkowski\r MUN (A)",
    "Player_8": "B.Fernandes\r EVE (H)",
    "Player_9": "Mbeumo\r 2",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "720( 1,244,126 ) TotalXfr : 12",
    "Teams": "SakaWakaXI( Deepti D )",
    "SXL": "India",
    "Latp": "38",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Justin\r -1",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Smith Rowe\r TOT (A)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Hall\r 2",
    "Player_4": "Lewis\r LIV (A)",
    "Player_8": "Saka\r 15",
    "Player_9": "Wood\r 6",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "718( 1,296,172 ) TotalXfr : 9",
    "Teams": "km11( tamil vanan )",
    "SXL": "India",
    "Latp": "25",
    "Player_1": "Pickford\r MUN (A)",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Wissa\r 6",
    "Player_12": "Turner\r 0",
    "Player_13": "Amad\r EVE (H)",
    "Player_14": "Faes\r 0",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Robertson\r MCI (H)",
    "Player_5": "Luis D\u00EDaz\r MCI (H)",
    "Player_6": "Saka\r 15",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "Lewis\r LIV (A)",
    "Player_8": "Mbeumo\r 4",
    "Player_9": "Ra\u00FAl\r TOT (A)",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "716( 1,382,804 ) TotalXfr : 15",
    "Teams": "Mushrooms of Europe( Nicholas Neyt )",
    "SXL": "Belgium",
    "Latp": "31",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Isak\r 1",
    "Player_10": "Ra\u00FAl\r TOT (A)",
    "Player_12": "Henderson\r 2",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Gabriel\r 9",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Saka\r 15",
    "Player_3": "Hall\r 2",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Cunha\r 2",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "716( 1,385,417 ) TotalXfr : 17",
    "Teams": "Shadows FC( Altab Rahi )",
    "SXL": "India",
    "Latp": "53",
    "Player_1": "Sels\r 6",
    "Player_11": "Solanke\r FUL (H)",
    "Player_10": "Cunha\r 2",
    "Player_12": "Kelleher\r MCI (H)",
    "Player_13": "Davis\r 2",
    "Player_14": "Rogers\r CHE (A)",
    "Player_7": "Saka\r 30",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "J.Timber\r 1",
    "Player_4": "Milenkovi\u0107\r 6",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Wood\r 6",
    "Player_15": "Robinson\r TOT (A)"
  },
  {
    "manager_Name": "715( 1,391,898 ) TotalXfr : 7",
    "Teams": "Broad-Sword( Sheldon Benny )",
    "SXL": "India",
    "Latp": "53",
    "Player_1": "Raya\r 2",
    "Player_11": "Wissa\r 6",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Lavia\r AVL (H)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Amad\r EVE (H)",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "\u00D8degaard\r 7",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Digne\r CHE (A)",
    "Player_4": "Aina\r 6",
    "Player_8": "Saka\r 30",
    "Player_9": "Haaland\r LIV (A)",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "714( 1,449,392 ) TotalXfr : 15",
    "Teams": "Bear XI( Adi Patil )",
    "SXL": "India",
    "Latp": "45",
    "Player_1": "Raya\r 2",
    "Player_11": "Wood\r 6",
    "Player_10": "Isak\r 1",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Archer\r 2",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Aina\r 6",
    "Player_5": "Rogers\r CHE (A)",
    "Player_6": "Saka\r 30",
    "Player_3": "Robinson\r TOT (A)",
    "Player_4": "Konsa\r CHE (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "B.Fernandes\r EVE (H)",
    "Player_15": "Konat\u00E9\r MCI (H)"
  },
  {
    "manager_Name": "711( 1,528,659 ) TotalXfr : 8",
    "Teams": "RYSing Red Devils( Rikin Shah )",
    "SXL": "India",
    "Latp": "29",
    "Player_1": "Henderson\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Vardy\r 5",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Saka\r 15",
    "Player_3": "Robinson\r TOT (A)",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Smith Rowe\r TOT (A)",
    "Player_9": "Rogers\r CHE (A)",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "709( 1,627,360 ) TotalXfr : 17",
    "Teams": "Kounde Bhajji( Ronak Kapadia )",
    "SXL": "India",
    "Latp": "28",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Wissa\r 6",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Colwill\r AVL (H)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "J.Timber\r 1",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Saka\r 15",
    "Player_3": "Udogie\r FUL (H)",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Cunha\r 2",
    "Player_15": "Burgess\r 2"
  },
  {
    "manager_Name": "708( 1,637,010 ) TotalXfr : 9",
    "Teams": "Errors 11( aman sharma )",
    "SXL": "India",
    "Latp": "34",
    "Player_1": "Areola\r 0",
    "Player_11": "Watkins\r CHE (A)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Barnes\r 2",
    "Player_14": "Faes\r 0",
    "Player_7": "Saka\r 30",
    "Player_2": "Konat\u00E9\r MCI (H)",
    "Player_5": "Bowen\r 2",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Konsa\r CHE (A)",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Ra\u00FAl\r TOT (A)",
    "Player_15": "Mykolenko\r MUN (A)"
  }
];