var s = [
  {
    "manager_Name": "905( 1 ) TotalXfr : 11",
    "Teams": "3ALLA ALLAH( yassine hilmi )",
    "SXL": "Morocco",
    "Latp": "4",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Wissa\r LEI (H)",
    "Player_12": "Pickford\r MUN (A)",
    "Player_13": "Wood\r IPS (H)",
    "Player_14": "Johnson\r NFO (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Virgil\r MCI (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "Estupi\u00F1an\r 4",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "Kulusevski\r FUL (H)",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "895( 2 ) TotalXfr : 11",
    "Teams": "BB GW1( Ayoub NACIR \uD83C\uDDF2\uD83C\uDDE6 )",
    "SXL": "Morocco",
    "Latp": "0",
    "Player_1": "Henderson\r NEW (H)",
    "Player_11": "Wood\r IPS (H)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Van de Ven\r FUL (H)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Aina\r IPS (H)",
    "Player_5": "B.Fernandes\r EVE (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Gabriel\r WHU (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Isak\r CRY (A)",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "893( 3 ) TotalXfr : 11",
    "Teams": "Pipat FC( Pipat Boss )",
    "SXL": "Thailand",
    "Latp": "6",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Wood\r IPS (H)",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Cunha\r BOU (H)",
    "Player_14": "A\u00EFt-Nouri\r BOU (H)",
    "Player_7": "Mbeumo\r LEI (H)",
    "Player_2": "Estupi\u00F1an\r 4",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "B.Fernandes\r EVE (H)",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "886( 4 ) TotalXfr : 10",
    "Teams": "7OoOda( Mahmoud Ibrahim )",
    "SXL": "Egypt",
    "Latp": "1",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Turner\r NEW (H)",
    "Player_13": "Keane\r MUN (A)",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Robinson\r TOT (A)",
    "Player_4": "Dunk\r 1",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "B.Fernandes\r EVE (H)",
    "Player_15": "Vardy\r BRE (A)"
  },
  {
    "manager_Name": "886( 4 ) TotalXfr : 10",
    "Teams": "The Seniors( Radhi Alqaisi )",
    "SXL": "Egypt",
    "Latp": "2",
    "Player_1": "Sels\r IPS (H)",
    "Player_11": "Isak\r CRY (A)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Flekken\r LEI (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Faes\r BRE (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "Konat\u00E9\r MCI (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "885( 6 ) TotalXfr : 9",
    "Teams": "Blueberries( Alex Hirkjolen )",
    "SXL": "Norway",
    "Latp": "0",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Isak\r CRY (A)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Gvardiol\r LIV (A)",
    "Player_14": "Rogers\r CHE (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "Saka\r WHU (A)",
    "Player_3": "Hall\r CRY (A)",
    "Player_4": "Gabriel\r WHU (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Wood\r IPS (H)",
    "Player_15": "Faes\r BRE (A)"
  },
  {
    "manager_Name": "884( 7 ) TotalXfr : 11",
    "Teams": "LIV( Dani Lio messi \uD83C\uDDEA\uD83C\uDDF9 )",
    "SXL": "Ethiopia",
    "Latp": "2",
    "Player_1": "Kelleher\r MCI (H)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Areola\r ARS (H)",
    "Player_13": "Ra\u00FAl\r TOT (A)",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gabriel\r WHU (A)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "Bowen\r ARS (H)",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "Veltman\r 0",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "Palmer\r AVL (H)",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "884( 8 ) TotalXfr : 12",
    "Teams": "Stella Rosa( Kristijan Anicic )",
    "SXL": "Bosnia-Herzegovina",
    "Latp": "10",
    "Player_1": "Pickford\r MUN (A)",
    "Player_11": "Solanke\r FUL (H)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Turner\r NEW (H)",
    "Player_13": "Konat\u00E9\r MCI (H)",
    "Player_14": "Faes\r BRE (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "J.Timber\r WHU (A)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "Saka\r WHU (A)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Burn\r CRY (A)",
    "Player_8": "Mitoma\r 10",
    "Player_9": "Palmer\r AVL (H)",
    "Player_15": "Fraser\r BOU (H)"
  },
  {
    "manager_Name": "883( 9 ) TotalXfr : 10",
    "Teams": "Bukayo\u0027s Sadza( Brendan Sylvester )",
    "SXL": "Netherlands",
    "Latp": "4",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Jo\u00E3o Pedro\r 4",
    "Player_12": "Valdimarsson\r LEI (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Saka\r WHU (A)",
    "Player_2": "Gvardiol\r LIV (A)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Gabriel\r WHU (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Wood\r IPS (H)",
    "Player_15": "Greaves\r NFO (A)"
  },
  {
    "manager_Name": "878( 10 ) TotalXfr : 13",
    "Teams": "Kobs on the Job( Harry Jones )",
    "SXL": "Australia",
    "Latp": "0",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Wood\r IPS (H)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Hermansen\r BRE (A)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Dalot\r EVE (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Saliba\r WHU (A)",
    "Player_4": "Aina\r IPS (H)",
    "Player_8": "Garnacho\r EVE (H)",
    "Player_9": "Wissa\r LEI (H)",
    "Player_15": "Young\r MUN (A)"
  },
  {
    "manager_Name": "877( 11 ) TotalXfr : 11",
    "Teams": "Holy Boehly( Niels Pretorius )",
    "SXL": "Norway",
    "Latp": "2",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Mykolenko\r MUN (A)",
    "Player_7": "Saka\r WHU (A)",
    "Player_2": "Aina\r IPS (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Robinson\r TOT (A)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Isak\r CRY (A)",
    "Player_15": "Van den Berg\r LEI (H)"
  },
  {
    "manager_Name": "877( 12 ) TotalXfr : 13",
    "Teams": "Flying Dutchman \uFFFD\uFFFD\u2620( Karim Radi )",
    "SXL": "Egypt",
    "Latp": "2",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Wissa\r LEI (H)",
    "Player_12": "Turner\r NEW (H)",
    "Player_13": "M.Salah\r MCI (H)",
    "Player_14": "Burn\r CRY (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Aina\r IPS (H)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Wood\r IPS (H)",
    "Player_15": "Digne\r CHE (A)"
  },
  {
    "manager_Name": "876( 13 ) TotalXfr : 14",
    "Teams": "Joelinton Enjoyer( James White )",
    "SXL": "New Zealand",
    "Latp": "4",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Dennis\r WOL (A)",
    "Player_13": "Wissa\r LEI (H)",
    "Player_14": "Mykolenko\r MUN (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Collins\r LEI (H)",
    "Player_4": "Hall\r CRY (A)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "Mbeumo\r LEI (H)",
    "Player_15": "Greaves\r NFO (A)"
  },
  {
    "manager_Name": "874( 14 ) TotalXfr : 10",
    "Teams": "J\u00FCrgen Klopp( Abdullah AlGhfeli )",
    "SXL": "United Arab Emirates",
    "Latp": "10",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Wood\r IPS (H)",
    "Player_12": "Valdimarsson\r LEI (H)",
    "Player_13": "Ra\u00FAl\r TOT (A)",
    "Player_14": "Gvardiol\r LIV (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gabriel\r WHU (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Alexander-Arnold\r MCI (H)",
    "Player_8": "B.Fernandes\r EVE (H)",
    "Player_9": "Mitoma\r 10",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "872( 15 ) TotalXfr : 11",
    "Teams": "KobbieManU( JAMIE WALKER )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Fabianski\r ARS (H)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Martinez\r CHE (A)",
    "Player_13": "Gvardiol\r LIV (A)",
    "Player_14": "Rogers\r CHE (A)",
    "Player_7": "Johnson\r FUL (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Greaves\r NFO (A)"
  },
  {
    "manager_Name": "872( 16 ) TotalXfr : 12",
    "Teams": "SC Villa Jogoo( Godfrey Lusiba )",
    "SXL": "Uganda",
    "Latp": "2",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Pickford\r MUN (A)",
    "Player_13": "Evanilson\r WOL (A)",
    "Player_14": "Davis\r NFO (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Pedro Porro\r FUL (H)",
    "Player_5": "A\u00EFt-Nouri\r BOU (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "Dalot\r EVE (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Saka\r WHU (A)",
    "Player_15": "Smith Rowe\r TOT (A)"
  },
  {
    "manager_Name": "871( 17 ) TotalXfr : 9",
    "Teams": "NYC Whites( Andrew Warriner )",
    "SXL": "England",
    "Latp": "0",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Wood\r IPS (H)",
    "Player_10": "Solanke\r FUL (H)",
    "Player_12": "Verbruggen\r 2",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Greaves\r NFO (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "Johnson\r FUL (H)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "Gvardiol\r LIV (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Faes\r BRE (A)"
  },
  {
    "manager_Name": "871( 18 ) TotalXfr : 10",
    "Teams": "Trust the Process ;)( Robb Lacey )",
    "SXL": "England",
    "Latp": "4",
    "Player_1": "Verbruggen\r 4",
    "Player_11": "Evanilson\r WOL (A)",
    "Player_10": "Watkins\r CHE (A)",
    "Player_12": "Pickford\r MUN (A)",
    "Player_13": "Bowen\r ARS (H)",
    "Player_14": "Gvardiol\r LIV (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Van den Berg\r LEI (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "Saka\r WHU (A)",
    "Player_3": "Pinnock\r LEI (H)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Solanke\r FUL (H)",
    "Player_15": "Mykolenko\r MUN (A)"
  },
  {
    "manager_Name": "871( 19 ) TotalXfr : 11",
    "Teams": "ArkanHM( Kurdistan Is1 )",
    "SXL": "Iraq",
    "Latp": "2",
    "Player_1": "Henderson\r NEW (H)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Valdimarsson\r LEI (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Ajer\r LEI (H)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Mykolenko\r MUN (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Robinson\r TOT (A)",
    "Player_4": "Pau\r CHE (A)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Solanke\r FUL (H)",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "871( 19 ) TotalXfr : 11",
    "Teams": "\uFFFD\uFFFD\u2642\uFE0F( Abdallah Mahdy )",
    "SXL": "Egypt",
    "Latp": "2",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Nedeljkovic\r CHE (A)",
    "Player_14": "Johnson\r NFO (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Georginio\r 2",
    "Player_6": "Maddison\r FUL (H)",
    "Player_3": "Lewis\r LIV (A)",
    "Player_4": "J.Timber\r WHU (A)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "M.Salah\r MCI (H)",
    "Player_15": "Ui-jo\r IPS (H)"
  },
  {
    "manager_Name": "871( 19 ) TotalXfr : 11",
    "Teams": "H\u0026M( hossam Mohamed )",
    "SXL": "Egypt",
    "Latp": "14",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Wissa\r LEI (H)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Onana\r EVE (H)",
    "Player_13": "Mitoma\r 10",
    "Player_14": "Estupi\u00F1an\r 4",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Dalot\r EVE (H)",
    "Player_5": "N.Semedo\r BOU (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "B.Fernandes\r EVE (H)",
    "Player_9": "Ra\u00FAl\r TOT (A)",
    "Player_15": "Palmer\r AVL (H)"
  },
  {
    "manager_Name": "871( 22 ) TotalXfr : 12",
    "Teams": "TAAnnihilation( Tom Warlow )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "McNeil\r MUN (A)",
    "Player_14": "Konsa\r CHE (A)",
    "Player_7": "Saka\r WHU (A)",
    "Player_2": "Van den Berg\r LEI (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Gvardiol\r LIV (A)",
    "Player_4": "Gabriel\r WHU (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "870( 23 ) TotalXfr : 10",
    "Teams": "Clayton Gondo FC( Clayton Gondo )",
    "SXL": "Zimbabwe",
    "Latp": "2",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Ramsdale\r 0",
    "Player_13": "Johnson\r FUL (H)",
    "Player_14": "Justin\r BRE (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gvardiol\r LIV (A)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Kulusevski\r FUL (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Dunk\r 1"
  },
  {
    "manager_Name": "869( 24 ) TotalXfr : 10",
    "Teams": "ugly squad( abdullah alanazi )",
    "SXL": "Saudi Arabia",
    "Latp": "2",
    "Player_1": "Fabianski\r ARS (H)",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Wood\r IPS (H)",
    "Player_12": "Pickford\r MUN (A)",
    "Player_13": "Gordon\r CRY (A)",
    "Player_14": "Alexander-Arnold\r MCI (H)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Milenkovi\u0107\r IPS (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Collins\r LEI (H)",
    "Player_4": "Gabriel\r WHU (A)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Greaves\r NFO (A)"
  },
  {
    "manager_Name": "869( 25 ) TotalXfr : 11",
    "Teams": "Holy Boehly( james delaney )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Martinez\r CHE (A)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Turner\r NEW (H)",
    "Player_13": "Robinson\r TOT (A)",
    "Player_14": "Johnson\r NFO (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Gvardiol\r LIV (A)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Son\r FUL (H)",
    "Player_9": "Saka\r WHU (A)",
    "Player_15": "Jebbison\r WOL (A)"
  },
  {
    "manager_Name": "869( 25 ) TotalXfr : 11",
    "Teams": "geezers fc( Oliver Stanley )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Watkins\r CHE (A)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "McNeil\r MUN (A)",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Gabriel\r WHU (A)",
    "Player_5": "Maddison\r FUL (H)",
    "Player_6": "Saka\r WHU (A)",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Burn\r CRY (A)"
  },
  {
    "manager_Name": "869( 27 ) TotalXfr : 12",
    "Teams": "AW( Adrian Wagstyl )",
    "SXL": "Poland",
    "Latp": "0",
    "Player_1": "Sels\r IPS (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Isak\r CRY (A)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Justin\r BRE (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Aina\r IPS (H)",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "Wood\r IPS (H)",
    "Player_15": "Robinson\r TOT (A)"
  },
  {
    "manager_Name": "868( 28 ) TotalXfr : 11",
    "Teams": "Ziad Squad( ziad talha )",
    "SXL": "Saudi Arabia",
    "Latp": "10",
    "Player_1": "Sels\r IPS (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Armstrong\r 5",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "B.Fernandes\r EVE (H)",
    "Player_6": "Mitoma\r 10",
    "Player_3": "Udogie\r FUL (H)",
    "Player_4": "Hall\r CRY (A)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "M.Salah\r MCI (H)",
    "Player_15": "O\u0027Shea\r NFO (A)"
  },
  {
    "manager_Name": "868( 29 ) TotalXfr : 12",
    "Teams": "kurdistan \uFFFD( muhamad burhan )",
    "SXL": "Iraq",
    "Latp": "2",
    "Player_1": "Ramsdale\r 0",
    "Player_11": "Solanke\r FUL (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Pickford\r MUN (A)",
    "Player_13": "Watkins\r CHE (A)",
    "Player_14": "Rogers\r CHE (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Collins\r LEI (H)",
    "Player_5": "Dalot\r EVE (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "A\u00EFt-Nouri\r BOU (H)",
    "Player_4": "Pedro Porro\r FUL (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "M.Salah\r MCI (H)",
    "Player_15": "Faes\r BRE (A)"
  },
  {
    "manager_Name": "868( 30 ) TotalXfr : 13",
    "Teams": "Manchester still \uFFFD( nejm boukhres )",
    "SXL": "Tunisia",
    "Latp": "0",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Watkins\r CHE (A)",
    "Player_10": "Wood\r IPS (H)",
    "Player_12": "Ward\r BRE (A)",
    "Player_13": "Robinson\r TOT (A)",
    "Player_14": "Dibling\r 1",
    "Player_7": "Mbeumo\r LEI (H)",
    "Player_2": "Van den Berg\r LEI (H)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "Konat\u00E9\r MCI (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "867( 31 ) TotalXfr : 11",
    "Teams": "The Difference( Eric Scott )",
    "SXL": "Scotland",
    "Latp": "2",
    "Player_1": "Onana\r EVE (H)",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Wood\r IPS (H)",
    "Player_12": "Raya\r WHU (A)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Digne\r CHE (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Konat\u00E9\r MCI (H)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Veltman\r 0",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Robinson\r TOT (A)"
  },
  {
    "manager_Name": "867( 32 ) TotalXfr : 12",
    "Teams": "The Notorious D.U.G( Doug Yellowley )",
    "SXL": "Scotland",
    "Latp": "2",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Wood\r IPS (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Konsa\r CHE (A)",
    "Player_14": "Greaves\r NFO (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Gabriel\r WHU (A)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "Lewis\r LIV (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Rogers\r CHE (A)"
  },
  {
    "manager_Name": "867( 33 ) TotalXfr : 13",
    "Teams": "I AM PANDA( Fahad Al kharafi\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC\uD83C\uDDF0\uD83C\uDDFC )",
    "SXL": "Kuwait",
    "Latp": "2",
    "Player_1": "Henderson\r NEW (H)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Isak\r CRY (A)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Keane\r MUN (A)",
    "Player_14": "McNeil\r MUN (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Aina\r IPS (H)",
    "Player_5": "B.Fernandes\r EVE (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Digne\r CHE (A)",
    "Player_4": "Dalot\r EVE (H)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Faes\r BRE (A)"
  },
  {
    "manager_Name": "867( 33 ) TotalXfr : 13",
    "Teams": "Kaluno City( Innocent Kalukuta )",
    "SXL": "Malawi",
    "Latp": "2",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "S\u00E1nchez\r AVL (H)",
    "Player_13": "Wood\r IPS (H)",
    "Player_14": "Faes\r BRE (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Veltman\r 0",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "Digne\r CHE (A)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "B.Fernandes\r EVE (H)",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "866( 35 ) TotalXfr : 10",
    "Teams": "Elkabiri mohamed( Mohamed elkabiri )",
    "SXL": "Morocco",
    "Latp": "2",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Turner\r NEW (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Konat\u00E9\r MCI (H)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Mykolenko\r MUN (A)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Robinson\r TOT (A)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Wissa\r LEI (H)",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "866( 36 ) TotalXfr : 12",
    "Teams": "\u0645\u0635\u0637\u0641\u0649 \u0641\u0624\u0627\u062F( Mustafa YNWA )",
    "SXL": "Iraq",
    "Latp": "2",
    "Player_1": "Jos\u00E9 S\u00E1\r BOU (H)",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Ward\r BRE (A)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Johnson\r NFO (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Cucurella\r AVL (H)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Aina\r IPS (H)",
    "Player_4": "Veltman\r 0",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Watkins\r CHE (A)",
    "Player_15": "Konsa\r CHE (A)"
  },
  {
    "manager_Name": "865( 37 ) TotalXfr : 9",
    "Teams": "Alex( Alex Lindholm )",
    "SXL": "Japan",
    "Latp": "4",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "B.Fernandes\r EVE (H)",
    "Player_14": "Robinson\r TOT (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "F.Kad\u0131o\u011Flu\r 0",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "Konat\u00E9\r MCI (H)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Digne\r CHE (A)"
  },
  {
    "manager_Name": "865( 38 ) TotalXfr : 10",
    "Teams": "Bu Hussain (BH)( Bu Hussain )",
    "SXL": "Bahrain",
    "Latp": "0",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Wissa\r LEI (H)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Sels\r IPS (H)",
    "Player_13": "Buonanotte\r BRE (A)",
    "Player_14": "Collins\r LEI (H)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Aina\r IPS (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Gvardiol\r LIV (A)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Keane\r MUN (A)"
  },
  {
    "manager_Name": "865( 38 ) TotalXfr : 10",
    "Teams": "Charlie\u2019s team( Charlie Shepherd )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Isak\r CRY (A)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Dennis\r WOL (A)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Konsa\r CHE (A)",
    "Player_7": "Mbeumo\r LEI (H)",
    "Player_2": "Gabriel\r WHU (A)",
    "Player_5": "Saka\r WHU (A)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Robinson\r TOT (A)",
    "Player_4": "Konat\u00E9\r MCI (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Greaves\r NFO (A)"
  },
  {
    "manager_Name": "865( 40 ) TotalXfr : 11",
    "Teams": "Makis( klimis xanthopoulos )",
    "SXL": "Greece",
    "Latp": "0",
    "Player_1": "Raya\r WHU (A)",
    "Player_11": "Wissa\r LEI (H)",
    "Player_10": "Cunha\r BOU (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Adama\r TOT (A)",
    "Player_14": "Faes\r BRE (A)",
    "Player_7": "B.Fernandes\r EVE (H)",
    "Player_2": "Gvardiol\r LIV (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "N.Jackson\r AVL (H)",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "865( 40 ) TotalXfr : 11",
    "Teams": "SlotMeOut( David Ionescu )",
    "SXL": "Romania",
    "Latp": "4",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Mbeumo\r LEI (H)",
    "Player_14": "Digne\r CHE (A)",
    "Player_7": "Saka\r WHU (A)",
    "Player_2": "Hall\r CRY (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "B.Fernandes\r EVE (H)",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Isak\r CRY (A)",
    "Player_15": "Van den Berg\r LEI (H)"
  },
  {
    "manager_Name": "864( 42 ) TotalXfr : 9",
    "Teams": "Snoop Udogie Dogg( Sion Nierada )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Sels\r IPS (H)",
    "Player_11": "Wood\r IPS (H)",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Van den Berg\r LEI (H)",
    "Player_14": "Mykolenko\r MUN (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Milenkovi\u0107\r IPS (H)",
    "Player_5": "Son\r FUL (H)",
    "Player_6": "Saka\r WHU (A)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "Gvardiol\r LIV (A)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Winks\r BRE (A)"
  },
  {
    "manager_Name": "864( 43 ) TotalXfr : 10",
    "Teams": "HA HA NO SALAH( Joshua Jones )",
    "SXL": "England",
    "Latp": "10",
    "Player_1": "Henderson\r NEW (H)",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Strand Larsen\r BOU (H)",
    "Player_12": "Muric\r NFO (A)",
    "Player_13": "Davis\r NFO (A)",
    "Player_14": "Delap\r NFO (A)",
    "Player_7": "Mbeumo\r LEI (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Johnson\r FUL (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Gabriel\r WHU (A)",
    "Player_4": "Pinnock\r LEI (H)",
    "Player_8": "B.Fernandes\r EVE (H)",
    "Player_9": "Mitoma\r 10",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "864( 44 ) TotalXfr : 11",
    "Teams": "MANO XXd( \u0639\u0628\u062F\u0627\u0644\u0631\u062D\u0645\u0646 \u0634\u0639\u064A\u0634\u0639 )",
    "SXL": "Egypt",
    "Latp": "2",
    "Player_1": "Sels\r IPS (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Turner\r NEW (H)",
    "Player_13": "Lewis\r LIV (A)",
    "Player_14": "Gvardiol\r LIV (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Mbeumo\r LEI (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Mazraoui\r EVE (H)",
    "Player_4": "Konat\u00E9\r MCI (H)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Rogers\r CHE (A)"
  },
  {
    "manager_Name": "864( 45 ) TotalXfr : 12",
    "Teams": "genka( genka kauman )",
    "SXL": "Indonesia",
    "Latp": "2",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Son\r FUL (H)",
    "Player_12": "Leno\r TOT (A)",
    "Player_13": "Wood\r IPS (H)",
    "Player_14": "Smith Rowe\r TOT (A)",
    "Player_7": "Saka\r WHU (A)",
    "Player_2": "Gabriel\r WHU (A)",
    "Player_5": "Dalot\r EVE (H)",
    "Player_6": "Van Hecke\r 2",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Mbeumo\r LEI (H)",
    "Player_15": "Antonio\r ARS (H)"
  },
  {
    "manager_Name": "864( 46 ) TotalXfr : 13",
    "Teams": "AFC Doubtfire( Connor Andrew )",
    "SXL": "England",
    "Latp": "2",
    "Player_1": "Ederson M.\r LIV (A)",
    "Player_11": "Cunha\r BOU (H)",
    "Player_10": "Isak\r CRY (A)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Gabriel\r WHU (A)",
    "Player_7": "Mbeumo\r LEI (H)",
    "Player_2": "Aina\r IPS (H)",
    "Player_5": "B.Fernandes\r EVE (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Pedro Porro\r FUL (H)",
    "Player_4": "A\u00EFt-Nouri\r BOU (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Greaves\r NFO (A)"
  },
  {
    "manager_Name": "863( 47 ) TotalXfr : 11",
    "Teams": "\u0627\u0644\u0647\u0627\u064A\u0628\u0631\u064A( Always qidiys )",
    "SXL": "Iraq",
    "Latp": "0",
    "Player_1": "Flekken\r LEI (H)",
    "Player_11": "Wissa\r LEI (H)",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Pickford\r MUN (A)",
    "Player_13": "Johnson\r FUL (H)",
    "Player_14": "Virgil\r MCI (H)",
    "Player_7": "Saka\r WHU (A)",
    "Player_2": "A\u00EFt-Nouri\r BOU (H)",
    "Player_5": "Garnacho\r EVE (H)",
    "Player_6": "M.Salah\r MCI (H)",
    "Player_3": "Dalot\r EVE (H)",
    "Player_4": "Udogie\r FUL (H)",
    "Player_8": "Mbeumo\r LEI (H)",
    "Player_9": "Cunha\r BOU (H)",
    "Player_15": "Konat\u00E9\r MCI (H)"
  },
  {
    "manager_Name": "863( 47 ) TotalXfr : 11",
    "Teams": "Alwan kurd \uFFFD( Alwan kurd \uD83E\uDEF0\uD83C\uDFFB )",
    "SXL": "Syria",
    "Latp": "2",
    "Player_1": "Pickford\r MUN (A)",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Isak\r CRY (A)",
    "Player_12": "Ward\r BRE (A)",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Digne\r CHE (A)",
    "Player_7": "Saka\r WHU (A)",
    "Player_2": "Young\r MUN (A)",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Virgil\r MCI (H)",
    "Player_4": "Alex Moreno\r IPS (H)",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Solanke\r FUL (H)",
    "Player_15": "Tuanzebe\r NFO (A)"
  },
  {
    "manager_Name": "863( 47 ) TotalXfr : 11",
    "Teams": "\u0627\u0644\u062E\u0648\u0641 \u0645\u0634 \u0645\u0646 \u0627\u0644\u0644\u064A \u062C\u0627\u064A( Sayed Said )",
    "SXL": "Egypt",
    "Latp": "6",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Isak\r CRY (A)",
    "Player_10": "Wissa\r LEI (H)",
    "Player_12": "Fabianski\r ARS (H)",
    "Player_13": "Pau\r CHE (A)",
    "Player_14": "Greaves\r NFO (A)",
    "Player_7": "M.Salah\r MCI (H)",
    "Player_2": "Estupi\u00F1an\r 4",
    "Player_5": "Smith Rowe\r TOT (A)",
    "Player_6": "Mbeumo\r LEI (H)",
    "Player_3": "Aina\r IPS (H)",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Saka\r WHU (A)",
    "Player_9": "Haaland\r LIV (A)",
    "Player_15": "Winks\r BRE (A)"
  },
  {
    "manager_Name": "863( 50 ) TotalXfr : 15",
    "Teams": "\u0643\u0631\u0648\u0628 \u0627\u0644\u0641\u064A\u0633\u0628\u0648\u0643( Fantasy Premier League Iraq 43K )",
    "SXL": "Iraq",
    "Latp": "8",
    "Player_1": "Neto\r WHU (A)",
    "Player_11": "Jo\u00E3o Pedro\r 4",
    "Player_10": "N.Jackson\r AVL (H)",
    "Player_12": "Martinez\r CHE (A)",
    "Player_13": "Smith Rowe\r TOT (A)",
    "Player_14": "Kilman\r ARS (H)",
    "Player_7": "Saka\r WHU (A)",
    "Player_2": "Estupi\u00F1an\r 4",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Maddison\r FUL (H)",
    "Player_3": "Lewis\r LIV (A)",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "Amad\r EVE (H)",
    "Player_9": "Wissa\r LEI (H)",
    "Player_15": "Keane\r MUN (A)"
  }
];