var s = [
  {
    "manager_Name": "797( 88,618 ) TotalXfr : 11",
    "Teams": "Blue Brigade( Bhuman Basnet )",
    "SXL": "India",
    "Latp": "70",
    "Player_1": "Flekken\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r 2",
    "Player_14": "Greaves\r 0",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "M.Salah\r 11",
    "Player_6": "Johnson\r 7",
    "Player_3": "Aina\r 8",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Palmer\r 11",
    "Player_9": "Wissa\r 16",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "791( 117,293 ) TotalXfr : 10",
    "Teams": "BLIND at the BACK( Prayash Thapa )",
    "SXL": "India",
    "Latp": "58",
    "Player_1": "Flekken\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Strand Larsen\r 11",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Smith Rowe\r 2",
    "Player_14": "Robinson\r 2",
    "Player_7": "Palmer\r 11",
    "Player_2": "Faes\r 0",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "M.Salah\r 22",
    "Player_3": "Milenkovi\u0107\r 6",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Rogers\r 2",
    "Player_9": "Solanke\r 0",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "783( 173,013 ) TotalXfr : 13",
    "Teams": "FALSE 9( Rohan Rai )",
    "SXL": "India",
    "Latp": "74",
    "Player_1": "Henderson\r 2",
    "Player_11": "Welbeck\r 2",
    "Player_10": "N.Jackson\r 6",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r 2",
    "Player_14": "Digne\r 1",
    "Player_7": "Saka\r 36",
    "Player_2": "Gvardiol\r 0",
    "Player_5": "Smith Rowe\r 2",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Robinson\r 2",
    "Player_4": "Gabriel\r 9",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Cunha\r 2",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "751( 569,285 ) TotalXfr : 11",
    "Teams": "Mersali( Bishal Rai )",
    "SXL": "India",
    "Latp": "91",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Wissa\r 8",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Konat\u00E9\r 0",
    "Player_14": "Chiwome\r 0",
    "Player_7": "M.Salah\r 11",
    "Player_2": "Gvardiol\r 0",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Smith Rowe\r 2",
    "Player_3": "Aina\r 8",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Palmer\r 11",
    "Player_9": "Saka\r 36",
    "Player_15": "Taylor\r 0"
  },
  {
    "manager_Name": "741( 775,371 ) TotalXfr : 11",
    "Teams": "Last Season\u0027s Loser( \u00CFaraplang Pompyrthat )",
    "SXL": "India",
    "Latp": "62",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Konat\u00E9\r 0",
    "Player_14": "Rogers\r 2",
    "Player_7": "B.Fernandes\r 9",
    "Player_2": "Hall\r 2",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Palmer\r 11",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Veltman\r 0",
    "Player_8": "M.Salah\r 22",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Burgess\r 2"
  },
  {
    "manager_Name": "740( 798,609 ) TotalXfr : 11",
    "Teams": "Error404( Duri Tadu )",
    "SXL": "India",
    "Latp": "68",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 1",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Smith Rowe\r 2",
    "Player_14": "Lewis\r 1",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Palmer\r 22",
    "Player_6": "M.Salah\r 11",
    "Player_3": "Robinson\r 2",
    "Player_4": "Virgil\r 6",
    "Player_8": "B.Fernandes\r 9",
    "Player_9": "Cunha\r 2",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "739( 837,101 ) TotalXfr : 17",
    "Teams": "KungFuPandoos( Indrajeet Singh )",
    "SXL": "India",
    "Latp": "94",
    "Player_1": "S\u00E1nchez\r 7",
    "Player_11": "Evanilson\r 12",
    "Player_10": "N.Jackson\r 6",
    "Player_12": "Turner\r 0",
    "Player_13": "Wan-Bissaka\r 6",
    "Player_14": "Gvardiol\r 0",
    "Player_7": "Saka\r 18",
    "Player_2": "Romero\r 0",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "M.Salah\r 22",
    "Player_3": "Dalot\r 6",
    "Player_4": "Martinez\r 5",
    "Player_8": "Palmer\r 11",
    "Player_9": "Vardy\r 5",
    "Player_15": "Winks\r 0"
  },
  {
    "manager_Name": "738( 855,157 ) TotalXfr : 13",
    "Teams": "Avijit@afc( AVIJIT DAS )",
    "SXL": "India",
    "Latp": "59",
    "Player_1": "Flekken\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Wood\r 9",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r 2",
    "Player_14": "Keane\r 0",
    "Player_7": "M.Salah\r 22",
    "Player_2": "J.Timber\r 1",
    "Player_5": "Palmer\r 11",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Gvardiol\r 0",
    "Player_8": "B.Fernandes\r 9",
    "Player_9": "Isak\r 1",
    "Player_15": "Thomas\r 0"
  },
  {
    "manager_Name": "734( 946,299 ) TotalXfr : 11",
    "Teams": "Mawat( Arwat Lyngdoh )",
    "SXL": "India",
    "Latp": "78",
    "Player_1": "Onana\r 6",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Isak\r 1",
    "Player_12": "Sels\r 6",
    "Player_13": "Rogers\r 2",
    "Player_14": "Hall\r 2",
    "Player_7": "B.Fernandes\r 9",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Smith Rowe\r 2",
    "Player_6": "Palmer\r 11",
    "Player_3": "Murillo\r 7",
    "Player_4": "Gabriel\r 9",
    "Player_8": "M.Salah\r 22",
    "Player_9": "Wissa\r 8",
    "Player_15": "Gvardiol\r 0"
  },
  {
    "manager_Name": "731( 1,035,805 ) TotalXfr : 13",
    "Teams": "Fu\u00DFball-Mannschaft( Gaurav Shrestha )",
    "SXL": "India",
    "Latp": "73",
    "Player_1": "Flekken\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Mykolenko\r -1",
    "Player_14": "Greaves\r 0",
    "Player_7": "M.Salah\r 11",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Palmer\r 22",
    "Player_3": "Pinnock\r 2",
    "Player_4": "Hall\r 2",
    "Player_8": "Saka\r 18",
    "Player_9": "Isak\r 1",
    "Player_15": "Semenyo\r 0"
  },
  {
    "manager_Name": "728( 1,105,247 ) TotalXfr : 9",
    "Teams": "heregoesnothing11!!( Ashish Rai )",
    "SXL": "India",
    "Latp": "58",
    "Player_1": "Pickford\r 0",
    "Player_11": "Wissa\r 8",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r 2",
    "Player_14": "Lewis\r 1",
    "Player_7": "M.Salah\r 11",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Van den Berg\r 2",
    "Player_6": "Georginio\r 2",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Kulusevski\r 1",
    "Player_9": "Palmer\r 22",
    "Player_15": "Wheatley\r 0"
  },
  {
    "manager_Name": "727( 1,144,521 ) TotalXfr : 12",
    "Teams": "Bottled FC( Rishi Thulung )",
    "SXL": "India",
    "Latp": "62",
    "Player_1": "Henderson\r 2",
    "Player_11": "Haaland\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r 2",
    "Player_14": "Keane\r 0",
    "Player_7": "M.Salah\r 22",
    "Player_2": "Van den Berg\r 2",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Saka\r 18",
    "Player_3": "Konat\u00E9\r 0",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Madueke\r 3",
    "Player_9": "Wood\r 9",
    "Player_15": "Hall\r 2"
  },
  {
    "manager_Name": "727( 1,152,099 ) TotalXfr : 14",
    "Teams": "Blue Moon X1\uFFFD( PRAYAS BAJGAI )",
    "SXL": "India",
    "Latp": "70",
    "Player_1": "Raya\r 2",
    "Player_11": "N.Jackson\r 12",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r 2",
    "Player_14": "Lewis\r 1",
    "Player_7": "M.Salah\r 11",
    "Player_2": "Mykolenko\r -1",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Palmer\r 11",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Van den Berg\r 2",
    "Player_8": "Saka\r 18",
    "Player_9": "Cunha\r 2",
    "Player_15": "Johnson\r 0"
  },
  {
    "manager_Name": "713( 1,595,265 ) TotalXfr : 12",
    "Teams": "nativ fc( Monlom Rongong )",
    "SXL": "India",
    "Latp": "60",
    "Player_1": "Henderson\r 2",
    "Player_11": "Cunha\r 4",
    "Player_10": "Wood\r 9",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Nedeljkovic\r 0",
    "Player_14": "Winks\r 0",
    "Player_7": "B.Fernandes\r 9",
    "Player_2": "Gvardiol\r 0",
    "Player_5": "Palmer\r 11",
    "Player_6": "M.Salah\r 11",
    "Player_3": "Harwood-Bellis\r 1",
    "Player_4": "Gabriel\r 9",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Delap\r 2",
    "Player_15": "Konat\u00E9\r 0"
  },
  {
    "manager_Name": "712( 1,620,372 ) TotalXfr : 10",
    "Teams": "GustavousGooner( Ashish Subba )",
    "SXL": "India",
    "Latp": "57",
    "Player_1": "S\u00E1nchez\r 7",
    "Player_11": "Haaland\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 4",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Robinson\r 2",
    "Player_14": "Keane\r 0",
    "Player_7": "Saka\r 18",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Smith Rowe\r 2",
    "Player_6": "Maddison\r 2",
    "Player_3": "Aina\r 8",
    "Player_4": "Justin\r -1",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Mbeumo\r 2",
    "Player_15": "Wheatley\r 0"
  },
  {
    "manager_Name": "712( 1,647,428 ) TotalXfr : 25",
    "Teams": "GUNNERS( Omkar Subba )",
    "SXL": "India",
    "Latp": "80",
    "Player_1": "Onana\r 6",
    "Player_11": "Cunha\r 2",
    "Player_10": "Ra\u00FAl\r 2",
    "Player_12": "Kelleher\r 6",
    "Player_13": "Caicedo\r 3",
    "Player_14": "Keane\r 0",
    "Player_7": "M.Salah\r 11",
    "Player_2": "Virgil\r 6",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Saka\r 36",
    "Player_3": "Gvardiol\r 0",
    "Player_4": "Robinson\r 2",
    "Player_8": "Palmer\r 11",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Justin\r -1"
  },
  {
    "manager_Name": "703( 1,967,065 ) TotalXfr : 12",
    "Teams": "FC ASSASSINS( Kushal Sahota )",
    "SXL": "India",
    "Latp": "64",
    "Player_1": "S\u00E1nchez\r 7",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wissa\r 8",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Adama\r 0",
    "Player_14": "Lewis\r 1",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Hall\r 2",
    "Player_5": "Rogers\r 2",
    "Player_6": "Palmer\r 11",
    "Player_3": "Virgil\r 6",
    "Player_4": "Faes\r 0",
    "Player_8": "M.Salah\r 22",
    "Player_9": "Cunha\r 2",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "701( 2,030,170 ) TotalXfr : 7",
    "Teams": "Jatin( Jatin Ghimiray )",
    "SXL": "India",
    "Latp": "62",
    "Player_1": "Raya\r 2",
    "Player_11": "H\u00F8jlund\r 0",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Konsa\r 1",
    "Player_14": "Van den Berg\r 2",
    "Player_7": "Luis D\u00EDaz\r 6",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Palmer\r 11",
    "Player_6": "M.Salah\r 11",
    "Player_3": "Konat\u00E9\r 0",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "Saka\r 18",
    "Player_9": "Smith Rowe\r 2",
    "Player_15": "Jebbison\r 0"
  },
  {
    "manager_Name": "700( 2,085,403 ) TotalXfr : 12",
    "Teams": "The SAFfron Sword( Milan Singh )",
    "SXL": "India",
    "Latp": "76",
    "Player_1": "Raya\r 2",
    "Player_11": "Wissa\r 8",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r 2",
    "Player_14": "Mykolenko\r -1",
    "Player_7": "Palmer\r 22",
    "Player_2": "A\u00EFt-Nouri\r 0",
    "Player_5": "Saka\r 18",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Greaves\r 0",
    "Player_4": "Gabriel\r 9",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Cunha\r 2",
    "Player_15": "Lewis\r 1"
  },
  {
    "manager_Name": "695( 2,283,762 ) TotalXfr : 11",
    "Teams": "100 Yard Line Lords( Abhinay Pradhan )",
    "SXL": "India",
    "Latp": "49",
    "Player_1": "S\u00E1nchez\r 7",
    "Player_11": "N.Jackson\r 12",
    "Player_10": "Cunha\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Johnson\r 7",
    "Player_14": "Winks\r 0",
    "Player_7": "Smith Rowe\r 2",
    "Player_2": "Mykolenko\r -1",
    "Player_5": "Andersen\r 0",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "Virgil\r 6",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Romero\r 0"
  },
  {
    "manager_Name": "693( 2,363,059 ) TotalXfr : 10",
    "Teams": "FOMO7 FC( Chaje Lokam )",
    "SXL": "India",
    "Latp": "67",
    "Player_1": "S\u00E1nchez\r 7",
    "Player_11": "Haaland\r 2",
    "Player_10": "Ra\u00FAl\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Yarmoliuk\r 1",
    "Player_14": "Burgess\r 2",
    "Player_7": "Palmer\r 22",
    "Player_2": "Gabriel\r 9",
    "Player_5": "Rogers\r 2",
    "Player_6": "M.Salah\r 11",
    "Player_3": "Hall\r 2",
    "Player_4": "Gvardiol\r 0",
    "Player_8": "Garnacho\r 1",
    "Player_9": "Wood\r 9",
    "Player_15": "Bree\r 0"
  },
  {
    "manager_Name": "693( 2,367,639 ) TotalXfr : 11",
    "Teams": "Imperial Blues FC( Saurabh Tamang )",
    "SXL": "India",
    "Latp": "61",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Solanke\r 0",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Van den Berg\r 2",
    "Player_14": "Faes\r 0",
    "Player_7": "Mbeumo\r 4",
    "Player_2": "Gabriel\r 9",
    "Player_5": "M.Salah\r 11",
    "Player_6": "Palmer\r 11",
    "Player_3": "Virgil\r 6",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Johnson\r 7",
    "Player_9": "Wood\r 9",
    "Player_15": "Rogers\r 2"
  },
  {
    "manager_Name": "691( 2,447,284 ) TotalXfr : 10",
    "Teams": "PR11( pranam rai )",
    "SXL": "India",
    "Latp": "41",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Haaland\r 2",
    "Player_12": "Areola\r 0",
    "Player_13": "McNeil\r 2",
    "Player_14": "Vardy\r 5",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "A\u00EFt-Nouri\r 0",
    "Player_6": "Smith Rowe\r 2",
    "Player_3": "Gvardiol\r 0",
    "Player_4": "Lewis\r 1",
    "Player_8": "Rogers\r 2",
    "Player_9": "M.Salah\r 22",
    "Player_15": "Van de Ven\r 0"
  },
  {
    "manager_Name": "687( 2,620,569 ) TotalXfr : 10",
    "Teams": "ZilchExpectationsXI( Dipen Thapa )",
    "SXL": "India",
    "Latp": "69",
    "Player_1": "Raya\r 2",
    "Player_11": "Wood\r 9",
    "Player_10": "Havertz\r 6",
    "Player_12": "Flekken\r 2",
    "Player_13": "Burn\r 4",
    "Player_14": "Konsa\r 1",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Aina\r 8",
    "Player_5": "Smith Rowe\r 2",
    "Player_6": "Palmer\r 11",
    "Player_3": "Dalot\r 6",
    "Player_4": "Harwood-Bellis\r 1",
    "Player_8": "Saka\r 18",
    "Player_9": "Haaland\r 4",
    "Player_15": "Winks\r 0"
  },
  {
    "manager_Name": "684( 2,757,479 ) TotalXfr : 11",
    "Teams": "Darjeeling City( Ruben Pradhan )",
    "SXL": "India",
    "Latp": "66",
    "Player_1": "Pope\r 2",
    "Player_11": "Wood\r 18",
    "Player_10": "Evanilson\r 12",
    "Player_12": "S\u00E1nchez\r 7",
    "Player_13": "McNeil\r 2",
    "Player_14": "Bernardo\r 2",
    "Player_7": "Palmer\r 11",
    "Player_2": "Mazraoui\r 1",
    "Player_5": "Toti\r 1",
    "Player_6": "Janelt\r 1",
    "Player_3": "Gu\u00E9hi\r 3",
    "Player_4": "Burn\r 4",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Haaland\r 2",
    "Player_15": "Romero\r 0"
  },
  {
    "manager_Name": "683( 2,802,258 ) TotalXfr : 11",
    "Teams": "Busby Baby( Regean Lama )",
    "SXL": "India",
    "Latp": "53",
    "Player_1": "Henderson\r 2",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Haaland\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Lewis\r 1",
    "Player_14": "Wheatley\r 0",
    "Player_7": "Rogers\r 2",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "M.Salah\r 11",
    "Player_3": "Colwill\r 6",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Smith Rowe\r 2",
    "Player_9": "B.Fernandes\r 18",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "683( 2,808,907 ) TotalXfr : 12",
    "Teams": "Hooligans \u00B0\u00B024( Pradhyumna Subba )",
    "SXL": "India",
    "Latp": "55",
    "Player_1": "S\u00E1nchez\r 7",
    "Player_11": "Solanke\r 0",
    "Player_10": "Haaland\r 4",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Gvardiol\r 0",
    "Player_14": "Konsa\r 1",
    "Player_7": "Kulusevski\r 1",
    "Player_2": "Van den Berg\r 2",
    "Player_5": "Rogers\r 2",
    "Player_6": "M.Salah\r 11",
    "Player_3": "Aina\r 8",
    "Player_4": "Gabriel\r 9",
    "Player_8": "B.Fernandes\r 9",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Dibling\r 1"
  },
  {
    "manager_Name": "681( 2,887,229 ) TotalXfr : 10",
    "Teams": "\u2694\uFE0FFURY\u2694\uFE0F( Ashim Lama )",
    "SXL": "India",
    "Latp": "56",
    "Player_1": "Flekken\r 2",
    "Player_11": "Welbeck\r 2",
    "Player_10": "N.Jackson\r 6",
    "Player_12": "S\u00E1nchez\r 7",
    "Player_13": "Gvardiol\r 0",
    "Player_14": "Smith Rowe\r 2",
    "Player_7": "Amad\r 9",
    "Player_2": "Mykolenko\r -1",
    "Player_5": "Rogers\r 2",
    "Player_6": "Maddison\r 2",
    "Player_3": "Gabriel\r 9",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "M.Salah\r 22",
    "Player_9": "Haaland\r 2",
    "Player_15": "Greaves\r 0"
  },
  {
    "manager_Name": "681( 2,891,712 ) TotalXfr : 11",
    "Teams": "Dany11( Avinash DAniel Khawas )",
    "SXL": "India",
    "Latp": "54",
    "Player_1": "Onana\r 6",
    "Player_11": "Wood\r 9",
    "Player_10": "Haaland\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Barco\r 0",
    "Player_14": "Mazraoui\r 1",
    "Player_7": "Bowen\r 2",
    "Player_2": "Konat\u00E9\r 0",
    "Player_5": "M.Salah\r 22",
    "Player_6": "Martinelli\r 0",
    "Player_3": "Faes\r 0",
    "Player_4": "Virgil\r 6",
    "Player_8": "Iwobi\r 5",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Mario Jr.\r 1"
  },
  {
    "manager_Name": "678( 3,048,593 ) TotalXfr : 16",
    "Teams": "YFC Jb( Vivek Lama )",
    "SXL": "India",
    "Latp": "59",
    "Player_1": "S\u00E1nchez\r 7",
    "Player_11": "Cunha\r 2",
    "Player_10": "Welbeck\r 2",
    "Player_12": "Forster\r 3",
    "Player_13": "Winks\r 0",
    "Player_14": "Robinson\r 2",
    "Player_7": "M.Salah\r 22",
    "Player_2": "Virgil\r 6",
    "Player_5": "Sou\u010Dek\r 1",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Dalot\r 6",
    "Player_4": "Pedro Porro\r 2",
    "Player_8": "Johnson\r 7",
    "Player_9": "Haaland\r 2",
    "Player_15": "Andersen\r 0"
  },
  {
    "manager_Name": "676( 3,119,915 ) TotalXfr : 11",
    "Teams": "The Regista.( Passang T Sherpa )",
    "SXL": "India",
    "Latp": "61",
    "Player_1": "Sels\r 6",
    "Player_11": "Haaland\r 2",
    "Player_10": "Wood\r 9",
    "Player_12": "Pope\r 2",
    "Player_13": "Maddison\r 2",
    "Player_14": "Aina\r 8",
    "Player_7": "Palmer\r 22",
    "Player_2": "Virgil\r 6",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Luis D\u00EDaz\r 6",
    "Player_3": "Gu\u00E9hi\r 3",
    "Player_4": "Digne\r 1",
    "Player_8": "Smith Rowe\r 2",
    "Player_9": "Welbeck\r 2",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "672( 3,317,597 ) TotalXfr : 13",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "India",
    "Latp": "61",
    "Player_1": "Fabianski\r -1",
    "Player_11": "Cunha\r 2",
    "Player_10": "Havertz\r 6",
    "Player_12": "Henderson\r 2",
    "Player_13": "Konat\u00E9\r 0",
    "Player_14": "Faes\r 0",
    "Player_7": "M.Salah\r 22",
    "Player_2": "J.Timber\r 1",
    "Player_5": "Johnson\r 7",
    "Player_6": "Smith Rowe\r 2",
    "Player_3": "W.Fofana\r 1",
    "Player_4": "Saliba\r 1",
    "Player_8": "Palmer\r 11",
    "Player_9": "B.Fernandes\r 9",
    "Player_15": "Wheatley\r 0"
  },
  {
    "manager_Name": "668( 3,500,561 ) TotalXfr : 12",
    "Teams": "PINE( SATYAM RAI )",
    "SXL": "India",
    "Latp": "55",
    "Player_1": "Flekken\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 2",
    "Player_10": "Isak\r 1",
    "Player_12": "Lis\r 0",
    "Player_13": "Rogers\r 2",
    "Player_14": "Burgess\r 2",
    "Player_7": "Palmer\r 22",
    "Player_2": "Alexander-Arnold\r 6",
    "Player_5": "Garnacho\r 1",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Mykolenko\r -1",
    "Player_4": "Gabriel\r 9",
    "Player_8": "M.Salah\r 11",
    "Player_9": "Solanke\r 0",
    "Player_15": "Lewis\r 1"
  },
  {
    "manager_Name": "661( 3,847,499 ) TotalXfr : 19",
    "Teams": "Comet FC( Pranesh Sharma )",
    "SXL": "India",
    "Latp": "55",
    "Player_1": "S\u00E1nchez\r 7",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Cunha\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Robinson\r 2",
    "Player_14": "Taylor\r 0",
    "Player_7": "Saka\r 18",
    "Player_2": "Digne\r 1",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Son\r 4",
    "Player_3": "Hall\r 2",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Bowen\r 2",
    "Player_9": "M.Salah\r 11",
    "Player_15": "Al-Hamadi\r 0"
  },
  {
    "manager_Name": "655( 4,110,130 ) TotalXfr : 11",
    "Teams": "\uFFFD Fields FC( Ravish Verma )",
    "SXL": "Canada",
    "Latp": "46",
    "Player_1": "Flekken\r 2",
    "Player_11": "Cunha\r 2",
    "Player_10": "Haaland\r 2",
    "Player_12": "Fabianski\r -1",
    "Player_13": "O\u0027Shea\r 1",
    "Player_14": "Lewis\r 1",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Hall\r 2",
    "Player_5": "Garnacho\r 1",
    "Player_6": "Palmer\r 22",
    "Player_3": "A\u00EFt-Nouri\r 0",
    "Player_4": "Van den Berg\r 2",
    "Player_8": "B.Fernandes\r 9",
    "Player_9": "Watkins\r 2",
    "Player_15": "Dibling\r 1"
  },
  {
    "manager_Name": "648( 4,466,802 ) TotalXfr : 23",
    "Teams": "Busby Babes( Pema Lepcha )",
    "SXL": "India",
    "Latp": "70",
    "Player_1": "Muric\r 3",
    "Player_11": "Cunha\r 4",
    "Player_10": "Wood\r 9",
    "Player_12": "Vicario\r 0",
    "Player_13": "Gabriel\r 9",
    "Player_14": "Ra\u00FAl\r 2",
    "Player_7": "B.Fernandes\r 9",
    "Player_2": "Pedro Porro\r 2",
    "Player_5": "A\u00EFt-Nouri\r 0",
    "Player_6": "Saka\r 18",
    "Player_3": "Mazraoui\r 1",
    "Player_4": "Hall\r 2",
    "Player_8": "Palmer\r 11",
    "Player_9": "M.Salah\r 11",
    "Player_15": "Semenyo\r 0"
  },
  {
    "manager_Name": "637( 4,948,627 ) TotalXfr : 7",
    "Teams": "Renga FC( William Serto )",
    "SXL": "India",
    "Latp": "37",
    "Player_1": "Pickford\r 0",
    "Player_11": "Haaland\r 2",
    "Player_10": "Jo\u00E3o Pedro\r 2",
    "Player_12": "Flekken\r 2",
    "Player_13": "Faes\r 0",
    "Player_14": "B.Soumar\u00E9\r 2",
    "Player_7": "M.Salah\r 22",
    "Player_2": "Gvardiol\r 0",
    "Player_5": "Robinson\r 2",
    "Player_6": "Adama\r 0",
    "Player_3": "Alexander-Arnold\r 6",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Martinelli\r 0",
    "Player_9": "Neto\r 3",
    "Player_15": "N.Jackson\r 6"
  },
  {
    "manager_Name": "563( 7,798,689 ) TotalXfr : 14",
    "Teams": "HEROES11( Obed Hang Subba )",
    "SXL": "India",
    "Latp": "55",
    "Player_1": "Pope\r 2",
    "Player_11": "N.Jackson\r 6",
    "Player_10": "Haaland\r 4",
    "Player_12": "Bentley\r 0",
    "Player_13": "Emerson\r 5",
    "Player_14": "Holgate\r 0",
    "Player_7": "Luis D\u00EDaz\r 6",
    "Player_2": "Dalot\r 6",
    "Player_5": "Mbeumo\r 2",
    "Player_6": "Palmer\r 11",
    "Player_3": "Mazraoui\r 1",
    "Player_4": "Robertson\r 6",
    "Player_8": "McNeil\r 2",
    "Player_9": "Wood\r 9",
    "Player_15": "Nwaneri\r 1"
  }
];