var s = [
  {
    "manager_Name": "845( 5,082 ) TotalXfr : 13",
    "Teams": "Palmlermo( Pawat Kamonsereerat )",
    "SXL": "Thailand",
    "Latp": "31",
    "Player_1": "Sels\r 6",
    "Player_11": "Wood\r 9",
    "Player_10": "Cunha\r 2",
    "Player_12": "Turner\r 0",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Lewis\r LIV (A)",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Mazraoui\r EVE (H)",
    "Player_5": "Johnson\r FUL (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "J.Timber\r 1",
    "Player_4": "Gabriel\r 9",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Jo\u00E3o Pedro\r 2",
    "Player_15": "Harwood-Bellis\r 1"
  },
  {
    "manager_Name": "783( 173,874 ) TotalXfr : 14",
    "Teams": "OnePete( Peter Jong )",
    "SXL": "Thailand",
    "Latp": "65",
    "Player_1": "Sels\r 6",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Wissa\r 8",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Konat\u00E9\r MCI (H)",
    "Player_7": "Saka\r 36",
    "Player_2": "Veltman\r 0",
    "Player_5": "M.Salah\r MCI (H)",
    "Player_6": "Palmer\r AVL (H)",
    "Player_3": "Gabriel\r 9",
    "Player_4": "A\u00EFt-Nouri\r 0",
    "Player_8": "Mbeumo\r 2",
    "Player_9": "Cunha\r 2",
    "Player_15": "Lewis\r LIV (A)"
  },
  {
    "manager_Name": "726( 1,163,344 ) TotalXfr : 9",
    "Teams": "Auto win user( Kamolphan Chayasoontorn )",
    "SXL": "Thailand",
    "Latp": "17",
    "Player_1": "S\u00E1nchez\r AVL (H)",
    "Player_11": "Haaland\r LIV (A)",
    "Player_10": "Strand Larsen\r 11",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Keane\r MUN (A)",
    "Player_7": "Palmer\r AVL (H)",
    "Player_2": "Lewis\r LIV (A)",
    "Player_5": "Digne\r CHE (A)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Konat\u00E9\r MCI (H)",
    "Player_4": "Hall\r 2",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Delap\r 2",
    "Player_15": "McNeil\r MUN (A)"
  },
  {
    "manager_Name": "699( 2,112,345 ) TotalXfr : 9",
    "Teams": "Viola( GoLf Peera )",
    "SXL": "Thailand",
    "Latp": "6",
    "Player_1": "Flekken\r 2",
    "Player_11": "Welbeck\r 2",
    "Player_10": "Ra\u00FAl\r TOT (A)",
    "Player_12": "Fabianski\r -1",
    "Player_13": "Rogers\r CHE (A)",
    "Player_14": "Murillo\r 7",
    "Player_7": "Mbeumo\r 2",
    "Player_2": "Robinson\r TOT (A)",
    "Player_5": "Palmer\r AVL (H)",
    "Player_6": "Smith Rowe\r TOT (A)",
    "Player_3": "Konat\u00E9\r MCI (H)",
    "Player_4": "Mazraoui\r EVE (H)",
    "Player_8": "M.Salah\r MCI (H)",
    "Player_9": "Haaland\r LIV (A)",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "624( 5,555,451 ) TotalXfr : 13",
    "Teams": "Tor Achee( TOR ACHEE )",
    "SXL": "Thailand",
    "Latp": "9",
    "Player_1": "Raya\r 2",
    "Player_11": "N.Jackson\r AVL (H)",
    "Player_10": "Haaland\r LIV (A)",
    "Player_12": "Jos\u00E9 S\u00E1\r 0",
    "Player_13": "J.Gomes\r 2",
    "Player_14": "Keane\r MUN (A)",
    "Player_7": "Johnson\r FUL (H)",
    "Player_2": "Van den Berg\r 2",
    "Player_5": "Neto\r AVL (H)",
    "Player_6": "Mbeumo\r 2",
    "Player_3": "Robinson\r TOT (A)",
    "Player_4": "Saliba\r 1",
    "Player_8": "Palmer\r AVL (H)",
    "Player_9": "Cunha\r 2",
    "Player_15": "Lewis\r LIV (A)"
  }
];