var s = [
  {
    "manager_Name": "197( 158,409 )",
    "Teams": "cavac215( Ankit Chhetri )",
    "SXL": "countryCode",
    "Latp": "60",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Jo\u00E3o Pedro 18",
    "Player_10": "Gy\u00F6keres 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Wan-Bissaka 0",
    "Player_14": "Gabriel 2",
    "Player_7": "Grealish 10",
    "Player_2": "Cucurella 6",
    "Player_5": "Kudus 2",
    "Player_6": "M.Salah 3",
    "Player_3": "Van de Ven 1",
    "Player_4": "Aina 1",
    "Player_8": "B.Fernandes 10",
    "Player_9": "Reijnders 2",
    "Player_15": "Marc Guiu 1"
  },
  {
    "manager_Name": "193( 239,398 )",
    "Teams": "Kung fu Pandoos( Indrajeet Singh )",
    "SXL": "countryCode",
    "Latp": "55",
    "Player_1": "Kelleher 1",
    "Player_11": "Watkins 2",
    "Player_10": "Haaland 18",
    "Player_12": "S\u00E1nchez 6",
    "Player_13": "Aina 1",
    "Player_14": "Walker 0",
    "Player_7": "Semenyo 2",
    "Player_2": "Cucurella 6",
    "Player_5": "Kudus 2",
    "Player_6": "Grealish 10",
    "Player_3": "Pedro Porro 4",
    "Player_4": "A\u00EFt-Nouri 0",
    "Player_8": "Cunha 1",
    "Player_9": "Bowen 9",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "191( 302,134 )",
    "Teams": "False 9( Rohan Rai )",
    "SXL": "countryCode",
    "Latp": "58",
    "Player_1": "Sels 2",
    "Player_11": "Watkins 2",
    "Player_10": "Jo\u00E3o Pedro 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Dewsbury-Hall 12",
    "Player_14": "Konsa 1",
    "Player_7": "Gakpo 3",
    "Player_2": "Cucurella 6",
    "Player_5": "Kudus 2",
    "Player_6": "Mbeumo 10",
    "Player_3": "Pedro Porro 4",
    "Player_4": "N.Williams 1",
    "Player_8": "Cunha 1",
    "Player_9": "Haaland 18",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "186( 493,714 )",
    "Teams": "abcde FC( Prayash Thapa )",
    "SXL": "countryCode",
    "Latp": "64",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Jo\u00E3o Pedro 9",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Dewsbury-Hall 12",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "Reijnders 2",
    "Player_2": "Van de Ven 1",
    "Player_5": "B.Fernandes 20",
    "Player_6": "M.Salah 3",
    "Player_3": "N.Williams 1",
    "Player_4": "Richards 8",
    "Player_8": "Wirtz 3",
    "Player_9": "Bowen 9",
    "Player_15": "Wan-Bissaka 0"
  },
  {
    "manager_Name": "185( 541,869 )",
    "Teams": "error404( Duri Tadu )",
    "SXL": "countryCode",
    "Latp": "66",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Watkins 2",
    "Player_10": "Bowen 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Anderson 2",
    "Player_14": "Andersen 3",
    "Player_7": "Reijnders 2",
    "Player_2": "N.Williams 1",
    "Player_5": "Rogers 2",
    "Player_6": "M.Salah 3",
    "Player_3": "Richards 8",
    "Player_4": "Pedro Porro 4",
    "Player_8": "B.Fernandes 20",
    "Player_9": "Jo\u00E3o Pedro 9",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "181( 758,104 )",
    "Teams": "PWS( Z S )",
    "SXL": "countryCode",
    "Latp": "60",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Haaland 18",
    "Player_10": "Jo\u00E3o Pedro 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Dorgu 0",
    "Player_14": "Gakpo 3",
    "Player_7": "Anderson 2",
    "Player_2": "Cucurella 6",
    "Player_5": "Semenyo 2",
    "Player_6": "Reijnders 2",
    "Player_3": "Gabriel 2",
    "Player_4": "Van de Ven 1",
    "Player_8": "Mbeumo 10",
    "Player_9": "Watkins 2",
    "Player_15": "Reinildo 1"
  },
  {
    "manager_Name": "181( 772,668 )",
    "Teams": "11 n over( Ashish Rai )",
    "SXL": "countryCode",
    "Latp": "59",
    "Player_1": "Raya 2",
    "Player_11": "Jo\u00E3o Pedro 9",
    "Player_10": "Haaland 18",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Diouf 10",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "Wirtz 3",
    "Player_2": "Aina 1",
    "Player_5": "Minteh 4",
    "Player_6": "Kudus 2",
    "Player_3": "Mu\u00F1oz 9",
    "Player_4": "Rodon 7",
    "Player_8": "O.Dango 2",
    "Player_9": "Richarlison 2",
    "Player_15": "Palmer 0"
  },
  {
    "manager_Name": "176( 1,142,760 )",
    "Teams": "GustavousGooner( Ashish Subba )",
    "SXL": "countryCode",
    "Latp": "57",
    "Player_1": "Sels 2",
    "Player_11": "Jo\u00E3o Pedro 9",
    "Player_10": "Haaland 18",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Dorgu 0",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "Mbeumo 10",
    "Player_2": "Reinildo 1",
    "Player_5": "Ndoye 1",
    "Player_6": "Reijnders 2",
    "Player_3": "Gudmundsson 9",
    "Player_4": "Aina 1",
    "Player_8": "M.Salah 3",
    "Player_9": "Gy\u00F6keres 1",
    "Player_15": "Nyoni 0"
  },
  {
    "manager_Name": "172( 1,559,481 )",
    "Teams": "Cheesygarlic( Rishi Thulung )",
    "SXL": "countryCode",
    "Latp": "65",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Haaland 18",
    "Player_10": "Jo\u00E3o Pedro 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Dorgu 0",
    "Player_14": "Marc Guiu 1",
    "Player_7": "Caicedo 4",
    "Player_2": "N.Williams 1",
    "Player_5": "Virgil 8",
    "Player_6": "M.Salah 3",
    "Player_3": "Van de Ven 1",
    "Player_4": "Tarkowski 3",
    "Player_8": "Reijnders 2",
    "Player_9": "B.Fernandes 10",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "168( 2,037,157 )",
    "Teams": "ASHLAD FC( Ashim Lama )",
    "SXL": "countryCode",
    "Latp": "52",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Watkins 2",
    "Player_10": "Jo\u00E3o Pedro 18",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Wan-Bissaka 0",
    "Player_14": "Dorgu 0",
    "Player_7": "Gakpo 3",
    "Player_2": "Virgil 8",
    "Player_5": "M.Salah 3",
    "Player_6": "Cunha 1",
    "Player_3": "Van de Ven 1",
    "Player_4": "Est\u00E8ve 1",
    "Player_8": "Semenyo 2",
    "Player_9": "Ndiaye 7",
    "Player_15": "Marc Guiu 1"
  },
  {
    "manager_Name": "164( 2,590,197 )",
    "Teams": "GODFATHER FC( Riwaj Rai )",
    "SXL": "countryCode",
    "Latp": "56",
    "Player_1": "Sels 2",
    "Player_11": "Jo\u00E3o Pedro 18",
    "Player_10": "M.Salah 3",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Wan-Bissaka 0",
    "Player_14": "Welbeck 2",
    "Player_7": "Reijnders 2",
    "Player_2": "Murillo 1",
    "Player_5": "Pedro Porro 4",
    "Player_6": "Kudus 2",
    "Player_3": "Est\u00E8ve 1",
    "Player_4": "Cucurella 6",
    "Player_8": "Marmoush 7",
    "Player_9": "Grealish 10",
    "Player_15": "F\u00FCllkrug 2"
  },
  {
    "manager_Name": "162( 2,952,202 )",
    "Teams": "Busby Baby( Regean Lama )",
    "SXL": "countryCode",
    "Latp": "47",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Haaland 18",
    "Player_10": "Jo\u00E3o Pedro 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Alex Moreno 0",
    "Player_14": "Dorgu 0",
    "Player_7": "Tavernier 3",
    "Player_2": "Van de Ven 1",
    "Player_5": "Reijnders 2",
    "Player_6": "Cunha 1",
    "Player_3": "Aina 1",
    "Player_4": "Konsa 1",
    "Player_8": "Kudus 2",
    "Player_9": "M.Salah 3",
    "Player_15": "\u00C9douard 0"
  },
  {
    "manager_Name": "158( 3,539,807 )",
    "Teams": "\u0160e\u0161ko and Destroy( Pema Lepcha )",
    "SXL": "countryCode",
    "Latp": "48",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Watkins 2",
    "Player_10": "Jo\u00E3o Pedro 18",
    "Player_12": "Darlow 0",
    "Player_13": "Wan-Bissaka 0",
    "Player_14": "Marc Guiu 1",
    "Player_7": "B.Fernandes 10",
    "Player_2": "Van de Ven 1",
    "Player_5": "Reijnders 2",
    "Player_6": "M.Salah 3",
    "Player_3": "Est\u00E8ve 1",
    "Player_4": "Cash 0",
    "Player_8": "Bruno G. 3",
    "Player_9": "Kudus 2",
    "Player_15": "Frimpong 0"
  },
  {
    "manager_Name": "158( 3,636,129 )",
    "Teams": "RIP-DIOGO.20( pranam rai )",
    "SXL": "countryCode",
    "Latp": "50",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Haaland 18",
    "Player_10": "Wood 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Damsgaard 2",
    "Player_14": "A.Ramsey 0",
    "Player_7": "Semenyo 2",
    "Player_2": "N.Williams 1",
    "Player_5": "Est\u00E8ve 1",
    "Player_6": "Kudus 2",
    "Player_3": "Cucurella 6",
    "Player_4": "Aina 1",
    "Player_8": "Reijnders 2",
    "Player_9": "Jo\u00E3o Pedro 9",
    "Player_15": "Gabriel 2"
  },
  {
    "manager_Name": "157( 3,674,636 )",
    "Teams": "The Regista.( Passang T Sherpa )",
    "SXL": "countryCode",
    "Latp": "52",
    "Player_1": "Vicario 3",
    "Player_11": "Jo\u00E3o Pedro 18",
    "Player_10": "Wood 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Reijnders 2",
    "Player_14": "N.Williams 1",
    "Player_7": "M.Salah 3",
    "Player_2": "Cucurella 6",
    "Player_5": "Enzo 12",
    "Player_6": "Ndoye 1",
    "Player_3": "Calafiori 2",
    "Player_4": "Van de Ven 1",
    "Player_8": "Kudus 2",
    "Player_9": "Ekitik\u00E9 2",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "156( 3,876,509 )",
    "Teams": "Blue Brigade( Bhuman Basnet )",
    "SXL": "countryCode",
    "Latp": "44",
    "Player_1": "Sels 2",
    "Player_11": "Wood 4",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Tarkowski 3",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "M.Salah 3",
    "Player_2": "Aina 1",
    "Player_5": "B.Fernandes 10",
    "Player_6": "Johnson 1",
    "Player_3": "Cucurella 6",
    "Player_4": "Pedro Porro 4",
    "Player_8": "Reijnders 2",
    "Player_9": "Jo\u00E3o Pedro 9",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "155( 4,046,717 )",
    "Teams": "Hangkim_0011( ABHINANDAN RAI )",
    "SXL": "countryCode",
    "Latp": "47",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Ekitik\u00E9 2",
    "Player_10": "Jo\u00E3o Pedro 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Konsa 1",
    "Player_14": "P.M.Sarr 2",
    "Player_7": "Wirtz 3",
    "Player_2": "Pedro Porro 4",
    "Player_5": "Reijnders 2",
    "Player_6": "M.Salah 3",
    "Player_3": "A\u00EFt-Nouri 0",
    "Player_4": "Reinildo 1",
    "Player_8": "Ndiaye 7",
    "Player_9": "Watkins 4",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "154( 4,217,967 )",
    "Teams": "Imperial Blues( Saurabh Tamang )",
    "SXL": "countryCode",
    "Latp": "62",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Jo\u00E3o Pedro 9",
    "Player_10": "Sarr 7",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Strand Larsen 0",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "Reijnders 4",
    "Player_2": "Virgil 8",
    "Player_5": "Richards 8",
    "Player_6": "M.Salah 3",
    "Player_3": "N.Williams 1",
    "Player_4": "Pedro Porro 4",
    "Player_8": "B.Fernandes 10",
    "Player_9": "Anderson 2",
    "Player_15": "Marc Guiu 1"
  },
  {
    "manager_Name": "153( 4,452,931 )",
    "Teams": "MANCHESTER IS BLUE( PRAYAS BAJGAI )",
    "SXL": "countryCode",
    "Latp": "64",
    "Player_1": "Sels 2",
    "Player_11": "Haaland 18",
    "Player_10": "Jo\u00E3o Pedro 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Est\u00E8ve 1",
    "Player_14": "Diouf 10",
    "Player_7": "M.Salah 3",
    "Player_2": "Andersen 3",
    "Player_5": "Cunha 1",
    "Player_6": "Rogers 2",
    "Player_3": "Pedro Porro 4",
    "Player_4": "Richards 8",
    "Player_8": "Reijnders 2",
    "Player_9": "Dewsbury-Hall 12",
    "Player_15": "Marc Guiu 1"
  },
  {
    "manager_Name": "152( 4,561,541 )",
    "Teams": "Lu Lu( Nishant Lohagun )",
    "SXL": "countryCode",
    "Latp": "44",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Richarlison 4",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Rogers 2",
    "Player_14": "Andersen 3",
    "Player_7": "M.Salah 3",
    "Player_2": "N.Williams 1",
    "Player_5": "B.Fernandes 10",
    "Player_6": "Semenyo 2",
    "Player_3": "Pedro Porro 4",
    "Player_4": "Agbadou 1",
    "Player_8": "Reijnders 2",
    "Player_9": "Jo\u00E3o Pedro 9",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "151( 4,703,284 )",
    "Teams": "I_am_done_XI( Dipen Thapa )",
    "SXL": "countryCode",
    "Latp": "38",
    "Player_1": "Raya 2",
    "Player_11": "Richarlison 2",
    "Player_10": "Gy\u00F6keres 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Gakpo 3",
    "Player_14": "Gu\u00E9hi 15",
    "Player_7": "Madueke 2",
    "Player_2": "Konsa 1",
    "Player_5": "Semenyo 2",
    "Player_6": "Kudus 2",
    "Player_3": "Aina 1",
    "Player_4": "Pedro Porro 4",
    "Player_8": "M.Salah 3",
    "Player_9": "Jo\u00E3o Pedro 18",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "149( 5,075,894 )",
    "Teams": "Hooligans25( Pradhyumna Subba )",
    "SXL": "countryCode",
    "Latp": "38",
    "Player_1": "D\u00FAbravka 2",
    "Player_11": "Watkins 2",
    "Player_10": "Jo\u00E3o Pedro 18",
    "Player_12": "Verbruggen 2",
    "Player_13": "Foden 0",
    "Player_14": "Reinildo 1",
    "Player_7": "Reijnders 2",
    "Player_2": "N.Williams 1",
    "Player_5": "M.Salah 3",
    "Player_6": "Wirtz 3",
    "Player_3": "Konsa 1",
    "Player_4": "Van de Ven 1",
    "Player_8": "Neto 3",
    "Player_9": "F\u00FCllkrug 2",
    "Player_15": "De Cuyper 2"
  },
  {
    "manager_Name": "148( 5,214,958 )",
    "Teams": "Top Gooner( VibhutiHang Subba )",
    "SXL": "countryCode",
    "Latp": "40",
    "Player_1": "Sels 2",
    "Player_11": "Wood 4",
    "Player_10": "Gy\u00F6keres 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Anthony 6",
    "Player_14": "Rodon 7",
    "Player_7": "Ndoye 1",
    "Player_2": "Livramento 6",
    "Player_5": "B.Fernandes 10",
    "Player_6": "Cunha 1",
    "Player_3": "Tarkowski 3",
    "Player_4": "Gabriel 2",
    "Player_8": "Elanga 1",
    "Player_9": "Haaland 9",
    "Player_15": "Ekdal 3"
  },
  {
    "manager_Name": "148( 5,244,406 )",
    "Teams": "Alpha11( AVIJIT DAS )",
    "SXL": "countryCode",
    "Latp": "43",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Wood 4",
    "Player_10": "Jo\u00E3o Pedro 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Rogers 2",
    "Player_14": "Rodon 7",
    "Player_7": "B.Fernandes 10",
    "Player_2": "Pedro Porro 4",
    "Player_5": "M.Salah 3",
    "Player_6": "Johnson 1",
    "Player_3": "N.Williams 1",
    "Player_4": "Konsa 1",
    "Player_8": "Reijnders 2",
    "Player_9": "Watkins 2",
    "Player_15": "Diouf 10"
  },
  {
    "manager_Name": "147( 5,468,010 )",
    "Teams": "Invincibles( Bishal Rai )",
    "SXL": "countryCode",
    "Latp": "26",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Ekitik\u00E9 2",
    "Player_10": "Wood 4",
    "Player_12": "Kinsky 0",
    "Player_13": "A\u00EFt-Nouri 0",
    "Player_14": "Wirtz 3",
    "Player_7": "Johnson 1",
    "Player_2": "Milenkovi\u0107 1",
    "Player_5": "Pedro Porro 4",
    "Player_6": "Semenyo 2",
    "Player_3": "Aina 1",
    "Player_4": "Saliba 1",
    "Player_8": "Neto 3",
    "Player_9": "Gy\u00F6keres 1",
    "Player_15": "Irving 1"
  },
  {
    "manager_Name": "145( 5,740,766 )",
    "Teams": "PINE( SATYAM RAI )",
    "SXL": "countryCode",
    "Latp": "54",
    "Player_1": "Sels 2",
    "Player_11": "Wood 2",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Strand Larsen 0",
    "Player_14": "Truffert 7",
    "Player_7": "M.Salah 3",
    "Player_2": "Richards 8",
    "Player_5": "Wirtz 3",
    "Player_6": "B.Fernandes 20",
    "Player_3": "Pedro Porro 4",
    "Player_4": "Konsa 1",
    "Player_8": "Sarr 7",
    "Player_9": "Reijnders 2",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "145( 5,816,634 )",
    "Teams": "Jorebungalow YFC( Vivek Lama )",
    "SXL": "countryCode",
    "Latp": "40",
    "Player_1": "Verbruggen 2",
    "Player_11": "Haaland 9",
    "Player_10": "Welbeck 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "A.Ramsey 0",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "Cunha 1",
    "Player_2": "Cucurella 6",
    "Player_5": "De Cuyper 2",
    "Player_6": "Kudus 2",
    "Player_3": "Van de Ven 1",
    "Player_4": "A\u00EFt-Nouri 0",
    "Player_8": "M.Salah 6",
    "Player_9": "Jo\u00E3o Pedro 9",
    "Player_15": "L.Miley 1"
  },
  {
    "manager_Name": "144( 5,874,661 )",
    "Teams": "F.C. ASSASSINS( Kushal Sahota )",
    "SXL": "countryCode",
    "Latp": "52",
    "Player_1": "Sels 2",
    "Player_11": "Haaland 9",
    "Player_10": "Jo\u00E3o Pedro 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Virgil 8",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "M.Salah 6",
    "Player_2": "Livramento 6",
    "Player_5": "Ndoye 1",
    "Player_6": "Reijnders 2",
    "Player_3": "Van de Ven 1",
    "Player_4": "Chalobah 13",
    "Player_8": "Johnson 1",
    "Player_9": "Richarlison 2",
    "Player_15": "King 2"
  },
  {
    "manager_Name": "143( 6,059,108 )",
    "Teams": "G\u00CBNJ\u00CF\u00CF UNITED( Pema Bhutia )",
    "SXL": "countryCode",
    "Latp": "51",
    "Player_1": "Sels 2",
    "Player_11": "Jo\u00E3o Pedro 9",
    "Player_10": "Mateta 5",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Dorgu 0",
    "Player_14": "Georginio 1",
    "Player_7": "M.Salah 3",
    "Player_2": "Pedro Porro 4",
    "Player_5": "Reijnders 2",
    "Player_6": "Semenyo 2",
    "Player_3": "Murillo 1",
    "Player_4": "Van de Ven 1",
    "Player_8": "B.Fernandes 20",
    "Player_9": "Watkins 2",
    "Player_15": "Diouf 10"
  },
  {
    "manager_Name": "142( 6,187,653 )",
    "Teams": "Liverpool FC( Sunil Rai )",
    "SXL": "countryCode",
    "Latp": "59",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Mateta 5",
    "Player_10": "Jo\u00E3o Pedro 9",
    "Player_12": "Pope 5",
    "Player_13": "Mu\u00F1oz 9",
    "Player_14": "Tavernier 3",
    "Player_7": "M.Salah 3",
    "Player_2": "Pedro Porro 4",
    "Player_5": "Sarr 14",
    "Player_6": "Semenyo 2",
    "Player_3": "Livramento 6",
    "Player_4": "Cucurella 6",
    "Player_8": "Reijnders 2",
    "Player_9": "Ekitik\u00E9 2",
    "Player_15": "Van de Ven 1"
  },
  {
    "manager_Name": "141( 6,365,270 )",
    "Teams": "Comet FC( Pranesh Sharma )",
    "SXL": "countryCode",
    "Latp": "37",
    "Player_1": "S\u00E1nchez 12",
    "Player_11": "Watkins 2",
    "Player_10": "Jo\u00E3o Pedro 9",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Saka 0",
    "Player_14": "Alex Moreno 0",
    "Player_7": "Kudus 2",
    "Player_2": "Pedro Porro 4",
    "Player_5": "Clyne 1",
    "Player_6": "M.Salah 3",
    "Player_3": "Est\u00E8ve 1",
    "Player_4": "Cash 0",
    "Player_8": "Reijnders 2",
    "Player_9": "Marc Guiu 1",
    "Player_15": "Palmer 0"
  },
  {
    "manager_Name": "139( 6,697,666 )",
    "Teams": "Let MEE COOK( \u00CFaraplang Pompyrthat )",
    "SXL": "countryCode",
    "Latp": "38",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Jo\u00E3o Pedro 9",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Richards 8",
    "Player_14": "Dewsbury-Hall 12",
    "Player_7": "Gakpo 3",
    "Player_2": "Pedro Porro 4",
    "Player_5": "Kudus 2",
    "Player_6": "M.Salah 3",
    "Player_3": "N.Williams 1",
    "Player_4": "Agbadou 1",
    "Player_8": "Wirtz 3",
    "Player_9": "Wood 4",
    "Player_15": "Est\u00E8ve 1"
  },
  {
    "manager_Name": "137( 6,930,457 )",
    "Teams": "F95( Sibin - )",
    "SXL": "countryCode",
    "Latp": "38",
    "Player_1": "Sels 2",
    "Player_11": "Jo\u00E3o Pedro 18",
    "Player_10": "Semenyo 2",
    "Player_12": "Kinsky 0",
    "Player_13": "Solanke 0",
    "Player_14": "Masuaku 0",
    "Player_7": "Reijnders 2",
    "Player_2": "Pedro Porro 4",
    "Player_5": "Van Hecke 1",
    "Player_6": "Wirtz 3",
    "Player_3": "Saliba 1",
    "Player_4": "Aina 1",
    "Player_8": "M.Salah 3",
    "Player_9": "Adingra 1",
    "Player_15": "Marc Guiu 1"
  },
  {
    "manager_Name": "136( 7,061,993 )",
    "Teams": "Native United( Monlom Rongong )",
    "SXL": "countryCode",
    "Latp": "39",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Wood 4",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Est\u00E8ve 1",
    "Player_14": "Rodon 7",
    "Player_7": "M.Salah 3",
    "Player_2": "Murillo 1",
    "Player_5": "Semenyo 2",
    "Player_6": "Wirtz 3",
    "Player_3": "Virgil 8",
    "Player_4": "Van de Ven 1",
    "Player_8": "Ndiaye 7",
    "Player_9": "Reijnders 2",
    "Player_15": "Marc Guiu 1"
  },
  {
    "manager_Name": "135( 7,169,561 )",
    "Teams": "Fu\u00DFball-Mannschaft( Gaurav Shrestha )",
    "SXL": "countryCode",
    "Latp": "31",
    "Player_1": "Sels 2",
    "Player_11": "Jo\u00E3o Pedro 9",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Rodon 7",
    "Player_14": "Andersen 3",
    "Player_7": "Wirtz 3",
    "Player_2": "Pedro Porro 4",
    "Player_5": "M.Salah 3",
    "Player_6": "Cunha 2",
    "Player_3": "Murillo 1",
    "Player_4": "Van de Ven 1",
    "Player_8": "Reijnders 2",
    "Player_9": "Rogers 2",
    "Player_15": "Marc Guiu 1"
  },
  {
    "manager_Name": "132( 7,573,418 )",
    "Teams": "GUNNERS( Omkar Subba )",
    "SXL": "countryCode",
    "Latp": "37",
    "Player_1": "Sels 2",
    "Player_11": "Wood 2",
    "Player_10": "Richarlison 4",
    "Player_12": "Verbruggen 2",
    "Player_13": "J.Murphy 3",
    "Player_14": "Wan-Bissaka 0",
    "Player_7": "M.Salah 3",
    "Player_2": "Virgil 8",
    "Player_5": "Milenkovi\u0107 1",
    "Player_6": "Mbeumo 10",
    "Player_3": "Saliba 1",
    "Player_4": "Spence 1",
    "Player_8": "Reijnders 2",
    "Player_9": "Gakpo 3",
    "Player_15": "Bamford 0"
  },
  {
    "manager_Name": "128( 7,958,982 )",
    "Teams": "Bruno-nly Fans( Bejoy M Shrestha\u00B2\u2076\u2074 )",
    "SXL": "countryCode",
    "Latp": "29",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Wood 2",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Diouf 10",
    "Player_14": "Est\u00E8ve 1",
    "Player_7": "M.Salah 6",
    "Player_2": "N.Williams 1",
    "Player_5": "Kudus 2",
    "Player_6": "Semenyo 2",
    "Player_3": "Pedro Porro 4",
    "Player_4": "Reinildo 1",
    "Player_8": "Cunha 1",
    "Player_9": "Reijnders 2",
    "Player_15": "Marc Guiu 1"
  },
  {
    "manager_Name": "121( 8,540,740 )",
    "Teams": "Boehly Blues( Aditya Bhandari )",
    "SXL": "countryCode",
    "Latp": "57",
    "Player_1": "D\u00FAbravka 2",
    "Player_11": "Haaland 18",
    "Player_10": "Wood 2",
    "Player_12": "Petrovi\u0107 5",
    "Player_13": "Brooks 4",
    "Player_14": "Dorgu 0",
    "Player_7": "M.Salah 3",
    "Player_2": "Aina 1",
    "Player_5": "Reijnders 2",
    "Player_6": "Gakpo 3",
    "Player_3": "Gudmundsson 9",
    "Player_4": "Cucurella 6",
    "Player_8": "Kudus 2",
    "Player_9": "Jo\u00E3o Pedro 9",
    "Player_15": "Est\u00E8ve 1"
  }
];