var s = [
   {
      "manager_Name":"Sahil Lampard",
      "Teams":"MarxUnited",
      "Player_1":"Ramsdale 7",
      "Player_2":"Alexander-Arnold 9",
      "Player_3":"James MUN (H)",
      "Player_4":"Cancelo WHU (H)",
      "Player_5":"White 6",
      "Player_6":"Benrahma MCI (A)",
      "Player_7":"Smith Rowe 3",
      "Player_8":"Salah 12$ captain",
      "Player_9":"Hudson-Odoi MUN (H)",
      "Player_10":"Vardy WAT (H)",
      "Player_11":"Saint-Maximin 2",
      "Player_12":"Sánchez 8",
      "Player_13":"Townsend BRE (A)",
      "Player_14":"Maupay 2",
      "Player_15":"Livramento 0",
      "SXL":"39",
      "Bench":"693",
      "Count  ":"1,249,698"
   },
   {
      "manager_Name":"Saurabh Tamang",
      "Teams":"Lucky FC",
      "Player_1":"Guaita 1",
      "Player_2":"Livramento 0",
      "Player_3":"Cancelo WHU (H)",
      "Player_4":"Alexander-Arnold 9",
      "Player_5":"Duffy 0",
      "Player_6":"Smith Rowe 3",
      "Player_7":"Salah 12$ captain",
      "Player_8":"Gallagher 2",
      "Player_9":"Cornet TOT (H)",
      "Player_10":"Ronaldo CHE (A)",
      "Player_11":"Vardy WAT (H)",
      "Player_12":"Sánchez 8",
      "Player_13":"Gray BRE (A)",
      "Player_14":"Omobamidele 0",
      "Player_15":"Archer 0",
      "SXL":"27",
      "Bench":"641",
      "Count  ":"2,554,026"
   },
   {
      "manager_Name":"Pranesh Sharma",
      "Teams":"Immortal FC",
      "Player_1":"Schmeichel WAT (H)",
      "Player_2":"James MUN (H)",
      "Player_3":"White 6",
      "Player_4":"Alexander-Arnold 9",
      "Player_5":"Gallagher 2",
      "Player_6":"Jota 14",
      "Player_7":"Salah 12$ captain",
      "Player_8":"Smith Rowe 3",
      "Player_9":"Pukki 2",
      "Player_10":"Kane BUR (A)",
      "Player_11":"Vardy WAT (H)",
      "Player_12":"Foster LEI (A)",
      "Player_13":"Bissouma 2",
      "Player_14":"Dier BUR (A)",
      "Player_15":"Amartey WAT (H)",
      "SXL":"48",
      "Bench":"726",
      "Count  ":"639,542"
   },
   {
      "manager_Name":"Sanjeev Kumar",
      "Teams":"GAROBADHA UNITED",
      "Player_1":"de Gea CHE (A)",
      "Player_2":"Duffy 0",
      "Player_3":"Cancelo WHU (H)",
      "Player_4":"White 6",
      "Player_5":"Son BUR (A)",
      "Player_6":"Højbjerg BUR (A)",
      "Player_7":"Salah 12$ captain",
      "Player_8":"Raphinha 3",
      "Player_9":"Gallagher 2",
      "Player_10":"Hwang 2",
      "Player_11":"Kane BUR (A)",
      "Player_12":"Foster LEI (A)",
      "Player_13":"Alonso MUN (H)",
      "Player_14":"Pukki 2",
      "Player_15":"Shaw CHE (A)",
      "SXL":"25",
      "Bench":"712",
      "Count  ":"873,611"
   },
   {
      "manager_Name":"Kumar Anku",
      "Teams":"The Borderland Fc",
      "Player_1":"Ramsdale 7",
      "Player_2":"Tomiyasu 12",
      "Player_3":"Cancelo WHU (H)",
      "Player_4":"Reguilón BUR (A)",
      "Player_5":"Walker WHU (H)",
      "Player_6":"Alexander-Arnold 9",
      "Player_7":"Smith Rowe 3",
      "Player_8":"Bergwijn BUR (A)",
      "Player_9":"Salah 12$ captain",
      "Player_10":"Vardy WAT (H)",
      "Player_11":"Ronaldo CHE (A)",
      "Player_12":"McCarthy 0",
      "Player_13":"Benrahma MCI (A)",
      "Player_14":"Gelhardt 0",
      "Player_15":"Moder 3",
      "SXL":"43",
      "Bench":"652",
      "Count  ":"2,254,703"
   },
   {
      "manager_Name":"Kushal Sahota",
      "Teams":"FC ASSASSINS",
      "Player_1":"Mendy MUN (H)",
      "Player_2":"Duffy 0",
      "Player_3":"Walker WHU (H)",
      "Player_4":"Tsimikas 0",
      "Player_5":"James MUN (H)",
      "Player_6":"Raphinha 3",
      "Player_7":"Gallagher 2",
      "Player_8":"Salah 12$ captain",
      "Player_9":"Hwang 2",
      "Player_10":"Vardy WAT (H)",
      "Player_11":"Ronaldo CHE (A)",
      "Player_12":"Guaita 1",
      "Player_13":"Townsend BRE (A)",
      "Player_14":"Livramento 0",
      "Player_15":"Bissouma 2",
      "SXL":"19",
      "Bench":"663",
      "Count  ":"1,967,144"
   },
   {
      "manager_Name":"Regean Lama",
      "Teams":"BUSBY BABIES 2",
      "Player_1":"Ramsdale 7",
      "Player_2":"Rüdiger MUN (H)",
      "Player_3":"Pinnock EVE (H)",
      "Player_4":"Alexander-Arnold 9",
      "Player_5":"Gallagher 2",
      "Player_6":"Mbeumo EVE (H)",
      "Player_7":"Raphinha 3",
      "Player_8":"Jota 14",
      "Player_9":"Salah 12$ captain",
      "Player_10":"Antonio MCI (A)",
      "Player_11":"Ronaldo CHE (A)",
      "Player_12":"Sánchez 8",
      "Player_13":"Livramento 0",
      "Player_14":"Veltman 6",
      "Player_15":"Scarlett BUR (A)",
      "SXL":"47",
      "Bench":"709",
      "Count  ":"921,502"
   },
   {
      "manager_Name":"pranam rai",
      "Teams":"SYAKREE FC",
      "Player_1":"McCarthy 0",
      "Player_2":"Alexander-Arnold 9",
      "Player_3":"Dias WHU (H)",
      "Player_4":"James MUN (H)",
      "Player_5":"Tsimikas 0",
      "Player_6":"Bernardo WHU (H)",
      "Player_7":"Salah 12$ captain",
      "Player_8":"Son BUR (A)",
      "Player_9":"Ødegaard 3",
      "Player_10":"Hwang 2",
      "Player_11":"Ronaldo CHE (A)",
      "Player_12":"Raya EVE (H)",
      "Player_13":"Højbjerg BUR (A)",
      "Player_14":"Dennis LEI (A)",
      "Player_15":"Manquillo 0",
      "SXL":"26",
      "Bench":"657",
      "Count  ":"2,124,347"
   },
   {
      "manager_Name":"Ashim Lama",
      "Teams":"⚔️FURY⚔️",
      "Player_1":"Lloris BUR (A)",
      "Player_2":"Alexander-Arnold 9",
      "Player_3":"Duffy 0",
      "Player_4":"James MUN (H)",
      "Player_5":"Salah 12$ captain",
      "Player_6":"Gallagher 2",
      "Player_7":"Gray BRE (A)",
      "Player_8":"Benrahma MCI (A)",
      "Player_9":"Benteke 2",
      "Player_10":"Ronaldo CHE (A)",
      "Player_11":"Antonio MCI (A)",
      "Player_12":"Ward WAT (H)",
      "Player_13":"Jansson EVE (H)",
      "Player_14":"Gilmour 2",
      "Player_15":"Chilwell MUN (H)",
      "SXL":"25",
      "Bench":"701",
      "Count  ":"1,074,309"
   },
   {
      "manager_Name":"Vivek Pradhan",
      "Teams":"PEPPERBOX83",
      "Player_1":"Sánchez 8",
      "Player_2":"Alexander-Arnold 9",
      "Player_3":"Reguilón BUR (A)",
      "Player_4":"Cancelo WHU (H)",
      "Player_5":"Dias WHU (H)",
      "Player_6":"Smith Rowe 3",
      "Player_7":"Raphinha 3",
      "Player_8":"Salah 12$ captain",
      "Player_9":"Benrahma MCI (A)",
      "Player_10":"Antonio MCI (A)",
      "Player_11":"Vardy WAT (H)",
      "Player_12":"Raya EVE (H)",
      "Player_13":"Dennis LEI (A)",
      "Player_14":"Pinnock EVE (H)",
      "Player_15":"Gray BRE (A)",
      "SXL":"35",
      "Bench":"696",
      "Count  ":"1,177,861"
   },
   {
      "manager_Name":"Sibin _",
      "Teams":"F95",
      "Player_1":"Ramsdale 7",
      "Player_2":"Dias WHU (H)",
      "Player_3":"Rüdiger MUN (H)",
      "Player_4":"White 6",
      "Player_5":"Dier BUR (A)",
      "Player_6":"Havertz MUN (H)",
      "Player_7":"Salah 12$ captain",
      "Player_8":"Gallagher 2",
      "Player_9":"Smith Rowe 3",
      "Player_10":"Vardy WAT (H)",
      "Player_11":"Hwang 2",
      "Player_12":"Ederson WHU (H)",
      "Player_13":"Foden WHU (H)",
      "Player_14":"Antonio MCI (A)",
      "Player_15":"Livramento 0",
      "SXL":"32",
      "Bench":"729",
      "Count  ":"598,199"
   },
   {
      "manager_Name":"Omkar Subba",
      "Teams":"Omk09",
      "Player_1":"Alisson 7",
      "Player_2":"James MUN (H)",
      "Player_3":"Alexander-Arnold 9",
      "Player_4":"Duffy 0",
      "Player_5":"Cancelo WHU (H)",
      "Player_6":"Gallagher 2",
      "Player_7":"Gray BRE (A)",
      "Player_8":"Salah 12$ captain",
      "Player_9":"Toney EVE (H)",
      "Player_10":"Antonio MCI (A)",
      "Player_11":"Vardy WAT (H)",
      "Player_12":"Ramsdale 7",
      "Player_13":"Jansson EVE (H)",
      "Player_14":"Benrahma MCI (A)",
      "Player_15":"Bissouma 2",
      "SXL":"30",
      "Bench":"698",
      "Count  ":"1,142,945"
   },
   {
      "manager_Name":"Indrajeet Singh",
      "Teams":"Kung Fu Pandoos",
      "Player_1":"Lloris BUR (A)",
      "Player_2":"Tierney 0",
      "Player_3":"Coady 8",
      "Player_4":"Digne BRE (A)",
      "Player_5":"Söyüncü WAT (H)",
      "Player_6":"Saka 8",
      "Player_7":"Son BUR (A)",
      "Player_8":"Salah 6",
      "Player_9":"Jiménez 2",
      "Player_10":"Saint-Maximin 2",
      "Player_11":"Kane BUR (A)$ captain",
      "Player_12":"Foster LEI (A)",
      "Player_13":"James MUN (H)",
      "Player_14":"Bissouma 2",
      "Player_15":"Gilmour 2",
      "SXL":"26",
      "Bench":"646",
      "Count  ":"2,419,999"
   },
   {
      "manager_Name":"Rishi Thulung",
      "Teams":"PL CG FC",
      "Player_1":"Ramsdale 7",
      "Player_2":"James MUN (H)",
      "Player_3":"Alexander-Arnold 9",
      "Player_4":"Cancelo WHU (H)",
      "Player_5":"Duffy 0",
      "Player_6":"Salah 12$ captain",
      "Player_7":"Gallagher 2",
      "Player_8":"Son BUR (A)",
      "Player_9":"Smith Rowe 3",
      "Player_10":"Antonio MCI (A)",
      "Player_11":"Vardy WAT (H)",
      "Player_12":"Foster LEI (A)",
      "Player_13":"Livramento 0",
      "Player_14":"Douglas Luiz 0",
      "Player_15":"Hwang 2",
      "SXL":"33",
      "Bench":"728",
      "Count  ":"610,258"
   },
   {
      "manager_Name":"Dipen Thapa",
      "Teams":"BW4_11",
      "Player_1":"Sánchez 8",
      "Player_2":"Alexander-Arnold 9",
      "Player_3":"Dias WHU (H)",
      "Player_4":"Gabriel 8",
      "Player_5":"Smith Rowe 3",
      "Player_6":"Gallagher 2",
      "Player_7":"Salah 12$ captain",
      "Player_8":"Son BUR (A)",
      "Player_9":"Aubameyang 1",
      "Player_10":"Jiménez 2",
      "Player_11":"Antonio MCI (A)",
      "Player_12":"Steele 0",
      "Player_13":"Williams 7",
      "Player_14":"Allan BRE (A)",
      "Player_15":"Amartey WAT (H)",
      "SXL":"45",
      "Bench":"713",
      "Count  ":"849,627"
   },
   {
      "manager_Name":"Nishant Singh",
      "Teams":"beta",
      "Player_1":"Sánchez 8",
      "Player_2":"Livramento 0",
      "Player_3":"Cancelo WHU (H)",
      "Player_4":"Chilwell MUN (H)",
      "Player_5":"Duffy 0",
      "Player_6":"Smith Rowe 3",
      "Player_7":"Salah 12$ captain",
      "Player_8":"Benrahma MCI (A)",
      "Player_9":"Ings 0",
      "Player_10":"Vardy WAT (H)",
      "Player_11":"Antonio MCI (A)",
      "Player_12":"Foster LEI (A)",
      "Player_13":"McArthur 0",
      "Player_14":"Allan BRE (A)",
      "Player_15":"Ayling 0",
      "SXL":"23",
      "Bench":"672",
      "Count  ":"1,740,429"
   },
   {
      "manager_Name":"Ashish Subba",
      "Teams":"Gustavous Gunner",
      "Player_1":"Schmeichel WAT (H)",
      "Player_2":"Duffy 0",
      "Player_3":"Alexander-Arnold 9",
      "Player_4":"Cancelo WHU (H)",
      "Player_5":"White 6",
      "Player_6":"Raphinha 3",
      "Player_7":"Smith Rowe 3",
      "Player_8":"Gallagher 2",
      "Player_9":"Salah 6",
      "Player_10":"Vardy WAT (H)",
      "Player_11":"Aubameyang 2$ captain",
      "Player_12":"Foster LEI (A)",
      "Player_13":"Pinnock EVE (H)",
      "Player_14":"Foden WHU (H)",
      "Player_15":"Obafemi 0",
      "SXL":"31",
      "Bench":"698",
      "Count  ":"1,137,590"
   },
   {
      "manager_Name":"Rohan Rai",
      "Teams":"False 9",
      "Player_1":"Ramsdale 7",
      "Player_2":"Tomiyasu 12",
      "Player_3":"James MUN (H)",
      "Player_4":"Cancelo WHU (H)",
      "Player_5":"Salah 12$ captain",
      "Player_6":"Raphinha 3",
      "Player_7":"Zaha 1",
      "Player_8":"Jota 14",
      "Player_9":"Toney EVE (H)",
      "Player_10":"Kane BUR (A)",
      "Player_11":"Antonio MCI (A)",
      "Player_12":"Raya EVE (H)",
      "Player_13":"Laporte WHU (H)",
      "Player_14":"Brownhill TOT (H)",
      "Player_15":"Livramento 0",
      "SXL":"49",
      "Bench":"734",
      "Count  ":"530,748"
   },
   {
      "manager_Name":"Raj Kanango",
      "Teams":"Weightloss Coach",
      "Player_1":"Martínez 2",
      "Player_2":"James MUN (H)",
      "Player_3":"Manquillo 0",
      "Player_4":"Alexander-Arnold 9",
      "Player_5":"Benrahma MCI (A)",
      "Player_6":"Raphinha 3",
      "Player_7":"Son BUR (A)",
      "Player_8":"Salah 12$ captain",
      "Player_9":"Hwang 2",
      "Player_10":"Vardy WAT (H)",
      "Player_11":"Pukki 2",
      "Player_12":"Sánchez 8",
      "Player_13":"Chilwell MUN (H)",
      "Player_14":"Livramento 0",
      "Player_15":"Bissouma 2",
      "SXL":"30",
      "Bench":"716",
      "Count  ":"804,023"
   },
   {
      "manager_Name":"Gaurav Shrestha",
      "Teams":"Fußball-Mannschaft",
      "Player_1":"Ramsdale 7",
      "Player_2":"James MUN (H)",
      "Player_3":"Alexander-Arnold 9",
      "Player_4":"Cancelo WHU (H)",
      "Player_5":"Salah 12$ captain",
      "Player_6":"Foden WHU (H)",
      "Player_7":"Gallagher 2",
      "Player_8":"Raphinha 3",
      "Player_9":"Kane BUR (A)",
      "Player_10":"Toney EVE (H)",
      "Player_11":"Antonio MCI (A)",
      "Player_12":"Foster LEI (A)",
      "Player_13":"Duffy 0",
      "Player_14":"Brownhill TOT (H)",
      "Player_15":"Livramento 0",
      "SXL":"33",
      "Bench":"782",
      "Count  ":"119,041"
   },
   {
      "manager_Name":"Bishal Rai",
      "Teams":"Gooner for Life 037",
      "Player_1":"Foster LEI (A)",
      "Player_2":"Alexander-Arnold 9",
      "Player_3":"Cancelo WHU (H)",
      "Player_4":"James MUN (H)",
      "Player_5":"Alonso MUN (H)",
      "Player_6":"Foden WHU (H)",
      "Player_7":"Jota 14",
      "Player_8":"Raphinha 3",
      "Player_9":"Salah 12$ captain",
      "Player_10":"Benteke 2",
      "Player_11":"Jesus WHU (H)",
      "Player_12":"Sánchez 8",
      "Player_13":"Mbeumo EVE (H)",
      "Player_14":"Duffy 0",
      "Player_15":"Richardson TOT (H)",
      "SXL":"40",
      "Bench":"758",
      "Count  ":"277,771"
   },
   {
      "manager_Name":"RAJIYUNG Sun",
      "Teams":"hansing",
      "Player_1":"Alisson 7",
      "Player_2":"Chilwell MUN (H)",
      "Player_3":"Duffy 0",
      "Player_4":"Alexander-Arnold 9",
      "Player_5":"Cancelo WHU (H)",
      "Player_6":"Salah 12$ captain",
      "Player_7":"Son BUR (A)",
      "Player_8":"Gallagher 2",
      "Player_9":"Smith Rowe 3",
      "Player_10":"Dennis LEI (A)",
      "Player_11":"Vardy WAT (H)",
      "Player_12":"Steer 0",
      "Player_13":"Antonio MCI (A)",
      "Player_14":"Livramento 0",
      "Player_15":"McArthur 0",
      "SXL":"33",
      "Bench":"698",
      "Count  ":"1,142,945"
   },
   {
      "manager_Name":"Ashish Rai",
      "Teams":"Deadhead",
      "Player_1":"Krul 6",
      "Player_2":"Cancelo WHU (H)",
      "Player_3":"James MUN (H)",
      "Player_4":"Castagne WAT (H)",
      "Player_5":"Smith Rowe 3",
      "Player_6":"Gallagher 2",
      "Player_7":"Son BUR (A)",
      "Player_8":"Salah 12$ captain",
      "Player_9":"Bernardo WHU (H)",
      "Player_10":"Rodrigo 2",
      "Player_11":"Ronaldo CHE (A)",
      "Player_12":"Foster LEI (A)",
      "Player_13":"Omobamidele 0",
      "Player_14":"Livramento 0",
      "Player_15":"Scarlett BUR (A)",
      "SXL":"25",
      "Bench":"758",
      "Count  ":"277,771"
   },
   {
      "manager_Name":"prabin kumar",
      "Teams":"Prabin Singh",
      "Player_1":"Mendy MUN (H)",
      "Player_2":"Rüdiger MUN (H)",
      "Player_3":"Alonso MUN (H)",
      "Player_4":"Dias WHU (H)",
      "Player_5":"Benrahma MCI (A)",
      "Player_6":"Greenwood CHE (A)",
      "Player_7":"Townsend BRE (A)",
      "Player_8":"Son BUR (A)",
      "Player_9":"Jiménez 2",
      "Player_10":"Antonio MCI (A)",
      "Player_11":"Aubameyang 2$ captain",
      "Player_12":"Foster LEI (A)",
      "Player_13":"Shaw CHE (A)",
      "Player_14":"Tsimikas 0",
      "Player_15":"Bissouma 2",
      "SXL":"4",
      "Bench":"571",
      "Count  ":"4,380,711"
   },
   {
      "manager_Name":"Ravish Verma",
      "Teams":"Marijuana Fields FC",
      "Player_1":"Guaita 1",
      "Player_2":"Alexander-Arnold 9",
      "Player_3":"James MUN (H)",
      "Player_4":"Cancelo WHU (H)",
      "Player_5":"White 6",
      "Player_6":"Salah 12$ captain",
      "Player_7":"Son BUR (A)",
      "Player_8":"Gallagher 2",
      "Player_9":"Hwang 2",
      "Player_10":"Toney EVE (H)",
      "Player_11":"Kane BUR (A)",
      "Player_12":"Foster LEI (A)",
      "Player_13":"Mbeumo EVE (H)",
      "Player_14":"Livramento 0",
      "Player_15":"Brownhill TOT (H)",
      "SXL":"32",
      "Bench":"741",
      "Count  ":"442,912"
   },
   {
      "manager_Name":"Prayash Thapa",
      "Teams":"abcde FC",
      "Player_1":"Ramsdale 7",
      "Player_2":"Alexander-Arnold 9",
      "Player_3":"Cancelo WHU (H)",
      "Player_4":"James MUN (H)",
      "Player_5":"Rüdiger MUN (H)",
      "Player_6":"Raphinha 3",
      "Player_7":"Saka 8",
      "Player_8":"Salah 12$ captain",
      "Player_9":"Jiménez 2",
      "Player_10":"Toney EVE (H)",
      "Player_11":"Kane BUR (A)",
      "Player_12":"Foster LEI (A)",
      "Player_13":"Mbeumo EVE (H)",
      "Player_14":"Douglas Luiz 0",
      "Player_15":"Livramento 0",
      "SXL":"41",
      "Bench":"788",
      "Count  ":"92,588"
   },
   {
      "manager_Name":"Tenzing Ninjey",
      "Teams":"One Step Beyond 026*",
      "Player_1":"Sánchez 8",
      "Player_2":"Cancelo WHU (H)",
      "Player_3":"Alexander-Arnold 9",
      "Player_4":"Rüdiger MUN (H)",
      "Player_5":"Salah 12$ captain",
      "Player_6":"Foden WHU (H)",
      "Player_7":"Mbeumo EVE (H)",
      "Player_8":"Jota 14",
      "Player_9":"Antonio MCI (A)",
      "Player_10":"Kane BUR (A)",
      "Player_11":"Dennis LEI (A)",
      "Player_12":"Foster LEI (A)",
      "Player_13":"Gilmour 2",
      "Player_14":"Livramento 0",
      "Player_15":"Marçal 0",
      "SXL":"43",
      "Bench":"728",
      "Count  ":"615,912"
   },
   {
      "manager_Name":"Harsh Raval",
      "Teams":"Up the Bees",
      "Player_1":"Guaita 1",
      "Player_2":"Emerson Royal BUR (A)",
      "Player_3":"Cancelo WHU (H)",
      "Player_4":"James MUN (H)",
      "Player_5":"Alexander-Arnold 9",
      "Player_6":"Son BUR (A)",
      "Player_7":"Gallagher 2",
      "Player_8":"Salah 12$ captain",
      "Player_9":"Jota 14",
      "Player_10":"Kane BUR (A)",
      "Player_11":"Hwang 2",
      "Player_12":"Foster LEI (A)",
      "Player_13":"Normann 1",
      "Player_14":"Omobamidele 0",
      "Player_15":"Davis 0",
      "SXL":"40",
      "Bench":"770",
      "Count  ":"185,580"
   },
   {
      "manager_Name":"PRAYAS BAJGAI",
      "Teams":"MCFC@1894",
      "Player_1":"Ramsdale 7",
      "Player_2":"Cancelo WHU (H)",
      "Player_3":"Alexander-Arnold 9",
      "Player_4":"James MUN (H)",
      "Player_5":"Foden WHU (H)",
      "Player_6":"Salah 12$ captain",
      "Player_7":"Jota 14",
      "Player_8":"Gallagher 2",
      "Player_9":"Dennis LEI (A)",
      "Player_10":"Toney EVE (H)",
      "Player_11":"Ronaldo CHE (A)",
      "Player_12":"Foster LEI (A)",
      "Player_13":"Williams 7",
      "Player_14":"Brownhill TOT (H)",
      "Player_15":"Livramento 0",
      "SXL":"44",
      "Bench":"770",
      "Count  ":"188,689"
   },
   {
      "manager_Name":"AVIJIT DAS",
      "Teams":"Roing FC",
      "Player_1":"Ramsdale 7",
      "Player_2":"Cancelo WHU (H)",
      "Player_3":"James MUN (H)",
      "Player_4":"Alexander-Arnold 9",
      "Player_5":"Dier BUR (A)",
      "Player_6":"Raphinha 3",
      "Player_7":"Jota 14",
      "Player_8":"Salah 12$ captain",
      "Player_9":"Mbeumo EVE (H)",
      "Player_10":"Kane BUR (A)",
      "Player_11":"Hwang 2",
      "Player_12":"Foster LEI (A)",
      "Player_13":"Antonio MCI (A)",
      "Player_14":"Livramento 0",
      "Player_15":"Brownhill TOT (H)",
      "SXL":"47",
      "Bench":"741",
      "Count  ":"447,780"
   },
   {
      "manager_Name":"Abhijeet Singh",
      "Teams":"WEIGHTLOSS COACH",
      "Player_1":"Ramsdale 7",
      "Player_2":"Alexander-Arnold 9",
      "Player_3":"James MUN (H)",
      "Player_4":"Cancelo WHU (H)",
      "Player_5":"Dias WHU (H)",
      "Player_6":"Smith Rowe 3",
      "Player_7":"Salah 12$ captain",
      "Player_8":"Gallagher 2",
      "Player_9":"Bernardo WHU (H)",
      "Player_10":"Vardy WAT (H)",
      "Player_11":"Jiménez 2",
      "Player_12":"Foster LEI (A)",
      "Player_13":"Antonio MCI (A)",
      "Player_14":"Manquillo 0",
      "Player_15":"Brownhill TOT (H)",
      "SXL":"35",
      "Bench":"754",
      "Count  ":"308,998"
   },
   {
      "manager_Name":"SATYAM RAI",
      "Teams":"PINE",
      "Player_1":"Ramsdale 7",
      "Player_2":"Cancelo WHU (H)",
      "Player_3":"James MUN (H)",
      "Player_4":"Alexander-Arnold 9",
      "Player_5":"Gallagher 2",
      "Player_6":"Mbeumo EVE (H)",
      "Player_7":"Salah 12$ captain",
      "Player_8":"Jota 14",
      "Player_9":"Kane BUR (A)",
      "Player_10":"Hwang 2",
      "Player_11":"Antonio MCI (A)",
      "Player_12":"Foster LEI (A)",
      "Player_13":"White 6",
      "Player_14":"Brownhill TOT (H)",
      "Player_15":"Livramento 0",
      "SXL":"46",
      "Bench":"781",
      "Count  ":"124,577"
   }
]