var s =[{
	"manager_Name": "Nishant Singh",
	"Teams": "beta 11",
	"Player_1": "McCarthy 6",
	"Player_2": "Zouma 2",
	"Player_3": "Mings ARS (A)",
	"Player_4": "Mitchell 0",
	"Player_5": "Grealish ARS (A)",
	"Player_6": "Salah MCI (A)",
	"Player_7": "Son WBA (A)$ captain",
	"Player_8": "Zaha 5",
	"Player_9": "Kane WBA (A)",
	"Player_10": "Calvert-Lewin 5",
	"Player_11": "Jiménez LEI (A)",
	"Player_12": "Martínez ARS (A)",
	"Player_13": "Saïss LEI (A)",
	"Player_14": "Alzate 0",
	"Player_15": "Douglas 0",
	"SXL": "18",
	"Bench": "0",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "Rohan Rai",
	"Teams": "FALSE 9",
	"Player_1": "Ryan 6",
	"Player_2": "Coufal 8",
	"Player_3": "Justin WOL (H)",
	"Player_4": "Kilman LEI (A)",
	"Player_5": "Sterling LIV (H)",
	"Player_6": "Salah MCI (A)",
	"Player_7": "Ziyech 11",
	"Player_8": "Podence LEI (A)",
	"Player_9": "Son WBA (A)",
	"Player_10": "Calvert-Lewin 5",
	"Player_11": "Kane WBA (A)$ captain",
	"Player_12": "Martínez ARS (A)",
	"Player_13": "Taylor 8",
	"Player_14": "Dunne 0",
	"Player_15": "Davis ARS (A)",
	"SXL": "30",
	"Bench": "8",
	"Count  ": "5( 4+1 )"
}, {
	"manager_Name": "Avijit Das",
	"Teams": "WeAreTheArsenal",
	"Player_1": "Martínez ARS (A)",
	"Player_2": "Chilwell 8",
	"Player_3": "Saïss LEI (A)",
	"Player_4": "Walker-Peters 9",
	"Player_5": "Zaha 5",
	"Player_6": "Son WBA (A)",
	"Player_7": "Salah MCI (A)",
	"Player_8": "Sterling LIV (H)",
	"Player_9": "Bamford 7",
	"Player_10": "Calvert-Lewin 5",
	"Player_11": "Kane WBA (A)$ captain",
	"Player_12": "Steer ARS (A)",
	"Player_13": "Ayling 0",
	"Player_14": "Mitchell 0",
	"Player_15": "Bissouma 2",
	"SXL": "34",
	"Bench": "2",
	"Count  ": "5( 5+0 )"
}, {
	"manager_Name": "Gaurav Shrestha",
	"Teams": "Fußball-Mannschaft",
	"Player_1": "Martínez ARS (A)",
	"Player_2": "Lamptey 6",
	"Player_3": "Zouma 2",
	"Player_4": "Robertson MCI (A)",
	"Player_5": "Salah MCI (A)",
	"Player_6": "Grealish ARS (A)",
	"Player_7": "Son WBA (A)",
	"Player_8": "Rodríguez 2",
	"Player_9": "Kane WBA (A)$ captain",
	"Player_10": "Calvert-Lewin 5",
	"Player_11": "Maupay 2",
	"Player_12": "Forster 0",
	"Player_13": "Dallas 0",
	"Player_14": "Bissouma 2",
	"Player_15": "Mitchell 0",
	"SXL": "17",
	"Bench": "2",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "Dipen Thapa",
	"Teams": "Lokipower Reloaded",
	"Player_1": "McCarthy 6",
	"Player_2": "Mings ARS (A)",
	"Player_3": "Mitchell 0",
	"Player_4": "Gabriel AVL (H)",
	"Player_5": "Fernandes 17",
	"Player_6": "Costa -1",
	"Player_7": "Son WBA (A)",
	"Player_8": "Salah MCI (A)",
	"Player_9": "Calvert-Lewin 5",
	"Player_10": "Jiménez LEI (A)$ captain",
	"Player_11": "Maupay 2",
	"Player_12": "Martínez ARS (A)",
	"Player_13": "Rodríguez 2",
	"Player_14": "Taylor 8",
	"Player_15": "Dunne 0",
	"SXL": "29",
	"Bench": "10",
	"Count  ": "4( 3+1 )"
}, {
	"manager_Name": "Sibin _",
	"Teams": "FortunaDüsseldorfer",
	"Player_1": "Guaita 2",
	"Player_2": "Chilwell 8",
	"Player_3": "Alderweireld WBA (A)",
	"Player_4": "Azpilicueta 0",
	"Player_5": "Tierney AVL (H)",
	"Player_6": "Son WBA (A)$ captain",
	"Player_7": "Zaha 5",
	"Player_8": "Fernandes 17",
	"Player_9": "Kane WBA (A)",
	"Player_10": "Callum Robinson TOT (H)",
	"Player_11": "Bamford 7",
	"Player_12": "Ramsdale 2",
	"Player_13": "Keane 1",
	"Player_14": "Oriol Romeu 2",
	"Player_15": "McCarthy 1",
	"SXL": "39",
	"Bench": "6",
	"Count  ": "4( 4+0 )"
}, {
	"manager_Name": "Kushal Sahota",
	"Teams": "FC ASSASSINS",
	"Player_1": "Schmeichel WOL (H)",
	"Player_2": "Mitchell 0",
	"Player_3": "Aké LIV (H)",
	"Player_4": "Lamptey 6",
	"Player_5": "Saint-Maximin 2",
	"Player_6": "Son WBA (A)",
	"Player_7": "Ziyech 11",
	"Player_8": "Salah MCI (A)$ captain",
	"Player_9": "Calvert-Lewin 5",
	"Player_10": "Kane WBA (A)",
	"Player_11": "Werner 7",
	"Player_12": "Ryan 6",
	"Player_13": "Alioski 0",
	"Player_14": "Oriol Romeu 2",
	"Player_15": "Bernardo 0",
	"SXL": "31",
	"Bench": "8",
	"Count  ": "5( 4+1 )"
}, {
	"manager_Name": "SATYAM RAI",
	"Teams": "PINE",
	"Player_1": "McCarthy 6",
	"Player_2": "Robertson MCI (A)",
	"Player_3": "Justin WOL (H)",
	"Player_4": "Taylor 8",
	"Player_5": "Zouma 2",
	"Player_6": "Salah MCI (A)",
	"Player_7": "Son WBA (A)",
	"Player_8": "Sterling LIV (H)",
	"Player_9": "Wilson 2",
	"Player_10": "Mitrović 1",
	"Player_11": "Kane WBA (A)$ captain",
	"Player_12": "Steer ARS (A)",
	"Player_13": "Bissouma 2",
	"Player_14": "Branthwaite 0",
	"Player_15": "Gordon 0",
	"SXL": "19",
	"Bench": "2",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "ashim lama",
	"Teams": "⚔️FURY⚔️",
	"Player_1": "Martínez ARS (A)",
	"Player_2": "Justin WOL (H)",
	"Player_3": "Chilwell 8",
	"Player_4": "Walker-Peters 9",
	"Player_5": "De Bruyne LIV (H)",
	"Player_6": "Son WBA (A)",
	"Player_7": "Ziyech 11",
	"Player_8": "Barkley ARS (A)",
	"Player_9": "Werner 14$ captain",
	"Player_10": "Jiménez LEI (A)",
	"Player_11": "Calvert-Lewin 5",
	"Player_12": "Steer ARS (A)",
	"Player_13": "Alexander-Arnold MCI (A)",
	"Player_14": "Podence LEI (A)",
	"Player_15": "Mitchell 0",
	"SXL": "47",
	"Bench": "0",
	"Count  ": "5( 5+0 )"
}, {
	"manager_Name": "Indrajeet Singh",
	"Teams": "Kung fu Pandoos",
	"Player_1": "Meslier 1",
	"Player_2": "Dier WBA (A)",
	"Player_3": "Walker-Peters 9",
	"Player_4": "Zouma 2",
	"Player_5": "Son WBA (A)",
	"Player_6": "Pereira TOT (H)",
	"Player_7": "Salah MCI (A)",
	"Player_8": "Aubameyang AVL (H)",
	"Player_9": "Bamford 7",
	"Player_10": "Jiménez LEI (A)",
	"Player_11": "Kane WBA (A)$ captain",
	"Player_12": "Henderson 0",
	"Player_13": "Holding AVL (H)",
	"Player_14": "Mitchell 0",
	"Player_15": "Reed 2",
	"SXL": "19",
	"Bench": "2",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "Vivek Lama",
	"Teams": "JOJOs LFC",
	"Player_1": "Alisson MCI (A)",
	"Player_2": "Alexander-Arnold MCI (A)",
	"Player_3": "Saïss LEI (A)",
	"Player_4": "Walker-Peters 9",
	"Player_5": "Zaha 5",
	"Player_6": "Son WBA (A)",
	"Player_7": "Sterling LIV (H)",
	"Player_8": "Mané MCI (A)$ captain",
	"Player_9": "Saint-Maximin 2",
	"Player_10": "Mitrović 1",
	"Player_11": "Bamford 7",
	"Player_12": "Ryan 6",
	"Player_13": "Connolly 1",
	"Player_14": "Dunne 0",
	"Player_15": "Egan -1",
	"SXL": "24",
	"Bench": "6",
	"Count  ": "4( 3+1 )"
}, {
	"manager_Name": "Prabin Singh",
	"Teams": "Random XI",
	"Player_1": "Mendy 2",
	"Player_2": "Vestergaard 6",
	"Player_3": "Mitchell 0",
	"Player_4": "Justin WOL (H)",
	"Player_5": "Son WBA (A)",
	"Player_6": "Salah MCI (A)",
	"Player_7": "Costa -1",
	"Player_8": "Zaha 5",
	"Player_9": "Jiménez LEI (A)",
	"Player_10": "Calvert-Lewin 5",
	"Player_11": "Kane WBA (A)$ captain",
	"Player_12": "Macey AVL (H)",
	"Player_13": "Grealish ARS (A)",
	"Player_14": "Saïss LEI (A)",
	"Player_15": "Dunne 0",
	"SXL": "17",
	"Bench": "0",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "Kumar Anku",
	"Teams": "Galaxies Stars",
	"Player_1": "Mendy 2",
	"Player_2": "Bellerín AVL (H)",
	"Player_3": "Digne 1",
	"Player_4": "Kilman LEI (A)",
	"Player_5": "Lookman 0",
	"Player_6": "Sterling LIV (H)$ captain",
	"Player_7": "Son WBA (A)",
	"Player_8": "Salah MCI (A)",
	"Player_9": "Rashford 5",
	"Player_10": "Watkins ARS (A)",
	"Player_11": "Werner 7",
	"Player_12": "Forster 0",
	"Player_13": "Mitchell 0",
	"Player_14": "Targett ARS (A)",
	"Player_15": "Delap LIV (H)",
	"SXL": "15",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "Okdenri Longchari",
	"Teams": "Happy Williams",
	"Player_1": "McCarthy 6",
	"Player_2": "Coufal 8",
	"Player_3": "Lamptey 6",
	"Player_4": "Walker-Peters 9",
	"Player_5": "Salah MCI (A)",
	"Player_6": "Podence LEI (A)",
	"Player_7": "Fernandes 17",
	"Player_8": "Son WBA (A)$ captain",
	"Player_9": "Sterling LIV (H)",
	"Player_10": "Calvert-Lewin 5",
	"Player_11": "Wilson 2",
	"Player_12": "Martínez ARS (A)",
	"Player_13": "Mitrović 1",
	"Player_14": "Saïss LEI (A)",
	"Player_15": "Mitchell 0",
	"SXL": "53",
	"Bench": "1",
	"Count  ": "6( 6+0 )"
}, {
	"manager_Name": "Omkar Subba",
	"Teams": "Omk09",
	"Player_1": "McCarthy 6",
	"Player_2": "Saïss LEI (A)",
	"Player_3": "Zouma 2",
	"Player_4": "James 2",
	"Player_5": "Salah MCI (A)",
	"Player_6": "Rodríguez 2",
	"Player_7": "Ziyech 11",
	"Player_8": "Son WBA (A)$ captain",
	"Player_9": "Grealish ARS (A)",
	"Player_10": "Bamford 7",
	"Player_11": "Calvert-Lewin 5",
	"Player_12": "Nyland ARS (A)",
	"Player_13": "Jiménez LEI (A)",
	"Player_14": "Justin WOL (H)",
	"Player_15": "Mitchell 0",
	"SXL": "35",
	"Bench": "0",
	"Count  ": "4( 4+0 )"
}, {
	"manager_Name": "Abhijeet Singh",
	"Teams": "Impact Creators",
	"Player_1": "McCarthy 6",
	"Player_2": "Balbuena 6",
	"Player_3": "Zouma 2",
	"Player_4": "Vestergaard 6",
	"Player_5": "Ziyech 11",
	"Player_6": "Son WBA (A)",
	"Player_7": "De Bruyne LIV (H)",
	"Player_8": "Salah MCI (A)",
	"Player_9": "Calvert-Lewin 5",
	"Player_10": "Bamford 7",
	"Player_11": "Kane WBA (A)$ captain",
	"Player_12": "Martin 0",
	"Player_13": "Riedewald 2",
	"Player_14": "Phillips MCI (A)",
	"Player_15": "Kilman LEI (A)",
	"SXL": "43",
	"Bench": "2",
	"Count  ": "6( 6+0 )"
}, {
	"manager_Name": "Ashish Subba",
	"Teams": "GUSTAVOUS GUNNER",
	"Player_1": "Pickford 1",
	"Player_2": "Vestergaard 6",
	"Player_3": "Justin WOL (H)",
	"Player_4": "Alexander-Arnold MCI (A)",
	"Player_5": "Grealish ARS (A)",
	"Player_6": "Zaha 5",
	"Player_7": "Salah MCI (A)",
	"Player_8": "Son WBA (A)",
	"Player_9": "Klich 4",
	"Player_10": "Kane WBA (A)$ captain",
	"Player_11": "Werner 7",
	"Player_12": "Martínez ARS (A)",
	"Player_13": "Mitchell 0",
	"Player_14": "Dunne 0",
	"Player_15": "Davis ARS (A)",
	"SXL": "23",
	"Bench": "0",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "Nitesh Singh",
	"Teams": "Danapur United",
	"Player_1": "Martínez ARS (A)",
	"Player_2": "Saïss LEI (A)",
	"Player_3": "Chilwell 8",
	"Player_4": "Robertson MCI (A)",
	"Player_5": "Costa -1",
	"Player_6": "Zaha 5",
	"Player_7": "Son WBA (A)",
	"Player_8": "Salah MCI (A)",
	"Player_9": "Bamford 7",
	"Player_10": "Wilson 2",
	"Player_11": "Kane WBA (A)$ captain",
	"Player_12": "Ryan 6",
	"Player_13": "Struijk 0",
	"Player_14": "Harper TOT (H)",
	"Player_15": "Buur LEI (A)",
	"SXL": "21",
	"Bench": "6",
	"Count  ": "4( 3+1 )"
}, {
	"manager_Name": "Raj Kanango",
	"Teams": "Dream Killer",
	"Player_1": "Pope 9",
	"Player_2": "Alexander-Arnold MCI (A)",
	"Player_3": "Walker LIV (H)",
	"Player_4": "Justin WOL (H)",
	"Player_5": "Grealish ARS (A)",
	"Player_6": "Zaha 5",
	"Player_7": "Son WBA (A)$ captain",
	"Player_8": "Mané MCI (A)",
	"Player_9": "Wilson 2",
	"Player_10": "Maupay 2",
	"Player_11": "Vardy WOL (H)",
	"Player_12": "Johnstone TOT (H)",
	"Player_13": "Bardsley 0",
	"Player_14": "Oriol Romeu 2",
	"Player_15": "Branthwaite 0",
	"SXL": "18",
	"Bench": "2",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "Sahil Lampard",
	"Teams": "Marx 11",
	"Player_1": "Martínez ARS (A)",
	"Player_2": "Saïss LEI (A)",
	"Player_3": "Castagne WOL (H)",
	"Player_4": "Chilwell 8",
	"Player_5": "Rodríguez 2",
	"Player_6": "Grealish ARS (A)",
	"Player_7": "Son WBA (A)",
	"Player_8": "Salah MCI (A)",
	"Player_9": "Oriol Romeu 2",
	"Player_10": "Calvert-Lewin 5",
	"Player_11": "Kane WBA (A)$ captain",
	"Player_12": "Ryan 6",
	"Player_13": "Bertrand 0",
	"Player_14": "Delap LIV (H)",
	"Player_15": "Casey 0",
	"SXL": "17",
	"Bench": "6",
	"Count  ": "3( 2+1 )"
}, {
	"manager_Name": "Pema Sherpa",
	"Teams": "CottonMouth XI",
	"Player_1": "Martínez ARS (A)",
	"Player_2": "Saïss LEI (A)",
	"Player_3": "Chilwell 8",
	"Player_4": "Dunne 0",
	"Player_5": "Son WBA (A)$ captain",
	"Player_6": "Salah MCI (A)",
	"Player_7": "Foden LIV (H)",
	"Player_8": "Zaha 5",
	"Player_9": "Bamford 7",
	"Player_10": "Kane WBA (A)",
	"Player_11": "Calvert-Lewin 5",
	"Player_12": "Button TOT (H)",
	"Player_13": "Mitchell 0",
	"Player_14": "Castagne WOL (H)",
	"Player_15": "Phillips 0",
	"SXL": "25",
	"Bench": "0",
	"Count  ": "4( 4+0 )"
}, {
	"manager_Name": "pranam rai",
	"Teams": "SYAKREE F.C.",
	"Player_1": "Martínez ARS (A)",
	"Player_2": "Lamptey 6",
	"Player_3": "Kilman LEI (A)",
	"Player_4": "James 2",
	"Player_5": "Saint-Maximin 2",
	"Player_6": "Salah MCI (A)",
	"Player_7": "Rodríguez 2",
	"Player_8": "Son WBA (A)",
	"Player_9": "Werner 14$ captain",
	"Player_10": "Bamford 7",
	"Player_11": "Calvert-Lewin 5",
	"Player_12": "Guaita 2",
	"Player_13": "Robertson MCI (A)",
	"Player_14": "Castagne WOL (H)",
	"Player_15": "Foden LIV (H)",
	"SXL": "38",
	"Bench": "2",
	"Count  ": "4( 4+0 )"
}, {
	"manager_Name": "Regean Lama",
	"Teams": "Busby Baby",
	"Player_1": "McCarthy 6",
	"Player_2": "Taylor 8",
	"Player_3": "Alexander-Arnold MCI (A)",
	"Player_4": "Justin WOL (H)",
	"Player_5": "Salah MCI (A)",
	"Player_6": "Son WBA (A)",
	"Player_7": "Rodríguez 2",
	"Player_8": "Rashford 5",
	"Player_9": "Podence LEI (A)",
	"Player_10": "Mitrović 1",
	"Player_11": "Kane WBA (A)$ captain",
	"Player_12": "Steer ARS (A)",
	"Player_13": "Brewster 2",
	"Player_14": "Walker-Peters 9",
	"Player_15": "Douglas 0",
	"SXL": "22",
	"Bench": "11",
	"Count  ": "4( 3+1 )"
}, {
	"manager_Name": "Han Sing",
	"Teams": "hansing",
	"Player_1": "Martínez ARS (A)",
	"Player_2": "Vestergaard 6",
	"Player_3": "Zouma 2",
	"Player_4": "Chilwell 8",
	"Player_5": "Zaha 5",
	"Player_6": "Salah MCI (A)",
	"Player_7": "Fernandes 17",
	"Player_8": "Son WBA (A)",
	"Player_9": "Calvert-Lewin 5",
	"Player_10": "Bamford 7",
	"Player_11": "Kane WBA (A)$ captain",
	"Player_12": "Nyland ARS (A)",
	"Player_13": "Saïss LEI (A)",
	"Player_14": "Mitchell 0",
	"Player_15": "Anguissa 2",
	"SXL": "50",
	"Bench": "2",
	"Count  ": "6( 6+0 )"
}, {
	"manager_Name": "Sanjeev Kumar",
	"Teams": "mendal11",
	"Player_1": "Mendy 2",
	"Player_2": "Targett ARS (A)",
	"Player_3": "James 2",
	"Player_4": "Coufal 8",
	"Player_5": "Zaha 5",
	"Player_6": "Jorginho 1",
	"Player_7": "Salah MCI (A)",
	"Player_8": "Son WBA (A)",
	"Player_9": "Kane WBA (A)$ captain",
	"Player_10": "Maupay 2",
	"Player_11": "Jiménez LEI (A)",
	"Player_12": "Steer ARS (A)",
	"Player_13": "Barnes WOL (H)",
	"Player_14": "Mitchell 0",
	"Player_15": "Justin WOL (H)",
	"SXL": "20",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "Ashish Rai",
	"Teams": "goooooooners",
	"Player_1": "Ryan 6",
	"Player_2": "Coady LEI (A)",
	"Player_3": "Dallas 0",
	"Player_4": "Bednarek 6",
	"Player_5": "Bowen 3",
	"Player_6": "Salah MCI (A)",
	"Player_7": "Aubameyang AVL (H)",
	"Player_8": "Zaha 5",
	"Player_9": "Werner 14$ captain",
	"Player_10": "Watkins ARS (A)",
	"Player_11": "Kane WBA (A)",
	"Player_12": "Nyland ARS (A)",
	"Player_13": "Oriol Romeu 2",
	"Player_14": "Lascelles 1",
	"Player_15": "Branthwaite 0",
	"SXL": "34",
	"Bench": "3",
	"Count  ": "4( 4+0 )"
}, {
	"manager_Name": "Ravish Verma",
	"Teams": "Jatt Da Muqaabla FC",
	"Player_1": "Martínez ARS (A)",
	"Player_2": "Bellerín AVL (H)",
	"Player_3": "Justin WOL (H)",
	"Player_4": "Walker-Peters 9",
	"Player_5": "Son WBA (A)",
	"Player_6": "Grealish ARS (A)",
	"Player_7": "Zaha 5",
	"Player_8": "Salah MCI (A)",
	"Player_9": "Calvert-Lewin 5",
	"Player_10": "Maupay 2",
	"Player_11": "Kane WBA (A)$ captain",
	"Player_12": "Steer ARS (A)",
	"Player_13": "Reed 2",
	"Player_14": "Mitchell 0",
	"Player_15": "Douglas 0",
	"SXL": "21",
	"Bench": "2",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "Bishal Rai",
	"Teams": "Gooner for Life",
	"Player_1": "Ryan 6",
	"Player_2": "Lamptey 6",
	"Player_3": "Chilwell 8",
	"Player_4": "Justin WOL (H)",
	"Player_5": "Grealish ARS (A)",
	"Player_6": "Salah MCI (A)",
	"Player_7": "Son WBA (A)",
	"Player_8": "Zaha 5",
	"Player_9": "Kane WBA (A)$ captain",
	"Player_10": "Bamford 7",
	"Player_11": "Calvert-Lewin 5",
	"Player_12": "Martínez ARS (A)",
	"Player_13": "Alexander-Arnold MCI (A)",
	"Player_14": "McCarthy 1",
	"Player_15": "Branthwaite 0",
	"SXL": "37",
	"Bench": "1",
	"Count  ": "6( 6+0 )"
}]