var s = [
  {
    "manager_Name": "2,132( 11,055 ) TotalXfr : 28",
    "Teams": "The Bees( Tove Ronneb\u00E4ck )",
    "SXL": "countryCode",
    "Latp": "45",
    "Player_1": "Raya 2",
    "Player_11": "Isak 8",
    "Player_10": "Watkins 0",
    "Player_12": "Fabianski 0",
    "Player_13": "J.Murphy 5",
    "Player_14": "Mykolenko 2",
    "Player_7": "Trossard 1",
    "Player_2": "Gvardiol 6",
    "Player_5": "Mbeumo 8",
    "Player_6": "M.Salah 6",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Gabriel 1",
    "Player_8": "Bowen 2",
    "Player_9": "Marmoush 9",
    "Player_15": "Harwood-Bellis 2"
  },
  {
    "manager_Name": "2,115( 21,263 ) TotalXfr : 29",
    "Teams": "Lorrainesson( Lorraine Busuttil )",
    "SXL": "countryCode",
    "Latp": "55",
    "Player_1": "Raya 2",
    "Player_11": "Marmoush 9",
    "Player_10": "Mateta 1",
    "Player_12": "Areola 2",
    "Player_13": "Gordon 0",
    "Player_14": "Burn 2",
    "Player_7": "I.Sarr 2",
    "Player_2": "Gabriel 1",
    "Player_5": "M.Salah 6",
    "Player_6": "Saka 8",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Gvardiol 6",
    "Player_8": "Rogers 10",
    "Player_9": "Isak 8",
    "Player_15": "Konsa 6"
  },
  {
    "manager_Name": "2,094( 43,041 ) TotalXfr : 28",
    "Teams": "Los Blancos( Eamonn Mifsud )",
    "SXL": "countryCode",
    "Latp": "54",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 1",
    "Player_10": "Marmoush 9",
    "Player_12": "Martinez 6",
    "Player_13": "J.Murphy 5",
    "Player_14": "Livramento 2",
    "Player_7": "I.Sarr 2",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "M.Salah 6",
    "Player_6": "Saka 8",
    "Player_3": "Gvardiol 6",
    "Player_4": "Gabriel 1",
    "Player_8": "Savinho 9",
    "Player_9": "Isak 8",
    "Player_15": "Konsa 6"
  },
  {
    "manager_Name": "2,053( 138,090 ) TotalXfr : 28",
    "Teams": "FC Pek( Erik Lindberg )",
    "SXL": "countryCode",
    "Latp": "43",
    "Player_1": "Raya 2",
    "Player_11": "Marmoush 9",
    "Player_10": "Isak 8",
    "Player_12": "Arrizabalaga 1",
    "Player_13": "Kluivert 0",
    "Player_14": "Rogers 10",
    "Player_7": "Bowen 2",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "Kerkez 1",
    "Player_6": "M.Salah 6",
    "Player_3": "Gabriel 1",
    "Player_4": "Gvardiol 6",
    "Player_8": "J.Murphy 5",
    "Player_9": "Mateta 1",
    "Player_15": "Livramento 2"
  },
  {
    "manager_Name": "2,019( 296,763 ) TotalXfr : 27",
    "Teams": "Udogie\u0027s Doggies( Claude Taliana )",
    "SXL": "countryCode",
    "Latp": "29",
    "Player_1": "Flekken 1",
    "Player_11": "Watkins 0",
    "Player_10": "M.Salah 6",
    "Player_12": "Fabianski 0",
    "Player_13": "Foden 0",
    "Player_14": "Wood 0",
    "Player_7": "Semenyo 2",
    "Player_2": "J.Timber 7",
    "Player_5": "Aina 1",
    "Player_6": "Robinson 1",
    "Player_3": "Gu\u00E9hi 2",
    "Player_4": "Kerkez 1",
    "Player_8": "Mitoma 2",
    "Player_9": "Palmer 6",
    "Player_15": "Cunha 0"
  },
  {
    "manager_Name": "2,004( 398,483 ) TotalXfr : 28",
    "Teams": "FC Qvantas( Johan Hammarstrom )",
    "SXL": "countryCode",
    "Latp": "48",
    "Player_1": "Pickford 3",
    "Player_11": "Isak 8",
    "Player_10": "Marmoush 9",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Wood 0",
    "Player_14": "Kluivert 0",
    "Player_7": "M.Salah 6",
    "Player_2": "Gabriel 1",
    "Player_5": "Mu\u00F1oz 2",
    "Player_6": "Milenkovi\u0107 6",
    "Player_3": "Saliba 2",
    "Player_4": "Aina 1",
    "Player_8": "I.Sarr 2",
    "Player_9": "Mbeumo 8",
    "Player_15": "Bowen 2"
  },
  {
    "manager_Name": "1,999( 438,761 ) TotalXfr : 30",
    "Teams": "NoHopeFC( John Maguire )",
    "SXL": "countryCode",
    "Latp": "40",
    "Player_1": "Henderson 2",
    "Player_11": "Watkins 0",
    "Player_10": "Isak 8",
    "Player_12": "Turner 0",
    "Player_13": "Minteh 0",
    "Player_14": "Wood 0",
    "Player_7": "Gibbs-White 3",
    "Player_2": "Wan-Bissaka 2",
    "Player_5": "Trippier 2",
    "Player_6": "Bruno G. 2",
    "Player_3": "Robinson 1",
    "Player_4": "Konat\u00E9 6",
    "Player_8": "M.Salah 6",
    "Player_9": "Mbeumo 8",
    "Player_15": "Van den Berg 1"
  },
  {
    "manager_Name": "1,995( 470,027 ) TotalXfr : 29",
    "Teams": "Lallish United( Melwin Holst )",
    "SXL": "countryCode",
    "Latp": "54",
    "Player_1": "Raya 2",
    "Player_11": "Marmoush 9",
    "Player_10": "Mateta 1",
    "Player_12": "Martinez 6",
    "Player_13": "J.Murphy 5",
    "Player_14": "Burn 2",
    "Player_7": "M.Salah 6",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "Savinho 9",
    "Player_6": "Eze 2",
    "Player_3": "Gabriel 1",
    "Player_4": "Gvardiol 6",
    "Player_8": "Saka 8",
    "Player_9": "Isak 8",
    "Player_15": "Wan-Bissaka 2"
  },
  {
    "manager_Name": "1,991( 506,247 ) TotalXfr : 32",
    "Teams": "Joga Bonito( Christophe Peixoto )",
    "SXL": "countryCode",
    "Latp": "62",
    "Player_1": "Sels 8",
    "Player_11": "Evanilson 8",
    "Player_10": "Isak 8",
    "Player_12": "Areola 2",
    "Player_13": "Kluivert 0",
    "Player_14": "Foden 0",
    "Player_7": "Barnes 5",
    "Player_2": "Gvardiol 6",
    "Player_5": "Gabriel 1",
    "Player_6": "I.Sarr 2",
    "Player_3": "Kerkez 1",
    "Player_4": "Mu\u00F1oz 2",
    "Player_8": "M.Salah 3",
    "Player_9": "Marmoush 18",
    "Player_15": "Livramento 2"
  },
  {
    "manager_Name": "1,975( 652,625 ) TotalXfr : 26",
    "Teams": "JDT Out( Filip Larsson )",
    "SXL": "countryCode",
    "Latp": "60",
    "Player_1": "Raya 2",
    "Player_11": "Isak 8",
    "Player_10": "Marmoush 9",
    "Player_12": "Fabianski 0",
    "Player_13": "Mateta 1",
    "Player_14": "Burn 2",
    "Player_7": "M.Salah 6",
    "Player_2": "Gabriel 1",
    "Player_5": "I.Sarr 2",
    "Player_6": "Saka 8",
    "Player_3": "Gvardiol 6",
    "Player_4": "Mu\u00F1oz 2",
    "Player_8": "J.Murphy 5",
    "Player_9": "Elanga 11",
    "Player_15": "N.Williams 5"
  },
  {
    "manager_Name": "1,974( 663,217 ) TotalXfr : 27",
    "Teams": "Kinder Mbeumo( Gerson Seguna )",
    "SXL": "countryCode",
    "Latp": "45",
    "Player_1": "Raya 2",
    "Player_11": "Isak 8",
    "Player_10": "Marmoush 9",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Milenkovi\u0107 6",
    "Player_14": "Huijsen 0",
    "Player_7": "I.Sarr 2",
    "Player_2": "Gabriel 1",
    "Player_5": "Semenyo 2",
    "Player_6": "M.Salah 6",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Gvardiol 6",
    "Player_8": "Palmer 6",
    "Player_9": "Mateta 1",
    "Player_15": "J.Murphy 5"
  },
  {
    "manager_Name": "1,959( 834,792 ) TotalXfr : 34",
    "Teams": "Im Sorry Nic Jackson( Jon Briscoe White )",
    "SXL": "countryCode",
    "Latp": "51",
    "Player_1": "Sels 8",
    "Player_11": "Watkins 0",
    "Player_10": "Isak 8",
    "Player_12": "Flekken 1",
    "Player_13": "Gabriel 1",
    "Player_14": "Bruno G. 2",
    "Player_7": "M.Salah 6",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "Szoboszlai 3",
    "Player_6": "Semenyo 2",
    "Player_3": "Burn 2",
    "Player_4": "Kerkez 1",
    "Player_8": "Rogers 10",
    "Player_9": "Marmoush 9",
    "Player_15": "Aina 1"
  },
  {
    "manager_Name": "1,952( 921,245 ) TotalXfr : 36",
    "Teams": "Biancoverde Utd 4.0( Michael Keramas )",
    "SXL": "countryCode",
    "Latp": "61",
    "Player_1": "Sels 8",
    "Player_11": "Wissa 5",
    "Player_10": "Isak 8",
    "Player_12": "Fabianski 0",
    "Player_13": "Kluivert 0",
    "Player_14": "A.Doucoure 2",
    "Player_7": "M.Salah 3",
    "Player_2": "Milenkovi\u0107 6",
    "Player_5": "Livramento 2",
    "Player_6": "Palmer 6",
    "Player_3": "Robinson 1",
    "Player_4": "Mu\u00F1oz 2",
    "Player_8": "I.Sarr 2",
    "Player_9": "Marmoush 18",
    "Player_15": "Hall 0"
  },
  {
    "manager_Name": "1,935( 1,140,511 ) TotalXfr : 29",
    "Teams": "Ajax CT( Dimitrios Siderakis )",
    "SXL": "countryCode",
    "Latp": "73",
    "Player_1": "Sels 8",
    "Player_11": "Marmoush 9",
    "Player_10": "Isak 8",
    "Player_12": "S\u00E1nchez 6",
    "Player_13": "Kluivert 0",
    "Player_14": "Wissa 5",
    "Player_7": "M.Salah 6",
    "Player_2": "Kerkez 1",
    "Player_5": "Milenkovi\u0107 6",
    "Player_6": "Murillo 9",
    "Player_3": "Konat\u00E9 6",
    "Player_4": "Gvardiol 6",
    "Player_8": "Palmer 6",
    "Player_9": "Mbeumo 8",
    "Player_15": "Dibling 1"
  },
  {
    "manager_Name": "1,934( 1,151,585 ) TotalXfr : 26",
    "Teams": "Blue Core( Avinash Chatlani )",
    "SXL": "countryCode",
    "Latp": "51",
    "Player_1": "Jos\u00E9 S\u00E1 5",
    "Player_11": "Jo\u00E3o Pedro 2",
    "Player_10": "Wissa 5",
    "Player_12": "Pickford 3",
    "Player_13": "Enzo 11",
    "Player_14": "Mykolenko 2",
    "Player_7": "Mbeumo 8",
    "Player_2": "Kerkez 1",
    "Player_5": "M.Salah 6",
    "Player_6": "Palmer 6",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Gvardiol 6",
    "Player_8": "Bowen 2",
    "Player_9": "Isak 8",
    "Player_15": "A\u00EFt-Nouri 8"
  },
  {
    "manager_Name": "1,924( 1,301,473 ) TotalXfr : 30",
    "Teams": "Tourinho FC( Alexis Touris )",
    "SXL": "countryCode",
    "Latp": "51",
    "Player_1": "Ederson M. 6",
    "Player_11": "Isak 8",
    "Player_10": "Ra\u00FAl 2",
    "Player_12": "S\u00E1nchez 6",
    "Player_13": "Kluivert 0",
    "Player_14": "Wood 0",
    "Player_7": "Palmer 12",
    "Player_2": "Pedro Porro 0",
    "Player_5": "Huijsen 0",
    "Player_6": "Semenyo 2",
    "Player_3": "Aina 1",
    "Player_4": "Murillo 9",
    "Player_8": "Mbeumo 8",
    "Player_9": "M.Salah 3",
    "Player_15": "Andersen 0"
  },
  {
    "manager_Name": "1,920( 1,360,184 ) TotalXfr : 29",
    "Teams": "HUNdorito( Adam Rajki )",
    "SXL": "countryCode",
    "Latp": "42",
    "Player_1": "Raya 2",
    "Player_11": "Jo\u00E3o Pedro 2",
    "Player_10": "Isak 8",
    "Player_12": "Henderson 2",
    "Player_13": "Wood 0",
    "Player_14": "Kluivert 0",
    "Player_7": "B.Fernandes 2",
    "Player_2": "Burn 2",
    "Player_5": "Kerkez 1",
    "Player_6": "Milenkovi\u0107 6",
    "Player_3": "Virgil 8",
    "Player_4": "Saliba 2",
    "Player_8": "M.Salah 6",
    "Player_9": "Szoboszlai 3",
    "Player_15": "Gibbs-White 3"
  },
  {
    "manager_Name": "1,908( 1,547,215 ) TotalXfr : 28",
    "Teams": "Fantasikonungen( Albin Jonsson )",
    "SXL": "countryCode",
    "Latp": "46",
    "Player_1": "Areola 2",
    "Player_11": "Mateta 1",
    "Player_10": "Isak 8",
    "Player_12": "J\u00F8rgensen 0",
    "Player_13": "Kluivert 0",
    "Player_14": "Disasi 0",
    "Player_7": "Szoboszlai 3",
    "Player_2": "Konat\u00E9 6",
    "Player_5": "Livramento 2",
    "Player_6": "M.Salah 6",
    "Player_3": "Cucurella 5",
    "Player_4": "Mu\u00F1oz 2",
    "Player_8": "I.Sarr 2",
    "Player_9": "Marmoush 9",
    "Player_15": "Bergvall 2"
  },
  {
    "manager_Name": "1,907( 1,563,600 ) TotalXfr : 28",
    "Teams": "Salahvation Army( Tom Atkinson )",
    "SXL": "countryCode",
    "Latp": "46",
    "Player_1": "Henderson 2",
    "Player_11": "Isak 8",
    "Player_10": "Watkins 0",
    "Player_12": "Martinez 6",
    "Player_13": "Kluivert 0",
    "Player_14": "Winks 0",
    "Player_7": "Eze 2",
    "Player_2": "Saliba 2",
    "Player_5": "Livramento 2",
    "Player_6": "Mbeumo 8",
    "Player_3": "Milenkovi\u0107 6",
    "Player_4": "Gabriel 1",
    "Player_8": "M.Salah 6",
    "Player_9": "Marmoush 9",
    "Player_15": "Bednarek 1"
  },
  {
    "manager_Name": "1,898( 1,715,315 ) TotalXfr : 30",
    "Teams": "ThereWeLand( Haykel Mansour )",
    "SXL": "countryCode",
    "Latp": "55",
    "Player_1": "Leno 2",
    "Player_11": "Marmoush 18",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "A.Becker 0",
    "Player_13": "Wissa 5",
    "Player_14": "Khusanov 0",
    "Player_7": "Son 2",
    "Player_2": "Virgil 8",
    "Player_5": "Semenyo 2",
    "Player_6": "Trossard 1",
    "Player_3": "J.Timber 7",
    "Player_4": "Wan-Bissaka 2",
    "Player_8": "Mbeumo 8",
    "Player_9": "M.Salah 3",
    "Player_15": "Kayode 0"
  },
  {
    "manager_Name": "1,897( 1,725,720 ) TotalXfr : 19",
    "Teams": "Matteo fc( Matteo Vella )",
    "SXL": "countryCode",
    "Latp": "52",
    "Player_1": "Leno 2",
    "Player_11": "Watkins 0",
    "Player_10": "Isak 8",
    "Player_12": "Fabianski 0",
    "Player_13": "Luis D\u00EDaz 9",
    "Player_14": "Hall 0",
    "Player_7": "Rogers 10",
    "Player_2": "Robinson 1",
    "Player_5": "Palmer 6",
    "Player_6": "Semenyo 2",
    "Player_3": "Milenkovi\u0107 6",
    "Player_4": "Konat\u00E9 6",
    "Player_8": "M.Salah 6",
    "Player_9": "Wissa 5",
    "Player_15": "Konsa 6"
  },
  {
    "manager_Name": "1,897( 1,730,596 ) TotalXfr : 29",
    "Teams": "20x MU( John Tiltmann )",
    "SXL": "countryCode",
    "Latp": "51",
    "Player_1": "Sels 8",
    "Player_11": "Ra\u00FAl 2",
    "Player_10": "Isak 8",
    "Player_12": "Flekken 1",
    "Player_13": "Wood 0",
    "Player_14": "Pedro Porro 0",
    "Player_7": "Bellegarde 3",
    "Player_2": "Virgil 8",
    "Player_5": "Robinson 1",
    "Player_6": "J.Murphy 5",
    "Player_3": "Kerkez 1",
    "Player_4": "Aina 1",
    "Player_8": "Mbeumo 8",
    "Player_9": "M.Salah 6",
    "Player_15": "Palmer 6"
  },
  {
    "manager_Name": "1,894( 1,785,879 ) TotalXfr : 33",
    "Teams": "\u0106umura\u0161i( Aleksandar Deletic )",
    "SXL": "countryCode",
    "Latp": "39",
    "Player_1": "Raya 2",
    "Player_11": "Isak 8",
    "Player_10": "Wissa 5",
    "Player_12": "S\u00E1nchez 6",
    "Player_13": "Wood 0",
    "Player_14": "Kluivert 0",
    "Player_7": "M.Salah 6",
    "Player_2": "Gabriel 1",
    "Player_5": "J.Timber 7",
    "Player_6": "Semenyo 2",
    "Player_3": "Gu\u00E9hi 2",
    "Player_4": "Kerkez 1",
    "Player_8": "Gibbs-White 3",
    "Player_9": "Eze 2",
    "Player_15": "Aina 1"
  },
  {
    "manager_Name": "1,893( 1,801,047 ) TotalXfr : 31",
    "Teams": "Starship( Olumide Okedusi )",
    "SXL": "countryCode",
    "Latp": "60",
    "Player_1": "Martinez 6",
    "Player_11": "Strand Larsen 9",
    "Player_10": "Marmoush 9",
    "Player_12": "Iraola 1",
    "Player_13": "Pickford 3",
    "Player_14": "Robinson 1",
    "Player_7": "M.Salah 6",
    "Player_2": "Virgil 8",
    "Player_5": "Eze 2",
    "Player_6": "B.Fernandes 2",
    "Player_3": "Aina 1",
    "Player_4": "Mu\u00F1oz 2",
    "Player_8": "Palmer 6",
    "Player_9": "Evanilson 8",
    "Player_15": "P.M.Sarr 0"
  },
  {
    "manager_Name": "1,882( 1,993,677 ) TotalXfr : 32",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "countryCode",
    "Latp": "54",
    "Player_1": "Henderson 2",
    "Player_11": "Watkins 0",
    "Player_10": "Isak 8",
    "Player_12": "Pickford 3",
    "Player_13": "Wood 0",
    "Player_14": "Kluivert 0",
    "Player_7": "Nwaneri 6",
    "Player_2": "Dalot 2",
    "Player_5": "Milenkovi\u0107 6",
    "Player_6": "Burn 2",
    "Player_3": "Konat\u00E9 6",
    "Player_4": "J.Timber 7",
    "Player_8": "M.Salah 3",
    "Player_9": "Palmer 12",
    "Player_15": "Iroegbunam 1"
  },
  {
    "manager_Name": "1,879( 2,042,954 ) TotalXfr : 29",
    "Teams": "Wan Utd( Mindaugas Grigaitis )",
    "SXL": "countryCode",
    "Latp": "49",
    "Player_1": "Raya 2",
    "Player_11": "Isak 8",
    "Player_10": "Marmoush 9",
    "Player_12": "Verbruggen 1",
    "Player_13": "Neto 2",
    "Player_14": "Chalobah 5",
    "Player_7": "Szoboszlai 3",
    "Player_2": "Kerkez 1",
    "Player_5": "I.Sarr 2",
    "Player_6": "M.Salah 6",
    "Player_3": "Saliba 2",
    "Player_4": "Gvardiol 6",
    "Player_8": "Semenyo 2",
    "Player_9": "Evanilson 8",
    "Player_15": "Pedro Porro 0"
  },
  {
    "manager_Name": "1,870( 2,204,886 ) TotalXfr : 29",
    "Teams": "MainooInTheBank( Thanasis Fouras )",
    "SXL": "countryCode",
    "Latp": "37",
    "Player_1": "Flekken 1",
    "Player_11": "Isak 8",
    "Player_10": "Ra\u00FAl 2",
    "Player_12": "Matthews 0",
    "Player_13": "Rogers 10",
    "Player_14": "Robinson 1",
    "Player_7": "Palmer 6",
    "Player_2": "Pedro Porro 0",
    "Player_5": "Semenyo 2",
    "Player_6": "Bowen 2",
    "Player_3": "A\u00EFt-Nouri 8",
    "Player_4": "Aina 1",
    "Player_8": "M.Salah 6",
    "Player_9": "Mateta 1",
    "Player_15": "Greaves 0"
  },
  {
    "manager_Name": "1,857( 2,440,819 ) TotalXfr : 27",
    "Teams": "Cursed Technique( Ini Etienam )",
    "SXL": "countryCode",
    "Latp": "48",
    "Player_1": "Pickford 3",
    "Player_11": "Watkins 0",
    "Player_10": "Isak 8",
    "Player_12": "Flekken 1",
    "Player_13": "Wood 0",
    "Player_14": "Kluivert 0",
    "Player_7": "Mbeumo 8",
    "Player_2": "Virgil 8",
    "Player_5": "Kerkez 1",
    "Player_6": "M.Salah 6",
    "Player_3": "Gu\u00E9hi 2",
    "Player_4": "Aina 1",
    "Player_8": "Luis D\u00EDaz 9",
    "Player_9": "Mitoma 2",
    "Player_15": "Hall 0"
  },
  {
    "manager_Name": "1,857( 2,447,082 ) TotalXfr : 32",
    "Teams": "Gidia KK( Aggelos Flamiatos )",
    "SXL": "countryCode",
    "Latp": "53",
    "Player_1": "Verbruggen 1",
    "Player_11": "Watkins 0",
    "Player_10": "Evanilson 16",
    "Player_12": "Flekken 1",
    "Player_13": "Murillo 9",
    "Player_14": "Ra\u00FAl 2",
    "Player_7": "Mbeumo 8",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "Palmer 6",
    "Player_6": "M.Salah 3",
    "Player_3": "Virgil 8",
    "Player_4": "Cucurella 5",
    "Player_8": "Neto 2",
    "Player_9": "I.Sarr 2",
    "Player_15": "Robinson 1"
  },
  {
    "manager_Name": "1,847( 2,636,208 ) TotalXfr : 36",
    "Teams": "LxFxC( Ervin Rigo )",
    "SXL": "countryCode",
    "Latp": "53",
    "Player_1": "Areola 2",
    "Player_11": "Marmoush 9",
    "Player_10": "Isak 8",
    "Player_12": "A.Becker 0",
    "Player_13": "Rogers 10",
    "Player_14": "Aina 1",
    "Player_7": "O.Dango 2",
    "Player_2": "Gvardiol 6",
    "Player_5": "A\u00EFt-Nouri 8",
    "Player_6": "Mbeumo 8",
    "Player_3": "Gabriel 1",
    "Player_4": "Kerkez 1",
    "Player_8": "M.Salah 6",
    "Player_9": "Son 2",
    "Player_15": "Cunha 0"
  },
  {
    "manager_Name": "1,846( 2,653,101 ) TotalXfr : 33",
    "Teams": "Guglielmo( Jonas Megert )",
    "SXL": "countryCode",
    "Latp": "43",
    "Player_1": "Flekken 1",
    "Player_11": "Wood 0",
    "Player_10": "Isak 8",
    "Player_12": "Turner 0",
    "Player_13": "Kluivert 0",
    "Player_14": "Keane 0",
    "Player_7": "M.Salah 6",
    "Player_2": "Murillo 9",
    "Player_5": "Rogers 10",
    "Player_6": "Damsgaard 1",
    "Player_3": "Alexander-Arnold 0",
    "Player_4": "Gabriel 1",
    "Player_8": "Palmer 6",
    "Player_9": "Gakpo 1",
    "Player_15": "Taylor 0"
  },
  {
    "manager_Name": "1,841( 2,741,546 ) TotalXfr : 28",
    "Teams": "Crvena Zvezda( Dejan Mrdanov )",
    "SXL": "countryCode",
    "Latp": "45",
    "Player_1": "Pope 2",
    "Player_11": "Evanilson 8",
    "Player_10": "Watkins 0",
    "Player_12": "Jos\u00E9 S\u00E1 5",
    "Player_13": "Minteh 0",
    "Player_14": "Gibbs-White 3",
    "Player_7": "Mitoma 2",
    "Player_2": "A\u00EFt-Nouri 8",
    "Player_5": "Lacroix 2",
    "Player_6": "Bruno G. 2",
    "Player_3": "Milenkovi\u0107 6",
    "Player_4": "J.Timber 7",
    "Player_8": "M.Salah 6",
    "Player_9": "Jo\u00E3o Pedro 2",
    "Player_15": "Mu\u00F1oz 2"
  },
  {
    "manager_Name": "1,827( 3,001,961 ) TotalXfr : 22",
    "Teams": "Ctrl Alt De Ligt( Marlon Vella )",
    "SXL": "countryCode",
    "Latp": "50",
    "Player_1": "Sels 8",
    "Player_11": "Wood 0",
    "Player_10": "Gakpo 1",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Hall 0",
    "Player_14": "Amad 0",
    "Player_7": "Rogers 10",
    "Player_2": "Virgil 8",
    "Player_5": "Gordon 0",
    "Player_6": "Palmer 6",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Aina 1",
    "Player_8": "M.Salah 6",
    "Player_9": "Isak 8",
    "Player_15": "Greaves 0"
  },
  {
    "manager_Name": "1,823( 3,081,971 ) TotalXfr : 29",
    "Teams": "Bruno Fernax FC( Chris Zammit )",
    "SXL": "countryCode",
    "Latp": "50",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Welbeck 0",
    "Player_10": "Isak 8",
    "Player_12": "A.Becker 0",
    "Player_13": "Wood 0",
    "Player_14": "Kluivert 0",
    "Player_7": "Elanga 11",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "Saliba 2",
    "Player_6": "Rogers 10",
    "Player_3": "Lewis 1",
    "Player_4": "Wan-Bissaka 2",
    "Player_8": "M.Salah 6",
    "Player_9": "B.Fernandes 2",
    "Player_15": "Alexander-Arnold 0"
  },
  {
    "manager_Name": "1,817( 3,192,156 ) TotalXfr : 27",
    "Teams": "Hakuna Mateta( Jason Evans )",
    "SXL": "countryCode",
    "Latp": "50",
    "Player_1": "Sels 8",
    "Player_11": "Wissa 5",
    "Player_10": "Isak 8",
    "Player_12": "Turner 0",
    "Player_13": "Wood 0",
    "Player_14": "Burgess 2",
    "Player_7": "Mitoma 2",
    "Player_2": "Aina 1",
    "Player_5": "M.Salah 6",
    "Player_6": "Saka 8",
    "Player_3": "Gabriel 1",
    "Player_4": "Kerkez 1",
    "Player_8": "Mbeumo 8",
    "Player_9": "Bergvall 2",
    "Player_15": "Thomas 0"
  },
  {
    "manager_Name": "1,816( 3,215,620 ) TotalXfr : 31",
    "Teams": "Rekegutt United( Eirik Presttun )",
    "SXL": "countryCode",
    "Latp": "48",
    "Player_1": "Henderson 2",
    "Player_11": "Marmoush 18",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "S\u00E1nchez 6",
    "Player_13": "Ra\u00FAl 2",
    "Player_14": "Harwood-Bellis 2",
    "Player_7": "Rashford 8",
    "Player_2": "Aina 1",
    "Player_5": "Mbeumo 8",
    "Player_6": "Bowen 2",
    "Player_3": "Gabriel 1",
    "Player_4": "Gu\u00E9hi 2",
    "Player_8": "Dibling 1",
    "Player_9": "M.Salah 3",
    "Player_15": "Faes 1"
  },
  {
    "manager_Name": "1,788( 3,735,118 ) TotalXfr : 33",
    "Teams": "klopp notch( Tobias Nocke )",
    "SXL": "countryCode",
    "Latp": "47",
    "Player_1": "Verbruggen 1",
    "Player_11": "Gakpo 1",
    "Player_10": "Wissa 5",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "Gordon 0",
    "Player_14": "Tsimikas 0",
    "Player_7": "Rashford 8",
    "Player_2": "Ajer 1",
    "Player_5": "Robinson 1",
    "Player_6": "M.Salah 6",
    "Player_3": "Colwill 6",
    "Player_4": "Kerkez 1",
    "Player_8": "Savinho 9",
    "Player_9": "Isak 8",
    "Player_15": "Kluivert 0"
  },
  {
    "manager_Name": "1,764( 4,147,514 ) TotalXfr : 16",
    "Teams": "Massilia( Daniel Borg )",
    "SXL": "countryCode",
    "Latp": "62",
    "Player_1": "Sels 8",
    "Player_11": "Isak 8",
    "Player_10": "Ra\u00FAl 2",
    "Player_12": "Flekken 1",
    "Player_13": "Hall 0",
    "Player_14": "Savinho 9",
    "Player_7": "Palmer 6",
    "Player_2": "Gabriel 1",
    "Player_5": "J.Murphy 5",
    "Player_6": "M.Salah 6",
    "Player_3": "Virgil 8",
    "Player_4": "Aina 1",
    "Player_8": "Mbeumo 8",
    "Player_9": "Delap 9",
    "Player_15": "A\u00EFt-Nouri 8"
  },
  {
    "manager_Name": "1,762( 4,182,301 ) TotalXfr : 20",
    "Teams": "FC Lokomotiv Sliema( Philip H\u00E5kansson )",
    "SXL": "countryCode",
    "Latp": "52",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 1",
    "Player_10": "Gakpo 1",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Kulusevski 0",
    "Player_14": "Hall 0",
    "Player_7": "Savinho 9",
    "Player_2": "Virgil 8",
    "Player_5": "Harwood-Bellis 2",
    "Player_6": "M.Salah 6",
    "Player_3": "Mazraoui 2",
    "Player_4": "Colwill 6",
    "Player_8": "J.Murphy 5",
    "Player_9": "Rogers 10",
    "Player_15": "Haaland 0"
  },
  {
    "manager_Name": "1,759( 4,230,162 ) TotalXfr : 5",
    "Teams": "Nachos( Melvin Xuereb )",
    "SXL": "countryCode",
    "Latp": "26",
    "Player_1": "Areola 2",
    "Player_11": "Ra\u00FAl 2",
    "Player_10": "Semenyo 2",
    "Player_12": "Fabianski 0",
    "Player_13": "Haaland 0",
    "Player_14": "Calvert-Lewin 0",
    "Player_7": "M.Salah 6",
    "Player_2": "Saliba 2",
    "Player_5": "Andersen 0",
    "Player_6": "Palmer 6",
    "Player_3": "Mazraoui 2",
    "Player_4": "Estupi\u00F1an 1",
    "Player_8": "Damsgaard 1",
    "Player_9": "Eze 2",
    "Player_15": "Faes 1"
  },
  {
    "manager_Name": "1,756( 4,284,940 ) TotalXfr : 25",
    "Teams": "Nketiah_\u0393\u03B1\u03C1\u03BC\u03C0\u03AE( Dimitris Tselikas )",
    "SXL": "countryCode",
    "Latp": "68",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Marmoush 18",
    "Player_10": "Wissa 5",
    "Player_12": "Flekken 1",
    "Player_13": "Kluivert 0",
    "Player_14": "Faes 1",
    "Player_7": "Son 2",
    "Player_2": "Aina 1",
    "Player_5": "Colwill 6",
    "Player_6": "Nwaneri 6",
    "Player_3": "J.Timber 7",
    "Player_4": "Robinson 1",
    "Player_8": "Mbeumo 8",
    "Player_9": "Isak 8",
    "Player_15": "M.Salah 3"
  },
  {
    "manager_Name": "1,756( 4,287,906 ) TotalXfr : 29",
    "Teams": "Gambit( Nicola Frasca )",
    "SXL": "countryCode",
    "Latp": "46",
    "Player_1": "Pickford 3",
    "Player_11": "Jo\u00E3o Pedro 2",
    "Player_10": "Wissa 5",
    "Player_12": "Slot 9",
    "Player_13": "Fabianski 0",
    "Player_14": "Taylor 0",
    "Player_7": "B.Fernandes 4",
    "Player_2": "Gabriel 1",
    "Player_5": "Smith Rowe 2",
    "Player_6": "Palmer 6",
    "Player_3": "Digne 6",
    "Player_4": "Pedro Porro 0",
    "Player_8": "Mbeumo 8",
    "Player_9": "Wood 0",
    "Player_15": "Winks 0"
  },
  {
    "manager_Name": "1,750( 4,386,482 ) TotalXfr : 28",
    "Teams": "Red Tigers FC( George Vepkhvadze )",
    "SXL": "countryCode",
    "Latp": "71",
    "Player_1": "Arrizabalaga 1",
    "Player_11": "Marmoush 18",
    "Player_10": "Isak 8",
    "Player_12": "Arteta 8",
    "Player_13": "Pickford 3",
    "Player_14": "Kluivert 0",
    "Player_7": "B.Fernandes 2",
    "Player_2": "Gabriel 1",
    "Player_5": "Murillo 9",
    "Player_6": "Bowen 2",
    "Player_3": "J.Timber 7",
    "Player_4": "Kerkez 1",
    "Player_8": "Palmer 6",
    "Player_9": "Rashford 8",
    "Player_15": "Mykolenko 2"
  },
  {
    "manager_Name": "1,723( 4,817,623 ) TotalXfr : 37",
    "Teams": "Seaside Hotspurs( Jostein Grodum )",
    "SXL": "countryCode",
    "Latp": "52",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Isak 8",
    "Player_10": "Marmoush 18",
    "Player_12": "Areola 2",
    "Player_13": "Wood 0",
    "Player_14": "Kluivert 0",
    "Player_7": "M.Salah 3",
    "Player_2": "Burn 2",
    "Player_5": "Aina 1",
    "Player_6": "Faes 1",
    "Player_3": "J.Timber 7",
    "Player_4": "Mu\u00F1oz 2",
    "Player_8": "Bruno G. 2",
    "Player_9": "B.Fernandes 2",
    "Player_15": "Foden 0"
  },
  {
    "manager_Name": "1,700( 5,142,969 ) TotalXfr : 2",
    "Teams": "Sparta( Andrew Spiteri )",
    "SXL": "countryCode",
    "Latp": "34",
    "Player_1": "Raya 2",
    "Player_11": "Havertz 0",
    "Player_10": "Isak 8",
    "Player_12": "Steele 0",
    "Player_13": "Nkunku 0",
    "Player_14": "Zinchenko 0",
    "Player_7": "Foden 0",
    "Player_2": "Cash 6",
    "Player_5": "M.Salah 6",
    "Player_6": "Tielemans 3",
    "Player_3": "Andersen 0",
    "Player_4": "Mazraoui 2",
    "Player_8": "Diogo J. 7",
    "Player_9": "Welbeck 0",
    "Player_15": "Alexander-Arnold 0"
  },
  {
    "manager_Name": "1,689( 5,302,486 ) TotalXfr : 28",
    "Teams": "Rolling Fernander( Adam Ruggier )",
    "SXL": "countryCode",
    "Latp": "53",
    "Player_1": "Sels 8",
    "Player_11": "Isak 8",
    "Player_10": "Wood 0",
    "Player_12": "Turner 0",
    "Player_13": "Alexander-Arnold 0",
    "Player_14": "Hall 0",
    "Player_7": "Mbeumo 8",
    "Player_2": "Robinson 1",
    "Player_5": "Bergvall 2",
    "Player_6": "Palmer 6",
    "Player_3": "Harwood-Bellis 2",
    "Player_4": "Mazraoui 2",
    "Player_8": "Rogers 10",
    "Player_9": "M.Salah 6",
    "Player_15": "Stewart 0"
  },
  {
    "manager_Name": "1,669( 5,566,382 ) TotalXfr : 26",
    "Teams": "grenbenzen( Gren Kallasmaa )",
    "SXL": "countryCode",
    "Latp": "35",
    "Player_1": "Raya 2",
    "Player_11": "Isak 8",
    "Player_10": "Gakpo 1",
    "Player_12": "Turner 0",
    "Player_13": "Amad 0",
    "Player_14": "Martinez 0",
    "Player_7": "Palmer 6",
    "Player_2": "Gabriel 1",
    "Player_5": "Tuanzebe 2",
    "Player_6": "Mbeumo 8",
    "Player_3": "Robinson 1",
    "Player_4": "Pedro Porro 0",
    "Player_8": "M.Salah 6",
    "Player_9": "Wood 0",
    "Player_15": "McAteer 0"
  },
  {
    "manager_Name": "1,668( 5,577,960 ) TotalXfr : 22",
    "Teams": "Santa Lucia FC( Antoine Sapiano )",
    "SXL": "countryCode",
    "Latp": "48",
    "Player_1": "Onana 2",
    "Player_11": "Ra\u00FAl 2",
    "Player_10": "Isak 8",
    "Player_12": "Bentley 0",
    "Player_13": "Kluivert 0",
    "Player_14": "Beto 1",
    "Player_7": "M.Salah 6",
    "Player_2": "Kerkez 1",
    "Player_5": "Milenkovi\u0107 6",
    "Player_6": "Rashford 8",
    "Player_3": "Burn 2",
    "Player_4": "Gu\u00E9hi 2",
    "Player_8": "Son 2",
    "Player_9": "Luis D\u00EDaz 9",
    "Player_15": "Pedro Porro 0"
  },
  {
    "manager_Name": "1,666( 5,599,991 ) TotalXfr : 8",
    "Teams": "Maximum Efferton( Jonathan Harding )",
    "SXL": "countryCode",
    "Latp": "30",
    "Player_1": "Areola 2",
    "Player_11": "Mateta 1",
    "Player_10": "Watkins 0",
    "Player_12": "Neto 0",
    "Player_13": "Kova\u010Di\u0107 0",
    "Player_14": "Vardy 0",
    "Player_7": "Palmer 6",
    "Player_2": "Romero 1",
    "Player_5": "Lewis 1",
    "Player_6": "Bowen 2",
    "Player_3": "Tarkowski 1",
    "Player_4": "Castagne 1",
    "Player_8": "M.Salah 6",
    "Player_9": "Luis D\u00EDaz 9",
    "Player_15": "Van de Ven 2"
  },
  {
    "manager_Name": "1,655( 5,737,031 ) TotalXfr : 0",
    "Teams": "Thebackstreetmoyes( Dave Clarke )",
    "SXL": "countryCode",
    "Latp": "53",
    "Player_1": "Raya 2",
    "Player_11": "Watkins 0",
    "Player_10": "Isak 16",
    "Player_12": "Bettinelli 0",
    "Player_13": "Alexander-Arnold 0",
    "Player_14": "Mainoo 0",
    "Player_7": "Saka 8",
    "Player_2": "Burn 2",
    "Player_5": "Cash 6",
    "Player_6": "Eze 2",
    "Player_3": "Gvardiol 6",
    "Player_4": "Saliba 2",
    "Player_8": "B.Fernandes 2",
    "Player_9": "Diogo J. 7",
    "Player_15": "Cunha 0"
  }
];