var s = [
  {
    "manager_Name": "2,078( 71,015 ) TotalXfr : 32",
    "Teams": "Blue Moon X1\uFFFD( PRAYAS BAJGAI )",
    "SXL": "countryCode",
    "Latp": "56",
    "Player_1": "Raya 2",
    "Player_11": "Marmoush 18",
    "Player_10": "Mateta 1",
    "Player_12": "Areola 2",
    "Player_13": "Foden 0",
    "Player_14": "Agbadou 6",
    "Player_7": "J.Murphy 5",
    "Player_2": "Gvardiol 6",
    "Player_5": "I.Sarr 2",
    "Player_6": "Saka 8",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Gabriel 1",
    "Player_8": "M.Salah 3",
    "Player_9": "Isak 8",
    "Player_15": "Burn 2"
  },
  {
    "manager_Name": "2,072( 84,068 ) TotalXfr : 31",
    "Teams": "BLIND at the BACK( Prayash Thapa )",
    "SXL": "countryCode",
    "Latp": "54",
    "Player_1": "Jos\u00E9 S\u00E1 5",
    "Player_11": "Isak 8",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Kluivert 0",
    "Player_14": "Huijsen 0",
    "Player_7": "Palmer 6",
    "Player_2": "A\u00EFt-Nouri 8",
    "Player_5": "M.Salah 6",
    "Player_6": "Mbeumo 8",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Milenkovi\u0107 6",
    "Player_8": "B.Fernandes 2",
    "Player_9": "Mateta 1",
    "Player_15": "Robinson 1"
  },
  {
    "manager_Name": "2,070( 89,032 ) TotalXfr : 31",
    "Teams": "Blue Brigade( Bhuman Basnet )",
    "SXL": "countryCode",
    "Latp": "54",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 1",
    "Player_10": "Isak 8",
    "Player_12": "Areola 2",
    "Player_13": "Kerkez 1",
    "Player_14": "J.Murphy 5",
    "Player_7": "M.Salah 6",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "I.Sarr 2",
    "Player_6": "Saka 8",
    "Player_3": "Gvardiol 6",
    "Player_4": "Gabriel 1",
    "Player_8": "Savinho 9",
    "Player_9": "Marmoush 9",
    "Player_15": "Burn 2"
  },
  {
    "manager_Name": "2,038( 199,134 ) TotalXfr : 31",
    "Teams": "Fu\u00DFball-Mannschaft( Gaurav Shrestha )",
    "SXL": "countryCode",
    "Latp": "52",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 1",
    "Player_10": "Isak 8",
    "Player_12": "Areola 2",
    "Player_13": "J.Murphy 5",
    "Player_14": "Konsa 6",
    "Player_7": "M.Salah 6",
    "Player_2": "Gabriel 1",
    "Player_5": "Savinho 9",
    "Player_6": "I.Sarr 2",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Gvardiol 6",
    "Player_8": "Palmer 6",
    "Player_9": "Marmoush 9",
    "Player_15": "Burn 2"
  },
  {
    "manager_Name": "2,006( 386,948 ) TotalXfr : 32",
    "Teams": "Avijit@afc( AVIJIT DAS )",
    "SXL": "countryCode",
    "Latp": "40",
    "Player_1": "Sels 8",
    "Player_11": "Beto 1",
    "Player_10": "Gibbs-White 3",
    "Player_12": "Fabianski 0",
    "Player_13": "Kluivert 0",
    "Player_14": "Haaland 0",
    "Player_7": "Mbeumo 8",
    "Player_2": "Robinson 1",
    "Player_5": "Mykolenko 2",
    "Player_6": "Thomas 0",
    "Player_3": "Virgil 8",
    "Player_4": "Kerkez 1",
    "Player_8": "B.Fernandes 2",
    "Player_9": "M.Salah 6",
    "Player_15": "Wood 0"
  },
  {
    "manager_Name": "2,006( 386,948 ) TotalXfr : 32",
    "Teams": "FALSE 9( Rohan Rai )",
    "SXL": "countryCode",
    "Latp": "50",
    "Player_1": "Henderson 2",
    "Player_11": "Marmoush 9",
    "Player_10": "Isak 8",
    "Player_12": "Jos\u00E9 S\u00E1 5",
    "Player_13": "Semenyo 2",
    "Player_14": "Robinson 1",
    "Player_7": "M.Salah 6",
    "Player_2": "Digne 6",
    "Player_5": "Palmer 6",
    "Player_6": "Bowen 2",
    "Player_3": "Gabriel 1",
    "Player_4": "Kerkez 1",
    "Player_8": "Mbeumo 8",
    "Player_9": "Mateta 1",
    "Player_15": "Mykolenko 2"
  },
  {
    "manager_Name": "2,002( 415,408 ) TotalXfr : 30",
    "Teams": "PINE( SATYAM RAI )",
    "SXL": "countryCode",
    "Latp": "54",
    "Player_1": "Raya 2",
    "Player_11": "Isak 8",
    "Player_10": "Marmoush 18",
    "Player_12": "Areola 2",
    "Player_13": "Rashford 8",
    "Player_14": "Livramento 2",
    "Player_7": "I.Sarr 2",
    "Player_2": "Gabriel 1",
    "Player_5": "Palmer 6",
    "Player_6": "J.Murphy 5",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Gvardiol 6",
    "Player_8": "M.Salah 3",
    "Player_9": "Mateta 1",
    "Player_15": "Konsa 6"
  },
  {
    "manager_Name": "2,001( 423,917 ) TotalXfr : 31",
    "Teams": "Last Season\u0027s Loser( \u00CFaraplang Pompyrthat )",
    "SXL": "countryCode",
    "Latp": "51",
    "Player_1": "Verbruggen 1",
    "Player_11": "Marmoush 9",
    "Player_10": "Isak 8",
    "Player_12": "Pickford 3",
    "Player_13": "Kluivert 0",
    "Player_14": "Wood 0",
    "Player_7": "O.Dango 2",
    "Player_2": "A\u00EFt-Nouri 8",
    "Player_5": "Castagne 1",
    "Player_6": "M.Salah 6",
    "Player_3": "Aina 1",
    "Player_4": "Gabriel 1",
    "Player_8": "Mbeumo 8",
    "Player_9": "Palmer 6",
    "Player_15": "Burgess 2"
  },
  {
    "manager_Name": "1,996( 464,876 ) TotalXfr : 33",
    "Teams": "Error404( Duri Tadu )",
    "SXL": "countryCode",
    "Latp": "51",
    "Player_1": "Pickford 3",
    "Player_11": "Evanilson 8",
    "Player_10": "Mateta 1",
    "Player_12": "Fabianski 0",
    "Player_13": "Enzo 11",
    "Player_14": "A\u00EFt-Nouri 8",
    "Player_7": "Palmer 6",
    "Player_2": "Gabriel 1",
    "Player_5": "O.Dango 2",
    "Player_6": "M.Salah 6",
    "Player_3": "Gvardiol 6",
    "Player_4": "Mu\u00F1oz 2",
    "Player_8": "Mbeumo 8",
    "Player_9": "Isak 8",
    "Player_15": "Robinson 1"
  },
  {
    "manager_Name": "1,995( 474,972 ) TotalXfr : 39",
    "Teams": "The SAFfron Sword( Milan Singh )",
    "SXL": "countryCode",
    "Latp": "44",
    "Player_1": "Raya 2",
    "Player_11": "Marmoush 9",
    "Player_10": "Isak 8",
    "Player_12": "Areola 2",
    "Player_13": "Foden 0",
    "Player_14": "Kluivert 0",
    "Player_7": "J.Murphy 5",
    "Player_2": "Gvardiol 6",
    "Player_5": "Wan-Bissaka 2",
    "Player_6": "M.Salah 6",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Gabriel 1",
    "Player_8": "I.Sarr 2",
    "Player_9": "Mateta 1",
    "Player_15": "Livramento 2"
  },
  {
    "manager_Name": "1,968( 728,605 ) TotalXfr : 29",
    "Teams": "Mawat( Arwat Lyngdoh )",
    "SXL": "countryCode",
    "Latp": "44",
    "Player_1": "Raya 2",
    "Player_11": "Marmoush 9",
    "Player_10": "Isak 8",
    "Player_12": "Areola 2",
    "Player_13": "Rogers 10",
    "Player_14": "Gabriel 1",
    "Player_7": "J.Murphy 5",
    "Player_2": "Kerkez 1",
    "Player_5": "I.Sarr 2",
    "Player_6": "M.Salah 6",
    "Player_3": "Gvardiol 6",
    "Player_4": "Mu\u00F1oz 2",
    "Player_8": "B.Fernandes 2",
    "Player_9": "Mateta 1",
    "Player_15": "Burn 2"
  },
  {
    "manager_Name": "1,944( 1,021,511 ) TotalXfr : 32",
    "Teams": "Bottled FC( Rishi Thulung )",
    "SXL": "countryCode",
    "Latp": "56",
    "Player_1": "Henderson 2",
    "Player_11": "Isak 8",
    "Player_10": "M.Salah 6",
    "Player_12": "Pickford 3",
    "Player_13": "Wood 0",
    "Player_14": "Beto 1",
    "Player_7": "Mbeumo 8",
    "Player_2": "Kerkez 1",
    "Player_5": "N.Williams 5",
    "Player_6": "Mazraoui 2",
    "Player_3": "A\u00EFt-Nouri 8",
    "Player_4": "Konat\u00E9 6",
    "Player_8": "Semenyo 2",
    "Player_9": "Saka 8",
    "Player_15": "Winks 0"
  },
  {
    "manager_Name": "1,942( 1,045,981 ) TotalXfr : 30",
    "Teams": "FC ASSASSINS( Kushal Sahota )",
    "SXL": "countryCode",
    "Latp": "58",
    "Player_1": "Raya 2",
    "Player_11": "Isak 8",
    "Player_10": "Marmoush 9",
    "Player_12": "Areola 2",
    "Player_13": "Kluivert 0",
    "Player_14": "Wood 0",
    "Player_7": "M.Salah 6",
    "Player_2": "Kerkez 1",
    "Player_5": "Livramento 2",
    "Player_6": "Mbeumo 8",
    "Player_3": "Milenkovi\u0107 6",
    "Player_4": "Virgil 8",
    "Player_8": "Palmer 6",
    "Player_9": "I.Sarr 2",
    "Player_15": "Van Hecke 1"
  },
  {
    "manager_Name": "1,931( 1,205,500 ) TotalXfr : 42",
    "Teams": "GUNNERS( Omkar Subba )",
    "SXL": "countryCode",
    "Latp": "41",
    "Player_1": "Henderson 2",
    "Player_11": "Isak 8",
    "Player_10": "Jo\u00E3o Pedro 2",
    "Player_12": "Sels 8",
    "Player_13": "Kluivert 0",
    "Player_14": "Wood 0",
    "Player_7": "B.Fernandes 2",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "Gvardiol 6",
    "Player_6": "M.Salah 6",
    "Player_3": "Kerkez 1",
    "Player_4": "Aina 1",
    "Player_8": "Bowen 2",
    "Player_9": "Savinho 9",
    "Player_15": "Mykolenko 2"
  },
  {
    "manager_Name": "1,921( 1,342,090 ) TotalXfr : 26",
    "Teams": "Jatin( Jatin Ghimiray )",
    "SXL": "countryCode",
    "Latp": "45",
    "Player_1": "Raya 2",
    "Player_11": "Isak 8",
    "Player_10": "Mbeumo 8",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Alexander-Arnold 0",
    "Player_14": "Wood 0",
    "Player_7": "Luis D\u00EDaz 9",
    "Player_2": "Konsa 6",
    "Player_5": "Van den Berg 1",
    "Player_6": "M.Salah 6",
    "Player_3": "Gabriel 1",
    "Player_4": "Robinson 1",
    "Player_8": "Mitoma 2",
    "Player_9": "Garnacho 1",
    "Player_15": "Jebbison 1"
  },
  {
    "manager_Name": "1,914( 1,453,214 ) TotalXfr : 29",
    "Teams": "Mersali( Bishal Rai )",
    "SXL": "countryCode",
    "Latp": "55",
    "Player_1": "Raya 2",
    "Player_11": "Wissa 5",
    "Player_10": "Isak 8",
    "Player_12": "Fabianski 0",
    "Player_13": "Kluivert 0",
    "Player_14": "Wood 0",
    "Player_7": "Nwaneri 6",
    "Player_2": "Milenkovi\u0107 6",
    "Player_5": "Castagne 1",
    "Player_6": "M.Salah 3",
    "Player_3": "Gabriel 1",
    "Player_4": "Aina 1",
    "Player_8": "Mbeumo 16",
    "Player_9": "Palmer 6",
    "Player_15": "Mu\u00F1oz 2"
  },
  {
    "manager_Name": "1,902( 1,650,893 ) TotalXfr : 32",
    "Teams": "\uFFFD Fields FC( Ravish Verma )",
    "SXL": "countryCode",
    "Latp": "49",
    "Player_1": "Raya 2",
    "Player_11": "Isak 8",
    "Player_10": "Mateta 1",
    "Player_12": "Areola 2",
    "Player_13": "Gordon 0",
    "Player_14": "Kluivert 0",
    "Player_7": "Rogers 10",
    "Player_2": "Gvardiol 6",
    "Player_5": "Burn 2",
    "Player_6": "M.Salah 6",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Gabriel 1",
    "Player_8": "I.Sarr 2",
    "Player_9": "Marmoush 9",
    "Player_15": "Konsa 6"
  },
  {
    "manager_Name": "1,895( 1,764,148 ) TotalXfr : 29",
    "Teams": "Busby Baby( Regean Lama )",
    "SXL": "countryCode",
    "Latp": "76",
    "Player_1": "Henderson 2",
    "Player_11": "Isak 8",
    "Player_10": "Marmoush 9",
    "Player_12": "Turner 0",
    "Player_13": "Wood 0",
    "Player_14": "Livramento 2",
    "Player_7": "Semenyo 2",
    "Player_2": "A\u00EFt-Nouri 8",
    "Player_5": "M.Salah 6",
    "Player_6": "Elanga 11",
    "Player_3": "Gvardiol 6",
    "Player_4": "Colwill 6",
    "Player_8": "Rogers 10",
    "Player_9": "Rashford 8",
    "Player_15": "Mykolenko 2"
  },
  {
    "manager_Name": "1,893( 1,799,822 ) TotalXfr : 30",
    "Teams": "\u2694\uFE0FFURY\u2694\uFE0F( Ashim Lama )",
    "SXL": "countryCode",
    "Latp": "60",
    "Player_1": "Flekken 1",
    "Player_11": "Isak 8",
    "Player_10": "Wissa 5",
    "Player_12": "Martinez 6",
    "Player_13": "Kluivert 0",
    "Player_14": "Wood 0",
    "Player_7": "M.Salah 6",
    "Player_2": "Mazraoui 2",
    "Player_5": "Milenkovi\u0107 6",
    "Player_6": "Mykolenko 2",
    "Player_3": "Gvardiol 6",
    "Player_4": "Virgil 8",
    "Player_8": "Rogers 10",
    "Player_9": "Palmer 6",
    "Player_15": "Kulusevski 0"
  },
  {
    "manager_Name": "1,882( 1,993,677 ) TotalXfr : 32",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "countryCode",
    "Latp": "54",
    "Player_1": "Henderson 2",
    "Player_11": "Watkins 0",
    "Player_10": "Isak 8",
    "Player_12": "Pickford 3",
    "Player_13": "Wood 0",
    "Player_14": "Kluivert 0",
    "Player_7": "Nwaneri 6",
    "Player_2": "Dalot 2",
    "Player_5": "Milenkovi\u0107 6",
    "Player_6": "Burn 2",
    "Player_3": "Konat\u00E9 6",
    "Player_4": "J.Timber 7",
    "Player_8": "M.Salah 3",
    "Player_9": "Palmer 12",
    "Player_15": "Iroegbunam 1"
  },
  {
    "manager_Name": "1,878( 2,057,013 ) TotalXfr : 25",
    "Teams": "Darjeeling City( Ruben Pradhan )",
    "SXL": "countryCode",
    "Latp": "60",
    "Player_1": "Jos\u00E9 S\u00E1 5",
    "Player_11": "Isak 8",
    "Player_10": "Watkins 0",
    "Player_12": "Howe 8",
    "Player_13": "Flekken 1",
    "Player_14": "Wood 0",
    "Player_7": "Palmer 6",
    "Player_2": "Digne 6",
    "Player_5": "Mu\u00F1oz 2",
    "Player_6": "J.Murphy 5",
    "Player_3": "Gu\u00E9hi 2",
    "Player_4": "Kerkez 1",
    "Player_8": "Elanga 11",
    "Player_9": "M.Salah 6",
    "Player_15": "Chalobah 5"
  },
  {
    "manager_Name": "1,877( 2,080,203 ) TotalXfr : 30",
    "Teams": "100 Yard Line Lords( Abhinay Pradhan )",
    "SXL": "countryCode",
    "Latp": "41",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 1",
    "Player_10": "Isak 8",
    "Player_12": "Turner 0",
    "Player_13": "Kluivert 0",
    "Player_14": "Wood 0",
    "Player_7": "M.Salah 6",
    "Player_2": "Aina 1",
    "Player_5": "Saliba 2",
    "Player_6": "I.Sarr 2",
    "Player_3": "Gabriel 1",
    "Player_4": "Huijsen 0",
    "Player_8": "Mbeumo 8",
    "Player_9": "Rogers 10",
    "Player_15": "Gvardiol 6"
  },
  {
    "manager_Name": "1,868( 2,238,527 ) TotalXfr : 27",
    "Teams": "nativ fc( Monlom Rongong )",
    "SXL": "countryCode",
    "Latp": "54",
    "Player_1": "Henderson 2",
    "Player_11": "Marmoush 9",
    "Player_10": "Evanilson 8",
    "Player_12": "Sels 8",
    "Player_13": "Kluivert 0",
    "Player_14": "Livramento 2",
    "Player_7": "M.Salah 6",
    "Player_2": "Milenkovi\u0107 6",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Mbeumo 8",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Gabriel 1",
    "Player_8": "I.Sarr 2",
    "Player_9": "Isak 8",
    "Player_15": "Gvardiol 6"
  },
  {
    "manager_Name": "1,866( 2,277,858 ) TotalXfr : 29",
    "Teams": "The Regista.( Passang T Sherpa )",
    "SXL": "countryCode",
    "Latp": "42",
    "Player_1": "Sels 8",
    "Player_11": "Watkins 0",
    "Player_10": "Isak 8",
    "Player_12": "Pickford 3",
    "Player_13": "Kluivert 0",
    "Player_14": "Wood 0",
    "Player_7": "Mitoma 2",
    "Player_2": "J.Timber 7",
    "Player_5": "Tarkowski 1",
    "Player_6": "Gu\u00E9hi 2",
    "Player_3": "Aina 1",
    "Player_4": "Kerkez 1",
    "Player_8": "M.Salah 6",
    "Player_9": "Palmer 6",
    "Player_15": "Smith Rowe 2"
  },
  {
    "manager_Name": "1,861( 2,371,171 ) TotalXfr : 30",
    "Teams": "Imperial Blues FC( Saurabh Tamang )",
    "SXL": "countryCode",
    "Latp": "60",
    "Player_1": "Sels 8",
    "Player_11": "Isak 8",
    "Player_10": "Marmoush 18",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Kluivert 0",
    "Player_14": "Wood 0",
    "Player_7": "Schade 2",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "Robinson 1",
    "Player_6": "M.Salah 3",
    "Player_3": "N.Williams 5",
    "Player_4": "Gabriel 1",
    "Player_8": "Rogers 10",
    "Player_9": "B.Fernandes 2",
    "Player_15": "Faes 1"
  },
  {
    "manager_Name": "1,835( 2,860,395 ) TotalXfr : 33",
    "Teams": "GustavousGooner( Ashish Subba )",
    "SXL": "countryCode",
    "Latp": "58",
    "Player_1": "Sels 8",
    "Player_11": "Strand Larsen 9",
    "Player_10": "Isak 8",
    "Player_12": "Howe 8",
    "Player_13": "Fabianski 0",
    "Player_14": "Wood 0",
    "Player_7": "Palmer 6",
    "Player_2": "Gabriel 1",
    "Player_5": "Pedro Porro 0",
    "Player_6": "I.Sarr 2",
    "Player_3": "Aina 1",
    "Player_4": "Kerkez 1",
    "Player_8": "M.Salah 6",
    "Player_9": "Mbeumo 8",
    "Player_15": "Kluivert 0"
  },
  {
    "manager_Name": "1,833( 2,902,998 ) TotalXfr : 46",
    "Teams": "Busby Babes( Pema Lepcha )",
    "SXL": "countryCode",
    "Latp": "38",
    "Player_1": "Henderson 2",
    "Player_11": "Wissa 5",
    "Player_10": "Beto 1",
    "Player_12": "Flekken 1",
    "Player_13": "Khusanov 0",
    "Player_14": "Kluivert 0",
    "Player_7": "Mbeumo 8",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "Spence 1",
    "Player_6": "I.Sarr 2",
    "Player_3": "Kerkez 1",
    "Player_4": "A\u00EFt-Nouri 8",
    "Player_8": "M.Salah 6",
    "Player_9": "B.Fernandes 2",
    "Player_15": "Haaland 0"
  },
  {
    "manager_Name": "1,832( 2,906,963 ) TotalXfr : 21",
    "Teams": "PR11( pranam rai )",
    "SXL": "countryCode",
    "Latp": "61",
    "Player_1": "Raya 2",
    "Player_11": "Delap 9",
    "Player_10": "Marmoush 9",
    "Player_12": "Areola 2",
    "Player_13": "Wood 0",
    "Player_14": "Alexander-Arnold 0",
    "Player_7": "Palmer 6",
    "Player_2": "Kerkez 1",
    "Player_5": "Mbeumo 8",
    "Player_6": "M.Salah 6",
    "Player_3": "Colwill 6",
    "Player_4": "Mu\u00F1oz 2",
    "Player_8": "Rogers 10",
    "Player_9": "Smith Rowe 2",
    "Player_15": "Wan-Bissaka 2"
  },
  {
    "manager_Name": "1,832( 2,910,962 ) TotalXfr : 28",
    "Teams": "ZilchExpectationsXI( Dipen Thapa )",
    "SXL": "countryCode",
    "Latp": "41",
    "Player_1": "Raya 2",
    "Player_11": "Isak 8",
    "Player_10": "Watkins 0",
    "Player_12": "Potter 0",
    "Player_13": "Flekken 1",
    "Player_14": "Kluivert 0",
    "Player_7": "Mbeumo 8",
    "Player_2": "Kerkez 1",
    "Player_5": "Aina 1",
    "Player_6": "Palmer 6",
    "Player_3": "Milenkovi\u0107 6",
    "Player_4": "Harwood-Bellis 2",
    "Player_8": "Sou\u010Dek 1",
    "Player_9": "M.Salah 6",
    "Player_15": "Wood 0"
  },
  {
    "manager_Name": "1,824( 3,061,784 ) TotalXfr : 28",
    "Teams": "FOMO7 FC( Chaje Lokam )",
    "SXL": "countryCode",
    "Latp": "55",
    "Player_1": "Pickford 3",
    "Player_11": "Isak 16",
    "Player_10": "Wissa 5",
    "Player_12": "Fabianski 0",
    "Player_13": "Wood 0",
    "Player_14": "Yarmoliuk 2",
    "Player_7": "B.Fernandes 2",
    "Player_2": "Pedro Porro 0",
    "Player_5": "Mu\u00F1oz 2",
    "Player_6": "Palmer 6",
    "Player_3": "Burgess 2",
    "Player_4": "Virgil 8",
    "Player_8": "M.Salah 3",
    "Player_9": "Rashford 8",
    "Player_15": "Bree 0"
  },
  {
    "manager_Name": "1,820( 3,146,086 ) TotalXfr : 42",
    "Teams": "YFC Jb( Vivek Lama )",
    "SXL": "countryCode",
    "Latp": "42",
    "Player_1": "Arrizabalaga 1",
    "Player_11": "Marmoush 9",
    "Player_10": "Isak 8",
    "Player_12": "Martinez 6",
    "Player_13": "Kluivert 0",
    "Player_14": "Wood 0",
    "Player_7": "Mitoma 2",
    "Player_2": "Saliba 2",
    "Player_5": "Dalot 2",
    "Player_6": "M.Salah 6",
    "Player_3": "Kerkez 1",
    "Player_4": "Doherty 7",
    "Player_8": "I.Sarr 2",
    "Player_9": "Smith Rowe 2",
    "Player_15": "Coady 1"
  },
  {
    "manager_Name": "1,777( 3,934,289 ) TotalXfr : 41",
    "Teams": "heregoesnothing11!!( Ashish Rai )",
    "SXL": "countryCode",
    "Latp": "48",
    "Player_1": "Pickford 3",
    "Player_11": "Isak 8",
    "Player_10": "Mateta 1",
    "Player_12": "Fabianski 0",
    "Player_13": "Wissa 5",
    "Player_14": "Aina 1",
    "Player_7": "Son 2",
    "Player_2": "A\u00EFt-Nouri 8",
    "Player_5": "M.Salah 3",
    "Player_6": "O.Dango 2",
    "Player_3": "Kerkez 2",
    "Player_4": "J.Timber 7",
    "Player_8": "Nwaneri 6",
    "Player_9": "Palmer 6",
    "Player_15": "Coady 1"
  },
  {
    "manager_Name": "1,776( 3,948,071 ) TotalXfr : 32",
    "Teams": "Hooligans \u00B0\u00B024( Pradhyumna Subba )",
    "SXL": "countryCode",
    "Latp": "58",
    "Player_1": "Henderson 2",
    "Player_11": "Watkins 0",
    "Player_10": "Isak 16",
    "Player_12": "Fabianski 0",
    "Player_13": "Kluivert 0",
    "Player_14": "Dibling 1",
    "Player_7": "Rogers 10",
    "Player_2": "Aina 1",
    "Player_5": "Van den Berg 1",
    "Player_6": "M.Salah 3",
    "Player_3": "Konsa 6",
    "Player_4": "Mitchell 1",
    "Player_8": "Luis D\u00EDaz 9",
    "Player_9": "Marmoush 9",
    "Player_15": "Alexander-Arnold 0"
  },
  {
    "manager_Name": "1,771( 4,037,462 ) TotalXfr : 35",
    "Teams": "Comet FC( Pranesh Sharma )",
    "SXL": "countryCode",
    "Latp": "55",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Delap 9",
    "Player_10": "Isak 8",
    "Player_12": "Fabianski 0",
    "Player_13": "Cunha 0",
    "Player_14": "Hall 0",
    "Player_7": "Foden 0",
    "Player_2": "Emerson 1",
    "Player_5": "Palmer 6",
    "Player_6": "Elanga 11",
    "Player_3": "Robinson 1",
    "Player_4": "J.Timber 7",
    "Player_8": "M.Salah 6",
    "Player_9": "Kluivert 0",
    "Player_15": "Taylor 0"
  },
  {
    "manager_Name": "1,763( 4,169,426 ) TotalXfr : 28",
    "Teams": "KungFuPandoos( Indrajeet Singh )",
    "SXL": "countryCode",
    "Latp": "50",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Vardy 0",
    "Player_10": "Ra\u00FAl 2",
    "Player_12": "Henderson 2",
    "Player_13": "Kluivert 0",
    "Player_14": "Foden 0",
    "Player_7": "Mbeumo 16",
    "Player_2": "Konat\u00E9 6",
    "Player_5": "Burn 2",
    "Player_6": "Cash 6",
    "Player_3": "Dalot 2",
    "Player_4": "Colwill 6",
    "Player_8": "B.Fernandes 2",
    "Player_9": "Son 2",
    "Player_15": "Haaland 0"
  },
  {
    "manager_Name": "1,741( 4,526,242 ) TotalXfr : 9",
    "Teams": "Renga FC( William Serto )",
    "SXL": "countryCode",
    "Latp": "44",
    "Player_1": "Flekken 1",
    "Player_11": "Jo\u00E3o Pedro 2",
    "Player_10": "B.Soumar\u00E9 2",
    "Player_12": "Fabianski 0",
    "Player_13": "Alexander-Arnold 0",
    "Player_14": "Haaland 0",
    "Player_7": "M.Salah 6",
    "Player_2": "Faes 1",
    "Player_5": "Gvardiol 6",
    "Player_6": "Rogers 10",
    "Player_3": "A\u00EFt-Nouri 8",
    "Player_4": "Robinson 1",
    "Player_8": "Martinelli 5",
    "Player_9": "Neto 2",
    "Player_15": "N.Jackson 1"
  },
  {
    "manager_Name": "1,649( 5,818,645 ) TotalXfr : 26",
    "Teams": "Dany11( Avinash DAniel Khawas )",
    "SXL": "countryCode",
    "Latp": "49",
    "Player_1": "Sels 8",
    "Player_11": "Wood 0",
    "Player_10": "Isak 8",
    "Player_12": "Turner 0",
    "Player_13": "Stewart 0",
    "Player_14": "Amad 0",
    "Player_7": "M.Salah 6",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "Aina 1",
    "Player_6": "Faes 1",
    "Player_3": "Gabriel 1",
    "Player_4": "Virgil 8",
    "Player_8": "Palmer 6",
    "Player_9": "Mbeumo 8",
    "Player_15": "Choudhury 0"
  },
  {
    "manager_Name": "1,593( 6,488,297 ) TotalXfr : 35",
    "Teams": "HEROES11( Obed Hang Subba )",
    "SXL": "countryCode",
    "Latp": "80",
    "Player_1": "Raya 2",
    "Player_11": "Watkins 0",
    "Player_10": "Isak 8",
    "Player_12": "Arteta 8",
    "Player_13": "Bentley 0",
    "Player_14": "Emerson 1",
    "Player_7": "M.Salah 3",
    "Player_2": "Milenkovi\u0107 6",
    "Player_5": "Nwaneri 6",
    "Player_6": "Luis D\u00EDaz 9",
    "Player_3": "Spence 1",
    "Player_4": "Virgil 8",
    "Player_8": "Elanga 11",
    "Player_9": "Marmoush 18",
    "Player_15": "Holgate 0"
  }
];