var s =[
   {
      "manager_Name":"Sahil Lampard",
      "Teams":"MarxUnited",
      "Player_1":"Ramsdale 1",
      "Player_2":"Cancelo 6",
      "Player_3":"James 0",
      "Player_4":"Livramento 2",
      "Player_5":"White 1",
      "Player_6":"Bernardo 1",
      "Player_7":"Salah 6$ captain",
      "Player_8":"Benrahma 2",
      "Player_9":"Son 12",
      "Player_10":"Maupay 0",
      "Player_11":"Dennis 1",
      "Player_12":"Sánchez 6",
      "Player_13":"Alexander-Arnold 0",
      "Player_14":"Archer 0",
      "Player_15":"Hudson-Odoi 0",
      "SXL":"32",
      "Bench":"1804",
      "Count  ":"2,483,152"
   },
   {
      "manager_Name":"Saurabh Tamang",
      "Teams":"Lucky FC",
      "Player_1":"Sánchez 6",
      "Player_2":"Amartey 1",
      "Player_3":"Coady 1",
      "Player_4":"Cancelo 6",
      "Player_5":"Gallagher 3",
      "Player_6":"Douglas Luiz 1",
      "Player_7":"Son 12",
      "Player_8":"Saka 2",
      "Player_9":"Salah 6$ captain",
      "Player_10":"Kane 4",
      "Player_11":"Cucho 1",
      "Player_12":"Guaita 7",
      "Player_13":"Tsimikas 0",
      "Player_14":"Alexander-Arnold 0",
      "Player_15":"Gelhardt 1",
      "SXL":"43",
      "Bench":"1757",
      "Count  ":"2,996,551"
   },
   {
      "manager_Name":"Pranesh Sharma",
      "Teams":"Immortal FC",
      "Player_1":"Sánchez 6",
      "Player_2":"Robertson 6",
      "Player_3":"Doherty 14",
      "Player_4":"Coady 1",
      "Player_5":"Saka 2",
      "Player_6":"Son 12",
      "Player_7":"Salah 6$ captain",
      "Player_8":"Raphinha 5",
      "Player_9":"Lacazette 2",
      "Player_10":"Weghorst 3",
      "Player_11":"Broja 2",
      "Player_12":"Foster 1",
      "Player_13":"Ramsey 2",
      "Player_14":"Alexander-Arnold 0",
      "Player_15":"White 1",
      "SXL":"59",
      "Bench":"2118",
      "Count  ":"293,268"
   },
   {
      "manager_Name":"Sanjeev Kumar",
      "Teams":"GAROBADHA UNITED",
      "Player_1":"Lloris 2",
      "Player_2":"White 1",
      "Player_3":"Robertson 6",
      "Player_4":"Cancelo 6",
      "Player_5":"Bowen 13",
      "Player_6":"Salah 3",
      "Player_7":"Son 24$ captain",
      "Player_8":"Saka 2",
      "Player_9":"Broja 2",
      "Player_10":"Adams 2",
      "Player_11":"Saint-Maximin 1",
      "Player_12":"Foster 1",
      "Player_13":"Tierney 0",
      "Player_14":"Alexander-Arnold 0",
      "Player_15":"Gordon 6",
      "SXL":"62",
      "Bench":"2097",
      "Count  ":"361,079"
   },
   {
      "manager_Name":"Kumar Anku",
      "Teams":"The Borderland Fc",
      "Player_1":"Schmeichel 3",
      "Player_2":"Cancelo 6",
      "Player_3":"Davies 8",
      "Player_4":"Taylor 5",
      "Player_5":"Gray 6$ captain",
      "Player_6":"Maddison 6",
      "Player_7":"Salah 3",
      "Player_8":"Saka 2",
      "Player_9":"Coutinho 2",
      "Player_10":"Rodriguez 8",
      "Player_11":"Kane 4",
      "Player_12":"Bachmann 0",
      "Player_13":"Alexander-Arnold 0",
      "Player_14":"Ait Nouri 0",
      "Player_15":"Hwang 1",
      "SXL":"53",
      "Bench":"2050",
      "Count  ":"549,160"
   },
   {
      "manager_Name":"Kushal Sahota",
      "Teams":"FC ASSASSINS",
      "Player_1":"Ramsdale 1",
      "Player_2":"Livramento 2",
      "Player_3":"Dias 0",
      "Player_4":"Duffy 0",
      "Player_5":"Jota 14",
      "Player_6":"Bowen 13",
      "Player_7":"Gallagher 3",
      "Player_8":"Salah 6$ captain",
      "Player_9":"Ronaldo 0",
      "Player_10":"Dennis 1",
      "Player_11":"Antonio 5",
      "Player_12":"Steele 0",
      "Player_13":"Tsimikas 0",
      "Player_14":"Allan 0",
      "Player_15":"Reguilón 0",
      "SXL":"45",
      "Bench":"1651",
      "Count  ":"4,212,757"
   },
   {
      "manager_Name":"Regean Lama",
      "Teams":"BUSBY BABIES 2",
      "Player_1":"Dubravka 0",
      "Player_2":"Veltman 7",
      "Player_3":"Robertson 6",
      "Player_4":"Doherty 14",
      "Player_5":"Ramsey 2",
      "Player_6":"Ødegaard 2",
      "Player_7":"Martinelli 1",
      "Player_8":"Son 12",
      "Player_9":"Salah 6$ captain",
      "Player_10":"Richarlison 17",
      "Player_11":"Kane 4",
      "Player_12":"Carson 0",
      "Player_13":"Tierney 0",
      "Player_14":"Pinnock 2",
      "Player_15":"Gelhardt 1",
      "SXL":"71",
      "Bench":"2124",
      "Count  ":"277,201"
   },
   {
      "manager_Name":"pranam rai",
      "Teams":"SYAKREE FC",
      "Player_1":"Lloris 2",
      "Player_2":"Rüdiger 6",
      "Player_3":"Matip 7",
      "Player_4":"Manquillo 0",
      "Player_5":"Ødegaard 2",
      "Player_6":"Kulusevski 6",
      "Player_7":"Bernardo 1",
      "Player_8":"Salah 3",
      "Player_9":"Mateta 6",
      "Player_10":"Toney 10$ captain",
      "Player_11":"Ronaldo 0",
      "Player_12":"Sánchez 6",
      "Player_13":"Alexander-Arnold 0",
      "Player_14":"Neves 0",
      "Player_15":"Chalobah 0",
      "SXL":"43",
      "Bench":"1900",
      "Count  ":"1,550,774"
   },
   {
      "manager_Name":"Ashim Lama",
      "Teams":"⚔️FURY⚔️",
      "Player_1":"Sá 3",
      "Player_2":"Cancelo 6",
      "Player_3":"Roberts 2",
      "Player_4":"Gabriel 1",
      "Player_5":"Coutinho 2",
      "Player_6":"Gallagher 3",
      "Player_7":"Martinelli 1",
      "Player_8":"Kulusevski 6",
      "Player_9":"Salah 3",
      "Player_10":"Broja 2",
      "Player_11":"Weghorst 6$ captain",
      "Player_12":"Ward 0",
      "Player_13":"Alexander-Arnold 0",
      "Player_14":"Jansson 2",
      "Player_15":"Toney 5",
      "SXL":"35",
      "Bench":"1941",
      "Count  ":"1,215,006"
   },
   {
      "manager_Name":"Vivek Pradhan",
      "Teams":"PEPPERBOX83",
      "Player_1":"Sánchez 6",
      "Player_2":"Cancelo 6",
      "Player_3":"Rüdiger 6",
      "Player_4":"van Dijk 6",
      "Player_5":"Gray 6$ captain",
      "Player_6":"Salah 3",
      "Player_7":"Sissoko 2",
      "Player_8":"Son 12",
      "Player_9":"Brownhill 3",
      "Player_10":"Weghorst 3",
      "Player_11":"Dennis 1",
      "Player_12":"Raya 4",
      "Player_13":"King 1",
      "Player_14":"Alexander-Arnold 0",
      "Player_15":"Mee 0",
      "SXL":"54",
      "Bench":"1985",
      "Count  ":"903,535"
   },
   {
      "manager_Name":"Sibin _",
      "Teams":"F95",
      "Player_1":"Ramsdale 1",
      "Player_2":"Coady 1",
      "Player_3":"White 1",
      "Player_4":"Robertson 6",
      "Player_5":"Dier 2",
      "Player_6":"Rüdiger 6",
      "Player_7":"Ødegaard 2",
      "Player_8":"Jota 14",
      "Player_9":"Salah 6$ captain",
      "Player_10":"Kulusevski 6",
      "Player_11":"Kane 4",
      "Player_12":"Sá 3",
      "Player_13":"Hwang 1",
      "Player_14":"Broja 2",
      "Player_15":"Ramsey 2",
      "SXL":"49",
      "Bench":"2081",
      "Count  ":"419,508"
   },
   {
      "manager_Name":"Omkar Subba",
      "Teams":"Omk09",
      "Player_1":"Ramsdale 1",
      "Player_2":"Robertson 6",
      "Player_3":"van Dijk 6",
      "Player_4":"Doherty 14",
      "Player_5":"Salah 6$ captain",
      "Player_6":"Kulusevski 6",
      "Player_7":"Saka 2",
      "Player_8":"Son 12",
      "Player_9":"Coutinho 2",
      "Player_10":"Weghorst 3",
      "Player_11":"Richarlison 17",
      "Player_12":"Foster 1",
      "Player_13":"Tierney 0",
      "Player_14":"Livramento 2",
      "Player_15":"Saint-Maximin 1",
      "SXL":"75",
      "Bench":"2079",
      "Count  ":"426,681"
   },
   {
      "manager_Name":"Indrajeet Singh",
      "Teams":"Kung Fu Pandoos",
      "Player_1":"de Gea 2",
      "Player_2":"Kilman 2",
      "Player_3":"Laporte 6",
      "Player_4":"Matip 7",
      "Player_5":"Ward-Prowse 10",
      "Player_6":"Raphinha 5",
      "Player_7":"Mané 1",
      "Player_8":"Coutinho 2",
      "Player_9":"Kane 4",
      "Player_10":"Weghorst 6$ captain",
      "Player_11":"Maupay 0",
      "Player_12":"Foster 1",
      "Player_13":"Tierney 0",
      "Player_14":"Mee 0",
      "Player_15":"Gilmour 3",
      "SXL":"45",
      "Bench":"1944",
      "Count  ":"1,192,274"
   },
   {
      "manager_Name":"Rishi Thulung",
      "Teams":"PL CG FC",
      "Player_1":"Mendy 0",
      "Player_2":"Marçal 5",
      "Player_3":"Rüdiger 6",
      "Player_4":"Cancelo 6",
      "Player_5":"Robertson 6",
      "Player_6":"Kulusevski 6",
      "Player_7":"Saka 2",
      "Player_8":"Mané 1",
      "Player_9":"Brownhill 3",
      "Player_10":"Antonio 5",
      "Player_11":"Kane 8$ captain",
      "Player_12":"Ramsdale 1",
      "Player_13":"Neves 0",
      "Player_14":"Tierney 0",
      "Player_15":"Dennis 1",
      "SXL":"48",
      "Bench":"2022",
      "Count  ":"688,459"
   },
   {
      "manager_Name":"Dipen Thapa",
      "Teams":"BW4_11",
      "Player_1":"Sá 3",
      "Player_2":"Livramento 2",
      "Player_3":"Gabriel 1",
      "Player_4":"Alexander-Arnold 0",
      "Player_5":"Soucek 2",
      "Player_6":"Jota 28$ captain",
      "Player_7":"Bernardo 1",
      "Player_8":"Fernandes 5",
      "Player_9":"Dennis 1",
      "Player_10":"Watkins 9",
      "Player_11":"Antonio 5",
      "Player_12":"Sánchez 6",
      "Player_13":"Tomiyasu 0",
      "Player_14":"Gallagher 3",
      "Player_15":"Dias 0",
      "SXL":"57",
      "Bench":"1777",
      "Count  ":"2,775,627"
   },
   {
      "manager_Name":"Nishant Singh",
      "Teams":"beta",
      "Player_1":"Ramsdale 1",
      "Player_2":"Doherty 14",
      "Player_3":"Cancelo 6",
      "Player_4":"Livramento 2",
      "Player_5":"Kulusevski 6",
      "Player_6":"Salah 3",
      "Player_7":"Saka 2",
      "Player_8":"Coutinho 2",
      "Player_9":"Weghorst 6$ captain",
      "Player_10":"Lacazette 2",
      "Player_11":"Maupay 0",
      "Player_12":"Sánchez 6",
      "Player_13":"Alexander-Arnold 0",
      "Player_14":"Maddison 6",
      "Player_15":"Dier 2",
      "SXL":"44",
      "Bench":"1960",
      "Count  ":"1,076,870"
   },
   {
      "manager_Name":"Ashish Subba",
      "Teams":"Gustavous Gunner",
      "Player_1":"Pope 3",
      "Player_2":"Bednarek 2",
      "Player_3":"Coady 1",
      "Player_4":"Cancelo 6",
      "Player_5":"Saka 2",
      "Player_6":"Salah 6$ captain",
      "Player_7":"Fernandes 5",
      "Player_8":"Gallagher 3",
      "Player_9":"Ward-Prowse 10",
      "Player_10":"Dennis 1",
      "Player_11":"Antonio 5",
      "Player_12":"Foster 1",
      "Player_13":"Tierney 0",
      "Player_14":"Alexander-Arnold 0",
      "Player_15":"Obafemi 0",
      "SXL":"44",
      "Bench":"1979",
      "Count  ":"944,201"
   },
   {
      "manager_Name":"Rohan Rai",
      "Teams":"False 9",
      "Player_1":"Ramsdale 1",
      "Player_2":"Robertson 6",
      "Player_3":"Rüdiger 6",
      "Player_4":"White 1",
      "Player_5":"Raphinha 5",
      "Player_6":"Salah 6$ captain",
      "Player_7":"Saka 2",
      "Player_8":"Mount 2",
      "Player_9":"Podence 3",
      "Player_10":"Richarlison 17",
      "Player_11":"Kane 4",
      "Player_12":"Sá 3",
      "Player_13":"Broja 2",
      "Player_14":"Davies 8",
      "Player_15":"Kilman 2",
      "SXL":"53",
      "Bench":"2258",
      "Count  ":"40,358"
   },
   {
      "manager_Name":"Raj Kanango",
      "Teams":"Weightloss Coach",
      "Player_1":"Forster 2",
      "Player_2":"Marçal 5",
      "Player_3":"Doherty 14",
      "Player_4":"Robertson 6",
      "Player_5":"Saka 2",
      "Player_6":"Martinelli 1",
      "Player_7":"Son 12",
      "Player_8":"Salah 6$ captain",
      "Player_9":"Toney 5",
      "Player_10":"Pukki 2",
      "Player_11":"Kane 4",
      "Player_12":"Raya 4",
      "Player_13":"Tierney 0",
      "Player_14":"Willock 5",
      "Player_15":"Schär 6",
      "SXL":"59",
      "Bench":"2137",
      "Count  ":"241,541"
   },
   {
      "manager_Name":"Gaurav Shrestha",
      "Teams":"Fußball-Mannschaft",
      "Player_1":"Ramsdale 1",
      "Player_2":"Robertson 6",
      "Player_3":"Amartey 1",
      "Player_4":"Doherty 14",
      "Player_5":"Havertz 2",
      "Player_6":"Kulusevski 6",
      "Player_7":"Saka 2",
      "Player_8":"Salah 6$ captain",
      "Player_9":"Raphinha 5",
      "Player_10":"Weghorst 3",
      "Player_11":"Kane 4",
      "Player_12":"Foster 1",
      "Player_13":"Alexander-Arnold 0",
      "Player_14":"Broja 2",
      "Player_15":"Tierney 0",
      "SXL":"50",
      "Bench":"2274",
      "Count  ":"28,648"
   },
   {
      "manager_Name":"Bishal Rai",
      "Teams":"Gooner for Life 037",
      "Player_1":"Ramsdale 1",
      "Player_2":"Robertson 6",
      "Player_3":"James 0",
      "Player_4":"Gabriel 1",
      "Player_5":"Doherty 14",
      "Player_6":"Cancelo 6",
      "Player_7":"Salah 6$ captain",
      "Player_8":"Raphinha 5",
      "Player_9":"Kulusevski 6",
      "Player_10":"Saka 2",
      "Player_11":"Kane 4",
      "Player_12":"Dubravka 0",
      "Player_13":"Ramsey 2",
      "Player_14":"Broja 2",
      "Player_15":"Richardson 0",
      "SXL":"51",
      "Bench":"2200",
      "Count  ":"108,964"
   },
   {
      "manager_Name":"RAJIYUNG Sun",
      "Teams":"hansing",
      "Player_1":"Alisson 6",
      "Player_2":"Laporte 6",
      "Player_3":"Cancelo 6",
      "Player_4":"Shaw 0",
      "Player_5":"Bowen 13",
      "Player_6":"Fernandes 5",
      "Player_7":"De Bruyne 11",
      "Player_8":"Pogba 4$ captain",
      "Player_9":"Broja 2",
      "Player_10":"Dennis 1",
      "Player_11":"Daka 1",
      "Player_12":"Raya 4",
      "Player_13":"White 1",
      "Player_14":"Saka 2",
      "Player_15":"Alexander-Arnold 0",
      "SXL":"55",
      "Bench":"1998",
      "Count  ":"824,299"
   },
   {
      "manager_Name":"Ashish Rai",
      "Teams":"Deadhead",
      "Player_1":"Ramsdale 1",
      "Player_2":"Doherty 14",
      "Player_3":"van Dijk 6",
      "Player_4":"Digne 1",
      "Player_5":"Podence 3",
      "Player_6":"Saka 2",
      "Player_7":"Zaha 8",
      "Player_8":"Ward-Prowse 10",
      "Player_9":"Salah 3",
      "Player_10":"Kane 4",
      "Player_11":"Calvert-Lewin 8$ captain",
      "Player_12":"Foster 1",
      "Player_13":"Saïss 0",
      "Player_14":"Mitchell 7",
      "Player_15":"Dennis 1",
      "SXL":"60",
      "Bench":"2113",
      "Count  ":"310,744"
   },
   {
      "manager_Name":"prabin kumar",
      "Teams":"Prabin Singh",
      "Player_1":"Mendy 0",
      "Player_2":"Shaw 0",
      "Player_3":"Alonso 0",
      "Player_4":"Rüdiger 6",
      "Player_5":"Townsend 0",
      "Player_6":"Benrahma 2",
      "Player_7":"Son 12",
      "Player_8":"Greenwood 0",
      "Player_9":"Antonio 5",
      "Player_10":"Aubameyang 0$ captain",
      "Player_11":"Jiménez 0",
      "Player_12":"Foster 1",
      "Player_13":"Dias 0",
      "Player_14":"Tsimikas 0",
      "Player_15":"Bissouma 0",
      "SXL":"25",
      "Bench":"1326",
      "Count  ":"7,345,868"
   },
   {
      "manager_Name":"Ravish Verma",
      "Teams":"Little Chilli FC",
      "Player_1":"Ramsdale 1",
      "Player_2":"van Dijk 6",
      "Player_3":"Thiago Silva 0",
      "Player_4":"Cancelo 6",
      "Player_5":"White 1",
      "Player_6":"Kulusevski 6",
      "Player_7":"Saka 2",
      "Player_8":"Salah 6$ captain",
      "Player_9":"Raphinha 5",
      "Player_10":"Weghorst 3",
      "Player_11":"Kane 4",
      "Player_12":"Guaita 7",
      "Player_13":"Alexander-Arnold 0",
      "Player_14":"Broja 2",
      "Player_15":"Ramsey 2",
      "SXL":"40",
      "Bench":"2140",
      "Count  ":"232,927"
   },
   {
      "manager_Name":"Prayash Thapa",
      "Teams":"abcde FC",
      "Player_1":"Pope 3",
      "Player_2":"Amartey 1",
      "Player_3":"Cancelo 6",
      "Player_4":"Doherty 14",
      "Player_5":"Salah 6$ captain",
      "Player_6":"Son 12",
      "Player_7":"Saka 2",
      "Player_8":"Coutinho 2",
      "Player_9":"Broja 2",
      "Player_10":"Weghorst 3",
      "Player_11":"Lacazette 2",
      "Player_12":"Dubravka 0",
      "Player_13":"Alexander-Arnold 0",
      "Player_14":"Barnes 2",
      "Player_15":"Tierney 0",
      "SXL":"53",
      "Bench":"2263",
      "Count  ":"36,735"
   },
   {
      "manager_Name":"Tenzing Ninjey",
      "Teams":"One Step Beyond 026*",
      "Player_1":"Ramsdale 1",
      "Player_2":"Doherty 14",
      "Player_3":"Robertson 6",
      "Player_4":"Digne 1",
      "Player_5":"Coutinho 2",
      "Player_6":"Salah 3",
      "Player_7":"Raphinha 5",
      "Player_8":"Saka 2",
      "Player_9":"Kulusevski 6",
      "Player_10":"Weghorst 3",
      "Player_11":"Kane 8$ captain",
      "Player_12":"Dubravka 0",
      "Player_13":"Tierney 0",
      "Player_14":"Broja 2",
      "Player_15":"Ait Nouri 0",
      "SXL":"51",
      "Bench":"2125",
      "Count  ":"274,782"
   },
   {
      "manager_Name":"Harsh Raval",
      "Teams":"Up the Bees",
      "Player_1":"de Gea 2",
      "Player_2":"Doherty 14",
      "Player_3":"Cancelo 6",
      "Player_4":"Keane -2",
      "Player_5":"Salah 6$ captain",
      "Player_6":"Mané 1",
      "Player_7":"Harrison 9",
      "Player_8":"Kulusevski 6",
      "Player_9":"Iheanacho 8",
      "Player_10":"Watkins 9",
      "Player_11":"Calvert-Lewin 4",
      "Player_12":"Foster 1",
      "Player_13":"Tierney 0",
      "Player_14":"Alexander-Arnold 0",
      "Player_15":"Ramsey 2",
      "SXL":"63",
      "Bench":"2199",
      "Count  ":"111,008"
   },
   {
      "manager_Name":"PRAYAS BAJGAI",
      "Teams":"MCFC@1894",
      "Player_1":"Ramsdale 1",
      "Player_2":"Doherty 14",
      "Player_3":"Rüdiger 6",
      "Player_4":"Robertson 6",
      "Player_5":"Cancelo 6",
      "Player_6":"Kulusevski 6",
      "Player_7":"Saka 2",
      "Player_8":"Raphinha 5",
      "Player_9":"Salah 6$ captain",
      "Player_10":"Weghorst 3",
      "Player_11":"Kane 4",
      "Player_12":"Foster 1",
      "Player_13":"Broja 2",
      "Player_14":"Alexander-Arnold 0",
      "Player_15":"Ramsey 2",
      "SXL":"59",
      "Bench":"2290",
      "Count  ":"19,881"
   },
   {
      "manager_Name":"AVIJIT DAS",
      "Teams":"Roing FC",
      "Player_1":"Pope 3",
      "Player_2":"White 1",
      "Player_3":"Rüdiger 6",
      "Player_4":"Doherty 14",
      "Player_5":"Raphinha 5",
      "Player_6":"Saka 2",
      "Player_7":"Salah 6$ captain",
      "Player_8":"Kulusevski 6",
      "Player_9":"Broja 2",
      "Player_10":"Weghorst 3",
      "Player_11":"Kane 4",
      "Player_12":"Foster 1",
      "Player_13":"Alexander-Arnold 0",
      "Player_14":"Coutinho 2",
      "Player_15":"Saïss 0",
      "SXL":"52",
      "Bench":"2189",
      "Count  ":"128,347"
   },
   {
      "manager_Name":"Abhijeet Singh",
      "Teams":"WEIGHTLOSS COACH",
      "Player_1":"Forster 2",
      "Player_2":"Cancelo 6",
      "Player_3":"Thiago Silva 0",
      "Player_4":"Matip 7",
      "Player_5":"Doherty 14",
      "Player_6":"Kulusevski 6",
      "Player_7":"Saka 2",
      "Player_8":"Salah 6$ captain",
      "Player_9":"Sancho 2",
      "Player_10":"Kane 4",
      "Player_11":"Weghorst 3",
      "Player_12":"Ramsdale 1",
      "Player_13":"Tierney 0",
      "Player_14":"Podence 3",
      "Player_15":"Wood 2",
      "SXL":"52",
      "Bench":"2205",
      "Count  ":"101,577"
   },
   {
      "manager_Name":"SATYAM RAI",
      "Teams":"PINE",
      "Player_1":"Pope 3",
      "Player_2":"Doherty 14",
      "Player_3":"Alonso 0",
      "Player_4":"Robertson 6",
      "Player_5":"Raphinha 5",
      "Player_6":"Salah 6$ captain",
      "Player_7":"Son 12",
      "Player_8":"Saka 2",
      "Player_9":"Kulusevski 6",
      "Player_10":"Lacazette 2",
      "Player_11":"Weghorst 3",
      "Player_12":"Foster 1",
      "Player_13":"Livramento 2",
      "Player_14":"Digne 1",
      "Player_15":"Jiménez 0",
      "SXL":"59",
      "Bench":"2233",
      "Count  ":"64,665"
   }
]