var s = [{
	"manager_Name": " nishant kumar singh ",
	"Teams": "beta 11",
	"Player_1": "Fabianski AVL (A)",
	"Player_2": "Stones BUR (A)",
	"Player_3": "Justin FUL (A)",
	"Player_4": "Cancelo BUR (A)",
	"Player_5": "Sterling BUR (A)$ captain$ captain",
	"Player_6": "Salah BHA (H)",
	"Player_7": "Fernandes 6",
	"Player_8": "Soucek AVL (A)",
	"Player_9": "Harrison EVE (H)",
	"Player_10": "Watkins WHU (H)",
	"Player_11": "Antonio AVL (A)",
	"Player_12": "Pope MCI (H)",
	"Player_13": "Bamford EVE (H)",
	"Player_14": "Mee MCI (H)",
	"Player_15": "Dallas EVE (H)",
	"SXL": "6",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": " Rohan Rai ",
	"Teams": "FALSE 9",
	"Player_1": "Martínez WHU (H)",
	"Player_2": "Stones BUR (A)",
	"Player_3": "Holding 1",
	"Player_4": "Shaw 7",
	"Player_5": "Fernandes 6",
	"Player_6": "Sterling BUR (A)",
	"Player_7": "Salah BHA (H)$ captain$ captain",
	"Player_8": "Son CHE (H)",
	"Player_9": "Maddison FUL (A)",
	"Player_10": "Antonio AVL (A)",
	"Player_11": "Watkins WHU (H)",
	"Player_12": "Sánchez LIV (A)",
	"Player_13": "Mitchell 0",
	"Player_14": "Coufal AVL (A)",
	"Player_15": "Brewster 0",
	"SXL": "14",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "  AVIJIT DAS ",
	"Teams": "WeAreTheArsenal",
	"Player_1": "Martínez WHU (H)",
	"Player_2": "Cresswell AVL (A)",
	"Player_3": "Wan-Bissaka 12",
	"Player_4": "Cancelo BUR (A)",
	"Player_5": "Maddison FUL (A)",
	"Player_6": "Fernandes 6",
	"Player_7": "Salah BHA (H)$ captain$ captain",
	"Player_8": "Sterling BUR (A)",
	"Player_9": "Wilson 5",
	"Player_10": "Bamford EVE (H)",
	"Player_11": "Calvert-Lewin LEE (A)",
	"Player_12": "Steer WHU (H)",
	"Player_13": "Soucek AVL (A)",
	"Player_14": "Mitchell 0",
	"Player_15": "Ayling EVE (H)",
	"SXL": "23",
	"Bench": "0",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": " gauravShrestha ",
	"Teams": "Fußball-Mannschaft",
	"Player_1": "Martínez WHU (H)",
	"Player_2": "Stones BUR (A)",
	"Player_3": "Dallas EVE (H)",
	"Player_4": "Cancelo BUR (A)",
	"Player_5": "Fernandes 6",
	"Player_6": "Raphinha EVE (H)",
	"Player_7": "Salah BHA (H)$ captain$ captain",
	"Player_8": "Sterling BUR (A)",
	"Player_9": "Bamford EVE (H)",
	"Player_10": "Calvert-Lewin LEE (A)",
	"Player_11": "Antonio AVL (A)",
	"Player_12": "Forster 0",
	"Player_13": "Soucek AVL (A)",
	"Player_14": "Coufal AVL (A)",
	"Player_15": "Mitchell 0",
	"SXL": "6",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "Dipen Thapa",
	"Teams": "Lokipower Reloaded",
	"Player_1": "McCarthy 0",
	"Player_2": "Cancelo BUR (A)",
	"Player_3": "Justin FUL (A)",
	"Player_4": "Mings WHU (H)",
	"Player_5": "Salah BHA (H)$ captain$ captain",
	"Player_6": "Zaha 1",
	"Player_7": "Son CHE (H)",
	"Player_8": "Barnes FUL (A)",
	"Player_9": "Fernandes 6",
	"Player_10": "Calvert-Lewin LEE (A)",
	"Player_11": "Watkins WHU (H)",
	"Player_12": "Martínez WHU (H)",
	"Player_13": "Antonio AVL (A)",
	"Player_14": "Taylor MCI (H)",
	"Player_15": "Kilman 1",
	"SXL": "7",
	"Bench": "1",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": " Sibin Surendran ",
	"Teams": "FortunaDüsseldorfer",
	"Player_1": "Ederson BUR (A)",
	"Player_2": "Stones BUR (A)",
	"Player_3": "Dias BUR (A)",
	"Player_4": "Coufal AVL (A)",
	"Player_5": "Son CHE (H)",
	"Player_6": "Salah BHA (H)$ captain$ captain",
	"Player_7": "Smith Rowe 2",
	"Player_8": "Fernandes 6",
	"Player_9": "Adams 2",
	"Player_10": "Bamford EVE (H)",
	"Player_11": "Werner TOT (A)",
	"Player_12": "Johnstone 2",
	"Player_13": "Raphinha EVE (H)",
	"Player_14": "Davies CHE (H)",
	"Player_15": "Walker-Peters 0",
	"SXL": "10",
	"Bench": "2",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "  Kushal Sahota ",
	"Teams": "FC ASSASSINS",
	"Player_1": "Lloris CHE (H)",
	"Player_2": "Cresswell AVL (A)",
	"Player_3": "Cancelo BUR (A)",
	"Player_4": "Alioski EVE (H)",
	"Player_5": "Foden BUR (A)",
	"Player_6": "Son CHE (H)",
	"Player_7": "Fernandes 6",
	"Player_8": "Salah BHA (H)$ captain$ captain",
	"Player_9": "Wilson 5",
	"Player_10": "Calvert-Lewin LEE (A)",
	"Player_11": "Bamford EVE (H)",
	"Player_12": "Macey 0",
	"Player_13": "Neco Williams BHA (H)",
	"Player_14": "Bernardo LIV (A)",
	"Player_15": "Oriol Romeu 0",
	"SXL": "11",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "  SATYAM RAI ",
	"Teams": "PINE",
	"Player_1": "Martínez WHU (H)",
	"Player_2": "Cancelo BUR (A)",
	"Player_3": "Shaw 7",
	"Player_4": "Justin FUL (A)",
	"Player_5": "Gündogan BUR (A)",
	"Player_6": "Fernandes 6",
	"Player_7": "Sterling BUR (A)",
	"Player_8": "Salah BHA (H)$ captain$ captain",
	"Player_9": "Wilson 5",
	"Player_10": "Bamford EVE (H)",
	"Player_11": "Antonio AVL (A)",
	"Player_12": "Peacock-Farrell MCI (H)",
	"Player_13": "Soucek AVL (A)",
	"Player_14": "Chilwell TOT (A)",
	"Player_15": "Coufal AVL (A)",
	"SXL": "18",
	"Bench": "0",
	"Count  ": "3( 3+0 )"
}, {
	"manager_Name": "  Ashim Lama ",
	"Teams": "⚔️FURY⚔️",
	"Player_1": "Martínez WHU (H)",
	"Player_2": "Stones BUR (A)",
	"Player_3": "Justin FUL (A)",
	"Player_4": "Dias BUR (A)",
	"Player_5": "Sterling BUR (A)$ captain$ captain",
	"Player_6": "Son CHE (H)",
	"Player_7": "Saka 2",
	"Player_8": "Fernandes 6",
	"Player_9": "Salah BHA (H)",
	"Player_10": "Bamford EVE (H)",
	"Player_11": "Watkins WHU (H)",
	"Player_12": "Martin AVL (A)",
	"Player_13": "Brewster 0",
	"Player_14": "Mitchell 0",
	"Player_15": "Taylor MCI (H)",
	"SXL": "8",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": "  indrajeet kumar singh ",
	"Teams": "Kung fu Pandoos",
	"Player_1": "Meslier EVE (H)",
	"Player_2": "Bellerín 1",
	"Player_3": "Maguire 5",
	"Player_4": "Cresswell AVL (A)",
	"Player_5": "Salah BHA (H)",
	"Player_6": "Son CHE (H)",
	"Player_7": "Maddison FUL (A)",
	"Player_8": "Pereira 1",
	"Player_9": "Sterling BUR (A)$ captain$ captain",
	"Player_10": "Wilson 5",
	"Player_11": "Bamford EVE (H)",
	"Player_12": "Henderson 0",
	"Player_13": "Calvert-Lewin LEE (A)",
	"Player_14": "Webster LIV (A)",
	"Player_15": "Walker-Peters 0",
	"SXL": "12",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": "   Vivek Lama ",
	"Teams": "JOJOs LFC",
	"Player_1": "Alisson BHA (H)",
	"Player_2": "Saïss 0",
	"Player_3": "Alexander-Arnold BHA (H)",
	"Player_4": "Walker-Peters 0",
	"Player_5": "Tielemans FUL (A)",
	"Player_6": "Son CHE (H)",
	"Player_7": "Sterling BUR (A)",
	"Player_8": "Mané BHA (H)$ captain$ captain",
	"Player_9": "Connolly LIV (A)",
	"Player_10": "Adams 2",
	"Player_11": "Bamford EVE (H)",
	"Player_12": "Ryan 0",
	"Player_13": "Saint-Maximin 1",
	"Player_14": "Egan 5",
	"Player_15": "Dunne MCI (H)",
	"SXL": "2",
	"Bench": "6",
	"Count  ": "1( 0+1 )"
}, {
	"manager_Name": " Prabin ",
	"Teams": "Random XI",
	"Player_1": "Ederson BUR (A)",
	"Player_2": "Cancelo BUR (A)",
	"Player_3": "Holding 1",
	"Player_4": "Justin FUL (A)",
	"Player_5": "Shaw 7",
	"Player_6": "Barnes FUL (A)",
	"Player_7": "Mahrez BUR (A)$ captain$ captain",
	"Player_8": "Zaha 1",
	"Player_9": "Grealish WHU (H)",
	"Player_10": "Wilson 5",
	"Player_11": "Antonio AVL (A)",
	"Player_12": "Macey 0",
	"Player_13": "Son CHE (H)",
	"Player_14": "Kane CHE (H)",
	"Player_15": "Dunne MCI (H)",
	"SXL": "14",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": " AnkuKumar ",
	"Teams": "Galaxies Stars",
	"Player_1": "Leno -1",
	"Player_2": "Konsa WHU (H)",
	"Player_3": "Cancelo BUR (A)",
	"Player_4": "Digne LEE (A)$ captain$ captain",
	"Player_5": "Salah BHA (H)",
	"Player_6": "Zaha 1",
	"Player_7": "Sterling BUR (A)",
	"Player_8": "Son CHE (H)",
	"Player_9": "Sigurdsson LEE (A)",
	"Player_10": "Watkins WHU (H)",
	"Player_11": "Martial 5",
	"Player_12": "Forster 0",
	"Player_13": "Ayling EVE (H)",
	"Player_14": "Brewster 0",
	"Player_15": "Kilman 1",
	"SXL": "5",
	"Bench": "1",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": " okendri",
	"Teams": "Happy Williams",
	"Player_1": "Martínez WHU (H)",
	"Player_2": "Dias BUR (A)",
	"Player_3": "Coufal AVL (A)",
	"Player_4": "Dallas EVE (H)",
	"Player_5": "Salah BHA (H)",
	"Player_6": "Fernandes 6",
	"Player_7": "Sterling BUR (A)$ captain$ captain",
	"Player_8": "Grealish WHU (H)",
	"Player_9": "Bamford EVE (H)",
	"Player_10": "Wilson 5",
	"Player_11": "Antonio AVL (A)",
	"Player_12": "McCarthy 0",
	"Player_13": "Soucek AVL (A)",
	"Player_14": "Dier CHE (H)",
	"Player_15": "Dunk LIV (A)",
	"SXL": "11",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": " ONkarSUbba",
	"Teams": "Omk09",
	"Player_1": "Lloris CHE (H)",
	"Player_2": "Stones BUR (A)",
	"Player_3": "Targett WHU (H)",
	"Player_4": "Robertson BHA (H)",
	"Player_5": "Salah BHA (H)$ captain$ captain",
	"Player_6": "Grealish WHU (H)",
	"Player_7": "Son CHE (H)",
	"Player_8": "Fernandes 6",
	"Player_9": "Gündogan BUR (A)",
	"Player_10": "Bamford EVE (H)",
	"Player_11": "Wilson 5",
	"Player_12": "Nyland WHU (H)",
	"Player_13": "Justin FUL (A)",
	"Player_14": "Calvert-Lewin LEE (A)",
	"Player_15": "Bednarek -3",
	"SXL": "11",
	"Bench": "-3",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": " abhijeetSingh",
	"Teams": "Impact Creators",
	"Player_1": "Martínez WHU (H)",
	"Player_2": "Justin FUL (A)",
	"Player_3": "Cresswell AVL (A)",
	"Player_4": "Maguire 5",
	"Player_5": "Fernandes 12$ captain$ captain",
	"Player_6": "Maddison FUL (A)",
	"Player_7": "Salah BHA (H)",
	"Player_8": "Sterling BUR (A)",
	"Player_9": "Wilson 5",
	"Player_10": "Bamford EVE (H)",
	"Player_11": "Calvert-Lewin LEE (A)",
	"Player_12": "Martin AVL (A)",
	"Player_13": "Kilman 1",
	"Player_14": "Riedewald 7",
	"Player_15": "Johnson AVL (A)",
	"SXL": "22",
	"Bench": "8",
	"Count  ": "4( 3+1 )"
}, {
	"manager_Name": " ashishSubba ",
	"Teams": "GUSTAVOUS GUNNER",
	"Player_1": "Martínez WHU (H)",
	"Player_2": "Cresswell AVL (A)",
	"Player_3": "Dallas EVE (H)",
	"Player_4": "Justin FUL (A)",
	"Player_5": "Chilwell TOT (A)",
	"Player_6": "Barnes FUL (A)",
	"Player_7": "Grealish WHU (H)",
	"Player_8": "Maddison FUL (A)",
	"Player_9": "Salah BHA (H)$ captain$ captain",
	"Player_10": "Fernandes 6",
	"Player_11": "Bamford EVE (H)",
	"Player_12": "McCarthy 0",
	"Player_13": "Lacazette 4",
	"Player_14": "Alioski EVE (H)",
	"Player_15": "Davis WHU (H)",
	"SXL": "6",
	"Bench": "4",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": " nitesh singh",
	"Teams": "Danapur United",
	"Player_1": "Martínez WHU (H)",
	"Player_2": "Keane LEE (A)",
	"Player_3": "Dier CHE (H)",
	"Player_4": "Saïss 0",
	"Player_5": "Cresswell AVL (A)",
	"Player_6": "Salah BHA (H)$ captain$ captain",
	"Player_7": "Grealish WHU (H)",
	"Player_8": "Son CHE (H)",
	"Player_9": "Fernandes 6",
	"Player_10": "Zaha 1",
	"Player_11": "Bamford EVE (H)",
	"Player_12": "Areola LEI (H)",
	"Player_13": "Mee MCI (H)",
	"Player_14": "Huggins EVE (H)",
	"Player_15": "Diaby 0",
	"SXL": "7",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": " RajKanango ",
	"Teams": "Dream Killer",
	"Player_1": "Martínez WHU (H)",
	"Player_2": "Cancelo BUR (A)",
	"Player_3": "Dallas EVE (H)",
	"Player_4": "Stones BUR (A)",
	"Player_5": "Fernandes 6",
	"Player_6": "Grealish WHU (H)",
	"Player_7": "Salah BHA (H)$ captain$ captain",
	"Player_8": "Barnes FUL (A)",
	"Player_9": "Firmino BHA (H)",
	"Player_10": "Bamford EVE (H)",
	"Player_11": "Calvert-Lewin LEE (A)",
	"Player_12": "Steer WHU (H)",
	"Player_13": "Dier CHE (H)",
	"Player_14": "Burke 1",
	"Player_15": "Neco Williams BHA (H)",
	"SXL": "6",
	"Bench": "1",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": " sahilLampard ",
	"Teams": "Marx 11",
	"Player_1": "Martínez WHU (H)",
	"Player_2": "Bertrand -1",
	"Player_3": "Justin FUL (A)",
	"Player_4": "Robertson BHA (H)",
	"Player_5": "Grealish WHU (H)",
	"Player_6": "Salah BHA (H)$ captain$ captain",
	"Player_7": "Son CHE (H)",
	"Player_8": "Fernandes 6",
	"Player_9": "Klich EVE (H)",
	"Player_10": "Bamford EVE (H)",
	"Player_11": "Calvert-Lewin LEE (A)",
	"Player_12": "Ryan 0",
	"Player_13": "Reguilón CHE (H)",
	"Player_14": "Delap BUR (A)",
	"Player_15": "Casey EVE (H)",
	"SXL": "5",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": " PemaSHerpa ",
	"Teams": "CottonMouth XI",
	"Player_1": "Martínez WHU (H)",
	"Player_2": "Justin FUL (A)",
	"Player_3": "Stones BUR (A)",
	"Player_4": "Cancelo BUR (A)",
	"Player_5": "Son CHE (H)",
	"Player_6": "Bernardo Silva BUR (A)",
	"Player_7": "Barnes FUL (A)",
	"Player_8": "Fernandes 6",
	"Player_9": "Bamford EVE (H)",
	"Player_10": "Werner TOT (A)$ captain$ captain",
	"Player_11": "Antonio AVL (A)",
	"Player_12": "Button 0",
	"Player_13": "Maddison FUL (A)",
	"Player_14": "Tierney 0",
	"Player_15": "Cresswell AVL (A)",
	"SXL": "6",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": " pranamRai ",
	"Teams": "SYAKREE F.C.",
	"Player_1": "Guaita 3",
	"Player_2": "Chilwell TOT (A)",
	"Player_3": "Stones BUR (A)",
	"Player_4": "Targett WHU (H)",
	"Player_5": "Robertson BHA (H)",
	"Player_6": "Foden BUR (A)",
	"Player_7": "Barnes FUL (A)",
	"Player_8": "Mané BHA (H)",
	"Player_9": "Son CHE (H)",
	"Player_10": "Saka 2",
	"Player_11": "Lacazette 8$ captain$ captain",
	"Player_12": "Martínez WHU (H)",
	"Player_13": "Johnson AVL (A)",
	"Player_14": "Bamford EVE (H)",
	"Player_15": "Davis WHU (H)",
	"SXL": "13",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": " regeanLama ",
	"Teams": "Busby Baby",
	"Player_1": "Meslier EVE (H)",
	"Player_2": "Dallas EVE (H)",
	"Player_3": "Coufal AVL (A)",
	"Player_4": "Justin FUL (A)",
	"Player_5": "Salah BHA (H)",
	"Player_6": "Sterling BUR (A)$ captain$ captain",
	"Player_7": "Soucek AVL (A)",
	"Player_8": "Fernandes 6",
	"Player_9": "Son CHE (H)",
	"Player_10": "Bamford EVE (H)",
	"Player_11": "Antonio AVL (A)",
	"Player_12": "McCarthy 0",
	"Player_13": "Brewster 0",
	"Player_14": "Walker-Peters 0",
	"Player_15": "Taylor MCI (H)",
	"SXL": "6",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": " hanSingh ",
	"Teams": "hansing",
	"Player_1": "de Gea 6",
	"Player_2": "Konsa WHU (H)",
	"Player_3": "Dias BUR (A)",
	"Player_4": "Stones BUR (A)",
	"Player_5": "Fernandes 6",
	"Player_6": "Salah BHA (H)$ captain$ captain",
	"Player_7": "Maddison FUL (A)",
	"Player_8": "Son CHE (H)",
	"Player_9": "Saka 2",
	"Player_10": "Calvert-Lewin LEE (A)",
	"Player_11": "Bamford EVE (H)",
	"Player_12": "Nyland WHU (H)",
	"Player_13": "Coufal AVL (A)",
	"Player_14": "Lowton MCI (H)",
	"Player_15": "Kane CHE (H)",
	"SXL": "14",
	"Bench": "0",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": " sanjeevkumar ",
	"Teams": "mendal11",
	"Player_1": "Ederson BUR (A)",
	"Player_2": "Justin FUL (A)",
	"Player_3": "Stones BUR (A)",
	"Player_4": "Coufal AVL (A)",
	"Player_5": "Grealish WHU (H)",
	"Player_6": "Son CHE (H)$ captain$ captain",
	"Player_7": "Fernandes 6",
	"Player_8": "Zaha 1",
	"Player_9": "Gündogan BUR (A)",
	"Player_10": "Adams 2",
	"Player_11": "Watkins WHU (H)",
	"Player_12": "Martin AVL (A)",
	"Player_13": "Mitchell 0",
	"Player_14": "James TOT (A)",
	"Player_15": "Kane CHE (H)",
	"SXL": "9",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}, {
	"manager_Name": " ashishRai ",
	"Teams": "goooooooners",
	"Player_1": "Johnstone 2",
	"Player_2": "Cresswell AVL (A)",
	"Player_3": "Alexander-Arnold BHA (H)",
	"Player_4": "Cancelo BUR (A)$ captain$ captain",
	"Player_5": "Son CHE (H)",
	"Player_6": "Maddison FUL (A)",
	"Player_7": "Foden BUR (A)",
	"Player_8": "Salah BHA (H)",
	"Player_9": "Calvert-Lewin LEE (A)",
	"Player_10": "Antonio AVL (A)",
	"Player_11": "Bamford EVE (H)",
	"Player_12": "Areola LEI (H)",
	"Player_13": "Lookman LEI (H)",
	"Player_14": "Robinson LEI (H)",
	"Player_15": "Pieters MCI (H)",
	"SXL": "2",
	"Bench": "0",
	"Count  ": "0( 0+0 )"
}, {
	"manager_Name": " ravishVerma ",
	"Teams": "Little Chilli FC",
	"Player_1": "Sánchez LIV (A)",
	"Player_2": "Dias BUR (A)",
	"Player_3": "Cresswell AVL (A)",
	"Player_4": "Dallas EVE (H)",
	"Player_5": "Fernandes 6",
	"Player_6": "Gündogan BUR (A)",
	"Player_7": "Son CHE (H)",
	"Player_8": "Salah BHA (H)$ captain$ captain",
	"Player_9": "Wilson 5",
	"Player_10": "Bamford EVE (H)",
	"Player_11": "Calvert-Lewin LEE (A)",
	"Player_12": "Button 0",
	"Player_13": "Walker-Peters 0",
	"Player_14": "Neco Williams BHA (H)",
	"Player_15": "Burke 1",
	"SXL": "11",
	"Bench": "1",
	"Count  ": "2( 2+0 )"
}, {
	"manager_Name": " bishalRai ",
	"Teams": "Gooner for Life",
	"Player_1": "Martínez WHU (H)",
	"Player_2": "Dias BUR (A)",
	"Player_3": "Robertson BHA (H)",
	"Player_4": "Justin FUL (A)",
	"Player_5": "Raphinha EVE (H)",
	"Player_6": "Fernandes 6",
	"Player_7": "Son CHE (H)",
	"Player_8": "Salah BHA (H)$ captain$ captain",
	"Player_9": "Grealish WHU (H)",
	"Player_10": "Bamford EVE (H)",
	"Player_11": "Watkins WHU (H)",
	"Player_12": "Fabianski AVL (A)",
	"Player_13": "Chilwell TOT (A)",
	"Player_14": "Cresswell AVL (A)",
	"Player_15": "Brewster 0",
	"SXL": "6",
	"Bench": "0",
	"Count  ": "1( 1+0 )"
}]