var s = [
  {
    "manager_Name": "1,343( 25,531 ) TotalXfr : 19",
    "Teams": "YoroOYoro( Rajdeep Gupta )",
    "SXL": "India",
    "Latp": "51",
    "Player_1": "Raya 3",
    "Player_11": "Wood 8",
    "Player_10": "Isak 7",
    "Player_12": "Fabianski 0",
    "Player_13": "Rogers 0",
    "Player_14": "Amad 9",
    "Player_7": "M.Salah 14",
    "Player_2": "Robinson 1",
    "Player_5": "Hall 2",
    "Player_6": "Palmer 10",
    "Player_3": "Alexander-Arnold 0",
    "Player_4": "Gabriel 2",
    "Player_8": "I.Sarr 2",
    "Player_9": "N.Jackson 2",
    "Player_15": "Colwill 1"
  },
  {
    "manager_Name": "1,338( 31,759 ) TotalXfr : 17",
    "Teams": "Gunners 24( Suumit Bhardwaj )",
    "SXL": "India",
    "Latp": "60",
    "Player_1": "Raya 3",
    "Player_11": "Isak 7",
    "Player_10": "Wissa 11",
    "Player_12": "Flekken 6",
    "Player_13": "Jo\u00E3o Pedro 9",
    "Player_14": "Rogers 0",
    "Player_7": "Palmer 10",
    "Player_2": "Gabriel 2",
    "Player_5": "Mu\u00F1oz 2",
    "Player_6": "Gordon 7",
    "Player_3": "Virgil 1",
    "Player_4": "Robinson 1",
    "Player_8": "M.Salah 14",
    "Player_9": "I.Sarr 2",
    "Player_15": "Faes 1"
  },
  {
    "manager_Name": "1,326( 54,709 ) TotalXfr : 18",
    "Teams": "Va Va Voom( Piyush R )",
    "SXL": "USA",
    "Latp": "95",
    "Player_1": "Sels 9",
    "Player_11": "Isak 7",
    "Player_10": "Wood 8",
    "Player_12": "Flekken 6",
    "Player_13": "Smith Rowe 1",
    "Player_14": "Rogers 0",
    "Player_7": "Mbeumo 19",
    "Player_2": "Kerkez 12",
    "Player_5": "Murillo 9",
    "Player_6": "M.Salah 14",
    "Player_3": "Hall 2",
    "Player_4": "Alexander-Arnold 0",
    "Player_8": "Palmer 10",
    "Player_9": "Vardy 5",
    "Player_15": "J.Timber 0"
  },
  {
    "manager_Name": "1,306( 119,388 ) TotalXfr : 16",
    "Teams": "Dwiz Mania( Dhawal Toppo )",
    "SXL": "India",
    "Latp": "75",
    "Player_1": "Raya 3",
    "Player_11": "Wood 8",
    "Player_10": "N.Jackson 2",
    "Player_12": "Henderson 2",
    "Player_13": "Cunha 0",
    "Player_14": "Rogers 0",
    "Player_7": "Palmer 10",
    "Player_2": "Gabriel 2",
    "Player_5": "Aina 6",
    "Player_6": "Milenkovi\u0107 6",
    "Player_3": "Pedro Porro 4",
    "Player_4": "Virgil 1",
    "Player_8": "M.Salah 14",
    "Player_9": "Mbeumo 19",
    "Player_15": "J.Murphy 5"
  },
  {
    "manager_Name": "1,296( 173,204 ) TotalXfr : 22",
    "Teams": "amp( Aditya Patil )",
    "SXL": "India",
    "Latp": "55",
    "Player_1": "Raya 3",
    "Player_11": "G.Jesus 2",
    "Player_10": "Isak 7",
    "Player_12": "Fabianski 0",
    "Player_13": "Amad 9",
    "Player_14": "Mykolenko 2",
    "Player_7": "Palmer 10",
    "Player_2": "Gabriel 2",
    "Player_5": "Lewis 2",
    "Player_6": "M.Salah 14",
    "Player_3": "Colwill 1",
    "Player_4": "Alexander-Arnold 0",
    "Player_8": "J.Murphy 5",
    "Player_9": "Jo\u00E3o Pedro 9",
    "Player_15": "Rogers 0"
  },
  {
    "manager_Name": "1,295( 179,771 ) TotalXfr : 24",
    "Teams": "Gooner_Psy( Saiprasad Shankar )",
    "SXL": "India",
    "Latp": "73",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Isak 7",
    "Player_10": "N.Jackson 2",
    "Player_12": "Verbruggen 2",
    "Player_13": "Nwaneri 6",
    "Player_14": "Quansah 0",
    "Player_7": "M.Salah 14",
    "Player_2": "Hall 2",
    "Player_5": "Palmer 10",
    "Player_6": "J.Murphy 5",
    "Player_3": "Gabriel 2",
    "Player_4": "Kerkez 12",
    "Player_8": "Foden 8",
    "Player_9": "Wood 8",
    "Player_15": "Mazraoui 1"
  },
  {
    "manager_Name": "1,290( 209,950 ) TotalXfr : 21",
    "Teams": "DangerDon( Rohit Nate )",
    "SXL": "India",
    "Latp": "59",
    "Player_1": "Flekken 6",
    "Player_11": "Isak 7",
    "Player_10": "G.Jesus 2",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Hall 2",
    "Player_14": "Rogers 0",
    "Player_7": "Palmer 10",
    "Player_2": "Saliba 2",
    "Player_5": "Colwill 1",
    "Player_6": "M.Salah 14",
    "Player_3": "Robinson 1",
    "Player_4": "Alexander-Arnold 0",
    "Player_8": "B.Fernandes 7",
    "Player_9": "Jo\u00E3o Pedro 9",
    "Player_15": "McNeil 0"
  },
  {
    "manager_Name": "1,284( 253,567 ) TotalXfr : 20",
    "Teams": "Banter FC( Johann Duckworth )",
    "SXL": "India",
    "Latp": "50",
    "Player_1": "Raya 3",
    "Player_11": "Isak 14",
    "Player_10": "N.Jackson 2",
    "Player_12": "Ward 0",
    "Player_13": "Cunha 0",
    "Player_14": "Rogers 0",
    "Player_7": "Palmer 10",
    "Player_2": "Hall 2",
    "Player_5": "Robinson 1",
    "Player_6": "Gordon 7",
    "Player_3": "Alexander-Arnold 0",
    "Player_4": "Mykolenko 2",
    "Player_8": "I.Sarr 2",
    "Player_9": "M.Salah 7",
    "Player_15": "Faes 1"
  },
  {
    "manager_Name": "1,280( 286,694 ) TotalXfr : 22",
    "Teams": "Holding Ream Cash( Karan Thorat )",
    "SXL": "India",
    "Latp": "58",
    "Player_1": "Raya 3",
    "Player_11": "Isak 7",
    "Player_10": "Wood 8",
    "Player_12": "Muric 0",
    "Player_13": "Jo\u00E3o Pedro 9",
    "Player_14": "Greaves 1",
    "Player_7": "Semenyo 3",
    "Player_2": "Alexander-Arnold 0",
    "Player_5": "M.Salah 14",
    "Player_6": "Gordon 7",
    "Player_3": "Gabriel 2",
    "Player_4": "Hall 2",
    "Player_8": "I.Sarr 2",
    "Player_9": "Palmer 10",
    "Player_15": "Mykolenko 2"
  },
  {
    "manager_Name": "1,271( 364,961 ) TotalXfr : 16",
    "Teams": "Deys Knights( Rohan Dey )",
    "SXL": "India",
    "Latp": "58",
    "Player_1": "Pickford 4",
    "Player_11": "Wood 8",
    "Player_10": "Isak 7",
    "Player_12": "Fabianski 0",
    "Player_13": "J.Timber 0",
    "Player_14": "Cunha 0",
    "Player_7": "Gordon 7",
    "Player_2": "Hall 2",
    "Player_5": "Enzo 1",
    "Player_6": "Palmer 10",
    "Player_3": "Gabriel 2",
    "Player_4": "Robinson 1",
    "Player_8": "M.Salah 14",
    "Player_9": "I.Sarr 2",
    "Player_15": "Harwood-Bellis -1"
  },
  {
    "manager_Name": "1,262( 471,500 ) TotalXfr : 22",
    "Teams": "lakaka( Kabeer Bhagat )",
    "SXL": "India",
    "Latp": "68",
    "Player_1": "Henderson 2",
    "Player_11": "Jo\u00E3o Pedro 9",
    "Player_10": "Isak 7",
    "Player_12": "Fabianski 0",
    "Player_13": "Burgess 0",
    "Player_14": "Smith Rowe 1",
    "Player_7": "Palmer 10",
    "Player_2": "Robinson 1",
    "Player_5": "M.Salah 14",
    "Player_6": "Kulusevski 2",
    "Player_3": "Hall 2",
    "Player_4": "Milenkovi\u0107 6",
    "Player_8": "B.Fernandes 7",
    "Player_9": "Wood 8",
    "Player_15": "J.Timber 0"
  },
  {
    "manager_Name": "1,261( 482,518 ) TotalXfr : 21",
    "Teams": "TYSM11( Tasdique Yasin )",
    "SXL": "India",
    "Latp": "79",
    "Player_1": "Sels 9",
    "Player_11": "Isak 7",
    "Player_10": "G.Jesus 2",
    "Player_12": "Flekken 6",
    "Player_13": "Amad 9",
    "Player_14": "Mazraoui 1",
    "Player_7": "M.Salah 14",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "Palmer 10",
    "Player_6": "Luis D\u00EDaz 1",
    "Player_3": "Robinson 1",
    "Player_4": "Aina 6",
    "Player_8": "Mbeumo 19",
    "Player_9": "Wood 8",
    "Player_15": "J.Timber 0"
  },
  {
    "manager_Name": "1,256( 546,204 ) TotalXfr : 20",
    "Teams": "SakaWakaXI( Deepti D )",
    "SXL": "India",
    "Latp": "73",
    "Player_1": "Raya 3",
    "Player_11": "Wood 8",
    "Player_10": "Isak 7",
    "Player_12": "Fabianski 0",
    "Player_13": "Jo\u00E3o Pedro 9",
    "Player_14": "Rogers 0",
    "Player_7": "Mbeumo 19",
    "Player_2": "Saliba 2",
    "Player_5": "Robinson 1",
    "Player_6": "Palmer 10",
    "Player_3": "Hall 2",
    "Player_4": "Aina 6",
    "Player_8": "M.Salah 14",
    "Player_9": "Martinelli 1",
    "Player_15": "Keane 0"
  },
  {
    "manager_Name": "1,253( 589,094 ) TotalXfr : 22",
    "Teams": "Sakalicous( Sachin thakur )",
    "SXL": "India",
    "Latp": "69",
    "Player_1": "Sels 9",
    "Player_11": "Isak 7",
    "Player_10": "Amad 9",
    "Player_12": "Kelleher 0",
    "Player_13": "Havertz 0",
    "Player_14": "Cunha 0",
    "Player_7": "Palmer 10",
    "Player_2": "A\u00EFt-Nouri 1",
    "Player_5": "Gabriel 2",
    "Player_6": "Aina 6",
    "Player_3": "Gvardiol 2",
    "Player_4": "Hall 2",
    "Player_8": "M.Salah 14",
    "Player_9": "Gordon 7",
    "Player_15": "Lavia 0"
  },
  {
    "manager_Name": "1,245( 706,646 ) TotalXfr : 22",
    "Teams": "Change Name( Puneet Gupta )",
    "SXL": "India",
    "Latp": "86",
    "Player_1": "Sels 9",
    "Player_11": "Haaland 13",
    "Player_10": "Isak 7",
    "Player_12": "Fabianski 0",
    "Player_13": "J.Timber 0",
    "Player_14": "Rogers 0",
    "Player_7": "Amad 9",
    "Player_2": "Hall 2",
    "Player_5": "Palmer 10",
    "Player_6": "M.Salah 14",
    "Player_3": "O\u0027Shea 0",
    "Player_4": "Kerkez 12",
    "Player_8": "I.Sarr 2",
    "Player_9": "Wood 8",
    "Player_15": "Harwood-Bellis -1"
  },
  {
    "manager_Name": "1,243( 739,305 ) TotalXfr : 25",
    "Teams": "Mushrooms of Europe( Nicholas Neyt )",
    "SXL": "Belgium",
    "Latp": "58",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "G.Jesus 2",
    "Player_10": "Isak 7",
    "Player_12": "Henderson 2",
    "Player_13": "Rogers 0",
    "Player_14": "Harwood-Bellis -1",
    "Player_7": "Palmer 10",
    "Player_2": "Robinson 1",
    "Player_5": "Cash 3",
    "Player_6": "M.Salah 14",
    "Player_3": "Hall 2",
    "Player_4": "Gabriel 2",
    "Player_8": "Enzo 1",
    "Player_9": "Haaland 13",
    "Player_15": "Bergvall 2"
  },
  {
    "manager_Name": "1,242( 757,990 ) TotalXfr : 29",
    "Teams": "Captain\u00D8( Jebarwocky JD )",
    "SXL": "USA",
    "Latp": "89",
    "Player_1": "Sels 9",
    "Player_11": "Wood 8",
    "Player_10": "Isak 7",
    "Player_12": "Ramsdale 1",
    "Player_13": "Wan-Bissaka 0",
    "Player_14": "Cunha 0",
    "Player_7": "Mbeumo 19",
    "Player_2": "Aina 6",
    "Player_5": "Palmer 10",
    "Player_6": "Luis D\u00EDaz 1",
    "Player_3": "Kerkez 12",
    "Player_4": "Mykolenko 2",
    "Player_8": "M.Salah 14",
    "Player_9": "Maddison 1",
    "Player_15": "Faes 1"
  },
  {
    "manager_Name": "1,239( 804,281 ) TotalXfr : 21",
    "Teams": "FALSE 9( Rohan Rai )",
    "SXL": "India",
    "Latp": "63",
    "Player_1": "Henderson 2",
    "Player_11": "Watkins 2",
    "Player_10": "N.Jackson 2",
    "Player_12": "Fabianski 0",
    "Player_13": "Rogers 0",
    "Player_14": "Kerkez 12",
    "Player_7": "Mbeumo 19",
    "Player_2": "Digne 2",
    "Player_5": "M.Salah 14",
    "Player_6": "Palmer 10",
    "Player_3": "Robinson 1",
    "Player_4": "Gabriel 2",
    "Player_8": "I.Sarr 2",
    "Player_9": "Isak 7",
    "Player_15": "Colwill 1"
  },
  {
    "manager_Name": "1,238( 824,288 ) TotalXfr : 25",
    "Teams": "Kounde Bhajji( Ronak Kapadia )",
    "SXL": "India",
    "Latp": "59",
    "Player_1": "Verbruggen 2",
    "Player_11": "Isak 7",
    "Player_10": "G.Jesus 2",
    "Player_12": "Fabianski 0",
    "Player_13": "Rogers 0",
    "Player_14": "J.Timber 0",
    "Player_7": "Foden 8",
    "Player_2": "Colwill 1",
    "Player_5": "M.Salah 14",
    "Player_6": "Eze 5",
    "Player_3": "Robinson 1",
    "Player_4": "Alexander-Arnold 0",
    "Player_8": "Palmer 10",
    "Player_9": "Jo\u00E3o Pedro 9",
    "Player_15": "Burgess 0"
  },
  {
    "manager_Name": "1,229( 980,095 ) TotalXfr : 19",
    "Teams": "CoolPalmsFc( Naveed Surve )",
    "SXL": "India",
    "Latp": "80",
    "Player_1": "Flekken 6",
    "Player_11": "Isak 7",
    "Player_10": "Wood 8",
    "Player_12": "Valdimarsson 0",
    "Player_13": "J.Timber 0",
    "Player_14": "Rogers 0",
    "Player_7": "Palmer 10",
    "Player_2": "Robinson 1",
    "Player_5": "Hall 2",
    "Player_6": "M.Salah 14",
    "Player_3": "Huijsen 8",
    "Player_4": "Wan-Bissaka 0",
    "Player_8": "Mbeumo 19",
    "Player_9": "J.Murphy 5",
    "Player_15": "Cunha 0"
  },
  {
    "manager_Name": "1,226( 1,037,806 ) TotalXfr : 21",
    "Teams": "Danzig( Engelbert Dsilva )",
    "SXL": "Chinese Taipei",
    "Latp": "54",
    "Player_1": "A.Becker 1",
    "Player_11": "Wood 8",
    "Player_10": "Isak 7",
    "Player_12": "Fabianski 0",
    "Player_13": "Bernardo 2",
    "Player_14": "Jo\u00E3o Pedro 9",
    "Player_7": "M.Salah 14",
    "Player_2": "Saliba 2",
    "Player_5": "Aina 6",
    "Player_6": "Luis D\u00EDaz 1",
    "Player_3": "Hall 2",
    "Player_4": "Cucurella 2",
    "Player_8": "Martinelli 1",
    "Player_9": "Palmer 10",
    "Player_15": "Burgess 0"
  },
  {
    "manager_Name": "1,226( 1,040,157 ) TotalXfr : 20",
    "Teams": "WengerBoys( Sanket Marwah )",
    "SXL": "India",
    "Latp": "62",
    "Player_1": "Sels 9",
    "Player_11": "Wood 8",
    "Player_10": "Gakpo 6",
    "Player_12": "Pope 0",
    "Player_13": "Rogers 0",
    "Player_14": "Cunha 0",
    "Player_7": "Johnson 2",
    "Player_2": "Pedro Porro 4",
    "Player_5": "Harwood-Bellis -1",
    "Player_6": "Palmer 10",
    "Player_3": "Gvardiol 2",
    "Player_4": "Robinson 1",
    "Player_8": "M.Salah 14",
    "Player_9": "B.Fernandes 7",
    "Player_15": "Okoli 1"
  },
  {
    "manager_Name": "1,225( 1,057,580 ) TotalXfr : 20",
    "Teams": "Kishore\u2019s Rascals( Nandakishore K )",
    "SXL": "India",
    "Latp": "82",
    "Player_1": "Henderson 2",
    "Player_11": "Haaland 13",
    "Player_10": "Ra\u00FAl 13",
    "Player_12": "Fabianski 0",
    "Player_13": "Rogers 0",
    "Player_14": "Colwill 1",
    "Player_7": "Gordon 7",
    "Player_2": "Saliba 2",
    "Player_5": "M.Salah 14",
    "Player_6": "Enzo 1",
    "Player_3": "Robinson 1",
    "Player_4": "Van den Berg 10",
    "Player_8": "Palmer 10",
    "Player_9": "Jo\u00E3o Pedro 9",
    "Player_15": "Greaves 1"
  },
  {
    "manager_Name": "1,225( 1,064,464 ) TotalXfr : 23",
    "Teams": "RED_DEVils_XI( Devraj Redkar )",
    "SXL": "England",
    "Latp": "56",
    "Player_1": "Sels 9",
    "Player_11": "Isak 7",
    "Player_10": "Wood 8",
    "Player_12": "Raya 3",
    "Player_13": "N.Jackson 2",
    "Player_14": "Zabarnyi 7",
    "Player_7": "Enzo 1",
    "Player_2": "Gvardiol 2",
    "Player_5": "Alexander-Arnold 0",
    "Player_6": "M.Salah 14",
    "Player_3": "Robinson 1",
    "Player_4": "Gabriel 2",
    "Player_8": "Iwobi 2",
    "Player_9": "Palmer 10",
    "Player_15": "Amad 9"
  },
  {
    "manager_Name": "1,220( 1,159,548 ) TotalXfr : 19",
    "Teams": "Fantasy Xi( Daniel Gekonge )",
    "SXL": "Kenya",
    "Latp": "75",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Isak 7",
    "Player_10": "Wood 8",
    "Player_12": "Henderson 2",
    "Player_13": "Ra\u00FAl 13",
    "Player_14": "Hall 2",
    "Player_7": "M.Salah 14",
    "Player_2": "Gabriel 2",
    "Player_5": "Kulusevski 2",
    "Player_6": "Palmer 10",
    "Player_3": "Alexander-Arnold 0",
    "Player_4": "Robinson 1",
    "Player_8": "Mbeumo 19",
    "Player_9": "Amad 9",
    "Player_15": "A\u00EFt-Nouri 1"
  },
  {
    "manager_Name": "1,220( 1,165,441 ) TotalXfr : 23",
    "Teams": "Jurgen\u0027s Kop( Prathamesh Manjrekar )",
    "SXL": "India",
    "Latp": "80",
    "Player_1": "Flekken 6",
    "Player_11": "Isak 7",
    "Player_10": "Maddison 1",
    "Player_12": "Verbruggen 2",
    "Player_13": "Delap 8",
    "Player_14": "Cunha 0",
    "Player_7": "M.Salah 14",
    "Player_2": "Mu\u00F1oz 2",
    "Player_5": "Digne 2",
    "Player_6": "Milenkovi\u0107 6",
    "Player_3": "Kerkez 12",
    "Player_4": "Robinson 1",
    "Player_8": "Mbeumo 19",
    "Player_9": "Palmer 10",
    "Player_15": "Rogers 0"
  },
  {
    "manager_Name": "1,220( 1,165,441 ) TotalXfr : 22",
    "Teams": "Licha al-Gaib( Hardit S )",
    "SXL": "Canada",
    "Latp": "88",
    "Player_1": "Raya 3",
    "Player_11": "Isak 7",
    "Player_10": "Ra\u00FAl 13",
    "Player_12": "Fabianski 0",
    "Player_13": "Colwill 1",
    "Player_14": "Rogers 0",
    "Player_7": "Palmer 10",
    "Player_2": "Aina 6",
    "Player_5": "Mbeumo 19",
    "Player_6": "Gordon 7",
    "Player_3": "Robinson 1",
    "Player_4": "Alexander-Arnold 0",
    "Player_8": "M.Salah 14",
    "Player_9": "Wood 8",
    "Player_15": "Greaves 1"
  },
  {
    "manager_Name": "1,218( 1,207,126 ) TotalXfr : 23",
    "Teams": "Kamada Dragons( Rohan Kapre )",
    "SXL": "India",
    "Latp": "80",
    "Player_1": "Sels 9",
    "Player_11": "Ra\u00FAl 13",
    "Player_10": "Evanilson 2",
    "Player_12": "Valdimarsson 0",
    "Player_13": "Mitoma 1",
    "Player_14": "Rogers 0",
    "Player_7": "Foden 8",
    "Player_2": "Cucurella 2",
    "Player_5": "Kerkez 12",
    "Player_6": "M.Salah 14",
    "Player_3": "Robinson 1",
    "Player_4": "Gabriel 2",
    "Player_8": "Palmer 10",
    "Player_9": "Isak 7",
    "Player_15": "Tuanzebe 0"
  },
  {
    "manager_Name": "1,217( 1,224,962 ) TotalXfr : 21",
    "Teams": "Amigo\u0027s_13( Rakesh Dake )",
    "SXL": "India",
    "Latp": "64",
    "Player_1": "Flekken 6",
    "Player_11": "Isak 7",
    "Player_10": "Watkins 2",
    "Player_12": "Turner 0",
    "Player_13": "Schade 8",
    "Player_14": "Enzo 1",
    "Player_7": "Palmer 10",
    "Player_2": "Gvardiol 2",
    "Player_5": "Kerkez 12",
    "Player_6": "\u00D8degaard 1",
    "Player_3": "Gabriel 2",
    "Player_4": "Aina 6",
    "Player_8": "M.Salah 14",
    "Player_9": "Strand Larsen 2",
    "Player_15": "Mu\u00F1oz 2"
  },
  {
    "manager_Name": "1,216( 1,254,337 ) TotalXfr : 29",
    "Teams": "Shadows FC( Altab Rahi )",
    "SXL": "India",
    "Latp": "83",
    "Player_1": "Sels 9",
    "Player_11": "Mateta 8",
    "Player_10": "Isak 7",
    "Player_12": "Kelleher 0",
    "Player_13": "Davis 0",
    "Player_14": "Rogers 0",
    "Player_7": "Palmer 10",
    "Player_2": "Milenkovi\u0107 6",
    "Player_5": "M.Salah 14",
    "Player_6": "\u00D8degaard 1",
    "Player_3": "Kerkez 12",
    "Player_4": "Robinson 1",
    "Player_8": "Gordon 7",
    "Player_9": "Wood 8",
    "Player_15": "J.Timber 0"
  },
  {
    "manager_Name": "1,215( 1,262,348 ) TotalXfr : 18",
    "Teams": "Arsenal( Kunal Modi )",
    "SXL": "India",
    "Latp": "57",
    "Player_1": "Henderson 2",
    "Player_11": "Isak 7",
    "Player_10": "Wood 8",
    "Player_12": "Fabianski 0",
    "Player_13": "Mazraoui 1",
    "Player_14": "J.Timber 0",
    "Player_7": "Palmer 10",
    "Player_2": "Gabriel 2",
    "Player_5": "Dibling 2",
    "Player_6": "M.Salah 14",
    "Player_3": "Hall 2",
    "Player_4": "Alexander-Arnold 0",
    "Player_8": "Martinelli 1",
    "Player_9": "Jo\u00E3o Pedro 9",
    "Player_15": "Rogers 0"
  },
  {
    "manager_Name": "1,213( 1,304,416 ) TotalXfr : 17",
    "Teams": "Arsene\u0027s Avengers( Abhijay Khatry )",
    "SXL": "India",
    "Latp": "74",
    "Player_1": "Sels 9",
    "Player_11": "Wood 8",
    "Player_10": "Isak 7",
    "Player_12": "Fabianski 0",
    "Player_13": "Jo\u00E3o Pedro 9",
    "Player_14": "Greaves 1",
    "Player_7": "Mbeumo 19",
    "Player_2": "Alexander-Arnold 0",
    "Player_5": "Palmer 10",
    "Player_6": "M.Salah 14",
    "Player_3": "Mu\u00F1oz 2",
    "Player_4": "Gabriel 2",
    "Player_8": "Luis D\u00EDaz 1",
    "Player_9": "Dibling 2",
    "Player_15": "Mykolenko 2"
  },
  {
    "manager_Name": "1,213( 1,318,804 ) TotalXfr : 28",
    "Teams": "EniObankeAraFC( Specs Fad )",
    "SXL": "Nigeria",
    "Latp": "87",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Haaland 13",
    "Player_10": "G.Jesus 2",
    "Player_12": "Turner 0",
    "Player_13": "Smith Rowe 1",
    "Player_14": "Quansah 0",
    "Player_7": "Mbeumo 19",
    "Player_2": "Kerkez 12",
    "Player_5": "Semenyo 3",
    "Player_6": "M.Salah 14",
    "Player_3": "Hall 2",
    "Player_4": "Robinson 1",
    "Player_8": "Palmer 10",
    "Player_9": "Wood 8",
    "Player_15": "Harwood-Bellis -1"
  },
  {
    "manager_Name": "1,212( 1,334,354 ) TotalXfr : 21",
    "Teams": "Blistering Barnacles( Sushanta Mondal )",
    "SXL": "India",
    "Latp": "65",
    "Player_1": "Henderson 2",
    "Player_11": "Wood 8",
    "Player_10": "Isak 7",
    "Player_12": "Fabianski 0",
    "Player_13": "Havertz 0",
    "Player_14": "Rogers 0",
    "Player_7": "M.Salah 14",
    "Player_2": "Gabriel 2",
    "Player_5": "Colwill 1",
    "Player_6": "Mitoma 1",
    "Player_3": "Robinson 1",
    "Player_4": "Kerkez 12",
    "Player_8": "Gordon 7",
    "Player_9": "Palmer 10",
    "Player_15": "Faes 1"
  },
  {
    "manager_Name": "1,211( 1,354,073 ) TotalXfr : 19",
    "Teams": "GoonerXI( Siddharth Kamath )",
    "SXL": "USA",
    "Latp": "57",
    "Player_1": "Flekken 6",
    "Player_11": "Wood 8",
    "Player_10": "Isak 7",
    "Player_12": "Turner 0",
    "Player_13": "Havertz 0",
    "Player_14": "Barco 0",
    "Player_7": "Luis D\u00EDaz 1",
    "Player_2": "Wan-Bissaka 0",
    "Player_5": "Palmer 10",
    "Player_6": "J.Murphy 5",
    "Player_3": "Saliba 2",
    "Player_4": "Hall 2",
    "Player_8": "M.Salah 14",
    "Player_9": "Winks 2",
    "Player_15": "Harwood-Bellis -1"
  },
  {
    "manager_Name": "1,209( 1,395,789 ) TotalXfr : 19",
    "Teams": "kalafiori( Adarsh Pakala )",
    "SXL": "Hong Kong",
    "Latp": "69",
    "Player_1": "Raya 3",
    "Player_11": "Wood 8",
    "Player_10": "Jo\u00E3o Pedro 9",
    "Player_12": "S\u00E1nchez 3",
    "Player_13": "Dibling 2",
    "Player_14": "Wan-Bissaka 0",
    "Player_7": "Kluivert 3",
    "Player_2": "Gabriel 2",
    "Player_5": "\u00D8degaard 1",
    "Player_6": "M.Salah 7",
    "Player_3": "Virgil 1",
    "Player_4": "Huijsen 8",
    "Player_8": "Palmer 20",
    "Player_9": "Isak 7",
    "Player_15": "Van Hecke 2"
  },
  {
    "manager_Name": "1,208( 1,426,620 ) TotalXfr : 22",
    "Teams": "Leothrix FC( Tanmay Dey )",
    "SXL": "India",
    "Latp": "82",
    "Player_1": "Sels 9",
    "Player_11": "Isak 7",
    "Player_10": "Solanke 9",
    "Player_12": "Henderson 2",
    "Player_13": "A\u00EFt-Nouri 1",
    "Player_14": "Greaves 1",
    "Player_7": "Palmer 10",
    "Player_2": "Virgil 1",
    "Player_5": "Iwobi 2",
    "Player_6": "M.Salah 14",
    "Player_3": "Konsa 2",
    "Player_4": "Robinson 1",
    "Player_8": "Mbeumo 19",
    "Player_9": "Wood 8",
    "Player_15": "Rogers 0"
  },
  {
    "manager_Name": "1,207( 1,447,465 ) TotalXfr : 21",
    "Teams": "Ashburton Grove FC( Zafar Khan )",
    "SXL": "India",
    "Latp": "50",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Isak 7",
    "Player_10": "N.Jackson 2",
    "Player_12": "Ward 0",
    "Player_13": "I.Sarr 2",
    "Player_14": "Johnson 1",
    "Player_7": "Iwobi 2",
    "Player_2": "Alexander-Arnold 0",
    "Player_5": "A\u00EFt-Nouri 1",
    "Player_6": "M.Salah 14",
    "Player_3": "Gabriel 2",
    "Player_4": "Robinson 1",
    "Player_8": "Palmer 10",
    "Player_9": "Wood 8",
    "Player_15": "Rogers 0"
  },
  {
    "manager_Name": "1,206( 1,480,525 ) TotalXfr : 33",
    "Teams": "Nawaz\u0027s balls \u26BD( Nawaz Ahmed )",
    "SXL": "United Arab Emirates",
    "Latp": "53",
    "Player_1": "Henderson 2",
    "Player_11": "Isak 7",
    "Player_10": "Wood 8",
    "Player_12": "Raya 3",
    "Player_13": "Rogers 0",
    "Player_14": "J.Timber 0",
    "Player_7": "Martinelli 1",
    "Player_2": "Aina 6",
    "Player_5": "M.Salah 14",
    "Player_6": "Kulusevski 2",
    "Player_3": "A\u00EFt-Nouri 1",
    "Player_4": "Alexander-Arnold 0",
    "Player_8": "Palmer 10",
    "Player_9": "N.Jackson 2",
    "Player_15": "Hall 2"
  },
  {
    "manager_Name": "1,203( 1,538,818 ) TotalXfr : 19",
    "Teams": "Jaanbaaz Shikari( Saurabh Mittal )",
    "SXL": "India",
    "Latp": "57",
    "Player_1": "Henderson 2",
    "Player_11": "Isak 7",
    "Player_10": "Wissa 11",
    "Player_12": "Fabianski 0",
    "Player_13": "Rogers 0",
    "Player_14": "Strand Larsen 2",
    "Player_7": "M.Salah 14",
    "Player_2": "Aina 6",
    "Player_5": "Virgil 1",
    "Player_6": "\u00D8degaard 1",
    "Player_3": "Gabriel 2",
    "Player_4": "Robinson 1",
    "Player_8": "Kulusevski 2",
    "Player_9": "Palmer 10",
    "Player_15": "Greaves 1"
  },
  {
    "manager_Name": "1,200( 1,613,157 ) TotalXfr : 21",
    "Teams": "Don\u2019t Jimmy Me Jules( Raunak Lamsal )",
    "SXL": "Nepal",
    "Latp": "77",
    "Player_1": "Raya 3",
    "Player_11": "Jo\u00E3o Pedro 9",
    "Player_10": "Solanke 9",
    "Player_12": "Fabianski 0",
    "Player_13": "Rogers 0",
    "Player_14": "Mitoma 1",
    "Player_7": "Palmer 10",
    "Player_2": "Virgil 1",
    "Player_5": "Mykolenko 2",
    "Player_6": "Mbeumo 19",
    "Player_3": "Castagne 1",
    "Player_4": "Gabriel 2",
    "Player_8": "M.Salah 14",
    "Player_9": "Isak 7",
    "Player_15": "Greaves 1"
  },
  {
    "manager_Name": "1,200( 1,618,342 ) TotalXfr : 25",
    "Teams": "miskharege fc( Jordan D\u0027Almeida )",
    "SXL": "India",
    "Latp": "59",
    "Player_1": "Flekken 6",
    "Player_11": "N.Jackson 2",
    "Player_10": "Isak 7",
    "Player_12": "Fabianski 0",
    "Player_13": "Bowen 0",
    "Player_14": "Greaves 1",
    "Player_7": "Amad 9",
    "Player_2": "Saliba 2",
    "Player_5": "A\u00EFt-Nouri 1",
    "Player_6": "Luis D\u00EDaz 1",
    "Player_3": "Virgil 1",
    "Player_4": "Aina 6",
    "Player_8": "M.Salah 14",
    "Player_9": "Palmer 10",
    "Player_15": "Stewart 0"
  },
  {
    "manager_Name": "1,200( 1,621,099 ) TotalXfr : 27",
    "Teams": "XGALX( Dhearika Ramadhanty )",
    "SXL": "Indonesia",
    "Latp": "83",
    "Player_1": "Raya 3",
    "Player_11": "Isak 7",
    "Player_10": "Wood 8",
    "Player_12": "Pickford 4",
    "Player_13": "I.Sarr 2",
    "Player_14": "Muniz 1",
    "Player_7": "Mbeumo 19",
    "Player_2": "Aina 6",
    "Player_5": "Huijsen 8",
    "Player_6": "J.Murphy 5",
    "Player_3": "Gabriel 2",
    "Player_4": "Virgil 1",
    "Player_8": "Palmer 10",
    "Player_9": "M.Salah 14",
    "Player_15": "Young 2"
  },
  {
    "manager_Name": "1,199( 1,631,553 ) TotalXfr : 19",
    "Teams": "Pep\u2019s Boys( Kayaan Shah )",
    "SXL": "India",
    "Latp": "73",
    "Player_1": "Raya 3",
    "Player_11": "Wood 8",
    "Player_10": "Gakpo 6",
    "Player_12": "Pickford 4",
    "Player_13": "Cucurella 2",
    "Player_14": "J.Murphy 5",
    "Player_7": "Palmer 20",
    "Player_2": "Pedro Porro 4",
    "Player_5": "M.Salah 7",
    "Player_6": "Gibbs-White 8",
    "Player_3": "Saliba 2",
    "Player_4": "Hall 2",
    "Player_8": "Elanga 6",
    "Player_9": "Isak 7",
    "Player_15": "Mykolenko 2"
  },
  {
    "manager_Name": "1,199( 1,631,553 ) TotalXfr : 19",
    "Teams": "Here for Beer( Gaurav K )",
    "SXL": "India",
    "Latp": "64",
    "Player_1": "Sels 9",
    "Player_11": "Wood 8",
    "Player_10": "N.Jackson 2",
    "Player_12": "Fabianski 0",
    "Player_13": "Rogers 0",
    "Player_14": "Gomez 0",
    "Player_7": "M.Salah 14",
    "Player_2": "Gabriel 2",
    "Player_5": "Amad 9",
    "Player_6": "I.Sarr 2",
    "Player_3": "Hall 2",
    "Player_4": "Harwood-Bellis -1",
    "Player_8": "Palmer 10",
    "Player_9": "Isak 7",
    "Player_15": "Mazraoui 1"
  },
  {
    "manager_Name": "1,199( 1,641,367 ) TotalXfr : 22",
    "Teams": "ABXI( Abhijit Sawant )",
    "SXL": "India",
    "Latp": "76",
    "Player_1": "S\u00E1nchez 3",
    "Player_11": "Gakpo 6",
    "Player_10": "Wood 8",
    "Player_12": "Turner 0",
    "Player_13": "Keane 0",
    "Player_14": "Smith Rowe 1",
    "Player_7": "M.Salah 14",
    "Player_2": "Alexander-Arnold 0",
    "Player_5": "Gordon 7",
    "Player_6": "Mbeumo 19",
    "Player_3": "Burn 1",
    "Player_4": "Colwill 1",
    "Player_8": "Palmer 10",
    "Player_9": "Isak 7",
    "Player_15": "Johnson 1"
  },
  {
    "manager_Name": "1,198( 1,659,170 ) TotalXfr : 21",
    "Teams": "Slumdog Mignolet( Xerxes Khambatta )",
    "SXL": "India",
    "Latp": "50",
    "Player_1": "Raya 3",
    "Player_11": "Isak 7",
    "Player_10": "N.Jackson 2",
    "Player_12": "Fabianski 0",
    "Player_13": "Jo\u00E3o Pedro 9",
    "Player_14": "Greaves 1",
    "Player_7": "Diogo J. 1",
    "Player_2": "Aina 6",
    "Player_5": "Lewis 2",
    "Player_6": "M.Salah 14",
    "Player_3": "Colwill 1",
    "Player_4": "Hall 2",
    "Player_8": "Palmer 10",
    "Player_9": "I.Sarr 2",
    "Player_15": "Rogers 0"
  },
  {
    "manager_Name": "1,198( 1,669,061 ) TotalXfr : 26",
    "Teams": "Y2K( Yatnesh Kamat )",
    "SXL": "India",
    "Latp": "80",
    "Player_1": "Sels 9",
    "Player_11": "Isak 7",
    "Player_10": "Wood 8",
    "Player_12": "Turner 0",
    "Player_13": "Rogers 0",
    "Player_14": "J.Timber 0",
    "Player_7": "Palmer 10",
    "Player_2": "Robinson 1",
    "Player_5": "Harwood-Bellis -1",
    "Player_6": "Mbeumo 19",
    "Player_3": "Hall 2",
    "Player_4": "Aina 6",
    "Player_8": "J.Murphy 5",
    "Player_9": "M.Salah 14",
    "Player_15": "Cunha 0"
  },
  {
    "manager_Name": "1,196( 1,702,467 ) TotalXfr : 17",
    "Teams": "Predators( Ruchik Shirode )",
    "SXL": "India",
    "Latp": "62",
    "Player_1": "Onana 2",
    "Player_11": "Watkins 2",
    "Player_10": "Isak 7",
    "Player_12": "Fabianski 0",
    "Player_13": "J.Timber 0",
    "Player_14": "Amad 9",
    "Player_7": "Palmer 10",
    "Player_2": "Milenkovi\u0107 6",
    "Player_5": "Martinelli 1",
    "Player_6": "B.Fernandes 7",
    "Player_3": "Hall 2",
    "Player_4": "Mu\u00F1oz 2",
    "Player_8": "M.Salah 14",
    "Player_9": "Jo\u00E3o Pedro 9",
    "Player_15": "Colwill 1"
  },
  {
    "manager_Name": "1,196( 1,708,083 ) TotalXfr : 19",
    "Teams": "kopside( Hemanth SD )",
    "SXL": "India",
    "Latp": "60",
    "Player_1": "A.Becker -",
    "Player_11": "Isak -",
    "Player_10": "N.Jackson -",
    "Player_12": "Valdimarsson -",
    "Player_13": "Jo\u00E3o Pedro -",
    "Player_14": "Amad -",
    "Player_7": "J.Murphy -",
    "Player_2": "Virgil -",
    "Player_5": "Kerkez -",
    "Player_6": "Palmer -",
    "Player_3": "Pedro Porro -",
    "Player_4": "Gabriel -",
    "Player_8": "M.Salah -",
    "Player_9": "Iwobi -",
    "Player_15": "Colwill -"
  }
];