var s = [
   {
      "manager_Name":"Sahil Lampard",
      "Teams":"MarxUnited",
      "Player_1":"Ramsdale 8",
      "Player_2":"Alexander-Arnold 2",
      "Player_3":"James 0",
      "Player_4":"Cancelo 2",
      "Player_5":"Son 0",
      "Player_6":"Benrahma 0",
      "Player_7":"Bernardo 2",
      "Player_8":"Salah 0$ captain",
      "Player_9":"Hudson-Odoi 6",
      "Player_10":"Dennis -1, BUR (A)",
      "Player_11":"Maupay 5",
      "Player_12":"Sánchez 4",
      "Player_13":"Livramento 0",
      "Player_14":"Archer 0",
      "Player_15":"White 8",
      "SXL":"24",
      "Bench":"1195",
      "Count  ":"1,956,118"
   },
   {
      "manager_Name":"Saurabh Tamang",
      "Teams":"Lucky FC",
      "Player_1":"Sánchez 4",
      "Player_2":"Cancelo 2",
      "Player_3":"Alexander-Arnold 2",
      "Player_4":"Coady 2",
      "Player_5":"Gray 2",
      "Player_6":"Smith Rowe 3",
      "Player_7":"Bowen 2",
      "Player_8":"Gallagher 1",
      "Player_9":"Bernardo 2",
      "Player_10":"Dennis -1, BUR (A)",
      "Player_11":"Ronaldo 4$ captain",
      "Player_12":"Guaita 2",
      "Player_13":"Livramento 0",
      "Player_14":"Omobamidele 0",
      "Player_15":"Archer 0",
      "SXL":"23",
      "Bench":"1132",
      "Count  ":"3,022,767"
   },
   {
      "manager_Name":"Pranesh Sharma",
      "Teams":"Immortal FC",
      "Player_1":"Foster 0, BUR (A)",
      "Player_2":"Coufal 7",
      "Player_3":"White 8",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Raphinha 2",
      "Player_6":"Mount 6",
      "Player_7":"De Bruyne 8",
      "Player_8":"Foden 2",
      "Player_9":"King 4, BUR (A)$ captain",
      "Player_10":"Dennis -1, BUR (A)",
      "Player_11":"Ronaldo 2",
      "Player_12":"Sánchez 4",
      "Player_13":"Gallagher 1",
      "Player_14":"Tsimikas 0",
      "Player_15":"Dier 1",
      "SXL":"40",
      "Bench":"1297",
      "Count  ":"682,515"
   },
   {
      "manager_Name":"Sanjeev Kumar",
      "Teams":"GAROBADHA UNITED",
      "Player_1":"Foster 0, BUR (A)",
      "Player_2":"Cancelo 2",
      "Player_3":"Alexander-Arnold 2",
      "Player_4":"Tierney 8",
      "Player_5":"White 8",
      "Player_6":"De Bruyne 8",
      "Player_7":"Bowen 2",
      "Player_8":"Jota 5",
      "Player_9":"Raphinha 2",
      "Player_10":"Maddison 2",
      "Player_11":"Dennis -2, BUR (A)$ captain",
      "Player_12":"Lloris 2",
      "Player_13":"Edouard 8",
      "Player_14":"Broja 2",
      "Player_15":"Dalot 9",
      "SXL":"37",
      "Bench":"1340",
      "Count  ":"371,561"
   },
   {
      "manager_Name":"Kumar Anku",
      "Teams":"The Børderland Fc",
      "Player_1":"Bachmann 1, BUR (A)",
      "Player_2":"Alexander-Arnold 2",
      "Player_3":"Mings 6",
      "Player_4":"Varane 8",
      "Player_5":"Cancelo 2",
      "Player_6":"Sissoko 2, BUR (A)",
      "Player_7":"Fernandes 3",
      "Player_8":"Mac Allister 2",
      "Player_9":"King 4, BUR (A)$ captain",
      "Player_10":"Kane 2",
      "Player_11":"Ronaldo 2",
      "Player_12":"Arrizabalaga 8",
      "Player_13":"Mbeumo 5",
      "Player_14":"Davies 1",
      "Player_15":"Winks 2",
      "SXL":"34",
      "Bench":"1255",
      "Count  ":"1,116,056"
   },
   {
      "manager_Name":"Kushal Sahota",
      "Teams":"FC ASSASSINS",
      "Player_1":"Ramsdale 8",
      "Player_2":"Dias 2",
      "Player_3":"Reguilón 0",
      "Player_4":"Duffy 0",
      "Player_5":"Jota 5",
      "Player_6":"Bowen 2",
      "Player_7":"Gallagher 1",
      "Player_8":"Salah 0",
      "Player_9":"Dennis -1, BUR (A)",
      "Player_10":"Antonio 2",
      "Player_11":"Ronaldo 4$ captain",
      "Player_12":"Steele 0",
      "Player_13":"Allan 0",
      "Player_14":"Tsimikas 0",
      "Player_15":"Livramento 0",
      "SXL":"23",
      "Bench":"1117",
      "Count  ":"3,288,472"
   },
   {
      "manager_Name":"Regean Lama",
      "Teams":"BUSBY BABIES 2",
      "Player_1":"Sánchez 4",
      "Player_2":"Veltman 2",
      "Player_3":"Alexander-Arnold 2",
      "Player_4":"Tierney 8",
      "Player_5":"Jota 5",
      "Player_6":"Bernardo 2",
      "Player_7":"Maddison 2",
      "Player_8":"Bowen 2",
      "Player_9":"King 4, BUR (A)$ captain",
      "Player_10":"Ronaldo 2",
      "Player_11":"Kane 2",
      "Player_12":"Carson 0",
      "Player_13":"Coufal 7",
      "Player_14":"Pinnock 1",
      "Player_15":"Ødegaard 3",
      "SXL":"35",
      "Bench":"1302",
      "Count  ":"641,919"
   },
   {
      "manager_Name":"pranam rai",
      "Teams":"SYAKREE FC",
      "Player_1":"Sánchez 4",
      "Player_2":"Alexander-Arnold 2",
      "Player_3":"Dias 2",
      "Player_4":"Tsimikas 0",
      "Player_5":"Bernardo 2",
      "Player_6":"Ødegaard 3",
      "Player_7":"Mount 6",
      "Player_8":"Højbjerg 2",
      "Player_9":"Dennis -1, BUR (A)",
      "Player_10":"Ronaldo 4$ captain",
      "Player_11":"Antonio 2",
      "Player_12":"Lloris 2",
      "Player_13":"Salah 0",
      "Player_14":"Saïss 0",
      "Player_15":"Manquillo 4",
      "SXL":"26",
      "Bench":"1265",
      "Count  ":"997,263"
   },
   {
      "manager_Name":"Ashim Lama",
      "Teams":"⚔️FURY⚔️",
      "Player_1":"Lloris 2",
      "Player_2":"Gabriel 6",
      "Player_3":"Cancelo 2",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Bowen 2",
      "Player_6":"Coutinho 3",
      "Player_7":"Martinelli 3",
      "Player_8":"Gallagher 1",
      "Player_9":"Antonio 2",
      "Player_10":"Ronaldo 2",
      "Player_11":"Dennis -2, BUR (A)$ captain",
      "Player_12":"Ward 0",
      "Player_13":"Gray 2",
      "Player_14":"Jansson 0",
      "Player_15":"Reguilón 0",
      "SXL":"23",
      "Bench":"1281",
      "Count  ":"829,886"
   },
   {
      "manager_Name":"Vivek Pradhan",
      "Teams":"PEPPERBOX83",
      "Player_1":"Sánchez 4",
      "Player_2":"Alexander-Arnold 2",
      "Player_3":"Cancelo 2",
      "Player_4":"Reguilón 0",
      "Player_5":"Smith Rowe 3",
      "Player_6":"Jota 10$ captain",
      "Player_7":"Sissoko 2, BUR (A)",
      "Player_8":"Raphinha 2",
      "Player_9":"King 2, BUR (A)",
      "Player_10":"Toney 7",
      "Player_11":"Dennis -1, BUR (A)",
      "Player_12":"Raya 0",
      "Player_13":"Dias 2",
      "Player_14":"Salah 0",
      "Player_15":"Pinnock 1",
      "SXL":"33",
      "Bench":"1331",
      "Count  ":"424,302"
   },
   {
      "manager_Name":"Sibin _",
      "Teams":"F95",
      "Player_1":"Ramsdale 8",
      "Player_2":"Dias 2",
      "Player_3":"Rüdiger 7",
      "Player_4":"Robertson 11",
      "Player_5":"Reguilón 0",
      "Player_6":"Smith Rowe 3",
      "Player_7":"Bernardo 2",
      "Player_8":"Mount 6",
      "Player_9":"King 2, BUR (A)",
      "Player_10":"Dennis -2, BUR (A)$ captain",
      "Player_11":"Ronaldo 2",
      "Player_12":"Ederson 2",
      "Player_13":"Alonso 1",
      "Player_14":"Lucas Moura 1",
      "Player_15":"Gallagher 1",
      "SXL":"41",
      "Bench":"1318",
      "Count  ":"514,983"
   },
   {
      "manager_Name":"Omkar Subba",
      "Teams":"Omk09",
      "Player_1":"Alisson 3",
      "Player_2":"Rüdiger 7",
      "Player_3":"Alexander-Arnold 2",
      "Player_4":"Cancelo 2",
      "Player_5":"Tierney 8",
      "Player_6":"Coutinho 3",
      "Player_7":"Fred 3",
      "Player_8":"Bowen 2",
      "Player_9":"Fernandes 3",
      "Player_10":"Dennis -2, BUR (A)$ captain",
      "Player_11":"Ronaldo 2",
      "Player_12":"Ramsdale 8",
      "Player_13":"Toney 7",
      "Player_14":"Højbjerg 2",
      "Player_15":"Jansson 0",
      "SXL":"33",
      "Bench":"1242",
      "Count  ":"1,280,139"
   },
   {
      "manager_Name":"Indrajeet Singh",
      "Teams":"Kung Fu Pandoos",
      "Player_1":"Foster 0, BUR (A)",
      "Player_2":"Tierney 8",
      "Player_3":"Laporte 10",
      "Player_4":"van Dijk 8",
      "Player_5":"White 8",
      "Player_6":"Bernardo 2",
      "Player_7":"Jota 5",
      "Player_8":"Sterling 1",
      "Player_9":"Raphinha 2",
      "Player_10":"Kane 2",
      "Player_11":"King 4, BUR (A)$ captain",
      "Player_12":"Lloris 2",
      "Player_13":"Matip 2",
      "Player_14":"Maupay 5",
      "Player_15":"Gilmour 0",
      "SXL":"50",
      "Bench":"1202",
      "Count  ":"1,845,350"
   },
   {
      "manager_Name":"Rishi Thulung",
      "Teams":"PL CG FC",
      "Player_1":"Ramsdale 8",
      "Player_2":"Alonso 1",
      "Player_3":"Alexander-Arnold 2",
      "Player_4":"Cancelo 2",
      "Player_5":"Bowen 2",
      "Player_6":"Raphinha 2",
      "Player_7":"Lucas Moura 1",
      "Player_8":"Jota 5",
      "Player_9":"Antonio 2",
      "Player_10":"Dennis -2, BUR (A)$ captain",
      "Player_11":"King 2, BUR (A)",
      "Player_12":"de Gea 6",
      "Player_13":"Lamptey 1",
      "Player_14":"Marçal 0",
      "Player_15":"Mount 6",
      "SXL":"25",
      "Bench":"1284",
      "Count  ":"799,959"
   },
   {
      "manager_Name":"Dipen Thapa",
      "Teams":"BW4_11",
      "Player_1":"Sá 1",
      "Player_2":"Gabriel 6",
      "Player_3":"Dias 2",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Tomiyasu 0",
      "Player_6":"Bernardo 2",
      "Player_7":"Jota 5",
      "Player_8":"Fernandes 3",
      "Player_9":"Dennis -2, BUR (A)$ captain",
      "Player_10":"Antonio 2",
      "Player_11":"Watkins 2",
      "Player_12":"Sánchez 4",
      "Player_13":"Livramento 0",
      "Player_14":"Gallagher 1",
      "Player_15":"Soucek 2",
      "SXL":"23",
      "Bench":"1244",
      "Count  ":"1,254,578"
   },
   {
      "manager_Name":"Nishant Singh",
      "Teams":"beta",
      "Player_1":"Ramsdale 8",
      "Player_2":"Reguilón 0",
      "Player_3":"Cancelo 2",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Bowen 2",
      "Player_6":"Fernandes 6$ captain",
      "Player_7":"Jota 5",
      "Player_8":"Foden 2",
      "Player_9":"King 2, BUR (A)",
      "Player_10":"Antonio 2",
      "Player_11":"Dennis -1, BUR (A)",
      "Player_12":"Sánchez 4",
      "Player_13":"Smith Rowe 3",
      "Player_14":"Livramento 0",
      "Player_15":"Tomiyasu 0",
      "SXL":"30",
      "Bench":"1242",
      "Count  ":"1,280,668"
   },
   {
      "manager_Name":"Ashish Subba",
      "Teams":"Gustavous Gunner",
      "Player_1":"Foster 0, BUR (A)",
      "Player_2":"Lowton 0, WAT (H)",
      "Player_3":"Cancelo 2",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Gallagher 1",
      "Player_6":"Bernardo 2",
      "Player_7":"Fernandes 3",
      "Player_8":"Raphinha 2",
      "Player_9":"Maddison 2",
      "Player_10":"Dennis -2, BUR (A)$ captain",
      "Player_11":"Antonio 2",
      "Player_12":"Ramsdale 8",
      "Player_13":"Rüdiger 7",
      "Player_14":"White 8",
      "Player_15":"Obafemi 0",
      "SXL":"14",
      "Bench":"1285",
      "Count  ":"790,808"
   },
   {
      "manager_Name":"Rohan Rai",
      "Teams":"False 9",
      "Player_1":"Ramsdale 8",
      "Player_2":"Tomiyasu 0",
      "Player_3":"Cancelo 2",
      "Player_4":"Laporte 10",
      "Player_5":"Jota 5",
      "Player_6":"De Bruyne 8",
      "Player_7":"Raphinha 2",
      "Player_8":"Fernandes 3",
      "Player_9":"Bowen 2",
      "Player_10":"Antonio 2",
      "Player_11":"Dennis -2, BUR (A)$ captain",
      "Player_12":"de Gea 6",
      "Player_13":"Toney 7",
      "Player_14":"Coufal 7",
      "Player_15":"Livramento 0",
      "SXL":"40",
      "Bench":"1406",
      "Count  ":"105,469"
   },
   {
      "manager_Name":"Raj Kanango",
      "Teams":"Weightloss Coach",
      "Player_1":"de Gea 6",
      "Player_2":"Cancelo 2",
      "Player_3":"Alexander-Arnold 2",
      "Player_4":"Tierney 8",
      "Player_5":"De Bruyne 8",
      "Player_6":"Fernandes 3",
      "Player_7":"Bowen 2",
      "Player_8":"Jota 5",
      "Player_9":"Antonio 2",
      "Player_10":"Dennis -2, BUR (A)$ captain",
      "Player_11":"King 2, BUR (A)",
      "Player_12":"Carson 0",
      "Player_13":"Amartey 2",
      "Player_14":"Davies 1",
      "Player_15":"Bissouma 0",
      "SXL":"38",
      "Bench":"1332",
      "Count  ":"422,015"
   },
   {
      "manager_Name":"Gaurav Shrestha",
      "Teams":"Fußball-Mannschaft",
      "Player_1":"Foster 0, BUR (A)",
      "Player_2":"Alexander-Arnold 2",
      "Player_3":"Cancelo 2",
      "Player_4":"Tierney 8",
      "Player_5":"Bowen 2",
      "Player_6":"Raphinha 2",
      "Player_7":"Foden 4$ captain",
      "Player_8":"Jota 5",
      "Player_9":"Antonio 2",
      "Player_10":"Ronaldo 2",
      "Player_11":"Watkins 2",
      "Player_12":"de Gea 6",
      "Player_13":"Digne 12",
      "Player_14":"Gallagher 1",
      "Player_15":"Livramento 0",
      "SXL":"31",
      "Bench":"1402",
      "Count  ":"115,238"
   },
   {
      "manager_Name":"Bishal Rai",
      "Teams":"Gooner for Life 037",
      "Player_1":"Ramsdale 8",
      "Player_2":"Alexander-Arnold 2",
      "Player_3":"Alonso 1",
      "Player_4":"Cancelo 2",
      "Player_5":"Foden 2",
      "Player_6":"Trossard 2",
      "Player_7":"Jota 5",
      "Player_8":"Bowen 2",
      "Player_9":"King 2, BUR (A)",
      "Player_10":"Antonio 2",
      "Player_11":"Dennis -2, BUR (A)$ captain",
      "Player_12":"de Gea 6",
      "Player_13":"Gray 2",
      "Player_14":"Rüdiger 7",
      "Player_15":"Coufal 7",
      "SXL":"26",
      "Bench":"1387",
      "Count  ":"161,614"
   },
   {
      "manager_Name":"RAJIYUNG Sun",
      "Teams":"hansing",
      "Player_1":"Alisson 3",
      "Player_2":"Alexander-Arnold 2",
      "Player_3":"Laporte 10",
      "Player_4":"Cancelo 2",
      "Player_5":"White 8",
      "Player_6":"Bowen 2",
      "Player_7":"Fernandes 3",
      "Player_8":"Saka 3",
      "Player_9":"De Bruyne 8",
      "Player_10":"Antonio 2",
      "Player_11":"Dennis -2, BUR (A)$ captain",
      "Player_12":"Steer 0",
      "Player_13":"Reguilón 0",
      "Player_14":"Gallagher 1",
      "Player_15":"Broja 2",
      "SXL":"41",
      "Bench":"1317",
      "Count  ":"523,924"
   },
   {
      "manager_Name":"Ashish Rai",
      "Teams":"Deadhead",
      "Player_1":"Foster 0, BUR (A)",
      "Player_2":"Cancelo 2",
      "Player_3":"Digne 12",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Bowen 2",
      "Player_6":"Mount 6",
      "Player_7":"Jota 5",
      "Player_8":"Bernardo 2",
      "Player_9":"Jiménez 0",
      "Player_10":"Kane 2",
      "Player_11":"João Pedro 4, BUR (A)$ captain",
      "Player_12":"Ramsdale 8",
      "Player_13":"Williams 7",
      "Player_14":"Smith Rowe 3",
      "Player_15":"Livramento 0",
      "SXL":"37",
      "Bench":"1341",
      "Count  ":"368,494"
   },
   {
      "manager_Name":"prabin kumar",
      "Teams":"Prabin Singh",
      "Player_1":"Mendy 0",
      "Player_2":"Rüdiger 7",
      "Player_3":"Alonso 1",
      "Player_4":"Dias 2",
      "Player_5":"Benrahma 0",
      "Player_6":"Greenwood 3",
      "Player_7":"Townsend 1",
      "Player_8":"Son 0",
      "Player_9":"Jiménez 0",
      "Player_10":"Antonio 2",
      "Player_11":"Aubameyang 0$ captain",
      "Player_12":"Foster 0, BUR (A)",
      "Player_13":"Shaw 0",
      "Player_14":"Tsimikas 0",
      "Player_15":"Bissouma 0",
      "SXL":"16",
      "Bench":"962",
      "Count  ":"5,848,888"
   },
   {
      "manager_Name":"Ravish Verma",
      "Teams":"Marijuana Fields FC",
      "Player_1":"Ramsdale 8",
      "Player_2":"Cancelo 2",
      "Player_3":"White 8",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Cash 5",
      "Player_6":"Jota 5",
      "Player_7":"Bowen 2",
      "Player_8":"Fernandes 3",
      "Player_9":"Antonio 2",
      "Player_10":"King 4, BUR (A)$ captain",
      "Player_11":"Ronaldo 2",
      "Player_12":"Guaita 2",
      "Player_13":"Gray 2",
      "Player_14":"Gallagher 1",
      "Player_15":"Livramento 0",
      "SXL":"43",
      "Bench":"1360",
      "Count  ":"267,775"
   },
   {
      "manager_Name":"Prayash Thapa",
      "Teams":"abcde FC",
      "Player_1":"Foster 0, BUR (A)",
      "Player_2":"Cancelo 2",
      "Player_3":"Alexander-Arnold 2",
      "Player_4":"Laporte 10",
      "Player_5":"Bowen 2",
      "Player_6":"Jota 5",
      "Player_7":"Fernandes 3",
      "Player_8":"Gray 2",
      "Player_9":"Dennis -2, BUR (A)$ captain",
      "Player_10":"King 2, BUR (A)",
      "Player_11":"Antonio 2",
      "Player_12":"de Gea 6",
      "Player_13":"Alonso 1",
      "Player_14":"Douglas Luiz 3",
      "Player_15":"Reguilón 0",
      "SXL":"28",
      "Bench":"1447",
      "Count  ":"32,659"
   },
   {
      "manager_Name":"Tenzing Ninjey",
      "Teams":"One Step Beyond 026*",
      "Player_1":"Ramsdale 8",
      "Player_2":"Cancelo 2",
      "Player_3":"Reguilón 0",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Foden 2",
      "Player_6":"Mount 6",
      "Player_7":"Jota 5",
      "Player_8":"Bowen 2",
      "Player_9":"Antonio 2",
      "Player_10":"Dennis -2, BUR (A)$ captain",
      "Player_11":"King 2, BUR (A)",
      "Player_12":"Bachmann 1, BUR (A)",
      "Player_13":"Gündogan 0",
      "Player_14":"Dawson 2",
      "Player_15":"Livramento 0",
      "SXL":"29",
      "Bench":"1299",
      "Count  ":"669,300"
   },
   {
      "manager_Name":"Harsh Raval",
      "Teams":"Up the Bees",
      "Player_1":"Foster 0, BUR (A)",
      "Player_2":"Dias 2",
      "Player_3":"Cancelo 2",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Tierney 8",
      "Player_6":"Gray 2",
      "Player_7":"Harrison 2",
      "Player_8":"Jota 5",
      "Player_9":"Calvert-Lewin 1",
      "Player_10":"King 4, BUR (A)$ captain",
      "Player_11":"Ronaldo 2",
      "Player_12":"de Gea 6",
      "Player_13":"Bowen 2",
      "Player_14":"Keane 0",
      "Player_15":"Ramsey 3",
      "SXL":"30",
      "Bench":"1406",
      "Count  ":"105,229"
   },
   {
      "manager_Name":"PRAYAS BAJGAI",
      "Teams":"MCFC@1894",
      "Player_1":"Foster 0, BUR (A)",
      "Player_2":"Alexander-Arnold 2",
      "Player_3":"Dalot 9",
      "Player_4":"Cancelo 2",
      "Player_5":"Martinelli 3",
      "Player_6":"Bowen 2",
      "Player_7":"Jota 5",
      "Player_8":"De Bruyne 8",
      "Player_9":"Dennis -1, BUR (A)",
      "Player_10":"Kane 2",
      "Player_11":"King 4, BUR (A)$ captain",
      "Player_12":"de Gea 6",
      "Player_13":"Gallagher 1",
      "Player_14":"Davies 1",
      "Player_15":"James 0",
      "SXL":"36",
      "Bench":"1420",
      "Count  ":"74,363"
   },
   {
      "manager_Name":"AVIJIT DAS",
      "Teams":"Roing FC",
      "Player_1":"Foster 0, BUR (A)",
      "Player_2":"Laporte 10",
      "Player_3":"Cancelo 2",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Fernandes 3",
      "Player_6":"Jota 5",
      "Player_7":"Bowen 2",
      "Player_8":"Gray 2",
      "Player_9":"Watkins 2",
      "Player_10":"Dennis -2, BUR (A)$ captain",
      "Player_11":"Ronaldo 2",
      "Player_12":"de Gea 6",
      "Player_13":"Smith Rowe 3",
      "Player_14":"Burn 1",
      "Player_15":"Livramento 0",
      "SXL":"28",
      "Bench":"1376",
      "Count  ":"201,968"
   },
   {
      "manager_Name":"Abhijeet Singh",
      "Teams":"WEIGHTLOSS COACH",
      "Player_1":"Foster 0, BUR (A)",
      "Player_2":"Dias 2",
      "Player_3":"Cancelo 2",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"De Bruyne 16$ captain",
      "Player_6":"Bowen 2",
      "Player_7":"Jota 5",
      "Player_8":"Raphinha 2",
      "Player_9":"Lacazette 2",
      "Player_10":"Antonio 2",
      "Player_11":"Dennis -1, BUR (A)",
      "Player_12":"Lloris 2",
      "Player_13":"Smith Rowe 3",
      "Player_14":"Manquillo 4",
      "Player_15":"James 0",
      "SXL":"34",
      "Bench":"1426",
      "Count  ":"62,172"
   },
   {
      "manager_Name":"SATYAM RAI",
      "Teams":"PINE",
      "Player_1":"Foster 0, BUR (A)",
      "Player_2":"Alonso 1",
      "Player_3":"Cancelo 2",
      "Player_4":"Alexander-Arnold 2",
      "Player_5":"Jota 5",
      "Player_6":"Gray 2",
      "Player_7":"De Bruyne 8",
      "Player_8":"Bowen 2",
      "Player_9":"Dennis -1, BUR (A)",
      "Player_10":"Ronaldo 2",
      "Player_11":"King 4, BUR (A)$ captain",
      "Player_12":"Ramsdale 8",
      "Player_13":"Gallagher 1",
      "Player_14":"Livramento 0",
      "Player_15":"James 0",
      "SXL":"27",
      "Bench":"1402",
      "Count  ":"116,267"
   }
]