var s = [
  {
    "manager_Name": "1,208( 144,250 ) TotalXfr : 19",
    "Teams": "Humbesi( ~ Kopi ~ )",
    "SXL": "Albania",
    "Latp": "66",
    "Player_1": "Raya\r BRE (A)",
    "Player_11": "Isak\r 6",
    "Player_10": "Jo\u00E3o Pedro\r 8",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Rogers\r 9",
    "Player_14": "Huijsen\r 1",
    "Player_7": "Enzo\r 1",
    "Player_2": "Alexander-Arnold\r 15",
    "Player_5": "Palmer\r 2",
    "Player_6": "B.Fernandes\r 0",
    "Player_3": "Castagne\r 1",
    "Player_4": "Gabriel\r BRE (A)",
    "Player_8": "M.Salah\r 32",
    "Player_9": "N.Jackson\r 1",
    "Player_15": "Mykolenko\r 1"
  },
  {
    "manager_Name": "1,074( 2,598,292 ) TotalXfr : 20",
    "Teams": "Supercampeones( Ronny Nelkenbaum )",
    "SXL": "France",
    "Latp": "68",
    "Player_1": "Sels\r 6",
    "Player_11": "Wood\r 12",
    "Player_10": "Isak\r 6",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Hall\r 9",
    "Player_14": "Kluivert\r 0",
    "Player_7": "Luis D\u00EDaz\r 9",
    "Player_2": "Mu\u00F1oz\r 2",
    "Player_5": "Robinson\r 4",
    "Player_6": "M.Salah\r 16",
    "Player_3": "Gabriel\r BRE (A)",
    "Player_4": "Colwill\r 0",
    "Player_8": "Palmer\r 4",
    "Player_9": "Rogers\r 9",
    "Player_15": "Lankshear\r 0"
  },
  {
    "manager_Name": "1,160( 608,637 ) TotalXfr : 22",
    "Teams": "Jelly Flood( Lorin Minxhozi )",
    "SXL": "England",
    "Latp": "62",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "N.Jackson\r 1",
    "Player_10": "Isak\r 6",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 8",
    "Player_14": "Kerkez\r 1",
    "Player_7": "M.Salah\r 32",
    "Player_2": "Robinson\r 4",
    "Player_5": "Rogers\r 9",
    "Player_6": "Mbeumo\r ARS (H)",
    "Player_3": "J.Timber\r BRE (A)",
    "Player_4": "Gabriel\r BRE (A)",
    "Player_8": "Palmer\r 2",
    "Player_9": "Gordon\r 6",
    "Player_15": "Greaves\r 6"
  },
  {
    "manager_Name": "1,108( 1,656,392 ) TotalXfr : 17",
    "Teams": "#SorareMarin( Marin Jano )",
    "SXL": "Albania",
    "Latp": "68",
    "Player_1": "Sels\r 6",
    "Player_11": "Cunha\r 1",
    "Player_10": "Isak\r 6",
    "Player_12": "Flekken\r ARS (H)",
    "Player_13": "Gu\u00E9hi\r 0",
    "Player_14": "Hall\r 9",
    "Player_7": "Maddison\r 1",
    "Player_2": "Pedro Porro\r 4",
    "Player_5": "Rogers\r 9",
    "Player_6": "Gordon\r 6",
    "Player_3": "Cucurella\r 1",
    "Player_4": "Gabriel\r BRE (A)",
    "Player_8": "Palmer\r 2",
    "Player_9": "M.Salah\r 32",
    "Player_15": "Chiwome\r 0"
  },
  {
    "manager_Name": "1,157( 652,683 ) TotalXfr : 21",
    "Teams": "Wiggler FC( Andrew Carr )",
    "SXL": "England",
    "Latp": "65",
    "Player_1": "Henderson\r 2",
    "Player_11": "Wood\r 12",
    "Player_10": "Cunha\r 1",
    "Player_12": "Valdimarsson\r ARS (H)",
    "Player_13": "Pau\r 1",
    "Player_14": "Lankshear\r 0",
    "Player_7": "Enzo\r 1",
    "Player_2": "J.Timber\r BRE (A)",
    "Player_5": "Son\r 0",
    "Player_6": "M.Salah\r 32",
    "Player_3": "Gabriel\r BRE (A)",
    "Player_4": "Robertson\r 6",
    "Player_8": "Palmer\r 2",
    "Player_9": "Luis D\u00EDaz\r 9",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "1,101( 1,837,438 ) TotalXfr : 17",
    "Teams": "Data Crisis( Camilla Nurkhanov )",
    "SXL": "England",
    "Latp": "87",
    "Player_1": "Raya\r BRE (A)",
    "Player_11": "Ra\u00FAl\r 9",
    "Player_10": "Cunha\r 1",
    "Player_12": "Turner\r 0",
    "Player_13": "Young\r 1",
    "Player_14": "Kluivert\r 0",
    "Player_7": "M.Salah\r 32",
    "Player_2": "Gvardiol\r 6",
    "Player_5": "Hall\r 9",
    "Player_6": "Amad\r 2",
    "Player_3": "Alexander-Arnold\r 15",
    "Player_4": "Pedro Porro\r 4",
    "Player_8": "Enzo\r 1",
    "Player_9": "Haaland\r 8",
    "Player_15": "Damsgaard\r ARS (H)"
  },
  {
    "manager_Name": "1,081( 2,403,969 ) TotalXfr : 25",
    "Teams": "Iwobi Wan-Kenobi( Sunit Patel )",
    "SXL": "England",
    "Latp": "70",
    "Player_1": "Raya\r BRE (A)",
    "Player_11": "N.Jackson\r 1",
    "Player_10": "Cunha\r 1",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Amad\r 2",
    "Player_14": "Mykolenko\r 1",
    "Player_7": "M.Salah\r 32",
    "Player_2": "Robinson\r 4",
    "Player_5": "Martinelli\r BRE (A)",
    "Player_6": "Palmer\r 2",
    "Player_3": "J.Timber\r BRE (A)",
    "Player_4": "Alexander-Arnold\r 15",
    "Player_8": "Rogers\r 9",
    "Player_9": "Isak\r 6",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "1,115( 1,491,192 ) TotalXfr : 20",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "India",
    "Latp": "59",
    "Player_1": "Henderson\r 2",
    "Player_11": "Cunha\r 1",
    "Player_10": "G.Jesus\r BRE (A)",
    "Player_12": "Fabianski\r 0",
    "Player_13": "B.Fernandes\r 0",
    "Player_14": "Kluivert\r 0",
    "Player_7": "Johnson\r 9",
    "Player_2": "J.Timber\r BRE (A)",
    "Player_5": "Dalot\r 1",
    "Player_6": "Milenkovi\u0107\r 6",
    "Player_3": "Burn\r 6",
    "Player_4": "Saliba\r BRE (A)",
    "Player_8": "M.Salah\r 32",
    "Player_9": "Palmer\r 2",
    "Player_15": "Armstrong\r 5"
  },
  {
    "manager_Name": "1,044( 3,473,580 ) TotalXfr : 18",
    "Teams": "Enter Team Name( teo teo )",
    "SXL": "Italy",
    "Latp": "72",
    "Player_1": "S\u00E1nchez\r 0",
    "Player_11": "Isak\r 6",
    "Player_10": "Cunha\r 1",
    "Player_12": "Flekken\r ARS (H)",
    "Player_13": "Konsa\r 1",
    "Player_14": "Kluivert\r 0",
    "Player_7": "Palmer\r 2",
    "Player_2": "Gvardiol\r 6",
    "Player_5": "Rogers\r 9",
    "Player_6": "Maddison\r 1",
    "Player_3": "Virgil\r 6",
    "Player_4": "Kerkez\r 1",
    "Player_8": "M.Salah\r 32",
    "Player_9": "Jo\u00E3o Pedro\r 8",
    "Player_15": "Tuanzebe\r 0"
  },
  {
    "manager_Name": "994( 4,898,237 ) TotalXfr : 16",
    "Teams": "Sniper( Florian Toslluku )",
    "SXL": "Albania",
    "Latp": "48",
    "Player_1": "Henderson\r 2",
    "Player_11": "N.Jackson\r 1",
    "Player_10": "Havertz\r BRE (A)",
    "Player_12": "Ederson M.\r 0",
    "Player_13": "Stewart\r 0",
    "Player_14": "Alex Moreno\r 0",
    "Player_7": "Maddison\r 1",
    "Player_2": "Alexander-Arnold\r 15",
    "Player_5": "Gordon\r 6",
    "Player_6": "Thomas\r BRE (A)",
    "Player_3": "Virgil\r 6",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "B.Fernandes\r 0",
    "Player_9": "M.Salah\r 16",
    "Player_15": "Andersen\r 0"
  },
  {
    "manager_Name": "1,125( 1,246,192 ) TotalXfr : 15",
    "Teams": "Blue Boys \uFFFD( Ilir B )",
    "SXL": "England",
    "Latp": "66",
    "Player_1": "S\u00E1nchez\r 0",
    "Player_11": "Wood\r 12",
    "Player_10": "Cunha\r 1",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Yarmoliuk\r ARS (H)",
    "Player_14": "Keane\r 0",
    "Player_7": "Iwobi\r 2",
    "Player_2": "Aina\r 8",
    "Player_5": "Palmer\r 2",
    "Player_6": "Mbeumo\r ARS (H)",
    "Player_3": "Huijsen\r 1",
    "Player_4": "Harwood-Bellis\r 0",
    "Player_8": "M.Salah\r 32",
    "Player_9": "Haaland\r 8",
    "Player_15": "Disasi\r 1"
  },
  {
    "manager_Name": "976( 5,383,558 ) TotalXfr : 9",
    "Teams": "Ibis Warriors( Harmeet Chana )",
    "SXL": "England",
    "Latp": "52",
    "Player_1": "Raya\r BRE (A)",
    "Player_11": "Ra\u00FAl\r 9",
    "Player_10": "Haaland\r 16",
    "Player_12": "Turner\r 0",
    "Player_13": "Adama\r 1",
    "Player_14": "Harwood-Bellis\r 0",
    "Player_7": "Onana\r 1",
    "Player_2": "Saliba\r BRE (A)",
    "Player_5": "Palmer\r 2",
    "Player_6": "Smith Rowe\r 1",
    "Player_3": "Digne\r 1",
    "Player_4": "Robertson\r 6",
    "Player_8": "M.Salah\r 16",
    "Player_9": "Welbeck\r 0",
    "Player_15": "Barco\r 0"
  },
  {
    "manager_Name": "993( 4,923,799 ) TotalXfr : 14",
    "Teams": "Inceneratori( Geri Muho )",
    "SXL": "USA",
    "Latp": "58",
    "Player_1": "Raya\r BRE (A)",
    "Player_11": "N.Jackson\r 1",
    "Player_10": "Wissa\r ARS (H)",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Yarmoliuk\r ARS (H)",
    "Player_14": "Harwood-Bellis\r 0",
    "Player_7": "M.Salah\r 32",
    "Player_2": "A\u00EFt-Nouri\r 10",
    "Player_5": "Bernardo\r 3",
    "Player_6": "Madueke\r 2",
    "Player_3": "Gvardiol\r 6",
    "Player_4": "Saliba\r BRE (A)",
    "Player_8": "Palmer\r 2",
    "Player_9": "Vardy\r 2",
    "Player_15": "Greaves\r 6"
  },
  {
    "manager_Name": "1,022( 4,120,152 ) TotalXfr : 22",
    "Teams": "5-D( Erald Haxhiu )",
    "SXL": "USA",
    "Latp": "78",
    "Player_1": "Raya\r BRE (A)",
    "Player_11": "Havertz\r BRE (A)",
    "Player_10": "Wissa\r ARS (H)",
    "Player_12": "Cahill\r 0",
    "Player_13": "Luis D\u00EDaz\r 9",
    "Player_14": "Bowen\r 1",
    "Player_7": "Elanga\r 6",
    "Player_2": "Pedro Porro\r 4",
    "Player_5": "Lewis\r 6",
    "Player_6": "Mbeumo\r ARS (H)",
    "Player_3": "Hall\r 9",
    "Player_4": "Alexander-Arnold\r 15",
    "Player_8": "M.Salah\r 32",
    "Player_9": "Isak\r 6",
    "Player_15": "Mykolenko\r 1"
  },
  {
    "manager_Name": "1,053( 3,211,510 ) TotalXfr : 19",
    "Teams": "Herr Direktor( Roger Shehu )",
    "SXL": "Netherlands",
    "Latp": "81",
    "Player_1": "Jos\u00E9 S\u00E1\r 6",
    "Player_11": "N.Jackson\r 1",
    "Player_10": "Isak\r 6",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Mbeumo\r ARS (H)",
    "Player_14": "Bednarek\r 0",
    "Player_7": "Amad\r 2",
    "Player_2": "Quansah\r 1",
    "Player_5": "M.Salah\r 32",
    "Player_6": "Palmer\r 2",
    "Player_3": "Gvardiol\r 6",
    "Player_4": "Alexander-Arnold\r 15",
    "Player_8": "Maddison\r 1",
    "Player_9": "Ra\u00FAl\r 9",
    "Player_15": "Davis\r 5"
  },
  {
    "manager_Name": "962( 5,762,959 ) TotalXfr : 19",
    "Teams": "Tokenized Maxi \u26A1\uFE0F( Eni Shtini )",
    "SXL": "Albania",
    "Latp": "51",
    "Player_1": "D\u00FAbravka\r 6",
    "Player_11": "Cunha\r 1",
    "Player_10": "Solanke\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Semenyo\r 5",
    "Player_14": "A\u00EFt-Nouri\r 10",
    "Player_7": "Palmer\r 4",
    "Player_2": "Gabriel\r BRE (A)",
    "Player_5": "Gordon\r 6",
    "Player_6": "Rogers\r 9",
    "Player_3": "J.Timber\r BRE (A)",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "M.Salah\r 16",
    "Player_9": "Isak\r 6",
    "Player_15": "Mosquera\r 0"
  },
  {
    "manager_Name": "920( 6,795,932 ) TotalXfr : 8",
    "Teams": "RoboKoop( Enio Minxhozi )",
    "SXL": "Albania",
    "Latp": "65",
    "Player_1": "Raya\r BRE (A)",
    "Player_11": "Haaland\r 16",
    "Player_10": "Isak\r 6",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Harwood-Bellis\r 0",
    "Player_14": "Chiwome\r 0",
    "Player_7": "Buonanotte\r 2",
    "Player_2": "Alexander-Arnold\r 15",
    "Player_5": "Rogers\r 9",
    "Player_6": "Eze\r 10",
    "Player_3": "Mazraoui\r 1",
    "Player_4": "Gvardiol\r 6",
    "Player_8": "Mbeumo\r ARS (H)",
    "Player_9": "Son\r 0",
    "Player_15": "A.Phillips\r 0"
  },
  {
    "manager_Name": "867( 7,939,730 ) TotalXfr : 20",
    "Teams": "Yaya( Bardhyl Minxhozi )",
    "SXL": "Albania",
    "Latp": "49",
    "Player_1": "Henderson\r 2",
    "Player_11": "Broja\r 2",
    "Player_10": "Kulusevski\r 5",
    "Player_12": "Ederson M.\r 0",
    "Player_13": "De Ligt\r 1",
    "Player_14": "Jo\u00E3o Pedro\r 8",
    "Player_7": "Luis D\u00EDaz\r 9",
    "Player_2": "Saliba\r BRE (A)",
    "Player_5": "Digne\r 1",
    "Player_6": "M.Salah\r 16",
    "Player_3": "Pedro Porro\r 4",
    "Player_4": "Robertson\r 6",
    "Player_8": "Trossard\r BRE (A)",
    "Player_9": "Palmer\r 4",
    "Player_15": "Scarlett\r 0"
  },
  {
    "manager_Name": "1,014( 4,339,374 ) TotalXfr : 17",
    "Teams": "Kokeqethurit( Daver Berberi )",
    "SXL": "Albania",
    "Latp": "75",
    "Player_1": "Raya\r BRE (A)",
    "Player_11": "Wood\r 12",
    "Player_10": "Isak\r 6",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Hall\r 9",
    "Player_14": "Welbeck\r 0",
    "Player_7": "Enzo\r 1",
    "Player_2": "Gabriel\r BRE (A)",
    "Player_5": "Cucurella\r 1",
    "Player_6": "Palmer\r 2",
    "Player_3": "Gvardiol\r 6",
    "Player_4": "Lewis\r 6",
    "Player_8": "Rogers\r 9",
    "Player_9": "M.Salah\r 32",
    "Player_15": "Smith Rowe\r 1"
  },
  {
    "manager_Name": "887( 7,536,710 ) TotalXfr : 16",
    "Teams": "Leftisti( Magi Muco )",
    "SXL": "Albania",
    "Latp": "55",
    "Player_1": "Fabianski\r 0",
    "Player_11": "Strand Larsen\r 6",
    "Player_10": "Haaland\r 16",
    "Player_12": "S\u00E1nchez\r 0",
    "Player_13": "Lewis-Skelly\r BRE (A)",
    "Player_14": "Faes\r 0",
    "Player_7": "Luis D\u00EDaz\r 9",
    "Player_2": "Hall\r 9",
    "Player_5": "Madueke\r 2",
    "Player_6": "Palmer\r 2",
    "Player_3": "Pedro Porro\r 4",
    "Player_4": "Lewis\r 6",
    "Player_8": "Maddison\r 1",
    "Player_9": "Havertz\r BRE (A)",
    "Player_15": "Quansah\r 1"
  }
];