var s = [
  {
    "manager_Name": "1,288( 9,139 ) TotalXfr : 17",
    "Teams": "YoroOYoro( Rajdeep Gupta )",
    "SXL": "India",
    "Latp": "72",
    "Player_1": "Raya\r 2",
    "Player_11": "N.Jackson\r 1",
    "Player_10": "Isak\r 7",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Amad\r 2",
    "Player_14": "Hall\r 12",
    "Player_7": "Rogers\r 11",
    "Player_2": "Gabriel\r 2",
    "Player_5": "M.Salah\r 32",
    "Player_6": "Palmer\r 2",
    "Player_3": "Colwill\r 0",
    "Player_4": "Robinson\r 4",
    "Player_8": "I.Sarr\r 2",
    "Player_9": "Jo\u00E3o Pedro\r 9",
    "Player_15": "Burgess\r 0"
  },
  {
    "manager_Name": "1,274( 19,017 ) TotalXfr : 15",
    "Teams": "Gunners 24( Suumit Bhardwaj )",
    "SXL": "India",
    "Latp": "78",
    "Player_1": "Raya\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 9",
    "Player_10": "Isak\r 7",
    "Player_12": "Flekken\r 1",
    "Player_13": "Wissa\r 2",
    "Player_14": "Bowen\r 1",
    "Player_7": "M.Salah\r 32",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Robinson\r 4",
    "Player_6": "Palmer\r 2",
    "Player_3": "Mu\u00F1oz\r 2",
    "Player_4": "Virgil\r 6",
    "Player_8": "Mitoma\r 1",
    "Player_9": "Rogers\r 11",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "1,232( 122,987 ) TotalXfr : 20",
    "Teams": "Banter FC( Johann Duckworth )",
    "SXL": "India",
    "Latp": "84",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 7",
    "Player_10": "N.Jackson\r 1",
    "Player_12": "Ward\r 0",
    "Player_13": "Rogers\r 11",
    "Player_14": "Mykolenko\r 1",
    "Player_7": "M.Salah\r 32",
    "Player_2": "Hall\r 12",
    "Player_5": "I.Sarr\r 2",
    "Player_6": "Gordon\r 6",
    "Player_3": "Robinson\r 4",
    "Player_4": "Alexander-Arnold\r 15",
    "Player_8": "Palmer\r 2",
    "Player_9": "Cunha\r 1",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "1,228( 141,667 ) TotalXfr : 19",
    "Teams": "DangerDon( Rohit Nate )",
    "SXL": "India",
    "Latp": "84",
    "Player_1": "Flekken\r 1",
    "Player_11": "Isak\r 7",
    "Player_10": "N.Jackson\r 1",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Hall\r 12",
    "Player_14": "B.Fernandes\r 0",
    "Player_7": "Palmer\r 2",
    "Player_2": "Saliba\r 2",
    "Player_5": "Colwill\r 0",
    "Player_6": "M.Salah\r 32",
    "Player_3": "Robinson\r 4",
    "Player_4": "Alexander-Arnold\r 15",
    "Player_8": "Rogers\r 11",
    "Player_9": "Jo\u00E3o Pedro\r 9",
    "Player_15": "McNeil\r 0"
  },
  {
    "manager_Name": "1,225( 157,798 ) TotalXfr : 20",
    "Teams": "amp( Aditya Patil )",
    "SXL": "India",
    "Latp": "95",
    "Player_1": "Raya\r 2",
    "Player_11": "G.Jesus\r 9",
    "Player_10": "Isak\r 7",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Amad\r 2",
    "Player_14": "Mykolenko\r 1",
    "Player_7": "Palmer\r 2",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Lewis\r 6",
    "Player_6": "M.Salah\r 32",
    "Player_3": "Colwill\r 0",
    "Player_4": "Alexander-Arnold\r 15",
    "Player_8": "Rogers\r 11",
    "Player_9": "Jo\u00E3o Pedro\r 9",
    "Player_15": "Kluivert\r 0"
  },
  {
    "manager_Name": "1,223( 166,454 ) TotalXfr : 17",
    "Teams": "Va Va Voom( Piyush R )",
    "SXL": "USA",
    "Latp": "106",
    "Player_1": "Sels\r 6",
    "Player_11": "Isak\r 7",
    "Player_10": "Wood\r 12",
    "Player_12": "Flekken\r 1",
    "Player_13": "Vardy\r 2",
    "Player_14": "Smith Rowe\r 1",
    "Player_7": "M.Salah\r 32",
    "Player_2": "J.Timber\r 1",
    "Player_5": "Alexander-Arnold\r 15",
    "Player_6": "Rogers\r 11",
    "Player_3": "Kerkez\r 1",
    "Player_4": "Hall\r 12",
    "Player_8": "Mbeumo\r 7",
    "Player_9": "Palmer\r 2",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "1,222( 175,132 ) TotalXfr : 21",
    "Teams": "Gooner_Psy( Saiprasad Shankar )",
    "SXL": "India",
    "Latp": "77",
    "Player_1": "S\u00E1nchez\r 0",
    "Player_11": "Isak\r 7",
    "Player_10": "N.Jackson\r 1",
    "Player_12": "Verbruggen\r 2",
    "Player_13": "Jo\u00E3o Pedro\r 9",
    "Player_14": "Mazraoui\r 1",
    "Player_7": "M.Salah\r 32",
    "Player_2": "Hall\r 12",
    "Player_5": "Palmer\r 2",
    "Player_6": "J.Murphy\r 3",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Kerkez\r 1",
    "Player_8": "Foden\r 6",
    "Player_9": "Rogers\r 11",
    "Player_15": "Quansah\r 1"
  },
  {
    "manager_Name": "1,220( 183,434 ) TotalXfr : 16",
    "Teams": "Dwiz Mania( Dhawal Toppo )",
    "SXL": "India",
    "Latp": "84",
    "Player_1": "Raya\r 2",
    "Player_11": "N.Jackson\r 1",
    "Player_10": "Wood\r 12",
    "Player_12": "Henderson\r 2",
    "Player_13": "Pedro Porro\r 4",
    "Player_14": "Milenkovi\u0107\r 6",
    "Player_7": "Rogers\r 11",
    "Player_2": "Virgil\r 6",
    "Player_5": "Palmer\r 2",
    "Player_6": "M.Salah\r 32",
    "Player_3": "Aina\r 8",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Mbeumo\r 7",
    "Player_9": "Cunha\r 1",
    "Player_15": "J.Murphy\r 3"
  },
  {
    "manager_Name": "1,220( 186,270 ) TotalXfr : 19",
    "Teams": "Holding Ream Cash( Karan Thorat )",
    "SXL": "India",
    "Latp": "75",
    "Player_1": "Raya\r 2",
    "Player_11": "Cunha\r 1",
    "Player_10": "Jo\u00E3o Pedro\r 9",
    "Player_12": "Muric\r 0",
    "Player_13": "Semenyo\r 5",
    "Player_14": "Hall\r 12",
    "Player_7": "Palmer\r 2",
    "Player_2": "Alexander-Arnold\r 15",
    "Player_5": "M.Salah\r 32",
    "Player_6": "\u00D8degaard\r 2",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Mykolenko\r 1",
    "Player_8": "I.Sarr\r 2",
    "Player_9": "Isak\r 7",
    "Player_15": "Greaves\r 6"
  },
  {
    "manager_Name": "1,210( 253,324 ) TotalXfr : 16",
    "Teams": "Deys Knights( Rohan Dey )",
    "SXL": "India",
    "Latp": "65",
    "Player_1": "Pickford\r 1",
    "Player_11": "Cunha\r 1",
    "Player_10": "Isak\r 7",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Gordon\r 6",
    "Player_14": "Hall\r 12",
    "Player_7": "Palmer\r 2",
    "Player_2": "Robinson\r 4",
    "Player_5": "M.Salah\r 32",
    "Player_6": "I.Sarr\r 2",
    "Player_3": "Gabriel\r 2",
    "Player_4": "J.Timber\r 1",
    "Player_8": "Enzo\r 1",
    "Player_9": "Wood\r 12",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "1,197( 375,488 ) TotalXfr : 19",
    "Teams": "lakaka( Kabeer Bhagat )",
    "SXL": "India",
    "Latp": "76",
    "Player_1": "Henderson\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 9",
    "Player_10": "Isak\r 7",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Mazraoui\r 1",
    "Player_14": "B.Fernandes\r 0",
    "Player_7": "Smith Rowe\r 1",
    "Player_2": "Robinson\r 4",
    "Player_5": "M.Salah\r 32",
    "Player_6": "Kulusevski\r 5",
    "Player_3": "Hall\r 12",
    "Player_4": "J.Timber\r 1",
    "Player_8": "Palmer\r 2",
    "Player_9": "Cunha\r 1",
    "Player_15": "Burgess\r 0"
  },
  {
    "manager_Name": "1,174( 672,232 ) TotalXfr : 20",
    "Teams": "FALSE 9( Rohan Rai )",
    "SXL": "India",
    "Latp": "72",
    "Player_1": "Henderson\r 2",
    "Player_11": "Ra\u00FAl\r 9",
    "Player_10": "N.Jackson\r 1",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Mbeumo\r 7",
    "Player_14": "Kerkez\r 1",
    "Player_7": "I.Sarr\r 2",
    "Player_2": "Colwill\r 0",
    "Player_5": "M.Salah\r 32",
    "Player_6": "Palmer\r 2",
    "Player_3": "Robinson\r 4",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Rogers\r 11",
    "Player_9": "Isak\r 7",
    "Player_15": "Digne\r 1"
  },
  {
    "manager_Name": "1,171( 719,260 ) TotalXfr : 20",
    "Teams": "RED_DEVils_XI( Devraj Redkar )",
    "SXL": "England",
    "Latp": "64",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r 1",
    "Player_10": "Isak\r 7",
    "Player_12": "Raya\r 2",
    "Player_13": "Zabarnyi\r 1",
    "Player_14": "Cunha\r 1",
    "Player_7": "Enzo\r 1",
    "Player_2": "Gvardiol\r 6",
    "Player_5": "Amad\r 2",
    "Player_6": "M.Salah\r 32",
    "Player_3": "Robinson\r 4",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Maddison\r 1",
    "Player_9": "Palmer\r 2",
    "Player_15": "Emerson\r 0"
  },
  {
    "manager_Name": "1,169( 753,859 ) TotalXfr : 22",
    "Teams": "Mushrooms of Europe( Nicholas Neyt )",
    "SXL": "Belgium",
    "Latp": "88",
    "Player_1": "S\u00E1nchez\r 0",
    "Player_11": "G.Jesus\r 9",
    "Player_10": "Haaland\r 8",
    "Player_12": "Henderson\r 2",
    "Player_13": "Bergvall\r 0",
    "Player_14": "Harwood-Bellis\r 0",
    "Player_7": "Rogers\r 11",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Enzo\r 1",
    "Player_6": "M.Salah\r 32",
    "Player_3": "Hall\r 12",
    "Player_4": "Robinson\r 4",
    "Player_8": "Palmer\r 2",
    "Player_9": "Isak\r 7",
    "Player_15": "Cash\r 0"
  },
  {
    "manager_Name": "1,168( 768,295 ) TotalXfr : 20",
    "Teams": "Sakalicous( Sachin thakur )",
    "SXL": "India",
    "Latp": "62",
    "Player_1": "Kelleher\r 0",
    "Player_11": "Havertz\r 0",
    "Player_10": "Isak\r 7",
    "Player_12": "Sels\r 6",
    "Player_13": "A\u00EFt-Nouri\r 10",
    "Player_14": "Faes\r 0",
    "Player_7": "M.Salah\r 32",
    "Player_2": "Gabriel\r 2",
    "Player_5": "\u00D8degaard\r 2",
    "Player_6": "Amad\r 2",
    "Player_3": "Gvardiol\r 6",
    "Player_4": "Aina\r 8",
    "Player_8": "Palmer\r 2",
    "Player_9": "Cunha\r 1",
    "Player_15": "Lavia\r 0"
  },
  {
    "manager_Name": "1,166( 805,546 ) TotalXfr : 24",
    "Teams": "Kounde Bhajji( Ronak Kapadia )",
    "SXL": "India",
    "Latp": "99",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Isak\r 7",
    "Player_10": "G.Jesus\r 9",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 9",
    "Player_14": "Colwill\r 0",
    "Player_7": "Palmer\r 2",
    "Player_2": "Alexander-Arnold\r 15",
    "Player_5": "M.Salah\r 32",
    "Player_6": "Foden\r 6",
    "Player_3": "Robinson\r 4",
    "Player_4": "J.Timber\r 1",
    "Player_8": "Eze\r 10",
    "Player_9": "Rogers\r 11",
    "Player_15": "Burgess\r 0"
  },
  {
    "manager_Name": "1,163( 850,338 ) TotalXfr : 18",
    "Teams": "SakaWakaXI( Deepti D )",
    "SXL": "India",
    "Latp": "89",
    "Player_1": "Raya\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 9",
    "Player_10": "Cunha\r 1",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Rogers\r 11",
    "Player_14": "Justin\r 2",
    "Player_7": "M.Salah\r 32",
    "Player_2": "Saliba\r 2",
    "Player_5": "Palmer\r 2",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Hall\r 12",
    "Player_4": "Aina\r 8",
    "Player_8": "Martinelli\r 7",
    "Player_9": "Isak\r 7",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "1,162( 870,296 ) TotalXfr : 19",
    "Teams": "TYSM11( Tasdique Yasin )",
    "SXL": "India",
    "Latp": "85",
    "Player_1": "Sels\r 6",
    "Player_11": "Isak\r 7",
    "Player_10": "G.Jesus\r 9",
    "Player_12": "Flekken\r 1",
    "Player_13": "Cunha\r 1",
    "Player_14": "Robinson\r 4",
    "Player_7": "Luis D\u00EDaz\r 9",
    "Player_2": "J.Timber\r 1",
    "Player_5": "Palmer\r 2",
    "Player_6": "Amad\r 2",
    "Player_3": "Mu\u00F1oz\r 2",
    "Player_4": "Aina\r 8",
    "Player_8": "M.Salah\r 32",
    "Player_9": "Mbeumo\r 7",
    "Player_15": "Mazraoui\r 1"
  },
  {
    "manager_Name": "1,161( 888,119 ) TotalXfr : 19",
    "Teams": "Danzig( Engelbert Dsilva )",
    "SXL": "Chinese Taipei",
    "Latp": "79",
    "Player_1": "A.Becker\r 6",
    "Player_11": "Wood\r 12",
    "Player_10": "Isak\r 7",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Aina\r 8",
    "Player_14": "Jo\u00E3o Pedro\r 9",
    "Player_7": "Luis D\u00EDaz\r 9",
    "Player_2": "Saliba\r 2",
    "Player_5": "Bernardo\r 3",
    "Player_6": "Palmer\r 4",
    "Player_3": "Hall\r 12",
    "Player_4": "Cucurella\r 1",
    "Player_8": "Martinelli\r 7",
    "Player_9": "M.Salah\r 16",
    "Player_15": "Burgess\r 0"
  },
  {
    "manager_Name": "1,158( 944,935 ) TotalXfr : 20",
    "Teams": "Change Name( Puneet Gupta )",
    "SXL": "India",
    "Latp": "84",
    "Player_1": "Sels\r 6",
    "Player_11": "Haaland\r 8",
    "Player_10": "Isak\r 7",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 9",
    "Player_14": "Harwood-Bellis\r 0",
    "Player_7": "Rogers\r 11",
    "Player_2": "Hall\r 12",
    "Player_5": "Palmer\r 2",
    "Player_6": "M.Salah\r 32",
    "Player_3": "J.Timber\r 1",
    "Player_4": "Kerkez\r 1",
    "Player_8": "I.Sarr\r 2",
    "Player_9": "Amad\r 2",
    "Player_15": "O\u0027Shea\r 5"
  },
  {
    "manager_Name": "1,157( 962,124 ) TotalXfr : 19",
    "Teams": "WengerBoys( Sanket Marwah )",
    "SXL": "India",
    "Latp": "84",
    "Player_1": "D\u00FAbravka\r 6",
    "Player_11": "Isak\r 7",
    "Player_10": "Cunha\r 1",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Watkins\r 12",
    "Player_14": "Wood\r 1",
    "Player_7": "M.Salah\r 32",
    "Player_2": "Tarkowski\r 0",
    "Player_5": "Palmer\r 2",
    "Player_6": "Rogers\r 11",
    "Player_3": "Aina\r 8",
    "Player_4": "Robinson\r 4",
    "Player_8": "Mbeumo\r 7",
    "Player_9": "Gordon\r 6",
    "Player_15": "Okoli\r 1"
  },
  {
    "manager_Name": "1,155( 1,000,327 ) TotalXfr : 19",
    "Teams": "Ashburton Grove FC( Zafar Khan )",
    "SXL": "India",
    "Latp": "68",
    "Player_1": "S\u00E1nchez\r 0",
    "Player_11": "N.Jackson\r 1",
    "Player_10": "Isak\r 7",
    "Player_12": "Ward\r 0",
    "Player_13": "Rogers\r 11",
    "Player_14": "A\u00EFt-Nouri\r 10",
    "Player_7": "Palmer\r 2",
    "Player_2": "Alexander-Arnold\r 15",
    "Player_5": "I.Sarr\r 2",
    "Player_6": "M.Salah\r 32",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Robinson\r 4",
    "Player_8": "Iwobi\r 2",
    "Player_9": "Cunha\r 1",
    "Player_15": "Johnson\r 1"
  },
  {
    "manager_Name": "1,149( 1,117,833 ) TotalXfr : 18",
    "Teams": "GoonerXI( Siddharth Kamath )",
    "SXL": "USA",
    "Latp": "78",
    "Player_1": "Flekken\r 1",
    "Player_11": "Wood\r 12",
    "Player_10": "Havertz\r 0",
    "Player_12": "Turner\r 0",
    "Player_13": "Winks\r 2",
    "Player_14": "Barco\r 0",
    "Player_7": "M.Salah\r 32",
    "Player_2": "Saliba\r 2",
    "Player_5": "Enzo\r 1",
    "Player_6": "Luis D\u00EDaz\r 9",
    "Player_3": "Hall\r 12",
    "Player_4": "Wan-Bissaka\r 0",
    "Player_8": "Palmer\r 2",
    "Player_9": "Isak\r 7",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "1,148( 1,143,003 ) TotalXfr : 20",
    "Teams": "Amigo\u0027s_13( Rakesh Dake )",
    "SXL": "India",
    "Latp": "80",
    "Player_1": "Flekken\r 1",
    "Player_11": "Isak\r 7",
    "Player_10": "Watkins\r 12",
    "Player_12": "Turner\r 0",
    "Player_13": "Enzo\r 1",
    "Player_14": "Kerkez\r 1",
    "Player_7": "Palmer\r 2",
    "Player_2": "Gvardiol\r 6",
    "Player_5": "Aina\r 8",
    "Player_6": "\u00D8degaard\r 2",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Mu\u00F1oz\r 2",
    "Player_8": "M.Salah\r 32",
    "Player_9": "Strand Larsen\r 6",
    "Player_15": "Schade\r 1"
  },
  {
    "manager_Name": "1,146( 1,175,390 ) TotalXfr : 16",
    "Teams": "Arsenal( Kunal Modi )",
    "SXL": "India",
    "Latp": "85",
    "Player_1": "Henderson\r 2",
    "Player_11": "Isak\r 7",
    "Player_10": "Wood\r 12",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Mazraoui\r 1",
    "Player_14": "Dibling\r 8",
    "Player_7": "Martinelli\r 7",
    "Player_2": "Gabriel\r 2",
    "Player_5": "M.Salah\r 32",
    "Player_6": "Palmer\r 2",
    "Player_3": "Harwood-Bellis\r 0",
    "Player_4": "J.Timber\r 1",
    "Player_8": "Rogers\r 11",
    "Player_9": "Jo\u00E3o Pedro\r 9",
    "Player_15": "Wan-Bissaka\r 0"
  },
  {
    "manager_Name": "1,146( 1,183,126 ) TotalXfr : 19",
    "Teams": "Slumdog Mignolet( Xerxes Khambatta )",
    "SXL": "India",
    "Latp": "83",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 7",
    "Player_10": "N.Jackson\r 1",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 9",
    "Player_14": "Lewis\r 6",
    "Player_7": "Diogo J.\r 6",
    "Player_2": "Aina\r 8",
    "Player_5": "Rogers\r 11",
    "Player_6": "M.Salah\r 32",
    "Player_3": "Colwill\r 0",
    "Player_4": "Hall\r 12",
    "Player_8": "Palmer\r 2",
    "Player_9": "I.Sarr\r 2",
    "Player_15": "Greaves\r 6"
  },
  {
    "manager_Name": "1,146( 1,190,018 ) TotalXfr : 25",
    "Teams": "Captain\u00D8( Jebarwocky JD )",
    "SXL": "USA",
    "Latp": "78",
    "Player_1": "Sels\r 6",
    "Player_11": "Cunha\r 1",
    "Player_10": "Wood\r 12",
    "Player_12": "Ramsdale\r 3",
    "Player_13": "Amad\r 2",
    "Player_14": "Wan-Bissaka\r 0",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Aina\r 8",
    "Player_5": "Palmer\r 2",
    "Player_6": "Maddison\r 1",
    "Player_3": "Kerkez\r 1",
    "Player_4": "Mykolenko\r 1",
    "Player_8": "M.Salah\r 32",
    "Player_9": "Isak\r 7",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "1,144( 1,225,702 ) TotalXfr : 19",
    "Teams": "Blistering Barnacles( Sushanta Mondal )",
    "SXL": "India",
    "Latp": "67",
    "Player_1": "Henderson\r 2",
    "Player_11": "Cunha\r 1",
    "Player_10": "Isak\r 7",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Mitoma\r 1",
    "Player_14": "Kerkez\r 1",
    "Player_7": "Rogers\r 11",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Gordon\r 6",
    "Player_6": "M.Salah\r 32",
    "Player_3": "Robinson\r 4",
    "Player_4": "Colwill\r 0",
    "Player_8": "Palmer\r 2",
    "Player_9": "Havertz\r 0",
    "Player_15": "Faes\r 0"
  },
  {
    "manager_Name": "1,143( 1,256,037 ) TotalXfr : 30",
    "Teams": "Nawaz\u0027s balls \u26BD( Nawaz Ahmed )",
    "SXL": "United Arab Emirates",
    "Latp": "81",
    "Player_1": "Henderson\r 2",
    "Player_11": "N.Jackson\r 1",
    "Player_10": "Cunha\r 1",
    "Player_12": "Raya\r 2",
    "Player_13": "Rogers\r 11",
    "Player_14": "Hall\r 12",
    "Player_7": "M.Salah\r 32",
    "Player_2": "J.Timber\r 1",
    "Player_5": "Palmer\r 2",
    "Player_6": "Kulusevski\r 5",
    "Player_3": "Alexander-Arnold\r 15",
    "Player_4": "Aina\r 8",
    "Player_8": "Martinelli\r 7",
    "Player_9": "Isak\r 7",
    "Player_15": "A\u00EFt-Nouri\r 10"
  },
  {
    "manager_Name": "1,140( 1,307,700 ) TotalXfr : 17",
    "Teams": "Kishore\u2019s Rascals( Nandakishore K )",
    "SXL": "India",
    "Latp": "63",
    "Player_1": "Henderson\r 2",
    "Player_11": "Haaland\r 16",
    "Player_10": "Strand Larsen\r 6",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 9",
    "Player_14": "Van den Berg\r 1",
    "Player_7": "Gordon\r 6",
    "Player_2": "Saliba\r 2",
    "Player_5": "M.Salah\r 16",
    "Player_6": "Enzo\r 1",
    "Player_3": "J.Timber\r 1",
    "Player_4": "Colwill\r 0",
    "Player_8": "Palmer\r 2",
    "Player_9": "Rogers\r 11",
    "Player_15": "Greaves\r 6"
  },
  {
    "manager_Name": "1,140( 1,311,097 ) TotalXfr : 18",
    "Teams": "CoolPalmsFc( Naveed Surve )",
    "SXL": "India",
    "Latp": "69",
    "Player_1": "Valdimarsson\r 0",
    "Player_11": "Cunha\r 1",
    "Player_10": "Isak\r 7",
    "Player_12": "Flekken\r 1",
    "Player_13": "Wood\r 12",
    "Player_14": "Wan-Bissaka\r 0",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Robinson\r 4",
    "Player_5": "M.Salah\r 32",
    "Player_6": "Palmer\r 2",
    "Player_3": "Huijsen\r 1",
    "Player_4": "J.Timber\r 1",
    "Player_8": "Rogers\r 11",
    "Player_9": "J.Murphy\r 3",
    "Player_15": "Burgess\r 0"
  },
  {
    "manager_Name": "1,140( 1,311,097 ) TotalXfr : 18",
    "Teams": "Jaanbaaz Shikari( Saurabh Mittal )",
    "SXL": "India",
    "Latp": "59",
    "Player_1": "Henderson\r 2",
    "Player_11": "Isak\r 7",
    "Player_10": "Wissa\r 2",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Virgil\r 6",
    "Player_14": "Strand Larsen\r 6",
    "Player_7": "\u00D8degaard\r 2",
    "Player_2": "Aina\r 8",
    "Player_5": "Rogers\r 11",
    "Player_6": "Maddison\r 1",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Robinson\r 4",
    "Player_8": "Palmer\r 4",
    "Player_9": "M.Salah\r 16",
    "Player_15": "Greaves\r 6"
  },
  {
    "manager_Name": "1,138( 1,361,890 ) TotalXfr : 21",
    "Teams": "miskharege fc( Jordan D\u0027Almeida )",
    "SXL": "India",
    "Latp": "67",
    "Player_1": "Flekken\r 1",
    "Player_11": "N.Jackson\r 1",
    "Player_10": "Cunha\r 1",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Bowen\r 1",
    "Player_14": "Greaves\r 6",
    "Player_7": "Amad\r 2",
    "Player_2": "Saliba\r 2",
    "Player_5": "A\u00EFt-Nouri\r 10",
    "Player_6": "Luis D\u00EDaz\r 9",
    "Player_3": "Virgil\r 6",
    "Player_4": "Mazraoui\r 1",
    "Player_8": "M.Salah\r 32",
    "Player_9": "Palmer\r 2",
    "Player_15": "Stewart\r 0"
  },
  {
    "manager_Name": "1,136( 1,403,891 ) TotalXfr : 19",
    "Teams": "Fantasy Xi( Daniel Gekonge )",
    "SXL": "Kenya",
    "Latp": "87",
    "Player_1": "Henderson\r 2",
    "Player_11": "Isak\r 7",
    "Player_10": "Cunha\r 1",
    "Player_12": "S\u00E1nchez\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 9",
    "Player_14": "Mazraoui\r 1",
    "Player_7": "M.Salah\r 32",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Kulusevski\r 5",
    "Player_6": "Palmer\r 2",
    "Player_3": "Alexander-Arnold\r 15",
    "Player_4": "Hall\r 12",
    "Player_8": "Mbeumo\r 7",
    "Player_9": "Amad\r 2",
    "Player_15": "Keane\r 0"
  },
  {
    "manager_Name": "1,136( 1,407,666 ) TotalXfr : 21",
    "Teams": "Kamada Dragons( Rohan Kapre )",
    "SXL": "India",
    "Latp": "80",
    "Player_1": "Sels\r 6",
    "Player_11": "Evanilson\r 8",
    "Player_10": "Isak\r 7",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Mitoma\r 1",
    "Player_14": "Kerkez\r 1",
    "Player_7": "Palmer\r 2",
    "Player_2": "Cucurella\r 1",
    "Player_5": "M.Salah\r 32",
    "Player_6": "Foden\r 6",
    "Player_3": "Robinson\r 4",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Rogers\r 11",
    "Player_9": "Cunha\r 1",
    "Player_15": "Tuanzebe\r 0"
  },
  {
    "manager_Name": "1,134( 1,444,627 ) TotalXfr : 17",
    "Teams": "kalafiori( Adarsh Pakala )",
    "SXL": "Hong Kong",
    "Latp": "55",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 14",
    "Player_10": "Jo\u00E3o Pedro\r 9",
    "Player_12": "S\u00E1nchez\r 0",
    "Player_13": "Kluivert\r 0",
    "Player_14": "Van Hecke\r 1",
    "Player_7": "Palmer\r 2",
    "Player_2": "Gabriel\r 2",
    "Player_5": "Wan-Bissaka\r 0",
    "Player_6": "\u00D8degaard\r 2",
    "Player_3": "Virgil\r 6",
    "Player_4": "Huijsen\r 1",
    "Player_8": "M.Salah\r 16",
    "Player_9": "Muniz\r 1",
    "Player_15": "Dibling\r 8"
  },
  {
    "manager_Name": "1,134( 1,448,016 ) TotalXfr : 18",
    "Teams": "kopside( Hemanth SD )",
    "SXL": "India",
    "Latp": "56",
    "Player_1": "A.Becker\r 6",
    "Player_11": "Isak\r 7",
    "Player_10": "N.Jackson\r 1",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "Mitoma\r 1",
    "Player_14": "Kerkez\r 1",
    "Player_7": "J.Murphy\r 3",
    "Player_2": "Virgil\r 6",
    "Player_5": "Amad\r 2",
    "Player_6": "Palmer\r 4",
    "Player_3": "Colwill\r 0",
    "Player_4": "Gabriel\r 2",
    "Player_8": "M.Salah\r 16",
    "Player_9": "Jo\u00E3o Pedro\r 9",
    "Player_15": "Pedro Porro\r 4"
  },
  {
    "manager_Name": "1,134( 1,452,931 ) TotalXfr : 20",
    "Teams": "Licha al-Gaib( Hardit S )",
    "SXL": "Canada",
    "Latp": "82",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 7",
    "Player_10": "Cunha\r 1",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Robinson\r 4",
    "Player_14": "Mbeumo\r 7",
    "Player_7": "Palmer\r 2",
    "Player_2": "Aina\r 8",
    "Player_5": "Gordon\r 6",
    "Player_6": "Rogers\r 11",
    "Player_3": "Gomez\r 1",
    "Player_4": "Colwill\r 0",
    "Player_8": "M.Salah\r 32",
    "Player_9": "Wood\r 12",
    "Player_15": "Greaves\r 6"
  },
  {
    "manager_Name": "1,134( 1,458,892 ) TotalXfr : 26",
    "Teams": "Shadows FC( Altab Rahi )",
    "SXL": "India",
    "Latp": "79",
    "Player_1": "Sels\r 6",
    "Player_11": "Mateta\r 2",
    "Player_10": "Isak\r 7",
    "Player_12": "Kelleher\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 9",
    "Player_14": "Davis\r 5",
    "Player_7": "Palmer\r 2",
    "Player_2": "Milenkovi\u0107\r 6",
    "Player_5": "M.Salah\r 32",
    "Player_6": "\u00D8degaard\r 2",
    "Player_3": "J.Timber\r 1",
    "Player_4": "Robinson\r 4",
    "Player_8": "Gordon\r 6",
    "Player_9": "Rogers\r 11",
    "Player_15": "A\u00EFt-Nouri\r 10"
  },
  {
    "manager_Name": "1,133( 1,468,155 ) TotalXfr : 17",
    "Teams": "Here for Beer( Gaurav K )",
    "SXL": "India",
    "Latp": "79",
    "Player_1": "Sels\r 6",
    "Player_11": "N.Jackson\r 1",
    "Player_10": "Wood\r 12",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Enzo\r 1",
    "Player_14": "Mazraoui\r 1",
    "Player_7": "M.Salah\r 32",
    "Player_2": "Gomez\r 1",
    "Player_5": "Amad\r 2",
    "Player_6": "Palmer\r 2",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Hall\r 12",
    "Player_8": "I.Sarr\r 2",
    "Player_9": "Isak\r 7",
    "Player_15": "Harwood-Bellis\r 0"
  },
  {
    "manager_Name": "1,133( 1,478,080 ) TotalXfr : 21",
    "Teams": "Jurgen\u0027s Kop( Prathamesh Manjrekar )",
    "SXL": "India",
    "Latp": "70",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Isak\r 7",
    "Player_10": "Cunha\r 1",
    "Player_12": "Flekken\r 1",
    "Player_13": "Digne\r 1",
    "Player_14": "Mazraoui\r 1",
    "Player_7": "Palmer\r 2",
    "Player_2": "Mu\u00F1oz\r 2",
    "Player_5": "M.Salah\r 32",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Kerkez\r 1",
    "Player_4": "Robinson\r 4",
    "Player_8": "Maddison\r 1",
    "Player_9": "Rogers\r 11",
    "Player_15": "Delap\r 11"
  },
  {
    "manager_Name": "1,130( 1,539,616 ) TotalXfr : 17",
    "Teams": "Arsene\u0027s Avengers( Abhijay Khatry )",
    "SXL": "India",
    "Latp": "103",
    "Player_1": "Sels\r 6",
    "Player_11": "Jo\u00E3o Pedro\r 9",
    "Player_10": "Wood\r 12",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Mykolenko\r 1",
    "Player_14": "Greaves\r 6",
    "Player_7": "Mbeumo\r 7",
    "Player_2": "Alexander-Arnold\r 15",
    "Player_5": "Palmer\r 2",
    "Player_6": "M.Salah\r 32",
    "Player_3": "Mu\u00F1oz\r 2",
    "Player_4": "Gabriel\r 2",
    "Player_8": "Luis D\u00EDaz\r 9",
    "Player_9": "Isak\r 7",
    "Player_15": "Dibling\r 8"
  },
  {
    "manager_Name": "1,129( 1,576,505 ) TotalXfr : 23",
    "Teams": "The Well Read Devils( Shouvik T )",
    "SXL": "India",
    "Latp": "57",
    "Player_1": "Verbruggen\r 2",
    "Player_11": "Jo\u00E3o Pedro\r 9",
    "Player_10": "Isak\r 7",
    "Player_12": "Fabianski\r 0",
    "Player_13": "B.Fernandes\r 0",
    "Player_14": "Kerkez\r 1",
    "Player_7": "Martinelli\r 7",
    "Player_2": "Milenkovi\u0107\r 6",
    "Player_5": "Enzo\r 1",
    "Player_6": "Palmer\r 4",
    "Player_3": "Mitchell\r 2",
    "Player_4": "Saliba\r 2",
    "Player_8": "M.Salah\r 16",
    "Player_9": "Cunha\r 1",
    "Player_15": "Hall\r 12"
  },
  {
    "manager_Name": "1,128( 1,601,964 ) TotalXfr : 24",
    "Teams": "Emile\u0027s Mitron( Rohit Nair )",
    "SXL": "India",
    "Latp": "70",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 7",
    "Player_10": "Cunha\r 1",
    "Player_12": "Ramsdale\r 3",
    "Player_13": "Rogers\r 11",
    "Player_14": "Van den Berg\r 1",
    "Player_7": "Amad\r 2",
    "Player_2": "Mu\u00F1oz\r 2",
    "Player_5": "Palmer\r 4",
    "Player_6": "M.Salah\r 16",
    "Player_3": "Alexander-Arnold\r 15",
    "Player_4": "Aina\r 8",
    "Player_8": "Maddison\r 1",
    "Player_9": "Wood\r 12",
    "Player_15": "Bednarek\r 0"
  },
  {
    "manager_Name": "1,126( 1,635,493 ) TotalXfr : 16",
    "Teams": "redfoxchallenger( Rajas Prasannakumar Thakur )",
    "SXL": "USA",
    "Latp": "87",
    "Player_1": "Raya\r 2",
    "Player_11": "Wood\r 12",
    "Player_10": "Isak\r 7",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Jo\u00E3o Pedro\r 9",
    "Player_14": "A\u00EFt-Nouri\r 10",
    "Player_7": "Palmer\r 2",
    "Player_2": "Virgil\r 6",
    "Player_5": "Martinelli\r 7",
    "Player_6": "Amad\r 2",
    "Player_3": "Colwill\r 0",
    "Player_4": "Lewis\r 6",
    "Player_8": "M.Salah\r 32",
    "Player_9": "Rogers\r 11",
    "Player_15": "Greaves\r 6"
  },
  {
    "manager_Name": "1,125( 1,670,382 ) TotalXfr : 20",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "India",
    "Latp": "72",
    "Player_1": "Henderson\r 2",
    "Player_11": "Cunha\r 1",
    "Player_10": "G.Jesus\r 9",
    "Player_12": "Fabianski\r 0",
    "Player_13": "B.Fernandes\r 0",
    "Player_14": "Kluivert\r 0",
    "Player_7": "Johnson\r 9",
    "Player_2": "J.Timber\r 1",
    "Player_5": "Dalot\r 1",
    "Player_6": "Milenkovi\u0107\r 6",
    "Player_3": "Burn\r 7",
    "Player_4": "Saliba\r 2",
    "Player_8": "M.Salah\r 32",
    "Player_9": "Palmer\r 2",
    "Player_15": "Armstrong\r 5"
  },
  {
    "manager_Name": "1,123( 1,724,798 ) TotalXfr : 23",
    "Teams": "Bear XI( Adi Patil )",
    "SXL": "India",
    "Latp": "74",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 7",
    "Player_10": "Jo\u00E3o Pedro\r 9",
    "Player_12": "Valdimarsson\r 0",
    "Player_13": "B.Fernandes\r 0",
    "Player_14": "Konsa\r 1",
    "Player_7": "Palmer\r 2",
    "Player_2": "Aina\r 8",
    "Player_5": "Lewis\r 6",
    "Player_6": "M.Salah\r 32",
    "Player_3": "Gabriel\r 2",
    "Player_4": "Robinson\r 4",
    "Player_8": "Enzo\r 1",
    "Player_9": "Cunha\r 1",
    "Player_15": "Bowen\r 1"
  },
  {
    "manager_Name": "1,122( 1,734,844 ) TotalXfr : 16",
    "Teams": "Predators( Ruchik Shirode )",
    "SXL": "India",
    "Latp": "50",
    "Player_1": "Onana\r 1",
    "Player_11": "Watkins\r 12",
    "Player_10": "Cunha\r 1",
    "Player_12": "Fabianski\r 0",
    "Player_13": "Amad\r 2",
    "Player_14": "Jo\u00E3o Pedro\r 9",
    "Player_7": "Martinelli\r 7",
    "Player_2": "J.Timber\r 1",
    "Player_5": "Mu\u00F1oz\r 2",
    "Player_6": "B.Fernandes\r 0",
    "Player_3": "Colwill\r 0",
    "Player_4": "Milenkovi\u0107\r 6",
    "Player_8": "Palmer\r 4",
    "Player_9": "M.Salah\r 16",
    "Player_15": "Hall\r 12"
  },
  {
    "manager_Name": "1,121( 1,766,100 ) TotalXfr : 18",
    "Teams": "Pep\u2019s Boys( Kayaan Shah )",
    "SXL": "India",
    "Latp": "53",
    "Player_1": "Raya\r 2",
    "Player_11": "Isak\r 7",
    "Player_10": "Enzo\r 1",
    "Player_12": "Pickford\r 1",
    "Player_13": "Evanilson\r 8",
    "Player_14": "Adama\r 1",
    "Player_7": "M.Salah\r 16",
    "Player_2": "Pedro Porro\r 4",
    "Player_5": "Sch\u00E4r\r 5",
    "Player_6": "Cucurella\r 1",
    "Player_3": "J.Timber\r 1",
    "Player_4": "Saliba\r 2",
    "Player_8": "Gibbs-White\r 10",
    "Player_9": "Palmer\r 4",
    "Player_15": "Cunha\r 1"
  },
  {
    "manager_Name": "1,120( 1,796,469 ) TotalXfr : 20",
    "Teams": "ABXI( Abhijit Sawant )",
    "SXL": "India",
    "Latp": "79",
    "Player_1": "S\u00E1nchez\r 0",
    "Player_11": "Gakpo\r 5",
    "Player_10": "Wood\r 12",
    "Player_12": "Turner\r 0",
    "Player_13": "Keane\r 0",
    "Player_14": "Luis D\u00EDaz\r 9",
    "Player_7": "M.Salah\r 32",
    "Player_2": "Johnson\r 1",
    "Player_5": "Gordon\r 6",
    "Player_6": "Mbeumo\r 7",
    "Player_3": "Burn\r 7",
    "Player_4": "Colwill\r 0",
    "Player_8": "Palmer\r 2",
    "Player_9": "Isak\r 7",
    "Player_15": "Faes\r 0"
  }
];