var s = [
  {
    "manager_Name": "1,323( 1 )",
    "Teams": "Matty C\u0027s 5ft 3\u0027s( Matt Chamberlain )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "Raya BOU",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Calvert-Lewin MUN",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Mukiele TOT",
    "Player_14": "Bijol MUN",
    "Player_7": "Rogers 5",
    "Player_2": "Gabriel BOU",
    "Player_5": "Saka BOU",
    "Player_6": "Foden CHE",
    "Player_3": "Tarkowski BRE",
    "Player_4": "Thiaw CRY",
    "Player_8": "Szoboszlai FUL",
    "Player_9": "Haaland CHE",
    "Player_15": "Garner BRE"
  },
  {
    "manager_Name": "1,321( 2 )",
    "Teams": "Le Puissant FC( Oluwatobi Ajayi )",
    "SXL": "USA",
    "Latp": "5",
    "Player_1": "Pickford BRE",
    "Player_11": "Thiago EVE",
    "Player_10": "Bowen WOL",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "E.Le F\u00E9e",
    "Player_14": "Mukiele TOT",
    "Player_7": "Foden CHE",
    "Player_2": "Gabriel BOU",
    "Player_5": "Saka BOU",
    "Player_6": "Rogers 5",
    "Player_3": "Lewis-Potter EVE",
    "Player_4": "Virgil FUL",
    "Player_8": "Szoboszlai FUL",
    "Player_9": "Haaland CHE",
    "Player_15": "Dorgu LEE"
  },
  {
    "manager_Name": "1,315( 3 )",
    "Teams": "The A Team( Henry Huynh )",
    "SXL": "ENG",
    "Latp": "0",
    "Player_1": "Verbruggen BUR",
    "Player_11": "Bowen WOL",
    "Player_10": "Haaland CHE",
    "Player_12": "Raya BOU",
    "Player_13": "Schade EVE",
    "Player_14": "Gravenberch FUL",
    "Player_7": "Gordon CRY",
    "Player_2": "Thiaw CRY",
    "Player_5": "Van Hecke",
    "Player_6": "Foden CHE",
    "Player_3": "Virgil FUL",
    "Player_4": "Collins EVE",
    "Player_8": "Bruno G.",
    "Player_9": "Ekitik\u00E9 FUL",
    "Player_15": "Keane BRE"
  },
  {
    "manager_Name": "1,312( 4 )",
    "Teams": "The Honest Trundlers( Ian Foster )",
    "SXL": "GBR",
    "Latp": "5",
    "Player_1": "Raya BOU",
    "Player_11": "Thiago EVE",
    "Player_10": "Ekitik\u00E9 FUL",
    "Player_12": "Darlow MUN",
    "Player_13": "Gravenberch FUL",
    "Player_14": "Wilson LIV",
    "Player_7": "Gordon CRY",
    "Player_2": "Thiaw CRY",
    "Player_5": "Gvardiol CHE",
    "Player_6": "Foden CHE",
    "Player_3": "Virgil FUL",
    "Player_4": "Gabriel BOU",
    "Player_8": "Rogers 5",
    "Player_9": "Haaland CHE",
    "Player_15": "Van Hecke"
  },
  {
    "manager_Name": "1,310( 5 )",
    "Teams": "Big Dom\u0027s Army( Ryan Monaghan )",
    "SXL": "IRL",
    "Latp": "0",
    "Player_1": "Raya BOU",
    "Player_11": "Haaland CHE",
    "Player_10": "Ekitik\u00E9 FUL",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Van de",
    "Player_14": "Xhaka TOT",
    "Player_7": "Semenyo ARS",
    "Player_2": "Van Hecke",
    "Player_5": "Gabriel BOU",
    "Player_6": "Saka BOU",
    "Player_3": "Gu\u00E9hi NEW",
    "Player_4": "Gvardiol CHE",
    "Player_8": "Foden CHE",
    "Player_9": "Kudus SUN",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,308( 6 )",
    "Teams": "K\u0105\u00F1\u021B \u1E9Ee \u1E9Eeat \u26BD\uFE0F( A Khaled )",
    "SXL": "EGY",
    "Latp": "5",
    "Player_1": "Kelleher EVE",
    "Player_11": "Haaland CHE",
    "Player_10": "Ekitik\u00E9 FUL",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Ra\u00FAl LIV",
    "Player_14": "Alderete TOT",
    "Player_7": "Rogers 5",
    "Player_2": "O\u0027Reilly CHE",
    "Player_5": "Foden CHE",
    "Player_6": "Gordon CRY",
    "Player_3": "Frimpong FUL",
    "Player_4": "Keane BRE",
    "Player_8": "Saka BOU",
    "Player_9": "Wilson LIV",
    "Player_15": "Andersen LIV"
  },
  {
    "manager_Name": "1,308( 7 )",
    "Teams": "Wizards( Captain Ahmed )",
    "SXL": "EGY",
    "Latp": "0",
    "Player_1": "Verbruggen BUR",
    "Player_11": "Haaland CHE",
    "Player_10": "Thiago EVE",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Anderson 4",
    "Player_14": "Andersen LIV",
    "Player_7": "Cunha LEE",
    "Player_2": "Gabriel BOU",
    "Player_5": "Cherki CHE",
    "Player_6": "Foden CHE",
    "Player_3": "Hincapie BOU",
    "Player_4": "Dorgu LEE",
    "Player_8": "Saka BOU",
    "Player_9": "Ra\u00FAl LIV",
    "Player_15": "Gu\u00E9hi NEW"
  },
  {
    "manager_Name": "1,306( 8 )",
    "Teams": "Top Scorers( Momodou Jallow )",
    "SXL": "USA",
    "Latp": "5",
    "Player_1": "A.Becker FUL",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Thiago EVE",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Chalobah MCI",
    "Player_14": "Heaven LEE",
    "Player_7": "Rogers 5",
    "Player_2": "Gu\u00E9hi NEW",
    "Player_5": "Foden CHE",
    "Player_6": "Trossard BOU",
    "Player_3": "J.Timber BOU",
    "Player_4": "Virgil FUL",
    "Player_8": "Bruno G.",
    "Player_9": "Haaland CHE",
    "Player_15": "Tr\u00E9sor BHA"
  },
  {
    "manager_Name": "1,306( 9 )",
    "Teams": "Diamondos( michael jewell )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "Pickford BRE",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Haaland CHE",
    "Player_12": "Petrovi\u0107 ARS",
    "Player_13": "Thiago EVE",
    "Player_14": "Alderete TOT",
    "Player_7": "Foden CHE",
    "Player_2": "Gabriel BOU",
    "Player_5": "Cash 5",
    "Player_6": "Saka BOU",
    "Player_3": "Gu\u00E9hi NEW",
    "Player_4": "Gvardiol CHE",
    "Player_8": "Garner BRE",
    "Player_9": "Szoboszlai FUL",
    "Player_15": "Rice BOU"
  },
  {
    "manager_Name": "1,306( 10 )",
    "Teams": "Haaland tiembla( Charlie Shanahan )",
    "SXL": "ENG",
    "Latp": "0",
    "Player_1": "A.Becker FUL",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Thiago EVE",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Wharton NEW",
    "Player_14": "Alderete TOT",
    "Player_7": "Foden CHE",
    "Player_2": "Gabriel BOU",
    "Player_5": "Saka BOU",
    "Player_6": "Rice BOU",
    "Player_3": "O\u0027Reilly CHE",
    "Player_4": "Gu\u00E9hi NEW",
    "Player_8": "Enzo MCI",
    "Player_9": "Haaland CHE",
    "Player_15": "Andersen LIV"
  },
  {
    "manager_Name": "1,305( 11 )",
    "Teams": "Walkin Humans( Gustav Walkin )",
    "SXL": "SWE",
    "Latp": "5",
    "Player_1": "Raya BOU",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Haaland CHE",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Dalot LEE",
    "Player_14": "Semenyo ARS",
    "Player_7": "Rogers 5",
    "Player_2": "Virgil FUL",
    "Player_5": "Thiaw CRY",
    "Player_6": "Foden CHE",
    "Player_3": "Keane BRE",
    "Player_4": "Gvardiol CHE",
    "Player_8": "Cunha LEE",
    "Player_9": "Rice BOU",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,304( 12 )",
    "Teams": "the crystals( Luke Hosking )",
    "SXL": "AUS",
    "Latp": "0",
    "Player_1": "Pickford BRE",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Haaland CHE",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Mukiele TOT",
    "Player_14": "Obi LEE",
    "Player_7": "Foden CHE",
    "Player_2": "Chalobah MCI",
    "Player_5": "Gabriel BOU",
    "Player_6": "Bruno G.",
    "Player_3": "R\u00FAben CHE",
    "Player_4": "Tarkowski BRE",
    "Player_8": "Rice BOU",
    "Player_9": "Semenyo ARS",
    "Player_15": "Caicedo MCI"
  },
  {
    "manager_Name": "1,300( 13 )",
    "Teams": "The gentlemen\u2019s XI( Chris Mounsey-Thear )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "Raya BOU",
    "Player_11": "Haaland CHE",
    "Player_10": "Ekitik\u00E9 FUL",
    "Player_12": "John 1",
    "Player_13": "Semenyo ARS",
    "Player_14": "Anderson 4",
    "Player_7": "Foden CHE",
    "Player_2": "Matheus N.",
    "Player_5": "Gu\u00E9hi NEW",
    "Player_6": "Rogers 5",
    "Player_3": "Mukiele TOT",
    "Player_4": "Saliba BOU",
    "Player_8": "Trossard BOU",
    "Player_9": "Calvert-Lewin MUN",
    "Player_15": "Dalot LEE"
  },
  {
    "manager_Name": "1,300( 14 )",
    "Teams": "Aboudz( Abdalrahman Allam )",
    "SXL": "LBN",
    "Latp": "5",
    "Player_1": "Kelleher EVE",
    "Player_11": "Haaland CHE",
    "Player_10": "Thiago EVE",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Virgil FUL",
    "Player_14": "Truffert ARS",
    "Player_7": "Cunha LEE",
    "Player_2": "Andersen LIV",
    "Player_5": "Saka BOU",
    "Player_6": "Cherki CHE",
    "Player_3": "J.Timber BOU",
    "Player_4": "Gabriel BOU",
    "Player_8": "Rogers 5",
    "Player_9": "Wilson LIV",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,296( 15 )",
    "Teams": "Wassim030killer( Wassim El Mourabit )",
    "SXL": "NLD",
    "Latp": "5",
    "Player_1": "A.Becker FUL",
    "Player_11": "Welbeck BUR",
    "Player_10": "Woltemade CRY",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Alderete TOT",
    "Player_14": "Wirtz FUL",
    "Player_7": "Saka BOU",
    "Player_2": "Matheus N.",
    "Player_5": "Semenyo ARS",
    "Player_6": "Foden CHE",
    "Player_3": "Van Hecke",
    "Player_4": "Dorgu LEE",
    "Player_8": "Rogers 5",
    "Player_9": "Haaland CHE",
    "Player_15": "Senesi ARS"
  },
  {
    "manager_Name": "1,294( 16 )",
    "Teams": "Shien( Wei Shien Ng )",
    "SXL": "MYS",
    "Latp": "0",
    "Player_1": "Kelleher EVE",
    "Player_11": "Haaland CHE",
    "Player_10": "Ekitik\u00E9 FUL",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "E.Le F\u00E9e",
    "Player_14": "Alderete TOT",
    "Player_7": "Saka BOU",
    "Player_2": "Virgil FUL",
    "Player_5": "Thiaw CRY",
    "Player_6": "Foden CHE",
    "Player_3": "Gabriel BOU",
    "Player_4": "O\u0027Reilly CHE",
    "Player_8": "Cunha LEE",
    "Player_9": "Rice BOU",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,294( 17 )",
    "Teams": "FC Truckdrivers( Janne Ojanpera )",
    "SXL": "FIN",
    "Latp": "0",
    "Player_1": "Raya BOU",
    "Player_11": "Calvert-Lewin MUN",
    "Player_10": "Ekitik\u00E9 FUL",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Cunha LEE",
    "Player_14": "Gu\u00E9hi NEW",
    "Player_7": "Wirtz FUL",
    "Player_2": "Dorgu LEE",
    "Player_5": "Foden CHE",
    "Player_6": "Saka BOU",
    "Player_3": "Keane BRE",
    "Player_4": "Gusto MCI",
    "Player_8": "Wilson LIV",
    "Player_9": "Haaland CHE",
    "Player_15": "Est\u00E8ve BHA"
  },
  {
    "manager_Name": "1,292( 18 )",
    "Teams": "Heroes!( Abraham Assim Ita )",
    "SXL": "NGA",
    "Latp": "5",
    "Player_1": "Pickford BRE",
    "Player_11": "Haaland CHE",
    "Player_10": "Calvert-Lewin MUN",
    "Player_12": "Petrovi\u0107 ARS",
    "Player_13": "Xhaka TOT",
    "Player_14": "Van Hecke",
    "Player_7": "Rice BOU",
    "Player_2": "Tarkowski BRE",
    "Player_5": "Foden CHE",
    "Player_6": "Saka BOU",
    "Player_3": "Mukiele TOT",
    "Player_4": "Gabriel BOU",
    "Player_8": "Rogers 5",
    "Player_9": "Thiago EVE",
    "Player_15": "Senesi ARS"
  },
  {
    "manager_Name": "1,292( 19 )",
    "Teams": "Boat Toffees( boat cahill )",
    "SXL": "THA",
    "Latp": "0",
    "Player_1": "Raya BOU",
    "Player_11": "Haaland CHE",
    "Player_10": "Ekitik\u00E9 FUL",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Thiago EVE",
    "Player_14": "Andersen LIV",
    "Player_7": "Saka BOU",
    "Player_2": "Gabriel BOU",
    "Player_5": "Foden CHE",
    "Player_6": "Cunha LEE",
    "Player_3": "Dalot LEE",
    "Player_4": "Van de",
    "Player_8": "Cherki CHE",
    "Player_9": "Minteh BUR",
    "Player_15": "Rodon MUN"
  },
  {
    "manager_Name": "1,292( 20 )",
    "Teams": "Jumbo Whiffy( simon graney )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "Pickford BRE",
    "Player_11": "Haaland CHE",
    "Player_10": "Thiago EVE",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Semenyo ARS",
    "Player_14": "Isidor TOT",
    "Player_7": "Rogers 5",
    "Player_2": "Robinson LIV",
    "Player_5": "Mukiele TOT",
    "Player_6": "Xhaka TOT",
    "Player_3": "Gabriel BOU",
    "Player_4": "Gu\u00E9hi NEW",
    "Player_8": "Cherki CHE",
    "Player_9": "Foden CHE",
    "Player_15": "Chalobah MCI"
  },
  {
    "manager_Name": "1,291( 21 )",
    "Teams": "The Eagle v2.0( Oussama Bhmch )",
    "SXL": "MAR",
    "Latp": "7",
    "Player_1": "Leno LIV",
    "Player_11": "Haaland CHE",
    "Player_10": "Ekitik\u00E9 FUL",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Casemiro LEE",
    "Player_14": "De Cuyper",
    "Player_7": "Foden CHE",
    "Player_2": "Gabriel BOU",
    "Player_5": "Gibbs-White 7",
    "Player_6": "Gomez BUR",
    "Player_3": "J.Timber BOU",
    "Player_4": "Hall CRY",
    "Player_8": "Gordon CRY",
    "Player_9": "Richarlison SUN",
    "Player_15": "Clyne NEW"
  },
  {
    "manager_Name": "1,291( 22 )",
    "Teams": "FC Collymore( Staffan Arlefalk )",
    "SXL": "SWE",
    "Latp": "0",
    "Player_1": "D\u00FAbravka BHA",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Haaland CHE",
    "Player_12": "S\u00E1nchez MCI",
    "Player_13": "Rice BOU",
    "Player_14": "Calvert-Lewin MUN",
    "Player_7": "Cherki CHE",
    "Player_2": "Tarkowski BRE",
    "Player_5": "Van de",
    "Player_6": "Saliba BOU",
    "Player_3": "Virgil FUL",
    "Player_4": "R\u00FAben CHE",
    "Player_8": "Gordon CRY",
    "Player_9": "Wirtz FUL",
    "Player_15": "Semenyo ARS"
  },
  {
    "manager_Name": "1,291( 22 )",
    "Teams": "Stuart Does Dallas( Geoffrey Kazlow )",
    "SXL": "USA",
    "Latp": "0",
    "Player_1": "D\u00FAbravka BHA",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Haaland CHE",
    "Player_12": "S\u00E1nchez MCI",
    "Player_13": "Wirtz FUL",
    "Player_14": "Alderete TOT",
    "Player_7": "Foden CHE",
    "Player_2": "Thiaw CRY",
    "Player_5": "Dorgu LEE",
    "Player_6": "Cunha LEE",
    "Player_3": "Tarkowski BRE",
    "Player_4": "Gabriel BOU",
    "Player_8": "Cherki CHE",
    "Player_9": "Gordon CRY",
    "Player_15": "Kroupi.Jr ARS"
  },
  {
    "manager_Name": "1,291( 24 )",
    "Teams": "CityQuintessence( Konrad Janiszewski )",
    "SXL": "POL",
    "Latp": "5",
    "Player_1": "Verbruggen BUR",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Haaland CHE",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Gudmundsson MUN",
    "Player_14": "Mukiele TOT",
    "Player_7": "Foden CHE",
    "Player_2": "Tarkowski BRE",
    "Player_5": "Rogers 5",
    "Player_6": "L.Paquet\u00E1 WOL",
    "Player_3": "Gabriel BOU",
    "Player_4": "J.Timber BOU",
    "Player_8": "Saka BOU",
    "Player_9": "Gordon CRY",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,290( 25 )",
    "Teams": "TheFrimpongs( Ulf Hauan )",
    "SXL": "NOR",
    "Latp": "0",
    "Player_1": "Raya BOU",
    "Player_11": "Welbeck BUR",
    "Player_10": "Haaland CHE",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Senesi ARS",
    "Player_14": "Andersen LIV",
    "Player_7": "Cunha LEE",
    "Player_2": "J.Timber BOU",
    "Player_5": "Kudus SUN",
    "Player_6": "Saka BOU",
    "Player_3": "Virgil FUL",
    "Player_4": "Van Hecke",
    "Player_8": "Cherki CHE",
    "Player_9": "Woltemade CRY",
    "Player_15": "Dewsbury-Hall BRE"
  },
  {
    "manager_Name": "1,290( 26 )",
    "Teams": "Isra25( Basil Njoka )",
    "SXL": "KEN",
    "Latp": "5",
    "Player_1": "Pickford BRE",
    "Player_11": "Haaland CHE",
    "Player_10": "Mateta NEW",
    "Player_12": "Roefs TOT",
    "Player_13": "Van de",
    "Player_14": "Rice BOU",
    "Player_7": "Foden CHE",
    "Player_2": "J.Timber BOU",
    "Player_5": "Cunha LEE",
    "Player_6": "Rogers 5",
    "Player_3": "Gabriel BOU",
    "Player_4": "Tarkowski BRE",
    "Player_8": "Szoboszlai FUL",
    "Player_9": "Calvert-Lewin MUN",
    "Player_15": "Mukiele TOT"
  },
  {
    "manager_Name": "1,289( 27 )",
    "Teams": "Dullusoccer( Hreggvi\u00F0ur Haukur R\u00FAnarsson )",
    "SXL": "ISL",
    "Latp": "0",
    "Player_1": "Kelleher EVE",
    "Player_11": "Bowen WOL",
    "Player_10": "Haaland CHE",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "Alderete TOT",
    "Player_14": "Andersen LIV",
    "Player_7": "Saka BOU",
    "Player_2": "Hall CRY",
    "Player_5": "Cunha LEE",
    "Player_6": "Foden CHE",
    "Player_3": "Gabriel BOU",
    "Player_4": "Keane BRE",
    "Player_8": "Semenyo ARS",
    "Player_9": "Ekitik\u00E9 FUL",
    "Player_15": "Gonzalez WHU"
  },
  {
    "manager_Name": "1,289( 27 )",
    "Teams": "darxh( darshan harihar )",
    "SXL": "IND",
    "Latp": "0",
    "Player_1": "Kelleher EVE",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Haaland CHE",
    "Player_12": "D\u00FAbravka BHA",
    "Player_13": "O\u0027Reilly CHE",
    "Player_14": "Andersen LIV",
    "Player_7": "Gordon CRY",
    "Player_2": "Tarkowski BRE",
    "Player_5": "Garner BRE",
    "Player_6": "Saka BOU",
    "Player_3": "Gabriel BOU",
    "Player_4": "Dorgu LEE",
    "Player_8": "Cunha LEE",
    "Player_9": "Foden CHE",
    "Player_15": "Obi LEE"
  },
  {
    "manager_Name": "1,288( 29 )",
    "Teams": "Mehras( mehras akbari )",
    "SXL": "IRN",
    "Latp": "0",
    "Player_1": "Verbruggen 0",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Haaland CHE",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "Keane BRE",
    "Player_14": "Alderete TOT",
    "Player_7": "Cunha LEE",
    "Player_2": "Dorgu LEE",
    "Player_5": "Gordon CRY",
    "Player_6": "Saka BOU",
    "Player_3": "Hall CRY",
    "Player_4": "Gabriel BOU",
    "Player_8": "Foden CHE",
    "Player_9": "Cherki CHE",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,288( 30 )",
    "Teams": "Hunters( Mido Syd )",
    "SXL": "EGY",
    "Latp": "0",
    "Player_1": "Verbruggen 0",
    "Player_11": "Haaland CHE",
    "Player_10": "Thiago EVE",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "O\u0027Reilly CHE",
    "Player_14": "Potts 0",
    "Player_7": "Foden CHE",
    "Player_2": "Van Hecke",
    "Player_5": "Gordon CRY",
    "Player_6": "Saka BOU",
    "Player_3": "J.Timber BOU",
    "Player_4": "Dorgu LEE",
    "Player_8": "Cunha LEE",
    "Player_9": "Ekitik\u00E9 FUL",
    "Player_15": "Clyne NEW"
  },
  {
    "manager_Name": "1,287( 31 )",
    "Teams": "Shawrys Scorers( Amber Shaw )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "Pickford BRE",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Bowen 0",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "Wilson LIV",
    "Player_14": "Van den",
    "Player_7": "Rogers 5",
    "Player_2": "J.Timber BOU",
    "Player_5": "Bruno G.",
    "Player_6": "Foden CHE",
    "Player_3": "Dalot LEE",
    "Player_4": "Virgil FUL",
    "Player_8": "Cunha LEE",
    "Player_9": "Haaland CHE",
    "Player_15": "Gudmundsson MUN"
  },
  {
    "manager_Name": "1,287( 32 )",
    "Teams": "Creme de la creme( liban abdi )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "Raya BOU",
    "Player_11": "Mateta NEW",
    "Player_10": "Haaland CHE",
    "Player_12": "Austin SUN",
    "Player_13": "Konsa 2",
    "Player_14": "Wharton NEW",
    "Player_7": "Foden CHE",
    "Player_2": "Gusto MCI",
    "Player_5": "Gu\u00E9hi NEW",
    "Player_6": "Rogers 5",
    "Player_3": "James MCI",
    "Player_4": "Gvardiol CHE",
    "Player_8": "Saka BOU",
    "Player_9": "Ekitik\u00E9 FUL",
    "Player_15": "McGinn 12"
  },
  {
    "manager_Name": "1,286( 33 )",
    "Teams": "The Real Quiz( Matt Boyce )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "Verbruggen 0",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Haaland CHE",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "Keane BRE",
    "Player_14": "Est\u00E8ve 0",
    "Player_7": "Bruno G.",
    "Player_2": "Gvardiol CHE",
    "Player_5": "Rogers 5",
    "Player_6": "Foden CHE",
    "Player_3": "Thiaw CRY",
    "Player_4": "Gabriel BOU",
    "Player_8": "Saka BOU",
    "Player_9": "Szoboszlai FUL",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,286( 34 )",
    "Teams": "RuudAwakening( Abhimanyu Kulkarni )",
    "SXL": "USA",
    "Latp": "0",
    "Player_1": "Verbruggen 0",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Haaland CHE",
    "Player_12": "Kelleher EVE",
    "Player_13": "Dewsbury-Hall BRE",
    "Player_14": "Van den",
    "Player_7": "Foden CHE",
    "Player_2": "Dalot LEE",
    "Player_5": "Cunha LEE",
    "Player_6": "Saka BOU",
    "Player_3": "Gabriel BOU",
    "Player_4": "O\u0027Reilly CHE",
    "Player_8": "Mount LEE",
    "Player_9": "Bowen 0",
    "Player_15": "Andersen LIV"
  },
  {
    "manager_Name": "1,285( 35 )",
    "Teams": "11 Paths Sage( Preye Princewill )",
    "SXL": "NGA",
    "Latp": "11",
    "Player_1": "Kelleher EVE",
    "Player_11": "Thiago EVE",
    "Player_10": "Haaland CHE",
    "Player_12": "Henderson NEW",
    "Player_13": "Van de",
    "Player_14": "Semenyo ARS",
    "Player_7": "Bruno G.",
    "Player_2": "Gabriel BOU",
    "Player_5": "Rogers 5",
    "Player_6": "Cherki CHE",
    "Player_3": "Gu\u00E9hi NEW",
    "Player_4": "James MCI",
    "Player_8": "Rice BOU",
    "Player_9": "Watkins 6",
    "Player_15": "J.Timber BOU"
  },
  {
    "manager_Name": "1,285( 36 )",
    "Teams": "neto delap garnacho( gus tav )",
    "SXL": "SWE",
    "Latp": "5",
    "Player_1": "Kelleher EVE",
    "Player_11": "Haaland CHE",
    "Player_10": "Calvert-Lewin MUN",
    "Player_12": "Lammens LEE",
    "Player_13": "Calafiori BOU",
    "Player_14": "Collins EVE",
    "Player_7": "Cunha LEE",
    "Player_2": "Van Hecke",
    "Player_5": "Rogers 5",
    "Player_6": "Cherki CHE",
    "Player_3": "Gabriel BOU",
    "Player_4": "Thiaw CRY",
    "Player_8": "Wirtz FUL",
    "Player_9": "Saka BOU",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,285( 37 )",
    "Teams": "MYTEAMWEARSCLARKS( J Brix )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "Raya BOU",
    "Player_11": "Calvert-Lewin MUN",
    "Player_10": "Woltemade CRY",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "R\u00FAben CHE",
    "Player_14": "Wilson LIV",
    "Player_7": "Rice BOU",
    "Player_2": "Hall CRY",
    "Player_5": "Foden CHE",
    "Player_6": "Wirtz FUL",
    "Player_3": "Hincapie BOU",
    "Player_4": "Tarkowski BRE",
    "Player_8": "Rogers 5",
    "Player_9": "Haaland CHE",
    "Player_15": "Andersen LIV"
  },
  {
    "manager_Name": "1,284( 38 )",
    "Teams": "ValiQ Hotspur( Valentin Dumitrescu )",
    "SXL": "ROU",
    "Latp": "0",
    "Player_1": "Pickford BRE",
    "Player_11": "Bowen 0",
    "Player_10": "Haaland CHE",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "Alderete TOT",
    "Player_14": "Gudmundsson MUN",
    "Player_7": "Cunha LEE",
    "Player_2": "Gabriel BOU",
    "Player_5": "Gordon CRY",
    "Player_6": "Bruno G.",
    "Player_3": "Hall CRY",
    "Player_4": "Tarkowski BRE",
    "Player_8": "Foden CHE",
    "Player_9": "Ekitik\u00E9 FUL",
    "Player_15": "Devenny NEW"
  },
  {
    "manager_Name": "1,284( 38 )",
    "Teams": "WingardiumLevioSarr( Rory Gibney )",
    "SXL": "ENG",
    "Latp": "0",
    "Player_1": "Verbruggen 0",
    "Player_11": "Haaland CHE",
    "Player_10": "Woltemade CRY",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "Keane BRE",
    "Player_14": "Devenny NEW",
    "Player_7": "Cherki CHE",
    "Player_2": "Dalot LEE",
    "Player_5": "Gordon CRY",
    "Player_6": "Foden CHE",
    "Player_3": "Gabriel BOU",
    "Player_4": "Thiaw CRY",
    "Player_8": "Cunha LEE",
    "Player_9": "Ekitik\u00E9 FUL",
    "Player_15": "Gudmundsson MUN"
  },
  {
    "manager_Name": "1,284( 40 )",
    "Teams": "hakim dahem( TOP KADER )",
    "SXL": "DZA",
    "Latp": "0",
    "Player_1": "Kelleher EVE",
    "Player_11": "Haaland CHE",
    "Player_10": "Ekitik\u00E9 FUL",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "Andersen LIV",
    "Player_14": "Reinildo TOT",
    "Player_7": "Semenyo ARS",
    "Player_2": "Matheus N.",
    "Player_5": "Wilson LIV",
    "Player_6": "Foden CHE",
    "Player_3": "Gabriel BOU",
    "Player_4": "Hincapie BOU",
    "Player_8": "Cunha LEE",
    "Player_9": "Thiago EVE",
    "Player_15": "Dewsbury-Hall BRE"
  },
  {
    "manager_Name": "1,284( 40 )",
    "Teams": "washington fc( sow ibrahim )",
    "SXL": "SLE",
    "Latp": "7",
    "Player_1": "Verbruggen 0",
    "Player_11": "Igor Jesus",
    "Player_10": "Haaland CHE",
    "Player_12": "Vicario SUN",
    "Player_13": "Rice BOU",
    "Player_14": "Andersen LIV",
    "Player_7": "Rogers 5",
    "Player_2": "Gvardiol CHE",
    "Player_5": "Cherki CHE",
    "Player_6": "Saka BOU",
    "Player_3": "Hincapie BOU",
    "Player_4": "Gu\u00E9hi NEW",
    "Player_8": "L.Miley CRY",
    "Player_9": "Ekitik\u00E9 FUL",
    "Player_15": "Pedro Porro"
  },
  {
    "manager_Name": "1,283( 42 )",
    "Teams": "I predict a Wyatt( Ben Wyatt )",
    "SXL": "ENG",
    "Latp": "16",
    "Player_1": "Verbruggen 0",
    "Player_11": "Watkins 6",
    "Player_10": "Ekitik\u00E9 FUL",
    "Player_12": "Sels 1",
    "Player_13": "Anderson 4",
    "Player_14": "Broja 0",
    "Player_7": "Rogers 10",
    "Player_2": "Gabriel BOU",
    "Player_5": "Virgil FUL",
    "Player_6": "Wirtz FUL",
    "Player_3": "O\u0027Reilly CHE",
    "Player_4": "Cucurella MCI",
    "Player_8": "Foden CHE",
    "Player_9": "Saka BOU",
    "Player_15": "Lucas Pires"
  },
  {
    "manager_Name": "1,283( 43 )",
    "Teams": "The Special Ones( Suki Sidhu )",
    "SXL": "USA",
    "Latp": "5",
    "Player_1": "D\u00FAbravka 0",
    "Player_11": "Ekitik\u00E9 FUL",
    "Player_10": "Haaland CHE",
    "Player_12": "S\u00E1nchez MCI",
    "Player_13": "Gudmundsson MUN",
    "Player_14": "Mukiele TOT",
    "Player_7": "Palmer MCI",
    "Player_2": "Gabriel BOU",
    "Player_5": "Bruno G.",
    "Player_6": "Saka BOU",
    "Player_3": "O\u0027Reilly CHE",
    "Player_4": "Keane BRE",
    "Player_8": "Rogers 5",
    "Player_9": "Wilson LIV",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,283( 44 )",
    "Teams": "mirinda( Luka Ortulan )",
    "SXL": "HRV",
    "Latp": "0",
    "Player_1": "Raya BOU",
    "Player_11": "Haaland CHE",
    "Player_10": "Bowen 0",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "Thiago EVE",
    "Player_14": "Wilson LIV",
    "Player_7": "Foden CHE",
    "Player_2": "Tarkowski BRE",
    "Player_5": "Van Hecke",
    "Player_6": "Bruno G.",
    "Player_3": "Virgil FUL",
    "Player_4": "Gabriel BOU",
    "Player_8": "Cunha LEE",
    "Player_9": "Wirtz FUL",
    "Player_15": "Senesi ARS"
  },
  {
    "manager_Name": "1,282( 45 )",
    "Teams": "PigglyKeeks( Darren McMullin )",
    "SXL": "AUS",
    "Latp": "5",
    "Player_1": "Raya BOU",
    "Player_11": "Thiago EVE",
    "Player_10": "Haaland CHE",
    "Player_12": "Roefs TOT",
    "Player_13": "Ra\u00FAl LIV",
    "Player_14": "Truffert ARS",
    "Player_7": "Foden CHE",
    "Player_2": "Gvardiol CHE",
    "Player_5": "Saka BOU",
    "Player_6": "Gravenberch FUL",
    "Player_3": "Thiaw CRY",
    "Player_4": "Van Hecke",
    "Player_8": "Gordon CRY",
    "Player_9": "Rogers 5",
    "Player_15": "Kayode EVE"
  },
  {
    "manager_Name": "1,282( 45 )",
    "Teams": "Louie\u0027s Dream( Terry Flint )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "Pickford BRE",
    "Player_11": "Thiago EVE",
    "Player_10": "Ekitik\u00E9 FUL",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "Gu\u00E9hi NEW",
    "Player_14": "Wilson LIV",
    "Player_7": "Cherki CHE",
    "Player_2": "Virgil FUL",
    "Player_5": "Saka BOU",
    "Player_6": "Foden CHE",
    "Player_3": "J.Timber BOU",
    "Player_4": "Van de",
    "Player_8": "Rogers 5",
    "Player_9": "Haaland CHE",
    "Player_15": "Est\u00E8ve 0"
  },
  {
    "manager_Name": "1,282( 47 )",
    "Teams": "g7412877( George McNicholas )",
    "SXL": "ENG",
    "Latp": "5",
    "Player_1": "Raya BOU",
    "Player_11": "Haaland CHE",
    "Player_10": "Woltemade CRY",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "Gravenberch FUL",
    "Player_14": "Gu\u00E9hi NEW",
    "Player_7": "Bruno G.",
    "Player_2": "Gabriel BOU",
    "Player_5": "Rogers 5",
    "Player_6": "Rice BOU",
    "Player_3": "Thiaw CRY",
    "Player_4": "Gvardiol CHE",
    "Player_8": "Foden CHE",
    "Player_9": "Ekitik\u00E9 FUL",
    "Player_15": "Est\u00E8ve 0"
  },
  {
    "manager_Name": "1,281( 48 )",
    "Teams": "Ahli Stars( Mo Khattab )",
    "SXL": "EGY",
    "Latp": "0",
    "Player_1": "Raya BOU",
    "Player_11": "Haaland CHE",
    "Player_10": "Ekitik\u00E9 FUL",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "L.Miley CRY",
    "Player_14": "Gudmundsson MUN",
    "Player_7": "Saka BOU",
    "Player_2": "Konat\u00E9 FUL",
    "Player_5": "Szoboszlai FUL",
    "Player_6": "Cunha LEE",
    "Player_3": "Dorgu LEE",
    "Player_4": "Gabriel BOU",
    "Player_8": "Foden CHE",
    "Player_9": "Thiago EVE",
    "Player_15": "Clyne NEW"
  },
  {
    "manager_Name": "1,280( 49 )",
    "Teams": "FreiburgChamp( Parsa Ebrahimi )",
    "SXL": "DEU",
    "Latp": "5",
    "Player_1": "Verbruggen 0",
    "Player_11": "Calvert-Lewin MUN",
    "Player_10": "Ekitik\u00E9 FUL",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "Rice BOU",
    "Player_14": "Dorgu LEE",
    "Player_7": "Cherki CHE",
    "Player_2": "Gabriel BOU",
    "Player_5": "Szoboszlai FUL",
    "Player_6": "Cunha LEE",
    "Player_3": "Hall CRY",
    "Player_4": "Tarkowski BRE",
    "Player_8": "Rogers 5",
    "Player_9": "Haaland CHE",
    "Player_15": "O\u0027Reilly CHE"
  },
  {
    "manager_Name": "1,280( 49 )",
    "Teams": "M7( mo 7 )",
    "SXL": "IRQ",
    "Latp": "11",
    "Player_1": "Raya BOU",
    "Player_11": "Watkins 6",
    "Player_10": "Haaland CHE",
    "Player_12": "D\u00FAbravka 0",
    "Player_13": "Hall CRY",
    "Player_14": "Wilson LIV",
    "Player_7": "Rogers 5",
    "Player_2": "Frimpong FUL",
    "Player_5": "Gordon CRY",
    "Player_6": "\u00D8degaard BOU",
    "Player_3": "Tarkowski BRE",
    "Player_4": "Gabriel BOU",
    "Player_8": "Cherki CHE",
    "Player_9": "Thiago EVE",
    "Player_15": "Nallo FUL"
  }
];