var s = [
  {
    "manager_Name": "1,275( 3,930 )",
    "Teams": "cavac215( Ankit Chhetri )",
    "SXL": "IND",
    "Latp": "54",
    "Player_1": "Donnarumma 2",
    "Player_11": "Calvert-Lewin 2",
    "Player_10": "Thiago 17",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Rice 17",
    "Player_14": "Gu\u00E9hi 2",
    "Player_7": "Wirtz 10",
    "Player_2": "Chalobah 4",
    "Player_5": "Saka 4",
    "Player_6": "Cherki 4",
    "Player_3": "Keane 0",
    "Player_4": "J.Timber 3",
    "Player_8": "Garner 4",
    "Player_9": "Haaland 4",
    "Player_15": "Pau 0"
  },
  {
    "manager_Name": "1,232( 43,195 )",
    "Teams": "False 9( Rohan Rai )",
    "SXL": "IND",
    "Latp": "63",
    "Player_1": "Kelleher 2",
    "Player_11": "Thiago 17",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Mukiele 4",
    "Player_7": "Cunha 9",
    "Player_2": "O\u0027Reilly 2",
    "Player_5": "Rogers 5",
    "Player_6": "Saka 4",
    "Player_3": "Dalot 2",
    "Player_4": "Gabriel 9",
    "Player_8": "Foden 2",
    "Player_9": "L.Miley 7",
    "Player_15": "Gudmundsson 2"
  },
  {
    "manager_Name": "1,218( 82,887 )",
    "Teams": "PWS( Z S )",
    "SXL": "IND",
    "Latp": "53",
    "Player_1": "Roefs 3",
    "Player_11": "Haaland 4",
    "Player_10": "Calvert-Lewin 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Van de",
    "Player_7": "Foden 2",
    "Player_2": "Hall 6",
    "Player_5": "Cherki 4",
    "Player_6": "Semenyo 1",
    "Player_3": "Hincapie 1",
    "Player_4": "J.Timber 3",
    "Player_8": "Rice 17",
    "Player_9": "Wirtz 10",
    "Player_15": "Dorgu 1"
  },
  {
    "manager_Name": "1,206( 137,515 )",
    "Teams": "abcde FC( Prayash Thapa )",
    "SXL": "IND",
    "Latp": "51",
    "Player_1": "Roefs 3",
    "Player_11": "Thiago 17",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Truffert 1",
    "Player_14": "Andersen 3",
    "Player_7": "Saka 4",
    "Player_2": "O\u0027Reilly 2",
    "Player_5": "Rogers 5",
    "Player_6": "Wilson 6",
    "Player_3": "J.Timber 3",
    "Player_4": "Virgil 1",
    "Player_8": "Foden 2",
    "Player_9": "Bowen 4",
    "Player_15": "Devenny 1"
  },
  {
    "manager_Name": "1,202( 158,658 )",
    "Teams": "Kung fu Pandoos( Indrajeet Singh )",
    "SXL": "IND",
    "Latp": "52",
    "Player_1": "Kelleher 2",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 17",
    "Player_12": "S\u00E1nchez 0",
    "Player_13": "Keane 0",
    "Player_14": "Chalobah 4",
    "Player_7": "Wilson 6",
    "Player_2": "Virgil 1",
    "Player_5": "Saka 4",
    "Player_6": "Foden 2",
    "Player_3": "Gvardiol 1",
    "Player_4": "Pedro Porro",
    "Player_8": "Cunha 9",
    "Player_9": "Calvert-Lewin 2",
    "Player_15": "Devenny 1"
  },
  {
    "manager_Name": "1,194( 212,392 )",
    "Teams": "11 n over( Ashish Rai )",
    "SXL": "IND",
    "Latp": "34",
    "Player_1": "Raya 1",
    "Player_11": "Bowen 4",
    "Player_10": "Haaland 4",
    "Player_12": "Darlow 0",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Alderete 1",
    "Player_7": "Ayari 12",
    "Player_2": "J.Timber 3",
    "Player_5": "Trossard 1",
    "Player_6": "Cherki 4",
    "Player_3": "Kerkez 1",
    "Player_4": "Matheus N.",
    "Player_8": "Dibling 1",
    "Player_9": "Palmer 2",
    "Player_15": "Rodon 0"
  },
  {
    "manager_Name": "1,176( 394,833 )",
    "Teams": "MANCHESTER IS BLUE( PRAYAS BAJGAI )",
    "SXL": "IND",
    "Latp": "36",
    "Player_1": "A.Becker 1",
    "Player_11": "Haaland 4",
    "Player_10": "Semenyo 1",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Andersen 3",
    "Player_7": "Cherki 4",
    "Player_2": "Dorgu 1",
    "Player_5": "J.Timber 3",
    "Player_6": "Cunha 9",
    "Player_3": "Keane 0",
    "Player_4": "Gabriel 9",
    "Player_8": "Gordon 2",
    "Player_9": "Foden 2",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,171( 458,871 )",
    "Teams": "Top Gooner( VibhutiHang Subba )",
    "SXL": "IND",
    "Latp": "45",
    "Player_1": "Raya 1",
    "Player_11": "Haaland 4",
    "Player_10": "Bruno G.",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Obi 0",
    "Player_14": "Ekitik\u00E9 0",
    "Player_7": "Wilson 6",
    "Player_2": "Matheus N.",
    "Player_5": "Andersen 3",
    "Player_6": "Saka 4",
    "Player_3": "Gabriel 9",
    "Player_4": "Mukiele 4",
    "Player_8": "Semenyo 1",
    "Player_9": "Foden 2",
    "Player_15": "Rodon 0"
  },
  {
    "manager_Name": "1,170( 472,379 )",
    "Teams": "Alpha11( AVIJIT DAS )",
    "SXL": "IND",
    "Latp": "58",
    "Player_1": "Henderson 2",
    "Player_11": "Thiago 17",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "E.Le F\u00E9e",
    "Player_7": "Foden 2",
    "Player_2": "Gabriel 9",
    "Player_5": "Keane 0",
    "Player_6": "Bruno G.",
    "Player_3": "Mukiele 4",
    "Player_4": "Dorgu 1",
    "Player_8": "Saka 4",
    "Player_9": "Rogers 5",
    "Player_15": "Chalobah 4"
  },
  {
    "manager_Name": "1,147( 864,109 )",
    "Teams": "Blue Brigade( Bhuman Basnet )",
    "SXL": "IND",
    "Latp": "55",
    "Player_1": "Vicario 2",
    "Player_11": "Calvert-Lewin 2",
    "Player_10": "Thiago 17",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Wilson 6",
    "Player_14": "O\u0027Reilly 2",
    "Player_7": "Foden 2",
    "Player_2": "Cash 5",
    "Player_5": "Saka 4",
    "Player_6": "Bruno G.",
    "Player_3": "Keane 0",
    "Player_4": "Frimpong 4",
    "Player_8": "Rogers 5",
    "Player_9": "Haaland 4",
    "Player_15": "Gu\u00E9hi 2"
  },
  {
    "manager_Name": "1,142( 967,208 )",
    "Teams": "error404( Duri Tadu )",
    "SXL": "IND",
    "Latp": "43",
    "Player_1": "Raya 1",
    "Player_11": "Haaland 4",
    "Player_10": "E.Le F\u00E9e",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Andersen 3",
    "Player_7": "Saka 4",
    "Player_2": "Gabriel 9",
    "Player_5": "Dalot 2",
    "Player_6": "Foden 2",
    "Player_3": "Alderete 1",
    "Player_4": "Virgil 1",
    "Player_8": "Cunha 9",
    "Player_9": "Wilson 6",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,139( 1,036,812 )",
    "Teams": "RIP-DIOGO.20( pranam rai )",
    "SXL": "IND",
    "Latp": "30",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Haaland 4",
    "Player_10": "Ekitik\u00E9 0",
    "Player_12": "Vicario 2",
    "Player_13": "Cucurella 0",
    "Player_14": "B.Fernandes 0",
    "Player_7": "Foden 2",
    "Player_2": "Gu\u00E9hi 2",
    "Player_5": "Wilson 6",
    "Player_6": "Szoboszlai 2",
    "Player_3": "R\u00FAben 5",
    "Player_4": "J.Timber 3",
    "Player_8": "Anderson 4",
    "Player_9": "Woltemade 1",
    "Player_15": "Est\u00E8ve 0"
  },
  {
    "manager_Name": "1,132( 1,210,349 )",
    "Teams": "Comet FC( Pranesh Sharma )",
    "SXL": "IND",
    "Latp": "45",
    "Player_1": "Roefs 3",
    "Player_11": "Haaland 4",
    "Player_10": "Calvert-Lewin 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Andersen 3",
    "Player_7": "Rogers 5",
    "Player_2": "Dorgu 1",
    "Player_5": "Saka 4",
    "Player_6": "Foden 2",
    "Player_3": "Mukiele 4",
    "Player_4": "Cash 5",
    "Player_8": "Cunha 9",
    "Player_9": "Wilson 6",
    "Player_15": "Est\u00E8ve 0"
  },
  {
    "manager_Name": "1,124( 1,399,765 )",
    "Teams": "Cheesygarlic( Rishi Thulung )",
    "SXL": "IND",
    "Latp": "64",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 17",
    "Player_12": "S\u00E1nchez 0",
    "Player_13": "Kroupi.Jr 5",
    "Player_14": "Mukiele 4",
    "Player_7": "Wilson 6",
    "Player_2": "Tarkowski 2",
    "Player_5": "Xhaka 4",
    "Player_6": "Foden 2",
    "Player_3": "O\u0027Reilly 2",
    "Player_4": "Thiaw 17",
    "Player_8": "Saka 4",
    "Player_9": "Rogers 5",
    "Player_15": "Andersen 3"
  },
  {
    "manager_Name": "1,124( 1,408,321 )",
    "Teams": "Lu Lu( Nishant Lohagun )",
    "SXL": "IND",
    "Latp": "31",
    "Player_1": "Raya 1",
    "Player_11": "Haaland 4",
    "Player_10": "Anderson 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Richards 0",
    "Player_7": "Saka 4",
    "Player_2": "O\u0027Reilly 2",
    "Player_5": "Andersen 3",
    "Player_6": "Rogers 5",
    "Player_3": "Senesi 1",
    "Player_4": "Chalobah 4",
    "Player_8": "Foden 2",
    "Player_9": "Semenyo 1",
    "Player_15": "Kroupi.Jr 5"
  },
  {
    "manager_Name": "1,119( 1,557,031 )",
    "Teams": "G\u00CBNJ\u00CF\u00CF UNITED( Pema Bhutia )",
    "SXL": "IND",
    "Latp": "60",
    "Player_1": "Raya 1",
    "Player_11": "Thiago 17",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Senesi 1",
    "Player_7": "Saka 4",
    "Player_2": "Van de",
    "Player_5": "Foden 2",
    "Player_6": "L.Miley 7",
    "Player_3": "Tarkowski 2",
    "Player_4": "Dorgu 1",
    "Player_8": "Cunha 9",
    "Player_9": "Wilson 6",
    "Player_15": "Thiaw 17"
  },
  {
    "manager_Name": "1,117( 1,600,110 )",
    "Teams": "Fu\u00DFball-Mannschaft( Gaurav Shrestha )",
    "SXL": "IND",
    "Latp": "47",
    "Player_1": "Raya 1",
    "Player_11": "Haaland 4",
    "Player_10": "Anderson 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Marc Guiu",
    "Player_7": "Foden 2",
    "Player_2": "Keane 0",
    "Player_5": "Virgil 1",
    "Player_6": "Cherki 4",
    "Player_3": "Thiaw 17",
    "Player_4": "Alderete 1",
    "Player_8": "Saka 4",
    "Player_9": "Cunha 9",
    "Player_15": "Rodon 0"
  },
  {
    "manager_Name": "1,113( 1,727,084 )",
    "Teams": "Liverpool FC( Sunil Rai )",
    "SXL": "IND",
    "Latp": "69",
    "Player_1": "Raya 1",
    "Player_11": "Thiago 17",
    "Player_10": "Woltemade 1",
    "Player_12": "S\u00E1nchez 0",
    "Player_13": "Minteh 0",
    "Player_14": "Senesi 1",
    "Player_7": "Enzo 11",
    "Player_2": "Gvardiol 1",
    "Player_5": "Bruno G.",
    "Player_6": "Foden 2",
    "Player_3": "Van de",
    "Player_4": "Gabriel 9",
    "Player_8": "Wilson 6",
    "Player_9": "Haaland 4",
    "Player_15": "Rodon 0"
  },
  {
    "manager_Name": "1,112( 1,742,871 )",
    "Teams": "PINE( SATYAM RAI )",
    "SXL": "IND",
    "Latp": "34",
    "Player_1": "Raya 1",
    "Player_11": "Calvert-Lewin 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Mukiele 4",
    "Player_7": "Saka 4",
    "Player_2": "Dalot 2",
    "Player_5": "Stach 4",
    "Player_6": "Rogers 5",
    "Player_3": "J.Timber 3",
    "Player_4": "Virgil 1",
    "Player_8": "Foden 2",
    "Player_9": "Wilson 6",
    "Player_15": "Rodon 0"
  },
  {
    "manager_Name": "1,110( 1,815,515 )",
    "Teams": "Bruno-nly Fans( Bejoy M Shrestha\u00B2\u2076\u2074 )",
    "SXL": "IND",
    "Latp": "49",
    "Player_1": "Raya 1",
    "Player_11": "Woltemade 1",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "King 0",
    "Player_14": "Andersen 3",
    "Player_7": "Wirtz 10",
    "Player_2": "Tarkowski 2",
    "Player_5": "Saka 8",
    "Player_6": "Rogers 5",
    "Player_3": "Gabriel 9",
    "Player_4": "Van de",
    "Player_8": "Foden 2",
    "Player_9": "Calvert-Lewin 2",
    "Player_15": "Gudmundsson 2"
  },
  {
    "manager_Name": "1,106( 1,930,032 )",
    "Teams": "Busby Baby( Regean Lama )",
    "SXL": "IND",
    "Latp": "39",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Haaland 4",
    "Player_10": "Woltemade 1",
    "Player_12": "S\u00E1nchez 0",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Gu\u00E9hi 2",
    "Player_7": "Foden 2",
    "Player_2": "Van de",
    "Player_5": "Reijnders 10",
    "Player_6": "Saka 4",
    "Player_3": "Dorgu 1",
    "Player_4": "Dalot 2",
    "Player_8": "Rogers 5",
    "Player_9": "Tavernier 2",
    "Player_15": "Senesi 1"
  },
  {
    "manager_Name": "1,102( 2,060,831 )",
    "Teams": "ASHLAD FC( Ashim Lama )",
    "SXL": "IND",
    "Latp": "47",
    "Player_1": "Roefs 3",
    "Player_11": "Thiago 17",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Alderete 1",
    "Player_14": "Wilson 6",
    "Player_7": "Semenyo 1",
    "Player_2": "Chalobah 4",
    "Player_5": "Tarkowski 2",
    "Player_6": "Foden 2",
    "Player_3": "Gvardiol 1",
    "Player_4": "Senesi 1",
    "Player_8": "Palmer 2",
    "Player_9": "Bruno G.",
    "Player_15": "Kroupi.Jr 5"
  },
  {
    "manager_Name": "1,096( 2,262,647 )",
    "Teams": "\u0160e\u0161ko and Destroy( Pema Lepcha )",
    "SXL": "IND",
    "Latp": "35",
    "Player_1": "Raya 1",
    "Player_11": "Haaland 2",
    "Player_10": "Woltemade 1",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Van Hecke",
    "Player_14": "Wilson 6",
    "Player_7": "Cherki 4",
    "Player_2": "Gvardiol 1",
    "Player_5": "Semenyo 1",
    "Player_6": "Rogers 5",
    "Player_3": "Virgil 1",
    "Player_4": "Lewis-Potter 0",
    "Player_8": "Cunha 18",
    "Player_9": "Welbeck 1",
    "Player_15": "Senesi 1"
  },
  {
    "manager_Name": "1,088( 2,532,523 )",
    "Teams": "F.C. ASSASSINS( Kushal Sahota )",
    "SXL": "IND",
    "Latp": "51",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 17",
    "Player_12": "S\u00E1nchez 0",
    "Player_13": "Van de",
    "Player_14": "Est\u00E8ve 0",
    "Player_7": "Bruno G.",
    "Player_2": "Gu\u00E9hi 2",
    "Player_5": "Foden 2",
    "Player_6": "Saka 4",
    "Player_3": "J.Timber 3",
    "Player_4": "Matheus N.",
    "Player_8": "Rogers 5",
    "Player_9": "Calvert-Lewin 2",
    "Player_15": "Wilson 6"
  },
  {
    "manager_Name": "1,069( 3,221,182 )",
    "Teams": "Imperial Blues( Saurabh Tamang )",
    "SXL": "IND",
    "Latp": "49",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Thiago 17",
    "Player_10": "Haaland 4",
    "Player_12": "S\u00E1nchez 0",
    "Player_13": "Keane 0",
    "Player_14": "Est\u00E8ve 0",
    "Player_7": "Foden 2",
    "Player_2": "Chalobah 4",
    "Player_5": "Wilson 6",
    "Player_6": "Rogers 5",
    "Player_3": "J.Timber 3",
    "Player_4": "O\u0027Reilly 2",
    "Player_8": "Saka 4",
    "Player_9": "Semenyo 1",
    "Player_15": "Foster 0"
  },
  {
    "manager_Name": "1,068( 3,255,368 )",
    "Teams": "Hooligans25( Pradhyumna Subba )",
    "SXL": "IND",
    "Latp": "51",
    "Player_1": "Raya 1",
    "Player_11": "Haaland 2",
    "Player_10": "Neto 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Isidor 0",
    "Player_7": "Cherki 4",
    "Player_2": "Kerkez 1",
    "Player_5": "Konsa 2",
    "Player_6": "Wirtz 20",
    "Player_3": "Dorgu 1",
    "Player_4": "Van de",
    "Player_8": "Foden 2",
    "Player_9": "Cunha 9",
    "Player_15": "Reinildo 0"
  },
  {
    "manager_Name": "1,066( 3,330,543 )",
    "Teams": "GustavousGooner( Ashish Subba )",
    "SXL": "IND",
    "Latp": "39",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Haaland 2",
    "Player_10": "Ra\u00FAl 5",
    "Player_12": "S\u00E1nchez 0",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Dalot 2",
    "Player_7": "Semenyo 1",
    "Player_2": "Van Hecke",
    "Player_5": "Gu\u00E9hi 2",
    "Player_6": "Saka 4",
    "Player_3": "Gudmundsson 2",
    "Player_4": "O\u0027Reilly 2",
    "Player_8": "Rogers 10",
    "Player_9": "Cherki 4",
    "Player_15": "Rice 17"
  },
  {
    "manager_Name": "1,044( 4,173,065 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "49",
    "Player_1": "Raya 1",
    "Player_11": "Thiago 17",
    "Player_10": "Haaland 4",
    "Player_12": "Petrovi\u0107 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Rice 17",
    "Player_7": "Stach 4",
    "Player_2": "R\u00FAben 5",
    "Player_5": "Cash 5",
    "Player_6": "Alderete 1",
    "Player_3": "Mitchell 2",
    "Player_4": "Mukiele 4",
    "Player_8": "Saka 4",
    "Player_9": "Foden 2",
    "Player_15": "L.Miley 7"
  },
  {
    "manager_Name": "1,043( 4,211,312 )",
    "Teams": "The Regista.( Passang T Sherpa )",
    "SXL": "IND",
    "Latp": "41",
    "Player_1": "D\u00FAbravka 1",
    "Player_11": "Calvert-Lewin 2",
    "Player_10": "Haaland 4",
    "Player_12": "Roefs 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Cucurella 0",
    "Player_7": "Rice 17",
    "Player_2": "Keane 0",
    "Player_5": "Wilson 6",
    "Player_6": "Semenyo 1",
    "Player_3": "James 1",
    "Player_4": "Gu\u00E9hi 2",
    "Player_8": "Foden 2",
    "Player_9": "Rogers 5",
    "Player_15": "Dalot 2"
  },
  {
    "manager_Name": "1,041( 4,293,265 )",
    "Teams": "GUNNERS( Omkar Subba )",
    "SXL": "IND",
    "Latp": "46",
    "Player_1": "Verbruggen 7",
    "Player_11": "Haaland 4",
    "Player_10": "Casemiro 7",
    "Player_12": "Raya 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Keane 0",
    "Player_7": "Semenyo 1",
    "Player_2": "Gabriel 9",
    "Player_5": "Alderete 1",
    "Player_6": "Bruno G.",
    "Player_3": "Gu\u00E9hi 2",
    "Player_4": "Gvardiol 1",
    "Player_8": "Gravenberch 2",
    "Player_9": "Foden 2",
    "Player_15": "Calvert-Lewin 2"
  },
  {
    "manager_Name": "1,036( 4,482,570 )",
    "Teams": "Let MEE COOK( \u00CFaraplang Pompyrthat )",
    "SXL": "IND",
    "Latp": "43",
    "Player_1": "Verbruggen 7",
    "Player_11": "Haaland 4",
    "Player_10": "Foden 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Est\u00E8ve 0",
    "Player_7": "Gordon 2",
    "Player_2": "Mykolenko 0",
    "Player_5": "Andersen 3",
    "Player_6": "Saka 4",
    "Player_3": "J.Timber 3",
    "Player_4": "Gabriel 9",
    "Player_8": "Xhaka 4",
    "Player_9": "Rogers 5",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,015( 5,250,611 )",
    "Teams": "Native United( Monlom Rongong )",
    "SXL": "IND",
    "Latp": "46",
    "Player_1": "Raya 1",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 17",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Tavernier 2",
    "Player_14": "Chalobah 4",
    "Player_7": "Garner 4",
    "Player_2": "Senesi 1",
    "Player_5": "Rogers 5",
    "Player_6": "Wilson 6",
    "Player_3": "J.Timber 3",
    "Player_4": "Gu\u00E9hi 2",
    "Player_8": "Foden 2",
    "Player_9": "Woltemade 1",
    "Player_15": "Rodon 0"
  },
  {
    "manager_Name": "1,007( 5,554,892 )",
    "Teams": "Boehly Blues( Aditya Bhandari )",
    "SXL": "IND",
    "Latp": "74",
    "Player_1": "Petrovi\u0107 1",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago 17",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Gu\u00E9hi 2",
    "Player_7": "Rogers 10",
    "Player_2": "J.Timber 3",
    "Player_5": "O\u0027Reilly 2",
    "Player_6": "Rice 17",
    "Player_3": "James 1",
    "Player_4": "Gabriel 9",
    "Player_8": "Foden 2",
    "Player_9": "Bruno G.",
    "Player_15": "Wilson 6"
  },
  {
    "manager_Name": "991( 6,105,192 )",
    "Teams": "Jorebungalow YFC( Vivek Lama )",
    "SXL": "IND",
    "Latp": "64",
    "Player_1": "Areola 2",
    "Player_11": "Haaland 2",
    "Player_10": "Watkins 14",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Wilson 6",
    "Player_7": "Rogers 5",
    "Player_2": "O\u0027Reilly 2",
    "Player_5": "Thiaw 17",
    "Player_6": "Foden 2",
    "Player_3": "Van de",
    "Player_4": "Cash 5",
    "Player_8": "Semenyo 1",
    "Player_9": "L.Miley 7",
    "Player_15": "Est\u00E8ve 0"
  },
  {
    "manager_Name": "990( 6,136,874 )",
    "Teams": "Hangkim_0011( ABHINANDAN RAI )",
    "SXL": "IND",
    "Latp": "44",
    "Player_1": "Pickford 1",
    "Player_11": "Calvert-Lewin 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "L.Paquet\u00E1 0",
    "Player_14": "Ekitik\u00E9 0",
    "Player_7": "Rogers 5",
    "Player_2": "Tarkowski 2",
    "Player_5": "Konsa 2",
    "Player_6": "Cherki 4",
    "Player_3": "Gabriel 9",
    "Player_4": "Pedro Porro",
    "Player_8": "Bruno G.",
    "Player_9": "Trossard 1",
    "Player_15": "Est\u00E8ve 0"
  },
  {
    "manager_Name": "987( 6,231,072 )",
    "Teams": "GODFATHER FC( Riwaj Rai )",
    "SXL": "IND",
    "Latp": "30",
    "Player_1": "Donnarumma 2",
    "Player_11": "Haaland 2",
    "Player_10": "Gravenberch 2",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Isidor 0",
    "Player_7": "Semenyo 2",
    "Player_2": "Pedro Porro",
    "Player_5": "Cash 5",
    "Player_6": "Kudus 1",
    "Player_3": "Tarkowski 2",
    "Player_4": "Gu\u00E9hi 2",
    "Player_8": "Wilson 6",
    "Player_9": "Foden 2",
    "Player_15": "Digne 1"
  },
  {
    "manager_Name": "973( 6,688,629 )",
    "Teams": "I_am_done_XI( Dipen Thapa )",
    "SXL": "IND",
    "Latp": "37",
    "Player_1": "Raya 1",
    "Player_11": "Haaland 4",
    "Player_10": "Watkins 7",
    "Player_12": "D\u00FAbravka 1",
    "Player_13": "Wilson 6",
    "Player_14": "Senesi 1",
    "Player_7": "\u00D8degaard 7",
    "Player_2": "Gu\u00E9hi 2",
    "Player_5": "Rogers 5",
    "Player_6": "Kudus 1",
    "Player_3": "Van de",
    "Player_4": "Hincapie 1",
    "Player_8": "Semenyo 1",
    "Player_9": "Woltemade 1",
    "Player_15": "Konsa 2"
  },
  {
    "manager_Name": "916( 8,279,769 )",
    "Teams": "Invincibles( Bishal Rai )",
    "SXL": "IND",
    "Latp": "69",
    "Player_1": "Raya 1",
    "Player_11": "Thiago 17",
    "Player_10": "Mateta 2",
    "Player_12": "Kinsky 0",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Milenkovi\u0107 3",
    "Player_7": "Semenyo 1",
    "Player_2": "Gu\u00E9hi 2",
    "Player_5": "Foden 2",
    "Player_6": "Neto 2",
    "Player_3": "Gabriel 18",
    "Player_4": "J.Timber 3",
    "Player_8": "Bruno G.",
    "Player_9": "Enzo 11",
    "Player_15": "Pedro Porro"
  }
];