var s = [
  {
    "manager_Name": "1,256( 12,534 )",
    "Teams": "Rice Rice Baby( kaisler Schembri )",
    "SXL": "MLT",
    "Latp": "33",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 9",
    "Player_12": "John 0",
    "Player_13": "Szoboszlai ARS",
    "Player_14": "Anderson 7",
    "Player_7": "Foden 2",
    "Player_2": "Gabriel LIV",
    "Player_5": "Thiaw -1",
    "Player_6": "Cunha 2",
    "Player_3": "J.Timber LIV",
    "Player_4": "Dorgu 4",
    "Player_8": "Saka LIV",
    "Player_9": "Bowen 2",
    "Player_15": "Andersen 2"
  },
  {
    "manager_Name": "1,202( 166,839 )",
    "Teams": "Charlie\u0027s Angels( Charlie Smith )",
    "SXL": "ENG",
    "Latp": "49",
    "Player_1": "Roefs 2",
    "Player_11": "Woltemade 5",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "R\u00FAben 0",
    "Player_14": "Est\u00E8ve 3",
    "Player_7": "Saka LIV",
    "Player_2": "Thiaw -1",
    "Player_5": "Palmer 1",
    "Player_6": "Foden 2",
    "Player_3": "Lacroix 8",
    "Player_4": "Mukiele 3",
    "Player_8": "Bruno G.",
    "Player_9": "Wilson 7",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,186( 288,821 )",
    "Teams": "MaltArsenal FC( Claude Spiteri )",
    "SXL": "MLT",
    "Latp": "38",
    "Player_1": "Donnarumma 1",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 9",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Senesi 6",
    "Player_14": "Semenyo 6",
    "Player_7": "Enzo 1",
    "Player_2": "J.Timber LIV",
    "Player_5": "Rice LIV",
    "Player_6": "Gordon 1",
    "Player_3": "Mukiele 3",
    "Player_4": "Gabriel LIV",
    "Player_8": "Bruno G.",
    "Player_9": "Richarlison 1",
    "Player_15": "Gu\u00E9hi 6"
  },
  {
    "manager_Name": "1,171( 463,088 )",
    "Teams": "Arteta Ball FC( Dylan Camilleri )",
    "SXL": "MLT",
    "Latp": "39",
    "Player_1": "Raya LIV",
    "Player_11": "Watkins 2",
    "Player_10": "Thiago 9",
    "Player_12": "Darlow 0",
    "Player_13": "Hincapie LIV",
    "Player_14": "Minteh 0",
    "Player_7": "Saka LIV",
    "Player_2": "Mukiele 3",
    "Player_5": "Cherki 1",
    "Player_6": "Xhaka 2",
    "Player_3": "Tarkowski 4",
    "Player_4": "Van Hecke",
    "Player_8": "Rogers 3",
    "Player_9": "Haaland 12",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "1,170( 476,743 )",
    "Teams": "Bend it like Boogie( Ryan Bonello Gatt )",
    "SXL": "MLT",
    "Latp": "51",
    "Player_1": "Kelleher 12",
    "Player_11": "Barry 2",
    "Player_10": "Calvert-Lewin 8",
    "Player_12": "Verbruggen 3",
    "Player_13": "Xhaka 2",
    "Player_14": "Mukiele 3",
    "Player_7": "Saka LIV",
    "Player_2": "Saliba LIV",
    "Player_5": "Foden 2",
    "Player_6": "Rogers 3",
    "Player_3": "J.Timber LIV",
    "Player_4": "Cash 6",
    "Player_8": "Semenyo 6",
    "Player_9": "Haaland 12",
    "Player_15": "Gu\u00E9hi 6"
  },
  {
    "manager_Name": "1,166( 540,612 )",
    "Teams": "Taggers FC( Karl Caruana )",
    "SXL": "MLT",
    "Latp": "53",
    "Player_1": "Kelleher 12",
    "Player_11": "Haaland 12",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Mukiele 3",
    "Player_14": "Minteh 0",
    "Player_7": "Cherki 1",
    "Player_2": "Gabriel LIV",
    "Player_5": "Wilson 7",
    "Player_6": "Saka LIV",
    "Player_3": "James 1",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Rogers 3",
    "Player_9": "Thiago 9",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "1,160( 624,817 )",
    "Teams": "diavoli 11( Paul Micallef )",
    "SXL": "MLT",
    "Latp": "51",
    "Player_1": "Donnarumma 1",
    "Player_11": "Calvert-Lewin 8",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 ARS",
    "Player_14": "Gu\u00E9hi 6",
    "Player_7": "Semenyo 6",
    "Player_2": "Senesi 6",
    "Player_5": "Bruno G.",
    "Player_6": "Rogers 3",
    "Player_3": "J.Timber LIV",
    "Player_4": "Chalobah 3",
    "Player_8": "Foden 2",
    "Player_9": "Rice LIV",
    "Player_15": "Byram 0"
  },
  {
    "manager_Name": "1,159( 639,067 )",
    "Teams": "Ellul FC( Andrew Ellul )",
    "SXL": "MLT",
    "Latp": "34",
    "Player_1": "Pope 2",
    "Player_11": "Watkins 2",
    "Player_10": "Haaland 6",
    "Player_12": "Henderson 7",
    "Player_13": "Milenkovi\u0107 2",
    "Player_14": "Wilson 7",
    "Player_7": "Rogers 3",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Van de",
    "Player_6": "Rice LIV",
    "Player_3": "Gabriel LIV",
    "Player_4": "J.Timber LIV",
    "Player_8": "Semenyo 6",
    "Player_9": "Thiago 9",
    "Player_15": "Tavernier 5"
  },
  {
    "manager_Name": "1,157( 677,240 )",
    "Teams": "Slika FC( Kyle Gatt )",
    "SXL": "MLT",
    "Latp": "40",
    "Player_1": "Lammens 1",
    "Player_11": "Gy\u00F6keres LIV",
    "Player_10": "Woltemade 5",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Gravenberch ARS",
    "Player_14": "Virgil ARS",
    "Player_7": "Rice LIV",
    "Player_2": "Pedro Porro",
    "Player_5": "Bruno G.",
    "Player_6": "Cunha 2",
    "Player_3": "Hartman 0",
    "Player_4": "Sch\u00E4r 3",
    "Player_8": "Wilson 7",
    "Player_9": "Haaland 12",
    "Player_15": "R\u00FAben 0"
  },
  {
    "manager_Name": "1,156( 690,912 )",
    "Teams": "Bench Warmers( kevin dalli )",
    "SXL": "MLT",
    "Latp": "55",
    "Player_1": "Kelleher 12",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 9",
    "Player_12": "Petrovi\u0107 1",
    "Player_13": "Wilson 7",
    "Player_14": "Jo\u00E3o Pedro",
    "Player_7": "Foden 2",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Hall 4",
    "Player_6": "Saka LIV",
    "Player_3": "Van de",
    "Player_4": "Mukiele 3",
    "Player_8": "Semenyo 6",
    "Player_9": "Gordon 1",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "1,131( 1,240,702 )",
    "Teams": "Let him cook( Henry Adjei )",
    "SXL": "MLT",
    "Latp": "46",
    "Player_1": "Raya LIV",
    "Player_11": "Watkins 2",
    "Player_10": "Thiago 9",
    "Player_12": "Kelleher 12",
    "Player_13": "Wilson 7",
    "Player_14": "R\u00FAben 0",
    "Player_7": "Semenyo 6",
    "Player_2": "Cash 6",
    "Player_5": "Mukiele 3",
    "Player_6": "Saka LIV",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Gabriel LIV",
    "Player_8": "Xhaka 2",
    "Player_9": "Haaland 12",
    "Player_15": "Kudus 0"
  },
  {
    "manager_Name": "1,130( 1,263,321 )",
    "Teams": "TetasSexyReds( Gary Pace )",
    "SXL": "MLT",
    "Latp": "40",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Ekitik\u00E9 ARS",
    "Player_10": "Haaland 12",
    "Player_12": "Henderson 7",
    "Player_13": "Wilson 7",
    "Player_14": "Mukiele 3",
    "Player_7": "Rice LIV",
    "Player_2": "Gabriel LIV",
    "Player_5": "Saka LIV",
    "Player_6": "Foden 2",
    "Player_3": "Konsa 6",
    "Player_4": "Cash 6",
    "Player_8": "Reijnders 2",
    "Player_9": "Thiago 9",
    "Player_15": "Andersen 2"
  },
  {
    "manager_Name": "1,129( 1,279,415 )",
    "Teams": "RZM765( Cedrik Dalli )",
    "SXL": "MLT",
    "Latp": "38",
    "Player_1": "Roefs 2",
    "Player_11": "Haaland 12",
    "Player_10": "Bowen 2",
    "Player_12": "Verbruggen 3",
    "Player_13": "Neto 5",
    "Player_14": "Est\u00E8ve 3",
    "Player_7": "Bruno G.",
    "Player_2": "Van de",
    "Player_5": "Rice LIV",
    "Player_6": "Rogers 3",
    "Player_3": "Chalobah 3",
    "Player_4": "Matheus N.",
    "Player_8": "Foden 2",
    "Player_9": "Mateta 2",
    "Player_15": "Rodon 1"
  },
  {
    "manager_Name": "1,123( 1,444,335 )",
    "Teams": "GunnerPorts( Matthew Portelli )",
    "SXL": "MLT",
    "Latp": "40",
    "Player_1": "Pope 2",
    "Player_11": "Haaland 12",
    "Player_10": "Bowen 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 ARS",
    "Player_14": "Gabriel LIV",
    "Player_7": "Cherki 1",
    "Player_2": "Hincapie LIV",
    "Player_5": "Wilson 7",
    "Player_6": "Minteh 0",
    "Player_3": "Senesi 6",
    "Player_4": "Lacroix 8",
    "Player_8": "Rice LIV",
    "Player_9": "Cunha 2",
    "Player_15": "Gudmundsson 0"
  },
  {
    "manager_Name": "1,118( 1,590,754 )",
    "Teams": "Select Team Name( Kurt Bonnici )",
    "SXL": "MLT",
    "Latp": "52",
    "Player_1": "Kelleher 12",
    "Player_11": "Thiago 9",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 ARS",
    "Player_14": "Virgil ARS",
    "Player_7": "Saka LIV",
    "Player_2": "Gabriel LIV",
    "Player_5": "Anderson 7",
    "Player_6": "Foden 2",
    "Player_3": "Kayode 6",
    "Player_4": "Thiaw -1",
    "Player_8": "L.Miley 4",
    "Player_9": "Cherki 1",
    "Player_15": "Gudmundsson 0"
  },
  {
    "manager_Name": "1,116( 1,636,362 )",
    "Teams": "gunner_xi( Justin kind )",
    "SXL": "MLT",
    "Latp": "36",
    "Player_1": "Raya LIV",
    "Player_11": "Haaland 12",
    "Player_10": "Wilson 7",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Saliba LIV",
    "Player_14": "Ekitik\u00E9 ARS",
    "Player_7": "Hutchinson 1",
    "Player_2": "Thiaw -1",
    "Player_5": "Cash 6",
    "Player_6": "Cherki 1",
    "Player_3": "Tarkowski 4",
    "Player_4": "Shaw 1",
    "Player_8": "Foden 2",
    "Player_9": "Rogers 3",
    "Player_15": "Calvert-Lewin 8"
  },
  {
    "manager_Name": "1,116( 1,652,963 )",
    "Teams": "Sultan Army( Julian Sultana )",
    "SXL": "MLT",
    "Latp": "40",
    "Player_1": "Pickford 3",
    "Player_11": "Thiago 18",
    "Player_10": "Calvert-Lewin 8",
    "Player_12": "Donnarumma 1",
    "Player_13": "Chalobah 3",
    "Player_14": "Mateta 2",
    "Player_7": "Saka LIV",
    "Player_2": "Cash 6",
    "Player_5": "Gabriel LIV",
    "Player_6": "Cherki 1",
    "Player_3": "Thiaw -1",
    "Player_4": "J.Timber LIV",
    "Player_8": "Rogers 3",
    "Player_9": "Foden 2",
    "Player_15": "Semenyo 6"
  },
  {
    "manager_Name": "1,115( 1,669,096 )",
    "Teams": "matthew 14( matthew borg )",
    "SXL": "MLT",
    "Latp": "36",
    "Player_1": "Martinez 1",
    "Player_11": "Haaland 12",
    "Player_10": "Watkins 2",
    "Player_12": "King 0",
    "Player_13": "Lacroix 8",
    "Player_14": "Donovan 0",
    "Player_7": "Wirtz ARS",
    "Player_2": "Chalobah 3",
    "Player_5": "Cunha 2",
    "Player_6": "Reijnders 2",
    "Player_3": "Pedro Porro",
    "Player_4": "Konsa 6",
    "Player_8": "Semenyo 6",
    "Player_9": "Bowen 2",
    "Player_15": "Mavropanos 2"
  },
  {
    "manager_Name": "1,114( 1,708,247 )",
    "Teams": "Gozo Gunners( Jonathan Portelli )",
    "SXL": "MLT",
    "Latp": "36",
    "Player_1": "Pickford 3",
    "Player_11": "Ekitik\u00E9 ARS",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Stach 2",
    "Player_14": "De Cuyper",
    "Player_7": "Rice LIV",
    "Player_2": "Gabriel LIV",
    "Player_5": "Cash 6",
    "Player_6": "Saka LIV",
    "Player_3": "Mukiele 3",
    "Player_4": "Collins 9",
    "Player_8": "Foden 2",
    "Player_9": "Gordon 1",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,113( 1,728,665 )",
    "Teams": "Old Havertz Kai Hard( Andy Bonaci )",
    "SXL": "MLT",
    "Latp": "40",
    "Player_1": "Raya LIV",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 9",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Anderson 7",
    "Player_14": "Alderete 1",
    "Player_7": "Foden 2",
    "Player_2": "O\u0027Reilly 1",
    "Player_5": "Cunha 2",
    "Player_6": "Rice LIV",
    "Player_3": "Gabriel LIV",
    "Player_4": "Senesi 6",
    "Player_8": "Semenyo 6",
    "Player_9": "Mateta 2",
    "Player_15": "Mukiele 3"
  },
  {
    "manager_Name": "1,110( 1,811,777 )",
    "Teams": "Hamrun Gunners( Mark Monseigneur )",
    "SXL": "MLT",
    "Latp": "27",
    "Player_1": "Pickford 3",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 12",
    "Player_12": "Henderson 7",
    "Player_13": "O\u0027Brien 2",
    "Player_14": "Toti 0",
    "Player_7": "Casemiro 4",
    "Player_2": "Mykolenko 2",
    "Player_5": "Rice LIV",
    "Player_6": "Saka LIV",
    "Player_3": "Virgil ARS",
    "Player_4": "Pedro Porro",
    "Player_8": "Eze LIV",
    "Player_9": "Woltemade 5",
    "Player_15": "Cullen 0"
  },
  {
    "manager_Name": "1,110( 1,814,787 )",
    "Teams": "The Invincibles 49( Clive Caruana )",
    "SXL": "MLT",
    "Latp": "49",
    "Player_1": "Roefs 2",
    "Player_11": "Thiago 9",
    "Player_10": "Woltemade 5",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Van de",
    "Player_14": "B.Fernandes 5",
    "Player_7": "Rice LIV",
    "Player_2": "Cash 6",
    "Player_5": "Wilson 7",
    "Player_6": "Semenyo 6",
    "Player_3": "Gabriel LIV",
    "Player_4": "J.Timber LIV",
    "Player_8": "Foden 2",
    "Player_9": "Haaland 12",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "1,109( 1,856,668 )",
    "Teams": "Gunz( Kurt Zammit )",
    "SXL": "MLT",
    "Latp": "39",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Haaland 12",
    "Player_10": "Woltemade 5",
    "Player_12": "S\u00E1nchez 2",
    "Player_13": "Anthony 6",
    "Player_14": "Calvert-Lewin 8",
    "Player_7": "Rogers 3",
    "Player_2": "Gabriel LIV",
    "Player_5": "James 1",
    "Player_6": "Foden 2",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "J.Timber LIV",
    "Player_8": "Rice LIV",
    "Player_9": "Wilson 7",
    "Player_15": "Cash 6"
  },
  {
    "manager_Name": "1,107( 1,910,121 )",
    "Teams": "kurt slika( Kurt Gatt )",
    "SXL": "MLT",
    "Latp": "35",
    "Player_1": "Raya LIV",
    "Player_11": "Thiago 9",
    "Player_10": "Gy\u00F6keres LIV",
    "Player_12": "Jos\u00E9 S\u00E1",
    "Player_13": "Cash 6",
    "Player_14": "Virgil ARS",
    "Player_7": "Garner 4",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "\u00D8degaard LIV",
    "Player_6": "Foden 2",
    "Player_3": "Van de",
    "Player_4": "R\u00FAben 0",
    "Player_8": "Xhaka 2",
    "Player_9": "Haaland 12",
    "Player_15": "Wilson 7"
  },
  {
    "manager_Name": "1,097( 2,239,974 )",
    "Teams": "Very Rice( Jake Caruana )",
    "SXL": "MLT",
    "Latp": "47",
    "Player_1": "Raya LIV",
    "Player_11": "Haaland 6",
    "Player_10": "Thiago 9",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 ARS",
    "Player_14": "Gu\u00E9hi 6",
    "Player_7": "Foden 2",
    "Player_2": "J.Timber LIV",
    "Player_5": "Saka LIV",
    "Player_6": "Wilson 7",
    "Player_3": "Senesi 6",
    "Player_4": "Matheus N.",
    "Player_8": "Bruno G.",
    "Player_9": "Tavernier 5",
    "Player_15": "Gudmundsson 0"
  },
  {
    "manager_Name": "1,086( 2,614,771 )",
    "Teams": "Sammygooner****( Sammy Vella )",
    "SXL": "MLT",
    "Latp": "41",
    "Player_1": "Pope 2",
    "Player_11": "Haaland 12",
    "Player_10": "Gy\u00F6keres LIV",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Gordon 1",
    "Player_14": "Virgil ARS",
    "Player_7": "Semenyo 6",
    "Player_2": "Konsa 6",
    "Player_5": "Reijnders 2",
    "Player_6": "Rice LIV",
    "Player_3": "O\u0027Reilly 1",
    "Player_4": "Van de",
    "Player_8": "Rogers 3",
    "Player_9": "Thiago 9",
    "Player_15": "Hume 0"
  },
  {
    "manager_Name": "1,081( 2,795,791 )",
    "Teams": "Noni your business( Owen Farrugia )",
    "SXL": "MLT",
    "Latp": "30",
    "Player_1": "Raya LIV",
    "Player_11": "Wilson 0",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Andersen 2",
    "Player_14": "L.Paquet\u00E1 2",
    "Player_7": "Rogers 3",
    "Player_2": "J.Timber LIV",
    "Player_5": "Foden 2",
    "Player_6": "Grealish -1",
    "Player_3": "Tarkowski 4",
    "Player_4": "James 1",
    "Player_8": "Wilson 7",
    "Player_9": "Haaland 12",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "1,078( 2,901,925 )",
    "Teams": "Eze Come Eze Go( Theo Magro )",
    "SXL": "MLT",
    "Latp": "52",
    "Player_1": "Raya LIV",
    "Player_11": "Thiago 9",
    "Player_10": "Ekitik\u00E9 ARS",
    "Player_12": "Petrovi\u0107 1",
    "Player_13": "Xhaka 2",
    "Player_14": "Merino LIV",
    "Player_7": "Foden 2",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "J.Timber LIV",
    "Player_6": "Semenyo 6",
    "Player_3": "Cash 6",
    "Player_4": "Tarkowski 4",
    "Player_8": "Wilson 7",
    "Player_9": "Haaland 12",
    "Player_15": "Lacroix 8"
  },
  {
    "manager_Name": "1,071( 3,168,274 )",
    "Teams": "Kind FC( Richard Kind )",
    "SXL": "MLT",
    "Latp": "33",
    "Player_1": "Raya LIV",
    "Player_11": "Haaland 12",
    "Player_10": "Enzo 1",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 ARS",
    "Player_14": "Kroupi.Jr 6",
    "Player_7": "Rice LIV",
    "Player_2": "Virgil ARS",
    "Player_5": "Martinez 1",
    "Player_6": "Lacroix 8",
    "Player_3": "Cash 6",
    "Player_4": "Saliba LIV",
    "Player_8": "Foden 2",
    "Player_9": "Rogers 3",
    "Player_15": "Potts 1"
  },
  {
    "manager_Name": "1,070( 3,184,231 )",
    "Teams": "Clarky FC( Carl Clark )",
    "SXL": "ENG",
    "Latp": "38",
    "Player_1": "Raya LIV",
    "Player_11": "Haaland 12",
    "Player_10": "Casemiro 4",
    "Player_12": "Slonina 0",
    "Player_13": "Mayenda 1",
    "Player_14": "Mitchell 5",
    "Player_7": "Enzo 1",
    "Player_2": "Konat\u00E9 ARS",
    "Player_5": "Chalobah 3",
    "Player_6": "Garner 4",
    "Player_3": "Murillo 2",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Saka LIV",
    "Player_9": "Semenyo 6",
    "Player_15": "Ekitik\u00E9 ARS"
  },
  {
    "manager_Name": "1,069( 3,233,897 )",
    "Teams": "Kanokk 118( Rodney Azzopardi )",
    "SXL": "MLT",
    "Latp": "35",
    "Player_1": "Donnarumma 1",
    "Player_11": "Thiago 9",
    "Player_10": "Woltemade 5",
    "Player_12": "Kelleher 12",
    "Player_13": "Neto 5",
    "Player_14": "Cucurella -3",
    "Player_7": "Saka LIV",
    "Player_2": "J.Timber LIV",
    "Player_5": "Rice LIV",
    "Player_6": "Semenyo 6",
    "Player_3": "Mukiele 3",
    "Player_4": "Cash 6",
    "Player_8": "Rogers 3",
    "Player_9": "Watkins 2",
    "Player_15": "Gu\u00E9hi 6"
  },
  {
    "manager_Name": "1,067( 3,308,661 )",
    "Teams": "Zubi-Dooby Doo( Malcolm Vella Vidal )",
    "SXL": "MLT",
    "Latp": "42",
    "Player_1": "Verbruggen 3",
    "Player_11": "Haaland 12",
    "Player_10": "Bowen 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "J.Timber LIV",
    "Player_14": "Calvert-Lewin 8",
    "Player_7": "Garner 4",
    "Player_2": "Matheus N.",
    "Player_5": "Wilson 7",
    "Player_6": "Saka LIV",
    "Player_3": "Keane 5",
    "Player_4": "Hall 4",
    "Player_8": "Foden 2",
    "Player_9": "Enzo 1",
    "Player_15": "Andersen 2"
  },
  {
    "manager_Name": "1,060( 3,570,731 )",
    "Teams": "Lassie fc( Kirsten Tanti )",
    "SXL": "MLT",
    "Latp": "42",
    "Player_1": "Raya LIV",
    "Player_11": "Kroupi.Jr 6",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Van de",
    "Player_14": "Pedro Porro",
    "Player_7": "Foden 2",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Saka LIV",
    "Player_6": "Reijnders 2",
    "Player_3": "James 1",
    "Player_4": "Cucurella -3",
    "Player_8": "Anderson 7",
    "Player_9": "Thiago 9",
    "Player_15": "Rogers 3"
  },
  {
    "manager_Name": "1,059( 3,624,313 )",
    "Teams": "SC CARBINE( yan cutajar )",
    "SXL": "MLT",
    "Latp": "50",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Woltemade 5",
    "Player_10": "Haaland 12",
    "Player_12": "Raya LIV",
    "Player_13": "Milenkovi\u0107 2",
    "Player_14": "Gu\u00E9hi 6",
    "Player_7": "Reijnders 2",
    "Player_2": "Romero 3",
    "Player_5": "Gibbs-White 9",
    "Player_6": "Wirtz ARS",
    "Player_3": "Gabriel LIV",
    "Player_4": "Gvardiol 0",
    "Player_8": "Wilson 7",
    "Player_9": "Thiago 9",
    "Player_15": "Semenyo 6"
  },
  {
    "manager_Name": "1,058( 3,643,116 )",
    "Teams": "Lions( Daniel Ferriggi )",
    "SXL": "MLT",
    "Latp": "51",
    "Player_1": "Raya LIV",
    "Player_11": "Haaland 12",
    "Player_10": "Mateta 2",
    "Player_12": "Verbruggen 3",
    "Player_13": "Wilson 7",
    "Player_14": "Dalot 1",
    "Player_7": "Rogers 3",
    "Player_2": "Keane 5",
    "Player_5": "Semenyo 6",
    "Player_6": "Rice LIV",
    "Player_3": "Chalobah 3",
    "Player_4": "O\u0027Reilly 1",
    "Player_8": "Bruno G.",
    "Player_9": "Thiago 9",
    "Player_15": "Hincapie LIV"
  },
  {
    "manager_Name": "1,058( 3,654,220 )",
    "Teams": "Senglea Gunners( Daryl Ebejer )",
    "SXL": "MLT",
    "Latp": "46",
    "Player_1": "Raya LIV",
    "Player_11": "Haaland 12",
    "Player_10": "Calvert-Lewin 8",
    "Player_12": "Moore 0",
    "Player_13": "Alderete 1",
    "Player_14": "Virgil ARS",
    "Player_7": "Xhaka 2",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Semenyo 6",
    "Player_6": "Rogers 3",
    "Player_3": "R\u00FAben 0",
    "Player_4": "J.Timber LIV",
    "Player_8": "Rice LIV",
    "Player_9": "Thiago 9",
    "Player_15": "Foden 2"
  },
  {
    "manager_Name": "1,047( 4,065,413 )",
    "Teams": "Dial Square( Liam Carabott )",
    "SXL": "MLT",
    "Latp": "41",
    "Player_1": "Roefs 2",
    "Player_11": "Haaland 12",
    "Player_10": "Calvert-Lewin 8",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Gu\u00E9hi 6",
    "Player_14": "Semenyo 6",
    "Player_7": "Bruno G.",
    "Player_2": "J.Timber LIV",
    "Player_5": "Enzo 1",
    "Player_6": "Minteh 0",
    "Player_3": "Cash 6",
    "Player_4": "O\u0027Reilly 1",
    "Player_8": "Rice LIV",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Chalobah 3"
  },
  {
    "manager_Name": "1,044( 4,184,183 )",
    "Teams": "Henry\u2019s Heroes( Jean Azzopardi )",
    "SXL": "MLT",
    "Latp": "37",
    "Player_1": "Donnarumma 1",
    "Player_11": "Thiago 9",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Wilson 7",
    "Player_14": "Tete 0",
    "Player_7": "Cherki 1",
    "Player_2": "Thiaw -1",
    "Player_5": "Trossard LIV",
    "Player_6": "Saka LIV",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Alderete 1",
    "Player_8": "Rogers 3",
    "Player_9": "Woltemade 5",
    "Player_15": "Calafiori LIV"
  },
  {
    "manager_Name": "1,044( 4,189,274 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "37",
    "Player_1": "Raya LIV",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 9",
    "Player_12": "Petrovi\u0107 1",
    "Player_13": "Ekitik\u00E9 ARS",
    "Player_14": "L.Miley 4",
    "Player_7": "Foden 2",
    "Player_2": "Mukiele 3",
    "Player_5": "Mitchell 5",
    "Player_6": "Alderete 1",
    "Player_3": "Cash 6",
    "Player_4": "Thiaw -1",
    "Player_8": "Saka LIV",
    "Player_9": "Rice LIV",
    "Player_15": "Stach 2"
  },
  {
    "manager_Name": "1,034( 4,561,998 )",
    "Teams": "Mandra United( Steven Silvio )",
    "SXL": "MLT",
    "Latp": "47",
    "Player_1": "Raya LIV",
    "Player_11": "Wilson 0",
    "Player_10": "Thiago 9",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Xhaka 2",
    "Player_14": "Virgil ARS",
    "Player_7": "Foden 2",
    "Player_2": "Senesi 6",
    "Player_5": "Rice LIV",
    "Player_6": "Semenyo 6",
    "Player_3": "Mitchell 5",
    "Player_4": "Gabriel LIV",
    "Player_8": "Anderson 7",
    "Player_9": "Haaland 12",
    "Player_15": "Gvardiol 0"
  },
  {
    "manager_Name": "993( 6,037,955 )",
    "Teams": "Rice Rice Baby( Ian Falzon )",
    "SXL": "MLT",
    "Latp": "31",
    "Player_1": "Donnarumma 1",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 6",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Woltemade 5",
    "Player_14": "Van de",
    "Player_7": "Neto 5",
    "Player_2": "Senesi 6",
    "Player_5": "Caicedo 4",
    "Player_6": "Mbeumo 0",
    "Player_3": "Virgil ARS",
    "Player_4": "J.Timber LIV",
    "Player_8": "Xhaka 2",
    "Player_9": "Semenyo 6",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "987( 6,250,126 )",
    "Teams": "Mihawha( Matthew Paris )",
    "SXL": "MLT",
    "Latp": "44",
    "Player_1": "Raya LIV",
    "Player_11": "Thiago 9",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Gy\u00F6keres LIV",
    "Player_14": "Van de",
    "Player_7": "Wilson 7",
    "Player_2": "Mukiele 3",
    "Player_5": "Semenyo 6",
    "Player_6": "Rice LIV",
    "Player_3": "James 1",
    "Player_4": "Chalobah 3",
    "Player_8": "Xhaka 2",
    "Player_9": "Cherki 1",
    "Player_15": "Mu\u00F1oz 0"
  },
  {
    "manager_Name": "950( 7,390,404 )",
    "Teams": "Gy\u00F6keres14( Zack Vella )",
    "SXL": "MLT",
    "Latp": "27",
    "Player_1": "Raya LIV",
    "Player_11": "Gy\u00F6keres LIV",
    "Player_10": "Haaland 12",
    "Player_12": "Heaton 0",
    "Player_13": "Gudmundsson 0",
    "Player_14": "Matete 0",
    "Player_7": "Rogers 3",
    "Player_2": "Truffert 1",
    "Player_5": "Saka LIV",
    "Player_6": "Foden 2",
    "Player_3": "Ballard 1",
    "Player_4": "Konsa 6",
    "Player_8": "Gonzalez 0",
    "Player_9": "Watkins 2",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "941( 7,629,557 )",
    "Teams": "NLD( Jordi Farrugia )",
    "SXL": "MLT",
    "Latp": "21",
    "Player_1": "Raya LIV",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "\u0160e\u0161ko 10",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Romero 3",
    "Player_14": "Saka LIV",
    "Player_7": "Eze LIV",
    "Player_2": "Cucurella -3",
    "Player_5": "James 1",
    "Player_6": "Elanga 0",
    "Player_3": "Gabriel LIV",
    "Player_4": "Burn 0",
    "Player_8": "Gibbs-White 9",
    "Player_9": "Rogers 3",
    "Player_15": "Evanilson 6"
  },
  {
    "manager_Name": "911( 8,417,955 )",
    "Teams": "Gorsil Gunners( Gordon Silvio )",
    "SXL": "MLT",
    "Latp": "39",
    "Player_1": "Raya LIV",
    "Player_11": "Thiago 9",
    "Player_10": "Haaland 12",
    "Player_12": "Sels 3",
    "Player_13": "Kluivert 0",
    "Player_14": "Konsa 6",
    "Player_7": "Semenyo 6",
    "Player_2": "James 1",
    "Player_5": "Wan-Bissaka 0",
    "Player_6": "Eze LIV",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Van de",
    "Player_8": "Neto 5",
    "Player_9": "Marmoush 0",
    "Player_15": "Beto 1"
  },
  {
    "manager_Name": "904( 8,589,999 )",
    "Teams": "Jack Nigret( Jack Gatt )",
    "SXL": "MLT",
    "Latp": "12",
    "Player_1": "Donnarumma 1",
    "Player_11": "Gy\u00F6keres LIV",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Mamardashvili ARS",
    "Player_13": "Rogers 3",
    "Player_14": "Gonzalez 0",
    "Player_7": "Potts 1",
    "Player_2": "Van de",
    "Player_5": "Konat\u00E9 ARS",
    "Player_6": "Reijnders 2",
    "Player_3": "Gabriel LIV",
    "Player_4": "Frimpong ARS",
    "Player_8": "Palmer 1",
    "Player_9": "Haaland 6",
    "Player_15": "Dixon 0"
  },
  {
    "manager_Name": "903( 8,617,410 )",
    "Teams": "Viktooooooor( Fredrick Buhagiar )",
    "SXL": "MLT",
    "Latp": "48",
    "Player_1": "Donnarumma 1",
    "Player_11": "Thiago 9",
    "Player_10": "Haaland 12",
    "Player_12": "S\u00E1nchez 2",
    "Player_13": "Gy\u00F6keres LIV",
    "Player_14": "Mukiele 3",
    "Player_7": "Enzo 1",
    "Player_2": "Mitchell 5",
    "Player_5": "Saka LIV",
    "Player_6": "Wilson 7",
    "Player_3": "Milenkovi\u0107 2",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Xhaka 2",
    "Player_9": "Rogers 3",
    "Player_15": "Reinildo 0"
  },
  {
    "manager_Name": "900( 8,674,692 )",
    "Teams": "Boca Seniors FC( Jake Bonnici )",
    "SXL": "MLT",
    "Latp": "11",
    "Player_1": "Vicario 1",
    "Player_11": "Beto 1",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Ramsdale 0",
    "Player_13": "Cherki 1",
    "Player_14": "Lewis-Skelly LIV",
    "Player_7": "Saka LIV",
    "Player_2": "Kerkez ARS",
    "Player_5": "M.Salah ARS",
    "Player_6": "Rogers 3",
    "Player_3": "Bassey 0",
    "Player_4": "Spence 1",
    "Player_8": "Wharton 3",
    "Player_9": "Ekitik\u00E9 ARS",
    "Player_15": "Aina 2"
  },
  {
    "manager_Name": "858( 9,577,803 )",
    "Teams": "Harambe FC( Glenn Gauci Borda )",
    "SXL": "MLT",
    "Latp": "19",
    "Player_1": "S\u00E1nchez 2",
    "Player_11": "Bowen 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Wan-Bissaka 0",
    "Player_14": "Est\u00E8ve 3",
    "Player_7": "Reijnders 2",
    "Player_2": "Van de",
    "Player_5": "Semenyo 6",
    "Player_6": "M.Salah ARS",
    "Player_3": "Konsa 6",
    "Player_4": "Reinildo 0",
    "Player_8": "Mbeumo 0",
    "Player_9": "Wood 0",
    "Player_15": "A.Ramsey 0"
  },
  {
    "manager_Name": "858( 9,578,925 )",
    "Teams": "Zubi dubi doo( Julia Schembri )",
    "SXL": "MLT",
    "Latp": "32",
    "Player_1": "Kelleher 12",
    "Player_11": "Beto 1",
    "Player_10": "Gy\u00F6keres LIV",
    "Player_12": "Verbruggen 3",
    "Player_13": "Wan-Bissaka 0",
    "Player_14": "Dewsbury-Hall 0",
    "Player_7": "Semenyo 6",
    "Player_2": "Konsa 6",
    "Player_5": "Eze LIV",
    "Player_6": "M.Salah ARS",
    "Player_3": "Saliba LIV",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Elanga 0",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Van de"
  }
];