var s = [
  {
    "manager_Name": "1,286( 47,623 )",
    "Teams": "YoureAToneyNoMore( Brendan Kehoe )",
    "SXL": "ENG",
    "Latp": "58",
    "Player_1": "Petrovi\u0107 1",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "A.Becker 10",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Virgil 6",
    "Player_7": "Foden 2",
    "Player_2": "O\u0027Brien 2",
    "Player_5": "J.Timber 6",
    "Player_6": "Garner 6",
    "Player_3": "Thiaw -1",
    "Player_4": "Dorgu 5",
    "Player_8": "Bruno G.",
    "Player_9": "Cunha 2",
    "Player_15": "Mount 1"
  },
  {
    "manager_Name": "1,279( 66,299 )",
    "Teams": "Wirtz Nightmare( Adam Owens )",
    "SXL": "WAL",
    "Latp": "53",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Andersen 2",
    "Player_7": "Grealish -1",
    "Player_2": "Keane 5",
    "Player_5": "Saka 3",
    "Player_6": "Foden 2",
    "Player_3": "Mukiele 3",
    "Player_4": "Dalot 1",
    "Player_8": "Gordon 1",
    "Player_9": "Wilson 9",
    "Player_15": "Konat\u00E9 7"
  },
  {
    "manager_Name": "1,262( 135,920 )",
    "Teams": "Kings of Leon Osman( Declan Reilly )",
    "SXL": "ENG",
    "Latp": "57",
    "Player_1": "Pickford 3",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Van de",
    "Player_14": "Alderete 1",
    "Player_7": "Saka 3",
    "Player_2": "Gabriel 6",
    "Player_5": "Wilson 9",
    "Player_6": "Rice 3",
    "Player_3": "Tarkowski 4",
    "Player_4": "O\u0027Reilly 1",
    "Player_8": "Foden 2",
    "Player_9": "Cunha 2",
    "Player_15": "Kroupi.Jr 7"
  },
  {
    "manager_Name": "1,261( 143,974 )",
    "Teams": "What The Nelli( Ben Cordingley )",
    "SXL": "ENG",
    "Latp": "55",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Calvert-Lewin 8",
    "Player_14": "Andersen 2",
    "Player_7": "Foden 2",
    "Player_2": "O\u0027Reilly 1",
    "Player_5": "Thiaw -1",
    "Player_6": "Saka 3",
    "Player_3": "Tarkowski 4",
    "Player_4": "J.Timber 6",
    "Player_8": "Anderson 7",
    "Player_9": "Szoboszlai 3",
    "Player_15": "Kudus 0"
  },
  {
    "manager_Name": "1,247( 238,567 )",
    "Teams": "Los Blancos( Eamonn Mifsud )",
    "SXL": "MLT",
    "Latp": "57",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 12",
    "Player_10": "Foden 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Rodon 1",
    "Player_7": "Bruno G.",
    "Player_2": "Virgil 6",
    "Player_5": "Andersen 2",
    "Player_6": "Cunha 2",
    "Player_3": "Gabriel 6",
    "Player_4": "O\u0027Reilly 1",
    "Player_8": "Rice 3",
    "Player_9": "Semenyo 6",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,242( 287,361 )",
    "Teams": "Glazebrook FC( Sam Frankland )",
    "SXL": "ENG",
    "Latp": "69",
    "Player_1": "Sels 3",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Richarlison 1",
    "Player_14": "Konat\u00E9 7",
    "Player_7": "Rogers 3",
    "Player_2": "Cash 6",
    "Player_5": "Saka 3",
    "Player_6": "Wilson 9",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Matheus N.",
    "Player_8": "Foden 2",
    "Player_9": "Bruno G.",
    "Player_15": "Van Hecke"
  },
  {
    "manager_Name": "1,241( 291,187 )",
    "Teams": "Haribo Scharmix( Conor Maguire )",
    "SXL": "ENG",
    "Latp": "78",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "Kelleher 13",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Keane 5",
    "Player_7": "Barnes 15",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Senesi 6",
    "Player_6": "Rogers 3",
    "Player_3": "Gabriel 6",
    "Player_4": "Chalobah 3",
    "Player_8": "Wilson 9",
    "Player_9": "Saka 3",
    "Player_15": "Anderson 7"
  },
  {
    "manager_Name": "1,241( 293,928 )",
    "Teams": "Hltex Lykoi( Ioannis Poulios )",
    "SXL": "GRC",
    "Latp": "44",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Woltemade 5",
    "Player_10": "Haaland 12",
    "Player_12": "Verbruggen 3",
    "Player_13": "Virgil 6",
    "Player_14": "Alderete 1",
    "Player_7": "Szoboszlai 3",
    "Player_2": "Hall 4",
    "Player_5": "Cherki 1",
    "Player_6": "Cunha 2",
    "Player_3": "Dorgu 5",
    "Player_4": "Gabriel 6",
    "Player_8": "Palmer 1",
    "Player_9": "Watkins 2",
    "Player_15": "Dewsbury-Hall 0"
  },
  {
    "manager_Name": "1,240( 308,003 )",
    "Teams": "For Better or Wirtz( Theo Dixon )",
    "SXL": "ENG",
    "Latp": "54",
    "Player_1": "Kelleher 13",
    "Player_11": "Haaland 12",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Mukiele 3",
    "Player_7": "Gordon 1",
    "Player_2": "Gabriel 6",
    "Player_5": "Cunha 2",
    "Player_6": "Rogers 3",
    "Player_3": "Dorgu 5",
    "Player_4": "O\u0027Reilly 1",
    "Player_8": "Foden 2",
    "Player_9": "Anderson 7",
    "Player_15": "Andersen 2"
  },
  {
    "manager_Name": "1,237( 334,923 )",
    "Teams": "Maggnificent15( Derren Maggs )",
    "SXL": "ENG",
    "Latp": "69",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Livramento 1",
    "Player_7": "Anderson 7",
    "Player_2": "Collins 13",
    "Player_5": "Gudmundsson 0",
    "Player_6": "Foden 2",
    "Player_3": "O\u0027Reilly 1",
    "Player_4": "Hall 4",
    "Player_8": "Saka 3",
    "Player_9": "Wilson 9",
    "Player_15": "Minteh 0"
  },
  {
    "manager_Name": "1,236( 344,305 )",
    "Teams": "IK S\u00E4tra( Filip Larsson )",
    "SXL": "MLT",
    "Latp": "65",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 5",
    "Player_10": "Thiago 12",
    "Player_12": "Verbruggen 3",
    "Player_13": "Neto 5",
    "Player_14": "Chalobah 3",
    "Player_7": "Cunha 2",
    "Player_2": "Collins 13",
    "Player_5": "Tarkowski 4",
    "Player_6": "Wilson 9",
    "Player_3": "Thiaw -1",
    "Player_4": "O\u0027Reilly 1",
    "Player_8": "Foden 2",
    "Player_9": "Haaland 12",
    "Player_15": "Minteh 0"
  },
  {
    "manager_Name": "1,230( 414,555 )",
    "Teams": "XG Stats XI( Will Gunn )",
    "SXL": "ENG",
    "Latp": "51",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Haaland 12",
    "Player_10": "Cunha 2",
    "Player_12": "Verbruggen 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Richards 0",
    "Player_7": "Garner 6",
    "Player_2": "Gabriel 6",
    "Player_5": "Virgil 6",
    "Player_6": "Semenyo 6",
    "Player_3": "Tarkowski 4",
    "Player_4": "Alderete 1",
    "Player_8": "Saka 3",
    "Player_9": "Foden 2",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,228( 443,987 )",
    "Teams": "NoRelegationPls( Haykel Mansour )",
    "SXL": "MLT",
    "Latp": "59",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 5",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Minteh 0",
    "Player_7": "Reijnders 2",
    "Player_2": "Collins 13",
    "Player_5": "Senesi 6",
    "Player_6": "Wilson 9",
    "Player_3": "Thiaw -1",
    "Player_4": "Gusto 2",
    "Player_8": "Cunha 2",
    "Player_9": "Saka 3",
    "Player_15": "Virgil 6"
  },
  {
    "manager_Name": "1,221( 545,541 )",
    "Teams": "Alpha Academy( Jamie Davies )",
    "SXL": "ENG",
    "Latp": "56",
    "Player_1": "Verbruggen 3",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Gomez 2",
    "Player_14": "Gu\u00E9hi 6",
    "Player_7": "Semenyo 6",
    "Player_2": "Dorgu 5",
    "Player_5": "Cunha 2",
    "Player_6": "Schade 6",
    "Player_3": "Matheus N.",
    "Player_4": "Truffert 1",
    "Player_8": "Foden 2",
    "Player_9": "Woltemade 5",
    "Player_15": "De Cuyper"
  },
  {
    "manager_Name": "1,219( 569,098 )",
    "Teams": "Mo With The Flo( Tom Atkinson )",
    "SXL": "MLT",
    "Latp": "56",
    "Player_1": "Donnarumma 1",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Virgil 6",
    "Player_14": "Andersen 2",
    "Player_7": "Rogers 3",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Anderson 7",
    "Player_6": "Reijnders 2",
    "Player_3": "Keane 5",
    "Player_4": "Chalobah 3",
    "Player_8": "Saka 3",
    "Player_9": "Cunha 2",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,218( 589,283 )",
    "Teams": "kinder mbeumo( Gianluca Tanti )",
    "SXL": "MLT",
    "Latp": "66",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 5",
    "Player_10": "Thiago 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Tete 0",
    "Player_14": "Wirtz 3",
    "Player_7": "Saka 3",
    "Player_2": "Dalot 1",
    "Player_5": "Wilson 9",
    "Player_6": "Rogers 3",
    "Player_3": "J.Timber 6",
    "Player_4": "Lacroix 8",
    "Player_8": "Cherki 1",
    "Player_9": "Haaland 12",
    "Player_15": "Konsa 7"
  },
  {
    "manager_Name": "1,211( 695,997 )",
    "Teams": "DBA Utd( Jim Lennox )",
    "SXL": "ENG",
    "Latp": "53",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Richards 0",
    "Player_14": "Van den",
    "Player_7": "Cherki 1",
    "Player_2": "Van de",
    "Player_5": "Semenyo 6",
    "Player_6": "Saka 3",
    "Player_3": "J.Timber 6",
    "Player_4": "Andersen 2",
    "Player_8": "Cunha 2",
    "Player_9": "Yeremy 3",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,208( 753,113 )",
    "Teams": "Joga Bonito FC( Christophe Peixoto )",
    "SXL": "HUN",
    "Latp": "34",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 12",
    "Player_10": "Enzo 1",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Gudmundsson 0",
    "Player_7": "Foden 2",
    "Player_2": "Thiaw -1",
    "Player_5": "Andersen 2",
    "Player_6": "Szoboszlai 3",
    "Player_3": "Keane 5",
    "Player_4": "Van de",
    "Player_8": "Gordon 1",
    "Player_9": "Saka 3",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,205( 810,295 )",
    "Teams": "Lallish United( Melwin Holst )",
    "SXL": "SWE",
    "Latp": "48",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 6",
    "Player_10": "Calvert-Lewin 8",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Stach 2",
    "Player_14": "Gu\u00E9hi 6",
    "Player_7": "Saka 3",
    "Player_2": "J.Timber 6",
    "Player_5": "Keane 5",
    "Player_6": "Semenyo 6",
    "Player_3": "Thiaw -1",
    "Player_4": "Matheus N.",
    "Player_8": "Rogers 3",
    "Player_9": "Cunha 4",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,203( 845,894 )",
    "Teams": "House TarGoalyen( Matteo Farrugia )",
    "SXL": "MLT",
    "Latp": "59",
    "Player_1": "Raya 6",
    "Player_11": "Watkins 2",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Mbeumo 0",
    "Player_14": "Konsa 7",
    "Player_7": "Anderson 7",
    "Player_2": "Saliba 7",
    "Player_5": "Est\u00E8ve 3",
    "Player_6": "B.Fernandes 7",
    "Player_3": "Virgil 6",
    "Player_4": "Van de",
    "Player_8": "Semenyo 6",
    "Player_9": "Rogers 3",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,203( 851,392 )",
    "Teams": "The Bees( Tove Ronneb\u00E4ck )",
    "SXL": "MLT",
    "Latp": "62",
    "Player_1": "S\u00E1nchez 2",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Virgil 6",
    "Player_14": "Marc Guiu",
    "Player_7": "Bruno G.",
    "Player_2": "Gabriel 6",
    "Player_5": "Tavernier 5",
    "Player_6": "Cunha 2",
    "Player_3": "O\u0027Reilly 1",
    "Player_4": "Lewis-Potter 6",
    "Player_8": "Saka 3",
    "Player_9": "Foden 2",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "1,197( 977,593 )",
    "Teams": "Bebenciukai( Marius z )",
    "SXL": "LTU",
    "Latp": "62",
    "Player_1": "Pope 2",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Reijnders 2",
    "Player_14": "Gudmundsson 0",
    "Player_7": "Cunha 2",
    "Player_2": "Dorgu 5",
    "Player_5": "Keane 5",
    "Player_6": "Saka 3",
    "Player_3": "J.Timber 6",
    "Player_4": "Van de",
    "Player_8": "Foden 2",
    "Player_9": "\u0160e\u0161ko 13",
    "Player_15": "Wilson 9"
  },
  {
    "manager_Name": "1,196( 1,002,279 )",
    "Teams": "DinamoB( Pietro Menna )",
    "SXL": "MLT",
    "Latp": "70",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "Vicario 1",
    "Player_13": "Anthony 6",
    "Player_14": "O\u0027Reilly 1",
    "Player_7": "Bruno G.",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Rice 3",
    "Player_6": "Foden 2",
    "Player_3": "Keane 5",
    "Player_4": "Gabriel 6",
    "Player_8": "Semenyo 6",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Chalobah 3"
  },
  {
    "manager_Name": "1,194( 1,041,438 )",
    "Teams": "Rekegutt United( Eirik Presttun )",
    "SXL": "MLT",
    "Latp": "55",
    "Player_1": "S\u00E1nchez 2",
    "Player_11": "Haaland 12",
    "Player_10": "Bowen 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Cash 6",
    "Player_14": "Hincapie 1",
    "Player_7": "Gakpo 3",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Bruno G.",
    "Player_6": "Foden 2",
    "Player_3": "Matheus N.",
    "Player_4": "James 1",
    "Player_8": "Semenyo 6",
    "Player_9": "Calvert-Lewin 8",
    "Player_15": "Cullen 0"
  },
  {
    "manager_Name": "1,192( 1,093,227 )",
    "Teams": "Gedward City FC( Graham Edwards )",
    "SXL": "ENG",
    "Latp": "61",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "S\u00E1nchez 2",
    "Player_13": "Virgil 6",
    "Player_14": "Devenny 3",
    "Player_7": "Semenyo 6",
    "Player_2": "Gabriel 6",
    "Player_5": "Foden 2",
    "Player_6": "Cunha 2",
    "Player_3": "O\u0027Reilly 1",
    "Player_4": "Van de",
    "Player_8": "Wilson 9",
    "Player_9": "Woltemade 5",
    "Player_15": "Justin 0"
  },
  {
    "manager_Name": "1,192( 1,098,972 )",
    "Teams": "KERAMACTICOS \u26A1( Michael Keramas )",
    "SXL": "GRC",
    "Latp": "45",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 12",
    "Player_10": "Ra\u00FAl 5",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Van den",
    "Player_7": "Rice 3",
    "Player_2": "O\u0027Reilly 1",
    "Player_5": "Dalot 1",
    "Player_6": "Foden 2",
    "Player_3": "Thiaw -1",
    "Player_4": "Gabriel 6",
    "Player_8": "Wilson 9",
    "Player_9": "Gordon 1",
    "Player_15": "Kudus 0"
  },
  {
    "manager_Name": "1,189( 1,161,386 )",
    "Teams": "Ronalbinho( Albin Jonsson )",
    "SXL": "MLT",
    "Latp": "52",
    "Player_1": "Donnarumma 1",
    "Player_11": "Haaland 12",
    "Player_10": "Woltemade 5",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Wirtz 3",
    "Player_14": "Virgil 6",
    "Player_7": "L.Miley 4",
    "Player_2": "Dalot 1",
    "Player_5": "Rogers 3",
    "Player_6": "Palmer 1",
    "Player_3": "Lacroix 8",
    "Player_4": "Thiaw -1",
    "Player_8": "Schade 6",
    "Player_9": "Thiago 12",
    "Player_15": "Gudmundsson 0"
  },
  {
    "manager_Name": "1,189( 1,167,476 )",
    "Teams": "Starship( Olumide Okedusi )",
    "SXL": "EST",
    "Latp": "63",
    "Player_1": "Donnarumma 1",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "L.Miley 4",
    "Player_14": "Mukiele 3",
    "Player_7": "Foden 2",
    "Player_2": "J.Timber 6",
    "Player_5": "Rogers 3",
    "Player_6": "Saka 3",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Tarkowski 4",
    "Player_8": "Wilson 9",
    "Player_9": "Woltemade 5",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "1,188( 1,197,787 )",
    "Teams": "Goalless( Panagiotis Sfikas )",
    "SXL": "GRC",
    "Latp": "42",
    "Player_1": "Petrovi\u0107 1",
    "Player_11": "Haaland 12",
    "Player_10": "Cunha 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Virgil 6",
    "Player_7": "Foden 2",
    "Player_2": "Tarkowski 4",
    "Player_5": "Van Hecke",
    "Player_6": "Rice 3",
    "Player_3": "Dorgu 5",
    "Player_4": "J.Timber 6",
    "Player_8": "Gordon 1",
    "Player_9": "Szoboszlai 3",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,186( 1,245,894 )",
    "Teams": "Ctrl Alt Attack( Laimonas Zukas )",
    "SXL": "LTU",
    "Latp": "53",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "Verbruggen 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Est\u00E8ve 3",
    "Player_7": "Anderson 7",
    "Player_2": "O\u0027Reilly 1",
    "Player_5": "Cunha 2",
    "Player_6": "Foden 2",
    "Player_3": "Senesi 6",
    "Player_4": "Thiaw -1",
    "Player_8": "Semenyo 6",
    "Player_9": "Rice 3",
    "Player_15": "Van Hecke"
  },
  {
    "manager_Name": "1,183( 1,307,329 )",
    "Teams": "COYS( Zachary Black )",
    "SXL": "CAN",
    "Latp": "59",
    "Player_1": "A.Becker 10",
    "Player_11": "Haaland 12",
    "Player_10": "Wilson 9",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Est\u00E8ve 3",
    "Player_14": "Obi 0",
    "Player_7": "Saka 3",
    "Player_2": "Gabriel 6",
    "Player_5": "Konsa 7",
    "Player_6": "Palmer 1",
    "Player_3": "Van de",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "\u00D8degaard 3",
    "Player_9": "Foden 2",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,183( 1,323,083 )",
    "Teams": "Saksa FC( Neil Mifsud )",
    "SXL": "MLT",
    "Latp": "42",
    "Player_1": "Pickford 3",
    "Player_11": "Haaland 12",
    "Player_10": "Woltemade 5",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Dewsbury-Hall 0",
    "Player_7": "Wirtz 3",
    "Player_2": "Thiaw -1",
    "Player_5": "Virgil 6",
    "Player_6": "Wilson 9",
    "Player_3": "Heaven 0",
    "Player_4": "Dalot 1",
    "Player_8": "Cunha 2",
    "Player_9": "Foden 2",
    "Player_15": "Richards 0"
  },
  {
    "manager_Name": "1,179( 1,415,317 )",
    "Teams": "Southmalm Strikers( Johan Hammarstrom )",
    "SXL": "SWE",
    "Latp": "60",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 12",
    "Player_10": "Watkins 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Wilson 9",
    "Player_14": "Andersen 2",
    "Player_7": "Rogers 3",
    "Player_2": "Dorgu 5",
    "Player_5": "Cunha 2",
    "Player_6": "Bruno G.",
    "Player_3": "Gabriel 6",
    "Player_4": "Van de",
    "Player_8": "Cherki 1",
    "Player_9": "Thiago 12",
    "Player_15": "Dalot 1"
  },
  {
    "manager_Name": "1,178( 1,444,872 )",
    "Teams": "FC Cantona( Nelson Schutt )",
    "SXL": "SWE",
    "Latp": "40",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Haaland 12",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "S\u00E1nchez 2",
    "Player_13": "Patterson 0",
    "Player_14": "King 0",
    "Player_7": "Saka 3",
    "Player_2": "Dorgu 5",
    "Player_5": "Cunha 2",
    "Player_6": "Wilson 9",
    "Player_3": "O\u0027Reilly 1",
    "Player_4": "James 1",
    "Player_8": "Foden 2",
    "Player_9": "Welbeck 1",
    "Player_15": "Andersen 2"
  },
  {
    "manager_Name": "1,177( 1,471,925 )",
    "Teams": "Toasted Ekitike( Ollie Hatfield )",
    "SXL": "WAL",
    "Latp": "58",
    "Player_1": "Roefs 2",
    "Player_11": "Haaland 6",
    "Player_10": "Thiago 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Gravenberch 3",
    "Player_14": "Van de",
    "Player_7": "Semenyo 6",
    "Player_2": "James 1",
    "Player_5": "Saka 3",
    "Player_6": "Rice 3",
    "Player_3": "Gabriel 6",
    "Player_4": "Keane 5",
    "Player_8": "Rogers 6",
    "Player_9": "Calvert-Lewin 8",
    "Player_15": "Alderete 1"
  },
  {
    "manager_Name": "1,175( 1,519,624 )",
    "Teams": "Ctrl Alt De Ligt( Marlon Vella )",
    "SXL": "MLT",
    "Latp": "70",
    "Player_1": "Petrovi\u0107 1",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Marc Guiu",
    "Player_14": "Alderete 1",
    "Player_7": "Bruno G.",
    "Player_2": "Hincapie 1",
    "Player_5": "Rice 3",
    "Player_6": "Foden 2",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "J.Timber 6",
    "Player_8": "Wilson 9",
    "Player_9": "B.Fernandes 7",
    "Player_15": "Andersen 2"
  },
  {
    "manager_Name": "1,169( 1,695,270 )",
    "Teams": "Change Name( Alexander Oyangen Johansen )",
    "SXL": "MLT",
    "Latp": "45",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 5",
    "Player_10": "Haaland 6",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Van de",
    "Player_14": "J.Timber 6",
    "Player_7": "Bruno G.",
    "Player_2": "Tarkowski 4",
    "Player_5": "Cunha 4",
    "Player_6": "Rogers 3",
    "Player_3": "Pedro Porro",
    "Player_4": "Chalobah 3",
    "Player_8": "Enzo 1",
    "Player_9": "Mateta 2",
    "Player_15": "Dewsbury-Hall 0"
  },
  {
    "manager_Name": "1,164( 1,835,714 )",
    "Teams": "Black \u0026 Blue( Mark Zammit )",
    "SXL": "MLT",
    "Latp": "50",
    "Player_1": "Roefs 2",
    "Player_11": "Haaland 12",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Raya 6",
    "Player_13": "Woltemade 5",
    "Player_14": "Alderete 1",
    "Player_7": "Bruno G.",
    "Player_2": "Chalobah 3",
    "Player_5": "Semenyo 6",
    "Player_6": "Rice 3",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Van de",
    "Player_8": "Foden 2",
    "Player_9": "Caicedo 4",
    "Player_15": "Lewis-Potter 6"
  },
  {
    "manager_Name": "1,163( 1,884,029 )",
    "Teams": "Cozier Vibes( D-J O\u0027Loughlin )",
    "SXL": "ENG",
    "Latp": "54",
    "Player_1": "Donnarumma 1",
    "Player_11": "Bowen 2",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Minteh 0",
    "Player_14": "Richards 0",
    "Player_7": "Stach 2",
    "Player_2": "Gabriel 6",
    "Player_5": "Foden 2",
    "Player_6": "Semenyo 6",
    "Player_3": "Andersen 2",
    "Player_4": "Senesi 6",
    "Player_8": "Saka 3",
    "Player_9": "Thiago 12",
    "Player_15": "Gudmundsson 0"
  },
  {
    "manager_Name": "1,162( 1,911,518 )",
    "Teams": "21X.....( John Tiltmann )",
    "SXL": "MLT",
    "Latp": "63",
    "Player_1": "Pickford 3",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "Petrovi\u0107 1",
    "Player_13": "Gu\u00E9hi 6",
    "Player_14": "Foden 2",
    "Player_7": "Bruno G.",
    "Player_2": "Alderete 1",
    "Player_5": "Semenyo 6",
    "Player_6": "Rogers 3",
    "Player_3": "Tarkowski 4",
    "Player_4": "Chalobah 3",
    "Player_8": "Rice 3",
    "Player_9": "Woltemade 5",
    "Player_15": "Hartman 0"
  },
  {
    "manager_Name": "1,161( 1,930,049 )",
    "Teams": "Gambit( Nicola Frasca )",
    "SXL": "MLT",
    "Latp": "43",
    "Player_1": "S\u00E1nchez 2",
    "Player_11": "Mateta 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Verbruggen 3",
    "Player_13": "Gu\u00E9hi 6",
    "Player_14": "Gudmundsson 0",
    "Player_7": "Rogers 3",
    "Player_2": "Virgil 6",
    "Player_5": "Reijnders 2",
    "Player_6": "Semenyo 6",
    "Player_3": "J.Timber 6",
    "Player_4": "Van de",
    "Player_8": "Rice 3",
    "Player_9": "Haaland 12",
    "Player_15": "Wilson 9"
  },
  {
    "manager_Name": "1,152( 2,221,212 )",
    "Teams": "Massilia( Daniel Borg )",
    "SXL": "MLT",
    "Latp": "77",
    "Player_1": "Petrovi\u0107 1",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "Sels 3",
    "Player_13": "Chalobah 3",
    "Player_14": "Van de",
    "Player_7": "Foden 2",
    "Player_2": "Lewis-Potter 6",
    "Player_5": "Semenyo 6",
    "Player_6": "Bruno G.",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Senesi 6",
    "Player_8": "Anderson 7",
    "Player_9": "Calvert-Lewin 8",
    "Player_15": "Stach 2"
  },
  {
    "manager_Name": "1,152( 2,237,266 )",
    "Teams": "A Cunha Mateta( Jon Briscoe White )",
    "SXL": "MLT",
    "Latp": "57",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "Roefs 2",
    "Player_13": "O\u0027Reilly 1",
    "Player_14": "Mukiele 3",
    "Player_7": "Rogers 3",
    "Player_2": "Gabriel 6",
    "Player_5": "Rice 3",
    "Player_6": "Foden 2",
    "Player_3": "Keane 5",
    "Player_4": "Chalobah 3",
    "Player_8": "Semenyo 6",
    "Player_9": "Georginio 2",
    "Player_15": "Kroupi.Jr 7"
  },
  {
    "manager_Name": "1,150( 2,284,472 )",
    "Teams": "Charli xGx( Charlie Rogers )",
    "SXL": "ENG",
    "Latp": "61",
    "Player_1": "Henderson 7",
    "Player_11": "Bowen 2",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Wilson 9",
    "Player_14": "Virgil 6",
    "Player_7": "Rogers 3",
    "Player_2": "Cash 6",
    "Player_5": "Saka 3",
    "Player_6": "Foden 2",
    "Player_3": "J.Timber 6",
    "Player_4": "Kayode 6",
    "Player_8": "Reijnders 2",
    "Player_9": "Thiago 12",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "1,149( 2,317,709 )",
    "Teams": "Mc Bryde FC( Mark Mc Bryde )",
    "SXL": "MLT",
    "Latp": "52",
    "Player_1": "Sels 3",
    "Player_11": "Haaland 12",
    "Player_10": "Woltemade 5",
    "Player_12": "S\u00E1nchez 2",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Gu\u00E9hi 6",
    "Player_7": "Rogers 3",
    "Player_2": "Senesi 6",
    "Player_5": "O\u0027Reilly 1",
    "Player_6": "Cunha 2",
    "Player_3": "Tarkowski 4",
    "Player_4": "James 1",
    "Player_8": "Wilson 9",
    "Player_9": "Semenyo 6",
    "Player_15": "Stach 2"
  },
  {
    "manager_Name": "1,148( 2,341,495 )",
    "Teams": "Malta Knights( Martin Knight )",
    "SXL": "MLT",
    "Latp": "58",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 6",
    "Player_10": "Bowen 4",
    "Player_12": "Pope 2",
    "Player_13": "Diouf 0",
    "Player_14": "Sarr 0",
    "Player_7": "Rice 3",
    "Player_2": "Konsa 7",
    "Player_5": "Lacroix 8",
    "Player_6": "Semenyo 6",
    "Player_3": "Gabriel 6",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Caicedo 4",
    "Player_9": "Mac Allister",
    "Player_15": "Ekitik\u00E9 0"
  },
  {
    "manager_Name": "1,143( 2,530,422 )",
    "Teams": "MDJ XI( Matthew James )",
    "SXL": "ENG",
    "Latp": "56",
    "Player_1": "S\u00E1nchez 2",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Wharton 3",
    "Player_14": "Hickey 1",
    "Player_7": "Saka 3",
    "Player_2": "Chalobah 3",
    "Player_5": "Cunha 2",
    "Player_6": "Bruno G.",
    "Player_3": "Thiaw -1",
    "Player_4": "Hincapie 1",
    "Player_8": "Wilson 9",
    "Player_9": "Watkins 2",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "1,140( 2,621,334 )",
    "Teams": "Soccertainment( Adam Lismore )",
    "SXL": "ENG",
    "Latp": "54",
    "Player_1": "Kelleher 13",
    "Player_11": "Haaland 12",
    "Player_10": "Gordon 1",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Kroupi.Jr 7",
    "Player_14": "Gudmundsson 0",
    "Player_7": "Garner 6",
    "Player_2": "Gabriel 6",
    "Player_5": "Dalot 1",
    "Player_6": "Rice 3",
    "Player_3": "Dorgu 5",
    "Player_4": "Hall 4",
    "Player_8": "Cherki 1",
    "Player_9": "Cunha 2",
    "Player_15": "Ekitik\u00E9 0"
  },
  {
    "manager_Name": "1,139( 2,667,453 )",
    "Teams": "Gimby( Piotr Kluczynski )",
    "SXL": "MLT",
    "Latp": "53",
    "Player_1": "Raya 6",
    "Player_11": "Woltemade 5",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Kroupi.Jr 7",
    "Player_14": "Virgil 6",
    "Player_7": "Rogers 3",
    "Player_2": "Cash 6",
    "Player_5": "Cunha 2",
    "Player_6": "Saka 3",
    "Player_3": "Van de",
    "Player_4": "J.Timber 6",
    "Player_8": "Cherki 1",
    "Player_9": "Wilson 9",
    "Player_15": "Van Hecke"
  },
  {
    "manager_Name": "1,130( 2,971,574 )",
    "Teams": "Red Devils( Ryan Schembri )",
    "SXL": "MLT",
    "Latp": "60",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "Kelleher 13",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Wilson 9",
    "Player_7": "Cherki 1",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Van de",
    "Player_6": "Semenyo 6",
    "Player_3": "Gabriel 6",
    "Player_4": "J.Timber 6",
    "Player_8": "Rogers 3",
    "Player_9": "Reijnders 2",
    "Player_15": "Gudmundsson 0"
  }
];