var s = [
  {
    "manager_Name": "1,447( 1 )",
    "Teams": "The A Team( Henry Huynh )",
    "SXL": "ENG",
    "Latp": "63",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 12",
    "Player_10": "Bowen 2",
    "Player_12": "Verbruggen 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Gravenberch 3",
    "Player_7": "Bruno G.",
    "Player_2": "Collins 13",
    "Player_5": "Virgil 6",
    "Player_6": "Foden 2",
    "Player_3": "Keane 5",
    "Player_4": "Thiaw -1",
    "Player_8": "Gordon 1",
    "Player_9": "Schade 6",
    "Player_15": "Van Hecke"
  },
  {
    "manager_Name": "1,436( 2 )",
    "Teams": "Matty C\u0027s 5ft 3\u0027s( Matt Chamberlain )",
    "SXL": "ENG",
    "Latp": "61",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 12",
    "Player_10": "Calvert-Lewin 8",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Szoboszlai 3",
    "Player_14": "Mukiele 3",
    "Player_7": "Rogers 3",
    "Player_2": "Gabriel 6",
    "Player_5": "Saka 3",
    "Player_6": "Foden 2",
    "Player_3": "Tarkowski 4",
    "Player_4": "Thiaw -1",
    "Player_8": "Garner 6",
    "Player_9": "Haaland 12",
    "Player_15": "Bijol 3"
  },
  {
    "manager_Name": "1,434( 3 )",
    "Teams": "Aboudz( Abdalrahman Allam )",
    "SXL": "LBN",
    "Latp": "68",
    "Player_1": "Kelleher 13",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Andersen 2",
    "Player_14": "Virgil 6",
    "Player_7": "Cunha 2",
    "Player_2": "Truffert 1",
    "Player_5": "Saka 3",
    "Player_6": "Cherki 1",
    "Player_3": "J.Timber 6",
    "Player_4": "Gabriel 6",
    "Player_8": "Rogers 3",
    "Player_9": "Wilson 9",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,433( 4 )",
    "Teams": "11 Paths Sage( Preye Princewill )",
    "SXL": "NGA",
    "Latp": "70",
    "Player_1": "Kelleher 13",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "Henderson 7",
    "Player_13": "Van de",
    "Player_14": "Semenyo 6",
    "Player_7": "Bruno G.",
    "Player_2": "Gabriel 6",
    "Player_5": "Rogers 3",
    "Player_6": "Cherki 1",
    "Player_3": "J.Timber 6",
    "Player_4": "James 1",
    "Player_8": "Rice 3",
    "Player_9": "Watkins 2",
    "Player_15": "Gu\u00E9hi 6"
  },
  {
    "manager_Name": "1,431( 5 )",
    "Teams": "Haaland tiembla( Charlie Shanahan )",
    "SXL": "ENG",
    "Latp": "52",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "A.Becker 10",
    "Player_13": "Alderete 1",
    "Player_14": "Ekitik\u00E9 0",
    "Player_7": "Foden 2",
    "Player_2": "Gabriel 6",
    "Player_5": "Saka 3",
    "Player_6": "Rice 3",
    "Player_3": "O\u0027Reilly 1",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Enzo 1",
    "Player_9": "Wharton 3",
    "Player_15": "Andersen 2"
  },
  {
    "manager_Name": "1,430( 6 )",
    "Teams": "The Honest Trundlers( Ian Foster )",
    "SXL": "GBR",
    "Latp": "57",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 12",
    "Player_10": "Wissa 1",
    "Player_12": "Darlow 0",
    "Player_13": "Gravenberch 3",
    "Player_14": "Virgil 6",
    "Player_7": "Rogers 3",
    "Player_2": "Thiaw -1",
    "Player_5": "Foden 2",
    "Player_6": "Gordon 1",
    "Player_3": "Gabriel 6",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Wilson 9",
    "Player_9": "Haaland 12",
    "Player_15": "Van Hecke"
  },
  {
    "manager_Name": "1,428( 7 )",
    "Teams": "Heroes!( Abraham Assim Ita )",
    "SXL": "NGA",
    "Latp": "69",
    "Player_1": "Pickford 3",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "Petrovi\u0107 1",
    "Player_13": "Calvert-Lewin 8",
    "Player_14": "Van Hecke",
    "Player_7": "Rice 3",
    "Player_2": "Tarkowski 4",
    "Player_5": "Wilson 9",
    "Player_6": "Saka 3",
    "Player_3": "Mukiele 3",
    "Player_4": "Gabriel 6",
    "Player_8": "Rogers 3",
    "Player_9": "Bruno G.",
    "Player_15": "Senesi 6"
  },
  {
    "manager_Name": "1,424( 8 )",
    "Teams": "Le Puissant FC( Oluwatobi Ajayi )",
    "SXL": "USA",
    "Latp": "54",
    "Player_1": "Pickford 3",
    "Player_11": "Thiago 12",
    "Player_10": "Bowen 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Szoboszlai 3",
    "Player_14": "Mukiele 3",
    "Player_7": "Foden 2",
    "Player_2": "Gabriel 6",
    "Player_5": "Saka 3",
    "Player_6": "Rogers 3",
    "Player_3": "Lewis-Potter 6",
    "Player_4": "Dorgu 5",
    "Player_8": "E.Le F\u00E9e",
    "Player_9": "Haaland 12",
    "Player_15": "Virgil 6"
  },
  {
    "manager_Name": "1,419( 9 )",
    "Teams": "Top Scorers( Momodou Jallow )",
    "SXL": "USA",
    "Latp": "63",
    "Player_1": "A.Becker 10",
    "Player_11": "Watkins 2",
    "Player_10": "Thiago 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Gu\u00E9hi 6",
    "Player_14": "Virgil 6",
    "Player_7": "Rogers 3",
    "Player_2": "J.Timber 6",
    "Player_5": "Foden 2",
    "Player_6": "Cunha 2",
    "Player_3": "Chalobah 3",
    "Player_4": "Heaven 0",
    "Player_8": "Bruno G.",
    "Player_9": "Haaland 12",
    "Player_15": "Tr\u00E9sor 0"
  },
  {
    "manager_Name": "1,419( 10 )",
    "Teams": "hakim dahem( TOP KADER )",
    "SXL": "DZA",
    "Latp": "80",
    "Player_1": "Kelleher 13",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Reinildo 0",
    "Player_7": "Semenyo 6",
    "Player_2": "Matheus N.",
    "Player_5": "Wilson 9",
    "Player_6": "Foden 2",
    "Player_3": "Gabriel 6",
    "Player_4": "Hincapie 1",
    "Player_8": "Cunha 2",
    "Player_9": "Barnes 15",
    "Player_15": "Andersen 2"
  },
  {
    "manager_Name": "1,419( 10 )",
    "Teams": "Wizards( Captain Ahmed )",
    "SXL": "EGY",
    "Latp": "52",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "Verbruggen 3",
    "Player_13": "Anderson 7",
    "Player_14": "Gu\u00E9hi 6",
    "Player_7": "Cunha 2",
    "Player_2": "Gabriel 6",
    "Player_5": "Cherki 1",
    "Player_6": "Foden 2",
    "Player_3": "Hincapie 1",
    "Player_4": "Dorgu 5",
    "Player_8": "Saka 3",
    "Player_9": "Ra\u00FAl 5",
    "Player_15": "Andersen 2"
  },
  {
    "manager_Name": "1,419( 12 )",
    "Teams": "g7412877( George McNicholas )",
    "SXL": "ENG",
    "Latp": "61",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Gu\u00E9hi 6",
    "Player_7": "Bruno G.",
    "Player_2": "Gabriel 6",
    "Player_5": "Foden 2",
    "Player_6": "Rice 3",
    "Player_3": "Thiaw -1",
    "Player_4": "Tarkowski 4",
    "Player_8": "Rogers 3",
    "Player_9": "Gravenberch 3",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "1,418( 13 )",
    "Teams": "Utter Woke Nonsense( Zac Brown )",
    "SXL": "ENG",
    "Latp": "59",
    "Player_1": "S\u00E1nchez 2",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "Verbruggen 3",
    "Player_13": "Alderete 1",
    "Player_14": "Ekitik\u00E9 0",
    "Player_7": "Rice 3",
    "Player_2": "Keane 5",
    "Player_5": "Saka 3",
    "Player_6": "Foden 2",
    "Player_3": "Gabriel 6",
    "Player_4": "Thiaw -1",
    "Player_8": "Bruno G.",
    "Player_9": "L.Miley 4",
    "Player_15": "Andersen 2"
  },
  {
    "manager_Name": "1,417( 14 )",
    "Teams": "Diamondos( michael jewell )",
    "SXL": "ENG",
    "Latp": "60",
    "Player_1": "Pickford 3",
    "Player_11": "Wissa 1",
    "Player_10": "Thiago 12",
    "Player_12": "Petrovi\u0107 1",
    "Player_13": "Szoboszlai 3",
    "Player_14": "Alderete 1",
    "Player_7": "Garner 6",
    "Player_2": "Gabriel 6",
    "Player_5": "Saka 3",
    "Player_6": "Foden 2",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Cash 6",
    "Player_8": "Rice 3",
    "Player_9": "Haaland 12",
    "Player_15": "Gvardiol 0"
  },
  {
    "manager_Name": "1,417( 15 )",
    "Teams": "marmooooush( Oliver Norvold )",
    "SXL": "DNK",
    "Latp": "73",
    "Player_1": "Raya 6",
    "Player_11": "Watkins 2",
    "Player_10": "Bowen 2",
    "Player_12": "Kelleher 13",
    "Player_13": "Garner 6",
    "Player_14": "Cash 6",
    "Player_7": "Rogers 3",
    "Player_2": "Thiaw -1",
    "Player_5": "Cunha 2",
    "Player_6": "Bruno G.",
    "Player_3": "Mukiele 3",
    "Player_4": "Gabriel 6",
    "Player_8": "L.Paquet\u00E1 2",
    "Player_9": "Haaland 12",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "1,416( 16 )",
    "Teams": "the crystals( Luke Hosking )",
    "SXL": "AUS",
    "Latp": "53",
    "Player_1": "Pickford 3",
    "Player_11": "Haaland 12",
    "Player_10": "Caicedo 4",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Mukiele 3",
    "Player_7": "Foden 2",
    "Player_2": "Chalobah 3",
    "Player_5": "Thiaw -1",
    "Player_6": "Bruno G.",
    "Player_3": "Tarkowski 4",
    "Player_4": "Gabriel 6",
    "Player_8": "Rice 3",
    "Player_9": "Semenyo 6",
    "Player_15": "Obi 0"
  },
  {
    "manager_Name": "1,415( 17 )",
    "Teams": "Frank Burrows Army( Christopher Harris )",
    "SXL": "ENG",
    "Latp": "68",
    "Player_1": "Donnarumma 1",
    "Player_11": "Haaland 6",
    "Player_10": "Thiago 12",
    "Player_12": "King 0",
    "Player_13": "Wilson 9",
    "Player_14": "Ekitik\u00E9 0",
    "Player_7": "Saka 3",
    "Player_2": "J.Timber 6",
    "Player_5": "Collins 13",
    "Player_6": "Rogers 3",
    "Player_3": "Tarkowski 4",
    "Player_4": "Gabriel 12",
    "Player_8": "Foden 2",
    "Player_9": "Garner 6",
    "Player_15": "Rodon 1"
  },
  {
    "manager_Name": "1,413( 18 )",
    "Teams": "Trust The Process FC( Piotr Zima )",
    "SXL": "POL",
    "Latp": "56",
    "Player_1": "Kelleher 13",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 6",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Van den",
    "Player_14": "Frimpong 6",
    "Player_7": "Grealish -1",
    "Player_2": "Thiaw -1",
    "Player_5": "Rogers 3",
    "Player_6": "Casemiro 4",
    "Player_3": "Gabriel 6",
    "Player_4": "Dorgu 5",
    "Player_8": "Rice 3",
    "Player_9": "Saka 6",
    "Player_15": "Ekitik\u00E9 0"
  },
  {
    "manager_Name": "1,410( 19 )",
    "Teams": "For my sins( Adam Davey )",
    "SXL": "ENG",
    "Latp": "62",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "Verbruggen 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Est\u00E8ve 3",
    "Player_7": "Bruno G.",
    "Player_2": "Dalot 1",
    "Player_5": "Saka 3",
    "Player_6": "Cunha 2",
    "Player_3": "Kayode 6",
    "Player_4": "O\u0027Reilly 1",
    "Player_8": "Foden 2",
    "Player_9": "Wilson 9",
    "Player_15": "Van Hecke"
  },
  {
    "manager_Name": "1,409( 20 )",
    "Teams": "Walkin Humans( Gustav Walkin )",
    "SXL": "SWE",
    "Latp": "45",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 12",
    "Player_10": "Semenyo 6",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Konsa 7",
    "Player_14": "Ekitik\u00E9 0",
    "Player_7": "Rogers 3",
    "Player_2": "Dalot 1",
    "Player_5": "Thiaw -1",
    "Player_6": "Foden 2",
    "Player_3": "Keane 5",
    "Player_4": "Gabriel 6",
    "Player_8": "Cunha 2",
    "Player_9": "Rice 3",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,408( 21 )",
    "Teams": "The Clearlake Blues( Bahij Hourani )",
    "SXL": "USA",
    "Latp": "73",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "Verbruggen 3",
    "Player_13": "Virgil 6",
    "Player_14": "Van Hecke",
    "Player_7": "Cunha 2",
    "Player_2": "Collins 13",
    "Player_5": "Foden 2",
    "Player_6": "Bruno G.",
    "Player_3": "Hall 4",
    "Player_4": "Gabriel 6",
    "Player_8": "Saka 3",
    "Player_9": "Ra\u00FAl 5",
    "Player_15": "Dewsbury-Hall 0"
  },
  {
    "manager_Name": "1,408( 22 )",
    "Teams": "neto delap garnacho( gus tav )",
    "SXL": "SWE",
    "Latp": "51",
    "Player_1": "Lammens 1",
    "Player_11": "Haaland 12",
    "Player_10": "Calvert-Lewin 8",
    "Player_12": "Kelleher 13",
    "Player_13": "Calafiori 0",
    "Player_14": "Van Hecke",
    "Player_7": "Saka 3",
    "Player_2": "Collins 13",
    "Player_5": "Wirtz 3",
    "Player_6": "Cunha 2",
    "Player_3": "Thiaw -1",
    "Player_4": "Gabriel 6",
    "Player_8": "Rogers 3",
    "Player_9": "Cherki 1",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,407( 23 )",
    "Teams": "Shien( Wei Shien Ng )",
    "SXL": "MYS",
    "Latp": "42",
    "Player_1": "Kelleher 13",
    "Player_11": "Haaland 12",
    "Player_10": "Rice 3",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Virgil 6",
    "Player_7": "Foden 2",
    "Player_2": "Gabriel 6",
    "Player_5": "Alderete 1",
    "Player_6": "E.Le F\u00E9e",
    "Player_3": "O\u0027Reilly 1",
    "Player_4": "Thiaw -1",
    "Player_8": "Saka 3",
    "Player_9": "Cunha 2",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,407( 24 )",
    "Teams": "Wingardium LeviSosa( Scott Whittaker )",
    "SXL": "ENG",
    "Latp": "73",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 12",
    "Player_10": "Bowen 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "O\u0027Reilly 1",
    "Player_14": "Gravenberch 3",
    "Player_7": "Cunha 2",
    "Player_2": "Collins 13",
    "Player_5": "Bruno G.",
    "Player_6": "Foden 2",
    "Player_3": "Tarkowski 4",
    "Player_4": "Gabriel 6",
    "Player_8": "Rice 3",
    "Player_9": "Thiago 12",
    "Player_15": "Richards 0"
  },
  {
    "manager_Name": "1,407( 25 )",
    "Teams": "mirinda( Luka Ortulan )",
    "SXL": "HRV",
    "Latp": "66",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 12",
    "Player_10": "Bowen 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Wilson 9",
    "Player_14": "Virgil 6",
    "Player_7": "Foden 2",
    "Player_2": "Tarkowski 4",
    "Player_5": "Wirtz 3",
    "Player_6": "Bruno G.",
    "Player_3": "Senesi 6",
    "Player_4": "Gabriel 6",
    "Player_8": "Cunha 2",
    "Player_9": "Thiago 12",
    "Player_15": "Van Hecke"
  },
  {
    "manager_Name": "1,406( 26 )",
    "Teams": "Farke The Bus( Liam Chamberlai )",
    "SXL": "ENG",
    "Latp": "68",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "Verbruggen 3",
    "Player_13": "Wilson 9",
    "Player_14": "Stach 2",
    "Player_7": "Cunha 2",
    "Player_2": "Thiaw -1",
    "Player_5": "Gabriel 6",
    "Player_6": "Collins 13",
    "Player_3": "Matheus N.",
    "Player_4": "Keane 5",
    "Player_8": "Bruno G.",
    "Player_9": "Saka 3",
    "Player_15": "Ekitik\u00E9 0"
  },
  {
    "manager_Name": "1,405( 27 )",
    "Teams": "sexy11( Naveen Shariff )",
    "SXL": "PAK",
    "Latp": "61",
    "Player_1": "Kelleher 13",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "Verbruggen 3",
    "Player_13": "Semenyo 6",
    "Player_14": "Senesi 6",
    "Player_7": "Cherki 1",
    "Player_2": "Cash 6",
    "Player_5": "Gabriel 6",
    "Player_6": "Foden 2",
    "Player_3": "Tarkowski 4",
    "Player_4": "Thiaw -1",
    "Player_8": "Rogers 3",
    "Player_9": "Rice 3",
    "Player_15": "Ekitik\u00E9 0"
  },
  {
    "manager_Name": "1,404( 28 )",
    "Teams": "C.R.T 1961( --Tayeb Ben--- )",
    "SXL": "DZA",
    "Latp": "75",
    "Player_1": "Kelleher 13",
    "Player_11": "\u0160e\u0161ko 13",
    "Player_10": "Thiago 12",
    "Player_12": "S\u00E1nchez 2",
    "Player_13": "Wilson 9",
    "Player_14": "Andersen 2",
    "Player_7": "Saka 3",
    "Player_2": "Gu\u00E9hi 6",
    "Player_5": "Cunha 2",
    "Player_6": "Bruno G.",
    "Player_3": "Truffert 1",
    "Player_4": "Thiaw -1",
    "Player_8": "Szoboszlai 3",
    "Player_9": "Haaland 12",
    "Player_15": "Virgil 6"
  },
  {
    "manager_Name": "1,404( 29 )",
    "Teams": "Harvey Had a Dream( Daniel Harris )",
    "SXL": "ENG",
    "Latp": "60",
    "Player_1": "Pickford 3",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "Kelleher 13",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Van de",
    "Player_7": "Wilson 9",
    "Player_2": "Mukiele 3",
    "Player_5": "Rogers 3",
    "Player_6": "Foden 2",
    "Player_3": "J.Timber 6",
    "Player_4": "Senesi 6",
    "Player_8": "Cherki 1",
    "Player_9": "Rice 3",
    "Player_15": "Dorgu 5"
  },
  {
    "manager_Name": "1,403( 30 )",
    "Teams": "Big Dom\u0027s Army( Ryan Monaghan )",
    "SXL": "IRL",
    "Latp": "55",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 12",
    "Player_10": "Foden 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Van Hecke",
    "Player_7": "Xhaka 2",
    "Player_2": "Van de",
    "Player_5": "Gu\u00E9hi 6",
    "Player_6": "Bruno G.",
    "Player_3": "Gabriel 6",
    "Player_4": "O\u0027Reilly 1",
    "Player_8": "Saka 3",
    "Player_9": "Semenyo 6",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,402( 31 )",
    "Teams": "The DAK( Daniel Knox )",
    "SXL": "SCO",
    "Latp": "71",
    "Player_1": "Kelleher 13",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "S\u00E1nchez 2",
    "Player_13": "Calvert-Lewin 8",
    "Player_14": "Andersen 2",
    "Player_7": "Saka 3",
    "Player_2": "Cash 6",
    "Player_5": "Bruno G.",
    "Player_6": "Rogers 3",
    "Player_3": "Gabriel 6",
    "Player_4": "Van de",
    "Player_8": "Foden 2",
    "Player_9": "Rice 3",
    "Player_15": "Gvardiol 0"
  },
  {
    "manager_Name": "1,401( 32 )",
    "Teams": "xMONDAY( Sutas Nakphan )",
    "SXL": "THA",
    "Latp": "60",
    "Player_1": "Verbruggen 3",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "S\u00E1nchez 2",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "O\u0027Reilly 1",
    "Player_7": "Cunha 2",
    "Player_2": "Keane 5",
    "Player_5": "Rogers 3",
    "Player_6": "Foden 2",
    "Player_3": "Gabriel 6",
    "Player_4": "Dorgu 5",
    "Player_8": "Gordon 1",
    "Player_9": "Wilson 9",
    "Player_15": "Andersen 2"
  },
  {
    "manager_Name": "1,401( 33 )",
    "Teams": "Rostafari FC( G\u00F6sta Gustafsson )",
    "SXL": "SWE",
    "Latp": "69",
    "Player_1": "Kelleher 13",
    "Player_11": "Thiago 12",
    "Player_10": "Bowen 2",
    "Player_12": "Verbruggen 3",
    "Player_13": "Andersen 2",
    "Player_14": "Wirtz 3",
    "Player_7": "Gordon 1",
    "Player_2": "Keane 5",
    "Player_5": "Foden 2",
    "Player_6": "Saka 3",
    "Player_3": "Tarkowski 4",
    "Player_4": "Gabriel 6",
    "Player_8": "Wilson 9",
    "Player_9": "Haaland 12",
    "Player_15": "Reinildo 0"
  },
  {
    "manager_Name": "1,400( 34 )",
    "Teams": "Is your Motherwell?( Harry Shepherd )",
    "SXL": "ENG",
    "Latp": "68",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "S\u00E1nchez 2",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Van de",
    "Player_7": "Anderson 7",
    "Player_2": "Hall 4",
    "Player_5": "Saka 3",
    "Player_6": "Foden 2",
    "Player_3": "Keane 5",
    "Player_4": "Collins 13",
    "Player_8": "L.Miley 4",
    "Player_9": "Wirtz 3",
    "Player_15": "Andersen 2"
  },
  {
    "manager_Name": "1,400( 35 )",
    "Teams": "Mayenda v DeFender( Louis Dinsdale )",
    "SXL": "ENG",
    "Latp": "69",
    "Player_1": "Kelleher 13",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "Roefs 2",
    "Player_13": "Calvert-Lewin 8",
    "Player_14": "Xhaka 2",
    "Player_7": "Saka 3",
    "Player_2": "Collins 13",
    "Player_5": "Thiaw -1",
    "Player_6": "Rogers 3",
    "Player_3": "J.Timber 6",
    "Player_4": "Mukiele 3",
    "Player_8": "Foden 2",
    "Player_9": "Rice 3",
    "Player_15": "Pedro Porro"
  },
  {
    "manager_Name": "1,400( 35 )",
    "Teams": "Shaw Me The Money( Bror Martin Juhasz Fossum )",
    "SXL": "NOR",
    "Latp": "60",
    "Player_1": "Kelleher 13",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Andersen 2",
    "Player_14": "L.Paquet\u00E1 2",
    "Player_7": "Saka 3",
    "Player_2": "Thiaw -1",
    "Player_5": "O\u0027Reilly 1",
    "Player_6": "Cunha 2",
    "Player_3": "Tarkowski 4",
    "Player_4": "Gabriel 6",
    "Player_8": "Foden 2",
    "Player_9": "Semenyo 6",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,400( 37 )",
    "Teams": "Livy( Livinus Asaah )",
    "SXL": "NGA",
    "Latp": "60",
    "Player_1": "Kelleher 13",
    "Player_11": "Bowen 2",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Clyne 0",
    "Player_14": "De Cuyper",
    "Player_7": "Cunha 2",
    "Player_2": "Lewis-Potter 6",
    "Player_5": "Rice 3",
    "Player_6": "Rogers 3",
    "Player_3": "Thiaw -1",
    "Player_4": "Gabriel 6",
    "Player_8": "Foden 2",
    "Player_9": "Thiago 12",
    "Player_15": "Minteh 0"
  },
  {
    "manager_Name": "1,400( 38 )",
    "Teams": "Boat Toffees( boat cahill )",
    "SXL": "THA",
    "Latp": "46",
    "Player_1": "Raya 6",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Andersen 2",
    "Player_14": "Barnes 0",
    "Player_7": "Saka 3",
    "Player_2": "Gabriel 6",
    "Player_5": "Foden 2",
    "Player_6": "Cunha 2",
    "Player_3": "Dalot 1",
    "Player_4": "Van de",
    "Player_8": "Cherki 1",
    "Player_9": "Palmer 1",
    "Player_15": "Rodon 1"
  },
  {
    "manager_Name": "1,399( 39 )",
    "Teams": "Tori Laure( Deepak Bhandari )",
    "SXL": "USA",
    "Latp": "74",
    "Player_1": "Pickford 3",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "Pope 2",
    "Player_13": "Wilson 9",
    "Player_14": "Virgil 6",
    "Player_7": "Cherki 1",
    "Player_2": "Keane 5",
    "Player_5": "Foden 2",
    "Player_6": "Saka 3",
    "Player_3": "Dalot 1",
    "Player_4": "J.Timber 6",
    "Player_8": "Rogers 3",
    "Player_9": "Barry 2",
    "Player_15": "Konsa 7"
  },
  {
    "manager_Name": "1,398( 40 )",
    "Teams": "FreiburgChamp( Parsa Ebrahimi )",
    "SXL": "DEU",
    "Latp": "51",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Calvert-Lewin 8",
    "Player_10": "Haaland 12",
    "Player_12": "Verbruggen 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Szoboszlai 3",
    "Player_7": "Cherki 1",
    "Player_2": "Gabriel 6",
    "Player_5": "Hall 4",
    "Player_6": "Cunha 2",
    "Player_3": "Tarkowski 4",
    "Player_4": "Dorgu 5",
    "Player_8": "Rogers 3",
    "Player_9": "Rice 3",
    "Player_15": "O\u0027Reilly 1"
  },
  {
    "manager_Name": "1,398( 41 )",
    "Teams": "Hamzah Bhi( Hamzah Attique )",
    "SXL": "ENG",
    "Latp": "76",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "Sels 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Gravenberch 3",
    "Player_7": "Wilson 9",
    "Player_2": "Gabriel 6",
    "Player_5": "O\u0027Reilly 1",
    "Player_6": "Foden 2",
    "Player_3": "Gu\u00E9hi 6",
    "Player_4": "Collins 13",
    "Player_8": "Schade 6",
    "Player_9": "Rogers 3",
    "Player_15": "Senesi 6"
  },
  {
    "manager_Name": "1,398( 41 )",
    "Teams": "DrEaM TeAm( idris alqatrany )",
    "SXL": "LBY",
    "Latp": "72",
    "Player_1": "Kelleher 13",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "S\u00E1nchez 2",
    "Player_13": "Mukiele 3",
    "Player_14": "Ekitik\u00E9 0",
    "Player_7": "Saka 3",
    "Player_2": "Matheus N.",
    "Player_5": "Semenyo 6",
    "Player_6": "Rogers 3",
    "Player_3": "Dorgu 5",
    "Player_4": "Gabriel 6",
    "Player_8": "Cherki 1",
    "Player_9": "Wilson 9",
    "Player_15": "Gu\u00E9hi 6"
  },
  {
    "manager_Name": "1,398( 41 )",
    "Teams": "PigglyKeeks( Darren McMullin )",
    "SXL": "AUS",
    "Latp": "55",
    "Player_1": "Raya 6",
    "Player_11": "Ra\u00FAl 5",
    "Player_10": "Thiago 12",
    "Player_12": "Roefs 2",
    "Player_13": "Gravenberch 3",
    "Player_14": "Truffert 1",
    "Player_7": "Gordon 1",
    "Player_2": "Gabriel 6",
    "Player_5": "Saka 3",
    "Player_6": "Foden 2",
    "Player_3": "Thiaw -1",
    "Player_4": "Kayode 6",
    "Player_8": "Rogers 3",
    "Player_9": "Haaland 12",
    "Player_15": "Van Hecke"
  },
  {
    "manager_Name": "1,397( 44 )",
    "Teams": "The Real Quiz( Matt Boyce )",
    "SXL": "ENG",
    "Latp": "50",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Haaland 12",
    "Player_10": "Szoboszlai 3",
    "Player_12": "Verbruggen 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Est\u00E8ve 3",
    "Player_7": "Bruno G.",
    "Player_2": "Thiaw -1",
    "Player_5": "Keane 5",
    "Player_6": "Rogers 3",
    "Player_3": "Gabriel 6",
    "Player_4": "Chalobah 3",
    "Player_8": "Saka 3",
    "Player_9": "Foden 2",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "1,396( 45 )",
    "Teams": "M7( mo 7 )",
    "SXL": "IRQ",
    "Latp": "54",
    "Player_1": "Raya 6",
    "Player_11": "Watkins 2",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Wilson 9",
    "Player_14": "Frimpong 6",
    "Player_7": "Rogers 3",
    "Player_2": "Hall 4",
    "Player_5": "Gordon 1",
    "Player_6": "\u00D8degaard 3",
    "Player_3": "Tarkowski 4",
    "Player_4": "Gabriel 6",
    "Player_8": "Cherki 1",
    "Player_9": "Thiago 12",
    "Player_15": "Nallo 0"
  },
  {
    "manager_Name": "1,396( 46 )",
    "Teams": "Ahli Stars( Mo Khattab )",
    "SXL": "EGY",
    "Latp": "62",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Ekitik\u00E9 0",
    "Player_14": "Gudmundsson 0",
    "Player_7": "Saka 3",
    "Player_2": "Dorgu 5",
    "Player_5": "Cunha 2",
    "Player_6": "Foden 2",
    "Player_3": "Gabriel 6",
    "Player_4": "Konat\u00E9 7",
    "Player_8": "Szoboszlai 3",
    "Player_9": "L.Miley 4",
    "Player_15": "Clyne 0"
  },
  {
    "manager_Name": "1,395( 47 )",
    "Teams": "Earth, Wind\u0026 Maguire( Peter Howe )",
    "SXL": "ENG",
    "Latp": "57",
    "Player_1": "Henderson 7",
    "Player_11": "Haaland 12",
    "Player_10": "Rogers 3",
    "Player_12": "A.Becker 10",
    "Player_13": "Kroupi.Jr 7",
    "Player_14": "Virgil 6",
    "Player_7": "Cherki 1",
    "Player_2": "Van de",
    "Player_5": "Lewis-Potter 6",
    "Player_6": "Rice 3",
    "Player_3": "Gabriel 6",
    "Player_4": "Gu\u00E9hi 6",
    "Player_8": "Foden 2",
    "Player_9": "Bruno G.",
    "Player_15": "Ekitik\u00E9 0"
  },
  {
    "manager_Name": "1,395( 48 )",
    "Teams": "The Pros( Doctor Mo )",
    "SXL": "EGY",
    "Latp": "60",
    "Player_1": "D\u00FAbravka 3",
    "Player_11": "Haaland 12",
    "Player_10": "Thiago 12",
    "Player_12": "Verbruggen 3",
    "Player_13": "Ra\u00FAl 5",
    "Player_14": "Gu\u00E9hi 6",
    "Player_7": "Foden 2",
    "Player_2": "Dorgu 5",
    "Player_5": "Saka 3",
    "Player_6": "Cunha 2",
    "Player_3": "Keane 5",
    "Player_4": "J.Timber 6",
    "Player_8": "Gordon 1",
    "Player_9": "Wilson 9",
    "Player_15": "Andersen 2"
  },
  {
    "manager_Name": "1,395( 49 )",
    "Teams": "OuiHenry( Jack Pick )",
    "SXL": "AUS",
    "Latp": "56",
    "Player_1": "Raya 6",
    "Player_11": "Thiago 12",
    "Player_10": "Haaland 12",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Van Hecke",
    "Player_14": "Xhaka 2",
    "Player_7": "Saka 3",
    "Player_2": "Gabriel 6",
    "Player_5": "Gu\u00E9hi 6",
    "Player_6": "Foden 2",
    "Player_3": "Chalobah 3",
    "Player_4": "Van de",
    "Player_8": "Cunha 2",
    "Player_9": "L.Miley 4",
    "Player_15": "Ekitik\u00E9 0"
  },
  {
    "manager_Name": "1,394( 50 )",
    "Teams": "Pessimistic doomlord( Robert Adam )",
    "SXL": "ENG",
    "Latp": "65",
    "Player_1": "Kelleher 13",
    "Player_11": "Haaland 12",
    "Player_10": "Bowen 2",
    "Player_12": "D\u00FAbravka 3",
    "Player_13": "Van de",
    "Player_14": "Mukiele 3",
    "Player_7": "Cherki 1",
    "Player_2": "Gabriel 6",
    "Player_5": "Foden 2",
    "Player_6": "Rogers 3",
    "Player_3": "Hall 4",
    "Player_4": "Saliba 7",
    "Player_8": "Saka 3",
    "Player_9": "Thiago 12",
    "Player_15": "E.Le F\u00E9e"
  }
];