var s = [
  {
    "manager_Name": "1,126( 1,366,887 )",
    "Teams": "yoo( Nishant Singh )",
    "SXL": "IND",
    "Latp": "7",
    "Player_1": "Donnarumma 1",
    "Player_11": "Haaland 2",
    "Player_10": "Watkins 1",
    "Player_12": "Kelleher 1",
    "Player_13": "Mukiele 1",
    "Player_14": "Xhaka 1",
    "Player_7": "Saka LIV",
    "Player_2": "J.Timber LIV",
    "Player_5": "Tarkowski 1",
    "Player_6": "Rogers 1",
    "Player_3": "Gabriel LIV",
    "Player_4": "Thiaw LEE",
    "Player_8": "Cherki 0",
    "Player_9": "Thiago 1",
    "Player_15": "Devenny 1"
  },
  {
    "manager_Name": "1,099( 2,179,626 )",
    "Teams": "WMB( Raj Kanango )",
    "SXL": "IND",
    "Latp": "8",
    "Player_1": "Donnarumma 1",
    "Player_11": "Haaland 2",
    "Player_10": "Bowen 2",
    "Player_12": "D\u00FAbravka MUN",
    "Player_13": "Wilson 1",
    "Player_14": "Senesi 1",
    "Player_7": "Saka LIV",
    "Player_2": "Dorgu BUR",
    "Player_5": "J.Timber LIV",
    "Player_6": "Rogers 1",
    "Player_3": "Dalot BUR",
    "Player_4": "Thiaw LEE",
    "Player_8": "Semenyo 1",
    "Player_9": "Thiago 1",
    "Player_15": "Cullen MUN"
  },
  {
    "manager_Name": "1,044( 4,189,274 )",
    "Teams": "F95( Sibin - )",
    "SXL": "IND",
    "Latp": "8",
    "Player_1": "Raya LIV",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago 1",
    "Player_12": "Petrovi\u0107 1",
    "Player_13": "Ekitik\u00E9 ARS",
    "Player_14": "L.Miley LEE",
    "Player_7": "Foden 1",
    "Player_2": "Mukiele 1",
    "Player_5": "Mitchell 1",
    "Player_6": "Alderete 1",
    "Player_3": "Cash 1",
    "Player_4": "Thiaw LEE",
    "Player_8": "Saka LIV",
    "Player_9": "Rice LIV",
    "Player_15": "Stach NEW"
  },
  {
    "manager_Name": "984( 6,355,109 )",
    "Teams": "DUFC( Nitesh Kumar Singh )",
    "SXL": "IND",
    "Latp": "8",
    "Player_1": "Pickford 1",
    "Player_11": "Richarlison 0",
    "Player_10": "Woltemade LEE",
    "Player_12": "D\u00FAbravka MUN",
    "Player_13": "Mitchell 1",
    "Player_14": "Tavernier 4",
    "Player_7": "Bruno G.",
    "Player_2": "Gu\u00E9hi 1",
    "Player_5": "Foden 1",
    "Player_6": "Rogers 1",
    "Player_3": "Chalobah 1",
    "Player_4": "R\u00FAben 0",
    "Player_8": "Garner 1",
    "Player_9": "Haaland 2",
    "Player_15": "Senesi 1"
  }
];