var s = [
  {
    "manager_Name": "1,799( 391,519 ) TotalXfr : 29",
    "Teams": "WMB( Raj Kanango )",
    "SXL": "countryCode",
    "Latp": "48",
    "Player_1": "Henderson 2",
    "Player_11": "Watkins 5",
    "Player_10": "Cunha 2",
    "Player_12": "Fabianski 0",
    "Player_13": "Isak 0",
    "Player_14": "Mykolenko 6",
    "Player_7": "Palmer 6",
    "Player_2": "Tarkowski 2",
    "Player_5": "Robinson 0",
    "Player_6": "Kluivert 10",
    "Player_3": "J.Timber 6",
    "Player_4": "Alexander-Arnold 6",
    "Player_8": "M.Salah 6",
    "Player_9": "Elanga 3",
    "Player_15": "Rogers 7"
  },
  {
    "manager_Name": "1,797( 409,489 ) TotalXfr : 33",
    "Teams": "yoo( Nishant Singh )",
    "SXL": "countryCode",
    "Latp": "58",
    "Player_1": "Flekken 3",
    "Player_11": "Wood 2",
    "Player_10": "Cunha 2",
    "Player_12": "Moyes 4",
    "Player_13": "Fabianski 0",
    "Player_14": "Isak 0",
    "Player_7": "Palmer 3",
    "Player_2": "Robinson 0",
    "Player_5": "Alexander-Arnold 6",
    "Player_6": "M.Salah 12",
    "Player_3": "Mykolenko 6",
    "Player_4": "Gabriel 7",
    "Player_8": "Kluivert 10",
    "Player_9": "Elanga 3",
    "Player_15": "Rogers 7"
  },
  {
    "manager_Name": "1,739( 1,094,692 ) TotalXfr : 33",
    "Teams": "Weightloss Coach( Abhijeet Singh )",
    "SXL": "countryCode",
    "Latp": "53",
    "Player_1": "Jos\u00E9 S\u00E1 2",
    "Player_11": "Wood 2",
    "Player_10": "Mitoma 2",
    "Player_12": "Fabianski 0",
    "Player_13": "Isak 0",
    "Player_14": "Rogers 7",
    "Player_7": "Palmer 6",
    "Player_2": "Konat\u00E9 6",
    "Player_5": "Robinson 0",
    "Player_6": "Mykolenko 6",
    "Player_3": "Alexander-Arnold 6",
    "Player_4": "Gabriel 7",
    "Player_8": "M.Salah 6",
    "Player_9": "Kluivert 10",
    "Player_15": "Ndiaye 0"
  },
  {
    "manager_Name": "1,732( 1,196,227 ) TotalXfr : 25",
    "Teams": "Bihar 11( Sanjeev Kumar )",
    "SXL": "countryCode",
    "Latp": "71",
    "Player_1": "Sels 6",
    "Player_11": "Gakpo 1",
    "Player_10": "Wood 2",
    "Player_12": "Slot 10",
    "Player_13": "Fabianski 0",
    "Player_14": "Isak 0",
    "Player_7": "M.Salah 12",
    "Player_2": "Robinson 0",
    "Player_5": "Gabriel 7",
    "Player_6": "Palmer 3",
    "Player_3": "Kerkez 4",
    "Player_4": "Huijsen 1",
    "Player_8": "Kluivert 10",
    "Player_9": "I.Sarr 15",
    "Player_15": "Amad 0"
  },
  {
    "manager_Name": "1,678( 2,199,374 ) TotalXfr : 30",
    "Teams": "SibinZibin( Sibin _ )",
    "SXL": "countryCode",
    "Latp": "58",
    "Player_1": "Pickford 2",
    "Player_11": "Watkins 5",
    "Player_10": "Wood 2",
    "Player_12": "Henderson 2",
    "Player_13": "Isak 0",
    "Player_14": "Burn 1",
    "Player_7": "Kluivert 10",
    "Player_2": "Dalot 4",
    "Player_5": "Milenkovi\u0107 5",
    "Player_6": "Nwaneri 3",
    "Player_3": "Konat\u00E9 6",
    "Player_4": "J.Timber 6",
    "Player_8": "M.Salah 12",
    "Player_9": "Palmer 3",
    "Player_15": "Iroegbunam 1"
  },
  {
    "manager_Name": "1,454( 6,178,383 ) TotalXfr : 26",
    "Teams": "Danapur United( Nitesh Kumar Singh )",
    "SXL": "countryCode",
    "Latp": "52",
    "Player_1": "Arrizabalaga 1",
    "Player_11": "Watkins 5",
    "Player_10": "Cunha 2",
    "Player_12": "King 0",
    "Player_13": "Yarmoliuk 1",
    "Player_14": "Keane 0",
    "Player_7": "Iwobi 1",
    "Player_2": "Gvardiol 7",
    "Player_5": "Aina 6",
    "Player_6": "Palmer 3",
    "Player_3": "Alexander-Arnold 6",
    "Player_4": "J.Timber 6",
    "Player_8": "M.Salah 12",
    "Player_9": "Schade 3",
    "Player_15": "Strand Larsen 1"
  },
  {
    "manager_Name": "1,220( 9,043,799 ) TotalXfr : 0",
    "Teams": "Prabin Singh( Prabin Singh )",
    "SXL": "countryCode",
    "Latp": "54",
    "Player_1": "Ederson M. 11",
    "Player_11": "Mateta 8",
    "Player_10": "Darwin 2",
    "Player_12": "A.Becker 6",
    "Player_13": "Walker 0",
    "Player_14": "Martinelli 0",
    "Player_7": "Sterling 1",
    "Player_2": "Gvardiol 7",
    "Player_5": "Virgil 7",
    "Player_6": "Eze 5",
    "Player_3": "Gabriel 7",
    "Player_4": "Calafiori 0",
    "Player_8": "Mbeumo 5",
    "Player_9": "Rashford 1",
    "Player_15": "Isak 0"
  }
];