// Fetches current weather for every stop in stops.json and writes the
// result to weatherData.json, which the page reads at load time. Same
// pattern as ../scrapeWeather.js — a periodic snapshot generated by
// hand-running this script (or the scheduled workflow), not a live
// per-visitor API call.
//
// Run manually from this folder: `node scrapeWeather.js`
//
// Keyed by `order` (route position) rather than `iso2`: several stops
// share a state (Kerala alone has 13 of the 39), and this is a route, not
// a set of distinct places ranked against each other, so "order" is also
// the more meaningful key than an artificial rank would be.
//
// The one thing beyond a plain snapshot: Koyilandi (stops.json's one
// entry with a `watch` field) gets checked against its threshold every
// run and logged loudly when crossed — see the README's "Koyilandi watch"
// section for why this exists and why it's a log line, not a different
// polling schedule.

const fs = require("fs");
const path = require("path");

// Same free-tier key every other scrapeWeather.js in this app already
// ships to the browser — reusing it here doesn't expose anything new.
const API_KEY = "39a9a737b07b4b703e3d1cd1e231eedc";
const DELAY_MS = 1100; // keeps us under OpenWeather's free-tier 60-calls/minute limit

const STOPS_PATH = path.join(__dirname, "stops.json");
const OUTPUT_PATH = path.join(__dirname, "weatherData.json");

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function fetchWeather(stop) {
  const url =
    `https://api.openweathermap.org/data/2.5/weather` +
    `?lat=${stop.lat}&lon=${stop.lon}&units=metric&appid=${API_KEY}`;

  const response = await fetch(url);
  const data = await response.json();

  if (!response.ok) {
    throw new Error(data.message || `Request failed (${response.status})`);
  }

  return {
    temp: data.main.temp,
    description: data.weather[0] ? data.weather[0].description : "",
    timezone: data.timezone,
    sunrise: data.sys.sunrise,
    sunset: data.sys.sunset,
    dayLengthSeconds: data.sys.sunset - data.sys.sunrise,
  };
}

async function main() {
  const stops = JSON.parse(fs.readFileSync(STOPS_PATH, "utf8"));
  const existing = fs.existsSync(OUTPUT_PATH)
    ? JSON.parse(fs.readFileSync(OUTPUT_PATH, "utf8"))
    : { generatedAt: null, byOrder: {} };

  const byOrder = { ...existing.byOrder };
  let failures = 0;

  for (const stop of stops) {
    process.stdout.write(`${stop.station}, ${stop.state} (#${stop.order})... `);
    try {
      byOrder[stop.order] = await fetchWeather(stop);
      console.log(`ok, ${byOrder[stop.order].temp.toFixed(1)}°C`);
    } catch (err) {
      // Keep whatever this stop had from the last successful scrape
      // rather than blanking its row out over one flaky request.
      failures += 1;
      console.log(`FAILED (${err.message}) — keeping previous data`);
    }
    await sleep(DELAY_MS);
  }

  // The Koyilandi watch: log loudly (not just another data point) when the
  // one stop with a `watch` threshold actually crosses it, since that's
  // the whole reason this scrapes hourly instead of every few hours like
  // ../scrapeWeather.js does.
  for (const stop of stops) {
    if (!stop.watch) continue;
    const reading = byOrder[stop.order];
    if (reading && reading.temp >= stop.watch.aboveC) {
      console.log(
        `\n>>> WATCH HIT: ${stop.station} is at ${reading.temp.toFixed(1)}°C ` +
        `(>= ${stop.watch.aboveC}°C threshold) <<<\n`
      );
    }
  }

  const output = { generatedAt: Math.floor(Date.now() / 1000), byOrder };
  fs.writeFileSync(OUTPUT_PATH, JSON.stringify(output, null, 2) + "\n");
  console.log(`\nWrote ${Object.keys(byOrder).length} entries to ${OUTPUT_PATH}` +
    (failures ? ` (${failures} failed this run, old data kept for those)` : ""));
}

main();
