var s = [
  {
    "manager_Name": "742( 125,506 )",
    "Teams": "YoureAToneyNoMore( Brendan Kehoe )",
    "SXL": "ENG",
    "Latp": "41",
    "Player_1": "Petrovi\u0107 1",
    "Player_11": "Thiago 4",
    "Player_10": "Mateta 1",
    "Player_12": "Pope 3",
    "Player_13": "Semenyo 0",
    "Player_14": "Kudus 2",
    "Player_7": "Merino 5",
    "Player_2": "Senesi 3",
    "Player_5": "J.Timber 5",
    "Player_6": "Grealish 3",
    "Player_3": "Virgil 3",
    "Player_4": "Gvardiol 1",
    "Player_8": "Enzo 11",
    "Player_9": "Haaland 4",
    "Player_15": "Thiaw 4"
  },
  {
    "manager_Name": "741( 132,464 )",
    "Teams": "Wirtz Nightmare( Adam Owens )",
    "SXL": "WAL",
    "Latp": "45",
    "Player_1": "Raya 2",
    "Player_11": "Thiago 4",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Digne 1",
    "Player_7": "Mbeumo 1",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "Andersen 10",
    "Player_6": "Saka 8",
    "Player_3": "Konat\u00E9 0",
    "Player_4": "Truffert 0",
    "Player_8": "Sarr 3",
    "Player_9": "Mateta 1",
    "Player_15": "King 3"
  },
  {
    "manager_Name": "731( 223,415 )",
    "Teams": "Alpha Academy( Jamie Davies )",
    "SXL": "ENG",
    "Latp": "55",
    "Player_1": "Verbruggen 7",
    "Player_11": "Ekitik\u00E9 1",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Reijnders 1",
    "Player_14": "Matheus N.",
    "Player_7": "Neto 8",
    "Player_2": "Truffert 0",
    "Player_5": "Eze 20",
    "Player_6": "Mbeumo 1",
    "Player_3": "J.Timber 5",
    "Player_4": "Gu\u00E9hi 5",
    "Player_8": "Ndiaye 3",
    "Player_9": "Haaland 4",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "729( 243,024 )",
    "Teams": "Goalless( Panagiotis Sfikas )",
    "SXL": "GRC",
    "Latp": "49",
    "Player_1": "Petrovi\u0107 1",
    "Player_11": "Mateta 1",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Enzo 11",
    "Player_2": "Virgil 3",
    "Player_5": "Diouf 3",
    "Player_6": "Tavernier 7",
    "Player_3": "Cucurella 6",
    "Player_4": "J.Timber 5",
    "Player_8": "Saka 8",
    "Player_9": "B.Fernandes 2",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "726( 277,421 )",
    "Teams": "The Bees( Tove Ronneb\u00E4ck )",
    "SXL": "MLT",
    "Latp": "43",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Haaland 2",
    "Player_10": "Mateta 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Caicedo 0",
    "Player_7": "Mbeumo 1",
    "Player_2": "Lacroix 11",
    "Player_5": "Van de",
    "Player_6": "Est\u00E8ve 3",
    "Player_3": "J.Timber 5",
    "Player_4": "Virgil 3",
    "Player_8": "Sarr 3",
    "Player_9": "Saka 8",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "725( 289,596 )",
    "Teams": "FC Cantona( Nelson Schutt )",
    "SXL": "SWE",
    "Latp": "43",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Haaland 4",
    "Player_10": "Wilson 12",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Patterson 0",
    "Player_14": "Semenyo 0",
    "Player_7": "Saka 4",
    "Player_2": "De Ligt",
    "Player_5": "B.Fernandes 2",
    "Player_6": "King 3",
    "Player_3": "Konat\u00E9 0",
    "Player_4": "James 1",
    "Player_8": "Mbeumo 1",
    "Player_9": "Welbeck 8",
    "Player_15": "Pond 0"
  },
  {
    "manager_Name": "723( 325,467 )",
    "Teams": "Maggnificent15( Derren Maggs )",
    "SXL": "ENG",
    "Latp": "37",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 1",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Gabriel 0",
    "Player_7": "Sarr 3",
    "Player_2": "Richards 6",
    "Player_5": "Van de",
    "Player_6": "Minteh 11",
    "Player_3": "Senesi 3",
    "Player_4": "Gudmundsson 1",
    "Player_8": "Saka 4",
    "Player_9": "B.Fernandes 2",
    "Player_15": "Foster 1"
  },
  {
    "manager_Name": "722( 333,654 )",
    "Teams": "Kings of Leon Osman( Declan Reilly )",
    "SXL": "ENG",
    "Latp": "38",
    "Player_1": "Raya 2",
    "Player_11": "Thiago 4",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Van de",
    "Player_7": "Ndiaye 3",
    "Player_2": "Senesi 3",
    "Player_5": "Tarkowski 8",
    "Player_6": "Saka 4",
    "Player_3": "Rodon 3",
    "Player_4": "Virgil 3",
    "Player_8": "Sarr 3",
    "Player_9": "Mbeumo 1",
    "Player_15": "Kroupi.Jr 2"
  },
  {
    "manager_Name": "721( 355,452 )",
    "Teams": "What The Nelli( Ben Cordingley )",
    "SXL": "ENG",
    "Latp": "71",
    "Player_1": "Raya 2",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Anderson 9",
    "Player_7": "Minteh 11",
    "Player_2": "J.Timber 5",
    "Player_5": "Virgil 3",
    "Player_6": "Senesi 3",
    "Player_3": "Mu\u00F1oz 14",
    "Player_4": "Andersen 10",
    "Player_8": "Enzo 11",
    "Player_9": "Welbeck 8",
    "Player_15": "Ndiaye 3"
  },
  {
    "manager_Name": "714( 481,816 )",
    "Teams": "Glazebrook FC( Sam Frankland )",
    "SXL": "ENG",
    "Latp": "54",
    "Player_1": "D\u00FAbravka 2",
    "Player_11": "Haaland 4",
    "Player_10": "Welbeck 8",
    "Player_12": "Sels 7",
    "Player_13": "Semenyo 0",
    "Player_14": "Van de",
    "Player_7": "Mbeumo 1",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "Gu\u00E9hi 5",
    "Player_6": "Saka 4",
    "Player_3": "James 1",
    "Player_4": "Cash 2",
    "Player_8": "Amad 2",
    "Player_9": "Minteh 11",
    "Player_15": "Woltemade 2"
  },
  {
    "manager_Name": "712( 513,976 )",
    "Teams": "Joga Bonito FC( Christophe Peixoto )",
    "SXL": "HUN",
    "Latp": "43",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 1",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Gudmundsson 1",
    "Player_7": "Saka 4",
    "Player_2": "Senesi 3",
    "Player_5": "Richards 6",
    "Player_6": "Szoboszlai 2",
    "Player_3": "Virgil 3",
    "Player_4": "Chalobah 6",
    "Player_8": "Enzo 11",
    "Player_9": "Haaland 4",
    "Player_15": "Anthony 2"
  },
  {
    "manager_Name": "711( 534,821 )",
    "Teams": "Hltex Lykoi( Ioannis Poulios )",
    "SXL": "GRC",
    "Latp": "45",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Mateta 2",
    "Player_10": "Haaland 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Anderson 9",
    "Player_7": "Sarr 3",
    "Player_2": "J.Timber 5",
    "Player_5": "Van de",
    "Player_6": "Enzo 11",
    "Player_3": "Senesi 3",
    "Player_4": "Gu\u00E9hi 5",
    "Player_8": "Saka 4",
    "Player_9": "Thiago 4",
    "Player_15": "Konsa 2"
  },
  {
    "manager_Name": "710( 565,049 )",
    "Teams": "Saksa FC( Neil Mifsud )",
    "SXL": "MLT",
    "Latp": "43",
    "Player_1": "Pope 3",
    "Player_11": "Haaland 2",
    "Player_10": "Mateta 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Dewsbury-Hall 13",
    "Player_7": "Sarr 3",
    "Player_2": "Cucurella 6",
    "Player_5": "J.Timber 5",
    "Player_6": "Enzo 11",
    "Player_3": "Virgil 3",
    "Player_4": "Richards 6",
    "Player_8": "Mbeumo 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Rodon 3"
  },
  {
    "manager_Name": "701( 769,928 )",
    "Teams": "KERAMACTICOS \u26A1( Michael Keramas )",
    "SXL": "GRC",
    "Latp": "48",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Buend\u00EDa 1",
    "Player_14": "Senesi 3",
    "Player_7": "Minteh 11",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "Mbeumo 1",
    "Player_6": "Gakpo 2",
    "Player_3": "Cucurella 6",
    "Player_4": "Virgil 3",
    "Player_8": "Sarr 3",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "698( 853,426 )",
    "Teams": "Los Blancos( Eamonn Mifsud )",
    "SXL": "MLT",
    "Latp": "42",
    "Player_1": "Donnarumma 1",
    "Player_11": "Mateta 1",
    "Player_10": "Thiago 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Caicedo 0",
    "Player_7": "Sarr 3",
    "Player_2": "Virgil 3",
    "Player_5": "Andersen 10",
    "Player_6": "B.Fernandes 2",
    "Player_3": "J.Timber 5",
    "Player_4": "Senesi 3",
    "Player_8": "Rice 6",
    "Player_9": "Haaland 4",
    "Player_15": "Rodon 3"
  },
  {
    "manager_Name": "697( 880,188 )",
    "Teams": "Lallish United( Melwin Holst )",
    "SXL": "SWE",
    "Latp": "36",
    "Player_1": "Raya 2",
    "Player_11": "Thiago 4",
    "Player_10": "Mateta 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Caicedo 0",
    "Player_7": "Saka 4",
    "Player_2": "Senesi 3",
    "Player_5": "Gvardiol 1",
    "Player_6": "Sarr 3",
    "Player_3": "Gu\u00E9hi 5",
    "Player_4": "J.Timber 5",
    "Player_8": "Stach 4",
    "Player_9": "Haaland 4",
    "Player_15": "Burn 0"
  },
  {
    "manager_Name": "696( 912,172 )",
    "Teams": "Gambit( Nicola Frasca )",
    "SXL": "MLT",
    "Latp": "24",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 4",
    "Player_12": "Verbruggen 7",
    "Player_13": "Caicedo 0",
    "Player_14": "Wan-Bissaka 2",
    "Player_7": "Reijnders 1",
    "Player_2": "Virgil 3",
    "Player_5": "Est\u00E8ve 3",
    "Player_6": "Grealish 3",
    "Player_3": "Van de",
    "Player_4": "Gudmundsson 1",
    "Player_8": "Mbeumo 1",
    "Player_9": "Mateta 1",
    "Player_15": "Semenyo 0"
  },
  {
    "manager_Name": "696( 912,172 )",
    "Teams": "COYS( Zachary Black )",
    "SXL": "CAN",
    "Latp": "39",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Welbeck 8",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Est\u00E8ve 3",
    "Player_14": "Nyoni 0",
    "Player_7": "Saka 4",
    "Player_2": "Cucurella 6",
    "Player_5": "Konsa 2",
    "Player_6": "M.Salah 4",
    "Player_3": "Van de",
    "Player_4": "Gu\u00E9hi 5",
    "Player_8": "Gravenberch 1",
    "Player_9": "Haaland 2",
    "Player_15": "Devenny 1"
  },
  {
    "manager_Name": "696( 917,029 )",
    "Teams": "kinder mbeumo( Gianluca Tanti )",
    "SXL": "MLT",
    "Latp": "45",
    "Player_1": "Raya 2",
    "Player_11": "Thiago 4",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Konsa 2",
    "Player_7": "Saka 4",
    "Player_2": "Lacroix 11",
    "Player_5": "Anderson 9",
    "Player_6": "Mbeumo 1",
    "Player_3": "Virgil 3",
    "Player_4": "Senesi 3",
    "Player_8": "Ndiaye 3",
    "Player_9": "Mateta 1",
    "Player_15": "Reinildo 1"
  },
  {
    "manager_Name": "694( 968,524 )",
    "Teams": "House TarGoalyen( Matteo Farrugia )",
    "SXL": "MLT",
    "Latp": "43",
    "Player_1": "Raya 2",
    "Player_11": "Watkins 2",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Konsa 2",
    "Player_7": "Mbeumo 1",
    "Player_2": "Saliba 2",
    "Player_5": "Est\u00E8ve 3",
    "Player_6": "B.Fernandes 2",
    "Player_3": "Virgil 3",
    "Player_4": "Van de",
    "Player_8": "Anderson 9",
    "Player_9": "Rogers 15",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "694( 969,173 )",
    "Teams": "Malta Knights( Martin Knight )",
    "SXL": "MLT",
    "Latp": "45",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 2",
    "Player_10": "Bowen 8",
    "Player_12": "Pope 3",
    "Player_13": "Gabriel 0",
    "Player_14": "Semenyo 0",
    "Player_7": "Rice 6",
    "Player_2": "Diouf 3",
    "Player_5": "Lacroix 11",
    "Player_6": "Sarr 3",
    "Player_3": "Konsa 2",
    "Player_4": "Gu\u00E9hi 5",
    "Player_8": "Mac Allister",
    "Player_9": "Ekitik\u00E9 1",
    "Player_15": "Caicedo 0"
  },
  {
    "manager_Name": "694( 990,771 )",
    "Teams": "IK S\u00E4tra( Filip Larsson )",
    "SXL": "MLT",
    "Latp": "64",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Mateta 1",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Reijnders 1",
    "Player_14": "Gabriel 0",
    "Player_7": "Eze 20",
    "Player_2": "Virgil 3",
    "Player_5": "Anderson 9",
    "Player_6": "Gakpo 2",
    "Player_3": "Mu\u00F1oz 14",
    "Player_4": "Van de",
    "Player_8": "Mbeumo 1",
    "Player_9": "Thiago 4",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "687( 1,203,324 )",
    "Teams": "DBA Utd( Jim Lennox )",
    "SXL": "ENG",
    "Latp": "42",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 1",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Mukiele 4",
    "Player_7": "Minteh 11",
    "Player_2": "J.Timber 5",
    "Player_5": "Senesi 3",
    "Player_6": "Mbeumo 1",
    "Player_3": "Van de",
    "Player_4": "Andersen 10",
    "Player_8": "B.Fernandes 2",
    "Player_9": "Sarr 3",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "686( 1,244,149 )",
    "Teams": "For Better or Wirtz( Theo Dixon )",
    "SXL": "ENG",
    "Latp": "60",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 2",
    "Player_10": "Mateta 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Cunha 0",
    "Player_14": "Marc Guiu",
    "Player_7": "Rogers 15",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "Rodon 3",
    "Player_6": "Saka 8",
    "Player_3": "Senesi 3",
    "Player_4": "Virgil 3",
    "Player_8": "Rice 6",
    "Player_9": "Sarr 3",
    "Player_15": "Mukiele 4"
  },
  {
    "manager_Name": "685( 1,285,935 )",
    "Teams": "XG Stats XI( Will Gunn )",
    "SXL": "ENG",
    "Latp": "46",
    "Player_1": "Pope 3",
    "Player_11": "Haaland 4",
    "Player_10": "Woltemade 2",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Alderete 0",
    "Player_7": "Saka 4",
    "Player_2": "Virgil 3",
    "Player_5": "J.Timber 5",
    "Player_6": "Enzo 11",
    "Player_3": "Senesi 3",
    "Player_4": "Richards 6",
    "Player_8": "Sarr 3",
    "Player_9": "B.Fernandes 2",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "683( 1,360,446 )",
    "Teams": "DinamoB( Pietro Menna )",
    "SXL": "MLT",
    "Latp": "35",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 4",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Vicario 1",
    "Player_13": "Caicedo 0",
    "Player_14": "Semenyo 0",
    "Player_7": "Foden 2",
    "Player_2": "Cucurella 6",
    "Player_5": "Gu\u00E9hi 5",
    "Player_6": "Reijnders 1",
    "Player_3": "Senesi 3",
    "Player_4": "J.Timber 5",
    "Player_8": "Anthony 2",
    "Player_9": "Thiago 4",
    "Player_15": "Calafiori 2"
  },
  {
    "manager_Name": "681( 1,423,880 )",
    "Teams": "Rodalleguianos( Sergio Andres P\u00E9rez Fern\u00E1ndez )",
    "SXL": "MLT",
    "Latp": "45",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 4",
    "Player_12": "Sels 7",
    "Player_13": "A.Murphy 0",
    "Player_14": "Enzo 11",
    "Player_7": "Gakpo 2",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "Walker-Peters 0",
    "Player_6": "B.Fernandes 2",
    "Player_3": "Milenkovi\u0107 8",
    "Player_4": "J.Timber 5",
    "Player_8": "J.Arias 1",
    "Player_9": "Zubimendi 2",
    "Player_15": "Morgan 0"
  },
  {
    "manager_Name": "681( 1,431,756 )",
    "Teams": "Bebenciukai( Marius z )",
    "SXL": "LTU",
    "Latp": "62",
    "Player_1": "D\u00FAbravka 2",
    "Player_11": "Mateta 1",
    "Player_10": "Haaland 4",
    "Player_12": "Pope 3",
    "Player_13": "Semenyo 0",
    "Player_14": "Gy\u00F6keres 0",
    "Player_7": "Reijnders 1",
    "Player_2": "Senesi 3",
    "Player_5": "Van de",
    "Player_6": "Enzo 11",
    "Player_3": "Mu\u00F1oz 14",
    "Player_4": "J.Timber 5",
    "Player_8": "Xavi 1",
    "Player_9": "Eze 20",
    "Player_15": "Gudmundsson 1"
  },
  {
    "manager_Name": "677( 1,590,574 )",
    "Teams": "Bugibba FC 4.0( Adam Azzopardi )",
    "SXL": "MLT",
    "Latp": "20",
    "Player_1": "Raya 2",
    "Player_11": "Gy\u00F6keres 0",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Gonzalez 0",
    "Player_14": "Gabriel 0",
    "Player_7": "Mbeumo 1",
    "Player_2": "Est\u00E8ve 3",
    "Player_5": "Gu\u00E9hi 5",
    "Player_6": "Semenyo 0",
    "Player_3": "Wan-Bissaka 2",
    "Player_4": "Van de",
    "Player_8": "Kudus 2",
    "Player_9": "Calvert-Lewin 1",
    "Player_15": "A.Ramsey 0"
  }
];