var s = [
  {
    "manager_Name": "881( 1 )",
    "Teams": "teddy\u0027s xv( C McQuade )",
    "SXL": "ENG",
    "Latp": "76",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 1",
    "Player_10": "Haaland 4",
    "Player_12": "Verbruggen 7",
    "Player_13": "Lacroix 11",
    "Player_14": "Bowen 4",
    "Player_7": "Enzo 11",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "O\u2019Reilly 1",
    "Player_6": "Bruno G.",
    "Player_3": "R\u00FAben 7",
    "Player_4": "Van de",
    "Player_8": "Rice 6",
    "Player_9": "Eze 20",
    "Player_15": "Semenyo 0"
  },
  {
    "manager_Name": "875( 2 )",
    "Teams": "losksjsns( Alex Simons )",
    "SXL": "ENG",
    "Latp": "81",
    "Player_1": "Pickford 10",
    "Player_11": "Haaland 4",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Ramsdale 0",
    "Player_13": "Semenyo 0",
    "Player_14": "Grealish 3",
    "Player_7": "Eze 20",
    "Player_2": "J.Timber 5",
    "Player_5": "Mu\u00F1oz 14",
    "Player_6": "Enzo 11",
    "Player_3": "Gu\u00E9hi 5",
    "Player_4": "Senesi 3",
    "Player_8": "Rice 6",
    "Player_9": "Woltemade 2",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "869( 3 )",
    "Teams": "Shiver Me Timber( Mike Tomlin )",
    "SXL": "ENG",
    "Latp": "68",
    "Player_1": "Raya 2",
    "Player_11": "Welbeck 8",
    "Player_10": "Haaland 2",
    "Player_12": "Sels 7",
    "Player_13": "Gabriel 0",
    "Player_14": "Gu\u00E9hi 5",
    "Player_7": "Bruno G.",
    "Player_2": "Senesi 3",
    "Player_5": "B.Fernandes 2",
    "Player_6": "Rice 6",
    "Player_3": "Mu\u00F1oz 14",
    "Player_4": "Murillo 17",
    "Player_8": "Damsgaard 2",
    "Player_9": "Mateta 2",
    "Player_15": "Semenyo 0"
  },
  {
    "manager_Name": "869( 4 )",
    "Teams": "Angeball( Oscar Pernehed )",
    "SXL": "SWE",
    "Latp": "52",
    "Player_1": "D\u00FAbravka 2",
    "Player_11": "Haaland 2",
    "Player_10": "Thiago 4",
    "Player_12": "Pickford 10",
    "Player_13": "Tarkowski 8",
    "Player_14": "L.Paquet\u00E1 0",
    "Player_7": "Mbeumo 1",
    "Player_2": "J.Timber 5",
    "Player_5": "Senesi 3",
    "Player_6": "B.Fernandes 4",
    "Player_3": "De Ligt",
    "Player_4": "Mu\u00F1oz 14",
    "Player_8": "Saka 4",
    "Player_9": "Enzo 11",
    "Player_15": "Barnes 0"
  },
  {
    "manager_Name": "863( 5 )",
    "Teams": "ZayceCFC( Zay McGuire )",
    "SXL": "USA",
    "Latp": "47",
    "Player_1": "Petrovi\u0107 1",
    "Player_11": "Haaland 4",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Pope 3",
    "Player_13": "Caicedo 0",
    "Player_14": "Semenyo 0",
    "Player_7": "Minteh 11",
    "Player_2": "Virgil 3",
    "Player_5": "Gu\u00E9hi 5",
    "Player_6": "Saliba 2",
    "Player_3": "Cucurella 6",
    "Player_4": "J.Timber 5",
    "Player_8": "Ndiaye 3",
    "Player_9": "Rice 6",
    "Player_15": "Woltemade 2"
  },
  {
    "manager_Name": "861( 6 )",
    "Teams": "Buffelsfontein FC( JEFF ABSALOM )",
    "SXL": "ZAF",
    "Latp": "47",
    "Player_1": "Raya 2",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 4",
    "Player_12": "Henderson 6",
    "Player_13": "Gabriel 0",
    "Player_14": "Caicedo 0",
    "Player_7": "B.Fernandes 2",
    "Player_2": "Pedro Porro",
    "Player_5": "Chalobah 6",
    "Player_6": "Eze 20",
    "Player_3": "Virgil 3",
    "Player_4": "Ballard 1",
    "Player_8": "Amad 2",
    "Player_9": "Enes \u00DCnal",
    "Player_15": "Semenyo 0"
  },
  {
    "manager_Name": "861( 7 )",
    "Teams": "Mohamed( Mohamed Roma )",
    "SXL": "EGY",
    "Latp": "63",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Mateta 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Van de",
    "Player_7": "Neto 8",
    "Player_2": "Saliba 2",
    "Player_5": "Sarr 3",
    "Player_6": "Mbeumo 1",
    "Player_3": "Senesi 3",
    "Player_4": "Mu\u00F1oz 14",
    "Player_8": "Eze 20",
    "Player_9": "Haaland 4",
    "Player_15": "Est\u00E8ve 3"
  },
  {
    "manager_Name": "859( 8 )",
    "Teams": "SakiT( abdullahi Diiriye )",
    "SXL": "ENG",
    "Latp": "57",
    "Player_1": "Henderson 6",
    "Player_11": "Haaland 4",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Gabriel 0",
    "Player_14": "Semenyo 0",
    "Player_7": "Dewsbury-Hall 13",
    "Player_2": "Cucurella 6",
    "Player_5": "Gu\u00E9hi 5",
    "Player_6": "Saka 4",
    "Player_3": "O\u2019Reilly 1",
    "Player_4": "Mu\u00F1oz 14",
    "Player_8": "Mbeumo 1",
    "Player_9": "Igor Jesus",
    "Player_15": "O.Dango 5"
  },
  {
    "manager_Name": "857( 9 )",
    "Teams": "toffees( Geronimo Idarraga )",
    "SXL": "USA",
    "Latp": "66",
    "Player_1": "Pickford 10",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 4",
    "Player_12": "Darlow 0",
    "Player_13": "Caicedo 0",
    "Player_14": "Bergvall 0",
    "Player_7": "M.Salah 2",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "Gu\u00E9hi 5",
    "Player_6": "Mukiele 4",
    "Player_3": "J.Timber 5",
    "Player_4": "R\u00FAben 7",
    "Player_8": "Enzo 11",
    "Player_9": "Ndiaye 3",
    "Player_15": "Kroupi.Jr 2"
  },
  {
    "manager_Name": "857( 10 )",
    "Teams": "Change Name( lucas clarke )",
    "SXL": "NZL",
    "Latp": "45",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Reinildo 1",
    "Player_7": "Minteh 11",
    "Player_2": "Senesi 3",
    "Player_5": "Est\u00E8ve 3",
    "Player_6": "B.Fernandes 2",
    "Player_3": "Lacroix 11",
    "Player_4": "Virgil 3",
    "Player_8": "Mbeumo 1",
    "Player_9": "Saka 4",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "857( 10 )",
    "Teams": "FC Collymore( Staffan Arlefalk )",
    "SXL": "SWE",
    "Latp": "74",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Welbeck 8",
    "Player_10": "Mateta 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Caicedo 0",
    "Player_14": "Tarkowski 8",
    "Player_7": "Eze 20",
    "Player_2": "J.Timber 5",
    "Player_5": "Mbeumo 1",
    "Player_6": "Rice 6",
    "Player_3": "Cucurella 6",
    "Player_4": "Yoro 2",
    "Player_8": "Rogers 15",
    "Player_9": "Haaland 4",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "857( 12 )",
    "Teams": "Adam El Sokkary( Adam Ayman )",
    "SXL": "EGY",
    "Latp": "73",
    "Player_1": "Petrovi\u0107 1",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Mateta 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Gabriel 0",
    "Player_14": "Semenyo 0",
    "Player_7": "Enzo 11",
    "Player_2": "Andersen 10",
    "Player_5": "Mitchell 6",
    "Player_6": "Eze 20",
    "Player_3": "J.Timber 5",
    "Player_4": "Mu\u00F1oz 14",
    "Player_8": "Mbeumo 2",
    "Player_9": "Haaland 2",
    "Player_15": "Potts 2"
  },
  {
    "manager_Name": "856( 13 )",
    "Teams": "Calafiorication( Aryan Kumar )",
    "SXL": "BHR",
    "Latp": "55",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta 1",
    "Player_12": "Sels 7",
    "Player_13": "Gabriel 0",
    "Player_14": "Onana 0",
    "Player_7": "Caicedo 0",
    "Player_2": "Gu\u00E9hi 5",
    "Player_5": "Tarkowski 8",
    "Player_6": "Enzo 11",
    "Player_3": "Mu\u00F1oz 14",
    "Player_4": "Virgil 3",
    "Player_8": "Rice 6",
    "Player_9": "Ekitik\u00E9 1",
    "Player_15": "Semenyo 0"
  },
  {
    "manager_Name": "856( 14 )",
    "Teams": "lemon \u0026 lime( Ben Leah )",
    "SXL": "ENG",
    "Latp": "81",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Thiago 4",
    "Player_10": "Haaland 2",
    "Player_12": "Petrovi\u0107 1",
    "Player_13": "Alderete 0",
    "Player_14": "Grealish 3",
    "Player_7": "Eze 40",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "Digne 1",
    "Player_6": "Mbeumo 1",
    "Player_3": "Calafiori 2",
    "Player_4": "Gu\u00E9hi 5",
    "Player_8": "Schade 2",
    "Player_9": "Saka 4",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "853( 15 )",
    "Teams": "Real Badmen Fc( Travis Murira )",
    "SXL": "KEN",
    "Latp": "76",
    "Player_1": "Raya 2",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Thiago 4",
    "Player_12": "Henderson 6",
    "Player_13": "Caicedo 0",
    "Player_14": "Mac Allister",
    "Player_7": "Rice 6",
    "Player_2": "Pedro Porro",
    "Player_5": "Mu\u00F1oz 14",
    "Player_6": "Eze 20",
    "Player_3": "Lacroix 11",
    "Player_4": "Virgil 3",
    "Player_8": "Enzo 11",
    "Player_9": "Haaland 4",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "852( 16 )",
    "Teams": "TheYellowFlash( Brent Paulse )",
    "SXL": "ZAF",
    "Latp": "45",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Haaland 4",
    "Player_10": "Welbeck 8",
    "Player_12": "Pope 3",
    "Player_13": "Semenyo 0",
    "Player_14": "Eze 20",
    "Player_7": "Ndiaye 3",
    "Player_2": "Cash 2",
    "Player_5": "J.Timber 5",
    "Player_6": "Sarr 3",
    "Player_3": "Cucurella 6",
    "Player_4": "Mitchell 6",
    "Player_8": "Mbeumo 1",
    "Player_9": "Mateta 1",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "852( 16 )",
    "Teams": "Tarts( Harry Goodrich )",
    "SXL": "ENG",
    "Latp": "58",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Haaland 4",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Vicario 1",
    "Player_13": "Semenyo 0",
    "Player_14": "Woltemade 2",
    "Player_7": "Eze 20",
    "Player_2": "J.Timber 5",
    "Player_5": "Gu\u00E9hi 5",
    "Player_6": "Sessegnon 3",
    "Player_3": "R\u00FAben 7",
    "Player_4": "Senesi 3",
    "Player_8": "Mbeumo 1",
    "Player_9": "Sarr 3",
    "Player_15": "Rodon 3"
  },
  {
    "manager_Name": "852( 18 )",
    "Teams": "The gentlemen\u2019s XI( Chris Mounsey-Thear )",
    "SXL": "ENG",
    "Latp": "56",
    "Player_1": "Verbruggen 7",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta 1",
    "Player_12": "Roefs 3",
    "Player_13": "Caicedo 0",
    "Player_14": "Cullen 2",
    "Player_7": "Rice 6",
    "Player_2": "Mitchell 6",
    "Player_5": "Mukiele 4",
    "Player_6": "Eze 20",
    "Player_3": "Gvardiol 1",
    "Player_4": "O\u2019Reilly 1",
    "Player_8": "B.Fernandes 2",
    "Player_9": "Thiago 4",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "852( 19 )",
    "Teams": "ABU( martin loenholdt )",
    "SXL": "ENG",
    "Latp": "74",
    "Player_1": "Pickford 10",
    "Player_11": "Thiago 4",
    "Player_10": "Haaland 4",
    "Player_12": "Pope 3",
    "Player_13": "Gvardiol 1",
    "Player_14": "Bruno G.",
    "Player_7": "Sarr 3",
    "Player_2": "Senesi 3",
    "Player_5": "Rice 6",
    "Player_6": "Rogers 15",
    "Player_3": "Mitchell 6",
    "Player_4": "Saliba 2",
    "Player_8": "Eze 20",
    "Player_9": "Mateta 1",
    "Player_15": "O\u2019Reilly 1"
  },
  {
    "manager_Name": "851( 20 )",
    "Teams": "Up on the Roefs( Matthew Coggin )",
    "SXL": "ENG",
    "Latp": "60",
    "Player_1": "Roefs 3",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta 1",
    "Player_12": "Vicario 1",
    "Player_13": "Caicedo 0",
    "Player_14": "Van de",
    "Player_7": "Eze 20",
    "Player_2": "Tarkowski 8",
    "Player_5": "Gu\u00E9hi 5",
    "Player_6": "Saka 4",
    "Player_3": "Cucurella 6",
    "Player_4": "O\u2019Reilly 1",
    "Player_8": "Rice 6",
    "Player_9": "Xhaka 2",
    "Player_15": "Woltemade 2"
  },
  {
    "manager_Name": "851( 20 )",
    "Teams": "Kongony FC( John Kowido )",
    "SXL": "KEN",
    "Latp": "56",
    "Player_1": "Henderson 6",
    "Player_11": "Isidor 4",
    "Player_10": "Mateta 1",
    "Player_12": "A.Becker 2",
    "Player_13": "Caicedo 0",
    "Player_14": "Semenyo 0",
    "Player_7": "Bruno G.",
    "Player_2": "Gu\u00E9hi 5",
    "Player_5": "Keane 9",
    "Player_6": "Rice 6",
    "Player_3": "J.Timber 5",
    "Player_4": "Cucurella 6",
    "Player_8": "B.Fernandes 2",
    "Player_9": "Haaland 2",
    "Player_15": "Gabriel 0"
  },
  {
    "manager_Name": "851( 22 )",
    "Teams": "In the Kvistgaarden( Joe Dean )",
    "SXL": "ENG",
    "Latp": "54",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Van den",
    "Player_7": "Saka 4",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "Van Hecke",
    "Player_6": "Ndiaye 3",
    "Player_3": "Senesi 3",
    "Player_4": "Cucurella 6",
    "Player_8": "Minteh 11",
    "Player_9": "Mbeumo 1",
    "Player_15": "Kroupi.Jr 2"
  },
  {
    "manager_Name": "850( 23 )",
    "Teams": "Saka spuds!( Jack Hall )",
    "SXL": "ENG",
    "Latp": "42",
    "Player_1": "Pope 3",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 4",
    "Player_12": "Raya 2",
    "Player_13": "Gabriel 0",
    "Player_14": "Caicedo 0",
    "Player_7": "Bruno G.",
    "Player_2": "Livramento 2",
    "Player_5": "Cucurella 6",
    "Player_6": "B.Fernandes 2",
    "Player_3": "Cash 2",
    "Player_4": "Gu\u00E9hi 5",
    "Player_8": "Rice 6",
    "Player_9": "Gravenberch 1",
    "Player_15": "Watkins 2"
  },
  {
    "manager_Name": "850( 24 )",
    "Teams": "1-0 FC( Gustav Nordstr\u00F6m )",
    "SXL": "SWE",
    "Latp": "79",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 4",
    "Player_10": "Mateta 1",
    "Player_12": "Verbruggen 7",
    "Player_13": "Semenyo 0",
    "Player_14": "Caicedo 0",
    "Player_7": "Rogers 15",
    "Player_2": "Truffert 0",
    "Player_5": "Mu\u00F1oz 14",
    "Player_6": "Murillo 17",
    "Player_3": "J.Timber 5",
    "Player_4": "Cucurella 6",
    "Player_8": "Saka 4",
    "Player_9": "Minteh 11",
    "Player_15": "Marc Guiu"
  },
  {
    "manager_Name": "850( 25 )",
    "Teams": "The Konate kid( Luke Riddell )",
    "SXL": "ENG",
    "Latp": "53",
    "Player_1": "Petrovi\u0107 1",
    "Player_11": "Thiago 4",
    "Player_10": "Haaland 2",
    "Player_12": "Henderson 6",
    "Player_13": "Cunha 0",
    "Player_14": "Gabriel 0",
    "Player_7": "Mbeumo 2",
    "Player_2": "James 1",
    "Player_5": "Gu\u00E9hi 5",
    "Player_6": "Eze 20",
    "Player_3": "Mu\u00F1oz 14",
    "Player_4": "Van de",
    "Player_8": "Okafor 2",
    "Player_9": "Woltemade 2",
    "Player_15": "Semenyo 0"
  },
  {
    "manager_Name": "850( 25 )",
    "Teams": "Haroun( ahmed haroun )",
    "SXL": "EGY",
    "Latp": "70",
    "Player_1": "Henderson 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Haaland 4",
    "Player_12": "Vicario 1",
    "Player_13": "Semenyo 0",
    "Player_14": "Calvert-Lewin 1",
    "Player_7": "Bruno G.",
    "Player_2": "Cucurella 6",
    "Player_5": "J.Timber 5",
    "Player_6": "Eze 20",
    "Player_3": "Van de",
    "Player_4": "Mu\u00F1oz 14",
    "Player_8": "Sarr 3",
    "Player_9": "Mbeumo 1",
    "Player_15": "Tosin 10"
  },
  {
    "manager_Name": "848( 27 )",
    "Teams": "MeMyselfNdiaye( Tafadzwa Shoniwa )",
    "SXL": "ENG",
    "Latp": "88",
    "Player_1": "Leno 5",
    "Player_11": "Haaland 4",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Petrovi\u0107 1",
    "Player_13": "Gabriel 0",
    "Player_14": "Semenyo 0",
    "Player_7": "Ndiaye 3",
    "Player_2": "R\u00FAben 7",
    "Player_5": "Tarkowski 8",
    "Player_6": "Minteh 11",
    "Player_3": "Mu\u00F1oz 14",
    "Player_4": "Gu\u00E9hi 5",
    "Player_8": "Bruno G.",
    "Player_9": "Eze 20",
    "Player_15": "Woltemade 2"
  },
  {
    "manager_Name": "848( 28 )",
    "Teams": "Realmaginge( Steven Grainger )",
    "SXL": "ENG",
    "Latp": "69",
    "Player_1": "Henderson 6",
    "Player_11": "Bowen 4",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "Petrovi\u0107 1",
    "Player_13": "Doku 2",
    "Player_14": "Cash 2",
    "Player_7": "Rogers 15",
    "Player_2": "Van de",
    "Player_5": "Eze 20",
    "Player_6": "Mbeumo 1",
    "Player_3": "Mu\u00F1oz 14",
    "Player_4": "Ballard 1",
    "Player_8": "Sarr 3",
    "Player_9": "Haaland 4",
    "Player_15": "Gabriel 0"
  },
  {
    "manager_Name": "847( 29 )",
    "Teams": "Jurgenmeister( Simon Herbert )",
    "SXL": "ENG",
    "Latp": "46",
    "Player_1": "Raya 2",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Mateta 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Caicedo 0",
    "Player_14": "Minteh 11",
    "Player_7": "Rice 6",
    "Player_2": "J.Timber 5",
    "Player_5": "Mu\u00F1oz 14",
    "Player_6": "Ndiaye 3",
    "Player_3": "Cucurella 6",
    "Player_4": "Senesi 3",
    "Player_8": "Mbeumo 1",
    "Player_9": "Haaland 4",
    "Player_15": "Hoever 0"
  },
  {
    "manager_Name": "847( 29 )",
    "Teams": "Team 26( Andrew Jennings )",
    "SXL": "ENG",
    "Latp": "51",
    "Player_1": "Raya 2",
    "Player_11": "Haaland 4",
    "Player_10": "Thiago 4",
    "Player_12": "Verbruggen 7",
    "Player_13": "Gabriel 0",
    "Player_14": "Semenyo 0",
    "Player_7": "Anthony 2",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "Lacroix 11",
    "Player_6": "Mbeumo 1",
    "Player_3": "Van de",
    "Player_4": "Gu\u00E9hi 5",
    "Player_8": "Rice 6",
    "Player_9": "Woltemade 2",
    "Player_15": "Caicedo 0"
  },
  {
    "manager_Name": "847( 31 )",
    "Teams": "greenies( Marc Green )",
    "SXL": "ENG",
    "Latp": "60",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Mateta 1",
    "Player_10": "Woltemade 2",
    "Player_12": "Jos\u00E9 S\u00E1",
    "Player_13": "Caicedo 0",
    "Player_14": "Est\u00E8ve 3",
    "Player_7": "Mbeumo 1",
    "Player_2": "J.Timber 5",
    "Player_5": "Senesi 3",
    "Player_6": "Saka 4",
    "Player_3": "Mu\u00F1oz 14",
    "Player_4": "Van de",
    "Player_8": "Eze 20",
    "Player_9": "Haaland 4",
    "Player_15": "Reed 1"
  },
  {
    "manager_Name": "847( 31 )",
    "Teams": "FC Wallin( Magnus Wallin )",
    "SXL": "SWE",
    "Latp": "68",
    "Player_1": "Henderson 6",
    "Player_11": "Welbeck 8",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Caicedo 0",
    "Player_14": "Gusto 1",
    "Player_7": "Eze 20",
    "Player_2": "J.Timber 5",
    "Player_5": "Yoro 2",
    "Player_6": "Amad 2",
    "Player_3": "Gu\u00E9hi 5",
    "Player_4": "Mu\u00F1oz 14",
    "Player_8": "Mbeumo 1",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Semenyo 0"
  },
  {
    "manager_Name": "845( 33 )",
    "Teams": "Ballo fc( Ade Bayo )",
    "SXL": "NGA",
    "Latp": "38",
    "Player_1": "Martinez 3",
    "Player_11": "Haaland 4",
    "Player_10": "Welbeck 8",
    "Player_12": "Petrovi\u0107 1",
    "Player_13": "Gabriel 0",
    "Player_14": "Caicedo 0",
    "Player_7": "Tonali 4",
    "Player_2": "Senesi 3",
    "Player_5": "Van de",
    "Player_6": "Szoboszlai 2",
    "Player_3": "Saliba 2",
    "Player_4": "Gu\u00E9hi 5",
    "Player_8": "Rice 6",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Kudus 2"
  },
  {
    "manager_Name": "845( 34 )",
    "Teams": "Madmax( Kelvin Maina )",
    "SXL": "KEN",
    "Latp": "52",
    "Player_1": "Raya 2",
    "Player_11": "Thiago 4",
    "Player_10": "Haaland 4",
    "Player_12": "Sels 7",
    "Player_13": "Gabriel 0",
    "Player_14": "Alderete 0",
    "Player_7": "Sarr 3",
    "Player_2": "Lacroix 11",
    "Player_5": "Dewsbury-Hall 13",
    "Player_6": "B.Fernandes 2",
    "Player_3": "Gu\u00E9hi 5",
    "Player_4": "J.Timber 5",
    "Player_8": "Kudus 2",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Semenyo 0"
  },
  {
    "manager_Name": "845( 35 )",
    "Teams": "Croydon Eagles( Luke Townsend )",
    "SXL": "ENG",
    "Latp": "48",
    "Player_1": "Pope 3",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Mateta 1",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Van de",
    "Player_7": "Enzo 11",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "Virgil 3",
    "Player_6": "Mbeumo 1",
    "Player_3": "Senesi 3",
    "Player_4": "Mukiele 4",
    "Player_8": "Ndiaye 3",
    "Player_9": "Haaland 4",
    "Player_15": "Reijnders 1"
  },
  {
    "manager_Name": "845( 36 )",
    "Teams": "Expect Toulouse FC( Bailey Armstrong )",
    "SXL": "ENG",
    "Latp": "52",
    "Player_1": "S\u00E1nchez 6",
    "Player_11": "Jo\u00E3o Pedro",
    "Player_10": "Woltemade 2",
    "Player_12": "Donnarumma 1",
    "Player_13": "Semenyo 0",
    "Player_14": "J.Timber 5",
    "Player_7": "Enzo 11",
    "Player_2": "Van de",
    "Player_5": "Senesi 3",
    "Player_6": "Rice 6",
    "Player_3": "Mu\u00F1oz 14",
    "Player_4": "Gu\u00E9hi 5",
    "Player_8": "Reijnders 1",
    "Player_9": "Haaland 2",
    "Player_15": "Xhaka 2"
  },
  {
    "manager_Name": "844( 37 )",
    "Teams": "50 Schades of Grey( Kai Antonio )",
    "SXL": "ENG",
    "Latp": "48",
    "Player_1": "Petrovi\u0107 1",
    "Player_11": "Thiago 4",
    "Player_10": "Haaland 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Ndoye 3",
    "Player_7": "Enzo 11",
    "Player_2": "Virgil 3",
    "Player_5": "Gudmundsson 1",
    "Player_6": "Szoboszlai 2",
    "Player_3": "Mu\u00F1oz 14",
    "Player_4": "Senesi 3",
    "Player_8": "Saka 4",
    "Player_9": "Mateta 1",
    "Player_15": "Gabriel 0"
  },
  {
    "manager_Name": "844( 38 )",
    "Teams": "Trillonarios( Joel Arvidsson )",
    "SXL": "SWE",
    "Latp": "68",
    "Player_1": "Martinez 3",
    "Player_11": "Mateta 1",
    "Player_10": "Thiago 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Van de",
    "Player_7": "Cherki 7",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "Sarr 3",
    "Player_6": "Eze 20",
    "Player_3": "Senesi 3",
    "Player_4": "J.Timber 5",
    "Player_8": "Saka 4",
    "Player_9": "Haaland 4",
    "Player_15": "Alderete 0"
  },
  {
    "manager_Name": "844( 39 )",
    "Teams": "Vamos!!( Gaurav Sareen )",
    "SXL": "IND",
    "Latp": "48",
    "Player_1": "Henderson 6",
    "Player_11": "Woltemade 2",
    "Player_10": "Thiago 4",
    "Player_12": "Pope 3",
    "Player_13": "Grealish 3",
    "Player_14": "Saliba 2",
    "Player_7": "B.Fernandes 2",
    "Player_2": "J.Timber 5",
    "Player_5": "Neto 8",
    "Player_6": "Rice 6",
    "Player_3": "R\u00FAben 7",
    "Player_4": "Virgil 3",
    "Player_8": "McGinn 1",
    "Player_9": "Haaland 4",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "844( 40 )",
    "Teams": "N5( Graham Allen )",
    "SXL": "ENG",
    "Latp": "53",
    "Player_1": "Henderson 6",
    "Player_11": "Mateta 1",
    "Player_10": "Haaland 2",
    "Player_12": "Darlow 0",
    "Player_13": "Reinildo 1",
    "Player_14": "Welbeck 8",
    "Player_7": "Minteh 11",
    "Player_2": "Gu\u00E9hi 5",
    "Player_5": "Saka 8",
    "Player_6": "Rice 6",
    "Player_3": "J.Timber 5",
    "Player_4": "Cucurella 6",
    "Player_8": "Mbeumo 1",
    "Player_9": "Gakpo 2",
    "Player_15": "Van de"
  },
  {
    "manager_Name": "843( 41 )",
    "Teams": "\uFFFD( Vincent Ngula )",
    "SXL": "KEN",
    "Latp": "43",
    "Player_1": "Donnarumma 1",
    "Player_11": "Haaland 4",
    "Player_10": "Welbeck 8",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Gabriel 0",
    "Player_14": "Gy\u00F6keres 0",
    "Player_7": "Cherki 7",
    "Player_2": "J.Timber 5",
    "Player_5": "Mbeumo 1",
    "Player_6": "Caicedo 0",
    "Player_3": "Van Hecke",
    "Player_4": "Gu\u00E9hi 5",
    "Player_8": "Cunha 0",
    "Player_9": "Bruno G.",
    "Player_15": "Burn 0"
  },
  {
    "manager_Name": "843( 42 )",
    "Teams": "Change Name( Elijah Cookson )",
    "SXL": "CAN",
    "Latp": "52",
    "Player_1": "Henderson 6",
    "Player_11": "Mateta 1",
    "Player_10": "Haaland 4",
    "Player_12": "Vicario 1",
    "Player_13": "Caicedo 0",
    "Player_14": "Semenyo 0",
    "Player_7": "Cherki 7",
    "Player_2": "Gvardiol 1",
    "Player_5": "J.Timber 5",
    "Player_6": "James 1",
    "Player_3": "Gu\u00E9hi 5",
    "Player_4": "Cucurella 6",
    "Player_8": "Bruno G.",
    "Player_9": "Rice 6",
    "Player_15": "Woltemade 2"
  },
  {
    "manager_Name": "843( 43 )",
    "Teams": "(:( Free Palestine . )",
    "SXL": "ARE",
    "Latp": "62",
    "Player_1": "Henderson 6",
    "Player_11": "Watkins 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Truffert 0",
    "Player_14": "Calafiori 2",
    "Player_7": "Eze 20",
    "Player_2": "Andersen 10",
    "Player_5": "Mbeumo 1",
    "Player_6": "Sarr 3",
    "Player_3": "Gu\u00E9hi 5",
    "Player_4": "J.Timber 5",
    "Player_8": "O.Dango 5",
    "Player_9": "Haaland 4",
    "Player_15": "Reijnders 1"
  },
  {
    "manager_Name": "843( 44 )",
    "Teams": "cabdixaafidmaxamed( Cabdi Jeeriya )",
    "SXL": "SOM",
    "Latp": "41",
    "Player_1": "Raya 2",
    "Player_11": "Woltemade 2",
    "Player_10": "Haaland 4",
    "Player_12": "Vicario 1",
    "Player_13": "Gabriel 0",
    "Player_14": "Semenyo 0",
    "Player_7": "Foden 2",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "Van de",
    "Player_6": "Mbeumo 1",
    "Player_3": "Virgil 3",
    "Player_4": "Senesi 3",
    "Player_8": "Rice 6",
    "Player_9": "Thiago 4",
    "Player_15": "Caicedo 0"
  },
  {
    "manager_Name": "842( 45 )",
    "Teams": "Hotel? Thiago( Harry Welham )",
    "SXL": "ENG",
    "Latp": "46",
    "Player_1": "Pickford 10",
    "Player_11": "Haaland 4",
    "Player_10": "Bowen 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "King 3",
    "Player_7": "B.Fernandes 2",
    "Player_2": "Richards 6",
    "Player_5": "Truffert 0",
    "Player_6": "Saka 4",
    "Player_3": "Andersen 10",
    "Player_4": "Calafiori 2",
    "Player_8": "Sarr 3",
    "Player_9": "Mateta 1",
    "Player_15": "Ekdal 0"
  },
  {
    "manager_Name": "842( 45 )",
    "Teams": "CityQuintessence( Konrad Janiszewski )",
    "SXL": "POL",
    "Latp": "32",
    "Player_1": "Pope 3",
    "Player_11": "Mateta 2",
    "Player_10": "Jo\u00E3o Pedro",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Pedro Porro",
    "Player_7": "Ndiaye 3",
    "Player_2": "Truffert 0",
    "Player_5": "Hartman 1",
    "Player_6": "Mbeumo 1",
    "Player_3": "Mu\u00F1oz 14",
    "Player_4": "Virgil 3",
    "Player_8": "Gakpo 2",
    "Player_9": "Haaland 2",
    "Player_15": "Kudus 2"
  },
  {
    "manager_Name": "842( 47 )",
    "Teams": "Tucheliban( Anthony Hardingham )",
    "SXL": "ENG",
    "Latp": "60",
    "Player_1": "Raya 2",
    "Player_11": "Mateta 1",
    "Player_10": "Haaland 2",
    "Player_12": "Vicario 1",
    "Player_13": "Semenyo 0",
    "Player_14": "Van de",
    "Player_7": "Minteh 11",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "Ndiaye 3",
    "Player_6": "Mbeumo 1",
    "Player_3": "Gu\u00E9hi 5",
    "Player_4": "J.Timber 10",
    "Player_8": "Bruno G.",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Burn 0"
  },
  {
    "manager_Name": "842( 47 )",
    "Teams": "Crouch Potato( Lloyd Morgan )",
    "SXL": "WAL",
    "Latp": "89",
    "Player_1": "Henderson 6",
    "Player_11": "Haaland 2",
    "Player_10": "Woltemade 2",
    "Player_12": "Donnarumma 1",
    "Player_13": "Semenyo 0",
    "Player_14": "Grealish 3",
    "Player_7": "Bruno G.",
    "Player_2": "Lacroix 11",
    "Player_5": "Rodon 3",
    "Player_6": "Rice 6",
    "Player_3": "Van de",
    "Player_4": "Mu\u00F1oz 28",
    "Player_8": "Eze 20",
    "Player_9": "Jo\u00E3o Pedro",
    "Player_15": "Gabriel 0"
  },
  {
    "manager_Name": "842( 49 )",
    "Teams": "ThomasTheFrankEngine( Chris Masters )",
    "SXL": "ENG",
    "Latp": "54",
    "Player_1": "A.Becker 2",
    "Player_11": "Haaland 4",
    "Player_10": "Bowen 4",
    "Player_12": "D\u00FAbravka 2",
    "Player_13": "Semenyo 0",
    "Player_14": "Van de",
    "Player_7": "Enzo 11",
    "Player_2": "Mu\u00F1oz 14",
    "Player_5": "Rice 6",
    "Player_6": "Ndiaye 3",
    "Player_3": "Virgil 3",
    "Player_4": "Gu\u00E9hi 5",
    "Player_8": "Mbeumo 1",
    "Player_9": "Mateta 1",
    "Player_15": "Spence 0"
  },
  {
    "manager_Name": "842( 49 )",
    "Teams": "Raphaelx Fc( Chizobam Raphael )",
    "SXL": "NGA",
    "Latp": "67",
    "Player_1": "Pope 3",
    "Player_11": "Haaland 4",
    "Player_10": "Welbeck 8",
    "Player_12": "Jos\u00E9 S\u00E1",
    "Player_13": "Cash 2",
    "Player_14": "Grealish 3",
    "Player_7": "B.Fernandes 2",
    "Player_2": "Senesi 3",
    "Player_5": "Mu\u00F1oz 14",
    "Player_6": "Rice 6",
    "Player_3": "Gu\u00E9hi 5",
    "Player_4": "O\u2019Reilly 1",
    "Player_8": "Eze 20",
    "Player_9": "Mateta 1",
    "Player_15": "Tavernier 7"
  }
];